Repository logto-io/logto, pull requests merged in 2021-09, with the labels that each got.

#105 test(ui): fix react-i18next warning in jest
  packages/ui/src/__mocks__/react-i18next.js
Labels: testing

#104 feat(core): detect language from querystring and header
  packages/core/package.json
  packages/core/src/app/init.ts
  packages/core/src/i18n/detect-language.ts
  packages/core/src/i18n/init.ts
  packages/core/src/middleware/koa-i18next.ts
  packages/core/src/routes/application.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/session.ts
  packages/core/src/routes/swagger.ts
  packages/core/src/routes/types.ts
  packages/core/src/routes/user.ts
  packages/phrases/package.json
  packages/schemas/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: feature

#106 feat(core): `GET /application/:id`
  packages/core/src/routes/application.ts
Labels: feature

#107 feat(core): `GET /applications`
  packages/core/src/queries/application.ts
  packages/core/src/routes/application.ts
Labels: feature

#108 fix(schemas): move `zod` into dependencies
  packages/schemas/package.json
  pnpm-lock.yaml
Labels: bugfix

#109 test(core): add unit tests for database insert into factory
  packages/core/src/database/insert-into.test.ts
Labels: testing

#110 feat(core): add status api and health check after deployment
  .github/workflows/deploy-dev.yml
  packages/core/src/routes/init.ts
  packages/core/src/routes/status.ts
Labels: feature

#111 refactor: adopt new ESLint rule set for FP
  packages/core/package.json
  packages/core/src/i18n/detect-language.ts
  packages/core/src/middleware/koa-guard.ts
  packages/core/src/middleware/koa-ui-proxy.ts
  packages/core/src/routes/user.ts
  packages/core/src/utils/password.ts
  packages/core/src/utils/repeat.ts
  packages/phrases/package.json
  packages/schemas/package.json
  packages/schemas/src/gen/index.ts
  packages/ui/package.json
  packages/ui/src/jest.setup.ts
  packages/ui/src/pages/Consent/index.tsx
  packages/ui/src/pages/Register/index.tsx
  packages/ui/src/pages/SignIn/index.tsx
  pnpm-lock.yaml
Labels: enhancement

#113 test(core): add unit tests for `generateUserId()`
  packages/core/src/lib/user.test.ts
  packages/core/src/lib/user.ts
  packages/core/src/routes/user.ts
Labels: testing

#112 chore: improved lifecycle scripts and workflow
  .github/workflows/core-main.yml
  .github/workflows/main.yml
  .github/workflows/phrases-main.yml
  .github/workflows/ui-main.yml
  package.json
Labels: chore

#114 chore: upgrade configs
  packages/core/package.json
  packages/core/src/lib/user.ts
  packages/phrases/package.json
  packages/schemas/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: chore

#116 chore(core): upgrade `oidc-provider`
  packages/core/package.json
  pnpm-lock.yaml
Labels: chore

#117 chore: upgrade configs
  packages/core/package.json
  packages/core/tsconfig.base.json
  packages/phrases/package.json
  packages/phrases/tsconfig.json
  packages/schemas/package.json
  packages/schemas/tsconfig.json
  packages/ui/package.json
  packages/ui/tsconfig.json
  pnpm-lock.yaml
Labels: chore

#118 refactor: `@logto/essentials` -> `@silverhand/essentials`
  packages/core/package.json
  packages/core/src/database/insert-into.ts
  packages/core/src/database/pool.ts
  packages/core/src/database/update-where.ts
  packages/core/src/database/utils.ts
  packages/core/src/env/consts.ts
  packages/core/src/i18n/detect-language.ts
  packages/core/src/middleware/koa-auth.ts
  packages/core/src/middleware/koa-guard.ts
  packages/core/src/oidc/consts.ts
  packages/core/src/queries/oidc-model-instance.ts
  packages/core/src/routes/session.ts
  packages/core/src/routes/swagger.ts
  packages/core/src/utils/assert-that.ts
  packages/core/src/utils/assert.ts
  packages/core/src/utils/env.test.ts
  packages/core/src/utils/env.ts
  packages/core/src/utils/password.ts
  packages/core/src/utils/repeat.ts
  packages/core/src/utils/string.ts
  packages/core/src/utils/zod.ts
  packages/schemas/package.json
  packages/schemas/src/gen/index.ts
  packages/schemas/src/gen/schema.ts
  packages/schemas/src/gen/utils.ts
  pnpm-lock.yaml
Labels: enhancement

#119 fix(core): add redirectURI to the response body of register endpoint /user
  packages/core/src/routes/init.ts
  packages/core/src/routes/user.ts
  packages/ui/src/hooks/use-api.ts
  packages/ui/src/pages/Consent/index.tsx
Labels: bugfix

#120 fix(schema): update db-entries generation job
  packages/schemas/src/gen/index.ts
Labels: bugfix

#122 fix: format PR template
  .github/pull_request_template.md
Labels: bugfix

#123 fix(core): load dist files when needed
  packages/core/src/middleware/koa-ui-proxy.ts
Labels: bugfix

#124 chore: update PR template
  .github/pull_request_template.md
Labels: chore
