Repository logto-io/logto, pull requests merged in 2021-12, with the labels that each got.

#145 feat(schema): add resource and scope table
  packages/core/src/queries/resources.ts
  packages/core/src/queries/scopes.ts
  packages/schemas/src/db-entries/custom-types.ts
  packages/schemas/src/db-entries/index.ts
  packages/schemas/src/db-entries/resource-scope.ts
  packages/schemas/src/db-entries/resource.ts
  packages/schemas/src/gen/index.ts
  packages/schemas/tables/resource_scopes.sql
  packages/schemas/tables/resources.sql
Labels: feature

#146 feat: implement getResourceIndicators logic
  packages/core/src/oidc/init.ts
  packages/core/src/queries/resources.ts
  packages/core/src/queries/scopes.ts
  packages/schemas/tables/resource_scopes.sql
Labels: feature

#148 fix(schema): fix zod guard infer type for option fields
  packages/schemas/src/foundations/schemas.ts
Labels: bugfix

#150 feat(core): support trusting TLS offloading proxies config
  packages/core/src/env/consts.ts
  packages/core/src/index.ts
Labels: feature

#151 refactor(core): replace `querystring` with `query-string`
  packages/core/package.json
  packages/core/src/utils/pagination.ts
  pnpm-lock.yaml
Labels: enhancement

#152 refactor: disable eslint rule for entire `describe`
  packages/core/src/middleware/koa-pagination.test.ts
Labels: enhancement

#153 refactor(core): rename `context` to `ctx` in test file
  packages/core/src/middleware/koa-pagination.test.ts
Labels: enhancement

#154 feat: generate 2 types for db table schema
  packages/core/src/database/insert-into.ts
  packages/core/src/database/update-where.ts
  packages/core/src/queries/application.ts
  packages/core/src/queries/oidc-model-instance.ts
  packages/core/src/queries/resources.ts
  packages/core/src/queries/scopes.ts
  packages/core/src/queries/user.ts
  packages/schemas/src/db-entries/application.ts
  packages/schemas/src/db-entries/oidc-model-instance.ts
  packages/schemas/src/db-entries/resource-scope.ts
  packages/schemas/src/db-entries/resource.ts
  packages/schemas/src/db-entries/user-log.ts
  packages/schemas/src/db-entries/user.ts
  packages/schemas/src/foundations/schemas.ts
  packages/schemas/src/gen/index.ts
  packages/schemas/src/gen/schema.ts
  packages/schemas/src/gen/types.ts
Labels: feature

#139 feat(core): sign in logs
  packages/core/src/app/init.ts
  packages/core/src/middleware/koa-user-log.ts
  packages/core/src/queries/user-log.ts
  packages/core/src/routes/session.ts
  packages/core/src/routes/types.ts
Labels: feature

#155 chore: update dependency of ESLint to version 8.1.0 or later
  packages/core/package.json
  packages/core/src/database/insert-into.test.ts
  packages/core/src/database/insert-into.ts
  packages/core/src/queries/resources.ts
  packages/core/src/queries/scopes.ts
  packages/core/src/queries/user.ts
  packages/core/src/utils/password.ts
  packages/phrases/package.json
  packages/schemas/package.json
  packages/schemas/src/foundations/schemas.ts
  packages/schemas/src/gen/index.ts
  packages/ui/package.json
  packages/ui/src/pages/Consent/index.tsx
  pnpm-lock.yaml
Labels: chore

#158 fix(ui): fix useApi request in useEffect dead loop bug
  packages/ui/src/hooks/use-api.ts
Labels: bugfix

#157 chore: update silverhand/configs dependency and fix the scope of eslint-disable rule
  packages/core/package.json
  packages/core/src/database/insert-into.test.ts
  packages/core/src/index.ts
  packages/phrases/package.json
  packages/phrases/src/types.ts
  packages/schemas/package.json
  packages/ui/package.json
  packages/ui/src/client.tsx
  pnpm-lock.yaml
Labels: chore
