Repository logto-io/logto, pull requests merged in 2021-08, with the labels that each got.

#69 chore: add labels according to title
  .github/workflows/add-labels.yml
Labels: chore

#70 chore: add preinstall script to packages
  packages/core/package.json
  packages/phrases/package.json
  packages/schemas/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: chore

#72 chore: add environment in `deploy-dev` workflow
  .github/workflows/deploy-dev.yml
Labels: chore

#67 chore: add `.pnpm-debug.log*` to git ignore
  .gitignore
  packages/ui/tsconfig.json
Labels: chore

#71 refactor(schemas): oidc_clients -> applications
  packages/schemas/src/db-entries/application.ts
  packages/schemas/src/db-entries/custom-types.ts
  packages/schemas/src/db-entries/index.ts
  packages/schemas/src/db-entries/oidc-client.ts
  packages/schemas/tables/applications.sql
  packages/schemas/tables/oidc_clients.sql
Labels: enhancement

#73 refactor(core): adopt new schemas
  packages/core/src/oidc/adapter.ts
  packages/core/src/queries/application.ts
  packages/core/src/queries/oidc-client.ts
  packages/schemas/src/db-entries/application.ts
  packages/schemas/tables/applications.sql
Labels: enhancement

#74 chore: refine workflow trigger
  .github/workflows/core-main.yml
  .github/workflows/ui-main.yml
Labels: chore

#76 chore: add MPL-2.0 license
  LICENSE
  package.json
  packages/core/package.json
  packages/phrases/package.json
  packages/schemas/package.json
  packages/ui/package.json
Labels: chore

#77 refactor: conform RESTful convention
  packages/core/src/init/apis.ts
  packages/core/src/routes/session.ts
  packages/core/src/routes/user.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/ui/src/apis/consent.ts
  packages/ui/src/apis/register.ts
  packages/ui/src/apis/sign-in.ts
  packages/ui/src/pages/Register/index.test.tsx
  packages/ui/src/pages/Register/index.tsx
  packages/ui/src/pages/SignIn/index.test.tsx
  packages/ui/src/pages/SignIn/index.tsx
Labels: enhancement

#75 refactor(core): move api errorType to schemas package flow
  package.json
  packages/core/src/errors/RequestError/index.ts
  packages/core/src/middleware/koa-error-handler.ts
  packages/schemas/package.json
  packages/schemas/src/api/error.ts
  packages/schemas/src/api/index.ts
  packages/schemas/src/index.ts
  pnpm-lock.yaml
Labels: enhancement

#78 refactor(core): re-org files
  package.json
  packages/core/src/app/init.ts
  packages/core/src/env/consts.ts
  packages/core/src/i18n/init.ts
  packages/core/src/index.ts
  packages/core/src/middleware/koa-ui-proxy.ts
  packages/core/src/oidc/init.ts
  packages/core/src/routes/consts.ts
  packages/core/src/routes/init.ts
Labels: enhancement

#81 feat: validate access token if needed
  packages/core/package.json
  packages/core/src/env/consts.ts
  packages/core/src/middleware/koa-auth.ts
  packages/core/src/middleware/koa-guard.ts
  packages/core/src/oidc/consts.ts
  packages/core/src/oidc/init.ts
  packages/core/src/routes/application.ts
  packages/core/src/routes/init.ts
  packages/schemas/src/index.ts
  packages/schemas/src/types/index.ts
  packages/schemas/src/types/user.ts
  pnpm-lock.yaml
Labels: feature

#82 feat: `POST /applicaiton`
  packages/core/src/database/insert.ts
  packages/core/src/database/types.ts
  packages/core/src/database/utils.ts
  packages/core/src/errors/RequestError/index.ts
  packages/core/src/oidc/adapter.ts
  packages/core/src/oidc/utils.ts
  packages/core/src/queries/application.ts
  packages/core/src/queries/oidc-model-instance.ts
  packages/core/src/queries/user.ts
  packages/core/src/routes/application.ts
  packages/core/src/routes/user.ts
  packages/core/src/utils/id.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/schemas/src/api/error.ts
  packages/schemas/src/db-entries/application.ts
  packages/schemas/src/db-entries/oidc-model-instance.ts
  packages/schemas/src/db-entries/user.ts
  packages/schemas/src/foundations.ts
  packages/schemas/src/gen/index.ts
Labels: feature

#83 refactor: unify timestamp usage
  packages/core/src/oidc/adapter.ts
  packages/core/src/queries/oidc-model-instance.ts
  packages/schemas/src/gen/utils.ts
  packages/schemas/tables/applications.sql
  packages/schemas/tables/oidc_model_instances.sql
Labels: enhancement

#86 refactor: use composite run steps and remove eslint formatter
  .github/workflows/add-labels.yml
  .github/workflows/commitlint.yml
  .github/workflows/core-main.yml
  .github/workflows/deploy-dev.yml
  .github/workflows/phrases-main.yml
  .github/workflows/schemas-main.yml
  .github/workflows/ui-main.yml
  packages/core/lint-staged.config.js
  packages/core/package.json
  packages/phrases/package.json
  packages/schemas/package.json
  packages/ui/lint-staged.config.js
  packages/ui/package.json
  pnpm-lock.yaml
Labels: enhancement

#84 feat: Read and show error from API response
  packages/core/src/middleware/koa-error-handler.ts
  packages/schemas/src/api/error.ts
  packages/ui/package.json
  packages/ui/razzle.config.js
  packages/ui/src/hooks/use-api.ts
  packages/ui/src/include.d/dom.d.ts
  packages/ui/src/pages/Register/index.tsx
  packages/ui/src/pages/SignIn/index.tsx
  pnpm-lock.yaml
Labels: enhancement, feature

#94 refactor: throw an error when requesting invalid scope
  packages/core/src/routes/session.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: enhancement

#95 test(core): add unit tests for database utils
  .github/workflows/add-labels.yml
  packages/core/src/database/utils.test.ts
  packages/core/src/database/utils.ts
Labels: testing

#100 chore: `lint-staged` for all packages
  lint-staged.config.js
  packages/core/lint-staged.config.js
  packages/phrases/package.json
  packages/schemas/package.json
  pnpm-lock.yaml
Labels: chore

#101 chore: enforce default export name on React files
  packages/core/package.json
  packages/phrases/package.json
  packages/schemas/package.json
  packages/ui/package.json
  packages/ui/src/App.tsx
  packages/ui/src/i18n/init.ts
  pnpm-lock.yaml
Labels: chore

#99 test(core): add tests for database `insert-into.ts`
  packages/core/jest.config.js
  packages/core/package.json
  packages/core/src/database/update-where.test.ts
  packages/core/src/database/update-where.ts
  packages/core/src/utils/assert.ts
  packages/core/src/utils/env.test.ts
  packages/core/src/utils/test-utils.ts
  packages/core/tsconfig.json
  packages/core/tsconfig.test.json
  pnpm-lock.yaml
Labels: testing

#102 chore: upgrade configs
  packages/core/package.json
  packages/phrases/package.json
  packages/schemas/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: chore

#103 refactor: replace plain `assert` with a more strict version
  packages/core/package.json
  packages/core/src/database/insert-into.ts
  packages/core/src/database/update-where.ts
  packages/core/src/middleware/koa-auth.ts
  packages/core/src/routes/session.ts
  packages/core/src/utils/assert.ts
  packages/core/src/utils/env.ts
  packages/core/src/utils/password.ts
  packages/phrases/package.json
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/schemas/package.json
  packages/schemas/src/gen/index.ts
  packages/ui/package.json
  pnpm-lock.yaml
Labels: enhancement
