Repository logto-io/logto, pull requests merged in 2021-11, with the labels that each got.

#131 chore(ui): add global-this polyfill to ky
  packages/ui/package.json
  packages/ui/razzle.config.js
  pnpm-lock.yaml
Labels: chore

#132 chore(chore): bump oidc-provider version
  packages/core/package.json
  pnpm-lock.yaml
Labels: chore

#133 feat(core): users basic API
  packages/core/src/queries/user.ts
  packages/core/src/routes/user.ts
Labels: feature

#134 refactor(core): use plural in endpoint
  packages/core/src/routes/application.ts
  packages/core/src/routes/user.ts
  packages/ui/src/apis/register.ts
Labels: enhancement

#135 refactor(core): encryptUserPassword
  packages/core/src/lib/user.test.ts
  packages/core/src/lib/user.ts
  packages/core/src/routes/user.ts
  packages/core/src/utils/password.ts
Labels: enhancement

#138 chore(core): fix comment mistake
  packages/core/src/middleware/koa-guard.ts
Labels: chore

#137 feat(schema): user logs
  packages/schemas/src/db-entries/custom-types.ts
  packages/schemas/src/db-entries/index.ts
  packages/schemas/src/db-entries/user-log.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/gen/index.ts
  packages/schemas/src/gen/utils.ts
  packages/schemas/tables/user_logs.sql
Labels: feature

#143 feat: add koa-pagination
  packages/core/package.json
  packages/core/src/middleware/koa-pagination.test.ts
  packages/core/src/middleware/koa-pagination.ts
  packages/core/src/utils/pagination.test.ts
  packages/core/src/utils/pagination.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  pnpm-lock.yaml
Labels: feature
