Repository logto-io/logto, pull requests merged in 2022-02, with the labels that each got.

#210 feat(core): allow jsonb partial update
  packages/core/src/database/update-where.test.ts
  packages/core/src/database/update-where.ts
  packages/core/src/routes/application.ts
Labels: feature

#211 feat(core): check email existency before sending code
  packages/core/src/lib/sign-in.ts
  packages/core/src/queries/user.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#213 chore: fix typo in the GitHub PR template
  .github/pull_request_template.md
Labels: chore

#216 fix(core): hard code resource access_token format
  packages/core/src/oidc/init.ts
Labels: bugfix

#214 refactor(core): add OIDCRequestError
  packages/core/src/errors/OIDCRequestError/index.ts
  packages/core/src/middleware/koa-error-handler.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: enhancement

#212 feat(core): register with email
  packages/core/src/lib/register.ts
  packages/core/src/lib/sign-in.ts
  packages/core/src/routes/session.ts
  packages/core/src/utils/regex.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#215 feat(schema): user identities
  packages/core/src/database/find-many.test.ts
  packages/schemas/src/db-entries/user.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/tables/users.sql
Labels: feature

#217 feat(phone passwordless): add passwordless sign-in with phone
  packages/core/src/lib/sign-in.ts
  packages/core/src/queries/user.ts
  packages/core/src/routes/session.ts
  packages/core/src/utils/regex.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/schemas/src/db-entries/custom-types.ts
  packages/schemas/tables/user_logs.sql
Labels: feature

#218 feat: social sign in
  packages/core/src/connectors/github/index.ts
  packages/core/src/connectors/index.ts
  packages/core/src/lib/sign-in.ts
  packages/core/src/middleware/koa-user-log.ts
  packages/core/src/queries/user.ts
  packages/core/src/routes/session.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/schemas/src/db-entries/custom-types.ts
  packages/schemas/tables/user_logs.sql
Labels: feature

#221 feat(core): add passwordless register flow of phone
  packages/core/src/lib/register.ts
  packages/core/src/lib/sign-in.ts
  packages/core/src/routes/session.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/schemas/src/db-entries/custom-types.ts
  packages/schemas/tables/user_logs.sql
Labels: feature

#222 feat: social register
  packages/core/src/lib/register.ts
  packages/core/src/lib/sign-in.ts
  packages/core/src/lib/social.ts
  packages/core/src/routes/session.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#220 refactor(core): refactor error handler logic
  packages/core/src/app/init.ts
  packages/core/src/errors/OIDCRequestError/index.ts
  packages/core/src/errors/RequestError/index.ts
  packages/core/src/errors/SlonikError/index.ts
  packages/core/src/middleware/koa-auth.ts
  packages/core/src/middleware/koa-error-handler.ts
  packages/core/src/middleware/koa-oidc-error-handler.ts
  packages/core/src/middleware/koa-slonik-error-handler.ts
  packages/core/src/queries/application.ts
  packages/core/src/queries/passcode.ts
  packages/core/src/queries/resource.ts
  packages/core/src/queries/scope.ts
  packages/core/src/queries/user.ts
  packages/core/src/routes/session.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/schemas/src/api/error.ts
Labels: enhancement

#226 feat: set profiles from social connector
  packages/core/src/database/find-many.test.ts
  packages/core/src/lib/register.ts
  packages/schemas/src/db-entries/user.ts
  packages/schemas/tables/users.sql
Labels: feature

#225 feat: update social info on sign in
  packages/core/src/lib/sign-in.ts
Labels: feature

#228 refactor(core): throw error on pagination middleware
  packages/core/src/middleware/koa-pagination.test.ts
  packages/core/src/middleware/koa-pagination.ts
Labels: enhancement

#224 fix(core): align resource_identifier namespace with OIDC provider
  packages/core/src/oidc/init.ts
  packages/core/src/queries/resource.ts
  packages/schemas/src/db-entries/resource.ts
  packages/schemas/tables/resources.sql
Labels: bugfix

#230 feat(core): add `custom_data` to the user schema
  packages/core/src/database/find-many.test.ts
  packages/schemas/src/db-entries/user.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/tables/users.sql
Labels: feature

#223 feat: continue social sign in
  packages/core/src/connectors/types.ts
  packages/core/src/lib/register.ts
  packages/core/src/lib/sign-in.ts
  packages/core/src/lib/social.ts
  packages/core/src/routes/session.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#229 test(ut): add error type ut
  packages/core/src/errors/RequestError/request-error.test.ts
  packages/core/src/errors/SlonikError/slonik-error.test.ts
Labels: testing

#227 test(core): add ut for app
  packages/core/jest.config.js
  packages/core/src/app/init.test.ts
  packages/core/src/utils/test-utils.ts
Labels: testing

#231 test(i18n): add detectLanguage util test
  packages/core/src/i18n/detect-language.test.ts
Labels: testing

#240 fix: connector_id_mismatch and mergeWithLastSubmission
  packages/core/src/lib/register.ts
  packages/core/src/lib/social.ts
Labels: bugfix

#239 feat(console): init
  .github/workflows/main.yml
  .gitignore
  .npmrc
  packages/console/README.md
  packages/console/package.json
  packages/console/src/App.module.scss
  packages/console/src/App.tsx
  packages/console/src/include.d/react-app.d.ts
  packages/console/src/index.html
  packages/console/src/index.tsx
  packages/console/tsconfig.json
  pnpm-lock.yaml
Labels: feature

#241 refactor: upgrade TypeScript
  package.json
  packages/console/package.json
  packages/core/package.json
  packages/phrases/package.json
  packages/schemas/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: enhancement

#237 feat(core): get `/users`
  packages/core/src/queries/user.ts
  packages/core/src/routes/admin-user.ts
Labels: feature

#236 feat(core): get `/users/:userId`
  packages/core/src/routes/admin-user.ts
Labels: feature

#238 feat(core): post `/users`
  packages/core/src/routes/admin-user.ts
Labels: feature

#232 feat(core): patch `/user/:userId/custom-data`
  packages/core/src/routes/admin-user.ts
  packages/schemas/src/types/user.ts
Labels: feature

#243 chore: upgrade configs
  packages/console/package.json
  packages/core/package.json
  packages/core/src/connectors/utilities/aliyun.ts
  packages/core/src/connectors/utilities/index.ts
  packages/core/src/i18n/detect-language.ts
  packages/core/src/utils/password.ts
  packages/phrases/package.json
  packages/schemas/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: chore

#242 chore: connector error
  packages/core/src/app/init.ts
  packages/core/src/connectors/aliyun-dm/index.ts
  packages/core/src/connectors/aliyun-sms/index.ts
  packages/core/src/connectors/github/index.ts
  packages/core/src/connectors/types.ts
  packages/core/src/middleware/koa-connector-error-handle.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: chore

#233 feat(core): delete `users/:userid/custom-data`
  packages/core/src/queries/user.ts
  packages/core/src/routes/admin-user.ts
Labels: feature

#244 test(core): add middleware tests [1 of 2]
  packages/core/jest.config.js
  packages/core/jest.setup.js
  packages/core/src/app/init.test.ts
  packages/core/src/middleware/koa-auth.test.ts
  packages/core/src/middleware/koa-error-handler.test.ts
  packages/core/src/middleware/koa-error-handler.ts
  packages/core/src/middleware/koa-guard.test.ts
  packages/core/src/middleware/koa-i18next.test.ts
  packages/core/src/utils/test-utils.ts
Labels: testing

#245 feat(ui): init `ui-new` package
  packages/console/src/index.html
  packages/ui-new/README.md
  packages/ui-new/package.json
  packages/ui-new/src/App.module.scss
  packages/ui-new/src/App.tsx
  packages/ui-new/src/include.d/react-app.d.ts
  packages/ui-new/src/index.html
  packages/ui-new/src/index.tsx
  packages/ui-new/tsconfig.json
  pnpm-lock.yaml
Labels: feature

#235 feat(core): separate sessionRoutes by flow types
  packages/core/src/routes/session.ts
  packages/ui/src/apis/register.ts
  packages/ui/src/apis/sign-in.ts
Labels: feature

#247 test(core): add more middleware tests [2 of 2]
  packages/core/src/middleware/koa-auth.test.ts
  packages/core/src/middleware/koa-guard.test.ts
  packages/core/src/middleware/koa-i18next.test.ts
  packages/core/src/middleware/koa-oidc-error-handler.test.ts
  packages/core/src/middleware/koa-oidc-error-handler.ts
  packages/core/src/middleware/koa-slonik-error-handler.test.ts
  packages/core/src/middleware/koa-ui-proxy.test.ts
  packages/core/src/middleware/koa-user-info.test.ts
  packages/core/src/middleware/koa-user-log.test.ts
  packages/core/src/utils/test-utils.ts
Labels: testing

#248 feat(core): users sensitive operation api
  packages/core/src/routes/admin-user.ts
Labels: feature

#254 refactor(core): remove user route
  packages/core/src/routes/init.ts
  packages/core/src/routes/user.ts
Labels: enhancement

#257 refactor(ui): migrate files 2/2
  packages/ui-new/jest.config.ts
  packages/ui-new/package.json
  packages/ui-new/src/App.tsx
  packages/ui-new/src/__mocks__/react-i18next.jsx
  packages/ui-new/src/jest.setup.ts
  packages/ui-new/tsconfig.json
  packages/ui-new/tsconfig.test.json
  pnpm-lock.yaml
Labels: enhancement

#252 test(core): add admin-user route UT
  packages/core/package.json
  packages/core/src/middleware/koa-user-info.test.ts
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
  packages/core/src/utils/test-utils.ts
  pnpm-lock.yaml
Labels: testing

#263 chore(core): fix UI router
  packages/ui/src/apis/register.ts
  packages/ui/src/apis/sign-in.ts
Labels: chore

#264 test(core): add ut for util methods
  packages/core/src/utils/assert-that.test.ts
  packages/core/src/utils/id.test.ts
  packages/core/src/utils/zod.test.ts
Labels: testing

#262 test(core): add ut for core routers
  packages/core/src/middleware/koa-user-info.test.ts
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/application.test.ts
  packages/core/src/routes/resource.test.ts
  packages/core/src/routes/role.test.ts
  packages/core/src/routes/setting.test.ts
  packages/core/src/routes/sign-in-experience.test.ts
  packages/core/src/routes/status.test.ts
  packages/core/src/routes/swagger.test.ts
  packages/core/src/utils/mock.ts
  packages/core/src/utils/test-utils.ts
Labels: testing

#259 feat: bind social account
  packages/core/src/routes/session.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#258 feat: sign in to social related user
  packages/core/src/lib/sign-in.ts
  packages/core/src/lib/social.ts
  packages/core/src/routes/session.ts
Labels: feature

#249 feat: continue to register with social
  packages/core/src/lib/register.ts
  packages/core/src/lib/sign-in.ts
  packages/core/src/lib/social.ts
  packages/core/src/routes/session.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#268 chore: make connectorInstance.connector non-nullable
  packages/core/src/connectors/index.ts
  packages/core/src/connectors/types.ts
  packages/core/src/lib/passcode.test.ts
  packages/core/src/lib/passcode.ts
  packages/core/src/lib/sign-in.ts
Labels: chore

#267 refactor(core): use custom `koa-router` types
  packages/core/package.json
  packages/core/src/include.d/koa-router.d.ts
  pnpm-lock.yaml
Labels: enhancement

#271 chore(core): refactor register codes
  packages/core/src/lib/register.ts
  packages/core/src/routes/session.ts
Labels: chore

#255 feat(core): add koa user role guard middleware
  packages/core/src/middleware/koa-role-guard.test.ts
  packages/core/src/middleware/koa-role-guard.ts
  packages/schemas/src/types/user.ts
Labels: feature

#266 test(oidc): add oidc adapter test case
  packages/core/src/oidc/adapter.test.ts
  packages/core/src/oidc/init.test.ts
  packages/core/src/oidc/init.ts
  packages/core/src/oidc/utils.test.ts
Labels: testing

#274 test(core): update the requester test utils
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/application.test.ts
  packages/core/src/routes/resource.test.ts
  packages/core/src/routes/role.test.ts
  packages/core/src/routes/setting.test.ts
  packages/core/src/routes/sign-in-experience.test.ts
  packages/core/src/routes/status.test.ts
  packages/core/src/routes/swagger.test.ts
  packages/core/src/utils/test-utils.ts
Labels: testing

#261 chore(core): hide settings default id
  packages/core/src/routes/setting.test.ts
  packages/core/src/routes/setting.ts
Labels: chore

#277 chore: rename route for bind and sign in
  packages/core/src/routes/session.ts
Labels: chore

#276 test(session): test setup for session route
  packages/core/src/routes/session.test.ts
  packages/core/src/routes/session.ts
  packages/core/src/utils/test-utils.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: testing

#278 chore: zh-cn translation for connector
  packages/phrases/src/locales/zh-cn.ts
Labels: chore

#273 chore(core): refactor sign-in routes
  packages/core/src/lib/session.ts
  packages/core/src/lib/sign-in.ts
  packages/core/src/routes/session.ts
Labels: chore

#270 feat(core): get `/users` with search
  packages/core/src/queries/user.ts
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
  packages/core/src/utils/mock.ts
Labels: feature

#279 test(core): add ut for admin-user
  packages/core/src/routes/admin-user.test.ts
Labels: testing

#281 refactor(core): add prefix for `password_encryption_method`
  packages/core/src/lib/user.test.ts
  packages/core/src/lib/user.ts
  packages/core/src/utils/password.ts
  packages/schemas/src/db-entries/custom-types.ts
  packages/schemas/src/db-entries/user.ts
  packages/schemas/tables/users.sql
Labels: enhancement

#280 feat(core): separate passwordless flow routes
  packages/core/src/lib/session.ts
  packages/core/src/routes/session.ts
Labels: feature

#275 feat(core): get `/session/register/:username/existence`
  packages/core/src/routes/session.ts
  packages/core/src/utils/regex.ts
Labels: feature

#285 chore(core): username/phone/email validity checks to koaGuard middleware (in /session routes)
  packages/core/src/lib/session.ts
  packages/core/src/routes/session.ts
Labels: chore

#286 fix: update VSCode settings to format js/ts on save
  .vscode/settings.json
Labels: bugfix

#282 test(core): add ut for application query
  packages/core/package.json
  packages/core/src/queries/application.test.ts
  packages/core/src/queries/application.ts
  packages/core/src/utils/test-utils.ts
  pnpm-lock.yaml
Labels: testing

#284 chore(core): enable pass redirectUri when sign-in with social
  packages/core/src/lib/session.ts
  packages/core/src/routes/session.ts
Labels: feature, chore

#283 test: session route
  packages/core/src/lib/social.ts
  packages/core/src/routes/session.test.ts
  packages/core/src/routes/session.ts
  packages/core/src/utils/test-utils.ts
Labels: testing

#290 refactor(core): add arbitrary object guard type
  packages/core/src/connectors/types.ts
  packages/core/src/connectors/utilities/index.ts
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
  packages/schemas/src/db-entries/connector.ts
  packages/schemas/src/db-entries/user.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/tables/connectors.sql
  packages/schemas/tables/users.sql
Labels: enhancement

#288 refactor(core): add regex for commonly used fileds
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
  packages/core/src/routes/session.ts
  packages/core/src/utils/regex.ts
Labels: enhancement

#293 fix(core): patch `/users/:userId` should not fail if only `name` or `avatar` is provided
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
Labels: bugfix

#291 test(core): github and connector utilities
  packages/core/src/connectors/github/index.test.ts
  packages/core/src/connectors/utilities/aliyun.ts
  packages/core/src/connectors/utilities/index.test.ts
  packages/core/src/connectors/utilities/index.ts
Labels: testing

#287 test(core): add ut for queires
  packages/core/src/oidc/adapter.test.ts
  packages/core/src/oidc/adapter.ts
  packages/core/src/queries/application.test.ts
  packages/core/src/queries/connector.test.ts
  packages/core/src/queries/oidc-model-instance.test.ts
  packages/core/src/queries/oidc-model-instance.ts
  packages/core/src/queries/passcode.test.ts
  packages/core/src/queries/passcode.ts
  packages/core/src/queries/resource.test.ts
  packages/core/src/queries/resource.ts
  packages/core/src/queries/roles.test.ts
  packages/core/src/queries/roles.ts
  packages/core/src/queries/scope.test.ts
  packages/core/src/queries/scope.ts
  packages/core/src/queries/setting.test.ts
  packages/core/src/queries/sign-in-experience.test.ts
  packages/core/src/queries/user-log.test.ts
  packages/core/src/queries/user.test.ts
  packages/core/src/queries/user.ts
  packages/core/src/utils/mock.ts
  packages/core/src/utils/test-utils.ts
Labels: testing

#294 chore: upgrade configs and eslint
  package.json
  packages/console/package.json
  packages/core/package.json
  packages/core/src/connectors/github/index.test.ts
  packages/core/src/database/utils.ts
  packages/core/src/lib/social.ts
  packages/core/src/queries/oidc-model-instance.ts
  packages/phrases/package.json
  packages/schemas/package.json
  packages/schemas/src/gen/types.ts
  packages/ui/package.json
  packages/ui/src/components/AppContent/index.module.scss
  packages/ui/src/hooks/use-api.ts
  pnpm-lock.yaml
Labels: chore

#296 fix(schemas): remove unused dependency
  packages/phrases/package.json
  pnpm-lock.yaml
Labels: bugfix
