Repository logto-io/logto, pull requests merged in 2022-01, with the labels that each got.

#163 chore: add boolean type for postgres
  packages/schemas/src/gen/utils.ts
Labels: chore

#159 feat: buildFindMany
  packages/core/src/database/find-many.test.ts
  packages/core/src/database/find-many.ts
Labels: feature

#164 feat: connector DB schema
  packages/schemas/src/db-entries/connector.ts
  packages/schemas/src/db-entries/custom-types.ts
  packages/schemas/src/db-entries/index.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/tables/connectors.sql
Labels: feature

#165 feat: settings DB schema
  packages/schemas/src/db-entries/index.ts
  packages/schemas/src/db-entries/setting.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/tables/settings.sql
Labels: feature

#169 feat(schema): update application db
  packages/core/src/oidc/adapter.ts
  packages/core/src/oidc/utils.ts
  packages/core/src/routes/application.ts
  packages/schemas/src/db-entries/application.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/tables/applications.sql
Labels: feature

#166 feat: init connectors
  packages/core/src/connectors/aliyun-dm/index.ts
  packages/core/src/connectors/index.ts
  packages/core/src/connectors/types.ts
  packages/core/src/index.ts
  packages/core/src/queries/connector.ts
Labels: feature

#170 feat(applications): add pagination middleware to findAllApplications
  packages/core/src/database/utils.ts
  packages/core/src/queries/application.ts
  packages/core/src/routes/application.ts
Labels: feature

#173 chore: rename all `\w+DBEntry` as `\w+Update` to eliminate misunderstanding
  packages/core/src/database/insert-into.test.ts
  packages/core/src/database/update-where.test.ts
  packages/core/src/oidc/adapter.ts
  packages/core/src/queries/application.ts
  packages/core/src/queries/connector.ts
  packages/core/src/queries/oidc-model-instance.ts
  packages/core/src/queries/resources.ts
  packages/core/src/queries/scopes.ts
  packages/core/src/queries/user-log.ts
  packages/core/src/queries/user.ts
  packages/schemas/src/db-entries/application.ts
  packages/schemas/src/db-entries/connector.ts
  packages/schemas/src/db-entries/oidc-model-instance.ts
  packages/schemas/src/db-entries/resource-scope.ts
  packages/schemas/src/db-entries/resource.ts
  packages/schemas/src/db-entries/setting.ts
  packages/schemas/src/db-entries/user-log.ts
  packages/schemas/src/db-entries/user.ts
  packages/schemas/src/gen/schema.ts
  packages/schemas/src/types/user.ts
Labels: chore

#168 feat: updateConnectorConfig
  packages/core/src/connectors/utils.ts
  packages/core/src/queries/connector.ts
Labels: feature

#176 feat(application): set idToken and refreshToken ttl based on client metadata
  packages/core/src/include.d/oidc-provider.d.ts
  packages/core/src/oidc/adapter.ts
  packages/core/src/oidc/consts.ts
  packages/core/src/oidc/init.ts
  packages/schemas/src/db-entries/application.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/tables/applications.sql
Labels: feature

#172 feat(application): add application query exceptions
  packages/core/src/middleware/koa-error-handler.ts
  packages/core/src/queries/application.ts
  packages/core/src/routes/application.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#177 refactor(errors): introduce Slonik Deletion Error
  packages/core/src/errors/SlonikError/index.ts
  packages/core/src/queries/application.ts
  packages/core/src/queries/resources.ts
  packages/core/src/queries/scopes.ts
  packages/core/src/queries/user.ts
Labels: enhancement

#179 refactor(core): resources related db query cleanup
  packages/core/src/oidc/init.ts
  packages/core/src/queries/resource.ts
  packages/core/src/queries/scope.ts
  packages/schemas/src/db-entries/custom-types.ts
  packages/schemas/src/db-entries/resource.ts
  packages/schemas/tables/resource_scopes.sql
  packages/schemas/tables/resources.sql
Labels: enhancement

#171 feat: connector i18n
  packages/core/src/connectors/aliyun-dm/index.ts
  packages/core/src/connectors/types.ts
  packages/phrases/src/index.ts
Labels: feature

#175 feat: aliyun direct mail connector
  packages/core/src/connectors/aliyun-dm/index.ts
  packages/core/src/connectors/aliyun-dm/single-send-mail.test.ts
  packages/core/src/connectors/aliyun-dm/single-send-mail.ts
  packages/core/src/connectors/types.ts
  packages/core/src/connectors/utilities/aliyun.test.ts
  packages/core/src/connectors/utilities/aliyun.ts
  packages/core/src/connectors/utilities/index.ts
Labels: feature

#180 feat(core): add resource apis
  packages/core/src/routes/init.ts
  packages/core/src/routes/resource.ts
Labels: feature

#182 refactor(schema): rename schema
  packages/core/src/database/insert-into.test.ts
  packages/core/src/database/update-where.test.ts
  packages/core/src/oidc/adapter.ts
  packages/core/src/queries/application.ts
  packages/core/src/queries/connector.ts
  packages/core/src/queries/oidc-model-instance.ts
  packages/core/src/queries/resource.ts
  packages/core/src/queries/scope.ts
  packages/core/src/queries/setting.ts
  packages/core/src/queries/user-log.ts
  packages/core/src/queries/user.ts
  packages/core/src/routes/application.ts
  packages/core/src/routes/resource.ts
  packages/core/src/routes/setting.ts
  packages/schemas/src/db-entries/application.ts
  packages/schemas/src/db-entries/connector.ts
  packages/schemas/src/db-entries/oidc-model-instance.ts
  packages/schemas/src/db-entries/resource-scope.ts
  packages/schemas/src/db-entries/resource.ts
  packages/schemas/src/db-entries/setting.ts
  packages/schemas/src/db-entries/user-log.ts
  packages/schemas/src/db-entries/user.ts
  packages/schemas/src/foundations/schemas.ts
  packages/schemas/src/gen/schema.ts
  packages/schemas/src/types/user.ts
Labels: enhancement

#184 feat(aliyun-dm): validate config
  packages/core/src/connectors/aliyun-dm/index.ts
  packages/core/src/connectors/types.ts
Labels: feature

#183 feat(aliyun-dm): test message template
  packages/core/src/connectors/aliyun-dm/index.ts
  packages/core/src/connectors/types.ts
Labels: feature

#185 feat(github): getAuthorizeUri
  packages/core/src/connectors/github/constant.ts
  packages/core/src/connectors/github/index.test.ts
  packages/core/src/connectors/github/index.ts
  packages/core/src/connectors/types.ts
Labels: feature

#186 feat(github): getAccessToken
  packages/core/package.json
  packages/core/src/connectors/github/constant.ts
  packages/core/src/connectors/github/index.test.ts
  packages/core/src/connectors/github/index.ts
  packages/core/src/connectors/types.ts
  pnpm-lock.yaml
Labels: feature

#189 feat(github): validateConfig
  packages/core/src/connectors/github/index.test.ts
  packages/core/src/connectors/github/index.ts
  packages/core/src/connectors/types.ts
Labels: feature

#188 feat(github): getUserInfo
  packages/core/src/connectors/github/constant.ts
  packages/core/src/connectors/github/index.test.ts
  packages/core/src/connectors/github/index.ts
  packages/core/src/connectors/types.ts
Labels: feature

#187 refactor(core): enable userinfo endpoint and resource scope consent
  packages/core/src/oidc/init.ts
  packages/core/src/routes/session.ts
Labels: enhancement

#190 chore: fix typo in pull request template
  .github/pull_request_template.md
Labels: chore

#178 feat(connector): connector queries and APIs
  packages/core/src/connectors/aliyun-dm/index.ts
  packages/core/src/connectors/github/index.ts
  packages/core/src/connectors/index.ts
  packages/core/src/connectors/types.ts
  packages/core/src/connectors/utilities/index.ts
  packages/core/src/queries/connector.ts
  packages/core/src/routes/connector.ts
  packages/core/src/routes/init.ts
  packages/schemas/src/db-entries/connector.ts
  packages/schemas/src/db-entries/custom-types.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/tables/connectors.sql
Labels: feature

#192 refactor(phrases): replace Normalize with NormalizeKeyPaths
  packages/phrases/package.json
  packages/phrases/src/index.ts
  packages/phrases/src/types.ts
  pnpm-lock.yaml
Labels: enhancement, chore

#195 fix: initConnector use hasConnector
  packages/core/src/connectors/index.ts
  packages/core/src/queries/connector.ts
Labels: bugfix

#191 feat(core): add sign-in-experiences table
  packages/schemas/src/db-entries/index.ts
  packages/schemas/src/db-entries/sign-in-experience.ts
  packages/schemas/src/db-entries/sign-in-method.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/tables/resource_scopes.sql
  packages/schemas/tables/sign_in_experiences.sql
  packages/schemas/tables/sign_in_methods.sql
Labels: feature

#194 fix(database): insertKeys filtering
  packages/core/src/database/insert-into.test.ts
  packages/core/src/database/insert-into.ts
Labels: bugfix

#193 chore: align routers return process of updating DB
  packages/core/src/queries/connector.ts
  packages/core/src/routes/connector.ts
  packages/core/src/routes/user.ts
Labels: chore

#197 feat(core): add sign-in experience query and api
  packages/core/src/queries/sign-in-experience.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/sign-in-experience.ts
Labels: feature

#196 feat: user register
  packages/core/src/routes/init.ts
  packages/core/src/routes/session.ts
  packages/core/src/routes/user.ts
  packages/ui/src/apis/register.ts
Labels: feature

#198 feat: passcode table
  packages/schemas/src/db-entries/custom-types.ts
  packages/schemas/src/db-entries/index.ts
  packages/schemas/src/db-entries/passcode.ts
  packages/schemas/tables/passcodes.sql
Labels: feature

#202 feat(schema): add roles table
  packages/core/src/database/find-many.test.ts
  packages/core/src/database/utils.test.ts
  packages/schemas/src/db-entries/index.ts
  packages/schemas/src/db-entries/role.ts
  packages/schemas/src/db-entries/user.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/foundations/schemas.ts
  packages/schemas/tables/roles.sql
  packages/schemas/tables/users.sql
Labels: feature

#205 chore: upgrade eslint-config to v0.6.1
  packages/core/package.json
  packages/core/src/app/init.ts
  packages/core/src/connectors/aliyun-dm/index.ts
  packages/core/src/connectors/github/index.ts
  packages/core/src/connectors/index.ts
  packages/core/src/connectors/utilities/aliyun.ts
  packages/core/src/connectors/utilities/index.ts
  packages/core/src/database/insert-into.test.ts
  packages/core/src/database/insert-into.ts
  packages/core/src/database/update-where.ts
  packages/core/src/i18n/detect-language.ts
  packages/core/src/index.ts
  packages/core/src/lib/user.test.ts
  packages/core/src/middleware/koa-auth.ts
  packages/core/src/middleware/koa-error-handler.ts
  packages/core/src/middleware/koa-i18next.ts
  packages/core/src/middleware/koa-pagination.test.ts
  packages/core/src/middleware/koa-pagination.ts
  packages/core/src/middleware/koa-ui-proxy.ts
  packages/core/src/middleware/koa-user-log.ts
  packages/core/src/oidc/init.ts
  packages/core/src/queries/application.ts
  packages/core/src/queries/resource.ts
  packages/core/src/queries/scope.ts
  packages/core/src/queries/user.ts
  packages/core/src/routes/application.ts
  packages/core/src/routes/resource.ts
  packages/core/src/routes/session.ts
  packages/core/src/routes/status.ts
  packages/core/src/routes/swagger.ts
  packages/core/src/routes/user.ts
  packages/core/src/utils/pagination.ts
  packages/phrases/package.json
  packages/phrases/src/types.ts
  packages/schemas/package.json
  packages/schemas/src/gen/index.ts
  packages/schemas/src/gen/schema.ts
  packages/schemas/src/gen/utils.ts
  packages/ui/package.json
  packages/ui/src/apis/consent.ts
  packages/ui/src/apis/register.ts
  packages/ui/src/apis/sign-in.ts
  packages/ui/src/client.tsx
  packages/ui/src/hooks/use-api.ts
  packages/ui/src/hooks/use-theme.ts
  pnpm-lock.yaml
Labels: chore

#199 feat(core): createPasscode
  packages/core/src/lib/passcode.test.ts
  packages/core/src/lib/passcode.ts
  packages/core/src/queries/passcode.ts
Labels: feature

#204 feat(core): add user roles related api
  packages/core/src/database/update-where.test.ts
  packages/core/src/database/utils.test.ts
  packages/core/src/database/utils.ts
  packages/core/src/queries/roles.ts
  packages/core/src/routes/admin-user.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/role.ts
  packages/core/src/routes/user.ts
  packages/schemas/src/db-entries/user.ts
  packages/schemas/src/types/user.ts
  packages/schemas/tables/users.sql
Labels: feature

#200 feat: sendPasscode
  packages/core/src/connectors/index.ts
  packages/core/src/connectors/types.ts
  packages/core/src/lib/passcode.test.ts
  packages/core/src/lib/passcode.ts
  packages/core/src/queries/passcode.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#201 feat: verifyPasscode
  packages/core/src/lib/passcode.test.ts
  packages/core/src/lib/passcode.ts
  packages/core/src/queries/passcode.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#206 fix(aliyun-dm): validate config before sending
  packages/core/src/connectors/aliyun-dm/index.ts
Labels: bugfix

#207 fix(passcode): use interaction_jti instead of session_id
  packages/core/src/lib/passcode.test.ts
  packages/core/src/lib/passcode.ts
  packages/core/src/queries/passcode.ts
  packages/schemas/src/db-entries/passcode.ts
  packages/schemas/tables/passcodes.sql
Labels: bugfix

#203 feat(aliyun sms connector): add aliyun sms connector
  packages/core/src/connectors/aliyun-dm/index.ts
  packages/core/src/connectors/aliyun-dm/single-send-mail.test.ts
  packages/core/src/connectors/aliyun-dm/single-send-mail.ts
  packages/core/src/connectors/aliyun-sms/index.ts
  packages/core/src/connectors/aliyun-sms/single-send-text.test.ts
  packages/core/src/connectors/aliyun-sms/single-send-text.ts
  packages/core/src/connectors/index.ts
  packages/core/src/connectors/types.ts
  packages/core/src/connectors/utilities/aliyun.ts
  packages/phrases/src/locales/en.ts
Labels: feature

#208 fix(aliyun): skip undefined fields
  packages/core/src/connectors/utilities/aliyun.ts
Labels: bugfix

#209 feat(core): sign in with email
  packages/core/src/lib/sign-in.ts
  packages/core/src/lib/user.ts
  packages/core/src/middleware/koa-user-log.ts
  packages/core/src/queries/passcode.ts
  packages/core/src/queries/user.ts
  packages/core/src/routes/session.ts
  packages/core/src/utils/regex.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/schemas/src/db-entries/custom-types.ts
  packages/schemas/tables/user_logs.sql
Labels: feature
