Repository logto-io/logto, pull requests merged in 2022-12, with the labels that each got.

#2551 refactor(core): add profile verification
  packages/core/src/routes/interaction/types/guard.ts
  packages/core/src/routes/interaction/types/index.ts
  packages/core/src/routes/interaction/utils/index.ts
  packages/core/src/routes/interaction/utils/interaction.ts
  packages/core/src/routes/interaction/verifications/identifier-verification.test.ts
  packages/core/src/routes/interaction/verifications/identifier-verification.ts
  packages/core/src/routes/interaction/verifications/profile-verification-profile-exist.test.ts
  packages/core/src/routes/interaction/verifications/profile-verification-profile-registered.test.ts
  packages/core/src/routes/interaction/verifications/profile-verification-protected-identifier.test.ts
  packages/core/src/routes/interaction/verifications/profile-verification.ts
Labels: enhancement, size/xl

#2560 feat(console): add standard connector
  packages/console/src/pages/Connectors/components/CreateForm/index.tsx
  packages/console/src/pages/Connectors/components/Guide/Form.tsx
  packages/console/src/pages/Connectors/components/Guide/index.module.scss
  packages/console/src/pages/Connectors/components/Guide/index.tsx
  packages/console/src/pages/Connectors/components/Guide/types.ts
  packages/console/src/pages/Connectors/utils/index.ts
  packages/console/src/types/connector.ts
  packages/console/src/types/guide.ts
  packages/phrases/src/locales/de/translation/admin-console/connectors.ts
  packages/phrases/src/locales/en/translation/admin-console/connectors.ts
  packages/phrases/src/locales/fr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/ko/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/connectors.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/connectors.ts
Labels: feature, size/l

#2563 refactor(core): refactor the type and guard
  packages/core/src/routes/interaction/middleware/koa-interaction-body-guard.ts
  packages/core/src/routes/interaction/types/guard.ts
  packages/core/src/routes/interaction/types/index.ts
  packages/core/src/routes/interaction/utils/index.ts
  packages/core/src/routes/interaction/utils/passcode-validation.test.ts
  packages/core/src/routes/interaction/utils/passcode-validation.ts
  packages/core/src/routes/interaction/utils/sign-in-experience-validation.ts
  packages/core/src/routes/interaction/utils/social-verification.ts
  packages/core/src/routes/interaction/verifications/identifier-verification.ts
  packages/schemas/src/types/interactions.ts
Labels: enhancement, size/m

#2564 fix: upgrade parcel and fix dropdown component css specificity issues
  packages/console/package.json
  packages/console/src/components/ActionMenu/index.module.scss
  packages/console/src/components/ActionMenu/index.tsx
  packages/console/src/components/AppContent/components/UserInfo/index.module.scss
  packages/console/src/components/AppContent/components/UserInfo/index.tsx
  packages/console/src/components/Dropdown/index.module.scss
  packages/console/src/components/Select/index.module.scss
  packages/console/src/components/Select/index.tsx
  packages/console/src/pages/GetStarted/components/GetStartedProgress/index.module.scss
  packages/console/src/pages/GetStarted/components/GetStartedProgress/index.tsx
  packages/demo-app/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: bugfix, size/m

#2565 fix(console): add language button should be hidden on click
  packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/AddLanguageSelector.module.scss
  packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/AddLanguageSelector.tsx
Labels: bugfix, size/s

#2559 refactor: sign up settings schema
  packages/console/src/hooks/use-connector-in-use.ts
  packages/console/src/pages/SignInExperience/components/SignUpAndSignInChangePreview/SignUpAndSignInDiffSection/SignInDiffSection.tsx
  packages/console/src/pages/SignInExperience/components/SignUpAndSignInChangePreview/SignUpAndSignInDiffSection/SignUpDiffSection.tsx
  packages/console/src/pages/SignInExperience/components/SignUpAndSignInChangePreview/SignUpAndSignInDiffSection/utilities.ts
  packages/console/src/pages/SignInExperience/components/Welcome/GuideModal.tsx
  packages/console/src/pages/SignInExperience/constants.ts
  packages/console/src/pages/SignInExperience/hooks/use-preview-configs.ts
  packages/console/src/pages/SignInExperience/index.tsx
  packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/LanguageDetails.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/SignUpForm.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SignInMethodEditBox/index.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/constants.ts
  packages/console/src/pages/SignInExperience/types.ts
  packages/console/src/pages/SignInExperience/utils/form.ts
  packages/console/src/pages/SignInExperience/utils/identifier.ts
  packages/console/src/pages/SignInExperience/utils/language.ts
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/lib/sign-in-experience/sign-in.test.ts
  packages/core/src/lib/sign-in-experience/sign-in.ts
  packages/core/src/lib/sign-in-experience/sign-up.test.ts
  packages/core/src/lib/sign-in-experience/sign-up.ts
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/interaction/utils/sign-in-experience-valiation.test.ts
  packages/core/src/routes/interaction/utils/sign-in-experience-validation.ts
  packages/core/src/routes/session/middleware/passwordless-action.ts
  packages/core/src/routes/session/password.test.ts
  packages/core/src/routes/session/password.ts
  packages/core/src/routes/session/passwordless.test.ts
  packages/core/src/routes/session/profile.test.ts
  packages/core/src/routes/session/social.bind-social.test.ts
  packages/core/src/routes/session/social.test.ts
  packages/core/src/routes/session/utils.test.ts
  packages/core/src/routes/session/utils.ts
  packages/integration-tests/src/constants.ts
  packages/integration-tests/src/helpers.ts
  packages/integration-tests/tests/api/dashboard.test.ts
  packages/integration-tests/tests/api/logs.test.ts
  packages/integration-tests/tests/api/session.test.ts
  packages/integration-tests/tests/api/social-session.test.ts
  packages/integration-tests/tests/api/wellknown.test.ts
  packages/schemas/alterations/next-1669702299-sign-up.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/seeds/sign-in-experience.ts
  packages/ui/src/__mocks__/RenderWithPageContext/SettingsProvider.tsx
  packages/ui/src/__mocks__/logto.tsx
  packages/ui/src/hooks/use-page-context.ts
  packages/ui/src/hooks/use-preview.ts
  packages/ui/src/hooks/use-sie.ts
  packages/ui/src/pages/Continue/SetEmail/index.test.tsx
  packages/ui/src/pages/Continue/SetPhone/index.test.tsx
  packages/ui/src/pages/PasswordRegisterWithUsername/index.test.tsx
  packages/ui/src/pages/Register/index.test.tsx
  packages/ui/src/pages/SecondaryRegister/index.test.tsx
  packages/ui/src/types/index.ts
  packages/ui/src/utils/sign-in-experience.test.ts
  packages/ui/src/utils/sign-in-experience.ts
Labels: enhancement, size/xl

#2571 chore(core): remove unused `checkMissingRequiredSignUpIdentifiers`
  packages/core/src/routes/session/utils.ts
Labels: chore, size/s

#2570 refactor(console): add animations for the submit form action bar
  packages/console/src/components/DetailsForm/index.module.scss
  packages/console/src/components/DetailsForm/index.tsx
  packages/console/src/components/SubmitFormChangesActionBar/index.module.scss
  packages/console/src/components/SubmitFormChangesActionBar/index.tsx
Labels: enhancement, size/s

#2566 feat(console): hide added connectors in modal
  packages/console/src/pages/Connectors/components/CreateForm/index.module.scss
  packages/console/src/pages/Connectors/components/CreateForm/index.tsx
Labels: feature, size/s

#2572 fix(core): `checkRequiredProfile` should work correctly when sign up identifier is `emailOrSms`
  packages/core/src/routes/session/utils.test.ts
  packages/core/src/routes/session/utils.ts
Labels: bugfix, size/m

#2574 refactor(console): increase the color picker interaction area
  packages/console/src/components/ColorPicker/index.module.scss
Labels: enhancement, size/xs

#2583 refactor(core): promote profile apis from session routes to its own api routes
  packages/core/src/lib/user.ts
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
  packages/core/src/routes/consts.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/profile.test.ts
  packages/core/src/routes/profile.ts
  packages/core/src/routes/session/consts.ts
  packages/core/src/routes/session/index.ts
  packages/core/src/routes/session/passwordless.test.ts
  packages/core/src/routes/session/utils.ts
Labels: enhancement, size/m

#2568 feat(console): edit standard connector
  packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx
  packages/console/src/pages/Connectors/components/ConnectorForm/index.module.scss
  packages/console/src/pages/Connectors/components/ConnectorForm/index.tsx
  packages/console/src/pages/Connectors/components/Guide/index.module.scss
  packages/console/src/pages/Connectors/components/Guide/index.tsx
  packages/console/src/pages/Connectors/types.ts
  packages/core/src/routes/connector.ts
  packages/core/src/routes/connector.update.test.ts
  packages/schemas/src/types/connector.ts
Labels: feature, size/m

#2584 style(console): `CopyToClipboard` component
  packages/console/src/components/CopyToClipboard/index.module.scss
  packages/console/src/components/CopyToClipboard/index.tsx
  packages/console/src/components/IconButton/index.tsx
Labels: size/s

#2585 style(console): set the `TabNavItem` text color to neutral-30
  packages/console/src/components/TabNav/TabNavItem.module.scss
Labels: size/xs

#2586 style(console): center align create buttons on list page
  packages/console/src/scss/resources.module.scss
Labels: size/xs

#2562 chore: merge v1.0.0-beta.16
  .changeset/clever-panthers-lay.md
  .changeset/green-geese-train.md
  .changeset/pre.json
  packages/cli/CHANGELOG.md
  packages/cli/package.json
  packages/console/CHANGELOG.md
  packages/console/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/core/src/routes/session/passwordless.ts
  packages/core/src/routes/session/utils.ts
  packages/create/CHANGELOG.md
  packages/create/package.json
  packages/demo-app/package.json
  packages/integration-tests/CHANGELOG.md
  packages/integration-tests/package.json
  packages/phrases-ui/package.json
  packages/phrases/CHANGELOG.md
  packages/phrases/package.json
  packages/phrases/src/locales/zh-cn/errors.ts
  packages/schemas/CHANGELOG.md
  packages/schemas/package.json
  packages/schemas/src/types/log.ts
  packages/shared/CHANGELOG.md
  packages/shared/package.json
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/containers/PasscodeValidation/use-register-with-email-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/use-register-with-sms-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/use-sign-in-with-email-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/use-sign-in-with-sms-passcode-validation.ts
  packages/ui/src/pages/Continue/EmailOrPhone/index.tsx
  packages/ui/src/pages/Continue/SetEmail/index.tsx
  packages/ui/src/pages/Continue/SetPassword/index.tsx
  packages/ui/src/pages/Continue/SetPhone/index.tsx
  packages/ui/src/pages/Continue/SetUsername/index.tsx
  pnpm-lock.yaml
Labels: chore, size/m

#2592 style(console): skeletons should not overlap the table header
  packages/console/src/scss/table.module.scss
Labels: size/xs

#2593 style(console): fix the minus icon size
  packages/console/src/assets/images/minus.svg
Labels: size/xs

#2588 refactor(console): extract toggle tip logic into a `ToggleTipButton` component
  packages/console/src/components/ToggleTipButton/index.module.scss
  packages/console/src/components/ToggleTipButton/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorStatusField/index.module.scss
  packages/console/src/pages/Connectors/components/ConnectorStatusField/index.tsx
Labels: enhancement, size/m

#2590 refactor(console): replace info tooltips with toggle tips
  packages/console/src/components/FormField/index.module.scss
  packages/console/src/components/FormField/index.tsx
  packages/console/src/components/MultiTextInputField/index.tsx
  packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
  packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx
  packages/console/src/pages/ApplicationDetails/components/Settings.tsx
  packages/console/src/pages/Dashboard/components/Block.module.scss
  packages/console/src/pages/Dashboard/components/Block.tsx
  packages/console/src/pages/Dashboard/index.tsx
  packages/console/src/pages/SignInExperience/tabs/Others/TermsForm.tsx
  packages/console/src/pages/UserDetails/components/UserSettings.tsx
Labels: enhancement, size/s

#2587 feat(console): sort connectors
  packages/console/src/pages/Connectors/components/CreateForm/constants.ts
  packages/console/src/pages/Connectors/components/CreateForm/index.tsx
  packages/console/src/pages/Connectors/components/CreateForm/utils.ts
Labels: feature, size/s

#2594 fix(console): error state for connector form
  packages/console/src/pages/Connectors/components/ConnectorForm/index.tsx
Labels: bugfix, size/s

#2595 feat(console): add trailing icon to dark visible toggle button
  packages/console/src/assets/images/caret-down.svg
  packages/console/src/assets/images/caret-up.svg
  packages/console/src/components/Button/index.module.scss
  packages/console/src/components/Button/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorForm/index.tsx
Labels: feature, size/s

#2576 fix: drop empty string, undefined and null fields of connector configurable metadata
  packages/core/src/routes/connector.test.ts
  packages/core/src/routes/connector.ts
  packages/core/src/routes/connector.update.test.ts
Labels: bugfix, size/s

#2591 chore: add IT for switching passwordless connector
  .github/workflows/integration-test.yml
  packages/integration-tests/src/__mocks__/connectors-mock.ts
  packages/integration-tests/tests/api/admin-user.test.ts
  packages/integration-tests/tests/api/connector.test.ts
  packages/integration-tests/tests/api/social-session.test.ts
Labels: chore, size/s

#2597 Revert "style(console): skeletons should not overlap the table header"
  packages/console/src/scss/table.module.scss
Labels: size/xs

#2589 feat(core,console): prevent target change after created
  packages/console/src/pages/Connectors/components/ConnectorForm/index.tsx
  packages/console/src/pages/Connectors/components/Guide/index.tsx
  packages/core/src/routes/connector.ts
  packages/core/src/routes/connector.update.test.ts
  packages/phrases/src/locales/de/errors.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
Labels: feature, size/s

#2599 refactor(console): align text link style
  packages/console/src/components/Alert/index.module.scss
  packages/console/src/components/Alert/index.tsx
  packages/console/src/components/FormCard/index.module.scss
  packages/console/src/components/FormCard/index.tsx
  packages/console/src/components/LinkButton/index.tsx
  packages/console/src/components/Markdown/index.module.scss
  packages/console/src/components/TextLink/index.module.scss
  packages/console/src/components/TextLink/index.tsx
  packages/console/src/mdx-components/Step/index.module.scss
  packages/console/src/pages/ApiResourceDetails/index.module.scss
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/console/src/pages/ApplicationDetails/index.module.scss
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/Applications/components/Guide/index.tsx
  packages/console/src/pages/AuditLogDetails/index.module.scss
  packages/console/src/pages/AuditLogDetails/index.tsx
  packages/console/src/pages/ConnectorDetails/index.module.scss
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorStatusField/index.module.scss
  packages/console/src/pages/Connectors/components/ConnectorStatusField/index.tsx
  packages/console/src/pages/Connectors/components/SignInExperienceSetupNotice/index.module.scss
  packages/console/src/pages/Connectors/components/SignInExperienceSetupNotice/index.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/ConnectorSetupWarning.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SocialConnectorEditBox/index.module.scss
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SocialConnectorEditBox/index.tsx
  packages/console/src/pages/UserDetails/index.module.scss
  packages/console/src/pages/UserDetails/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
Labels: enhancement, size/l

#2600 refactor(core,console): replace deduplicate logic with `deduplicate` util
  packages/console/src/hooks/use-ui-languages.ts
  packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx
  packages/core/src/app/init.ts
  packages/core/src/lib/sign-in-experience/index.ts
  packages/core/src/lib/user.ts
  packages/core/src/oidc/adapter.ts
Labels: enhancement, size/s

#2601 refactor(console,ui): import `noop` from `silverhand/essentials`
  packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/use-language-editor-context.ts
  packages/ui/src/containers/ConfirmModalProvider/index.tsx
  packages/ui/src/hooks/use-page-context.ts
Labels: enhancement, size/s

#2577 feat: prohibit multiple same-platform social connectors to share same target
  packages/core/src/__mocks__/connector.ts
  packages/core/src/lib/connector.test.ts
  packages/core/src/lib/connector.ts
  packages/core/src/routes/connector.test.ts
  packages/core/src/routes/connector.ts
  packages/phrases/src/locales/de/errors.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
Labels: feature, size/m

#2580 feat(core): patch interaction
  packages/core/src/routes/interaction/actions/submit-interaction.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/middleware/koa-interaction-body-guard.test.ts
  packages/core/src/routes/interaction/types/guard.ts
  packages/core/src/routes/interaction/types/index.ts
  packages/core/src/routes/interaction/utils/index.ts
  packages/core/src/routes/interaction/utils/interaction.ts
  packages/core/src/routes/interaction/verifications/identifier-payload-verification.test.ts
  packages/core/src/routes/interaction/verifications/identifier-payload-verification.ts
  packages/core/src/routes/interaction/verifications/identifier-verification.ts
  packages/core/src/routes/interaction/verifications/index.ts
  packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.test.ts
  packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.ts
  packages/core/src/routes/interaction/verifications/profile-verification-forgot-password.test.ts
  packages/core/src/routes/interaction/verifications/profile-verification-profile-exist.test.ts
  packages/core/src/routes/interaction/verifications/profile-verification-profile-registered.test.ts
  packages/core/src/routes/interaction/verifications/profile-verification-protected-identifier.test.ts
  packages/core/src/routes/interaction/verifications/profile-verification.ts
  packages/core/src/routes/interaction/verifications/user-identity-verification.test.ts
  packages/phrases/src/locales/de/errors.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
  packages/schemas/src/types/interactions.ts
Labels: feature, size/xl

#2606 refactor: fix workspace dep version
  packages/cli/package.json
  packages/console/package.json
  packages/core/package.json
  packages/create/package.json
  packages/demo-app/package.json
  packages/integration-tests/package.json
  packages/schemas/package.json
  packages/shared/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: enhancement, size/s

#2575 feat(phrases): add ptBR language
  packages/phrases-ui/src/index.ts
  packages/phrases-ui/src/locales/pt-br.ts
  packages/phrases/src/index.ts
  packages/phrases/src/locales/pt-br/errors.ts
  packages/phrases/src/locales/pt-br/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/applications.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/contact.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/dashboard.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/errors.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/get-started.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/log-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/logs.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/session-expired.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/settings.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tabs.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/users.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/welcome.ts
  packages/phrases/src/locales/pt-br/translation/demo-app.ts
  packages/phrases/src/locales/pt-br/translation/index.ts
Labels: feature, size/xl

#2608 refactor(console): improve tip components usage
  packages/console/src/components/Checkbox/index.tsx
  packages/console/src/components/CopyToClipboard/index.module.scss
  packages/console/src/components/CopyToClipboard/index.tsx
  packages/console/src/components/FormField/index.module.scss
  packages/console/src/components/FormField/index.tsx
  packages/console/src/components/IconButton/index.tsx
  packages/console/src/components/Tip/TipBubble/index.module.scss
  packages/console/src/components/Tip/TipBubble/index.tsx
  packages/console/src/components/Tip/TipBubble/utils.ts
  packages/console/src/components/Tip/ToggleTip/index.module.scss
  packages/console/src/components/Tip/ToggleTip/index.tsx
  packages/console/src/components/Tip/Tooltip/index.module.scss
  packages/console/src/components/Tip/Tooltip/index.tsx
  packages/console/src/components/Tip/index.ts
  packages/console/src/components/ToggleTip/index.tsx
  packages/console/src/components/ToggleTipButton/index.module.scss
  packages/console/src/components/ToggleTipButton/index.tsx
  packages/console/src/pages/Applications/components/GuideHeader/index.module.scss
  packages/console/src/pages/Applications/components/GuideHeader/index.tsx
  packages/console/src/pages/ConnectorDetails/components/SenderTester/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorStatusField/index.module.scss
  packages/console/src/pages/Connectors/components/ConnectorStatusField/index.tsx
  packages/console/src/pages/Dashboard/components/Block.module.scss
  packages/console/src/pages/Dashboard/components/Block.tsx
  packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/LanguageDetails.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SignInMethodEditBox/SignInMethodItem.tsx
Labels: enhancement, size/xl

#2619 feat(core): allow set primaryPhone in post user admin api
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
Labels: feature, size/s

#2616 feat(core): enable interaction routes online
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/interaction/verifications/user-identity-verification.test.ts
  packages/core/src/routes/interaction/verifications/user-identity-verification.ts
Labels: feature, size/s

#2612 test(core): add interaction route ut
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/core/src/routes/interaction/index.test.ts
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/utils/interaction.ts
  packages/core/src/routes/interaction/verifications/user-identity-verification.test.ts
  packages/core/src/routes/interaction/verifications/user-identity-verification.ts
Labels: testing, size/m

#2620 refactor(console): make the `LanguageEditor` responsive
  packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/LanguageDetails.module.scss
  packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/LanguageDetails.tsx
  packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/LanguageNav.module.scss
  packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/index.module.scss
  packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/index.tsx
Labels: enhancement, size/m

#2613 refactor(console): add link to toggle tips
  packages/console/src/components/FormField/index.tsx
  packages/console/src/components/Tip/TipBubble/index.module.scss
  packages/console/src/components/Tip/ToggleTip/index.tsx
  packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
  packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx
  packages/console/src/pages/ApplicationDetails/components/Settings.tsx
  packages/console/src/pages/Connectors/components/ConnectorStatusField/index.module.scss
  packages/console/src/pages/Connectors/components/ConnectorStatusField/index.tsx
  packages/console/src/pages/Dashboard/components/Block.tsx
  packages/console/src/pages/Dashboard/index.tsx
  packages/console/src/pages/SignInExperience/tabs/Others/TermsForm.tsx
  packages/console/src/pages/UserDetails/components/UserSettings.tsx
  packages/phrases/src/locales/de/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/de/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
Labels: enhancement, size/m

#2607 refactor(core): refactor the user account verification
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/core/src/routes/interaction/index.test.ts
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/utils/index.ts
  packages/core/src/routes/interaction/utils/interaction.test.ts
  packages/core/src/routes/interaction/utils/interaction.ts
  packages/core/src/routes/interaction/verifications/identifier-payload-verification.ts
  packages/core/src/routes/interaction/verifications/profile-verification.ts
  packages/core/src/routes/interaction/verifications/user-identity-verification.test.ts
  packages/core/src/routes/interaction/verifications/user-identity-verification.ts
Labels: enhancement, size/l

#2610 fix: should block add of social connector when original target and platform exists
  packages/core/src/routes/connector.test.ts
  packages/core/src/routes/connector.ts
Labels: bugfix, size/s

#2617 refactor(console): support small-size `CopyToClipBoard`
  packages/console/src/components/CopyToClipboard/index.module.scss
  packages/console/src/components/CopyToClipboard/index.tsx
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/UserDetails/index.tsx
Labels: enhancement, size/s

#2628 style(console): fix dropdown title text ellipsis
  packages/console/src/components/Select/index.module.scss
  packages/console/src/components/Select/index.tsx
Labels: size/xs

#2629 style(console): add radio groups margin-top on the sie branding page
  packages/console/src/pages/SignInExperience/tabs/Branding/BrandingForm.tsx
  packages/console/src/pages/SignInExperience/tabs/index.module.scss
Labels: size/xs

#2627 refactor(console): support close modal on `esc` pressed
  packages/console/src/components/AppContent/components/Sidebar/components/Contact/index.tsx
  packages/console/src/components/ConfirmModal/index.tsx
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/Connectors/components/CreateForm/index.tsx
  packages/console/src/pages/Settings/components/ChangePassword.tsx
  packages/console/src/pages/SignInExperience/components/Welcome/GuideModal.tsx
  packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/index.tsx
  packages/console/src/pages/UserDetails/components/CreateSuccess.tsx
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/pages/Users/index.tsx
  packages/ui/src/components/ConfirmModal/AcModal.tsx
  packages/ui/src/components/ConfirmModal/MobileModal.tsx
Labels: enhancement, size/s

#2630 refactor(console): `TabNavItem` props type
  packages/console/src/components/TabNav/TabNavItem.tsx
Labels: enhancement, size/s

#2632 chore: fix typos and errors in i18n phrases
  packages/console/src/pages/Connectors/components/ConnectorForm/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/connectors.ts
  packages/phrases/src/locales/en/translation/admin-console/connectors.ts
  packages/phrases/src/locales/fr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/ko/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/connectors.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/connectors.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
Labels: chore, size/s

#2634 style(console): update link styles in markdown contents
  packages/console/src/components/Markdown/index.module.scss
Labels: size/s

#2635 style(console): add border to the color block of `ColorPicker`
  packages/console/src/components/ColorPicker/index.module.scss
Labels: size/xs

#2638 refactor(console): remove unnecessary required tag
  packages/console/src/pages/ConnectorDetails/components/SenderTester/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorForm/index.tsx
Labels: enhancement, size/xs

#2640 fix(console): navigate to the details page on connector created
  packages/console/src/pages/Connectors/components/Guide/index.tsx
Labels: bugfix, size/xs

#2636 refactor(console): add a11y to the `SenderTester`
  packages/console/src/pages/ConnectorDetails/components/SenderTester/index.tsx
  packages/console/src/utilities/a11y.ts
Labels: enhancement, size/s

#2643 refactor(core): sort users data by `createdAt`
  packages/core/src/queries/user.test.ts
  packages/core/src/queries/user.ts
Labels: enhancement, size/xs

#2653 refactor(console): add another button
  packages/console/src/assets/images/circle-plus.svg
  packages/console/src/components/Button/index.module.scss
  packages/console/src/components/MultiTextInput/index.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SignInMethodEditBox/AddButton.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SocialConnectorEditBox/AddButton.tsx
  packages/phrases/src/locales/de/translation/admin-console/application-details.ts
  packages/phrases/src/locales/de/translation/admin-console/general.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/general.ts
  packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/general.ts
  packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
Labels: enhancement, size/s

#2641 fix(console): align the preview background color with the ui page
  packages/console/src/pages/SignInExperience/components/Preview/index.tsx
Labels: bugfix, size/xs

#2637 fix(console): remove sync profile field for non-social connector
  packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx
  packages/console/src/pages/Connectors/components/ConnectorForm/index.tsx
  packages/console/src/pages/Connectors/components/Guide/index.tsx
Labels: bugfix, size/s

#2659 fix(ui): forget pwd should be enabled correctly
  .changeset/neat-snakes-smash.md
  .changeset/pre.json
  packages/console/CHANGELOG.md
  packages/console/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/integration-tests/CHANGELOG.md
  packages/integration-tests/package.json
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/hooks/use-sie.ts
Labels: bugfix, size/s

#2648 chore: upgrade packages
  packages/cli/package.json
  packages/console/package.json
  packages/core/package.json
  packages/core/src/env-set/dot-env.ts
  packages/integration-tests/package.json
  packages/shared/package.json
  packages/shared/src/utils/find-package.ts
  pnpm-lock.yaml
Labels: chore, size/s

#2662 ci: fix codecov master workflow
  .github/workflows/master-codecov-report.yml
Labels: size/xs

#2656 fix: correct error messages
  packages/core/src/routes/connector.ts
  packages/phrases/src/locales/de/errors.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko/errors.ts
  packages/phrases/src/locales/pt-br/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
Labels: bugfix, size/s

#2661 refactor(console): keep pagination when the table is loading
  packages/console/src/components/AuditLogTable/index.tsx
  packages/console/src/components/Pagination/index.tsx
  packages/console/src/hooks/use-cache-value.ts
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/Users/index.tsx
Labels: enhancement, size/s

#2639 feat(core)!: enhanced user search params
  packages/console/src/pages/Users/index.tsx
  packages/core/nodemon.json
  packages/core/package.json
  packages/core/src/env-set/parameters.ts
  packages/core/src/lib/passcode.ts
  packages/core/src/lib/sign-in-experience/sign-in.ts
  packages/core/src/middleware/koa-auth.ts
  packages/core/src/middleware/koa-pagination.ts
  packages/core/src/queries/user.test.ts
  packages/core/src/queries/user.ts
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
  packages/core/src/routes/connector.ts
  packages/core/src/routes/interaction/utils/sign-in-experience-validation.ts
  packages/core/src/routes/sign-in-experience.ts
  packages/core/src/utils/search.test.ts
  packages/core/src/utils/search.ts
  packages/core/src/utils/test-utils.ts
  packages/core/src/utils/zod.ts
  packages/integration-tests/src/api/admin-user.ts
  packages/integration-tests/src/helpers.ts
  packages/integration-tests/src/tests/api/admin-user.search.test.ts
  packages/phrases/src/locales/de/errors.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko/errors.ts
  packages/phrases/src/locales/pt-br/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
  packages/schemas/src/types/index.ts
  packages/schemas/src/types/search.ts
Labels: feature, size/xl

#2668 refactor(schemas): add name index on users
  packages/schemas/alterations/next-1671039448-add-user-name-index.ts
  packages/schemas/tables/users.sql
Labels: enhancement, size/s

#2667 refactor(core): remove `query-string`
  packages/core/package.json
  packages/core/src/utils/pagination.ts
  pnpm-lock.yaml
Labels: enhancement, size/s

#2664 feat(test): add password and passcode identifier tests
  packages/integration-tests/package.json
  packages/integration-tests/src/api/connector.ts
  packages/integration-tests/src/api/interaction.ts
  packages/integration-tests/src/tests/api/admin-user.test.ts
  packages/integration-tests/src/tests/api/connector.test.ts
  packages/integration-tests/src/tests/api/session.test.ts
  packages/integration-tests/src/tests/api/social-session.test.ts
  packages/integration-tests/src/tests/interaction/sign-in-with-passcode-identifier.test.ts
  packages/integration-tests/src/tests/interaction/sign-in-with-password-identifier.test.ts
  packages/integration-tests/src/tests/interaction/utils/client.ts
  packages/integration-tests/src/tests/interaction/utils/connector.ts
  packages/integration-tests/src/tests/interaction/utils/sign-in-experience.ts
  packages/integration-tests/src/tests/interaction/utils/user.ts
Labels: feature, size/xl

#2654 refactor(console): add sie tab constants
  packages/console/src/App.tsx
  packages/console/src/consts/page-tabs.ts
  packages/console/src/pages/SignInExperience/index.tsx
Labels: enhancement, size/s

#2669 refactor(schemas): remove eslint in generate script
  packages/schemas/generate.sh
  packages/schemas/package.json
  packages/schemas/src/gen/schema.ts
Labels: enhancement, size/xs

#2666 fix: connector metadata update should be optional
  packages/core/src/routes/connector.ts
  packages/core/src/routes/connector.update.test.ts
  packages/integration-tests/src/tests/api/connector.test.ts
Labels: bugfix, size/s

#2665 refactor: replace `termsOfUse` with `termsOfUseUrl`
  packages/console/src/pages/SignInExperience/tabs/Others/TermsForm.tsx
  packages/console/src/pages/SignInExperience/utils/form.ts
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/libraries/sign-in-experience/index.test.ts
  packages/core/src/libraries/sign-in-experience/index.ts
  packages/core/src/queries/sign-in-experience.test.ts
  packages/core/src/routes/sign-in-experience.guard.test.ts
  packages/core/src/routes/sign-in-experience.test.ts
  packages/core/src/routes/sign-in-experience.ts
  packages/core/src/routes/well-known.test.ts
  packages/integration-tests/src/tests/api/sign-in-experience.test.ts
  packages/phrases/src/locales/de/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
  packages/schemas/alterations/next-1671080370-terms-of-use.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/seeds/sign-in-experience.ts
  packages/schemas/tables/sign_in_experiences.sql
  packages/ui/src/__mocks__/logto.tsx
  packages/ui/src/containers/TermsOfUse/TermsOfUseConfirmModalContent/index.tsx
  packages/ui/src/containers/TermsOfUse/index.tsx
  packages/ui/src/hooks/use-terms.ts
  packages/ui/src/utils/sign-in-experience.test.ts
Labels: enhancement, size/l

#2671 feat(test): add username, phone, email register integration test
  packages/integration-tests/src/tests/interaction/register-with-identifier.test.ts
  packages/integration-tests/src/tests/interaction/sign-in-with-passcode-identifier.test.ts
  packages/integration-tests/src/tests/interaction/sign-in-with-password-identifier.test.ts
  packages/integration-tests/src/tests/interaction/utils/client.ts
  packages/integration-tests/src/tests/interaction/utils/user.ts
Labels: feature, size/l

#2622 refactor(ui): add support for fullscreen profile layout
  packages/ui/src/App.tsx
  packages/ui/src/containers/AppBoundary/index.module.scss
  packages/ui/src/containers/AppBoundary/index.tsx
  packages/ui/src/containers/AppContent/index.module.scss
  packages/ui/src/containers/AppContent/index.tsx
  packages/ui/src/pages/Profile/index.tsx
  packages/ui/src/scss/normalized.scss
Labels: enhancement, size/l

#2642 refactor: add desktop and mobile views to render profile on different platforms
  packages/core/src/routes/profile.test.ts
  packages/core/src/routes/profile.ts
  packages/phrases-ui/src/locales/de.ts
  packages/phrases-ui/src/locales/en.ts
  packages/phrases-ui/src/locales/fr.ts
  packages/phrases-ui/src/locales/ko.ts
  packages/phrases-ui/src/locales/pt-br.ts
  packages/phrases-ui/src/locales/pt-pt.ts
  packages/phrases-ui/src/locales/tr-tr.ts
  packages/phrases-ui/src/locales/zh-cn.ts
  packages/schemas/src/types/user.ts
  packages/ui/src/apis/profile.ts
  packages/ui/src/assets/icons/arrow-next.svg
  packages/ui/src/assets/icons/nav-close.svg
  packages/ui/src/components/NavBar/index.module.scss
  packages/ui/src/components/NavBar/index.tsx
  packages/ui/src/pages/Profile/components/NavItem/index.module.scss
  packages/ui/src/pages/Profile/components/NavItem/index.tsx
  packages/ui/src/pages/Profile/containers/DesktopView/index.tsx
  packages/ui/src/pages/Profile/containers/MobileView/index.tsx
  packages/ui/src/pages/Profile/index.module.scss
  packages/ui/src/pages/Profile/index.tsx
Labels: enhancement, size/l

#2684 chore(phrases): improve Chinese translation
  packages/phrases/src/locales/zh-cn/errors.ts
Labels: chore, size/xs

#2658 chore: add social sign-in validation reference to interaction
  packages/core/src/libraries/social.ts
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/utils/social-verification.test.ts
  packages/core/src/routes/interaction/utils/social-verification.ts
  packages/core/src/routes/interaction/verifications/identifier-payload-verification.test.ts
  packages/core/src/routes/interaction/verifications/identifier-payload-verification.ts
  packages/core/src/routes/session/social.ts
  packages/core/src/routes/session/utils.ts
  packages/phrases/src/locales/de/errors.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko/errors.ts
  packages/phrases/src/locales/pt-br/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
  packages/toolkit/connector-kit/src/types.ts
Labels: chore, size/m

#2673 feat(test): add forgot pasword integration test
  packages/integration-tests/src/__mocks__/connectors-mock.ts
  packages/integration-tests/src/tests/interaction/forgot-password.test.ts
Labels: feature, size/m

#2692 fix(test): fix integration test
  packages/integration-tests/src/tests/api/interaction/forgot-password.test.ts
Labels: bugfix, size/xs

#2682 refactor: use default user avatar instead of founding team avatars
  packages/console/src/assets/avatars/avatar-001.png
  packages/console/src/assets/avatars/avatar-002.png
  packages/console/src/assets/avatars/avatar-003.png
  packages/console/src/assets/avatars/avatar-004.png
  packages/console/src/assets/avatars/avatar-005.png
  packages/console/src/assets/avatars/avatar-006.png
  packages/console/src/assets/avatars/avatar-007.png
  packages/console/src/assets/avatars/avatar-008.png
  packages/console/src/assets/avatars/avatar-009.png
  packages/console/src/assets/images/broken-image-dark.svg
  packages/console/src/assets/images/broken-image-light.svg
  packages/console/src/assets/images/default-avatar-dark.svg
  packages/console/src/assets/images/default-avatar-light.svg
  packages/console/src/components/AppContent/components/UserInfo/index.module.scss
  packages/console/src/components/AppContent/components/UserInfo/index.tsx
  packages/console/src/components/ImageWithErrorFallback/index.tsx
  packages/console/src/components/UserAvatar/index.tsx
  packages/console/src/consts/avatars.ts
  packages/console/src/consts/index.ts
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/pages/Users/index.tsx
Labels: enhancement, size/m

#2695 refactor: remove fs-extra
  packages/cli/package.json
  packages/cli/src/commands/connector/remove.ts
  packages/cli/src/commands/connector/utils.ts
  packages/cli/src/commands/database/alteration/utils.ts
  packages/cli/src/commands/install/utils.ts
  packages/core/package.json
  pnpm-lock.yaml
Labels: enhancement, size/s

#2681 refactor: log types 2
  packages/console/src/components/AuditLogTable/components/EventName/index.tsx
  packages/console/src/components/AuditLogTable/index.tsx
  packages/console/src/consts/logs.ts
  packages/console/src/pages/AuditLogDetails/index.tsx
  packages/core/src/middleware/koa-audit-log-legacy.test.ts
  packages/core/src/middleware/koa-audit-log-legacy.ts
  packages/core/src/middleware/koa-audit-log.test.ts
  packages/core/src/middleware/koa-audit-log.ts
  packages/core/src/queries/log.ts
  packages/core/src/routes/log.test.ts
  packages/core/src/routes/log.ts
  packages/integration-tests/src/tests/api/logs-legacy.test.ts
  packages/phrases/src/locales/de/translation/admin-console/log-details.ts
  packages/phrases/src/locales/en/translation/admin-console/log-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/log-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/log-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/log-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/log-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/log-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/log-details.ts
  packages/schemas/alterations/next-1671336831-refactor-log-types.ts
  packages/schemas/tables/logs.sql
Labels: enhancement, size/m

#2694 fix(console): use connector dark logo
  packages/console/src/components/ConnectorLogo/index.tsx
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorName/index.tsx
  packages/console/src/pages/Connectors/components/CreateForm/index.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SocialConnectorEditBox/AddButton.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SocialConnectorEditBox/SelectedConnectorItem.tsx
Labels: bugfix, size/s

#2690 refactor(console): add routes for create modals
  packages/console/src/App.tsx
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/Users/index.tsx
Labels: enhancement, size/m

#2689 feat(console): add toggle tip for connector target field
  packages/console/src/pages/Connectors/components/ConnectorForm/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/connectors.ts
  packages/phrases/src/locales/en/translation/admin-console/connectors.ts
  packages/phrases/src/locales/fr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/ko/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/connectors.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/connectors.ts
Labels: feature, size/s

#2697 fix(console): `buildUserDetailsPathname`
  packages/console/src/pages/Users/index.tsx
Labels: bugfix, size/xs

#2693 chore: should clear connector session after getSession()
  packages/core/src/routes/session/utils.ts
Labels: chore, size/xs

#2691 chore: add changeset of connector-kit update
  .changeset/silly-rules-laugh.md
Labels: chore, size/xs

#2705 release: toolkit packages
  .changeset/pre.json
  packages/toolkit/connector-kit/CHANGELOG.md
  packages/toolkit/connector-kit/package.json
Labels: size/m

#2703 fix(console): table scrollbar on the applications page
  packages/console/src/components/Table/StickyHeaderTable.module.scss
  packages/console/src/components/Table/StickyHeaderTable.tsx
  packages/console/src/pages/Applications/index.tsx
Labels: bugfix, size/m

#2698 refactor(console): create user process
  packages/console/src/consts/index.ts
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/pages/Users/components/CreateForm/index.tsx
  packages/console/src/pages/Users/index.tsx
Labels: enhancement, size/m

#2683 feat: hooks schema and APIs
  .vscode/extensions.json
  .vscode/settings.json
  packages/cli/src/commands/database/seed/index.ts
  packages/core/package.json
  packages/core/src/env-set/create-query-client-by-env.ts
  packages/core/src/env-set/index.ts
  packages/core/src/routes/hook.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/swagger.ts
  packages/core/src/test-utils/query-client.ts
  packages/integration-tests/package.json
  packages/integration-tests/src/tests/api/hooks.test.ts
  packages/schemas/alterations/1.0.0_beta.10-1-logto-config.ts
  packages/schemas/alterations/1.0.0_beta.10-1663923211-machine-to-machine-app.ts
  packages/schemas/alterations/1.0.0_beta.10-1664265197-custom-phrases.ts
  packages/schemas/alterations/1.0.0_beta.11-1664347703-rename-language-key-to-tag.ts
  packages/schemas/alterations/1.0.0_beta.11-1664356000-add-created-at-column-to-users.ts
  packages/schemas/alterations/1.0.0_beta.11-1664462389-correct-user-created-at-column-by-user-logs.ts
  packages/schemas/alterations/1.0.0_beta.14-1665300135-sign-in-sign-up.ts
  packages/schemas/alterations/1.0.0_beta.14-1667283640-remove-forgot-password.ts
  packages/schemas/alterations/1.0.0_beta.14-1667292082-remove-sign-in-method.ts
  packages/schemas/alterations/1.0.0_beta.14-1667374974-user-suspend.ts
  packages/schemas/alterations/1.0.0_beta.14-1667900481-add-passcode-type-continue.ts
  packages/schemas/alterations/next-1668666590-support-multiple-connector-instances.ts
  packages/schemas/alterations/next-1668666600-remove-connector-enabled.ts
  packages/schemas/alterations/next-1669091623-roles-and-scopes.ts
  packages/schemas/alterations/next-1669702299-sign-up.ts
  packages/schemas/alterations/next-1671039448-add-user-name-index.ts
  packages/schemas/alterations/next-1671080370-terms-of-use.ts
  packages/schemas/alterations/next-1671509870-hooks.ts
  packages/schemas/package.json
  packages/schemas/src/models/hooks.ts
  packages/schemas/src/models/index.ts
  pnpm-lock.yaml
Labels: feature, size/l

#2699 chore: response of connector POST API should be ConnectorResponse
  packages/core/src/routes/connector.test.ts
  packages/core/src/routes/connector.ts
Labels: chore, size/s

#2709 chore(deps): upgrade prettier to v2.8.1
  packages/cli/package.json
  packages/console/package.json
  packages/core/package.json
  packages/demo-app/package.json
  packages/integration-tests/package.json
  packages/phrases-ui/package.json
  packages/phrases/package.json
  packages/schemas/package.json
  packages/shared/package.json
  packages/toolkit/connector-kit/package.json
  packages/toolkit/core-kit/package.json
  packages/toolkit/language-kit/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: chore, size/s

#2712 release: skip download pptr in dockerfile
  Dockerfile
Labels: size/xs

#2700 fix(test): update interaction integration test
  packages/core/src/routes/interaction/index.test.ts
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/types/guard.ts
  packages/core/src/routes/interaction/verifications/identifier-payload-verification.test.ts
  packages/integration-tests/src/api/interaction.ts
  packages/integration-tests/src/client/index.ts
  packages/integration-tests/src/helpers.ts
  packages/integration-tests/src/tests/api/audit-logs/index.test.ts
  packages/integration-tests/src/tests/api/get-access-token.test.ts
  packages/integration-tests/src/tests/api/interaction/forgot-password.test.ts
  packages/integration-tests/src/tests/api/interaction/register-with-identifier.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-passcode-identifier.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier.test.ts
  packages/integration-tests/src/tests/api/interaction/social-interaction.test.ts
  packages/integration-tests/src/tests/api/interaction/utils/client.ts
  packages/integration-tests/src/tests/api/interaction/utils/connector.ts
  packages/integration-tests/src/utils.ts
  packages/schemas/src/types/interactions.ts
Labels: bugfix, size/xl

#2686 refactor(core): refactor interaction API
  packages/core/src/routes/interaction/actions/submit-interaction.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/core/src/routes/interaction/index.test.ts
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/middleware/koa-interaction-body-guard.test.ts
  packages/core/src/routes/interaction/middleware/koa-interaction-body-guard.ts
  packages/core/src/routes/interaction/middleware/koa-session-sign-in-experience-guard.ts
  packages/core/src/routes/interaction/middleware/koa-session-sign-inexperience-guard.test.ts
  packages/core/src/routes/interaction/types/guard.ts
  packages/core/src/routes/interaction/types/index.ts
  packages/core/src/routes/interaction/utils/interaction.test.ts
  packages/core/src/routes/interaction/utils/interaction.ts
  packages/core/src/routes/interaction/utils/sign-in-experience-valiation.test.ts
  packages/core/src/routes/interaction/utils/sign-in-experience-validation.ts
  packages/core/src/routes/interaction/verifications/identifier-payload-verification.test.ts
  packages/core/src/routes/interaction/verifications/identifier-payload-verification.ts
  packages/core/src/routes/interaction/verifications/identifier-verification.test.ts
  packages/core/src/routes/interaction/verifications/identifier-verification.ts
  packages/core/src/routes/interaction/verifications/index.ts
  packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.test.ts
  packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.ts
  packages/core/src/routes/interaction/verifications/profile-verification-forgot-password.test.ts
  packages/core/src/routes/interaction/verifications/profile-verification-profile-exist.test.ts
  packages/core/src/routes/interaction/verifications/profile-verification-profile-registered.test.ts
  packages/core/src/routes/interaction/verifications/profile-verification-protected-identifier.test.ts
  packages/core/src/routes/interaction/verifications/profile-verification.ts
  packages/core/src/routes/interaction/verifications/user-identity-verification.test.ts
  packages/core/src/routes/interaction/verifications/user-identity-verification.ts
  packages/integration-tests/src/api/interaction.ts
  packages/integration-tests/src/client/index.ts
  packages/integration-tests/src/helpers.ts
  packages/integration-tests/src/tests/api/audit-logs/index.test.ts
  packages/integration-tests/src/tests/api/get-access-token.test.ts
  packages/integration-tests/src/tests/api/interaction/forgot-password.test.ts
  packages/integration-tests/src/tests/api/interaction/register-with-identifier.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-passcode-identifier.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier.test.ts
  packages/integration-tests/src/tests/api/interaction/social-interaction.test.ts
  packages/integration-tests/src/tests/api/interaction/utils/client.ts
  packages/integration-tests/src/tests/api/interaction/utils/connector.ts
  packages/integration-tests/src/utils.ts
  packages/phrases/src/locales/de/errors.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko/errors.ts
  packages/phrases/src/locales/pt-br/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
  packages/schemas/src/types/interactions.ts
Labels: enhancement, size/xl

#2708 fix: svg rendering issue and add ui tests
  .github/workflows/integration-test.yml
  .github/workflows/main.yml
  packages/console/svgo.config.json
  packages/integration-tests/jest.config.ui.js
  packages/integration-tests/src/tests/api/session.test.ts
  packages/integration-tests/src/tests/ui/smoke.test.ts
Labels: bugfix, size/s

#2714 chore: fix typo in i18n phrase key
  packages/console/src/pages/Connectors/components/ConnectorForm/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/connectors.ts
  packages/phrases/src/locales/en/translation/admin-console/connectors.ts
  packages/phrases/src/locales/fr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/ko/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/connectors.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/connectors.ts
Labels: chore, size/s

#2715 refactor: remove lodash
  packages/cli/package.json
  packages/console/package.json
  packages/console/src/components/AppContent/components/Sidebar/utils.ts
  packages/console/src/components/Button/index.tsx
  packages/console/src/pages/SignInExperience/components/SignUpAndSignInChangePreview/SignUpAndSignInDiffSection/SignInDiffSection.tsx
  packages/console/src/pages/SignInExperience/components/SignUpAndSignInChangePreview/SignUpAndSignInDiffSection/SignUpDiffSection.tsx
  packages/core/package.json
  packages/core/src/__mocks__/user.ts
  packages/core/src/errors/RequestError/index.ts
  packages/core/src/middleware/koa-audit-log-legacy.ts
  packages/core/src/middleware/koa-audit-log.ts
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
  packages/core/src/routes/profile.ts
  packages/core/src/routes/session/social.ts
  packages/integration-tests/package.json
  packages/integration-tests/src/client/index.ts
  packages/phrases-ui/package.json
  packages/phrases/package.json
  packages/schemas/package.json
  packages/schemas/src/gen/index.ts
  packages/shared/package.json
  packages/toolkit/connector-kit/package.json
  packages/toolkit/core-kit/package.json
  packages/ui/jest.config.ts
  packages/ui/package.json
  pnpm-lock.yaml
Labels: enhancement, size/s

#2721 refactor: check alteration timestamp when seed database
  packages/cli/src/commands/database/alteration/utils.ts
  packages/cli/src/commands/database/seed/index.ts
Labels: enhancement, size/s

#2720 test: sleep 1s before each case to improve ui test stability
  packages/integration-tests/src/tests/ui/smoke.test.ts
Labels: testing, size/xs

#2722 refactor: improve typing in RadioGroup component
  packages/console/src/components/RadioGroup/index.tsx
Labels: enhancement, size/s

#2717 refactor(console): checkbox component
  packages/console/src/assets/images/check-box-selected-dark.svg
  packages/console/src/assets/images/check-box-selected-disabled-dark.svg
  packages/console/src/assets/images/check-box-selected-disabled.svg
  packages/console/src/assets/images/check-box-selected.svg
  packages/console/src/assets/images/check-box-unselected-dark.svg
  packages/console/src/assets/images/check-box-unselected-disabled-dark.svg
  packages/console/src/assets/images/check-box-unselected-disabled.svg
  packages/console/src/assets/images/check-box-unselected.svg
  packages/console/src/components/Checkbox/Icon.tsx
  packages/console/src/components/Checkbox/index.module.scss
  packages/console/src/components/Checkbox/index.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/SignUpForm.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SignInMethodEditBox/SignInMethodItem.tsx
  packages/toolkit/core-kit/scss/_console-themes.scss
Labels: enhancement, size/l

#2578 chore(phrases): translate untranslated pharses to ko-kr
  packages/phrases-ui/src/locales/ko.ts
  packages/phrases/src/locales/ko/errors.ts
  packages/phrases/src/locales/ko/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/applications.ts
  packages/phrases/src/locales/ko/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/connectors.ts
  packages/phrases/src/locales/ko/translation/admin-console/general.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/ko/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/ko/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ko/translation/demo-app.ts
Labels: chore, size/l

#2706 refactor: move assign/get connector session to interaction path
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/utils/interaction.ts
  packages/core/src/routes/interaction/verifications/identifier-payload-verification.ts
  packages/core/src/routes/session/social.ts
  packages/core/src/routes/session/utils.ts
Labels: enhancement, size/s

#2707 refactor(core): refactor createSocialAuthorizationUrl and verifySocialIdentity
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/utils/social-verification.test.ts
  packages/core/src/routes/interaction/utils/social-verification.ts
  packages/core/src/routes/interaction/verifications/identifier-payload-verification.test.ts
  packages/core/src/routes/interaction/verifications/identifier-payload-verification.ts
Labels: enhancement, size/s

#2726 fix(console): tooltip should point to box center of the checkbox
  packages/console/src/components/Checkbox/index.module.scss
  packages/console/src/components/Checkbox/index.tsx
Labels: bugfix, size/s

#2728 fix(console): checkbox label should not wrap
  packages/console/src/components/Checkbox/index.module.scss
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SignInMethodEditBox/index.module.scss
Labels: bugfix, size/xs

#2704 feat(core): interaction hooks
  packages/core/package.json
  packages/core/src/env-set/index.ts
  packages/core/src/event-listeners/grant.ts
  packages/core/src/index.ts
  packages/core/src/libraries/hook.test.ts
  packages/core/src/libraries/hook.ts
  packages/core/src/model-routers/index.ts
  packages/core/src/queries/log.ts
  packages/core/src/routes/hook.ts
  packages/core/src/routes/interaction/index.test.ts
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/middleware/koa-interaction-details.ts
  packages/core/src/routes/interaction/middleware/koa-interaction-hooks.ts
  packages/core/src/routes/interaction/middleware/koa-interaction-sie.ts
  packages/core/src/routes/interaction/utils/interaction.ts
  packages/core/src/routes/interaction/utils/sign-in-experience-validation.ts
  packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.test.ts
  packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.ts
  packages/core/src/routes/types.ts
  packages/schemas/src/models/hooks.ts
  packages/schemas/src/types/log/hook.ts
  packages/schemas/src/types/log/index.ts
  packages/schemas/src/types/log/token.ts
  packages/shared/src/utils/function.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#2718 refactor: rename interaction `Event` -> `InteractionEvent`
  packages/core/src/libraries/hook.test.ts
  packages/core/src/libraries/hook.ts
  packages/core/src/routes/interaction/actions/submit-interaction.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/core/src/routes/interaction/index.test.ts
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/types/guard.ts
  packages/core/src/routes/interaction/types/index.ts
  packages/core/src/routes/interaction/utils/interaction.ts
  packages/core/src/routes/interaction/utils/passcode-validation.test.ts
  packages/core/src/routes/interaction/utils/passcode-validation.ts
  packages/core/src/routes/interaction/utils/sign-in-experience-valiation.test.ts
  packages/core/src/routes/interaction/utils/sign-in-experience-validation.ts
  packages/core/src/routes/interaction/verifications/identifier-payload-verification.test.ts
  packages/core/src/routes/interaction/verifications/identifier-payload-verification.ts
  packages/core/src/routes/interaction/verifications/identifier-verification.test.ts
  packages/core/src/routes/interaction/verifications/identifier-verification.ts
  packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.test.ts
  packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.ts
  packages/core/src/routes/interaction/verifications/profile-verification-forgot-password.test.ts
  packages/core/src/routes/interaction/verifications/profile-verification-profile-exist.test.ts
  packages/core/src/routes/interaction/verifications/profile-verification-profile-registered.test.ts
  packages/core/src/routes/interaction/verifications/profile-verification-protected-identifier.test.ts
  packages/core/src/routes/interaction/verifications/profile-verification.ts
  packages/core/src/routes/interaction/verifications/user-identity-verification.test.ts
  packages/integration-tests/src/api/interaction.ts
  packages/integration-tests/src/tests/api/audit-logs/index.test.ts
  packages/integration-tests/src/tests/api/interaction/forgot-password.test.ts
  packages/integration-tests/src/tests/api/interaction/register-with-identifier.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-passcode-identifier.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier.test.ts
  packages/integration-tests/src/tests/api/interaction/social-interaction.test.ts
  packages/schemas/src/types/interactions.ts
  packages/schemas/src/types/log/interaction.ts
Labels: enhancement, size/l

#2724 test: add integration tests for interaction hooks
  packages/core/src/app/init.test.ts
  packages/core/src/libraries/hook.test.ts
  packages/core/src/libraries/hook.ts
  packages/core/src/middleware/koa-audit-log.test.ts
  packages/core/src/middleware/koa-audit-log.ts
  packages/core/src/routes/interaction/index.test.ts
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/middleware/koa-interaction-hooks.ts
  packages/integration-tests/jest.setup.js
  packages/integration-tests/src/helpers.ts
  packages/integration-tests/src/tests/api/audit-logs/index.test.ts
  packages/integration-tests/src/tests/api/hooks.test.ts
  packages/integration-tests/src/utils.ts
  packages/shared/src/utils/function.test.ts
  packages/shared/src/utils/function.ts
Labels: testing, size/l

#2729 fix(console): set min-width to left control panel in SIE
  packages/console/src/pages/SignInExperience/index.module.scss
Labels: bugfix, size/xs

#2727 refactor(console): add create route for connectors page
  packages/console/src/App.tsx
  packages/console/src/consts/page-tabs.ts
  packages/console/src/pages/ConnectorDetails/components/ConnectorTabs/index.tsx
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorName/index.module.scss
  packages/console/src/pages/Connectors/components/ConnectorName/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorRow/index.tsx
  packages/console/src/pages/Connectors/components/Guide/index.tsx
  packages/console/src/pages/Connectors/index.tsx
  packages/console/src/pages/GetStarted/hook.ts
Labels: enhancement, size/m

#2710 feat(test): add fulfill user profile integration tests
  packages/core/src/routes/interaction/index.test.ts
  packages/core/src/routes/interaction/index.ts
  packages/integration-tests/src/api/interaction.ts
  packages/integration-tests/src/tests/api/interaction/forgot-password.test.ts
  packages/integration-tests/src/tests/api/interaction/register-with-identifier.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-passcode-identifier.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier.test.ts
  packages/integration-tests/src/tests/api/interaction/social-interaction.test.ts
  packages/integration-tests/src/tests/api/interaction/utils/sign-in-experience.ts
Labels: feature, size/xl

#2734 chore(console): update wording in get-started subtitle
  packages/phrases/src/locales/en/translation/admin-console/get-started.ts
Labels: chore, size/xs

#2735 fix(console): use `getSafe` on the sie page
  packages/console/src/pages/SignInExperience/components/SignUpAndSignInChangePreview/SignUpAndSignInDiffSection/SignInDiffSection.tsx
  packages/console/src/pages/SignInExperience/components/SignUpAndSignInChangePreview/SignUpAndSignInDiffSection/SignUpDiffSection.tsx
Labels: bugfix, size/s

#2737 fix(core): should block POST of non-standard social connectors with conflicting `target`
  packages/core/src/routes/connector.test.ts
  packages/core/src/routes/connector.ts
Labels: bugfix, size/s

#2736 refactor(console): add space to learn more links
  packages/console/src/components/FormCard/index.module.scss
  packages/console/src/components/FormCard/index.tsx
Labels: enhancement, size/s

#2739 refactor!: align `PasscodeType` to `MessageTypes`
  packages/core/src/__mocks__/index.ts
  packages/core/src/connectors/types.ts
  packages/core/src/libraries/passcode.test.ts
  packages/core/src/libraries/passcode.ts
  packages/core/src/queries/passcode.test.ts
  packages/core/src/queries/passcode.ts
  packages/core/src/routes/interaction/utils/passcode-validation.test.ts
  packages/core/src/routes/interaction/utils/passcode-validation.ts
  packages/core/src/routes/session/continue.test.ts
  packages/core/src/routes/session/forgot-password.test.ts
  packages/core/src/routes/session/middleware/passwordless-action.ts
  packages/core/src/routes/session/passwordless.test.ts
  packages/core/src/routes/session/passwordless.ts
  packages/core/src/routes/session/types.ts
  packages/core/src/routes/session/utils.ts
  packages/integration-tests/package.json
  packages/integration-tests/src/api/session.ts
  packages/schemas/alterations/next-1672119200-align-passcode-type-with-message-type.ts
  packages/schemas/tables/passcodes.sql
  packages/ui/package.json
  packages/ui/src/apis/continue.test.ts
  packages/ui/src/apis/continue.ts
  packages/ui/src/apis/forgot-password.ts
  packages/ui/src/apis/index.test.ts
  packages/ui/src/apis/register.ts
  packages/ui/src/apis/sign-in.ts
  pnpm-lock.yaml
Labels: enhancement, size/l

#2730 refactor(ui): replace the password sign-in api
  packages/ui/src/apis/index.test.ts
  packages/ui/src/apis/interaction.ts
  packages/ui/src/apis/sign-in.ts
  packages/ui/src/containers/EmailPassword/index.test.tsx
  packages/ui/src/containers/EmailPassword/index.tsx
  packages/ui/src/containers/PasswordSignInForm/index.test.tsx
  packages/ui/src/containers/PasswordSignInForm/index.tsx
  packages/ui/src/containers/PhonePassword/index.test.tsx
  packages/ui/src/containers/PhonePassword/index.tsx
  packages/ui/src/containers/UsernameSignIn/index.test.tsx
  packages/ui/src/containers/UsernameSignIn/index.tsx
  packages/ui/src/hooks/use-password-sign-in.ts
Labels: enhancement, size/l

#2731 refactor(ui): refactor username password register flow
  packages/core/src/middleware/koa-audit-log.ts
  packages/core/src/routes/interaction/actions/submit-interaction.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/core/src/routes/interaction/types/guard.ts
  packages/core/src/routes/interaction/types/index.ts
  packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.test.ts
  packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.ts
  packages/core/src/routes/interaction/verifications/profile-verification-profile-registered.test.ts
  packages/core/src/routes/interaction/verifications/profile-verification.ts
  packages/ui/src/apis/index.test.ts
  packages/ui/src/apis/interaction.ts
  packages/ui/src/apis/register.ts
  packages/ui/src/containers/CreateAccount/index.test.tsx
  packages/ui/src/containers/CreateAccount/index.tsx
  packages/ui/src/containers/UsernameForm/UsernameRegister/index.test.tsx
  packages/ui/src/containers/UsernameForm/UsernameRegister/use-username-register.ts
  packages/ui/src/pages/PasswordRegisterWithUsername/index.test.tsx
  packages/ui/src/pages/PasswordRegisterWithUsername/index.tsx
  packages/ui/src/pages/PasswordRegisterWithUsername/use-username-password-register.ts
Labels: enhancement, size/l

#2740 chore(phrases,core): change 'passcode' to 'verification code' in content
  packages/core/src/libraries/passcode.test.ts
  packages/core/src/libraries/passcode.ts
  packages/core/src/routes/session/forgot-password.test.ts
  packages/core/src/routes/session/passwordless.test.ts
  packages/phrases/src/locales/de/errors.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko/errors.ts
  packages/phrases/src/locales/pt-br/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
  packages/ui/src/containers/PasscodeValidation/use-shared-error-handler.ts
Labels: chore, size/m

#2743 refactor(ui): replace all passcode verification flow with latest interaction API
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/verifications/user-identity-verification.test.ts
  packages/core/src/routes/interaction/verifications/user-identity-verification.ts
  packages/ui/src/apis/continue.test.ts
  packages/ui/src/apis/continue.ts
  packages/ui/src/apis/forgot-password.ts
  packages/ui/src/apis/index.test.ts
  packages/ui/src/apis/interaction.ts
  packages/ui/src/apis/register.ts
  packages/ui/src/apis/sign-in.ts
  packages/ui/src/apis/utils.ts
  packages/ui/src/containers/EmailForm/EmailContinue.test.tsx
  packages/ui/src/containers/EmailForm/EmailForm.test.tsx
  packages/ui/src/containers/EmailForm/EmailForm.tsx
  packages/ui/src/containers/EmailForm/EmailRegister.test.tsx
  packages/ui/src/containers/EmailForm/EmailResetPassword.test.tsx
  packages/ui/src/containers/EmailForm/EmailSignIn.test.tsx
  packages/ui/src/containers/PasscodeValidation/index.test.tsx
  packages/ui/src/containers/PasscodeValidation/use-continue-set-email-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/use-continue-set-sms-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/use-forgot-password-email-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/use-forgot-password-sms-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/use-register-with-email-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/use-register-with-sms-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/use-resend-passcode.ts
  packages/ui/src/containers/PasscodeValidation/use-sign-in-with-email-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/use-sign-in-with-sms-passcode-validation.ts
  packages/ui/src/containers/PasswordSignInForm/PasswordlessSignInLink.tsx
  packages/ui/src/containers/PasswordSignInForm/index.test.tsx
  packages/ui/src/containers/PhoneForm/PhoneForm.test.tsx
  packages/ui/src/containers/PhoneForm/PhoneForm.tsx
  packages/ui/src/containers/PhoneForm/SmsContinue.test.tsx
  packages/ui/src/containers/PhoneForm/SmsRegister.test.tsx
  packages/ui/src/containers/PhoneForm/SmsResetPassword.test.tsx
  packages/ui/src/containers/PhoneForm/SmsSignIn.test.tsx
  packages/ui/src/hooks/use-continue-sign-in-with-password.ts
  packages/ui/src/hooks/use-passwordless-send-code.ts
  packages/ui/src/pages/PasswordRegisterWithUsername/use-username-password-register.ts
  packages/ui/src/pages/ResetPassword/index.test.tsx
  packages/ui/src/pages/ResetPassword/use-reset-password.ts
  packages/ui/src/pages/SecondaryRegister/index.test.tsx
  packages/ui/src/pages/SecondarySignIn/index.test.tsx
Labels: enhancement, size/xl

#2742 refactor(core): remove the event from sendPasscode API payload
  packages/core/src/routes/interaction/index.test.ts
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/types/guard.ts
  packages/core/src/routes/interaction/utils/passcode-validation.test.ts
  packages/core/src/routes/interaction/utils/passcode-validation.ts
  packages/core/src/routes/interaction/verifications/user-identity-verification.test.ts
  packages/core/src/routes/interaction/verifications/user-identity-verification.ts
  packages/integration-tests/src/api/interaction.ts
  packages/integration-tests/src/tests/api/interaction/forgot-password.test.ts
  packages/integration-tests/src/tests/api/interaction/register-with-identifier.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-passcode-identifier.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier.test.ts
  packages/ui/src/apis/continue.test.ts
  packages/ui/src/apis/continue.ts
  packages/ui/src/apis/forgot-password.ts
  packages/ui/src/apis/index.test.ts
  packages/ui/src/apis/interaction.ts
  packages/ui/src/apis/register.ts
  packages/ui/src/apis/sign-in.ts
  packages/ui/src/apis/utils.ts
  packages/ui/src/containers/EmailForm/EmailContinue.test.tsx
  packages/ui/src/containers/EmailForm/EmailForm.test.tsx
  packages/ui/src/containers/EmailForm/EmailForm.tsx
  packages/ui/src/containers/EmailForm/EmailRegister.test.tsx
  packages/ui/src/containers/EmailForm/EmailResetPassword.test.tsx
  packages/ui/src/containers/EmailForm/EmailSignIn.test.tsx
  packages/ui/src/containers/PasscodeValidation/index.test.tsx
  packages/ui/src/containers/PasscodeValidation/use-continue-set-email-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/use-continue-set-sms-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/use-forgot-password-email-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/use-forgot-password-sms-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/use-register-with-email-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/use-register-with-sms-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/use-resend-passcode.ts
  packages/ui/src/containers/PasscodeValidation/use-sign-in-with-email-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/use-sign-in-with-sms-passcode-validation.ts
  packages/ui/src/containers/PasswordSignInForm/PasswordlessSignInLink.tsx
  packages/ui/src/containers/PasswordSignInForm/index.test.tsx
  packages/ui/src/containers/PhoneForm/PhoneForm.test.tsx
  packages/ui/src/containers/PhoneForm/PhoneForm.tsx
  packages/ui/src/containers/PhoneForm/SmsContinue.test.tsx
  packages/ui/src/containers/PhoneForm/SmsRegister.test.tsx
  packages/ui/src/containers/PhoneForm/SmsResetPassword.test.tsx
  packages/ui/src/containers/PhoneForm/SmsSignIn.test.tsx
  packages/ui/src/hooks/use-continue-sign-in-with-password.ts
  packages/ui/src/hooks/use-passwordless-send-code.ts
  packages/ui/src/pages/PasswordRegisterWithUsername/use-username-password-register.ts
  packages/ui/src/pages/ResetPassword/index.test.tsx
  packages/ui/src/pages/ResetPassword/use-reset-password.ts
  packages/ui/src/pages/SecondaryRegister/index.test.tsx
  packages/ui/src/pages/SecondarySignIn/index.test.tsx
Labels: enhancement, size/xl

#2733 test: improve ui test stability
  packages/integration-tests/src/tests/ui/smoke.test.ts
Labels: testing, size/s

#2660 refactor(console): update loading skeletons
  packages/console/src/components/DetailsSkeleton/index.module.scss
  packages/console/src/components/DetailsSkeleton/index.tsx
  packages/console/src/pages/SignInExperience/components/Skeleton/index.module.scss
  packages/console/src/pages/SignInExperience/components/Skeleton/index.tsx
Labels: enhancement, size/l, stale

#2745 refactor: rename `MessageTypes` -> `VerificationCodeType`
  packages/core/src/__mocks__/index.ts
  packages/core/src/connectors/types.ts
  packages/core/src/libraries/passcode.test.ts
  packages/core/src/libraries/passcode.ts
  packages/core/src/queries/passcode.test.ts
  packages/core/src/queries/passcode.ts
  packages/core/src/routes/connector.test.ts
  packages/core/src/routes/connector.ts
  packages/core/src/routes/interaction/utils/passcode-validation.test.ts
  packages/core/src/routes/interaction/utils/passcode-validation.ts
  packages/core/src/routes/session/continue.test.ts
  packages/core/src/routes/session/forgot-password.test.ts
  packages/core/src/routes/session/middleware/passwordless-action.ts
  packages/core/src/routes/session/passwordless.test.ts
  packages/core/src/routes/session/passwordless.ts
  packages/core/src/routes/session/types.ts
  packages/core/src/routes/session/utils.ts
  packages/integration-tests/src/api/session.ts
  packages/toolkit/connector-kit/src/types.ts
Labels: enhancement, size/l

#2744 refactor(ui): replace continue api with patchProfile
  packages/core/src/routes/interaction/verifications/user-identity-verification.test.ts
  packages/core/src/routes/interaction/verifications/user-identity-verification.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/pt-br/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
  packages/ui/src/apis/continue.test.ts
  packages/ui/src/apis/continue.ts
  packages/ui/src/apis/interaction.ts
  packages/ui/src/containers/PasscodeValidation/use-continue-set-email-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/use-continue-set-sms-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/use-forgot-password-email-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/use-forgot-password-sms-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/use-identifier-error-alert.ts
  packages/ui/src/containers/PasscodeValidation/use-sign-in-with-email-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/use-sign-in-with-sms-passcode-validation.ts
  packages/ui/src/containers/UsernameForm/SetUsername/index.test.tsx
  packages/ui/src/containers/UsernameForm/SetUsername/use-set-username.ts
  packages/ui/src/hooks/use-required-profile-error-handler.ts
  packages/ui/src/pages/Continue/SetPassword/index.test.tsx
  packages/ui/src/pages/Continue/SetPassword/use-set-password.ts
  packages/ui/src/pages/Continue/SetUsername/index.test.tsx
  packages/ui/src/types/guard.ts
Labels: enhancement, size/l

#2751 refactor(ui): replace social flow api
  packages/core/src/utils/format.test.ts
  packages/core/src/utils/format.ts
  packages/ui/src/apis/index.test.ts
  packages/ui/src/apis/interaction.ts
  packages/ui/src/apis/social.ts
  packages/ui/src/apis/utils.ts
  packages/ui/src/containers/SocialCreateAccount/index.test.tsx
  packages/ui/src/containers/SocialCreateAccount/index.tsx
  packages/ui/src/hooks/use-bind-social.ts
  packages/ui/src/hooks/use-social-sign-in-listener.ts
  packages/ui/src/hooks/use-social.ts
  packages/ui/src/pages/SocialSignInCallback/index.test.tsx
  packages/ui/src/types/guard.ts
Labels: enhancement, size/l

#2752 fix(ui): forgotpassword passcode verification page 404
  packages/core/src/routes/interaction/index.ts
  packages/ui/src/pages/Passcode/index.tsx
Labels: bugfix, size/xs

#2753 chore: update standard connector AC contents
  packages/console/src/pages/Connectors/components/ConnectorForm/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/connectors.ts
  packages/phrases/src/locales/en/translation/admin-console/connectors.ts
  packages/phrases/src/locales/fr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/ko/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/connectors.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/connectors.ts
Labels: chore, size/m

#2748 style(console): update select component style
  packages/console/src/components/Select/index.module.scss
  packages/console/src/pages/SignInExperience/components/Preview/index.module.scss
Labels: size/xs

#2749 fix(console): close deletion modal on connector changed
  packages/console/src/pages/ConnectorDetails/index.tsx
Labels: bugfix, size/xs

#2750 fix(console): close modal on tab changed on user details page
  packages/console/src/pages/UserDetails/index.tsx
Labels: bugfix, size/s

#2754 ci: update release workflows
  .github/workflows/changesets.yml
  .github/workflows/release.yml
  .scripts/merge-eslint-reports.js
  .scripts/packages-meta.js
  .scripts/publish.js
  commitlint.config.cjs
  lint-staged.config.js
  package.json
Labels: size/m

#2759 ci: fix workflows
  .github/workflows/changesets.yml
  .github/workflows/release.yml
Labels: size/s

#2765 fix: fix IT due to publish of mock connector
  packages/integration-tests/src/__mocks__/connectors-mock.ts
  packages/integration-tests/src/tests/api/connector.test.ts
Labels: bugfix, size/xs

#2738 refactor(console): refactor table component
  packages/console/src/components/Table/StickyHeaderTable.module.scss
  packages/console/src/components/Table/StickyHeaderTable.tsx
  packages/console/src/components/Table/index.module.scss
  packages/console/src/components/Table/index.tsx
  packages/console/src/components/Table/types.ts
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/EditSection.module.scss
  packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/EditSection.tsx
  packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/LanguageDetails.module.scss
  packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/LanguageDetails.tsx
  packages/console/src/scss/normalized.scss
Labels: enhancement, size/xl

#2764 refactor(cli): improved connector add command
  packages/cli/package.json
  packages/cli/src/commands/connector/list.ts
  packages/cli/src/commands/connector/utils.ts
  pnpm-lock.yaml
Labels: enhancement, size/m

#2768 refactor: add official connectors in dist
  .github/workflows/integration-test.yml
  .scripts/package.sh
  packages/cli/src/commands/connector/utils.ts
Labels: enhancement, size/s

#2762 ci: fix publish workflow
  .github/workflows/release.yml
  .scripts/publish.js
Labels: size/s

#2746 ci: check alteration sequence
  .github/workflows/main.yml
  .scripts/check-alterations-sequence.js
  packages/cli/src/commands/database/alteration/index.ts
Labels: size/m

#2769 ci: use import to fix alteration sequence check
  .scripts/check-alterations-sequence.js
Labels: size/xs

#2766 fix(console): search users by phone
  packages/console/src/pages/Users/index.tsx
Labels: bugfix, size/xs

#2767 refactor(console): api resources table
  packages/console/src/pages/ApiResources/index.module.scss
  packages/console/src/pages/ApiResources/index.tsx
Labels: enhancement, size/m

#2760 chore: add toolkit changeset
  .changeset/lovely-rivers-sniff.md
Labels: chore, size/s

#2778 style(console): remove full-width limit of add social dropdown
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SocialConnectorEditBox/AddButton.tsx
Labels: size/xs

#2775 ci: separate release groups
  .github/workflows/changesets.yml
  .scripts/version.js
  packages/integration-tests/package.json
  pnpm-lock.yaml
Labels: size/s

#2785 ci: use depth 0 in checkout to fetch all tags
  .github/workflows/release.yml
Labels: size/xs

#2771 fix(console): add url check for logo
  packages/console/src/pages/Connectors/components/ConnectorForm/index.tsx
Labels: bugfix, size/s
