Repository logto-io/logto, pull requests merged in 2022-04, with the labels that each got.

#468 feat(console): table scroll
  packages/console/src/pages/Users/index.module.scss
  packages/console/src/pages/Users/index.tsx
  packages/console/src/scss/normalized.scss
  packages/console/src/scss/table.module.scss
Labels: feature

#477 feat(core,phrases): validate sign-in experience branding and terms of use
  packages/core/src/lib/sign-in-experience.test.ts
  packages/core/src/lib/sign-in-experience.ts
  packages/core/src/routes/sign-in-experience.test.ts
  packages/core/src/routes/sign-in-experience.ts
  packages/core/src/utils/mock.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#472 feat(console): multi-text-input
  packages/console/src/components/MultiTextInput/index.module.scss
  packages/console/src/components/MultiTextInput/index.tsx
  packages/console/src/components/MultiTextInput/types.ts
  packages/console/src/components/MultiTextInput/utils.ts
  packages/console/src/components/MultilineInput/index.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/utilities/regex.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#475 feat(core,phrases): validate there must be one and only one primary sign-in method
  packages/core/src/lib/sign-in-experience.test.ts
  packages/core/src/lib/sign-in-experience.ts
  packages/core/src/routes/sign-in-experience.test.ts
  packages/core/src/routes/sign-in-experience.ts
  packages/core/src/utils/mock.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#486 feat(console): sticky footer in details page
  packages/console/src/pages/ApiResourceDetails/index.module.scss
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/console/src/pages/ApplicationDetails/index.module.scss
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/ConnectorDetails/index.module.scss
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/UserDetails/index.module.scss
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/scss/details.module.scss
Labels: feature

#476 fix(console): adjust styles on table
  packages/console/src/components/CopyToClipboard/index.module.scss
  packages/console/src/components/ImagePlaceholder/index.tsx
  packages/console/src/components/ItemPreview/index.module.scss
  packages/console/src/components/ItemPreview/index.tsx
  packages/console/src/components/Table/ItemPreviewLoading.module.scss
  packages/console/src/pages/ApiResources/index.module.scss
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/Applications/index.module.scss
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/Connectors/index.module.scss
  packages/console/src/pages/Connectors/index.tsx
  packages/console/src/pages/Users/index.module.scss
  packages/console/src/pages/Users/index.tsx
  packages/console/src/scss/_colors.scss
  packages/console/src/scss/_underscore.scss
  packages/console/src/scss/normalized.scss
  packages/console/src/scss/table.module.scss
Labels: bugfix

#480 feat(core,phrases): validate sign-in methods with enabled connectors
  packages/core/src/lib/sign-in-experience.test.ts
  packages/core/src/lib/sign-in-experience.ts
  packages/core/src/routes/sign-in-experience.test.ts
  packages/core/src/routes/sign-in-experience.ts
  packages/core/src/utils/mock.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#489 fix(console): add textField class to application details formfields
  packages/console/src/pages/ApplicationDetails/index.tsx
Labels: bugfix

#484 fix(console): input outline should be red in the error state on focused
  packages/console/src/components/TextInput/index.module.scss
Labels: bugfix

#485 feat(core,phrases): validate social sign-in method with social connector IDs
  packages/core/src/lib/sign-in-experience.test.ts
  packages/core/src/lib/sign-in-experience.ts
  packages/core/src/routes/sign-in-experience.test.ts
  packages/core/src/routes/sign-in-experience.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#488 feat(core): update social sign-in connector IDs only when social sign-in is enabled
  packages/core/src/lib/sign-in-experience.test.ts
  packages/core/src/lib/sign-in-experience.ts
  packages/core/src/routes/sign-in-experience.test.ts
  packages/core/src/routes/sign-in-experience.ts
Labels: feature

#481 refactor(console): promote and re-use get-started component in both applications and connectors
  packages/console/public/get-started/application/react/en/index.json
  packages/console/public/get-started/application/react/en/step1.md
  packages/console/public/get-started/application/react/en/step2.md
  packages/console/public/get-started/application/react/en/step3.md
  packages/console/public/get-started/application/react/en/step4.md
  packages/console/public/get-started/application/react/en/step5.md
  packages/console/public/get-started/application/react/zh-CN/index.json
  packages/console/public/get-started/application/react/zh-CN/step1.md
  packages/console/public/get-started/application/react/zh-CN/step2.md
  packages/console/public/get-started/application/react/zh-CN/step3.md
  packages/console/public/get-started/application/react/zh-CN/step4.md
  packages/console/public/get-started/application/react/zh-CN/step5.md
  packages/console/src/App.tsx
  packages/console/src/components/Card/index.tsx
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/Applications/components/GetStarted/index.module.scss
  packages/console/src/pages/Applications/components/GetStarted/index.tsx
  packages/console/src/pages/Applications/components/LibrarySelector/index.module.scss
  packages/console/src/pages/Applications/components/LibrarySelector/index.tsx
  packages/console/src/pages/GetStarted/components/Step/index.module.scss
  packages/console/src/pages/GetStarted/components/Step/index.tsx
  packages/console/src/pages/GetStarted/hooks/index.ts
  packages/console/src/pages/GetStarted/index.module.scss
  packages/console/src/pages/GetStarted/index.tsx
Labels: enhancement

#482 feat(console): support code editor in get-started steps
  packages/console/src/components/CodeEditor/index.module.scss
  packages/console/src/components/CodeEditor/index.tsx
  packages/console/src/pages/GetStarted/components/Step/index.tsx
Labels: feature

#487 feat(ui): implement passcode page
  packages/ui/package.json
  packages/ui/src/components/AppContent/index.module.scss
  packages/ui/src/components/Passcode/index.tsx
  packages/ui/src/components/TextLink/index.tsx
  packages/ui/src/containers/PasscodeValidation/index.module.scss
  packages/ui/src/containers/PasscodeValidation/index.test.tsx
  packages/ui/src/containers/PasscodeValidation/index.tsx
  packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
  packages/ui/src/pages/Passcode/index.module.scss
  packages/ui/src/pages/Passcode/index.test.tsx
  packages/ui/src/pages/Passcode/index.tsx
  pnpm-lock.yaml
Labels: feature

#491 feat(schemas,core,phrases)!: add type to connector schema and sync to DB
  packages/core/src/connectors/index.test.ts
  packages/core/src/connectors/index.ts
  packages/core/src/connectors/utilities/index.test.ts
  packages/core/src/lib/passcode.test.ts
  packages/core/src/queries/connector.test.ts
  packages/core/src/routes/connector.test.ts
  packages/core/src/utils/mock.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/schemas/src/db-entries/connector.ts
  packages/schemas/src/db-entries/custom-types.ts
  packages/schemas/src/types/connector.ts
  packages/schemas/tables/connectors.sql
Labels: feature

#493 feat(console): store filters in url search params
  packages/console/src/pages/Users/index.tsx
Labels: feature

#496 fix(console): page scroll should work when scrolling on monaco editor
  packages/console/src/components/CodeEditor/index.tsx
Labels: bugfix

#492 refactor(ui): update react router version
  packages/ui/package.json
  packages/ui/src/App.tsx
  packages/ui/src/apis/utils.ts
  packages/ui/src/containers/PasscodeValidation/index.tsx
  packages/ui/src/containers/Passwordless/EmailPasswordless.test.tsx
  packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.test.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
  packages/ui/src/pages/Passcode/index.test.tsx
  packages/ui/src/pages/Passcode/index.tsx
  packages/ui/src/pages/Register/index.test.tsx
  packages/ui/src/pages/Register/index.tsx
  packages/ui/src/pages/SecondarySignIn/index.test.tsx
  packages/ui/src/pages/SecondarySignIn/index.tsx
  packages/ui/src/types/index.ts
  pnpm-lock.yaml
Labels: enhancement

#500 fix(core): fix default enable value of new connectors
  packages/schemas/tables/connectors.sql
Labels: bugfix

#501 refactor(ui): refactor i18n phrases in logto main flow
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/ui/src/components/ConfirmModal/index.tsx
  packages/ui/src/components/Divider/index.test.tsx
  packages/ui/src/components/Divider/index.tsx
  packages/ui/src/components/ErrorMessage/index.tsx
  packages/ui/src/components/Input/PasswordInput.test.tsx
  packages/ui/src/components/Input/PhoneInput.test.tsx
  packages/ui/src/components/Input/index.test.tsx
  packages/ui/src/components/Input/index.tsx
  packages/ui/src/components/TermsOfUse/index.test.tsx
  packages/ui/src/components/TermsOfUse/index.tsx
  packages/ui/src/components/TextLink/index.test.tsx
  packages/ui/src/components/TextLink/index.tsx
  packages/ui/src/containers/CreateAccount/index.test.tsx
  packages/ui/src/containers/CreateAccount/index.tsx
  packages/ui/src/containers/PasscodeValidation/index.test.tsx
  packages/ui/src/containers/PasscodeValidation/index.tsx
  packages/ui/src/containers/Passwordless/EmailPasswordless.test.tsx
  packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.test.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
  packages/ui/src/containers/UsernameSignin/index.test.tsx
  packages/ui/src/containers/UsernameSignin/index.tsx
  packages/ui/src/pages/Consent/index.tsx
  packages/ui/src/pages/Passcode/index.test.tsx
  packages/ui/src/pages/Passcode/index.tsx
  packages/ui/src/pages/Register/index.test.tsx
  packages/ui/src/pages/Register/index.tsx
  packages/ui/src/pages/SecondarySignIn/index.test.tsx
  packages/ui/src/pages/SecondarySignIn/index.tsx
  packages/ui/src/pages/SignIn/index.test.tsx
  packages/ui/src/pages/SignIn/index.tsx
Labels: enhancement

#503 feat: init docs
  merge-eslint-reports.js
  packages/docs/.gitignore
  packages/docs/README.md
  packages/docs/babel.config.js
  packages/docs/docs/intro.md
  packages/docs/docusaurus.config.js
  packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/intro.md
  packages/docs/package.json
  packages/docs/sidebars.js
  packages/docs/src/components/HomepageFeatures/index.tsx
  packages/docs/src/components/HomepageFeatures/styles.module.css
  packages/docs/src/css/custom.css
  packages/docs/src/pages/index.module.css
  packages/docs/src/pages/index.tsx
  packages/docs/src/pages/markdown-page.md
  packages/docs/static/.nojekyll
  packages/docs/static/img/favicon.ico
  packages/docs/static/img/logo.svg
  packages/docs/tsconfig.json
  pnpm-lock.yaml
Labels: feature

#499 test(core): get sign-in experience
  packages/core/src/routes/sign-in-experience.test.ts
Labels: testing

#494 test(core): guard branding of sign-in experience
  packages/core/package.json
  packages/core/src/routes/sign-in-experience.guard.test.ts
  packages/core/src/routes/sign-in-experience.test.ts
  packages/ui/package.json
  pnpm-lock.yaml
Labels: testing

#497 test(core): guard terms of use and language info
  packages/core/src/routes/sign-in-experience.guard.test.ts
  packages/core/src/utils/mock.ts
Labels: testing

#502 feat(console): support input form fields in get-started steps
  packages/console/public/get-started/application/react/en/step3.md
  packages/console/public/get-started/application/react/en/step4.md
  packages/console/public/get-started/application/react/zh-CN/step3.md
  packages/console/public/get-started/application/react/zh-CN/step4.md
  packages/console/src/components/FormField/index.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/Applications/components/GetStartedModal/index.tsx
  packages/console/src/pages/Applications/components/LibrarySelector/index.module.scss
  packages/console/src/pages/GetStarted/components/CodeComponentRenderer/index.tsx
  packages/console/src/pages/GetStarted/components/Step/index.module.scss
  packages/console/src/pages/GetStarted/components/Step/index.tsx
  packages/console/src/pages/GetStarted/hooks/index.ts
  packages/console/src/pages/GetStarted/index.tsx
  packages/console/src/types/get-started.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#498 test(core): guard sign-in methods and social connector ids
  packages/core/src/routes/sign-in-experience.branding.guard.test.ts
  packages/core/src/routes/sign-in-experience.guard.test.ts
  packages/core/src/utils/mock.ts
Labels: testing

#508 fix(bug): display request message for now
  packages/ui/src/containers/UsernameSignin/index.tsx
Labels: bugfix

#506 chore(console): refactor connectors children components
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorName/index.module.scss
  packages/console/src/pages/Connectors/components/ConnectorName/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorRow/index.tsx
  packages/console/src/pages/Connectors/components/CreateForm/index.module.scss
  packages/console/src/pages/Connectors/components/CreateForm/index.tsx
  packages/console/src/pages/Connectors/index.tsx
Labels: chore

#514 fix: enable hmr in parcel projects
  packages/console/package.json
  packages/ui/package.json
Labels: bugfix

#495 feat(console): add paginations for applications and resources
  packages/console/src/pages/ApiResources/index.module.scss
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/Applications/index.module.scss
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/Users/index.tsx
Labels: feature

#517 fix(console): get started folder naming
  packages/console/public/get-started/application/react/en-us/index.json
  packages/console/public/get-started/application/react/en-us/step1.md
  packages/console/public/get-started/application/react/en-us/step2.md
  packages/console/public/get-started/application/react/en-us/step3.md
  packages/console/public/get-started/application/react/en-us/step4.md
  packages/console/public/get-started/application/react/en-us/step5.md
  packages/console/public/get-started/application/react/zh-cn/index.json
  packages/console/public/get-started/application/react/zh-cn/step1.md
  packages/console/public/get-started/application/react/zh-cn/step2.md
  packages/console/public/get-started/application/react/zh-cn/step3.md
  packages/console/public/get-started/application/react/zh-cn/step4.md
  packages/console/public/get-started/application/react/zh-cn/step5.md
Labels: bugfix

#513 feat(ui): add page level loading layer
  packages/ui/src/assets/icons/loading.svg
  packages/ui/src/components/AppContent/index.module.scss
  packages/ui/src/components/AppContent/index.tsx
  packages/ui/src/components/Icons/LoadingIcon.tsx
  packages/ui/src/components/Icons/index.ts
  packages/ui/src/components/LoadingLayer/index.module.scss
  packages/ui/src/components/LoadingLayer/index.tsx
  packages/ui/src/containers/CreateAccount/index.test.tsx
  packages/ui/src/containers/CreateAccount/index.tsx
  packages/ui/src/containers/PasscodeValidation/index.test.tsx
  packages/ui/src/containers/Passwordless/EmailPasswordless.test.tsx
  packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.test.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
  packages/ui/src/containers/UsernameSignin/index.test.tsx
  packages/ui/src/containers/UsernameSignin/index.tsx
  packages/ui/src/hooks/use-api.ts
Labels: feature

#512 fix(console): fix placeholder image padding
  packages/console/src/components/ImagePlaceholder/index.module.scss
  packages/console/src/components/ImagePlaceholder/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorName/index.module.scss
Labels: bugfix

#505 fix(console): fix ac ui issues
  packages/console/src/components/AppContent/components/Sidebar/consts.ts
  packages/console/src/components/AppContent/components/Sidebar/icons/Contact.tsx
  packages/console/src/components/AppContent/components/Sidebar/icons/Help.tsx
  packages/console/src/components/CopyToClipboard/index.module.scss
  packages/console/src/components/TabNav/TabNavLink.module.scss
  packages/console/src/components/TextInput/index.module.scss
  packages/console/src/icons/Plus.tsx
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/ConnectorDetails/components/SenderTester/index.tsx
  packages/console/src/pages/Connectors/index.tsx
  packages/console/src/pages/Users/index.tsx
  packages/console/src/scss/details.module.scss
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: bugfix

#516 feat(docs): init React SDK tutorial
  packages/docs/docs/integrate-sdk/_category_.json
  packages/docs/docs/integrate-sdk/react/_category_.json
  packages/docs/docs/integrate-sdk/react/_step-1.mdx
  packages/docs/docs/integrate-sdk/react/_step-2.md
  packages/docs/docs/integrate-sdk/react/_step-3.md
  packages/docs/docs/integrate-sdk/react/_step-4.md
  packages/docs/docs/integrate-sdk/react/_step-5.md
  packages/docs/docs/integrate-sdk/react/index.mdx
  packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current.json
  packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/integrate-sdk/react/_step-1.mdx
  packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/integrate-sdk/react/_step-2.md
  packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/integrate-sdk/react/_step-3.md
  packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/integrate-sdk/react/_step-4.md
  packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/integrate-sdk/react/_step-5.md
  packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/integrate-sdk/react/index.mdx
Labels: feature

#504 feat(ui): impelment signin methods links component
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/ui/package.json
  packages/ui/src/containers/PasscodeValidation/index.test.tsx
  packages/ui/src/containers/PasscodeValidation/index.tsx
  packages/ui/src/containers/SignInMethodsLink/index.module.scss
  packages/ui/src/containers/SignInMethodsLink/index.tsx
  packages/ui/src/containers/UsernameSignin/index.tsx
  pnpm-lock.yaml
Labels: feature

#519 feat(core): validate redirect uris of application
  packages/schemas/src/foundations/jsonb-types.ts
Labels: feature

#520 refactor(core): remove resource scopes
  packages/core/src/oidc/init.ts
  packages/core/src/queries/scope.test.ts
  packages/core/src/queries/scope.ts
  packages/core/src/routes/resource.test.ts
  packages/core/src/routes/resource.ts
  packages/core/src/utils/mock.ts
  packages/schemas/src/db-entries/index.ts
  packages/schemas/src/db-entries/resource-scope.ts
  packages/schemas/tables/resource_scopes.sql
Labels: enhancement

#521 feat(cli): init
  packages/cli/package.json
  packages/cli/src/database.ts
  packages/cli/src/index.ts
  packages/cli/tsconfig.json
  pnpm-lock.yaml
Labels: feature

#510 refactor(core): split mock.ts into __mocks__/*.ts
  packages/core/jest.config.js
  packages/core/src/__mocks__/connector.ts
  packages/core/src/__mocks__/index.ts
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/__mocks__/user.ts
  packages/core/src/lib/sign-in-experience.test.ts
  packages/core/src/middleware/koa-role-guard.test.ts
  packages/core/src/middleware/koa-user-info.test.ts
  packages/core/src/oidc/adapter.test.ts
  packages/core/src/queries/application.test.ts
  packages/core/src/queries/passcode.test.ts
  packages/core/src/queries/resource.test.ts
  packages/core/src/queries/roles.test.ts
  packages/core/src/queries/setting.test.ts
  packages/core/src/queries/sign-in-experience.test.ts
  packages/core/src/queries/user-log.test.ts
  packages/core/src/queries/user.test.ts
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/application.test.ts
  packages/core/src/routes/connector.test.ts
  packages/core/src/routes/resource.test.ts
  packages/core/src/routes/role.test.ts
  packages/core/src/routes/setting.test.ts
  packages/core/src/routes/sign-in-experience.branding.guard.test.ts
  packages/core/src/routes/sign-in-experience.guard.test.ts
  packages/core/src/routes/sign-in-experience.test.ts
  packages/core/src/utils/mock.ts
  packages/core/tsconfig.build.json
  packages/ui/jest.config.ts
Labels: enhancement

#507 feat(core,schemas): cors allowed origins
  packages/core/src/oidc/init.ts
  packages/core/src/oidc/utils.test.ts
  packages/core/src/oidc/utils.ts
  packages/schemas/src/foundations/jsonb-types.ts
Labels: feature

#518 feat(ui): add social apis
  packages/ui/src/apis/index.test.ts
  packages/ui/src/apis/register.ts
  packages/ui/src/apis/sign-in.ts
  packages/ui/src/apis/social.ts
Labels: feature

#523 feat(cli): seed tables
  packages/cli/package.json
  packages/cli/src/database.ts
  packages/cli/src/include.d/slonik-interceptor-preset.d.ts
  packages/cli/src/utilities.ts
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/core/src/__mocks__/index.ts
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/queries/sign-in-experience.test.ts
  packages/core/src/routes/setting.test.ts
  packages/core/src/routes/sign-in-experience.branding.guard.test.ts
  packages/schemas/src/db-entries/sign-in-experience.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/index.ts
  packages/schemas/src/seeds/index.ts
  packages/schemas/src/seeds/resource.ts
  packages/schemas/src/seeds/setting.ts
  packages/schemas/src/seeds/sign-in-experience.ts
  packages/schemas/tables/sign_in_experiences.sql
  pnpm-lock.yaml
Labels: feature

#530 fix(core): extraClientMetadata properties
  packages/core/src/oidc/init.ts
Labels: bugfix

#524 feat(cli): create database
  packages/cli/package.json
  packages/cli/src/database.ts
  packages/cli/src/index.ts
  pnpm-lock.yaml
Labels: feature

#525 fix(docs): package name
  packages/docs/package.json
Labels: bugfix

#526 feat(cli): integrate with command line
  packages/cli/package.json
  packages/cli/src/commands/database/index.ts
  packages/cli/src/commands/database/library.ts
  packages/cli/src/commands/database/utilities.ts
  packages/cli/src/index.ts
  pnpm-lock.yaml
Labels: feature

#527 feat(console): link button component
  packages/console/src/components/BackLink/index.module.scss
  packages/console/src/components/BackLink/index.tsx
  packages/console/src/components/LinkButton/index.module.scss
  packages/console/src/components/LinkButton/index.tsx
  packages/console/src/icons/Back.tsx
  packages/console/src/pages/ApiResourceDetails/index.module.scss
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/console/src/pages/ApplicationDetails/index.module.scss
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/ConnectorDetails/index.module.scss
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/UserDetails/index.module.scss
  packages/console/src/pages/UserDetails/index.tsx
Labels: feature

#509 feat(console): contact us
  packages/console/src/assets/images/slack.svg
  packages/console/src/components/AppContent/components/Sidebar/components/Contact/const.tsx
  packages/console/src/components/AppContent/components/Sidebar/components/Contact/index.module.scss
  packages/console/src/components/AppContent/components/Sidebar/components/Contact/index.tsx
  packages/console/src/components/AppContent/components/Sidebar/components/Item/index.module.scss
  packages/console/src/components/AppContent/components/Sidebar/components/Item/index.tsx
  packages/console/src/components/AppContent/components/Sidebar/consts.tsx
  packages/console/src/components/AppContent/components/Sidebar/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#533 fix(ui): fix svg radio box icon fill color
  packages/ui/src/assets/icons/radio-button.svg
Labels: bugfix

#532 refactor(docs): optimize React get started
  packages/docs/docs/integrate-sdk/react/_step-1.mdx
  packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/integrate-sdk/react/_step-1.mdx
Labels: enhancement

#534 feat(core): add sign-in-settings api for client use
  packages/core/src/routes/sign-in-experience.test.ts
  packages/core/src/routes/sign-in-experience.ts
Labels: feature

#528 fix(console): change button border color to color-component-border
  packages/console/src/components/Button/index.module.scss
Labels: bugfix

#540 fix(console): drawer component background
  packages/console/src/components/Drawer/index.module.scss
Labels: bugfix

#535 feat(console): init sign in exp page
  packages/console/src/App.tsx
  packages/console/src/pages/SignInExperience/index.module.scss
  packages/console/src/pages/SignInExperience/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#529 feat(core): validate custom client metadata when post or patch application
  packages/core/src/__mocks__/index.ts
  packages/core/src/oidc/utils.test.ts
  packages/core/src/oidc/utils.ts
  packages/core/src/routes/application.test.ts
  packages/core/src/routes/application.ts
  packages/schemas/src/foundations/jsonb-types.ts
Labels: feature

#537 refactor(core): phone method refactor
  packages/core/src/routes/session.test.ts
  packages/core/src/routes/session.ts
  packages/ui/src/apis/index.test.ts
  packages/ui/src/apis/register.ts
  packages/ui/src/apis/sign-in.ts
  packages/ui/src/apis/utils.ts
  packages/ui/src/containers/PasscodeValidation/index.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.test.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
  packages/ui/src/containers/SignInMethodsLink/index.tsx
  packages/ui/src/pages/Passcode/index.tsx
  packages/ui/src/pages/Register/index.test.tsx
  packages/ui/src/pages/Register/index.tsx
  packages/ui/src/pages/SecondarySignIn/index.test.tsx
  packages/ui/src/pages/SecondarySignIn/index.tsx
  packages/ui/src/types/index.ts
Labels: enhancement

#542 feat(ui): load sign-in experience settings from server
  packages/ui/src/App.tsx
  packages/ui/src/__mocks__/logto.tsx
  packages/ui/src/apis/settings.ts
  packages/ui/src/apis/utils.ts
  packages/ui/src/components/AppContent/index.tsx
  packages/ui/src/containers/PasscodeValidation/index.test.tsx
  packages/ui/src/containers/PasscodeValidation/index.tsx
  packages/ui/src/containers/SignInMethodsLink/index.tsx
  packages/ui/src/hooks/page-context.ts
  packages/ui/src/hooks/use-theme.ts
  packages/ui/src/pages/Passcode/index.test.tsx
  packages/ui/src/pages/Passcode/index.tsx
  packages/ui/src/pages/Register/index.test.tsx
  packages/ui/src/pages/Register/index.tsx
  packages/ui/src/pages/SecondarySignIn/index.test.tsx
  packages/ui/src/pages/SecondarySignIn/index.tsx
  packages/ui/src/types/index.ts
  packages/ui/src/utils/sign-in-experience.test.ts
  packages/ui/src/utils/sign-in-experience.ts
Labels: feature

#550 refactor(console): css color variables and theme mixins
  packages/console/src/components/AppContent/components/Sidebar/components/Contact/index.module.scss
  packages/console/src/components/AppContent/components/Sidebar/components/Item/index.module.scss
  packages/console/src/components/AppContent/components/Sidebar/components/Section/index.module.scss
  packages/console/src/components/AppContent/components/Sidebar/icons/Contact.tsx
  packages/console/src/components/AppContent/components/Topbar/index.module.scss
  packages/console/src/components/Button/index.module.scss
  packages/console/src/components/Card/index.module.scss
  packages/console/src/components/CardTitle/index.module.scss
  packages/console/src/components/CopyToClipboard/index.module.scss
  packages/console/src/components/FormField/index.module.scss
  packages/console/src/components/IconButton/index.module.scss
  packages/console/src/components/LinkButton/index.module.scss
  packages/console/src/components/RadioGroup/index.module.scss
  packages/console/src/components/Status/index.module.scss
  packages/console/src/components/TabNav/TabNavLink.module.scss
  packages/console/src/components/TextInput/index.module.scss
  packages/console/src/components/Toast/index.module.scss
  packages/console/src/pages/ApiResourceDetails/index.module.scss
  packages/console/src/pages/ApplicationDetails/index.module.scss
  packages/console/src/pages/Applications/components/LibrarySelector/index.module.scss
  packages/console/src/pages/Applications/components/TypeDescription/index.module.scss
  packages/console/src/pages/ConnectorDetails/components/SenderTester/index.module.scss
  packages/console/src/pages/ConnectorDetails/index.module.scss
  packages/console/src/pages/Connectors/components/GetStartedModal/index.module.scss
  packages/console/src/pages/GetStarted/index.module.scss
  packages/console/src/pages/UserDetails/index.module.scss
  packages/console/src/scss/_colors.scss
  packages/console/src/scss/_fonts.scss
  packages/console/src/scss/details.module.scss
  packages/console/src/scss/normalized.scss
  packages/console/src/scss/table.module.scss
Labels: enhancement

#522 feat(core): add Alipay web connector
  packages/core/package.json
  packages/core/src/connectors/alipay/README.md
  packages/core/src/connectors/alipay/config-template.md
  packages/core/src/connectors/alipay/constant.ts
  packages/core/src/connectors/alipay/index.test.ts
  packages/core/src/connectors/alipay/index.ts
  packages/core/src/connectors/alipay/mock.ts
  packages/core/src/connectors/alipay/types.ts
  packages/core/src/connectors/index.test.ts
  packages/core/src/connectors/index.ts
  packages/core/src/connectors/types.ts
  packages/core/src/connectors/utilities/index.ts
  packages/core/src/routes/session.test.ts
  packages/core/src/routes/session.ts
  packages/core/src/utils/regex.ts
  pnpm-lock.yaml
Labels: feature

#536 feat(core): add oidc config to the response of application apis
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/core/package.json
  packages/core/src/__mocks__/index.ts
  packages/core/src/routes/application.test.ts
  packages/core/src/routes/application.ts
  packages/schemas/package.json
  packages/schemas/src/types/application.ts
  packages/schemas/src/types/index.ts
  packages/schemas/src/types/oidc-config.ts
  pnpm-lock.yaml
Labels: feature

#539 feat(console): add experience form fields
  packages/console/src/pages/SignInExperience/components/BrandingForm.tsx
  packages/console/src/pages/SignInExperience/components/TermsForm.tsx
  packages/console/src/pages/SignInExperience/components/index.module.scss
  packages/console/src/pages/SignInExperience/index.module.scss
  packages/console/src/pages/SignInExperience/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#552 refactor(core): post application
  packages/core/src/routes/application.test.ts
  packages/core/src/routes/application.ts
Labels: enhancement

#546 feat(console): toggle switch
  packages/console/src/components/Switch/index.module.scss
  packages/console/src/components/Switch/index.tsx
  packages/console/src/pages/SignInExperience/components/BrandingForm.tsx
  packages/console/src/pages/SignInExperience/components/TermsForm.tsx
  packages/console/src/pages/SignInExperience/index.tsx
Labels: feature

#551 feat(core): add connector config examples
  packages/core/src/connectors/alipay/config-template.md
  packages/core/src/connectors/aliyun-dm/config-template.md
  packages/core/src/connectors/aliyun-sms/config-template.md
  packages/core/src/connectors/facebook/config-template.md
  packages/core/src/connectors/github/config-template.md
  packages/core/src/connectors/google/config-template.md
  packages/core/src/connectors/wechat/config-template.md
Labels: feature

#548 feat(console): plain radio
  packages/console/src/components/RadioGroup/Radio.tsx
  packages/console/src/components/RadioGroup/index.module.scss
  packages/console/src/components/RadioGroup/index.tsx
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/Applications/components/LibrarySelector/index.tsx
  packages/console/src/pages/Applications/components/TypeDescription/index.module.scss
  packages/console/src/pages/Applications/components/TypeDescription/index.tsx
  packages/console/src/pages/SignInExperience/components/BrandingForm.tsx
Labels: feature

#553 ci: update workflow
  .github/workflows/update-pr-metadata.yml
Labels: size/s

#549 feat(ui): add Primary SocialSignIn container and Popup
  packages/ui/src/__mocks__/logto.tsx
  packages/ui/src/assets/icons/expand-icon.svg
  packages/ui/src/components/ConfirmModal/index.tsx
  packages/ui/src/components/Drawer/index.module.scss
  packages/ui/src/components/Drawer/index.test.tsx
  packages/ui/src/components/Drawer/index.tsx
  packages/ui/src/components/Icons/ExpandMoreIcon.tsx
  packages/ui/src/components/Icons/index.ts
  packages/ui/src/components/TermsOfUse/index.tsx
  packages/ui/src/containers/SocialSignIn/PrimarySocialSignIn.test.tsx
  packages/ui/src/containers/SocialSignIn/PrimarySocialSignIn.tsx
  packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.tsx
  packages/ui/src/containers/SocialSignIn/SocialSignInPopUp.tsx
  packages/ui/src/containers/SocialSignIn/index.module.scss
  packages/ui/src/containers/SocialSignIn/index.ts
  packages/ui/src/pages/Passcode/index.tsx
  packages/ui/src/pages/Register/index.tsx
  packages/ui/src/pages/SecondarySignIn/index.tsx
  packages/ui/src/scss/modal.module.scss
Labels: feature

#557 chore(console,ui): parcel build --no-cache
  packages/console/package.json
  packages/ui/package.json
Labels: chore, size/xs

#556 refactor(schemas): extract sign-in method key
  packages/schemas/src/foundations/jsonb-types.ts
Labels: enhancement, size/s

#559 refactor(core): clear mocks after each test
  packages/core/src/middleware/koa-error-handler.test.ts
  packages/core/src/middleware/koa-spa-proxy.test.ts
  packages/core/src/middleware/koa-user-log.test.ts
Labels: enhancement, size/s

#563 refactor(ui): api method renaming
  packages/ui/src/apis/index.test.ts
  packages/ui/src/apis/register.ts
  packages/ui/src/apis/sign-in.ts
  packages/ui/src/apis/utils.ts
  packages/ui/src/containers/Passwordless/EmailPasswordless.test.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.test.tsx
Labels: enhancement, size/m

#558 refactor(core,schemas): pascalcase enum keys
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/lib/sign-in-experience.test.ts
  packages/core/src/lib/sign-in-experience.ts
  packages/core/src/middleware/koa-role-guard.test.ts
  packages/core/src/routes/sign-in-experience.guard.test.ts
  packages/core/src/routes/sign-in-experience.test.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/seeds/sign-in-experience.ts
  packages/schemas/src/types/user.ts
Labels: enhancement, size/m

#564 fix(core): fix sign-in settings api route
  packages/core/src/routes/session.test.ts
  packages/core/src/routes/session.ts
  packages/core/src/routes/sign-in-experience.test.ts
  packages/core/src/routes/sign-in-experience.ts
Labels: bugfix, size/s

#555 refactor(schemas): conform id length
  packages/schemas/tables/applications.sql
  packages/schemas/tables/passcodes.sql
  packages/schemas/tables/resources.sql
  packages/schemas/tables/settings.sql
  packages/schemas/tables/sign_in_experiences.sql
  packages/schemas/tables/users.sql
Labels: enhancement, size/s

#562 feat(console): add react error boundary
  packages/console/src/components/AppContent/index.tsx
  packages/console/src/components/ErrorBoundary/index.module.scss
  packages/console/src/components/ErrorBoundary/index.tsx
Labels: feature, size/m

#561 feat(schemas): logs schema and log payload type
  packages/schemas/src/db-entries/index.ts
  packages/schemas/src/db-entries/log.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/tables/logs.sql
Labels: feature, size/s

#554 feat(console): sign-in-methods form setup
  packages/console/src/pages/SignInExperience/components/BrandingForm.tsx
  packages/console/src/pages/SignInExperience/components/SignInMethodsForm.tsx
  packages/console/src/pages/SignInExperience/components/TermsForm.tsx
  packages/console/src/pages/SignInExperience/components/index.module.scss
  packages/console/src/pages/SignInExperience/index.tsx
  packages/console/src/pages/SignInExperience/types.ts
  packages/console/src/pages/SignInExperience/utilities.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature, size/m

#541 feat(console): color picker
  packages/console/package.json
  packages/console/src/components/ColorPicker/index.module.scss
  packages/console/src/components/ColorPicker/index.tsx
  packages/console/src/pages/SignInExperience/components/BrandingForm.tsx
  pnpm-lock.yaml
Labels: feature, size/s

#565 fix(schemas): remove wrong default values from sign-in experience schema
  packages/schemas/src/db-entries/sign-in-experience.ts
  packages/schemas/tables/sign_in_experiences.sql
Labels: bugfix, size/s

#566 fix(core): revert add oidc config to application response
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/core/package.json
  packages/core/src/__mocks__/index.ts
  packages/core/src/routes/application.test.ts
  packages/core/src/routes/application.ts
  packages/schemas/src/types/application.ts
  packages/schemas/src/types/index.ts
  pnpm-lock.yaml
Labels: bugfix, size/m

#572 fix: typos in phrases
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/ui/src/containers/PasscodeValidation/index.test.tsx
  packages/ui/src/containers/PasscodeValidation/index.tsx
Labels: bugfix, size/s

#567 fix(console): center align image and error message in error boundary
  packages/console/src/components/ErrorBoundary/index.module.scss
  packages/console/src/components/ErrorBoundary/index.tsx
Labels: bugfix, size/xs

#573 docs: add Swift Logto core reference
  packages/docs/docs/sdk/README.md
  packages/docs/docs/sdk/Swift/Logto/Enums/JwtField.md
  packages/docs/docs/sdk/Swift/Logto/Enums/LogtoCore.md
  packages/docs/docs/sdk/Swift/Logto/Enums/LogtoErrors.Response.md
  packages/docs/docs/sdk/Swift/Logto/Enums/LogtoErrors.UriVerification.md
  packages/docs/docs/sdk/Swift/Logto/Enums/LogtoErrors.UrlConstruction.md
  packages/docs/docs/sdk/Swift/Logto/Enums/LogtoErrors.md
  packages/docs/docs/sdk/Swift/Logto/Enums/LogtoRequest.HttpMethod.md
  packages/docs/docs/sdk/Swift/Logto/Enums/LogtoRequest.md
  packages/docs/docs/sdk/Swift/Logto/Enums/LogtoUtilities.md
  packages/docs/docs/sdk/Swift/Logto/Enums/_category_.json
  packages/docs/docs/sdk/Swift/Logto/Extensions/URLSession.md
  packages/docs/docs/sdk/Swift/Logto/Extensions/_category_.json
  packages/docs/docs/sdk/Swift/Logto/Protocols/NetworkSession.md
  packages/docs/docs/sdk/Swift/Logto/Protocols/_category_.json
  packages/docs/docs/sdk/Swift/Logto/README.md
  packages/docs/docs/sdk/Swift/Logto/Structs/IdTokenClaims.md
  packages/docs/docs/sdk/Swift/Logto/Structs/JwtHeader.md
  packages/docs/docs/sdk/Swift/Logto/Structs/LogtoCore.CodeTokenResponse.md
  packages/docs/docs/sdk/Swift/Logto/Structs/LogtoCore.OidcConfigResponse.md
  packages/docs/docs/sdk/Swift/Logto/Structs/LogtoCore.RefreshTokenTokenResponse.md
  packages/docs/docs/sdk/Swift/Logto/Structs/LogtoCore.UserInfoResponse.md
  packages/docs/docs/sdk/Swift/Logto/Structs/_category_.json
  packages/docs/docs/sdk/Swift/README.md
  packages/docs/docs/tutorial/README.md
  packages/docs/docs/tutorial/integrate-sdk/_category_.json
  packages/docs/docs/tutorial/integrate-sdk/react/_category_.json
  packages/docs/docs/tutorial/integrate-sdk/react/_step-1.mdx
  packages/docs/docs/tutorial/integrate-sdk/react/_step-2.md
  packages/docs/docs/tutorial/integrate-sdk/react/_step-3.md
  packages/docs/docs/tutorial/integrate-sdk/react/_step-4.md
  packages/docs/docs/tutorial/integrate-sdk/react/_step-5.md
  packages/docs/docs/tutorial/integrate-sdk/react/index.mdx
  packages/docs/docusaurus.config.js
  packages/docs/sidebars.js
  packages/docs/src/pages/index.tsx
Labels: size/xl

#571 feat(console): draft logto loading state animation page
  packages/console/src/components/AppContent/index.tsx
  packages/console/src/components/LogtoLoading/index.module.scss
  packages/console/src/components/LogtoLoading/index.tsx
  packages/console/src/pages/Callback/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature, size/s

#575 docs: update config for deployment
  packages/docs/docusaurus.config.js
  packages/docs/static/CNAME
Labels: size/xs

#574 docs: add Swift Logto client reference
  packages/docs/docs/sdk/README.md
  packages/docs/docs/sdk/Swift/Logto/Enums/LogtoErrors.Response.md
  packages/docs/docs/sdk/Swift/Logto/Enums/LogtoErrors.UriVerification.md
  packages/docs/docs/sdk/Swift/Logto/Enums/LogtoErrors.UrlConstruction.md
  packages/docs/docs/sdk/Swift/Logto/Enums/LogtoRequest.HttpMethod.md
  packages/docs/docs/sdk/Swift/Logto/Enums/LogtoRequest.md
  packages/docs/docs/sdk/Swift/LogtoClient/Classes/LogtoClient.md
  packages/docs/docs/sdk/Swift/LogtoClient/Classes/_category_.json
  packages/docs/docs/sdk/Swift/LogtoClient/Enums/LogtoClientErrorTypes.AccessToken.md
  packages/docs/docs/sdk/Swift/LogtoClient/Enums/LogtoClientErrorTypes.JwkSet.md
  packages/docs/docs/sdk/Swift/LogtoClient/Enums/LogtoClientErrorTypes.OidcConfig.md
  packages/docs/docs/sdk/Swift/LogtoClient/Enums/LogtoClientErrorTypes.SignIn.md
  packages/docs/docs/sdk/Swift/LogtoClient/Enums/LogtoClientErrorTypes.SignOut.md
  packages/docs/docs/sdk/Swift/LogtoClient/Enums/LogtoClientErrorTypes.UserInfo.md
  packages/docs/docs/sdk/Swift/LogtoClient/Enums/LogtoClientErrorTypes.md
  packages/docs/docs/sdk/Swift/LogtoClient/Enums/LogtoClientErrors.IdToken.md
  packages/docs/docs/sdk/Swift/LogtoClient/Enums/LogtoClientErrors.md
  packages/docs/docs/sdk/Swift/LogtoClient/Enums/_category_.json
  packages/docs/docs/sdk/Swift/LogtoClient/Protocols/_category_.json
  packages/docs/docs/sdk/Swift/LogtoClient/README.md
  packages/docs/docs/sdk/Swift/LogtoClient/Structs/AccessToken.md
  packages/docs/docs/sdk/Swift/LogtoClient/Structs/LogtoClient.NotificationObject.md
  packages/docs/docs/sdk/Swift/LogtoClient/Structs/LogtoConfig.md
  packages/docs/docs/sdk/Swift/LogtoClient/Structs/LogtoError.md
  packages/docs/docs/sdk/Swift/LogtoClient/Structs/_category_.json
  packages/docs/docs/sdk/Swift/LogtoClient/Typealiases/LogtoClientErrors.AccessToken.md
  packages/docs/docs/sdk/Swift/LogtoClient/Typealiases/LogtoClientErrors.JwkSet.md
  packages/docs/docs/sdk/Swift/LogtoClient/Typealiases/LogtoClientErrors.OidcConfig.md
  packages/docs/docs/sdk/Swift/LogtoClient/Typealiases/LogtoClientErrors.SignIn.md
  packages/docs/docs/sdk/Swift/LogtoClient/Typealiases/LogtoClientErrors.SignOut.md
  packages/docs/docs/sdk/Swift/LogtoClient/Typealiases/LogtoClientErrors.UserInfo.md
  packages/docs/docs/sdk/Swift/LogtoClient/Typealiases/UnifiedViewController.md
  packages/docs/docs/sdk/Swift/LogtoClient/Typealiases/_category_.json
  packages/docs/docs/sdk/Swift/README.md
Labels: size/xl

#570 refactor(ui): refactor social login hooks
  packages/ui/src/App.tsx
  packages/ui/src/__mocks__/ContextProvider.tsx
  packages/ui/src/apis/index.test.ts
  packages/ui/src/apis/social.ts
  packages/ui/src/components/Toast/index.module.scss
  packages/ui/src/containers/SocialSignIn/PrimarySocialSignIn.tsx
  packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.test.tsx
  packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.tsx
  packages/ui/src/hooks/use-social-connector.ts
  packages/ui/src/hooks/use-social.ts
  packages/ui/src/include.d/global.d.ts
  packages/ui/src/pages/Callback/index.module.scss
  packages/ui/src/pages/Callback/index.tsx
  packages/ui/src/utils/index.test.ts
  packages/ui/src/utils/index.ts
Labels: enhancement, size/l

#568 feat(console): add connectors transfer component
  packages/console/package.json
  packages/console/src/components/Transfer/DragDropProvider.tsx
  packages/console/src/components/Transfer/DraggableItem.tsx
  packages/console/src/components/Transfer/index.module.scss
  packages/console/src/components/Transfer/index.tsx
  packages/console/src/components/UnnamedTrans/index.tsx
  packages/console/src/icons/CircleMinus.tsx
  packages/console/src/icons/CirclePlus.tsx
  packages/console/src/icons/Draggable.tsx
  packages/console/src/pages/SignInExperience/components/ConnectorsTransfer.module.scss
  packages/console/src/pages/SignInExperience/components/ConnectorsTransfer.tsx
  packages/console/src/pages/SignInExperience/components/SignInMethodsForm.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  pnpm-lock.yaml
Labels: feature, size/l

#579 fix(console): fix issues on user management
  packages/console/src/components/CardTitle/index.module.scss
  packages/console/src/components/TextInput/index.module.scss
  packages/console/src/pages/UserDetails/components/UserConnectors.module.scss
  packages/console/src/pages/UserDetails/components/UserConnectors.tsx
  packages/console/src/pages/UserDetails/index.module.scss
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/pages/Users/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: bugfix, size/s

#577 test(core): separate the color validation cases from tests of sign-in experience
  packages/core/src/routes/sign-in-experience.branding.guard.test.ts
  packages/core/src/utils/regex.test.ts
Labels: testing, size/s

#580 fix(console): button hover and pressed state colors
  packages/console/src/components/Button/index.module.scss
  packages/console/src/scss/_colors.scss
Labels: bugfix, size/s

#587 feat(core): insert log into DB
  packages/core/src/queries/log.ts
Labels: feature, size/xs

#578 refactor(core): use SSOT for env variables
  packages/core/jest.config.js
  packages/core/jest.global-setup.js
  packages/core/jest.setup.js
  packages/core/src/app/init.ts
  packages/core/src/database/pool.ts
  packages/core/src/env-set/index.ts
  packages/core/src/env/consts.ts
  packages/core/src/index.ts
  packages/core/src/middleware/koa-auth.test.ts
  packages/core/src/middleware/koa-auth.ts
  packages/core/src/middleware/koa-spa-proxy.test.ts
  packages/core/src/middleware/koa-spa-proxy.ts
  packages/core/src/oidc/consts.ts
  packages/core/src/oidc/init.ts
  packages/core/src/routes/consts.ts
  packages/core/src/utils/password.ts
Labels: enhancement, size/m

#588 refactor(core): rename koa-user-log types and functions to avoid naming conflicts
  packages/core/src/middleware/koa-user-log.test.ts
  packages/core/src/middleware/koa-user-log.ts
Labels: enhancement, size/xs

#584 feat(console): button loading state with delay timeout
  packages/console/src/components/Button/index.module.scss
  packages/console/src/components/Button/index.tsx
  packages/console/src/icons/Spinner.tsx
  packages/console/src/pages/ApiResourceDetails/components/DeleteForm/index.tsx
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
  packages/console/src/pages/ApplicationDetails/components/DeleteForm/index.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/ConnectorDetails/components/SenderTester/index.tsx
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/SignInExperience/index.tsx
  packages/console/src/pages/UserDetails/components/ResetPasswordForm.tsx
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/scss/_underscore.scss
Labels: feature, size/m

#590 feat(core,schema): new koa-log middleware
  packages/core/src/app/init.test.ts
  packages/core/src/app/init.ts
  packages/core/src/middleware/koa-log.test.ts
  packages/core/src/middleware/koa-log.ts
  packages/schemas/src/types/index.ts
  packages/schemas/src/types/log.ts
Labels: feature, size/m

#583 feat(ui): ui style foundation update
  packages/ui/src/assets/icons/radio-button.svg
  packages/ui/src/components/AppContent/index.module.scss
  packages/ui/src/components/BrandingHeader/index.module.scss
  packages/ui/src/components/Button/MoreButton.tsx
  packages/ui/src/components/Button/SocialIconButton.module.scss
  packages/ui/src/components/Button/SocialLinkButton.module.scss
  packages/ui/src/components/Button/SocialLinkButton.tsx
  packages/ui/src/components/Button/index.module.scss
  packages/ui/src/components/Button/index.tsx
  packages/ui/src/components/ConfirmModal/index.module.scss
  packages/ui/src/components/Divider/index.module.scss
  packages/ui/src/components/Drawer/index.module.scss
  packages/ui/src/components/Drawer/index.tsx
  packages/ui/src/components/ErrorMessage/index.module.scss
  packages/ui/src/components/Icons/MoreSocialIcon.tsx
  packages/ui/src/components/Input/index.module.scss
  packages/ui/src/components/Input/phoneInput.module.scss
  packages/ui/src/components/LoadingLayer/index.module.scss
  packages/ui/src/components/NavBar/index.module.scss
  packages/ui/src/components/NavBar/index.tsx
  packages/ui/src/components/Passcode/index.module.scss
  packages/ui/src/components/TermsOfUse/index.module.scss
  packages/ui/src/components/TermsOfUse/index.tsx
  packages/ui/src/components/TextLink/index.module.scss
  packages/ui/src/components/Toast/index.module.scss
  packages/ui/src/containers/CreateAccount/index.module.scss
  packages/ui/src/containers/CreateAccount/index.tsx
  packages/ui/src/containers/PasscodeValidation/index.module.scss
  packages/ui/src/containers/PasscodeValidation/index.tsx
  packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
  packages/ui/src/containers/Passwordless/index.module.scss
  packages/ui/src/containers/SignInMethodsLink/index.tsx
  packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.test.tsx
  packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.tsx
  packages/ui/src/containers/SocialSignIn/index.module.scss
  packages/ui/src/containers/UsernameSignin/index.module.scss
  packages/ui/src/containers/UsernameSignin/index.test.tsx
  packages/ui/src/containers/UsernameSignin/index.tsx
  packages/ui/src/pages/Passcode/index.module.scss
  packages/ui/src/pages/Passcode/index.tsx
  packages/ui/src/pages/Register/index.module.scss
  packages/ui/src/pages/Register/index.tsx
  packages/ui/src/pages/SecondarySignIn/index.module.scss
  packages/ui/src/pages/SecondarySignIn/index.tsx
  packages/ui/src/pages/SignIn/index.module.scss
  packages/ui/src/pages/SignIn/index.tsx
  packages/ui/src/scss/_underscore.scss
  packages/ui/src/scss/modal.module.scss
Labels: feature, size/xl

#591 refactor(core): remove deprecated koa-user-log middleware
  packages/core/src/app/init.test.ts
  packages/core/src/app/init.ts
  packages/core/src/middleware/koa-user-log.test.ts
  packages/core/src/middleware/koa-user-log.ts
  packages/core/src/queries/user-log.test.ts
  packages/core/src/queries/user-log.ts
  packages/core/src/routes/session.ts
  packages/core/src/routes/types.ts
Labels: enhancement, size/l

#592 ci: trigger main workflow on all pull requests
  .github/workflows/main.yml
Labels: size/xs

#585 refactor(core): move database pool into env set
  packages/core/jest.config.js
  packages/core/jest.global-setup.ts
  packages/core/jest.setup.js
  packages/core/jest.setup.ts
  packages/core/src/database/insert-into.test.ts
  packages/core/src/database/insert-into.ts
  packages/core/src/database/pool.ts
  packages/core/src/database/update-where.test.ts
  packages/core/src/database/update-where.ts
  packages/core/src/database/utils.ts
  packages/core/src/env-set/index.ts
  packages/core/src/index.ts
  packages/core/src/middleware/koa-auth.test.ts
  packages/core/src/middleware/koa-spa-proxy.test.ts
  packages/core/src/queries/application.test.ts
  packages/core/src/queries/application.ts
  packages/core/src/queries/connector.test.ts
  packages/core/src/queries/connector.ts
  packages/core/src/queries/log.ts
  packages/core/src/queries/oidc-model-instance.test.ts
  packages/core/src/queries/oidc-model-instance.ts
  packages/core/src/queries/passcode.test.ts
  packages/core/src/queries/passcode.ts
  packages/core/src/queries/resource.test.ts
  packages/core/src/queries/resource.ts
  packages/core/src/queries/roles.test.ts
  packages/core/src/queries/roles.ts
  packages/core/src/queries/setting.test.ts
  packages/core/src/queries/setting.ts
  packages/core/src/queries/sign-in-experience.test.ts
  packages/core/src/queries/sign-in-experience.ts
  packages/core/src/queries/user-log.test.ts
  packages/core/src/queries/user-log.ts
  packages/core/src/queries/user.test.ts
  packages/core/src/queries/user.ts
  packages/core/tsconfig.json
Labels: enhancement, size/l

#593 refactor(phrases,schemas): move language enum and fix Lanugage.Chinese value
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/routes/sign-in-experience.guard.test.ts
  packages/phrases/src/index.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/seeds/sign-in-experience.ts
Labels: enhancement, bugfix, size/s

#597 chore(core,schemas): remove old user logs
  packages/core/src/__mocks__/index.ts
  packages/core/src/queries/user-log.test.ts
  packages/core/src/queries/user-log.ts
  packages/schemas/src/db-entries/custom-types.ts
  packages/schemas/src/db-entries/index.ts
  packages/schemas/src/db-entries/user-log.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/tables/user_logs.sql
Labels: chore, size/m

#560 feat(console): select
  packages/console/src/components/ActionMenu/index.tsx
  packages/console/src/components/Dropdown/DropdownItem.module.scss
  packages/console/src/components/Dropdown/DropdownItem.tsx
  packages/console/src/components/Dropdown/index.module.scss
  packages/console/src/components/Dropdown/index.tsx
  packages/console/src/components/Dropdown/use-position.ts
  packages/console/src/components/Select/index.module.scss
  packages/console/src/components/Select/index.tsx
  packages/console/src/pages/SignInExperience/components/SignInMethodsForm.tsx
  packages/console/src/scss/_colors.scss
Labels: feature, size/l

#589 feat(console): user role select
  packages/console/src/pages/UserDetails/components/RoleSelect.tsx
  packages/console/src/pages/UserDetails/index.tsx
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature, size/m

#600 chore(schemas): conform sql style
  packages/schemas/tables/logs.sql
Labels: chore, size/xs

#595 feat(ui): load lanuage settings from sign-in-experience settings
  packages/ui/src/App.tsx
  packages/ui/src/components/Input/index.module.scss
  packages/ui/src/i18n/init.ts
  packages/ui/src/utils/sign-in-experience.test.ts
  packages/ui/src/utils/sign-in-experience.ts
Labels: feature, size/s

#599 refactor(ui): update global page context
  packages/ui/src/App.tsx
  packages/ui/src/__mocks__/ContextProvider.tsx
  packages/ui/src/__mocks__/RenderWithPageContext/ContextProvider.tsx
  packages/ui/src/__mocks__/RenderWithPageContext/index.tsx
  packages/ui/src/components/AppContent/index.module.scss
  packages/ui/src/components/AppContent/index.tsx
  packages/ui/src/containers/CreateAccount/index.test.tsx
  packages/ui/src/containers/CreateAccount/index.tsx
  packages/ui/src/containers/PasscodeValidation/index.module.scss
  packages/ui/src/containers/PasscodeValidation/index.test.tsx
  packages/ui/src/containers/PasscodeValidation/index.tsx
  packages/ui/src/containers/Passwordless/EmailPasswordless.test.tsx
  packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.test.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
  packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.test.tsx
  packages/ui/src/containers/UsernameSignin/index.test.tsx
  packages/ui/src/containers/UsernameSignin/index.tsx
  packages/ui/src/hooks/page-context.ts
  packages/ui/src/hooks/use-api.ts
  packages/ui/src/hooks/use-page-context.ts
  packages/ui/src/hooks/use-social.ts
  packages/ui/src/hooks/use-theme.ts
Labels: enhancement, size/l

#594 feat(core,schemas): log sign-in
  packages/core/src/routes/session.test.ts
  packages/core/src/routes/session.ts
  packages/schemas/src/types/log.ts
Labels: feature, size/s

#604 fix(ui): show response error toast
  packages/ui/src/containers/CreateAccount/index.tsx
Labels: bugfix, size/xs

#605 refactor(ui): nativeCallback renaming
  packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.test.tsx
  packages/ui/src/hooks/use-social.ts
  packages/ui/src/include.d/global.d.ts
Labels: enhancement, size/s

#608 refactor(ui): load branding info from settings
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/ui/src/pages/Consent/index.module.scss
  packages/ui/src/pages/Consent/index.tsx
  packages/ui/src/pages/SignIn/index.test.tsx
  packages/ui/src/pages/SignIn/index.tsx
Labels: enhancement, size/s

#603 refactor(ui): refactor terms of use
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/ui/src/__mocks__/RenderWithPageContext/SettingsProvider.tsx
  packages/ui/src/__mocks__/logto.tsx
  packages/ui/src/components/ConfirmModal/index.tsx
  packages/ui/src/components/TermsOfUse/index.test.tsx
  packages/ui/src/components/TermsOfUse/index.tsx
  packages/ui/src/components/TermsOfUseModal/index.test.tsx
  packages/ui/src/components/TermsOfUseModal/index.tsx
  packages/ui/src/components/TextLink/index.tsx
  packages/ui/src/containers/CreateAccount/index.test.tsx
  packages/ui/src/containers/CreateAccount/index.tsx
  packages/ui/src/containers/Passwordless/EmailPasswordless.test.tsx
  packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.test.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
  packages/ui/src/containers/TermsOfUse/index.tsx
  packages/ui/src/containers/TermsOfUse/intext.test.tsx
  packages/ui/src/containers/UsernameSignin/index.test.tsx
  packages/ui/src/containers/UsernameSignin/index.tsx
  packages/ui/src/hooks/use-terms.ts
Labels: enhancement, size/l

#610 refactor(ui): replace termsOfUse Component with Container
  packages/ui/src/__mocks__/RenderWithPageContext/SettingsProvider.tsx
  packages/ui/src/containers/CreateAccount/index.test.tsx
  packages/ui/src/containers/CreateAccount/index.tsx
  packages/ui/src/containers/Passwordless/EmailPasswordless.test.tsx
  packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.test.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
  packages/ui/src/containers/TermsOfUse/intext.test.tsx
  packages/ui/src/containers/UsernameSignin/index.test.tsx
  packages/ui/src/containers/UsernameSignin/index.tsx
  packages/ui/src/hooks/use-social.ts
  packages/ui/src/hooks/use-terms.ts
Labels: enhancement, size/m

#616 ci: extends renovate `:preserveSemverRanges` preset
  renovate.json
Labels: size/xs

#598 fix(console): detail top card spacing
  packages/console/src/pages/ApiResourceDetails/index.module.scss
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/console/src/pages/ApplicationDetails/index.module.scss
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/ConnectorDetails/index.module.scss
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/UserDetails/index.module.scss
  packages/console/src/pages/UserDetails/index.tsx
Labels: bugfix, size/s

#621 docs: update LogtoClient `clientId` -> `appId`
  packages/docs/docs/sdk/Swift/LogtoClient/Classes/LogtoClient.md
  packages/docs/docs/sdk/Swift/LogtoClient/Structs/LogtoClient.NotificationObject.md
  packages/docs/docs/sdk/Swift/LogtoClient/Structs/LogtoConfig.md
  packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/sdk/Swift/LogtoClient/Classes/LogtoClient.md
  packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/sdk/Swift/LogtoClient/Structs/LogtoClient.NotificationObject.md
  packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/sdk/Swift/LogtoClient/Structs/LogtoConfig.md
Labels: size/s

#607 chore: add package script
  package.json
  package.sh
  packages/console/package.json
  packages/docs/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: chore, size/s

#625 refactor: align node version
  packages/cli/package.json
  packages/core/package.json
  packages/phrases/package.json
  packages/schemas/package.json
Labels: enhancement, size/xs

#628 refactor(core): add `--no-inquiry` option
  packages/core/src/env-set/create-pool-by-env.ts
  packages/core/src/env-set/oidc.ts
  packages/core/src/env-set/parameters.ts
  packages/core/src/env-set/password.ts
Labels: enhancement, size/s

#576 feat(console): add component checkbox
  packages/console/src/components/Checkbox/Icon.tsx
  packages/console/src/components/Checkbox/index.module.scss
  packages/console/src/components/Checkbox/index.tsx
  packages/console/src/pages/SignInExperience/components/SignInMethodsForm.tsx
  packages/console/src/pages/SignInExperience/components/index.module.scss
Labels: feature, size/m

#612 feat(console): page settings
  packages/console/src/App.tsx
  packages/console/src/components/AppContent/components/Sidebar/index.tsx
  packages/console/src/pages/Settings/index.tsx
  packages/core/src/__mocks__/index.ts
  packages/core/src/routes/setting.test.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/seeds/setting.ts
Labels: feature, size/m

#630 refactor: allow start from project root
  package.json
  packages/core/src/env-set/append-dot-env.ts
  packages/core/src/env-set/create-pool-by-env.ts
  packages/core/src/env-set/dot-env.ts
  packages/core/src/env-set/oidc.ts
  packages/core/src/env-set/parameters.ts
  packages/core/src/env-set/password.ts
  packages/core/src/index.ts
  packages/core/src/middleware/koa-spa-proxy.ts
Labels: enhancement, size/s

#629 refactor(core): allow read private key from env
  packages/core/src/env-set/oidc.ts
Labels: enhancement, size/s

#650 fix(console): ac iterations fixes
  packages/console/src/components/AppContent/components/Sidebar/components/Contact/index.module.scss
  packages/console/src/components/AppContent/components/Sidebar/components/Contact/index.tsx
  packages/console/src/components/CopyToClipboard/index.module.scss
  packages/console/src/components/CopyToClipboard/index.tsx
  packages/console/src/components/Pagination/index.module.scss
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/console/src/pages/ApiResources/index.module.scss
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/Applications/index.module.scss
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/pages/Users/index.module.scss
  packages/console/src/scss/_colors.scss
Labels: bugfix, size/s

#653 fix(core): remove useless todo comment
  packages/core/src/oidc/init.test.ts
Labels: bugfix, size/xs

#644 feat(jest-config): init package
  packages/core/jest.config.js
  packages/core/jest.config.ts
  packages/core/package.json
  packages/jest-config/jest.config.ts
  packages/jest-config/package.json
  packages/jest-config/tsconfig.json
  packages/ui/jest.config.ts
  packages/ui/package.json
  pnpm-lock.yaml
Labels: feature, size/m

#652 fix(ui): fix overlay
  packages/ui/src/components/AppContent/index.module.scss
Labels: bugfix, size/xs

#642 feat(core): wrap @logto/shared and @logto/connector-types
  packages/connector-types/package.json
  packages/connector-types/src/index.ts
  packages/connector-types/tsconfig.build.json
  packages/connector-types/tsconfig.json
  packages/schemas/package.json
  packages/schemas/src/db-entries/connector.ts
  packages/schemas/src/db-entries/custom-types.ts
  packages/schemas/src/types/connector.ts
  packages/schemas/tables/connectors.sql
  packages/shared/package.json
  packages/shared/src/index.ts
  packages/shared/tsconfig.build.json
  packages/shared/tsconfig.json
  pnpm-lock.yaml
Labels: feature, size/l

#657 chore: align author
  packages/cli/package.json
  packages/connector-types/package.json
  packages/console/package.json
  packages/core/package.json
  packages/jest-config/package.json
  packages/phrases/package.json
  packages/schemas/package.json
  packages/shared/package.json
Labels: chore, size/s

#651 refactor(ui): refactor ui form
  packages/ui/src/containers/CreateAccount/index.tsx
  packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
  packages/ui/src/containers/UsernameSignin/index.tsx
  packages/ui/src/hooks/use-form.ts
  packages/ui/src/utils/field-validations.ts
  packages/ui/src/utils/index.ts
Labels: enhancement, size/l

#655 feat(ui): render page using sign-in exp settings
  packages/phrases/src/locales/zh-cn.ts
  packages/ui/src/__mocks__/logto.tsx
  packages/ui/src/components/ConfirmModal/index.module.scss
  packages/ui/src/components/ConfirmModal/index.tsx
  packages/ui/src/components/Input/phoneInput.module.scss
  packages/ui/src/containers/Passwordless/index.module.scss
  packages/ui/src/containers/SignInMethodsLink/index.tsx
  packages/ui/src/containers/SocialSignIn/PrimarySocialSignIn.test.tsx
  packages/ui/src/containers/SocialSignIn/PrimarySocialSignIn.tsx
  packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.test.tsx
  packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.tsx
  packages/ui/src/containers/SocialSignIn/SocialSignInPopUp.tsx
  packages/ui/src/containers/UsernameSignin/index.module.scss
  packages/ui/src/hooks/use-social.ts
  packages/ui/src/pages/SignIn/index.module.scss
  packages/ui/src/pages/SignIn/index.test.tsx
  packages/ui/src/pages/SignIn/index.tsx
  packages/ui/src/pages/SignIn/registry.tsx
  packages/ui/src/scss/modal.module.scss
  packages/ui/src/types/index.ts
  packages/ui/src/utils/sign-in-experience.ts
Labels: feature, size/l

#643 feat(core): wrap alipay web connector
  packages/connector-alipay/jest.config.ts
  packages/connector-alipay/package.json
  packages/connector-alipay/src/README.md
  packages/connector-alipay/src/config-template.md
  packages/connector-alipay/src/constant.ts
  packages/connector-alipay/src/index.test.ts
  packages/connector-alipay/src/index.ts
  packages/connector-alipay/src/mock.ts
  packages/connector-alipay/src/types.ts
  packages/connector-alipay/src/utils.test.ts
  packages/connector-alipay/src/utils.ts
  packages/connector-alipay/tsconfig.base.json
  packages/connector-alipay/tsconfig.build.json
  packages/connector-alipay/tsconfig.json
  packages/connector-alipay/tsconfig.test.json
  packages/connector-types/src/index.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#656 refactor(core,schemas): make it type-safer to log
  packages/core/package.json
  packages/core/src/middleware/koa-log.test.ts
  packages/core/src/middleware/koa-log.ts
  packages/core/src/routes/session.test.ts
  packages/core/src/routes/session.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/types/log.ts
  pnpm-lock.yaml
Labels: enhancement, feature, size/m

#601 feat(core,schemas): log register
  packages/core/src/routes/session.test.ts
  packages/core/src/routes/session.ts
  packages/schemas/src/types/log.ts
Labels: feature, size/s

#664 feat(ui): add social sign-in binding page
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/ui/src/App.tsx
  packages/ui/src/apis/index.test.ts
  packages/ui/src/apis/social.ts
  packages/ui/src/components/NavBar/index.module.scss
  packages/ui/src/components/NavBar/index.tsx
  packages/ui/src/containers/SocialCreateAccount/index.module.scss
  packages/ui/src/containers/SocialCreateAccount/index.test.tsx
  packages/ui/src/containers/SocialCreateAccount/index.tsx
  packages/ui/src/pages/SocialRegister/index.module.scss
  packages/ui/src/pages/SocialRegister/index.test.tsx
  packages/ui/src/pages/SocialRegister/index.tsx
Labels: feature, size/l

#662 feat(console): sign in experience setup others tab
  packages/console/src/pages/SignInExperience/components/LanguagesForm.tsx
  packages/console/src/pages/SignInExperience/index.tsx
  packages/console/src/pages/SignInExperience/types.ts
  packages/console/src/pages/SignInExperience/utilities.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature, size/m

#669 refactor(ui): refactor signin method link
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/ui/src/containers/SignInMethodsLink/index.module.scss
  packages/ui/src/containers/SignInMethodsLink/index.tsx
  packages/ui/src/pages/SignIn/registry.tsx
Labels: enhancement, size/s

#665 refactor(core): add `manyRows()` for queries
  packages/core/src/database/utils.ts
  packages/core/src/queries/application.ts
  packages/core/src/queries/connector.ts
  packages/core/src/queries/resource.ts
Labels: enhancement, size/s

#663 refactor: move cli -> core
  package.json
  packages/cli/bin/run.js
  packages/cli/package.json
  packages/cli/src/commands/database/index.ts
  packages/cli/src/commands/database/utilities.ts
  packages/cli/src/include.d/slonik-interceptor-preset.d.ts
  packages/cli/src/index.ts
  packages/cli/tsconfig.json
  packages/core/package.json
  packages/core/src/database/row-count.ts
  packages/core/src/database/seed.ts
  packages/core/src/database/utils.ts
  packages/core/src/env-set/create-pool-by-env.ts
  packages/core/src/env-set/index.ts
  packages/core/src/queries/application.ts
  packages/core/src/queries/connector.ts
  packages/core/src/queries/resource.ts
  pnpm-lock.yaml
Labels: enhancement, size/l

#672 feat(core): wrap facebook connector
  packages/connector-facebook/README.md
  packages/connector-facebook/docs/config-template.md
  packages/connector-facebook/jest.config.ts
  packages/connector-facebook/package.json
  packages/connector-facebook/src/constant.ts
  packages/connector-facebook/src/index.test.ts
  packages/connector-facebook/src/index.ts
  packages/connector-facebook/src/mock.ts
  packages/connector-facebook/tsconfig.base.json
  packages/connector-facebook/tsconfig.build.json
  packages/connector-facebook/tsconfig.json
  packages/connector-facebook/tsconfig.test.json
  pnpm-lock.yaml
Labels: feature, size/l

#675 fix(console): remove plain CopyToClipboard padding
  packages/console/src/components/CopyToClipboard/index.module.scss
Labels: bugfix, size/xs

#671 feat(ui): add bind social account flow
  packages/ui/src/apis/index.test.ts
  packages/ui/src/apis/sign-in.ts
  packages/ui/src/containers/PasscodeValidation/index.test.tsx
  packages/ui/src/containers/PasscodeValidation/index.tsx
  packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
  packages/ui/src/containers/SocialCreateAccount/index.module.scss
  packages/ui/src/containers/SocialCreateAccount/index.test.tsx
  packages/ui/src/containers/SocialCreateAccount/index.tsx
  packages/ui/src/containers/UsernameSignin/index.test.tsx
  packages/ui/src/containers/UsernameSignin/index.tsx
  packages/ui/src/hooks/use-bind-social.ts
  packages/ui/src/types/index.ts
  packages/ui/src/utils/index.test.ts
  packages/ui/src/utils/index.ts
Labels: feature, size/m

#661 fix(console): new ui in save changes footer
  packages/console/src/pages/ApiResourceDetails/index.module.scss
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/console/src/pages/ApplicationDetails/index.module.scss
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/Connectors/components/CreateForm/index.tsx
  packages/console/src/pages/Settings/index.module.scss
  packages/console/src/pages/Settings/index.tsx
  packages/console/src/pages/SignInExperience/index.module.scss
  packages/console/src/pages/SignInExperience/index.tsx
  packages/console/src/pages/UserDetails/index.module.scss
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/scss/details.module.scss
Labels: bugfix, size/l

#678 fix(console): ui fixes
  packages/console/src/components/ActionMenu/index.module.scss
  packages/console/src/components/ActionMenu/index.tsx
  packages/console/src/components/ActionMenu/use-position.ts
  packages/console/src/components/CopyToClipboard/index.module.scss
  packages/console/src/components/CopyToClipboard/index.tsx
  packages/console/src/components/Dropdown/DropdownItem.module.scss
  packages/console/src/components/Dropdown/index.module.scss
  packages/console/src/components/Dropdown/index.tsx
  packages/console/src/components/TabNav/TabNavLink.module.scss
  packages/console/src/components/TabNav/index.module.scss
  packages/console/src/icons/Delete.tsx
  packages/console/src/icons/Reset.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: bugfix, size/m

#668 chore: download and install logto
  install.js
  package.json
Labels: chore, size/s

#677 fix(core): update timestamp field with millisecond precision
  packages/core/src/database/utils.test.ts
  packages/core/src/database/utils.ts
  packages/core/src/queries/oidc-model-instance.test.ts
Labels: bugfix, size/s

#680 refactor(ui): update api lang header
  packages/ui/src/apis/api.ts
  packages/ui/src/apis/consent.ts
  packages/ui/src/apis/register.ts
  packages/ui/src/apis/settings.ts
  packages/ui/src/apis/sign-in.ts
  packages/ui/src/apis/social.ts
Labels: enhancement, size/s

#683 fix(ut): fix ut
  packages/ui/src/apis/index.test.ts
Labels: bugfix, size/xs

#681 refactor(core): use esm in core
  packages/core/package.json
  packages/core/tsconfig.json
  packages/jest-config/jest.config.ts
Labels: enhancement, size/s
