Repository logto-io/logto, pull requests merged in 2022-03, with the labels that each got.

#295 test(core): aliyun-dm
  packages/core/src/connectors/aliyun-dm/index.test.ts
  packages/core/src/connectors/aliyun-dm/index.ts
Labels: testing

#301 chore(phrases): fix typos in locales/en.ts
  packages/phrases/src/locales/en.ts
Labels: chore

#302 refactor(core): session tests
  packages/core/src/routes/session.test.ts
Labels: enhancement

#304 test(core): session consent
  packages/core/src/routes/session.test.ts
Labels: testing

#298 feat(console): sidebar
  packages/console/package.json
  packages/console/src/App.module.scss
  packages/console/src/App.tsx
  packages/console/src/components/Sidebar/components/Item/index.module.scss
  packages/console/src/components/Sidebar/components/Item/index.tsx
  packages/console/src/components/Sidebar/components/Section/index.module.scss
  packages/console/src/components/Sidebar/components/Section/index.tsx
  packages/console/src/components/Sidebar/consts.ts
  packages/console/src/components/Sidebar/icons/BarGraph.tsx
  packages/console/src/components/Sidebar/icons/Bolt.tsx
  packages/console/src/components/Sidebar/icons/Box.tsx
  packages/console/src/components/Sidebar/icons/Cloud.tsx
  packages/console/src/components/Sidebar/icons/Connection.tsx
  packages/console/src/components/Sidebar/icons/Document.tsx
  packages/console/src/components/Sidebar/icons/Gear.tsx
  packages/console/src/components/Sidebar/icons/Help.tsx
  packages/console/src/components/Sidebar/icons/List.tsx
  packages/console/src/components/Sidebar/icons/UserProfile.tsx
  packages/console/src/components/Sidebar/icons/Web.tsx
  packages/console/src/components/Sidebar/index.module.scss
  packages/console/src/components/Sidebar/index.tsx
  packages/console/src/i18n/init.ts
  packages/console/src/include.d/react-i18next.d.ts
  packages/console/src/scss/_underscore.scss
  packages/console/src/scss/normalized.scss
  packages/phrases/src/index.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/ui/package.json
  pnpm-lock.yaml
Labels: feature

#299 test(core): add UTs for session routes
  packages/core/src/routes/session.test.ts
  packages/core/src/routes/session.ts
Labels: feature, testing

#306 feat(core): connect console
  package.json
  packages/console/package.json
  packages/core/src/app/init.test.ts
  packages/core/src/app/init.ts
  packages/core/src/env/consts.ts
  packages/core/src/middleware/koa-spa-proxy.test.ts
  packages/core/src/middleware/koa-spa-proxy.ts
  packages/core/src/middleware/koa-ui-proxy.test.ts
  packages/core/src/middleware/koa-ui-proxy.ts
  packages/ui/package.json
Labels: feature

#310 feat(console): topbar
  packages/console/src/App.module.scss
  packages/console/src/assets/images/logo.svg
  packages/console/src/components/Sidebar/components/Item/index.module.scss
  packages/console/src/components/Topbar/index.module.scss
  packages/console/src/components/Topbar/index.tsx
  packages/console/src/scss/_underscore.scss
Labels: feature

#309 feat(console): active tab by route
  packages/console/package.json
  packages/console/src/App.tsx
  packages/console/src/components/Sidebar/components/Item/index.module.scss
  packages/console/src/components/Sidebar/components/Item/index.tsx
  packages/console/src/components/Sidebar/index.tsx
  packages/console/src/components/Sidebar/utils.ts
  packages/console/src/index.tsx
  pnpm-lock.yaml
Labels: feature

#311 feat(console): theme
  packages/console/src/App.module.scss
  packages/console/src/App.tsx
  packages/console/src/components/AppContent/index.module.scss
  packages/console/src/components/AppContent/index.tsx
  packages/console/src/components/Sidebar/components/Item/index.module.scss
  packages/console/src/components/Topbar/index.module.scss
  packages/console/src/scss/_underscore.scss
  packages/console/src/scss/normalized.scss
Labels: feature

#312 fix(console): set base url when needed
  packages/console/src/App.tsx
  packages/console/src/components/Sidebar/components/Item/index.tsx
  packages/console/src/include.d/node.d.ts
  packages/core/src/middleware/koa-spa-proxy.ts
Labels: bugfix

#314 fix(console): tab route link
  packages/console/src/components/Sidebar/components/Item/index.tsx
  packages/console/src/components/Sidebar/index.tsx
Labels: bugfix

#315 refactor(console): title i18n
  packages/console/src/components/Topbar/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: enhancement

#316 feat(console): applications layout
  packages/console/src/App.module.scss
  packages/console/src/App.tsx
  packages/console/src/components/AppContent/index.module.scss
  packages/console/src/components/Button/index.module.scss
  packages/console/src/components/Button/index.tsx
  packages/console/src/components/Card/index.module.scss
  packages/console/src/components/CardTitle/index.module.scss
  packages/console/src/components/CardTitle/index.tsx
  packages/console/src/pages/Applications/index.module.scss
  packages/console/src/pages/Applications/index.tsx
  packages/phrases/src/index.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#317 feat(console): init table
  packages/console/src/assets/images/default-placeholder.svg
  packages/console/src/components/AppContent/index.module.scss
  packages/console/src/components/Button/index.module.scss
  packages/console/src/components/CopyToClipboard/index.module.scss
  packages/console/src/components/CopyToClipboard/index.tsx
  packages/console/src/components/ImagePlaceholder/index.module.scss
  packages/console/src/components/ImagePlaceholder/index.tsx
  packages/console/src/components/ItemPreview/index.module.scss
  packages/console/src/components/ItemPreview/index.tsx
  packages/console/src/pages/Applications/index.module.scss
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/scss/_underscore.scss
  packages/console/src/scss/normalized.scss
Labels: feature

#319 fix(console): styles
  packages/console/src/components/AppContent/index.module.scss
  packages/console/src/components/CopyToClipboard/index.module.scss
  packages/console/src/components/CopyToClipboard/index.tsx
  packages/console/src/components/ItemPreview/index.module.scss
Labels: bugfix

#318 refactor(console): update sidebar styles
  packages/console/src/components/Sidebar/components/Item/index.module.scss
  packages/console/src/components/Sidebar/components/Section/index.module.scss
  packages/console/src/components/Sidebar/icons/BarGraph.tsx
  packages/console/src/components/Sidebar/icons/Bolt.tsx
  packages/console/src/components/Sidebar/icons/Box.tsx
  packages/console/src/components/Sidebar/icons/Cloud.tsx
  packages/console/src/components/Sidebar/icons/Connection.tsx
  packages/console/src/components/Sidebar/icons/Document.tsx
  packages/console/src/components/Sidebar/icons/Gear.tsx
  packages/console/src/components/Sidebar/icons/Help.tsx
  packages/console/src/components/Sidebar/icons/List.tsx
  packages/console/src/components/Sidebar/icons/UserProfile.tsx
  packages/console/src/components/Sidebar/icons/Web.tsx
  packages/console/src/components/Sidebar/index.module.scss
Labels: enhancement

#320 feat(console): retrieve applications from api
  packages/console/package.json
  packages/console/src/App.tsx
  packages/console/src/components/ItemPreview/index.tsx
  packages/console/src/pages/Applications/index.module.scss
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/swr/index.ts
  packages/console/src/types/applications.ts
  packages/core/src/include.d/koa.d.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  pnpm-lock.yaml
Labels: feature

#322 feat(console): api resources list page
  packages/console/src/pages/ApiResources/index.module.scss
  packages/console/src/pages/ApiResources/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#328 test(core): fix typos in connectors/*/index.test.ts
  packages/core/src/connectors/github/index.test.ts
  packages/core/src/connectors/google/index.test.ts
Labels: chore, testing

#329 refactor(core): remove unnecessary check in github and aliyun-sms connector
  packages/core/src/connectors/aliyun-sms/index.ts
  packages/core/src/connectors/github/index.test.ts
  packages/core/src/connectors/github/index.ts
Labels: enhancement

#330 chore(core): add TODO comments for adding the real connector logo URL
  packages/core/src/connectors/aliyun-dm/index.ts
  packages/core/src/connectors/aliyun-sms/index.ts
  packages/core/src/connectors/github/index.ts
  packages/core/src/connectors/google/index.ts
Labels: chore

#331 feat(console): init connector page
  packages/console/src/App.tsx
  packages/console/src/pages/Connectors/Connector.tsx
  packages/core/src/connectors/types.ts
  packages/core/src/routes/connector.ts
  packages/schemas/src/types/connector.ts
  packages/schemas/src/types/index.ts
Labels: feature

#326 feat(core): add forgot password send passcode to phone route
  packages/core/src/lib/user.test.ts
  packages/core/src/lib/user.ts
  packages/core/src/routes/session.test.ts
  packages/core/src/routes/session.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/schemas/src/db-entries/custom-types.ts
  packages/schemas/tables/user_logs.sql
Labels: feature

#333 refactor(core): simplify check-and-throw-ConnectorError with assertThat
  packages/core/src/connectors/aliyun-dm/index.ts
  packages/core/src/connectors/aliyun-sms/index.ts
  packages/core/src/connectors/github/index.ts
  packages/core/src/connectors/google/index.ts
Labels: enhancement

#323 feat(console): implement tooltip and integrate with copy
  packages/console/package.json
  packages/console/src/components/CopyToClipboard/index.module.scss
  packages/console/src/components/CopyToClipboard/index.tsx
  packages/console/src/components/Tooltip/index.module.scss
  packages/console/src/components/Tooltip/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/ui/package.json
  pnpm-lock.yaml
Labels: feature

#332 feat(console): init connectors
  packages/console/src/App.tsx
  packages/console/src/pages/Connectors/index.module.scss
  packages/console/src/pages/Connectors/index.tsx
  packages/core/src/connectors/aliyun-dm/index.ts
  packages/core/src/connectors/aliyun-sms/index.ts
  packages/core/src/connectors/github/index.ts
  packages/core/src/connectors/google/index.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#321 feat(core): facebook connector
  packages/core/src/connectors/facebook/constant.ts
  packages/core/src/connectors/facebook/index.test.ts
  packages/core/src/connectors/facebook/index.ts
  packages/core/src/connectors/index.ts
Labels: feature

#324 feat(console): init app create form
  package.json
  packages/console/package.json
  packages/console/src/components/AppContent/index.module.scss
  packages/console/src/components/AppContent/index.tsx
  packages/console/src/components/Card/index.tsx
  packages/console/src/components/FormField/index.module.scss
  packages/console/src/components/FormField/index.tsx
  packages/console/src/components/RadioGroup/Radio.tsx
  packages/console/src/components/RadioGroup/index.module.scss
  packages/console/src/components/RadioGroup/index.tsx
  packages/console/src/icons/Close.tsx
  packages/console/src/index.tsx
  packages/console/src/pages/Applications/components/CreateForm/index.module.scss
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/Applications/components/TypeDescription/index.module.scss
  packages/console/src/pages/Applications/components/TypeDescription/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/scss/modal.module.scss
  packages/console/src/types/applications.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/ui/src/components/AppContent/index.module.scss
  pnpm-lock.yaml
Labels: feature

#327 feat(console): app details header
  packages/console/src/App.tsx
  packages/console/src/assets/images/default-placeholder.svg
  packages/console/src/components/AppContent/index.module.scss
  packages/console/src/components/ImagePlaceholder/index.module.scss
  packages/console/src/components/ImagePlaceholder/index.tsx
  packages/console/src/components/TextButton/index.module.scss
  packages/console/src/pages/ApplicationDetails/icons/Back.tsx
  packages/console/src/pages/ApplicationDetails/index.module.scss
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#325 feat(console): app create form
  packages/console/package.json
  packages/console/src/components/AppContent/index.module.scss
  packages/console/src/components/Button/index.tsx
  packages/console/src/components/FormField/index.module.scss
  packages/console/src/components/FormField/index.tsx
  packages/console/src/components/RadioGroup/index.module.scss
  packages/console/src/components/RadioGroup/index.tsx
  packages/console/src/components/TextInput/index.module.scss
  packages/console/src/components/TextInput/index.tsx
  packages/console/src/pages/Applications/components/CreateForm/index.module.scss
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/Applications/components/TypeDescription/index.module.scss
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/scss/modal.module.scss
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  pnpm-lock.yaml
Labels: feature

#337 feat(core): only allow one enabled sms/email
  packages/core/src/routes/connector.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#339 chore: upgrade configs
  packages/console/package.json
  packages/core/package.json
  packages/phrases/package.json
  packages/schemas/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: chore

#334 feat(core): post /session/forgot-password/phone/verify-passcode-and-reset-password
  packages/core/src/routes/session.test.ts
  packages/core/src/routes/session.ts
Labels: feature

#335 feat(ui): add Branding component
  packages/console/src/scss/_underscore.scss
  packages/ui/src/__mocks__/logto.tsx
  packages/ui/src/components/AppContent/index.module.scss
  packages/ui/src/components/BrandingHeader/index.module.scss
  packages/ui/src/components/BrandingHeader/index.test.tsx
  packages/ui/src/components/BrandingHeader/index.tsx
  packages/ui/src/pages/Register/index.module.scss
  packages/ui/src/pages/SignIn/index.module.scss
  packages/ui/src/scss/_underscore.scss
Labels: feature

#341 feat(console): applications list navigation
  packages/console/src/pages/Applications/index.tsx
Labels: feature

#340 refactor(console): improve create app form ux
  packages/console/src/components/RadioGroup/Radio.tsx
  packages/console/src/components/RadioGroup/index.module.scss
  packages/console/src/components/RadioGroup/index.tsx
  packages/console/src/pages/Applications/components/CreateForm/index.module.scss
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: enhancement

#338 feat(console): connectors
  packages/console/src/App.tsx
  packages/console/src/assets/images/social-connectors-placeholder.svg
  packages/console/src/components/AppContent/index.module.scss
  packages/console/src/components/Sidebar/index.tsx
  packages/console/src/components/Status/index.module.scss
  packages/console/src/components/Status/index.tsx
  packages/console/src/components/TabNav/TabNavLink.module.scss
  packages/console/src/components/TabNav/TabNavLink.tsx
  packages/console/src/components/TabNav/index.module.scss
  packages/console/src/components/TabNav/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorName.module.scss
  packages/console/src/pages/Connectors/components/ConnectorName.tsx
  packages/console/src/pages/Connectors/components/ConnectorRow.tsx
  packages/console/src/pages/Connectors/index.module.scss
  packages/console/src/pages/Connectors/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#343 feat(console): create resource page
  packages/console/src/pages/ApiResources/components/CreateForm/index.module.scss
  packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/scss/_underscore.scss
Labels: feature

#349 feat(console): default button style
  packages/console/src/components/AppContent/index.module.scss
  packages/console/src/components/Button/index.module.scss
  packages/console/src/components/Button/index.tsx
  packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorRow.tsx
  packages/console/src/pages/Connectors/index.tsx
Labels: feature

#342 feat(ui): update input field
  packages/ui/src/components/AppContent/index.module.scss
  packages/ui/src/components/BrandingHeader/index.module.scss
  packages/ui/src/components/Icons/CloseIcon.tsx
  packages/ui/src/components/Input/index.module.scss
  packages/ui/src/components/Input/index.test.tsx
  packages/ui/src/components/Input/index.tsx
  packages/ui/src/pages/SignIn/index.module.scss
  packages/ui/src/pages/SignIn/index.tsx
  packages/ui/src/scss/_underscore.scss
Labels: feature

#345 refactor(console): support `to` in `<ItemPreview>`
  packages/console/src/components/ItemPreview/index.module.scss
  packages/console/src/components/ItemPreview/index.tsx
  packages/console/src/pages/Applications/index.tsx
Labels: enhancement

#346 feat(console): conditional navigation after create app
  packages/console/src/pages/Applications/index.tsx
Labels: feature

#352 feat(console): api resource details
  packages/console/src/App.tsx
  packages/console/src/pages/ApiResourceDetails/index.module.scss
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/console/src/pages/ApiResources/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#351 feat(console): connector details readme
  packages/console/src/pages/ConnectorDetails/index.module.scss
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/scss/drawer.module.scss
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#357 test(core): add UT for connector route
  packages/core/src/routes/connector.test.ts
  packages/core/src/utils/mock.ts
Labels: testing

#356 fix(console): page layout issues
  .gitignore
  packages/console/src/App.module.scss
  packages/console/src/components/Card/index.module.scss
  packages/console/src/components/TabNav/index.tsx
  packages/console/src/components/Topbar/index.module.scss
  packages/console/src/pages/ApiResources/index.module.scss
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/Applications/index.module.scss
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorRow.tsx
  packages/console/src/pages/Connectors/index.module.scss
  packages/console/src/pages/Connectors/index.tsx
  packages/console/src/scss/normalized.scss
Labels: bugfix

#354 feat(console): show toast after app created
  packages/console/package.json
  packages/console/src/App.tsx
  packages/console/src/components/AppContent/index.module.scss
  packages/console/src/components/Toast/index.module.scss
  packages/console/src/components/Toast/index.tsx
  packages/console/src/components/Tooltip/index.module.scss
  packages/console/src/pages/Applications/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  pnpm-lock.yaml
Labels: feature

#353 refactor(console): replace the text-filed css with mixin in the application create form
  packages/console/src/pages/Applications/components/CreateForm/index.module.scss
Labels: enhancement

#336 feat(core): add email forgot password flow (send/verify passcode)
  packages/core/src/routes/session.test.ts
  packages/core/src/routes/session.ts
Labels: feature

#358 feat(console): connector config
  packages/console/src/components/CodeEditor/index.module.scss
  packages/console/src/components/CodeEditor/index.tsx
  packages/console/src/components/TabNav/index.module.scss
  packages/console/src/pages/ConnectorDetails/index.module.scss
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/Connectors/index.module.scss
  packages/core/src/middleware/koa-connector-error-handle.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#360 refactor(console): restore paddings to Card component
  packages/console/src/components/Card/index.module.scss
  packages/console/src/pages/ApiResources/index.module.scss
  packages/console/src/pages/Applications/index.module.scss
  packages/console/src/pages/Connectors/index.module.scss
Labels: enhancement

#344 feat(core): findAllApplications order by createdAt desc
  packages/core/src/database/find-many.test.ts
  packages/core/src/database/find-many.ts
  packages/core/src/database/types.ts
  packages/core/src/queries/application.test.ts
  packages/core/src/queries/application.ts
Labels: feature

#363 fix(console): correct form field registry
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
Labels: bugfix

#355 refactor(console): buildDetailsLink in api resources page
  packages/console/src/pages/ApiResources/index.tsx
Labels: enhancement

#368 chore: upgrade packages
  package.json
  packages/console/package.json
  packages/core/package.json
  packages/phrases/package.json
  packages/schemas/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: chore

#365 revert(core): manually revert forgot password logic
  packages/core/src/lib/user.test.ts
  packages/core/src/lib/user.ts
  packages/core/src/routes/session.test.ts
  packages/core/src/routes/session.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/schemas/src/db-entries/custom-types.ts
  packages/schemas/tables/user_logs.sql
Labels: chore

#374 chore: update vscode settings
  .vscode/settings.json
Labels: chore

#366 feat(console): code editor component
  packages/console/package.json
  packages/console/src/components/CodeEditor/index.module.scss
  packages/console/src/components/CodeEditor/index.tsx
  packages/console/src/components/Status/index.tsx
  packages/console/src/pages/ConnectorDetails/index.tsx
  pnpm-lock.yaml
Labels: feature

#367 feat(console): connector sender test
  packages/console/src/components/Tooltip/index.tsx
  packages/console/src/pages/ConnectorDetails/components/SenderTester/index.module.scss
  packages/console/src/pages/ConnectorDetails/components/SenderTester/index.tsx
  packages/console/src/pages/ConnectorDetails/index.module.scss
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/utils/regex.ts
  packages/core/src/connectors/types.ts
  packages/core/src/routes/connector.test.ts
  packages/core/src/routes/connector.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#370 feat(console): wrap ky to handle response error
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/utilities/api.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#362 feat(core): add README.md for connectors
  packages/core/src/connectors/aliyun-dm/README.md
  packages/core/src/connectors/aliyun-dm/index.ts
  packages/core/src/connectors/aliyun-sms/README.md
  packages/core/src/connectors/aliyun-sms/index.ts
  packages/core/src/connectors/facebook/README.md
  packages/core/src/connectors/facebook/index.ts
  packages/core/src/connectors/github/README.md
  packages/core/src/connectors/github/index.ts
  packages/core/src/connectors/google/README.md
  packages/core/src/connectors/google/index.ts
  packages/core/src/lib/passcode.test.ts
  packages/core/src/routes/connector.test.ts
  packages/core/src/utils/mock.ts
  packages/schemas/src/types/connector.ts
Labels: feature

#377 fix(core): fix connector route tests
  packages/core/src/routes/connector.test.ts
Labels: feature, bugfix

#380 feat(console): init users page
  packages/console/src/App.tsx
  packages/console/src/components/Sidebar/consts.ts
  packages/console/src/pages/Users/components/CreateForm/index.module.scss
  packages/console/src/pages/Users/components/CreateForm/index.tsx
  packages/console/src/pages/Users/index.module.scss
  packages/console/src/pages/Users/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#376 refactor(console): application detail header
  packages/console/src/components/AppContent/index.module.scss
  packages/console/src/components/CopyToClipboard/index.tsx
  packages/console/src/components/Topbar/index.module.scss
  packages/console/src/pages/ApplicationDetails/index.module.scss
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/scss/_underscore.scss
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: enhancement

#378 feat(console): markdown component
  packages/console/package.json
  packages/console/src/components/Markdown/index.module.scss
  packages/console/src/components/Markdown/index.tsx
  packages/console/src/pages/ConnectorDetails/index.module.scss
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/core/src/connectors/github/README.md
  pnpm-lock.yaml
Labels: feature

#379 refactor(console): drawer component
  packages/console/src/components/Drawer/index.module.scss
  packages/console/src/components/Drawer/index.tsx
  packages/console/src/pages/ConnectorDetails/index.module.scss
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/scss/drawer.module.scss
Labels: enhancement

#364 feat(console): action menu
  packages/console/src/components/ActionMenu/ActionMenuButton.tsx
  packages/console/src/components/ActionMenu/ActionMenuItem.module.scss
  packages/console/src/components/ActionMenu/ActionMenuItem.tsx
  packages/console/src/components/ActionMenu/index.module.scss
  packages/console/src/components/ActionMenu/index.tsx
  packages/console/src/components/ActionMenu/use-position.ts
  packages/console/src/components/AppContent/index.module.scss
  packages/console/src/components/Button/index.tsx
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#381 feat(console): application details settings
  packages/console/src/App.tsx
  packages/console/src/components/CopyToClipboard/index.module.scss
  packages/console/src/pages/ApplicationDetails/index.module.scss
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#369 refactor(console): tonal palette colors and theme mixins
  packages/console/src/components/AppContent/index.module.scss
  packages/console/src/components/Button/index.module.scss
  packages/console/src/components/Card/index.module.scss
  packages/console/src/components/CopyToClipboard/index.module.scss
  packages/console/src/components/Status/index.module.scss
  packages/console/src/pages/Applications/components/TypeDescription/index.module.scss
  packages/console/src/scss/_colors.scss
  packages/console/src/scss/normalized.scss
Labels: enhancement

#373 feat(console): integrate React SDK
  .npmrc
  package.json
  packages/console/package.json
  packages/console/src/App.module.scss
  packages/console/src/App.tsx
  packages/console/src/components/AppContent/components/Sidebar/components/Item/index.module.scss
  packages/console/src/components/AppContent/components/Sidebar/components/Item/index.tsx
  packages/console/src/components/AppContent/components/Sidebar/components/Section/index.module.scss
  packages/console/src/components/AppContent/components/Sidebar/components/Section/index.tsx
  packages/console/src/components/AppContent/components/Sidebar/consts.ts
  packages/console/src/components/AppContent/components/Sidebar/icons/BarGraph.tsx
  packages/console/src/components/AppContent/components/Sidebar/icons/Bolt.tsx
  packages/console/src/components/AppContent/components/Sidebar/icons/Box.tsx
  packages/console/src/components/AppContent/components/Sidebar/icons/Cloud.tsx
  packages/console/src/components/AppContent/components/Sidebar/icons/Connection.tsx
  packages/console/src/components/AppContent/components/Sidebar/icons/Document.tsx
  packages/console/src/components/AppContent/components/Sidebar/icons/Gear.tsx
  packages/console/src/components/AppContent/components/Sidebar/icons/Help.tsx
  packages/console/src/components/AppContent/components/Sidebar/icons/List.tsx
  packages/console/src/components/AppContent/components/Sidebar/icons/UserProfile.tsx
  packages/console/src/components/AppContent/components/Sidebar/icons/Web.tsx
  packages/console/src/components/AppContent/components/Sidebar/index.module.scss
  packages/console/src/components/AppContent/components/Sidebar/index.tsx
  packages/console/src/components/AppContent/components/Sidebar/utils.ts
  packages/console/src/components/AppContent/components/Topbar/index.module.scss
  packages/console/src/components/AppContent/components/Topbar/index.tsx
  packages/console/src/components/AppContent/index.module.scss
  packages/console/src/components/AppContent/index.tsx
  packages/console/src/components/Content/index.module.scss
  packages/console/src/components/Content/index.tsx
  packages/console/src/pages/Callback/index.tsx
  packages/console/src/pages/GetStarted/index.tsx
  packages/core/src/oidc/init.ts
  pnpm-lock.yaml
Labels: feature

#382 feat(console): add outline and plain button types
  packages/console/src/components/Button/index.module.scss
  packages/console/src/components/Button/index.tsx
Labels: feature

#385 refactor(console): merge utilities folder
  packages/console/src/pages/ConnectorDetails/components/SenderTester/index.tsx
  packages/console/src/utilities/regex.ts
Labels: enhancement

#361 feat(schemas): sign-in-experiences
  packages/core/src/queries/sign-in-experience.test.ts
  packages/core/src/routes/sign-in-experience.test.ts
  packages/core/src/utils/mock.ts
  packages/schemas/src/db-entries/index.ts
  packages/schemas/src/db-entries/sign-in-experience.ts
  packages/schemas/src/db-entries/sign-in-method.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/tables/sign_in_experiences.sql
  packages/schemas/tables/sign_in_methods.sql
Labels: feature

#372 feat(ui): implement phonenumber input field
  packages/ui/jest.config.ts
  packages/ui/package.json
  packages/ui/src/assets/icons/arrow.svg
  packages/ui/src/assets/icons/close-icon.svg
  packages/ui/src/assets/icons/privacy-icon.svg
  packages/ui/src/components/AppContent/index.module.scss
  packages/ui/src/components/Icons/ClearIcon.tsx
  packages/ui/src/components/Icons/DownArrowIcon.tsx
  packages/ui/src/components/Icons/PrivacyIcon.tsx
  packages/ui/src/components/Icons/index.ts
  packages/ui/src/components/Input/PasswordInput.test.tsx
  packages/ui/src/components/Input/PasswordInput.tsx
  packages/ui/src/components/Input/PhoneInput.test.tsx
  packages/ui/src/components/Input/PhoneInput.tsx
  packages/ui/src/components/Input/index.module.scss
  packages/ui/src/components/Input/index.test.tsx
  packages/ui/src/components/Input/index.tsx
  packages/ui/src/components/Input/phoneInput.module.scss
  packages/ui/src/containers/PhoneInputProvider/index.test.tsx
  packages/ui/src/containers/PhoneInputProvider/index.tsx
  packages/ui/src/hooks/use-phone-number.ts
  packages/ui/src/include.d/dom.d.ts
  packages/ui/src/scss/_underscore.scss
  pnpm-lock.yaml
Labels: feature

#388 feat(console): create user
  packages/console/src/icons/Eye.tsx
  packages/console/src/pages/UserDetails/components/CreateSuccess.module.scss
  packages/console/src/pages/UserDetails/components/CreateSuccess.tsx
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/pages/Users/components/CreateForm/index.tsx
  packages/console/src/pages/Users/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#389 feat(console): delete api resource
  packages/console/src/components/ActionMenu/ActionMenuItem.tsx
  packages/console/src/components/ActionMenu/index.tsx
  packages/console/src/pages/ApiResourceDetails/components/DeleteForm/index.module.scss
  packages/console/src/pages/ApiResourceDetails/components/DeleteForm/index.tsx
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#383 feat(console): user details header
  packages/console/src/App.tsx
  packages/console/src/icons/Eye.tsx
  packages/console/src/pages/UserDetails/components/CreateSuccess.module.scss
  packages/console/src/pages/UserDetails/components/CreateSuccess.tsx
  packages/console/src/pages/UserDetails/index.module.scss
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/pages/Users/components/CreateForm/index.tsx
  packages/console/src/pages/Users/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#392 refactor(core): rename sign-in-experience api paths from sign-in-ex to sign-in-exp
  packages/core/src/routes/sign-in-experience.test.ts
  packages/core/src/routes/sign-in-experience.ts
Labels: enhancement

#386 feat(console): send access token in requests
  packages/console/package.json
  packages/console/src/App.tsx
  packages/console/src/consts/api.ts
  packages/console/src/consts/applications.ts
  packages/console/src/hooks/use-api.ts
  packages/console/src/hooks/use-swr-fetcher.ts
  packages/console/src/pages/ApiResourceDetails/components/DeleteForm/index.tsx
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/Callback/index.tsx
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/Connectors/index.tsx
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/pages/Users/components/CreateForm/index.tsx
  packages/console/src/pages/Users/index.tsx
  packages/console/src/swr/index.ts
  packages/console/src/utilities/api.ts
  pnpm-lock.yaml
Labels: feature

#395 feat(console): not found page
  packages/console/src/App.tsx
  packages/console/src/pages/NotFound/index.tsx
Labels: feature

#393 feat(console): button with title and icon
  packages/console/src/components/Button/index.module.scss
  packages/console/src/components/Button/index.tsx
  packages/console/src/icons/Search.tsx
Labels: feature

#384 feat(ui): add passcode input component
  packages/ui/src/components/AppContent/index.module.scss
  packages/ui/src/components/Input/PasswordInput.tsx
  packages/ui/src/components/Input/PhoneInput.tsx
  packages/ui/src/components/Input/index.module.scss
  packages/ui/src/components/Passcode/index.module.scss
  packages/ui/src/components/Passcode/index.test.tsx
  packages/ui/src/components/Passcode/index.tsx
  packages/ui/src/index.html
Labels: feature

#396 feat(console): icon button
  packages/console/src/components/Drawer/index.tsx
  packages/console/src/components/IconButton/index.module.scss
  packages/console/src/components/IconButton/index.tsx
  packages/console/src/icons/Close.tsx
  packages/console/src/icons/Eye.tsx
  packages/console/src/pages/ApiResourceDetails/components/DeleteForm/index.tsx
  packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/UserDetails/components/CreateSuccess.tsx
  packages/console/src/pages/Users/components/CreateForm/index.tsx
  packages/console/src/scss/_colors.scss
Labels: feature

#398 fix(console): change status component type
  packages/console/src/components/Status/index.tsx
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorRow.tsx
Labels: bugfix

#397 refactor(console): add dev origin to allowed CORS domain in OIDC
  packages/core/src/oidc/init.ts
Labels: enhancement

#399 fix(console): tab nav link font
  packages/console/src/components/TabNav/TabNavLink.module.scss
Labels: bugfix

#400 feat(ui): add button components
  packages/ui/src/components/AppContent/index.module.scss
  packages/ui/src/components/Button/SocialLinkButton.module.scss
  packages/ui/src/components/Button/SocialLinkButton.tsx
  packages/ui/src/components/Button/index.module.scss
  packages/ui/src/components/Button/index.test.tsx
  packages/ui/src/components/Button/index.tsx
  packages/ui/src/pages/Register/index.tsx
  packages/ui/src/pages/SignIn/index.module.scss
  packages/ui/src/pages/SignIn/index.tsx
Labels: feature

#402 refactor(console): update sidebar styles
  packages/console/src/components/AppContent/components/Sidebar/components/Item/index.module.scss
Labels: enhancement

#408 fix(console): icon button classname
  packages/console/src/components/IconButton/index.tsx
Labels: bugfix

#407 fix(console): button inline flex
  packages/console/src/components/Button/index.module.scss
  packages/console/src/components/Button/index.tsx
Labels: bugfix

#401 feat(console): add component UnnamedTrans
  packages/console/src/components/ItemPreview/index.tsx
  packages/console/src/components/UnnamedTrans/index.tsx
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorName.tsx
Labels: feature

#406 feat(console): delete user
  packages/console/src/components/ActionMenu/ActionMenuItem.module.scss
  packages/console/src/components/ActionMenu/ActionMenuItem.tsx
  packages/console/src/components/ActionMenu/index.module.scss
  packages/console/src/icons/Delete.tsx
  packages/console/src/icons/More.tsx
  packages/console/src/pages/ApiResourceDetails/components/DeleteForm/index.tsx
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/console/src/pages/UserDetails/components/DeleteForm.module.scss
  packages/console/src/pages/UserDetails/components/DeleteForm.tsx
  packages/console/src/pages/UserDetails/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#415 feat(console): add styles for code editor
  packages/console/src/components/CodeEditor/index.module.scss
  packages/console/src/components/CodeEditor/index.tsx
  packages/console/src/icons/Copy.tsx
Labels: feature

#404 feat(ui): textual ui components
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/ui/src/assets/icons/radio-button.svg
  packages/ui/src/components/AppContent/index.module.scss
  packages/ui/src/components/Divider/index.module.scss
  packages/ui/src/components/Divider/index.test.tsx
  packages/ui/src/components/Divider/index.tsx
  packages/ui/src/components/ErrorMessage/index.module.scss
  packages/ui/src/components/ErrorMessage/index.tsx
  packages/ui/src/components/Icons/RadioButtonIcon.tsx
  packages/ui/src/components/MessageBox/index.module.scss
  packages/ui/src/components/MessageBox/index.tsx
  packages/ui/src/components/TermsOfUse/index.module.scss
  packages/ui/src/components/TermsOfUse/index.test.tsx
  packages/ui/src/components/TermsOfUse/index.tsx
  packages/ui/src/components/TextLink/index.module.scss
  packages/ui/src/components/TextLink/index.test.tsx
  packages/ui/src/components/TextLink/index.tsx
  packages/ui/src/pages/Register/index.module.scss
  packages/ui/src/pages/Register/index.tsx
  packages/ui/src/pages/SignIn/index.module.scss
  packages/ui/src/pages/SignIn/index.tsx
  packages/ui/src/scss/_underscore.scss
Labels: feature

#413 test(core): connectors
  packages/core/src/connectors/index.test.ts
Labels: testing

#414 feat(console): change password
  packages/console/src/icons/Reset.tsx
  packages/console/src/pages/UserDetails/components/ResetPasswordForm.module.scss
  packages/console/src/pages/UserDetails/components/ResetPasswordForm.tsx
  packages/console/src/pages/UserDetails/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#387 feat(console): `add another` for redirect uris in application details
  packages/console/src/components/MultilineInput/index.module.scss
  packages/console/src/components/MultilineInput/index.tsx
  packages/console/src/components/TextButton/index.module.scss
  packages/console/src/icons/Minus.tsx
  packages/console/src/pages/ApplicationDetails/index.module.scss
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  pnpm-lock.yaml
Labels: feature

#416 fix(console): operation button align in api resource detail
  packages/console/src/pages/ApiResourceDetails/index.module.scss
  packages/console/src/pages/ApiResourceDetails/index.tsx
Labels: bugfix

#409 feat(console): show get started guide on application creation success
  packages/console/src/assets/images/high-five.svg
  packages/console/src/assets/images/tada.svg
  packages/console/src/components/AppContent/index.module.scss
  packages/console/src/components/CardTitle/index.tsx
  packages/console/src/components/IconButton/index.module.scss
  packages/console/src/components/RadioGroup/Radio.tsx
  packages/console/src/components/Spacer/index.module.scss
  packages/console/src/components/Spacer/index.tsx
  packages/console/src/icons/Close.tsx
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/Applications/components/GetStarted/index.module.scss
  packages/console/src/pages/Applications/components/GetStarted/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/scss/_colors.scss
  packages/console/src/scss/modal.module.scss
  packages/console/src/types/applications.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#394 feat(core): add wechat-web connector
  packages/core/src/connectors/facebook/index.test.ts
  packages/core/src/connectors/facebook/index.ts
  packages/core/src/connectors/github/index.test.ts
  packages/core/src/connectors/github/index.ts
  packages/core/src/connectors/google/index.test.ts
  packages/core/src/connectors/google/index.ts
  packages/core/src/connectors/index.test.ts
  packages/core/src/connectors/index.ts
  packages/core/src/connectors/types.ts
  packages/core/src/connectors/wechat/README.md
  packages/core/src/connectors/wechat/constant.ts
  packages/core/src/connectors/wechat/index.test.ts
  packages/core/src/connectors/wechat/index.ts
  packages/core/src/lib/social.ts
Labels: feature

#418 chore: update vscode settings
  .vscode/settings.json
Labels: chore

#403 feat(console): user details settings
  packages/console/src/components/AppContent/index.module.scss
  packages/console/src/pages/UserDetails/index.module.scss
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/utilities/json.ts
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#421 fix(console): add readonly style for text input
  packages/console/src/components/TextInput/index.module.scss
  packages/console/src/scss/_colors.scss
Labels: bugfix

#420 fix(console): api resource table data style
  packages/console/src/pages/ApiResources/index.tsx
Labels: bugfix

#424 feat(core): copy markdown files to build folder when building project
  packages/core/package.json
  pnpm-lock.yaml
Labels: feature

#419 feat(console): modal layout
  packages/console/src/components/ModalLayout/index.module.scss
  packages/console/src/components/ModalLayout/index.tsx
  packages/console/src/pages/ApiResourceDetails/components/DeleteForm/index.module.scss
  packages/console/src/pages/ApiResourceDetails/components/DeleteForm/index.tsx
  packages/console/src/scss/modal.module.scss
Labels: feature

#422 fix(core): fix response code for requesting WeChat APIs
  packages/core/src/connectors/wechat/index.test.ts
  packages/core/src/connectors/wechat/index.ts
Labels: bugfix

#435 refactor(console): refactor modals with modallayout
  .vscode/scss.code-snippets
  packages/console/src/components/ItemPreview/index.module.scss
  packages/console/src/components/ItemPreview/index.tsx
  packages/console/src/components/ModalLayout/index.module.scss
  packages/console/src/pages/ApiResources/components/CreateForm/index.module.scss
  packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/Applications/components/CreateForm/index.module.scss
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/UserDetails/components/CreateSuccess.module.scss
  packages/console/src/pages/UserDetails/components/CreateSuccess.tsx
  packages/console/src/pages/UserDetails/components/DeleteForm.module.scss
  packages/console/src/pages/UserDetails/components/DeleteForm.tsx
  packages/console/src/pages/UserDetails/components/ResetPasswordForm.tsx
  packages/console/src/pages/Users/components/CreateForm/index.module.scss
  packages/console/src/pages/Users/components/CreateForm/index.tsx
  packages/console/src/scss/_dimensions.scss
  packages/console/src/scss/_underscore.scss
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: enhancement

#434 feat(console): user details connectors
  packages/console/src/pages/UserDetails/components/UserConnectors.module.scss
  packages/console/src/pages/UserDetails/components/UserConnectors.tsx
  packages/console/src/pages/UserDetails/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/schemas/src/types/user.ts
Labels: feature

#433 feat(console): delete connector
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#425 feat(ui): add toast component
  packages/ui/src/assets/icons/close-icon.svg
  packages/ui/src/assets/icons/privacy-icon.svg
  packages/ui/src/components/AppContent/index.module.scss
  packages/ui/src/components/AppContent/index.tsx
  packages/ui/src/components/Icons/ClearIcon.tsx
  packages/ui/src/components/Toast/index.module.scss
  packages/ui/src/components/Toast/index.test.tsx
  packages/ui/src/components/Toast/index.tsx
  packages/ui/src/hooks/page-context.ts
  packages/ui/src/pages/SignIn/index.tsx
Labels: feature

#428 feat(console): add connector
  packages/console/src/components/ModalLayout/index.tsx
  packages/console/src/components/RadioGroup/Radio.tsx
  packages/console/src/components/RadioGroup/index.module.scss
  packages/console/src/pages/ConnectorDetails/index.module.scss
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorRow.tsx
  packages/console/src/pages/Connectors/components/SetupModal.module.scss
  packages/console/src/pages/Connectors/components/SetupModal.tsx
  packages/console/src/pages/Connectors/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#426 refactor(core): get sign-in experience
  packages/core/src/connectors/index.test.ts
  packages/core/src/connectors/index.ts
  packages/core/src/routes/sign-in-experience.test.ts
  packages/core/src/routes/sign-in-experience.ts
  packages/core/src/utils/mock.ts
Labels: enhancement

#444 fix(core): missing some commits
  packages/core/src/queries/sign-in-experience.test.ts
  packages/core/src/queries/sign-in-experience.ts
  packages/core/src/routes/sign-in-experience.test.ts
  packages/core/src/routes/sign-in-experience.ts
Labels: bugfix

#441 feat(console): table loading component
  packages/console/src/components/Table/ItemPreviewLoading.module.scss
  packages/console/src/components/Table/ItemPreviewLoading.tsx
  packages/console/src/components/Table/TableLoading.module.scss
  packages/console/src/components/Table/TableLoading.tsx
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/Connectors/index.tsx
  packages/console/src/pages/Users/index.tsx
Labels: feature

#439 feat(console): save changes in application detail page
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#442 feat(console): table error component
  packages/console/src/assets/images/table-error.svg
  packages/console/src/components/Table/TableError.module.scss
  packages/console/src/components/Table/TableError.tsx
  packages/console/src/hooks/use-api.ts
  packages/console/src/hooks/use-swr-fetcher.ts
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/Connectors/index.tsx
  packages/console/src/pages/UserDetails/components/UserConnectors.tsx
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/pages/Users/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#450 refactor(console): minor adjustments made to plain button styles
  packages/console/src/components/Button/index.module.scss
Labels: enhancement

#430 feat(core): order connectors by enabled desc, id asc
  packages/core/src/queries/connector.test.ts
  packages/core/src/queries/connector.ts
Labels: enhancement, feature

#429 refactor(core): make getConnectorInstances access DB only once
  packages/core/src/connectors/index.test.ts
  packages/core/src/connectors/index.ts
Labels: enhancement

#445 refactor(console): use colgroup in table
  packages/console/src/components/Card/index.module.scss
  packages/console/src/components/Table/TableLoading.tsx
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorRow.tsx
  packages/console/src/pages/Connectors/index.tsx
  packages/console/src/pages/Users/index.tsx
  packages/console/src/scss/normalized.scss
Labels: enhancement

#452 refactor(console): use nullable in form type
  packages/console/src/pages/UserDetails/index.tsx
Labels: enhancement

#437 feat(core): add DELETE /users/:userId/identities/:connectorId
  packages/core/src/queries/user.test.ts
  packages/core/src/queries/user.ts
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
  packages/core/src/utils/mock.ts
Labels: feature

#451 refactor(core): make initConnectors check existing connectors in DB once
  packages/core/src/connectors/index.test.ts
  packages/core/src/connectors/index.ts
  packages/core/src/queries/connector.test.ts
  packages/core/src/queries/connector.ts
Labels: enhancement

#449 feat(ui): implement Confirm Modal
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/ui/package.json
  packages/ui/src/components/AppContent/index.module.scss
  packages/ui/src/components/Button/index.module.scss
  packages/ui/src/components/Button/index.tsx
  packages/ui/src/components/ConfirmModal/index.module.scss
  packages/ui/src/components/ConfirmModal/index.tsx
  packages/ui/src/scss/modal.module.scss
  pnpm-lock.yaml
Labels: feature

#447 feat(ui): re-implement username signin page
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/ui/src/components/AppContent/index.module.scss
  packages/ui/src/components/BrandingHeader/index.tsx
  packages/ui/src/components/ErrorMessage/index.tsx
  packages/ui/src/components/Input/PasswordInput.test.tsx
  packages/ui/src/components/Input/PasswordInput.tsx
  packages/ui/src/components/Input/index.module.scss
  packages/ui/src/components/Input/index.test.tsx
  packages/ui/src/components/Input/index.tsx
  packages/ui/src/components/TermsOfUse/index.module.scss
  packages/ui/src/components/TermsOfUse/index.tsx
  packages/ui/src/containers/UsernameSignin/index.module.scss
  packages/ui/src/containers/UsernameSignin/index.test.tsx
  packages/ui/src/containers/UsernameSignin/index.tsx
  packages/ui/src/hooks/use-api.ts
  packages/ui/src/jest.setup.ts
  packages/ui/src/pages/Register/index.tsx
  packages/ui/src/pages/SignIn/index.module.scss
  packages/ui/src/pages/SignIn/index.test.tsx
  packages/ui/src/pages/SignIn/index.tsx
  packages/ui/src/scss/_underscore.scss
Labels: feature

#440 feat(console): modal-layout size limitation
  packages/console/src/components/ModalLayout/index.module.scss
  packages/console/src/components/ModalLayout/index.tsx
  packages/console/src/pages/ApiResourceDetails/components/DeleteForm/index.module.scss
  packages/console/src/pages/ApiResourceDetails/components/DeleteForm/index.tsx
  packages/console/src/pages/ApiResources/components/CreateForm/index.module.scss
  packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
  packages/console/src/pages/ApplicationDetails/components/DeleteForm/index.module.scss
  packages/console/src/pages/ApplicationDetails/components/DeleteForm/index.tsx
  packages/console/src/pages/Applications/components/CreateForm/index.module.scss
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/UserDetails/components/CreateSuccess.module.scss
  packages/console/src/pages/UserDetails/components/CreateSuccess.tsx
  packages/console/src/pages/UserDetails/components/DeleteForm.module.scss
  packages/console/src/pages/UserDetails/components/DeleteForm.tsx
  packages/console/src/pages/UserDetails/components/ResetPasswordForm.module.scss
  packages/console/src/pages/UserDetails/components/ResetPasswordForm.tsx
  packages/console/src/pages/Users/components/CreateForm/index.module.scss
  packages/console/src/pages/Users/components/CreateForm/index.tsx
  packages/console/src/scss/_dimensions.scss
Labels: feature

#432 feat(core): provide a means to fetch get-started markdown metadata
  packages/console/package.json
  packages/console/public/get-started/react/en/index.json
  packages/console/public/get-started/react/en/step1.md
  packages/console/public/get-started/react/en/step2.md
  packages/console/public/get-started/react/en/step3.md
  packages/console/public/get-started/react/en/step4.md
  packages/console/public/get-started/react/en/step5.md
  packages/console/public/get-started/react/zh-CN/index.json
  packages/console/public/get-started/react/zh-CN/step1.md
  packages/console/public/get-started/react/zh-CN/step2.md
  packages/console/public/get-started/react/zh-CN/step3.md
  packages/console/public/get-started/react/zh-CN/step4.md
  packages/console/public/get-started/react/zh-CN/step5.md
  packages/console/src/components/AppContent/index.module.scss
  packages/console/src/components/Card/index.module.scss
  packages/console/src/components/Card/index.tsx
  packages/console/src/components/CardTitle/index.tsx
  packages/console/src/hooks/use-api.ts
  packages/console/src/hooks/use-swr-fetcher.ts
  packages/console/src/icons/Arrow.tsx
  packages/console/src/icons/Tick.tsx
  packages/console/src/include.d/dom.d.ts
  packages/console/src/pages/Applications/components/GetStarted/index.module.scss
  packages/console/src/pages/Applications/components/GetStarted/index.tsx
  packages/console/src/scss/_colors.scss
  packages/console/src/utilities/markdown.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  pnpm-lock.yaml
Labels: feature

#453 feat(console): pagination
  packages/console/package.json
  packages/console/src/components/Button/index.tsx
  packages/console/src/components/DangerousRaw/index.tsx
  packages/console/src/components/Pagination/Next.tsx
  packages/console/src/components/Pagination/Previous.tsx
  packages/console/src/components/Pagination/index.module.scss
  packages/console/src/components/Pagination/index.tsx
  pnpm-lock.yaml
Labels: feature

#454 fix(console): prevent css overiding in table-loading
  packages/console/src/components/Table/TableLoading.module.scss
  packages/console/src/components/Table/TableLoading.tsx
Labels: bugfix

#446 feat(console): table empty state
  packages/console/src/assets/images/social-connectors-placeholder.svg
  packages/console/src/assets/images/table-empty.svg
  packages/console/src/components/Table/TableEmpty.module.scss
  packages/console/src/components/Table/TableEmpty.tsx
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/Connectors/index.tsx
  packages/console/src/pages/Users/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#448 feat(console): extract total number from headers for useSWR
  packages/console/src/hooks/use-swr-fetcher.ts
  packages/console/src/pages/Users/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#456 fix(console): align button icon size to 20
  packages/console/src/components/Button/index.module.scss
  packages/console/src/icons/More.tsx
Labels: bugfix

#455 refactor(console): the submit state of forms
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/UserDetails/components/ResetPasswordForm.tsx
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/pages/Users/components/CreateForm/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: enhancement

#464 refactor(console): remove zero-colspan
  packages/console/src/components/Table/TableEmpty.tsx
  packages/console/src/components/Table/TableError.tsx
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/Connectors/index.tsx
  packages/console/src/pages/UserDetails/components/UserConnectors.tsx
  packages/console/src/pages/Users/index.tsx
Labels: enhancement

#463 chore(console): update code comments in markdown util
  packages/console/src/utilities/markdown.ts
Labels: chore

#465 fix(core): error message interpolation
  packages/core/src/connectors/index.test.ts
  packages/core/src/connectors/index.ts
  packages/core/src/lib/social.ts
  packages/core/src/routes/session.test.ts
Labels: bugfix

#461 fix(core): fix WeChat web response code and related UTs
  packages/core/src/connectors/wechat/index.test.ts
  packages/core/src/connectors/wechat/index.ts
Labels: bugfix

#462 refactor(console): match design mockups by adjusting fonts, paddings, etc
  packages/console/src/components/ActionMenu/ActionMenuItem.module.scss
  packages/console/src/components/ActionMenu/index.module.scss
  packages/console/src/components/AppContent/components/Topbar/index.module.scss
  packages/console/src/components/AppContent/index.module.scss
  packages/console/src/components/AppContent/index.tsx
  packages/console/src/components/Button/index.module.scss
  packages/console/src/components/CardTitle/index.module.scss
  packages/console/src/components/CardTitle/index.tsx
  packages/console/src/components/CopyToClipboard/index.module.scss
  packages/console/src/components/FormField/index.module.scss
  packages/console/src/components/ItemPreview/index.module.scss
  packages/console/src/components/Markdown/index.module.scss
  packages/console/src/components/RadioGroup/index.module.scss
  packages/console/src/components/RadioGroup/index.tsx
  packages/console/src/components/TabNav/TabNavLink.module.scss
  packages/console/src/components/Table/TableEmpty.module.scss
  packages/console/src/components/Table/TableError.module.scss
  packages/console/src/components/TextButton/index.module.scss
  packages/console/src/components/TextInput/index.module.scss
  packages/console/src/components/Toast/index.module.scss
  packages/console/src/components/Tooltip/index.module.scss
  packages/console/src/icons/Tick.tsx
  packages/console/src/pages/ApiResourceDetails/components/DeleteForm/index.module.scss
  packages/console/src/pages/ApplicationDetails/components/DeleteForm/index.module.scss
  packages/console/src/pages/Applications/components/CreateForm/index.module.scss
  packages/console/src/pages/Applications/components/GetStarted/index.module.scss
  packages/console/src/pages/Applications/components/GetStarted/index.tsx
  packages/console/src/pages/Applications/components/TypeDescription/index.module.scss
  packages/console/src/pages/ConnectorDetails/components/SenderTester/index.module.scss
  packages/console/src/pages/Connectors/components/SetupModal.module.scss
  packages/console/src/pages/Connectors/index.module.scss
  packages/console/src/pages/UserDetails/components/CreateSuccess.module.scss
  packages/console/src/pages/UserDetails/components/UserConnectors.module.scss
  packages/console/src/scss/_fonts.scss
  packages/console/src/scss/_underscore.scss
  packages/console/src/scss/normalized.scss
  packages/ui/src/components/ConfirmModal/index.module.scss
  packages/ui/src/components/Divider/index.module.scss
  packages/ui/src/components/Toast/index.module.scss
Labels: enhancement

#458 feat(console): support icon in text-input
  packages/console/src/components/Search/index.module.scss
  packages/console/src/components/Search/index.tsx
  packages/console/src/components/TextInput/index.module.scss
  packages/console/src/components/TextInput/index.tsx
  packages/console/src/icons/Search.tsx
  packages/console/src/pages/Users/index.module.scss
  packages/console/src/pages/Users/index.tsx
  packages/core/src/queries/user.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature

#459 feat(ui): add password less related api
  packages/ui/src/apis/index.test.ts
  packages/ui/src/apis/register.ts
  packages/ui/src/apis/sign-in.ts
Labels: feature

#471 fix(core): did not mock test request which results in a timeout
  packages/core/src/connectors/wechat/index.test.ts
Labels: bugfix

#469 feat(ui): add passwordless container
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/ui/src/App.tsx
  packages/ui/src/components/Input/PhoneInput.tsx
  packages/ui/src/containers/Passwordless/EmailPasswordless.test.tsx
  packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.test.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
  packages/ui/src/containers/Passwordless/index.module.scss
  packages/ui/src/containers/Passwordless/index.tsx
  packages/ui/src/containers/PhoneInputProvider/index.test.tsx
  packages/ui/src/containers/PhoneInputProvider/index.tsx
  packages/ui/src/hooks/use-phone-number.ts
  packages/ui/src/pages/SecondarySignIn/index.module.scss
  packages/ui/src/pages/SecondarySignIn/index.tsx
Labels: feature

#473 feat(schemas): zod type guards of sign-in experience jsonb fields
  packages/core/package.json
  packages/core/src/utils/regex.ts
  packages/schemas/package.json
  packages/schemas/src/foundations/jsonb-types.ts
  pnpm-lock.yaml
Labels: feature

#474 chore: bump version of configs
  packages/console/package.json
  packages/core/package.json
  packages/core/src/include.d/koa-router.d.ts
  packages/core/src/routes/connector.test.ts
  packages/core/src/routes/session.test.ts
  packages/core/src/routes/session.ts
  packages/core/src/utils/mock.ts
  packages/phrases/package.json
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/schemas/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: chore

#478 feat(core): validate connector config before enabling
  packages/core/src/routes/connector.test.ts
  packages/core/src/routes/connector.ts
Labels: feature

#470 feat(core): add wechat-native connector
  packages/core/src/connectors/index.test.ts
  packages/core/src/connectors/index.ts
  packages/core/src/connectors/wechat-native/constant.ts
  packages/core/src/connectors/wechat-native/index.test.ts
  packages/core/src/connectors/wechat-native/index.ts
  packages/core/src/connectors/wechat/index.ts
Labels: feature
