Repository logto-io/logto, pull requests merged in 2022-11, with the labels that each got.

#2281 feat(core): continue sign in with social
  packages/core/src/routes/session/continue.test.ts
  packages/core/src/routes/session/continue.ts
  packages/core/src/routes/session/passwordless.test.ts
  packages/core/src/routes/session/social.test.ts
  packages/core/src/routes/session/social.ts
  packages/core/src/routes/session/utils.ts
  packages/integration-tests/tests/api/dashboard.test.ts
  packages/integration-tests/tests/api/logs.test.ts
  packages/integration-tests/tests/api/social-session.test.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
Labels: feature, size/l

#2289 fix(console): should not render when `watch` return `undefined` in sign up and sign in form
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/SignInForm.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/SignUpForm.tsx
  packages/console/src/pages/SignInExperience/types.ts
  packages/console/src/pages/SignInExperience/utilities.ts
Labels: bugfix, size/s

#2288 fix(ui): fix register page other methods link bug
  packages/ui/src/apis/api.test.ts
  packages/ui/src/apis/utils.ts
  packages/ui/src/containers/OtherMethodsLink/index.module.scss
  packages/ui/src/containers/OtherMethodsLink/index.tsx
  packages/ui/src/containers/PasscodeValidation/index.test.tsx
  packages/ui/src/containers/PasscodeValidation/use-passcode-validation-error-handler.ts
  packages/ui/src/containers/Passwordless/EmailPasswordless.test.tsx
  packages/ui/src/containers/Passwordless/PasswordlessSwitch.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.test.tsx
  packages/ui/src/containers/SocialCreateAccount/index.test.tsx
  packages/ui/src/containers/SocialCreateAccount/index.tsx
  packages/ui/src/pages/ForgotPassword/index.tsx
  packages/ui/src/pages/Register/Main.tsx
  packages/ui/src/pages/Register/index.test.tsx
  packages/ui/src/pages/Register/index.tsx
  packages/ui/src/pages/SecondaryRegister/index.tsx
  packages/ui/src/pages/SecondarySignIn/index.tsx
  packages/ui/src/pages/SignIn/Main.tsx
  packages/ui/src/pages/SignIn/index.tsx
  packages/ui/src/types/index.ts
Labels: bugfix, size/m

#2290 feat(core): check username
  packages/core/src/routes/session/password.test.ts
  packages/core/src/routes/session/password.ts
Labels: feature, size/s

#2292 refactor(ui): add new PasswordRegisterWithUsernamePage
  packages/ui/src/App.tsx
  packages/ui/src/containers/SetPassword/index.module.scss
  packages/ui/src/containers/SetPassword/index.test.tsx
  packages/ui/src/containers/SetPassword/index.tsx
  packages/ui/src/containers/UsernameRegister/index.tsx
  packages/ui/src/containers/UsernameSignIn/index.tsx
  packages/ui/src/hooks/use-form.ts
  packages/ui/src/pages/PasswordRegisterWithUsername/index.test.tsx
  packages/ui/src/pages/PasswordRegisterWithUsername/index.tsx
  packages/ui/src/pages/PasswordRegisterWithUsername/use-username-password-register.ts
  packages/ui/src/pages/ResetPassword/index.test.tsx
  packages/ui/src/pages/ResetPassword/index.tsx
  packages/ui/src/pages/ResetPassword/use-reset-password.ts
  packages/ui/src/types/guard.ts
Labels: enhancement, size/l

#2294 refactor(ui): update the check username api
  packages/ui/src/apis/register.ts
  packages/ui/src/containers/UsernameRegister/index.test.tsx
  packages/ui/src/containers/UsernameRegister/index.tsx
Labels: enhancement, size/s

#2273 feat(console): sign up and sign in change alert
  packages/console/package.json
  packages/console/src/pages/SignInExperience/components/SignInMethodsChangePreview.module.scss
  packages/console/src/pages/SignInExperience/components/SignInMethodsChangePreview.tsx
  packages/console/src/pages/SignInExperience/index.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignUpAndSignInDiffSection/DiffSegment.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignUpAndSignInDiffSection/SignInDiffSection.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignUpAndSignInDiffSection/SignUpDiffSection.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignUpAndSignInDiffSection/SocialTargetsDiffSection.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignUpAndSignInDiffSection/index.module.scss
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignUpAndSignInDiffSection/index.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignUpAndSignInDiffSection/types.ts
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignUpAndSignInDiffSection/utilities.ts
  packages/console/src/pages/SignInExperience/utilities.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
  pnpm-lock.yaml
Labels: feature, size/l

#2298 fix(console): correct sign-in method item state
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/SignInMethodItem.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/index.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/utilities.ts
Labels: bugfix, size/s

#2297 chore: ignore fly.toml
  .gitignore
Labels: chore, size/xs

#2291 feat: remove forgot password control
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/queries/sign-in-experience.test.ts
  packages/core/src/routes/session/forgot-password.test.ts
  packages/core/src/routes/session/forgot-password.ts
  packages/core/src/routes/sign-in-experience.test.ts
  packages/core/src/routes/sign-in-experience.ts
  packages/core/src/routes/well-known.ts
  packages/schemas/alterations/next-1667283640-remove-forgot-password.ts
  packages/schemas/src/seeds/sign-in-experience.ts
  packages/schemas/tables/sign_in_experiences.sql
  packages/ui/src/__mocks__/logto.tsx
Labels: feature, size/m

#2267 chore: config codespaces container
  .devcontainer/devcontainer.json
Labels: chore, size/s

#2306 feat(console): add setup sie notice for the connectors page
  packages/console/src/components/Alert/index.tsx
  packages/console/src/hooks/use-user-preferences.ts
  packages/console/src/pages/Connectors/components/SignInExperienceSetupNotice/index.module.scss
  packages/console/src/pages/Connectors/components/SignInExperienceSetupNotice/index.tsx
  packages/console/src/pages/Connectors/index.module.scss
  packages/console/src/pages/Connectors/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/connectors.ts
  packages/phrases/src/locales/en/translation/admin-console/general.ts
  packages/phrases/src/locales/fr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/fr/translation/admin-console/general.ts
  packages/phrases/src/locales/ko/translation/admin-console/connectors.ts
  packages/phrases/src/locales/ko/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/connectors.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
Labels: feature, size/s

#2310 Merge `master` into feature/sie-v2
  .devcontainer/devcontainer.json
  .github/workflows/main.yml
  .gitignore
  .gitpod.yml
  .vscode/settings.json
  packages/console/package.json
  packages/console/src/hooks/use-api.ts
  packages/console/src/hooks/use-position.ts
  packages/core/src/middleware/koa-auth.ts
  packages/core/src/routes/authn.test.ts
  packages/core/src/routes/authn.ts
  packages/demo-app/package.json
  packages/integration-tests/package.json
  packages/phrases-ui/src/locales/zh-cn.ts
  packages/phrases/src/locales/zh-cn/errors.ts
  packages/ui/src/components/Button/index.module.scss
  packages/ui/src/components/Button/index.tsx
  packages/ui/src/components/ConfirmModal/AcModal.tsx
  packages/ui/src/components/Input/index.module.scss
  packages/ui/src/components/Notification/index.module.scss
  packages/ui/src/components/Notification/index.tsx
  packages/ui/src/components/TextLink/index.module.scss
  packages/ui/src/scss/_colors.scss
  packages/ui/src/utils/a11y.ts
  pnpm-lock.yaml
Labels: size/l

#2053 feat(phrases): add german language
  packages/phrases-ui/src/index.ts
  packages/phrases-ui/src/locales/de.ts
  packages/phrases/src/index.ts
  packages/phrases/src/locales/de/errors.ts
  packages/phrases/src/locales/de/index.ts
  packages/phrases/src/locales/de/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/de/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/de/translation/admin-console/application-details.ts
  packages/phrases/src/locales/de/translation/admin-console/applications.ts
  packages/phrases/src/locales/de/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/de/translation/admin-console/connectors.ts
  packages/phrases/src/locales/de/translation/admin-console/contact.ts
  packages/phrases/src/locales/de/translation/admin-console/dashboard.ts
  packages/phrases/src/locales/de/translation/admin-console/errors.ts
  packages/phrases/src/locales/de/translation/admin-console/general.ts
  packages/phrases/src/locales/de/translation/admin-console/get-started.ts
  packages/phrases/src/locales/de/translation/admin-console/index.ts
  packages/phrases/src/locales/de/translation/admin-console/log-details.ts
  packages/phrases/src/locales/de/translation/admin-console/logs.ts
  packages/phrases/src/locales/de/translation/admin-console/session-expired.ts
  packages/phrases/src/locales/de/translation/admin-console/settings.ts
  packages/phrases/src/locales/de/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/de/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/de/translation/admin-console/tabs.ts
  packages/phrases/src/locales/de/translation/admin-console/user-details.ts
  packages/phrases/src/locales/de/translation/admin-console/users.ts
  packages/phrases/src/locales/de/translation/admin-console/welcome.ts
  packages/phrases/src/locales/de/translation/demo-app.ts
  packages/phrases/src/locales/de/translation/index.ts
Labels: feature, size/xl

#2295 chore: remove old sign in methods
  packages/console/src/hooks/use-connector-in-use.ts
  packages/console/src/pages/SignInExperience/components/ConnectorSetupWarning.tsx
  packages/console/src/pages/SignInExperience/components/SignInMethodsForm.tsx
  packages/console/src/pages/SignInExperience/components/SignInMethodsPreview.tsx
  packages/console/src/pages/SignInExperience/types.ts
  packages/console/src/pages/SignInExperience/utilities.ts
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/lib/sign-in-experience/index.ts
  packages/core/src/lib/sign-in-experience/sign-in-methods.test.ts
  packages/core/src/lib/sign-in-experience/sign-in-methods.ts
  packages/core/src/queries/sign-in-experience.test.ts
  packages/core/src/routes/sign-in-experience.guard.test.ts
  packages/core/src/routes/sign-in-experience.test.ts
  packages/core/src/routes/sign-in-experience.ts
  packages/integration-tests/src/helpers.ts
  packages/integration-tests/tests/api/session.test.ts
  packages/integration-tests/tests/api/sign-in-experience.test.ts
  packages/integration-tests/tests/api/wellknown.test.ts
  packages/schemas/alterations/next-1667292082-remove-sign-in-method.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/seeds/sign-in-experience.ts
  packages/schemas/tables/sign_in_experiences.sql
  packages/ui/src/__mocks__/logto.tsx
Labels: chore, size/xl

#2308 feat(ui): add EmailSignIn container
  packages/ui/src/App.tsx
  packages/ui/src/containers/EmailForm/EmailForm.tsx
  packages/ui/src/containers/EmailForm/EmailRegister.test.tsx
  packages/ui/src/containers/EmailForm/EmailRegister.tsx
  packages/ui/src/containers/EmailForm/EmailSignIn.test.tsx
  packages/ui/src/containers/EmailForm/EmailSignIn.tsx
  packages/ui/src/containers/EmailForm/use-email-sign-in.ts
  packages/ui/src/containers/EmailPassword/index.test.tsx
  packages/ui/src/containers/EmailPassword/index.tsx
  packages/ui/src/containers/PhoneForm/PhoneForm.tsx
  packages/ui/src/containers/PhoneForm/SmsRegister.tsx
  packages/ui/src/pages/Register/index.test.tsx
  packages/ui/src/pages/SecondaryRegister/index.test.tsx
  packages/ui/src/pages/SecondarySignIn/index.test.tsx
  packages/ui/src/pages/SecondarySignIn/index.tsx
  packages/ui/src/pages/SignIn/Main.tsx
  packages/ui/src/pages/SignIn/index.test.tsx
  packages/ui/src/pages/SignIn/index.tsx
  packages/ui/src/pages/SignInPassword/index.tsx
Labels: feature, size/l

#2311 refactor(ui): extract passwordless code hook
  packages/ui/src/apis/api.test.ts
  packages/ui/src/apis/utils.ts
  packages/ui/src/containers/EmailForm/EmailForm.tsx
  packages/ui/src/containers/EmailForm/EmailRegister.tsx
  packages/ui/src/containers/EmailForm/EmailSignIn.tsx
  packages/ui/src/containers/EmailForm/use-email-sign-in.ts
  packages/ui/src/containers/PasscodeValidation/index.test.tsx
  packages/ui/src/containers/PasscodeValidation/index.tsx
  packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
  packages/ui/src/containers/PhoneForm/PhoneForm.tsx
  packages/ui/src/containers/PhoneForm/SmsRegister.tsx
  packages/ui/src/containers/PhoneForm/SmsSignIn.tsx
  packages/ui/src/containers/PhoneForm/use-sms-register.ts
  packages/ui/src/containers/PhoneForm/use-sms-sign-in.ts
  packages/ui/src/hooks/use-continue-sign-in-with-password.ts
  packages/ui/src/hooks/use-passwordless-send-code.ts
Labels: enhancement, size/l

#2305 feat(schemas): add user is suspended column
  packages/core/src/__mocks__/user.ts
  packages/schemas/alterations/next-1667374974-user-suspend.ts
  packages/schemas/tables/users.sql
Labels: feature, size/s

#2300 feat: add case insensitive user search
  packages/core/src/queries/user.test.ts
  packages/core/src/queries/user.ts
  packages/core/src/routes/admin-user.ts
Labels: feature, size/m

#2317 feat(ui): add signInMode guard
  packages/ui/src/App.tsx
  packages/ui/src/hooks/use-sie.ts
  packages/ui/src/hooks/use-social-sign-in-listener.ts
  packages/ui/src/pages/Register/index.test.tsx
  packages/ui/src/pages/Register/index.tsx
  packages/ui/src/pages/SecondaryRegister/index.test.tsx
  packages/ui/src/pages/SecondaryRegister/index.tsx
  packages/ui/src/pages/SecondarySignIn/index.test.tsx
  packages/ui/src/pages/SecondarySignIn/index.tsx
  packages/ui/src/pages/SignIn/index.test.tsx
  packages/ui/src/pages/SignIn/index.tsx
Labels: feature, size/m

#2316 refactor(ui): add sms and email reset-password container
  packages/ui/src/__mocks__/logto.tsx
  packages/ui/src/containers/EmailForm/EmailResetPassword.test.tsx
  packages/ui/src/containers/EmailForm/EmailResetPassword.tsx
  packages/ui/src/containers/EmailForm/index.tsx
  packages/ui/src/containers/Passwordless/EmailPasswordless.test.tsx
  packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.test.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
  packages/ui/src/containers/Passwordless/index.module.scss
  packages/ui/src/containers/Passwordless/index.tsx
  packages/ui/src/containers/PhoneForm/SmsResetPassword.test.tsx
  packages/ui/src/containers/PhoneForm/SmsResetPassword.tsx
  packages/ui/src/containers/PhoneForm/index.tsx
  packages/ui/src/hooks/use-sie.ts
  packages/ui/src/pages/ForgotPassword/index.test.tsx
  packages/ui/src/pages/ForgotPassword/index.tsx
  packages/ui/src/types/index.ts
Labels: enhancement, size/xl

#2324 chore: add German language changeset
  .changeset/config.json
  .changeset/fifty-balloons-taste.md
  .changeset/pre.json
Labels: chore, size/s

#2334 chore: optimize Dockerfile
  Dockerfile
Labels: chore, size/xs

#2333 refactor(core): optimize translation strictly partial check
  packages/core/src/routes/custom-phrase.test.ts
  packages/core/src/routes/custom-phrase.ts
  packages/core/src/utils/translation.test.ts
  packages/core/src/utils/translation.ts
Labels: enhancement, size/s

#2335 chore(core): upgrade oidc-provider
  packages/cli/package.json
  packages/core/package.json
  packages/integration-tests/package.json
  pnpm-lock.yaml
Labels: chore, size/s

#2318 refactor(console): tooltip
  packages/console/src/components/IconButton/index.tsx
  packages/console/src/components/TipBubble/index.module.scss
  packages/console/src/components/TipBubble/index.tsx
  packages/console/src/components/TipBubble/utils.ts
  packages/console/src/components/Tooltip/index.module.scss
  packages/console/src/components/Tooltip/index.tsx
  packages/console/src/hooks/use-position.ts
Labels: enhancement, size/l

#2346 feat(ui): add continue related apis
  packages/ui/src/apis/continue.test.ts
  packages/ui/src/apis/continue.ts
Labels: feature, size/m

#2319 feat(console): toggle tip
  packages/console/src/components/ToggleTip/index.module.scss
  packages/console/src/components/ToggleTip/index.tsx
Labels: feature, size/s

#2340 feat(ui): add password switch link
  packages/phrases-ui/src/locales/en.ts
  packages/phrases-ui/src/locales/fr.ts
  packages/phrases-ui/src/locales/ko.ts
  packages/phrases-ui/src/locales/pt-pt.ts
  packages/phrases-ui/src/locales/tr-tr.ts
  packages/phrases-ui/src/locales/zh-cn.ts
  packages/ui/src/apis/continue.test.ts
  packages/ui/src/apis/continue.ts
  packages/ui/src/containers/PasscodeValidation/PasswordSignInLink.tsx
  packages/ui/src/containers/PasscodeValidation/index.module.scss
  packages/ui/src/containers/PasscodeValidation/index.tsx
  packages/ui/src/pages/Passcode/index.test.tsx
  packages/ui/src/pages/Passcode/index.tsx
Labels: feature, size/m

#2336 chore: enable Node 18
  .github/workflows/integration-test.yml
  .github/workflows/main.yml
  package.json
  packages/cli/package.json
  packages/cli/src/commands/install/utils.ts
  packages/console/package.json
  packages/core/package.json
  packages/create/package.json
  packages/demo-app/package.json
  packages/integration-tests/package.json
  packages/phrases-ui/package.json
  packages/phrases/package.json
  packages/schemas/package.json
  packages/shared/package.json
  packages/ui/package.json
Labels: chore, size/s

#2341 chore(console): update default avatars
  packages/console/src/assets/avatars/avatar-002.png
  packages/console/src/assets/avatars/avatar-005.png
  packages/console/src/assets/avatars/avatar-010.png
  packages/console/src/consts/avatars.ts
Labels: chore, size/xs

#2338 refactor(ui): refactor passcodevalidation
  packages/phrases-ui/src/locales/en.ts
  packages/phrases-ui/src/locales/fr.ts
  packages/phrases-ui/src/locales/ko.ts
  packages/phrases-ui/src/locales/pt-pt.ts
  packages/phrases-ui/src/locales/tr-tr.ts
  packages/phrases-ui/src/locales/zh-cn.ts
  packages/ui/src/apis/continue.test.ts
  packages/ui/src/apis/continue.ts
  packages/ui/src/containers/PasscodeValidation/PasswordSignInLink.tsx
  packages/ui/src/containers/PasscodeValidation/index.module.scss
  packages/ui/src/containers/PasscodeValidation/index.test.tsx
  packages/ui/src/containers/PasscodeValidation/index.tsx
  packages/ui/src/containers/PasscodeValidation/use-forgot-password-email-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/use-forgot-password-sms-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/use-forgot-password-with-email-error-handler.ts
  packages/ui/src/containers/PasscodeValidation/use-forgot-password-with-sms-error-handler.ts
  packages/ui/src/containers/PasscodeValidation/use-identifier-error-alert.ts
  packages/ui/src/containers/PasscodeValidation/use-passcode-validation-error-handler.ts
  packages/ui/src/containers/PasscodeValidation/use-register-with-email-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/use-register-with-sms-error-handler.ts
  packages/ui/src/containers/PasscodeValidation/use-register-with-sms-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/use-resend-passcode.ts
  packages/ui/src/containers/PasscodeValidation/use-shared-error-handler.ts
  packages/ui/src/containers/PasscodeValidation/use-sign-in-with-email-error-handler.ts
  packages/ui/src/containers/PasscodeValidation/use-sign-in-with-email-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/use-sign-in-with-sms-error-handler.ts
  packages/ui/src/containers/PasscodeValidation/use-sign-in-with-sms-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/user-register-with-email-error-handler.ts
  packages/ui/src/containers/PasscodeValidation/utils.ts
  packages/ui/src/pages/Passcode/index.test.tsx
  packages/ui/src/pages/Passcode/index.tsx
  packages/ui/src/types/index.ts
Labels: enhancement, size/xl

#2322 feat(ui): add forgot password link
  packages/core/src/routes/well-known.ts
  packages/phrases-ui/src/locales/en.ts
  packages/phrases-ui/src/locales/fr.ts
  packages/phrases-ui/src/locales/ko.ts
  packages/phrases-ui/src/locales/pt-pt.ts
  packages/phrases-ui/src/locales/tr-tr.ts
  packages/phrases-ui/src/locales/zh-cn.ts
  packages/ui/src/apis/continue.test.ts
  packages/ui/src/apis/continue.ts
  packages/ui/src/components/ForgotPasswordLink/index.tsx
  packages/ui/src/containers/EmailForm/index.module.scss
  packages/ui/src/containers/EmailPassword/index.module.scss
  packages/ui/src/containers/EmailPassword/index.test.tsx
  packages/ui/src/containers/EmailPassword/index.tsx
  packages/ui/src/containers/PasscodeValidation/PasswordSignInLink.tsx
  packages/ui/src/containers/PasscodeValidation/index.module.scss
  packages/ui/src/containers/PasscodeValidation/index.test.tsx
  packages/ui/src/containers/PasscodeValidation/index.tsx
  packages/ui/src/containers/PasscodeValidation/use-forgot-password-email-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/use-forgot-password-sms-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/use-forgot-password-with-email-error-handler.ts
  packages/ui/src/containers/PasscodeValidation/use-forgot-password-with-sms-error-handler.ts
  packages/ui/src/containers/PasscodeValidation/use-identifier-error-alert.ts
  packages/ui/src/containers/PasscodeValidation/use-passcode-validation-error-handler.ts
  packages/ui/src/containers/PasscodeValidation/use-register-with-email-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/use-register-with-sms-error-handler.ts
  packages/ui/src/containers/PasscodeValidation/use-register-with-sms-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/use-resend-passcode.ts
  packages/ui/src/containers/PasscodeValidation/use-shared-error-handler.ts
  packages/ui/src/containers/PasscodeValidation/use-sign-in-with-email-error-handler.ts
  packages/ui/src/containers/PasscodeValidation/use-sign-in-with-email-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/use-sign-in-with-sms-error-handler.ts
  packages/ui/src/containers/PasscodeValidation/use-sign-in-with-sms-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/user-register-with-email-error-handler.ts
  packages/ui/src/containers/PasscodeValidation/utils.ts
  packages/ui/src/containers/PasswordSignInForm/index.module.scss
  packages/ui/src/containers/PasswordSignInForm/index.tsx
  packages/ui/src/containers/PhoneForm/index.module.scss
  packages/ui/src/containers/PhonePassword/index.module.scss
  packages/ui/src/containers/PhonePassword/index.test.tsx
  packages/ui/src/containers/PhonePassword/index.tsx
  packages/ui/src/containers/UsernameSignIn/index.module.scss
  packages/ui/src/containers/UsernameSignIn/index.test.tsx
  packages/ui/src/containers/UsernameSignIn/index.tsx
  packages/ui/src/hooks/use-sie.ts
  packages/ui/src/pages/ForgotPassword/index.tsx
  packages/ui/src/pages/Passcode/index.test.tsx
  packages/ui/src/pages/Passcode/index.tsx
  packages/ui/src/types/index.ts
Labels: feature, size/xl

#2332 refactor(core): reuse connector reading function in cli
  packages/cli/src/commands/connector/utils.ts
  packages/cli/src/utilities.ts
  packages/core/src/connectors/index.ts
Labels: enhancement, size/s

#2345 feat(console): in-used connectors deletion alert
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/connector-details.ts
Labels: feature, size/s

#2323 feat(console): add toggle tip for the sie not-in-use status
  packages/console/src/pages/Connectors/components/ConnectorStatusField/index.module.scss
  packages/console/src/pages/Connectors/components/ConnectorStatusField/index.tsx
  packages/console/src/pages/Connectors/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/connectors.ts
  packages/phrases/src/locales/en/translation/admin-console/connectors.ts
  packages/phrases/src/locales/fr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/ko/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/connectors.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/connectors.ts
Labels: feature, size/m

#2325 feat(core): add sign-in timestamp in session interaction
  packages/core/src/lib/session.ts
  packages/core/src/routes/session/continue.test.ts
  packages/core/src/routes/session/password.test.ts
  packages/core/src/routes/session/passwordless.test.ts
  packages/core/src/routes/session/social.test.ts
  packages/core/src/routes/session/utils.test.ts
Labels: feature, size/s

#2364 refactor(console): remove draggle preview item background
  packages/console/src/components/Transfer/DraggableItem.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/index.module.scss
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/index.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SocialConnectorEditBox/index.module.scss
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SocialConnectorEditBox/index.tsx
Labels: enhancement, size/s

#2327 feat(core,phrases): add re-authentication check function for protected access
  packages/core/src/lib/session.ts
  packages/phrases/src/locales/de/errors.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
Labels: feature, size/s

#2360 refactor(console): enabled verification code checkbox when sign-up identifier set to none
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/index.tsx
Labels: enhancement, size/xs

#2358 fix(console): preview forgot password
  packages/console/src/pages/SignInExperience/components/Preview.tsx
Labels: bugfix, size/s

#2357 fix(core): add check required profile to password routes
  packages/core/src/routes/session/password.test.ts
  packages/core/src/routes/session/password.ts
  packages/core/src/routes/session/utils.ts
Labels: bugfix, size/s

#2344 feat(cli): trim keys
  .changeset/unlucky-lizards-agree.md
  packages/cli/src/commands/database/config.ts
Labels: feature, size/s

#2342 feat(cli): rotate keys
  .changeset/unlucky-lizards-agree.md
  packages/cli/src/commands/database/config.ts
  packages/cli/src/commands/database/seed/oidc-config.ts
  packages/cli/src/commands/database/utilities.ts
Labels: feature, size/m

#2361 refactor(console): the swap icon should be fixed in the sign-in method item
  packages/console/src/components/Checkbox/index.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/SignInMethodItem.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/index.module.scss
Labels: enhancement, size/s

#2362 style(console): add margins to the draggable icon in sign-in method items
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/index.module.scss
Labels: enhancement, size/xs

#2370 refactor(console): fix undesired appearance for popup and tooltip
  packages/console/src/components/Dropdown/index.tsx
  packages/console/src/components/ToggleTip/index.tsx
  packages/console/src/components/Tooltip/index.tsx
Labels: enhancement, size/xs

#2371 feat(console): add tool tips to disabled action items in sie
  packages/console/src/components/Checkbox/index.module.scss
  packages/console/src/components/Checkbox/index.tsx
  packages/console/src/components/IconButton/index.module.scss
  packages/console/src/components/IconButton/index.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/LanguageDetails.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/SignUpForm.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/SignInMethodItem.tsx
  packages/phrases/src/locales/de/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
Labels: feature, size/m

#2382 refactor(console): display full sign-up and sign-in config in the change alert
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignUpAndSignInDiffSection/index.tsx
Labels: enhancement, size/s

#2359 refactor(core): allowing more editable properties for patch user API
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
  packages/core/src/routes/session/utils.ts
  packages/phrases/src/locales/de/errors.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
Labels: enhancement, size/l

#2375 style(ui): update notification style
  packages/ui/src/components/Notification/index.module.scss
  packages/ui/src/components/Toast/index.module.scss
  packages/ui/src/containers/AppContent/index.module.scss
  packages/ui/src/scss/_colors.scss
Labels: size/s

#2376 style(ui): add cursor pointer to terms
  packages/ui/src/components/TermsOfUse/index.module.scss
Labels: size/xs

#2374 fix(ui): update content
  packages/ui/src/containers/CreateAccount/index.test.tsx
  packages/ui/src/containers/CreateAccount/index.tsx
  packages/ui/src/containers/UsernameRegister/index.test.tsx
  packages/ui/src/containers/UsernameRegister/index.tsx
Labels: bugfix, size/s

#2381 refactor(console): remove the required label from the dark mode color picker
  packages/console/src/pages/SignInExperience/components/ColorForm.tsx
Labels: enhancement, size/xs

#2384 fix(core): sign in method requires at least one factor
  packages/core/src/lib/sign-in-experience/sign-in.test.ts
  packages/core/src/lib/sign-in-experience/sign-in.ts
  packages/phrases/src/locales/de/errors.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
Labels: bugfix, size/s

#2366 feat(core): block suspended user from sign in
  packages/core/src/routes/session/middleware/passwordless-action.ts
  packages/core/src/routes/session/passwordless.test.ts
  packages/core/src/routes/session/social.bind-social.test.ts
  packages/core/src/routes/session/social.test.ts
  packages/core/src/routes/session/social.ts
  packages/core/src/routes/session/utils.test.ts
  packages/core/src/routes/session/utils.ts
  packages/phrases/src/locales/de/errors.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
Labels: feature, size/l

#2386 refactor(core): remove SIE identifier check from user management API
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
Labels: enhancement, size/s

#2377 fix(console): unset compare data on the sie data updated
  packages/console/src/pages/SignInExperience/index.tsx
Labels: bugfix, size/xs

#2378 fix(console): correct sentence cases in the sie change alert modal
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignUpAndSignInDiffSection/SignInDiffSection.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignUpAndSignInDiffSection/SignUpDiffSection.tsx
Labels: bugfix, size/s

#2385 style(ui): layout styling updates
  packages/ui/src/components/BrandingHeader/index.module.scss
  packages/ui/src/components/Input/index.module.scss
  packages/ui/src/components/Passcode/index.module.scss
  packages/ui/src/components/SecondaryPageWrapper/index.module.scss
  packages/ui/src/components/SecondaryPageWrapper/index.tsx
  packages/ui/src/containers/EmailForm/index.module.scss
  packages/ui/src/containers/EmailPassword/index.module.scss
  packages/ui/src/containers/EmailPassword/index.tsx
  packages/ui/src/containers/PasswordSignInForm/index.module.scss
  packages/ui/src/containers/PhoneForm/index.module.scss
  packages/ui/src/containers/PhonePassword/index.module.scss
  packages/ui/src/containers/SetPassword/index.module.scss
  packages/ui/src/containers/UsernameSignIn/index.module.scss
  packages/ui/src/pages/Register/index.module.scss
  packages/ui/src/pages/Register/index.tsx
  packages/ui/src/pages/SignIn/index.module.scss
  packages/ui/src/pages/SignIn/index.tsx
Labels: size/m

#2380 refactor(console): make the inline connector setup warning display only once
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/SignInForm.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/index.tsx
Labels: enhancement, size/s

#2387 style(ui): update text link styling
  packages/ui/src/components/TextLink/index.module.scss
  packages/ui/src/containers/PasscodeValidation/index.module.scss
  packages/ui/src/containers/PasscodeValidation/index.tsx
Labels: size/s

#2367 refactor(core)!: use case insensitive search for emails
  packages/core/src/queries/user.test.ts
  packages/core/src/queries/user.ts
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
  packages/integration-tests/src/api/admin-user.ts
  packages/integration-tests/src/api/session.ts
  packages/integration-tests/src/helpers.ts
  packages/integration-tests/src/utils.ts
  packages/integration-tests/tests/api/dashboard.test.ts
  packages/integration-tests/tests/api/get-access-token.test.ts
  packages/integration-tests/tests/api/session.test.ts
  packages/integration-tests/tests/api/social-session.test.ts
Labels: enhancement, size/m

#2369 feat(ui): add the profile fill flow for social bind and register
  packages/ui/src/hooks/use-bind-social.ts
Labels: feature, size/s

#2368 feat(ui): add set email and phone passcode validation hooks
  packages/ui/src/apis/continue.test.ts
  packages/ui/src/apis/continue.ts
  packages/ui/src/containers/PasscodeValidation/index.test.tsx
  packages/ui/src/containers/PasscodeValidation/use-continue-set-email-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/use-continue-set-sms-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/utils.ts
  packages/ui/src/hooks/use-bind-social.ts
  packages/ui/src/types/guard.ts
Labels: feature, size/l

#2365 feat(ui): add continue with email and phone container
  packages/phrases-ui/src/locales/de.ts
  packages/phrases-ui/src/locales/en.ts
  packages/phrases-ui/src/locales/fr.ts
  packages/phrases-ui/src/locales/ko.ts
  packages/phrases-ui/src/locales/pt-pt.ts
  packages/phrases-ui/src/locales/tr-tr.ts
  packages/phrases-ui/src/locales/zh-cn.ts
  packages/ui/src/apis/api.test.ts
  packages/ui/src/apis/continue.test.ts
  packages/ui/src/apis/continue.ts
  packages/ui/src/apis/utils.ts
  packages/ui/src/containers/EmailForm/EmailContinue.test.tsx
  packages/ui/src/containers/EmailForm/EmailContinue.tsx
  packages/ui/src/containers/EmailForm/index.tsx
  packages/ui/src/containers/PasscodeValidation/index.test.tsx
  packages/ui/src/containers/PasscodeValidation/use-continue-set-email-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/use-continue-set-sms-passcode-validation.ts
  packages/ui/src/containers/PasscodeValidation/utils.ts
  packages/ui/src/containers/PhoneForm/SmsContinue.test.tsx
  packages/ui/src/containers/PhoneForm/SmsContinue.tsx
  packages/ui/src/containers/PhoneForm/index.tsx
  packages/ui/src/hooks/use-bind-social.ts
  packages/ui/src/pages/Continue/SetEmail/index.test.tsx
  packages/ui/src/pages/Continue/SetEmail/index.tsx
  packages/ui/src/pages/Continue/SetPhone/index.test.tsx
  packages/ui/src/pages/Continue/SetPhone/index.tsx
  packages/ui/src/pages/Continue/index.tsx
  packages/ui/src/types/guard.ts
Labels: feature, size/xl

#2394 fix(core): require connector when verification code is enabled
  packages/core/src/lib/sign-in-experience/sign-in.test.ts
  packages/core/src/lib/sign-in-experience/sign-in.ts
Labels: bugfix, size/s

#2379 fix(core): fix user password and identities check
  packages/core/src/routes/session/continue.ts
  packages/core/src/routes/session/utils.ts
Labels: bugfix, size/s

#2395 fix(console): do not check sms or email connectors on verification code disabled in sign-in method
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/index.tsx
Labels: bugfix, size/s

#2391 chore(console): remove deprecated code about sign-in methods
  packages/console/src/pages/SignInExperience/components/ConnectorsTransfer.module.scss
  packages/console/src/pages/SignInExperience/components/ConnectorsTransfer.tsx
  packages/phrases/src/locales/de/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
Labels: chore, size/l

#2392 style(ui): main page overflow
  packages/ui/src/containers/AppContent/index.module.scss
  packages/ui/src/containers/AppContent/index.tsx
Labels: size/xs

#2398 fix(core): fix field updating issues in patch user management api
  packages/core/src/queries/user.ts
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
  packages/core/src/routes/session/utils.ts
Labels: bugfix, size/s

#2390 style(ui): fix web button font size
  packages/ui/src/components/Button/index.module.scss
Labels: size/xs

#2388 style(ui): fix modal border radius issue
  packages/ui/src/components/ConfirmModal/Acmodal.module.scss
  packages/ui/src/components/ConfirmModal/MobileModal.module.scss
Labels: size/s

#2393 refactor(console): update the ac sign-up and sign-in phrases
  packages/console/src/components/Checkbox/index.module.scss
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/SignUpForm.tsx
  packages/phrases/src/locales/de/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
Labels: enhancement, size/l

#2401 fix(phrases): zh-CN typo about sign-in
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
Labels: bugfix, size/xs

#2326 feat(core): update user suspended
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
Labels: feature, size/s

#2404 chore: add changeset
  .changeset/thin-oranges-act.md
Labels: chore, size/xs

#2397 style(ui): fix mobile body font
  packages/ui/src/containers/AppContent/index.module.scss
Labels: size/xs

#2407 feat(core): revoke tokens when user is suspended
  packages/core/src/queries/oidc-model-instance.ts
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
Labels: feature, size/s

#2403 style(ui): update bg color
  packages/ui/src/scss/_colors.scss
Labels: size/xs

#2405 style(ui): hide toast outline
  packages/ui/src/components/Toast/index.module.scss
Labels: size/xs

#2406 fix(ui): fix i18n content
  packages/ui/src/pages/SignInPassword/index.tsx
Labels: bugfix, size/xs

#2408 fix(ui): sign-in with phone password api namespace
  packages/ui/src/apis/index.test.ts
  packages/ui/src/apis/sign-in.ts
Labels: bugfix, size/xs

#2410 fix(ui): content update
  packages/phrases-ui/src/locales/de.ts
  packages/phrases-ui/src/locales/en.ts
  packages/phrases-ui/src/locales/fr.ts
  packages/phrases-ui/src/locales/ko.ts
  packages/phrases-ui/src/locales/pt-pt.ts
  packages/phrases-ui/src/locales/tr-tr.ts
  packages/phrases-ui/src/locales/zh-cn.ts
Labels: bugfix, size/m

#2402 feat(ui): add key event to AC modals
  packages/ui/src/components/ConfirmModal/AcModal.tsx
  packages/ui/src/components/ConfirmModal/Acmodal.module.scss
  packages/ui/src/components/ConfirmModal/MobileModal.module.scss
  packages/ui/src/components/ConfirmModal/type.ts
  packages/ui/src/components/TermsOfUse/index.tsx
Labels: feature, size/s

#2409 fix(schemas): add missing log types for continue with passwordless
  packages/schemas/src/types/log.ts
Labels: bugfix, size/s

#2420 fix(console): correct sms connector status
  packages/console/src/hooks/use-connector-in-use.ts
Labels: bugfix, size/xs

#2417 feat(schemas): update connector_instances table and add db alteration script
  packages/schemas/alterations/next-1668140465-support-multiple-connector-instances.ts
  packages/schemas/package.json
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/types/connector.ts
  packages/schemas/tables/connectors.sql
  pnpm-lock.yaml
Labels: feature, size/s

#2423 refactor(core): change session health validation method for session APIs
  packages/core/src/lib/session.ts
  packages/core/src/routes/session/continue.test.ts
  packages/core/src/routes/session/password.test.ts
  packages/core/src/routes/session/passwordless.test.ts
  packages/core/src/routes/session/social.test.ts
  packages/core/src/routes/session/utils.test.ts
Labels: enhancement, size/m

#2419 fix(console): avoid unexpected data reset in sign-up and sign-in tab
  packages/console/src/pages/SignInExperience/index.tsx
  packages/console/src/pages/SignInExperience/tabs/BrandingTab.tsx
  packages/console/src/pages/SignInExperience/tabs/OthersTab.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/index.tsx
Labels: bugfix, size/m

#2422 fix(console): sign-up identifier translation
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignUpAndSignInDiffSection/SignUpDiffSection.tsx
Labels: bugfix, size/xs

#2416 style(console): sign-up and sign-in form field description margins
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/SignUpForm.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/index.module.scss
Labels: size/s

#2415 fix(phrases): connectors setup warnings
  packages/phrases/src/locales/de/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/connectors.ts
Labels: bugfix, size/s

#2320 feat: suspend user
  packages/core/src/__mocks__/user.ts
  packages/core/src/queries/oidc-model-instance.ts
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
  packages/core/src/routes/session/middleware/passwordless-action.ts
  packages/core/src/routes/session/passwordless.test.ts
  packages/core/src/routes/session/social.bind-social.test.ts
  packages/core/src/routes/session/social.test.ts
  packages/core/src/routes/session/social.ts
  packages/core/src/routes/session/utils.test.ts
  packages/core/src/routes/session/utils.ts
  packages/phrases/src/locales/de/errors.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
  packages/schemas/alterations/next-1667374974-user-suspend.ts
  packages/schemas/tables/users.sql
Labels: feature, size/l

#2412 chore: add pubilsh script
  .changeset/config.json
  .github/workflows/integration-test.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
  .github/workflows/upload-annotations.yml
  .scripts/merge-eslint-reports.js
  .scripts/package.sh
  .scripts/publish.js
Labels: chore, size/m

#2431 chore: add sign-in experience v2 changeset
  .changeset/quick-turtles-joke.md
Labels: chore, size/s

#2418 refactor(ui): refactor continue with email or phone
  packages/ui/src/App.tsx
  packages/ui/src/containers/PasswordlessSwitch/index.tsx
  packages/ui/src/hooks/use-required-profile-error-handler.ts
  packages/ui/src/pages/Continue/EmailOrPhone/index.test.tsx
  packages/ui/src/pages/Continue/EmailOrPhone/index.tsx
  packages/ui/src/pages/Continue/SetEmail/index.test.tsx
  packages/ui/src/pages/Continue/SetEmail/index.tsx
  packages/ui/src/pages/Continue/SetPassword/index.tsx
  packages/ui/src/pages/Continue/SetPhone/index.test.tsx
  packages/ui/src/pages/Continue/SetPhone/index.tsx
  packages/ui/src/pages/Continue/SetUsername/index.tsx
Labels: enhancement, size/m

#2433 fix(core): get per app sie
  packages/core/src/lib/session.ts
  packages/core/src/lib/sign-in-experience/index.ts
  packages/core/src/lib/sign-in-experience/sign-up.test.ts
  packages/core/src/routes/session/continue.ts
  packages/core/src/routes/session/middleware/koa-guard-session-action.ts
  packages/core/src/routes/session/middleware/passwordless-action.ts
  packages/core/src/routes/session/password.test.ts
  packages/core/src/routes/session/password.ts
  packages/core/src/routes/session/passwordless.test.ts
  packages/core/src/routes/session/social.ts
  packages/core/src/routes/session/utils.ts
  packages/core/src/routes/well-known.ts
Labels: bugfix, size/l

#2434 refactor(console): enable password and verification code auth in sign-in method by default
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/utilities.ts
Labels: enhancement, size/xs

#2437 fix(ui): update cn content
  packages/phrases-ui/src/locales/zh-cn.ts
Labels: bugfix, size/s

#2432 feat(ui): add inline notification
  packages/phrases-ui/src/locales/de.ts
  packages/phrases-ui/src/locales/en.ts
  packages/phrases-ui/src/locales/fr.ts
  packages/phrases-ui/src/locales/ko.ts
  packages/phrases-ui/src/locales/pt-pt.ts
  packages/phrases-ui/src/locales/tr-tr.ts
  packages/phrases-ui/src/locales/zh-cn.ts
  packages/ui/src/components/Notification/AppNotification/index.module.scss
  packages/ui/src/components/Notification/AppNotification/index.tsx
  packages/ui/src/components/Notification/InlineNotification/index.module.scss
  packages/ui/src/components/Notification/InlineNotification/index.tsx
  packages/ui/src/components/Notification/index.module.scss
  packages/ui/src/components/Notification/index.tsx
  packages/ui/src/components/SecondaryPageWrapper/index.module.scss
  packages/ui/src/components/SecondaryPageWrapper/index.tsx
  packages/ui/src/containers/AppContent/index.module.scss
  packages/ui/src/containers/AppNotification/index.module.scss
  packages/ui/src/containers/AppNotification/index.test.tsx
  packages/ui/src/containers/AppNotification/index.tsx
  packages/ui/src/containers/LandingPageContainer/index.tsx
  packages/ui/src/pages/Continue/SetPassword/index.tsx
Labels: feature, size/l

#2436 fix(core): throw invalid credentials for empty password users
  packages/core/src/lib/user.ts
Labels: bugfix, size/xs

#2438 fix(ui): hot fix the rebase issue
  packages/ui/src/components/SecondaryPageWrapper/index.module.scss
  packages/ui/src/pages/Continue/EmailOrPhone/index.tsx
  packages/ui/src/pages/Continue/SetEmail/index.tsx
  packages/ui/src/pages/Continue/SetPhone/index.tsx
  packages/ui/src/pages/Continue/SetUsername/index.tsx
Labels: bugfix, size/xs

#2435 feat(console): add suspended label
  packages/console/src/pages/UserDetails/index.module.scss
  packages/console/src/pages/UserDetails/index.tsx
  packages/core/src/routes/admin-user.test.ts
  packages/phrases/src/locales/de/translation/admin-console/user-details.ts
  packages/phrases/src/locales/en/translation/admin-console/user-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/user-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/user-details.ts
  packages/schemas/src/types/user.ts
Labels: feature, size/s

#2439 chore: update changeset format
  .changeset/quick-turtles-joke.md
  .changeset/thin-oranges-act.md
  .changeset/unlucky-lizards-agree.md
Labels: chore, size/s

#2440 ci: add npm token
  .github/workflows/release.yml
Labels: size/xs

#2441 ci: set bot token for release workflow
  .github/workflows/release.yml
Labels: size/xs

#2443 fix(console): fix forgotpassword not shown on preview
  packages/console/src/pages/SignInExperience/components/Preview.tsx
Labels: bugfix, size/xs

#2399 feat(core): add change username session api
  packages/core/src/routes/admin-user.ts
  packages/core/src/routes/session/index.ts
  packages/core/src/routes/session/profile.test.ts
  packages/core/src/routes/session/profile.ts
  packages/core/src/routes/session/utils.ts
Labels: feature, size/m

#2411 feat(core): add change password session api
  packages/core/src/routes/session/forgot-password.test.ts
  packages/core/src/routes/session/forgot-password.ts
  packages/core/src/routes/session/profile.test.ts
  packages/core/src/routes/session/profile.ts
Labels: feature, size/s

#2421 fix(ui): fix phone input android layout bug
  packages/ui/src/components/Input/phoneInput.module.scss
Labels: bugfix, size/xs

#2449 chore: update README.md
  README.md
Labels: chore, size/xs

#2447 ci: fetch all tags for release workflow
  .github/workflows/release.yml
Labels: size/xs

#2455 feat: email related profile session apis
  packages/core/src/routes/session/profile.test.ts
  packages/core/src/routes/session/profile.ts
  packages/core/src/routes/session/utils.ts
Labels: feature, size/m

#2456 feat: phone related profile session APIs
  packages/core/src/routes/session/profile.test.ts
  packages/core/src/routes/session/profile.ts
Labels: feature, size/m

#2445 refactor(console): connector setup warning
  packages/console/src/hooks/use-enabled-connector-types.ts
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/ConnectorSetupWarning.tsx
Labels: enhancement, size/s

#2446 refactor(console): validate sign-up identifier
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/SignUpForm.tsx
Labels: enhancement, size/s

#2448 refactor(console): form validations on sign-up and sign-in page
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/SignInForm.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/SignUpForm.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/SignInMethodItem.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/index.module.scss
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/index.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/utilities.ts
  packages/console/src/pages/SignInExperience/types.ts
  packages/console/src/pages/SignInExperience/utilities.ts
  packages/phrases/src/locales/de/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
Labels: enhancement, size/xl

#2461 fix: alteration scripts
  .changeset/pre.json
  .changeset/tricky-mirrors-act.md
  .github/workflows/release.yml
  .scripts/publish.js
  package.json
  packages/cli/CHANGELOG.md
  packages/cli/package.json
  packages/console/CHANGELOG.md
  packages/console/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/create/CHANGELOG.md
  packages/create/package.json
  packages/integration-tests/CHANGELOG.md
  packages/integration-tests/package.json
  packages/schemas/CHANGELOG.md
  packages/schemas/alterations/1.0.0_beta.14-1665300135-sign-in-sign-up.ts
  packages/schemas/alterations/1.0.0_beta.14-1667283640-remove-forgot-password.ts
  packages/schemas/alterations/1.0.0_beta.14-1667292082-remove-sign-in-method.ts
  packages/schemas/alterations/1.0.0_beta.14-1667374974-user-suspend.ts
  packages/schemas/alterations/1.0.0_beta.14-1667900481-add-passcode-type-continue.ts
  packages/schemas/package.json
  packages/shared/CHANGELOG.md
  packages/shared/package.json
  packages/ui/CHANGELOG.md
  packages/ui/package.json
Labels: bugfix, size/s

#2454 refactor(console): add pagination item range info
  packages/console/src/components/AuditLogTable/index.tsx
  packages/console/src/components/Pagination/index.module.scss
  packages/console/src/components/Pagination/index.tsx
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/Users/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/general.ts
  packages/phrases/src/locales/en/translation/admin-console/general.ts
  packages/phrases/src/locales/fr/translation/admin-console/general.ts
  packages/phrases/src/locales/ko/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
Labels: enhancement, size/s

#2457 feat: profile API to change other insensitive user info
  packages/core/src/routes/session/profile.test.ts
  packages/core/src/routes/session/profile.ts
Labels: feature, size/m

#2468 feat: update connectors table and load connector logic
  packages/console/package.json
  packages/core/package.json
  packages/core/src/__mocks__/connector-base-data.ts
  packages/core/src/__mocks__/connector.ts
  packages/core/src/connectors/index.ts
  packages/core/src/connectors/utilities/index.test.ts
  packages/core/src/queries/connector.test.ts
  packages/demo-app/package.json
  packages/phrases-ui/package.json
  packages/phrases/package.json
  packages/schemas/alterations/next-1668666590-support-multiple-connector-instances.ts
  packages/schemas/package.json
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/types/connector.ts
  packages/schemas/tables/connectors.sql
  packages/ui/package.json
  pnpm-lock.yaml
Labels: feature, size/m

#2462 refactor(console): ac layout
  packages/console/src/components/AppContent/index.module.scss
  packages/console/src/components/AuditLogTable/index.module.scss
  packages/console/src/components/AuditLogTable/index.tsx
  packages/console/src/components/Pagination/index.module.scss
  packages/console/src/components/Pagination/index.tsx
  packages/console/src/pages/ApiResources/index.module.scss
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/Applications/index.module.scss
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/AuditLogs/index.module.scss
  packages/console/src/pages/AuditLogs/index.tsx
  packages/console/src/pages/Connectors/index.module.scss
  packages/console/src/pages/Connectors/index.tsx
  packages/console/src/pages/Users/index.module.scss
  packages/console/src/pages/Users/index.tsx
  packages/console/src/scss/_underscore.scss
  packages/console/src/scss/resources.module.scss
  packages/phrases/src/locales/de/translation/admin-console/general.ts
  packages/phrases/src/locales/en/translation/admin-console/general.ts
  packages/phrases/src/locales/fr/translation/admin-console/general.ts
  packages/phrases/src/locales/ko/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
Labels: enhancement, size/m

#2469 feat: update PATCH /connectors/:id
  packages/core/package.json
  packages/core/src/routes/connector.ts
  packages/core/src/routes/connector.update.test.ts
  packages/schemas/package.json
  pnpm-lock.yaml
Labels: feature, size/s

#2458 feat(console): submit form changes action bar
  packages/console/src/components/SubmitFormChangesActionBar/index.module.scss
  packages/console/src/components/SubmitFormChangesActionBar/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/general.ts
  packages/phrases/src/locales/en/translation/admin-console/general.ts
  packages/phrases/src/locales/fr/translation/admin-console/general.ts
  packages/phrases/src/locales/ko/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
Labels: feature, size/s

#2460 refactor(console): application details
  packages/console/src/App.tsx
  packages/console/src/components/AppContent/components/Sidebar/index.module.scss
  packages/console/src/components/AppContent/index.module.scss
  packages/console/src/components/FormCard/index.module.scss
  packages/console/src/components/FormCard/index.tsx
  packages/console/src/components/TabNav/index.module.scss
  packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx
  packages/console/src/pages/ApplicationDetails/components/Settings.tsx
  packages/console/src/pages/ApplicationDetails/index.module.scss
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/scss/_underscore.scss
  packages/phrases/src/locales/de/translation/admin-console/application-details.ts
  packages/phrases/src/locales/de/translation/admin-console/general.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/general.ts
  packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/general.ts
  packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
Labels: enhancement, size/l

#2464 refactor(console): api resource details
  packages/console/src/components/DetailsForm/index.module.scss
  packages/console/src/components/DetailsForm/index.tsx
  packages/console/src/components/SubmitFormChangesActionBar/index.tsx
  packages/console/src/pages/ApiResourceDetails/index.module.scss
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/console/src/pages/ApplicationDetails/index.module.scss
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/de/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
Labels: enhancement, size/m

#1862 chore: integrate Uffizzi PR Environments
  docker-compose.uffizzi.yml
Labels: chore, size/s

#2476 fix(core): hot fix getConnectors bug
  packages/core/src/connectors/index.ts
Labels: bugfix, size/s

#2474 refactor(console): hide pagination if the page count is less than two
  packages/console/src/components/AuditLogTable/index.tsx
  packages/console/src/components/Pagination/index.tsx
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/Users/index.tsx
Labels: enhancement, size/s

#2473 refactor(console): add padding-bottom to resources layout
  packages/console/src/scss/resources.module.scss
Labels: enhancement, size/xs

#2467 refactor(console): user details
  packages/console/src/pages/UserDetails/components/UserLogs.module.scss
  packages/console/src/pages/UserDetails/components/UserLogs.tsx
  packages/console/src/pages/UserDetails/components/UserSettings.tsx
  packages/console/src/pages/UserDetails/index.module.scss
  packages/console/src/pages/UserDetails/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/user-details.ts
  packages/phrases/src/locales/en/translation/admin-console/user-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/user-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/user-details.ts
Labels: enhancement, size/m

#2471 refactor(console): tab nav
  packages/console/src/components/TabNav/TabNavItem.module.scss
  packages/console/src/components/TabNav/TabNavItem.tsx
  packages/console/src/pages/SignInExperience/components/Preview.module.scss
  packages/phrases/src/locales/de/translation/admin-console/general.ts
  packages/phrases/src/locales/en/translation/admin-console/general.ts
  packages/phrases/src/locales/fr/translation/admin-console/general.ts
  packages/phrases/src/locales/ko/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
Labels: enhancement, size/m

#2479 refactor(console): recover the main content size limitations
  packages/console/src/scss/_underscore.scss
Labels: enhancement, size/xs

#2481 fix(console): set background color for preview iframe
  packages/console/src/pages/SignInExperience/components/Preview.module.scss
Labels: bugfix, size/xs

#2466 refactor(console): settings
  packages/console/src/pages/Settings/components/ChangePassword.module.scss
  packages/console/src/pages/Settings/index.module.scss
  packages/console/src/pages/Settings/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/settings.ts
  packages/phrases/src/locales/en/translation/admin-console/settings.ts
  packages/phrases/src/locales/fr/translation/admin-console/settings.ts
  packages/phrases/src/locales/ko/translation/admin-console/settings.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/settings.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/settings.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/settings.ts
Labels: enhancement, size/s

#2470 feat(core): social related profile session apis
  packages/core/src/routes/session/profile.test.ts
  packages/core/src/routes/session/profile.ts
Labels: feature, size/m

#2465 refactor(console): connector details page
  packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx
  packages/console/src/pages/ConnectorDetails/components/SenderTester/index.tsx
  packages/console/src/pages/ConnectorDetails/index.module.scss
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/scss/resources.module.scss
  packages/phrases/src/locales/de/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/en/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/connector-details.ts
Labels: enhancement, size/m

#2483 style(console): settings
  packages/console/src/pages/Settings/index.module.scss
  packages/console/src/pages/Settings/index.tsx
Labels: size/xs

#2488 fix: master lint error
  packages/console/src/scss/resources.module.scss
Labels: bugfix, size/xs

#2487 fix(console): secondary "cancel" button should use default border style
  packages/console/src/components/ConfirmModal/index.tsx
Labels: bugfix, size/xs

#2492 chore: remove unnecessary console log
  packages/core/src/routes/session/profile.ts
Labels: chore, size/xs

#2477 feat: add POST /connectors
  packages/core/src/__mocks__/connector.ts
  packages/core/src/connectors/index.ts
  packages/core/src/connectors/types.ts
  packages/core/src/queries/connector.test.ts
  packages/core/src/queries/connector.ts
  packages/core/src/routes/connector.test.ts
  packages/core/src/routes/connector.ts
  packages/integration-tests/src/api/connector.ts
  packages/integration-tests/src/helpers.ts
  packages/integration-tests/tests/api/connector.test.ts
  packages/phrases/src/locales/de/errors.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
Labels: feature, size/l

#2490 refactor(console): update "contact us" dark logs in contact modal
  packages/console/src/assets/images/discord-dark.svg
  packages/console/src/assets/images/email-dark.svg
  packages/console/src/assets/images/github-dark.svg
Labels: enhancement, size/s

#2478 feat: add DELETE /connectors/:id
  packages/core/src/queries/connector.test.ts
  packages/core/src/queries/connector.ts
  packages/core/src/routes/connector.test.ts
  packages/core/src/routes/connector.ts
Labels: feature, size/s

#2484 style(console): `CardTitle` should not be shrunk in the flex layout
  packages/console/src/components/CardTitle/index.module.scss
Labels: size/xs

#2482 refactor(console): resources table
  packages/console/src/components/AuditLogTable/index.tsx
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/Connectors/index.tsx
  packages/console/src/pages/Users/index.module.scss
  packages/console/src/pages/Users/index.tsx
  packages/console/src/scss/resources.module.scss
  packages/console/src/scss/table.module.scss
Labels: enhancement, size/xl

#2508 feat: update virtual connector loading to getConfig by id
  packages/core/src/__mocks__/connector.ts
  packages/core/src/connectors/index.ts
  packages/core/src/connectors/types.ts
  packages/core/src/routes/connector.test.ts
  packages/core/src/routes/connector.ts
Labels: feature, size/m

#2485 refactor(console): audit log table
  packages/console/src/components/AuditLogTable/index.module.scss
  packages/console/src/components/AuditLogTable/index.tsx
Labels: enhancement, size/s
