Repository logto-io/logto, pull requests merged in 2022-05, with the labels that each got.

#715 feat(console): integrate dark mode settings
  packages/console/src/App.module.scss
  packages/console/src/App.tsx
  packages/console/src/components/AppContent/components/Topbar/index.module.scss
  packages/console/src/components/AppContent/components/Topbar/index.tsx
  packages/console/src/components/AppContent/index.module.scss
  packages/console/src/components/AppContent/index.tsx
  packages/console/src/components/Drawer/index.module.scss
  packages/console/src/consts/index.ts
  packages/console/src/icons/Logo.tsx
  packages/console/src/pages/Connectors/components/GuideModal/index.module.scss
  packages/console/src/pages/Settings/index.tsx
  packages/console/src/scss/_colors.scss
  packages/console/src/scss/normalized.scss
  packages/console/src/scss/table.module.scss
  packages/phrases/src/locales/en.ts
  packages/schemas/src/foundations/jsonb-types.ts
Labels: feature, size/l

#716 feat(console): integrate language settings
  packages/console/src/App.tsx
  packages/console/src/i18n/init.ts
Labels: feature, size/s

#718 chore: upgrade lockfile version
  pnpm-lock.yaml
Labels: chore, size/xs

#709 refactor(ui): remove /404 path
  packages/ui/src/App.tsx
  packages/ui/src/pages/Passcode/index.test.tsx
  packages/ui/src/pages/Passcode/index.tsx
  packages/ui/src/pages/Register/index.test.tsx
  packages/ui/src/pages/Register/index.tsx
  packages/ui/src/pages/SecondarySignIn/index.test.tsx
  packages/ui/src/pages/SecondarySignIn/index.tsx
  packages/ui/src/pages/SocialRegister/index.test.tsx
  packages/ui/src/pages/SocialRegister/index.tsx
Labels: enhancement, size/m

#717 refactor(ui): main flow mobile design review fix part 1
  packages/ui/src/assets/icons/clear-icon.svg
  packages/ui/src/components/AppContent/index.module.scss
  packages/ui/src/components/Divider/index.module.scss
  packages/ui/src/components/Drawer/index.tsx
  packages/ui/src/components/Icons/ClearIcon.tsx
  packages/ui/src/components/Icons/CloseIcon.tsx
  packages/ui/src/components/Icons/index.ts
  packages/ui/src/components/Input/PasswordInput.tsx
  packages/ui/src/components/Input/PhoneInput.tsx
  packages/ui/src/components/Input/index.tsx
  packages/ui/src/components/LoadingLayer/index.tsx
  packages/ui/src/components/NavBar/index.tsx
  packages/ui/src/components/Passcode/index.module.scss
  packages/ui/src/components/Passcode/index.tsx
  packages/ui/src/components/TermsOfUseModal/index.tsx
  packages/ui/src/containers/CreateAccount/index.module.scss
  packages/ui/src/containers/CreateAccount/index.tsx
  packages/ui/src/containers/PasscodeValidation/index.module.scss
  packages/ui/src/containers/Passwordless/index.module.scss
  packages/ui/src/containers/PasswordlessConfirmModal/index.tsx
  packages/ui/src/containers/SocialCreateAccount/index.module.scss
  packages/ui/src/containers/SocialSignIn/PrimarySocialSignIn.tsx
  packages/ui/src/containers/SocialSignIn/index.module.scss
  packages/ui/src/containers/UsernameSignin/index.module.scss
  packages/ui/src/containers/UsernameSignin/index.tsx
  packages/ui/src/pages/Callback/index.module.scss
  packages/ui/src/pages/SignIn/index.module.scss
  packages/ui/src/pages/SignIn/index.tsx
  packages/ui/src/pages/SignIn/registry.tsx
  packages/ui/src/scss/_underscore.scss
  packages/ui/src/utils/field-validations.ts
Labels: enhancement, size/m

#721 refactor(ui): remove second attribute in unit scss function
  packages/ui/src/scss/_underscore.scss
Labels: enhancement, size/xs

#688 feat(core,schemas): save application id that the user first consented
  packages/core/src/__mocks__/user.ts
  packages/core/src/database/insert-into.test.ts
  packages/core/src/database/update-where.test.ts
  packages/core/src/lib/session.ts
  packages/core/src/middleware/koa-slonik-error-handler.test.ts
  packages/core/src/oidc/adapter.test.ts
  packages/core/src/routes/session.test.ts
  packages/core/src/routes/session.ts
  packages/schemas/src/db-entries/user.ts
  packages/schemas/tables/users.sql
Labels: feature, size/m

#682 feat(core,schemas): log IP and user agent
  packages/core/src/middleware/koa-log.test.ts
  packages/core/src/middleware/koa-log.ts
  packages/schemas/src/types/log.ts
Labels: feature, size/m

#679 feat(console): add column lastSignIn in user management
  packages/console/package.json
  packages/console/src/components/DateTime/index.tsx
  packages/console/src/pages/Users/index.tsx
  packages/core/src/__mocks__/user.ts
  packages/core/src/lib/user.test.ts
  packages/core/src/lib/user.ts
  packages/core/src/queries/user.test.ts
  packages/core/src/routes/session.test.ts
  packages/core/src/routes/session.ts
  packages/schemas/src/db-entries/user.ts
  packages/schemas/src/types/user.ts
  packages/schemas/tables/users.sql
  pnpm-lock.yaml
Labels: feature, size/s

#707 docs: android sdk api reference
  packages/docs/docs/sdk/Kotlin/README.md
  packages/docs/docs/sdk/Kotlin/android/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.auth.logto/-logto-auth-session/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.auth.logto/-logto-web-view-auth-activity/-companion/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.auth.logto/-logto-web-view-auth-activity/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.auth.logto/-logto-web-view-auth-client/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.auth.logto/-logto-web-view-social-handler/-companion/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.auth.logto/-logto-web-view-social-handler/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.auth.logto/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.auth.social.alipay/-alipay-social-session/-companion/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.auth.social.alipay/-alipay-social-session/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.auth.social.alipay/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.auth.social.web/-web-social-result-activity/-companion/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.auth.social.web/-web-social-result-activity/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.auth.social.web/-web-social-session/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.auth.social.web/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.auth.social.wechat/-wechat-social-result-activity/-companion/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.auth.social.wechat/-wechat-social-result-activity/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.auth.social.wechat/-wechat-social-session/-companion/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.auth.social.wechat/-wechat-social-session/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.auth.social.wechat/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.auth.social/-social-exception/-type/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.auth.social/-social-exception/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.auth.social/-social-session-helper/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.auth.social/-social-session/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.auth.social/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.completion/-completion/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.completion/-empty-completion/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.completion/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.constant/-storage-key/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.constant/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.exception/-logto-exception/-message/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.exception/-logto-exception/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.exception/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.extension/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.storage/-persist-storage/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.storage/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.type/-access-token/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.type/-logto-config/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.type/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.util/-logto-utils/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android.util/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android/-logto-client/fetch-user-info.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android/-logto-client/get-access-token-constructor.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android/-logto-client/get-id-token-claims.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android/-logto-client/index.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android/-logto-client/is-authenticated.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android/-logto-client/logto-config.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android/-logto-client/sign-in.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android/-logto-client/sign-out.md
  packages/docs/docs/sdk/Kotlin/android/io.logto.sdk.android/index.md
  packages/docs/docs/sdk/Kotlin/kotlin/index.md
  packages/docs/docs/sdk/Swift/README.md
  packages/docs/src/css/custom.css
Labels: size/xl

#730 fix: `lint:report` script
  packages/connector-alipay/package.json
  packages/connector-aliyun-dm/package.json
  packages/connector-aliyun-sms/package.json
  packages/connector-facebook/package.json
  packages/connector-github/package.json
  packages/connector-google/package.json
  packages/connector-types/package.json
  packages/connector-wechat-native/package.json
  packages/connector-wechat/package.json
  packages/console/package.json
  packages/core/package.json
  packages/jest-config/package.json
  packages/phrases/package.json
  packages/schemas/package.json
  packages/shared/package.json
  packages/ui/package.json
Labels: bugfix, size/s

#733 chore(console): update react sdk to v0.1.5
  packages/console/package.json
  packages/console/src/App.tsx
  pnpm-lock.yaml
Labels: chore, size/xs

#722 refactor(console): promote error boundary to highest level
  packages/console/src/App.tsx
  packages/console/src/components/AppContent/index.tsx
Labels: enhancement, size/s

#736 fix(console): connector details save changes footer
  packages/console/src/pages/ConnectorDetails/index.module.scss
  packages/console/src/pages/ConnectorDetails/index.tsx
Labels: bugfix, size/s

#737 fix: delete custom domain
  packages/console/src/pages/Settings/index.tsx
  packages/core/src/__mocks__/index.ts
  packages/core/src/database/seed.ts
  packages/core/src/env-set/create-pool-by-env.ts
  packages/core/src/env-set/index.ts
  packages/core/src/queries/setting.test.ts
  packages/core/src/routes/setting.test.ts
  packages/schemas/src/db-entries/setting.ts
  packages/schemas/src/seeds/setting.ts
  packages/schemas/tables/settings.sql
Labels: bugfix, size/s

#726 refactor(ui): refactor page layout and base style
  packages/ui/src/components/AppContent/index.module.scss
  packages/ui/src/components/NavBar/index.module.scss
  packages/ui/src/components/Passcode/index.module.scss
  packages/ui/src/containers/CreateAccount/index.module.scss
  packages/ui/src/containers/PasscodeValidation/index.module.scss
  packages/ui/src/containers/Passwordless/index.module.scss
  packages/ui/src/containers/SocialCreateAccount/index.module.scss
  packages/ui/src/containers/SocialSignIn/index.module.scss
  packages/ui/src/containers/UsernameSignin/index.module.scss
  packages/ui/src/pages/Callback/index.module.scss
  packages/ui/src/pages/Consent/index.module.scss
  packages/ui/src/pages/Passcode/index.module.scss
  packages/ui/src/pages/Passcode/index.tsx
  packages/ui/src/pages/Register/index.module.scss
  packages/ui/src/pages/Register/index.tsx
  packages/ui/src/pages/SecondarySignIn/index.module.scss
  packages/ui/src/pages/SecondarySignIn/index.tsx
  packages/ui/src/pages/SignIn/index.module.scss
  packages/ui/src/pages/SocialRegister/index.module.scss
  packages/ui/src/pages/SocialRegister/index.tsx
  packages/ui/src/scss/_underscore.scss
Labels: enhancement, size/m

#724 docs: init introduction
  .vscode/settings.json
  packages/core/src/env-set/create-pool-by-env.ts
  packages/core/src/env-set/index.ts
  packages/core/src/env-set/oidc.ts
  packages/core/src/index.ts
  packages/docs/docs/tutorial/README.md
  packages/docs/docs/tutorial/configuration.md
Labels: size/m

#739 fix(console): text field style in settings
  packages/console/src/components/Dropdown/index.module.scss
  packages/console/src/pages/Settings/index.module.scss
  packages/console/src/pages/Settings/index.tsx
  packages/console/src/scss/_colors.scss
Labels: bugfix, size/s

#728 feat(console): add application column in user management
  packages/console/src/pages/Users/components/ApplicationName/index.tsx
  packages/console/src/pages/Users/index.tsx
  packages/schemas/src/types/user.ts
Labels: feature, size/s

#738 refactor(core): use argon2 for password encryption
  packages/core/package.json
  packages/core/src/__mocks__/user.ts
  packages/core/src/lib/user.test.ts
  packages/core/src/lib/user.ts
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
  packages/core/src/routes/session.test.ts
  packages/core/src/routes/session.ts
  packages/core/src/utils/password.ts
  packages/schemas/src/db-entries/custom-types.ts
  packages/schemas/src/db-entries/user.ts
  packages/schemas/tables/users.sql
  pnpm-lock.yaml
Labels: enhancement, size/m

#744 refactor(core): guard phone number with digital-only regex
  packages/console/src/utilities/regex.ts
  packages/core/src/routes/session.test.ts
  packages/core/src/utils/regex.ts
Labels: enhancement, size/s

#741 fix(console): call settings API after user authentication
  packages/console/src/App.tsx
Labels: bugfix, size/xs

#740 docs: reorg integrate SDK
  packages/console/src/pages/Guide/index.tsx
  packages/docs/docs/tutorial/integrate-sdk/README.md
  packages/docs/docs/tutorial/integrate-sdk/_category_.json
  packages/docs/docs/tutorial/integrate-sdk/android.mdx
  packages/docs/docs/tutorial/integrate-sdk/android/_category_.json
  packages/docs/docs/tutorial/integrate-sdk/react.mdx
  packages/docs/docs/tutorial/integrate-sdk/react/_category_.json
  packages/docs/docusaurus.config.js
  packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/tutorial/integrate-sdk/react.mdx
  packages/docs/src/components/Step/index.tsx
Labels: size/s

#745 feat(core): add experience configs
  packages/schemas/src/foundations/jsonb-types.ts
Labels: feature, size/xs

#747 refactor(console): align with new mdx content from docs
  packages/console/package.json
  packages/console/src/pages/Guide/index.module.scss
  packages/console/src/pages/Guide/index.tsx
Labels: enhancement, size/s

#735 feat(core): separate social sign-in api
  packages/core/src/routes/session.test.ts
  packages/core/src/routes/session.ts
  pnpm-lock.yaml
Labels: feature, size/s

#749 fix(console): prevent autofill background color
  packages/console/src/components/TextInput/index.module.scss
  pnpm-lock.yaml
Labels: bugfix, size/xs

#752 feat(console): multi-text-input delete reminder
  packages/console/src/components/MultiTextInput/DeleteConfirm.tsx
  packages/console/src/components/MultiTextInput/index.module.scss
  packages/console/src/components/MultiTextInput/index.tsx
  packages/console/src/pages/ApplicationDetails/components/Settings.tsx
  packages/console/src/pages/Guide/components/MultiTextInputField/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature, size/m

#743 fix(console): change application column name
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: bugfix, size/xs

#746 feat(console): sign in experience welcome page
  packages/console/src/assets/images/sign-in-experience-welcome.svg
  packages/console/src/pages/SignInExperience/components/Welcome.module.scss
  packages/console/src/pages/SignInExperience/components/Welcome.tsx
  packages/console/src/pages/SignInExperience/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature, size/m

#701 feat(console): sign in methods change alert
  packages/console/src/pages/SignInExperience/components/SaveAlert.module.scss
  packages/console/src/pages/SignInExperience/components/SaveAlert.tsx
  packages/console/src/pages/SignInExperience/components/SignInMethodsPreview.tsx
  packages/console/src/pages/SignInExperience/index.tsx
  packages/console/src/pages/SignInExperience/utilities.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature, size/l

#754 refactor(console): remove second param from 'unit' mixin
  packages/console/src/scss/_underscore.scss
Labels: enhancement, size/xs

#748 docs: integrate iOS SDK
  packages/docs/docs/tutorial/integrate-sdk/README.md
  packages/docs/docs/tutorial/integrate-sdk/ios.mdx
  packages/docs/docs/tutorial/integrate-sdk/react.mdx
Labels: size/m

#751 refactor(console): separate mdx usages from docs
  .gitignore
  packages/console/package.json
  packages/console/src/assets/docs/tutorial/integrate-sdk/android.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/react.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/react_zh-cn.mdx
  packages/console/src/mdx-components/MultiTextInputField/index.tsx
  packages/console/src/mdx-components/Step/index.module.scss
  packages/console/src/mdx-components/Step/index.tsx
  packages/console/src/pages/Connectors/components/GuideModal/index.tsx
  packages/console/src/pages/Guide/index.tsx
  pnpm-lock.yaml
Labels: enhancement, size/xl

#710 feat(console): connector warnings in sign in methods
  packages/console/src/pages/SignInExperience/components/ConnectorSetupWarning.tsx
  packages/console/src/pages/SignInExperience/components/ConnectorsTransfer.tsx
  packages/console/src/pages/SignInExperience/components/SignInMethodsForm.tsx
  packages/console/src/pages/SignInExperience/types.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature, size/m

#753 refactor(console): improve tabs used in mdx files
  packages/console/src/mdx-components/Tabs/index.module.scss
  packages/console/src/mdx-components/Tabs/index.tsx
Labels: enhancement, size/s

#759 docs: downgrade docusaurus to v2.0.0-beta.18
  packages/docs/package.json
  pnpm-lock.yaml
Labels: size/xs

#757 docs: rephrase React SDK integration guide
  packages/docs/docs/tutorial/integrate-sdk/components/AppNote.tsx
  packages/docs/docs/tutorial/integrate-sdk/components/SignInNote.tsx
  packages/docs/docs/tutorial/integrate-sdk/ios.mdx
  packages/docs/docs/tutorial/integrate-sdk/react.mdx
Labels: size/m

#764 refactor(schemas): remove `src/db-entries` from source control
  packages/schemas/.gitignore
  packages/schemas/src/db-entries/application.ts
  packages/schemas/src/db-entries/connector.ts
  packages/schemas/src/db-entries/custom-types.ts
  packages/schemas/src/db-entries/index.ts
  packages/schemas/src/db-entries/log.ts
  packages/schemas/src/db-entries/oidc-model-instance.ts
  packages/schemas/src/db-entries/passcode.ts
  packages/schemas/src/db-entries/resource.ts
  packages/schemas/src/db-entries/role.ts
  packages/schemas/src/db-entries/setting.ts
  packages/schemas/src/db-entries/sign-in-experience.ts
  packages/schemas/src/db-entries/user.ts
Labels: enhancement, size/xl

#763 refactor(ui): social sign-in api update
  packages/ui/src/apis/index.test.ts
  packages/ui/src/apis/social.ts
  packages/ui/src/hooks/use-social.ts
Labels: enhancement, size/s

#742 refactor(ui): main flow ui refine part 2
  packages/phrases/src/locales/en.ts
  packages/ui/src/components/AppContent/index.module.scss
  packages/ui/src/components/ConfirmModal/index.module.scss
  packages/ui/src/components/ConfirmModal/index.tsx
  packages/ui/src/components/Drawer/index.module.scss
  packages/ui/src/components/Drawer/index.tsx
  packages/ui/src/components/Input/index.module.scss
  packages/ui/src/components/Input/index.tsx
  packages/ui/src/components/NavBar/index.module.scss
  packages/ui/src/components/Passcode/index.module.scss
  packages/ui/src/components/Passcode/index.tsx
  packages/ui/src/containers/CreateAccount/index.module.scss
  packages/ui/src/containers/CreateAccount/index.tsx
  packages/ui/src/containers/SignInMethodsLink/index.module.scss
  packages/ui/src/pages/Callback/index.module.scss
  packages/ui/src/pages/Callback/index.tsx
  packages/ui/src/scss/modal.module.scss
  packages/ui/src/scss/normalized.scss
Labels: enhancement, size/s

#761 refactor(ui): refactor ui style foundations
  packages/ui/src/components/AppContent/index.module.scss
  packages/ui/src/components/AppContent/index.tsx
  packages/ui/src/components/ConfirmModal/index.tsx
  packages/ui/src/components/Drawer/index.module.scss
  packages/ui/src/components/Drawer/index.tsx
  packages/ui/src/scss/_basic.scss
  packages/ui/src/scss/_colors.scss
  packages/ui/src/scss/modal.module.scss
Labels: enhancement, size/m

#760 feat(console): add drawer animation
  packages/console/src/components/Drawer/index.module.scss
  packages/console/src/components/Drawer/index.tsx
Labels: feature, size/s

#769 docs: update content
  packages/docs/docs/tutorial/README.md
  packages/docs/docs/tutorial/configuration.md
Labels: size/s

#766 docs: use docs only mode
  packages/docs/docs/tutorial/README.md
  packages/docs/docusaurus.config.js
  packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/tutorial/README.md
  packages/docs/src/pages/index.module.css
  packages/docs/src/pages/index.tsx
  packages/docs/src/pages/markdown-page.md
Labels: size/s

#777 ci: add pr size diff check
  .github/workflows/update-pr-metadata.yml
Labels: size/s

#773 refactor(console): replace monaco editor with prism highlighter
  packages/console/package.json
  packages/console/src/assets/docs/tutorial/integrate-sdk/react.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/react_zh-cn.mdx
  packages/console/src/components/CodeEditor/index.module.scss
  packages/console/src/components/CodeEditor/index.tsx
  packages/console/src/components/CopyToClipboard/index.module.scss
  packages/console/src/components/CopyToClipboard/index.tsx
  packages/console/src/pages/Guide/index.tsx
  packages/console/src/pages/UserDetails/index.tsx
  pnpm-lock.yaml
Labels: enhancement, size/m

#778 refactor(console): refactor guide pages
  packages/console/src/pages/Applications/components/GuideModal/index.module.scss
  packages/console/src/pages/Applications/components/GuideModal/index.tsx
  packages/console/src/pages/Applications/components/LibrarySelector/index.tsx
  packages/console/src/pages/Connectors/components/GuideModal/index.tsx
  packages/console/src/pages/Guide/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: enhancement, size/l

#782 ci: show size diff per file
  .github/workflows/update-pr-metadata.yml
Labels: size/s

#772 fix(ui): fix social native interaction bug
  packages/ui/src/containers/SocialSignIn/PrimarySocialSignIn.tsx
  packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.test.tsx
  packages/ui/src/hooks/use-api.ts
  packages/ui/src/hooks/use-social.ts
  packages/ui/src/include.d/global.d.ts
Labels: bugfix, size/m

#784 ci: fix file size diff comment display
  .github/workflows/update-pr-metadata.yml
Labels: size/xs

#781 feat(console): implement get started page (client UI)
  packages/console/src/App.tsx
  packages/console/src/assets/images/cake.svg
  packages/console/src/assets/images/crab.svg
  packages/console/src/assets/images/drink.svg
  packages/console/src/assets/images/frog.svg
  packages/console/src/assets/images/grinning-face.svg
  packages/console/src/assets/images/owl.svg
  packages/console/src/pages/GetStarted/index.module.scss
  packages/console/src/pages/GetStarted/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature, size/l

#771 ci: init integration test
  .github/workflows/integration-test.yml
  install.js
  packages/core/src/database/seed.ts
  packages/core/src/env-set/create-pool-by-env.ts
  packages/core/src/env-set/index.ts
  packages/core/src/env-set/oidc.ts
  packages/core/src/env-set/parameters.ts
  packages/core/src/env-set/password.ts
  packages/core/src/middleware/koa-spa-proxy.test.ts
Labels: size/m

#785 feat(console): autofocus in create modal
  packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
  packages/console/src/pages/Users/components/CreateForm/index.tsx
Labels: feature, size/xs

#788 ci: add collapse for file diff
  .github/workflows/update-pr-metadata.yml
Labels: size/xs

#787 feat(ui): init destop styling foundation
  packages/ui/package.json
  packages/ui/src/components/AppContent/index.module.scss
  packages/ui/src/components/AppContent/index.tsx
  packages/ui/src/components/Drawer/index.module.scss
  packages/ui/src/components/NavBar/index.module.scss
  packages/ui/src/pages/Callback/index.module.scss
  packages/ui/src/pages/Consent/index.module.scss
  packages/ui/src/pages/ErrorPage/index.module.scss
  packages/ui/src/pages/ErrorPage/index.tsx
  packages/ui/src/pages/Passcode/index.module.scss
  packages/ui/src/pages/Passcode/index.tsx
  packages/ui/src/pages/Register/index.module.scss
  packages/ui/src/pages/Register/index.tsx
  packages/ui/src/pages/SecondarySignIn/index.module.scss
  packages/ui/src/pages/SecondarySignIn/index.tsx
  packages/ui/src/pages/SignIn/index.module.scss
  packages/ui/src/pages/SocialRegister/index.module.scss
  packages/ui/src/pages/SocialRegister/index.tsx
  packages/ui/src/scss/_basic.scss
  packages/ui/src/scss/_desktop.scss
  packages/ui/src/scss/_mobile.scss
  packages/ui/src/scss/_underscore.scss
  pnpm-lock.yaml
Labels: feature, size/l

#786 feat(console): form field tooltip
  packages/console/src/components/FormField/index.module.scss
  packages/console/src/components/FormField/index.tsx
  packages/console/src/icons/Tip.tsx
  packages/console/src/pages/SignInExperience/components/TermsForm.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature, size/s

#789 chore: update README
  README.md
  logo.png
Labels: chore, size/s

#791 feat(console): support persisting get-started progress in settings config
  packages/console/src/hooks/use-configs.ts
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/Connectors/components/GuideModal/index.tsx
  packages/console/src/pages/GetStarted/index.tsx
  packages/console/src/pages/SignInExperience/components/Welcome.tsx
  packages/console/src/pages/SignInExperience/index.tsx
  packages/core/src/__mocks__/index.ts
  packages/core/src/routes/setting.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/seeds/setting.ts
Labels: feature, size/m

#790 fix(ui): catch request exceptions with no response body
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/ui/src/hooks/use-api.ts
Labels: bugfix, size/s

#792 fix(ui): fix typo
  packages/ui/src/pages/SignIn/index.tsx
  packages/ui/src/pages/SignIn/registry.tsx
Labels: bugfix, size/xs

#793 chore: update README
  README.md
Labels: chore, size/s

#801 fix(console): resolve js warning reported in code editor component
  packages/console/src/components/CodeEditor/index.tsx
Labels: bugfix, size/xs

#755 feat(console): sign in exp guide
  packages/console/src/components/Alert/index.module.scss
  packages/console/src/components/Alert/index.tsx
  packages/console/src/pages/SignInExperience/components/GuideModal.module.scss
  packages/console/src/pages/SignInExperience/components/GuideModal.tsx
  packages/console/src/pages/SignInExperience/components/Welcome.tsx
  packages/console/src/pages/SignInExperience/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/schemas/src/foundations/jsonb-types.ts
Labels: feature, size/l

#732 feat(core): update connector db schema
  packages/connector-alipay/src/constant.ts
  packages/connector-alipay/src/index.ts
  packages/connector-aliyun-dm/src/constant.ts
  packages/connector-aliyun-dm/src/index.ts
  packages/connector-aliyun-sms/src/constant.ts
  packages/connector-aliyun-sms/src/index.ts
  packages/connector-facebook/src/constant.ts
  packages/connector-facebook/src/index.ts
  packages/connector-github/src/constant.ts
  packages/connector-github/src/index.ts
  packages/connector-google/src/constant.ts
  packages/connector-google/src/index.ts
  packages/connector-types/src/index.ts
  packages/connector-wechat-native/src/constant.ts
  packages/connector-wechat-native/src/index.ts
  packages/connector-wechat/src/constant.ts
  packages/connector-wechat/src/index.ts
  packages/console/src/components/UnnamedTrans/index.tsx
  packages/console/src/pages/Connectors/components/GuideModal/index.tsx
  packages/console/src/pages/UserDetails/components/UserConnectors.tsx
  packages/core/package.json
  packages/core/src/__mocks__/connector.ts
  packages/core/src/connectors/index.test.ts
  packages/core/src/connectors/index.ts
  packages/core/src/connectors/utilities/index.test.ts
  packages/core/src/connectors/utilities/index.ts
  packages/core/src/lib/passcode.test.ts
  packages/core/src/queries/connector.test.ts
  packages/core/src/queries/connector.ts
  packages/core/src/routes/connector.test.ts
  packages/phrases/src/index.ts
  packages/phrases/src/types.ts
  packages/schemas/src/types/connector.ts
  packages/schemas/tables/connectors.sql
  packages/ui/src/__mocks__/logto.tsx
  packages/ui/src/components/Button/SocialIconButton.tsx
  packages/ui/src/components/Button/SocialLinkButton.tsx
  packages/ui/src/components/Button/index.test.tsx
  packages/ui/src/containers/SocialSignIn/PrimarySocialSignIn.tsx
  packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.test.tsx
  packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.tsx
  packages/ui/src/hooks/use-social.ts
  packages/ui/src/pages/Callback/index.tsx
  packages/ui/src/types/index.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#795 style(ui): refactor page level styling for both mobile & desktop
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/ui/src/components/Divider/index.module.scss
  packages/ui/src/components/NavBar/index.module.scss
  packages/ui/src/components/NavBar/index.tsx
  packages/ui/src/components/Passcode/index.module.scss
  packages/ui/src/containers/CreateAccount/index.module.scss
  packages/ui/src/containers/PasscodeValidation/index.module.scss
  packages/ui/src/containers/Passwordless/index.module.scss
  packages/ui/src/containers/SocialCreateAccount/index.module.scss
  packages/ui/src/containers/SocialSignIn/index.module.scss
  packages/ui/src/containers/UsernameSignin/index.module.scss
  packages/ui/src/pages/Callback/index.module.scss
  packages/ui/src/pages/Callback/index.tsx
  packages/ui/src/pages/Consent/index.module.scss
  packages/ui/src/pages/Consent/index.tsx
  packages/ui/src/pages/ErrorPage/index.module.scss
  packages/ui/src/pages/ErrorPage/index.tsx
  packages/ui/src/pages/Passcode/index.module.scss
  packages/ui/src/pages/Register/index.module.scss
  packages/ui/src/pages/SecondarySignIn/index.module.scss
  packages/ui/src/pages/SignIn/index.module.scss
  packages/ui/src/pages/SocialRegister/index.module.scss
  packages/ui/src/pages/SocialRegister/index.tsx
  packages/ui/src/scss/_desktop.scss
  packages/ui/src/scss/_mobile.scss
  packages/ui/src/scss/_underscore.scss
Labels: size/l

#798 feat(console): implement get-started progress indicator component
  packages/console/src/assets/images/cake.svg
  packages/console/src/assets/images/check-demo.svg
  packages/console/src/assets/images/circle-tick.svg
  packages/console/src/assets/images/crab.svg
  packages/console/src/assets/images/create-app.svg
  packages/console/src/assets/images/customize.svg
  packages/console/src/assets/images/drink.svg
  packages/console/src/assets/images/frog.svg
  packages/console/src/assets/images/further-readings.svg
  packages/console/src/assets/images/grinning-face.svg
  packages/console/src/assets/images/one-click.svg
  packages/console/src/assets/images/owl.svg
  packages/console/src/assets/images/passwordless.svg
  packages/console/src/assets/images/tada.svg
  packages/console/src/components/AppContent/components/Topbar/index.module.scss
  packages/console/src/components/AppContent/components/Topbar/index.tsx
  packages/console/src/components/AppContent/index.module.scss
  packages/console/src/components/Dropdown/DropdownItem.tsx
  packages/console/src/components/Dropdown/index.module.scss
  packages/console/src/components/Dropdown/index.tsx
  packages/console/src/components/Dropdown/use-position.ts
  packages/console/src/components/Index/index.module.scss
  packages/console/src/components/Index/index.tsx
  packages/console/src/mdx-components/Step/index.module.scss
  packages/console/src/mdx-components/Step/index.tsx
  packages/console/src/pages/GetStarted/components/GetStartedProgress/index.module.scss
  packages/console/src/pages/GetStarted/components/GetStartedProgress/index.tsx
  packages/console/src/pages/GetStarted/hook.ts
  packages/console/src/pages/GetStarted/index.module.scss
  packages/console/src/pages/GetStarted/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature, size/xl

#783 feat(console): sign in experience preview
  packages/console/src/components/TabNav/TabNavItem.module.scss
  packages/console/src/components/TabNav/TabNavItem.tsx
  packages/console/src/components/TabNav/TabNavLink.tsx
  packages/console/src/components/TabNav/index.tsx
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/Connectors/index.tsx
  packages/console/src/pages/Settings/index.tsx
  packages/console/src/pages/SignInExperience/components/Preview.module.scss
  packages/console/src/pages/SignInExperience/components/Preview.tsx
  packages/console/src/pages/SignInExperience/index.module.scss
  packages/console/src/pages/SignInExperience/index.tsx
  packages/console/src/pages/UserDetails/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature, size/l

#810 fix(console): typo
  packages/console/src/pages/ApplicationDetails/components/DeleteForm/index.module.scss
  packages/console/src/pages/ApplicationDetails/components/DeleteForm/index.tsx
Labels: bugfix, size/xs

#802 refactor(console): use-position in tooltip
  packages/console/src/components/CopyToClipboard/index.module.scss
  packages/console/src/components/CopyToClipboard/index.tsx
  packages/console/src/components/Dropdown/index.tsx
  packages/console/src/components/Dropdown/use-position.ts
  packages/console/src/components/FormField/index.tsx
  packages/console/src/components/Tooltip/index.module.scss
  packages/console/src/components/Tooltip/index.tsx
  packages/console/src/hooks/use-position.ts
  packages/console/src/pages/ConnectorDetails/components/SenderTester/index.module.scss
  packages/console/src/pages/ConnectorDetails/components/SenderTester/index.tsx
  packages/console/src/pages/GetStarted/components/GetStartedProgress/index.tsx
Labels: enhancement, size/l

#812 refactor(console): use switch-case to make the select aligment logic more readable
  packages/console/src/hooks/use-position.ts
Labels: enhancement, size/s

#813 fix(console): update shadow styles
  packages/console/src/components/RadioGroup/index.module.scss
  packages/console/src/components/Toast/index.module.scss
Labels: bugfix, size/xs

#805 fix(console): tip icon color
  packages/console/src/components/FormField/index.module.scss
Labels: bugfix, size/xs

#806 feat(core): expose connector and metadata from sendPasscode
  packages/core/src/lib/passcode.ts
Labels: feature, size/xs

#807 refactor(connectors): reorganize connectors
  packages/connector-aliyun-dm/src/constant.ts
  packages/connector-aliyun-dm/src/index.test.ts
  packages/connector-aliyun-dm/src/index.ts
  packages/connector-aliyun-dm/src/single-send-mail.ts
  packages/connector-aliyun-dm/src/types.ts
  packages/connector-aliyun-dm/src/utils.ts
  packages/connector-aliyun-sms/src/constant.ts
  packages/connector-aliyun-sms/src/index.test.ts
  packages/connector-aliyun-sms/src/index.ts
  packages/connector-aliyun-sms/src/single-send-text.ts
  packages/connector-aliyun-sms/src/types.ts
  packages/connector-aliyun-sms/src/utils.ts
  packages/connector-facebook/src/constant.ts
  packages/connector-facebook/src/index.test.ts
  packages/connector-facebook/src/index.ts
  packages/connector-facebook/src/types.ts
  packages/connector-github/src/constant.ts
  packages/connector-github/src/index.test.ts
  packages/connector-github/src/index.ts
  packages/connector-github/src/types.ts
  packages/connector-google/src/constant.ts
  packages/connector-google/src/index.test.ts
  packages/connector-google/src/index.ts
  packages/connector-google/src/types.ts
  packages/connector-wechat-native/src/constant.ts
  packages/connector-wechat-native/src/index.test.ts
  packages/connector-wechat-native/src/index.ts
  packages/connector-wechat-native/src/types.ts
  packages/connector-wechat/src/constant.ts
  packages/connector-wechat/src/index.test.ts
  packages/connector-wechat/src/index.ts
  packages/connector-wechat/src/types.ts
Labels: enhancement, chore, size/xl

#804 feat(core): add socialConnectors details for get sign-in-settings
  packages/core/src/routes/session.test.ts
  packages/core/src/routes/session.ts
  packages/ui/src/__mocks__/logto.tsx
  packages/ui/src/apis/settings.ts
  packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.tsx
  packages/ui/src/hooks/use-social.ts
  packages/ui/src/pages/Callback/index.tsx
  packages/ui/src/types/index.ts
  packages/ui/src/utils/sign-in-experience.ts
Labels: feature, size/m

#811 feat(console): page skeleton animation mixin
  packages/console/src/scss/_colors.scss
  packages/console/src/scss/_underscore.scss
Labels: feature, size/s

#808 feat(console): hide get-started page on clicking 'Hide this' button
  packages/console/src/App.tsx
  packages/console/src/components/AppContent/components/Sidebar/consts.tsx
  packages/console/src/components/AppContent/components/Sidebar/hook.tsx
  packages/console/src/components/AppContent/components/Sidebar/index.tsx
  packages/console/src/components/ConfirmModal/index.tsx
  packages/console/src/pages/GetStarted/components/GetStartedProgress/index.tsx
  packages/console/src/pages/GetStarted/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/schemas/src/foundations/jsonb-types.ts
Labels: feature, size/l

#820 fix(connector-wechat-native): fix wechat-native target
  packages/connector-wechat-native/src/constant.ts
  packages/core/src/connectors/index.test.ts
Labels: bugfix, size/xs

#822 refactor(ui): add ui social connector filters
  packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.test.tsx
  packages/ui/src/hooks/use-social.ts
  packages/ui/src/hooks/utils.test.ts
  packages/ui/src/hooks/utils.ts
  packages/ui/src/types/index.ts
Labels: enhancement, size/l

#767 feat(core,schemas): koaLogSession middleware
  packages/core/src/middleware/koa-log-session.test.ts
  packages/core/src/middleware/koa-log-session.ts
  packages/core/src/middleware/koa-log.test.ts
  packages/core/src/middleware/koa-log.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/session.test.ts
  packages/core/src/routes/session.ts
  packages/schemas/src/types/log.ts
Labels: feature, size/m

#828 chore: use cross-env to make 'pnpm dev' compatible on windows
  packages/console/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: chore, size/xs

#829 refactor(console): adjust dark theme styles per updated UX design
  packages/console/package.json
  packages/console/src/App.tsx
  packages/console/src/components/AppContent/components/Sidebar/components/Item/index.module.scss
  packages/console/src/components/Button/index.module.scss
  packages/console/src/components/CopyToClipboard/index.module.scss
  packages/console/src/components/ItemPreview/index.module.scss
  packages/console/src/components/LinkButton/index.module.scss
  packages/console/src/components/TabNav/TabNavItem.module.scss
  packages/console/src/components/TextButton/index.module.scss
  packages/console/src/mdx-components/Tabs/index.module.scss
  packages/console/src/pages/Applications/components/GuideModal/index.module.scss
  packages/console/src/pages/GetStarted/index.module.scss
  packages/console/src/scss/_colors.scss
  pnpm-lock.yaml
Labels: enhancement, size/s

#814 style(ui): container style adjustment
  packages/ui/src/components/NavBar/index.module.scss
  packages/ui/src/containers/PasscodeValidation/index.module.scss
  packages/ui/src/containers/SignInMethodsLink/index.module.scss
  packages/ui/src/containers/SocialCreateAccount/index.module.scss
  packages/ui/src/pages/ErrorPage/index.module.scss
  packages/ui/src/scss/_desktop.scss
  packages/ui/src/scss/_mobile.scss
Labels: size/m

#815 style(ui): terms of use checkbox ui
  packages/ui/src/assets/icons/check-box.svg
  packages/ui/src/assets/icons/radio-button.svg
  packages/ui/src/components/Checkbox/index.module.scss
  packages/ui/src/components/Checkbox/index.tsx
  packages/ui/src/components/Icons/CheckBoxIcon.tsx
  packages/ui/src/components/Icons/RadioButtonIcon.tsx
  packages/ui/src/components/Icons/index.ts
  packages/ui/src/components/TermsOfUse/index.module.scss
  packages/ui/src/components/TermsOfUse/index.tsx
Labels: size/m

#816 style(ui): add desktop styling
  packages/ui/src/scss/_desktop.scss
  packages/ui/src/scss/_mobile.scss
Labels: size/s

#817 style(ui): button & confirm modal
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/ui/src/components/Button/SocialIconButton.module.scss
  packages/ui/src/components/Button/SocialLinkButton.module.scss
  packages/ui/src/components/Button/SocialLinkButton.tsx
  packages/ui/src/components/Button/index.module.scss
  packages/ui/src/components/Button/index.tsx
  packages/ui/src/components/Checkbox/index.tsx
  packages/ui/src/components/ConfirmModal/AcModal.tsx
  packages/ui/src/components/ConfirmModal/Acmodal.module.scss
  packages/ui/src/components/ConfirmModal/MobileModal.module.scss
  packages/ui/src/components/ConfirmModal/MobileModal.tsx
  packages/ui/src/components/ConfirmModal/index.tsx
  packages/ui/src/components/ConfirmModal/type.ts
  packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.tsx
  packages/ui/src/containers/SocialSignIn/index.module.scss
  packages/ui/src/scss/modal.module.scss
Labels: size/l

#826 refactor(console): refine scrollbar styles and positions
  packages/console/src/components/AppContent/index.module.scss
  packages/console/src/scss/normalized.scss
Labels: enhancement, size/s

#827 fix(core): catch and print interaction not found error
  packages/core/src/middleware/koa-log-session.test.ts
  packages/core/src/middleware/koa-log-session.ts
Labels: bugfix, size/s

#819 fix(console): use native color picker style
  packages/console/src/components/ColorPicker/index.module.scss
  packages/console/src/components/ColorPicker/index.tsx
Labels: bugfix, size/s

#835 fix(console): long text should wrap in code editor
  packages/console/src/components/CodeEditor/index.module.scss
  packages/console/src/components/CodeEditor/index.tsx
Labels: bugfix, size/s

#818 style(ui): rest components style update
  packages/ui/src/components/BrandingHeader/index.module.scss
  packages/ui/src/components/Divider/index.module.scss
  packages/ui/src/components/Input/PasswordInput.tsx
  packages/ui/src/components/Input/PhoneInput.tsx
  packages/ui/src/components/Input/index.module.scss
  packages/ui/src/components/Input/index.tsx
  packages/ui/src/components/Input/phoneInput.module.scss
  packages/ui/src/components/Passcode/index.module.scss
  packages/ui/src/components/Passcode/index.tsx
  packages/ui/src/components/TextLink/index.module.scss
  packages/ui/src/components/Toast/index.module.scss
Labels: size/m

#836 feat(console): contact us icon and texts
  packages/console/src/assets/images/discord.svg
  packages/console/src/assets/images/email.svg
  packages/console/src/assets/images/github.svg
  packages/console/src/assets/images/slack.svg
  packages/console/src/components/AppContent/components/Sidebar/components/Contact/const.tsx
  packages/console/src/components/AppContent/components/Sidebar/components/Contact/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature, size/s

#825 feat(console): add page loading skeleton to data table and detail pages
  packages/console/src/App.tsx
  packages/console/src/components/DetailsSkeleton/index.module.scss
  packages/console/src/components/DetailsSkeleton/index.tsx
  packages/console/src/components/Table/ItemPreviewLoading.module.scss
  packages/console/src/components/Table/ItemPreviewLoading.tsx
  packages/console/src/components/Table/TableLoading.module.scss
  packages/console/src/components/Table/TableLoading.tsx
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/scss/_underscore.scss
Labels: feature, size/l

#803 refactor(ui): add session guard to ui page
  packages/core/src/app/init.ts
  packages/core/src/middleware/koa-client-session-guard.test.ts
  packages/core/src/middleware/koa-client-session-guard.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/ui/src/App.tsx
  packages/ui/src/pages/ErrorPage/index.test.tsx
  packages/ui/src/pages/ErrorPage/index.tsx
Labels: enhancement, size/m

#832 fix(ui): fix create account page reload issue
  packages/ui/src/components/TextLink/index.tsx
  packages/ui/src/pages/SignIn/registry.tsx
Labels: bugfix, size/s

#831 fix(ui): add body background color
  packages/ui/src/components/AppContent/index.module.scss
Labels: bugfix, size/xs

#834 feat(ui): add social dropdown list for desktop
  packages/ui/src/components/Dropdown/DropdownItem.module.scss
  packages/ui/src/components/Dropdown/DropdownItem.tsx
  packages/ui/src/components/Dropdown/index.module.scss
  packages/ui/src/components/Dropdown/index.tsx
  packages/ui/src/components/Icons/MoreSocialIcon.tsx
  packages/ui/src/containers/SocialSignIn/PrimarySocialSignIn.module.scss
  packages/ui/src/containers/SocialSignIn/PrimarySocialSignIn.tsx
  packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.module.scss
  packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.tsx
  packages/ui/src/containers/SocialSignIn/SocialSignInDropdown.module.scss
  packages/ui/src/containers/SocialSignIn/SocialSignInDropdown.tsx
  packages/ui/src/containers/SocialSignIn/index.ts
  packages/ui/src/scss/_desktop.scss
  packages/ui/src/utils/sign-in-experience.ts
Labels: feature, size/l

#838 fix(UI): fix connector target and id used in UI
  packages/ui/src/__mocks__/logto.tsx
  packages/ui/src/components/Button/SocialIconButton.tsx
  packages/ui/src/components/Button/SocialLinkButton.tsx
  packages/ui/src/components/Button/index.test.tsx
  packages/ui/src/containers/SocialSignIn/PrimarySocialSignIn.tsx
  packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.test.tsx
  packages/ui/src/types/index.ts
Labels: bugfix, size/s

#840 fix(console): fix infinite loading issue when not authenticated
  packages/console/src/App.tsx
Labels: bugfix, size/xs

#824 feat(core): log sending passcode with connector id
  packages/core/src/routes/session.test.ts
  packages/core/src/routes/session.ts
  packages/schemas/src/types/log.ts
Labels: feature, size/s

#823 feat(core): get /logs
  packages/core/src/queries/log.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/log.test.ts
  packages/core/src/routes/log.ts
Labels: feature, size/m

#841 fix(ui): fix sign-in not found bug
  packages/core/src/middleware/koa-client-session-guard.ts
Labels: bugfix, size/xs

#845 style(console): add min & max widths to center stage page contents
  packages/console/src/components/AppContent/index.module.scss
  packages/console/src/components/Drawer/index.module.scss
  packages/console/src/pages/SignInExperience/index.module.scss
Labels: size/s

#830 feat(console): add app icon and api icon
  packages/console/src/assets/images/api-resource.svg
  packages/console/src/assets/images/native-app.svg
  packages/console/src/assets/images/single-page-app.svg
  packages/console/src/assets/images/traditional-web-app.svg
  packages/console/src/components/ItemPreview/index.tsx
  packages/console/src/consts/icons.ts
  packages/console/src/consts/index.ts
  packages/console/src/pages/ApiResourceDetails/index.module.scss
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/ApplicationDetails/index.module.scss
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/Applications/index.tsx
Labels: feature, size/m

#837 fix(console): align usage of customizeSignInExperience
  packages/console/src/pages/SignInExperience/components/GuideModal.tsx
  packages/console/src/pages/SignInExperience/index.tsx
  packages/schemas/src/foundations/jsonb-types.ts
Labels: bugfix, size/xs

#843 fix(console): open new tab for setup connectors
  packages/console/src/components/Transfer/index.module.scss
  packages/console/src/pages/SignInExperience/components/ConnectorsTransfer.tsx
Labels: bugfix, size/xs

#844 fix(console): reduce welcome image size
  packages/console/src/assets/images/sign-in-experience-welcome.svg
Labels: bugfix, size/s

#842 fix(ui): add default success true for no response api
  packages/ui/src/apis/index.test.ts
  packages/ui/src/apis/register.ts
  packages/ui/src/apis/sign-in.ts
Labels: bugfix, size/s

#849 refactor(ui): add svg transformer
  packages/jest-config/jest.config.ts
  packages/jest-config/package.json
  packages/ui/.parcelrc
  packages/ui/package.json
  packages/ui/src/__mocks__/react-i18next.jsx
  packages/ui/src/assets/icons/arrow-down.svg
  packages/ui/src/assets/icons/arrow-prev.svg
  packages/ui/src/assets/icons/arrow.svg
  packages/ui/src/assets/icons/check-box.svg
  packages/ui/src/assets/icons/checkbox-icon.svg
  packages/ui/src/assets/icons/clear-icon.svg
  packages/ui/src/assets/icons/close-icon.svg
  packages/ui/src/assets/icons/error-icon.svg
  packages/ui/src/assets/icons/expand-icon.svg
  packages/ui/src/assets/icons/loading-icon.svg
  packages/ui/src/assets/icons/loading.svg
  packages/ui/src/assets/icons/more-social-icon.svg
  packages/ui/src/assets/icons/password-hide-icon.svg
  packages/ui/src/assets/icons/password-show-icon.svg
  packages/ui/src/assets/icons/privacy-icon.svg
  packages/ui/src/assets/icons/radio-button-icon.svg
  packages/ui/src/assets/icons/radio-button.svg
  packages/ui/src/assets/index.d.ts
  packages/ui/src/components/Checkbox/index.module.scss
  packages/ui/src/components/Checkbox/index.tsx
  packages/ui/src/components/ConfirmModal/AcModal.tsx
  packages/ui/src/components/ConfirmModal/Acmodal.module.scss
  packages/ui/src/components/Drawer/index.module.scss
  packages/ui/src/components/Drawer/index.tsx
  packages/ui/src/components/Icons/CheckBoxIcon.tsx
  packages/ui/src/components/Icons/ClearIcon.tsx
  packages/ui/src/components/Icons/CloseIcon.tsx
  packages/ui/src/components/Icons/DownArrowIcon.tsx
  packages/ui/src/components/Icons/ErrorIcon.tsx
  packages/ui/src/components/Icons/ExpandMoreIcon.tsx
  packages/ui/src/components/Icons/LoadingIcon.tsx
  packages/ui/src/components/Icons/MoreSocialIcon.tsx
  packages/ui/src/components/Icons/NavArrowIcon.tsx
  packages/ui/src/components/Icons/PrivacyIcon.tsx
  packages/ui/src/components/Icons/index.ts
  packages/ui/src/components/Input/PasswordInput.tsx
  packages/ui/src/components/Input/PhoneInput.tsx
  packages/ui/src/components/Input/index.module.scss
  packages/ui/src/components/Input/index.test.tsx
  packages/ui/src/components/Input/index.tsx
  packages/ui/src/components/Input/phoneInput.module.scss
  packages/ui/src/components/LoadingLayer/index.module.scss
  packages/ui/src/components/LoadingLayer/index.tsx
  packages/ui/src/components/NavBar/index.module.scss
  packages/ui/src/components/NavBar/index.tsx
  packages/ui/src/containers/SocialSignIn/PrimarySocialSignIn.module.scss
  packages/ui/src/containers/SocialSignIn/PrimarySocialSignIn.tsx
  packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.module.scss
  packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.tsx
  packages/ui/src/containers/SocialSignIn/SocialSignInDropdown.tsx
  packages/ui/src/pages/ErrorPage/index.tsx
  pnpm-lock.yaml
Labels: enhancement, size/xl

#847 fix(console): improve swr error handling to avoid app crash
  packages/console/src/hooks/use-api.ts
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/Connectors/index.tsx
  packages/console/src/pages/Settings/index.tsx
  packages/console/src/pages/SignInExperience/components/ConnectorsTransfer.tsx
  packages/console/src/pages/SignInExperience/components/SignInMethodsPreview.tsx
  packages/console/src/pages/SignInExperience/index.tsx
  packages/console/src/pages/UserDetails/components/UserConnectors.tsx
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/pages/Users/index.tsx
Labels: bugfix, size/s

#852 feat(ui): implement preview mode
  packages/console/src/pages/SignInExperience/components/Preview.tsx
  packages/ui/src/App.tsx
  packages/ui/src/components/AppContent/index.tsx
  packages/ui/src/components/Checkbox/index.tsx
  packages/ui/src/components/ConfirmModal/AcModal.tsx
  packages/ui/src/components/ConfirmModal/index.tsx
  packages/ui/src/components/NavBar/index.tsx
  packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.tsx
  packages/ui/src/hooks/use-api.ts
  packages/ui/src/hooks/use-page-context.ts
  packages/ui/src/hooks/use-platform.ts
  packages/ui/src/hooks/use-preview.ts
  packages/ui/src/hooks/use-theme.ts
  packages/ui/src/pages/SocialRegister/index.tsx
  packages/ui/src/types/index.ts
  packages/ui/src/utils/sign-in-experience.ts
Labels: feature, size/m

#839 feat(console): add preview in guide modal
  packages/console/src/pages/SignInExperience/components/GuideModal.module.scss
  packages/console/src/pages/SignInExperience/components/GuideModal.tsx
  packages/console/src/pages/SignInExperience/components/Preview.module.scss
  packages/console/src/pages/SignInExperience/components/Preview.tsx
Labels: feature, size/s

#853 test: setup integration test package
  .github/workflows/integration-test.yml
  .vscode/settings.json
  packages/integration-tests/jest.config.ts
  packages/integration-tests/package.json
  packages/integration-tests/src/api.ts
  packages/integration-tests/tests/health-check.test.ts
  packages/integration-tests/tsconfig.json
  packages/integration-tests/tsconfig.test.json
  packages/jest-config/package.json
  pnpm-lock.yaml
Labels: testing, size/m

#851 feat(core,console): social connector targets
  packages/console/src/hooks/use-connector-groups.ts
  packages/console/src/pages/SignInExperience/components/ConnectorsTransfer.tsx
  packages/console/src/pages/SignInExperience/components/SignInMethodsForm.tsx
  packages/console/src/pages/SignInExperience/components/SignInMethodsPreview.tsx
  packages/console/src/pages/SignInExperience/utilities.ts
  packages/console/src/types/connector.ts
  packages/core/src/__mocks__/connector.ts
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/lib/sign-in-experience.ts
  packages/core/src/queries/sign-in-experience.test.ts
  packages/core/src/routes/session.test.ts
  packages/core/src/routes/session.ts
  packages/core/src/routes/sign-in-experience.guard.test.ts
  packages/core/src/routes/sign-in-experience.test.ts
  packages/core/src/routes/sign-in-experience.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/seeds/sign-in-experience.ts
  packages/schemas/tables/sign_in_experiences.sql
  packages/ui/src/__mocks__/logto.tsx
Labels: feature, size/l

#861 refactor: use `@silverhand/jest-config`
  packages/connector-alipay/jest.config.ts
  packages/connector-alipay/package.json
  packages/connector-aliyun-dm/jest.config.ts
  packages/connector-aliyun-dm/package.json
  packages/connector-aliyun-sms/jest.config.ts
  packages/connector-aliyun-sms/package.json
  packages/connector-facebook/jest.config.ts
  packages/connector-facebook/package.json
  packages/connector-github/jest.config.ts
  packages/connector-github/package.json
  packages/connector-google/jest.config.ts
  packages/connector-google/package.json
  packages/connector-wechat-native/jest.config.ts
  packages/connector-wechat-native/package.json
  packages/connector-wechat/jest.config.ts
  packages/connector-wechat/package.json
  packages/core/jest.config.ts
  packages/core/package.json
  packages/jest-config/jest.config.ts
  packages/jest-config/package.json
  packages/jest-config/tsconfig.json
  packages/ui/jest.config.ts
  packages/ui/package.json
  pnpm-lock.yaml
Labels: enhancement, size/m

#867 fix(core): disabled session check for preview mode
  packages/core/src/middleware/koa-client-session-guard.ts
Labels: bugfix, size/xs

#855 fix(ui): ui refinement
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/ui/src/components/AppContent/index.module.scss
  packages/ui/src/components/ConfirmModal/AcModal.tsx
  packages/ui/src/components/ConfirmModal/MobileModal.tsx
  packages/ui/src/components/Drawer/index.tsx
  packages/ui/src/components/Input/index.module.scss
  packages/ui/src/components/Passcode/index.module.scss
  packages/ui/src/containers/PasswordlessConfirmModal/index.tsx
  packages/ui/src/containers/UsernameSignin/index.module.scss
  packages/ui/src/containers/UsernameSignin/index.tsx
  packages/ui/src/hooks/use-form.ts
  packages/ui/src/pages/Passcode/index.tsx
  packages/ui/src/scss/modal.module.scss
Labels: bugfix, size/s

#860 feat(console): dark logo
  packages/console/src/pages/SignInExperience/components/BrandingForm.tsx
  packages/console/src/pages/SignInExperience/utilities.ts
  packages/core/src/routes/sign-in-experience.branding.guard.test.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/seeds/sign-in-experience.ts
Labels: feature, size/s

#870 chore: add `ci:*` scripts
  .github/workflows/main.yml
  package.json
Labels: chore, size/s

#850 feat(connector-sendgrid-email): add sendgrid email connector
  packages/connector-aliyun-dm/docs/config-template.md
  packages/connector-aliyun-sms/docs/config-template.md
  packages/connector-sendgrid-mail/README.md
  packages/connector-sendgrid-mail/docs/config-template.md
  packages/connector-sendgrid-mail/jest.config.ts
  packages/connector-sendgrid-mail/package.json
  packages/connector-sendgrid-mail/src/constant.ts
  packages/connector-sendgrid-mail/src/index.test.ts
  packages/connector-sendgrid-mail/src/index.ts
  packages/connector-sendgrid-mail/src/mock.ts
  packages/connector-sendgrid-mail/src/types.ts
  packages/connector-sendgrid-mail/tsconfig.base.json
  packages/connector-sendgrid-mail/tsconfig.build.json
  packages/connector-sendgrid-mail/tsconfig.json
  packages/connector-sendgrid-mail/tsconfig.test.json
  packages/connector-types/src/index.ts
  packages/core/package.json
  packages/core/src/connectors/index.test.ts
  packages/core/src/connectors/index.ts
  pnpm-lock.yaml
Labels: feature, size/l

#857 feat(console): user icon
  packages/console/src/assets/avatars/avatar-001.png
  packages/console/src/assets/avatars/avatar-002.png
  packages/console/src/assets/avatars/avatar-003.png
  packages/console/src/assets/avatars/avatar-004.png
  packages/console/src/assets/avatars/avatar-005.png
  packages/console/src/assets/avatars/avatar-006.png
  packages/console/src/assets/avatars/avatar-007.png
  packages/console/src/assets/avatars/avatar-008.png
  packages/console/src/assets/avatars/avatar-009.png
  packages/console/src/assets/avatars/avatar-010.png
  packages/console/src/components/ItemPreview/index.tsx
  packages/console/src/consts/avatars.ts
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/UserDetails/index.module.scss
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/pages/Users/index.module.scss
  packages/console/src/pages/Users/index.tsx
Labels: feature, size/s

#872 fix(console): upgrade react-sdk and integrate session expired page
  packages/console/package.json
  packages/console/src/App.module.scss
  packages/console/src/App.tsx
  packages/console/src/assets/images/warning.svg
  packages/console/src/components/AppContent/components/Sidebar/hook.tsx
  packages/console/src/components/AppContent/components/Sidebar/index.tsx
  packages/console/src/components/AppContent/index.module.scss
  packages/console/src/components/AppContent/index.tsx
  packages/console/src/components/LogtoLoading/index.module.scss
  packages/console/src/components/SessionExpired/index.module.scss
  packages/console/src/components/SessionExpired/index.tsx
  packages/console/src/hooks/use-configs.ts
  packages/console/src/pages/Callback/index.tsx
  packages/console/src/utilities/app.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  pnpm-lock.yaml
Labels: bugfix, size/l

#854 feat: update field check rules
  packages/console/package.json
  packages/console/src/pages/ConnectorDetails/components/SenderTester/index.tsx
  packages/console/src/utilities/regex.ts
  packages/core/package.json
  packages/core/src/routes/admin-user.ts
  packages/core/src/routes/connector.ts
  packages/core/src/routes/session.test.ts
  packages/core/src/routes/session.ts
  packages/core/src/utils/regex.test.ts
  packages/schemas/package.json
  packages/schemas/src/foundations/jsonb-types.ts
  packages/shared/src/file-utils.ts
  packages/shared/src/index.ts
  packages/shared/src/regex.ts
  pnpm-lock.yaml
Labels: feature, size/s

#874 fix(ui): fix countdown bug
  packages/phrases/src/locales/en.ts
  packages/ui/src/containers/PasscodeValidation/index.tsx
Labels: bugfix, size/s

#871 feat(ui): add global primary color settings
  packages/ui/src/components/AppContent/index.module.scss
  packages/ui/src/components/AppContent/index.tsx
  packages/ui/src/scss/_desktop.scss
  packages/ui/src/scss/_mobile.scss
Labels: feature, size/s

#876 fix(ui): fix undefined dark-primary-color bug
  packages/ui/src/components/AppContent/index.tsx
Labels: bugfix, size/xs

#877 style(ui): some desktop ui component style update
  packages/ui/src/components/AppContent/index.module.scss
  packages/ui/src/components/ConfirmModal/Acmodal.module.scss
  packages/ui/src/components/Dropdown/index.module.scss
  packages/ui/src/components/LoadingLayer/index.module.scss
  packages/ui/src/components/Toast/index.module.scss
  packages/ui/src/scss/_desktop.scss
  packages/ui/src/scss/_mobile.scss
Labels: size/s

#882 refactor(console): improve dark theme styles
  packages/console/src/components/CopyToClipboard/index.module.scss
  packages/console/src/components/Dropdown/DropdownItem.module.scss
  packages/console/src/components/Dropdown/index.module.scss
  packages/console/src/components/Dropdown/index.tsx
  packages/console/src/components/Index/index.module.scss
  packages/console/src/components/ModalLayout/index.module.scss
  packages/console/src/components/RadioGroup/index.module.scss
  packages/console/src/components/Select/index.module.scss
  packages/console/src/components/TextButton/index.module.scss
  packages/console/src/components/TextInput/index.module.scss
  packages/console/src/components/Tooltip/index.module.scss
  packages/console/src/pages/Applications/components/CreateForm/index.module.scss
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/GetStarted/components/GetStartedProgress/index.module.scss
  packages/console/src/scss/_colors.scss
  packages/console/src/scss/modal.module.scss
Labels: enhancement, size/m

#809 feat(core,schemas): log token exchange success
  packages/core/src/oidc/adapter.ts
  packages/core/src/oidc/init.ts
  packages/core/src/utils/oidc-provider-event-listener.test.ts
  packages/core/src/utils/oidc-provider-event-listener.ts
  packages/schemas/src/types/log.ts
  packages/schemas/src/types/oidc-config.ts
Labels: feature, size/m

#875 refactor(core): move GET /sign-in-settings out of sessionRouter
  packages/core/src/routes/init.ts
  packages/core/src/routes/session.test.ts
  packages/core/src/routes/session.ts
  packages/core/src/routes/sign-in-settings.test.ts
  packages/core/src/routes/sign-in-settings.ts
Labels: enhancement, size/m

#886 feat(core): disable introspection feature
  packages/core/src/oidc/init.ts
Labels: feature, size/xs

#890 refactor(core): remove SignInSocial log from POST /session/sign-in/social
  packages/core/src/routes/session.ts
Labels: enhancement, size/xs

#889 fix(console): back to social connectors
  packages/console/src/pages/ConnectorDetails/index.tsx
Labels: bugfix, size/xs

#885 style(console): fix the shadow-2 style
  packages/console/src/scss/_colors.scss
Labels: size/xs

#878 refactor(console): improve dark theme styles for toast
  packages/console/src/assets/images/toast-error.svg
  packages/console/src/assets/images/toast-success.svg
  packages/console/src/components/Toast/index.module.scss
  packages/console/src/components/Toast/index.tsx
  packages/console/src/scss/_colors.scss
Labels: enhancement, size/s

#887 feat(core,console): connector platform tabs
  packages/console/src/icons/Native.tsx
  packages/console/src/icons/Universal.tsx
  packages/console/src/icons/Web.tsx
  packages/console/src/pages/ConnectorDetails/components/ConnectorTabs/index.module.scss
  packages/console/src/pages/ConnectorDetails/components/ConnectorTabs/index.tsx
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/core/src/routes/connector.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature, size/m

#862 fix(console): socialConnectors in preview data
  packages/console/src/pages/SignInExperience/components/Preview.tsx
  packages/ui/src/hooks/use-preview.ts
Labels: bugfix, size/s

#880 feat(ui): add darkmode logo
  packages/ui/src/hooks/use-page-context.ts
  packages/ui/src/hooks/use-theme.ts
  packages/ui/src/pages/SignIn/index.tsx
  packages/ui/src/types/index.ts
Labels: feature, size/s

#888 refactor(ui): rename native supported connctors param name
  packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.test.tsx
  packages/ui/src/hooks/utils.test.ts
  packages/ui/src/hooks/utils.ts
  packages/ui/src/include.d/global.d.ts
Labels: enhancement, size/xs

#879 style(ui): web ui refinement
  packages/ui/src/components/AppContent/index.module.scss
  packages/ui/src/components/Button/IconButton.module.scss
  packages/ui/src/components/Button/IconButton.tsx
  packages/ui/src/components/ConfirmModal/AcModal.tsx
  packages/ui/src/components/ConfirmModal/Acmodal.module.scss
  packages/ui/src/components/Drawer/index.module.scss
  packages/ui/src/components/Drawer/index.tsx
  packages/ui/src/containers/SocialSignIn/PrimarySocialSignIn.module.scss
  packages/ui/src/containers/SocialSignIn/PrimarySocialSignIn.tsx
  packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.module.scss
  packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.tsx
  packages/ui/src/pages/SignIn/index.module.scss
  packages/ui/src/scss/_desktop.scss
  packages/ui/src/scss/_mobile.scss
Labels: size/m

#892 feat(console): connector logo and platform icon
  packages/connector-alipay/src/constant.ts
  packages/connector-facebook/src/constant.ts
  packages/connector-github/src/constant.ts
  packages/connector-google/src/constant.ts
  packages/connector-wechat-native/src/constant.ts
  packages/connector-wechat/src/constant.ts
  packages/console/src/hooks/use-connector-groups.ts
  packages/console/src/pages/SignInExperience/components/ConnectorsTransfer.module.scss
  packages/console/src/pages/SignInExperience/components/ConnectorsTransfer.tsx
  packages/console/src/types/connector.ts
Labels: feature, size/s

#894 feat(core): grantErrorListener for logging token exchange error
  packages/core/src/oidc/init.ts
  packages/core/src/utils/oidc-provider-event-listener.test.ts
  packages/core/src/utils/oidc-provider-event-listener.ts
Labels: feature, size/m

#899 chore: update README
  README.md
Labels: chore, size/xs

#901 style(console): fix header background color in sign-in experience guide
  packages/console/src/pages/SignInExperience/components/GuideModal.module.scss
Labels: size/xs

#902 feat(core): cookie keys configuration
  packages/core/jest.setup.ts
  packages/core/src/env-set/index.ts
  packages/core/src/env-set/oidc.ts
  packages/core/src/oidc/init.ts
  packages/docs/docs/tutorial/configuration.md
Labels: feature, size/s

#881 feat(connector-twilio-sms): add twilio sms connector
  packages/connector-twilio-sms/README.md
  packages/connector-twilio-sms/docs/config-template.md
  packages/connector-twilio-sms/jest.config.ts
  packages/connector-twilio-sms/package.json
  packages/connector-twilio-sms/src/constant.ts
  packages/connector-twilio-sms/src/index.test.ts
  packages/connector-twilio-sms/src/index.ts
  packages/connector-twilio-sms/src/mock.ts
  packages/connector-twilio-sms/src/types.ts
  packages/connector-twilio-sms/tsconfig.base.json
  packages/connector-twilio-sms/tsconfig.build.json
  packages/connector-twilio-sms/tsconfig.json
  packages/connector-twilio-sms/tsconfig.test.json
  packages/core/package.json
  packages/core/src/connectors/index.test.ts
  packages/core/src/connectors/index.ts
  pnpm-lock.yaml
Labels: feature, size/l

#897 refactor(ui): refactor terms modal as a promisified function
  packages/ui/package.json
  packages/ui/src/containers/CreateAccount/index.tsx
  packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
  packages/ui/src/containers/SocialSignIn/PrimarySocialSignIn.test.tsx
  packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.test.tsx
  packages/ui/src/containers/TermsOfUse/index.tsx
  packages/ui/src/containers/TermsOfUsePromiseModal/index.tsx
  packages/ui/src/containers/UsernameSignin/index.tsx
  packages/ui/src/hooks/use-page-context.ts
  packages/ui/src/hooks/use-social.ts
  packages/ui/src/hooks/use-terms.ts
  packages/ui/src/pages/SignIn/index.test.tsx
  pnpm-lock.yaml
Labels: enhancement, size/m

#891 feat(core): add phone number and email mask
  packages/core/src/lib/social.ts
  packages/core/src/routes/session.ts
  packages/core/src/utils/format.test.ts
  packages/core/src/utils/format.ts
Labels: feature, size/s

#895 feat(connector-types/wechat-native): fix wechat native getAuthUri
  packages/connector-wechat-native/src/constant.ts
  packages/connector-wechat-native/src/index.test.ts
  packages/connector-wechat-native/src/index.ts
Labels: feature, size/s
