Repository logto-io/logto, pull requests merged in 2022-07, with the labels that each got.

#1265 style(ui): add dark mode social icon
  packages/ui/src/components/Button/SocialIconButton.module.scss
  packages/ui/src/components/Button/SocialIconButton.tsx
  packages/ui/src/components/Button/SocialLinkButton.tsx
  packages/ui/src/components/Button/index.test.tsx
  packages/ui/src/containers/SocialLanding/index.tsx
  packages/ui/src/containers/SocialSignIn/SocialSignInDropdown/index.tsx
  packages/ui/src/containers/SocialSignIn/SocialSignInIconList/index.tsx
  packages/ui/src/containers/SocialSignIn/SocialSignInList/index.tsx
  packages/ui/src/hooks/use-social.ts
  packages/ui/src/utils/social-connectors.ts
Labels: size/m

#1336 chore: update favicon for console, demo-app and main-flow
  packages/console/src/apple-touch-icon.png
  packages/console/src/favicon.ico
  packages/console/src/index.html
  packages/demo-app/src/apple-touch-icon.png
  packages/demo-app/src/favicon.ico
  packages/demo-app/src/index.html
  packages/ui/src/apple-touch-icon.png
  packages/ui/src/favicon.ico
  packages/ui/src/index.html
Labels: chore, size/xs

#1323 fix(console): remove dashboard tip time range
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: bugfix, size/s

#1327 fix(console): checkbox style
  packages/console/src/components/Checkbox/Icon.tsx
  packages/console/src/components/Checkbox/index.module.scss
  packages/console/src/icons/CheckBoxSelected.tsx
  packages/console/src/icons/CheckBoxSelectedDisabled.tsx
  packages/console/src/icons/CheckBoxSelectedDisabledDark.tsx
  packages/console/src/icons/CheckBoxUnselected.tsx
  packages/console/src/icons/CheckBoxUnselectedDark.tsx
  packages/console/src/icons/CheckBoxUnselectedDisabled.tsx
  packages/console/src/icons/CheckBoxUnselectedDisabledDark.tsx
  packages/console/src/pages/SignInExperience/components/index.module.scss
Labels: bugfix, size/l

#1334 docs(connector-alipay-native): iOS SDK guide
  packages/connector-alipay-native/README.md
  packages/connector-alipay-native/docs/add-framework.png
  packages/connector-wechat-native/README.md
Labels: size/s

#1325 style(console): move done button to right in sie guide
  packages/console/src/pages/SignInExperience/components/GuideModal.module.scss
  packages/console/src/pages/SignInExperience/components/GuideModal.tsx
Labels: size/s

#1341 refactor(demo-app): remove "continue to explore" section
  packages/demo-app/src/App.module.scss
  packages/demo-app/src/App.tsx
Labels: enhancement, size/s

#1338 fix(console): details page should not be shrinked
  packages/console/src/pages/ApplicationDetails/index.module.scss
  packages/console/src/scss/details.module.scss
Labels: bugfix, size/s

#1300 fix(console): reset password label
  packages/console/src/pages/UserDetails/components/CreateSuccess.tsx
  packages/console/src/pages/UserDetails/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: bugfix, size/s

#1343 fix(console): get-started progress style
  packages/console/src/pages/GetStarted/components/GetStartedProgress/index.module.scss
Labels: bugfix, size/s

#1340 feat(console): display topbar shadow while scrolling
  .vscode/settings.json
  packages/console/src/components/AppContent/components/Topbar/index.tsx
  packages/console/src/components/AppContent/index.module.scss
  packages/console/src/components/AppContent/index.tsx
  packages/console/src/hooks/use-scroll.ts
Labels: feature, size/s

#1346 docs(connector-wechat-web): readme (en-US)
  packages/connector-wechat-native/README.md
  packages/connector-wechat/README.md
  packages/connector-wechat/docs/app-tabs.png
  packages/connector-wechat/docs/create-web-app.png
Labels: size/s

#1337 refactor(ui): ui content phrases update
  packages/phrases-ui/src/locales/en.ts
  packages/phrases-ui/src/locales/zh-cn.ts
  packages/ui/src/pages/Passcode/index.tsx
Labels: enhancement, size/s

#1339 refactor(core): update sign-in-settings api path
  packages/core/src/routes/init.ts
  packages/core/src/routes/well-known.test.ts
  packages/core/src/routes/well-known.ts
  packages/ui/src/apis/settings.ts
Labels: enhancement, size/s

#1352 refactor(core): refactor root path
  packages/core/src/middleware/koa-root-proxy.ts
Labels: enhancement, size/xs

#1348 feat(console): hard code admin display name with username
  packages/console/src/components/AppContent/components/UserInfo/index.tsx
Labels: feature, size/xs

#1292 fix(console): set preview desktop background color
  packages/console/src/pages/SignInExperience/components/Preview.tsx
Labels: bugfix, size/xs

#1344 fix(console): change account password modal margin
  packages/console/src/pages/Settings/components/ChangePassword.module.scss
  packages/console/src/pages/Settings/components/ChangePassword.tsx
Labels: bugfix, size/s

#1345 fix(console): fix dark mode char tooltip background
  packages/console/src/pages/Dashboard/components/ChartTooltip/index.module.scss
Labels: bugfix, size/xs

#1347 fix(console): fix connector platform label i18n
  packages/console/src/pages/ConnectorDetails/components/ConnectorTabs/index.tsx
Labels: bugfix, size/xs

#1354 ci: update workflow trigger
  .github/workflows/integration-test.yml
  .github/workflows/main.yml
Labels: size/xs

#1335 docs(connector-wechat-native): sdk note
  packages/connector-wechat-native/README.md
  packages/connector-wechat-native/docs/custom-url-scheme.png
  packages/connector-wechat-native/docs/plist.png
  packages/connector-wechat-native/docs/universal-link.png
Labels: size/s

#1349 style(ui): update create account link style
  packages/ui/src/containers/AppContent/index.module.scss
  packages/ui/src/index.html
  packages/ui/src/pages/SignIn/index.module.scss
  packages/ui/src/pages/SignIn/registry.tsx
Labels: size/s

#1353 refactor(console): optimize placeholder
  packages/console/src/pages/ApplicationDetails/components/Settings.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: enhancement, size/s

#1356 ci: fix concurrency issue
  .github/workflows/integration-test.yml
  .github/workflows/main.yml
  .github/workflows/upload-annotations.yml
Labels: size/xs

#1329 docs(apple-connector): readme (en-US)
  packages/connector-apple/README.md
  packages/connector-apple/docs/domain-and-url.png
  packages/connector-apple/docs/enable-sign-in-with-apple-in-xcode.png
  packages/connector-apple/docs/enable-sign-in-with-apple.png
  packages/connector-wechat-native/README.md
Labels: size/s

#1358 ci: update publish workflow
  .github/workflows/publish.yml
  commitlint.config.js
  lerna.json
  package.json
  packages/demo-app/package.json
Labels: size/s

#1357 docs(conector-alipay-native): android SDK guide
  packages/connector-alipay-native/README.md
Labels: size/s

#1359 ci: update publish workflow
  .github/workflows/publish.yml
Labels: size/s

#1362 style(console): improve styles in guides
  packages/console/src/components/Markdown/index.module.scss
  packages/console/src/mdx-components/DetailsSummary/index.module.scss
  packages/console/src/mdx-components/Step/index.module.scss
  packages/console/src/mdx-components/Tabs/index.module.scss
Labels: size/s

#1364 refactor: get-started task corresponding keys in DB
  packages/console/src/components/AppContent/components/Sidebar/hook.tsx
  packages/console/src/hooks/use-user-preferences.ts
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/Connectors/components/Guide/index.tsx
  packages/console/src/pages/GetStarted/components/GetStartedProgress/index.tsx
  packages/console/src/pages/GetStarted/hook.ts
  packages/console/src/pages/GetStarted/index.tsx
  packages/console/src/pages/SignInExperience/components/GuideModal.tsx
  packages/console/src/pages/SignInExperience/index.tsx
  packages/core/src/__mocks__/index.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/seeds/setting.ts
Labels: enhancement, size/s

#1361 ci: update publish workflow
  .github/workflows/publish.yml
  .github/workflows/release.yml
  .github/workflows/update-pr-metadata.yml
Labels: size/s

#1366 ci: fix release tag
  .github/workflows/release.yml
  package.sh
Labels: size/xs

#1370 feat(console): add loading skeleton to sign in experience page
  packages/console/src/pages/SignInExperience/components/Skeleton/index.module.scss
  packages/console/src/pages/SignInExperience/components/Skeleton/index.tsx
  packages/console/src/pages/SignInExperience/index.tsx
Labels: feature, size/m

#1363 style(console): notification text in demo-app should not wrap on desktop
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/ui/src/containers/AppNotification/index.module.scss
Labels: size/xs

#1368 ci: fix test tag
  .github/workflows/release.yml
Labels: size/s

#1360 feat(console): add traditional web guide - express js demo
  packages/console/src/assets/docs/tutorial/integrate-sdk/express.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/express_zh-cn.mdx
  packages/console/src/pages/Applications/components/Guide/index.tsx
  packages/console/src/pages/Applications/components/GuideHeader/index.tsx
  packages/console/src/types/applications.ts
Labels: feature, size/xl

#1369 feat(core): auto sign-out
  packages/core/src/database/seed.ts
  packages/core/src/env-set/dot-env.ts
  packages/core/src/middleware/koa-spa-proxy.ts
  packages/core/src/oidc/init.ts
  packages/core/static/html/logout.html
Labels: feature, size/s

#1372 ci: add changelog to release
  .github/workflows/release.yml
  packages/schemas/package.json
Labels: size/s

#1371 chore: add scope enum
  commitlint.config.js
Labels: chore, size/xs

#1374 refactor(console): update branding area
  packages/console/src/pages/SignInExperience/components/BrandingForm.tsx
  packages/phrases/src/locales/zh-cn.ts
Labels: enhancement, size/s

#1375 ci: add prelease tag on docker images
  .github/workflows/release.yml
Labels: size/xs

#1376 chore: remove WIP
  README.md
Labels: chore, size/xs

#1373 style(ac): refactor ac welcome page style
  packages/console/.parcelrc
  packages/console/src/assets/icons/snowflake.svg
  packages/console/src/assets/icons/welcome-dark.svg
  packages/console/src/assets/icons/welcome.svg
  packages/console/src/assets/images/welcome-dark.svg
  packages/console/src/assets/images/welcome.svg
  packages/console/src/components/Button/index.module.scss
  packages/console/src/components/Button/index.tsx
  packages/console/src/pages/Welcome/index.module.scss
  packages/console/src/pages/Welcome/index.tsx
Labels: size/xl

#1367 refactor(ui): refactor ac signin exp
  packages/core/src/routes/well-known.test.ts
  packages/core/src/routes/well-known.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/schemas/src/seeds/sign-in-experience.ts
  packages/ui/src/pages/SignIn/index.module.scss
  packages/ui/src/pages/SignIn/index.tsx
Labels: enhancement, size/m

#1379 style(ui): add short screen notification style
  packages/ui/src/containers/AppNotification/index.module.scss
Labels: size/s

#1377 ci: fix prerelease tag
  .github/workflows/release.yml
Labels: size/xs

#1378 chore: update README
  README.md
Labels: chore, size/s

#1380 ci: fix prerelease tag
  .github/workflows/release.yml
Labels: size/xs

#1382 refactor(console): update content
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: enhancement, size/xs

#1385 fix(console): use png for calendar icon
  packages/console/src/assets/images/calendar.png
  packages/console/src/assets/images/calendar.svg
  packages/console/src/components/TextInput/index.module.scss
Labels: bugfix, size/xs

#1384 fix(console): disable secondary should remove sign in methods
  packages/console/src/pages/SignInExperience/utilities.ts
Labels: bugfix, size/xs

#1386 chore(phrases): refine dashboard tooltip description
  packages/phrases/src/locales/zh-cn.ts
Labels: chore, size/s

#1387 refactor(console): swap sms and email connector
  packages/console/src/pages/Connectors/index.tsx
Labels: enhancement, size/s

#1388 refactor(console): remove add user subtitle
  packages/console/src/pages/Users/components/CreateForm/index.tsx
Labels: enhancement, size/xs

#1390 chore: update i18n keys
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: chore, size/xs

#1389 docs(connector): wechat web readme zh-CN
  packages/connector-wechat/README.md
Labels: size/s

#1391 fix(console): remove userinfo endpoint on application details page
  packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx
Labels: bugfix, size/s

#1381 refactor(core): db seed question
  packages/core/src/env-set/create-pool-by-env.ts
Labels: enhancement, size/s

#1392 chore(connector): update Alipay configTemplates for better demonstration
  packages/connector-alipay-native/docs/config-template.json
  packages/connector-alipay/docs/config-template.json
Labels: chore, size/xs

#1394 fix(console): hide reset description on dark-mode primary color matched
  packages/console/src/pages/SignInExperience/components/ColorForm.tsx
Labels: bugfix, size/s

#1397 chore(connector): update connectors description
  packages/connector-alipay-native/src/constant.ts
  packages/connector-alipay/src/constant.ts
  packages/connector-aliyun-dm/src/constant.ts
  packages/connector-aliyun-sms/src/constant.ts
  packages/connector-apple/src/constant.ts
  packages/connector-facebook/src/constant.ts
  packages/connector-github/src/constant.ts
  packages/connector-google/src/constant.ts
  packages/connector-sendgrid-mail/src/constant.ts
  packages/connector-smtp/src/constant.ts
  packages/connector-twilio-sms/src/constant.ts
  packages/connector-wechat-native/src/constant.ts
  packages/connector-wechat/src/constant.ts
Labels: chore, size/s

#1395 feat(console): update task complete icon
  packages/console/src/assets/images/circle-tick.svg
  packages/console/src/assets/images/task-complete.svg
  packages/console/src/pages/GetStarted/index.module.scss
  packages/console/src/pages/GetStarted/index.tsx
Labels: feature, size/s

#1399 refactor: update demo app id
  packages/console/src/pages/GetStarted/hook.ts
  packages/schemas/src/seeds/application.ts
Labels: enhancement, size/xs

#1400 refactor(phrases): sign out the demo app
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: enhancement, size/xs

#1396 chore(connector): update apple connector logos
  packages/connector-apple/logo-dark.svg
  packages/connector-apple/logo.svg
Labels: chore, size/xs

#1403 fix: update en.ts
  packages/phrases/src/locales/en.ts
Labels: bugfix, size/xs

#1402 refactor(ui): refactor default logo
  packages/core/src/lib/sign-in-experience.test.ts
  packages/core/src/lib/sign-in-experience.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/schemas/src/seeds/sign-in-experience.ts
  packages/ui/src/assets/logo/logto-dark.svg
  packages/ui/src/assets/logo/logto-light.svg
  packages/ui/src/pages/Consent/index.tsx
  packages/ui/src/pages/SignIn/index.tsx
Labels: enhancement, size/m

#1405 style(ui): ui & console style update
  packages/console/src/components/Button/index.module.scss
  packages/console/src/pages/Welcome/index.module.scss
  packages/ui/src/components/Button/SocialIconButton.module.scss
  packages/ui/src/containers/SocialSignIn/SocialSignInIconList/index.tsx
  packages/ui/src/containers/UsernameSignin/index.module.scss
  packages/ui/src/scss/_desktop.scss
  packages/ui/src/scss/_mobile.scss
Labels: size/m

#1404 chore: add badges
  README.md
Labels: chore, size/xs

#1410 fix(console): save sie when secondary method is disabled
  packages/console/src/pages/SignInExperience/components/SignInMethodsForm.tsx
Labels: bugfix, size/xs

#1412 fix(core): do not titlize tags of .well-known APIs
  packages/core/src/routes/swagger.test.ts
  packages/core/src/routes/swagger.ts
Labels: bugfix, size/s

#1415 refactor(phrases): get started l10n
  packages/phrases/src/locales/zh-cn.ts
Labels: enhancement, size/xs

#1409 feat(console): unsaved changes alert
  packages/console/package.json
  packages/console/src/components/ConfirmModal/index.tsx
  packages/console/src/components/UnsavedChangesAlertModal/index.tsx
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx
  packages/console/src/pages/ApplicationDetails/components/Settings.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/SignInExperience/index.tsx
  packages/console/src/pages/SignInExperience/tabs/BrandingTab.tsx
  packages/console/src/pages/SignInExperience/tabs/OthersTab.tsx
  packages/console/src/pages/SignInExperience/tabs/SignInMethodsTab.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  pnpm-lock.yaml
Labels: feature, size/l

#1418 chore: add link for badges
  README.md
Labels: chore, size/s

#1416 refactor(core): use `ENDPOINT` to replace original env urls
  packages/core/src/app/init.ts
  packages/core/src/database/seed.ts
  packages/core/src/env-set/create-pool-by-env.ts
  packages/core/src/env-set/index.ts
  packages/core/src/env-set/oidc.ts
  packages/core/src/oidc/adapter.ts
  packages/core/src/utils/url.ts
  packages/integration-tests/src/constants.ts
  packages/schemas/src/seeds/application.ts
Labels: enhancement, size/s

#1417 fix(console): dashbaord chart grid color
  packages/console/src/pages/Dashboard/index.tsx
Labels: bugfix, size/xs

#1421 fix(console): leave page button should be a danger button
  packages/console/src/components/ConfirmModal/index.tsx
  packages/console/src/components/UnsavedChangesAlertModal/index.tsx
Labels: bugfix, size/s

#1422 docs(connector): remove redundant query configs in wechat native readme
  packages/connector-wechat-native/README.md
Labels: size/s

#1427 refactor: improve allow CORS tooltip wording
  packages/core/src/oidc/utils.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: enhancement, size/xs

#1426 fix(ui): dark mode seed
  packages/schemas/src/seeds/sign-in-experience.ts
  packages/ui/src/containers/AppNotification/index.module.scss
Labels: bugfix, size/s

#1432 refactor(console): remove redundant reset logic on sign-in experience tabs
  packages/console/src/pages/SignInExperience/tabs/BrandingTab.tsx
  packages/console/src/pages/SignInExperience/tabs/OthersTab.tsx
  packages/console/src/pages/SignInExperience/tabs/SignInMethodsTab.tsx
Labels: enhancement, size/xs

#1431 docs: update node component in docs
  packages/connector-smtp/README.md
  packages/connector-twilio-sms/README.md
  packages/connector-wechat-native/README.md
Labels: size/s

#1434 refactor(phrases): update content
  packages/console/src/pages/GetStarted/hook.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: enhancement, size/s

#1424 style(console): plain button
  packages/console/src/components/Button/index.module.scss
Labels: size/xs

#1423 fix(console): fix typo for variant
  packages/console/src/components/Status/index.tsx
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/Dashboard/components/Block.tsx
  packages/console/src/pages/Dashboard/index.tsx
Labels: bugfix, size/s

#1433 chore: update README
  README.md
Labels: chore, size/xs

#1436 chore(core): remove needless todo
  packages/core/src/middleware/koa-slonik-error-handler.ts
Labels: chore, size/xs

#1429 chore(core): add default ttl settings
  packages/core/src/oidc/init.ts
Labels: chore, size/s

#1430 refactor(core): adjust access token ttl
  packages/schemas/tables/resources.sql
Labels: enhancement, size/xs

#1411 feat(console): user settings unsaved changes alert
  packages/console/src/pages/UserDetails/components/UserLogs.tsx
  packages/console/src/pages/UserDetails/components/UserSettings.tsx
  packages/console/src/pages/UserDetails/index.tsx
Labels: feature, size/l

#1435 fix(console): dashboard chart yaxis width
  packages/console/src/pages/Dashboard/index.tsx
Labels: bugfix, size/xs

#1438 fix(console): change user added modal button to done
  packages/console/src/pages/UserDetails/components/CreateSuccess.tsx
Labels: bugfix, size/xs

#1439 style(console): sign out dropdown
  packages/console/src/components/AppContent/components/UserInfo/index.module.scss
Labels: size/xs

#1440 fix(console): use icon button in copytoclipboard
  packages/console/src/components/CopyToClipboard/index.module.scss
  packages/console/src/components/CopyToClipboard/index.tsx
Labels: bugfix, size/s

#1441 fix(ui): set ui specific i18n storage key
  packages/console/src/i18n/init.ts
  packages/ui/src/i18n/init.ts
Labels: bugfix, size/xs

#1437 style(console): connector name font
  packages/console/src/pages/Connectors/components/CreateForm/index.module.scss
Labels: size/xs

#1425 refactor(console,schemas,shared): extract dark mode color generator
  packages/console/package.json
  packages/console/src/pages/SignInExperience/components/ColorForm.tsx
  packages/schemas/src/seeds/sign-in-experience.ts
  packages/shared/src/utilities/color.ts
  pnpm-lock.yaml
Labels: enhancement, size/s

#1449 chore: gitpod logto port public
  .gitpod.yml
Labels: chore, size/xs

#1443 chore: allow deps for commit scope
  commitlint.config.js
Labels: chore, size/xs

#1452 refactor(console): update iOS tutorial
  packages/console/src/assets/docs/tutorial/integrate-sdk/ios.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/ios_zh-cn.mdx
Labels: enhancement, size/xs

#1407 feat(core): append additional yaml responses to swagger.json
  packages/core/package.json
  packages/core/src/routes/swagger.test.ts
  packages/core/src/routes/swagger.ts
  packages/core/static/yaml/additional-swagger.yaml
  pnpm-lock.yaml
Labels: feature, size/m

#1454 fix(core,ui): remove todo comments
  packages/core/src/middleware/koa-role-guard.test.ts
  packages/core/src/middleware/koa-role-guard.ts
  packages/core/src/queries/passcode.ts
  packages/core/src/routes/resource.ts
  packages/ui/src/components/Button/index.tsx
  packages/ui/src/hooks/use-phone-number.ts
Labels: bugfix, size/s

#1455 refactor(console): sync input URI values in code samples in guide
  packages/console/src/assets/docs/tutorial/integrate-sdk/android.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/android_zh-cn.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/express.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/express_zh-cn.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/ios.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/ios_zh-cn.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/react.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/react_zh-cn.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/vanilla.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/vanilla_zh-cn.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/vue.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/vue_zh-cn.mdx
  packages/console/src/pages/Applications/components/Guide/index.tsx
Labels: enhancement, size/m

#1446 fix(console): set user select to none for link button
  packages/console/src/components/LinkButton/index.module.scss
Labels: bugfix, size/xs

#1445 test(test): validate swagger.json using openapi-schema-validator
  packages/integration-tests/package.json
  packages/integration-tests/tests/swagger-check.test.ts
  pnpm-lock.yaml
Labels: testing, size/s

#1456 fix(console): language auto detection
  packages/console/src/i18n/init.ts
Labels: bugfix, size/xs

#1463 refactor(console): link to localized docs website
  packages/console/src/components/AppContent/components/Sidebar/hook.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: enhancement, size/s

#1461 fix(console): vanilla sdk integration guide
  packages/console/src/assets/docs/tutorial/integrate-sdk/vanilla.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/vanilla_zh-cn.mdx
Labels: bugfix, size/xs

#1466 fix(console): pagination color should be color-text-link
  packages/console/src/components/Pagination/index.module.scss
Labels: bugfix, size/xs

#1465 refactor(phrases): remove unused tip
  packages/phrases/src/locales/en.ts
Labels: enhancement, size/xs

#1462 docs(connector): alipay native connector
  packages/connector-alipay-native/README.md
Labels: size/m

#1453 fix(core): add session check
  packages/core/src/routes/session/session.ts
  packages/core/src/routes/session/social.ts
Labels: bugfix, size/xs

#1467 docs(connector): update alipay web connector
  packages/connector-alipay/README.md
Labels: size/s

#1460 chore(connector): add `charset` to Alipay web config
  packages/connector-alipay/README.md
  packages/connector-alipay/docs/config-template.json
  packages/connector-alipay/src/constant.ts
  packages/connector-alipay/src/index.test.ts
  packages/connector-alipay/src/index.ts
  packages/connector-alipay/src/mock.ts
  packages/connector-alipay/src/types.ts
  packages/connector-alipay/src/utils.ts
Labels: chore, size/s

#1459 fix(console): admin console language detection
  packages/console/src/hooks/use-user-preferences.ts
  packages/console/src/i18n/init.ts
Labels: bugfix, size/xs

#1471 fix(console): connector guide should not have sub title
  packages/console/src/pages/Connectors/components/Guide/index.tsx
Labels: bugfix, size/xs

#1464 docs(connector): apple readme (zh-CN)
  packages/connector-apple/README.md
  packages/connector-wechat-native/README.md
  packages/connector-wechat/README.md
Labels: size/m

#1472 fix(console): connector placeholder icon should not have background color
  packages/console/src/assets/images/connector-email.svg
  packages/console/src/assets/images/connector-sms.svg
  packages/console/src/consts/connectors.ts
  packages/console/src/pages/Connectors/components/ConnectorName/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorPlaceholderIcon/index.tsx
Labels: bugfix, size/s

#1473 fix(console): hide the add connectors hint when no connectors found on sign-in-experience page
  packages/console/src/pages/SignInExperience/components/ConnectorsTransfer.tsx
Labels: bugfix, size/xs

#1474 feat: expose zod error
  packages/connector-apple/src/index.ts
  packages/connector-types/src/index.ts
  packages/console/src/components/Toast/index.module.scss
  packages/console/src/hooks/use-api.ts
  packages/core/src/errors/RequestError/index.ts
  packages/core/src/middleware/koa-connector-error-handler.ts
  packages/core/src/middleware/koa-guard.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/schemas/src/api/error.ts
Labels: feature, size/s

#1476 feat(console): add placeholder for connector sender test
  packages/console/src/pages/ConnectorDetails/components/SenderTester/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature, size/xs

#1469 style(ui): adjust headline style
  packages/ui/src/components/BrandingHeader/index.module.scss
Labels: size/s

#1468 style(ui): increase desktop input padding
  packages/ui/src/components/Input/index.module.scss
Labels: size/xs

#1480 fix(console): hide demo-app from topbar get-started progress if it is deleted
  packages/console/src/pages/GetStarted/components/GetStartedProgress/index.tsx
  packages/console/src/pages/GetStarted/hook.ts
  packages/console/src/pages/GetStarted/index.tsx
Labels: bugfix, size/m

#1477 refactor(core): remove InvalidInputError
  packages/core/src/middleware/koa-slonik-error-handler.ts
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: enhancement, size/s

#1482 fix(console): docs link in get-started should be localized
  packages/console/src/pages/GetStarted/hook.ts
Labels: bugfix, size/s

#1486 fix(console): provide fallback value for language field in settings
  packages/console/src/pages/Settings/index.tsx
Labels: bugfix, size/xs

#1487 fix(console): add unsaved changes warning in settings page
  packages/console/src/pages/Settings/index.tsx
Labels: bugfix, size/xs

#1483 refactor(ui): refactor country code
  packages/ui/package.json
  packages/ui/src/components/Input/PhoneInput.test.tsx
  packages/ui/src/components/Input/PhoneInput.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.test.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
  packages/ui/src/hooks/use-phone-number.ts
  packages/ui/src/pages/Register/index.test.tsx
  packages/ui/src/pages/SecondarySignIn/index.test.tsx
  packages/ui/src/pages/SignIn/index.test.tsx
  packages/ui/src/utils/country-code.test.ts
  packages/ui/src/utils/country-code.ts
  pnpm-lock.yaml
Labels: enhancement, size/m

#1490 refactor(console): stick sie tutorial topbar
  packages/console/src/pages/SignInExperience/components/GuideModal.module.scss
  packages/console/src/pages/SignInExperience/components/GuideModal.tsx
Labels: enhancement, size/s

#1484 refactor(connector): use raw error for config guard
  packages/connector-alipay-native/src/index.ts
  packages/connector-alipay/src/index.ts
  packages/connector-aliyun-dm/src/index.ts
  packages/connector-aliyun-sms/src/index.ts
  packages/connector-facebook/src/index.ts
  packages/connector-github/src/index.ts
  packages/connector-google/src/index.ts
  packages/connector-sendgrid-mail/src/index.ts
  packages/connector-smtp/src/index.ts
  packages/connector-twilio-sms/src/index.ts
  packages/connector-wechat-native/src/index.ts
  packages/connector-wechat/src/index.ts
Labels: enhancement, size/s

#1491 fix(console): improve error handling in connector details and sender tester
  packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx
  packages/console/src/pages/ConnectorDetails/components/SenderTester/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: bugfix, size/s

#1481 docs(connector): add Aliyun DM README zh-CN
  packages/connector-aliyun-dm/README.md
  packages/connector-aliyun-dm/docs/config-template.json
  packages/connector-wechat/README.md
Labels: size/m

#1475 fix(console): mutate after connector delete
  packages/console/src/pages/ConnectorDetails/index.tsx
Labels: bugfix, size/xs

#1458 feat(connector): connector error handler, throw errmsg on general errors
  packages/connector-alipay-native/src/constant.ts
  packages/connector-alipay-native/src/index.test.ts
  packages/connector-alipay-native/src/index.ts
  packages/connector-alipay-native/src/types.ts
  packages/connector-alipay/src/constant.ts
  packages/connector-alipay/src/index.test.ts
  packages/connector-alipay/src/index.ts
  packages/connector-alipay/src/types.ts
  packages/connector-aliyun-dm/src/index.ts
  packages/connector-aliyun-dm/src/types.ts
  packages/connector-aliyun-sms/src/index.ts
  packages/connector-facebook/src/index.test.ts
  packages/connector-facebook/src/index.ts
  packages/connector-github/src/index.ts
  packages/connector-google/src/index.ts
  packages/connector-twilio-sms/src/types.ts
  packages/connector-wechat-native/src/constant.ts
  packages/connector-wechat-native/src/index.test.ts
  packages/connector-wechat-native/src/index.ts
  packages/connector-wechat/src/constant.ts
  packages/connector-wechat/src/index.test.ts
  packages/connector-wechat/src/index.ts
  packages/core/src/middleware/koa-connector-error-handler.test.ts
  packages/core/src/middleware/koa-connector-error-handler.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature, size/l

#1489 fix(ui): add form submit event
  packages/ui/src/containers/CreateAccount/index.tsx
  packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
  packages/ui/src/containers/UsernameSignin/index.tsx
Labels: bugfix, size/m

#1493 style(console): adjust welcome page style
  packages/console/src/assets/icons/snowflake.svg
  packages/console/src/assets/icons/welcome-dark.svg
  packages/console/src/assets/icons/welcome.svg
  packages/console/src/pages/Welcome/index.module.scss
  packages/console/src/pages/Welcome/index.tsx
Labels: size/xl

#1495 chore: remove TODOs with linear issues
  packages/console/src/pages/Connectors/components/Guide/index.tsx
  packages/core/src/lib/passcode.ts
  packages/core/src/routes/admin-user.ts
  packages/ui/src/utils/sign-in-experience.ts
Labels: chore, size/xs

#1497 refactor(console): update sie preview tab
  packages/console/src/pages/SignInExperience/components/Preview.tsx
  packages/phrases/src/locales/zh-cn.ts
Labels: enhancement, size/s

#1498 fix(demo-app): username should not overflow info card
  packages/demo-app/src/App.module.scss
Labels: bugfix, size/xs

#1499 fix(console): specify toast type
  packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx
Labels: bugfix, size/xs

#1500 docs(connector): add Aliyun SMS README zh-CN
  packages/connector-aliyun-dm/README.md
  packages/connector-aliyun-sms/README.md
Labels: size/m

#1503 chore: update README
  README.md
Labels: chore, size/xs

#1478 feat(core): read connector packages env
  packages/core/src/connectors/consts.ts
Labels: feature, size/s

#1506 docs(connector): fix wrong indents in connector-twilio-sms
  packages/connector-twilio-sms/README.md
Labels: size/xs

#1505 chore: create contributing guideline
  .github/CONTRIBUTING.md
Labels: chore, size/m

#1513 refactor(core): simplify increasePasscodeTryCount and consumePasscode
  packages/core/src/queries/passcode.ts
Labels: enhancement, size/xs

#1515 docs(connector): fix wrong indents in connector-sendgrid-mail
  packages/connector-sendgrid-mail/README.md
Labels: size/xs

#1518 docs(connector): fix twilio readme according to bug bash
  packages/connector-twilio-sms/README.md
Labels: size/s
