Repository logto-io/logto, pull requests merged in 2022-06, with the labels that each got.

#1010 refactor(core): serve static middleware
  packages/core/package.json
  packages/core/src/middleware/koa-serve-static.ts
  packages/core/src/middleware/koa-spa-proxy.test.ts
  packages/core/src/middleware/koa-spa-proxy.ts
  pnpm-lock.yaml
Labels: enhancement, size/s

#1006 feat(console): init dashboard
  packages/console/src/App.tsx
  packages/console/src/components/AppError/index.tsx
  packages/console/src/components/Select/index.tsx
  packages/console/src/icons/Arrow.tsx
  packages/console/src/mdx-components/Step/index.tsx
  packages/console/src/pages/Dashboard/index.module.scss
  packages/console/src/pages/Dashboard/index.tsx
  packages/console/src/pages/Dashboard/types.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature, size/m

#1013 feat(core): set claims for `profile` scope
  packages/core/src/oidc/init.ts
Labels: feature, size/s

#1002 refactor(connector-alipay*): refactor Alipay UTs and pass config into getAccessToken
  packages/connector-alipay-native/src/constant.ts
  packages/connector-alipay-native/src/index.test.ts
  packages/connector-alipay-native/src/index.ts
  packages/connector-alipay/src/constant.ts
  packages/connector-alipay/src/index.test.ts
  packages/connector-alipay/src/index.ts
Labels: enhancement, size/m

#1016 refactor(core): align `role_names` claim with DB
  packages/core/src/oidc/init.ts
Labels: enhancement, size/xs

#1009 fix(ui): add i18n formater for zh-CN list
  packages/phrases/src/locales/zh-cn.ts
  packages/ui/src/i18n/init.ts
Labels: bugfix, size/s

#1017 refactor(core): use snake_case for extra claims
  packages/core/src/oidc/init.ts
Labels: enhancement, size/xs

#1014 refactor(console): add AppBoundary in admin console
  packages/console/src/App.tsx
  packages/console/src/components/AppBoundary/index.module.scss
  packages/console/src/components/AppBoundary/index.tsx
  packages/console/src/components/AppContent/index.module.scss
  packages/console/src/components/AppContent/index.tsx
Labels: enhancement, size/m

#1022 fix(console): bump react sdk to 0.1.13 to resolve sign in issue
  packages/console/package.json
  packages/demo-app/package.json
  pnpm-lock.yaml
Labels: bugfix, size/xs

#1023 fix(ac): fix ac text input
  packages/console/src/components/TextInput/index.module.scss
  packages/console/src/components/TextInput/index.tsx
Labels: bugfix, size/s

#1004 feat(console): audit log filters
  packages/console/src/components/IconButton/index.module.scss
  packages/console/src/components/Select/index.module.scss
  packages/console/src/components/Select/index.tsx
  packages/console/src/icons/Fail.tsx
  packages/console/src/pages/AuditLogs/components/ApplicationSelector/index.tsx
  packages/console/src/pages/AuditLogs/components/EventSelector/index.tsx
  packages/console/src/pages/AuditLogs/index.module.scss
  packages/console/src/pages/AuditLogs/index.tsx
  packages/console/src/pages/UserDetails/components/RoleSelect.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature, size/m

#1024 chore(connectors): remove unused jest-matcher-specific-error in connector
  packages/connector-aliyun-dm/jest.config.ts
  packages/connector-aliyun-dm/package.json
  packages/connector-aliyun-dm/tsconfig.json
  packages/connector-aliyun-sms/jest.config.ts
  packages/connector-aliyun-sms/package.json
  packages/connector-aliyun-sms/tsconfig.json
  packages/connector-apple/jest.config.ts
  packages/connector-apple/package.json
  packages/connector-apple/tsconfig.json
  packages/connector-sendgrid-mail/jest.config.ts
  packages/connector-sendgrid-mail/package.json
  packages/connector-sendgrid-mail/tsconfig.json
  packages/connector-twilio-sms/jest.config.ts
  packages/connector-twilio-sms/package.json
  packages/connector-twilio-sms/tsconfig.json
  packages/connector-types/package.json
  pnpm-lock.yaml
Labels: chore, size/s

#1026 fix(core): update roleNames to role_names to resolve 401 errors
  packages/core/src/middleware/koa-auth.test.ts
  packages/core/src/middleware/koa-auth.ts
Labels: bugfix, size/s

#1027 fix(console): display dark mode color setting only when dark mode is enabled
  packages/console/src/pages/SignInExperience/components/BrandingForm.tsx
Labels: bugfix, size/s

#1012 feat(console): connector in use status
  packages/console/src/hooks/use-connector-in-use.ts
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorName/index.module.scss
  packages/console/src/pages/Connectors/components/ConnectorName/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorRow/index.module.scss
  packages/console/src/pages/Connectors/components/ConnectorRow/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature, size/m

#1025 fix(console): wrap connector id with copytoclipboard
  packages/console/src/components/CopyToClipboard/index.module.scss
  packages/console/src/pages/ApiResourceDetails/index.module.scss
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/console/src/pages/ApplicationDetails/index.module.scss
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/ConnectorDetails/index.module.scss
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/UserDetails/index.module.scss
  packages/console/src/pages/UserDetails/index.tsx
Labels: bugfix, size/s

#1030 fix(console): remove redundant `required` label
  packages/console/src/pages/Settings/index.tsx
  packages/console/src/pages/SignInExperience/components/BrandingForm.tsx
  packages/console/src/pages/SignInExperience/components/LanguagesForm.tsx
  packages/console/src/pages/SignInExperience/components/SignInMethodsForm.tsx
  packages/console/src/pages/SignInExperience/components/TermsForm.tsx
Labels: bugfix, size/s

#1032 fix(console): add mobile platform preview description
  packages/console/src/pages/SignInExperience/components/Preview.module.scss
  packages/console/src/pages/SignInExperience/components/Preview.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: bugfix, size/s

#1021 feat(demo-app): implementation (3/3)
  packages/console/src/App.tsx
  packages/console/src/components/ApplicationName/index.tsx
  packages/console/src/hooks/use-api.ts
  packages/console/src/pages/AuditLogs/components/ApplicationSelector/index.tsx
  packages/console/src/pages/GetStarted/hook.ts
  packages/core/package.json
  packages/core/src/app/init.ts
  packages/core/src/database/seed.ts
  packages/core/src/env-set/create-pool-by-env.ts
  packages/core/src/env-set/index.ts
  packages/core/src/middleware/koa-auth.ts
  packages/core/src/middleware/koa-check-demo-app.ts
  packages/core/src/oidc/adapter.ts
  packages/demo-app/src/App.tsx
  packages/schemas/src/seeds/application.ts
  packages/schemas/src/seeds/index.ts
  packages/schemas/src/seeds/resource.ts
  packages/schemas/src/types/oidc-config.ts
  pnpm-lock.yaml
Labels: feature, size/m

#1031 refactor(core): recognize developer id in header
  packages/core/src/middleware/koa-auth.test.ts
  packages/core/src/middleware/koa-auth.ts
Labels: enhancement, size/s

#1038 feat(demo-app): show notification in main flow
  packages/demo-app/src/App.tsx
  packages/schemas/src/consts/index.ts
  packages/schemas/src/index.ts
  packages/ui/src/containers/AppNotification/index.test.tsx
  packages/ui/src/utils/session-storage.ts
Labels: feature, size/s

#1035 chore(core,locale): fix error messages of signing in with non-existing username
  packages/core/src/lib/user.ts
  packages/core/src/queries/user.ts
  packages/core/src/routes/session.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: chore, size/s

#1037 fix(console): user connector table bottom line
  packages/console/src/pages/UserDetails/components/UserConnectors.module.scss
Labels: bugfix, size/xs

#1033 fix(console): add letter spacing for sign-in-experience title
  packages/console/src/components/AppContent/components/Sidebar/components/Section/index.module.scss
  packages/console/src/components/Dropdown/index.module.scss
  packages/console/src/pages/GetStarted/components/GetStartedProgress/index.module.scss
  packages/console/src/pages/SignInExperience/components/index.module.scss
  packages/console/src/scss/_underscore.scss
Labels: bugfix, size/s

#1008 feat(core): make GET /api/swagger.json contain all api routes
  packages/core/src/routes/init.ts
  packages/core/src/routes/swagger.test.ts
  packages/core/src/routes/swagger.ts
  packages/core/src/utils/zod.test.ts
  packages/core/src/utils/zod.ts
Labels: feature, size/m

#1043 refactor(console): replace user api with fetchUserInfo
  packages/console/package.json
  packages/console/src/components/AppContent/components/UserInfo/index.tsx
  packages/demo-app/package.json
  pnpm-lock.yaml
Labels: enhancement, size/s

#1029 feat(console): group connectors in add modal
  packages/console/src/components/RadioGroup/index.module.scss
  packages/console/src/consts/connectors.ts
  packages/console/src/hooks/use-connector-groups.ts
  packages/console/src/pages/Connectors/components/CreateForm/PlatformSelector.module.scss
  packages/console/src/pages/Connectors/components/CreateForm/PlatformSelector.tsx
  packages/console/src/pages/Connectors/components/CreateForm/index.tsx
  packages/console/src/types/connector.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature, size/m

#1034 feat(console): platform label in connectors table
  packages/console/src/components/ItemPreview/index.module.scss
  packages/console/src/components/ItemPreview/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorName/index.module.scss
  packages/console/src/pages/Connectors/components/ConnectorName/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorRow/index.tsx
Labels: feature, size/s

#1049 fix(console): fix platform label prefix caused by merge
  packages/console/src/pages/Connectors/components/ConnectorName/index.tsx
Labels: bugfix, size/xs

#1052 fix(console): wrap routes with AppContent
  packages/console/src/App.tsx
Labels: bugfix, size/s

#1055 style(ui): input auto fill style
  packages/ui/src/components/Input/index.module.scss
  packages/ui/src/scss/_desktop.scss
  packages/ui/src/scss/_mobile.scss
Labels: size/s

#1054 feat(demo-app): implement (part 2)
  packages/console/src/scss/normalized.scss
  packages/demo-app/package.json
  packages/demo-app/src/App.module.scss
  packages/demo-app/src/App.tsx
  packages/demo-app/src/Callback.tsx
  packages/demo-app/src/i18n/init.ts
  packages/demo-app/src/scss/normalized.scss
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/shared/scss/_fonts.scss
  pnpm-lock.yaml
Labels: feature, size/m

#1050 feat(console): input error message
  packages/console/src/components/TextInput/index.module.scss
  packages/console/src/components/TextInput/index.tsx
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/console/src/pages/ApplicationDetails/components/Settings.tsx
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/SignInExperience/components/BrandingForm.tsx
  packages/console/src/pages/SignInExperience/components/TermsForm.tsx
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/pages/Users/components/CreateForm/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature, size/m

#1020 chore(connector-wechat*): fix wechat connectors error handler, comments and UTs
  packages/connector-wechat-native/src/index.test.ts
  packages/connector-wechat-native/src/index.ts
  packages/connector-wechat-native/src/types.ts
  packages/connector-wechat/src/index.test.ts
  packages/connector-wechat/src/index.ts
  packages/connector-wechat/src/types.ts
Labels: chore, size/m

#1060 fix(console): error message in text input component
  packages/console/src/components/TextInput/index.tsx
  packages/console/src/pages/SignInExperience/components/BrandingForm.tsx
  packages/console/src/pages/SignInExperience/components/TermsForm.tsx
Labels: bugfix, size/s

#1059 feat(sms/email-connectors): expose third-party API request error message
  packages/connector-aliyun-dm/src/index.ts
  packages/connector-aliyun-dm/src/types.ts
  packages/connector-aliyun-sms/src/index.test.ts
  packages/connector-aliyun-sms/src/index.ts
  packages/connector-aliyun-sms/src/single-send-text.ts
  packages/connector-aliyun-sms/src/types.ts
  packages/connector-aliyun-sms/src/utils.ts
  packages/connector-sendgrid-mail/src/index.ts
  packages/connector-sendgrid-mail/src/types.ts
  packages/connector-twilio-sms/src/index.ts
  packages/connector-twilio-sms/src/types.ts
Labels: feature, size/m

#1047 feat(core): convert route guards to swagger.json
  packages/core/src/routes/swagger.test.ts
  packages/core/src/routes/swagger.ts
  packages/core/src/utils/zod.test.ts
  packages/core/src/utils/zod.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature, size/l

#1048 docs: api reference
  packages/docs/.gitignore
  packages/docs/docusaurus.config.js
  packages/docs/package.json
  pnpm-lock.yaml
Labels: size/s

#1045 feat: use user level custom data to save preferences
  packages/console/package.json
  packages/console/src/components/AppBoundary/index.tsx
  packages/console/src/components/AppContent/components/Sidebar/hook.tsx
  packages/console/src/components/AppContent/components/Sidebar/index.tsx
  packages/console/src/components/AppContent/index.tsx
  packages/console/src/consts/index.ts
  packages/console/src/hooks/use-settings.ts
  packages/console/src/hooks/use-user-preferences.ts
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/Connectors/components/GuideModal/index.tsx
  packages/console/src/pages/GetStarted/components/GetStartedProgress/index.tsx
  packages/console/src/pages/GetStarted/hook.ts
  packages/console/src/pages/GetStarted/index.tsx
  packages/console/src/pages/Settings/index.tsx
  packages/console/src/pages/SignInExperience/components/GuideModal.tsx
  packages/console/src/pages/SignInExperience/index.tsx
  packages/core/src/__mocks__/index.ts
  packages/core/src/middleware/koa-auth.test.ts
  packages/core/src/middleware/koa-auth.ts
  packages/core/src/oidc/init.ts
  packages/core/src/routes/admin-user.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/me.ts
  packages/schemas/src/foundations/jsonb-types.ts
  pnpm-lock.yaml
Labels: feature, size/l

#1066 refactor(core): remove confusing `assertThat` signature
  packages/core/src/lib/sign-in-experience.ts
  packages/core/src/utils/assert-that.ts
  packages/core/src/utils/password.ts
Labels: enhancement, size/s

#1058 refactor(console): hide check demo button if demo app is deleted
  packages/console/src/hooks/use-api.ts
  packages/console/src/hooks/use-swr-fetcher.ts
  packages/console/src/pages/GetStarted/components/Skeleton/index.module.scss
  packages/console/src/pages/GetStarted/components/Skeleton/index.tsx
  packages/console/src/pages/GetStarted/hook.ts
  packages/console/src/pages/GetStarted/index.tsx
Labels: enhancement, size/m

#1053 fix(ui): fix some of the bug bash issues
  packages/ui/src/components/AppContent/index.module.scss
  packages/ui/src/components/Button/index.module.scss
  packages/ui/src/components/Input/PhoneInput.tsx
  packages/ui/src/components/LoadingLayer/index.module.scss
  packages/ui/src/components/Passcode/index.tsx
  packages/ui/src/components/Toast/index.module.scss
  packages/ui/src/containers/CreateAccount/index.tsx
  packages/ui/src/containers/PasscodeValidation/index.tsx
  packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
  packages/ui/src/containers/UsernameSignin/index.tsx
  packages/ui/src/scss/_desktop.scss
  packages/ui/src/scss/_mobile.scss
Labels: bugfix, size/s

#1061 fix(console): stop swr retry on error 401 and 403
  packages/console/src/App.tsx
  packages/console/src/hooks/use-swr-options.ts
Labels: bugfix, size/s

#1062 fix(console): select the old primary sign-in method when the primary method change
  packages/console/src/pages/SignInExperience/components/SignInMethodsForm.tsx
Labels: bugfix, size/s

#1065 feat(core): log error body
  packages/core/src/middleware/koa-log.test.ts
  packages/core/src/middleware/koa-log.ts
  packages/schemas/src/types/log.ts
Labels: feature, size/m

#1051 refactor(console): refactor `uriValidator` verification logic
  packages/console/src/mdx-components/MultiTextInputField/index.tsx
  packages/console/src/pages/ApplicationDetails/components/Settings.tsx
  packages/console/src/pages/SignInExperience/components/BrandingForm.tsx
  packages/console/src/pages/SignInExperience/components/TermsForm.tsx
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/utilities/validator.ts
Labels: enhancement, size/s

#1071 refactor(console): support generic type in select component
  packages/console/src/components/Select/index.tsx
  packages/console/src/pages/SignInExperience/components/Preview.tsx
  packages/console/src/pages/SignInExperience/components/SignInMethodsForm.tsx
Labels: enhancement, size/s

#1072 refactor(console): table error display
  packages/console/src/components/Table/TableEmpty.module.scss
  packages/console/src/components/Table/TableError.module.scss
  packages/console/src/components/Table/TableError.tsx
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/AuditLogs/index.tsx
  packages/console/src/pages/Connectors/index.tsx
  packages/console/src/pages/Users/index.tsx
  packages/console/src/scss/table.module.scss
Labels: enhancement, size/s

#1073 refactor(console): lazy loading admin console routes
  packages/console/src/App.tsx
Labels: enhancement, size/m

#1074 refactor(core): remove unnecessary console.log
  packages/core/src/middleware/koa-auth.test.ts
Labels: enhancement, size/xs

#1070 fix(console): only check demo app existence on get-started page
  packages/console/src/pages/GetStarted/components/GetStartedProgress/index.tsx
  packages/console/src/pages/GetStarted/hook.ts
  packages/console/src/pages/GetStarted/index.tsx
Labels: bugfix, size/s

#1064 feat(console): log details page
  packages/console/src/App.tsx
  packages/console/src/components/ApplicationName/index.module.scss
  packages/console/src/components/ApplicationName/index.tsx
  packages/console/src/components/UserName/index.module.scss
  packages/console/src/components/UserName/index.tsx
  packages/console/src/consts/logs.ts
  packages/console/src/pages/AuditLogDetails/components/EventIcon/Failed.tsx
  packages/console/src/pages/AuditLogDetails/components/EventIcon/Success.tsx
  packages/console/src/pages/AuditLogDetails/components/EventIcon/index.module.scss
  packages/console/src/pages/AuditLogDetails/components/EventIcon/index.tsx
  packages/console/src/pages/AuditLogDetails/index.module.scss
  packages/console/src/pages/AuditLogDetails/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/schemas/src/types/log.ts
Labels: feature, size/l

#1067 refactor(ui): refactor ui loading
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/ui/src/App.tsx
  packages/ui/src/assets/icons/loading-icon-light.svg
  packages/ui/src/assets/icons/loading-icon.svg
  packages/ui/src/components/AppContent/index.tsx
  packages/ui/src/components/LoadingLayer/LoadingIcon.tsx
  packages/ui/src/components/LoadingLayer/LoadingIconLight.tsx
  packages/ui/src/components/LoadingLayer/index.module.scss
  packages/ui/src/components/LoadingLayer/index.tsx
  packages/ui/src/containers/LoadingLayerProvider/index.tsx
  packages/ui/src/containers/SocialLanding/index.module.scss
  packages/ui/src/containers/SocialLanding/index.tsx
  packages/ui/src/hooks/use-social-callback-handler.ts
  packages/ui/src/hooks/use-social-landing-handler.ts
  packages/ui/src/pages/Callback/index.module.scss
  packages/ui/src/pages/Callback/index.tsx
  packages/ui/src/pages/Consent/index.module.scss
  packages/ui/src/pages/Consent/index.tsx
  packages/ui/src/pages/SocialLanding/index.tsx
Labels: enhancement, size/l

#1069 refactor(ui): ui refactor
  packages/ui/src/App.tsx
  packages/ui/src/containers/AppContent/index.module.scss
  packages/ui/src/containers/AppContent/index.tsx
  packages/ui/src/hooks/use-preview.ts
  packages/ui/src/hooks/use-social-callback-handler.ts
  packages/ui/src/hooks/use-social.ts
  packages/ui/src/pages/SocialSignInCallback/index.test.tsx
Labels: enhancement, size/s

#1080 feat(core): add welcome route
  packages/console/src/App.tsx
  packages/core/src/app/init.ts
  packages/core/src/env-set/index.ts
  packages/core/src/middleware/koa-root-proxy.test.ts
  packages/core/src/middleware/koa-root-proxy.ts
  packages/core/src/middleware/koa-spa-session-guard.test.ts
  packages/core/src/middleware/koa-spa-session-guard.ts
  packages/core/src/middleware/koa-welcome-proxy.test.ts
  packages/core/src/middleware/koa-welcome-proxy.ts
  packages/core/src/queries/user.ts
Labels: feature, size/m

#1040 docs: google universal connector
  packages/connector-google/README.md
Labels: size/s

#1076 feat(console): dashboard active users and curve
  packages/console/package.json
  packages/console/src/pages/Dashboard/components/Block.module.scss
  packages/console/src/pages/Dashboard/components/Block.tsx
  packages/console/src/pages/Dashboard/index.module.scss
  packages/console/src/pages/Dashboard/index.tsx
  packages/console/src/pages/Dashboard/types.ts
  packages/console/src/utilities/number.ts
  pnpm-lock.yaml
Labels: feature, size/l

#1077 feat(console): dashboard skeleton
  packages/console/src/pages/Dashboard/components/Skeleton/index.module.scss
  packages/console/src/pages/Dashboard/components/Skeleton/index.tsx
  packages/console/src/pages/Dashboard/index.tsx
Labels: feature, size/s

#1086 refactor(core): remove unused `/users/:userId/custom-data` APIs
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
Labels: enhancement, size/m

#1084 feat(core): remove unnecessary variable check and unused route
  packages/core/src/routes/session.test.ts
  packages/core/src/routes/session.ts
Labels: feature, size/s

#1087 refactor: bump react sdk 0.1.15 and use callback function instead of url
  packages/console/package.json
  packages/console/src/pages/Callback/index.tsx
  packages/demo-app/package.json
  packages/demo-app/src/App.tsx
  packages/demo-app/src/Callback.tsx
  pnpm-lock.yaml
Labels: enhancement, size/s

#1088 chore(docs): adjust sdk reference sorting order
  packages/docs/docs/sdk/JavaScript/README.md
  packages/docs/docs/sdk/JavaScript/browser/README.md
  packages/docs/docs/sdk/JavaScript/js/README.md
  packages/docs/docs/sdk/JavaScript/react/README.md
  packages/docs/docs/sdk/JavaScript/vue/README.md
  packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/sdk/README.md
Labels: chore, size/s

#1063 feat(core): align connector error handler middleware with ConnectorErrorCodes
  packages/core/src/app/init.ts
  packages/core/src/middleware/koa-connector-error-handler.test.ts
  packages/core/src/middleware/koa-connector-error-handler.ts
  packages/core/src/middleware/koa-oidc-error-handler.test.ts
  packages/core/src/middleware/koa-slonik-error-handler.test.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature, size/m

#1082 feat(console): user logs
  packages/console/src/App.tsx
  packages/console/src/components/AuditLogTable/components/ApplicationSelector/index.tsx
  packages/console/src/components/AuditLogTable/components/EventName/index.module.scss
  packages/console/src/components/AuditLogTable/components/EventName/index.tsx
  packages/console/src/components/AuditLogTable/components/EventSelector/index.tsx
  packages/console/src/components/AuditLogTable/index.module.scss
  packages/console/src/components/AuditLogTable/index.tsx
  packages/console/src/pages/AuditLogs/index.module.scss
  packages/console/src/pages/AuditLogs/index.tsx
  packages/console/src/pages/UserDetails/index.module.scss
  packages/console/src/pages/UserDetails/index.tsx
Labels: feature, size/xl

#1089 feat(dashboard): add tooltip to dashboard items
  packages/console/src/pages/Dashboard/components/Block.module.scss
  packages/console/src/pages/Dashboard/components/Block.tsx
  packages/console/src/pages/Dashboard/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature, size/s

#1078 refactor(connectors): use zod guard instead of got generic and elaborate error info
  packages/connector-alipay-native/src/index.test.ts
  packages/connector-alipay-native/src/index.ts
  packages/connector-alipay-native/src/types.ts
  packages/connector-alipay/src/index.test.ts
  packages/connector-alipay/src/index.ts
  packages/connector-alipay/src/types.ts
  packages/connector-aliyun-dm/src/index.test.ts
  packages/connector-aliyun-dm/src/index.ts
  packages/connector-aliyun-dm/src/single-send-mail.ts
  packages/connector-aliyun-dm/src/types.ts
  packages/connector-aliyun-dm/src/utils.ts
  packages/connector-aliyun-sms/src/index.ts
  packages/connector-facebook/src/index.test.ts
  packages/connector-facebook/src/index.ts
  packages/connector-facebook/src/types.ts
  packages/connector-github/src/index.test.ts
  packages/connector-github/src/index.ts
  packages/connector-github/src/types.ts
  packages/connector-google/src/index.test.ts
  packages/connector-google/src/index.ts
  packages/connector-google/src/types.ts
  packages/connector-wechat-native/src/index.test.ts
  packages/connector-wechat-native/src/index.ts
  packages/connector-wechat-native/src/types.ts
  packages/connector-wechat/src/index.test.ts
  packages/connector-wechat/src/index.ts
  packages/connector-wechat/src/types.ts
Labels: enhancement, size/xl

#1094 fix(github): fix the way of parsing github getAccessToken response
  packages/connector-github/package.json
  packages/connector-github/src/index.test.ts
  packages/connector-github/src/index.ts
  pnpm-lock.yaml
Labels: bugfix, size/s

#1095 refactor(console): app full page loading animation
  packages/console/src/App.tsx
  packages/console/src/assets/images/high-five.svg
  packages/console/src/assets/images/loading-illustration.svg
  packages/console/src/components/AppContent/components/UserInfo/index.tsx
  packages/console/src/components/AppContent/index.tsx
  packages/console/src/components/AppLoading/index.module.scss
  packages/console/src/components/AppLoading/index.tsx
  packages/console/src/components/Button/index.tsx
  packages/console/src/components/LogtoLoading/index.tsx
  packages/console/src/components/Spinner/index.module.scss
  packages/console/src/components/Spinner/index.tsx
  packages/console/src/pages/Callback/index.tsx
Labels: enhancement, size/l

#1093 style(ui): loading icon
  packages/ui/src/assets/icons/loading-icon-light.svg
  packages/ui/src/assets/icons/loading-icon.svg
  packages/ui/src/components/ConfirmModal/IframeConfirmModal.module.scss
  packages/ui/src/components/ConfirmModal/IframeConfirmModal.tsx
  packages/ui/src/components/LoadingLayer/LoadingIconLight.tsx
  packages/ui/src/components/LoadingLayer/index.module.scss
  packages/ui/src/components/LoadingLayer/index.tsx
  packages/ui/src/containers/SocialLanding/index.tsx
  packages/ui/src/pages/Consent/index.tsx
  packages/ui/src/scss/_desktop.scss
  packages/ui/src/scss/_mobile.scss
Labels: size/m

#1098 feat(console): add 404 page in admin console
  packages/console/src/assets/images/error.svg
  packages/console/src/pages/NotFound/index.module.scss
  packages/console/src/pages/NotFound/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/ui/src/assets/icons/error.svg
  packages/ui/src/pages/ErrorPage/index.tsx
Labels: feature, size/m

#1097 feat(ui): display error message on social callback page
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
  packages/ui/src/containers/SocialLanding/index.module.scss
  packages/ui/src/containers/SocialLanding/index.tsx
  packages/ui/src/hooks/use-api.ts
  packages/ui/src/hooks/use-social-callback-handler.ts
  packages/ui/src/pages/Callback/index.tsx
Labels: feature, size/s

#1100 refactor(console): revert ac lazy loading
  packages/console/src/App.tsx
Labels: enhancement, size/m

#1096 feat(ui): add native sdk guard logic
  packages/ui/src/utils/social-connectors.test.ts
  packages/ui/src/utils/social-connectors.ts
Labels: feature, size/s

#1090 feat(console): error handling in dashboard
  packages/console/src/pages/Dashboard/index.tsx
Labels: feature, size/s

#1099 refactor(ui): adjust input field auto focus logic
  packages/console/src/pages/SignInExperience/components/Preview.tsx
  packages/ui/src/components/Input/PhoneInput.tsx
  packages/ui/src/containers/CreateAccount/index.tsx
  packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
  packages/ui/src/containers/UsernameSignin/index.tsx
  packages/ui/src/pages/Register/index.tsx
  packages/ui/src/pages/SecondarySignIn/index.tsx
Labels: enhancement, size/s

#1101 refactor(console): add dedicated route path for create app popup dialog
  packages/console/src/App.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/GetStarted/hook.ts
Labels: enhancement, size/s

#1102 fix(console): misc improvements and ui fixes
  packages/console/package.json
  packages/console/src/components/AppContent/components/Sidebar/index.module.scss
  packages/console/src/components/AppContent/components/UserInfo/index.tsx
  packages/console/src/components/AppContent/components/UserInfoSkeleton/index.module.scss
  packages/console/src/components/AppContent/components/UserInfoSkeleton/index.tsx
  packages/console/src/components/ApplicationName/index.tsx
  packages/console/src/components/CodeEditor/index.module.scss
  packages/console/src/components/CodeEditor/index.tsx
  packages/console/src/components/CopyToClipboard/index.module.scss
  packages/console/src/components/UserName/index.tsx
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/ConnectorDetails/components/SenderTester/index.module.scss
  packages/console/src/pages/ConnectorDetails/index.module.scss
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorName/index.module.scss
  packages/console/src/pages/Connectors/index.tsx
  packages/console/src/pages/SignInExperience/index.tsx
  packages/console/src/pages/UserDetails/components/UserConnectors.module.scss
  packages/console/src/pages/UserDetails/components/UserConnectors.tsx
  packages/console/src/pages/Users/index.tsx
Labels: bugfix, size/m

#1110 feat(core): any-type parameter shows empty object in swagger example
  packages/core/src/utils/zod.test.ts
  packages/core/src/utils/zod.ts
Labels: feature, size/xs

#1113 refactor(docs): remove unused files
  packages/docs/src/components/HomepageFeatures/index.tsx
  packages/docs/src/components/HomepageFeatures/styles.module.css
  packages/docs/src/components/Step/index.tsx
Labels: enhancement, size/s

#1106 fix(console): fix info icon vertical alignment
  packages/console/src/pages/Dashboard/components/Block.module.scss
Labels: bugfix, size/xs

#1109 fix(core): remove name regex
  packages/core/src/routes/admin-user.ts
  packages/shared/src/regex.ts
Labels: bugfix, size/xs

#1108 fix(console): connector row clickable
  packages/console/src/pages/Connectors/components/ConnectorRow/index.tsx
Labels: bugfix, size/s

#1117 chore(console): update Client ID to App ID
  packages/console/src/pages/Applications/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: chore, size/xs

#1114 refactor(docs): reorg files
  .vscode/settings.json
  packages/docs/docs/docs/README.md
  packages/docs/docs/docs/recipes/integrate-logto/README.md
  packages/docs/docs/docs/recipes/integrate-logto/android.mdx
  packages/docs/docs/docs/recipes/integrate-logto/components/AppNote.tsx
  packages/docs/docs/docs/recipes/integrate-logto/components/SignInNote.tsx
  packages/docs/docs/docs/recipes/integrate-logto/ios.mdx
  packages/docs/docs/docs/recipes/integrate-logto/react.mdx
  packages/docs/docs/docs/recipes/integrate-logto/vue.mdx
  packages/docs/docs/docs/references/core/README.md
  packages/docs/docs/docs/references/core/configuration.md
  packages/docs/docs/docs/tutorials/get-started/README.md
  packages/docs/docs/docs/tutorials/get-started/_category_.json
  packages/docs/docs/docs/tutorials/get-started/add-a-social-connector.md
  packages/docs/docs/docs/tutorials/get-started/check-out-demo.md
  packages/docs/docs/docs/tutorials/get-started/create-and-integrate-the-first-app.mdx
  packages/docs/docs/docs/tutorials/get-started/customize-sign-in-experience.md
  packages/docs/docs/docs/tutorials/get-started/enable-passcode-sign-in.md
  packages/docs/docs/docs/tutorials/get-started/further-readings.md
  packages/docs/docusaurus.config.js
  packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current.json
  packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/README.md
  packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/android.mdx
  packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/components/AppNote.tsx
  packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/components/SignInNote.tsx
  packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/react.mdx
  packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/vue.mdx
  packages/docs/sidebars.js
  packages/docs/src/css/custom.css
Labels: enhancement, size/m

#1119 chore: remove only-allow pnpm from all sub-packages
  packages/connector-alipay-native/package.json
  packages/connector-alipay/package.json
  packages/connector-aliyun-dm/package.json
  packages/connector-aliyun-sms/package.json
  packages/connector-apple/package.json
  packages/connector-facebook/package.json
  packages/connector-github/package.json
  packages/connector-google/package.json
  packages/connector-sendgrid-mail/package.json
  packages/connector-twilio-sms/package.json
  packages/connector-types/package.json
  packages/connector-wechat-native/package.json
  packages/connector-wechat/package.json
  packages/console/package.json
  packages/core/package.json
  packages/demo-app/package.json
  packages/phrases/package.json
  packages/schemas/package.json
  packages/shared/package.json
  packages/ui/package.json
Labels: chore, size/xl

#1118 style(docs): update some doc styles
  packages/docs/docusaurus.config.js
  packages/docs/package.json
  packages/docs/src/css/custom.css
  packages/docs/src/theme/Footer/FooterLayout.tsx
  packages/docs/src/theme/Footer/index.d.ts
  packages/docs/src/theme/Footer/index.module.scss
  packages/docs/src/theme/Footer/index.tsx
  packages/docs/static/img/footer-logo.svg
  pnpm-lock.yaml
Labels: size/m

#1104 refactor(core): separate session routes and UTs
  packages/core/src/routes/init.ts
  packages/core/src/routes/session.test.ts
  packages/core/src/routes/session.ts
  packages/core/src/routes/session/passwordless.test.ts
  packages/core/src/routes/session/passwordless.ts
  packages/core/src/routes/session/session.test.ts
  packages/core/src/routes/session/session.ts
  packages/core/src/routes/session/social.test.ts
  packages/core/src/routes/session/social.ts
Labels: enhancement, feature, size/xl

#1116 style(console): update hover and focus background colors of topbar items
  packages/console/src/components/AppContent/components/UserInfo/index.module.scss
  packages/console/src/pages/GetStarted/components/GetStartedProgress/index.module.scss
Labels: size/s

#1122 fix(console): update terms of use
  packages/console/src/pages/SignInExperience/components/TermsForm.tsx
  packages/core/src/routes/sign-in-experience.guard.test.ts
  packages/schemas/src/foundations/jsonb-types.ts
Labels: bugfix, size/s

#1120 feat(core): append page and page_size to the query parameters in swagger.json
  packages/core/src/middleware/koa-pagination.ts
  packages/core/src/routes/swagger.test.ts
  packages/core/src/routes/swagger.ts
Labels: feature, size/m

#1128 chore: update README
  README.md
Labels: chore, size/xs

#1111 test(integration): username and password flow
  packages/integration-tests/jest.config.ts
  packages/integration-tests/jest.setup.js
  packages/integration-tests/package.json
  packages/integration-tests/src/api.ts
  packages/integration-tests/src/constants.ts
  packages/integration-tests/src/logto-context.ts
  packages/integration-tests/src/utils.ts
  packages/integration-tests/tests/username-password-flow.test.ts
  packages/integration-tests/tsconfig.json
  pnpm-lock.yaml
Labels: testing, size/l

#1130 fix(console): user management search result
  packages/console/src/pages/Users/index.tsx
Labels: bugfix, size/xs

#1127 test(integration-tests): swagger check
  packages/integration-tests/tests/swagger-check.test.ts
Labels: testing, size/xs

#1125 fix(ui): input fields
  packages/ui/src/components/Input/PhoneInput.tsx
  packages/ui/src/components/Passcode/index.test.tsx
  packages/ui/src/components/Passcode/index.tsx
  packages/ui/src/containers/CreateAccount/index.tsx
  packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
  packages/ui/src/hooks/use-preview.ts
  packages/ui/src/include.d/dom.d.ts
Labels: bugfix, size/m

#1132 feat(core): add sign-in-mode
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/queries/sign-in-experience.test.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/sign-in-settings.test.ts
  packages/core/src/routes/sign-in-settings.ts
  packages/schemas/src/seeds/sign-in-experience.ts
  packages/schemas/tables/sign_in_experiences.sql
  packages/ui/src/__mocks__/logto.tsx
  packages/ui/src/pages/SignIn/index.tsx
  packages/ui/src/pages/SignIn/registry.tsx
  packages/ui/src/types/index.ts
Labels: feature, size/m

#1133 fix(console): auto generate password
  packages/console/src/pages/Users/components/CreateForm/index.tsx
  packages/console/src/scss/modal.module.scss
Labels: bugfix, size/s

#1134 feat(console): use target in user connectors
  packages/console/src/pages/UserDetails/components/UserConnectors.tsx
Labels: feature, size/s

#1131 feat(core): add smtp connector
  packages/connector-smtp/README.md
  packages/connector-smtp/docs/config-template.json
  packages/connector-smtp/jest.config.ts
  packages/connector-smtp/logo.svg
  packages/connector-smtp/package.json
  packages/connector-smtp/src/constant.ts
  packages/connector-smtp/src/index.test.ts
  packages/connector-smtp/src/index.ts
  packages/connector-smtp/src/types.ts
  packages/connector-smtp/tsconfig.base.json
  packages/connector-smtp/tsconfig.build.json
  packages/connector-smtp/tsconfig.json
  packages/connector-smtp/tsconfig.test.json
  packages/core/package.json
  packages/core/src/connectors/consts.ts
  packages/core/src/connectors/index.test.ts
  pnpm-lock.yaml
Labels: feature, size/l

#1135 fix(console): return to user-details page from user-log-details page
  packages/console/src/App.tsx
  packages/console/src/components/AuditLogTable/index.tsx
  packages/console/src/pages/AuditLogDetails/index.tsx
  packages/console/src/pages/UserDetails/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: bugfix, size/s

#1137 fix(console): should return to previous page when on sign-in-experience and app details page
  packages/console/src/App.tsx
Labels: bugfix, size/xs

#1138 fix(core): align jsonb replace mode
  packages/core/src/queries/application.ts
  packages/core/src/queries/setting.ts
  packages/core/src/queries/sign-in-experience.test.ts
  packages/core/src/queries/sign-in-experience.ts
  packages/core/src/queries/user.test.ts
  packages/core/src/queries/user.ts
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
Labels: bugfix, size/m

#1147 fix(console): connector name in user detials
  packages/console/src/pages/UserDetails/components/UserConnectors.tsx
Labels: bugfix, size/xs

#1123 refactor(ci): add concurrency
  .github/workflows/commitlint.yml
  .github/workflows/deploy-dev.yml
  .github/workflows/integration-test.yml
  .github/workflows/main.yml
  .github/workflows/update-pr-metadata.yml
  .github/workflows/upload-annotations.yml
Labels: enhancement, size/s

#1136 test(ui): add ut
  packages/ui/src/containers/SocialSignIn/SocialSignInDropdown/index.test.tsx
  packages/ui/src/containers/TermsOfUse/TermsOfUsePromiseModal/index.test.tsx
Labels: testing, size/s

#1148 refactor(console): improve tab item click area
  packages/console/src/components/TabNav/TabNavItem.module.scss
Labels: enhancement, size/xs

#1145 feat(core): add role table seed
  packages/core/src/database/seed.ts
  packages/schemas/src/seeds/index.ts
  packages/schemas/src/seeds/roles.ts
Labels: feature, size/s

#1139 feat(ac): implement admin console welcome page
  packages/console/src/App.tsx
  packages/console/src/assets/images/welcome-icon.svg
  packages/console/src/pages/Welcome/index.module.scss
  packages/console/src/pages/Welcome/index.tsx
  packages/core/src/middleware/koa-welcome-proxy.test.ts
  packages/core/src/middleware/koa-welcome-proxy.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature, size/m

#1155 fix(console): dropdown max height
  packages/console/src/components/Dropdown/index.module.scss
Labels: bugfix, size/xs

#1153 feat(console): update pagination size and color
  packages/console/src/components/Pagination/index.module.scss
  packages/console/src/components/Pagination/index.tsx
Labels: feature, size/s

#1151 feat(console): update user management table row height and avatar size
  packages/console/src/pages/Users/index.module.scss
  packages/console/src/pages/Users/index.tsx
Labels: feature, size/s

#1154 fix(console): read-only text field background color should use color-layer-2
  packages/console/src/components/TextInput/index.module.scss
Labels: bugfix, size/xs

#1140 feat(core): register with admin role
  packages/core/src/routes/session/session.test.ts
  packages/core/src/routes/session/session.ts
Labels: feature, size/s

#1156 fix(console): only show enabled connectors in table
  packages/console/src/pages/Connectors/components/ConnectorName/index.tsx
  packages/console/src/pages/Connectors/index.tsx
Labels: bugfix, size/s

#1161 fix(console): sms and email connector in use status
  packages/console/src/hooks/use-connector-in-use.ts
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorRow/index.tsx
Labels: bugfix, size/s

#1159 fix(console): item preview alignment
  packages/console/src/components/ItemPreview/index.module.scss
  packages/console/src/components/ItemPreview/index.tsx
Labels: bugfix, size/xs

#1163 refactor(console): extract confirm modal component
  packages/console/src/components/Button/index.tsx
  packages/console/src/components/ConfirmModal/index.module.scss
  packages/console/src/components/ConfirmModal/index.tsx
  packages/console/src/components/MultiTextInput/DeleteConfirm.tsx
  packages/console/src/components/MultiTextInput/index.module.scss
  packages/console/src/components/MultiTextInput/index.tsx
  packages/console/src/pages/GetStarted/index.tsx
  packages/console/src/pages/SignInExperience/components/SignInMethodsChangePreview.module.scss
  packages/console/src/pages/SignInExperience/components/SignInMethodsChangePreview.tsx
  packages/console/src/pages/SignInExperience/components/SignInMethodsPreview.tsx
  packages/console/src/pages/SignInExperience/index.tsx
Labels: enhancement, size/m

#1157 fix(core): settings api should not throw session not found error
  packages/core/src/routes/sign-in-settings.ts
Labels: bugfix, size/s

#1158 fix(console): new platform tab colors
  packages/console/src/pages/ConnectorDetails/components/ConnectorTabs/index.module.scss
  packages/shared/scss/_console-themes.scss
Labels: bugfix, size/s

#1164 fix(console): user connectors name
  packages/console/src/pages/UserDetails/components/UserConnectors.tsx
Labels: bugfix, size/xs

#1168 fix(console): dropdown padding
  packages/console/src/components/Dropdown/index.module.scss
Labels: bugfix, size/xs

#1167 fix(console): save changes button on settings page
  packages/console/src/pages/Settings/index.tsx
  packages/phrases/src/locales/en.ts
Labels: bugfix, size/xs

#1165 feat(console): user connector delete confirmation
  packages/console/src/pages/UserDetails/components/UserConnectors.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature, size/s

#1180 fix(console): remove underline in the empty table
  packages/console/src/components/Table/TableEmpty.module.scss
  packages/console/src/components/Table/TableEmpty.tsx
Labels: bugfix, size/xs

#1179 fix(console): icon colors on the action menu
  packages/console/src/pages/ConnectorDetails/index.module.scss
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/UserDetails/index.module.scss
  packages/console/src/pages/UserDetails/index.tsx
Labels: bugfix, size/s

#1178 fix(console): dashboard chart tooltip
  packages/console/src/pages/Dashboard/components/ChartTooltip/index.module.scss
  packages/console/src/pages/Dashboard/components/ChartTooltip/index.tsx
  packages/console/src/pages/Dashboard/index.tsx
Labels: bugfix, size/s

#1175 fix(console): user details card footer
  packages/console/src/pages/UserDetails/index.module.scss
Labels: bugfix, size/xs

#1174 fix(console): remove sign in methods form fields in guide
  packages/console/src/pages/SignInExperience/components/GuideModal.tsx
Labels: bugfix, size/xs

#1177 fix(console): dashboard chart style
  packages/console/src/pages/Dashboard/components/ChartTooltip/index.module.scss
  packages/console/src/pages/Dashboard/components/ChartTooltip/index.tsx
  packages/console/src/pages/Dashboard/index.tsx
  packages/shared/scss/_fonts.scss
Labels: bugfix, size/s

#1170 fix(console): add code editor field label
  packages/console/src/pages/AuditLogDetails/index.tsx
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: bugfix, size/s

#1186 fix(console): add bottom color for connector logos
  packages/console/src/pages/ConnectorDetails/index.module.scss
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorName/index.module.scss
  packages/console/src/pages/Connectors/components/ConnectorName/index.tsx
Labels: bugfix, size/s

#1162 docs(connector-facebook): readme
  packages/connector-facebook/README.md
Labels: size/s

#1171 fix(console): date picker input height
  packages/console/src/components/TextInput/index.module.scss
Labels: bugfix, size/xs

#1172 fix(console): use custom icon in date input
  packages/console/src/assets/images/calendar.svg
  packages/console/src/components/TextInput/index.module.scss
Labels: bugfix, size/s

#1176 fix(core,console): delete specific user identity by target
  packages/console/src/pages/UserDetails/components/UserConnectors.tsx
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
Labels: bugfix, size/s

#1188 fix(console): button loading spinner position
  packages/console/src/components/Button/index.module.scss
Labels: bugfix, size/xs

#1187 feat(console): show app guide in "Check Help Guide" drawer
  packages/console/src/components/Drawer/index.module.scss
  packages/console/src/components/Drawer/index.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
Labels: feature, size/s

#1183 fix(ui): add missing ui codecov job
  .github/workflows/main.yml
Labels: bugfix, size/s

#1173 fix(core,console): remove role edit for user
  packages/console/src/pages/UserDetails/components/RoleSelect.tsx
  packages/console/src/pages/UserDetails/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: bugfix, size/s

#1189 fix(worklow): add master codecov report job
  .github/workflows/master-codecov-report.yml
Labels: bugfix, size/s

#1182 feat(console,core): hide admin user
  packages/console/src/components/ApplicationName/index.tsx
  packages/console/src/components/UserName/index.tsx
  packages/console/src/pages/Users/index.tsx
  packages/core/src/queries/user.test.ts
  packages/core/src/queries/user.ts
  packages/core/src/routes/admin-user.ts
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: feature, size/m

#1191 fix(console): display default avatar when the avatar is empty
  packages/console/src/components/AppContent/components/UserInfo/index.tsx
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/pages/Users/index.tsx
Labels: bugfix, size/xs

#1193 refactor(console): rename `id` -> `target` in display connector
  packages/console/src/pages/UserDetails/components/UserConnectors.tsx
Labels: enhancement, size/s

#1192 fix(console): connector card item style
  packages/console/src/components/RadioGroup/index.module.scss
  packages/console/src/pages/Connectors/components/CreateForm/index.module.scss
Labels: bugfix, size/s

#1184 fix(console): update user data
  packages/console/src/pages/UserDetails/index.tsx
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
Labels: bugfix, size/s

#1202 chore: remove Linear issue reference from PR template
  .github/pull_request_template.md
Labels: chore, size/xs

#1196 refactor(connector,core): add config param to email/sms connector test API
  packages/connector-aliyun-dm/src/index.ts
  packages/connector-aliyun-sms/src/index.ts
  packages/connector-types/src/index.ts
  packages/console/src/pages/ConnectorDetails/components/SenderTester/index.tsx
  packages/console/src/pages/ConnectorDetails/index.module.scss
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/core/src/routes/connector.test.ts
  packages/core/src/routes/connector.ts
Labels: enhancement, size/m

#1205 ci: optimize workflows
  .github/workflows/integration-test.yml
  .github/workflows/main.yml
Labels: size/xs

#1195 refactor(console): rename `getAvatarById` -> `generateAvatarPlaceHolderById`
  packages/console/src/components/AppContent/components/UserInfo/index.tsx
  packages/console/src/consts/avatars.ts
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/pages/Users/index.tsx
Labels: enhancement, size/s

#1204 refactor(console): combine steps in connector guide
  packages/console/src/components/CodeEditor/index.module.scss
  packages/console/src/components/Markdown/index.module.scss
  packages/console/src/components/Markdown/index.tsx
  packages/console/src/mdx-components/Step/index.tsx
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/Connectors/components/CreateForm/index.tsx
  packages/console/src/pages/Connectors/components/Guide/index.module.scss
  packages/console/src/pages/Connectors/components/Guide/index.tsx
  packages/console/src/pages/Connectors/components/GuideModal/index.tsx
  packages/console/src/pages/Connectors/index.tsx
  packages/phrases/src/locales/en.ts
  packages/phrases/src/locales/zh-cn.ts
Labels: enhancement, size/l
