Repository logto-io/logto, pull requests merged in 2022-08, with the labels that each got.

#1697 test(test): add passwordless integration test
  packages/connector-mock-mail/src/index.ts
  packages/connector-mock-sms/src/index.ts
  packages/integration-tests/src/api/session.ts
  packages/integration-tests/src/helpers.ts
  packages/integration-tests/src/utils.ts
  packages/integration-tests/tests/connector.test.ts
  packages/integration-tests/tests/session.test.ts
Labels: testing, size/l

#1704 feat(console): add Next.js integration guide in admin console
  packages/console/src/assets/docs/tutorial/integrate-sdk/next.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/next_zh-cn.mdx
  packages/console/src/pages/Applications/components/Guide/index.tsx
  packages/console/src/pages/Applications/components/GuideHeader/index.tsx
  packages/console/src/types/applications.ts
  packages/phrases/src/locales/en/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/applications.ts
  packages/shared/package.json
  packages/shared/src/utilities/index.ts
  packages/shared/src/utilities/string.ts
  pnpm-lock.yaml
Labels: feature, size/l

#1713 chore: align stale time
  .github/workflows/close-stale.yml
Labels: chore, size/xs

#1710 test: add mock social connector
  .github/workflows/integration-test.yml
  package.sh
  packages/connector-mock-social/README.md
  packages/connector-mock-social/docs/config-template.json
  packages/connector-mock-social/logo.svg
  packages/connector-mock-social/package.json
  packages/connector-mock-social/src/constant.ts
  packages/connector-mock-social/src/index.ts
  packages/connector-mock-social/src/types.ts
  packages/connector-mock-social/tsconfig.base.json
  packages/connector-mock-social/tsconfig.build.json
  packages/connector-mock-social/tsconfig.json
  pnpm-lock.yaml
Labels: testing, size/m

#1701 test(test): add get access token flow test
  packages/integration-tests/src/client/index.ts
  packages/integration-tests/src/helpers.ts
  packages/integration-tests/tests/get-access-token.test.ts
Labels: testing, size/s

#1702 test(test): add sign-in then sign-out test
  packages/integration-tests/src/client/index.ts
  packages/integration-tests/tests/session.test.ts
Labels: testing, size/s

#1705 refactor(console): refactor language options and refine documentation l10n url logic
  packages/console/src/components/AppContent/components/Sidebar/hook.tsx
  packages/console/src/hooks/use-documentation-url.ts
  packages/console/src/hooks/use-language.ts
  packages/console/src/pages/GetStarted/hook.ts
  packages/console/src/pages/Settings/index.tsx
  packages/phrases-ui/src/types.ts
  packages/phrases/src/types.ts
Labels: enhancement, bugfix, size/m

#1711 chore(core): make the i18n optional for connector metadata
  packages/connector-alipay-native/tsconfig.test.json
  packages/connector-twilio-sms/tsconfig.test.json
  packages/connector-types/src/index.ts
  packages/console/src/pages/UserDetails/components/UserConnectors.tsx
Labels: chore, size/s

#1712 Revert "feat(console): checked if sign in method is primary"
  packages/console/src/pages/SignInExperience/components/SignInMethodsForm.tsx
Labels: size/xs

#1717 chore: create CODEOWNERS
  .github/CODEOWNERS
Labels: chore, size/xs

#1714 refactor(test): replace facebook connector with mock social connector
  packages/integration-tests/src/__mocks__/connectors-mock.ts
  packages/integration-tests/tests/connector.test.ts
  packages/integration-tests/tests/sign-in-experience.test.ts
Labels: enhancement, size/s

#1719 fix(shared): fix dark color generator
  packages/shared/src/utilities/color.ts
Labels: bugfix, size/xs

#1718 fix(ui): connector name should fallback to en
  packages/ui/src/components/Button/SocialLinkButton.tsx
Labels: bugfix, size/xs

#1715 feat(core,schemas): add application secret
  packages/core/src/__mocks__/index.ts
  packages/core/src/database/seed.ts
  packages/core/src/oidc/adapter.test.ts
  packages/core/src/oidc/adapter.ts
  packages/core/src/routes/application.test.ts
  packages/core/src/routes/application.ts
  packages/core/src/utils/id.ts
  packages/schemas/src/seeds/application.ts
  packages/schemas/tables/applications.sql
Labels: feature, size/s

#1722 chore(console): remove unused language texts in i18n locale files
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/ko-kr/index.ts
  packages/phrases/src/locales/ko-kr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
Labels: chore, size/s

#1720 refactor(test): refactor integration-test workflow to link mock connectors
  .github/workflows/integration-test.yml
  link-mock-connectors.sh
  package.sh
Labels: enhancement, size/s

#1721 test(test): add social integration tests
  packages/connector-mock-social/src/index.ts
  packages/integration-tests/src/api/session.ts
  packages/integration-tests/src/client/index.ts
  packages/integration-tests/tests/social-session.test.ts
Labels: testing, size/m

#1727 refactor(core): replace deprecated .nonempty() with .min(1) for ZodString
  packages/core/src/routes/session/session.ts
  packages/core/src/utils/zod.test.ts
Labels: enhancement, size/xs

#1728 test: integration test for deleting user identities
  packages/integration-tests/src/api/admin-user.ts
  packages/integration-tests/src/helpers.ts
  packages/integration-tests/tests/admin-user.test.ts
Labels: testing, size/s

#1725 chore(console): update default app running port number from 1234 to 3000
  packages/console/src/assets/docs/tutorial/integrate-sdk/express.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/express_zh-cn.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/react.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/react_zh-cn.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/vanilla.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/vanilla_zh-cn.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/vue.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/vue_zh-cn.mdx
Labels: chore, size/s

#1734 chore: bump react sdk version to 1.0.0-beta.0
  packages/console/package.json
  packages/demo-app/package.json
  pnpm-lock.yaml
Labels: chore, size/xs

#1723 feat(console): show app secret
  packages/console/src/components/CopyToClipboard/index.module.scss
  packages/console/src/components/CopyToClipboard/index.tsx
  packages/console/src/icons/EyeClosed.tsx
  packages/console/src/pages/ApplicationDetails/components/Settings.tsx
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko-kr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
Labels: feature, size/s

#1735 feat(console): add app secret to guide
  packages/console/src/assets/docs/tutorial/integrate-sdk/express.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/express_zh-cn.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/next.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/next_zh-cn.mdx
  packages/console/src/pages/Applications/components/Guide/index.tsx
Labels: feature, size/xs

#1741 refactor: simplify jest.config.ts
  packages/connector-alipay-native/jest.config.ts
  packages/connector-alipay-web/jest.config.ts
  packages/connector-aliyun-dm/jest.config.ts
  packages/connector-aliyun-sms/jest.config.ts
  packages/connector-apple/jest.config.ts
  packages/connector-azuread/jest.config.ts
  packages/connector-facebook/jest.config.ts
  packages/connector-github/jest.config.ts
  packages/connector-google/jest.config.ts
  packages/connector-sendgrid-mail/jest.config.ts
  packages/connector-smtp/jest.config.ts
  packages/connector-twilio-sms/jest.config.ts
  packages/connector-wechat-native/jest.config.ts
  packages/connector-wechat-web/jest.config.ts
  packages/core/jest.config.ts
Labels: enhancement, size/s

#1724 docs(console): update next.js integration guide
  packages/console/src/assets/docs/tutorial/integrate-sdk/next.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/next_zh-cn.mdx
Labels: size/m

#1742 refactor(core,schemas,ui): fix non-consistent type definitions
  packages/core/src/lib/social.ts
  packages/core/src/middleware/koa-pagination.ts
  packages/core/src/queries/log.ts
  packages/core/src/utils/oidc-provider-event-listener.ts
  packages/schemas/src/types/log.ts
  packages/ui/src/types/index.ts
Labels: enhancement, size/m

#1732 feat(core): support signing key rotation
  packages/core/jest.setup.ts
  packages/core/src/env-set/oidc.test.ts
  packages/core/src/env-set/oidc.ts
  packages/core/src/env-set/utils.ts
  packages/core/src/middleware/koa-auth.ts
  packages/core/src/oidc/init.ts
  packages/core/src/utils/jwks.ts
Labels: feature, size/l

#1749 refactor(core): remove redundant `isBuffer('base64url')`
  packages/core/src/utils/jwks.ts
Labels: enhancement, bugfix, size/s

#1752 chore(console,demo-app): bump react sdk to 1.0.0-beta.2
  packages/console/package.json
  packages/demo-app/package.json
  pnpm-lock.yaml
Labels: chore, size/xs

#1750 fix(ui,console,demo-app): update react render method
  packages/console/src/index.tsx
  packages/demo-app/src/index.tsx
  packages/ui/src/index.tsx
Labels: bugfix, size/s

#1756 fix(ui): extract ReactModal elementApp and fix act warning in ut
  packages/ui/src/components/ConfirmModal/AcModal.tsx
  packages/ui/src/components/ConfirmModal/IframeConfirmModal.tsx
  packages/ui/src/components/ConfirmModal/MobileModal.tsx
  packages/ui/src/components/Drawer/index.tsx
  packages/ui/src/containers/CreateAccount/index.test.tsx
  packages/ui/src/containers/Passwordless/EmailPasswordless.test.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.test.tsx
  packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn/index.test.tsx
  packages/ui/src/index.tsx
  packages/ui/src/pages/SocialSignInCallback/index.test.tsx
Labels: bugfix, size/s

#1746 refactor(test): inline link-mock-connectors.sh
  .github/workflows/integration-test.yml
  link-mock-connectors.sh
  packages/connector-mock-email/CHANGELOG.md
  packages/connector-mock-email/README.md
  packages/connector-mock-email/docs/config-template.json
  packages/connector-mock-email/logo.svg
  packages/connector-mock-email/package.json
  packages/connector-mock-email/src/constant.ts
  packages/connector-mock-email/src/index.ts
  packages/connector-mock-email/src/types.ts
  packages/connector-mock-email/tsconfig.base.json
  packages/connector-mock-email/tsconfig.build.json
  packages/connector-mock-email/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement, size/s

#1757 fix(ui): add sandbox props to iframe
  packages/ui/src/components/ConfirmModal/IframeConfirmModal.tsx
  packages/ui/src/include.d/dom.d.ts
Labels: bugfix, size/xs

#1737 feat(schemas): guard string max length
  packages/schemas/jest.config.ts
  packages/schemas/package.json
  packages/schemas/src/gen/index.ts
  packages/schemas/src/gen/schema.ts
  packages/schemas/src/gen/types.ts
  packages/schemas/src/gen/utils.test.ts
  packages/schemas/src/gen/utils.ts
  packages/schemas/tsconfig.build.json
  packages/schemas/tsconfig.json
  packages/schemas/tsconfig.test.json
  pnpm-lock.yaml
Labels: feature, size/l

#1762 feat(core)!: use comma separated values as a string array in the env file
  packages/core/jest.setup.ts
  packages/core/src/connectors/consts.ts
  packages/core/src/connectors/index.ts
  packages/core/src/env-set/index.ts
  packages/core/src/env-set/oidc.test.ts
  packages/core/src/env-set/oidc.ts
  packages/core/src/env-set/utils.ts
Labels: feature, size/m

#1764 chore(core): remove redundant try catch in `readPrivateKeys`
  packages/core/src/env-set/oidc.ts
Labels: chore, size/s

#1766 chore: update README
  README.md
Labels: chore, size/xs

#1768 chore(core): update inaccurate content in `readPrivateKeys` method
  packages/core/src/env-set/oidc.ts
Labels: chore, size/s

#1770 chore(console): cleanup unused code
  packages/console/src/components/AppContent/components/UserInfo/index.tsx
Labels: chore, size/xs

#1771 test(ui): init smoke testing
  .github/workflows/integration-test.yml
  packages/integration-tests/jest.config.ui.ts
  packages/integration-tests/package.json
  packages/integration-tests/src/constants.ts
  packages/integration-tests/tests/api/admin-user.test.ts
  packages/integration-tests/tests/api/application.test.ts
  packages/integration-tests/tests/api/connector.test.ts
  packages/integration-tests/tests/api/dashboard.test.ts
  packages/integration-tests/tests/api/get-access-token.test.ts
  packages/integration-tests/tests/api/health-check.test.ts
  packages/integration-tests/tests/api/logs.test.ts
  packages/integration-tests/tests/api/me.test.ts
  packages/integration-tests/tests/api/resource.test.ts
  packages/integration-tests/tests/api/session.test.ts
  packages/integration-tests/tests/api/sign-in-experience.test.ts
  packages/integration-tests/tests/api/social-session.test.ts
  packages/integration-tests/tests/api/swagger-check.test.ts
  packages/integration-tests/tests/api/wellknown.test.ts
  packages/integration-tests/tests/ui/smoke.test.ts
  pnpm-lock.yaml
Labels: testing, size/s

#1773 refactor(core): update app secret length to 21
  packages/core/src/utils/id.ts
Labels: enhancement, size/xs

#1767 feat(phrases): add french language
  packages/phrases-ui/src/index.ts
  packages/phrases-ui/src/locales/fr.ts
  packages/phrases-ui/src/types.ts
  packages/phrases/src/index.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/fr/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/applications.ts
  packages/phrases/src/locales/fr/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/fr/translation/admin-console/contact.ts
  packages/phrases/src/locales/fr/translation/admin-console/dashboard.ts
  packages/phrases/src/locales/fr/translation/admin-console/errors.ts
  packages/phrases/src/locales/fr/translation/admin-console/general.ts
  packages/phrases/src/locales/fr/translation/admin-console/get-started.ts
  packages/phrases/src/locales/fr/translation/admin-console/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/log-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/logs.ts
  packages/phrases/src/locales/fr/translation/admin-console/session-expired.ts
  packages/phrases/src/locales/fr/translation/admin-console/settings.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/fr/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/fr/translation/admin-console/tabs.ts
  packages/phrases/src/locales/fr/translation/admin-console/user-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/users.ts
  packages/phrases/src/locales/fr/translation/admin-console/welcome.ts
  packages/phrases/src/locales/fr/translation/demo-app.ts
  packages/phrases/src/locales/fr/translation/index.ts
  packages/phrases/src/types.ts
Labels: feature, size/xl

#1774 chore: fix and dedup workflow runs
  .github/workflows/update-pr-metadata.yml
Labels: chore, size/xs

#1761 fix(core): fix ac & ui proxy under subpath deployment
  packages/core/src/middleware/koa-root-proxy.ts
  packages/core/src/middleware/koa-spa-session-guard.ts
  packages/core/src/middleware/koa-welcome-proxy.test.ts
  packages/core/src/middleware/koa-welcome-proxy.ts
Labels: bugfix, size/s

#1782 chore: update README
  README.md
Labels: chore, size/xs

#1785 ci: fix pr assignee
  .github/workflows/update-pr-metadata.yml
Labels: size/xs

#1783 feat(core): enable userinfo endpoint
  packages/core/package.json
  packages/core/src/oidc/init.ts
  pnpm-lock.yaml
Labels: feature, size/s

#1781 refactor(core,console)!: remove `/me` apis
  packages/console/src/hooks/use-user-preferences.ts
  packages/console/src/pages/Settings/components/ChangePassword.tsx
  packages/core/src/routes/admin-user.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/me.ts
  packages/core/static/yaml/additional-swagger.yaml
  packages/integration-tests/tests/api/me.test.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko-kr/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
Labels: enhancement, size/m

#1786 chore: update README
  README.md
Labels: chore, size/s

#1787 refactor(core): import `getEnvAsStringArray` from `silverhand/essentials`
  packages/connector-alipay-native/package.json
  packages/connector-alipay-web/package.json
  packages/connector-aliyun-dm/package.json
  packages/connector-aliyun-sms/package.json
  packages/connector-apple/package.json
  packages/connector-azuread/package.json
  packages/connector-facebook/package.json
  packages/connector-github/package.json
  packages/connector-google/package.json
  packages/connector-mock-email/package.json
  packages/connector-mock-sms/package.json
  packages/connector-mock-social/package.json
  packages/connector-sendgrid-mail/package.json
  packages/connector-smtp/package.json
  packages/connector-twilio-sms/package.json
  packages/connector-types/package.json
  packages/connector-wechat-native/package.json
  packages/connector-wechat-web/package.json
  packages/console/package.json
  packages/core/package.json
  packages/core/src/env-set/index.ts
  packages/core/src/env-set/oidc.ts
  packages/core/src/env-set/utils.ts
  packages/integration-tests/package.json
  packages/phrases-ui/package.json
  packages/phrases/package.json
  packages/schemas/package.json
  packages/shared/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: enhancement, size/s

#1789 docs(connector): change redirect uri prefix to `endpoint` on google connector readme file
  packages/connector-google/README.md
Labels: size/xs

#1790 feat(core): hasura authn
  packages/core/src/middleware/koa-auth.test.ts
  packages/core/src/middleware/koa-auth.ts
  packages/core/src/routes/authn.ts
  packages/core/src/routes/init.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko-kr/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
Labels: feature, size/m

#1792 fix(console): show platform icons in connector table
  packages/console/src/pages/Connectors/components/ConnectorName/index.tsx
Labels: bugfix, size/xs

#1794 refactor(core): replace `argon2` with `hash-wasm`
  .github/workflows/integration-test.yml
  install.js
  packages/core/package.json
  packages/core/src/lib/user.ts
  packages/core/src/utils/password.ts
  pnpm-lock.yaml
Labels: enhancement, size/s

#1793 feat(core): set user default roles from env
  packages/core/src/env-set/index.ts
  packages/core/src/lib/user.ts
  packages/core/src/queries/roles.ts
  packages/core/src/queries/user.test.ts
  packages/core/src/queries/user.ts
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
  packages/core/src/routes/session/passwordless.test.ts
  packages/core/src/routes/session/passwordless.ts
  packages/core/src/routes/session/session.test.ts
  packages/core/src/routes/session/session.ts
  packages/core/src/routes/session/social.test.ts
  packages/core/src/routes/session/social.ts
Labels: feature, size/m

#1799 chore: update README
  README.md
Labels: chore, size/xs

#1796 refactor: watch all packages when dev
  package.json
  packages/connector-alipay-native/package.json
  packages/connector-alipay-web/package.json
  packages/connector-aliyun-dm/package.json
  packages/connector-aliyun-sms/package.json
  packages/connector-apple/package.json
  packages/connector-azuread/package.json
  packages/connector-facebook/package.json
  packages/connector-github/package.json
  packages/connector-google/package.json
  packages/connector-mock-email/package.json
  packages/connector-mock-sms/package.json
  packages/connector-mock-social/package.json
  packages/connector-sendgrid-mail/package.json
  packages/connector-smtp/package.json
  packages/connector-twilio-sms/package.json
  packages/connector-types/package.json
  packages/connector-wechat-native/package.json
  packages/connector-wechat-web/package.json
  packages/core/nodemon.json
  packages/core/package.json
  packages/core/src/routes/authn.ts
  packages/phrases-ui/package.json
  packages/phrases/package.json
  packages/schemas/package.json
  packages/shared/package.json
  pnpm-lock.yaml
Labels: enhancement, size/s

#1801 chore: update README
  README.md
Labels: chore, size/s

#1806 feat(console): allow to disable create account
  packages/console/src/pages/SignInExperience/components/AuthenticationForm.tsx
  packages/console/src/pages/SignInExperience/tabs/OthersTab.tsx
  packages/console/src/pages/SignInExperience/types.ts
  packages/console/src/pages/SignInExperience/utilities.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/ko-kr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
Labels: feature, size/s

#1808 refactor(core): session routes
  packages/core/src/routes/init.ts
  packages/core/src/routes/session/index.test.ts
  packages/core/src/routes/session/index.ts
  packages/core/src/routes/session/passwordless.test.ts
  packages/core/src/routes/session/passwordless.ts
  packages/core/src/routes/session/social.test.ts
  packages/core/src/routes/session/social.ts
  packages/core/src/routes/session/username-password.test.ts
  packages/core/src/routes/session/username-password.ts
Labels: enhancement, size/xl

#1809 refactor(core): flatten router parameter context types
  packages/core/src/routes/types.ts
Labels: enhancement, size/xs

#1810 feat(core): guard session with sign-in mode
  packages/core/src/routes/session/index.ts
  packages/core/src/routes/session/middleware/koa-guard-session-action.ts
  packages/core/src/routes/session/username-password.test.ts
Labels: feature, size/s

#1807 feat(console): express integration guide
  packages/console/src/assets/docs/tutorial/integrate-sdk/express.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/express_zh-cn.mdx
  packages/console/src/pages/Applications/components/GuideHeader/index.tsx
Labels: feature, size/xl

#1813 style(console): fix copytoclipboard padding
  packages/console/src/components/CopyToClipboard/index.module.scss
Labels: size/xs

#1811 refactor(core): use consts for session prefix
  packages/core/src/routes/session/index.ts
  packages/core/src/routes/session/passwordless.test.ts
  packages/core/src/routes/session/passwordless.ts
  packages/core/src/routes/session/social.test.ts
  packages/core/src/routes/session/social.ts
  packages/core/src/routes/session/username-password.test.ts
  packages/core/src/routes/session/username-password.ts
  packages/core/src/routes/session/utils.ts
Labels: enhancement, size/m

#1814 fix(console): change step title to sentence case
  packages/console/src/assets/docs/tutorial/integrate-sdk/android.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/ios.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/next.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/react.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/vanilla.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/vue.mdx
Labels: bugfix, size/s

#1818 fix(core): fix IT description and undestructure error
  packages/core/src/routes/connector.ts
  packages/integration-tests/tests/api/session.test.ts
Labels: bugfix, size/xs

#1821 chore(connector): rename db in logto connector
  packages/core/src/__mocks__/connector.ts
  packages/core/src/connectors/consts.ts
  packages/core/src/connectors/index.test.ts
  packages/core/src/connectors/index.ts
  packages/core/src/connectors/types.ts
  packages/core/src/lib/passcode.test.ts
  packages/core/src/lib/passcode.ts
  packages/core/src/routes/connector.test.ts
  packages/core/src/routes/connector.ts
  packages/core/src/routes/connector.update.test.ts
  packages/core/src/routes/session/passwordless.test.ts
  packages/core/src/routes/session/passwordless.ts
  packages/core/src/routes/session/social.test.ts
  packages/core/src/routes/session/social.ts
  packages/core/src/routes/sign-in-experience.ts
  packages/core/src/routes/well-known.test.ts
  packages/core/src/routes/well-known.ts
Labels: chore, size/m

#1822 refactor(phrases,console): move terms_of_use translations
  packages/console/src/pages/SignInExperience/components/TermsForm.tsx
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/ko-kr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
Labels: enhancement, size/s

#1824 chore(connector): fix text encoding identifier cases
  packages/connector-alipay-native/src/index.ts
  packages/connector-alipay-native/src/mock.ts
  packages/connector-alipay-native/src/utils.test.ts
  packages/connector-alipay-native/src/utils.ts
  packages/connector-alipay-web/src/constant.ts
  packages/connector-alipay-web/src/mock.ts
  packages/connector-alipay-web/src/utils.test.ts
Labels: chore, size/s

#1823 chore(connector): use literal enum for ConnectorErrorCodes
  packages/connector-core/src/types.ts
Labels: chore, size/s

#1815 style(console): fix border style copy field padding
  packages/console/src/components/CopyToClipboard/index.module.scss
Labels: size/xs

#1820 style(console): fix detail page height in small window
  packages/console/src/scss/details.module.scss
Labels: size/xs

#1827 chore(connector): remove unused shared dep
  packages/connector-alipay-native/package.json
  packages/connector-alipay-web/package.json
  packages/connector-aliyun-dm/package.json
  packages/connector-aliyun-sms/package.json
  packages/connector-apple/package.json
  packages/connector-azuread/package.json
  packages/connector-facebook/package.json
  packages/connector-google/package.json
  packages/connector-mock-email/package.json
  packages/connector-mock-sms/package.json
  packages/connector-mock-social/package.json
  packages/connector-sendgrid-mail/package.json
  packages/connector-twilio-sms/package.json
  packages/connector-wechat-native/package.json
  packages/connector-wechat-web/package.json
  pnpm-lock.yaml
Labels: chore, size/s

#1832 test: increase request timeout in integration tests
  packages/integration-tests/src/api/api.ts
Labels: testing, size/xs

#1834 chore(core): function naming should stick to camel case
  packages/core/src/routes/session/middleware/koa-guard-session-action.ts
Labels: chore, size/xs

#1828 refactor(shared,connector-core): prepare for publishing
  packages/connector-core/package.json
  packages/shared/package.json
Labels: enhancement, size/s

#1836 chore: update publish workflow
  .github/workflows/publish.yml
Labels: chore, size/xs

#1838 refactor(phrases,shared,connector-core): move language key to shared
  packages/connector-core/package.json
  packages/connector-core/src/types.ts
  packages/console/src/hooks/use-user-preferences.ts
  packages/console/src/i18n/init.ts
  packages/console/src/pages/Connectors/components/Guide/index.tsx
  packages/console/src/pages/Settings/index.tsx
  packages/console/src/pages/SignInExperience/components/Preview.tsx
  packages/console/src/pages/SignInExperience/types.ts
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/routes/sign-in-experience.guard.test.ts
  packages/core/src/utils/zod.ts
  packages/demo-app/src/i18n/init.ts
  packages/phrases-ui/package.json
  packages/phrases-ui/src/index.ts
  packages/phrases-ui/src/types.ts
  packages/phrases/package.json
  packages/phrases/src/index.ts
  packages/phrases/src/types.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/seeds/setting.ts
  packages/schemas/src/seeds/sign-in-experience.ts
  packages/shared/package.json
  packages/shared/src/index.ts
  packages/shared/src/language.ts
  packages/ui/src/__mocks__/logto.tsx
  packages/ui/src/components/Button/SocialLinkButton.tsx
  packages/ui/src/containers/SocialSignIn/SocialSignInDropdown/index.tsx
  packages/ui/src/types/index.ts
  pnpm-lock.yaml
Labels: enhancement, size/m

#1826 feat(connector): add kakao connector
  packages/connector-kakao/README.md
  packages/connector-kakao/docs/config-template.json
  packages/connector-kakao/jest.config.ts
  packages/connector-kakao/logo.svg
  packages/connector-kakao/package.json
  packages/connector-kakao/src/constant.ts
  packages/connector-kakao/src/index.test.ts
  packages/connector-kakao/src/index.ts
  packages/connector-kakao/src/mock.ts
  packages/connector-kakao/src/types.ts
  packages/connector-kakao/tsconfig.base.json
  packages/connector-kakao/tsconfig.build.json
  packages/connector-kakao/tsconfig.json
  packages/connector-kakao/tsconfig.test.json
  packages/core/package.json
  packages/core/src/connectors/consts.ts
  packages/core/src/connectors/index.test.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#1840 build(connector): use ncc to package connector
  packages/connector-alipay-native/package.json
  packages/connector-alipay-web/package.json
  packages/connector-aliyun-dm/package.json
  packages/connector-aliyun-sms/package.json
  packages/connector-apple/package.json
  packages/connector-azuread/package.json
  packages/connector-facebook/package.json
  packages/connector-github/package.json
  packages/connector-google/package.json
  packages/connector-kakao/package.json
  packages/connector-mock-email/package.json
  packages/connector-mock-sms/package.json
  packages/connector-mock-social/package.json
  packages/connector-sendgrid-mail/package.json
  packages/connector-smtp/package.json
  packages/connector-twilio-sms/package.json
  packages/connector-wechat-native/package.json
  packages/connector-wechat-web/package.json
  pnpm-lock.yaml
Labels: size/s

#1833 chore(connector-core): connector error codes use i18n key as enum string literals
  packages/connector-core/src/types.ts
  packages/core/src/middleware/koa-connector-error-handler.test.ts
  packages/core/src/middleware/koa-connector-error-handler.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko-kr/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
Labels: chore, size/m
