Repository logto-io/logto, pull requests merged in 2022-09, with the labels that each got.

#1845 refactor(connector): update access configs
  packages/connector-alipay-native/package.json
  packages/connector-alipay-web/package.json
  packages/connector-aliyun-dm/package.json
  packages/connector-aliyun-sms/package.json
  packages/connector-apple/package.json
  packages/connector-azuread/package.json
  packages/connector-facebook/package.json
  packages/connector-github/package.json
  packages/connector-google/package.json
  packages/connector-kakao/package.json
  packages/connector-mock-email/package.json
  packages/connector-mock-sms/package.json
  packages/connector-mock-social/package.json
  packages/connector-sendgrid-mail/package.json
  packages/connector-smtp/package.json
  packages/connector-twilio-sms/package.json
  packages/connector-wechat-native/package.json
  packages/connector-wechat-web/package.json
Labels: enhancement, size/s

#1846 chore: fix postgres setup in integration test
  .github/workflows/integration-test.yml
Labels: chore, size/s

#1854 chore: upgrade silverhand packages
  packages/connector-alipay-native/package.json
  packages/connector-alipay-web/package.json
  packages/connector-alipay-web/src/constant.ts
  packages/connector-aliyun-dm/package.json
  packages/connector-aliyun-dm/src/constant.ts
  packages/connector-aliyun-sms/package.json
  packages/connector-aliyun-sms/src/constant.ts
  packages/connector-apple/package.json
  packages/connector-apple/src/constant.ts
  packages/connector-azuread/package.json
  packages/connector-azuread/src/constant.ts
  packages/connector-core/package.json
  packages/connector-facebook/package.json
  packages/connector-facebook/src/constant.ts
  packages/connector-facebook/src/types.ts
  packages/connector-github/package.json
  packages/connector-github/src/constant.ts
  packages/connector-google/package.json
  packages/connector-google/src/constant.ts
  packages/connector-google/src/types.ts
  packages/connector-kakao/package.json
  packages/connector-mock-email/package.json
  packages/connector-mock-email/src/constant.ts
  packages/connector-mock-sms/package.json
  packages/connector-mock-sms/src/constant.ts
  packages/connector-mock-social/package.json
  packages/connector-mock-social/src/constant.ts
  packages/connector-sendgrid-mail/package.json
  packages/connector-sendgrid-mail/src/constant.ts
  packages/connector-smtp/package.json
  packages/connector-smtp/src/constant.ts
  packages/connector-twilio-sms/package.json
  packages/connector-twilio-sms/src/constant.ts
  packages/connector-wechat-native/package.json
  packages/connector-wechat-native/src/constant.ts
  packages/connector-wechat-web/package.json
  packages/connector-wechat-web/src/constant.ts
  packages/console/package.json
  packages/console/src/include.d/react-i18next.d.ts
  packages/console/src/pages/Settings/index.tsx
  packages/console/src/pages/SignInExperience/components/AuthenticationForm.tsx
  packages/core/package.json
  packages/core/src/include.d/koa.d.ts
  packages/core/src/include.d/oidc-provider.d.ts
  packages/core/src/queries/user.test.ts
  packages/core/src/queries/user.ts
  packages/core/src/routes/connector.test.ts
  packages/core/src/routes/well-known.test.ts
  packages/demo-app/package.json
  packages/demo-app/src/include.d/react-i18next.d.ts
  packages/integration-tests/package.json
  packages/phrases-ui/package.json
  packages/phrases/package.json
  packages/schemas/package.json
  packages/schemas/src/gen/index.ts
  packages/shared/package.json
  packages/ui/package.json
  packages/ui/src/containers/SocialSignIn/SocialSignInDropdown/index.tsx
  pnpm-lock.yaml
Labels: chore, size/m

#1869 test: increase integration test case timeout to 10s
  packages/integration-tests/jest.setup.js
  packages/integration-tests/src/api/api.ts
Labels: testing, size/xs

#1873 fix: remove `--incremental` to temporarily fix `pnpm dev`
  package.json
Labels: bugfix, size/xs

#1878 chore: run dev mode in gitpod
  .gitpod.yml
Labels: chore, size/s

#1879 feat(core)!: load connectors by folder
  .github/workflows/integration-test.yml
  .github/workflows/release.yml
  .gitignore
  package.sh
  packages/core/package.json
  packages/core/src/cli/add-connector.ts
  packages/core/src/cli/add-official-connectors.ts
  packages/core/src/connectors/add-connectors.ts
  packages/core/src/connectors/consts.ts
  packages/core/src/connectors/index.test.ts
  packages/core/src/connectors/index.ts
  packages/core/src/connectors/types.ts
  packages/core/src/connectors/utilities/index.ts
  packages/core/src/env-set/add-connectors.ts
  packages/core/src/env-set/index.ts
  packages/integration-tests/tests/api/connector.test.ts
  packages/integration-tests/tests/api/sign-in-experience.test.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#1882 ci: add official connectors for dev server
  .github/workflows/deploy-dev.yml
Labels: size/xs

#1881 build: add official connectors for dockerfile
  Dockerfile
Labels: size/xs

#1883 chore: skip prepack for gitpod
  .gitpod.yml
Labels: chore, size/xs

#1864 feat(phrases): add portuguese language
  packages/core/src/__mocks__/connector.ts
  packages/phrases-ui/src/index.ts
  packages/phrases-ui/src/locales/pt-pt.ts
  packages/phrases-ui/src/types.ts
  packages/phrases/src/index.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/pt-pt/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/applications.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/contact.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/dashboard.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/errors.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/get-started.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/log-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/logs.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/session-expired.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/settings.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tabs.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/users.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/welcome.ts
  packages/phrases/src/locales/pt-pt/translation/demo-app.ts
  packages/phrases/src/locales/pt-pt/translation/index.ts
  packages/phrases/src/types.ts
  packages/shared/src/language.ts
  packages/ui/src/__mocks__/logto.tsx
Labels: feature, size/xl, bounty ⭐️⭐️

#1857 chore(connector-core,core,phrases): use try catch on JSON.parse
  packages/connector-core/src/index.ts
  packages/connector-core/src/types.ts
  packages/core/src/middleware/koa-connector-error-handler.test.ts
  packages/core/src/middleware/koa-connector-error-handler.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko-kr/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
Labels: chore, size/s

#1887 chore(console,demo-app): bump react sdk version to beta.3
  packages/console/package.json
  packages/console/src/components/AppContent/components/UserInfo/index.tsx
  packages/demo-app/package.json
  packages/demo-app/src/App.tsx
  pnpm-lock.yaml
Labels: chore, size/xs

#1831 docs: go web app integration guide
  packages/console/src/assets/docs/tutorial/integrate-sdk/go-web.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/go-web_zh-cn.mdx
  packages/console/src/pages/Applications/components/Guide/index.tsx
  packages/console/src/pages/Applications/components/GuideHeader/index.tsx
  packages/console/src/types/applications.ts
Labels: size/xl

#1891 fix(console,ui): fix locale guard issue in settings page
  packages/console/src/pages/Connectors/components/Guide/index.tsx
  packages/console/src/pages/Settings/index.tsx
  packages/shared/src/language.ts
  packages/shared/src/utilities/zod.ts
  packages/ui/src/containers/SocialSignIn/SocialSignInDropdown/index.tsx
Labels: bugfix, size/s

#1872 feat(console): press tab to insert 2 spaces in code editor (#1871)
  packages/console/src/components/CodeEditor/index.tsx
Labels: feature, bugfix, size/s

#1804 chore(phrases): update admin console phrases
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
Labels: chore, size/xs

#1894 fix: fetch connectors list from npm
  packages/core/src/connectors/add-connectors.ts
Labels: bugfix, size/s

#1884 chore(schemas,core,console): rename ConnectorDto to ConnectorResponse
  packages/console/src/hooks/use-connector-groups.ts
  packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx
  packages/console/src/pages/ConnectorDetails/components/ConnectorTabs/index.tsx
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorName/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorRow/index.tsx
  packages/console/src/pages/Connectors/components/Guide/index.tsx
  packages/console/src/pages/SignInExperience/components/ConnectorSetupWarning.tsx
  packages/console/src/pages/SignInExperience/components/Preview.tsx
  packages/console/src/pages/UserDetails/components/UserConnectors.tsx
  packages/console/src/types/connector.ts
  packages/core/src/routes/connector.ts
  packages/integration-tests/src/api/connector.ts
  packages/schemas/src/types/connector.ts
Labels: chore, size/s

#1895 fix(console): input invalid format content in multitextinput will not crash the app
  packages/console/src/components/MultiTextInput/types.ts
  packages/console/src/components/MultiTextInput/utils.ts
Labels: bugfix, size/s

#1896 fix: downgrade to sdk 1.0.0-beta.2
  packages/console/package.json
  packages/console/src/components/AppContent/components/UserInfo/index.tsx
  packages/demo-app/package.json
  packages/demo-app/src/App.tsx
  packages/integration-tests/jest.setup.js
  packages/integration-tests/package.json
  packages/integration-tests/src/client/index.ts
  packages/integration-tests/src/client/storage.ts
  packages/integration-tests/src/helpers.ts
  packages/integration-tests/tests/api/session.test.ts
  packages/integration-tests/tests/api/social-session.test.ts
  pnpm-lock.yaml
Labels: bugfix, size/s

#1897 chore: update integration test workflow
  .github/workflows/integration-test.yml
Labels: chore, size/xs

#1893 chore: update CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: chore, size/xs

#1899 docs: remove `persistAccessToken` from go web docs
  packages/console/src/assets/docs/tutorial/integrate-sdk/go-web.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/go-web_zh-cn.mdx
Labels: size/xs

#1901 feat(core): save empty string as null value in DB
  packages/core/src/database/utils.test.ts
  packages/core/src/database/utils.ts
Labels: feature, size/s

#1910 chore: bump to js sdk 1.0.0-beta.4
  packages/console/package.json
  packages/console/src/components/AppContent/components/UserInfo/index.tsx
  packages/console/src/components/AppContent/index.tsx
  packages/demo-app/package.json
  packages/demo-app/src/App.tsx
  packages/integration-tests/package.json
  packages/integration-tests/src/client/index.ts
  packages/integration-tests/src/client/storage.ts
  packages/integration-tests/src/helpers.ts
  packages/integration-tests/tests/api/session.test.ts
  packages/integration-tests/tests/api/social-session.test.ts
  pnpm-lock.yaml
Labels: chore, size/s

#1912 fix(console): old value does not flash back on saving form
  packages/console/src/components/AppContent/index.tsx
Labels: bugfix, size/xs

#1905 feat(core,schemas): add phrases schema and GET /custom-phrases/:languageKey route
  packages/core/src/queries/custom-phrase.ts
  packages/core/src/routes/custom-phrase.test.ts
  packages/core/src/routes/custom-phrase.ts
  packages/core/src/routes/init.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/tables/custom_phrases.sql
Labels: feature, size/m

#1918 chore: bump sdk to 1.0.0-beta.5
  packages/console/package.json
  packages/demo-app/package.json
  packages/integration-tests/package.json
  pnpm-lock.yaml
Labels: chore, size/xs

#1917 feat(core): add ts to interaction result
  packages/core/src/lib/session.ts
  packages/core/src/routes/session/passwordless.test.ts
  packages/core/src/routes/session/social.test.ts
  packages/core/src/routes/session/username-password.test.ts
Labels: feature, size/s

#1919 feat(core): add DELETE /custom-phrases/:languageKey route
  packages/core/src/queries/custom-phrase.ts
  packages/core/src/routes/custom-phrase.test.ts
  packages/core/src/routes/custom-phrase.ts
Labels: feature, size/s

#1920 fix: support capital letter "Y" in command line prompt
  install.js
  packages/core/src/env-set/parameters.ts
Labels: bugfix, size/xs

#1927 feat(core,phrases): add check protected access function
  packages/core/src/lib/session.ts
  packages/core/src/utils/format.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko-kr/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
Labels: feature, size/s

#1922 refactor(core)!: update user scopes
  packages/console/src/App.tsx
  packages/console/src/components/AppContent/components/UserInfo/index.tsx
  packages/core/package.json
  packages/core/src/env-set/add-connectors.ts
  packages/core/src/middleware/koa-error-handler.test.ts
  packages/core/src/middleware/koa-error-handler.ts
  packages/core/src/oidc/init.ts
  packages/core/src/oidc/scope.test.ts
  packages/core/src/oidc/scope.ts
  packages/shared/src/index.ts
  packages/shared/src/scope.ts
  pnpm-lock.yaml
Labels: enhancement, size/l

#1926 fix(console): add sandbox attribute to iframe
  packages/console/src/pages/SignInExperience/components/Preview.tsx
Labels: bugfix, size/xs

#1925 chore: check connector related types and eliminate redundancy
  packages/ui/src/containers/SocialSignIn/SocialSignInDropdown/index.test.tsx
  packages/ui/src/containers/SocialSignIn/SocialSignInDropdown/index.tsx
  packages/ui/src/containers/SocialSignIn/SocialSignInIconList/index.tsx
  packages/ui/src/containers/SocialSignIn/SocialSignInList/index.tsx
  packages/ui/src/containers/SocialSignIn/SocialSignInPopUp/index.tsx
  packages/ui/src/hooks/use-social.ts
  packages/ui/src/pages/SignIn/registry.tsx
  packages/ui/src/types/index.ts
  packages/ui/src/utils/social-connectors.test.ts
  packages/ui/src/utils/social-connectors.ts
Labels: chore, size/s

#1907 feat(core): add PUT /custom-phrases/:languageKey route
  packages/core/src/database/insert-into.ts
  packages/core/src/queries/custom-phrase.ts
  packages/core/src/routes/custom-phrase.test.ts
  packages/core/src/routes/custom-phrase.ts
  packages/core/src/routes/swagger.ts
  packages/core/src/utils/zod.test.ts
  packages/core/src/utils/zod.ts
Labels: feature, size/m

#1928 refactor(ui): refactor toast
  packages/ui/src/components/Input/index.module.scss
  packages/ui/src/components/Toast/index.module.scss
  packages/ui/src/components/Toast/index.test.tsx
  packages/ui/src/components/Toast/index.tsx
  packages/ui/src/containers/AppContent/index.tsx
  packages/ui/src/scss/normalized.scss
Labels: enhancement, size/s

#1936 chore: update README.md
  README.md
Labels: chore, size/xs

#1938 chore: update GetUserInfo to accept possible boolean or number typed values
  packages/connector-core/src/types.ts
Labels: chore, size/xs

#1940 feat(schemas): add logto configs table
  packages/schemas/tables/logto_configs.sql
Labels: feature, size/xs

#1935 feat(core): add GET /custom-phrases route
  packages/core/src/queries/custom-phrase.ts
  packages/core/src/routes/custom-phrase.test.ts
  packages/core/src/routes/custom-phrase.ts
Labels: feature, size/s

#1942 chore: expose fallback() from shared/utilities/zod
  packages/shared/src/utilities/index.ts
Labels: chore, size/xs

#1941 feat(console): auto detect language setting
  packages/console/src/pages/SignInExperience/components/LanguagesForm.tsx
  packages/console/src/pages/SignInExperience/components/index.module.scss
  packages/console/src/pages/SignInExperience/types.ts
  packages/console/src/pages/SignInExperience/utilities.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/ko-kr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
Labels: feature, size/m

#1939 chore: revert "Merge pull request #1927 from logto-io/sijie-log-4160-…
  packages/core/src/lib/session.ts
  packages/core/src/routes/session/passwordless.test.ts
  packages/core/src/routes/session/social.test.ts
  packages/core/src/routes/session/username-password.test.ts
  packages/core/src/utils/format.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko-kr/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
Labels: chore, size/s

#1948 fix(phrases): phrases-ui typo and types
  packages/phrases-ui/src/locales/ko-kr.ts
  packages/phrases-ui/src/locales/tr-tr.ts
Labels: bugfix, size/s

#1953 fix: bump react sdk and essentials toolkit to support CJK characters in idToken (fixes #1945)
  packages/console/package.json
  packages/core/package.json
  packages/demo-app/package.json
  packages/integration-tests/package.json
  packages/phrases-ui/package.json
  packages/phrases/package.json
  packages/schemas/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: bugfix, size/s

#1956 fix(console): get prefixed router basename in local dev env
  packages/console/src/App.tsx
  packages/console/src/utilities/router.ts
Labels: bugfix, size/s

#1957 chore(console): increase ky request timeout to 20s (fixes #1798)
  packages/console/src/consts/index.ts
  packages/console/src/hooks/use-api.ts
Labels: chore, size/xs

#1960 fix(console): use fallback language in preview
  packages/console/src/pages/SignInExperience/components/Preview.tsx
Labels: bugfix, size/xs

#1943 feat(ui): add forget password page
  packages/phrases-ui/src/locales/en.ts
  packages/phrases-ui/src/locales/fr.ts
  packages/phrases-ui/src/locales/ko-kr.ts
  packages/phrases-ui/src/locales/pt-pt.ts
  packages/phrases-ui/src/locales/tr-tr.ts
  packages/phrases-ui/src/locales/zh-cn.ts
  packages/ui/src/App.tsx
  packages/ui/src/containers/UsernameSignIn/index.module.scss
  packages/ui/src/containers/UsernameSignIn/index.test.tsx
  packages/ui/src/containers/UsernameSignIn/index.tsx
  packages/ui/src/pages/ForgotPassword/index.module.scss
  packages/ui/src/pages/ForgotPassword/index.test.tsx
  packages/ui/src/pages/ForgotPassword/index.tsx
  packages/ui/src/pages/SecondarySignIn/index.tsx
  packages/ui/src/pages/SignIn/registry.tsx
  packages/ui/src/types/index.ts
Labels: feature, size/m

#1952 feat(ui): add forget password flow
  packages/ui/src/App.tsx
  packages/ui/src/apis/utils.ts
  packages/ui/src/containers/Passwordless/EmailPasswordless.test.tsx
  packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.test.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
  packages/ui/src/containers/Passwordless/index.module.scss
  packages/ui/src/pages/ForgotPassword/index.test.tsx
  packages/ui/src/pages/ForgotPassword/index.tsx
  packages/ui/src/pages/Passcode/index.tsx
  packages/ui/src/pages/Register/index.tsx
  packages/ui/src/pages/SecondarySignIn/index.module.scss
  packages/ui/src/pages/SecondarySignIn/index.tsx
  packages/ui/src/types/guard.ts
  packages/ui/src/types/index.ts
Labels: feature, size/m

#1962 chore: exempt announcement issues from stale
  .github/workflows/close-stale.yml
Labels: chore, size/xs

#1965 chore: bump toolkit to v1.0.0-beta.13
  packages/console/package.json
  packages/core/package.json
  packages/demo-app/package.json
  packages/phrases-ui/package.json
  packages/phrases/package.json
  packages/schemas/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: chore, size/s

#1951 feat(core): cannot delete custom phrase used as default language in sign-in exp
  packages/core/src/routes/custom-phrase.test.ts
  packages/core/src/routes/custom-phrase.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko-kr/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
Labels: feature, size/s

#1961 feat(ui): add reset password page
  packages/phrases-ui/src/locales/en.ts
  packages/phrases-ui/src/locales/fr.ts
  packages/phrases-ui/src/locales/ko-kr.ts
  packages/phrases-ui/src/locales/pt-pt.ts
  packages/phrases-ui/src/locales/tr-tr.ts
  packages/phrases-ui/src/locales/zh-cn.ts
  packages/ui/src/App.tsx
  packages/ui/src/pages/ResetPassword/index.module.scss
  packages/ui/src/pages/ResetPassword/index.test.tsx
  packages/ui/src/pages/ResetPassword/index.tsx
Labels: feature, size/s

#1964 feat(ui): add reset password form
  packages/ui/src/apis/api.test.ts
  packages/ui/src/apis/index.test.ts
  packages/ui/src/apis/reset-password.ts
  packages/ui/src/apis/utils.ts
  packages/ui/src/containers/ResetPassword/index.module.scss
  packages/ui/src/containers/ResetPassword/index.test.tsx
  packages/ui/src/containers/ResetPassword/index.tsx
  packages/ui/src/pages/ResetPassword/index.tsx
Labels: feature, size/l

#1963 feat(core): add POST /session/forgot-password/{email,sms}/send-passcode
  packages/core/src/routes/session/forgot-password.test.ts
  packages/core/src/routes/session/forgot-password.ts
  packages/core/src/routes/session/index.ts
  packages/core/src/routes/session/utils.ts
  packages/schemas/src/types/log.ts
Labels: feature, size/m

#1968 feat(core): add POST /session/forgot-password/{email,sms}/verify-passcode
  packages/core/src/routes/session/consts.ts
  packages/core/src/routes/session/forgot-password.test.ts
  packages/core/src/routes/session/forgot-password.ts
  packages/core/src/routes/session/username-password.test.ts
  packages/schemas/src/types/log.ts
Labels: feature, size/m

#1970 refactor(core): refactor admin user auth check logic
  packages/core/src/lib/session.ts
  packages/core/src/routes/session/index.test.ts
  packages/core/src/routes/session/index.ts
  packages/core/src/routes/session/username-password.test.ts
  packages/core/src/routes/session/username-password.ts
  packages/integration-tests/src/client/index.ts
  packages/integration-tests/tests/api/session.test.ts
Labels: enhancement, size/m

#1958 refactor: updated button component in packages/ui (closes #1859)
  packages/ui/src/components/Button/index.test.tsx
  packages/ui/src/components/Button/index.tsx
  packages/ui/src/components/ConfirmModal/AcModal.tsx
  packages/ui/src/components/ConfirmModal/IframeConfirmModal.tsx
  packages/ui/src/components/ConfirmModal/MobileModal.tsx
  packages/ui/src/containers/CreateAccount/index.tsx
  packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
  packages/ui/src/containers/ResetPassword/index.tsx
  packages/ui/src/containers/SocialCreateAccount/index.tsx
  packages/ui/src/containers/UsernameSignIn/index.tsx
  packages/ui/src/pages/ErrorPage/index.tsx
Labels: enhancement, size/m

#1966 feat(core,schemas): migration deploy cli
  packages/core/package.json
  packages/core/src/cli/add-connector.ts
  packages/core/src/cli/add-official-connectors.ts
  packages/core/src/cli/migration-deploy.ts
  packages/core/src/migration/constants.ts
  packages/core/src/migration/index.test.ts
  packages/core/src/migration/index.ts
  packages/core/src/migration/types.ts
  packages/core/src/migration/utils.test.ts
  packages/core/src/migration/utils.ts
  packages/schemas/package.json
  packages/schemas/src/foundations/schemas.ts
  packages/schemas/src/migrations/README.md
  pnpm-lock.yaml
Labels: feature, size/l

#1972 feat(core): add POST /session/forgot-password/reset
  packages/core/src/__mocks__/user.ts
  packages/core/src/routes/session/forgot-password.test.ts
  packages/core/src/routes/session/forgot-password.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko-kr/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
  packages/schemas/src/types/log.ts
Labels: feature, size/l

#1973 feat(core): machine to machine apps
  packages/console/src/consts/applications.ts
  packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx
  packages/console/src/pages/ApplicationDetails/components/Settings.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/Applications/components/Guide/index.tsx
  packages/console/src/types/applications.ts
  packages/core/src/__mocks__/index.ts
  packages/core/src/oidc/adapter.test.ts
  packages/core/src/oidc/adapter.ts
  packages/core/src/oidc/init.ts
  packages/core/src/oidc/utils.test.ts
  packages/core/src/oidc/utils.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/applications.ts
  packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/applications.ts
  packages/phrases/src/locales/ko-kr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko-kr/translation/admin-console/applications.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/applications.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/applications.ts
  packages/schemas/src/types/oidc-config.ts
  packages/schemas/tables/applications.sql
Labels: feature, size/l

#1977 refactor(core)!: update `koaAuth()` to inject detailed auth info
  packages/core/src/middleware/koa-auth.test.ts
  packages/core/src/middleware/koa-auth.ts
  packages/core/src/middleware/koa-user-info.test.ts
  packages/core/src/middleware/koa-user-info.ts
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
  packages/core/src/routes/types.ts
  packages/core/src/utils/test-utils.ts
Labels: enhancement, size/m

#1980 feat(core): deploy migration in transaction mode
  packages/core/src/migration/index.ts
  packages/core/src/migration/types.ts
Labels: feature, size/s

#1976 feat(ui): add passwordless switch
  packages/core/src/middleware/koa-spa-session-guard.ts
  packages/phrases-ui/src/locales/en.ts
  packages/phrases-ui/src/locales/fr.ts
  packages/phrases-ui/src/locales/ko-kr.ts
  packages/phrases-ui/src/locales/pt-pt.ts
  packages/phrases-ui/src/locales/tr-tr.ts
  packages/phrases-ui/src/locales/zh-cn.ts
  packages/ui/src/containers/CreateAccount/index.module.scss
  packages/ui/src/containers/CreateAccount/index.tsx
  packages/ui/src/containers/Passwordless/EmailPasswordless.test.tsx
  packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
  packages/ui/src/containers/Passwordless/PasswordlessSwitch.test.tsx
  packages/ui/src/containers/Passwordless/PasswordlessSwitch.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.test.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
  packages/ui/src/containers/Passwordless/index.module.scss
  packages/ui/src/containers/SocialSignIn/PrimarySocialSignIn/index.module.scss
  packages/ui/src/containers/SocialSignIn/PrimarySocialSignIn/index.tsx
  packages/ui/src/containers/UsernameSignIn/index.module.scss
  packages/ui/src/containers/UsernameSignIn/index.tsx
  packages/ui/src/pages/ForgotPassword/index.tsx
  packages/ui/src/pages/Register/index.tsx
  packages/ui/src/pages/SecondarySignIn/index.tsx
  packages/ui/src/pages/SignIn/index.module.scss
  packages/ui/src/pages/SignIn/registry.tsx
Labels: feature, size/xl

#1984 docs(schemas): add migration file readme
  packages/schemas/src/migrations/README.md
Labels: size/s

#1978 refactor(core): add migration scripts for #1973
  packages/core/src/migration/index.ts
  packages/schemas/.gitignore
  packages/schemas/migrations/README.md
  packages/schemas/migrations/next.ts
  packages/schemas/migrations/types.ts
  packages/schemas/package.json
  packages/schemas/tsconfig.build.migrations.json
  packages/schemas/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement, size/s

#1987 fix(core): filter out connector-kit
  packages/core/src/connectors/add-connectors.ts
Labels: bugfix, size/xs

#1981 feat(console): manage language
  packages/console/src/components/ModalLayout/index.module.scss
  packages/console/src/components/ModalLayout/index.tsx
  packages/console/src/pages/SignInExperience/components/LanguagesForm.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/EditSection.module.scss
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/EditSection.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageEditor.module.scss
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageEditor.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageItem.module.scss
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageItem.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageNav.module.scss
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageNav.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/index.module.scss
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/index.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/types.ts
  packages/console/src/pages/SignInExperience/components/index.module.scss
  packages/console/src/pages/SignInExperience/utilities.ts
  packages/console/src/scss/_dimensions.scss
  packages/phrases-ui/src/index.ts
  packages/phrases-ui/src/locales/fr.ts
  packages/phrases-ui/src/locales/ko-kr.ts
  packages/phrases-ui/src/locales/pt-pt.ts
  packages/phrases-ui/src/locales/tr-tr.ts
  packages/phrases-ui/src/locales/zh-cn.ts
  packages/phrases-ui/src/types.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/ko-kr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
Labels: feature, size/xl

#1988 chore: bump to js sdk 1.0.0-beta.8
  packages/console/package.json
  packages/demo-app/package.json
  packages/integration-tests/package.json
  pnpm-lock.yaml
Labels: chore, size/xs

#1979 feat(core): check migration state before app start
  package.json
  packages/core/src/env-set/check-migration-state.ts
  packages/core/src/env-set/index.ts
  packages/core/src/migration/index.test.ts
Labels: feature, size/s

#1991 fix(ui): align mobile input outline
  packages/ui/src/components/Passcode/index.module.scss
Labels: bugfix, size/xs

#1998 chore: update commitlint config
  commitlint.config.js
Labels: chore, size/xs

#1993 refactor(ui): refactor confirmModalPromisify
  packages/ui/src/components/ConfirmModal/index.tsx
  packages/ui/src/components/ConfirmModal/modalPromisify/index.test.tsx
  packages/ui/src/components/ConfirmModal/modalPromisify/index.tsx
  packages/ui/src/containers/TermsOfUse/TermsOfUseConfirmModal/index.tsx
  packages/ui/src/containers/TermsOfUse/TermsOfUseIframeModal/index.tsx
  packages/ui/src/containers/UsernameSignIn/index.test.tsx
  packages/ui/src/hooks/use-terms.ts
  packages/ui/src/types/index.ts
  packages/ui/src/utils/promisify.test.ts
  packages/ui/src/utils/promisify.ts
Labels: enhancement, size/s

#1982 chore(core): remove unnecessary updateLastSignInAt
  packages/core/package.json
  packages/core/src/lib/user.test.ts
  packages/core/src/lib/user.ts
  packages/core/src/routes/session/passwordless.test.ts
  packages/core/src/routes/session/passwordless.ts
  packages/core/src/routes/session/social.test.ts
  packages/core/src/routes/session/social.ts
  packages/core/src/routes/session/username-password.test.ts
  packages/core/src/routes/session/username-password.ts
Labels: chore, size/s

#1999 feat(console): configure M2M app access
  packages/console/src/assets/images/machine-to-machine-dark.svg
  packages/console/src/assets/images/machine-to-machine.svg
  packages/console/src/assets/images/native-app-dark.svg
  packages/console/src/assets/images/native-app.svg
  packages/console/src/assets/images/single-page-app-dark.svg
  packages/console/src/assets/images/single-page-app.svg
  packages/console/src/assets/images/traditional-web-app-dark.svg
  packages/console/src/assets/images/traditional-web-app.svg
  packages/console/src/components/RadioGroup/index.module.scss
  packages/console/src/consts/applications.ts
  packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/Applications/components/TypeDescription/index.module.scss
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko-kr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
Labels: feature, size/l

#1996 refactor(console): fix me api error
  packages/console/src/assets/images/machine-to-machine-dark.svg
  packages/console/src/assets/images/machine-to-machine.svg
  packages/console/src/assets/images/native-app-dark.svg
  packages/console/src/assets/images/native-app.svg
  packages/console/src/assets/images/single-page-app-dark.svg
  packages/console/src/assets/images/single-page-app.svg
  packages/console/src/assets/images/traditional-web-app-dark.svg
  packages/console/src/assets/images/traditional-web-app.svg
  packages/console/src/components/RadioGroup/index.module.scss
  packages/console/src/consts/applications.ts
  packages/console/src/hooks/use-logto-user-id.ts
  packages/console/src/hooks/use-user-preferences.ts
  packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/Applications/components/TypeDescription/index.module.scss
  packages/console/src/pages/Settings/components/ChangePassword.tsx
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko-kr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
Labels: enhancement, size/l

#1994 feat(console): display unsaved alert on custom phrases changed
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageEditor.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/ko-kr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
Labels: feature, size/s

#1995 refactor(console): filter empty content before updating custom phrases
  packages/console/package.json
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageEditor.tsx
  pnpm-lock.yaml
Labels: enhancement, size/xs

#1990 feat(core,schemas): use timestamp to version migrations
  packages/core/package.json
  packages/core/src/env-set/index.ts
  packages/core/src/migration/constants.ts
  packages/core/src/migration/index.test.ts
  packages/core/src/migration/index.ts
  packages/core/src/migration/utils.test.ts
  packages/core/src/migration/utils.ts
  packages/schemas/migrations/README.md
  packages/schemas/migrations/next-1663923211-machine-to-machine-app.ts
  packages/schemas/migrations/types.ts
  pnpm-lock.yaml
Labels: feature, size/m

#2001 feat(core): update migration state after db init
  packages/core/src/database/seed.ts
  packages/core/src/env-set/index.ts
  packages/core/src/migration/index.ts
Labels: feature, size/s

#2002 refactor(core,schemas): rename migration to alteration
  package.json
  packages/core/package.json
  packages/core/src/alteration/constants.ts
  packages/core/src/alteration/index.test.ts
  packages/core/src/alteration/index.ts
  packages/core/src/alteration/utils.test.ts
  packages/core/src/alteration/utils.ts
  packages/core/src/cli/alteration.ts
  packages/core/src/database/seed.ts
  packages/core/src/env-set/check-migration-state.ts
  packages/core/src/env-set/index.ts
  packages/core/src/migration/constants.ts
  packages/schemas/.gitignore
  packages/schemas/alterations/README.md
  packages/schemas/alterations/next-1663923211-machine-to-machine-app.ts
  packages/schemas/alterations/types.ts
  packages/schemas/migrations/README.md
  packages/schemas/package.json
  packages/schemas/tsconfig.build.alterations.json
  packages/schemas/tsconfig.json
Labels: enhancement, size/l

#2005 fix(core,schemas): move alteration types into schemas src
  packages/core/src/alteration/index.ts
  packages/schemas/src/types/alteration.ts
Labels: bugfix, size/xs

#2003 Revert "fix(console): use fallback language in preview (#1960)"
  packages/console/src/pages/SignInExperience/components/Preview.tsx
Labels: size/xs

#2004 Revert "feat(console): auto detect language setting (#1941)"
  packages/console/src/pages/SignInExperience/components/LanguagesForm.tsx
  packages/console/src/pages/SignInExperience/components/index.module.scss
  packages/console/src/pages/SignInExperience/types.ts
  packages/console/src/pages/SignInExperience/utilities.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/ko-kr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
Labels: size/m

#1989 refactor(console): hide manage language button in sign-in-experience guide
  packages/console/src/pages/SignInExperience/components/LanguagesForm.tsx
  packages/console/src/pages/SignInExperience/tabs/OthersTab.tsx
Labels: enhancement, feature, size/s

#2006 refactor(console): use `Translation` type from `@logto/schemas`
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/EditSection.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageEditor.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/types.ts
  packages/console/src/pages/SignInExperience/utilities.ts
Labels: enhancement, size/s

#2008 refactor(schemas): auto update next alteration scripts
  packages/core/src/alteration/index.ts
  packages/schemas/package.json
  packages/schemas/update-next.sh
Labels: enhancement, size/s

#2014 chore: sleep 10s before dev health check
  .github/workflows/deploy-dev.yml
Labels: chore, size/xs

#1959 feat(core,phrases): add GET /phrase route
  packages/core/package.json
  packages/core/src/__mocks__/custom-phrase.ts
  packages/core/src/lib/phrase.test.ts
  packages/core/src/lib/phrase.ts
  packages/core/src/middleware/koa-guard.ts
  packages/core/src/queries/custom-phrase.ts
  packages/core/src/routes/custom-phrase.test.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/phrase.content-language.test.ts
  packages/core/src/routes/phrase.test.ts
  packages/core/src/routes/phrase.ts
  packages/phrases-ui/src/index.ts
  packages/phrases-ui/src/types.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#2016 chore(schemas): add custom phrases database alteration script
  packages/schemas/alterations/next-1663923211-machine-to-machine-app.ts
  packages/schemas/alterations/next-1664265197-custom-phrases.ts
Labels: feature, chore, size/s

#2019 chore(console): replace icons in get-started page
  packages/console/src/assets/images/check-demo-dark.svg
  packages/console/src/assets/images/check-demo.svg
  packages/console/src/assets/images/create-app-dark.svg
  packages/console/src/assets/images/create-app.svg
  packages/console/src/assets/images/customize-dark.svg
  packages/console/src/assets/images/customize.svg
  packages/console/src/assets/images/further-readings-dark.svg
  packages/console/src/assets/images/further-readings.svg
  packages/console/src/assets/images/one-click-dark.svg
  packages/console/src/assets/images/one-click.svg
  packages/console/src/assets/images/passwordless-dark.svg
  packages/console/src/assets/images/passwordless.svg
  packages/console/src/assets/images/social-dark.svg
  packages/console/src/assets/images/social.svg
  packages/console/src/pages/GetStarted/hook.ts
Labels: chore, size/l

#2011 refactor(console): open docs website for M2M app guide
  packages/console/src/pages/ApplicationDetails/index.tsx
Labels: enhancement, size/s

#2020 style(console): new style for add connectors
  packages/console/src/components/ModalLayout/index.module.scss
  packages/console/src/components/ModalLayout/index.tsx
  packages/console/src/components/RadioGroup/Radio.tsx
  packages/console/src/components/RadioGroup/index.module.scss
  packages/console/src/pages/Connectors/components/CreateForm/index.module.scss
  packages/console/src/pages/Connectors/components/CreateForm/index.tsx
  packages/console/src/scss/_dimensions.scss
Labels: size/m

#2024 refactor(console,core,phrases): replace `LanguageKey` with `LangaugeTag` in phrase-ui related code
  packages/console/package.json
  packages/console/src/pages/SignInExperience/components/LanguagesForm.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageEditor.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageItem.module.scss
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageItem.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageNav.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/index.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/types.ts
  packages/console/src/pages/SignInExperience/components/Preview.tsx
  packages/core/package.json
  packages/core/src/lib/phrase.ts
  packages/core/src/routes/phrase.ts
  packages/phrases-ui/package.json
  packages/phrases-ui/src/index.ts
  packages/phrases-ui/src/types.ts
  packages/phrases/package.json
  pnpm-lock.yaml
Labels: enhancement, size/m

#2025 chore: upgrade terser
  pnpm-lock.yaml
Labels: chore, size/xs

#2017 refactor(core): should not use login to store session info
  packages/core/src/routes/session/forgot-password.test.ts
  packages/core/src/routes/session/forgot-password.ts
Labels: enhancement, bugfix, size/s

#2023 refactor(core,phrases,schemas): validate fallback language before updating sign-in experience
  packages/core/package.json
  packages/core/src/lib/sign-in-experience.test.ts
  packages/core/src/lib/sign-in-experience.ts
  packages/core/src/routes/sign-in-experience.guard.test.ts
  packages/core/src/routes/sign-in-experience.test.ts
  packages/core/src/routes/sign-in-experience.ts
  packages/core/src/utils/zod.test.ts
  packages/core/src/utils/zod.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko-kr/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
  packages/schemas/package.json
  packages/schemas/src/foundations/jsonb-types.ts
  pnpm-lock.yaml
Labels: enhancement, size/m

#2027 refactor(core): count new users by created_at
  packages/core/src/__mocks__/user.ts
  packages/core/src/queries/log.ts
  packages/core/src/queries/user.ts
  packages/core/src/routes/dashboard.test.ts
  packages/core/src/routes/dashboard.ts
  packages/schemas/alterations/next-1664356000-add-created-at-column-to-users.ts
  packages/schemas/src/types/user.ts
  packages/schemas/tables/users.sql
Labels: enhancement, size/s

#2022 refactor(core,phrases): rm empty strings and check structure in PUT /custom-phrase
  packages/core/src/routes/custom-phrase.test.ts
  packages/core/src/routes/custom-phrase.ts
  packages/core/src/utils/translation.test.ts
  packages/core/src/utils/translation.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko-kr/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
Labels: enhancement, size/m

#2031 chore(schemas): add db alteration script to repair user created_at column by user logs
  packages/schemas/alterations/next-1664462389-correct-user-created-at-column-by-user-logs.ts
Labels: chore, size/s

#2026 refactor(core,console,phrases,schemas): replace language key with language tag
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/index.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/types.ts
  packages/core/src/__mocks__/custom-phrase.ts
  packages/core/src/lib/phrase.test.ts
  packages/core/src/lib/phrase.ts
  packages/core/src/lib/sign-in-experience.test.ts
  packages/core/src/lib/sign-in-experience.ts
  packages/core/src/queries/custom-phrase.ts
  packages/core/src/routes/custom-phrase.test.ts
  packages/core/src/routes/custom-phrase.ts
  packages/core/src/routes/phrase.content-language.test.ts
  packages/core/src/routes/phrase.test.ts
  packages/core/src/routes/phrase.ts
  packages/core/src/routes/sign-in-experience.test.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko-kr/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
  packages/schemas/alterations/next-1664347703-rename-language-key-to-tag.ts
  packages/schemas/tables/custom_phrases.sql
Labels: enhancement, size/l

#2018 feat(ui): global confirm modal
  packages/ui/src/components/ConfirmModal/AcModal.tsx
  packages/ui/src/components/ConfirmModal/IframeConfirmModal.tsx
  packages/ui/src/components/ConfirmModal/MobileModal.tsx
  packages/ui/src/components/ConfirmModal/index.tsx
  packages/ui/src/components/ConfirmModal/type.ts
  packages/ui/src/containers/AppContent/index.tsx
  packages/ui/src/containers/ConfirmModalProvider/index.tsx
  packages/ui/src/containers/ConfirmModalProvider/indext.test.tsx
  packages/ui/src/containers/PasscodeValidation/index.test.tsx
  packages/ui/src/containers/PasscodeValidation/index.tsx
  packages/ui/src/containers/Passwordless/EmailPasswordless.test.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
  packages/ui/src/containers/TermsOfUse/TermsOfUseConfirmModal/index.tsx
  packages/ui/src/hooks/use-confirm-modal.ts
Labels: feature, size/l

#2034 refactor(core,schemas): refactor log types with zod
  packages/core/jest.config.ts
  packages/core/src/middleware/koa-log.ts
  packages/schemas/src/types/log.ts
Labels: enhancement, size/l

#2029 feat(console): add custom language
  packages/console/src/pages/SignInExperience/components/LanguagesForm.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/AddLanguageSelector.module.scss
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/AddLanguageSelector.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageEditor.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageItem.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageNav.module.scss
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageNav.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/index.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/types.ts
  packages/console/src/pages/SignInExperience/hooks/use-custom-phrases-context.ts
  packages/console/src/pages/SignInExperience/types.ts
Labels: feature, size/xl

#2037 fix(console): language editor form should be dirty on clear button clicked
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageEditor.tsx
  packages/console/src/pages/SignInExperience/utilities.ts
Labels: bugfix, size/s
