Repository logto-io/logto, pull requests merged in 2022-10, with the labels that each got.

#2040 chore: update dev deployment
  .github/workflows/deploy-dev.yml
  .github/workflows/release.yml
Labels: chore, size/s

#2041 chore: fix typo in release workflow
  .github/workflows/release.yml
Labels: chore, size/xs

#2033 refactor(ui): refactor ui i18n
  packages/ui/src/App.tsx
  packages/ui/src/apis/settings.ts
  packages/ui/src/hooks/use-preview.ts
  packages/ui/src/i18n/init.ts
  packages/ui/src/i18n/utils.ts
  packages/ui/src/types/index.ts
  packages/ui/src/utils/sign-in-experience.test.ts
  packages/ui/src/utils/sign-in-experience.ts
Labels: enhancement, size/m

#2007 feat: init cli
  packages/cli/bin/logto
  packages/cli/package.json
  packages/cli/src/index.ts
  packages/cli/src/utilities.ts
  packages/cli/tsconfig.json
  pnpm-lock.yaml
Labels: feature, size/l

#2049 fix(core): fix deletePasscodeByIds bug
  packages/core/src/queries/passcode.test.ts
  packages/core/src/queries/passcode.ts
Labels: bugfix, size/s

#2042 feat(cli): command `init/i/install`
  packages/cli/package.json
  packages/cli/src/commands/install.ts
  packages/cli/src/index.ts
  pnpm-lock.yaml
Labels: feature, size/l

#2043 feat(cli): database config command
  packages/cli/package.json
  packages/cli/src/commands/database/index.ts
  packages/cli/src/commands/database/url.ts
  packages/cli/src/commands/install.ts
  packages/cli/src/config.ts
  packages/cli/src/index.ts
  packages/cli/src/utilities.ts
  pnpm-lock.yaml
Labels: feature, size/m

#2045 feat(cli): get/set db config key
  packages/cli/package.json
  packages/cli/src/commands/database/index.ts
  packages/cli/src/commands/database/key.ts
  packages/cli/src/commands/database/url.ts
  packages/cli/src/commands/install.ts
  packages/cli/src/database.ts
  packages/cli/src/include.d/slonik-interceptor-preset.d.ts
  packages/cli/src/index.ts
  packages/cli/src/queries/logto-config.ts
  packages/cli/src/utilities.ts
  packages/core/src/alteration/constants.ts
  packages/core/src/alteration/index.test.ts
  packages/core/src/alteration/index.ts
  packages/schemas/src/types/alteration.ts
  packages/schemas/src/types/index.ts
  packages/schemas/src/types/logto-config.ts
  pnpm-lock.yaml
Labels: feature, size/m

#2048 feat(cli): `db seed` command
  packages/cli/package.json
  packages/cli/src/commands/database/index.ts
  packages/cli/src/commands/database/seed.ts
  packages/cli/src/database.ts
  packages/cli/src/utilities.ts
  pnpm-lock.yaml
Labels: feature, size/m

#2050 feat(cli): `db alteration deploy` command
  packages/cli/.gitignore
  packages/cli/package.json
  packages/cli/src/commands/database/alteration.ts
  packages/cli/src/commands/database/index.ts
  packages/cli/src/commands/database/seed.ts
  packages/cli/src/queries/logto-config.ts
  packages/cli/src/utilities.ts
  packages/cli/tsconfig.json
  packages/core/src/alteration/constants.ts
  packages/core/src/alteration/index.test.ts
  packages/core/src/alteration/index.ts
  packages/schemas/alterations/1.0.0_beta.10-1-logto-config.ts
  packages/schemas/src/types/logto-config.ts
  pnpm-lock.yaml
Labels: feature, size/l

#2059 chore: update cli script
  packages/cli/package.json
Labels: chore, size/xs

#2051 refactor: remove database seed from core
  .github/workflows/integration-test.yml
  packages/cli/src/commands/database/alteration.ts
  packages/cli/src/commands/database/seed.ts
  packages/cli/src/commands/install.ts
  packages/cli/src/config.ts
  packages/cli/src/database.ts
  packages/cli/src/utilities.ts
  packages/core/package.json
  packages/core/src/database/seed.ts
  packages/core/src/env-set/check-alteration-state.ts
  packages/core/src/env-set/create-pool-by-env.ts
  pnpm-lock.yaml
Labels: enhancement, size/xl

#2038 refactor(console): make custom languages become available language options
  packages/console/src/hooks/use-ui-languages.ts
  packages/console/src/pages/SignInExperience/components/LanguagesForm.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageEditor.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageNav.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/index.tsx
  packages/console/src/pages/SignInExperience/components/Preview.tsx
  packages/console/src/pages/SignInExperience/hooks/use-custom-phrases-context.ts
  packages/console/src/pages/SignInExperience/hooks/use-language-editor-context.ts
  packages/console/src/pages/SignInExperience/index.tsx
  packages/console/src/pages/SignInExperience/types.ts
  packages/console/src/types/custom-phrase.ts
Labels: enhancement, size/xl

#2052 refactor: remove alteration from core
  package.json
  packages/cli/jest.config.ts
  packages/cli/package.json
  packages/cli/src/commands/database/alteration.test.ts
  packages/cli/src/commands/database/alteration.ts
  packages/cli/src/queries/logto-config.test.ts
  packages/cli/src/test-utilities.ts
  packages/cli/tsconfig.build.json
  packages/cli/tsconfig.json
  packages/cli/tsconfig.test.json
  packages/core/package.json
  packages/core/src/alteration/constants.ts
  packages/core/src/alteration/index.test.ts
  packages/core/src/alteration/index.ts
  packages/core/src/alteration/utils.test.ts
  packages/core/src/alteration/utils.ts
  packages/core/src/cli/alteration.ts
  packages/core/src/env-set/check-alteration-state.ts
  packages/core/src/env-set/index.ts
  packages/core/src/index.ts
  packages/schemas/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement, size/xl

#2063 fix(console): show correct password after reset
  packages/console/src/pages/UserDetails/components/ResetPasswordForm.tsx
Labels: bugfix, size/xs

#2062 refactor(cli): per review
  packages/cli/package.json
  packages/cli/src/commands/database/config.ts
  packages/cli/src/commands/database/index.ts
Labels: enhancement, size/s

#2065 feat(console): delete custom phrase
  packages/console/src/pages/SignInExperience/components/LanguagesForm.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageEditor.module.scss
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageEditor.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageItem.tsx
  packages/console/src/pages/SignInExperience/hooks/use-language-editor-context.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/ko-kr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
Labels: feature, size/m

#2064 refactor(cli): use env to replace config json
  .github/workflows/integration-test.yml
  packages/cli/package.json
  packages/cli/src/commands/database/alteration.ts
  packages/cli/src/commands/database/config.ts
  packages/cli/src/commands/database/index.ts
  packages/cli/src/commands/database/url.ts
  packages/cli/src/commands/install.ts
  packages/cli/src/config.ts
  packages/cli/src/database.ts
  packages/cli/src/index.ts
  pnpm-lock.yaml
Labels: enhancement, size/m

#2067 feat(cli): `db seed oidc` command
  packages/cli/src/commands/database/seed.ts
  packages/cli/src/commands/database/seed/index.ts
  packages/cli/src/commands/database/seed/oidc-config.ts
  packages/cli/src/commands/install.ts
  packages/cli/src/database.ts
  packages/cli/src/queries/logto-config.ts
  packages/cli/src/utilities.ts
  packages/schemas/src/types/logto-config.ts
Labels: feature, size/l

#2066 feat(console): add a11y lint to ac
  packages/console/package.json
  packages/console/src/components/AppContent/components/UserInfo/index.tsx
  packages/console/src/components/AppError/index.tsx
  packages/console/src/components/CopyToClipboard/index.tsx
  packages/console/src/components/DeleteConfirmModal/index.tsx
  packages/console/src/components/Drawer/index.tsx
  packages/console/src/components/Dropdown/DropdownItem.tsx
  packages/console/src/components/Dropdown/index.tsx
  packages/console/src/components/MultiTextInput/index.tsx
  packages/console/src/components/RadioGroup/Radio.tsx
  packages/console/src/components/Select/index.tsx
  packages/console/src/components/TabNav/TabNavItem.tsx
  packages/console/src/mdx-components/DetailsSummary/index.tsx
  packages/console/src/mdx-components/Step/index.tsx
  packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorName/index.tsx
  packages/console/src/pages/Connectors/components/CreateForm/index.tsx
  packages/console/src/pages/GetStarted/components/GetStartedProgress/index.tsx
  packages/console/src/pages/GetStarted/index.tsx
  packages/console/src/pages/SignInExperience/components/Preview.tsx
  packages/console/src/pages/UserDetails/components/UserConnectors.tsx
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/pages/Users/components/CreateForm/index.tsx
  packages/console/src/pages/Users/index.tsx
  packages/console/src/utilities/a11y.ts
  pnpm-lock.yaml
Labels: feature, size/m

#2056 feat(schemas): add sie2 schema
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/queries/sign-in-experience.test.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/seeds/sign-in-experience.ts
  packages/schemas/tables/sign_in_experiences.sql
  packages/ui/src/__mocks__/logto.tsx
  packages/ui/src/types/index.ts
Labels: feature, size/m

#2071 fix(console): clear select state on close modal
  packages/console/src/pages/Connectors/components/CreateForm/index.tsx
Labels: bugfix, size/xs

#2075 refactor(cli): use cli project root as alteration scripts directory
  packages/cli/package.json
  packages/cli/src/commands/database/alteration.ts
  pnpm-lock.yaml
Labels: enhancement, size/s

#2074 fix(console): set undefined value to empty string in custom phrases
  packages/console/package.json
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageEditor.tsx
  pnpm-lock.yaml
Labels: bugfix, size/xs

#2069 refactor(console): support searching in add language selector
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/AddLanguageSelector.module.scss
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/AddLanguageSelector.tsx
  packages/phrases/src/locales/en/translation/admin-console/general.ts
  packages/phrases/src/locales/fr/translation/admin-console/general.ts
  packages/phrases/src/locales/ko-kr/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
Labels: enhancement, size/m

#2073 refactor(cli): flatten OIDC config keys
  packages/cli/src/commands/database/seed/index.ts
  packages/cli/src/commands/database/seed/oidc-config.ts
  packages/cli/src/queries/logto-config.test.ts
  packages/cli/src/queries/logto-config.ts
  packages/schemas/src/types/logto-config.ts
Labels: enhancement, size/m

#2080 refactor: replace `LanguageKey` with `LanguageTag`
  packages/console/src/i18n/init.ts
  packages/console/src/include.d/react-i18next.d.ts
  packages/console/src/pages/Settings/index.tsx
  packages/demo-app/package.json
  packages/demo-app/src/i18n/init.ts
  packages/demo-app/src/include.d/react-i18next.d.ts
  packages/phrases/package.json
  packages/phrases/src/index.ts
  packages/phrases/src/locales/fr/index.ts
  packages/phrases/src/locales/ko-kr/index.ts
  packages/phrases/src/locales/pt-pt/index.ts
  packages/phrases/src/locales/tr-tr/index.ts
  packages/phrases/src/locales/zh-cn/index.ts
  packages/phrases/src/types.ts
  pnpm-lock.yaml
Labels: enhancement, size/m

#2079 feat(ui): add reset password error handling flow
  packages/phrases-ui/src/locales/en.ts
  packages/phrases-ui/src/locales/fr.ts
  packages/phrases-ui/src/locales/ko-kr.ts
  packages/phrases-ui/src/locales/pt-pt.ts
  packages/phrases-ui/src/locales/tr-tr.ts
  packages/phrases-ui/src/locales/zh-cn.ts
  packages/ui/src/apis/forgot-password.ts
  packages/ui/src/apis/utils.ts
  packages/ui/src/containers/PasscodeValidation/index.test.tsx
  packages/ui/src/containers/PasscodeValidation/index.tsx
  packages/ui/src/containers/Passwordless/PasswordlessSwitch.test.tsx
  packages/ui/src/containers/Passwordless/PasswordlessSwitch.tsx
  packages/ui/src/containers/ResetPassword/index.module.scss
  packages/ui/src/containers/ResetPassword/index.test.tsx
  packages/ui/src/containers/ResetPassword/index.tsx
Labels: feature, size/m

#2083 refactor(console): refresh preview on custom phrases updated
  packages/console/src/hooks/use-ui-languages.ts
  packages/console/src/pages/SignInExperience/components/Preview.tsx
Labels: enhancement, size/xs

#2076 feat(ui): add a11y support
  packages/ui/package.json
  packages/ui/src/components/ConfirmModal/IframeConfirmModal.tsx
  packages/ui/src/components/Drawer/index.tsx
  packages/ui/src/components/Dropdown/DropdownItem.tsx
  packages/ui/src/components/Dropdown/index.tsx
  packages/ui/src/components/Input/PhoneInput.tsx
  packages/ui/src/components/NavBar/index.tsx
  packages/ui/src/components/Notification/index.tsx
  packages/ui/src/components/TermsOfUse/index.tsx
  packages/ui/src/components/Toast/index.tsx
  packages/ui/src/containers/CreateAccount/index.tsx
  packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
  packages/ui/src/containers/ResetPassword/index.tsx
  packages/ui/src/containers/SocialLanding/index.tsx
  packages/ui/src/containers/UsernameSignIn/index.tsx
  packages/ui/src/pages/Consent/index.tsx
  packages/ui/src/pages/ForgotPassword/index.tsx
  packages/ui/src/pages/Register/index.tsx
  packages/ui/src/pages/ResetPassword/index.tsx
  packages/ui/src/pages/SecondarySignIn/index.tsx
  packages/ui/src/utils/a11y.ts
  pnpm-lock.yaml
Labels: feature, size/m

#2070 style(console): fix position of added tag
  packages/console/src/components/RadioGroup/index.module.scss
Labels: size/xs

#2077 feat(schemas): add sie v2 alteration
  packages/schemas/alterations/next-1665300135-sign-in-sign-up.ts
Labels: feature, size/m

#2078 refactor(core): read OIDC configs from database
  packages/core/jest.config.ts
  packages/core/jest.global-setup.ts
  packages/core/jest.setup.ts
  packages/core/src/env-set/__mocks__/check-alteration-state.ts
  packages/core/src/env-set/create-pool-by-env.ts
  packages/core/src/env-set/index.ts
  packages/core/src/env-set/oidc.test.ts
  packages/core/src/env-set/oidc.ts
  packages/core/src/lib/__mocks__/logto-config.ts
  packages/core/src/lib/logto-config.ts
  packages/core/src/middleware/koa-auth.ts
  packages/core/src/oidc/init.ts
  packages/core/src/queries/oidc-model-instance.ts
  packages/core/tsconfig.build.json
  packages/schemas/src/types/logto-config.ts
  pnpm-lock.yaml
Labels: enhancement, size/l

#2054 refactor(core,ui,test): sign-in and register flows mount on passwordless APIs
  packages/core/src/routes/session/passwordless.test.ts
  packages/core/src/routes/session/passwordless.ts
  packages/core/src/routes/session/types.ts
  packages/core/src/routes/session/utils.ts
  packages/integration-tests/src/api/session.ts
  packages/integration-tests/tests/api/session.test.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko-kr/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
  packages/ui/src/apis/index.test.ts
  packages/ui/src/apis/register.ts
  packages/ui/src/apis/sign-in.ts
Labels: enhancement, size/xl

#2094 ci: increase commitlint length tolerance in CI
  commitlint.config.js
Labels: size/xs

#1874 fix: add redirectURI validation on frontend & backend
  packages/console/src/pages/ApplicationDetails/components/Settings.tsx
  packages/core/src/routes/application.test.ts
  packages/core/src/utils/zod.ts
  packages/schemas/src/foundations/jsonb-types.ts
Labels: bugfix, size/s

#2032 feat: add vertical center support
  packages/console/src/components/Tooltip/index.module.scss
  packages/console/src/components/Tooltip/index.tsx
  packages/console/src/hooks/use-position.ts
Labels: feature, size/s

#2104 chore: fix gitpod
  .gitpod.yml
  package.json
Labels: chore, size/xs

#2106 chore: update GitPod demo link
  README.md
Labels: chore, size/xs

#2085 refactor(demo-app): upgrade configs and improve a11y in demo-app
  packages/demo-app/package.json
  packages/demo-app/src/App.tsx
  pnpm-lock.yaml
Labels: enhancement, size/xs

#2095 refactor(core): use fallback language as default in demo app
  packages/core/src/routes/well-known.ts
Labels: enhancement, size/xs

#2102 feat: `npm create` compatibility
  packages/cli/package.json
  packages/cli/src/commands/database/alteration.ts
  packages/cli/src/commands/database/config.ts
  packages/cli/src/commands/install.ts
  packages/cli/src/commands/install/index.ts
  packages/cli/src/commands/install/utils.ts
  packages/cli/src/database.ts
  packages/cli/src/index.ts
  packages/cli/src/utilities.ts
  packages/create/index.sh
  packages/create/package.json
  pnpm-lock.yaml
Labels: feature, size/xl

#2093 feat(core): validate sign up
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/lib/sign-in-experience/index.ts
  packages/core/src/lib/sign-in-experience/sign-up.test.ts
  packages/core/src/lib/sign-in-experience/sign-up.ts
  packages/core/src/routes/sign-in-experience.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko-kr/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
Labels: feature, size/m

#2105 refactor(ui,phrases,core): forgot password reuse verification flow
  packages/core/src/routes/session/forgot-password.test.ts
  packages/core/src/routes/session/forgot-password.ts
  packages/core/src/routes/session/passwordless.test.ts
  packages/core/src/routes/session/passwordless.ts
  packages/core/src/routes/session/types.ts
  packages/core/src/routes/session/utils.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko-kr/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
  packages/ui/src/apis/forgot-password.ts
  packages/ui/src/apis/index.test.ts
Labels: enhancement, size/xl

#2109 refactor(core): sign-in and register flow share verification session
  packages/core/src/routes/session/consts.ts
  packages/core/src/routes/session/passwordless.test.ts
  packages/core/src/routes/session/passwordless.ts
  packages/core/src/routes/session/types.ts
  packages/core/src/routes/session/utils.ts
Labels: enhancement, size/m

#2090 refactor(core): split sign in experience lib
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/lib/sign-in-experience/index.test.ts
  packages/core/src/lib/sign-in-experience/index.ts
  packages/core/src/lib/sign-in-experience/sign-in-methods.test.ts
  packages/core/src/lib/sign-in-experience/sign-in-methods.ts
  packages/core/src/lib/sign-in-experience/sign-up.test.ts
  packages/core/src/lib/sign-in-experience/sign-up.ts
  packages/core/src/routes/sign-in-experience.test.ts
  packages/core/src/routes/sign-in-experience.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko-kr/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
Labels: enhancement, size/l

#2117 ci: fix eslint report script
  merge-eslint-reports.js
Labels: size/xs

#2110 refactor(console): fix language editor styles
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/AddLanguageSelector.module.scss
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/AddLanguageSelector.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/EditSection.module.scss
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageEditor.module.scss
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageItem.module.scss
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageNav.module.scss
  packages/console/src/pages/SignInExperience/components/ManageLanguageModal/index.module.scss
Labels: enhancement, size/s

#2088 refactor(console): extract manage language components
  packages/console/src/pages/SignInExperience/components/LanguagesForm.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/AddLanguageSelector.module.scss
  packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/AddLanguageSelector.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/EditSection.module.scss
  packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/EditSection.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/LanguageDetails.module.scss
  packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/LanguageDetails.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/LanguageItem.module.scss
  packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/LanguageItem.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/LanguageNav.module.scss
  packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/LanguageNav.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/index.module.scss
  packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/index.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/use-language-editor-context.ts
  packages/console/src/pages/SignInExperience/components/ManageLanguage/ManageLanguageButton.module.scss
  packages/console/src/pages/SignInExperience/components/ManageLanguage/ManageLanguageButton.tsx
  packages/console/src/pages/SignInExperience/components/index.module.scss
Labels: enhancement, size/m

#2087 chore(ui): update content
  packages/phrases-ui/src/locales/en.ts
  packages/phrases-ui/src/locales/fr.ts
  packages/phrases-ui/src/locales/ko-kr.ts
  packages/phrases-ui/src/locales/pt-pt.ts
  packages/phrases-ui/src/locales/tr-tr.ts
  packages/phrases-ui/src/locales/zh-cn.ts
  packages/ui/src/containers/ResetPassword/index.test.tsx
  packages/ui/src/containers/ResetPassword/index.tsx
Labels: chore, size/s

#2111 refactor: remove deprecated `fixedLanguage` property from `LanguageInfo`
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/lib/sign-in-experience.test.ts
  packages/core/src/routes/custom-phrase.test.ts
  packages/core/src/routes/phrase.content-language.test.ts
  packages/core/src/routes/phrase.test.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/seeds/sign-in-experience.ts
  packages/ui/src/__mocks__/logto.tsx
Labels: enhancement, size/s

#2122 refactor(console): set language name font style to font-body-medium
  packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/LanguageItem.module.scss
Labels: enhancement, size/xs

#2115 refactor(demo-app): improve sign-out button in demo-app
  packages/demo-app/src/App.module.scss
  packages/demo-app/src/App.tsx
Labels: enhancement, size/s

#2114 feat(core): validate sign in
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/lib/sign-in-experience/index.ts
  packages/core/src/lib/sign-in-experience/sign-in.test.ts
  packages/core/src/lib/sign-in-experience/sign-in.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko-kr/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
Labels: feature, size/l

#2119 feat(cli): add connector command
  packages/cli/package.json
  packages/cli/src/commands/connector/add.ts
  packages/cli/src/commands/connector/index.ts
  packages/cli/src/commands/connector/utils.ts
  packages/cli/src/index.ts
  pnpm-lock.yaml
Labels: feature, size/m

#2121 refactor: remove connector commands in core
  packages/cli/package.json
  packages/cli/src/commands/connector/utils.ts
  packages/cli/src/commands/database/alteration.ts
  packages/cli/src/constants.ts
  packages/core/package.json
  packages/core/src/cli/add-connector.ts
  packages/core/src/cli/add-official-connectors.ts
  packages/core/src/connectors/add-connectors.ts
  packages/core/src/connectors/index.ts
  packages/core/src/connectors/types.ts
  packages/core/src/env-set/add-connectors.ts
  packages/core/src/env-set/index.ts
  packages/shared/package.json
  packages/shared/src/utils/find-package.ts
  packages/shared/src/utils/index.ts
  pnpm-lock.yaml
Labels: enhancement, size/m

#2124 refactor(core): remove parameters
  .gitpod.yml
  packages/core/.gitignore
  packages/core/package.json
  packages/core/src/env-set/dot-env.ts
  packages/core/src/env-set/parameters.ts
  packages/core/src/index.ts
  pnpm-lock.yaml
Labels: enhancement, size/s

#2072 fix(console): remove connector id and prevent text overflow
  packages/console/src/components/Tooltip/index.module.scss
  packages/console/src/pages/Connectors/components/CreateForm/index.module.scss
  packages/console/src/pages/Connectors/components/CreateForm/index.tsx
  packages/console/src/scss/_underscore.scss
  packages/ui/src/components/BrandingHeader/index.module.scss
  packages/ui/src/scss/_underscore.scss
Labels: bugfix, size/s

#2126 refactor(console): stick the language details table header to the top
  packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/LanguageDetails.module.scss
Labels: enhancement, size/xs

#2129 style(console): update font style of language item
  packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/LanguageItem.module.scss
Labels: size/xs

#2133 refactor: update default button border color
  packages/console/src/components/Button/index.module.scss
  packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/AddLanguageSelector.module.scss
  packages/demo-app/src/App.module.scss
  packages/ui/src/components/Button/index.module.scss
Labels: enhancement, size/xs

#2116 fix(console): save generated password in session storage
  packages/console/src/consts/index.ts
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/pages/Users/components/CreateForm/index.tsx
  packages/console/src/pages/Users/index.tsx
Labels: bugfix, size/s

#2135 style(console): remove `margin-top` of the manage language button
  packages/console/src/pages/SignInExperience/components/ManageLanguage/ManageLanguageButton.module.scss
  packages/console/src/pages/SignInExperience/components/ManageLanguage/ManageLanguageButton.tsx
Labels: size/xs

#2125 refactor(console): add translations for the manage language feature
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/ko-kr/errors.ts
  packages/phrases/src/locales/ko-kr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/zh-cn/errors.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
Labels: enhancement, size/m

#2132 refactor(cli): add official connectors during init
  packages/cli/src/commands/connector/add.ts
  packages/cli/src/commands/connector/utils.ts
  packages/cli/src/commands/install/index.ts
  packages/cli/src/commands/install/utils.ts
Labels: enhancement, size/m

#2139 refactor(cli): update install, alteration, and version command
  packages/cli/src/commands/database/alteration.test.ts
  packages/cli/src/commands/database/alteration/index.test.ts
  packages/cli/src/commands/database/alteration/index.ts
  packages/cli/src/commands/database/alteration/type.ts
  packages/cli/src/commands/database/alteration/version.ts
  packages/cli/src/commands/install/index.ts
  packages/cli/src/index.ts
  packages/cli/src/package.json
  packages/cli/src/utilities.ts
Labels: enhancement, size/l

#2134 refactor(console): create languages immediately on languages added in the editor
  packages/console/src/hooks/use-ui-languages.ts
  packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/LanguageDetails.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/LanguageNav.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/index.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/use-language-editor-context.ts
Labels: enhancement, size/m

#2127 refactor(console): update icon buttons in the language editor
  packages/console/src/assets/images/clear.svg
  packages/console/src/components/IconButton/index.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/LanguageDetails.module.scss
  packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/LanguageDetails.tsx
Labels: enhancement, size/s

#2138 refactor(console): update table styles
  packages/console/src/components/CopyToClipboard/index.module.scss
  packages/console/src/scss/normalized.scss
  packages/console/src/scss/table.module.scss
Labels: enhancement, size/s

#2137 refactor(ui): refactor terms of use modals
  packages/ui/package.json
  packages/ui/src/components/ConfirmModal/IframeConfirmModal.module.scss
  packages/ui/src/components/ConfirmModal/IframeConfirmModal.tsx
  packages/ui/src/components/ConfirmModal/MobileModal.module.scss
  packages/ui/src/components/ConfirmModal/index.tsx
  packages/ui/src/components/ConfirmModal/modalPromisify/index.test.tsx
  packages/ui/src/components/ConfirmModal/modalPromisify/index.tsx
  packages/ui/src/containers/ConfirmModalProvider/index.tsx
  packages/ui/src/containers/TermsOfUse/IframeConfirmModalContent/index.module.scss
  packages/ui/src/containers/TermsOfUse/IframeConfirmModalContent/index.tsx
  packages/ui/src/containers/TermsOfUse/TermsOfUseConfirmModal/index.test.tsx
  packages/ui/src/containers/TermsOfUse/TermsOfUseConfirmModal/index.tsx
  packages/ui/src/containers/TermsOfUse/TermsOfUseConfirmModalContent/index.tsx
  packages/ui/src/containers/TermsOfUse/TermsOfUseIframeModal/index.test.tsx
  packages/ui/src/containers/TermsOfUse/TermsOfUseIframeModal/index.tsx
  packages/ui/src/containers/TermsOfUse/index.tsx
  packages/ui/src/containers/UsernameSignIn/index.test.tsx
  packages/ui/src/hooks/use-confirm-modal.ts
  packages/ui/src/hooks/use-terms.ts
  packages/ui/src/utils/promisify.test.ts
  packages/ui/src/utils/promisify.ts
  pnpm-lock.yaml
Labels: enhancement, size/xl

#2142 refactor(core): refactor passwordless route
  packages/core/src/routes/session/forgot-password.test.ts
  packages/core/src/routes/session/forgot-password.ts
  packages/core/src/routes/session/middleware/passwordless-action.ts
  packages/core/src/routes/session/passwordless.test.ts
  packages/core/src/routes/session/passwordless.ts
  packages/core/src/routes/session/types.ts
  packages/core/src/routes/session/utils.ts
  packages/integration-tests/src/api/session.ts
  packages/integration-tests/tests/api/session.test.ts
Labels: enhancement, size/xl

#2154 ci: fix workflow env
  .github/workflows/release.yml
Labels: size/xs

#2150 chore: revert lerna version bump
  package.json
  packages/cli/package.json
  packages/console/package.json
  packages/core/package.json
  packages/create/package.json
  packages/demo-app/package.json
  packages/integration-tests/package.json
  packages/schemas/package.json
  packages/shared/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: chore, size/s

#2141 refactor(console): display full contents in language edit section
  packages/console/src/components/Textarea/index.module.scss
  packages/console/src/components/Textarea/index.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/EditSection.module.scss
  packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/EditSection.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/LanguageDetails.module.scss
Labels: enhancement, size/s

#2144 refactor(console,phrases): update the language editor phrases
  packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/LanguageDetails.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/ko-kr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
Labels: enhancement, size/s

#2146 refactor(console): support text button in the `Button` component
  packages/console/src/components/Alert/index.tsx
  packages/console/src/components/Button/index.module.scss
  packages/console/src/components/Button/index.tsx
  packages/console/src/components/MultiTextInput/index.tsx
  packages/console/src/components/Search/index.tsx
  packages/console/src/components/TextButton/index.module.scss
  packages/console/src/pages/Applications/components/GuideHeader/index.tsx
  packages/console/src/pages/GetStarted/index.module.scss
  packages/console/src/pages/GetStarted/index.tsx
  packages/console/src/pages/SignInExperience/components/ColorForm.tsx
  packages/console/src/pages/SignInExperience/components/GuideModal.tsx
  packages/console/src/pages/SignInExperience/components/LanguagesForm.tsx
  packages/console/src/pages/SignInExperience/components/ManageLanguage/ManageLanguageButton.tsx
  packages/console/src/pages/SignInExperience/components/index.module.scss
  packages/console/src/pages/UserDetails/components/UserConnectors.tsx
Labels: enhancement, size/m

#2148 chore: update error messages
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko-kr/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
  packages/ui/src/containers/ResetPassword/index.tsx
Labels: chore, size/s

#2147 style(console): fix clear button size to 16x16
  packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/LanguageDetails.module.scss
  packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/LanguageDetails.tsx
Labels: size/xs

#2153 chore: upgrade Silverhand configs
  packages/cli/package.json
  packages/console/package.json
  packages/console/src/components/ApplicationName/index.tsx
  packages/console/src/components/UserName/index.tsx
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/pages/Users/index.tsx
  packages/core/package.json
  packages/core/src/lib/passcode.ts
  packages/core/src/middleware/koa-auth.ts
  packages/core/src/middleware/koa-connector-error-handler.ts
  packages/core/src/middleware/koa-oidc-error-handler.ts
  packages/core/src/middleware/koa-pagination.ts
  packages/core/src/utils/test-utils.ts
  packages/core/src/utils/translation.ts
  packages/core/src/utils/zod.ts
  packages/demo-app/package.json
  packages/integration-tests/package.json
  packages/phrases-ui/package.json
  packages/phrases/package.json
  packages/schemas/package.json
  packages/schemas/src/gen/index.ts
  packages/schemas/src/gen/schema.ts
  packages/schemas/src/gen/utils.ts
  packages/shared/package.json
  packages/shared/src/utils/find-package.ts
  packages/ui/package.json
  packages/ui/src/components/Input/index.tsx
  packages/ui/src/containers/CreateAccount/index.tsx
  packages/ui/src/containers/ResetPassword/index.tsx
  pnpm-lock.yaml
Labels: chore, size/m

#2128 feat(core): update sie
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/routes/sign-in-experience.test.ts
  packages/core/src/routes/sign-in-experience.ts
Labels: feature, size/s

#2149 refactor(ui): refactor passwordless flow
  packages/core/src/routes/session/middleware/passwordless-action.ts
  packages/phrases-ui/src/locales/en.ts
  packages/phrases-ui/src/locales/fr.ts
  packages/phrases-ui/src/locales/ko-kr.ts
  packages/phrases-ui/src/locales/pt-pt.ts
  packages/phrases-ui/src/locales/tr-tr.ts
  packages/phrases-ui/src/locales/zh-cn.ts
  packages/ui/src/apis/forgot-password.ts
  packages/ui/src/apis/index.test.ts
  packages/ui/src/apis/register.ts
  packages/ui/src/apis/sign-in.ts
  packages/ui/src/containers/PasscodeValidation/index.tsx
  packages/ui/src/containers/PasscodeValidation/use-forgot-password-with-email-error-handler.ts
  packages/ui/src/containers/PasscodeValidation/use-forgot-password-with-sms-error-handler.ts
  packages/ui/src/containers/PasscodeValidation/use-passcode-validation-error-handler.ts
  packages/ui/src/containers/PasscodeValidation/use-register-with-sms-error-handler.ts
  packages/ui/src/containers/PasscodeValidation/use-sign-in-with-email-error-handler.ts
  packages/ui/src/containers/PasscodeValidation/use-sign-in-with-sms-error-handler.ts
  packages/ui/src/containers/PasscodeValidation/user-register-with-email-error-handler.ts
  packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
  packages/ui/src/containers/Passwordless/PasswordlessConfirmModal.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
Labels: enhancement, size/xl

#2159 style(console): fix text button hover style
  packages/console/src/components/Button/index.module.scss
Labels: size/xs

#2161 feat(cli): list & remove connectors
  packages/cli/src/commands/connector/add.ts
  packages/cli/src/commands/connector/index.ts
  packages/cli/src/commands/connector/list.ts
  packages/cli/src/commands/connector/remove.ts
  packages/cli/src/commands/connector/utils.ts
Labels: feature, size/m

#2162 feat(cli)!: add `download-url` option for install
  .github/workflows/integration-test.yml
  .gitpod.yml
  Dockerfile
  package.json
  packages/cli/src/commands/connector/index.ts
  packages/cli/src/commands/install/index.ts
  packages/cli/src/commands/install/utils.ts
  packages/core/package.json
  pnpm-lock.yaml
Labels: feature, size/s

#2168 ci: upgrade node pnpm run steps
  .github/workflows/commitlint.yml
  .github/workflows/main.yml
  .github/workflows/master-codecov-report.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
  .github/workflows/upload-annotations.yml
Labels: size/s

#2169 style(console): use small size button for clear button
  packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/LanguageDetails.tsx
Labels: size/xs

#2170 chore: remove lerna
  .github/workflows/integration-test.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
  .github/workflows/upload-annotations.yml
  .gitpod.yml
  .husky/pre-commit
  Dockerfile
  package.json
  pnpm-lock.yaml
Labels: chore, size/s

#2172 refactor(cli): add skip when exists option
  packages/cli/src/commands/database/seed/index.ts
  packages/cli/src/queries/logto-config.ts
Labels: enhancement, size/s

#2173 ci: fix publish script
  .github/workflows/publish.yml
Labels: size/xs

#2175 fix(cli): `chooseAlterationsByVersion` should contain the last `next` version alteration script
  packages/cli/src/commands/database/alteration/index.test.ts
  packages/cli/src/commands/database/alteration/version.ts
Labels: bugfix, size/xs

#2177 refactor(cli): supports `latest` version for db alteration
  packages/cli/src/commands/database/alteration/version.ts
Labels: enhancement, size/xs

#2178 fix(schemas): field name in sie db data type should be camel-case
  packages/core/src/cli/alteration.ts
  packages/schemas/alterations/next-1665300135-sign-in-sign-up.ts
Labels: bugfix, size/xs

#2174 chore: fix gitpod
  .gitpod.yml
  package.json
Labels: chore, size/s

#2176 refactor(cli): update config command
  packages/cli/src/commands/database/config.ts
  packages/cli/src/commands/database/index.ts
Labels: enhancement, size/s

#2180 fix(cli): fix skip-when-exists option
  packages/cli/src/commands/database/seed/index.ts
  packages/cli/src/queries/logto-config.ts
Labels: bugfix, size/s

#2160 fix(console): responsive modal items layout
  packages/console/src/components/RadioGroup/Radio.tsx
  packages/console/src/components/RadioGroup/index.module.scss
  packages/console/src/pages/Applications/components/CreateForm/index.module.scss
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/Applications/components/SdkSelector/index.module.scss
  packages/console/src/pages/Applications/components/TypeDescription/index.tsx
  packages/console/src/pages/Connectors/components/CreateForm/index.module.scss
  packages/console/src/pages/Connectors/components/CreateForm/index.tsx
  packages/console/src/scss/_dimensions.scss
Labels: bugfix, size/l

#2186 fix(ui): revert color token changes in ui as it uses different design system
  packages/ui/src/components/Button/IconButton.module.scss
  packages/ui/src/components/Checkbox/index.module.scss
  packages/ui/src/components/Divider/index.module.scss
  packages/ui/src/components/Drawer/index.module.scss
  packages/ui/src/components/Input/index.module.scss
  packages/ui/src/components/Input/phoneInput.module.scss
  packages/ui/src/components/Notification/index.module.scss
  packages/ui/src/components/Passcode/index.module.scss
  packages/ui/src/components/TermsOfUse/index.module.scss
  packages/ui/src/components/TextLink/index.module.scss
  packages/ui/src/containers/PasscodeValidation/index.module.scss
  packages/ui/src/containers/SocialLanding/index.module.scss
  packages/ui/src/pages/ForgotPassword/index.module.scss
  packages/ui/src/pages/Passcode/index.module.scss
  packages/ui/src/scss/_underscore.scss
Labels: bugfix, size/s

#2187 style(console): improve language selector dropdown styles
  packages/console/src/scss/normalized.scss
Labels: size/xs

#2188 refactor(console): avoid jumping when the language item is visible
  packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/LanguageItem.tsx
Labels: enhancement, size/xs

#2190 fix(console): checkbox styles
  packages/console/src/assets/images/check-box-selected-dark.svg
  packages/console/src/assets/images/check-box-unselected-dark.svg
  packages/console/src/assets/images/check-box-unselected-disabled-dark.svg
  packages/console/src/assets/images/check-box-unselected-disabled.svg
  packages/console/src/assets/images/check-box-unselected.svg
  packages/console/src/components/Checkbox/Icon.tsx
Labels: bugfix, size/s

#2183 fix: alteration script in dev
  package.json
  packages/cli/package.json
  packages/cli/src/commands/database/alteration/index.test.ts
  packages/cli/src/commands/database/alteration/index.ts
  packages/schemas/.gitignore
  packages/schemas/package.json
  packages/schemas/tsconfig.build.alterations.json
Labels: bugfix, size/s

#2192 fix: add publish config for public packages
  packages/cli/package.json
  packages/create/package.json
Labels: bugfix, size/xs

#2184 ci: add docker build to main workflow
  .github/workflows/main.yml
  Dockerfile
  packages/cli/src/commands/connector/utils.ts
  packages/cli/src/commands/database/alteration/version.ts
  packages/cli/src/commands/install/utils.ts
  packages/cli/src/utilities.ts
Labels: size/m

#2196 chore: bump `@logto/language-kit` to `v1.0.0-beta.19`
  packages/console/package.json
  packages/core/package.json
  packages/demo-app/package.json
  packages/phrases-ui/package.json
  packages/phrases/package.json
  packages/schemas/package.json
  pnpm-lock.yaml
Labels: chore, size/s

#2199 chore: update docker compose file
  docker-compose.yml
Labels: chore, size/xs

#2191 feat(console): sie sign up form
  packages/console/package.json
  packages/console/src/pages/SignInExperience/components/ConnectorSetupWarning.tsx
  packages/console/src/pages/SignInExperience/components/SignInMethodsForm.tsx
  packages/console/src/pages/SignInExperience/components/index.module.scss
  packages/console/src/pages/SignInExperience/index.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/ConnectorSetupWarning.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/SignUpForm.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/index.module.scss
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/ko-kr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#2200 fix: make packages public
  packages/phrases-ui/package.json
  packages/phrases/package.json
  packages/schemas/package.json
  packages/shared/package.json
Labels: bugfix, size/s

#2198 refactor: require database name in URL
  .github/workflows/integration-test.yml
  packages/cli/src/database.ts
  packages/core/src/env-set/create-pool-by-env.ts
  packages/schemas/package.json
Labels: enhancement, size/s

#2202 fix: handle versioning when no `next-*.ts` found
  packages/schemas/update-next.sh
Labels: bugfix, size/xs

#2203 refactor(console): remove deprecated `languageKeys`
  packages/console/src/hooks/use-user-preferences.ts
Labels: enhancement, size/xs

#2204 fix(console): show i18n content of "errors.unknown_server_error"
  packages/console/src/hooks/use-api.ts
Labels: bugfix, size/xs

#2207 chore: update content
  README.md
  docker-compose.yml
  install.js
  lerna.json
Labels: chore, size/s

#2205 refactor: use hook for toastError in order to get type support
  packages/console/src/hooks/use-api.ts
Labels: enhancement, size/s

#2208 ci: fix envrionment variable in docker compose
  docker-compose.yml
Labels: size/xs

#2209 chore: update contributing
  .github/CONTRIBUTING.md
  packages/core/src/env-set/check-alteration-state.ts
  packages/schemas/alterations/README.md
Labels: chore, size/s

#2194 feat(core): guard sign up methods
  packages/core/src/routes/session/passwordless.test.ts
  packages/core/src/routes/session/passwordless.ts
  packages/core/src/routes/session/username-password.test.ts
  packages/core/src/routes/session/username-password.ts
  packages/integration-tests/src/helpers.ts
  packages/integration-tests/tests/api/session.test.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko-kr/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
Labels: feature, size/m

#2039 refactor(core,phrases,schemas): decouple passcode verification
  packages/core/src/routes/session/consts.ts
  packages/core/src/routes/session/forgot-password.test.ts
  packages/core/src/routes/session/forgot-password.ts
  packages/core/src/routes/session/middleware/passwordless-action.ts
  packages/core/src/routes/session/passwordless.test.ts
  packages/core/src/routes/session/passwordless.ts
  packages/core/src/routes/session/types.ts
  packages/core/src/routes/session/utils.ts
  packages/integration-tests/src/api/session.ts
  packages/phrases-ui/src/locales/en.ts
  packages/phrases-ui/src/locales/fr.ts
  packages/phrases-ui/src/locales/ko-kr.ts
  packages/phrases-ui/src/locales/pt-pt.ts
  packages/phrases-ui/src/locales/tr-tr.ts
  packages/phrases-ui/src/locales/zh-cn.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko-kr/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
  packages/ui/src/apis/forgot-password.ts
  packages/ui/src/apis/index.test.ts
  packages/ui/src/apis/register.ts
  packages/ui/src/apis/sign-in.ts
  packages/ui/src/containers/PasscodeValidation/index.tsx
  packages/ui/src/containers/PasscodeValidation/use-forgot-password-with-email-error-handler.ts
  packages/ui/src/containers/PasscodeValidation/use-forgot-password-with-sms-error-handler.ts
  packages/ui/src/containers/PasscodeValidation/use-passcode-validation-error-handler.ts
  packages/ui/src/containers/PasscodeValidation/use-register-with-sms-error-handler.ts
  packages/ui/src/containers/PasscodeValidation/use-sign-in-with-email-error-handler.ts
  packages/ui/src/containers/PasscodeValidation/use-sign-in-with-sms-error-handler.ts
  packages/ui/src/containers/PasscodeValidation/user-register-with-email-error-handler.ts
  packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
  packages/ui/src/containers/Passwordless/PasswordlessConfirmModal.tsx
  packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
  packages/ui/src/containers/ResetPassword/index.tsx
Labels: enhancement, size/xl

#2185 style(ui): update branding color token name
  packages/ui/src/containers/AppContent/index.module.scss
  packages/ui/src/hooks/use-color-theme.ts
  packages/ui/src/scss/_desktop.scss
  packages/ui/src/scss/_mobile.scss
Labels: size/s

#2213 feat(core): limit sign in method
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/routes/session/passwordless.test.ts
  packages/core/src/routes/session/passwordless.ts
  packages/core/src/routes/session/username-password.test.ts
  packages/core/src/routes/session/username-password.ts
  packages/core/src/routes/sign-in-experience.test.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko-kr/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
  packages/schemas/src/seeds/sign-in-experience.ts
Labels: feature, size/m

#2218 chore: add renovate monorepo rules
  renovate.json
Labels: chore, size/s

#2219 fix(ui): fix text overflow issue
  packages/ui/src/components/Button/index.module.scss
  packages/ui/src/components/Notification/index.module.scss
  packages/ui/src/containers/AppContent/index.module.scss
Labels: bugfix, size/xs

#2214 style(ui): add new color theme file
  packages/ui/src/scss/_colors.scss
Labels: size/m

#2223 fix(console): fix ac chunky preview experience
  packages/ui/src/hooks/use-preview.ts
Labels: bugfix, size/xs

#2222 fix(core): let ac SIE language load from default SIE language settings
  packages/core/src/routes/well-known.test.ts
  packages/core/src/routes/well-known.ts
Labels: bugfix, size/s

#2215 chore: introduce changesets
  .changeset/README.md
  .changeset/config.json
  .github/workflows/release.yml
  package.json
  packages/cli/package.json
  packages/console/package.json
  packages/core/package.json
  packages/create/package.json
  packages/demo-app/package.json
  packages/integration-tests/package.json
  packages/schemas/package.json
  packages/shared/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: chore, size/m

#2230 fix(ui): fix prefiew render bug
  packages/ui/src/hooks/use-preview.ts
Labels: bugfix, size/xs

#2243 feat(console): show userinfo endpoint information
  packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx
Labels: feature, size/xs

#2236 ci: update changeset
  .changeset/README.md
  .changeset/config.json
  .github/CODEOWNERS
  .github/workflows/release.yml
Labels: size/s

#2232 refactor: update language kit
  packages/cli/package.json
  packages/console/package.json
  packages/console/src/pages/Connectors/components/Guide/index.tsx
  packages/console/src/pages/UserDetails/components/UserConnectors.tsx
  packages/core/package.json
  packages/core/src/__mocks__/connector.ts
  packages/demo-app/package.json
  packages/phrases-ui/package.json
  packages/phrases-ui/src/index.ts
  packages/phrases-ui/src/locales/ko.ts
  packages/phrases/package.json
  packages/phrases/src/index.ts
  packages/phrases/src/locales/ko/errors.ts
  packages/phrases/src/locales/ko/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/applications.ts
  packages/phrases/src/locales/ko/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/connectors.ts
  packages/phrases/src/locales/ko/translation/admin-console/contact.ts
  packages/phrases/src/locales/ko/translation/admin-console/dashboard.ts
  packages/phrases/src/locales/ko/translation/admin-console/errors.ts
  packages/phrases/src/locales/ko/translation/admin-console/general.ts
  packages/phrases/src/locales/ko/translation/admin-console/get-started.ts
  packages/phrases/src/locales/ko/translation/admin-console/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/log-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/logs.ts
  packages/phrases/src/locales/ko/translation/admin-console/session-expired.ts
  packages/phrases/src/locales/ko/translation/admin-console/settings.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/ko/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/ko/translation/admin-console/tabs.ts
  packages/phrases/src/locales/ko/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/users.ts
  packages/phrases/src/locales/ko/translation/admin-console/welcome.ts
  packages/phrases/src/locales/ko/translation/demo-app.ts
  packages/phrases/src/locales/ko/translation/index.ts
  packages/schemas/package.json
  packages/ui/package.json
  packages/ui/src/__mocks__/logto.tsx
  packages/ui/src/containers/SocialSignIn/SocialSignInDropdown/index.tsx
  pnpm-lock.yaml
Labels: enhancement, size/s

#2244 chore: update renovate.json
  renovate.json
Labels: chore, size/s

#2228 style(ui): add new font styling
  packages/ui/src/scss/_fonts.scss
Labels: size/s

#2240 refactor(ui): refactor ui style system
  packages/ui/src/App.module.scss
  packages/ui/src/components/BrandingHeader/index.module.scss
  packages/ui/src/components/Button/IconButton.module.scss
  packages/ui/src/components/Button/SocialIconButton.module.scss
  packages/ui/src/components/Button/index.module.scss
  packages/ui/src/components/Checkbox/index.module.scss
  packages/ui/src/components/ConfirmModal/Acmodal.module.scss
  packages/ui/src/components/ConfirmModal/MobileModal.module.scss
  packages/ui/src/components/Divider/index.module.scss
  packages/ui/src/components/Drawer/index.module.scss
  packages/ui/src/components/Dropdown/DropdownItem.module.scss
  packages/ui/src/components/Dropdown/index.module.scss
  packages/ui/src/components/ErrorMessage/index.module.scss
  packages/ui/src/components/Input/index.module.scss
  packages/ui/src/components/Input/phoneInput.module.scss
  packages/ui/src/components/LoadingLayer/index.module.scss
  packages/ui/src/components/NavBar/index.module.scss
  packages/ui/src/components/Notification/index.module.scss
  packages/ui/src/components/Passcode/index.module.scss
  packages/ui/src/components/TermsOfUse/index.module.scss
  packages/ui/src/components/TextLink/index.module.scss
  packages/ui/src/components/Toast/index.module.scss
  packages/ui/src/containers/AppContent/index.module.scss
  packages/ui/src/containers/AppContent/index.tsx
  packages/ui/src/containers/PasscodeValidation/index.module.scss
  packages/ui/src/containers/PasscodeValidation/index.tsx
  packages/ui/src/containers/SignInMethodsLink/index.module.scss
  packages/ui/src/containers/SocialLanding/index.module.scss
  packages/ui/src/containers/SocialSignIn/SocialSignInIconList/index.module.scss
  packages/ui/src/hooks/use-color-theme.ts
  packages/ui/src/hooks/use-preview.ts
  packages/ui/src/pages/ErrorPage/index.module.scss
  packages/ui/src/pages/ForgotPassword/index.module.scss
  packages/ui/src/pages/Passcode/index.module.scss
  packages/ui/src/pages/Register/index.module.scss
  packages/ui/src/pages/ResetPassword/index.module.scss
  packages/ui/src/pages/SecondarySignIn/index.module.scss
  packages/ui/src/pages/SocialRegister/index.module.scss
  packages/ui/src/scss/_colors.scss
  packages/ui/src/scss/_desktop.scss
  packages/ui/src/scss/_mobile.scss
  packages/ui/src/scss/_underscore.scss
  packages/ui/src/scss/modal.module.scss
  packages/ui/src/scss/normalized.scss
Labels: enhancement, size/xl

#2229 feat(console): sie sign-in form
  packages/console/src/assets/images/switch-arrow.svg
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/ConnectorSetupWarning.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/SignInForm.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/SignUpForm.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/ConnectorSetupWarning.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/AddSignInMethodButton.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/SignInMethodItem.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/index.module.scss
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/index.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/types.ts
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/utilities.ts
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/constants.ts
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/index.module.scss
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
Labels: feature, size/xl

#2246 Merge branch master into feature/sie-v2
  packages/ui/src/App.module.scss
  packages/ui/src/components/BrandingHeader/index.module.scss
  packages/ui/src/components/Button/IconButton.module.scss
  packages/ui/src/components/Button/SocialIconButton.module.scss
  packages/ui/src/components/Button/index.module.scss
  packages/ui/src/components/Checkbox/index.module.scss
  packages/ui/src/components/ConfirmModal/Acmodal.module.scss
  packages/ui/src/components/ConfirmModal/MobileModal.module.scss
  packages/ui/src/components/Divider/index.module.scss
  packages/ui/src/components/Drawer/index.module.scss
  packages/ui/src/components/Dropdown/DropdownItem.module.scss
  packages/ui/src/components/Dropdown/index.module.scss
  packages/ui/src/components/ErrorMessage/index.module.scss
  packages/ui/src/components/Input/index.module.scss
  packages/ui/src/components/Input/phoneInput.module.scss
  packages/ui/src/components/LoadingLayer/index.module.scss
  packages/ui/src/components/NavBar/index.module.scss
  packages/ui/src/components/Notification/index.module.scss
  packages/ui/src/components/Passcode/index.module.scss
  packages/ui/src/components/TermsOfUse/index.module.scss
  packages/ui/src/components/TextLink/index.module.scss
  packages/ui/src/components/Toast/index.module.scss
  packages/ui/src/containers/AppContent/index.module.scss
  packages/ui/src/containers/AppContent/index.tsx
  packages/ui/src/containers/PasscodeValidation/index.module.scss
  packages/ui/src/containers/PasscodeValidation/index.tsx
  packages/ui/src/containers/SignInMethodsLink/index.module.scss
  packages/ui/src/containers/SocialLanding/index.module.scss
  packages/ui/src/containers/SocialSignIn/SocialSignInIconList/index.module.scss
  packages/ui/src/hooks/use-color-theme.ts
  packages/ui/src/hooks/use-preview.ts
  packages/ui/src/pages/ErrorPage/index.module.scss
  packages/ui/src/pages/ForgotPassword/index.module.scss
  packages/ui/src/pages/Passcode/index.module.scss
  packages/ui/src/pages/Register/index.module.scss
  packages/ui/src/pages/ResetPassword/index.module.scss
  packages/ui/src/pages/SecondarySignIn/index.module.scss
  packages/ui/src/pages/SocialRegister/index.module.scss
  packages/ui/src/scss/_colors.scss
  packages/ui/src/scss/_desktop.scss
  packages/ui/src/scss/_fonts.scss
  packages/ui/src/scss/_mobile.scss
  packages/ui/src/scss/_underscore.scss
  packages/ui/src/scss/modal.module.scss
  packages/ui/src/scss/normalized.scss
Labels: size/xl

#2242 fix(console): axis calculations in use-position hook
  packages/console/src/hooks/use-position.ts
Labels: bugfix, size/s

#2248 refactor(console): update enable create account phrases
  packages/console/src/pages/SignInExperience/components/AuthenticationForm.tsx
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
Labels: enhancement, size/s

#2249 refactor(console): connector setup warning
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/SignUpForm.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/ConnectorSetupWarning.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/index.tsx
Labels: enhancement, size/s

#2250 refactor(console): add sign in method button
  packages/console/src/components/ActionMenu/index.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/AddSignInMethodButton.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/index.module.scss
Labels: enhancement, size/s

#2252 refactor(core): rename phone signInMethod to sms
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/constants.ts
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/lib/sign-in-experience/sign-in.test.ts
  packages/core/src/lib/sign-in-experience/sign-in.ts
  packages/core/src/lib/sign-in-experience/sign-up.test.ts
  packages/core/src/lib/sign-in-experience/sign-up.ts
  packages/core/src/routes/session/middleware/passwordless-action.ts
  packages/core/src/routes/session/passwordless.test.ts
  packages/core/src/routes/session/username-password.test.ts
  packages/integration-tests/tests/api/session.test.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
  packages/schemas/alterations/next-1665300135-sign-in-sign-up.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/seeds/sign-in-experience.ts
  packages/ui/src/__mocks__/logto.tsx
Labels: enhancement, size/m

#2254 chore(phrases): update contents
  packages/phrases-ui/src/locales/zh-cn.ts
  packages/phrases/src/locales/zh-cn/errors.ts
Labels: chore, size/xs

#2257 feat(core): enable forgot password check
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/routes/sign-in-experience.test.ts
  packages/core/src/routes/sign-in-experience.ts
  packages/schemas/src/seeds/sign-in-experience.ts
  packages/ui/src/__mocks__/logto.tsx
Labels: feature, size/s

#2261 fix(ui): fix tab key not working bug
  packages/ui/src/utils/a11y.ts
Labels: bugfix, size/xs

#2260 style(ui): remove outline button style
  packages/ui/src/components/Button/index.module.scss
  packages/ui/src/components/Button/index.tsx
  packages/ui/src/components/ConfirmModal/AcModal.tsx
Labels: size/s

#2256 style(ui): remove autofill styling
  packages/ui/src/components/Input/index.module.scss
Labels: size/xs

#2263 refactor(core): rename username password routes
  packages/core/src/lib/user.ts
  packages/core/src/routes/session/index.ts
  packages/core/src/routes/session/password.test.ts
  packages/core/src/routes/session/password.ts
  packages/core/src/routes/session/utils.ts
  packages/integration-tests/src/api/session.ts
  packages/ui/src/apis/index.test.ts
  packages/ui/src/apis/register.ts
  packages/ui/src/apis/sign-in.ts
Labels: enhancement, size/m

#2264 refactor(ui): refactor SIE schema
  packages/ui/src/__mocks__/logto.tsx
  packages/ui/src/apis/settings.ts
  packages/ui/src/components/Button/SocialIconButton.module.scss
  packages/ui/src/components/Button/SocialIconButton.tsx
  packages/ui/src/components/Drawer/index.module.scss
  packages/ui/src/components/Drawer/index.test.tsx
  packages/ui/src/components/Drawer/index.tsx
  packages/ui/src/components/Dropdown/DropdownItem.module.scss
  packages/ui/src/components/Dropdown/DropdownItem.tsx
  packages/ui/src/components/Dropdown/index.module.scss
  packages/ui/src/components/Dropdown/index.tsx
  packages/ui/src/containers/Passwordless/PasswordlessSwitch.test.tsx
  packages/ui/src/containers/Passwordless/PasswordlessSwitch.tsx
  packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn/index.test.tsx
  packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn/index.tsx
  packages/ui/src/containers/SocialSignIn/SocialSignInDropdown/index.module.scss
  packages/ui/src/containers/SocialSignIn/SocialSignInDropdown/index.test.tsx
  packages/ui/src/containers/SocialSignIn/SocialSignInDropdown/index.tsx
  packages/ui/src/containers/SocialSignIn/SocialSignInIconList/index.module.scss
  packages/ui/src/containers/SocialSignIn/SocialSignInIconList/index.tsx
  packages/ui/src/containers/SocialSignIn/SocialSignInPopUp/index.tsx
  packages/ui/src/containers/SocialSignIn/index.module.scss
  packages/ui/src/containers/SocialSignIn/index.ts
  packages/ui/src/containers/SocialSignIn/index.tsx
  packages/ui/src/hooks/use-bind-social.ts
  packages/ui/src/hooks/use-preview.ts
  packages/ui/src/pages/ForgotPassword/index.tsx
  packages/ui/src/pages/SignIn/MainForm.tsx
  packages/ui/src/pages/SignIn/index.test.tsx
  packages/ui/src/pages/SignIn/index.tsx
  packages/ui/src/pages/SignIn/registry.tsx
  packages/ui/src/types/guard.ts
  packages/ui/src/types/index.ts
  packages/ui/src/utils/a11y.ts
  packages/ui/src/utils/sign-in-experience.test.ts
  packages/ui/src/utils/sign-in-experience.ts
Labels: enhancement, size/xl

#2259 fix(ui): fix apple logo
  packages/ui/src/containers/SocialSignIn/SocialSignInIconList/index.tsx
Labels: bugfix, size/xs

#2268 fix(console): useApi hook should not cause component re-render
  packages/console/src/hooks/use-api.ts
Labels: bugfix, size/s

#2266 feat(core): password sign in with phone or email
  packages/core/src/routes/session/password.test.ts
  packages/core/src/routes/session/password.ts
  packages/core/src/routes/session/utils.test.ts
  packages/core/src/routes/session/utils.ts
  packages/integration-tests/src/helpers.ts
  packages/integration-tests/tests/api/session.test.ts
  packages/schemas/src/types/log.ts
Labels: feature, size/l

#2251 feat(console): add social connectors on the sie page
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/SignInForm.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/SocialSignInForm.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SocialConnectorEditBox/AddButton.module.scss
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SocialConnectorEditBox/AddButton.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SocialConnectorEditBox/SelectedConnectorItem.module.scss
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SocialConnectorEditBox/SelectedConnectorItem.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SocialConnectorEditBox/index.module.scss
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SocialConnectorEditBox/index.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/index.module.scss
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
Labels: feature, size/l
