Repository logto-io/logto, pull requests merged in 2023-07, with the labels that each got.

#4101 fix(core): block logto email connector (create and enter detail page)
  packages/core/src/utils/connectors/index.ts
Labels: bugfix, size/s

#4088 fix(console): avoid connector custom config fields conflict with reserved fields
  packages/console/src/components/ConnectorForm/ConfigForm/ConfigFormFields/index.tsx
  packages/console/src/components/ConnectorForm/ConfigForm/index.tsx
  packages/console/src/hooks/use-connector-form-config-parser.tsx
  packages/console/src/pages/ConnectorDetails/ConnectorContent/index.tsx
  packages/console/src/pages/Connectors/Guide/index.tsx
  packages/console/src/types/connector.ts
  packages/console/src/utils/connector-form.ts
Labels: bugfix, size/s

#4084 chore(phrases): add logto built-in connector phrases
  packages/phrases/src/locales/de/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/en/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/es/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/it/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/connector-details.ts
Labels: chore, size/l

#4103 refactor: cloud cleanup
  .github/CODEOWNERS
  .github/workflows/clean-up-images.yml
  .github/workflows/integration-test.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
  Dockerfile.cloud
  LICENSE
  package.json
  packages/cloud/CHANGELOG.md
  packages/cloud/LICENSE
  packages/cloud/jest.config.js
  packages/cloud/jest.setup.js
  packages/cloud/nodemon.json
  packages/cloud/package.json
  packages/cloud/src/env-set/index.ts
  packages/cloud/src/index.ts
  packages/cloud/src/libraries/services.ts
  packages/cloud/src/libraries/tenants.ts
  packages/cloud/src/middleware/with-auth.ts
  packages/cloud/src/middleware/with-error-report.ts
  packages/cloud/src/middleware/with-http-proxy.ts
  packages/cloud/src/middleware/with-pathname.ts
  packages/cloud/src/middleware/with-security-headers.ts
  packages/cloud/src/middleware/with-spa.ts
  packages/cloud/src/queries/application.ts
  packages/cloud/src/queries/connector.ts
  packages/cloud/src/queries/index.ts
  packages/cloud/src/queries/roles.ts
  packages/cloud/src/queries/service-logs.ts
  packages/cloud/src/queries/system.ts
  packages/cloud/src/queries/tenants.ts
  packages/cloud/src/queries/users.ts
  packages/cloud/src/queries/utils.ts
  packages/cloud/src/routes-anonymous/index.test.ts
  packages/cloud/src/routes-anonymous/index.ts
  packages/cloud/src/routes/index.ts
  packages/cloud/src/routes/service.test.ts
  packages/cloud/src/routes/services.ts
  packages/cloud/src/routes/tenants.test.ts
  packages/cloud/src/routes/tenants.ts
  packages/cloud/src/test-utils/context.ts
  packages/cloud/src/test-utils/function.ts
  packages/cloud/src/test-utils/libraries.ts
  packages/cloud/src/utils/connector/index.ts
  packages/cloud/src/utils/connector/seed.ts
  packages/cloud/src/utils/connector/types.ts
  packages/cloud/src/utils/guard.ts
  packages/cloud/src/utils/postgres.ts
  packages/cloud/src/utils/query.ts
  packages/cloud/src/utils/tenant.ts
  packages/cloud/src/utils/url.ts
  packages/cloud/tsconfig.build.json
  packages/cloud/tsconfig.json
  packages/cloud/tsconfig.test.json
  packages/console/package.json
  packages/integration-tests/package.json
  packages/integration-tests/src/tests/api-cloud/tenant.test.ts
  packages/integration-tests/src/tests/ui-cloud/operations.ts
  packages/integration-tests/src/tests/ui-cloud/smoke.test.ts
  pnpm-lock.yaml
Labels: enhancement, size/xl

#4100 refactor(core): add extraInfo to connector GET APIs response
  packages/core/src/routes/connector/index.ts
  packages/core/src/utils/connectors/index.ts
Labels: enhancement, size/s

#4089 feat(console): implement email service connector details page
  packages/connectors/connector-logto-email/src/constant.ts
  packages/console/src/components/ConnectorTester/index.tsx
  packages/console/src/pages/ConnectorDetails/ConnectorContent/EmailServiceConnectorForm/index.module.scss
  packages/console/src/pages/ConnectorDetails/ConnectorContent/EmailServiceConnectorForm/index.tsx
  packages/console/src/pages/ConnectorDetails/ConnectorContent/index.tsx
Labels: feature, size/m

#4110 refactor(console): refactor custom connector form initialization
  packages/console/src/pages/ConnectorDetails/ConnectorContent/index.tsx
  packages/console/src/pages/Connectors/Guide/index.tsx
  packages/console/src/types/connector.ts
  packages/console/src/utils/connector-form.ts
Labels: enhancement, size/m

#4096 feat(connector): create SMSAero connector
  .changeset/dull-starfishes-scream.md
  packages/connectors/connector-smsaero/README.md
  packages/connectors/connector-smsaero/logo.svg
  packages/connectors/connector-smsaero/package.json
  packages/connectors/connector-smsaero/src/constant.ts
  packages/connectors/connector-smsaero/src/index.test.ts
  packages/connectors/connector-smsaero/src/index.ts
  packages/connectors/connector-smsaero/src/mock.ts
  packages/connectors/connector-smsaero/src/types.ts
  pnpm-lock.yaml
Labels: feature, size/l

#4107 feat(console): add usage info for the email service connector
  packages/console/src/assets/icons/email-sent.svg
  packages/console/src/pages/ConnectorDetails/EmailUsage/index.module.scss
  packages/console/src/pages/ConnectorDetails/EmailUsage/index.tsx
  packages/console/src/pages/ConnectorDetails/index.tsx
Labels: feature, size/s

#4115 refactor(schemas): sync cloud m2m credential to logto config
  packages/schemas/src/seeds/logto-config.ts
  packages/schemas/src/types/logto-config.ts
Labels: enhancement, size/s

#4109 refactor(core,schemas,cli): save cloud service m2m app credentials
  packages/cli/src/commands/database/seed/tables.ts
  packages/core/src/env-set/index.ts
  packages/core/src/libraries/logto-config.ts
  packages/core/src/queries/logto-config.ts
  packages/core/src/tenants/Libraries.ts
  packages/core/src/utils/endpoint.ts
  packages/schemas/alterations/next-1688375200-sync-cloud-m2m-to-logto-config.ts
  packages/schemas/src/seeds/logto-config.ts
Labels: enhancement, size/m

#4108 feat(console): create email service connector
  packages/console/src/components/CreateConnectorForm/PlatformSelector/index.module.scss
  packages/console/src/components/CreateConnectorForm/PlatformSelector/index.tsx
  packages/console/src/components/CreateConnectorForm/Skeleton/index.module.scss
  packages/console/src/components/CreateConnectorForm/Skeleton/index.tsx
  packages/console/src/components/CreateConnectorForm/constants.ts
  packages/console/src/components/CreateConnectorForm/index.module.scss
  packages/console/src/components/CreateConnectorForm/index.tsx
  packages/console/src/components/CreateConnectorForm/utils.ts
  packages/console/src/hooks/use-api.ts
  packages/console/src/hooks/use-connector-api.ts
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/Connectors/Guide/index.tsx
  packages/console/src/pages/Connectors/index.tsx
Labels: feature, size/s

#4119 feat(console): hide the check readme button for the email service connector
  packages/console/src/pages/ConnectorDetails/index.tsx
Labels: feature, size/s

#4120 feat(core): enable email service connector
  packages/core/src/utils/connectors/index.ts
Labels: feature, size/xs

#4116 feat(console): save and update user default tenant id
  packages/console/src/cloud/pages/Main/Redirect.tsx
  packages/console/src/cloud/pages/Main/index.tsx
  packages/console/src/containers/TenantAccess/index.tsx
  packages/console/src/contexts/TenantsProvider.tsx
  packages/console/src/hooks/use-user-default-tenant-id.ts
Labels: feature, size/s

#4122 feat(core,connector): add cloud connection library
  packages/connectors/connector-logto-email/src/index.ts
  packages/connectors/connector-logto-email/src/mock.ts
  packages/connectors/connector-logto-email/src/types.ts
  packages/core/src/__mocks__/cloud-connection.ts
  packages/core/src/__mocks__/index.ts
  packages/core/src/libraries/cloud-connection.ts
  packages/core/src/libraries/connector.test.ts
  packages/core/src/libraries/connector.ts
  packages/core/src/libraries/logto-config.ts
  packages/core/src/libraries/sign-in-experience/index.test.ts
  packages/core/src/routes/connector/config-testing.ts
  packages/core/src/tenants/Libraries.ts
  packages/core/src/tenants/Tenant.ts
  packages/core/src/tenants/TenantContext.ts
  packages/core/src/test-utils/tenant.ts
  packages/core/src/utils/endpoint.ts
Labels: feature, size/m

#4123 fix(console): disable unnecessary fetchings when switching tenants
  packages/console/src/contexts/TenantsProvider.tsx
Labels: bugfix, size/xs

#4126 feat(schemas): drop m2m credentials in existing logto email connector config
  packages/schemas/alterations/next-1688613459-remove-m2m-credentials-from-existing-logto-email-connector-config.ts
Labels: feature, size/s

#4114 chore(phrases): add subscription-related phrases for console
  packages/phrases/src/locales/de/translation/admin-console/index.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription.ts
  packages/phrases/src/locales/de/translation/admin-console/tenants.ts
  packages/phrases/src/locales/en/translation/admin-console/index.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription.ts
  packages/phrases/src/locales/en/translation/admin-console/tenants.ts
  packages/phrases/src/locales/es/translation/admin-console/index.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription.ts
  packages/phrases/src/locales/es/translation/admin-console/tenants.ts
  packages/phrases/src/locales/fr/translation/admin-console/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription.ts
  packages/phrases/src/locales/fr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/it/translation/admin-console/index.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription.ts
  packages/phrases/src/locales/it/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ja/translation/admin-console/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription.ts
  packages/phrases/src/locales/ja/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ko/translation/admin-console/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription.ts
  packages/phrases/src/locales/ko/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ru/translation/admin-console/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription.ts
  packages/phrases/src/locales/ru/translation/admin-console/tenants.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tenants.ts
Labels: chore, size/xl

#4118 feat(console): add subscription page
  packages/console/src/consts/env.ts
  packages/console/src/consts/page-tabs.ts
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/index.tsx
  packages/console/src/pages/TenantSettings/index.tsx
Labels: feature, size/s

#4113 feat(core,schemas): record daily active users
  .changeset/chatty-spoons-joke.md
  packages/core/src/database/insert-into.ts
  packages/core/src/event-listeners/access-token.test.ts
  packages/core/src/event-listeners/access-token.ts
  packages/core/src/event-listeners/index.test.ts
  packages/core/src/event-listeners/index.ts
  packages/core/src/oidc/init.ts
  packages/core/src/oidc/utils.ts
  packages/core/src/queries/daily-active-user.ts
  packages/core/src/tenants/Queries.ts
  packages/schemas/alterations/next-1688627407-daily-active-users.ts
  packages/schemas/tables/daily_active_users.sql
  packages/shared/src/database/sql.ts
Labels: feature, size/m

#4127 feat(core): add cloud client
  packages/core/package.json
  packages/core/src/__mocks__/cloud-connection.ts
  packages/core/src/libraries/cloud-connection.test.ts
  packages/core/src/libraries/cloud-connection.ts
  packages/core/src/libraries/connector.test.ts
  packages/core/src/libraries/connector.ts
  packages/core/src/libraries/sign-in-experience/index.test.ts
  packages/core/src/utils/json.ts
  pnpm-lock.yaml
Labels: feature, size/m

#4135 fix(core,connector): use isProduction as email service feature switch
  packages/connectors/connector-logto-email/src/constant.ts
  packages/core/src/utils/connectors/index.ts
Labels: bugfix, size/s

#4139 chore(console): block subscritpion route
  packages/console/src/containers/ConsoleContent/index.tsx
Labels: chore, size/xs

#4129 chore(console,connector): update logto email connector related console
  packages/connectors/connector-logto-email/src/constant.ts
  packages/console/src/components/ConnectorTester/index.tsx
  packages/console/src/components/CreateConnectorForm/constants.ts
  packages/phrases/src/locales/de/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/en/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/es/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/it/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/connector-details.ts
Labels: chore, size/m

#4138 fix(console): avoid updating dirty form data
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/ConnectorDetails/ConnectorContent/index.tsx
  packages/console/src/pages/SignInExperience/index.tsx
  packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/LanguageDetails.tsx
  packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/index.tsx
Labels: bugfix, size/s

#4142 ci: compare multiple schemas including cloud
  .scripts/compare-database.js
Labels: size/s

#4136 chore(console): update email service usage UI
  packages/console/src/assets/icons/email-sent-dark.svg
  packages/console/src/pages/ConnectorDetails/EmailUsage/index.module.scss
  packages/console/src/pages/ConnectorDetails/EmailUsage/index.tsx
Labels: chore, size/s

#4137 feat(console): add plan quota table
  packages/console/package.json
  packages/console/src/cloud/hooks/use-cloud-swr.ts
  packages/console/src/cloud/types/router.ts
  packages/console/src/consts/subscriptions.ts
  packages/console/src/ds-components/DynamicT/index.tsx
  packages/console/src/ds-components/Table/index.tsx
  packages/console/src/hooks/use-subscription-plans.ts
  packages/console/src/pages/TenantSettings/Subscription/PlanQuotaTable/PlanName/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanQuotaTable/PlanQuotaGroupKeyLabel/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanQuotaTable/PlanQuotaKeyLabel/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanQuotaTable/index.module.scss
  packages/console/src/pages/TenantSettings/Subscription/PlanQuotaTable/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanQuotaTable/utils.ts
  packages/console/src/pages/TenantSettings/Subscription/index.tsx
  packages/console/src/types/subscriptions.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#4144 fix(console): reset connector form with updated data
  packages/console/src/pages/ConnectorDetails/ConnectorContent/index.tsx
Labels: bugfix, size/xs

#4145 fix(schemas): remove incorrect tenantInfoGuard type
  packages/schemas/src/models/tenants.ts
Labels: bugfix, size/xs

#4147 fix(core): fix the argument type of createConnectorLibrary
  packages/core/src/libraries/cloud-connection.ts
Labels: bugfix, size/xs

#4152 refactor(core,console): fix useCloudSwr type
  packages/console/package.json
  packages/console/src/cloud/hooks/use-cloud-swr.ts
  packages/core/package.json
  packages/schemas/package.json
  pnpm-lock.yaml
Labels: enhancement, size/s

#4143 chore(toolkit,phrases,connector,console): use company info instead of company address
  packages/connectors/connector-logto-email/src/constant.ts
  packages/connectors/connector-logto-email/src/index.ts
  packages/console/src/pages/ConnectorDetails/ConnectorContent/EmailServiceConnectorForm/index.module.scss
  packages/console/src/pages/ConnectorDetails/ConnectorContent/EmailServiceConnectorForm/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/en/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/es/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/it/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/connector-details.ts
  packages/toolkit/connector-kit/src/types.ts
Labels: chore, size/m

#4150 chore(connector,toolkit,console,phrases): align config key and display name
  packages/connectors/connector-logto-email/src/constant.ts
  packages/connectors/connector-logto-email/src/index.ts
  packages/console/src/pages/ConnectorDetails/ConnectorContent/EmailServiceConnectorForm/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/en/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/es/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/it/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/connector-details.ts
  packages/toolkit/connector-kit/src/types.ts
Labels: chore, size/m

#4154 chore(phrases): update subscription-related phrases
  packages/phrases/src/locales/de/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-item-limited.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-item-unlimited.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-item-limited.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-item-unlimited.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-item-limited.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-item-unlimited.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-item-limited.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-item-unlimited.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-item-limited.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-item-unlimited.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-item-limited.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-item-unlimited.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-item-limited.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-item-unlimited.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-item-limited.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-item-unlimited.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-item-limited.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-item-unlimited.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-item-limited.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-item-unlimited.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-item-limited.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-item-unlimited.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-item-limited.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-item-unlimited.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-item-limited.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-item-unlimited.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-item-limited.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-item-unlimited.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-item-limited.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-item-unlimited.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-item.ts
Labels: chore, size/xl

#4157 refactor(console): refactor `useSubscriptionPlans` hook
  packages/console/src/components/PlanName/index.tsx
  packages/console/src/hooks/use-subscription-plans.ts
  packages/console/src/pages/TenantSettings/Subscription/PlanQuotaTable/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/index.tsx
  packages/console/src/pages/TenantSettings/TenantDomainSettings/index.tsx
  packages/console/src/pages/TenantSettings/components/Skeleton/index.module.scss
  packages/console/src/pages/TenantSettings/components/Skeleton/index.tsx
Labels: enhancement, size/s

#4155 refactor(schemas): specify tenants table schema
  packages/schemas/package.json
  packages/schemas/src/models/tenants.ts
  pnpm-lock.yaml
Labels: enhancement, size/xs

#4159 refactor(schemas): update email service data guard
  packages/schemas/src/types/system.ts
Labels: enhancement, size/s

#4162 chore(phrases): update subscription-related phrases
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-item.ts
Labels: chore, size/xl

#4167 chore(console): bump `withtyped` and `@logto/cloud` version
  packages/console/package.json
  packages/console/src/cloud/types/router.ts
  packages/console/src/consts/subscriptions.ts
  packages/console/src/pages/TenantSettings/Subscription/PlanQuotaTable/PlanQuotaKeyLabel/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanQuotaTable/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanQuotaTable/utils.ts
  pnpm-lock.yaml
Labels: chore, size/s

#4164 refactor(core,connector): store and get fromEmail from logto email connector
  packages/connectors/connector-logto-email/src/constant.ts
  packages/connectors/connector-logto-email/src/index.ts
  packages/core/src/routes/connector/index.ts
  packages/core/src/tenants/SystemContext.ts
  packages/core/src/utils/connectors/extra-information.ts
  packages/core/src/utils/connectors/index.ts
  packages/toolkit/connector-kit/src/types.ts
Labels: enhancement, size/m

#4168 refactor(schemas): add manage affiliate scope
  packages/schemas/src/seeds/cloud-api.ts
Labels: enhancement, size/xs

#4166 fix(core,connector): fix patch connector api cannot reset config/metadata bug
  packages/connectors/connector-mock-email-alternative/src/index.ts
  packages/connectors/connector-mock-email-alternative/src/types.ts
  packages/core/src/database/update-where.test.ts
  packages/core/src/database/update-where.ts
  packages/core/src/routes/connector/index.patch.test.ts
  packages/core/src/routes/connector/index.ts
  packages/integration-tests/src/tests/api/connector.test.ts
Labels: bugfix, size/s

#4146 feat(console): add switch plan action bar
  packages/console/package.json
  packages/console/src/cloud/hooks/use-cloud-swr.ts
  packages/console/src/cloud/types/router.ts
  packages/console/src/consts/subscriptions.ts
  packages/console/src/hooks/use-current-subscription.ts
  packages/console/src/hooks/use-subscription-plans.ts
  packages/console/src/pages/TenantSettings/Subscription/PlanQuotaTable/index.module.scss
  packages/console/src/pages/TenantSettings/Subscription/PlanQuotaTable/utils.ts
  packages/console/src/pages/TenantSettings/Subscription/SwitchPlanActionBar/index.module.scss
  packages/console/src/pages/TenantSettings/Subscription/SwitchPlanActionBar/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/index.module.scss
  packages/console/src/pages/TenantSettings/Subscription/index.tsx
  packages/console/src/utils/subscription.ts
  pnpm-lock.yaml
Labels: feature, size/l

#4169 refactor(console): config the allowed mime type for ImageUploader component
  packages/console/src/ds-components/Uploader/ImageUploader/index.tsx
  packages/console/src/ds-components/Uploader/ImageUploaderField/index.tsx
  packages/console/src/hooks/use-image-mime-types.ts
  packages/console/src/pages/ConnectorDetails/ConnectorContent/EmailServiceConnectorForm/index.tsx
  packages/console/src/pages/SignInExperience/tabs/Branding/components/LogoAndFaviconUploader/index.tsx
Labels: enhancement, size/s

#4171 refactor(schemas): add create affiliate scope
  packages/schemas/src/seeds/cloud-api.ts
Labels: enhancement, size/xs

#4161 feat(console): add downgrade plan confirm modal
  packages/console/src/assets/icons/descend-arrow.svg
  packages/console/src/ds-components/ConfirmModal/index.tsx
  packages/console/src/ds-components/ModalLayout/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/DowngradeConfirmModalContent/PlanQuotaDiffList/QuotaDiffItem/index.module.scss
  packages/console/src/pages/TenantSettings/Subscription/DowngradeConfirmModalContent/PlanQuotaDiffList/QuotaDiffItem/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/DowngradeConfirmModalContent/PlanQuotaDiffList/index.module.scss
  packages/console/src/pages/TenantSettings/Subscription/DowngradeConfirmModalContent/PlanQuotaDiffList/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/DowngradeConfirmModalContent/index.module.scss
  packages/console/src/pages/TenantSettings/Subscription/DowngradeConfirmModalContent/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/NotEligibleDowngradeModalContent/index.module.scss
  packages/console/src/pages/TenantSettings/Subscription/NotEligibleDowngradeModalContent/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/SwitchPlanActionBar/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/quota-item-phrases.ts
  packages/console/src/types/subscriptions.ts
Labels: feature, size/l

#4173 chore: upgrade commitlint packages
  package.json
  pnpm-lock.yaml
Labels: chore, size/xs

#4174 chore(phrases): add upsell-related phrases
  packages/phrases/src/locales/de/translation/admin-console/index.ts
  packages/phrases/src/locales/de/translation/admin-console/tenants.ts
  packages/phrases/src/locales/de/translation/admin-console/upsell.ts
  packages/phrases/src/locales/en/translation/admin-console/index.ts
  packages/phrases/src/locales/en/translation/admin-console/tenants.ts
  packages/phrases/src/locales/en/translation/admin-console/upsell.ts
  packages/phrases/src/locales/es/translation/admin-console/index.ts
  packages/phrases/src/locales/es/translation/admin-console/tenants.ts
  packages/phrases/src/locales/es/translation/admin-console/upsell.ts
  packages/phrases/src/locales/fr/translation/admin-console/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/fr/translation/admin-console/upsell.ts
  packages/phrases/src/locales/it/translation/admin-console/index.ts
  packages/phrases/src/locales/it/translation/admin-console/tenants.ts
  packages/phrases/src/locales/it/translation/admin-console/upsell.ts
  packages/phrases/src/locales/ja/translation/admin-console/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ja/translation/admin-console/upsell.ts
  packages/phrases/src/locales/ko/translation/admin-console/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ko/translation/admin-console/upsell.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/upsell.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/upsell.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/upsell.ts
  packages/phrases/src/locales/ru/translation/admin-console/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ru/translation/admin-console/upsell.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/upsell.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/upsell.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/upsell.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/upsell.ts
Labels: chore, size/xl

#4172 fix(console): should block test of invalid connector config
  packages/console/src/components/ConnectorTester/index.tsx
Labels: bugfix, size/xs

#4176 chore(phrases): update subscription phrases
  packages/phrases/src/locales/de/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/index.ts
Labels: chore, size/s

#4153 feat(core,phrases): add quota guard middleware
  packages/core/package.json
  packages/core/src/__mocks__/subscription.ts
  packages/core/src/libraries/cloud-connection.ts
  packages/core/src/middleware/koa-quota-guard.test.ts
  packages/core/src/middleware/koa-quota-guard.ts
  packages/core/src/queries/application.ts
  packages/core/src/routes/application.ts
  packages/core/src/test-utils/cloud-connection.ts
  packages/core/src/utils/subscription/index.ts
  packages/core/src/utils/subscription/types.ts
  packages/phrases/src/locales/de/errors/index.ts
  packages/phrases/src/locales/de/errors/subscription.ts
  packages/phrases/src/locales/en/errors/index.ts
  packages/phrases/src/locales/en/errors/subscription.ts
  packages/phrases/src/locales/es/errors/index.ts
  packages/phrases/src/locales/es/errors/subscription.ts
  packages/phrases/src/locales/fr/errors/index.ts
  packages/phrases/src/locales/fr/errors/subscription.ts
  packages/phrases/src/locales/it/errors/index.ts
  packages/phrases/src/locales/it/errors/subscription.ts
  packages/phrases/src/locales/ja/errors/index.ts
  packages/phrases/src/locales/ja/errors/subscription.ts
  packages/phrases/src/locales/ko/errors/index.ts
  packages/phrases/src/locales/ko/errors/subscription.ts
  packages/phrases/src/locales/pl-pl/errors/index.ts
  packages/phrases/src/locales/pl-pl/errors/subscription.ts
  packages/phrases/src/locales/pt-br/errors/index.ts
  packages/phrases/src/locales/pt-br/errors/subscription.ts
  packages/phrases/src/locales/pt-pt/errors/index.ts
  packages/phrases/src/locales/pt-pt/errors/subscription.ts
  packages/phrases/src/locales/ru/errors/index.ts
  packages/phrases/src/locales/ru/errors/subscription.ts
  packages/phrases/src/locales/tr-tr/errors/index.ts
  packages/phrases/src/locales/tr-tr/errors/subscription.ts
  packages/phrases/src/locales/zh-cn/errors/index.ts
  packages/phrases/src/locales/zh-cn/errors/subscription.ts
  packages/phrases/src/locales/zh-hk/errors/index.ts
  packages/phrases/src/locales/zh-hk/errors/subscription.ts
  packages/phrases/src/locales/zh-tw/errors/index.ts
  packages/phrases/src/locales/zh-tw/errors/subscription.ts
  pnpm-lock.yaml
Labels: feature, size/l

#4179 feat(console): add free plan notification on the get-started page
  packages/console/src/assets/images/free-plan-notification-image.svg
  packages/console/src/pages/GetStarted/FreePlanNotification/index.module.scss
  packages/console/src/pages/GetStarted/FreePlanNotification/index.tsx
  packages/console/src/pages/GetStarted/index.tsx
Labels: feature, size/l

#4181 feat(console): apply quota limit for custom domain
  packages/console/src/components/FormCard/index.module.scss
  packages/console/src/components/FormCard/index.tsx
  packages/console/src/components/ProTag/index.module.scss
  packages/console/src/components/ProTag/index.tsx
  packages/console/src/hooks/use-current-subscription-plan.ts
  packages/console/src/pages/TenantSettings/TenantDomainSettings/AddDomainForm/index.tsx
  packages/console/src/pages/TenantSettings/TenantDomainSettings/index.module.scss
  packages/console/src/pages/TenantSettings/TenantDomainSettings/index.tsx
Labels: feature, size/m

#4183 refactor(console): refactor connector creation modal
  packages/console/src/components/CreateConnectorForm/ConnectorRadioGroup/ConnectorRadio/index.module.scss
  packages/console/src/components/CreateConnectorForm/ConnectorRadioGroup/ConnectorRadio/index.tsx
  packages/console/src/components/CreateConnectorForm/ConnectorRadioGroup/index.module.scss
  packages/console/src/components/CreateConnectorForm/ConnectorRadioGroup/index.tsx
  packages/console/src/components/CreateConnectorForm/Skeleton/index.tsx
  packages/console/src/components/CreateConnectorForm/index.module.scss
  packages/console/src/components/CreateConnectorForm/index.tsx
  packages/console/src/components/CreateConnectorForm/utils.ts
  packages/phrases/src/locales/de/translation/admin-console/connectors.ts
  packages/phrases/src/locales/en/translation/admin-console/connectors.ts
  packages/phrases/src/locales/es/translation/admin-console/connectors.ts
  packages/phrases/src/locales/fr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/it/translation/admin-console/connectors.ts
  packages/phrases/src/locales/ja/translation/admin-console/connectors.ts
  packages/phrases/src/locales/ko/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/connectors.ts
  packages/phrases/src/locales/ru/translation/admin-console/connectors.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/connectors.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/connectors.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/connectors.ts
Labels: enhancement, size/l

#4178 feat(console): checkout integration
  packages/console/package.json
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/index.tsx
  packages/console/src/consts/pages.ts
  packages/console/src/consts/storage.ts
  packages/console/src/consts/subscriptions.ts
  packages/console/src/hooks/use-subscribe.ts
  packages/console/src/pages/CheckoutSuccessCallback/index.tsx
  packages/console/src/pages/ConsoleRoutes/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/SwitchPlanActionBar/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/index.tsx
  packages/console/src/types/subscriptions.ts
  packages/console/src/utils/checkout.ts
  packages/phrases/src/locales/de/translation/admin-console/general.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/en/translation/admin-console/general.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/es/translation/admin-console/general.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/general.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/it/translation/admin-console/general.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/general.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/general.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/general.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/general.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/index.ts
  pnpm-lock.yaml
Labels: feature, size/l

#4184 feat(core): support fetching all applications without pagination
  packages/core/src/routes/application.test.ts
  packages/core/src/routes/application.ts
Labels: feature, size/s

#4186 feat(console): apply quota limit for webhooks
  packages/console/src/components/ContactUsPhraseLink/index.tsx
  packages/console/src/components/QuotaGuardFooter/index.module.scss
  packages/console/src/components/QuotaGuardFooter/index.tsx
  packages/console/src/ds-components/ModalLayout/index.module.scss
  packages/console/src/hooks/use-current-subscription.ts
  packages/console/src/hooks/use-subscription-plans.ts
  packages/console/src/pages/Webhooks/components/CreateFormModal/CreateForm.tsx
  packages/console/src/pages/Webhooks/components/CreateFormModal/index.tsx
  packages/console/src/pages/Webhooks/index.tsx
  packages/console/src/utils/quota.ts
Labels: feature, size/m

#4177 chore(console,phrases): add logto email service doc links
  packages/console/src/components/FormCard/index.tsx
  packages/console/src/pages/ConnectorDetails/ConnectorContent/EmailServiceConnectorForm/index.tsx
  packages/console/src/pages/ConnectorDetails/EmailUsage/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/en/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/es/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/it/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/connector-details.ts
Labels: chore, size/s

#4190 feat(console): apply quota limit for connector creation
  packages/console/src/components/CreateConnectorForm/Footer/index.tsx
  packages/console/src/components/CreateConnectorForm/index.tsx
Labels: feature, size/m

#4192 feat(console): apply quota limit for resource and scope creation
  packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx
  packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/index.tsx
  packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
Labels: feature, size/m

#4193 feat(console): apply quota limit for application creation
  packages/console/src/ds-components/RadioGroup/Radio.tsx
  packages/console/src/pages/Applications/components/ApplicationsPlaceholder/index.tsx
  packages/console/src/pages/Applications/components/CreateForm/Footer/index.tsx
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/Applications/components/TypeDescription/index.module.scss
  packages/console/src/pages/Applications/components/TypeDescription/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/general.ts
  packages/phrases/src/locales/de/translation/admin-console/upsell.ts
  packages/phrases/src/locales/en/translation/admin-console/general.ts
  packages/phrases/src/locales/en/translation/admin-console/upsell.ts
  packages/phrases/src/locales/es/translation/admin-console/general.ts
  packages/phrases/src/locales/es/translation/admin-console/upsell.ts
  packages/phrases/src/locales/fr/translation/admin-console/general.ts
  packages/phrases/src/locales/fr/translation/admin-console/upsell.ts
  packages/phrases/src/locales/it/translation/admin-console/general.ts
  packages/phrases/src/locales/it/translation/admin-console/upsell.ts
  packages/phrases/src/locales/ja/translation/admin-console/general.ts
  packages/phrases/src/locales/ja/translation/admin-console/upsell.ts
  packages/phrases/src/locales/ko/translation/admin-console/general.ts
  packages/phrases/src/locales/ko/translation/admin-console/upsell.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/general.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/upsell.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/upsell.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/upsell.ts
  packages/phrases/src/locales/ru/translation/admin-console/general.ts
  packages/phrases/src/locales/ru/translation/admin-console/upsell.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/upsell.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/upsell.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/upsell.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/upsell.ts
Labels: feature, size/l

#4194 feat(console): apply subscription cost for current plan info
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/index.tsx
Labels: feature, size/xs

#4189 feat(console): apply quota limit for roles
  packages/console/src/components/CreateConnectorForm/Footer/index.tsx
  packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx
  packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
  packages/console/src/pages/Applications/components/CreateForm/Footer/index.tsx
  packages/console/src/pages/RoleDetails/RolePermissions/components/AssignPermissionsModal/index.tsx
  packages/console/src/pages/RoleDetails/RolePermissions/index.tsx
  packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
  packages/console/src/pages/Roles/components/CreateRoleModal/index.tsx
  packages/console/src/pages/Roles/index.tsx
  packages/console/src/pages/Webhooks/components/CreateFormModal/CreateForm.tsx
  packages/console/src/utils/quota.ts
Labels: feature, size/m

#4182 test: added tests for the koaConsoleRedirectProxy function
  packages/core/src/middleware/koa-console-redirect-proxy.test.ts
  packages/core/src/utils/test-utils.ts
Labels: testing, size/s

#4185 refactor(core): create quota library
  packages/core/src/database/row-count.ts
  packages/core/src/libraries/quota.test.ts
  packages/core/src/libraries/quota.ts
  packages/core/src/middleware/koa-quota-guard.test.ts
  packages/core/src/middleware/koa-quota-guard.ts
  packages/core/src/queries/application.ts
  packages/core/src/routes/application.test.ts
  packages/core/src/routes/application.ts
  packages/core/src/routes/resource.test.ts
  packages/core/src/routes/resource.ts
  packages/core/src/tenants/Libraries.ts
  packages/core/src/tenants/Tenant.ts
  packages/core/src/test-utils/quota.ts
  packages/core/src/test-utils/tenant.ts
Labels: enhancement, size/l

#4187 feat(core): apply all quota guard
  packages/core/src/libraries/quota.test.ts
  packages/core/src/libraries/quota.ts
  packages/core/src/queries/application.ts
  packages/core/src/queries/roles-scopes.ts
  packages/core/src/queries/roles.ts
  packages/core/src/queries/scope.ts
  packages/core/src/routes/connector/factory.ts
  packages/core/src/routes/connector/index.post.test.ts
  packages/core/src/routes/connector/index.ts
  packages/core/src/routes/domain.test.ts
  packages/core/src/routes/domain.ts
  packages/core/src/routes/hook.test.ts
  packages/core/src/routes/hook.ts
  packages/core/src/routes/resource.ts
  packages/core/src/routes/role.scope.test.ts
  packages/core/src/routes/role.scope.ts
  packages/core/src/routes/role.test.ts
  packages/core/src/routes/role.ts
  packages/core/src/tenants/Libraries.ts
  packages/core/src/test-utils/connectors.ts
  packages/core/src/utils/subscription/types.ts
Labels: feature, size/l

#4188 chore(phrases): update content to sentence case
  packages/console/src/containers/ConsoleContent/Sidebar/hook.tsx
  packages/phrases/src/locales/de/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/en/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/en/translation/admin-console/tabs.ts
  packages/phrases/src/locales/es/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/fr/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/it/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/ja/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/ko/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/pt-pt/errors/subscription.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/ru/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tab-sections.ts
Labels: chore, size/s

#4199 chore(schemas): bump withTyped version
  packages/schemas/package.json
  pnpm-lock.yaml
Labels: chore, size/xs

#4201 chore(connector): update the parse of email usage api response
  packages/connectors/connector-logto-email/src/index.ts
Labels: chore, size/xs

#4160 feat(console): add billing history page
  packages/console/src/cloud/types/router.ts
  packages/console/src/consts/page-tabs.ts
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/hooks/use-invoices.ts
  packages/console/src/pages/TenantSettings/BillingHistory/InvoiceStatusTag/index.tsx
  packages/console/src/pages/TenantSettings/BillingHistory/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/PlanUsage/index.tsx
  packages/console/src/pages/TenantSettings/index.tsx
  packages/console/src/types/subscriptions.ts
  packages/console/src/utils/subscription.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/index.ts
Labels: feature, size/l

#4197 refactor(console): refactor subscription-related hooks
  packages/console/src/components/CreateConnectorForm/Footer/index.tsx
  packages/console/src/hooks/use-current-subscription-usage.ts
  packages/console/src/hooks/use-subscription-plan.ts
  packages/console/src/hooks/use-subscription-usage.ts
  packages/console/src/hooks/use-subscription.ts
  packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx
  packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
  packages/console/src/pages/Applications/components/CreateForm/Footer/index.tsx
  packages/console/src/pages/GetStarted/FreePlanNotification/index.tsx
  packages/console/src/pages/RoleDetails/RolePermissions/components/AssignPermissionsModal/index.tsx
  packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/index.tsx
  packages/console/src/pages/TenantSettings/TenantDomainSettings/index.tsx
  packages/console/src/pages/Webhooks/components/CreateFormModal/CreateForm.tsx
Labels: enhancement, size/m

#4200 feat(console): add subscription info for tenant selector
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/TenantDropdownItem/Skeleton/index.module.scss
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/TenantDropdownItem/Skeleton/index.tsx
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/TenantDropdownItem/TenantStatusTag.tsx
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/TenantDropdownItem/index.module.scss
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/index.module.scss
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/index.tsx
  packages/console/src/types/subscriptions.ts
  packages/console/src/utils/subscription.ts
Labels: feature, size/l

#4195 feat(console): add mau exceeeded modal
  packages/console/src/components/MauExceededModal/index.module.scss
  packages/console/src/components/MauExceededModal/index.tsx
  packages/console/src/components/PlanUsage/index.module.scss
  packages/console/src/components/PlanUsage/index.tsx
  packages/console/src/components/QuotaGuardFooter/index.tsx
  packages/console/src/containers/AppContent/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/MauLimitExceededNotification/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/index.tsx
Labels: feature, size/m

#4202 feat(console): add contact us help tip for downgrade modal
  packages/console/src/pages/TenantSettings/Subscription/NotEligibleDowngradeModalContent/index.tsx
Labels: feature, size/xs

#4198 refactor(core): improve error handling
  packages/core/src/middleware/koa-slonik-error-handler.ts
  packages/core/src/oidc/init.ts
  packages/integration-tests/src/tests/api/admin-user.test.ts
  packages/integration-tests/src/tests/api/interaction/error-handling.test.ts
  packages/phrases/src/locales/de/errors/entity.ts
  packages/phrases/src/locales/en/errors/entity.ts
  packages/phrases/src/locales/es/errors/entity.ts
  packages/phrases/src/locales/fr/errors/entity.ts
  packages/phrases/src/locales/it/errors/entity.ts
  packages/phrases/src/locales/ja/errors/entity.ts
  packages/phrases/src/locales/ko/errors/entity.ts
  packages/phrases/src/locales/pl-pl/errors/entity.ts
  packages/phrases/src/locales/pt-br/errors/entity.ts
  packages/phrases/src/locales/pt-pt/errors/entity.ts
  packages/phrases/src/locales/ru/errors/entity.ts
  packages/phrases/src/locales/tr-tr/errors/entity.ts
  packages/phrases/src/locales/zh-cn/errors/entity.ts
  packages/phrases/src/locales/zh-hk/errors/entity.ts
  packages/phrases/src/locales/zh-tw/errors/entity.ts
Labels: enhancement, size/m

#4203 feat(console): add payment overdue reminder
  packages/console/src/components/BillInfo/index.module.scss
  packages/console/src/components/BillInfo/index.tsx
  packages/console/src/components/PaymentOverdueModal/index.module.scss
  packages/console/src/components/PaymentOverdueModal/index.tsx
  packages/console/src/containers/AppContent/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/PaymentOverdueNotification/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/de/translation/admin-console/upsell.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/en/translation/admin-console/upsell.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/es/translation/admin-console/upsell.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/upsell.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/it/translation/admin-console/upsell.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/upsell.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/upsell.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/upsell.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/upsell.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/upsell.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/upsell.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/upsell.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/upsell.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/upsell.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/upsell.ts
Labels: feature, size/m

#4206 fix(console): adapt callback and current tenant id logic
  packages/console/src/cloud/AppRoutes.tsx
  packages/console/src/containers/TenantAccess/index.tsx
  packages/console/src/contexts/TenantsProvider.tsx
  packages/console/src/onboarding/pages/Congrats/index.tsx
  packages/console/src/pages/Callback/index.tsx
  packages/console/src/pages/ConsoleRoutes/index.tsx
Labels: bugfix, size/s

#4210 fix(console): add origin for `getUrl`
  packages/console/src/hooks/use-tenant-pathname.ts
Labels: bugfix, size/xs

#4209 feat(console): handle subscription related request errors
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/index.tsx
  packages/console/src/hooks/use-invoices.ts
  packages/console/src/hooks/use-subscription-plans.ts
  packages/console/src/hooks/use-subscription-usage.ts
  packages/console/src/hooks/use-subscription.ts
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/MauLimitExceededNotification/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/SwitchPlanActionBar/index.tsx
Labels: feature, size/m

#4204 fix(core): fix quota guard middleware env flag
  packages/core/src/__mocks__/subscription.ts
  packages/core/src/libraries/quota.test.ts
  packages/core/src/libraries/quota.ts
  packages/core/src/test-utils/cloud-connection.ts
  packages/core/src/test-utils/connectors.ts
Labels: bugfix, size/m

#4205 feat(console): should limit only the number of free tenant
  packages/console/package.json
  packages/console/src/cloud/pages/Main/TenantLandingPage/TenantLandingPageContent/index.tsx
  packages/console/src/cloud/types/router.ts
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/index.tsx
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/index.tsx
  packages/console/src/components/CreateTenantModal/index.tsx
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/index.module.scss
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/index.tsx
  packages/console/src/containers/TenantAccess/index.tsx
  packages/console/src/contexts/TenantsProvider.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/DeleteModal/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/index.tsx
  pnpm-lock.yaml
Labels: feature, size/m

#4211 refactor(console): improve error handling for cloud api request
  packages/console/src/cloud/hooks/use-cloud-api.ts
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/index.tsx
  packages/console/src/components/CreateTenantModal/index.tsx
  packages/console/src/hooks/use-invoices.ts
  packages/console/src/hooks/use-subscribe.ts
  packages/console/src/hooks/use-subscription-plans.ts
  packages/console/src/hooks/use-subscription-usage.ts
  packages/console/src/hooks/use-subscription.ts
  packages/console/src/pages/CheckoutSuccessCallback/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/MauLimitExceededNotification/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/SwitchPlanActionBar/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/index.tsx
Labels: enhancement, size/m

#4213 feat(console): support open stripe payment management page from console
  packages/console/package.json
  packages/console/src/components/BillInfo/index.tsx
  packages/console/src/components/PaymentOverdueModal/index.tsx
  packages/console/src/hooks/use-subscribe.ts
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/PaymentOverdueNotification/index.tsx
  pnpm-lock.yaml
Labels: feature, size/s

#4215 chore(console): remove pricing feature switch
  packages/console/src/components/CreateConnectorForm/index.tsx
  packages/console/src/components/CreateTenantModal/index.tsx
  packages/console/src/consts/env.ts
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx
  packages/console/src/containers/AppContent/index.tsx
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/hooks/use-invoices.ts
  packages/console/src/hooks/use-subscription-plans.ts
  packages/console/src/hooks/use-subscription-usage.ts
  packages/console/src/hooks/use-subscription.ts
  packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
  packages/console/src/pages/Applications/components/ApplicationsPlaceholder/index.tsx
  packages/console/src/pages/Applications/components/CreateForm/Footer/index.tsx
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/ConsoleRoutes/index.tsx
  packages/console/src/pages/GetStarted/FreePlanNotification/index.tsx
  packages/console/src/pages/TenantSettings/TenantDomainSettings/index.tsx
  packages/console/src/pages/TenantSettings/index.tsx
  packages/console/src/utils/quota.ts
Labels: chore, size/m

#4216 feat(console): display not eligible reminder for plan switching
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/MauLimitExceededNotification/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/SwitchPlanActionBar/index.tsx
  packages/console/src/pages/TenantSettings/components/NotEligibleSwitchPlanModalContent/index.module.scss
  packages/console/src/pages/TenantSettings/components/NotEligibleSwitchPlanModalContent/index.tsx
  packages/console/src/utils/subscription.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/index.ts
Labels: feature, size/l

#4220 style(console): fix mau unit price style
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanQuotaTable/index.tsx
Labels: size/xs

#4223 fix(console): avoid reading response error body more than once
  packages/console/src/cloud/hooks/use-cloud-api.ts
  packages/console/src/utils/subscription.ts
Labels: bugfix, size/s

#4219 refactor(console): update free plan get-started notification
  packages/console/src/pages/GetStarted/FreePlanNotification/index.module.scss
  packages/console/src/pages/GetStarted/FreePlanNotification/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/upsell.ts
  packages/phrases/src/locales/en/translation/admin-console/upsell.ts
  packages/phrases/src/locales/es/translation/admin-console/upsell.ts
  packages/phrases/src/locales/fr/translation/admin-console/upsell.ts
  packages/phrases/src/locales/it/translation/admin-console/upsell.ts
  packages/phrases/src/locales/ja/translation/admin-console/upsell.ts
  packages/phrases/src/locales/ko/translation/admin-console/upsell.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/upsell.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/upsell.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/upsell.ts
  packages/phrases/src/locales/ru/translation/admin-console/upsell.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/upsell.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/upsell.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/upsell.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/upsell.ts
Labels: enhancement, size/m

#4222 refactor(console): hide cancel button for not eligible switch plan modal
  packages/console/src/ds-components/ConfirmModal/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/MauLimitExceededNotification/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/SwitchPlanActionBar/index.tsx
Labels: enhancement, size/xs

#4221 style(console): update quota table border radius to 16px
  packages/console/src/pages/TenantSettings/Subscription/PlanQuotaTable/index.module.scss
Labels: size/xs

#4218 chore(console): remove preview
  packages/console/src/assets/icons/calendar.svg
  packages/console/src/assets/images/cloud-logo.svg
  packages/console/src/consts/external-links.ts
  packages/console/src/containers/AppContent/components/Topbar/Contact/ContactModal/hook.tsx
  packages/console/src/containers/AppContent/components/Topbar/index.tsx
  packages/console/src/containers/AppContent/index.tsx
  packages/console/src/onboarding/components/Broadcast/index.module.scss
  packages/console/src/onboarding/components/Broadcast/index.tsx
  packages/console/src/onboarding/components/EarlyBirdGift/GiftModal/index.module.scss
  packages/console/src/onboarding/components/EarlyBirdGift/GiftModal/index.tsx
  packages/console/src/onboarding/components/EarlyBirdGift/index.module.scss
  packages/console/src/onboarding/components/EarlyBirdGift/index.tsx
  packages/console/src/onboarding/components/ReachLogto/index.module.scss
  packages/console/src/onboarding/components/ReachLogto/index.tsx
  packages/console/src/onboarding/constants/index.ts
  packages/console/src/onboarding/index.tsx
  packages/console/src/onboarding/pages/Congrats/index.module.scss
  packages/console/src/onboarding/pages/Congrats/index.tsx
  packages/console/src/onboarding/pages/SignInExperience/components/Preview/index.module.scss
  packages/console/src/onboarding/pages/SignInExperience/components/Preview/index.tsx
  packages/console/src/onboarding/pages/SignInExperience/index.tsx
  packages/console/src/onboarding/pages/SignInExperience/options.tsx
  packages/console/src/onboarding/types.ts
  packages/phrases/src/locales/de/translation/admin-console/cloud.ts
  packages/phrases/src/locales/de/translation/admin-console/contact.ts
  packages/phrases/src/locales/en/translation/admin-console/cloud.ts
  packages/phrases/src/locales/en/translation/admin-console/contact.ts
  packages/phrases/src/locales/es/translation/admin-console/cloud.ts
  packages/phrases/src/locales/es/translation/admin-console/contact.ts
  packages/phrases/src/locales/fr/translation/admin-console/cloud.ts
  packages/phrases/src/locales/fr/translation/admin-console/contact.ts
  packages/phrases/src/locales/it/translation/admin-console/cloud.ts
  packages/phrases/src/locales/it/translation/admin-console/contact.ts
  packages/phrases/src/locales/ja/translation/admin-console/cloud.ts
  packages/phrases/src/locales/ja/translation/admin-console/contact.ts
  packages/phrases/src/locales/ko/translation/admin-console/cloud.ts
  packages/phrases/src/locales/ko/translation/admin-console/contact.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/contact.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/contact.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/contact.ts
  packages/phrases/src/locales/ru/translation/admin-console/cloud.ts
  packages/phrases/src/locales/ru/translation/admin-console/contact.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/cloud.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/contact.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/cloud.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/contact.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/cloud.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/contact.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/cloud.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/contact.ts
Labels: chore, size/xl

#4225 feat(console): add most popular tag for pro plan item
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/index.module.scss
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/index.tsx
Labels: feature, size/s

#4226 feat(console): add loading state for stripe actions
  packages/console/src/components/BillInfo/index.tsx
  packages/console/src/components/PaymentOverdueModal/index.tsx
  packages/console/src/ds-components/Button/index.tsx
  packages/console/src/ds-components/InlineNotification/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/MauLimitExceededNotification/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/PaymentOverdueNotification/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/SwitchPlanActionBar/index.tsx
Labels: feature, size/s

#4224 fix(console): use SWR for user endpoint
  packages/console/src/containers/TenantAccess/index.tsx
  packages/console/src/contexts/AppDataProvider.tsx
Labels: bugfix, size/s

#4217 chore(phrases): update onboarding contents
  packages/phrases/src/locales/de/translation/admin-console/cloud.ts
  packages/phrases/src/locales/en/translation/admin-console/cloud.ts
  packages/phrases/src/locales/es/translation/admin-console/cloud.ts
  packages/phrases/src/locales/fr/translation/admin-console/cloud.ts
  packages/phrases/src/locales/it/translation/admin-console/cloud.ts
  packages/phrases/src/locales/ja/translation/admin-console/cloud.ts
  packages/phrases/src/locales/ko/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/cloud.ts
  packages/phrases/src/locales/ru/translation/admin-console/cloud.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/cloud.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/cloud.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/cloud.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/cloud.ts
Labels: chore, size/s

#4230 fix(console): reset loading state on plan downgraded
  packages/console/src/pages/TenantSettings/Subscription/SwitchPlanActionBar/index.tsx
Labels: bugfix, size/xs

#4229 refactor(console): hide pro tag when related features are available
  packages/console/src/components/CreateConnectorForm/index.tsx
  packages/console/src/components/ProTag/index.module.scss
  packages/console/src/pages/Applications/components/ApplicationsPlaceholder/index.tsx
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/TenantSettings/TenantDomainSettings/index.tsx
Labels: enhancement, size/s

#4231 style(console): use large size for the webhook creation modal
  packages/console/src/pages/Webhooks/components/CreateFormModal/CreateForm.tsx
Labels: size/xs

#4212 chore(core): remove pricing feature switch
  packages/core/src/libraries/quota.ts
Labels: chore, size/xs

#4228 refactor(console): userEndpoint -> tenantEndpoint
  packages/console/src/App.tsx
  packages/console/src/components/ConnectorForm/ConfigForm/index.tsx
  packages/console/src/components/LivePreviewButton/index.tsx
  packages/console/src/components/SignInExperiencePreview/index.tsx
  packages/console/src/contexts/AppDataProvider.tsx
  packages/console/src/hooks/use-api.ts
  packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx
  packages/console/src/pages/Applications/components/Guide/index.tsx
  packages/console/src/pages/GetStarted/hook.ts
  packages/console/src/pages/TenantSettings/TenantDomainSettings/DefaultDomain/index.tsx
Labels: enhancement, size/s

#4235 refactor(phrases): update hook phrases to webhook
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-item.ts
Labels: enhancement, size/m

#4236 refactor(console): use plan id to index plan descriptions
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/index.tsx
  packages/console/src/components/PlanDescription/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/index.tsx
Labels: enhancement, size/s

#4237 chore(console): bump `@logto/cloud` version
  packages/console/package.json
  packages/console/src/components/CreateConnectorForm/Footer/index.tsx
  packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx
  packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
  packages/console/src/pages/Applications/components/CreateForm/Footer/index.tsx
  packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
  packages/console/src/pages/Webhooks/components/CreateFormModal/CreateForm.tsx
  pnpm-lock.yaml
Labels: chore, size/s

#4238 refactor(console): add dark image for free plan notification
  packages/console/src/assets/images/free-plan-notification-image.svg
  packages/console/src/pages/GetStarted/FreePlanNotification/index.tsx
Labels: enhancement, size/m

#4239 feat(console): make billing history item clickable
  packages/console/src/components/ItemPreview/index.tsx
  packages/console/src/pages/TenantSettings/BillingHistory/index.tsx
Labels: feature, size/s

#4241 fix(schemas): use pool.query to tolerate empty query results
  packages/schemas/alterations/next-1688375200-sync-cloud-m2m-to-logto-config.ts
Labels: bugfix, size/xs

#4233 fix(console): fix console dark mode logo
  packages/console/src/assets/images/cloud-logo.svg
Labels: bugfix, size/s

#4244 fix(console): should reset the form every time close CreateTenantModal
  packages/console/src/components/CreateTenantModal/index.tsx
Labels: bugfix, size/xs

#4232 refactor(console): allow editing refresh token ttl for non-m2m apps
  .changeset/allow-editing-refresh-token-ttl.md
  packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx
Labels: enhancement, size/xs

#4245 fix(core): exclude demo connector for quota
  packages/core/src/libraries/quota.ts
Labels: bugfix, size/s

#4246 refactor(console): sort quota list items
  packages/console/src/components/PlanQuotaList/index.tsx
  packages/console/src/consts/plan-quotas.ts
  packages/console/src/hooks/use-subscription-plans.ts
  packages/console/src/pages/TenantSettings/components/NotEligibleSwitchPlanModalContent/index.tsx
  packages/console/src/utils/sort.ts
Labels: enhancement, size/s

#4251 feat(console): report LinkedIn conversion
  packages/console/src/components/ReportConversion/index.tsx
  packages/console/src/components/ReportConversion/utils.ts
  packages/console/src/include.d/gtag.d.ts
  packages/console/src/include.d/tags.d.ts
  packages/console/src/onboarding/constants/index.ts
  packages/console/src/onboarding/index.tsx
  packages/console/src/onboarding/utils.ts
Labels: feature, size/m

#4253 fix(connector): manually add a changelog file for smsaero connector
  packages/connectors/connector-smsaero/CHANGELOG.md
Labels: bugfix, size/xs

#4248 refactor(phrases): update current plan form card description
  packages/phrases/src/locales/de/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/index.ts
Labels: enhancement, size/s

#4254 refactor(test): add `expectNavigation()`
  packages/integration-tests/src/tests/ui/bootstrap.test.ts
  packages/integration-tests/src/tests/ui/user-management.test.ts
  packages/integration-tests/src/tests/ui/webhooks.test.ts
  packages/integration-tests/src/ui-helpers/index.ts
  packages/integration-tests/src/utils.ts
Labels: enhancement, size/s

#4250 refactor(console,phrases): update plan selection cta phrases
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/SwitchPlanActionBar/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/de/translation/admin-console/upsell.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/en/translation/admin-console/upsell.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/es/translation/admin-console/upsell.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/upsell.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/it/translation/admin-console/upsell.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/upsell.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/upsell.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/upsell.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/upsell.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/upsell.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/upsell.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/upsell.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/upsell.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/upsell.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/upsell.ts
Labels: enhancement, size/s

#4249 style(console): fix free plan notification margin-bottom
  packages/console/src/pages/GetStarted/FreePlanNotification/index.module.scss
Labels: size/xs

#4252 chore(console): update quota table row style rules
  packages/console/src/pages/TenantSettings/Subscription/PlanQuotaTable/index.tsx
Labels: chore, size/xs

#4257 refactor(console): update upgrade reminder for early adopters
  packages/console/src/pages/TenantSettings/components/NotEligibleSwitchPlanModalContent/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/index.ts
Labels: enhancement, size/s

#4263 refactor(console): report reddit conversion
  packages/console/jest.setup.ts
  packages/console/src/components/ReportConversion/index.tsx
  packages/console/src/components/ReportConversion/utils.test.ts
  packages/console/src/components/ReportConversion/utils.ts
  packages/console/src/include.d/tags.d.ts
Labels: enhancement, size/m

#4256 chore(connector): remove Apple/SMTP connector README files CHN part
  packages/connectors/connector-apple/README.md
  packages/connectors/connector-smtp/README.md
Labels: chore, size/m

#4265 feat(cli): `translate sync-keys` command
  .changeset/sixty-cows-hang.md
  package.json
  packages/cli/package.json
  packages/cli/src/commands/translate/index.ts
  packages/cli/src/commands/translate/sync-keys/index.ts
  packages/cli/src/commands/translate/sync-keys/utils.ts
  packages/phrases/package.json
  packages/phrases/src/locales/de/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-table.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#4267 refactor(cli): use `tryThat()` to enforce exit
  packages/cli/src/commands/translate/sync-keys/utils.ts
Labels: enhancement, size/xs

#4266 style(console): add color token for upsell tags
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/index.module.scss
  packages/console/src/components/ProTag/index.module.scss
  packages/toolkit/core-kit/scss/_console-themes.scss
Labels: size/xs

#4268 fix(console): display guidance on application created
  packages/console/src/pages/ApplicationDetails/index.tsx
Labels: bugfix, size/xs

#4258 refactor(console): get real time email service usage
  packages/console/src/pages/ConnectorDetails/ConnectorContent/index.tsx
  packages/console/src/pages/ConnectorDetails/EmailUsage/index.tsx
  packages/console/src/pages/ConnectorDetails/index.tsx
Labels: enhancement, size/s
