Repository logto-io/logto, pull requests merged in 2023-06, with the labels that each got.

#3937 chore(phrases): update webhook phrases
  packages/phrases/src/locales/de/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/de/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/en/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/en/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/es/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/es/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/fr/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/it/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/it/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/ja/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/ko/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/ru/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/webhooks.ts
Labels: chore, size/m

#3931 chore(console): remove get started progress dropdown
  packages/console/src/containers/AppContent/components/Topbar/index.tsx
  packages/console/src/pages/GetStarted/components/GetStartedProgress/index.module.scss
  packages/console/src/pages/GetStarted/components/GetStartedProgress/index.tsx
Labels: chore, size/m

#3916 fix(core): trigger reset password hook
  .changeset/silly-impalas-pump.md
  packages/core/src/libraries/hook/index.test.ts
  packages/core/src/libraries/hook/index.ts
  packages/core/src/routes/interaction/actions/submit-interaction.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/core/src/routes/interaction/consent.ts
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/middleware/koa-interaction-details.ts
  packages/core/src/routes/interaction/middleware/koa-interaction-hooks.ts
  packages/core/src/routes/interaction/middleware/koa-interaction-sie.ts
  packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.ts
  packages/integration-tests/src/helpers/interactions.ts
  packages/integration-tests/src/tests/api/hook/hook.trigger.test.ts
Labels: bugfix, size/l

#3932 chore: add changeset for webhook features
  .changeset/pink-eggs-divide.md
Labels: chore, size/s

#3939 fix(core): verify an empty string password should return 400 instead of 500
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
  packages/integration-tests/src/api/admin-user.ts
  packages/integration-tests/src/tests/api/admin-user.test.ts
Labels: bugfix, size/s

#3919 feat(core): integrate with cloudflare
  .changeset/spicy-nails-share.md
  .github/workflows/integration-test.yml
  packages/core/src/__mocks__/domain.ts
  packages/core/src/__mocks__/system.ts
  packages/core/src/index.ts
  packages/core/src/libraries/domain.test.ts
  packages/core/src/libraries/domain.ts
  packages/core/src/queries/system.ts
  packages/core/src/routes/domain.test.ts
  packages/core/src/routes/domain.ts
  packages/core/src/tenants/Libraries.ts
  packages/core/src/tenants/SystemContex.test.ts
  packages/core/src/tenants/SystemContext.ts
  packages/core/src/utils/cloudflare/consts.ts
  packages/core/src/utils/cloudflare/index.ts
  packages/core/src/utils/cloudflare/mock.ts
  packages/core/src/utils/cloudflare/types.ts
  packages/core/src/utils/cloudflare/utils.ts
  packages/phrases/src/locales/de/errors/domain.ts
  packages/phrases/src/locales/en/errors/domain.ts
  packages/phrases/src/locales/es/errors/domain.ts
  packages/phrases/src/locales/fr/errors/domain.ts
  packages/phrases/src/locales/it/errors/domain.ts
  packages/phrases/src/locales/ja/errors/domain.ts
  packages/phrases/src/locales/ko/errors/domain.ts
  packages/phrases/src/locales/pl-pl/errors/domain.ts
  packages/phrases/src/locales/pt-br/errors/domain.ts
  packages/phrases/src/locales/pt-pt/errors/domain.ts
  packages/phrases/src/locales/ru/errors/domain.ts
  packages/phrases/src/locales/tr-tr/errors/domain.ts
  packages/phrases/src/locales/zh-cn/errors/domain.ts
  packages/phrases/src/locales/zh-hk/errors/domain.ts
  packages/phrases/src/locales/zh-tw/errors/domain.ts
  packages/schemas/src/types/domain.ts
Labels: feature, size/xl

#3934 fix(core): get cf id before insert
  packages/core/src/libraries/domain.test.ts
  packages/core/src/libraries/domain.ts
  packages/core/src/routes/domain.test.ts
  packages/core/src/routes/domain.ts
Labels: bugfix, size/s

#3945 test: improve ui test stability and remove unnecessary code
  packages/integration-tests/src/tests/ui/user-management.test.ts
  packages/integration-tests/src/tests/ui/webhooks.test.ts
  packages/integration-tests/user-conflict-email.png
Labels: testing, size/xs

#3948 fix(core): fix url resolver for cloudflare
  packages/core/src/utils/cloudflare/index.ts
Labels: bugfix, size/s

#3920 fix(connector): signature method for both Aliyun DM and SMS
  .changeset/odd-pumpkins-poke.md
  packages/connectors/connector-aliyun-dm/src/utils.ts
  packages/connectors/connector-aliyun-sms/src/utils.ts
Labels: bugfix, size/s

#3950 refactor(core): persist dns records to database
  packages/core/src/libraries/domain.test.ts
  packages/core/src/libraries/domain.ts
  packages/core/src/utils/cloudflare/utils.ts
Labels: enhancement, size/s

#3952 refactor(console): replace tsx svg components with svg files
  packages/console/src/assets/images/bar-graph.svg
  packages/console/src/assets/images/bolt.svg
  packages/console/src/assets/images/box.svg
  packages/console/src/assets/images/connection.svg
  packages/console/src/assets/images/contact.svg
  packages/console/src/assets/images/document.svg
  packages/console/src/assets/images/list.svg
  packages/console/src/assets/images/resource.svg
  packages/console/src/assets/images/web.svg
  packages/console/src/containers/ConsoleContent/Sidebar/hook.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/icons/BarGraph.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/icons/Bolt.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/icons/Box.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/icons/Cloud.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/icons/Connection.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/icons/Contact.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/icons/Document.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/icons/Gear.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/icons/List.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/icons/UserProfile.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/icons/Web.tsx
Labels: enhancement, size/m

#3953 fix(core): delete cloudflare custom domain
  packages/core/src/libraries/domain.test.ts
  packages/core/src/libraries/domain.ts
  packages/core/src/routes/domain.test.ts
  packages/core/src/routes/domain.ts
  packages/core/src/utils/cloudflare/index.ts
  packages/phrases/src/locales/de/errors/domain.ts
  packages/phrases/src/locales/en/errors/domain.ts
  packages/phrases/src/locales/es/errors/domain.ts
  packages/phrases/src/locales/fr/errors/domain.ts
  packages/phrases/src/locales/it/errors/domain.ts
  packages/phrases/src/locales/ja/errors/domain.ts
  packages/phrases/src/locales/ko/errors/domain.ts
  packages/phrases/src/locales/pl-pl/errors/domain.ts
  packages/phrases/src/locales/pt-br/errors/domain.ts
  packages/phrases/src/locales/pt-pt/errors/domain.ts
  packages/phrases/src/locales/ru/errors/domain.ts
  packages/phrases/src/locales/tr-tr/errors/domain.ts
  packages/phrases/src/locales/zh-cn/errors/domain.ts
  packages/phrases/src/locales/zh-hk/errors/domain.ts
  packages/phrases/src/locales/zh-tw/errors/domain.ts
Labels: bugfix, size/m

#3947 fix(console): use correct vanillajs isAuthenticated method in guide
  packages/console/src/assets/docs/tutorial/integrate-sdk/vanilla.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/vanilla_zh-cn.mdx
Labels: bugfix, size/xs

#3960 chore(phrases): update domain phrases for console
  packages/phrases/src/locales/de/translation/admin-console/domain.ts
  packages/phrases/src/locales/en/translation/admin-console/domain.ts
  packages/phrases/src/locales/es/translation/admin-console/domain.ts
  packages/phrases/src/locales/fr/translation/admin-console/domain.ts
  packages/phrases/src/locales/it/translation/admin-console/domain.ts
  packages/phrases/src/locales/ja/translation/admin-console/domain.ts
  packages/phrases/src/locales/ko/translation/admin-console/domain.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/domain.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/domain.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/domain.ts
  packages/phrases/src/locales/ru/translation/admin-console/domain.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/domain.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/domain.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/domain.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/domain.ts
Labels: chore, size/xl

#3967 feat(phrases): tenant settings page phrases
  packages/phrases/src/locales/de/translation/admin-console/index.ts
  packages/phrases/src/locales/de/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/de/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/en/translation/admin-console/index.ts
  packages/phrases/src/locales/en/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/en/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/es/translation/admin-console/index.ts
  packages/phrases/src/locales/es/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/es/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/fr/translation/admin-console/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/fr/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/it/translation/admin-console/index.ts
  packages/phrases/src/locales/it/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/it/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/ja/translation/admin-console/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/ja/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/ko/translation/admin-console/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/ko/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/ru/translation/admin-console/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/ru/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tenant-settings.ts
Labels: feature, size/l

#3964 refactor: stringify error before report to AppInsights
  packages/app-insights/src/node.ts
Labels: enhancement, size/s

#3968 refactor(console): card selector
  packages/console/src/components/CardSelector/CardSelector.tsx
  packages/console/src/components/CardSelector/MultiCardSelector/CardItem.module.scss
  packages/console/src/components/CardSelector/MultiCardSelector/CardItem.tsx
  packages/console/src/components/CardSelector/MultiCardSelector/index.module.scss
  packages/console/src/components/CardSelector/MultiCardSelector/index.tsx
  packages/console/src/components/CardSelector/index.tsx
  packages/console/src/components/CardSelector/types.ts
  packages/console/src/onboarding/pages/About/index.tsx
  packages/console/src/onboarding/pages/About/options.tsx
  packages/console/src/onboarding/pages/SignInExperience/components/SocialSelector/index.tsx
  packages/console/src/onboarding/pages/SignInExperience/index.tsx
  packages/console/src/onboarding/pages/SignInExperience/options.tsx
  packages/console/src/onboarding/pages/Welcome/index.tsx
  packages/console/src/onboarding/pages/Welcome/options.tsx
Labels: enhancement, size/s

#3922 feat: support default API Resource
  .changeset/small-hats-confess.md
  packages/console/src/pages/ApiResourceDetails/ApiResourceSettings/index.tsx
  packages/console/src/pages/ApiResourceDetails/index.module.scss
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/ApplicationDetails/index.module.scss
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/core/src/__mocks__/index.ts
  packages/core/src/errors/SlonikError/index.ts
  packages/core/src/oidc/init.ts
  packages/core/src/queries/resource.ts
  packages/core/src/routes/resource.test.ts
  packages/core/src/routes/resource.ts
  packages/integration-tests/src/api/resource.ts
  packages/integration-tests/src/tests/api/resource.test.ts
  packages/phrases/src/locales/de/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/en/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/es/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/fr/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/it/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/ja/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/ko/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/ru/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/api-resources.ts
  packages/schemas/alterations/next-1685285719-support-default-resource.ts
  packages/schemas/tables/resources.sql
Labels: feature, size/l

#3969 chore(phrases): add tenant settings tab phrase for domains
  packages/phrases/src/locales/de/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/en/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/es/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/fr/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/it/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/ja/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/ko/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/ru/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tenant-settings.ts
Labels: chore, size/s

#3970 refactor(core): return 422 if failed to send a webhook test payload
  packages/core/src/libraries/hook/index.test.ts
  packages/core/src/libraries/hook/index.ts
  packages/core/src/routes/hook.ts
  packages/integration-tests/src/tests/api/hook/hook.testing.test.ts
Labels: enhancement, size/xs

#3971 fix(console): hide some log headers for webhook event
  packages/console/src/pages/AuditLogDetails/index.tsx
  packages/schemas/src/types/log/hook.ts
Labels: bugfix, size/s

#3972 refactor: add learn more link for Default API switch
  packages/console/src/components/Switch/index.tsx
  packages/console/src/onboarding/constants/index.ts
  packages/console/src/pages/ApiResourceDetails/ApiResourceSettings/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/de/translation/admin-console/connectors.ts
  packages/phrases/src/locales/en/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/en/translation/admin-console/connectors.ts
  packages/phrases/src/locales/es/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/es/translation/admin-console/connectors.ts
  packages/phrases/src/locales/fr/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/fr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/it/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/it/translation/admin-console/connectors.ts
  packages/phrases/src/locales/ja/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/ja/translation/admin-console/connectors.ts
  packages/phrases/src/locales/ko/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/connectors.ts
  packages/phrases/src/locales/ru/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/ru/translation/admin-console/connectors.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/connectors.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/connectors.ts
Labels: enhancement, size/s

#3930 chore(console): reorganize console page
  packages/console/src/assets/images/contact-us.svg
  packages/console/src/assets/images/document-nav-button.svg
  packages/console/src/containers/AppContent/components/Topbar/Contact/ContactModal/hook.tsx
  packages/console/src/containers/AppContent/components/Topbar/Contact/ContactModal/index.module.scss
  packages/console/src/containers/AppContent/components/Topbar/Contact/ContactModal/index.tsx
  packages/console/src/containers/AppContent/components/Topbar/Contact/index.tsx
  packages/console/src/containers/AppContent/components/Topbar/DocumentNavButton/index.module.scss
  packages/console/src/containers/AppContent/components/Topbar/DocumentNavButton/index.tsx
  packages/console/src/containers/AppContent/components/Topbar/UserInfo/SubMenu/index.module.scss
  packages/console/src/containers/AppContent/components/Topbar/UserInfo/SubMenu/index.tsx
  packages/console/src/containers/AppContent/components/Topbar/UserInfo/UserInfoSkeleton/index.module.scss
  packages/console/src/containers/AppContent/components/Topbar/UserInfo/UserInfoSkeleton/index.tsx
  packages/console/src/containers/AppContent/components/Topbar/UserInfo/index.module.scss
  packages/console/src/containers/AppContent/components/Topbar/UserInfo/index.tsx
  packages/console/src/containers/AppContent/components/Topbar/index.module.scss
  packages/console/src/containers/AppContent/components/Topbar/index.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/components/Contact/index.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/hook.tsx
  packages/console/src/onboarding/components/EarlyBirdGift/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/contact.ts
  packages/phrases/src/locales/de/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/en/translation/admin-console/contact.ts
  packages/phrases/src/locales/en/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/es/translation/admin-console/contact.ts
  packages/phrases/src/locales/es/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/fr/translation/admin-console/contact.ts
  packages/phrases/src/locales/fr/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/it/translation/admin-console/contact.ts
  packages/phrases/src/locales/it/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/ja/translation/admin-console/contact.ts
  packages/phrases/src/locales/ja/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/ko/translation/admin-console/contact.ts
  packages/phrases/src/locales/ko/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/contact.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/contact.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/contact.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/ru/translation/admin-console/contact.ts
  packages/phrases/src/locales/ru/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/contact.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/contact.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/contact.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/contact.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tab-sections.ts
Labels: chore, size/xl

#3973 refactor(core): refine webhook log payload
  packages/core/src/libraries/hook/index.test.ts
  packages/core/src/libraries/hook/index.ts
Labels: enhancement, size/s

#3979 refactor(core): remove message id from hook request headers
  .changeset/pink-eggs-divide.md
  packages/core/src/libraries/hook/utils.test.ts
  packages/core/src/libraries/hook/utils.ts
Labels: enhancement, size/s

#3984 fix(console): fix fallback image in image uploader
  packages/console/src/components/Uploader/ImageUploader/index.module.scss
  packages/console/src/components/Uploader/ImageUploader/index.tsx
Labels: bugfix, size/s

#3975 feat(console): add tenant settings page
  packages/console/src/assets/images/gear.svg
  packages/console/src/consts/page-tabs.ts
  packages/console/src/consts/tenant-settings.ts
  packages/console/src/containers/ConsoleContent/Sidebar/hook.tsx
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/pages/TenantSettings/index.module.scss
  packages/console/src/pages/TenantSettings/index.tsx
  packages/console/src/pages/TenantSettings/tabs/TenantBasicSettings/index.tsx
  packages/console/src/pages/TenantSettings/tabs/TenantDomainSettings/index.tsx
Labels: feature, size/m

#3961 feat(console): add default domain content for domains page
  packages/console/src/pages/TenantSettings/tabs/TenantDomainSettings/components/DefaultDomain/index.module.scss
  packages/console/src/pages/TenantSettings/tabs/TenantDomainSettings/components/DefaultDomain/index.tsx
  packages/console/src/pages/TenantSettings/tabs/TenantDomainSettings/index.tsx
Labels: feature, size/s

#3976 fix(console): doc button and get help link
  packages/console/src/containers/AppContent/components/Topbar/Contact/ContactModal/index.module.scss
  packages/console/src/containers/AppContent/components/Topbar/Contact/ContactModal/index.tsx
  packages/console/src/containers/AppContent/components/Topbar/DocumentNavButton/index.tsx
Labels: bugfix, size/s

#3962 feat(console): add custom domain form
  packages/console/src/pages/TenantSettings/tabs/TenantDomainSettings/components/AddDomainForm/index.module.scss
  packages/console/src/pages/TenantSettings/tabs/TenantDomainSettings/components/AddDomainForm/index.tsx
  packages/console/src/pages/TenantSettings/tabs/TenantDomainSettings/index.module.scss
  packages/console/src/pages/TenantSettings/tabs/TenantDomainSettings/index.tsx
Labels: feature, size/m

#3982 fix(console): fix github avatar broken issue
  packages/console/src/components/ImageWithErrorFallback/index.tsx
  packages/core/src/middleware/koa-security-headers.ts
Labels: bugfix, size/s

#3985 fix: clone error for AppInsights
  packages/app-insights/src/node.ts
Labels: bugfix, size/s

#3981 fix(console): close confirm modal on the location path changed
  packages/console/src/contexts/AppConfirmModalProvider/index.tsx
  packages/console/src/pages/WebhookDetails/index.tsx
Labels: bugfix, size/s

#3980 refactor(phrases): update custom domain phrases
  packages/phrases/src/locales/de/translation/admin-console/domain.ts
  packages/phrases/src/locales/en/translation/admin-console/domain.ts
  packages/phrases/src/locales/es/translation/admin-console/domain.ts
  packages/phrases/src/locales/fr/translation/admin-console/domain.ts
  packages/phrases/src/locales/it/translation/admin-console/domain.ts
  packages/phrases/src/locales/ja/translation/admin-console/domain.ts
  packages/phrases/src/locales/ko/translation/admin-console/domain.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/domain.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/domain.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/domain.ts
  packages/phrases/src/locales/ru/translation/admin-console/domain.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/domain.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/domain.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/domain.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/domain.ts
Labels: enhancement, size/l

#3989 ci: fix deploy workflow
  .github/workflows/release.yml
Labels: size/xs

#3965 feat(console): implement active custom domain process
  packages/console/src/components/CopyToClipboard/index.module.scss
  packages/console/src/components/CopyToClipboard/index.tsx
  packages/console/src/pages/TenantSettings/tabs/TenantDomainSettings/components/CustomDomain/components/ActivationProcess/components/DnsRecordsTable/index.module.scss
  packages/console/src/pages/TenantSettings/tabs/TenantDomainSettings/components/CustomDomain/components/ActivationProcess/components/DnsRecordsTable/index.tsx
  packages/console/src/pages/TenantSettings/tabs/TenantDomainSettings/components/CustomDomain/components/ActivationProcess/components/Step/index.module.scss
  packages/console/src/pages/TenantSettings/tabs/TenantDomainSettings/components/CustomDomain/components/ActivationProcess/components/Step/index.tsx
  packages/console/src/pages/TenantSettings/tabs/TenantDomainSettings/components/CustomDomain/components/ActivationProcess/index.module.scss
  packages/console/src/pages/TenantSettings/tabs/TenantDomainSettings/components/CustomDomain/components/ActivationProcess/index.tsx
  packages/console/src/pages/TenantSettings/tabs/TenantDomainSettings/components/CustomDomain/index.tsx
  packages/console/src/pages/TenantSettings/tabs/TenantDomainSettings/index.tsx
Labels: feature, size/l

#3955 fix(cli): polish translate prompts
  packages/cli/src/commands/translate/openai.ts
  packages/cli/src/commands/translate/prompts.ts
Labels: bugfix, size/s

#3991 fix(console): use `process.env.NODE_ENV` to get node env for console
  packages/console/src/App.tsx
  packages/console/src/consts/cloud.ts
  packages/console/src/consts/env.ts
  packages/console/src/consts/tenant-settings.ts
  packages/console/src/consts/tenants.ts
  packages/console/src/consts/webhooks.ts
  packages/console/src/containers/AppContent/components/Topbar/Contact/ContactModal/index.tsx
  packages/console/src/containers/AppContent/components/Topbar/index.tsx
  packages/console/src/containers/AppContent/index.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/hook.tsx
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/containers/TenantAppContainer/index.tsx
  packages/console/src/contexts/TenantsProvider.tsx
  packages/console/src/onboarding/hooks/use-user-onboarding-data.ts
  packages/console/src/pages/Profile/components/BasicUserInfoSection/index.tsx
  packages/console/src/pages/Profile/index.tsx
  packages/console/src/pages/SignInExperience/index.tsx
  packages/console/src/pages/TenantSettings/index.tsx
Labels: bugfix, size/s

#3986 fix(core,schemas): use http method for cloudflare ssl
  packages/core/src/libraries/domain.test.ts
  packages/core/src/libraries/domain.ts
  packages/core/src/utils/cloudflare/index.ts
  packages/core/src/utils/cloudflare/utils.ts
  packages/schemas/src/foundations/jsonb-types.ts
Labels: bugfix, size/s

#3993 refactor(phrases): update custom domain notice phrases
  packages/phrases/src/locales/de/translation/admin-console/domain.ts
  packages/phrases/src/locales/en/translation/admin-console/domain.ts
  packages/phrases/src/locales/es/translation/admin-console/domain.ts
  packages/phrases/src/locales/fr/translation/admin-console/domain.ts
  packages/phrases/src/locales/it/translation/admin-console/domain.ts
  packages/phrases/src/locales/ja/translation/admin-console/domain.ts
  packages/phrases/src/locales/ko/translation/admin-console/domain.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/domain.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/domain.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/domain.ts
  packages/phrases/src/locales/ru/translation/admin-console/domain.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/domain.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/domain.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/domain.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/domain.ts
Labels: enhancement, size/m

#3958 fix(schemas): set domain status enum guard
  packages/core/src/__mocks__/domain.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/types/domain.ts
  packages/schemas/tables/domains.sql
Labels: bugfix, size/s

#3999 refactor(console): remove redundant domain status guard
  packages/console/src/pages/TenantSettings/tabs/TenantDomainSettings/components/CustomDomain/components/ActivationProcess/index.tsx
  packages/console/src/pages/TenantSettings/tabs/TenantDomainSettings/components/CustomDomain/components/CustomDomainHeader/index.tsx
  packages/console/src/pages/TenantSettings/tabs/TenantDomainSettings/components/CustomDomain/utils.ts
Labels: enhancement, size/s

#4002 feat(phrases): add phrases for tenant selector and create modal
  packages/phrases/src/locales/de/translation/admin-console/cloud.ts
  packages/phrases/src/locales/de/translation/admin-console/index.ts
  packages/phrases/src/locales/de/translation/admin-console/tenants.ts
  packages/phrases/src/locales/en/translation/admin-console/cloud.ts
  packages/phrases/src/locales/en/translation/admin-console/index.ts
  packages/phrases/src/locales/en/translation/admin-console/tenants.ts
  packages/phrases/src/locales/es/translation/admin-console/cloud.ts
  packages/phrases/src/locales/es/translation/admin-console/index.ts
  packages/phrases/src/locales/es/translation/admin-console/tenants.ts
  packages/phrases/src/locales/fr/translation/admin-console/cloud.ts
  packages/phrases/src/locales/fr/translation/admin-console/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/it/translation/admin-console/cloud.ts
  packages/phrases/src/locales/it/translation/admin-console/index.ts
  packages/phrases/src/locales/it/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ja/translation/admin-console/cloud.ts
  packages/phrases/src/locales/ja/translation/admin-console/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ko/translation/admin-console/cloud.ts
  packages/phrases/src/locales/ko/translation/admin-console/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ru/translation/admin-console/cloud.ts
  packages/phrases/src/locales/ru/translation/admin-console/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/tenants.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/cloud.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/cloud.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/cloud.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/cloud.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tenants.ts
Labels: feature, size/l

#4000 fix(cloud): delete tenant api
  packages/cloud/src/routes/tenants.test.ts
  packages/cloud/src/routes/tenants.ts
  packages/integration-tests/src/tests/api-cloud/tenant.test.ts
Labels: bugfix, size/s

#4006 refactor(phrases): update change endpoint notice for custom domain
  packages/phrases/src/locales/de/translation/admin-console/domain.ts
  packages/phrases/src/locales/en/translation/admin-console/domain.ts
  packages/phrases/src/locales/es/translation/admin-console/domain.ts
  packages/phrases/src/locales/fr/translation/admin-console/domain.ts
  packages/phrases/src/locales/it/translation/admin-console/domain.ts
  packages/phrases/src/locales/ja/translation/admin-console/domain.ts
  packages/phrases/src/locales/ko/translation/admin-console/domain.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/domain.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/domain.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/domain.ts
  packages/phrases/src/locales/ru/translation/admin-console/domain.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/domain.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/domain.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/domain.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/domain.ts
Labels: enhancement, size/m

#3990 refactor(ui): add utm params to powered by link
  packages/ui/src/components/LogtoSignature/index.tsx
Labels: enhancement, size/xs

#3994 feat(console): add activation error for custom domain
  packages/console/src/components/InlineNotification/index.module.scss
  packages/console/src/consts/custom-domain.ts
  packages/console/src/pages/TenantSettings/TenantDomainSettings/CustomDomain/ActivationProcess/index.module.scss
  packages/console/src/pages/TenantSettings/TenantDomainSettings/CustomDomain/ActivationProcess/index.tsx
  packages/console/src/pages/TenantSettings/TenantDomainSettings/index.tsx
Labels: feature, size/s

#3992 feat(console): add update endpoint notice for custom domain
  packages/console/src/components/InlineNotification/index.tsx
  packages/console/src/pages/TenantSettings/TenantDomainSettings/CustomDomain/index.module.scss
  packages/console/src/pages/TenantSettings/TenantDomainSettings/CustomDomain/index.tsx
Labels: feature, size/s

#3998 chore: adjust the code-owner of major packages
  .github/CODEOWNERS
Labels: chore, size/xs

#4005 feat(core,schemas): get fallback origin from cf api
  .github/workflows/integration-test.yml
  packages/core/src/__mocks__/system.ts
  packages/core/src/libraries/domain.test.ts
  packages/core/src/libraries/domain.ts
  packages/core/src/utils/cloudflare/index.ts
  packages/core/src/utils/cloudflare/mock.ts
  packages/core/src/utils/cloudflare/types.ts
  packages/schemas/src/types/system.ts
Labels: feature, size/m

#4012 refactor(console): remove redundant ssl dns config for custom domain
  packages/console/src/pages/TenantSettings/TenantDomainSettings/CustomDomain/ActivationProcess/index.tsx
Labels: enhancement, size/s

#4013 feat(console): enable custom domain feature
  packages/console/src/containers/ConsoleContent/Sidebar/hook.tsx
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/pages/TenantSettings/index.tsx
Labels: feature, size/s

#4009 refactor(core): apply no-unused-modules
  packages/core/package.json
  packages/core/src/__mocks__/custom-phrase.ts
  packages/core/src/__mocks__/interactions.ts
  packages/core/src/caches/well-known.ts
  packages/core/src/env-set/__mocks__/check-alteration-state.ts
  packages/core/src/env-set/utils.ts
  packages/core/src/libraries/__mocks__/logto-config.ts
  packages/core/src/libraries/application.ts
  packages/core/src/libraries/sign-in-experience/types.ts
  packages/core/src/libraries/social.ts
  packages/core/src/libraries/verification-status.ts
  packages/core/src/middleware/koa-pagination.ts
  packages/core/src/oidc/scope.ts
  packages/core/src/queries/log.ts
  packages/core/src/routes/interaction/types/index.ts
  packages/core/src/routes/interaction/utils/interaction.ts
  packages/core/src/routes/swagger.test.ts
  packages/core/src/routes/types.ts
  packages/core/src/utils/assert-that.ts
  packages/core/src/utils/connectors/types.ts
  packages/core/src/utils/search.ts
  packages/core/src/utils/storage/types.ts
Labels: enhancement, size/m

#4010 refactor(console): apply no-unused-modules
  packages/console/package.json
  packages/console/src/components/EmptyDataPlaceholder/index.tsx
  packages/console/src/components/IconButton/index.tsx
  packages/console/src/components/MultiTextInput/utils.ts
  packages/console/src/components/RoleScopesTransfer/components/TargetScopeItem/index.tsx
  packages/console/src/components/Uploader/index.tsx
  packages/console/src/components/VerificationCodeInput/index.tsx
  packages/console/src/contexts/AppConfirmModalProvider/index.tsx
  packages/console/src/contexts/AppEndpointsProvider.tsx
  packages/console/src/contexts/TenantsProvider.tsx
  packages/console/src/hooks/use-confirm-modal.ts
  packages/console/src/hooks/use-user-preferences.ts
  packages/console/src/onboarding/constants/index.ts
  packages/console/src/onboarding/pages/SignInExperience/index.tsx
  packages/console/src/onboarding/types.ts
  packages/console/src/pages/Connectors/components/ConnectorForm/hooks.tsx
  packages/console/src/pages/Dashboard/types.ts
  packages/console/src/pages/Profile/components/CardContent/index.tsx
  packages/console/src/pages/Profile/containers/BasicUserInfoUpdateModal/index.tsx
  packages/console/src/pages/Profile/containers/VerificationCodeModal/index.tsx
  packages/console/src/pages/SignInExperience/tabs/Branding/BrandingForm.tsx
  packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/use-language-editor-context.ts
  packages/console/src/pages/Webhooks/components/BasicWebhookForm/index.tsx
  packages/ui/src/containers/TermsAndPrivacy/TermsAndPrivacyConfirmModalContent/index.tsx
Labels: enhancement, size/s

#3938 feat(console): add tenant settings page
  packages/console/src/components/RadioGroup/Radio.module.scss
  packages/console/src/components/RadioGroup/Radio.tsx
  packages/console/src/components/RadioGroup/index.module.scss
  packages/console/src/components/RadioGroup/index.tsx
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/contexts/TenantsProvider.tsx
  packages/console/src/hooks/use-tenants.ts
  packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/index.module.scss
  packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/index.module.scss
  packages/console/src/pages/TenantSettings/TenantBasicSettings/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/types.ts
  packages/console/src/pages/TenantSettings/index.module.scss
  packages/console/src/pages/TenantSettings/index.tsx
Labels: feature, size/l

#4014 chore(console): add appInsights for custom domain page
  packages/console/src/pages/TenantSettings/TenantDomainSettings/index.tsx
Labels: chore, size/xs

#3996 feat: enable OIDC introspection endpoint
  packages/core/src/oidc/init.ts
Labels: enhancement, feature, size/xs

#4016 feat(console): add tenant deletion card and delete modal
  packages/console/src/components/DeleteConfirmModal/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/DeleteCard/index.module.scss
  packages/console/src/pages/TenantSettings/TenantBasicSettings/DeleteCard/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/DeleteModal/index.module.scss
  packages/console/src/pages/TenantSettings/TenantBasicSettings/DeleteModal/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/types.ts
  packages/phrases/src/locales/de/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/de/translation/admin-console/tenants.ts
  packages/phrases/src/locales/en/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/en/translation/admin-console/tenants.ts
  packages/phrases/src/locales/es/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/es/translation/admin-console/tenants.ts
  packages/phrases/src/locales/fr/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/fr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/it/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/it/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ja/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/ja/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ko/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/ko/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ru/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/ru/translation/admin-console/tenants.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tenants.ts
Labels: feature, size/l

#4004 feat(schemas,cloud): align tenant types
  packages/cli/src/commands/database/seed/tenant.ts
  packages/cloud/package.json
  packages/cloud/src/libraries/tenants.ts
  packages/cloud/src/queries/tenants.ts
  packages/cloud/src/routes/tenants.test.ts
  packages/cloud/src/routes/tenants.ts
  packages/cloud/src/test-utils/libraries.ts
  packages/console/src/cloud/pages/Main/Redirect.tsx
  packages/console/src/cloud/pages/Main/Tenants.tsx
  packages/console/src/cloud/pages/Main/index.tsx
  packages/console/src/contexts/TenantsProvider.tsx
  packages/console/src/hooks/use-tenants.ts
  packages/console/src/pages/TenantSettings/TenantBasicSettings/DeleteModal/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/types.ts
  packages/integration-tests/src/api/tenant.ts
  packages/integration-tests/src/tests/api-cloud/tenant.test.ts
  packages/schemas/package.json
  packages/schemas/src/models/tenants.ts
  packages/schemas/src/seeds/tenant.ts
  packages/schemas/src/types/index.ts
  packages/schemas/src/types/tenant.ts
  pnpm-lock.yaml
Labels: feature, size/m

#4021 refactor(phrases): update custom domain related phrases
  packages/console/src/pages/TenantSettings/TenantDomainSettings/CustomDomain/ActivationProcess/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/domain.ts
  packages/phrases/src/locales/de/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/en/translation/admin-console/domain.ts
  packages/phrases/src/locales/en/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/es/translation/admin-console/domain.ts
  packages/phrases/src/locales/es/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/fr/translation/admin-console/domain.ts
  packages/phrases/src/locales/fr/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/it/translation/admin-console/domain.ts
  packages/phrases/src/locales/it/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/ja/translation/admin-console/domain.ts
  packages/phrases/src/locales/ja/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/ko/translation/admin-console/domain.ts
  packages/phrases/src/locales/ko/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/domain.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/domain.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/domain.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/ru/translation/admin-console/domain.ts
  packages/phrases/src/locales/ru/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/domain.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/domain.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/domain.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/domain.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tenant-settings.ts
Labels: enhancement, size/m

#4023 feat(console): enable icon in modal header
  packages/console/src/components/ModalLayout/index.module.scss
  packages/console/src/components/ModalLayout/index.tsx
Labels: feature, size/s

#4029 fix(console): reset form state when the submit handler throws
  packages/console/src/mdx-components/UriInputField/index.tsx
  packages/console/src/onboarding/pages/About/index.tsx
  packages/console/src/onboarding/pages/SignInExperience/index.tsx
  packages/console/src/onboarding/pages/Welcome/index.tsx
  packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx
  packages/console/src/pages/ApiResourceDetails/ApiResourceSettings/index.tsx
  packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx
  packages/console/src/pages/ConnectorDetails/components/SenderTester/index.tsx
  packages/console/src/pages/Connectors/components/Guide/index.tsx
  packages/console/src/pages/Profile/containers/LinkEmailModal/index.tsx
  packages/console/src/pages/RoleDetails/RoleSettings/index.tsx
  packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
  packages/console/src/pages/SignInExperience/components/Welcome/GuideModal.tsx
  packages/console/src/pages/SignInExperience/index.tsx
  packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/LanguageDetails.tsx
  packages/console/src/pages/TenantSettings/TenantDomainSettings/AddDomainForm/index.tsx
  packages/console/src/pages/UserDetails/UserSettings/index.tsx
  packages/console/src/pages/Users/components/CreateForm/index.tsx
  packages/console/src/pages/WebhookDetails/WebhookSettings/index.tsx
  packages/console/src/pages/Webhooks/components/CreateFormModal/CreateForm.tsx
  packages/console/src/utils/form.ts
Labels: bugfix, size/xl

#4024 refactor(console): update change custom domain notice
  packages/console/src/pages/TenantSettings/TenantDomainSettings/CustomDomain/index.module.scss
  packages/console/src/pages/TenantSettings/TenantDomainSettings/CustomDomain/index.tsx
Labels: enhancement, size/xs

#4025 chore(console): remove redundant useSWR params from custom domain request
  packages/console/src/pages/TenantSettings/TenantDomainSettings/index.tsx
Labels: chore, size/xs

#4027 fix(console): set RHF default value
  packages/console/src/pages/TenantSettings/TenantBasicSettings/index.tsx
Labels: bugfix, size/s

#3988 feat(console): add tenant list dropdown
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/components/TenantEnvTag/index.module.scss
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/components/TenantEnvTag/index.tsx
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/index.module.scss
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/index.tsx
  packages/console/src/containers/AppContent/components/Topbar/index.tsx
  packages/toolkit/core-kit/scss/_console-themes.scss
Labels: feature, size/l

#4019 feat(console): create tenant modal
  packages/console/src/assets/images/create-tenant-header-dark.svg
  packages/console/src/assets/images/create-tenant-header.svg
  packages/console/src/cloud/pages/Main/CreateTenantModal/index.module.scss
  packages/console/src/cloud/pages/Main/CreateTenantModal/index.tsx
  packages/console/src/components/RadioGroup/Radio.module.scss
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/TenantEnvTag/index.module.scss
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/TenantEnvTag/index.tsx
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/index.tsx
Labels: feature, size/m

#4028 feat: various application improvements
  .changeset/brown-adults-speak.md
  .changeset/smart-icons-move.md
  packages/cli/src/commands/translate/prompts.ts
  packages/console/src/consts/oidc.ts
  packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/core/src/env-set/oidc.ts
  packages/core/src/oidc/defaults.ts
  packages/core/src/oidc/init.ts
  packages/integration-tests/src/tests/api/application.test.ts
  packages/phrases/src/locales/de/translation/admin-console/application-details.ts
  packages/phrases/src/locales/de/translation/admin-console/errors.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/errors.ts
  packages/phrases/src/locales/es/translation/admin-console/application-details.ts
  packages/phrases/src/locales/es/translation/admin-console/errors.ts
  packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/errors.ts
  packages/phrases/src/locales/it/translation/admin-console/application-details.ts
  packages/phrases/src/locales/it/translation/admin-console/errors.ts
  packages/phrases/src/locales/ja/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/errors.ts
  packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/errors.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/errors.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/errors.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/errors.ts
  packages/phrases/src/locales/ru/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/errors.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/errors.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/errors.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/errors.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/errors.ts
  packages/schemas/src/consts/date.ts
  packages/schemas/src/consts/index.ts
  packages/schemas/src/consts/oidc.ts
  packages/schemas/src/foundations/jsonb-types.ts
Labels: feature, size/l

#4026 refactor(console): use withtyped client for SWR
  packages/cloud/package.json
  packages/cloud/tsconfig.json
  packages/console/package.json
  packages/console/src/cloud/hooks/use-cloud-api.ts
  packages/console/src/cloud/hooks/use-cloud-swr.ts
  packages/console/src/cloud/pages/Main/CreateTenantModal/index.tsx
  packages/console/src/cloud/pages/Main/Tenants.tsx
  packages/console/src/cloud/pages/Main/index.tsx
  packages/console/src/hooks/use-swr-fetcher.ts
  packages/console/src/hooks/use-tenants.ts
  packages/console/src/pages/TenantSettings/TenantBasicSettings/index.tsx
  packages/integration-tests/src/tests/ui-cloud/smoke.test.ts
  pnpm-lock.yaml
Labels: enhancement, size/m

#4020 fix: remove unsafe-inline and unsafe-eval
  packages/cloud/src/middleware/with-security-headers.ts
  packages/core/src/middleware/koa-security-headers.ts
Labels: bugfix, size/xs

#4022 refactor(ui): align enum key pascal case
  packages/ui/src/apis/utils.ts
  packages/ui/src/containers/ForgotPasswordLink/index.tsx
  packages/ui/src/containers/VerificationCode/PasswordSignInLink.tsx
  packages/ui/src/containers/VerificationCode/index.test.tsx
  packages/ui/src/containers/VerificationCode/index.tsx
  packages/ui/src/containers/VerificationCode/use-continue-flow-code-verification.ts
  packages/ui/src/containers/VerificationCode/use-forgot-password-flow-code-verification.ts
  packages/ui/src/containers/VerificationCode/utils.ts
  packages/ui/src/hooks/use-required-profile-error-handler.ts
  packages/ui/src/hooks/use-social-landing-handler.ts
  packages/ui/src/pages/Continue/SetEmailOrPhone/index.test.tsx
  packages/ui/src/pages/Continue/SetEmailOrPhone/index.tsx
  packages/ui/src/pages/ForgotPassword/ForgotPasswordForm/index.test.tsx
  packages/ui/src/pages/ForgotPassword/ForgotPasswordForm/index.tsx
  packages/ui/src/pages/Register/IdentifierRegisterForm/index.test.tsx
  packages/ui/src/pages/Register/IdentifierRegisterForm/use-on-submit.ts
  packages/ui/src/pages/SignIn/IdentifierSignInForm/index.test.tsx
  packages/ui/src/pages/SignIn/IdentifierSignInForm/use-on-submit.ts
  packages/ui/src/pages/SignInPassword/PasswordForm/VerificationCodeLink.tsx
  packages/ui/src/pages/SignInPassword/PasswordForm/index.test.tsx
  packages/ui/src/pages/SocialLanding/index.test.tsx
  packages/ui/src/pages/VerificationCode/index.tsx
  packages/ui/src/types/guard.ts
  packages/ui/src/types/index.ts
  packages/ui/src/utils/social-connectors.test.ts
  packages/ui/src/utils/social-connectors.ts
Labels: enhancement, size/m

#3954 fix(schemas): modify domain table unique index
  packages/schemas/alterations/next-1685691718-domain-unique.ts
  packages/schemas/tables/domains.sql
Labels: bugfix, size/s

#4030 fix(console): ensure optional fields exist in the sie form data
  packages/console/src/pages/SignInExperience/utils/form.ts
Labels: bugfix, size/xs

#4037 fix(test): fix cloud UI test create new account idling URL mismatch error
  packages/console/src/cloud/pages/Main/index.tsx
  packages/integration-tests/src/tests/ui-cloud/smoke.test.ts
Labels: bugfix, size/s

#4034 feat(console): add custom domain notes for endpoints and social callback uri
  packages/console/src/hooks/use-custom-domain.ts
  packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx
  packages/console/src/pages/ApplicationDetails/index.module.scss
  packages/console/src/pages/Connectors/components/ConnectorForm/ConfigForm.tsx
  packages/console/src/pages/TenantSettings/TenantDomainSettings/index.tsx
  packages/console/src/utils/domain.ts
  packages/phrases/src/locales/de/translation/admin-console/domain.ts
  packages/phrases/src/locales/en/translation/admin-console/domain.ts
  packages/phrases/src/locales/es/translation/admin-console/domain.ts
  packages/phrases/src/locales/fr/translation/admin-console/domain.ts
  packages/phrases/src/locales/it/translation/admin-console/domain.ts
  packages/phrases/src/locales/ja/translation/admin-console/domain.ts
  packages/phrases/src/locales/ko/translation/admin-console/domain.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/domain.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/domain.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/domain.ts
  packages/phrases/src/locales/ru/translation/admin-console/domain.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/domain.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/domain.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/domain.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/domain.ts
Labels: feature, size/m

#4039 feat(console): add alternative endpoint for application get started guide
  packages/console/src/assets/docs/tutorial/integrate-sdk/android.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/android_zh-cn.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/express.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/express_zh-cn.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/go.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/go_zh-cn.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/ios.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/ios_zh-cn.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/next.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/next_zh-cn.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/react.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/react_zh-cn.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/vanilla.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/vanilla_zh-cn.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/vue.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/vue_zh-cn.mdx
  packages/console/src/pages/Applications/components/Guide/index.tsx
Labels: feature, size/s

#4040 chore(console): update light loading illustration
  packages/console/src/assets/images/loading-illustration.svg
Labels: chore, size/s

#4035 chore: add repository event dispatch job on logto master push
  .github/workflows/repository-dispatch.yml
Labels: chore, size/s

#4041 refactor(console): update management api settings description
  packages/console/src/pages/ApiResourceDetails/ApiResourceSettings/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/en/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/es/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/it/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/api-resource-details.ts
Labels: enhancement, size/s

#4042 style(console): update min-width of the sie page
  packages/console/src/pages/SignInExperience/index.module.scss
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SignInMethodEditBox/SignInMethodItem.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SignInMethodEditBox/index.module.scss
Labels: size/s

#4038 fix(ui): fix preview classname overwrite bug
  .changeset/six-starfishes-hide.md
  packages/ui/src/Providers/AppBoundary/AppMeta.tsx
Labels: bugfix, size/xs

#4031 feat(console): add tenant loading page
  packages/cli/src/commands/install/utils.ts
  packages/console/src/assets/images/tenant-landing-page-dark.svg
  packages/console/src/assets/images/tenant-landing-page.svg
  packages/console/src/cloud/pages/Main/Redirect.tsx
  packages/console/src/cloud/pages/Main/TenantLandingPage/TenantLandingPageContent/CreateTenantModal/index.module.scss
  packages/console/src/cloud/pages/Main/TenantLandingPage/TenantLandingPageContent/CreateTenantModal/index.tsx
  packages/console/src/cloud/pages/Main/TenantLandingPage/TenantLandingPageContent/index.module.scss
  packages/console/src/cloud/pages/Main/TenantLandingPage/TenantLandingPageContent/index.tsx
  packages/console/src/cloud/pages/Main/TenantLandingPage/index.module.scss
  packages/console/src/cloud/pages/Main/TenantLandingPage/index.tsx
  packages/console/src/cloud/pages/Main/Tenants.tsx
  packages/console/src/cloud/pages/Main/index.tsx
  packages/console/src/consts/env.ts
  packages/console/src/containers/AppContent/components/Topbar/Contact/index.module.scss
  packages/console/src/containers/AppContent/components/Topbar/Contact/index.tsx
  packages/console/src/containers/AppContent/components/Topbar/DocumentNavButton/index.module.scss
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/index.module.scss
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/index.tsx
  packages/console/src/containers/AppContent/components/Topbar/index.tsx
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/contexts/TenantsProvider.tsx
  packages/console/src/ds-components/RadioGroup/Radio.module.scss
  packages/console/src/pages/TenantSettings/TenantBasicSettings/index.tsx
  packages/console/src/pages/TenantSettings/index.tsx
  packages/integration-tests/src/tests/ui-cloud/smoke.test.ts
  packages/phrases/src/locales/de/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/de/translation/admin-console/tenants.ts
  packages/phrases/src/locales/en/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/en/translation/admin-console/tenants.ts
  packages/phrases/src/locales/es/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/es/translation/admin-console/tenants.ts
  packages/phrases/src/locales/fr/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/fr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/it/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/it/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ja/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/ja/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ko/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/ko/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ru/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/ru/translation/admin-console/tenants.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tenant-settings.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tenants.ts
Labels: feature, size/xl

#4050 chore(schemas,phrases): make zod peer dependency
  packages/phrases-ui/package.json
  packages/phrases/package.json
  packages/schemas/package.json
Labels: chore, size/s

#4018 fix(core): fix session not found redirect hostname
  packages/core/src/middleware/koa-spa-session-guard.test.ts
  packages/core/src/middleware/koa-spa-session-guard.ts
Labels: bugfix, size/s

#4049 fix(core): s3 region fallback
  packages/core/src/utils/storage/s3-storage.ts
Labels: bugfix, size/xs

#4048 fix(cloud,test): should block when users trying to create too many tenants
  packages/cloud/src/routes/tenants.test.ts
  packages/cloud/src/routes/tenants.ts
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/index.module.scss
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/index.tsx
  packages/integration-tests/src/tests/api-cloud/tenant.test.ts
Labels: bugfix, size/s

#4017 fix(core): update domain cache
  packages/core/src/libraries/domain.test.ts
  packages/core/src/libraries/domain.ts
  packages/core/src/utils/tenant.ts
Labels: bugfix, size/s

#4051 fix(console): direct to new created tenant and clear create modal on open
  packages/console/src/cloud/pages/Main/TenantLandingPage/TenantLandingPageContent/CreateTenantModal/index.tsx
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/index.tsx
  packages/integration-tests/src/tests/ui-cloud/smoke.test.ts
Labels: bugfix, size/s

#4055 refactor(console): rename props name for table component
  packages/console/src/ds-components/Table/index.tsx
  packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/LanguageDetails.tsx
  packages/console/src/pages/TenantSettings/TenantDomainSettings/CustomDomain/ActivationProcess/DnsRecordsTable/index.module.scss
  packages/console/src/pages/TenantSettings/TenantDomainSettings/CustomDomain/ActivationProcess/DnsRecordsTable/index.tsx
Labels: enhancement, size/s

#4057 chore(console): update tenant landing page LM image
  packages/console/src/assets/images/tenant-landing-page.svg
Labels: chore, size/xs

#4058 ci: add cloud related code owner
  .github/CODEOWNERS
Labels: size/xs

#4053 chore(console): update illustrations
  packages/console/src/assets/images/congrats.svg
  packages/console/src/assets/images/loading-illustration.svg
  packages/console/src/assets/images/sign-in-experience-welcome.svg
  packages/console/src/assets/images/social-connector-empty.svg
Labels: chore, size/m

#4061 feat(console): add custom domain related links
  packages/console/src/pages/TenantSettings/TenantDomainSettings/CustomDomain/index.tsx
  packages/console/src/pages/TenantSettings/TenantDomainSettings/index.tsx
Labels: feature, size/s

#4062 fix(console): correct domain settings page meta
  packages/console/src/pages/TenantSettings/TenantDomainSettings/index.tsx
Labels: bugfix, size/xs

#4060 refactor(console): remove use tenant hook and use cloud SWR instead
  packages/console/src/cloud/pages/Main/TenantLandingPage/TenantLandingPageContent/index.tsx
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/index.tsx
  packages/console/src/hooks/use-tenants.ts
  packages/console/src/pages/TenantSettings/TenantBasicSettings/index.tsx
Labels: enhancement, size/m

#4067 chore(console): remove toast for creating tenant
  packages/console/src/cloud/pages/Main/TenantLandingPage/TenantLandingPageContent/index.tsx
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/tenants.ts
  packages/phrases/src/locales/en/translation/admin-console/tenants.ts
  packages/phrases/src/locales/es/translation/admin-console/tenants.ts
  packages/phrases/src/locales/fr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/it/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ja/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ko/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ru/translation/admin-console/tenants.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tenants.ts
Labels: chore, size/s

#4064 fix(console): landing page placeholder css
  packages/console/src/cloud/pages/Main/TenantLandingPage/index.module.scss
  packages/console/src/cloud/pages/Main/TenantLandingPage/index.tsx
Labels: bugfix, size/xs

#4036 chore: update conversion id
  packages/console/src/onboarding/constants/index.ts
Labels: chore, size/xs

#4070 chore(deps): upgrade Logto React SDK
  packages/console/package.json
  packages/console/src/App.tsx
  packages/demo-app/package.json
  pnpm-lock.yaml
Labels: chore, size/xs

#4063 refactor(console): reorder passwordless connectors in the list
  packages/console/src/pages/Connectors/index.tsx
Labels: enhancement, size/xs

#4066 fix(console): should not block admin tenant owner from creating more tenants
  packages/console/src/consts/tenants.ts
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/index.tsx
Labels: bugfix, size/s

#4065 feat(toolkit): add new font tokens in core-kit
  .changeset/flat-rice-rhyme.md
  packages/console/src/containers/AppContent/index.module.scss
  packages/toolkit/core-kit/scss/_console-themes.scss
  packages/toolkit/core-kit/scss/_fonts.scss
Labels: feature, size/s

#4069 fix: support circular reference when normalizing errors
  .changeset/tough-buckets-listen.md
  packages/app-insights/jest.config.js
  packages/app-insights/package.json
  packages/app-insights/src/node.ts
  packages/app-insights/src/normalize-error.test.ts
  packages/app-insights/src/normalize-error.ts
  packages/app-insights/tsconfig.json
  packages/app-insights/tsconfig.test.json
  packages/cloud/src/middleware/with-error-report.ts
  packages/core/src/app/init.ts
  packages/core/src/caches/index.ts
  packages/core/src/middleware/koa-error-handler.ts
  pnpm-lock.yaml
Labels: bugfix, size/m

#4072 style(console): set passwordless connector creation modal to large by default
  packages/console/src/pages/Connectors/CreateForm/index.tsx
Labels: size/s

#4074 refactor(console): optimize tenant context and hooks
  package.json
  packages/console/src/App.tsx
  packages/console/src/cloud/App.tsx
  packages/console/src/cloud/hooks/use-cloud-swr.ts
  packages/console/src/cloud/pages/Main/AutoCreateTenant/index.tsx
  packages/console/src/cloud/pages/Main/Redirect.tsx
  packages/console/src/cloud/pages/Main/TenantLandingPage/TenantLandingPageContent/index.tsx
  packages/console/src/cloud/pages/Main/index.tsx
  packages/console/src/cloud/types.ts
  packages/console/src/components/SessionExpired/index.tsx
  packages/console/src/consts/tenants.ts
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/index.module.scss
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/index.tsx
  packages/console/src/containers/AppContent/index.tsx
  packages/console/src/containers/ErrorBoundary/index.tsx
  packages/console/src/containers/ProtectedRoutes/index.tsx
  packages/console/src/containers/TenantAccess/index.tsx
  packages/console/src/containers/TenantAppContainer/index.tsx
  packages/console/src/contexts/TenantsProvider.tsx
  packages/console/src/hooks/use-current-user.ts
  packages/console/src/hooks/use-logto-user-id.ts
  packages/console/src/hooks/use-me-custom-data.ts
  packages/console/src/onboarding/index.module.scss
  packages/console/src/onboarding/index.tsx
  packages/console/src/onboarding/pages/Congrats/index.tsx
  packages/console/src/pages/ConsoleRoutes/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/DeleteCard/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/index.tsx
  packages/console/src/pages/Welcome/index.tsx
  packages/integration-tests/src/tests/ui-cloud/smoke.test.ts
  packages/ui/src/components/Button/index.module.scss
Labels: enhancement, size/xl

#4080 refactor(console): add skeleton for custom domain page
  packages/console/src/components/DetailsPage/Skeleton/index.module.scss
  packages/console/src/components/DetailsPage/Skeleton/index.tsx
  packages/console/src/components/DetailsPage/index.tsx
  packages/console/src/components/DetailsSkeleton/index.tsx
  packages/console/src/components/FormCard/FormCardLayout/index.module.scss
  packages/console/src/components/FormCard/FormCardLayout/index.tsx
  packages/console/src/components/FormCard/Skeleton/index.module.scss
  packages/console/src/components/FormCard/Skeleton/index.tsx
  packages/console/src/components/FormCard/index.module.scss
  packages/console/src/components/FormCard/index.tsx
  packages/console/src/pages/TenantSettings/TenantDomainSettings/Skeleton/index.module.scss
  packages/console/src/pages/TenantSettings/TenantDomainSettings/Skeleton/index.tsx
  packages/console/src/pages/TenantSettings/TenantDomainSettings/index.tsx
Labels: enhancement, size/l

#4086 fix(ui): fix ui preview critical bug
  packages/ui/src/Layout/AppLayout/index.module.scss
  packages/ui/src/Providers/AppBoundary/AppMeta.tsx
  packages/ui/src/Providers/AppBoundary/index.module.scss
  packages/ui/src/Providers/SettingsProvider/use-preview.ts
Labels: bugfix, size/s

#4085 chore(toolkit): add email service branding config guard
  packages/toolkit/connector-kit/src/types.ts
Labels: chore, size/s

#4082 refactor(console): reorg error rendering
  packages/cloud/src/middleware/with-security-headers.ts
  packages/console/src/App.tsx
  packages/console/src/cloud/App.tsx
  packages/console/src/cloud/pages/Callback/index.tsx
  packages/console/src/containers/AppContent/index.tsx
  packages/console/src/containers/ErrorBoundary/index.tsx
  packages/console/src/containers/LogtoErrorBoundary/index.tsx
  packages/console/src/pages/Callback/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/index.tsx
  packages/console/src/pages/Welcome/index.tsx
  packages/core/src/middleware/koa-security-headers.ts
Labels: enhancement, size/m

#4079 feat(schemas): add email service guard and system key
  packages/core/src/tenants/SystemContext.ts
  packages/schemas/src/types/connector.ts
  packages/schemas/src/types/system.ts
  packages/toolkit/connector-kit/src/types.ts
Labels: feature, size/s

#4091 fix(console): text color of docs and help button
  packages/console/src/containers/AppContent/components/Topbar/Contact/index.module.scss
  packages/console/src/containers/AppContent/components/Topbar/DocumentNavButton/index.module.scss
Labels: bugfix, size/xs

#4093 fix(schemas): fix sendgrid email service config
  packages/schemas/src/types/system.ts
Labels: bugfix, size/s

#4087 fix(console): fix multi tenancy flow and sync ui-test
  packages/console/src/containers/ErrorBoundary/index.tsx
  packages/console/src/pages/Callback/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/index.tsx
  packages/console/src/utils/url.ts
  packages/integration-tests/src/tests/ui-cloud/operations.ts
  packages/integration-tests/src/tests/ui-cloud/smoke.test.ts
  packages/integration-tests/tsconfig.json
Labels: bugfix, size/l

#4090 chore(core,ui): set jest config coverage report to all files
  packages/core/jest.config.js
  packages/ui/jest.config.ts
Labels: chore, size/xs

#4094 fix(schemas): update email service config systems table key
  packages/schemas/src/types/system.ts
Labels: bugfix, size/xs

#4095 fix(core): add invalid body request error on oidc endpoints
  packages/core/src/errors/RequestError/index.ts
  packages/core/src/oidc/init.ts
Labels: bugfix, size/s

#4099 chore(toolkit,core): remove demo tag from logto email connector (1/2)
  packages/cloud/src/libraries/tenants.ts
  packages/toolkit/connector-kit/src/types.ts
Labels: chore, size/s

#4083 feat(connector): update logto email connector
  packages/connectors/connector-logto-email/src/constant.ts
  packages/connectors/connector-logto-email/src/index.ts
  packages/connectors/connector-logto-email/src/types.ts
  packages/toolkit/connector-kit/src/types.ts
Labels: feature, size/m

#4097 feat(core): add connector usage to GET APIs response
  packages/core/src/routes-me/social.ts
  packages/core/src/routes/connector/index.ts
  packages/core/src/utils/connectors/index.ts
  packages/schemas/src/types/connector.ts
Labels: feature, size/s
