Repository logto-io/logto, pull requests merged in 2023-02, with the labels that each got.

#3027 refactor(console): replace `useTableSearchParams` with `useSearchParametersWatcher`
  packages/console/src/components/AuditLogTable/index.tsx
  packages/console/src/components/Pagination/index.tsx
  packages/console/src/components/RoleUsersTransfer/components/SourceUsersBox/index.tsx
  packages/console/src/components/UserRolesTransfer/components/SourceRolesBox/index.tsx
  packages/console/src/hooks/use-search-parameters-watcher.ts
  packages/console/src/hooks/use-table-search-params.ts
  packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/index.tsx
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/RoleDetails/RolePermissions/index.tsx
  packages/console/src/pages/RoleDetails/RoleUsers/index.tsx
  packages/console/src/pages/Roles/index.tsx
  packages/console/src/pages/UserDetails/UserRoles/index.tsx
  packages/console/src/pages/Users/index.tsx
  packages/console/src/utilities/url.ts
Labels: enhancement, size/l

#3033 style(console): assigned users
  packages/console/src/pages/Roles/components/AssignedUsers/index.module.scss
Labels: size/xs

#3035 refactor(console): use overlay scrollbar in dropdown
  packages/console/src/components/Dropdown/DropdownItem.module.scss
  packages/console/src/components/Dropdown/DropdownItem.tsx
  packages/console/src/components/Dropdown/index.module.scss
  packages/console/src/components/Dropdown/index.tsx
  packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/AddLanguageSelector.module.scss
  packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/AddLanguageSelector.tsx
  packages/integration-tests/src/tests/ui/smoke.test.ts
Labels: enhancement, size/s

#3040 refactor(console): useDebounce
  packages/console/src/components/RoleUsersTransfer/components/SourceUsersBox/index.tsx
  packages/console/src/components/UserRolesTransfer/components/SourceRolesBox/index.tsx
  packages/console/src/hooks/use-debounce.ts
Labels: enhancement, size/s

#3043 chore: update node version in README
  .github/CONTRIBUTING.md
  README.md
Labels: chore, size/xs

#3041 refactor(console): use small size copy component on connector details page
  packages/console/src/pages/ConnectorDetails/index.tsx
Labels: enhancement, size/xs

#3044 refactor: update seed data
  .github/workflows/main.yml
  .scripts/compare-database.js
  packages/console/src/components/RoleScopesTransfer/components/SourceScopesBox/index.tsx
  packages/core/src/queries/roles.ts
  packages/core/src/routes/application.ts
  packages/integration-tests/src/tests/api/admin-user.roles.test.ts
  packages/integration-tests/src/tests/api/get-access-token.test.ts
  packages/schemas/alterations/next-1673853579-ac-default-scope.ts
  packages/schemas/alterations/next-1673863835-ac-scope-role.ts
  packages/schemas/alterations/next-1675316731-update-seed-data.ts
  packages/schemas/src/seeds/roles.ts
  packages/schemas/src/seeds/scope.ts
Labels: enhancement, size/m

#3048 chore(core,ui): add social flow changeset
  .changeset/sweet-dolphins-own.md
Labels: chore, size/s

#3049 fix(console): user roles table column name
  packages/console/src/pages/UserDetails/UserRoles/index.tsx
Labels: bugfix, size/xs

#3047 fix(console): improve table styles in markdown component
  packages/console/src/components/Markdown/index.module.scss
Labels: bugfix, size/s

#3050 chore: move changesets and enter rc
  .changeset/breezy-socks-joke.md
  .changeset/cyan-buses-trade.md
  .changeset/large-windows-scream.md
  .changeset/pre.json
  .changeset/six-falcons-sin.md
  .changeset/tender-maps-burn.md
  .changeset/three-ducks-yell.md
  .changeset/unlucky-months-clap.md
  packages/cli/CHANGELOG.md
  packages/cli/package.json
  packages/console/CHANGELOG.md
  packages/console/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/create/CHANGELOG.md
  packages/create/package.json
  packages/demo-app/package.json
  packages/integration-tests/CHANGELOG.md
  packages/integration-tests/package.json
  packages/phrases-ui/package.json
  packages/phrases/package.json
  packages/schemas/CHANGELOG.md
  packages/schemas/alterations/1.0.0_rc.0-1672815959-user-roles.ts
  packages/schemas/alterations/1.0.0_rc.0-1672820345-scope-resource-id.ts
  packages/schemas/alterations/1.0.0_rc.0-1672901841-roles-and-scopes-not-null.ts
  packages/schemas/alterations/1.0.0_rc.0-1673001922-support-generic-passcode.ts
  packages/schemas/alterations/1.0.0_rc.0-1673165463-scope-name-index.ts
  packages/schemas/alterations/1.0.0_rc.0-1673349501-sms-sign-in-identifier-to-phone.ts
  packages/schemas/alterations/1.0.0_rc.0-1673465463-ac-scope-name.ts
  packages/schemas/alterations/1.0.0_rc.0-1673853579-ac-default-scope.ts
  packages/schemas/alterations/1.0.0_rc.0-1673863835-ac-scope-role.ts
  packages/schemas/alterations/1.0.0_rc.0-1673882867-fix-alteration-issues.ts
  packages/schemas/alterations/1.0.0_rc.0-1673940577-scope-description-not-null.ts
  packages/schemas/alterations/1.0.0_rc.0-1673941897-application-roles.ts
  packages/schemas/alterations/1.0.0_rc.0-1674032095.1-dedup-resources-constraint.ts
  packages/schemas/alterations/1.0.0_rc.0-1674032095.2-oidc-model-pkey.ts
  packages/schemas/alterations/1.0.0_rc.0-1674032095.3-tenant-table.ts
  packages/schemas/alterations/1.0.0_rc.0-1674032095.4-add-id-column.ts
  packages/schemas/alterations/1.0.0_rc.0-1674032095.5-multi-tenancy.ts
  packages/schemas/alterations/1.0.0_rc.0-1674032095.6-add-tenant-id-trigger.ts
  packages/schemas/alterations/1.0.0_rc.0-1674987042-drop-settings-and-create-systems.ts
  packages/schemas/alterations/1.0.0_rc.0-1675316731-update-seed-data.ts
  packages/schemas/package.json
  packages/shared/CHANGELOG.md
  packages/shared/package.json
  packages/toolkit/connector-kit/package.json
  packages/toolkit/core-kit/package.json
  packages/toolkit/language-kit/package.json
  packages/ui/CHANGELOG.md
  packages/ui/package.json
Labels: chore, size/m

#3052 fix(core): insert id when patch application
  packages/core/src/queries/applications-roles.ts
Labels: bugfix, size/xs

#3034 fix(ui): should handle requiredProfile error on bindSocialRelatedUser
  packages/ui/src/hooks/use-social-link-related-user.ts
Labels: bugfix, size/xs

#3053 chore: add changesets
  .changeset/curly-hornets-end.md
Labels: chore, size/xs

#3039 refactor(console): keep sign-in method verification code check state
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/SignUpForm.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SignInMethodEditBox/index.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SignInMethodEditBox/utilities.ts
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/utilities.ts
Labels: enhancement, size/m

#3045 refactor(console): userAccountInformation
  packages/console/src/components/UserAccountInformation/index.module.scss
  packages/console/src/components/UserAccountInformation/index.tsx
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/pages/Users/components/CreateForm/index.tsx
  packages/console/src/pages/Users/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/users.ts
  packages/phrases/src/locales/en/translation/admin-console/users.ts
  packages/phrases/src/locales/fr/translation/admin-console/users.ts
  packages/phrases/src/locales/ko/translation/admin-console/users.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/users.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/users.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/users.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/users.ts
Labels: enhancement, size/s

#3020 refactor(ui): update set password form
  packages/integration-tests/src/tests/ui/smoke.test.ts
  packages/phrases-ui/src/locales/de.ts
  packages/phrases-ui/src/locales/en.ts
  packages/phrases-ui/src/locales/fr.ts
  packages/phrases-ui/src/locales/ko.ts
  packages/phrases-ui/src/locales/pt-br.ts
  packages/phrases-ui/src/locales/pt-pt.ts
  packages/phrases-ui/src/locales/tr-tr.ts
  packages/phrases-ui/src/locales/zh-cn.ts
  packages/ui/package.json
  packages/ui/src/components/InputField/index.module.scss
  packages/ui/src/components/InputField/index.tsx
  packages/ui/src/components/TermsOfUse/index.module.scss
  packages/ui/src/components/TermsOfUse/index.tsx
  packages/ui/src/containers/SetPassword/TogglePassword.tsx
  packages/ui/src/containers/SetPassword/index.module.scss
  packages/ui/src/containers/SetPassword/index.test.tsx
  packages/ui/src/containers/SetPassword/index.tsx
  packages/ui/src/pages/Continue/SetPassword/index.test.tsx
  packages/ui/src/pages/PasswordRegisterWithUsername/index.test.tsx
  packages/ui/src/pages/ResetPassword/index.test.tsx
  packages/ui/src/utils/form.ts
  pnpm-lock.yaml
Labels: enhancement, size/l

#3024 feat(ui): add new PasswordInputField Component based on new InputField
  packages/ui/src/components/InputFields/InputField.module.scss
  packages/ui/src/components/InputFields/InputField.test.tsx
  packages/ui/src/components/InputFields/InputField.tsx
  packages/ui/src/components/InputFields/PasswordInputField.test.tsx
  packages/ui/src/components/InputFields/PasswordInputField.tsx
  packages/ui/src/components/InputFields/index.tsx
  packages/ui/src/containers/SetPassword/index.tsx
  packages/ui/src/hooks/use-toggle.ts
  packages/ui/src/hooks/use-update-effect.ts
Labels: feature, size/m

#3062 refactor(console): i18n for documentation url
  packages/console/src/components/AppContent/components/Sidebar/hook.tsx
  packages/console/src/hooks/use-documentation-url.ts
  packages/console/src/pages/ApiResourceDetails/ApiResourceSettings/index.tsx
  packages/console/src/pages/ApplicationDetails/components/Settings.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx
  packages/console/src/pages/Connectors/components/ConnectorForm/index.tsx
  packages/console/src/pages/GetStarted/hook.ts
  packages/console/src/pages/UserDetails/UserSettings/index.tsx
Labels: enhancement, size/s

#3051 fix(phrases): update German locale
  packages/phrases-ui/src/locales/de.ts
Labels: bugfix, size/m

#3063 refactor(console): rename `Go Web` to `Go` in SDK docs
  packages/console/src/assets/docs/tutorial/integrate-sdk/go.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/go_zh-cn.mdx
  packages/console/src/pages/Applications/components/Guide/index.tsx
  packages/console/src/pages/Applications/components/GuideHeader/index.tsx
  packages/console/src/types/applications.ts
Labels: enhancement, size/s

#3038 feat(ui): add smart input field
  packages/ui/package.json
  packages/ui/src/components/InputFields/InputField/index.module.scss
  packages/ui/src/components/InputFields/InputField/index.test.tsx
  packages/ui/src/components/InputFields/InputField/index.tsx
  packages/ui/src/components/InputFields/PasswordInputField/index.test.tsx
  packages/ui/src/components/InputFields/PasswordInputField/index.tsx
  packages/ui/src/components/InputFields/SmartInputField/AnimatedPrefix/index.module.scss
  packages/ui/src/components/InputFields/SmartInputField/AnimatedPrefix/index.tsx
  packages/ui/src/components/InputFields/SmartInputField/CountryCodeSelector/index.module.scss
  packages/ui/src/components/InputFields/SmartInputField/CountryCodeSelector/index.tsx
  packages/ui/src/components/InputFields/SmartInputField/index.test.tsx
  packages/ui/src/components/InputFields/SmartInputField/index.tsx
  packages/ui/src/components/InputFields/SmartInputField/use-smart-input-field.ts
  packages/ui/src/components/InputFields/index.tsx
  pnpm-lock.yaml
Labels: feature, size/xl

#3066 refactor(console): update app structure
  packages/console/src/App.tsx
  packages/console/src/containers/AppBoundary/index.module.scss
  packages/console/src/containers/AppBoundary/index.tsx
  packages/console/src/containers/AppContent/Sidebar/components/Contact/hook.tsx
  packages/console/src/containers/AppContent/Sidebar/components/Contact/index.module.scss
  packages/console/src/containers/AppContent/Sidebar/components/Contact/index.tsx
  packages/console/src/containers/AppContent/Sidebar/components/Item/index.module.scss
  packages/console/src/containers/AppContent/Sidebar/components/Item/index.tsx
  packages/console/src/containers/AppContent/Sidebar/components/Section/index.module.scss
  packages/console/src/containers/AppContent/Sidebar/components/Section/index.tsx
  packages/console/src/containers/AppContent/Sidebar/hook.tsx
  packages/console/src/containers/AppContent/Sidebar/icons/BarGraph.tsx
  packages/console/src/containers/AppContent/Sidebar/icons/Bolt.tsx
  packages/console/src/containers/AppContent/Sidebar/icons/Box.tsx
  packages/console/src/containers/AppContent/Sidebar/icons/Cloud.tsx
  packages/console/src/containers/AppContent/Sidebar/icons/Connection.tsx
  packages/console/src/containers/AppContent/Sidebar/icons/Contact.tsx
  packages/console/src/containers/AppContent/Sidebar/icons/Document.tsx
  packages/console/src/containers/AppContent/Sidebar/icons/Gear.tsx
  packages/console/src/containers/AppContent/Sidebar/icons/List.tsx
  packages/console/src/containers/AppContent/Sidebar/icons/UserProfile.tsx
  packages/console/src/containers/AppContent/Sidebar/icons/Web.tsx
  packages/console/src/containers/AppContent/Sidebar/index.module.scss
  packages/console/src/containers/AppContent/Sidebar/index.tsx
  packages/console/src/containers/AppContent/Sidebar/utils.ts
  packages/console/src/containers/AppContent/index.module.scss
  packages/console/src/containers/AppContent/index.tsx
  packages/console/src/containers/AppLayout/components/Topbar/index.module.scss
  packages/console/src/containers/AppLayout/components/Topbar/index.tsx
  packages/console/src/containers/AppLayout/components/UserInfo/index.module.scss
  packages/console/src/containers/AppLayout/components/UserInfo/index.tsx
  packages/console/src/containers/AppLayout/components/UserInfoSkeleton/index.module.scss
  packages/console/src/containers/AppLayout/components/UserInfoSkeleton/index.tsx
  packages/console/src/containers/AppLayout/index.module.scss
  packages/console/src/containers/AppLayout/index.tsx
  packages/console/src/containers/AppLayout/types.ts
  packages/console/src/containers/ErrorBoundary/index.tsx
  packages/console/src/pages/CloudPreview/index.tsx
Labels: enhancement, size/m

#3067 chore(console): replace `as` with `satisfies`
  packages/console/src/pages/ApiResourceDetails/index.tsx
Labels: chore, size/xs

#3064 fix(phrases): update translation for Korean
  packages/phrases-ui/src/locales/ko.ts
  packages/phrases/src/locales/ko/errors.ts
  packages/phrases/src/locales/ko/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/applications.ts
  packages/phrases/src/locales/ko/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/connectors.ts
  packages/phrases/src/locales/ko/translation/admin-console/contact.ts
  packages/phrases/src/locales/ko/translation/admin-console/errors.ts
  packages/phrases/src/locales/ko/translation/admin-console/general.ts
  packages/phrases/src/locales/ko/translation/admin-console/get-started.ts
  packages/phrases/src/locales/ko/translation/admin-console/log-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/logs.ts
  packages/phrases/src/locales/ko/translation/admin-console/permissions.ts
  packages/phrases/src/locales/ko/translation/admin-console/role-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/roles.ts
  packages/phrases/src/locales/ko/translation/admin-console/session-expired.ts
  packages/phrases/src/locales/ko/translation/admin-console/settings.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/ko/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/ko/translation/admin-console/tabs.ts
  packages/phrases/src/locales/ko/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/users.ts
  packages/phrases/src/locales/ko/translation/admin-console/welcome.ts
Labels: bugfix, size/xl

#3068 fix(core): should validate config when creating a new connector instance
  packages/core/src/libraries/connector.ts
  packages/core/src/routes/connector.test.ts
  packages/core/src/routes/connector.ts
  packages/core/src/utils/connectors/index.ts
  packages/shared/package.json
  pnpm-lock.yaml
Labels: bugfix, size/m

#3071 feat(console): compact-style radio group
  packages/console/src/components/RadioGroup/Radio.tsx
  packages/console/src/components/RadioGroup/index.module.scss
  packages/console/src/components/RadioGroup/index.tsx
Labels: feature, size/s

#3072 refactor(core): move connector session read/write to social verification
  packages/core/src/routes/interaction/utils/interaction.ts
  packages/core/src/routes/interaction/utils/social-verification.ts
Labels: enhancement, size/s

#3073 feat(console): multi card selector on cloud preview page
  packages/console/src/pages/CloudPreview/components/MultiCardSelector/index.module.scss
  packages/console/src/pages/CloudPreview/components/MultiCardSelector/index.tsx
Labels: feature, size/s

#3080 refactor: update connector interfaces
  .changeset-staged/nine-apes-attend.md
  packages/core/src/libraries/social.ts
  packages/toolkit/connector-kit/src/types.ts
Labels: enhancement, size/s

#3077 refactor(console): support icon in radio item
  packages/console/src/components/RadioGroup/Radio.module.scss
  packages/console/src/components/RadioGroup/Radio.tsx
  packages/console/src/components/RadioGroup/index.module.scss
Labels: enhancement, size/l

#3085 feat(console): add `CardSelector` component for cloud preview
  packages/console/src/pages/CloudPreview/components/CardSelector/index.tsx
Labels: feature, size/s

#3088 chore(ui): remove unused profile related phrases
  packages/phrases-ui/src/locales/de.ts
  packages/phrases-ui/src/locales/en.ts
  packages/phrases-ui/src/locales/fr.ts
  packages/phrases-ui/src/locales/ko.ts
  packages/phrases-ui/src/locales/pt-br.ts
  packages/phrases-ui/src/locales/pt-pt.ts
  packages/phrases-ui/src/locales/tr-tr.ts
  packages/phrases-ui/src/locales/zh-cn.ts
Labels: chore, size/m

#3046 feat(ui): optimize smart input field
  packages/ui/src/components/InputFields/PasswordInputField/index.tsx
  packages/ui/src/components/InputFields/SmartInputField/index.test.tsx
  packages/ui/src/components/InputFields/SmartInputField/index.tsx
  packages/ui/src/components/InputFields/SmartInputField/utils.test.ts
  packages/ui/src/components/InputFields/SmartInputField/utils.ts
  packages/ui/src/hooks/use-update-effect.ts
Labels: feature, size/m

#3082 refactor(core)!: merge SAML assertion handler API to authn API
  packages/core/src/routes/authn.test.ts
  packages/core/src/routes/authn.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/saml-assertion-handler.test.ts
  packages/core/src/routes/saml-assertion-handler.ts
Labels: enhancement, size/l

#3089 refactor(console): multi-card selector
  packages/console/src/pages/CloudPreview/components/CardSelector/CardSelector.tsx
  packages/console/src/pages/CloudPreview/components/CardSelector/MultiCardSelector/index.module.scss
  packages/console/src/pages/CloudPreview/components/CardSelector/MultiCardSelector/index.tsx
  packages/console/src/pages/CloudPreview/components/CardSelector/index.tsx
  packages/console/src/pages/CloudPreview/components/CardSelector/types.ts
Labels: enhancement, size/m

#3078 fix(phrases): update sync profile tip
  packages/phrases/src/locales/de/translation/admin-console/connectors.ts
  packages/phrases/src/locales/en/translation/admin-console/connectors.ts
  packages/phrases/src/locales/fr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/connectors.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/connectors.ts
Labels: bugfix, size/s

#3079 chore: add web compatibility section in README
  README.md
Labels: chore, size/xs

#3032 chore: add Uffizzi demo button in README
  README.md
  docker-compose.demo.uffizzi.yml
Labels: chore, size/s

#3074 feat(console): connector config form
  packages/console/package.json
  packages/console/src/components/Textarea/index.module.scss
  packages/console/src/components/Textarea/index.tsx
  packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx
  packages/console/src/pages/Connectors/components/ConfigForm/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorForm/hooks.tsx
  packages/console/src/pages/Connectors/components/ConnectorForm/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorForm/utils.ts
  packages/console/src/pages/Connectors/components/Guide/index.tsx
  packages/console/src/pages/Connectors/types.ts
  packages/core/src/utils/connectors/index.ts
  packages/toolkit/connector-kit/src/types.ts
  pnpm-lock.yaml
Labels: feature, size/l

#3095 chore: remove annoying install module failure warning from parcel
  packages/console/package.json
  packages/demo-app/package.json
  packages/phrases-ui/package.json
  pnpm-lock.yaml
Labels: chore, size/xs

#3101 fix(console): fix connector json config save
  packages/console/src/pages/Connectors/components/ConnectorForm/hooks.tsx
Labels: bugfix, size/xs

#3075 refactor: use RLS
  .github/workflows/integration-test.yml
  .scripts/compare-database.js
  packages/cli/src/commands/database/seed/index.ts
  packages/cli/src/commands/database/seed/tables.ts
  packages/cli/src/commands/database/seed/tenant.ts
  packages/cli/src/queries/database.ts
  packages/core/jest.setup.js
  packages/core/package.json
  packages/core/src/app/init.ts
  packages/core/src/env-set/GlobalValues.ts
  packages/core/src/env-set/index.ts
  packages/core/src/index.ts
  packages/core/src/middleware/koa-auth.test.ts
  packages/core/src/middleware/koa-console-redirect-proxy.ts
  packages/core/src/oidc/adapter.test.ts
  packages/core/src/oidc/init.test.ts
  packages/core/src/oidc/utils.test.ts
  packages/core/src/tenants/Tenant.test.ts
  packages/core/src/tenants/Tenant.ts
  packages/core/src/tenants/index.ts
  packages/core/src/tenants/utils.ts
  packages/core/src/test-utils/env-set.ts
  packages/core/src/test-utils/tenant.ts
  packages/integration-tests/package.json
  packages/schemas/README.md
  packages/schemas/alterations/next-1675788753-multi-tenancy-rls.ts
  packages/schemas/package.json
  packages/schemas/src/models/hooks.ts
  packages/schemas/src/models/tenants.ts
  packages/schemas/src/seeds/tenant.ts
  packages/schemas/tables/_after_all.sql
  packages/schemas/tables/_after_each.sql
  packages/schemas/tables/_before_all.sql
  packages/schemas/tables/_functions.sql
  packages/schemas/tables/applications.sql
  packages/schemas/tables/applications_roles.sql
  packages/schemas/tables/connectors.sql
  packages/schemas/tables/custom_phrases.sql
  packages/schemas/tables/logs.sql
  packages/schemas/tables/logto_configs.sql
  packages/schemas/tables/oidc_model_instances.sql
  packages/schemas/tables/passcodes.sql
  packages/schemas/tables/resources.sql
  packages/schemas/tables/roles.sql
  packages/schemas/tables/roles_scopes.sql
  packages/schemas/tables/scopes.sql
  packages/schemas/tables/sign_in_experiences.sql
  packages/schemas/tables/systems.sql
  packages/schemas/tables/users.sql
  packages/schemas/tables/users_roles.sql
  pnpm-lock.yaml
Labels: enhancement, size/xl

#3093 refactor(console): remove api path leading slash
  .husky/pre-commit
  packages/console/src/components/ApplicationName/index.tsx
  packages/console/src/components/AuditLogTable/components/ApplicationSelector/index.tsx
  packages/console/src/components/AuditLogTable/index.tsx
  packages/console/src/components/RoleScopesTransfer/components/SourceScopesBox/index.tsx
  packages/console/src/components/RoleUsersTransfer/components/SourceUsersBox/index.tsx
  packages/console/src/components/UserName/index.tsx
  packages/console/src/components/UserRolesTransfer/components/SourceRolesBox/index.tsx
  packages/console/src/hooks/use-api.ts
  packages/console/src/hooks/use-configs.ts
  packages/console/src/hooks/use-connector-groups.ts
  packages/console/src/hooks/use-connector-in-use.ts
  packages/console/src/hooks/use-enabled-connector-types.ts
  packages/console/src/hooks/use-ui-languages.ts
  packages/console/src/hooks/use-user-preferences.ts
  packages/console/src/mdx-components/UriInputField/index.tsx
  packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx
  packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/index.tsx
  packages/console/src/pages/ApiResourceDetails/ApiResourceSettings/index.tsx
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/AuditLogDetails/index.tsx
  packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx
  packages/console/src/pages/ConnectorDetails/components/ConnectorTabs/index.tsx
  packages/console/src/pages/ConnectorDetails/components/SenderTester/index.tsx
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorTypeColumn/index.tsx
  packages/console/src/pages/Connectors/components/CreateForm/index.tsx
  packages/console/src/pages/Connectors/components/Guide/index.tsx
  packages/console/src/pages/Connectors/components/SignInExperienceSetupNotice/index.tsx
  packages/console/src/pages/Dashboard/index.tsx
  packages/console/src/pages/GetStarted/hook.ts
  packages/console/src/pages/RoleDetails/RolePermissions/components/AssignPermissionsModal/index.tsx
  packages/console/src/pages/RoleDetails/RolePermissions/index.tsx
  packages/console/src/pages/RoleDetails/RoleSettings/index.tsx
  packages/console/src/pages/RoleDetails/RoleUsers/components/AssignUsersModal/index.tsx
  packages/console/src/pages/RoleDetails/RoleUsers/index.tsx
  packages/console/src/pages/RoleDetails/index.tsx
  packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
  packages/console/src/pages/Roles/index.tsx
  packages/console/src/pages/Settings/components/ChangePassword.tsx
  packages/console/src/pages/SignInExperience/components/Preview/index.tsx
  packages/console/src/pages/SignInExperience/components/Welcome/GuideModal.tsx
  packages/console/src/pages/SignInExperience/index.tsx
  packages/console/src/pages/SignInExperience/tabs/Others/LanguagesForm.tsx
  packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/LanguageDetails.tsx
  packages/console/src/pages/UserDetails/UserRoles/components/AssignRolesModal/index.tsx
  packages/console/src/pages/UserDetails/UserRoles/index.tsx
  packages/console/src/pages/UserDetails/UserSettings/components/UserSocialIdentities/index.tsx
  packages/console/src/pages/UserDetails/UserSettings/index.tsx
  packages/console/src/pages/UserDetails/components/ResetPasswordForm/index.tsx
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/pages/Users/components/CreateForm/index.tsx
  packages/console/src/pages/Users/index.tsx
Labels: enhancement, size/m

#3099 feat(core): enable creating a new connector with specified id
  packages/core/src/routes/connector.ts
Labels: feature, size/s

#3102 chore: add changeset for connector kit
  .changeset/big-turkeys-invite.md
Labels: chore, size/xs

#3065 refactor(ui): use smart input field to replace all password sign-in form
  packages/integration-tests/src/tests/ui/smoke.test.ts
  packages/phrases-ui/src/locales/de.ts
  packages/phrases-ui/src/locales/en.ts
  packages/phrases-ui/src/locales/fr.ts
  packages/phrases-ui/src/locales/ko.ts
  packages/phrases-ui/src/locales/pt-br.ts
  packages/phrases-ui/src/locales/pt-pt.ts
  packages/phrases-ui/src/locales/tr-tr.ts
  packages/phrases-ui/src/locales/zh-cn.ts
  packages/ui/src/apis/interaction.ts
  packages/ui/src/components/Input/PasswordInput.test.tsx
  packages/ui/src/components/InputFields/PasswordInputField/index.test.tsx
  packages/ui/src/components/InputFields/SmartInputField/use-smart-input-field.ts
  packages/ui/src/components/InputFields/SmartInputField/utils.ts
  packages/ui/src/containers/CreateAccount/index.test.tsx
  packages/ui/src/containers/CreateAccount/index.tsx
  packages/ui/src/containers/EmailForm/EmailForm.tsx
  packages/ui/src/containers/EmailPassword/index.module.scss
  packages/ui/src/containers/EmailPassword/index.test.tsx
  packages/ui/src/containers/EmailPassword/index.tsx
  packages/ui/src/containers/PhonePassword/index.module.scss
  packages/ui/src/containers/PhonePassword/index.test.tsx
  packages/ui/src/containers/PhonePassword/index.tsx
  packages/ui/src/containers/SetPassword/index.tsx
  packages/ui/src/containers/UsernameForm/UsernameForm.test.tsx
  packages/ui/src/containers/UsernameForm/UsernameForm.tsx
  packages/ui/src/containers/UsernameSignIn/index.test.tsx
  packages/ui/src/containers/UsernameSignIn/index.tsx
  packages/ui/src/pages/SecondarySignIn/index.test.tsx
  packages/ui/src/pages/SecondarySignIn/index.tsx
  packages/ui/src/pages/SignIn/Main.tsx
  packages/ui/src/pages/SignIn/PasswordSignInForm/index.module.scss
  packages/ui/src/pages/SignIn/PasswordSignInForm/index.test.tsx
  packages/ui/src/pages/SignIn/PasswordSignInForm/index.tsx
  packages/ui/src/pages/SignIn/index.test.tsx
  packages/ui/src/pages/SignIn/index.tsx
  packages/ui/src/utils/country-code.test.ts
  packages/ui/src/utils/field-validations.ts
  packages/ui/src/utils/form.ts
Labels: enhancement, size/xl

#3069 refactor(ui): refactor useApi
  packages/ui/src/containers/CreateAccount/index.tsx
  packages/ui/src/containers/SetPassword/index.test.tsx
  packages/ui/src/containers/SetPassword/index.tsx
  packages/ui/src/containers/UsernameForm/SetUsername/use-set-username.ts
  packages/ui/src/containers/UsernameForm/UsernameRegister/use-username-register.ts
  packages/ui/src/containers/VerificationCode/use-continue-flow-code-verification.ts
  packages/ui/src/containers/VerificationCode/use-forgot-password-flow-code-verification.ts
  packages/ui/src/containers/VerificationCode/use-general-verification-code-error-handler.ts
  packages/ui/src/containers/VerificationCode/use-register-flow-code-verification.ts
  packages/ui/src/containers/VerificationCode/use-resend-verification-code.ts
  packages/ui/src/containers/VerificationCode/use-sign-in-flow-code-verification.ts
  packages/ui/src/hooks/use-api.ts
  packages/ui/src/hooks/use-error-handler.ts
  packages/ui/src/hooks/use-password-sign-in.ts
  packages/ui/src/hooks/use-required-profile-error-handler.ts
  packages/ui/src/hooks/use-send-verification-code.ts
  packages/ui/src/hooks/use-social-link-account.ts
  packages/ui/src/hooks/use-social-link-related-user.ts
  packages/ui/src/hooks/use-social-register.ts
  packages/ui/src/hooks/use-social-sign-in-listener.ts
  packages/ui/src/hooks/use-social.ts
  packages/ui/src/pages/Consent/index.tsx
  packages/ui/src/pages/Continue/SetPassword/use-set-password.ts
  packages/ui/src/pages/PasswordRegisterWithUsername/index.tsx
  packages/ui/src/pages/PasswordRegisterWithUsername/use-username-password-register.ts
  packages/ui/src/pages/ResetPassword/use-reset-password.ts
  packages/ui/src/pages/SignIn/PasswordSignInForm/index.test.tsx
  packages/ui/src/pages/SignIn/PasswordSignInForm/index.tsx
Labels: enhancement, size/xl

#3103 refactor(core): fix rls error alert message
  packages/core/src/tenants/utils.ts
Labels: enhancement, size/xs

#3081 refactor(ui): simplify the usage of inputField error message
  packages/ui/src/components/InputFields/InputField/index.test.tsx
  packages/ui/src/components/InputFields/InputField/index.tsx
  packages/ui/src/components/InputFields/PasswordInputField/index.test.tsx
  packages/ui/src/components/InputFields/SmartInputField/index.tsx
  packages/ui/src/containers/SetPassword/index.test.tsx
  packages/ui/src/containers/SetPassword/index.tsx
  packages/ui/src/hooks/use-social-sign-in-listener.ts
  packages/ui/src/pages/SignIn/IdentifierSignInForm/index.test.tsx
  packages/ui/src/pages/SignIn/IdentifierSignInForm/index.tsx
  packages/ui/src/pages/SignIn/PasswordSignInForm/index.test.tsx
  packages/ui/src/pages/SignIn/PasswordSignInForm/index.tsx
  packages/ui/src/pages/SignInPassword/PasswordForm/index.test.tsx
  packages/ui/src/pages/SignInPassword/PasswordForm/index.tsx
  packages/ui/src/utils/form.ts
Labels: enhancement, size/m

#3109 fix(ui): user claims hot fix
  packages/core/src/oidc/init.ts
  packages/core/src/oidc/scope.ts
Labels: bugfix, size/s

#3084 feat(console): cloud preview welcome page
  packages/console/src/App.tsx
  packages/console/src/assets/images/building.svg
  packages/console/src/assets/images/cloud.svg
  packages/console/src/assets/images/database.svg
  packages/console/src/assets/images/pizza.svg
  packages/console/src/pages/CloudPreview/cloud-page-size.scss
  packages/console/src/pages/CloudPreview/components/ActionBar/index.module.scss
  packages/console/src/pages/CloudPreview/components/ActionBar/index.tsx
  packages/console/src/pages/CloudPreview/index.module.scss
  packages/console/src/pages/CloudPreview/index.tsx
  packages/console/src/pages/CloudPreview/layout.module.scss
  packages/console/src/pages/CloudPreview/pages/Welcome/index.module.scss
  packages/console/src/pages/CloudPreview/pages/Welcome/index.tsx
  packages/console/src/pages/CloudPreview/pages/Welcome/options.tsx
  packages/console/src/pages/CloudPreview/types.ts
  packages/phrases/src/locales/de/translation/admin-console/cloud-preview.ts
  packages/phrases/src/locales/de/translation/admin-console/index.ts
  packages/phrases/src/locales/en/translation/admin-console/cloud-preview.ts
  packages/phrases/src/locales/en/translation/admin-console/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/cloud-preview.ts
  packages/phrases/src/locales/fr/translation/admin-console/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/cloud-preview.ts
  packages/phrases/src/locales/ko/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/cloud-preview.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/cloud-preview.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/cloud-preview.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/cloud-preview.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/index.ts
Labels: feature, size/l

#3114 fix(console): remove leading slash in the oidc config api path
  packages/console/src/pages/ApplicationDetails/index.tsx
Labels: bugfix, size/xs

#3121 fix(ui): fix continue flow verification-code 404 bug
  packages/ui/src/App.tsx
  packages/ui/src/hooks/use-send-verification-code.ts
  packages/ui/src/pages/ForgotPassword/ForgotPasswordForm/index.test.tsx
  packages/ui/src/pages/SignInPassword/PasswordForm/index.test.tsx
Labels: bugfix, size/s

#3120 ci: build arm64 per release
  .github/workflows/release.yml
Labels: size/s

#3100 test(core): add tests
  packages/core/jest.setup.js
  packages/core/src/app/init.ts
  packages/core/src/env-set/GlobalValues.ts
  packages/core/src/env-set/UrlSet.test.ts
  packages/core/src/env-set/UrlSet.ts
  packages/core/src/env-set/index.ts
  packages/core/src/env-set/utils.ts
  packages/core/src/middleware/koa-auth/utils.ts
  packages/core/src/routes/well-known.ts
  packages/core/src/tenants/Tenant.test.ts
  packages/core/src/tenants/Tenant.ts
  packages/core/src/tenants/consts.ts
  packages/core/src/tenants/index.ts
  packages/core/src/test-utils/env-set.ts
  packages/core/src/utils/tenant.test.ts
  packages/core/src/utils/tenant.ts
  packages/integration-tests/src/api/api.ts
  packages/integration-tests/src/api/interaction.ts
  packages/integration-tests/src/client/index.ts
  packages/integration-tests/src/helpers/admin-tenant.ts
  packages/integration-tests/src/helpers/client.ts
  packages/integration-tests/src/tests/api/health-check.test.ts
  packages/integration-tests/src/tests/api/me.test.ts
  packages/toolkit/core-kit/package.json
  pnpm-lock.yaml
Labels: testing, size/xl

#3122 refactor(schemas): fix alteration script
  packages/schemas/alterations/next-1676190092-migrate-admin-data.ts
Labels: enhancement, size/xs

#3113 refactor(ui): clean up legacy code
  packages/ui/src/components/Input/PasswordInput.test.tsx
  packages/ui/src/components/Input/PasswordInput.tsx
  packages/ui/src/components/Input/PhoneInput.test.tsx
  packages/ui/src/components/Input/PhoneInput.tsx
  packages/ui/src/components/Input/index.module.scss
  packages/ui/src/components/Input/index.test.tsx
  packages/ui/src/components/Input/index.tsx
  packages/ui/src/components/Input/phoneInput.module.scss
  packages/ui/src/hooks/use-phone-number.ts
Labels: enhancement, size/xl

#3115 feat(console): group connector form items
  packages/console/src/pages/ConnectorDetails/components/ConnectorContent.module.scss
  packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx
  packages/console/src/pages/ConnectorDetails/index.module.scss
  packages/console/src/pages/Connectors/components/ConnectorForm/BasicForm.module.scss
  packages/console/src/pages/Connectors/components/ConnectorForm/BasicForm.tsx
  packages/console/src/pages/Connectors/components/ConnectorForm/ConfigForm.tsx
  packages/console/src/pages/Connectors/components/Guide/index.module.scss
  packages/console/src/pages/Connectors/components/Guide/index.tsx
Labels: feature, size/m

#3123 refactor(core): expose all headers in CORS
  packages/core/src/routes/init.ts
Labels: enhancement, size/xs

#3112 refactor(console): new topbar user menu
  packages/console/src/App.tsx
  packages/console/src/assets/images/arrow-right.svg
  packages/console/src/assets/images/globe.svg
  packages/console/src/assets/images/palette.svg
  packages/console/src/assets/images/profile.svg
  packages/console/src/components/Dropdown/index.tsx
  packages/console/src/components/Select/index.tsx
  packages/console/src/containers/AppLayout/components/SubMenu/index.module.scss
  packages/console/src/containers/AppLayout/components/SubMenu/index.tsx
  packages/console/src/containers/AppLayout/components/UserInfo/index.module.scss
  packages/console/src/containers/AppLayout/components/UserInfo/index.tsx
  packages/console/src/containers/AppLayout/components/UserInfoSkeleton/index.tsx
  packages/console/src/pages/Profile/index.module.scss
  packages/console/src/pages/Profile/index.tsx
  packages/integration-tests/src/tests/ui/smoke.test.ts
  packages/phrases/src/locales/de/translation/admin-console/index.ts
  packages/phrases/src/locales/de/translation/admin-console/menu.ts
  packages/phrases/src/locales/en/translation/admin-console/index.ts
  packages/phrases/src/locales/en/translation/admin-console/menu.ts
  packages/phrases/src/locales/fr/translation/admin-console/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/menu.ts
  packages/phrases/src/locales/ko/translation/admin-console/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/menu.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/menu.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/menu.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/menu.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/menu.ts
Labels: enhancement, size/l

#3111 feat(console): cloud preview about page
  packages/console/src/App.tsx
  packages/console/src/assets/images/case.svg
  packages/console/src/pages/CloudPreview/components/CardSelector/CardSelector.tsx
  packages/console/src/pages/CloudPreview/components/CardSelector/MultiCardSelector/index.tsx
  packages/console/src/pages/CloudPreview/layout.module.scss
  packages/console/src/pages/CloudPreview/pages/About/index.module.scss
  packages/console/src/pages/CloudPreview/pages/About/index.tsx
  packages/console/src/pages/CloudPreview/pages/About/options.tsx
  packages/console/src/pages/CloudPreview/pages/Welcome/index.module.scss
  packages/console/src/pages/CloudPreview/pages/Welcome/index.tsx
  packages/console/src/pages/CloudPreview/types.ts
  packages/console/src/pages/CloudPreview/utils.ts
  packages/phrases/src/locales/de/translation/admin-console/cloud-preview.ts
  packages/phrases/src/locales/de/translation/admin-console/general.ts
  packages/phrases/src/locales/en/translation/admin-console/cloud-preview.ts
  packages/phrases/src/locales/en/translation/admin-console/general.ts
  packages/phrases/src/locales/fr/translation/admin-console/cloud-preview.ts
  packages/phrases/src/locales/fr/translation/admin-console/general.ts
  packages/phrases/src/locales/ko/translation/admin-console/cloud-preview.ts
  packages/phrases/src/locales/ko/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/cloud-preview.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/cloud-preview.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/cloud-preview.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/cloud-preview.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
Labels: feature, size/l

#3118 style(console): copy to clipboard icon size
  packages/console/src/assets/images/copy.svg
  packages/console/src/components/CopyToClipboard/index.tsx
Labels: size/xs

#3124 fix(ui): update password sign-in link state value
  packages/ui/src/containers/VerificationCode/PasswordSignInLink.tsx
Labels: bugfix, size/xs

#3128 refactor(core): optimize tenant not found error
  packages/core/src/app/init.ts
  packages/core/src/tenants/utils.ts
Labels: enhancement, size/s

#3130 fix(core): mask password in audit log
  .changeset-staged/afraid-eagles-retire.md
  packages/core/src/middleware/koa-audit-log.test.ts
  packages/core/src/middleware/koa-audit-log.ts
Labels: bugfix, size/s

#3131 refactor(console): rename `CloudPreivew`
  packages/console/src/App.tsx
  packages/console/src/pages/Cloud/cloud-page-size.scss
  packages/console/src/pages/Cloud/components/ActionBar/index.module.scss
  packages/console/src/pages/Cloud/components/ActionBar/index.tsx
  packages/console/src/pages/Cloud/components/CardSelector/CardSelector.tsx
  packages/console/src/pages/Cloud/components/CardSelector/MultiCardSelector/index.module.scss
  packages/console/src/pages/Cloud/components/CardSelector/MultiCardSelector/index.tsx
  packages/console/src/pages/Cloud/components/CardSelector/index.tsx
  packages/console/src/pages/Cloud/components/CardSelector/types.ts
  packages/console/src/pages/Cloud/index.module.scss
  packages/console/src/pages/Cloud/index.tsx
  packages/console/src/pages/Cloud/layout.module.scss
  packages/console/src/pages/Cloud/pages/About/index.module.scss
  packages/console/src/pages/Cloud/pages/About/index.tsx
  packages/console/src/pages/Cloud/pages/About/options.tsx
  packages/console/src/pages/Cloud/pages/Welcome/index.module.scss
  packages/console/src/pages/Cloud/pages/Welcome/index.tsx
  packages/console/src/pages/Cloud/pages/Welcome/options.tsx
  packages/console/src/pages/Cloud/types.ts
  packages/console/src/pages/Cloud/utils.ts
  packages/console/src/pages/CloudPreview/pages/About/options.tsx
  packages/console/src/pages/CloudPreview/utils.ts
  packages/phrases/src/locales/de/translation/admin-console/cloud-preview.ts
  packages/phrases/src/locales/de/translation/admin-console/cloud.ts
  packages/phrases/src/locales/de/translation/admin-console/index.ts
  packages/phrases/src/locales/en/translation/admin-console/cloud-preview.ts
  packages/phrases/src/locales/en/translation/admin-console/cloud.ts
  packages/phrases/src/locales/en/translation/admin-console/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/cloud-preview.ts
  packages/phrases/src/locales/fr/translation/admin-console/cloud.ts
  packages/phrases/src/locales/fr/translation/admin-console/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/cloud-preview.ts
  packages/phrases/src/locales/ko/translation/admin-console/cloud.ts
  packages/phrases/src/locales/ko/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/cloud-preview.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/cloud-preview.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/cloud-preview.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/cloud.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/cloud-preview.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/cloud.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/index.ts
Labels: enhancement, size/xl

#3125 feat(console): cloud congrats page
  packages/console/src/App.tsx
  packages/console/src/assets/images/air-play.svg
  packages/console/src/assets/images/calendar.svg
  packages/console/src/assets/images/get-started.svg
  packages/console/src/components/Divider/index.module.scss
  packages/console/src/components/Divider/index.tsx
  packages/console/src/containers/AppLayout/components/UserInfo/index.module.scss
  packages/console/src/containers/AppLayout/components/UserInfo/index.tsx
  packages/console/src/pages/Cloud/pages/Congrats/index.module.scss
  packages/console/src/pages/Cloud/pages/Congrats/index.tsx
  packages/console/src/pages/Cloud/pages/Welcome/index.module.scss
  packages/console/src/pages/Cloud/types.ts
  packages/phrases/src/locales/de/translation/admin-console/cloud.ts
  packages/phrases/src/locales/en/translation/admin-console/cloud.ts
  packages/phrases/src/locales/fr/translation/admin-console/cloud.ts
  packages/phrases/src/locales/ko/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/cloud.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/cloud.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/cloud.ts
Labels: feature, size/l

#3134 fix(console): open demo app on cloud congrats page
  packages/console/src/pages/Cloud/pages/Congrats/index.tsx
Labels: bugfix, size/xs

#3136 chore: upgrade configs
  package.json
  packages/cli/package.json
  packages/cli/src/commands/database/config.ts
  packages/cli/src/commands/database/seed/index.ts
  packages/cli/src/queries/logto-config.ts
  packages/cli/tsconfig.json
  packages/console/package.json
  packages/console/src/components/Tip/TipBubble/utils.ts
  packages/console/src/mdx-components/Tabs/index.tsx
  packages/console/src/pages/Applications/components/GuideHeader/index.tsx
  packages/core/package.json
  packages/core/src/libraries/hook.test.ts
  packages/core/src/middleware/koa-audit-log.test.ts
  packages/core/src/middleware/koa-connector-error-handler.ts
  packages/core/src/middleware/koa-oidc-error-handler.ts
  packages/core/src/middleware/koa-spa-session-guard.test.ts
  packages/core/src/oidc/init.ts
  packages/core/src/oidc/utils.ts
  packages/core/src/queries/user.test.ts
  packages/core/src/routes/custom-phrase.test.ts
  packages/core/src/routes/well-known.test.ts
  packages/core/src/utils/jwks.ts
  packages/core/src/utils/search.ts
  packages/core/src/utils/zod.ts
  packages/core/tsconfig.base.json
  packages/demo-app/package.json
  packages/integration-tests/package.json
  packages/integration-tests/src/tests/api/admin-user.search.test.ts
  packages/integration-tests/tsconfig.json
  packages/phrases-ui/package.json
  packages/phrases-ui/tsconfig.json
  packages/phrases/package.json
  packages/phrases/tsconfig.json
  packages/schemas/package.json
  packages/schemas/src/gen/schema.ts
  packages/schemas/src/gen/utils.ts
  packages/schemas/src/models/hooks.ts
  packages/schemas/src/types/system.ts
  packages/schemas/src/types/user.ts
  packages/schemas/tsconfig.json
  packages/shared/package.json
  packages/shared/src/database/utils.ts
  packages/shared/tsconfig.json
  packages/toolkit/connector-kit/package.json
  packages/toolkit/connector-kit/tsconfig.json
  packages/toolkit/core-kit/package.json
  packages/toolkit/core-kit/tsconfig.json
  packages/toolkit/language-kit/package.json
  packages/toolkit/language-kit/tsconfig.json
  packages/ui/package.json
  packages/ui/src/components/VerificationCode/index.tsx
  packages/ui/src/hooks/use-required-profile-error-handler.ts
  packages/ui/src/pages/SignIn/IdentifierSignInForm/index.test.tsx
  packages/ui/src/utils/form.ts
  pnpm-lock.yaml
Labels: chore, size/xl

#3139 feat(console): progress bar on cloud page
  packages/console/src/pages/Cloud/components/ActionBar/index.module.scss
  packages/console/src/pages/Cloud/components/ActionBar/index.tsx
  packages/console/src/pages/Cloud/components/ProgressBar/index.module.scss
  packages/console/src/pages/Cloud/components/ProgressBar/index.tsx
  packages/console/src/pages/Cloud/pages/About/index.tsx
  packages/console/src/pages/Cloud/pages/Congrats/index.tsx
  packages/console/src/pages/Cloud/pages/Welcome/index.tsx
Labels: feature, size/s

#3143 style(ui): style and content polish
  packages/phrases-ui/src/locales/zh-cn.ts
  packages/phrases/src/locales/zh-cn/errors.ts
  packages/ui/src/scss/_colors.scss
Labels: size/s

#3142 style(ui): adjust signin and register switch link pos
  packages/ui/src/pages/Register/index.module.scss
  packages/ui/src/pages/Register/index.tsx
  packages/ui/src/pages/SignIn/index.module.scss
Labels: size/s

#3138 feat: init cloud
  package.json
  packages/cli/package.json
  packages/cloud/nodemon.json
  packages/cloud/package.json
  packages/cloud/src/index.ts
  packages/cloud/src/middleware/with-http-proxy.ts
  packages/cloud/src/middleware/with-spa.ts
  packages/cloud/src/utils/url.ts
  packages/cloud/tsconfig.build.json
  packages/cloud/tsconfig.json
  packages/console/package.json
  packages/console/src/consts/tenants.ts
  packages/core/package.json
  packages/core/src/env-set/GlobalValues.ts
  packages/core/src/middleware/koa-cors.ts
  packages/core/src/oidc/adapter.ts
  packages/core/src/routes-me/init.ts
  packages/core/src/routes/init.ts
  packages/integration-tests/package.json
  packages/phrases-ui/package.json
  packages/phrases/package.json
  packages/schemas/package.json
  packages/shared/package.json
  packages/toolkit/core-kit/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: feature, size/l

#3146 feat(cloud): `GET /api/tenants`
  commitlint.config.cjs
  package.json
  packages/cloud/package.json
  packages/cloud/src/index.ts
  packages/cloud/src/middleware/with-http-proxy.ts
  packages/cloud/src/middleware/with-spa.ts
  packages/cloud/src/queries/index.ts
  packages/cloud/src/queries/tenants.ts
  packages/cloud/src/routes/index.ts
  packages/cloud/src/routes/tenants.ts
  packages/cloud/src/utils/postgres.ts
  packages/cloud/src/utils/tenant.ts
  packages/cloud/src/utils/url.ts
  packages/console/package.json
  packages/console/src/App.tsx
  packages/console/src/consts/tenants.ts
  packages/console/src/containers/AppEndpointsProvider/index.tsx
  packages/console/src/utils/router.ts
  pnpm-lock.yaml
Labels: feature, size/m

#3147 refactor(cloud): implement request auth
  packages/cloud/package.json
  packages/cloud/src/env-set/index.ts
  packages/cloud/src/index.ts
  packages/cloud/src/middleware/with-auth.ts
  packages/cloud/src/middleware/with-http-proxy.ts
  packages/cloud/src/middleware/with-pathname.ts
  packages/cloud/src/middleware/with-spa.ts
  packages/cloud/src/queries/index.ts
  packages/cloud/src/routes/index.ts
  packages/cloud/src/routes/tenants.ts
  packages/cloud/src/utils/url.ts
  packages/core/package.json
  packages/integration-tests/package.json
  packages/schemas/package.json
  packages/schemas/src/consts/cloud.ts
  packages/schemas/src/consts/index.ts
  packages/schemas/src/index.ts
  pnpm-lock.yaml
Labels: enhancement, size/m

#3150 refactor(core): remove duplicate findEntityById query before delete
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
  packages/core/src/routes/application.test.ts
  packages/core/src/routes/application.ts
  packages/core/src/routes/resource.test.ts
  packages/core/src/routes/resource.ts
Labels: enhancement, size/s

#3153 chore: add ELv2 license
  LICENSE.cloud
Labels: chore, size/s

#3148 feat(cloud): `POST /tenants`
  .scripts/package.sh
  packages/cli/src/commands/database/seed/tables.ts
  packages/cli/src/commands/database/seed/tenant.ts
  packages/cloud/package.json
  packages/cloud/src/libraries/tenants.ts
  packages/cloud/src/middleware/with-auth.ts
  packages/cloud/src/queries/index.ts
  packages/cloud/src/queries/tenants.ts
  packages/cloud/src/queries/users.ts
  packages/cloud/src/queries/utils.ts
  packages/cloud/src/routes/tenants.ts
  packages/cloud/src/utils/query.ts
  packages/core/package.json
  packages/core/src/test-utils/query-client.ts
  packages/integration-tests/package.json
  packages/schemas/alterations/next-1676823841-update-sie-primary-key.ts
  packages/schemas/package.json
  packages/schemas/src/seeds/application.ts
  packages/schemas/src/seeds/logto-config.ts
  packages/schemas/src/seeds/management-api.ts
  packages/schemas/src/seeds/sign-in-experience.ts
  packages/schemas/tables/sign_in_experiences.sql
  packages/shared/package.json
  packages/shared/src/index.ts
  packages/shared/src/models/index.ts
  packages/shared/src/models/tenant.ts
  pnpm-lock.yaml
Labels: feature, size/l

#3141 refactor(ui): update form validation logic
  packages/ui/src/containers/SetPassword/index.test.tsx
  packages/ui/src/containers/SetPassword/index.tsx
  packages/ui/src/pages/Continue/IdentifierProfileForm/index.tsx
  packages/ui/src/pages/ForgotPassword/ForgotPasswordForm/index.tsx
  packages/ui/src/pages/Register/IdentifierRegisterForm/index.test.tsx
  packages/ui/src/pages/Register/IdentifierRegisterForm/index.tsx
  packages/ui/src/pages/SignIn/IdentifierSignInForm/index.tsx
  packages/ui/src/pages/SignIn/PasswordSignInForm/index.test.tsx
  packages/ui/src/pages/SignIn/PasswordSignInForm/index.tsx
  packages/ui/src/pages/SignInPassword/PasswordForm/index.tsx
Labels: enhancement, size/s

#3151 refactor(cloud): wrap create tenant in transaction
  packages/cloud/package.json
  packages/cloud/src/consts/rbac.ts
  packages/cloud/src/index.ts
  packages/cloud/src/libraries/tenants.ts
  packages/cloud/src/middleware/with-auth.ts
  packages/cloud/src/queries/tenants.ts
  packages/cloud/src/queries/users.ts
  packages/cloud/src/queries/utils.ts
  packages/cloud/src/routes/tenants.ts
  packages/schemas/src/seeds/management-api.ts
Labels: enhancement, size/m

#3140 refactor(ui): refactor smart input field
  packages/ui/src/components/InputFields/SmartInputField/index.test.tsx
  packages/ui/src/components/InputFields/SmartInputField/index.tsx
  packages/ui/src/components/InputFields/SmartInputField/use-smart-input-field.ts
  packages/ui/src/components/InputFields/SmartInputField/utils.test.ts
  packages/ui/src/components/InputFields/SmartInputField/utils.ts
  packages/ui/src/components/InputFields/index.tsx
  packages/ui/src/containers/ForgotPasswordLink/index.tsx
  packages/ui/src/containers/SetPassword/index.test.tsx
  packages/ui/src/containers/SetPassword/index.tsx
  packages/ui/src/pages/Continue/IdentifierProfileForm/index.tsx
  packages/ui/src/pages/ForgotPassword/ForgotPasswordForm/index.tsx
  packages/ui/src/pages/ForgotPassword/index.tsx
  packages/ui/src/pages/Register/IdentifierRegisterForm/index.test.tsx
  packages/ui/src/pages/Register/IdentifierRegisterForm/index.tsx
  packages/ui/src/pages/SignIn/IdentifierSignInForm/index.tsx
  packages/ui/src/pages/SignIn/PasswordSignInForm/index.test.tsx
  packages/ui/src/pages/SignIn/PasswordSignInForm/index.tsx
  packages/ui/src/pages/SignInPassword/PasswordForm/index.tsx
  packages/ui/src/utils/form.ts
Labels: enhancement, size/xl

#3117 fix(ui): native app postMessage listener should be registered properly
  packages/ui/src/containers/SocialSignIn/SocialSignInList/index.tsx
  packages/ui/src/containers/SocialSignIn/index.tsx
Labels: bugfix, size/xs

#3144 feat(console): add `isCloud` constant
  packages/console/src/App.tsx
  packages/console/src/cloud/components/ActionBar/index.module.scss
  packages/console/src/cloud/components/ActionBar/index.tsx
  packages/console/src/cloud/components/CardSelector/CardSelector.tsx
  packages/console/src/cloud/components/CardSelector/MultiCardSelector/index.module.scss
  packages/console/src/cloud/components/CardSelector/MultiCardSelector/index.tsx
  packages/console/src/cloud/components/CardSelector/index.tsx
  packages/console/src/cloud/components/CardSelector/types.ts
  packages/console/src/cloud/components/ProgressBar/index.module.scss
  packages/console/src/cloud/components/ProgressBar/index.tsx
  packages/console/src/cloud/pages/About/index.module.scss
  packages/console/src/cloud/pages/About/index.tsx
  packages/console/src/cloud/pages/About/options.tsx
  packages/console/src/cloud/pages/Cloud/index.module.scss
  packages/console/src/cloud/pages/Cloud/index.tsx
  packages/console/src/cloud/pages/Congrats/index.module.scss
  packages/console/src/cloud/pages/Congrats/index.tsx
  packages/console/src/cloud/pages/Welcome/index.module.scss
  packages/console/src/cloud/pages/Welcome/index.tsx
  packages/console/src/cloud/pages/Welcome/options.tsx
  packages/console/src/cloud/scss/cloud-page-size.scss
  packages/console/src/cloud/scss/layout.module.scss
  packages/console/src/cloud/types.ts
  packages/console/src/cloud/utils.ts
  packages/console/src/consts/cloud.ts
  packages/console/src/pages/Cloud/index.tsx
Labels: feature, size/s

#3158 feat(phrases): add "ru" language
  packages/phrases-ui/src/index.ts
  packages/phrases-ui/src/locales/ru.ts
Labels: feature, size/m

#3126 feat(console): new style for create and edit connector
  packages/console/src/pages/ConnectorDetails/components/ConnectorContent.module.scss
  packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx
  packages/console/src/pages/Connectors/components/Guide/index.module.scss
  packages/console/src/pages/Connectors/components/Guide/index.tsx
  packages/console/src/pages/Connectors/utils/index.ts
  packages/phrases/src/locales/de/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/de/translation/admin-console/connectors.ts
  packages/phrases/src/locales/en/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/en/translation/admin-console/connectors.ts
  packages/phrases/src/locales/fr/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/ko/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/connectors.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/connectors.ts
Labels: feature, size/m

#3127 feat: enabled connector db read and write
  packages/core/src/__mocks__/connector-base-data.ts
  packages/core/src/__mocks__/connector.ts
  packages/core/src/libraries/connector.test.ts
  packages/core/src/libraries/social.ts
  packages/core/src/queries/connector.test.ts
  packages/core/src/queries/connector.ts
  packages/core/src/routes/connector.ts
  packages/core/src/routes/interaction/utils/social-verification.test.ts
  packages/core/src/routes/interaction/utils/social-verification.ts
  packages/schemas/alterations/next-1676886855-connector-database-read-write.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/types/connector.ts
  packages/schemas/tables/connectors.sql
  packages/toolkit/connector-kit/src/types.ts
Labels: feature, size/m

#3166 fix(toolkit): capitalize initial letter in language names
  packages/toolkit/language-kit/src/const.ts
Labels: bugfix, size/xs

#3157 refactor(ui): passing in social connectors as props
  packages/ui/src/containers/SocialSignIn/index.tsx
  packages/ui/src/pages/Register/index.tsx
  packages/ui/src/pages/SignIn/Main.tsx
Labels: enhancement, size/s

#3154 ci: build cloud Docker image
  .github/workflows/main.yml
  .github/workflows/release-cloud.yml
  Dockerfile.cloud
Labels: size/s

#3159 feat(cloud): add status apis
  packages/cloud/src/index.ts
  packages/cloud/src/middleware/with-pathname.ts
  packages/cloud/src/routes-anonymous/index.ts
Labels: feature, size/s

#3161 fix(ui): update country code detection logic
  packages/ui/src/utils/country-code.test.ts
  packages/ui/src/utils/country-code.ts
Labels: bugfix, size/s

#3155 feat: custom css
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/queries/sign-in-experience.test.ts
  packages/schemas/alterations/next-1676874936-support-custom-css.ts
  packages/schemas/src/seeds/sign-in-experience.ts
  packages/schemas/tables/sign_in_experiences.sql
  packages/ui/src/App.tsx
  packages/ui/src/__mocks__/logto.tsx
Labels: feature, size/m

#3167 refactor(ui): clean up the field validation file
  packages/ui/src/containers/SetPassword/index.tsx
  packages/ui/src/utils/field-validations.ts
  packages/ui/src/utils/form.ts
Labels: enhancement, size/m

#3129 feat(toolkit): add description and tooltip for formItems
  .changeset/curly-apes-tease.md
  packages/toolkit/connector-kit/src/types.ts
Labels: feature, size/xs

#3165 refactor: remove demo app db entity
  packages/cli/src/commands/database/seed/tables.ts
  packages/console/src/pages/GetStarted/hook.ts
  packages/core/src/env-set/utils.ts
  packages/core/src/middleware/koa-check-demo-app.ts
  packages/core/src/oidc/adapter.ts
  packages/core/src/tenants/Tenant.test.ts
  packages/core/src/tenants/Tenant.ts
  packages/integration-tests/src/tests/api/application.test.ts
  packages/schemas/alterations/next-1676906977-remove-demo-app.ts
  packages/schemas/package.json
  packages/schemas/src/seeds/application.ts
  pnpm-lock.yaml
Labels: enhancement, size/m

#3162 refactor(core,ui): refactor get phrases for preview
  packages/core/src/routes/phrase.test.ts
  packages/core/src/routes/phrase.ts
  packages/ui/src/App.tsx
  packages/ui/src/apis/settings.ts
  packages/ui/src/i18n/init.ts
  packages/ui/src/i18n/utils.ts
Labels: enhancement, size/m

#3160 fix(ui): prevent infinite getPhrase api call
  packages/core/src/routes/phrase.test.ts
  packages/core/src/routes/phrase.ts
  packages/ui/src/App.tsx
  packages/ui/src/apis/settings.ts
  packages/ui/src/hooks/use-preview.ts
  packages/ui/src/i18n/init.ts
  packages/ui/src/i18n/utils.ts
Labels: bugfix, size/m

#3174 style(ui): replace error page icon
  packages/ui/src/assets/icons/empty_state.svg
  packages/ui/src/assets/icons/empty_state_dark.svg
  packages/ui/src/assets/icons/error.svg
  packages/ui/src/pages/ErrorPage/index.module.scss
  packages/ui/src/pages/ErrorPage/index.tsx
Labels: size/m

#3171 refactor: move console sie to database
  .github/workflows/integration-test.yml
  packages/cli/src/commands/database/seed/tables.ts
  packages/core/src/libraries/session.ts
  packages/core/src/libraries/sign-in-experience/index.ts
  packages/core/src/libraries/sign-in-experience/sign-up.test.ts
  packages/core/src/oidc/init.ts
  packages/core/src/routes/consts.ts
  packages/core/src/routes/interaction/actions/submit-interaction.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/core/src/routes/interaction/index.test.ts
  packages/core/src/routes/interaction/middleware/koa-interaction-sie.ts
  packages/core/src/routes/phrase.test.ts
  packages/core/src/routes/phrase.ts
  packages/core/src/routes/well-known.test.ts
  packages/core/src/routes/well-known.ts
  packages/integration-tests/jest.config.js
  packages/integration-tests/jest.setup.api.js
  packages/integration-tests/src/api/index.ts
  packages/integration-tests/src/api/wellknown.ts
  packages/integration-tests/src/client/index.ts
  packages/integration-tests/src/tests/api/well-known.test.ts
  packages/integration-tests/src/tests/api/wellknown.test.ts
  packages/phrases-ui/src/locales/de.ts
  packages/phrases-ui/src/locales/en.ts
  packages/phrases-ui/src/locales/fr.ts
  packages/phrases-ui/src/locales/ko.ts
  packages/phrases-ui/src/locales/pt-br.ts
  packages/phrases-ui/src/locales/pt-pt.ts
  packages/phrases-ui/src/locales/ru.ts
  packages/phrases-ui/src/locales/tr-tr.ts
  packages/phrases-ui/src/locales/zh-cn.ts
  packages/phrases/src/locales/de/translation/demo-app.ts
  packages/phrases/src/locales/en/translation/demo-app.ts
  packages/phrases/src/locales/fr/translation/demo-app.ts
  packages/phrases/src/locales/ko/translation/demo-app.ts
  packages/phrases/src/locales/pt-br/translation/demo-app.ts
  packages/phrases/src/locales/pt-pt/translation/demo-app.ts
  packages/phrases/src/locales/tr-tr/translation/demo-app.ts
  packages/phrases/src/locales/zh-cn/translation/demo-app.ts
  packages/schemas/alterations/next-1676906977-remove-demo-app.ts
  packages/schemas/alterations/next-1676956206-move-console-sie-to-database.ts
  packages/schemas/src/seeds/sign-in-experience.ts
  packages/ui/src/components/Notification/AppNotification/index.tsx
  packages/ui/src/containers/AppNotification/index.tsx
Labels: enhancement, size/xl

#3175 refactor(ui): properly set autocomplete props
  packages/ui/src/components/InputFields/SmartInputField/index.tsx
  packages/ui/src/components/InputFields/SmartInputField/utils.test.ts
  packages/ui/src/components/InputFields/SmartInputField/utils.ts
  packages/ui/src/pages/Continue/IdentifierProfileForm/index.tsx
  packages/ui/src/pages/ForgotPassword/ForgotPasswordForm/index.tsx
  packages/ui/src/pages/Register/IdentifierRegisterForm/index.tsx
  packages/ui/src/pages/SignIn/IdentifierSignInForm/index.tsx
  packages/ui/src/pages/SignIn/PasswordSignInForm/index.tsx
Labels: enhancement, size/s

#3156 chore(phrases): align terms in phrases to capitalized case
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
Labels: chore, size/s

#3169 refactor(ui): hard code the page slogan
  packages/phrases-ui/src/locales/de.ts
  packages/phrases-ui/src/locales/en.ts
  packages/phrases-ui/src/locales/fr.ts
  packages/phrases-ui/src/locales/ko.ts
  packages/phrases-ui/src/locales/pt-br.ts
  packages/phrases-ui/src/locales/pt-pt.ts
  packages/phrases-ui/src/locales/ru.ts
  packages/phrases-ui/src/locales/tr-tr.ts
  packages/phrases-ui/src/locales/zh-cn.ts
  packages/ui/src/components/BrandingHeader/index.test.tsx
  packages/ui/src/components/BrandingHeader/index.tsx
  packages/ui/src/containers/LandingPageContainer/index.tsx
  packages/ui/src/pages/Register/index.tsx
  packages/ui/src/pages/SignIn/index.tsx
Labels: enhancement, size/s

#3178 chore(console): polish subtitle wording in various pages
  packages/phrases/src/locales/de/translation/admin-console/applications.ts
  packages/phrases/src/locales/en/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/en/translation/admin-console/applications.ts
  packages/phrases/src/locales/en/translation/admin-console/get-started.ts
  packages/phrases/src/locales/en/translation/admin-console/logs.ts
  packages/phrases/src/locales/fr/translation/admin-console/applications.ts
  packages/phrases/src/locales/ko/translation/admin-console/applications.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/applications.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/applications.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/applications.ts
Labels: chore, size/s

#3179 refactor: fix cloud env
  Dockerfile
  Dockerfile.cloud
  package.json
  packages/cloud/package.json
  packages/cloud/src/env-set/index.ts
  packages/core/package.json
  packages/core/src/middleware/koa-cors.ts
  packages/core/src/oidc/adapter.ts
Labels: enhancement, size/s

#3163 fix(phrases): ru translation mismatches
  packages/phrases-ui/src/locales/ru.ts
Labels: bugfix, size/s

#3170 fix(core): should throw error when multiple connector factories have same id
  packages/core/src/routes/connector.ts
  packages/core/src/utils/connectors/factories.ts
  packages/phrases/src/locales/de/errors.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko/errors.ts
  packages/phrases/src/locales/pt-br/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
Labels: bugfix, size/s

#3185 refactor: move admin console app to database
  packages/cli/src/commands/database/seed/tables.ts
  packages/console/src/App.tsx
  packages/console/src/consts/management-api.ts
  packages/console/src/consts/tenants.ts
  packages/console/src/hooks/use-api.ts
  packages/core/src/middleware/koa-console-redirect-proxy.ts
  packages/core/src/oidc/adapter.ts
  packages/core/src/tenants/Tenant.ts
  packages/schemas/alterations/next-1676956206-move-console-sie-to-database.ts
  packages/schemas/alterations/next-1677059985-move-console-application-to-database.ts
  packages/schemas/src/consts/cloud.ts
  packages/schemas/src/consts/index.ts
  packages/schemas/src/consts/oidc.ts
  packages/schemas/src/consts/system.ts
  packages/schemas/src/seeds/application.ts
Labels: enhancement, size/m

#3186 refactor: fix cloud env
  Dockerfile.cloud
  packages/console/src/containers/AppLayout/components/UserInfo/index.tsx
  packages/core/src/tenants/Tenant.ts
Labels: enhancement, chore, size/s

#3188 refactor(console): welcome state of the sie page
  packages/console/src/assets/images/sign-in-experience-welcome-dark.svg
  packages/console/src/assets/images/sign-in-experience-welcome.svg
  packages/console/src/pages/SignInExperience/components/Welcome/index.module.scss
  packages/console/src/pages/SignInExperience/components/Welcome/index.tsx
  packages/console/src/pages/SignInExperience/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
Labels: enhancement, size/l

#3177 feat(console): early bird gift
  packages/console/src/assets/images/gift.svg
  packages/console/src/cloud/components/EarlyBirdGift/GiftModal/index.module.scss
  packages/console/src/cloud/components/EarlyBirdGift/GiftModal/index.tsx
  packages/console/src/cloud/components/EarlyBirdGift/index.tsx
  packages/console/src/cloud/components/Reservation/index.module.scss
  packages/console/src/cloud/components/Reservation/index.tsx
  packages/console/src/cloud/constants/index.ts
  packages/console/src/cloud/pages/Congrats/index.module.scss
  packages/console/src/cloud/pages/Congrats/index.tsx
  packages/console/src/components/CardTitle/index.module.scss
  packages/console/src/components/CardTitle/index.tsx
  packages/console/src/components/ModalLayout/index.tsx
  packages/console/src/containers/AppLayout/components/Topbar/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/cloud.ts
  packages/phrases/src/locales/en/translation/admin-console/cloud.ts
  packages/phrases/src/locales/fr/translation/admin-console/cloud.ts
  packages/phrases/src/locales/ko/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/cloud.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/cloud.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/cloud.ts
Labels: feature, size/l

#3172 feat(console): submit cloud questionnaire
  packages/console/src/cloud/hooks/use-user-onboarding-data.ts
  packages/console/src/cloud/pages/About/index.tsx
  packages/console/src/cloud/pages/Cloud/index.tsx
  packages/console/src/cloud/pages/Welcome/index.tsx
  packages/console/src/cloud/types.ts
  packages/console/src/hooks/use-me-custom-data.ts
  packages/console/src/hooks/use-user-preferences.ts
Labels: feature, size/l

#3176 refactor(ui): optimize smart input animation
  packages/ui/package.json
  packages/ui/src/components/InputFields/InputField/index.module.scss
  packages/ui/src/components/InputFields/InputField/index.tsx
  packages/ui/src/components/InputFields/SmartInputField/AnimatedPrefix/index.module.scss
  packages/ui/src/components/InputFields/SmartInputField/AnimatedPrefix/index.tsx
  packages/ui/src/components/InputFields/SmartInputField/CountryCodeSelector/index.module.scss
  packages/ui/src/components/InputFields/SmartInputField/index.test.tsx
  packages/ui/src/components/InputFields/SmartInputField/index.tsx
  packages/ui/src/pages/ForgotPassword/index.test.tsx
  pnpm-lock.yaml
Labels: enhancement, size/m

#3191 refactor(console): refactor cloud router
  packages/console/src/App.tsx
  packages/console/src/cloud/App.module.scss
  packages/console/src/cloud/App.tsx
  packages/console/src/cloud/pages/Cloud/index.module.scss
  packages/console/src/cloud/pages/Main/index.tsx
  packages/console/src/cloud/pages/Onboard/index.module.scss
  packages/console/src/cloud/pages/Onboard/index.tsx
  packages/console/src/cloud/types.ts
  packages/console/src/consts/tenants.ts
Labels: enhancement, size/s

#3181 fix(core): mount OIDC after all middlewares
  packages/core/src/tenants/Tenant.ts
Labels: bugfix, size/xs

#3194 style(ui): adjust input suffix button padding space
  packages/ui/src/components/InputFields/InputField/index.module.scss
Labels: size/xs

#3195 style(ui): adjust LandingPage spacing
  packages/ui/src/containers/AppContent/index.module.scss
  packages/ui/src/containers/LandingPageContainer/index.module.scss
  packages/ui/src/containers/SocialSignIn/SocialSignInList/index.module.scss
Labels: size/s

#3196 style(ui): mobile home page spacing
  packages/ui/src/containers/LandingPageContainer/index.module.scss
Labels: size/xs

#3197 refactor(ui): remove continue page notification
  packages/ui/src/containers/VerificationCode/use-sign-in-flow-code-verification.ts
  packages/ui/src/hooks/use-password-sign-in.ts
  packages/ui/src/hooks/use-required-profile-error-handler.ts
  packages/ui/src/hooks/use-social-sign-in-listener.ts
  packages/ui/src/pages/Continue/index.tsx
  packages/ui/src/types/guard.ts
Labels: enhancement, size/s

#3202 fix(core): fix empty error message
  packages/core/src/routes/interaction/utils/sign-in-experience-validation.ts
Labels: bugfix, size/s

#3183 feat(core): update the OIDC post signout page
  packages/core/src/oidc/init.ts
  packages/core/static/html/post-logout/favicon.ico
  packages/core/static/html/post-logout/index.html
  packages/phrases/src/locales/de/translation/index.ts
  packages/phrases/src/locales/de/translation/oidc.ts
  packages/phrases/src/locales/en/translation/index.ts
  packages/phrases/src/locales/en/translation/oidc.ts
  packages/phrases/src/locales/fr/translation/index.ts
  packages/phrases/src/locales/fr/translation/oidc.ts
  packages/phrases/src/locales/ko/translation/index.ts
  packages/phrases/src/locales/ko/translation/oidc.ts
  packages/phrases/src/locales/pt-br/translation/index.ts
  packages/phrases/src/locales/pt-br/translation/oidc.ts
  packages/phrases/src/locales/pt-pt/translation/index.ts
  packages/phrases/src/locales/pt-pt/translation/oidc.ts
  packages/phrases/src/locales/tr-tr/translation/index.ts
  packages/phrases/src/locales/tr-tr/translation/oidc.ts
  packages/phrases/src/locales/zh-cn/translation/index.ts
  packages/phrases/src/locales/zh-cn/translation/oidc.ts
Labels: feature, size/m

#3198 fix(phrases): update some zh content
  packages/phrases-ui/src/locales/zh-cn.ts
Labels: bugfix, size/s

#3209 refactor: fix alteration script
  .scripts/check-alterations-sequence.js
  packages/core/src/queries/user.ts
  packages/schemas/alterations/next-1676956206-move-console-sie-to-database.ts
Labels: enhancement, size/xs

#3184 feat(cloud): new APIs for social linking/unlinking in cloud AC
  packages/core/src/routes-me/init.ts
  packages/core/src/routes-me/social.ts
  packages/core/src/routes-me/types.ts
  packages/phrases/src/locales/de/errors.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko/errors.ts
  packages/phrases/src/locales/pt-br/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
Labels: feature, size/m

#3192 feat(core): provide `/me` APIs for user password and verification code in cloud AC
  packages/core/src/routes-me/init.ts
  packages/core/src/routes-me/user.ts
  packages/core/src/routes-me/verification-code.ts
Labels: feature, size/m

#3206 chore: opensource -> open-source
  packages/console/src/cloud/pages/Welcome/options.tsx
  packages/console/src/cloud/types.ts
  packages/phrases/src/locales/de/translation/admin-console/cloud.ts
  packages/phrases/src/locales/en/translation/admin-console/cloud.ts
  packages/phrases/src/locales/fr/translation/admin-console/cloud.ts
  packages/phrases/src/locales/ko/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/cloud.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/cloud.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/cloud.ts
Labels: chore, size/s

#3201 fix(core): should not block social email/phone identifiers by SIE
  packages/core/src/routes/interaction/utils/sign-in-experience-valiation.test.ts
  packages/core/src/routes/interaction/utils/sign-in-experience-validation.ts
Labels: bugfix, size/s

#3199 refactor(core): throw registered social email or phone info
  packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.test.ts
  packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.ts
  packages/ui/src/hooks/use-required-profile-error-handler.ts
Labels: enhancement, size/s

#3200 fix(console): font size of readme title and card title should be 16px
  packages/console/src/pages/Connectors/components/Guide/index.module.scss
Labels: bugfix, size/xs

#3210 chore: update connector AC contents
  packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx
  packages/console/src/pages/Connectors/components/ConnectorForm/BasicForm.tsx
  packages/console/src/pages/Connectors/components/Guide/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/de/translation/admin-console/connectors.ts
  packages/phrases/src/locales/en/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/en/translation/admin-console/connectors.ts
  packages/phrases/src/locales/fr/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/ko/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/connectors.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/connectors.ts
Labels: chore, size/m

#3193 feat(console): page error state
  packages/console/src/assets/images/request-error-dark.svg
  packages/console/src/assets/images/request-error.svg
  packages/console/src/components/RequestDataError/index.module.scss
  packages/console/src/components/RequestDataError/index.tsx
  packages/console/src/components/Table/TableError.tsx
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/AuditLogDetails/index.tsx
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/RoleDetails/index.tsx
  packages/console/src/pages/Settings/index.tsx
  packages/console/src/pages/SignInExperience/index.module.scss
  packages/console/src/pages/SignInExperience/index.tsx
  packages/console/src/pages/UserDetails/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/errors.ts
  packages/phrases/src/locales/en/translation/admin-console/errors.ts
  packages/phrases/src/locales/fr/translation/admin-console/errors.ts
  packages/phrases/src/locales/ko/translation/admin-console/errors.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/errors.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/errors.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/errors.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/errors.ts
Labels: feature, size/xl

#3207 refactor(console): rename `cloudPage` to `onboardPage`
  packages/console/src/cloud/pages/About/index.tsx
  packages/console/src/cloud/pages/Congrats/index.tsx
  packages/console/src/cloud/pages/Onboard/index.tsx
  packages/console/src/cloud/pages/Welcome/index.tsx
  packages/console/src/cloud/types.ts
  packages/console/src/cloud/utils.ts
Labels: enhancement, size/s

#3190 chore: update configs
  .gitpod.yml
  Dockerfile.cloud
  packages/cloud/src/env-set/index.ts
  packages/console/src/consts/tenants.ts
Labels: chore, size/s

#3213 fix(console): fix passwordless connectors test title
  packages/console/src/pages/Connectors/components/Guide/index.tsx
Labels: bugfix, size/xs

#3217 chore: add changeset for ru translation
  .changeset-staged/lemon-cars-wonder.md
Labels: chore, size/xs

#3216 fix(ui): update SmartInput animation
  packages/ui/src/__mocks__/logto.tsx
  packages/ui/src/components/InputFields/SmartInputField/AnimatedPrefix/index.tsx
  packages/ui/src/components/InputFields/SmartInputField/index.test.tsx
  packages/ui/src/pages/ForgotPassword/index.test.tsx
Labels: bugfix, size/s

#3203 feat(core): added a new endpoint to replace user roles
  packages/core/src/__mocks__/index.ts
  packages/core/src/routes/admin-user-role.test.ts
  packages/core/src/routes/admin-user-role.ts
Labels: feature, size/s

#3211 chore(core): add change set for smart input field
  .changeset-staged/many-avocados-know.md
Labels: chore, size/s

#3214 fix(console): change password should use me router api
  packages/console/src/pages/Settings/components/ChangePassword.tsx
Labels: bugfix, size/xs

#3220 chore(console): rename target to idp name
  packages/phrases/src/locales/en/translation/admin-console/connectors.ts
Labels: chore, size/xs

#3218 chore: add changesets
  .changeset-staged/empty-rockets-march.md
  .changeset-staged/fast-toys-share.md
Labels: chore, size/s

#3222 refactor(phrases): update demo app notification
  packages/phrases-ui/src/locales/de.ts
  packages/phrases-ui/src/locales/en.ts
  packages/phrases-ui/src/locales/fr.ts
  packages/phrases-ui/src/locales/ko.ts
  packages/phrases-ui/src/locales/pt-br.ts
  packages/phrases-ui/src/locales/pt-pt.ts
  packages/phrases-ui/src/locales/ru.ts
  packages/phrases-ui/src/locales/tr-tr.ts
  packages/phrases-ui/src/locales/zh-cn.ts
Labels: enhancement, size/s

#3221 Revert "refactor(ui): hard code the page slogan"
  packages/phrases-ui/src/locales/de.ts
  packages/phrases-ui/src/locales/en.ts
  packages/phrases-ui/src/locales/fr.ts
  packages/phrases-ui/src/locales/ko.ts
  packages/phrases-ui/src/locales/pt-br.ts
  packages/phrases-ui/src/locales/pt-pt.ts
  packages/phrases-ui/src/locales/ru.ts
  packages/phrases-ui/src/locales/tr-tr.ts
  packages/phrases-ui/src/locales/zh-cn.ts
  packages/ui/src/components/BrandingHeader/index.test.tsx
  packages/ui/src/components/BrandingHeader/index.tsx
  packages/ui/src/containers/LandingPageContainer/index.tsx
  packages/ui/src/pages/Register/index.tsx
  packages/ui/src/pages/SignIn/index.tsx
Labels: size/s

#3224 chore: update logo
  README.md
  logo.png
Labels: chore, size/xs

#3223 chore: update docker-compose file and README
  README.md
  docker-compose.yml
Labels: enhancement, chore, size/s

#3208 refactor(console): get-started tasks
  packages/console/src/consts/external-links.ts
  packages/console/src/consts/index.ts
  packages/console/src/containers/AppContent/Sidebar/components/Contact/hook.tsx
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/Connectors/components/Guide/index.tsx
  packages/console/src/pages/GetStarted/hook.ts
  packages/core/src/__mocks__/index.ts
  packages/core/src/routes/logto-config.test.ts
  packages/phrases/src/locales/de/translation/admin-console/general.ts
  packages/phrases/src/locales/de/translation/admin-console/get-started.ts
  packages/phrases/src/locales/en/translation/admin-console/general.ts
  packages/phrases/src/locales/en/translation/admin-console/get-started.ts
  packages/phrases/src/locales/fr/translation/admin-console/general.ts
  packages/phrases/src/locales/fr/translation/admin-console/get-started.ts
  packages/phrases/src/locales/ko/translation/admin-console/general.ts
  packages/phrases/src/locales/ko/translation/admin-console/get-started.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/get-started.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/get-started.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/get-started.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/get-started.ts
  packages/schemas/alterations/next-1677208902-update-admin-console-config.ts
  packages/schemas/src/seeds/logto-config.ts
  packages/schemas/src/types/logto-config.ts
Labels: enhancement, size/xl

#3229 style(console): fix connector dark collapse button margin
  packages/console/src/pages/Connectors/components/ConnectorForm/BasicForm.module.scss
  packages/console/src/pages/Connectors/components/ConnectorForm/BasicForm.tsx
Labels: size/s

#3234 refactor(console): remove i18n text context
  packages/console/package.json
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorStatus/index.tsx
  packages/console/src/pages/SignInExperience/components/SignUpAndSignInChangePreview/SignUpAndSignInDiffSection/SignInDiffSection.tsx
  packages/console/src/pages/SignInExperience/components/SignUpAndSignInChangePreview/SignUpAndSignInDiffSection/SignUpDiffSection.tsx
  packages/console/src/pages/SignInExperience/constants.ts
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/SignUpForm.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/ConnectorSetupWarning.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SignInMethodEditBox/AddButton.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SignInMethodEditBox/SignInMethodItem.tsx
  packages/phrases/src/locales/de/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
  pnpm-lock.yaml
Labels: enhancement, size/m

#3204 feat(console): new profile settings page
  packages/console/src/containers/AppLayout/components/UserInfo/index.tsx
  packages/console/src/pages/Profile/components/CardContent/index.module.scss
  packages/console/src/pages/Profile/components/CardContent/index.tsx
  packages/console/src/pages/Profile/components/Section/index.module.scss
  packages/console/src/pages/Profile/components/Section/index.tsx
  packages/console/src/pages/Profile/index.module.scss
  packages/console/src/pages/Profile/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/index.ts
  packages/phrases/src/locales/de/translation/admin-console/profile.ts
  packages/phrases/src/locales/en/translation/admin-console/index.ts
  packages/phrases/src/locales/en/translation/admin-console/profile.ts
  packages/phrases/src/locales/fr/translation/admin-console/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/profile.ts
  packages/phrases/src/locales/ko/translation/admin-console/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/profile.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/profile.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/profile.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/profile.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/profile.ts
Labels: feature, size/xl

#3233 fix(ui): fix typo which could result in undesirable reminder content
  packages/ui/src/containers/VerificationCode/use-sign-in-flow-code-verification.ts
Labels: bugfix, size/xs
