Repository logto-io/logto, pull requests merged in 2023-11, with the labels that each got.

#4791 fix(console): organization guide should check required fields on navigation
  packages/console/src/pages/Organizations/Guide/CreatePermissions/index.tsx
  packages/console/src/pages/Organizations/Guide/CreateRoles/index.tsx
Labels: bugfix, size/s

#4795 feat(core): add get sso-connectors by email interaction api
  packages/core/src/__mocks__/sso.ts
  packages/core/src/libraries/sign-in-experience/index.test.ts
  packages/core/src/libraries/sign-in-experience/index.ts
  packages/core/src/libraries/sso-connector.test.ts
  packages/core/src/libraries/sso-connector.ts
  packages/core/src/routes/interaction/single-sign-on.ts
  packages/integration-tests/src/api/interaction-sso.ts
  packages/integration-tests/src/tests/api/interaction/single-sign-on/happy-path.test.ts
  packages/integration-tests/src/tests/api/well-known.test.ts
  packages/schemas/src/types/sso-connector.ts
Labels: feature, size/l

#4794 refactor(experience): generate webauthn options before switching to the webauthn page
  packages/experience/src/containers/MfaFactorList/index.tsx
  packages/experience/src/hooks/use-mfa-error-handler.ts
  packages/experience/src/hooks/use-start-webauthn-processing.ts
  packages/experience/src/hooks/use-webauthn-operation.ts
  packages/experience/src/pages/MfaBinding/WebAuthnBinding/index.tsx
  packages/experience/src/pages/MfaVerification/WebAuthnVerification/index.tsx
  packages/experience/src/types/guard.ts
  packages/experience/src/types/index.ts
  packages/experience/src/utils/webauthn.ts
Labels: enhancement, size/l

#4802 chore(phrases): add dev tenant phrases
  packages/phrases/src/locales/de/translation/admin-console/general.ts
  packages/phrases/src/locales/de/translation/admin-console/tenants.ts
  packages/phrases/src/locales/en/translation/admin-console/general.ts
  packages/phrases/src/locales/en/translation/admin-console/tenants.ts
  packages/phrases/src/locales/es/translation/admin-console/general.ts
  packages/phrases/src/locales/es/translation/admin-console/tenants.ts
  packages/phrases/src/locales/fr/translation/admin-console/general.ts
  packages/phrases/src/locales/fr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/it/translation/admin-console/general.ts
  packages/phrases/src/locales/it/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ja/translation/admin-console/general.ts
  packages/phrases/src/locales/ja/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ko/translation/admin-console/general.ts
  packages/phrases/src/locales/ko/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/general.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ru/translation/admin-console/general.ts
  packages/phrases/src/locales/ru/translation/admin-console/tenants.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tenants.ts
Labels: chore, size/xl

#4801 feat(schemas): add user sso identities table
  packages/schemas/alterations/next-1698820410-add-user-sso-identities-table.ts
  packages/schemas/tables/user_sso_identities.sql
Labels: feature, size/s

#4798 refactor(core,schemas,console): refactor log key types and sso-connector authn-url api name
  packages/console/src/consts/logs.ts
  packages/core/src/routes/interaction/additional.ts
  packages/core/src/routes/interaction/single-sign-on.ts
  packages/core/src/routes/interaction/verifications/identifier-payload-verification.ts
  packages/integration-tests/src/api/interaction-sso.ts
  packages/schemas/alterations/next-1698820410-add-user-sso-identities-table.ts
  packages/schemas/src/types/log/interaction.ts
  packages/schemas/tables/user_sso_identities.sql
Labels: enhancement, size/m

#4790 fix(core): check user mfa when binding backup code
  packages/core/src/routes/interaction/mfa.test.ts
  packages/core/src/routes/interaction/mfa.ts
Labels: bugfix, size/s

#4803 refactor(console): fix organization issues
  packages/console/src/assets/icons/role-feature.svg
  packages/console/src/components/OrganizationRolesSelect/index.module.scss
  packages/console/src/components/OrganizationRolesSelect/index.tsx
  packages/console/src/ds-components/Button/index.module.scss
  packages/console/src/ds-components/Select/MultiSelect.tsx
  packages/console/src/ds-components/Select/index.module.scss
  packages/console/src/pages/OrganizationDetails/Members/AddMembersToOrganization.tsx
  packages/console/src/pages/OrganizationDetails/Members/index.tsx
  packages/console/src/pages/Organizations/OrganizationsTable/index.tsx
  packages/console/src/pages/Organizations/PermissionsField/index.tsx
  packages/console/src/pages/Organizations/RolesField/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/de/translation/admin-console/organizations.ts
  packages/phrases/src/locales/de/translation/admin-console/user-details.ts
  packages/phrases/src/locales/en/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/en/translation/admin-console/organizations.ts
  packages/phrases/src/locales/en/translation/admin-console/user-details.ts
  packages/phrases/src/locales/es/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/es/translation/admin-console/organizations.ts
  packages/phrases/src/locales/es/translation/admin-console/user-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/organizations.ts
  packages/phrases/src/locales/fr/translation/admin-console/user-details.ts
  packages/phrases/src/locales/it/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/it/translation/admin-console/organizations.ts
  packages/phrases/src/locales/it/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ja/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ko/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ru/translation/admin-console/user-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organizations.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/user-details.ts
Labels: enhancement, size/l

#4805 refactor(console): apply new layout for org settings
  packages/console/src/pages/Organizations/Guide/CreateOrganization/index.tsx
  packages/console/src/pages/Organizations/PermissionsCard/index.tsx
  packages/console/src/pages/Organizations/RolesCard/index.module.scss
  packages/console/src/pages/Organizations/RolesCard/index.tsx
  packages/console/src/pages/Organizations/Settings/index.module.scss
  packages/console/src/pages/Organizations/Settings/index.tsx
  packages/console/src/pages/Organizations/TemplateTable/index.module.scss
  packages/console/src/pages/Organizations/TemplateTable/index.tsx
  packages/console/src/pages/Organizations/index.module.scss
  packages/phrases/src/locales/de/translation/admin-console/organizations.ts
  packages/phrases/src/locales/en/translation/admin-console/organizations.ts
  packages/phrases/src/locales/es/translation/admin-console/organizations.ts
  packages/phrases/src/locales/fr/translation/admin-console/organizations.ts
  packages/phrases/src/locales/it/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ja/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ko/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ru/translation/admin-console/organizations.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/organizations.ts
Labels: enhancement, size/m

#4786 feat(core,phrases): disable auto skip mfa
  packages/core/src/routes/interaction/actions/submit-interaction.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/core/src/routes/interaction/mfa.test.ts
  packages/core/src/routes/interaction/mfa.ts
  packages/core/src/routes/interaction/types/index.ts
  packages/core/src/routes/interaction/verifications/mfa-verification.test.ts
  packages/core/src/routes/interaction/verifications/mfa-verification.ts
  packages/experience/src/apis/interaction.ts
  packages/experience/src/hooks/use-skip-mfa.ts
  packages/integration-tests/jest-puppeteer.config.js
  packages/integration-tests/src/api/interaction.ts
  packages/integration-tests/src/tests/api/interaction/mfa/totp.test.ts
  packages/integration-tests/src/tests/experience/mfa/user-controlled.test.ts
  packages/phrases/src/locales/de/errors/session.ts
  packages/phrases/src/locales/en/errors/session.ts
  packages/phrases/src/locales/es/errors/session.ts
  packages/phrases/src/locales/fr/errors/session.ts
  packages/phrases/src/locales/it/errors/session.ts
  packages/phrases/src/locales/ja/errors/session.ts
  packages/phrases/src/locales/ko/errors/session.ts
  packages/phrases/src/locales/pl-pl/errors/session.ts
  packages/phrases/src/locales/pt-br/errors/session.ts
  packages/phrases/src/locales/pt-pt/errors/session.ts
  packages/phrases/src/locales/ru/errors/session.ts
  packages/phrases/src/locales/tr-tr/errors/session.ts
  packages/phrases/src/locales/zh-cn/errors/session.ts
  packages/phrases/src/locales/zh-hk/errors/session.ts
  packages/phrases/src/locales/zh-tw/errors/session.ts
Labels: feature, size/xl

#4810 refactor(console,phrases): improve org guide introduction diagram
  packages/console/src/pages/Organizations/Guide/CreatePermissions/Introduction/Diagram.tsx
  packages/console/src/pages/Organizations/Guide/CreatePermissions/Introduction/index.module.scss
  packages/console/src/pages/Organizations/Guide/CreatePermissions/Introduction/index.tsx
  packages/console/src/pages/Organizations/Guide/CreatePermissions/index.tsx
  packages/console/src/pages/Organizations/Guide/index.module.scss
  packages/phrases/src/locales/de/translation/admin-console/organizations.ts
  packages/phrases/src/locales/en/translation/admin-console/organizations.ts
  packages/phrases/src/locales/es/translation/admin-console/organizations.ts
  packages/phrases/src/locales/fr/translation/admin-console/organizations.ts
  packages/phrases/src/locales/it/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ja/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ko/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ru/translation/admin-console/organizations.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/organizations.ts
Labels: enhancement, size/xl

#4811 feat(console): add organization details guide drawer
  packages/console/src/components/Drawer/index.module.scss
  packages/console/src/pages/OrganizationDetails/index.tsx
  packages/console/src/pages/Organizations/Guide/IntroductionAndPermissions/Introduction/Diagram.tsx
  packages/console/src/pages/Organizations/Guide/IntroductionAndPermissions/Introduction/index.module.scss
  packages/console/src/pages/Organizations/Guide/IntroductionAndPermissions/Introduction/index.tsx
  packages/console/src/pages/Organizations/Guide/IntroductionAndPermissions/index.tsx
  packages/console/src/pages/Organizations/Guide/index.tsx
Labels: feature, size/m

#4792 refactor(core,schemas): add user logto_data column to store mfa
  packages/core/src/__mocks__/user.ts
  packages/core/src/queries/user.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/core/src/routes/interaction/verifications/mfa-verification.test.ts
  packages/core/src/routes/interaction/verifications/mfa-verification.ts
  packages/schemas/alterations/next-1698910485-user-logto-data.ts
  packages/schemas/tables/users.sql
Labels: enhancement, size/s

#4817 fix(console): details page header text should not overflow its container
  packages/console/src/components/DetailsPage/DetailsPageHeader/index.module.scss
Labels: bugfix, size/xs

#4815 refactor(console): add pro tag for mfa feature
  packages/console/src/ds-components/CardTitle/index.module.scss
  packages/console/src/ds-components/CardTitle/index.tsx
  packages/console/src/pages/Mfa/PageWrapper/index.tsx
Labels: enhancement, size/s

#4813 refactor(core): disable org apis for non-dev envs
  packages/core/src/routes/organization/index.ts
Labels: enhancement, size/xs

#4816 refactor(console,phrases): improve organization empty placeholder
  packages/console/src/assets/images/organization-empty-dark.svg
  packages/console/src/assets/images/organization-empty.svg
  packages/console/src/pages/Organizations/OrganizationsTable/EmptyDataPlaceholder/index.module.scss
  packages/console/src/pages/Organizations/OrganizationsTable/EmptyDataPlaceholder/index.tsx
  packages/console/src/pages/Organizations/OrganizationsTable/index.tsx
  packages/console/src/pages/Organizations/consts.ts
  packages/console/src/pages/Organizations/index.module.scss
  packages/console/src/pages/Organizations/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/organizations.ts
  packages/phrases/src/locales/en/translation/admin-console/organizations.ts
  packages/phrases/src/locales/es/translation/admin-console/organizations.ts
  packages/phrases/src/locales/fr/translation/admin-console/organizations.ts
  packages/phrases/src/locales/it/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ja/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ko/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ru/translation/admin-console/organizations.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/organizations.ts
Labels: enhancement, size/xl

#4818 chore(phrases): update dev tenant phrases
  packages/phrases/src/locales/de/translation/admin-console/general.ts
  packages/phrases/src/locales/de/translation/admin-console/tenants.ts
  packages/phrases/src/locales/en/translation/admin-console/general.ts
  packages/phrases/src/locales/en/translation/admin-console/tenants.ts
  packages/phrases/src/locales/es/translation/admin-console/general.ts
  packages/phrases/src/locales/es/translation/admin-console/tenants.ts
  packages/phrases/src/locales/fr/translation/admin-console/general.ts
  packages/phrases/src/locales/fr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/it/translation/admin-console/general.ts
  packages/phrases/src/locales/it/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ja/translation/admin-console/general.ts
  packages/phrases/src/locales/ja/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ko/translation/admin-console/general.ts
  packages/phrases/src/locales/ko/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/general.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ru/translation/admin-console/general.ts
  packages/phrases/src/locales/ru/translation/admin-console/tenants.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tenants.ts
Labels: chore, size/s

#4804 feat(console): add dev tenant nofication on the get-started page
  packages/console/src/contexts/TenantsProvider.tsx
  packages/console/src/pages/GetStarted/DevelopmentTenantNotification/index.module.scss
  packages/console/src/pages/GetStarted/DevelopmentTenantNotification/index.tsx
  packages/console/src/pages/GetStarted/index.tsx
Labels: feature, size/s

#4812 refactor(console): refactor tenant settings page
  packages/console/src/components/TenantEnvTag/index.module.scss
  packages/console/src/components/TenantEnvTag/index.tsx
  packages/console/src/components/Topbar/TenantSelector/index.module.scss
  packages/console/src/consts/external-links.ts
  packages/console/src/pages/TenantSettings/TenantBasicSettings/DeleteModal/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/TenantEnvironment/index.module.scss
  packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/TenantEnvironment/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/TenantRegion/index.module.scss
  packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/TenantRegion/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/index.tsx
Labels: enhancement, size/m

#4828 style(console): center align `CardTitle` content for application placeholder page
  packages/console/src/ds-components/CardTitle/index.module.scss
  packages/console/src/pages/Applications/index.module.scss
Labels: size/xs

#4829 chore: bump dev dependencies
  packages/cli/package.json
  packages/connectors/templates/package.json
  packages/console/package.json
  packages/core/package.json
  packages/demo-app/package.json
  packages/experience/package.json
  packages/phrases-experience/package.json
  packages/phrases/package.json
  packages/schemas/package.json
  packages/toolkit/connector-kit/package.json
  packages/toolkit/core-kit/package.json
  packages/toolkit/language-kit/package.json
  pnpm-lock.yaml
Labels: chore, size/s

#4823 fix(core): allow http1 in core services
  packages/core/src/app/init.ts
Labels: bugfix, size/xs

#4830 feat(console): control console content by tenant env tag
  packages/console/src/components/CreateConnectorForm/index.tsx
  packages/console/src/components/Guide/GuideCard/index.tsx
  packages/console/src/components/ProTag/index.tsx
  packages/console/src/containers/AppContent/TenantNotificationContainer/index.tsx
  packages/console/src/containers/AppContent/index.tsx
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
  packages/console/src/pages/Applications/components/TypeDescription/index.tsx
  packages/console/src/pages/Mfa/PageWrapper/index.tsx
  packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
  packages/console/src/pages/TenantSettings/TenantDomainSettings/index.tsx
  packages/console/src/pages/TenantSettings/index.tsx
Labels: feature, size/m

#4822 refactor(console): fix organization issues
  packages/console/src/components/ActionsButton/index.module.scss
  packages/console/src/components/ActionsButton/index.tsx
  packages/console/src/components/Breakable/index.module.scss
  packages/console/src/components/Breakable/index.tsx
  packages/console/src/components/FormCard/FormCardLayout/index.module.scss
  packages/console/src/components/OrganizationRolesSelect/index.module.scss
  packages/console/src/components/OrganizationRolesSelect/index.tsx
  packages/console/src/components/OrganizationScopesSelect/index.tsx
  packages/console/src/ds-components/ActionMenu/index.tsx
  packages/console/src/ds-components/ModalLayout/index.tsx
  packages/console/src/pages/OrganizationDetails/Settings/index.tsx
  packages/console/src/pages/Organizations/OrganizationsTable/EmptyDataPlaceholder/index.tsx
  packages/console/src/pages/Organizations/OrganizationsTable/index.tsx
  packages/console/src/pages/Organizations/PermissionsCard/index.tsx
  packages/console/src/pages/Organizations/RolesCard/index.tsx
  packages/console/src/pages/Organizations/consts.ts
  packages/console/src/pages/Organizations/index.tsx
  packages/integration-tests/src/tests/console/machine-to-machine-rbac/machime-to-machime-rbac.test.ts
  packages/integration-tests/src/ui-helpers/index.ts
Labels: enhancement, size/m

#4825 feat(core): add isDevelopmentTenant to SIE well-known api
  packages/core/src/libraries/sign-in-experience/index.test.ts
  packages/core/src/libraries/sign-in-experience/index.ts
  packages/core/src/libraries/sign-in-experience/types.ts
  packages/core/src/tenants/Libraries.ts
Labels: feature, size/s

#4799 feat(console): support plan subscription from the tenant landing page
  packages/console/src/cloud/AppRoutes.tsx
  packages/console/src/consts/subscriptions.ts
  packages/console/src/contexts/TenantsProvider.tsx
  packages/console/src/hooks/use-subscribe.ts
  packages/console/src/pages/ConsoleRoutes/index.tsx
  packages/console/src/utils/url.ts
Labels: feature, size/s

#4806 feat(core): add saml sso class
  packages/core/package.json
  packages/core/src/routes/interaction/single-sign-on.ts
  packages/core/src/routes/sso-connector/index.ts
  packages/core/src/routes/sso-connector/utils.test.ts
  packages/core/src/routes/sso-connector/utils.ts
  packages/core/src/sso/OidcConnector/index.ts
  packages/core/src/sso/SamlConnector/index.ts
  packages/core/src/sso/SamlConnector/utils.test.ts
  packages/core/src/sso/SamlConnector/utils.ts
  packages/core/src/sso/SamlSsoConnector/index.test.ts
  packages/core/src/sso/SamlSsoConnector/index.ts
  packages/core/src/sso/index.ts
  packages/core/src/sso/types/index.ts
  packages/core/src/sso/types/saml.ts
  packages/integration-tests/src/__mocks__/sso-connectors-mock.ts
  packages/integration-tests/src/api/api.ts
  packages/integration-tests/src/tests/api/sso-connectors.test.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#4840 test: add delay before clicking switch mfa factors link
  packages/integration-tests/src/ui-helpers/expect-mfa-experience.ts
Labels: testing, size/xs

#4842 style(console): update mfa factor title font style
  packages/console/src/components/MfaFactorTitle/index.module.scss
Labels: size/xs

#4833 fix(console): improve search placeholder text in organization
  packages/console/src/ds-components/Search/index.module.scss
  packages/console/src/ds-components/Search/index.tsx
  packages/console/src/pages/Organizations/OrganizationsTable/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/de/translation/admin-console/organizations.ts
  packages/phrases/src/locales/en/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/en/translation/admin-console/organizations.ts
  packages/phrases/src/locales/es/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/es/translation/admin-console/organizations.ts
  packages/phrases/src/locales/fr/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/organizations.ts
  packages/phrases/src/locales/it/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/it/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ja/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ko/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ru/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/organizations.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/organizations.ts
Labels: bugfix, size/s

#4834 feat(core): support searching organization by id
  packages/core/src/routes/organization/index.ts
Labels: feature, size/xs

#4835 fix(console): icon color on add buttons in organization template
  packages/console/src/pages/Organizations/TemplateTable/index.module.scss
Labels: bugfix, size/xs

#4836 fix(console): should use organization role tag in user details page
  packages/console/src/pages/UserDetails/UserOrganizations/index.tsx
Labels: bugfix, size/xs

#4839 refactor(console): search fields should auto fit its placeholder as minimum width
  packages/console/src/components/PermissionsTable/index.module.scss
  packages/console/src/components/PermissionsTable/index.tsx
  packages/console/src/pages/ApplicationDetails/components/MachineToMachineApplicationRoles/index.module.scss
  packages/console/src/pages/ApplicationDetails/components/MachineToMachineApplicationRoles/index.tsx
  packages/console/src/pages/Roles/index.module.scss
  packages/console/src/pages/Roles/index.tsx
  packages/console/src/pages/UserDetails/UserRoles/index.module.scss
  packages/console/src/pages/UserDetails/UserRoles/index.tsx
  packages/console/src/pages/Users/index.module.scss
  packages/console/src/pages/Users/index.tsx
Labels: enhancement, size/s

#4826 refactor(console): refactor tenant creation form
  packages/console/src/cloud/pages/Main/TenantLandingPage/TenantLandingPageContent/index.tsx
  packages/console/src/components/CreateTenantModal/EnvTagOptionContent/index.module.scss
  packages/console/src/components/CreateTenantModal/EnvTagOptionContent/index.tsx
  packages/console/src/components/CreateTenantModal/index.module.scss
  packages/console/src/components/CreateTenantModal/index.tsx
  packages/console/src/ds-components/RadioGroup/Radio.module.scss
  packages/console/src/ds-components/Tag/index.module.scss
  packages/console/src/ds-components/Tag/index.tsx
Labels: enhancement, size/l

#4838 feat(core): add sso email guard to interaction endpoint
  packages/core/src/libraries/sign-in-experience/index.ts
  packages/core/src/routes/interaction/index.test.ts
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/utils/single-sign-on-guard.test.ts
  packages/core/src/routes/interaction/utils/single-sign-on-guard.ts
  packages/core/src/routes/interaction/utils/single-sign-on.test.ts
  packages/integration-tests/src/constants.ts
  packages/integration-tests/src/helpers/connector.ts
  packages/integration-tests/src/tests/api/interaction/forgot-password/happy-path.test.ts
  packages/integration-tests/src/tests/api/interaction/register-with-identifier/sad-path.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-passcode-identifier/sad-path.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier/happy-path.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier/sad-path.test.ts
  packages/integration-tests/src/tests/api/well-known.test.ts
  packages/integration-tests/src/utils.ts
  packages/phrases/src/locales/de/errors/session.ts
  packages/phrases/src/locales/en/errors/session.ts
  packages/phrases/src/locales/es/errors/session.ts
  packages/phrases/src/locales/fr/errors/session.ts
  packages/phrases/src/locales/it/errors/session.ts
  packages/phrases/src/locales/ja/errors/session.ts
  packages/phrases/src/locales/ko/errors/session.ts
  packages/phrases/src/locales/pl-pl/errors/session.ts
  packages/phrases/src/locales/pt-br/errors/session.ts
  packages/phrases/src/locales/pt-pt/errors/session.ts
  packages/phrases/src/locales/ru/errors/session.ts
  packages/phrases/src/locales/tr-tr/errors/session.ts
  packages/phrases/src/locales/zh-cn/errors/session.ts
  packages/phrases/src/locales/zh-hk/errors/session.ts
  packages/phrases/src/locales/zh-tw/errors/session.ts
Labels: feature, size/l

#4814 feat(core): add single sign on authentication api
  packages/core/src/libraries/sign-in-experience/index.ts
  packages/core/src/queries/user-sso-identities.ts
  packages/core/src/routes/interaction/index.test.ts
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/single-sign-on.ts
  packages/core/src/routes/interaction/utils/single-sign-on-guard.test.ts
  packages/core/src/routes/interaction/utils/single-sign-on-guard.ts
  packages/core/src/routes/interaction/utils/single-sign-on.test.ts
  packages/core/src/routes/interaction/utils/single-sign-on.ts
  packages/core/src/routes/sso-connector/index.ts
  packages/core/src/sso/OidcConnector/index.ts
  packages/core/src/sso/OidcSsoConnector/index.ts
  packages/core/src/sso/SamlSsoConnector/index.ts
  packages/core/src/sso/types/index.ts
  packages/core/src/tenants/Libraries.ts
  packages/core/src/tenants/Queries.ts
  packages/integration-tests/src/constants.ts
  packages/integration-tests/src/helpers/connector.ts
  packages/integration-tests/src/tests/api/interaction/forgot-password/happy-path.test.ts
  packages/integration-tests/src/tests/api/interaction/register-with-identifier/sad-path.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-passcode-identifier/sad-path.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier/happy-path.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier/sad-path.test.ts
  packages/integration-tests/src/tests/api/interaction/single-sign-on/sad-path.test.ts
  packages/integration-tests/src/tests/api/well-known.test.ts
  packages/integration-tests/src/utils.ts
  packages/phrases/src/locales/de/errors/session.ts
  packages/phrases/src/locales/en/errors/session.ts
  packages/phrases/src/locales/es/errors/session.ts
  packages/phrases/src/locales/fr/errors/session.ts
  packages/phrases/src/locales/it/errors/session.ts
  packages/phrases/src/locales/ja/errors/session.ts
  packages/phrases/src/locales/ko/errors/session.ts
  packages/phrases/src/locales/pl-pl/errors/session.ts
  packages/phrases/src/locales/pt-br/errors/session.ts
  packages/phrases/src/locales/pt-pt/errors/session.ts
  packages/phrases/src/locales/ru/errors/session.ts
  packages/phrases/src/locales/tr-tr/errors/session.ts
  packages/phrases/src/locales/zh-cn/errors/session.ts
  packages/phrases/src/locales/zh-hk/errors/session.ts
  packages/phrases/src/locales/zh-tw/errors/session.ts
Labels: feature, size/xl

#4759 refactor(core): overwrite response with parsed result
  packages/core/src/middleware/koa-guard.ts
  packages/core/src/routes/log.test.ts
  packages/core/src/routes/log.ts
  packages/core/src/routes/organization/index.ts
  packages/schemas/src/foundations/jsonb-types/users.ts
  packages/schemas/src/types/organization.ts
Labels: enhancement, size/s

#4843 refactor(schemas): add new sso_connector_id column to the users_sso_identities table
  .github/workflows/main.yml
  packages/core/src/libraries/sign-in-experience/index.ts
  packages/core/src/queries/user-sso-identities.ts
  packages/core/src/routes/interaction/index.test.ts
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/single-sign-on.ts
  packages/core/src/routes/interaction/utils/single-sign-on-guard.test.ts
  packages/core/src/routes/interaction/utils/single-sign-on-guard.ts
  packages/core/src/routes/interaction/utils/single-sign-on.test.ts
  packages/core/src/routes/interaction/utils/single-sign-on.ts
  packages/core/src/routes/sso-connector/index.ts
  packages/core/src/sso/OidcConnector/index.ts
  packages/core/src/sso/OidcSsoConnector/index.ts
  packages/core/src/sso/SamlSsoConnector/index.ts
  packages/core/src/sso/types/index.ts
  packages/core/src/tenants/Libraries.ts
  packages/core/src/tenants/Queries.ts
  packages/integration-tests/src/constants.ts
  packages/integration-tests/src/helpers/connector.ts
  packages/integration-tests/src/tests/api/interaction/forgot-password/happy-path.test.ts
  packages/integration-tests/src/tests/api/interaction/register-with-identifier/sad-path.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-passcode-identifier/sad-path.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier/happy-path.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier/sad-path.test.ts
  packages/integration-tests/src/tests/api/interaction/single-sign-on/sad-path.test.ts
  packages/integration-tests/src/tests/api/well-known.test.ts
  packages/integration-tests/src/utils.ts
  packages/phrases/src/locales/de/errors/session.ts
  packages/phrases/src/locales/en/errors/session.ts
  packages/phrases/src/locales/es/errors/session.ts
  packages/phrases/src/locales/fr/errors/session.ts
  packages/phrases/src/locales/it/errors/session.ts
  packages/phrases/src/locales/ja/errors/session.ts
  packages/phrases/src/locales/ko/errors/session.ts
  packages/phrases/src/locales/pl-pl/errors/session.ts
  packages/phrases/src/locales/pt-br/errors/session.ts
  packages/phrases/src/locales/pt-pt/errors/session.ts
  packages/phrases/src/locales/ru/errors/session.ts
  packages/phrases/src/locales/tr-tr/errors/session.ts
  packages/phrases/src/locales/zh-cn/errors/session.ts
  packages/phrases/src/locales/zh-hk/errors/session.ts
  packages/phrases/src/locales/zh-tw/errors/session.ts
  packages/schemas/alterations/next-1699422979-add-sso-connector-id-col-to-user-sso-identities-table.ts
  packages/schemas/tables/sso_connectors.sql
  packages/schemas/tables/user_sso_identities.sql
Labels: enhancement, size/xl

#4837 refactor(console): add tags for upcoming feature items
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/index.tsx
  packages/console/src/components/PlanQuotaList/QuotaItem/index.tsx
  packages/console/src/components/PlanQuotaList/index.tsx
  packages/console/src/consts/plan-quotas.ts
  packages/console/src/consts/quota-item-phrases.ts
  packages/console/src/pages/TenantSettings/Subscription/PlanQuotaTable/PlanQuotaGroupKeyLabel/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanQuotaTable/PlanQuotaKeyLabel/index.tsx
  packages/console/src/types/subscriptions.ts
  packages/console/src/utils/subscription.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-table.ts
Labels: enhancement, size/xl

#4831 feat: support organizations scope for ID token
  packages/console/src/App.tsx
  packages/core/src/oidc/init.ts
  packages/core/src/oidc/scope.ts
  packages/core/src/queries/organizations.ts
  packages/integration-tests/src/tests/api/oidc/id-token.test.ts
  packages/schemas/src/types/organization.ts
  packages/toolkit/core-kit/src/scope.ts
Labels: feature, size/m

#4824 refactor(console): support using keyboard to remove option
  packages/console/src/ds-components/IconButton/index.module.scss
  packages/console/src/ds-components/Select/MultiSelect.tsx
  packages/console/src/ds-components/Select/index.module.scss
  packages/toolkit/core-kit/scss/_console-themes.scss
Labels: enhancement, size/s

#4848 refactor(console): only display reserved plans in the console
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/index.tsx
  packages/console/src/consts/subscriptions.ts
  packages/console/src/pages/TenantSettings/Subscription/index.tsx
  packages/console/src/utils/subscription.ts
Labels: enhancement, size/s

#4851 refactor(experience): remove demo app notification
  packages/console/src/pages/SignInExperience/utils/constants.ts
  packages/core/src/oidc/init.ts
  packages/experience/src/Layout/LandingPageLayout/index.tsx
  packages/experience/src/containers/AppNotification/index.module.scss
  packages/experience/src/containers/AppNotification/index.tsx
  packages/experience/src/utils/search-parameters.ts
  packages/integration-tests/src/tests/api/well-known.test.ts
  packages/phrases-experience/src/locales/de/demo-app.ts
  packages/phrases-experience/src/locales/de/index.ts
  packages/phrases-experience/src/locales/en/demo-app.ts
  packages/phrases-experience/src/locales/en/index.ts
  packages/phrases-experience/src/locales/es/demo-app.ts
  packages/phrases-experience/src/locales/es/index.ts
  packages/phrases-experience/src/locales/fr/demo-app.ts
  packages/phrases-experience/src/locales/fr/index.ts
  packages/phrases-experience/src/locales/it/demo-app.ts
  packages/phrases-experience/src/locales/it/index.ts
  packages/phrases-experience/src/locales/ja/demo-app.ts
  packages/phrases-experience/src/locales/ja/index.ts
  packages/phrases-experience/src/locales/ko/demo-app.ts
  packages/phrases-experience/src/locales/ko/index.ts
  packages/phrases-experience/src/locales/pl-pl/demo-app.ts
  packages/phrases-experience/src/locales/pl-pl/index.ts
  packages/phrases-experience/src/locales/pt-br/demo-app.ts
  packages/phrases-experience/src/locales/pt-br/index.ts
  packages/phrases-experience/src/locales/pt-pt/demo-app.ts
  packages/phrases-experience/src/locales/pt-pt/index.ts
  packages/phrases-experience/src/locales/ru/demo-app.ts
  packages/phrases-experience/src/locales/ru/index.ts
  packages/phrases-experience/src/locales/tr-tr/demo-app.ts
  packages/phrases-experience/src/locales/tr-tr/index.ts
  packages/phrases-experience/src/locales/zh-cn/demo-app.ts
  packages/phrases-experience/src/locales/zh-cn/index.ts
  packages/phrases-experience/src/locales/zh-hk/demo-app.ts
  packages/phrases-experience/src/locales/zh-hk/index.ts
  packages/phrases-experience/src/locales/zh-tw/demo-app.ts
  packages/phrases-experience/src/locales/zh-tw/index.ts
Labels: enhancement, size/m

#4844 feat: organization_token grant
  packages/core/package.json
  packages/core/src/event-listeners/grant.ts
  packages/core/src/include.d/oidc-provider/index.d.ts
  packages/core/src/include.d/oidc-provider/lib-keep/README.md
  packages/core/src/include.d/oidc-provider/lib-keep/helpers/_/difference.d.ts
  packages/core/src/include.d/oidc-provider/lib-keep/helpers/revoke.d.ts
  packages/core/src/include.d/oidc-provider/lib-keep/helpers/validate_presence.d.ts
  packages/core/src/include.d/oidc-provider/lib-keep/helpers/weak_cache.d.ts
  packages/core/src/oidc/grants/organization-token.ts
  packages/core/src/oidc/init.ts
  packages/core/src/oidc/resource.ts
  packages/core/src/oidc/utils.test.ts
  packages/core/src/oidc/utils.ts
  packages/core/src/queries/organizations.ts
  packages/core/src/routes/interaction/consent.ts
  packages/phrases/src/locales/de/errors/oidc.ts
  packages/phrases/src/locales/en/errors/oidc.ts
  packages/phrases/src/locales/es/errors/oidc.ts
  packages/phrases/src/locales/fr/errors/oidc.ts
  packages/phrases/src/locales/it/errors/oidc.ts
  packages/phrases/src/locales/ja/errors/oidc.ts
  packages/phrases/src/locales/ko/errors/oidc.ts
  packages/phrases/src/locales/pl-pl/errors/oidc.ts
  packages/phrases/src/locales/pt-br/errors/oidc.ts
  packages/phrases/src/locales/pt-pt/errors/oidc.ts
  packages/phrases/src/locales/ru/errors/oidc.ts
  packages/phrases/src/locales/tr-tr/errors/oidc.ts
  packages/phrases/src/locales/zh-cn/errors/oidc.ts
  packages/phrases/src/locales/zh-hk/errors/oidc.ts
  packages/phrases/src/locales/zh-tw/errors/oidc.ts
  packages/schemas/src/types/oidc-config.ts
  packages/schemas/src/types/organization.ts
  packages/toolkit/core-kit/src/index.ts
  packages/toolkit/core-kit/src/openid.ts
Labels: feature, size/xl

#4853 feat(console): add mfa docs link on the mfa config page
  packages/console/src/pages/Mfa/MfaForm/index.tsx
Labels: feature, size/xs

#4846 test(core): add organization token grant unit tests
  packages/core/src/include.d/oidc-provider/lib-keep/helpers/validate_presence.d.ts
  packages/core/src/oidc/grants/organization-token.test.ts
  packages/core/src/oidc/grants/organization-token.ts
  packages/core/src/test-utils/oidc-provider.ts
Labels: testing, size/l

#4847 refactor: update organization scopes
  packages/core/src/oidc/scope.ts
  packages/core/src/routes/organization/index.ts
  packages/core/src/utils/SchemaRouter.ts
  packages/demo-app/src/App.tsx
  packages/integration-tests/src/tests/api/oidc/id-token.test.ts
  packages/schemas/src/types/organization.ts
  packages/toolkit/core-kit/src/openid.ts
Labels: enhancement, size/s

#4849 refactor(test): add integration tests for org token grant
  packages/integration-tests/jest.config.js
  packages/integration-tests/jest.config.ui.js
  packages/integration-tests/package.json
  packages/integration-tests/src/client/index.ts
  packages/integration-tests/src/tests/api/oidc/organization-token-grant.test.ts
  packages/integration-tests/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement, size/l

#4858 refactor(console,phrases): move permissions and roles to step 2 in org guide
  packages/console/src/pages/OrganizationDetails/index.tsx
  packages/console/src/pages/Organizations/Guide/CreateRoles/index.tsx
  packages/console/src/pages/Organizations/Guide/Introduction/Diagram.tsx
  packages/console/src/pages/Organizations/Guide/Introduction/index.module.scss
  packages/console/src/pages/Organizations/Guide/Introduction/index.tsx
  packages/console/src/pages/Organizations/Guide/IntroductionAndPermissions/Introduction/index.tsx
  packages/console/src/pages/Organizations/Guide/IntroductionAndPermissions/index.tsx
  packages/console/src/pages/Organizations/Guide/OrganizationInfo/index.tsx
  packages/console/src/pages/Organizations/Guide/PermissionsAndRoles/index.tsx
  packages/console/src/pages/Organizations/Guide/const.ts
  packages/console/src/pages/Organizations/Guide/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/organizations.ts
  packages/phrases/src/locales/en/translation/admin-console/organizations.ts
  packages/phrases/src/locales/es/translation/admin-console/organizations.ts
  packages/phrases/src/locales/fr/translation/admin-console/organizations.ts
  packages/phrases/src/locales/it/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ja/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ko/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ru/translation/admin-console/organizations.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/organizations.ts
Labels: enhancement, size/xl

#4856 feat(core,schemas): remove the ssoOnly setting of the sso connectors
  packages/core/src/__mocks__/sso.ts
  packages/core/src/libraries/sign-in-experience/index.test.ts
  packages/core/src/libraries/sign-in-experience/index.ts
  packages/core/src/routes/interaction/utils/single-sign-on-guard.test.ts
  packages/core/src/routes/interaction/utils/single-sign-on-guard.ts
  packages/core/src/routes/sso-connector/type.ts
  packages/experience/src/__mocks__/logto.tsx
  packages/integration-tests/src/constants.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier/happy-path.test.ts
  packages/integration-tests/src/tests/api/interaction/single-sign-on/happy-path.test.ts
  packages/integration-tests/src/tests/api/sso-connectors.test.ts
  packages/integration-tests/src/tests/api/well-known.test.ts
  packages/schemas/alterations/next-1699598903-remove-sso-only-column-in-sso-connectors-table.ts
  packages/schemas/src/types/sso-connector.ts
  packages/schemas/tables/sso_connectors.sql
Labels: feature, size/s

#4845 feat(console,phrases): add SSO connector creation modal
  packages/console/src/components/CreateConnectorForm/Skeleton/index.tsx
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/pages/EnterpriseSso/SsoCreationModal/SsoConnectorRadioGroup/SsoConnectorRadio/index.module.scss
  packages/console/src/pages/EnterpriseSso/SsoCreationModal/SsoConnectorRadioGroup/SsoConnectorRadio/index.tsx
  packages/console/src/pages/EnterpriseSso/SsoCreationModal/SsoConnectorRadioGroup/index.module.scss
  packages/console/src/pages/EnterpriseSso/SsoCreationModal/SsoConnectorRadioGroup/index.tsx
  packages/console/src/pages/EnterpriseSso/SsoCreationModal/index.module.scss
  packages/console/src/pages/EnterpriseSso/SsoCreationModal/index.tsx
  packages/console/src/pages/EnterpriseSso/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/en/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/es/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/fr/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/it/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/ja/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/ko/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/ru/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/enterprise-sso.ts
Labels: feature, size/xl

#4852 refactor(console): update pro and beta tags
  .vscode/settings.json
  packages/console/src/components/CreateConnectorForm/index.module.scss
  packages/console/src/components/CreateConnectorForm/index.tsx
  packages/console/src/components/FeatureTag/index.module.scss
  packages/console/src/components/FeatureTag/index.tsx
  packages/console/src/components/FormCard/index.module.scss
  packages/console/src/components/Guide/GuideCard/index.module.scss
  packages/console/src/components/Guide/GuideCard/index.tsx
  packages/console/src/components/InlineUpsell/index.module.scss
  packages/console/src/components/InlineUpsell/index.tsx
  packages/console/src/components/ProTag/index.module.scss
  packages/console/src/components/ProTag/index.tsx
  packages/console/src/containers/AppContent/TenantNotificationContainer/index.tsx
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/contexts/TenantsProvider.tsx
  packages/console/src/ds-components/CardTitle/index.tsx
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/Applications/components/GuideLibrary/index.module.scss
  packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
  packages/console/src/pages/Applications/components/TypeDescription/index.tsx
  packages/console/src/pages/GetStarted/index.tsx
  packages/console/src/pages/Mfa/PageWrapper/index.tsx
  packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
  packages/console/src/pages/TenantSettings/TenantDomainSettings/index.tsx
  packages/console/src/pages/TenantSettings/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/de/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/en/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/en/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/es/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/es/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/fr/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/it/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/it/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/ja/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/ko/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/ru/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/upsell/paywall.ts
  packages/toolkit/core-kit/scss/_console-themes.scss
Labels: enhancement, size/l

#4869 fix(console): allow dev tenant deletion
  packages/console/src/pages/TenantSettings/TenantBasicSettings/index.tsx
Labels: bugfix, size/s

#4854 refactor(core): reuse `refresh_token` grant for org tokens
  packages/core/src/event-listeners/grant.ts
  packages/core/src/include.d/oidc-provider/lib-keep/README.md
  packages/core/src/include.d/oidc-provider/lib-keep/helpers/certificate_thumbprint.d.ts
  packages/core/src/include.d/oidc-provider/lib-keep/helpers/epoch_time.d.ts
  packages/core/src/include.d/oidc-provider/lib-keep/helpers/filter_claims.d.ts
  packages/core/src/include.d/oidc-provider/lib-keep/helpers/resolve_resource.d.ts
  packages/core/src/include.d/oidc-provider/lib-keep/helpers/validate_dpop.d.ts
  packages/core/src/oidc/grants/index.ts
  packages/core/src/oidc/grants/organization-token.ts
  packages/core/src/oidc/grants/refresh-token.test.ts
  packages/core/src/oidc/grants/refresh-token.ts
  packages/core/src/oidc/init.test.ts
  packages/core/src/oidc/init.ts
  packages/core/src/oidc/utils.test.ts
  packages/core/src/oidc/utils.ts
  packages/core/src/tenants/Tenant.ts
  packages/demo-app/src/App.tsx
  packages/integration-tests/src/tests/api/oidc/refresh-token-grant.test.ts
  packages/schemas/src/types/oidc-config.ts
Labels: enhancement, size/xl

#4862 refactor(core): generate shared id parameters definition for swagger
  .changeset/warm-tips-attack.md
  .vscode/settings.json
  packages/core/package.json
  packages/core/src/routes/init.ts
  packages/core/src/routes/swagger/index.test.ts
  packages/core/src/routes/swagger/index.ts
  packages/core/src/routes/swagger/utils/general.ts
  packages/core/src/routes/swagger/utils/parameters.ts
  packages/core/src/utils/SchemaRouter.ts
  packages/core/src/utils/zod.ts
Labels: enhancement, size/xl

#4859 feat(console): add tenant env migration modal
  packages/console/package.json
  packages/console/src/assets/images/tenant-modal-fireworks.svg
  packages/console/src/components/CreateTenantModal/EnvTagOptionContent/index.tsx
  packages/console/src/components/CreateTenantModal/index.tsx
  packages/console/src/components/TenantEnvTag/index.tsx
  packages/console/src/containers/AppContent/TenantNotificationContainer/TenantEnvMigrationModal/DevelopmentTenantFeatures/index.tsx
  packages/console/src/containers/AppContent/TenantNotificationContainer/TenantEnvMigrationModal/DevelopmentTenantMigrationHint/index.module.scss
  packages/console/src/containers/AppContent/TenantNotificationContainer/TenantEnvMigrationModal/DevelopmentTenantMigrationHint/index.tsx
  packages/console/src/containers/AppContent/TenantNotificationContainer/TenantEnvMigrationModal/index.module.scss
  packages/console/src/containers/AppContent/TenantNotificationContainer/TenantEnvMigrationModal/index.tsx
  packages/console/src/containers/AppContent/TenantNotificationContainer/index.tsx
  packages/console/src/contexts/TenantsProvider.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/TenantEnvironment/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/index.tsx
  packages/integration-tests/src/api/tenant.ts
  packages/schemas/src/models/tenants.ts
  packages/schemas/src/types/index.ts
  packages/schemas/src/types/logto-config.ts
  packages/schemas/src/types/tenant.ts
  pnpm-lock.yaml
Labels: feature, size/l

#4855 feat(core,phrases): add sso domains validation
  packages/core/src/routes/sso-connector/index.ts
  packages/core/src/routes/sso-connector/utils.test.ts
  packages/core/src/routes/sso-connector/utils.ts
  packages/core/src/sso/index.ts
  packages/phrases/src/locales/de/errors/index.ts
  packages/phrases/src/locales/de/errors/single-sign-on.ts
  packages/phrases/src/locales/en/errors/index.ts
  packages/phrases/src/locales/en/errors/single-sign-on.ts
  packages/phrases/src/locales/es/errors/index.ts
  packages/phrases/src/locales/es/errors/single-sign-on.ts
  packages/phrases/src/locales/fr/errors/index.ts
  packages/phrases/src/locales/fr/errors/single-sign-on.ts
  packages/phrases/src/locales/it/errors/index.ts
  packages/phrases/src/locales/it/errors/single-sign-on.ts
  packages/phrases/src/locales/ja/errors/index.ts
  packages/phrases/src/locales/ja/errors/single-sign-on.ts
  packages/phrases/src/locales/ko/errors/index.ts
  packages/phrases/src/locales/ko/errors/single-sign-on.ts
  packages/phrases/src/locales/pl-pl/errors/index.ts
  packages/phrases/src/locales/pl-pl/errors/single-sign-on.ts
  packages/phrases/src/locales/pt-br/errors/index.ts
  packages/phrases/src/locales/pt-br/errors/single-sign-on.ts
  packages/phrases/src/locales/pt-pt/errors/index.ts
  packages/phrases/src/locales/pt-pt/errors/single-sign-on.ts
  packages/phrases/src/locales/ru/errors/index.ts
  packages/phrases/src/locales/ru/errors/single-sign-on.ts
  packages/phrases/src/locales/tr-tr/errors/index.ts
  packages/phrases/src/locales/tr-tr/errors/single-sign-on.ts
  packages/phrases/src/locales/zh-cn/errors/index.ts
  packages/phrases/src/locales/zh-cn/errors/single-sign-on.ts
  packages/phrases/src/locales/zh-hk/errors/index.ts
  packages/phrases/src/locales/zh-hk/errors/single-sign-on.ts
  packages/phrases/src/locales/zh-tw/errors/index.ts
  packages/phrases/src/locales/zh-tw/errors/single-sign-on.ts
Labels: feature, size/l

#4868 refactor(console): replace mfa upsell notification with `InlineUpsell` component
  packages/console/src/components/InlineUpsell/index.tsx
  packages/console/src/components/MauExceededModal/index.tsx
  packages/console/src/components/PaymentOverdueModal/index.tsx
  packages/console/src/pages/Mfa/MfaForm/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/SwitchPlanActionBar/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/DeleteModal/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/mfa.ts
  packages/phrases/src/locales/de/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/de/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/en/translation/admin-console/mfa.ts
  packages/phrases/src/locales/en/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/en/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/es/translation/admin-console/mfa.ts
  packages/phrases/src/locales/es/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/es/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/fr/translation/admin-console/mfa.ts
  packages/phrases/src/locales/fr/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/it/translation/admin-console/mfa.ts
  packages/phrases/src/locales/it/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/it/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/ja/translation/admin-console/mfa.ts
  packages/phrases/src/locales/ja/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/ko/translation/admin-console/mfa.ts
  packages/phrases/src/locales/ko/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/mfa.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/mfa.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/mfa.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/ru/translation/admin-console/mfa.ts
  packages/phrases/src/locales/ru/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/mfa.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/mfa.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/mfa.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/mfa.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/upsell/paywall.ts
Labels: enhancement, size/m

#4863 refactor(core): add swagger data for org apis
  Dockerfile
  packages/core/package.json
  packages/core/src/routes/organization/index.openapi.json
  packages/core/src/routes/organization/roles.openapi.json
  packages/core/src/routes/organization/scopes.openapi.json
  packages/core/src/utils/SchemaRouter.ts
  packages/integration-tests/src/tests/api/organization-role.test.ts
  packages/integration-tests/src/tests/api/organization-scope.test.ts
  pnpm-lock.yaml
Labels: enhancement, size/xl

#4867 chore(core): add cloud note for swagger response
  packages/core/src/routes/swagger/index.ts
Labels: chore, size/s

#4870 refactor(console): show paywall tag and beta notice for mfa
  packages/console/src/components/CreateConnectorForm/index.tsx
  packages/console/src/components/FeatureTag/index.tsx
  packages/console/src/components/Guide/GuideCard/index.tsx
  packages/console/src/ds-components/CardTitle/index.tsx
  packages/console/src/ds-components/InlineNotification/index.tsx
  packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
  packages/console/src/pages/Applications/components/TypeDescription/index.tsx
  packages/console/src/pages/Mfa/PageWrapper/index.module.scss
  packages/console/src/pages/Mfa/PageWrapper/index.tsx
  packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
  packages/console/src/pages/TenantSettings/TenantDomainSettings/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/general.ts
  packages/phrases/src/locales/en/translation/admin-console/general.ts
  packages/phrases/src/locales/es/translation/admin-console/general.ts
  packages/phrases/src/locales/fr/translation/admin-console/general.ts
  packages/phrases/src/locales/it/translation/admin-console/general.ts
  packages/phrases/src/locales/ja/translation/admin-console/general.ts
  packages/phrases/src/locales/ko/translation/admin-console/general.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
  packages/phrases/src/locales/ru/translation/admin-console/general.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/general.ts
Labels: enhancement, size/m

#4861 chore: mfa feature release
  .changeset/cuddly-ghosts-mix.md
  packages/console/src/consts/plan-quotas.ts
  packages/console/src/containers/ConsoleContent/Sidebar/hook.tsx
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/pages/SignInExperience/utils/constants.ts
  packages/console/src/pages/UserDetails/UserSettings/index.tsx
  packages/core/src/libraries/sign-in-experience/mfa.ts
  packages/experience/src/App.tsx
  packages/experience/src/hooks/use-pre-sign-in-error-handler.ts
Labels: chore, size/s

#4871 refactor(core): refactor single sign-on session handle logic
  packages/core/src/routes/interaction/single-sign-on.ts
  packages/core/src/routes/interaction/utils/single-sign-on-guard.ts
  packages/core/src/routes/interaction/utils/single-sign-on.test.ts
  packages/core/src/routes/interaction/utils/single-sign-on.ts
  packages/core/src/sso/OidcConnector/index.ts
  packages/core/src/sso/SamlConnector/index.ts
  packages/core/src/sso/SamlConnector/utils.ts
  packages/core/src/sso/SamlSsoConnector/index.ts
  packages/core/src/sso/types/index.ts
  packages/core/src/sso/types/saml.ts
  packages/core/src/sso/types/session.ts
Labels: enhancement, size/m

#4857 feat(experience): add dev tenant notification
  packages/console/src/pages/SignInExperience/utils/constants.ts
  packages/experience/src/Layout/AppLayout/index.tsx
  packages/experience/src/__mocks__/logto.tsx
  packages/experience/src/assets/icons/dev-icon.svg
  packages/experience/src/containers/DevelopmentTenantNotification/index.tsx
  packages/experience/src/scss/_colors.scss
  packages/experience/src/types/index.ts
  packages/experience/src/utils/sign-in-experience.ts
  packages/phrases-experience/src/locales/de/development-tenant.ts
  packages/phrases-experience/src/locales/de/index.ts
  packages/phrases-experience/src/locales/en/development-tenant.ts
  packages/phrases-experience/src/locales/en/index.ts
  packages/phrases-experience/src/locales/es/development-tenant.ts
  packages/phrases-experience/src/locales/es/index.ts
  packages/phrases-experience/src/locales/fr/development-tenant.ts
  packages/phrases-experience/src/locales/fr/index.ts
  packages/phrases-experience/src/locales/it/development-tenant.ts
  packages/phrases-experience/src/locales/it/index.ts
  packages/phrases-experience/src/locales/ja/development-tenant.ts
  packages/phrases-experience/src/locales/ja/index.ts
  packages/phrases-experience/src/locales/ko/development-tenant.ts
  packages/phrases-experience/src/locales/ko/index.ts
  packages/phrases-experience/src/locales/pl-pl/development-tenant.ts
  packages/phrases-experience/src/locales/pl-pl/index.ts
  packages/phrases-experience/src/locales/pt-br/development-tenant.ts
  packages/phrases-experience/src/locales/pt-br/index.ts
  packages/phrases-experience/src/locales/pt-pt/development-tenant.ts
  packages/phrases-experience/src/locales/pt-pt/index.ts
  packages/phrases-experience/src/locales/ru/development-tenant.ts
  packages/phrases-experience/src/locales/ru/index.ts
  packages/phrases-experience/src/locales/tr-tr/development-tenant.ts
  packages/phrases-experience/src/locales/tr-tr/index.ts
  packages/phrases-experience/src/locales/zh-cn/development-tenant.ts
  packages/phrases-experience/src/locales/zh-cn/index.ts
  packages/phrases-experience/src/locales/zh-hk/development-tenant.ts
  packages/phrases-experience/src/locales/zh-hk/index.ts
  packages/phrases-experience/src/locales/zh-tw/development-tenant.ts
  packages/phrases-experience/src/locales/zh-tw/index.ts
Labels: feature, size/l

#4882 chore(core): fix dev script
  packages/core/nodemon.json
  packages/core/package.json
Labels: chore, size/xs

#4883 feat(console): add sso quota item and related phrases
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/index.tsx
  packages/console/src/consts/plan-quotas.ts
  packages/console/src/consts/quota-item-phrases.ts
  packages/console/src/containers/AppContent/TenantNotificationContainer/TenantEnvMigrationModal/DevelopmentTenantFeatures/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanQuotaTable/PlanQuotaKeyLabel/index.tsx
  packages/console/src/types/subscriptions.ts
  packages/console/src/utils/subscription.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-table.ts
Labels: feature, size/l

#4888 fix(core): fix devleopment plan id
  packages/core/src/libraries/sign-in-experience/index.ts
Labels: bugfix, size/xs

#4890 refactor(core): fix org apis
  packages/core/src/routes/organization/roles.ts
  packages/integration-tests/src/helpers/organization.ts
  packages/integration-tests/src/tests/api/organization-role.test.ts
Labels: enhancement, size/m

#4881 fix(console): organization guide router link
  packages/console/src/pages/Organizations/index.tsx
Labels: bugfix, size/xs

#4885 refactor(schemas): use user membership as foreign key for user org roles
  packages/integration-tests/src/tests/api/organization-user.test.ts
  packages/schemas/alterations/next-1700031616-update-org-role-foreign-keys.ts
  packages/schemas/tables/organization_role_user_relations.sql
Labels: enhancement, size/s

#4884 fix(core): generate correct swagger components
  .changeset/neat-spiders-change.md
  packages/core/package.json
  packages/core/src/routes/swagger/index.test.ts
  packages/core/src/routes/swagger/index.ts
  packages/core/src/routes/swagger/utils/parameters.ts
  packages/core/src/utils/zod.ts
  packages/integration-tests/package.json
  packages/integration-tests/src/tests/api/swagger-check.test.ts
  packages/schemas/package.json
  pnpm-lock.yaml
Labels: bugfix, size/s

#4893 refactor(console): update organization ui
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/ds-components/Select/MultiSelect.tsx
  packages/console/src/pages/Organizations/PermissionsCard/index.tsx
  packages/console/src/pages/Organizations/RolesCard/index.tsx
  packages/console/src/pages/Organizations/TemplateTable/index.module.scss
  packages/console/src/pages/Organizations/TemplateTable/index.tsx
  packages/console/src/pages/Organizations/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/de/translation/admin-console/organizations.ts
  packages/phrases/src/locales/en/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/en/translation/admin-console/organizations.ts
  packages/phrases/src/locales/es/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/es/translation/admin-console/organizations.ts
  packages/phrases/src/locales/fr/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/organizations.ts
  packages/phrases/src/locales/it/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/it/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ja/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ko/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ru/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/organizations.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/upsell/index.ts
Labels: enhancement, size/m

#4687 feat(console): show SSO identities on user details page and reorg the page
  packages/console/src/pages/UserDetails/UserSettings/components/UserSocialIdentities/index.module.scss
  packages/console/src/pages/UserDetails/UserSettings/components/UserSocialIdentities/index.tsx
  packages/console/src/pages/UserDetails/UserSettings/components/UserSsoIdentities/index.tsx
  packages/console/src/pages/UserDetails/UserSettings/index.tsx
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/pages/UserDetails/types.ts
  packages/core/src/queries/user-sso-identities.ts
  packages/core/src/routes/admin-user/basics.ts
  packages/integration-tests/src/api/admin-user.ts
  packages/integration-tests/src/tests/api/admin-user.test.ts
  packages/schemas/src/types/user.ts
Labels: enhancement, feature, size/l

#4892 chore(console): update comments about hidden locale phrases
  packages/console/src/pages/SignInExperience/utils/constants.ts
Labels: chore, size/xs

#4891 feat(console): add docs link for env tag feature
  packages/console/src/consts/external-links.ts
  packages/console/src/pages/GetStarted/DevelopmentTenantNotification/index.module.scss
  packages/console/src/pages/GetStarted/DevelopmentTenantNotification/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/TenantEnvironment/index.tsx
Labels: feature, size/s

#4895 fix(console): add a brief header to the organization guide in drawer view
  packages/console/src/components/Drawer/index.module.scss
  packages/console/src/pages/OrganizationDetails/index.tsx
  packages/console/src/pages/Organizations/Guide/Introduction/components/User/index.tsx
  packages/console/src/pages/Organizations/Guide/Introduction/index.module.scss
  packages/console/src/pages/Organizations/Guide/Introduction/index.tsx
Labels: bugfix, size/s

#4897 fix(console): filter out empty org permissions and roles on guide submit
  packages/console/src/pages/Organizations/Guide/PermissionsAndRoles/index.tsx
Labels: bugfix, size/s

#4901 refactor(console): organization permissions and roles are split into two isolated steps
  packages/console/src/pages/Organizations/Guide/Introduction/index.tsx
  packages/console/src/pages/Organizations/Guide/OrganizationInfo/index.tsx
  packages/console/src/pages/Organizations/Guide/OrganizationPermissions/index.tsx
  packages/console/src/pages/Organizations/Guide/OrganizationRoles/index.tsx
  packages/console/src/pages/Organizations/Guide/const.ts
  packages/console/src/pages/Organizations/Guide/index.tsx
Labels: enhancement, size/l

#4899 feat(console): display 'no subscription' on dev tenant selector items
  packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/index.ts
Labels: feature, size/s

#4872 feat(core): add the saml assertion handle flow
  packages/core/src/routes/authn.ts
  packages/core/src/routes/interaction/utils/single-sign-on-guard.ts
  packages/core/src/routes/interaction/utils/single-sign-on.test.ts
  packages/core/src/routes/interaction/utils/single-sign-on.ts
  packages/core/src/sso/OidcConnector/index.ts
  packages/core/src/sso/SamlConnector/index.ts
  packages/core/src/sso/SamlSsoConnector/index.ts
  packages/core/src/utils/saml-assertion-handler.ts
  packages/integration-tests/src/__mocks__/sso-connectors-mock.ts
  packages/integration-tests/src/api/interaction-sso.ts
  packages/integration-tests/src/tests/api/interaction/single-sign-on/sad-path.test.ts
Labels: feature, size/l

#4904 refactor(console): update phrases on the tenant creation modal
  packages/console/src/components/CreateTenantModal/EnvTagOptionContent/index.module.scss
  packages/phrases/src/locales/de/translation/admin-console/tenants.ts
  packages/phrases/src/locales/en/translation/admin-console/tenants.ts
  packages/phrases/src/locales/es/translation/admin-console/tenants.ts
  packages/phrases/src/locales/fr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/it/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ja/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ko/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ru/translation/admin-console/tenants.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tenants.ts
Labels: enhancement, size/m

#4877 refactor(experience): reorg hooks location
  packages/experience/src/containers/SocialLinkAccount/index.tsx
  packages/experience/src/containers/SocialLinkAccount/use-social-link-related-user.ts
  packages/experience/src/containers/SocialSignInList/index.tsx
  packages/experience/src/containers/SocialSignInList/use-social.ts
  packages/experience/src/pages/Callback/index.tsx
  packages/experience/src/pages/Callback/use-social-callback-handler.ts
  packages/experience/src/pages/SocialLanding/index.tsx
  packages/experience/src/pages/SocialLanding/use-social-landing-handler.ts
  packages/experience/src/pages/SocialSignInCallback/SingleSignOn.tsx
  packages/experience/src/pages/SocialSignInCallback/SocialSignIn.tsx
  packages/experience/src/pages/SocialSignInCallback/use-single-sign-on-listener.ts
  packages/experience/src/pages/SocialSignInCallback/use-social-sign-in-listener.ts
Labels: enhancement, size/s

#4886 feat(experience): block email sign-in and register
  packages/experience/src/App.tsx
  packages/experience/src/Providers/SingleSignOnContextProvider/index.tsx
  packages/experience/src/hooks/use-check-single-sign-on.ts
  packages/experience/src/pages/Register/IdentifierRegisterForm/index.test.tsx
  packages/experience/src/pages/Register/IdentifierRegisterForm/use-on-submit.ts
  packages/experience/src/pages/SignIn/IdentifierSignInForm/index.test.tsx
  packages/experience/src/pages/SignIn/IdentifierSignInForm/use-on-submit.ts
  packages/experience/src/pages/SingleSignOnEmail/index.tsx
Labels: feature, size/l

#4889 feat(core): add social returned email sso guard
  packages/core/src/routes/interaction/utils/single-sign-on-guard.ts
  packages/core/src/routes/interaction/verifications/identifier-payload-verification.test.ts
  packages/core/src/routes/interaction/verifications/identifier-payload-verification.ts
Labels: feature, size/s

#4905 refactor(console): update phrases on the tenant settings page
  packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/TenantEnvironment/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/tenants.ts
  packages/phrases/src/locales/en/translation/admin-console/tenants.ts
  packages/phrases/src/locales/es/translation/admin-console/tenants.ts
  packages/phrases/src/locales/fr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/it/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ja/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ko/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ru/translation/admin-console/tenants.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tenants.ts
Labels: enhancement, size/m

#4907 refactor(console): update dev tenant migration phrases
  packages/console/src/containers/AppContent/TenantNotificationContainer/TenantEnvMigrationModal/DevelopmentTenantFeatures/index.tsx
  packages/console/src/containers/AppContent/TenantNotificationContainer/TenantEnvMigrationModal/DevelopmentTenantMigrationHint/index.module.scss
  packages/console/src/containers/AppContent/TenantNotificationContainer/TenantEnvMigrationModal/DevelopmentTenantMigrationHint/index.tsx
  packages/console/src/containers/AppContent/TenantNotificationContainer/TenantEnvMigrationModal/index.module.scss
  packages/console/src/containers/AppContent/TenantNotificationContainer/TenantEnvMigrationModal/index.tsx
  packages/console/src/pages/GetStarted/DevelopmentTenantNotification/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/tenants.ts
  packages/phrases/src/locales/en/translation/admin-console/tenants.ts
  packages/phrases/src/locales/es/translation/admin-console/tenants.ts
  packages/phrases/src/locales/fr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/it/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ja/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ko/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ru/translation/admin-console/tenants.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tenants.ts
Labels: enhancement, size/xl

#4908 feat(console): add pricing link for dev tenant notification
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/index.tsx
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/index.tsx
  packages/console/src/consts/external-links.ts
  packages/console/src/ds-components/TextLink/index.tsx
  packages/console/src/pages/GetStarted/DevelopmentTenantNotification/index.module.scss
  packages/console/src/pages/GetStarted/DevelopmentTenantNotification/index.tsx
Labels: feature, size/s

#4866 feat(console,phrases,core): add SSO connector creation guide
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/pages/EnterpriseSso/Guide/BasicInfo/index.module.scss
  packages/console/src/pages/EnterpriseSso/Guide/BasicInfo/index.tsx
  packages/console/src/pages/EnterpriseSso/Guide/OidcMetadataForm/index.tsx
  packages/console/src/pages/EnterpriseSso/Guide/SamlAttributeMapping/index.module.scss
  packages/console/src/pages/EnterpriseSso/Guide/SamlAttributeMapping/index.tsx
  packages/console/src/pages/EnterpriseSso/Guide/SamlMetadataForm/SwitchFormatButton/index.module.scss
  packages/console/src/pages/EnterpriseSso/Guide/SamlMetadataForm/SwitchFormatButton/index.tsx
  packages/console/src/pages/EnterpriseSso/Guide/SamlMetadataForm/index.module.scss
  packages/console/src/pages/EnterpriseSso/Guide/SamlMetadataForm/index.tsx
  packages/console/src/pages/EnterpriseSso/Guide/index.module.scss
  packages/console/src/pages/EnterpriseSso/Guide/index.tsx
  packages/console/src/pages/EnterpriseSso/Guide/types.ts
  packages/console/src/pages/EnterpriseSso/SsoCreationModal/index.tsx
  packages/console/src/pages/EnterpriseSso/index.tsx
  packages/console/src/pages/EnterpriseSso/types.ts
  packages/core/src/__mocks__/sso.ts
  packages/core/src/libraries/sso-connector.ts
  packages/core/src/routes/interaction/utils/single-sign-on.ts
  packages/core/src/routes/sso-connector/index.ts
  packages/core/src/routes/sso-connector/utils.test.ts
  packages/core/src/routes/sso-connector/utils.ts
  packages/core/src/sso/OidcSsoConnector/index.test.ts
  packages/core/src/sso/OidcSsoConnector/index.ts
  packages/core/src/sso/SamlConnector/index.ts
  packages/core/src/sso/SamlSsoConnector/index.test.ts
  packages/core/src/sso/SamlSsoConnector/index.ts
  packages/core/src/sso/index.ts
  packages/core/src/sso/types/index.ts
  packages/core/src/sso/utils.test.ts
  packages/core/src/sso/utils.ts
  packages/integration-tests/src/api/sso-connector.ts
  packages/integration-tests/src/constants.ts
  packages/integration-tests/src/tests/api/interaction/single-sign-on/happy-path.test.ts
  packages/integration-tests/src/tests/api/interaction/single-sign-on/sad-path.test.ts
  packages/integration-tests/src/tests/api/sso-connectors.test.ts
  packages/phrases/src/locales/de/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/en/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/es/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/fr/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/it/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/ja/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/ko/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/ru/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/enterprise-sso.ts
  packages/schemas/src/types/sso-connector.ts
Labels: feature, size/xl

#4898 feat(experience): add single sign on switch to the password sign-in form
  packages/experience/src/hooks/use-check-single-sign-on.ts
  packages/experience/src/hooks/use-password-sign-in.ts
  packages/experience/src/pages/SignIn/PasswordSignInForm/index.module.scss
  packages/experience/src/pages/SignIn/PasswordSignInForm/index.test.tsx
  packages/experience/src/pages/SignIn/PasswordSignInForm/index.tsx
  packages/experience/src/pages/SignIn/PasswordSignInForm/use-single-sign-on-watch.ts
  packages/phrases-experience/src/locales/de/description.ts
  packages/phrases-experience/src/locales/en/description.ts
  packages/phrases-experience/src/locales/es/description.ts
  packages/phrases-experience/src/locales/fr/description.ts
  packages/phrases-experience/src/locales/it/description.ts
  packages/phrases-experience/src/locales/ja/description.ts
  packages/phrases-experience/src/locales/ko/description.ts
  packages/phrases-experience/src/locales/pl-pl/description.ts
  packages/phrases-experience/src/locales/pt-br/description.ts
  packages/phrases-experience/src/locales/pt-pt/description.ts
  packages/phrases-experience/src/locales/ru/description.ts
  packages/phrases-experience/src/locales/tr-tr/description.ts
  packages/phrases-experience/src/locales/zh-cn/description.ts
  packages/phrases-experience/src/locales/zh-hk/description.ts
  packages/phrases-experience/src/locales/zh-tw/description.ts
Labels: feature, size/l

#4906 refactor(phrases,console): update wording in organization pages
  packages/console/src/pages/Organizations/Guide/Introduction/components/Vector/John.tsx
  packages/console/src/pages/Organizations/Guide/Introduction/components/Vector/Sarah.tsx
  packages/console/src/pages/Organizations/Guide/Introduction/components/Vector/index.module.scss
  packages/console/src/pages/Organizations/Guide/OrganizationInfo/index.tsx
  packages/console/src/pages/Organizations/Guide/OrganizationRoles/index.tsx
  packages/console/src/pages/Organizations/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/de/translation/admin-console/organizations.ts
  packages/phrases/src/locales/en/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/en/translation/admin-console/organizations.ts
  packages/phrases/src/locales/es/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/es/translation/admin-console/organizations.ts
  packages/phrases/src/locales/fr/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/organizations.ts
  packages/phrases/src/locales/it/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/it/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ja/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ko/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ru/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/organizations.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/organizations.ts
Labels: enhancement, size/l

#4915 refactor(console): display paywall tag on mfa page for dev tenant
  packages/console/src/pages/Mfa/PageWrapper/index.tsx
Labels: enhancement, size/xs

#4916 fix(console): remove feature tag for custom domain feature
  packages/console/src/pages/TenantSettings/TenantDomainSettings/AddDomainForm/index.tsx
  packages/console/src/pages/TenantSettings/TenantDomainSettings/index.tsx
Labels: bugfix, size/s

#4914 chore: update tenant type doc link
  packages/console/src/consts/external-links.ts
Labels: chore, size/xs

#4917 chore(console): update dev tenant phrases
  packages/phrases/src/locales/de/translation/admin-console/tenants.ts
  packages/phrases/src/locales/en/translation/admin-console/tenants.ts
  packages/phrases/src/locales/es/translation/admin-console/tenants.ts
  packages/phrases/src/locales/fr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/it/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ja/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ko/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ru/translation/admin-console/tenants.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tenants.ts
Labels: chore, size/s

#4919 refactor(console,schemas): add reserved plan id enum
  packages/console/src/components/CreateConnectorForm/Footer/index.tsx
  packages/console/src/components/CreateConnectorForm/index.tsx
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/index.tsx
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/index.tsx
  packages/console/src/components/FeatureTag/index.tsx
  packages/console/src/components/Guide/GuideCard/index.tsx
  packages/console/src/components/PlanDescription/index.tsx
  packages/console/src/consts/plan-quotas.ts
  packages/console/src/consts/subscriptions.ts
  packages/console/src/contexts/TenantsProvider.tsx
  packages/console/src/ds-components/CardTitle/index.tsx
  packages/console/src/hooks/use-subscribe.ts
  packages/console/src/hooks/use-subscription-plans.ts
  packages/console/src/pages/Applications/components/CreateForm/Footer/index.tsx
  packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
  packages/console/src/pages/Applications/components/TypeDescription/index.tsx
  packages/console/src/pages/Mfa/PageWrapper/index.tsx
  packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/MauLimitExceededNotification/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/SwitchPlanActionBar/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/index.tsx
  packages/console/src/pages/TenantSettings/components/NotEligibleSwitchPlanModalContent/index.tsx
  packages/console/src/utils/sort.ts
  packages/console/src/utils/subscription.ts
  packages/schemas/src/consts/index.ts
  packages/schemas/src/consts/subscriptions.ts
Labels: enhancement, size/m

#4922 fix(console): display mfa feature item in downgrade plan modal
  packages/console/src/pages/TenantSettings/Subscription/DowngradeConfirmModalContent/index.tsx
  packages/console/src/pages/TenantSettings/components/NotEligibleSwitchPlanModalContent/index.tsx
Labels: bugfix, size/s

#4923 fix(console): hide coming soon features from the downgrade plan modal
  packages/console/src/components/PlanQuotaList/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/DowngradeConfirmModalContent/index.tsx
  packages/console/src/pages/TenantSettings/components/NotEligibleSwitchPlanModalContent/index.tsx
  packages/console/src/types/subscriptions.ts
Labels: bugfix, size/s

#4913 fix(experience): fix the ut randomly fail issue
  packages/experience/src/pages/SignIn/PasswordSignInForm/index.test.tsx
Labels: bugfix, size/s

#4903 feat(cli): support sync array keys
  .changeset/empty-buttons-ring.md
  packages/cli/src/commands/translate/sync-keys/utils.ts
  packages/cli/src/commands/translate/sync.ts
Labels: feature, size/m

#4925 feat(core,experience): implement google workspace connector
  packages/core/src/routes/interaction/utils/single-sign-on.test.ts
  packages/core/src/routes/interaction/utils/single-sign-on.ts
  packages/core/src/routes/sso-connector/utils.test.ts
  packages/core/src/sso/AzureAdSsoConnector/index.ts
  packages/core/src/sso/GoogleWorkspaceSsoConnector/index.ts
  packages/core/src/sso/OidcConnector/index.ts
  packages/core/src/sso/OidcSsoConnector/index.ts
  packages/core/src/sso/SamlSsoConnector/index.ts
  packages/core/src/sso/index.ts
  packages/core/src/sso/types/oidc.test.ts
  packages/core/src/sso/types/oidc.ts
  packages/experience/src/apis/single-sign-on.ts
  packages/integration-tests/src/__mocks__/sso-connectors-mock.ts
  packages/schemas/src/types/sso-connector.ts
Labels: feature, size/m

#4909 refactor(schemas): add js-doc to tenant tag enum
  packages/schemas/src/types/tenant.ts
Labels: enhancement, size/xs

#4924 fix(console): default button icon should use secondary color
  packages/console/src/ds-components/Button/index.module.scss
  packages/console/src/pages/Organizations/TemplateTable/index.module.scss
  packages/console/src/pages/Organizations/TemplateTable/index.tsx
Labels: bugfix, size/s

#4921 chore(console,experience): remove feature flag for dev tenant
  packages/console/src/cloud/AppRoutes.tsx
  packages/console/src/cloud/pages/Main/TenantLandingPage/TenantLandingPageContent/index.tsx
  packages/console/src/components/CreateTenantModal/index.tsx
  packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx
  packages/console/src/containers/AppContent/TenantNotificationContainer/index.tsx
  packages/console/src/contexts/TenantsProvider.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/index.tsx
  packages/experience/src/utils/sign-in-experience.ts
  packages/phrases/src/locales/de/translation/admin-console/tenants.ts
  packages/phrases/src/locales/en/translation/admin-console/tenants.ts
  packages/phrases/src/locales/es/translation/admin-console/tenants.ts
  packages/phrases/src/locales/fr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/it/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ja/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ko/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ru/translation/admin-console/tenants.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tenants.ts
Labels: chore, size/l

#4931 refactor(console): remove org feature from coming soon list
  packages/console/src/consts/plan-quotas.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-table.ts
Labels: enhancement, size/s

#4933 feat(experience): add struct guard to session storage hook
  packages/experience/package.json
  packages/experience/src/hooks/use-session-storages.test.ts
  packages/experience/src/hooks/use-session-storages.ts
  packages/experience/src/types/guard.ts
  pnpm-lock.yaml
Labels: feature, size/m

#4929 refactor(console): only display exceeded quota items on not eligible switch plan modal
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/MauLimitExceededNotification/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/SwitchPlanActionBar/index.tsx
  packages/console/src/pages/TenantSettings/components/NotEligibleSwitchPlanModalContent/index.tsx
  packages/console/src/utils/subscription.ts
Labels: enhancement, size/s

#4920 refactor(console): improve table loading experience
  packages/console/src/ds-components/Table/Skeleton/index.module.scss
  packages/console/src/ds-components/Table/Skeleton/index.tsx
  packages/console/src/ds-components/Table/index.tsx
  packages/console/src/pages/Organizations/OrganizationsTable/index.tsx
  packages/console/src/pages/Organizations/TemplateTable/index.tsx
  packages/console/src/pages/Organizations/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/SigningKeys/index.tsx
  packages/console/src/pages/UserDetails/UserSettings/UserMfaVerifications/index.tsx
  packages/console/src/pages/UserDetails/UserSettings/components/UserSocialIdentities/index.tsx
  packages/console/src/pages/UserDetails/UserSettings/components/UserSsoIdentities/index.tsx
Labels: enhancement, size/m

#4928 feat(experience): add lock icon to the single sign-on button
  packages/experience/src/assets/icons/lock.svg
  packages/experience/src/components/Button/index.module.scss
  packages/experience/src/components/Button/index.tsx
  packages/experience/src/pages/SignIn/PasswordSignInForm/index.tsx
  packages/experience/src/pages/SingleSignOnEmail/index.tsx
Labels: feature, size/s

#4930 feat(experience): add native listener to SSO callback page
  packages/experience/src/hooks/use-native-message-listener.ts
  packages/experience/src/pages/SocialSignInCallback/SingleSignOn.tsx
Labels: feature, size/s

#4927 refactor(core,schemas): remove get provider properties method
  packages/console/src/pages/EnterpriseSso/Guide/BasicInfo/index.tsx
  packages/console/src/pages/EnterpriseSso/Guide/index.tsx
  packages/core/src/routes/sso-connector/utils.ts
  packages/core/src/sso/GoogleWorkspaceSsoConnector/index.ts
  packages/core/src/sso/OidcSsoConnector/index.ts
  packages/core/src/sso/SamlConnector/index.ts
  packages/core/src/sso/SamlSsoConnector/index.ts
  packages/core/src/sso/types/index.ts
  packages/core/src/sso/types/saml.ts
  packages/schemas/src/types/sso-connector.ts
Labels: enhancement, size/s

#4935 feat(core): add signInMode guard to sso register api
  packages/core/src/routes/interaction/single-sign-on.ts
Labels: feature, size/s

#4940 fix(core): fix saml sso connector bug
  packages/core/src/sso/SamlConnector/index.ts
  packages/core/src/sso/SamlSsoConnector/index.ts
Labels: bugfix, size/xs

#4934 refactor(core,experience): extract sso register api
  packages/core/src/routes/interaction/single-sign-on.ts
  packages/core/src/routes/interaction/utils/single-sign-on-guard.ts
  packages/core/src/routes/interaction/utils/single-sign-on-session.ts
  packages/core/src/routes/interaction/utils/single-sign-on.test.ts
  packages/core/src/routes/interaction/utils/single-sign-on.ts
  packages/core/src/sso/types/session.ts
  packages/experience/src/apis/single-sign-on.ts
  packages/experience/src/pages/SocialSignInCallback/use-single-sign-on-listener.ts
Labels: enhancement, size/l

#4912 feat(console): add SSO connector details page (settings tab)
  packages/console/src/consts/page-tabs.ts
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/ds-components/Uploader/FileUploader/index.module.scss
  packages/console/src/ds-components/Uploader/FileUploader/index.tsx
  packages/console/src/ds-components/Uploader/ImageUploader/index.module.scss
  packages/console/src/ds-components/Uploader/ImageUploader/index.tsx
  packages/console/src/pages/EnterpriseSso/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/Settings/LogosUploader/index.module.scss
  packages/console/src/pages/EnterpriseSsoDetails/Settings/LogosUploader/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/Settings/MultiInput/index.module.scss
  packages/console/src/pages/EnterpriseSsoDetails/Settings/MultiInput/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/Settings/index.module.scss
  packages/console/src/pages/EnterpriseSsoDetails/Settings/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/index.module.scss
  packages/console/src/pages/EnterpriseSsoDetails/index.tsx
  packages/core/src/routes/sso-connector/utils.ts
  packages/core/src/sso/SamlSsoConnector/index.ts
  packages/core/src/sso/index.ts
  packages/phrases/src/locales/de/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/de/translation/admin-console/index.ts
  packages/phrases/src/locales/en/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/en/translation/admin-console/index.ts
  packages/phrases/src/locales/es/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/es/translation/admin-console/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/index.ts
  packages/phrases/src/locales/it/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/it/translation/admin-console/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/index.ts
  packages/schemas/src/types/sso-connector.ts
  packages/schemas/src/utils/domain.test.ts
  packages/schemas/src/utils/domain.ts
  packages/schemas/src/utils/index.ts
Labels: feature, size/xl

#4941 fix(console): remove row hover effects from organization inline tables
  packages/console/src/pages/OrganizationDetails/Members/index.tsx
  packages/console/src/pages/Organizations/TemplateTable/index.tsx
Labels: bugfix, size/xs

#4939 feat(console,phrases): add organizations paywall
  packages/connectors/connector-logto-email/package.json
  packages/console/package.json
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/index.tsx
  packages/console/src/consts/plan-quotas.ts
  packages/console/src/consts/quota-item-phrases.ts
  packages/console/src/pages/Organizations/OrganizationsTable/EmptyDataPlaceholder/index.tsx
  packages/console/src/pages/Organizations/OrganizationsTable/index.tsx
  packages/console/src/pages/Organizations/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanQuotaTable/PlanQuotaGroupKeyLabel/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanQuotaTable/PlanQuotaKeyLabel/index.tsx
  packages/console/src/types/subscriptions.ts
  packages/console/src/utils/subscription.ts
  packages/core/package.json
  packages/core/src/libraries/quota.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/en/errors/organization.ts
  packages/phrases/src/locales/en/translation/admin-console/organizations.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-table.ts
  pnpm-lock.yaml
Labels: feature, size/l

#4926 feat(console): add SSO connector "connection" tab
  packages/console/src/components/FormCard/index.tsx
  packages/console/src/pages/EnterpriseSso/Guide/BasicInfo/index.tsx
  packages/console/src/pages/EnterpriseSso/Guide/OidcMetadataForm/ParsedConfigPreview/index.module.scss
  packages/console/src/pages/EnterpriseSso/Guide/OidcMetadataForm/ParsedConfigPreview/index.tsx
  packages/console/src/pages/EnterpriseSso/Guide/OidcMetadataForm/index.tsx
  packages/console/src/pages/EnterpriseSso/Guide/SamlAttributeMapping/index.tsx
  packages/console/src/pages/EnterpriseSso/Guide/SamlMetadataForm/ParsedConfigPreview/index.module.scss
  packages/console/src/pages/EnterpriseSso/Guide/SamlMetadataForm/ParsedConfigPreview/index.tsx
  packages/console/src/pages/EnterpriseSso/Guide/SamlMetadataForm/index.module.scss
  packages/console/src/pages/EnterpriseSso/Guide/SamlMetadataForm/index.tsx
  packages/console/src/pages/EnterpriseSso/Guide/index.module.scss
  packages/console/src/pages/EnterpriseSso/Guide/index.tsx
  packages/console/src/pages/EnterpriseSso/Guide/types.ts
  packages/console/src/pages/EnterpriseSso/index.tsx
  packages/console/src/pages/EnterpriseSso/types.ts
  packages/console/src/pages/EnterpriseSsoDetails/Connection/index.module.scss
  packages/console/src/pages/EnterpriseSsoDetails/Connection/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/Settings/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/en/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/es/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/it/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/enterprise-sso-details.ts
Labels: feature, size/xl

#4948 chore: update management api docs url
  packages/core/src/routes/swagger/index.ts
Labels: chore, size/xs

#4949 chore: remove dev feature flag for orgs
  packages/console/src/containers/ConsoleContent/Sidebar/hook.tsx
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/core/src/oidc/init.ts
  packages/core/src/routes/organization/index.ts
Labels: chore, size/s

#4950 chore(console): remove m2m app guide content feature switch
  packages/console/src/assets/docs/guides/m2m-general/README.mdx
Labels: chore, size/s

#4946 fix(console): partially check config on guide page
  packages/console/src/pages/EnterpriseSso/Guide/index.tsx
Labels: bugfix, size/xs

#4947 fix(console): fix SAML SSO connector status
  packages/console/src/pages/EnterpriseSso/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/index.tsx
Labels: bugfix, size/s

#4944 fix(console): update SSO console display
  packages/console/src/pages/EnterpriseSso/Guide/BasicInfo/index.tsx
  packages/console/src/pages/EnterpriseSso/Guide/SamlMetadataForm/index.tsx
Labels: bugfix, size/s

#4943 chore(core): update generation of SAML service provider entity id
  packages/core/src/sso/SamlConnector/index.ts
  packages/core/src/sso/SamlConnector/utils.ts
Labels: chore, size/s

#4945 fix(test): fix experience ui test randomly fail issue
  packages/integration-tests/src/ui-helpers/expect-experience.ts
  packages/integration-tests/src/ui-helpers/expect-page.ts
  packages/integration-tests/src/utils.ts
Labels: bugfix, size/s

#4936 feat(console): add xml text file reader
  packages/console/src/assets/icons/file-icon.svg
  packages/console/src/pages/EnterpriseSso/Guide/SamlMetadataForm/index.tsx
  packages/console/src/pages/EnterpriseSso/Guide/SamlMetadataForm/utils.ts
  packages/console/src/pages/EnterpriseSso/Guide/XmlFileReader/index.module.scss
  packages/console/src/pages/EnterpriseSso/Guide/XmlFileReader/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/de/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/en/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/en/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/es/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/es/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/fr/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/it/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/it/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/ja/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/ko/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/ru/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/enterprise-sso.ts
Labels: feature, size/l

#4952 feat(console,core,phrases): add more organization paywalls
  packages/console/src/pages/Organizations/CreateOrganizationModal/index.tsx
  packages/console/src/pages/Organizations/index.tsx
  packages/core/src/middleware/koa-quota-guard.ts
  packages/core/src/routes/organization/index.ts
  packages/core/src/routes/organization/roles.ts
  packages/core/src/routes/organization/scopes.ts
  packages/phrases/src/locales/de/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/en/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/es/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/fr/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/it/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/ja/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/ko/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/ru/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/upsell/paywall.ts
Labels: feature, size/m

#4942 refactor(core): simplify the saml getIssuer method
  packages/core/src/sso/SamlConnector/index.ts
  packages/core/src/sso/SamlSsoConnector/index.ts
Labels: enhancement, size/s

#4951 feat(core): add OKTA sso connector
  packages/core/src/sso/OidcConnector/utils.ts
  packages/core/src/sso/OktaSsoConnector/index.ts
  packages/core/src/sso/index.ts
  packages/schemas/src/types/sso-connector.ts
Labels: feature, size/m

#4955 feat(console): reuse existing oidc/saml form for OOTB SSO connector config
  packages/console/src/pages/EnterpriseSso/Guide/BasicInfo/index.tsx
  packages/console/src/pages/EnterpriseSso/Guide/OidcMetadataForm/ParsedConfigPreview/index.tsx
  packages/console/src/pages/EnterpriseSso/Guide/OidcMetadataForm/index.module.scss
  packages/console/src/pages/EnterpriseSso/Guide/OidcMetadataForm/index.tsx
  packages/console/src/pages/EnterpriseSso/Guide/index.tsx
  packages/console/src/pages/EnterpriseSso/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/Connection/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/index.tsx
Labels: feature, size/s

#4957 fix(console): update documentation links
  packages/console/src/mdx-components/Steps/FurtherReadings.tsx
  packages/console/src/pages/ApiResourceDetails/ApiResourceSettings/index.tsx
  packages/console/src/pages/ApiResourceDetails/index.tsx
Labels: bugfix, size/s

#4960 refactor(core): refactor SAML SSO idpConfig type
  packages/core/src/sso/SamlConnector/index.ts
  packages/core/src/sso/SamlConnector/utils.ts
  packages/core/src/sso/SamlSsoConnector/index.test.ts
  packages/core/src/sso/SamlSsoConnector/index.ts
  packages/core/src/sso/types/saml.ts
Labels: enhancement, size/m

#4958 refactor(core): remove SSO connector config partial update logic
  packages/core/src/routes/sso-connector/index.ts
  packages/core/src/routes/sso-connector/utils.ts
  packages/core/src/sso/SamlConnector/index.ts
  packages/core/src/sso/SamlConnector/utils.ts
  packages/core/src/sso/SamlSsoConnector/index.test.ts
  packages/core/src/sso/SamlSsoConnector/index.ts
  packages/core/src/sso/types/saml.ts
  packages/integration-tests/src/api/sso-connector.ts
  packages/integration-tests/src/tests/api/interaction/single-sign-on/sad-path.test.ts
  packages/integration-tests/src/tests/api/sso-connectors.test.ts
  packages/integration-tests/src/tests/api/well-known.test.ts
  packages/schemas/src/types/sso-connector.ts
Labels: enhancement, size/l

#4961 fix(core): update google SSO connector prompt always select-account
  packages/core/src/sso/GoogleWorkspaceSsoConnector/index.ts
  packages/core/src/sso/OidcConnector/index.ts
Labels: bugfix, size/s

#4963 chore(console,core): add/replace SSO connector logo resources
  packages/console/src/components/DetailsPage/DetailsPageHeader/index.module.scss
  packages/console/src/pages/EnterpriseSso/SsoConnectorLogo/index.module.scss
  packages/console/src/pages/EnterpriseSso/SsoConnectorLogo/index.tsx
  packages/console/src/pages/EnterpriseSso/SsoCreationModal/SsoConnectorRadioGroup/SsoConnectorRadio/index.tsx
  packages/console/src/pages/EnterpriseSso/index.module.scss
  packages/console/src/pages/EnterpriseSso/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/index.module.scss
  packages/console/src/pages/EnterpriseSsoDetails/index.tsx
  packages/console/src/pages/UserDetails/UserSettings/components/UserSsoIdentities/index.tsx
  packages/core/src/libraries/sign-in-experience/index.test.ts
  packages/core/src/libraries/sign-in-experience/index.ts
  packages/core/src/routes/sso-connector/utils.test.ts
  packages/core/src/routes/sso-connector/utils.ts
  packages/core/src/sso/AzureAdSsoConnector/index.ts
  packages/core/src/sso/GoogleWorkspaceSsoConnector/index.ts
  packages/core/src/sso/OidcSsoConnector/index.ts
  packages/core/src/sso/OktaSsoConnector/consts.ts
  packages/core/src/sso/OktaSsoConnector/index.ts
  packages/core/src/sso/SamlSsoConnector/index.ts
  packages/core/src/sso/index.ts
  packages/integration-tests/src/api/sso-connector.ts
  packages/integration-tests/src/tests/api/sso-connectors.test.ts
  packages/schemas/src/types/sso-connector.ts
Labels: chore, size/m

#4966 chore(console,phrases): update email domain input field interaction
  packages/console/src/pages/EnterpriseSsoDetails/Settings/MultiInput/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/Settings/index.tsx
  packages/phrases/src/locales/de/errors/single-sign-on.ts
  packages/phrases/src/locales/en/errors/single-sign-on.ts
  packages/phrases/src/locales/es/errors/single-sign-on.ts
  packages/phrases/src/locales/fr/errors/single-sign-on.ts
  packages/phrases/src/locales/it/errors/single-sign-on.ts
  packages/phrases/src/locales/ja/errors/single-sign-on.ts
  packages/phrases/src/locales/ko/errors/single-sign-on.ts
  packages/phrases/src/locales/pl-pl/errors/single-sign-on.ts
  packages/phrases/src/locales/pt-br/errors/single-sign-on.ts
  packages/phrases/src/locales/pt-pt/errors/single-sign-on.ts
  packages/phrases/src/locales/ru/errors/single-sign-on.ts
  packages/phrases/src/locales/tr-tr/errors/single-sign-on.ts
  packages/phrases/src/locales/zh-cn/errors/single-sign-on.ts
  packages/phrases/src/locales/zh-hk/errors/single-sign-on.ts
  packages/phrases/src/locales/zh-tw/errors/single-sign-on.ts
Labels: chore, size/s

#4968 fix(core): fix OIDC SSO connector config guard
  packages/core/src/sso/OidcConnector/index.ts
  packages/core/src/sso/types/oidc.ts
Labels: bugfix, size/s

#4971 chore(core): add dev feature guard to SSO endpoints
  packages/core/src/routes/interaction/single-sign-on.ts
  packages/core/src/routes/sso-connector/index.ts
Labels: chore, size/s

#4970 feat(experience): directly invoke sso flow if there are only one SSO connector
  packages/experience/src/__mocks__/logto.tsx
  packages/experience/src/hooks/use-check-single-sign-on.ts
  packages/experience/src/hooks/use-single-sign-on.ts
  packages/experience/src/pages/SignIn/PasswordSignInForm/index.test.tsx
  packages/experience/src/pages/SignIn/PasswordSignInForm/index.tsx
  packages/experience/src/pages/SignIn/PasswordSignInForm/use-single-sign-on-watch.ts
  packages/experience/src/pages/SingleSignOnConnectors/index.tsx
Labels: feature, size/s

#4962 feat(core): guard sso config
  packages/core/src/routes/interaction/utils/single-sign-on.test.ts
  packages/core/src/routes/sso-connector/index.ts
  packages/core/src/routes/sso-connector/utils.test.ts
  packages/core/src/routes/sso-connector/utils.ts
  packages/core/src/sso/GoogleWorkspaceSsoConnector/index.ts
  packages/core/src/sso/OidcConnector/index.ts
  packages/core/src/sso/OidcConnector/utils.test.ts
  packages/core/src/sso/OidcConnector/utils.ts
  packages/core/src/sso/OidcSsoConnector/index.test.ts
  packages/core/src/sso/OidcSsoConnector/index.ts
  packages/core/src/sso/OktaSsoConnector/index.ts
  packages/core/src/sso/SamlConnector/index.ts
  packages/core/src/sso/SamlConnector/utils.ts
  packages/core/src/sso/SamlSsoConnector/index.test.ts
  packages/core/src/sso/SamlSsoConnector/index.ts
  packages/core/src/sso/index.ts
  packages/core/src/sso/types/error.ts
  packages/core/src/sso/types/index.ts
  packages/integration-tests/src/tests/api/interaction/single-sign-on/sad-path.test.ts
Labels: feature, size/l

#4973 fix(experience): use absolute path for password sign-in form nav
  packages/experience/src/pages/SignIn/IdentifierSignInForm/index.test.tsx
  packages/experience/src/pages/SignIn/IdentifierSignInForm/use-on-submit.ts
Labels: bugfix, size/s

#4969 refactor(core,schemas): add SSO displayName
  packages/core/src/libraries/sign-in-experience/index.test.ts
  packages/core/src/libraries/sign-in-experience/index.ts
  packages/core/src/queries/sso-connectors.ts
  packages/core/src/routes/sso-connector/index.ts
  packages/integration-tests/src/constants.ts
  packages/integration-tests/src/tests/api/interaction/register-with-identifier/sad-path.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-passcode-identifier/sad-path.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier/happy-path.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier/sad-path.test.ts
  packages/integration-tests/src/tests/api/sso-connectors.test.ts
  packages/integration-tests/src/tests/api/well-known.test.ts
  packages/integration-tests/src/utils.ts
  packages/phrases/src/locales/de/errors/single-sign-on.ts
  packages/phrases/src/locales/en/errors/single-sign-on.ts
  packages/phrases/src/locales/es/errors/single-sign-on.ts
  packages/phrases/src/locales/fr/errors/single-sign-on.ts
  packages/phrases/src/locales/it/errors/single-sign-on.ts
  packages/phrases/src/locales/ja/errors/single-sign-on.ts
  packages/phrases/src/locales/ko/errors/single-sign-on.ts
  packages/phrases/src/locales/pl-pl/errors/single-sign-on.ts
  packages/phrases/src/locales/pt-br/errors/single-sign-on.ts
  packages/phrases/src/locales/pt-pt/errors/single-sign-on.ts
  packages/phrases/src/locales/ru/errors/single-sign-on.ts
  packages/phrases/src/locales/tr-tr/errors/single-sign-on.ts
  packages/phrases/src/locales/zh-cn/errors/single-sign-on.ts
  packages/phrases/src/locales/zh-hk/errors/single-sign-on.ts
  packages/phrases/src/locales/zh-tw/errors/single-sign-on.ts
  packages/schemas/src/foundations/jsonb-types/sso-connector.ts
Labels: enhancement, size/m

#4965 chore(console,phrases): update SSO connector name display
  packages/console/src/pages/EnterpriseSso/SsoCreationModal/SsoConnectorRadioGroup/SsoConnectorRadio/index.tsx
  packages/console/src/pages/EnterpriseSso/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/index.tsx
  packages/core/src/routes/sso-connector/index.ts
  packages/core/src/routes/sso-connector/utils.test.ts
  packages/core/src/routes/sso-connector/utils.ts
  packages/core/src/sso/AzureAdSsoConnector/index.ts
  packages/core/src/sso/GoogleWorkspaceSsoConnector/index.ts
  packages/core/src/sso/OidcSsoConnector/index.ts
  packages/core/src/sso/OktaSsoConnector/index.ts
  packages/core/src/sso/SamlSsoConnector/index.ts
  packages/core/src/sso/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/enterprise-sso.ts
  packages/schemas/src/types/sso-connector.ts
Labels: chore, size/s

#4976 fix(console): fix wrong illustration status
  packages/console/src/pages/EnterpriseSso/SsoConnectorLogo/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/Settings/index.tsx
Labels: bugfix, size/s

#4980 fix(console): update SSO connector logo uploader file types
  packages/console/src/pages/EnterpriseSsoDetails/Settings/LogosUploader/index.tsx
Labels: bugfix, size/xs

#4981 fix(console): add page level loading for SSO details page
  packages/console/src/pages/EnterpriseSsoDetails/index.tsx
Labels: bugfix, size/s

#4979 fix(console,phrases): remove SSO connectors status tags
  packages/console/src/pages/EnterpriseSso/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/en/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/es/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/fr/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/it/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/ja/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/ko/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/ru/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/enterprise-sso.ts
Labels: bugfix, size/m

#4983 feat(console,core,phrases): add display name field, fix error display
  packages/console/src/pages/EnterpriseSso/SsoCreationModal/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/Experience/LogosUploader/index.module.scss
  packages/console/src/pages/EnterpriseSsoDetails/Experience/LogosUploader/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/Experience/MultiInput/index.module.scss
  packages/console/src/pages/EnterpriseSsoDetails/Experience/MultiInput/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/Experience/index.module.scss
  packages/console/src/pages/EnterpriseSsoDetails/Experience/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/index.tsx
  packages/core/src/routes/sso-connector/index.ts
  packages/integration-tests/src/tests/api/sso-connectors.test.ts
  packages/phrases/src/locales/de/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/en/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/es/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/it/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/enterprise-sso-details.ts
Labels: feature, size/m
