Repository logto-io/logto, pull requests merged in 2023-03, with the labels that each got.

#3247 feat(console): support multi-tenancy (2/2)
  packages/console/src/App.tsx
  packages/console/src/cloud/pages/Main/Redirect.tsx
  packages/console/src/cloud/pages/Main/Tenants.tsx
  packages/console/src/cloud/pages/Main/index.module.scss
  packages/console/src/cloud/pages/Main/index.tsx
  packages/console/src/components/AppLoading/Offline.tsx
  packages/console/src/consts/tenants.ts
  packages/console/src/containers/AppLayout/components/UserInfo/index.tsx
  packages/console/src/contexts/TenantsProvider.tsx
  packages/console/src/hooks/use-theme.ts
  packages/console/src/utils/theme.ts
Labels: feature, size/l

#3253 chore: update README.md
  README.md
Labels: chore, size/s

#3231 feat(console): add callback uri field
  packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx
  packages/console/src/pages/Connectors/components/ConnectorForm/ConfigForm.module.scss
  packages/console/src/pages/Connectors/components/ConnectorForm/ConfigForm.tsx
  packages/console/src/pages/Connectors/components/Guide/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/connectors.ts
  packages/phrases/src/locales/en/translation/admin-console/connectors.ts
  packages/phrases/src/locales/fr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/ko/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/connectors.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/connectors.ts
Labels: feature, size/s

#3254 fix(core): error invalid credentials should return 401 instead of 400
  packages/core/src/libraries/user.ts
Labels: bugfix, size/xs

#3258 fix(console): fix app endpoints import path
  packages/console/src/pages/Connectors/components/ConnectorForm/ConfigForm.tsx
Labels: bugfix, size/xs

#3236 fix(console): refactor useMeCustomData
  packages/console/src/hooks/use-me-custom-data.ts
  packages/console/src/hooks/use-swr-fetcher.ts
  packages/console/src/hooks/use-swr-options.ts
Labels: bugfix, size/s

#3235 refactor(core,console): refactor AC 403 flow
  .changeset-staged/eight-rocks-wave.md
  packages/console/src/App.tsx
  packages/console/src/components/ConfirmModal/index.tsx
  packages/console/src/contexts/AppConfirmModalProvider/index.tsx
  packages/console/src/hooks/use-api.ts
  packages/console/src/hooks/use-confirm-modal.ts
  packages/console/src/hooks/use-me-custom-data.ts
  packages/console/src/hooks/use-swr-fetcher.ts
  packages/console/src/hooks/use-swr-options.ts
  packages/core/src/routes/interaction/consent.ts
Labels: enhancement, size/m

#3255 feat: create tenant for new users
  packages/cloud/package.json
  packages/cloud/src/libraries/tenants.ts
  packages/cloud/src/queries/tenants.ts
  packages/console/src/cloud/pages/Main/Tenants.tsx
  packages/console/src/cloud/pages/Main/index.tsx
  packages/core/nodemon.json
  packages/core/package.json
  packages/core/src/env-set/GlobalValues.ts
  packages/core/src/env-set/UrlSet.ts
  packages/core/src/env-set/parameters.ts
  packages/core/src/oidc/adapter.ts
  packages/core/src/routes/resource.ts
  packages/core/src/utils/search.ts
  packages/core/src/utils/tenant.ts
  packages/schemas/src/seeds/logto-config.ts
  pnpm-lock.yaml
Labels: feature, size/m

#3265 chore(phrases): update content
  packages/phrases/src/locales/de/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-br/translation/demo-app.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-pt/translation/demo-app.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
Labels: chore, size/s

#3263 fix(console): userinfo submenu should have shadow effect
  packages/console/src/containers/AppLayout/components/SubMenu/index.module.scss
Labels: bugfix, size/xs

#3264 refactor: optimize tenant requests
  packages/console/src/App.tsx
  packages/console/src/cloud/pages/Main/Tenants.tsx
  packages/console/src/cloud/pages/Main/index.tsx
  packages/console/src/components/AppLoading/Offline.tsx
  packages/console/src/contexts/AppEndpointsProvider.tsx
  packages/console/src/contexts/TenantsProvider.tsx
  packages/console/src/hooks/use-api.ts
  packages/core/src/env-set/GlobalValues.ts
  packages/core/src/env-set/UrlSet.ts
  packages/core/src/env-set/index.ts
  packages/core/src/middleware/koa-auth/utils.ts
  packages/core/src/middleware/koa-body-etag.ts
  packages/core/src/oidc/adapter.ts
  packages/core/src/oidc/init.ts
  packages/core/src/routes/well-known.ts
Labels: enhancement, size/m

#3256 feat(ui): add power by logto signature
  .changeset-staged/violet-cups-relate.md
  packages/ui/src/assets/icons/empty-state-dark.svg
  packages/ui/src/assets/icons/empty-state.svg
  packages/ui/src/assets/icons/logto-logo-dark.svg
  packages/ui/src/assets/icons/logto-logo-light.svg
  packages/ui/src/assets/icons/logto-logo-shadow.svg
  packages/ui/src/components/LogtoSignature/index.module.scss
  packages/ui/src/components/LogtoSignature/index.tsx
  packages/ui/src/components/Notification/AppNotification/index.module.scss
  packages/ui/src/containers/AppContent/index.module.scss
  packages/ui/src/containers/AppContent/index.tsx
  packages/ui/src/pages/ErrorPage/index.tsx
Labels: feature, size/m

#3260 refactor(console): replace theme selector with toggle in sie preview
  packages/console/src/assets/images/moon.svg
  packages/console/src/assets/images/sun.svg
  packages/console/src/components/ToggleThemeButton/index.module.scss
  packages/console/src/components/ToggleThemeButton/index.tsx
  packages/console/src/pages/SignInExperience/components/Preview/index.module.scss
  packages/console/src/pages/SignInExperience/components/Preview/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
Labels: enhancement, size/m

#3261 feat(console): application table placeholder
  packages/console/src/pages/Applications/components/ApplicationsPlaceholder/index.module.scss
  packages/console/src/pages/Applications/components/ApplicationsPlaceholder/index.tsx
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/Applications/components/TypeDescription/index.module.scss
  packages/console/src/pages/Applications/components/TypeDescription/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/applications.ts
  packages/phrases/src/locales/en/translation/admin-console/applications.ts
  packages/phrases/src/locales/fr/translation/admin-console/applications.ts
  packages/phrases/src/locales/ko/translation/admin-console/applications.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/applications.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/applications.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/applications.ts
Labels: feature, size/l

#3272 refactor(phrases): update live preview notification
  packages/phrases-ui/src/locales/de.ts
  packages/phrases-ui/src/locales/en.ts
  packages/phrases-ui/src/locales/fr.ts
  packages/phrases-ui/src/locales/ko.ts
  packages/phrases-ui/src/locales/pt-br.ts
  packages/phrases-ui/src/locales/pt-pt.ts
  packages/phrases-ui/src/locales/ru.ts
  packages/phrases-ui/src/locales/tr-tr.ts
  packages/phrases-ui/src/locales/zh-cn.ts
Labels: enhancement, size/s

#3268 refactor(console): handling cloud errors
  packages/console/src/App.tsx
  packages/console/src/components/AppError/index.tsx
  packages/console/src/components/AppLoading/Offline.tsx
  packages/console/src/containers/ErrorBoundary/index.tsx
  packages/console/src/hooks/use-swr-options.ts
  packages/console/src/utils/theme.ts
Labels: enhancement, size/s

#3270 feat(console): add live preview entry in the sie preview
  packages/console/src/assets/images/external-link.svg
  packages/console/src/components/Button/index.module.scss
  packages/console/src/components/Button/index.tsx
  packages/console/src/components/LivePreviewButton/index.module.scss
  packages/console/src/components/LivePreviewButton/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorForm/BasicForm.module.scss
  packages/console/src/pages/Connectors/components/ConnectorForm/BasicForm.tsx
  packages/console/src/pages/SignInExperience/components/Preview/index.tsx
  packages/console/src/pages/SignInExperience/components/Welcome/GuideModal.tsx
  packages/console/src/pages/SignInExperience/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
Labels: feature, size/m

#3252 feat(console): add mainflow like modal style for change password
  packages/console/src/assets/images/arrow-connection.svg
  packages/console/src/assets/images/arrow-left.svg
  packages/console/src/pages/Main/index.tsx
  packages/console/src/pages/Profile/components/BasicUserInfoSection/index.tsx
  packages/console/src/pages/Profile/components/MainFlowLikeModal/index.module.scss
  packages/console/src/pages/Profile/components/MainFlowLikeModal/index.tsx
  packages/console/src/pages/Profile/components/PasswordSection/index.tsx
  packages/console/src/pages/Profile/containers/BasicUserInfoUpdateModal/index.tsx
  packages/console/src/pages/Profile/containers/ChangePasswordModal/index.tsx
  packages/console/src/pages/Profile/containers/VerifyPasswordModal/index.tsx
  packages/console/src/pages/Profile/index.tsx
  packages/console/src/pages/Profile/modals/BasicUserInfoUpdateModal/index.tsx
  packages/console/src/pages/Profile/modals/ChangePasswordModal/index.module.scss
  packages/console/src/pages/Profile/modals/ChangePasswordModal/index.tsx
  packages/console/src/scss/modal.module.scss
  packages/core/src/routes-me/user.ts
  packages/core/src/utils/cookie.ts
  packages/phrases/src/locales/de/translation/admin-console/general.ts
  packages/phrases/src/locales/de/translation/admin-console/profile.ts
  packages/phrases/src/locales/en/translation/admin-console/general.ts
  packages/phrases/src/locales/en/translation/admin-console/profile.ts
  packages/phrases/src/locales/fr/translation/admin-console/general.ts
  packages/phrases/src/locales/fr/translation/admin-console/profile.ts
  packages/phrases/src/locales/ko/translation/admin-console/general.ts
  packages/phrases/src/locales/ko/translation/admin-console/profile.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/profile.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/profile.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/profile.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/profile.ts
  packages/schemas/src/types/user.ts
Labels: feature, size/xl

#3276 feat(console): add delete account dialog in profile page
  packages/console/src/pages/Profile/containers/DeleteAccountModal/index.module.scss
  packages/console/src/pages/Profile/containers/DeleteAccountModal/index.tsx
  packages/console/src/pages/Profile/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/profile.ts
Labels: feature, size/s

#3257 feat(console): add suffix icon button on input component
  packages/console/src/assets/images/clear-input.svg
  packages/console/src/assets/images/password-hide.svg
  packages/console/src/assets/images/password-show.svg
  packages/console/src/components/TextInput/index.module.scss
  packages/console/src/components/TextInput/index.tsx
  packages/console/src/pages/Profile/containers/ChangePasswordModal/index.tsx
  packages/console/src/pages/Profile/containers/VerifyPasswordModal/index.tsx
Labels: feature, size/s

#3269 feat(core): support path-based multi-tenancy
  .changeset/flat-mirrors-kiss.md
  packages/core/src/env-set/GlobalValues.ts
  packages/core/src/env-set/utils.ts
  packages/core/src/middleware/koa-auth/utils.ts
  packages/core/src/tenants/Tenant.ts
  packages/core/src/utils/tenant.test.ts
  packages/core/src/utils/tenant.ts
Labels: feature, size/m

#3274 refactor: seed data for multi-tenancy
  .changeset-staged/lucky-shrimps-collect.md
  .scripts/compare-database.js
  packages/cli/src/commands/database/seed/cloud.ts
  packages/cli/src/commands/database/seed/index.ts
  packages/cli/src/commands/database/seed/tables.ts
  packages/cli/src/commands/database/seed/tenant.ts
  packages/cli/src/commands/install/utils.ts
  packages/cloud/nodemon.json
  packages/cloud/package.json
  packages/cloud/src/middleware/with-auth.ts
  packages/cloud/src/queries/tenants.ts
  packages/core/src/env-set/index.ts
  packages/core/src/env-set/throw-errors.ts
  packages/core/src/env-set/utils.ts
  packages/core/src/middleware/koa-auth/utils.ts
  packages/core/src/middleware/koa-cors.test.ts
  packages/core/src/middleware/koa-cors.ts
  packages/core/src/middleware/koa-spa-session-guard.ts
  packages/core/src/oidc/adapter.ts
  packages/core/src/tenants/Tenant.ts
  packages/core/src/utils/tenant.test.ts
  packages/core/src/utils/tenant.ts
  packages/schemas/alterations/next-1677765137-seed-for-admin-tenant.ts
  packages/schemas/src/consts/system.ts
  packages/schemas/src/seeds/cloud-api.ts
  packages/schemas/src/seeds/index.ts
  packages/schemas/src/seeds/management-api.ts
  packages/shared/package.json
  packages/shared/src/env/GlobalValues.ts
  packages/shared/src/env/UrlSet.test.ts
  packages/shared/src/env/UrlSet.ts
  packages/shared/src/env/throw-errors.ts
  packages/shared/src/index.ts
  packages/shared/src/utils/index.ts
  packages/shared/src/utils/url.ts
  pnpm-lock.yaml
Labels: enhancement, size/l

#3281 refactor: fix cloud dev
  packages/cli/src/commands/database/seed/cloud.ts
  packages/console/src/contexts/AppEndpointsProvider.tsx
  packages/core/src/routes/interaction/actions/submit-interaction.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/core/src/utils/array.ts
  packages/shared/src/env/GlobalValues.ts
Labels: enhancement, size/s

#3283 chore: update docker-compose
  docker-compose.yml
Labels: chore, size/xs

#3243 fix(console): show platform icons for non-universal
  packages/console/src/pages/Connectors/components/ConnectorName/index.tsx
Labels: bugfix, size/xs

#3292 fix(core): check identifier collision before updating admin tenant user
  packages/core/src/routes-me/user.ts
Labels: bugfix, size/s

#3280 feat(ui): add interactionMode OIDC param
  .changeset-staged/gorgeous-berries-smoke.md
  packages/core/src/oidc/init.ts
  packages/core/src/oidc/type.ts
  packages/core/src/routes/consts.ts
Labels: feature, size/s

#3291 chore(console): remove settings page and its sidebar menu item
  .changeset-staged/little-cars-impress.md
  packages/console/src/containers/AppContent/Sidebar/index.tsx
  packages/console/src/containers/AppLayout/components/UserInfo/index.tsx
  packages/console/src/pages/Main/index.tsx
  packages/console/src/pages/Profile/containers/ChangePasswordModal/index.tsx
  packages/console/src/pages/Settings/components/ChangePassword.module.scss
  packages/console/src/pages/Settings/components/ChangePassword.tsx
  packages/console/src/pages/Settings/index.module.scss
  packages/console/src/pages/Settings/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/index.ts
  packages/phrases/src/locales/de/translation/admin-console/menu.ts
  packages/phrases/src/locales/de/translation/admin-console/settings.ts
  packages/phrases/src/locales/en/translation/admin-console/index.ts
  packages/phrases/src/locales/en/translation/admin-console/menu.ts
  packages/phrases/src/locales/en/translation/admin-console/settings.ts
  packages/phrases/src/locales/fr/translation/admin-console/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/menu.ts
  packages/phrases/src/locales/fr/translation/admin-console/settings.ts
  packages/phrases/src/locales/ko/translation/admin-console/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/menu.ts
  packages/phrases/src/locales/ko/translation/admin-console/settings.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/menu.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/settings.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/menu.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/settings.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/menu.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/settings.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/menu.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/settings.ts
Labels: chore, size/xl

#3277 refactor(console): sie preview
  packages/console/src/components/SignInExperiencePreview/index.module.scss
  packages/console/src/components/SignInExperiencePreview/index.tsx
  packages/console/src/components/SignInExperiencePreview/types.ts
  packages/console/src/pages/SignInExperience/components/Preview/index.module.scss
  packages/console/src/pages/SignInExperience/components/Preview/index.tsx
Labels: enhancement, size/l

#3278 fix(console): base path of sie pages
  packages/console/src/pages/SignInExperience/index.tsx
Labels: bugfix, size/xs

#3288 feat(console): link social account in ac profile page
  packages/console/package.json
  packages/console/src/assets/images/mail.svg
  packages/console/src/components/UserAvatar/index.module.scss
  packages/console/src/components/UserAvatar/index.tsx
  packages/console/src/components/UserInfoCard/index.module.scss
  packages/console/src/components/UserInfoCard/index.tsx
  packages/console/src/consts/index.ts
  packages/console/src/containers/AppLayout/components/UserInfo/index.module.scss
  packages/console/src/containers/AppLayout/components/UserInfo/index.tsx
  packages/console/src/pages/Main/index.tsx
  packages/console/src/pages/Profile/components/BasicUserInfoSection/index.module.scss
  packages/console/src/pages/Profile/components/BasicUserInfoSection/index.tsx
  packages/console/src/pages/Profile/components/CardContent/index.module.scss
  packages/console/src/pages/Profile/components/CardContent/index.tsx
  packages/console/src/pages/Profile/components/LinkAccountSection/index.module.scss
  packages/console/src/pages/Profile/components/LinkAccountSection/index.tsx
  packages/console/src/pages/Profile/components/NotSet/index.module.scss
  packages/console/src/pages/Profile/components/NotSet/index.tsx
  packages/console/src/pages/Profile/components/Section/index.module.scss
  packages/console/src/pages/Profile/containers/HandleSocialCallback/index.tsx
  packages/console/src/pages/Profile/index.tsx
  packages/console/src/pages/Profile/utils.ts
  packages/console/src/types/profile.ts
  packages/core/src/routes-me/social.ts
  packages/core/src/routes-me/user.ts
  packages/core/src/routes/connector.ts
  packages/core/src/utils/connectors/index.ts
  packages/ui/src/App.tsx
  packages/ui/src/pages/Springboard/index.tsx
  packages/ui/src/utils/social-connectors.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#3285 refactor: allow admin to create tenants
  .changeset-staged/gold-mugs-allow.md
  packages/cli/package.json
  packages/cli/src/commands/database/seed/tables.ts
  packages/cli/src/commands/database/seed/tenant.ts
  packages/cloud/package.json
  packages/cloud/src/routes/tenants.ts
  packages/console/package.json
  packages/console/src/App.tsx
  packages/console/src/components/SessionExpired/index.tsx
  packages/console/src/containers/AppLayout/index.tsx
  packages/console/src/containers/ErrorBoundary/index.tsx
  packages/console/src/hooks/use-api.ts
  packages/console/src/pages/Welcome/index.tsx
  packages/core/package.json
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/core/src/utils/array.ts
  packages/integration-tests/package.json
  packages/phrases-ui/package.json
  packages/phrases/package.json
  packages/schemas/alterations/next-1677907982-allow-admin-create-multiple-tenants.ts
  packages/schemas/package.json
  packages/schemas/src/seeds/cloud-api.ts
  packages/shared/package.json
  packages/toolkit/connector-kit/package.json
  packages/toolkit/core-kit/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: enhancement, size/l

#3297 fix(console): admin user should be able to link google account to profile
  packages/console/src/pages/Profile/containers/HandleSocialCallback/index.tsx
  packages/core/src/queries/user.ts
  packages/core/src/routes-me/social.ts
Labels: bugfix, size/s

#3293 chore: polish profile page UI
  packages/console/src/containers/AppLayout/components/UserInfo/index.tsx
  packages/console/src/hooks/use-logto-admin-user.ts
  packages/console/src/hooks/use-logto-userinfo.ts
  packages/console/src/pages/Profile/components/LinkAccountSection/index.tsx
  packages/console/src/pages/Profile/components/MainFlowLikeModal/index.module.scss
  packages/console/src/pages/Profile/components/Section/index.module.scss
  packages/console/src/pages/Profile/containers/BasicUserInfoUpdateModal/index.tsx
  packages/console/src/pages/Profile/containers/ChangePasswordModal/index.tsx
  packages/console/src/pages/Profile/containers/DeleteAccountModal/index.tsx
  packages/console/src/pages/Profile/containers/VerificationCodeModal/index.module.scss
  packages/console/src/pages/Profile/containers/VerificationCodeModal/index.tsx
  packages/console/src/pages/Profile/containers/VerifyPasswordModal/index.module.scss
  packages/console/src/pages/Profile/containers/VerifyPasswordModal/index.tsx
  packages/console/src/pages/Profile/index.module.scss
  packages/console/src/pages/Profile/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/profile.ts
  packages/phrases/src/locales/en/translation/admin-console/profile.ts
  packages/phrases/src/locales/fr/translation/admin-console/profile.ts
  packages/phrases/src/locales/ko/translation/admin-console/profile.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/profile.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/profile.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/profile.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/profile.ts
Labels: chore, size/l

#3300 fix(console): profile social linking in cloud env should use correct URL without double slashes
  packages/console/src/pages/Profile/components/LinkAccountSection/index.tsx
Labels: bugfix, size/xs

#3301 fix(console): admin user should be able to set email if current email is null
  packages/console/src/pages/Profile/components/LinkAccountSection/index.tsx
  packages/console/src/pages/Profile/containers/LinkEmailModal/index.tsx
Labels: bugfix, size/xs

#3303 fix(console): cloud ac profile should use correct callback URL when linking social
  packages/console/src/pages/Profile/components/LinkAccountSection/index.tsx
  packages/console/src/pages/Profile/containers/HandleSocialCallback/index.tsx
Labels: bugfix, size/xs

#3294 refactor(console): refactor console routes
  packages/console/src/cloud/App.tsx
  packages/console/src/cloud/pages/Congrats/index.tsx
  packages/console/src/cloud/pages/Onboard/index.tsx
  packages/console/src/cloud/types.ts
  packages/console/src/containers/AppContent/components/SubMenu/index.module.scss
  packages/console/src/containers/AppContent/components/SubMenu/index.tsx
  packages/console/src/containers/AppContent/components/Topbar/index.module.scss
  packages/console/src/containers/AppContent/components/Topbar/index.tsx
  packages/console/src/containers/AppContent/components/UserInfo/index.module.scss
  packages/console/src/containers/AppContent/components/UserInfo/index.tsx
  packages/console/src/containers/AppContent/components/UserInfoSkeleton/index.module.scss
  packages/console/src/containers/AppContent/components/UserInfoSkeleton/index.tsx
  packages/console/src/containers/AppContent/index.module.scss
  packages/console/src/containers/AppContent/index.tsx
  packages/console/src/containers/AppContent/types.ts
  packages/console/src/containers/AppLayout/index.module.scss
  packages/console/src/containers/AppLayout/index.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/components/Contact/hook.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/components/Contact/index.module.scss
  packages/console/src/containers/ConsoleContent/Sidebar/components/Contact/index.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/components/Item/index.module.scss
  packages/console/src/containers/ConsoleContent/Sidebar/components/Item/index.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/components/Section/index.module.scss
  packages/console/src/containers/ConsoleContent/Sidebar/components/Section/index.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/hook.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/icons/BarGraph.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/icons/Bolt.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/icons/Box.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/icons/Cloud.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/icons/Connection.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/icons/Contact.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/icons/Document.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/icons/Gear.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/icons/List.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/icons/UserProfile.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/icons/Web.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/index.module.scss
  packages/console/src/containers/ConsoleContent/Sidebar/index.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/utils.ts
  packages/console/src/containers/ConsoleContent/index.module.scss
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/pages/Main/index.tsx
Labels: enhancement, size/l

#3296 feat(console): onboarding sie preview
  packages/console/src/cloud/components/CardSelector/MultiCardSelector/index.tsx
  packages/console/src/cloud/constants/index.ts
  packages/console/src/cloud/pages/Congrats/index.tsx
  packages/console/src/cloud/pages/SignInExperience/components/PlatformTabs/PlatformTab.module.scss
  packages/console/src/cloud/pages/SignInExperience/components/PlatformTabs/PlatformTab.tsx
  packages/console/src/cloud/pages/SignInExperience/components/PlatformTabs/index.module.scss
  packages/console/src/cloud/pages/SignInExperience/components/PlatformTabs/index.tsx
  packages/console/src/cloud/pages/SignInExperience/components/Preview/index.module.scss
  packages/console/src/cloud/pages/SignInExperience/components/Preview/index.tsx
  packages/console/src/cloud/pages/SignInExperience/index.module.scss
  packages/console/src/cloud/pages/SignInExperience/index.tsx
  packages/console/src/cloud/pages/SignInExperience/utils.ts
  packages/console/src/cloud/types.ts
  packages/console/src/components/LivePreviewButton/index.tsx
  packages/console/src/components/RadioGroup/Radio.module.scss
  packages/console/src/components/SignInExperiencePreview/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/cloud.ts
  packages/phrases/src/locales/en/translation/admin-console/cloud.ts
  packages/phrases/src/locales/fr/translation/admin-console/cloud.ts
  packages/phrases/src/locales/ko/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/cloud.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/cloud.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/cloud.ts
Labels: feature, size/l

#3290 refactor: init cloud ui tests
  .github/workflows/integration-test.yml
  .scripts/package.sh
  packages/cli/src/commands/install/index.ts
  packages/cli/src/commands/install/utils.ts
  packages/integration-tests/package.json
  packages/integration-tests/src/constants.ts
  packages/integration-tests/src/tests/ui-cloud/smoke.test.ts
  packages/integration-tests/src/tests/ui/smoke.test.ts
Labels: enhancement, size/m

#3306 ci: add deploy cloud workflow
  .github/workflows/release-cloud.yml
Labels: size/s

#3307 ci: update cloud env name
  .github/workflows/release-cloud.yml
Labels: size/xs

#3298 refactor(core): update core password regex
  packages/core/src/routes/admin-user.test.ts
  packages/toolkit/core-kit/src/regex.ts
Labels: enhancement, size/xs

#3309 chore(console): fix typo
  packages/console/src/cloud/constants/index.ts
  packages/console/src/cloud/pages/About/index.tsx
  packages/console/src/cloud/pages/Congrats/index.tsx
  packages/console/src/cloud/pages/Onboarding/index.module.scss
  packages/console/src/cloud/pages/Onboarding/index.tsx
  packages/console/src/cloud/pages/SignInExperience/index.tsx
  packages/console/src/cloud/pages/SignInExperience/utils.ts
  packages/console/src/cloud/pages/Welcome/index.tsx
  packages/console/src/cloud/types.ts
  packages/console/src/cloud/utils.ts
  packages/console/src/containers/AppContent/index.tsx
  packages/console/src/pages/Main/index.tsx
Labels: chore, size/s

#3304 refactor(console): update the cloud congrats page
  packages/console/src/assets/images/calendar-outline.svg
  packages/console/src/cloud/components/ActionBar/index.tsx
  packages/console/src/cloud/components/Reservation/index.tsx
  packages/console/src/cloud/pages/Congrats/index.module.scss
  packages/console/src/cloud/pages/Congrats/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/cloud.ts
  packages/phrases/src/locales/en/translation/admin-console/cloud.ts
  packages/phrases/src/locales/fr/translation/admin-console/cloud.ts
  packages/phrases/src/locales/ko/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/cloud.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/cloud.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/cloud.ts
Labels: enhancement, size/m

#3289 feat(core,phrases,schemas): upload user assets with azure storage
  .changeset-staged/happy-paws-nail.md
  packages/core/package.json
  packages/core/src/index.ts
  packages/core/src/middleware/koa-guard.test.ts
  packages/core/src/middleware/koa-guard.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/user-assets.ts
  packages/core/src/tenants/SystemContext.ts
  packages/core/src/tenants/Tenant.ts
  packages/core/src/utils/storage/azure-storage.ts
  packages/core/src/utils/storage/consts.ts
  packages/core/src/utils/storage/index.ts
  packages/core/src/utils/storage/types.ts
  packages/phrases/src/locales/de/errors.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko/errors.ts
  packages/phrases/src/locales/pt-br/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
  packages/schemas/src/types/logto-config.ts
  packages/schemas/src/types/system.ts
  pnpm-lock.yaml
Labels: feature, size/l

#3251 feat(core,console): handle connector target confict
  packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx
  packages/console/src/pages/Connectors/components/ConnectorForm/BasicForm.module.scss
  packages/console/src/pages/Connectors/components/ConnectorForm/BasicForm.tsx
  packages/console/src/pages/Connectors/components/Guide/index.tsx
  packages/core/src/routes/connector.ts
  packages/phrases/src/locales/de/translation/admin-console/connectors.ts
  packages/phrases/src/locales/en/translation/admin-console/connectors.ts
  packages/phrases/src/locales/fr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/ko/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/connectors.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/connectors.ts
  packages/schemas/src/api/error.ts
Labels: feature, size/l

#3308 chore(console): polish UI and add ac profile loading skeleton
  packages/console/src/components/UserInfoCard/index.tsx
  packages/console/src/containers/AppContent/components/UserInfo/index.tsx
  packages/console/src/hooks/use-current-user.ts
  packages/console/src/pages/Profile/components/BasicUserInfoSection/index.tsx
  packages/console/src/pages/Profile/components/CardContent/index.module.scss
  packages/console/src/pages/Profile/components/CardContent/index.tsx
  packages/console/src/pages/Profile/components/LinkAccountSection/index.module.scss
  packages/console/src/pages/Profile/components/LinkAccountSection/index.tsx
  packages/console/src/pages/Profile/components/Section/index.module.scss
  packages/console/src/pages/Profile/components/Section/index.tsx
  packages/console/src/pages/Profile/components/Skeleton/index.module.scss
  packages/console/src/pages/Profile/components/Skeleton/index.tsx
  packages/console/src/pages/Profile/containers/VerificationCodeModal/index.tsx
  packages/console/src/pages/Profile/index.tsx
Labels: chore, size/l

#3320 feat(core): add s3 storage provider
  .changeset-staged/giant-mice-applaud.md
  packages/core/package.json
  packages/core/src/utils/storage/index.ts
  packages/core/src/utils/storage/s3-storage.ts
  packages/schemas/src/types/system.ts
  pnpm-lock.yaml
Labels: feature, size/s

#3318 feat(cli): add system get and set commands
  .changeset-staged/loud-snakes-cross.md
  packages/cli/src/commands/database/index.ts
  packages/cli/src/commands/database/system.ts
  packages/cli/src/queries/system.ts
Labels: feature, size/m

#3299 test: improve ui test code
  packages/console/src/cloud/pages/Main/Tenants.tsx
  packages/integration-tests/package.json
  packages/integration-tests/src/tests/ui-cloud/smoke.test.ts
  packages/integration-tests/src/tests/ui/smoke.test.ts
  packages/phrases/src/locales/en/translation/admin-console/welcome.ts
  pnpm-lock.yaml
Labels: testing, size/m

#3315 feat(core,console,schemas,phrases): add privacy policy url
  .changeset-staged/great-turkeys-fry.md
  packages/console/src/pages/SignInExperience/tabs/Others/TermsForm.tsx
  packages/console/src/pages/SignInExperience/utils/form.ts
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/queries/sign-in-experience.test.ts
  packages/core/src/routes/sign-in-experience/guard.test.ts
  packages/core/src/routes/sign-in-experience/index.test.ts
  packages/core/src/routes/sign-in-experience/index.ts
  packages/integration-tests/src/tests/api/sign-in-experience.test.ts
  packages/phrases/src/locales/de/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
  packages/schemas/alterations/next-1678157950-privacy-policy-url.ts
  packages/schemas/src/seeds/sign-in-experience.ts
  packages/schemas/tables/sign_in_experiences.sql
  packages/ui/src/__mocks__/logto.tsx
Labels: feature, size/m

#3311 refactor: use URL class
  packages/cli/src/commands/database/seed/cloud.ts
  packages/console/src/App.tsx
  packages/console/src/consts/tenants.ts
  packages/console/src/hooks/use-api.ts
  packages/console/src/pages/Profile/components/LinkAccountSection/index.tsx
  packages/core/src/env-set/index.ts
  packages/core/src/middleware/koa-auth/utils.ts
  packages/core/src/middleware/koa-spa-session-guard.ts
  packages/core/src/oidc/adapter.ts
  packages/integration-tests/src/tests/ui-cloud/smoke.test.ts
  packages/shared/src/utils/index.ts
  packages/shared/src/utils/url.ts
Labels: enhancement, size/s

#3313 test: add ui cloud tests
  packages/integration-tests/src/tests/ui-cloud/smoke.test.ts
Labels: testing, size/s

#3316 test(cloud): init cloud unit tests
  packages/cli/package.json
  packages/cloud/jest.config.js
  packages/cloud/package.json
  packages/cloud/src/middleware/with-auth.ts
  packages/cloud/src/routes-anonymous/index.test.ts
  packages/cloud/src/routes/index.ts
  packages/cloud/src/routes/tenants.test.ts
  packages/cloud/src/routes/tenants.ts
  packages/cloud/src/test-utils/context.ts
  packages/cloud/src/test-utils/function.ts
  packages/cloud/src/test-utils/libraries.ts
  packages/cloud/tsconfig.json
  packages/cloud/tsconfig.test.json
  packages/core/package.json
  packages/integration-tests/package.json
  packages/schemas/package.json
  packages/shared/package.json
  packages/toolkit/core-kit/package.json
  packages/toolkit/language-kit/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: testing, size/l

#3310 fix(console): passwordless connectors should not show callbackUri
  packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx
  packages/console/src/pages/Connectors/components/ConnectorForm/ConfigForm.tsx
  packages/console/src/pages/Connectors/components/Guide/index.tsx
Labels: bugfix, size/s

#3321 refactor(ui): add privacy link to the terms
  packages/phrases-ui/src/locales/de.ts
  packages/phrases-ui/src/locales/en.ts
  packages/phrases-ui/src/locales/fr.ts
  packages/phrases-ui/src/locales/ko.ts
  packages/phrases-ui/src/locales/pt-br.ts
  packages/phrases-ui/src/locales/pt-pt.ts
  packages/phrases-ui/src/locales/ru.ts
  packages/phrases-ui/src/locales/tr-tr.ts
  packages/phrases-ui/src/locales/zh-cn.ts
  packages/ui/src/components/TermsLinks/index.module.scss
  packages/ui/src/components/TermsLinks/index.tsx
  packages/ui/src/components/TermsOfUse/index.test.tsx
  packages/ui/src/components/TermsOfUse/index.tsx
  packages/ui/src/containers/SocialSignIn/index.tsx
  packages/ui/src/containers/TermsAndPrivacy/TermsAndPrivacyConfirmModalContent/index.tsx
  packages/ui/src/containers/TermsAndPrivacy/index.module.scss
  packages/ui/src/containers/TermsAndPrivacy/index.tsx
  packages/ui/src/containers/TermsAndPrivacy/intext.test.tsx
  packages/ui/src/containers/TermsOfUse/IframeConfirmModalContent/index.module.scss
  packages/ui/src/containers/TermsOfUse/IframeConfirmModalContent/index.tsx
  packages/ui/src/containers/TermsOfUse/TermsOfUseConfirmModalContent/index.tsx
  packages/ui/src/containers/TermsOfUse/index.tsx
  packages/ui/src/hooks/use-terms.ts
  packages/ui/src/pages/Register/IdentifierRegisterForm/index.tsx
  packages/ui/src/pages/SignIn/IdentifierSignInForm/index.tsx
  packages/ui/src/pages/SignIn/PasswordSignInForm/index.tsx
Labels: enhancement, size/l

#3322 fix: should return demo app data when query api
  packages/console/src/pages/AuditLogDetails/index.tsx
  packages/core/src/oidc/adapter.ts
  packages/core/src/routes/application.ts
  packages/demo-app/src/index.html
  packages/schemas/src/seeds/application.ts
Labels: bugfix, size/s

#3314 feat(console): cloud preview broadcast
  packages/console/src/cloud/components/Broadcast/index.module.scss
  packages/console/src/cloud/components/Broadcast/index.tsx
  packages/console/src/cloud/constants/index.ts
  packages/console/src/containers/AppContent/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/cloud.ts
  packages/phrases/src/locales/en/translation/admin-console/cloud.ts
  packages/phrases/src/locales/fr/translation/admin-console/cloud.ts
  packages/phrases/src/locales/ko/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/cloud.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/cloud.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/cloud.ts
Labels: feature, size/s

#3230 Revert "Revert "refactor(ui): hard code the page slogan""
  packages/phrases-ui/src/locales/de.ts
  packages/phrases-ui/src/locales/en.ts
  packages/phrases-ui/src/locales/fr.ts
  packages/phrases-ui/src/locales/ko.ts
  packages/phrases-ui/src/locales/pt-br.ts
  packages/phrases-ui/src/locales/pt-pt.ts
  packages/phrases-ui/src/locales/ru.ts
  packages/phrases-ui/src/locales/tr-tr.ts
  packages/phrases-ui/src/locales/zh-cn.ts
  packages/ui/src/components/BrandingHeader/index.test.tsx
  packages/ui/src/components/BrandingHeader/index.tsx
  packages/ui/src/containers/LandingPageContainer/index.tsx
  packages/ui/src/pages/Register/index.tsx
  packages/ui/src/pages/SignIn/index.tsx
Labels: size/s

#3324 refactor(console): polish code by improving data types and API routes
  packages/console/src/components/ImageWithErrorFallback/index.tsx
  packages/console/src/hooks/use-current-user.ts
  packages/console/src/pages/Profile/components/BasicUserInfoSection/index.tsx
  packages/console/src/pages/Profile/components/CardContent/index.tsx
  packages/console/src/pages/Profile/components/LinkAccountSection/index.tsx
  packages/console/src/pages/Profile/containers/BasicUserInfoUpdateModal/index.tsx
  packages/console/src/pages/Profile/containers/VerificationCodeModal/index.tsx
  packages/console/src/pages/Profile/index.tsx
  packages/core/src/routes-me/user.ts
  packages/core/src/routes-me/verification-code.ts
  packages/schemas/src/types/user.ts
Labels: enhancement, size/s

#3329 fix(core): should not guard input when verifying password
  packages/core/src/routes-me/user.ts
Labels: bugfix, size/xs

#3319 fix(ui): reset InputField on enabledTypes change
  packages/ui/src/components/InputFields/SmartInputField/use-smart-input-field.ts
  packages/ui/src/hooks/use-update-effect.ts
Labels: bugfix, size/s

#3337 fix(console): text input in AC should support both 36px and 44px heights
  packages/console/src/components/TextInput/index.module.scss
  packages/console/src/components/TextInput/index.tsx
  packages/console/src/pages/Profile/containers/BasicUserInfoUpdateModal/index.tsx
  packages/console/src/pages/Profile/containers/ChangePasswordModal/index.tsx
  packages/console/src/pages/Profile/containers/LinkEmailModal/index.tsx
  packages/console/src/pages/Profile/containers/VerifyPasswordModal/index.tsx
Labels: bugfix, size/s

#3334 fix(console): fallback broken connector logo to default image
  packages/console/src/components/ConnectorLogo/index.module.scss
  packages/console/src/components/ConnectorLogo/index.tsx
  packages/console/src/components/ImageWithErrorFallback/index.tsx
  packages/console/src/pages/ConnectorDetails/index.module.scss
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorName/index.tsx
  packages/console/src/pages/Connectors/components/CreateForm/index.module.scss
  packages/console/src/pages/Connectors/components/CreateForm/index.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SocialConnectorEditBox/AddButton.module.scss
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SocialConnectorEditBox/AddButton.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SocialConnectorEditBox/SelectedConnectorItem.module.scss
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SocialConnectorEditBox/SelectedConnectorItem.tsx
Labels: bugfix, size/m

#3335 fix(console): better error handling when linking social in profile page
  packages/console/src/pages/Profile/containers/HandleSocialCallback/index.tsx
Labels: bugfix, size/s

#3332 fix(console): properly handle errors on profile change basic info dialog
  packages/console/src/pages/Profile/containers/BasicUserInfoUpdateModal/index.tsx
  packages/console/src/pages/Profile/containers/VerificationCodeModal/index.tsx
  packages/console/src/pages/Profile/utils.ts
Labels: bugfix, size/s

#3330 fix(console): verify email via verification code should work properly
  packages/console/src/pages/Profile/containers/VerificationCodeModal/index.tsx
Labels: bugfix, size/xs

#3326 refactor: remove branding style config
  .changeset-staged/nice-lions-dream.md
  packages/console/src/pages/SignInExperience/tabs/Branding/BrandingForm.tsx
  packages/console/src/pages/SignInExperience/utils/form.ts
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/libraries/sign-in-experience/index.test.ts
  packages/core/src/libraries/sign-in-experience/index.ts
  packages/core/src/routes/sign-in-experience/guard.branding.test.ts
  packages/core/src/routes/sign-in-experience/index.test.ts
  packages/core/src/routes/sign-in-experience/index.ts
  packages/integration-tests/src/tests/api/sign-in-experience.test.ts
  packages/phrases/src/locales/de/errors.ts
  packages/phrases/src/locales/de/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/ko/errors.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-br/errors.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/zh-cn/errors.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
  packages/schemas/alterations/next-1678259693-remove-branding-style-config.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/seeds/sign-in-experience.ts
  packages/ui/src/__mocks__/logto.tsx
  packages/ui/src/components/BrandingHeader/index.tsx
  packages/ui/src/containers/LandingPageContainer/index.tsx
  packages/ui/src/hooks/use-preview.ts
  packages/ui/src/pages/Consent/index.tsx
  packages/ui/src/utils/logo.ts
Labels: enhancement, size/l

#3338 style(console): change "not set" font to body-2
  packages/console/src/pages/Profile/components/NotSet/index.module.scss
Labels: size/xs

#3328 refactor(schemas): use restrictive policies
  .scripts/compare-database.js
  packages/schemas/alterations/next-1678269972-use-restrictive-policies.ts
  packages/schemas/tables/_after_all.sql
  packages/schemas/tables/_after_each.sql
Labels: enhancement, size/m

#3333 refactor: hide internal roles for user tenants
  packages/cli/package.json
  packages/cli/src/database.ts
  packages/cli/src/queries/system.test.ts
  packages/cli/src/queries/system.ts
  packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
  packages/core/package.json
  packages/core/src/middleware/koa-role-rls-error-handler.ts
  packages/core/src/queries/applications-roles.ts
  packages/core/src/queries/roles.ts
  packages/core/src/routes/admin-user-role.ts
  packages/core/src/routes/application.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/core/src/routes/role.ts
  packages/integration-tests/src/tests/api/role.scope.test.ts
  packages/integration-tests/src/tests/api/role.test.ts
  packages/phrases/src/locales/de/errors.ts
  packages/phrases/src/locales/de/translation/admin-console/errors.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/en/translation/admin-console/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/fr/translation/admin-console/errors.ts
  packages/phrases/src/locales/ko/errors.ts
  packages/phrases/src/locales/ko/translation/admin-console/errors.ts
  packages/phrases/src/locales/pt-br/errors.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/errors.ts
  packages/schemas/alterations/next-1678284778-restrict-internal-roles.ts
  packages/schemas/src/index.ts
  packages/schemas/src/seeds/cloud-api.ts
  packages/schemas/src/seeds/management-api.ts
  packages/schemas/src/types/user.ts
  packages/schemas/src/utils/index.ts
  packages/schemas/src/utils/role.ts
  packages/schemas/tables/_after_all.sql
  pnpm-lock.yaml
Labels: enhancement, size/l

#3341 fix(console): remove "change" button from link social in profile
  packages/console/src/pages/Profile/components/LinkAccountSection/index.tsx
Labels: bugfix, size/s

#3343 chore: update admin tenant endpoint
  Dockerfile.cloud
Labels: chore, size/xs

#3327 refactor(ui): remove the terms verification in sign-in page
  .changeset-staged/curly-shoes-end.md
  packages/ui/src/components/TermsLinks/index.module.scss
  packages/ui/src/components/TermsLinks/index.tsx
  packages/ui/src/containers/SocialSignIn/index.module.scss
  packages/ui/src/containers/SocialSignIn/index.tsx
  packages/ui/src/containers/SocialSignInList/index.module.scss
  packages/ui/src/containers/SocialSignInList/index.test.tsx
  packages/ui/src/containers/SocialSignInList/index.tsx
  packages/ui/src/containers/TermsAndPrivacyLinks/index.tsx
  packages/ui/src/hooks/use-social-sign-in-listener.ts
  packages/ui/src/hooks/use-social.ts
  packages/ui/src/pages/Register/IdentifierRegisterForm/index.test.tsx
  packages/ui/src/pages/Register/index.module.scss
  packages/ui/src/pages/Register/index.tsx
  packages/ui/src/pages/SignIn/IdentifierSignInForm/index.module.scss
  packages/ui/src/pages/SignIn/IdentifierSignInForm/index.tsx
  packages/ui/src/pages/SignIn/Main.tsx
  packages/ui/src/pages/SignIn/PasswordSignInForm/index.test.tsx
  packages/ui/src/pages/SignIn/PasswordSignInForm/index.tsx
  packages/ui/src/pages/SignIn/index.module.scss
  packages/ui/src/pages/SignIn/index.test.tsx
  packages/ui/src/pages/SignIn/index.tsx
  packages/ui/src/pages/SocialSignInCallback/index.test.tsx
Labels: enhancement, size/l

#3340 refactor(console): extract the onboarding app from the admin console
  packages/console/src/App.tsx
  packages/console/src/cloud/pages/Onboarding/index.module.scss
  packages/console/src/cloud/pages/Onboarding/index.tsx
  packages/console/src/cloud/scss/cloud-page-size.scss
  packages/console/src/cloud/types.ts
  packages/console/src/cloud/utils.ts
  packages/console/src/containers/AppContent/components/Topbar/index.tsx
  packages/console/src/containers/AppContent/index.tsx
  packages/console/src/containers/TenantAppContainer/index.tsx
  packages/console/src/contexts/TenantsProvider.tsx
  packages/console/src/onboarding/App.module.scss
  packages/console/src/onboarding/App.tsx
  packages/console/src/onboarding/components/ActionBar/index.module.scss
  packages/console/src/onboarding/components/ActionBar/index.tsx
  packages/console/src/onboarding/components/Broadcast/index.module.scss
  packages/console/src/onboarding/components/Broadcast/index.tsx
  packages/console/src/onboarding/components/CardSelector/CardSelector.tsx
  packages/console/src/onboarding/components/CardSelector/MultiCardSelector/index.module.scss
  packages/console/src/onboarding/components/CardSelector/MultiCardSelector/index.tsx
  packages/console/src/onboarding/components/CardSelector/index.tsx
  packages/console/src/onboarding/components/CardSelector/types.ts
  packages/console/src/onboarding/components/EarlyBirdGift/GiftModal/index.module.scss
  packages/console/src/onboarding/components/EarlyBirdGift/GiftModal/index.tsx
  packages/console/src/onboarding/components/EarlyBirdGift/index.tsx
  packages/console/src/onboarding/components/ProgressBar/index.module.scss
  packages/console/src/onboarding/components/ProgressBar/index.tsx
  packages/console/src/onboarding/components/Reservation/index.module.scss
  packages/console/src/onboarding/components/Reservation/index.tsx
  packages/console/src/onboarding/constants/index.ts
  packages/console/src/onboarding/containers/AppContent/index.module.scss
  packages/console/src/onboarding/containers/AppContent/index.tsx
  packages/console/src/onboarding/hooks/use-user-onboarding-data.ts
  packages/console/src/onboarding/pages/About/index.module.scss
  packages/console/src/onboarding/pages/About/index.tsx
  packages/console/src/onboarding/pages/About/options.tsx
  packages/console/src/onboarding/pages/Congrats/index.module.scss
  packages/console/src/onboarding/pages/Congrats/index.tsx
  packages/console/src/onboarding/pages/SignInExperience/components/PlatformTabs/PlatformTab.module.scss
  packages/console/src/onboarding/pages/SignInExperience/components/PlatformTabs/PlatformTab.tsx
  packages/console/src/onboarding/pages/SignInExperience/components/PlatformTabs/index.module.scss
  packages/console/src/onboarding/pages/SignInExperience/components/PlatformTabs/index.tsx
  packages/console/src/onboarding/pages/SignInExperience/components/Preview/index.module.scss
  packages/console/src/onboarding/pages/SignInExperience/components/Preview/index.tsx
  packages/console/src/onboarding/pages/SignInExperience/index.module.scss
  packages/console/src/onboarding/pages/SignInExperience/index.tsx
  packages/console/src/onboarding/pages/SignInExperience/options.tsx
  packages/console/src/onboarding/pages/SignInExperience/utils.ts
  packages/console/src/onboarding/pages/Welcome/index.module.scss
  packages/console/src/onboarding/pages/Welcome/index.tsx
  packages/console/src/onboarding/pages/Welcome/options.tsx
  packages/console/src/onboarding/scss/layout.module.scss
  packages/console/src/onboarding/types.ts
  packages/console/src/onboarding/utils.ts
  packages/console/src/pages/Main/index.tsx
  packages/console/src/pages/NotFound/index.module.scss
  packages/console/src/pages/NotFound/index.tsx
  packages/integration-tests/src/tests/ui-cloud/smoke.test.ts
Labels: enhancement, size/xl

#3346 refactor(core): refactor backend password regex rule
  packages/core/src/routes/admin-user.test.ts
  packages/toolkit/core-kit/src/regex.test.ts
  packages/toolkit/core-kit/src/regex.ts
Labels: enhancement, size/s

#3351 ci: release cloud prod
  .github/workflows/release-cloud.yml
  Dockerfile.cloud
Labels: size/s

#3349 refactor(phrases): update de phrases
  packages/phrases-ui/src/locales/de.ts
Labels: enhancement, feature, size/s

#3353 refactor(ui): update fr phrases
  packages/phrases-ui/src/locales/fr.ts
Labels: enhancement, size/s

#3352 refactor(phrases): update en phrases
  packages/phrases-ui/src/locales/en.ts
Labels: enhancement, feature, size/s

#3323 feat(console): image uploader
  packages/console/package.json
  packages/console/src/assets/images/upload.svg
  packages/console/src/components/FileUploader/index.module.scss
  packages/console/src/components/FileUploader/index.tsx
  packages/console/src/components/ImageUploader/index.module.scss
  packages/console/src/components/ImageUploader/index.tsx
  packages/core/src/routes/user-assets.ts
  packages/core/src/utils/storage/consts.ts
  packages/phrases/src/locales/de/translation/admin-console/components.ts
  packages/phrases/src/locales/de/translation/admin-console/index.ts
  packages/phrases/src/locales/en/translation/admin-console/components.ts
  packages/phrases/src/locales/en/translation/admin-console/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/components.ts
  packages/phrases/src/locales/fr/translation/admin-console/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/components.ts
  packages/phrases/src/locales/ko/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/components.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/components.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/components.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/components.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/index.ts
  packages/schemas/src/types/index.ts
  packages/schemas/src/types/user-assets.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#3355 refactor(ui): reorg the ui page layout structure
  packages/ui/src/App.tsx
  packages/ui/src/Layout/AppLayout/index.module.scss
  packages/ui/src/Layout/AppLayout/index.tsx
  packages/ui/src/Layout/LandingPageLayout/index.module.scss
  packages/ui/src/Layout/LandingPageLayout/index.tsx
  packages/ui/src/Layout/SecondaryPageLayout/index.module.scss
  packages/ui/src/Layout/SecondaryPageLayout/index.tsx
  packages/ui/src/Layout/StaticPageLayout/index.module.scss
  packages/ui/src/Layout/StaticPageLayout/index.tsx
  packages/ui/src/Providers/AppBoundary/index.module.scss
  packages/ui/src/Providers/AppBoundary/index.tsx
  packages/ui/src/Providers/ConfirmModalProvider/index.tsx
  packages/ui/src/Providers/ConfirmModalProvider/indext.test.tsx
  packages/ui/src/Providers/LoadingLayerProvider/index.tsx
  packages/ui/src/Providers/ToastProvider/index.tsx
  packages/ui/src/hooks/use-confirm-modal.ts
  packages/ui/src/hooks/use-preview.ts
  packages/ui/src/pages/Callback/index.module.scss
  packages/ui/src/pages/Callback/index.tsx
  packages/ui/src/pages/Consent/index.module.scss
  packages/ui/src/pages/Consent/index.tsx
  packages/ui/src/pages/Continue/SetEmailOrPhone/index.tsx
  packages/ui/src/pages/Continue/SetPassword/index.tsx
  packages/ui/src/pages/Continue/SetUsername/index.tsx
  packages/ui/src/pages/ErrorPage/index.module.scss
  packages/ui/src/pages/ErrorPage/index.tsx
  packages/ui/src/pages/ForgotPassword/index.tsx
  packages/ui/src/pages/Register/IdentifierRegisterForm/index.test.tsx
  packages/ui/src/pages/Register/index.tsx
  packages/ui/src/pages/RegisterPassword/index.tsx
  packages/ui/src/pages/ResetPassword/index.tsx
  packages/ui/src/pages/SignIn/index.tsx
  packages/ui/src/pages/SignInPassword/index.tsx
  packages/ui/src/pages/SocialLanding/index.module.scss
  packages/ui/src/pages/SocialLanding/index.tsx
  packages/ui/src/pages/SocialLinkAccount/index.tsx
  packages/ui/src/pages/VerificationCode/index.tsx
Labels: enhancement, size/m

#3356 ci: fix release cloud workflow
  .github/workflows/release-cloud.yml
Labels: size/xs

#3354 refactor(phrases): update ko phrases
  packages/phrases-ui/src/locales/ko.ts
Labels: enhancement, size/s

#3357 refactor(phrases): update multiple phrases
  packages/phrases-ui/src/locales/pt-br.ts
  packages/phrases-ui/src/locales/pt-pt.ts
  packages/phrases-ui/src/locales/ru.ts
  packages/phrases-ui/src/locales/tr-tr.ts
  packages/phrases-ui/src/locales/zh-cn.ts
Labels: enhancement, size/l

#3342 refactor(ui): preload data
  packages/ui/.parcelrc
  packages/ui/.parcelrc.arm64
  packages/ui/package.json
  packages/ui/src/index.html
  pnpm-lock.yaml
Labels: enhancement, size/s

#3359 refactor(core,ui,console): compress response when possible
  packages/console/.parcelrc
  packages/console/.parcelrc.arm64
  packages/console/package.json
  packages/core/package.json
  packages/core/src/tenants/Tenant.ts
  packages/ui/.parcelrc
  packages/ui/.parcelrc.arm64
  packages/ui/package.json
  pnpm-lock.yaml
Labels: enhancement, size/s

#3366 fix(console): text input value should display properly
  packages/console/src/components/TextInput/index.tsx
Labels: bugfix, size/xs

#3364 feat(cli,cloud,schemas): seed m2m app for each tenant
  .scripts/compare-database.js
  packages/cli/src/commands/database/seed/tables.ts
  packages/cloud/src/libraries/tenants.ts
  packages/cloud/src/queries/application.ts
  packages/cloud/src/queries/index.ts
  packages/cloud/src/queries/roles.ts
  packages/schemas/alterations/next-1678425761-m2m-app-for-tenants.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/seeds/application.ts
  packages/schemas/src/seeds/cloud-api.ts
  packages/schemas/src/types/user.ts
Labels: feature, size/l

#3362 refactor(cloud): send compressed spa file when possible
  packages/cloud/package.json
  packages/cloud/src/middleware/with-spa.ts
  packages/core/package.json
  packages/integration-tests/package.json
  packages/schemas/package.json
  pnpm-lock.yaml
Labels: enhancement, size/s

#3371 ci: refactor release workflow
  .github/workflows/release-cloud.yml
  .github/workflows/release.yml
Labels: size/m

#3370 refactor(console): optimize adaptation rules of sie preview
  packages/console/src/components/SignInExperiencePreview/index.module.scss
  packages/console/src/components/SignInExperiencePreview/screen-size.module.scss
  packages/ui/src/components/BrandingHeader/index.module.scss
Labels: enhancement, size/s

#3339 fix(console): add auto focus to inputs in ac profile modals
  packages/console/src/pages/Profile/containers/BasicUserInfoUpdateModal/index.tsx
  packages/console/src/pages/Profile/containers/ChangePasswordModal/index.tsx
  packages/console/src/pages/Profile/containers/LinkEmailModal/index.tsx
  packages/console/src/pages/Profile/containers/VerifyPasswordModal/index.tsx
Labels: bugfix, size/xs

#3350 fix(ui): theme adaption
  packages/ui/src/App.tsx
  packages/ui/src/hooks/use-page-context.ts
  packages/ui/src/hooks/use-preview.ts
  packages/ui/src/hooks/use-theme.ts
Labels: bugfix, size/s

#3361 refactor(core): fix api issues
  packages/core/src/app/init.ts
  packages/core/src/middleware/koa-body-etag.ts
  packages/core/src/middleware/koa-spa-session-guard.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/well-known.ts
  packages/core/src/utils/test-utils.ts
Labels: enhancement, size/m

#3363 refactor(core,cloud): disable cache for index files
  packages/cloud/src/middleware/with-spa.ts
  packages/core/src/middleware/koa-serve-static.ts
Labels: enhancement, size/s

#3373 refactor(core): update cache size and end pool when tenant disposes
  packages/core/src/env-set/index.ts
  packages/core/src/tenants/index.ts
Labels: enhancement, size/s

#3345 fix(core,schemas): remove sessionId usage from verification status table
  packages/core/src/libraries/verification-status.ts
  packages/core/src/queries/verification-status.ts
  packages/core/src/routes-me/user.ts
  packages/core/src/routes-me/verification-code.ts
  packages/core/src/utils/cookie.ts
  packages/schemas/alterations/next-1678199795-add-verification-status-table.ts
  packages/schemas/tables/verification_statuses.sql
Labels: bugfix, size/s

#3376 ci: fix release workflow
  .github/workflows/release.yml
Labels: size/s

#3365 feat(schemas,core): add `sessionNotFoundRedirectUrl` tenant config
  .changeset-staged/lemon-spies-switch.md
  packages/core/src/middleware/koa-spa-session-guard.test.ts
  packages/core/src/middleware/koa-spa-session-guard.ts
  packages/core/src/queries/logto-config.ts
  packages/core/src/tenants/Tenant.ts
  packages/schemas/src/seeds/logto-config.ts
  packages/schemas/src/types/logto-config.ts
Labels: feature, size/m

#3325 feat(console): enable AC config and real-time live preview on customCss
  .changeset-staged/quick-schools-complain.md
  packages/console/src/components/SignInExperiencePreview/index.tsx
  packages/console/src/pages/SignInExperience/tabs/Branding/CustomCssForm.tsx
  packages/console/src/pages/SignInExperience/tabs/Branding/index.module.scss
  packages/console/src/pages/SignInExperience/tabs/Branding/index.tsx
  packages/console/src/pages/SignInExperience/utils/form.ts
  packages/phrases/src/locales/de/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
  packages/ui/src/App.tsx
Labels: feature, size/m

#3374 refactor(core)!: move phrases api to well-known path
  .changeset-staged/stupid-jokes-brush.md
  packages/core/src/routes/init.ts
  packages/core/src/routes/phrase.ts
  packages/core/src/routes/well-known.phrases.content-language.test.ts
  packages/core/src/routes/well-known.phrases.test.ts
  packages/core/src/routes/well-known.ts
  packages/ui/src/apis/settings.ts
  packages/ui/src/index.html
Labels: enhancement, size/m

#3375 refactor: remove withtyped in core
  packages/cli/src/commands/database/seed/tables.ts
  packages/cloud/src/libraries/tenants.ts
  packages/core/package.json
  packages/core/src/env-set/create-query-client.ts
  packages/core/src/env-set/index.ts
  packages/core/src/index.ts
  packages/core/src/libraries/hook.test.ts
  packages/core/src/libraries/hook.ts
  packages/core/src/middleware/koa-auth/utils.ts
  packages/core/src/model-routers/index.ts
  packages/core/src/queries/hooks.ts
  packages/core/src/routes/hook.ts
  packages/core/src/tenants/Libraries.ts
  packages/core/src/tenants/Queries.ts
  packages/core/src/tenants/Tenant.ts
  packages/core/src/tenants/TenantContext.ts
  packages/core/src/tenants/index.ts
  packages/core/src/tenants/utils.ts
  packages/core/src/test-utils/query-client.ts
  packages/core/src/test-utils/tenant.ts
  packages/core/src/utils/zod.ts
  packages/integration-tests/src/tests/api/hooks.test.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/models/hooks.ts
  packages/schemas/src/models/index.ts
  packages/schemas/src/types/hook.ts
  packages/schemas/src/types/index.ts
  packages/schemas/src/types/log/hook.ts
  packages/schemas/tables/hooks.sql
  pnpm-lock.yaml
Labels: enhancement, size/xl

#3360 feat(console): inspire me
  .github/workflows/integration-test.yml
  packages/console/src/assets/images/light-bulb.svg
  packages/console/src/components/FileUploader/index.tsx
  packages/console/src/components/RadioGroup/Radio.tsx
  packages/console/src/hooks/use-user-assets-service.ts
  packages/console/src/onboarding/components/CardSelector/CardSelector.tsx
  packages/console/src/onboarding/components/CardSelector/MultiCardSelector/index.module.scss
  packages/console/src/onboarding/components/CardSelector/MultiCardSelector/index.tsx
  packages/console/src/onboarding/components/CardSelector/index.tsx
  packages/console/src/onboarding/components/CardSelector/types.ts
  packages/console/src/onboarding/constants/index.ts
  packages/console/src/onboarding/pages/About/options.tsx
  packages/console/src/onboarding/pages/SignInExperience/components/InspireMe/index.module.scss
  packages/console/src/onboarding/pages/SignInExperience/components/InspireMe/index.tsx
  packages/console/src/onboarding/pages/SignInExperience/components/SocialSelector/index.tsx
  packages/console/src/onboarding/pages/SignInExperience/index.module.scss
  packages/console/src/onboarding/pages/SignInExperience/index.tsx
  packages/console/src/onboarding/pages/SignInExperience/options.tsx
  packages/console/src/onboarding/pages/SignInExperience/sie-config-templates.ts
  packages/console/src/onboarding/pages/SignInExperience/utils.ts
  packages/console/src/onboarding/pages/Welcome/options.tsx
  packages/console/src/onboarding/types.ts
  packages/core/src/routes/user-assets.ts
  packages/integration-tests/src/tests/ui-cloud/smoke.test.ts
  packages/phrases/src/locales/de/translation/admin-console/general.ts
  packages/phrases/src/locales/en/translation/admin-console/general.ts
  packages/phrases/src/locales/fr/translation/admin-console/general.ts
  packages/phrases/src/locales/ko/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
  packages/schemas/src/types/user-assets.ts
Labels: feature, size/xl

#3358 refactor(console): add dedicated routes to AC guides
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/Applications/components/ApplicationsPlaceholder/index.tsx
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/Applications/components/Guide/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorForm/ConfigForm.tsx
  packages/console/src/pages/Connectors/components/CreateForm/index.tsx
  packages/console/src/pages/Connectors/components/Guide/index.tsx
  packages/console/src/pages/Connectors/index.tsx
Labels: enhancement, size/xl

#3381 refactor(console): fix onboarding about page
  packages/console/src/onboarding/pages/About/index.tsx
  packages/console/src/onboarding/pages/About/options.tsx
  packages/console/src/onboarding/types.ts
  packages/phrases/src/locales/de/translation/admin-console/cloud.ts
  packages/phrases/src/locales/en/translation/admin-console/cloud.ts
  packages/phrases/src/locales/fr/translation/admin-console/cloud.ts
  packages/phrases/src/locales/ko/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/cloud.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/cloud.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/cloud.ts
Labels: enhancement, size/m

#3382 feat(console): add demo state to connectors
  packages/console/src/components/Tip/Tooltip/index.module.scss
  packages/console/src/components/Tip/Tooltip/index.tsx
  packages/console/src/consts/connectors.ts
  packages/console/src/onboarding/pages/SignInExperience/components/SocialSelector/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorDeleteButton/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorName/DemoTag.module.scss
  packages/console/src/pages/Connectors/components/ConnectorName/DemoTag.tsx
  packages/console/src/pages/Connectors/components/ConnectorName/index.module.scss
  packages/console/src/pages/Connectors/components/ConnectorName/index.tsx
  packages/console/src/pages/Connectors/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/connectors.ts
  packages/phrases/src/locales/de/translation/admin-console/general.ts
  packages/phrases/src/locales/en/translation/admin-console/connectors.ts
  packages/phrases/src/locales/en/translation/admin-console/general.ts
  packages/phrases/src/locales/fr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/fr/translation/admin-console/general.ts
  packages/phrases/src/locales/ko/translation/admin-console/connectors.ts
  packages/phrases/src/locales/ko/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/connectors.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
Labels: feature, size/m

#3369 feat(schemas,ui): add custom content slot
  .changeset-staged/smooth-steaks-cough.md
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/queries/sign-in-experience.test.ts
  packages/core/src/utils/zod.test.ts
  packages/core/src/utils/zod.ts
  packages/schemas/alterations/next-1678450233-support-custom-content.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/seeds/sign-in-experience.ts
  packages/schemas/tables/sign_in_experiences.sql
  packages/ui/src/Layout/AppLayout/CustomContent.tsx
  packages/ui/src/Layout/AppLayout/index.module.scss
  packages/ui/src/Layout/AppLayout/index.tsx
  packages/ui/src/Layout/LandingPageLayout/index.tsx
  packages/ui/src/__mocks__/logto.tsx
  packages/ui/src/hooks/use-sie.ts
  packages/ui/src/utils/consts.ts
Labels: feature, size/m

#3378 feat(console): add custom css editor debounce
  packages/console/src/pages/SignInExperience/hooks/use-preview-configs.ts
Labels: feature, size/s

#3379 refactor: fix schema types
  packages/core/src/database/find-entity-by-id.ts
  packages/core/src/database/insert-into.ts
  packages/core/src/database/update-where.ts
  packages/core/src/errors/SlonikError/index.ts
  packages/core/src/libraries/user.ts
  packages/core/src/middleware/koa-slonik-error-handler.ts
  packages/core/src/queries/application.ts
  packages/core/src/queries/connector.ts
  packages/core/src/queries/custom-phrase.ts
  packages/core/src/queries/hooks.ts
  packages/core/src/queries/log.ts
  packages/core/src/queries/oidc-model-instance.ts
  packages/core/src/queries/passcode.ts
  packages/core/src/queries/resource.test.ts
  packages/core/src/queries/resource.ts
  packages/core/src/queries/roles.test.ts
  packages/core/src/queries/roles.ts
  packages/core/src/queries/scope.ts
  packages/core/src/queries/sign-in-experience.ts
  packages/core/src/queries/user.ts
  packages/core/src/queries/verification-status.ts
  packages/core/src/utils/schema.ts
  packages/schemas/src/foundations/schemas.ts
  packages/schemas/src/gen/schema.ts
  packages/shared/src/database/utils.ts
Labels: enhancement, size/m

#3386 chore: update blog url and title
  README.md
  packages/console/src/onboarding/constants/index.ts
Labels: chore, size/xs

#3394 refactor(console): update onboarding welcome page image and description
  packages/console/src/onboarding/pages/Welcome/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/cloud.ts
  packages/phrases/src/locales/en/translation/admin-console/cloud.ts
  packages/phrases/src/locales/fr/translation/admin-console/cloud.ts
  packages/phrases/src/locales/ko/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/cloud.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/cloud.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/cloud.ts
Labels: enhancement, size/s

#3390 feat(schemas): add service logs table
  packages/core/src/tenants/utils.ts
  packages/schemas/alterations/next-1678716747-service-logs.ts
  packages/schemas/tables/_after_all.sql
  packages/schemas/tables/service_logs.sql
Labels: feature, size/s

#3387 refactor(console): add `AppThemeProvider`
  packages/console/src/components/AppError/index.tsx
  packages/console/src/components/AppLoading/Offline.tsx
  packages/console/src/components/AppLoading/index.tsx
  packages/console/src/components/ApplicationIcon/index.tsx
  packages/console/src/components/ConnectorLogo/index.tsx
  packages/console/src/components/EmptyDataPlaceholder/index.tsx
  packages/console/src/components/ImageWithErrorFallback/index.tsx
  packages/console/src/components/RequestDataError/index.tsx
  packages/console/src/components/SignInExperiencePreview/index.tsx
  packages/console/src/components/Table/TableError.tsx
  packages/console/src/components/Table/TablePlaceholder.tsx
  packages/console/src/components/ToggleThemeButton/index.tsx
  packages/console/src/components/UserAvatar/index.tsx
  packages/console/src/containers/AppBoundary/index.module.scss
  packages/console/src/containers/AppBoundary/index.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/components/Contact/hook.tsx
  packages/console/src/contexts/AppThemeProvider/index.module.scss
  packages/console/src/contexts/AppThemeProvider/index.tsx
  packages/console/src/hooks/use-theme.ts
  packages/console/src/onboarding/App.tsx
  packages/console/src/onboarding/pages/Congrats/index.tsx
  packages/console/src/onboarding/pages/SignInExperience/components/Preview/index.module.scss
  packages/console/src/onboarding/pages/SignInExperience/components/Preview/index.tsx
  packages/console/src/onboarding/pages/SignInExperience/index.tsx
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/Applications/components/SdkSelector/index.tsx
  packages/console/src/pages/GetStarted/components/GetStartedProgress/index.tsx
  packages/console/src/pages/GetStarted/hook.ts
  packages/console/src/pages/Main/index.tsx
  packages/console/src/pages/NotFound/index.tsx
  packages/console/src/pages/Profile/components/LinkAccountSection/index.tsx
  packages/console/src/pages/SignInExperience/components/Preview/index.tsx
  packages/console/src/pages/SignInExperience/components/Welcome/index.tsx
  packages/console/src/pages/Welcome/index.tsx
  packages/console/src/types/theme.ts
  packages/console/src/utils/theme.ts
Labels: enhancement, size/xl

#3395 refactor(console): add inspire me button hover background
  packages/console/src/onboarding/assets/images/fireworks.png
  packages/console/src/onboarding/pages/SignInExperience/components/InspireMe/index.module.scss
  packages/console/src/onboarding/pages/SignInExperience/components/InspireMe/index.tsx
Labels: enhancement, size/s

#3402 fix(test): remove jest-matcher-specific-error
  packages/core/src/routes/well-known.test.ts
  packages/toolkit/core-kit/jest.config.js
  packages/ui/package.json
  pnpm-lock.yaml
Labels: bugfix, size/xs

#3397 feat(cloud): init service route
  packages/cloud/src/libraries/services.ts
  packages/cloud/src/queries/application.ts
  packages/cloud/src/routes/index.ts
  packages/cloud/src/routes/service.test.ts
  packages/cloud/src/routes/services.ts
  packages/cloud/src/routes/tenants.test.ts
  packages/cloud/src/routes/tenants.ts
  packages/cloud/src/test-utils/libraries.ts
Labels: feature, size/m

#3384 refactor(console): hide error toast in language modal
  packages/console/src/hooks/use-api.ts
  packages/console/src/hooks/use-swr-fetcher.ts
  packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/LanguageDetails.tsx
Labels: enhancement, size/s

#3385 refactor(console): use in-place navigation for in-app links
  packages/console/src/components/ApplicationName/index.tsx
  packages/console/src/components/UserName/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorStatusField/index.tsx
  packages/console/src/pages/Connectors/components/SignInExperienceSetupNotice/index.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/ConnectorSetupWarning.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SocialConnectorEditBox/index.tsx
Labels: enhancement, size/s

#3398 chore: remove dirty code
  packages/console/src/components/SignInExperiencePreview/index.tsx
Labels: chore, size/xs

#3380 refactor(core): add response and status guard for hooks apis
  packages/core/src/middleware/koa-guard.test.ts
  packages/core/src/middleware/koa-guard.ts
  packages/core/src/routes/hook.ts
  packages/integration-tests/src/tests/api/hooks.test.ts
Labels: enhancement, size/m

#3383 refactor(core): optimize tenant disposal
  packages/core/src/app/init.ts
  packages/core/src/env-set/index.ts
  packages/core/src/tenants/Tenant.ts
  packages/core/src/tenants/index.ts
Labels: enhancement, size/m

#3400 refactor(core,toolkit): extract connector loading code to toolkit
  packages/cli/package.json
  packages/cli/src/connector/consts.ts
  packages/cli/src/connector/factories.ts
  packages/cli/src/connector/index.ts
  packages/cli/src/connector/loader.ts
  packages/cli/src/connector/types.ts
  packages/cli/src/connector/utils.ts
  packages/core/src/__mocks__/connector.ts
  packages/core/src/index.ts
  packages/core/src/libraries/connector.ts
  packages/core/src/libraries/passcode.test.ts
  packages/core/src/routes-me/social.ts
  packages/core/src/routes/connector.test.ts
  packages/core/src/routes/connector.ts
  packages/core/src/utils/connectors/factories.ts
  packages/core/src/utils/connectors/index.ts
  packages/core/src/utils/connectors/types.ts
  packages/phrases-ui/package.json
  packages/phrases-ui/src/index.ts
  packages/phrases/package.json
  packages/phrases/src/index.ts
  packages/toolkit/connector-kit/package.json
  packages/toolkit/core-kit/src/utils/index.ts
  packages/toolkit/core-kit/src/utils/zod.test.ts
  packages/toolkit/core-kit/src/utils/zod.ts
  packages/toolkit/language-kit/src/utility.test.ts
  packages/toolkit/language-kit/src/utility.ts
  pnpm-lock.yaml
Labels: enhancement, size/xl

#3407 style(ui): hide back CTA for root error pages
  packages/ui/src/App.tsx
  packages/ui/src/pages/ErrorPage/index.tsx
  packages/ui/src/pages/Register/index.tsx
  packages/ui/src/pages/SignIn/index.tsx
Labels: size/s

#3406 style(ui): fix secondary page spacing
  packages/ui/src/Layout/AppLayout/index.module.scss
  packages/ui/src/Layout/LandingPageLayout/index.module.scss
Labels: size/xs

#3413 refactor(console): update selector styles
  packages/console/src/components/RadioGroup/Radio.module.scss
  packages/console/src/components/RadioGroup/index.module.scss
  packages/console/src/onboarding/components/CardSelector/MultiCardSelector/index.module.scss
  packages/console/src/onboarding/pages/SignInExperience/index.module.scss
Labels: enhancement, size/s

#3410 refactor(console): use image uploader in branding form
  packages/console/src/components/FileUploader/index.tsx
  packages/console/src/components/ImageUploader/index.tsx
  packages/console/src/components/Uploader/FileUploader/index.module.scss
  packages/console/src/components/Uploader/FileUploader/index.tsx
  packages/console/src/components/Uploader/ImageUploader/index.module.scss
  packages/console/src/components/Uploader/ImageUploader/index.tsx
  packages/console/src/components/Uploader/ImageUploaderField/index.module.scss
  packages/console/src/components/Uploader/ImageUploaderField/index.tsx
  packages/console/src/components/Uploader/index.tsx
  packages/console/src/consts/user-assets.ts
  packages/console/src/onboarding/pages/SignInExperience/index.tsx
  packages/console/src/pages/SignInExperience/components/Welcome/GuideModal.tsx
  packages/console/src/pages/SignInExperience/tabs/Branding/BrandingForm.tsx
  packages/console/src/pages/SignInExperience/tabs/Branding/ColorForm.tsx
  packages/console/src/pages/SignInExperience/tabs/Branding/components/LogoAndFaviconUploader/index.module.scss
  packages/console/src/pages/SignInExperience/tabs/Branding/components/LogoAndFaviconUploader/index.tsx
  packages/console/src/pages/SignInExperience/tabs/Branding/index.tsx
  packages/console/src/pages/SignInExperience/tabs/index.module.scss
  packages/console/src/utils/uploader.ts
  packages/phrases/src/locales/de/translation/admin-console/components.ts
  packages/phrases/src/locales/de/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/en/translation/admin-console/components.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/fr/translation/admin-console/components.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/ko/translation/admin-console/components.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/components.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/components.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/components.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/components.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
Labels: enhancement, size/xl

#3388 feat(ui): implement country code selector with search box
  .changeset-staged/mighty-dodos-admire.md
  packages/phrases-ui/src/locales/de.ts
  packages/phrases-ui/src/locales/en.ts
  packages/phrases-ui/src/locales/fr.ts
  packages/phrases-ui/src/locales/ko.ts
  packages/phrases-ui/src/locales/pt-br.ts
  packages/phrases-ui/src/locales/pt-pt.ts
  packages/phrases-ui/src/locales/ru.ts
  packages/phrases-ui/src/locales/tr-tr.ts
  packages/phrases-ui/src/locales/zh-cn.ts
  packages/ui/src/assets/icons/check-mark.svg
  packages/ui/src/assets/icons/search-icon.svg
  packages/ui/src/components/ConfirmModal/AcModal.tsx
  packages/ui/src/components/InputFields/SmartInputField/CountryCodeSelector/CountryCodeDropdown/index.module.scss
  packages/ui/src/components/InputFields/SmartInputField/CountryCodeSelector/CountryCodeDropdown/index.test.tsx
  packages/ui/src/components/InputFields/SmartInputField/CountryCodeSelector/CountryCodeDropdown/index.tsx
  packages/ui/src/components/InputFields/SmartInputField/CountryCodeSelector/index.tsx
  packages/ui/src/components/InputFields/SmartInputField/index.test.tsx
  packages/ui/src/components/InputFields/SmartInputField/index.tsx
  packages/ui/src/components/InputFields/SmartInputField/use-smart-input-field.ts
  packages/ui/src/hooks/use-debounce.ts
  packages/ui/src/pages/ForgotPassword/index.test.tsx
Labels: feature, size/xl

#3347 feat(ui): implement a fullscreen iframe modal container
  .changeset-staged/good-actors-reflect.md
  .changeset-staged/mighty-dodos-admire.md
  packages/phrases-ui/src/locales/de.ts
  packages/phrases-ui/src/locales/en.ts
  packages/phrases-ui/src/locales/fr.ts
  packages/phrases-ui/src/locales/ko.ts
  packages/phrases-ui/src/locales/pt-br.ts
  packages/phrases-ui/src/locales/pt-pt.ts
  packages/phrases-ui/src/locales/ru.ts
  packages/phrases-ui/src/locales/tr-tr.ts
  packages/phrases-ui/src/locales/zh-cn.ts
  packages/ui/package.json
  packages/ui/src/Providers/AppBoundary/index.tsx
  packages/ui/src/Providers/IframeModalProvider/IframeModal/index.module.scss
  packages/ui/src/Providers/IframeModalProvider/IframeModal/index.tsx
  packages/ui/src/Providers/IframeModalProvider/index.tsx
  packages/ui/src/assets/icons/check-mark.svg
  packages/ui/src/assets/icons/search-icon.svg
  packages/ui/src/components/ConfirmModal/AcModal.tsx
  packages/ui/src/components/InputFields/SmartInputField/CountryCodeSelector/CountryCodeDropdown/index.module.scss
  packages/ui/src/components/InputFields/SmartInputField/CountryCodeSelector/CountryCodeDropdown/index.test.tsx
  packages/ui/src/components/InputFields/SmartInputField/CountryCodeSelector/CountryCodeDropdown/index.tsx
  packages/ui/src/components/InputFields/SmartInputField/CountryCodeSelector/index.tsx
  packages/ui/src/components/InputFields/SmartInputField/index.test.tsx
  packages/ui/src/components/InputFields/SmartInputField/index.tsx
  packages/ui/src/components/InputFields/SmartInputField/use-smart-input-field.ts
  packages/ui/src/components/NavBar/index.tsx
  packages/ui/src/components/TermsLinks/index.tsx
  packages/ui/src/components/TextLink/index.tsx
  packages/ui/src/hooks/use-debounce.ts
  packages/ui/src/pages/ForgotPassword/index.test.tsx
  pnpm-lock.yaml
Labels: feature, size/xl

#3405 feat(cloud): send email
  .changeset-staged/real-carpets-wait.md
  packages/cli/package.json
  packages/cloud/package.json
  packages/cloud/src/index.ts
  packages/cloud/src/libraries/services.ts
  packages/cloud/src/queries/connector.ts
  packages/cloud/src/queries/index.ts
  packages/cloud/src/routes/service.test.ts
  packages/cloud/src/routes/services.ts
  packages/cloud/src/test-utils/libraries.ts
  packages/cloud/src/utils/connector/index.ts
  packages/cloud/src/utils/connector/types.ts
  packages/toolkit/connector-kit/src/types.ts
  pnpm-lock.yaml
Labels: feature, size/m

#3414 feat(cli,core,shared): install demo connectors only in cloud
  .scripts/package.sh
  packages/cli/src/commands/connector/add.ts
  packages/cli/src/commands/connector/utils.ts
  packages/core/src/routes/connector.ts
  packages/shared/src/models/connector.ts
  packages/shared/src/models/index.ts
Labels: feature, size/s

#3418 feat(cloud): limit control for send email
  packages/cloud/src/libraries/services.ts
  packages/cloud/src/queries/index.ts
  packages/cloud/src/queries/service-logs.ts
  packages/cloud/src/routes/service.test.ts
  packages/cloud/src/routes/services.ts
  packages/cloud/src/test-utils/libraries.ts
  packages/schemas/src/types/index.ts
  packages/schemas/src/types/service-log.ts
Labels: feature, size/m

#3422 feat(cloud): add demo connector configs on tenant create
  packages/cloud/src/libraries/tenants.ts
  packages/cloud/src/queries/connector.ts
  packages/cloud/src/queries/service-logs.ts
  packages/core/src/routes/connector.ts
  packages/shared/src/models/connector.ts
Labels: feature, size/s

#3403 chore: send testing sms/email using Generic template type
  packages/core/src/routes/connector.test.ts
  packages/core/src/routes/connector.ts
  packages/toolkit/connector-kit/src/types.ts
Labels: chore, size/xs

#3391 refactor: support setting pool sizes by env variable
  .github/workflows/release.yml
  packages/core/src/env-set/create-pool.ts
  packages/core/src/env-set/index.ts
  packages/core/src/libraries/hook.ts
  packages/core/src/tenants/index.ts
  packages/shared/src/env/GlobalValues.ts
Labels: enhancement, size/m

#3409 style(ui): update ui main card style
  packages/ui/src/Layout/AppLayout/index.module.scss
  packages/ui/src/Layout/AppLayout/index.tsx
  packages/ui/src/components/LogtoSignature/index.module.scss
Labels: size/s

#3423 refactor(console): update logto logo
  packages/console/src/assets/images/logo.svg
  packages/console/src/containers/AppContent/components/Topbar/index.module.scss
  packages/console/src/onboarding/components/Topbar/index.module.scss
Labels: enhancement, size/s

#3425 feat(core,console): display demo connectors
  packages/cloud/src/libraries/tenants.ts
  packages/console/src/consts/connectors.ts
  packages/console/src/pages/Connectors/components/ConnectorName/index.tsx
  packages/console/src/pages/Connectors/components/CreateForm/index.tsx
  packages/console/src/pages/Connectors/index.tsx
  packages/console/src/pages/Connectors/utils/index.ts
  packages/console/src/types/connector.ts
  packages/core/src/routes/connector.ts
  packages/core/src/utils/connectors/index.ts
  packages/schemas/src/types/connector.ts
  packages/shared/src/models/connector.ts
Labels: feature, size/s

#3396 chore: update custom css content and add placeholder in code editor
  packages/console/src/pages/SignInExperience/index.tsx
  packages/console/src/pages/SignInExperience/types.ts
  packages/console/src/pages/SignInExperience/utils/form.ts
  packages/phrases/src/locales/de/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
Labels: chore, size/s

#3426 ci: add cloud connectors when build for dev
  .github/workflows/release.yml
  Dockerfile
Labels: size/xs

#3427 ci: fix core dev build
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: size/xs

#3429 chore: update custom css render delay to 400ms
  packages/console/src/pages/SignInExperience/hooks/use-preview-configs.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
Labels: chore, size/xs

#3428 fix: install connector in cloud dockerfile
  Dockerfile.cloud
Labels: bugfix, size/xs

#3431 fix(ui): added search + hash string interpolation
  packages/ui/src/hooks/use-social-callback-handler.ts
Labels: bugfix, size/s

#3420 fix(console): hide the demo_app phrases in ac
  packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/LanguageDetails.tsx
Labels: bugfix, size/xs

#3424 feat(console): add rbac related learn more links
  packages/console/src/components/CardTitle/index.module.scss
  packages/console/src/components/CardTitle/index.tsx
  packages/console/src/components/ModalLayout/index.tsx
  packages/console/src/onboarding/components/EarlyBirdGift/GiftModal/index.tsx
  packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx
  packages/console/src/pages/RoleDetails/RolePermissions/components/AssignPermissionsModal/index.tsx
  packages/console/src/pages/RoleDetails/RoleSettings/index.tsx
  packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
  packages/console/src/pages/Roles/index.tsx
Labels: feature, size/s

#3399 fix(console): fix preview post message error
  packages/console/src/components/SignInExperiencePreview/index.tsx
Labels: bugfix, size/s

#3433 style(ui): ui styling optimization
  packages/phrases-ui/src/locales/de.ts
  packages/phrases-ui/src/locales/en.ts
  packages/phrases-ui/src/locales/fr.ts
  packages/phrases-ui/src/locales/ko.ts
  packages/phrases-ui/src/locales/pt-br.ts
  packages/phrases-ui/src/locales/pt-pt.ts
  packages/phrases-ui/src/locales/ru.ts
  packages/phrases-ui/src/locales/tr-tr.ts
  packages/phrases-ui/src/locales/zh-cn.ts
  packages/ui/src/components/InputFields/SmartInputField/CountryCodeSelector/CountryCodeDropdown/index.module.scss
  packages/ui/src/hooks/use-error-handler.ts
  packages/ui/src/pages/Consent/index.module.scss
  packages/ui/src/pages/Consent/index.tsx
Labels: size/s

#3419 refactor(console): refactor theme-related types
  packages/console/src/components/AppError/index.tsx
  packages/console/src/components/AppLoading/Offline.tsx
  packages/console/src/components/AppLoading/index.tsx
  packages/console/src/components/ApplicationIcon/index.tsx
  packages/console/src/components/ConnectorLogo/index.tsx
  packages/console/src/components/EmptyDataPlaceholder/index.tsx
  packages/console/src/components/ImageWithErrorFallback/index.tsx
  packages/console/src/components/RequestDataError/index.tsx
  packages/console/src/components/SignInExperiencePreview/components/ToggleUiThemeButton/index.module.scss
  packages/console/src/components/SignInExperiencePreview/components/ToggleUiThemeButton/index.tsx
  packages/console/src/components/SignInExperiencePreview/index.tsx
  packages/console/src/components/Table/TableError.tsx
  packages/console/src/components/Table/TablePlaceholder.tsx
  packages/console/src/components/UserAvatar/index.tsx
  packages/console/src/consts/index.ts
  packages/console/src/containers/AppContent/components/UserInfo/index.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/components/Contact/hook.tsx
  packages/console/src/contexts/AppThemeProvider/index.tsx
  packages/console/src/hooks/use-theme.ts
  packages/console/src/hooks/use-user-preferences.ts
  packages/console/src/onboarding/App.tsx
  packages/console/src/onboarding/pages/SignInExperience/components/Preview/index.tsx
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/Applications/components/SdkSelector/index.tsx
  packages/console/src/pages/GetStarted/components/GetStartedProgress/index.tsx
  packages/console/src/pages/GetStarted/hook.ts
  packages/console/src/pages/NotFound/index.tsx
  packages/console/src/pages/Profile/components/LinkAccountSection/index.tsx
  packages/console/src/pages/SignInExperience/components/Preview/index.tsx
  packages/console/src/pages/SignInExperience/components/Welcome/index.tsx
  packages/console/src/pages/Welcome/index.tsx
  packages/console/src/types/appearance-mode.ts
  packages/console/src/types/theme.ts
  packages/console/src/utils/theme.ts
  packages/schemas/alterations/next-1678928481-remove-deprecated-logto-config-item.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/seeds/logto-config.ts
  packages/schemas/src/types/index.ts
  packages/schemas/src/types/theme.ts
  packages/ui/src/components/LogtoSignature/index.tsx
  packages/ui/src/containers/SocialLanding/index.tsx
  packages/ui/src/hooks/use-color-theme.ts
  packages/ui/src/hooks/use-page-context.ts
  packages/ui/src/hooks/use-theme.ts
  packages/ui/src/pages/ErrorPage/index.tsx
  packages/ui/src/types/index.ts
  packages/ui/src/utils/logo.ts
Labels: enhancement, size/l
