Repository logto-io/logto, pull requests merged in 2023-05, with the labels that each got.

#3789 test(core): add api response guard and error case tests to dashboard api
  packages/core/src/routes/dashboard.ts
  packages/integration-tests/src/tests/api/dashboard.test.ts
  packages/schemas/src/types/dashboard.ts
  packages/schemas/src/types/index.ts
Labels: testing, size/m

#3798 chore: delete root CHANGELOG
  CHANGELOG.md
Labels: chore, size/xl

#3804 chore(core): remove legacy commented code
  packages/core/src/routes/authn.test.ts
Labels: chore, size/xs

#3805 fix(console): fix the back link of the log details page
  packages/console/src/pages/AuditLogDetails/index.tsx
Labels: bugfix, size/xs

#3801 refactor(core): add response schemas to swagger.json API
  .changeset/flat-rivers-press.md
  packages/core/package.json
  packages/core/src/middleware/koa-guard.ts
  packages/core/src/routes/swagger.test.ts
  packages/core/src/routes/swagger.ts
  packages/core/src/utils/http.ts
  packages/core/src/utils/zod.ts
  packages/core/static/yaml/additional-swagger.yaml
  pnpm-lock.yaml
Labels: enhancement, size/l

#3810 fix(core): fix unpaginated scopes response
  packages/core/src/__mocks__/index.ts
  packages/core/src/routes/role.scope.test.ts
  packages/core/src/routes/role.scope.ts
  packages/schemas/src/types/scope.ts
Labels: bugfix, size/s

#3811 fix(console): trim trailing spaces in app guide code sample
  packages/console/src/pages/Applications/components/Guide/index.tsx
Labels: bugfix, size/xs

#3769 chore: add response guard and integration test for .well-known api
  packages/core/src/routes/well-known.ts
  packages/integration-tests/src/tests/api/well-known.test.ts
Labels: chore, size/s

#3802 test(core): add exception cases for role api and scope api
  packages/console/src/pages/Profile/components/LinkAccountSection/index.tsx
  packages/core/src/routes/dashboard.ts
  packages/core/src/routes/role.scope.ts
  packages/core/src/routes/role.ts
  packages/core/src/utils/http.ts
  packages/integration-tests/src/tests/api/role.scope.test.ts
  packages/integration-tests/src/tests/api/role.test.ts
  packages/integration-tests/src/tests/api/role.user.test.ts
  packages/schemas/src/types/user.ts
Labels: testing, size/l

#3808 refactor(console): remove superstruct dependency from console
  packages/console/package.json
  packages/console/src/pages/Profile/containers/LinkEmailModal/index.tsx
  packages/console/src/pages/Profile/containers/VerificationCodeModal/index.tsx
  packages/console/src/pages/Profile/containers/VerifyPasswordModal/index.tsx
  packages/console/src/pages/Profile/utils.ts
  packages/console/src/types/profile.ts
  pnpm-lock.yaml
Labels: enhancement, size/s

#3806 test(core): add api response guard and error case tests to connector api
  packages/core/src/routes/connector/index.ts
  packages/integration-tests/src/tests/api/connector.test.ts
  packages/schemas/src/types/connector.ts
Labels: testing, size/m

#3809 test(core): add api response guard and error case tests to admin user
  packages/core/src/routes-me/user.ts
  packages/core/src/routes/admin-user-search.test.ts
  packages/core/src/routes/admin-user-search.ts
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/role.ts
  packages/integration-tests/src/tests/api/admin-user.roles.test.ts
  packages/integration-tests/src/tests/api/admin-user.test.ts
  packages/schemas/src/types/user.ts
Labels: testing, size/l

#3812 fix(core): use correct status code for slonik errors
  packages/core/src/middleware/koa-slonik-error-handler.test.ts
  packages/core/src/middleware/koa-slonik-error-handler.ts
Labels: bugfix, size/xs

#3771 chore: add response guard and integration tests for application APIs
  packages/core/src/routes/application.test.ts
  packages/core/src/routes/application.ts
  packages/integration-tests/src/api/application.ts
  packages/integration-tests/src/tests/api/application.test.ts
Labels: chore, size/s

#3765 chore(test): update connector integration tests
  packages/integration-tests/src/__mocks__/connectors-mock.ts
  packages/integration-tests/src/api/connector.ts
  packages/integration-tests/src/helpers/connector.ts
  packages/integration-tests/src/tests/api/admin-user.test.ts
  packages/integration-tests/src/tests/api/connector.test.ts
Labels: chore, size/m

#3813 chore(core,test): add status code guard for SIE, custom phrase and config APIs
  packages/core/src/routes/custom-phrase.test.ts
  packages/core/src/routes/custom-phrase.ts
  packages/core/src/routes/logto-config.ts
  packages/core/src/routes/sign-in-experience/index.ts
  packages/integration-tests/src/tests/api/custom-phrase.test.ts
  packages/integration-tests/src/tests/api/sign-in-experience.test.ts
Labels: chore, size/s

#3807 test(core): add api response guard and error case tests to log api
  packages/core/src/routes/log.ts
  packages/integration-tests/src/tests/api/log.test.ts
Labels: testing, size/s

#3816 chore: bump caniuse-lite version
  pnpm-lock.yaml
Labels: chore, size/xs

#3818 fix(console): main content should take 100% available height
  packages/console/src/containers/ConsoleContent/index.module.scss
Labels: bugfix, size/xs

#3788 refactor(schemas): update hook schema
  packages/core/src/libraries/hook.test.ts
  packages/core/src/libraries/hook.ts
  packages/integration-tests/src/tests/api/hooks.test.ts
  packages/schemas/alterations/next-1683292832-update-hooks.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/tables/hooks.sql
Labels: enhancement, size/m

#3790 feat(console): list and create webhooks
  packages/console/src/assets/images/hook.svg
  packages/console/src/assets/images/webhook-dark.svg
  packages/console/src/assets/images/webhook.svg
  packages/console/src/assets/images/webhooks-empty-dark.svg
  packages/console/src/assets/images/webhooks-empty.svg
  packages/console/src/components/Table/TablePlaceholder.module.scss
  packages/console/src/consts/webhooks.ts
  packages/console/src/containers/ConsoleContent/Sidebar/hook.tsx
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/pages/Webhooks/components/CreateFormModal/CreateForm.module.scss
  packages/console/src/pages/Webhooks/components/CreateFormModal/CreateForm.tsx
  packages/console/src/pages/Webhooks/components/CreateFormModal/index.tsx
  packages/console/src/pages/Webhooks/index.module.scss
  packages/console/src/pages/Webhooks/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/general.ts
  packages/phrases/src/locales/en/translation/admin-console/general.ts
  packages/phrases/src/locales/es/translation/admin-console/general.ts
  packages/phrases/src/locales/fr/translation/admin-console/general.ts
  packages/phrases/src/locales/it/translation/admin-console/general.ts
  packages/phrases/src/locales/ja/translation/admin-console/general.ts
  packages/phrases/src/locales/ko/translation/admin-console/general.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
  packages/phrases/src/locales/ru/translation/admin-console/general.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/general.ts
Labels: feature, size/xl

#3820 feat(console): implement webhook basic details page
  packages/console/src/consts/page-tabs.ts
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/pages/WebhookDetails/WebhookSettings/index.tsx
  packages/console/src/pages/WebhookDetails/index.module.scss
  packages/console/src/pages/WebhookDetails/index.tsx
  packages/console/src/pages/WebhookDetails/types.ts
  packages/console/src/pages/WebhookDetails/utils.ts
  packages/console/src/pages/Webhooks/components/BasicWebhookForm/index.module.scss
  packages/console/src/pages/Webhooks/components/BasicWebhookForm/index.tsx
  packages/console/src/pages/Webhooks/components/CreateFormModal/CreateForm.tsx
  packages/console/src/pages/Webhooks/types.ts
Labels: feature, size/xl

#3823 feat(console): support editing webhook custom headers in the console
  packages/console/src/pages/WebhookDetails/WebhookSettings/components/CustomHeaderField/index.module.scss
  packages/console/src/pages/WebhookDetails/WebhookSettings/components/CustomHeaderField/index.tsx
  packages/console/src/pages/WebhookDetails/WebhookSettings/index.tsx
  packages/console/src/pages/WebhookDetails/types.ts
  packages/console/src/pages/WebhookDetails/utils.ts
  packages/phrases/src/locales/de/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/en/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/es/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/it/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/webhook-details.ts
Labels: feature, size/m

#3826 fix(schemas): add non-empty string type guard
  .changeset/smooth-icons-fetch.md
  packages/integration-tests/src/tests/api/resource.scope.test.ts
  packages/schemas/src/gen/schema.ts
Labels: bugfix, size/s

#3825 test(core): add api response guard and error case tests for verification code
  packages/core/src/routes/verification-code.ts
  packages/integration-tests/src/api/verification-code.ts
  packages/integration-tests/src/tests/api/verification-code.test.ts
Labels: testing, size/s

#3830 chore(core): update custom phrase PUT API response status
  packages/core/src/routes/custom-phrase.test.ts
  packages/core/src/routes/custom-phrase.ts
Labels: chore, size/xs

#3836 chore: fixed typo README.md
  README.md
Labels: chore, size/xs

#3838 chore: update README.md
  README.md
Labels: chore, size/s

#3829 test(core): add integration test for application isAdmin
  packages/core/src/routes/application.ts
  packages/integration-tests/src/api/application.ts
  packages/integration-tests/src/tests/api/application.test.ts
Labels: testing, size/s

#3834 fix(core): compatibility for `retries` field in HookConfig
  packages/console/src/pages/WebhookDetails/utils.ts
  packages/core/src/libraries/hook.test.ts
  packages/core/src/libraries/hook.ts
  packages/integration-tests/src/tests/api/hooks.test.ts
  packages/schemas/src/foundations/jsonb-types.ts
Labels: bugfix, size/s

#3831 feat(core): add 401,403 status guard to all management api routes
  packages/core/src/middleware/koa-auth/index.ts
  packages/core/src/routes/role.scope.ts
  packages/core/src/routes/swagger.ts
Labels: feature, size/s

#3843 refactor(core): add guards for authn routes
  packages/core/src/routes/authn.ts
Labels: enhancement, size/s

#3844 fix(schemas): remove the notnull string min-length guard from response type
  packages/integration-tests/src/tests/api/application.test.ts
  packages/schemas/src/gen/schema.ts
Labels: bugfix, size/s

#3821 feat(core): add management APIs to help with linking social identities to user
  .changeset/nice-monkeys-hope.md
  packages/core/src/routes/admin-user-social.test.ts
  packages/core/src/routes/admin-user-social.ts
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
  packages/core/src/routes/connector/authorization-uri.test.ts
  packages/core/src/routes/connector/authorization-uri.ts
  packages/core/src/routes/connector/index.ts
  packages/core/src/routes/init.ts
  packages/integration-tests/src/api/admin-user.ts
  packages/integration-tests/src/api/connector.ts
  packages/integration-tests/src/tests/api/admin-user.test.ts
Labels: feature, size/xl

#3842 fix(ui): set tabIndex -1 for hidden countryCode
  packages/ui/src/components/InputFields/SmartInputField/AnimatedPrefix/index.tsx
  packages/ui/src/components/InputFields/SmartInputField/CountryCodeSelector/index.tsx
Labels: bugfix, size/xs

#3845 chore(console): add app insights for webhook pages
  packages/console/src/pages/WebhookDetails/index.tsx
  packages/console/src/pages/Webhooks/index.tsx
Labels: chore, size/xs

#3847 chore(cli): lock logto schemas version
  packages/cli/package.json
  pnpm-lock.yaml
Labels: chore, size/xs

#3848 ci: update release workflow
  .github/workflows/release.yml
Labels: size/xs

#3851 chore(phrases): add webhook creation blocker description
  packages/phrases/src/locales/de/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/en/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/es/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/fr/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/it/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/ja/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/ko/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/ru/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/webhooks.ts
Labels: chore, size/s

#3850 refactor(schemas,core): enable min string length guard
  packages/schemas/src/gen/schema.ts
  packages/schemas/src/seeds/application.ts
Labels: enhancement, size/xs

#3853 feat(console): implement tag component
  packages/console/src/components/Status/index.module.scss
  packages/console/src/components/Status/index.tsx
  packages/console/src/components/Tag/index.module.scss
  packages/console/src/components/Tag/index.tsx
  packages/console/src/pages/ApplicationDetails/index.module.scss
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/ConnectorDetails/components/ConnectorTypeName/index.module.scss
  packages/console/src/pages/ConnectorDetails/components/ConnectorTypeName/index.tsx
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorName/DemoTag.tsx
  packages/console/src/pages/Connectors/components/ConnectorStatus/index.tsx
  packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/LanguageDetails.module.scss
  packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/LanguageDetails.tsx
  packages/console/src/pages/Users/components/SuspendedTag/index.module.scss
  packages/console/src/pages/Users/components/SuspendedTag/index.tsx
  packages/console/src/pages/WebhookDetails/index.tsx
  packages/toolkit/core-kit/scss/_console-themes.scss
Labels: feature, size/l

#3773 chore(core): add response guard for user roles APIs
  packages/core/src/routes/admin-user-role.ts
Labels: chore, size/s

#3849 refactor(core): remove the reportOnly flag
  .changeset/cool-oranges-cheer.md
  packages/cloud/src/middleware/with-security-headers.ts
  packages/core/src/middleware/koa-security-headers.ts
Labels: enhancement, size/s

#3856 chore: update README.md
  README.md
Labels: chore, size/xs

#3855 test: remove tests with defaultManagementApi.role.id
  packages/integration-tests/src/tests/api/admin-user.roles.test.ts
Labels: testing, size/s

#3852 feat(console): add webhook creation limit reminder
  packages/console/src/consts/external-links.ts
  packages/console/src/onboarding/constants/index.ts
  packages/console/src/pages/Profile/containers/DeleteAccountModal/index.tsx
  packages/console/src/pages/Webhooks/components/CreateFormModal/index.tsx
  packages/console/src/pages/Webhooks/index.tsx
  packages/shared/src/constants.ts
  packages/shared/src/universal.ts
Labels: feature, size/s

#3828 feat(console,phrases): add support to update sign-in identifiers in user details form
  .changeset/three-terms-confess.md
  packages/console/package.json
  packages/console/src/pages/UserDetails/UserSettings/index.tsx
  packages/console/src/pages/UserDetails/utils.ts
  packages/console/src/pages/Users/components/CreateForm/index.tsx
  packages/console/src/utils/json.ts
  packages/console/src/utils/phone.ts
  packages/console/src/utils/user.ts
  packages/phrases/src/locales/de/translation/admin-console/user-details.ts
  packages/phrases/src/locales/de/translation/admin-console/users.ts
  packages/phrases/src/locales/en/translation/admin-console/user-details.ts
  packages/phrases/src/locales/en/translation/admin-console/users.ts
  packages/phrases/src/locales/es/translation/admin-console/user-details.ts
  packages/phrases/src/locales/es/translation/admin-console/users.ts
  packages/phrases/src/locales/fr/translation/admin-console/user-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/users.ts
  packages/phrases/src/locales/it/translation/admin-console/user-details.ts
  packages/phrases/src/locales/it/translation/admin-console/users.ts
  packages/phrases/src/locales/ja/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/users.ts
  packages/phrases/src/locales/ko/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/users.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/users.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/users.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/users.ts
  packages/phrases/src/locales/ru/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/users.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/user-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/users.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/users.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/users.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/users.ts
  packages/schemas/src/foundations/jsonb-types.ts
  pnpm-lock.yaml
Labels: feature, size/l

#3864 fix: use only necessary domains in CSP
  packages/cloud/src/middleware/with-security-headers.ts
  packages/core/src/middleware/koa-security-headers.ts
Labels: bugfix, size/s

#3858 refactor: disable pkce requirement for traditional app
  packages/cli/CHANGELOG.md
  packages/cli/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/core/src/oidc/init.ts
  packages/create/CHANGELOG.md
  packages/create/package.json
  packages/schemas/CHANGELOG.md
  packages/schemas/package.json
  pnpm-lock.yaml
Labels: enhancement, feature, size/s

#3868 fix(schemas): guard string length for default value field
  packages/schemas/src/gen/schema.ts
Labels: bugfix, size/xs

#3819 refactor: update webhook API
  packages/core/src/__mocks__/hook.ts
  packages/core/src/libraries/hook.ts
  packages/core/src/routes/hook.test.ts
  packages/core/src/routes/hook.ts
  packages/core/src/utils/zod.ts
  packages/integration-tests/src/tests/api/hooks.test.ts
  packages/phrases/src/locales/de/errors/hook.ts
  packages/phrases/src/locales/de/errors/index.ts
  packages/phrases/src/locales/en/errors/hook.ts
  packages/phrases/src/locales/en/errors/index.ts
  packages/phrases/src/locales/es/errors/hook.ts
  packages/phrases/src/locales/es/errors/index.ts
  packages/phrases/src/locales/fr/errors/hook.ts
  packages/phrases/src/locales/fr/errors/index.ts
  packages/phrases/src/locales/it/errors/hook.ts
  packages/phrases/src/locales/it/errors/index.ts
  packages/phrases/src/locales/ja/errors/hook.ts
  packages/phrases/src/locales/ja/errors/index.ts
  packages/phrases/src/locales/ko/errors/hook.ts
  packages/phrases/src/locales/ko/errors/index.ts
  packages/phrases/src/locales/pl-pl/errors/hook.ts
  packages/phrases/src/locales/pl-pl/errors/index.ts
  packages/phrases/src/locales/pt-br/errors/hook.ts
  packages/phrases/src/locales/pt-br/errors/index.ts
  packages/phrases/src/locales/pt-pt/errors/hook.ts
  packages/phrases/src/locales/pt-pt/errors/index.ts
  packages/phrases/src/locales/ru/errors/hook.ts
  packages/phrases/src/locales/ru/errors/index.ts
  packages/phrases/src/locales/tr-tr/errors/hook.ts
  packages/phrases/src/locales/tr-tr/errors/index.ts
  packages/phrases/src/locales/zh-cn/errors/hook.ts
  packages/phrases/src/locales/zh-cn/errors/index.ts
  packages/phrases/src/locales/zh-hk/errors/hook.ts
  packages/phrases/src/locales/zh-hk/errors/index.ts
  packages/phrases/src/locales/zh-tw/errors/hook.ts
  packages/phrases/src/locales/zh-tw/errors/index.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/types/hook.ts
Labels: enhancement, size/xl

#3866 feat(console): regenerate signing key
  packages/console/src/assets/images/redo.svg
  packages/console/src/pages/WebhookDetails/WebhookSettings/components/SigningKeyField/index.module.scss
  packages/console/src/pages/WebhookDetails/WebhookSettings/components/SigningKeyField/index.tsx
  packages/console/src/pages/WebhookDetails/WebhookSettings/index.tsx
Labels: feature, size/m

#3869 chore: remove uffizzi configs
  docker-compose.demo.uffizzi.yml
  docker-compose.uffizzi.yml
Labels: chore, size/s

#3863 test(test): add tests for console user management
  packages/integration-tests/jest.config.ui.js
  packages/integration-tests/package.json
  packages/integration-tests/src/constants.ts
  packages/integration-tests/src/tests/api/admin-user.test.ts
  packages/integration-tests/src/tests/ui/bootstrap.test.ts
  packages/integration-tests/src/tests/ui/user-management.test.ts
  packages/integration-tests/src/utils.ts
  packages/integration-tests/ui-test-sequencer.js
  packages/integration-tests/user-conflict-email.png
  pnpm-lock.yaml
Labels: testing, size/l

#3859 feat(core,schemas): support get hook recent logs
  packages/core/src/queries/log.ts
  packages/core/src/routes/hook.test.ts
  packages/core/src/routes/hook.ts
  packages/integration-tests/src/tests/api/hooks.test.ts
  packages/schemas/alterations/next-1684739802-create-hook-id-index-for-logs.ts
  packages/schemas/tables/logs.sql
Labels: feature, size/m

#3873 refactor(core): sync social email and phone for new registered user
  .changeset/perfect-hairs-marry.md
  packages/core/src/routes/interaction/actions/submit-interaction.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/integration-tests/src/tests/api/interaction/social-interaction.test.ts
  packages/integration-tests/src/tests/api/oidc/content-type-json.test.ts
Labels: enhancement, size/m

#3860 feat(schemas): update tenants table schema
  packages/schemas/alterations/next-1684382842-add-name-tag-created-at-for-tenants-table.ts
  packages/schemas/src/models/tenants.ts
  packages/schemas/src/seeds/tenant.ts
  packages/schemas/src/types/tenant.ts
  packages/schemas/tables/_after_all.sql
  packages/schemas/tables/_functions.sql
Labels: feature, size/s

#3861 feat(console): add hover tooltip for micro user avatars
  packages/console/src/components/RoleUsersTransfer/components/SourceUserItem/index.tsx
  packages/console/src/components/RoleUsersTransfer/components/TargetUserItem/index.tsx
  packages/console/src/components/Tip/TipBubble/index.module.scss
  packages/console/src/components/UserAvatar/index.module.scss
  packages/console/src/components/UserAvatar/index.tsx
  packages/console/src/components/UserName/index.module.scss
  packages/console/src/components/UserName/index.tsx
  packages/console/src/pages/AuditLogDetails/index.tsx
  packages/console/src/pages/RoleDetails/RoleUsers/index.tsx
  packages/console/src/pages/UserDetails/UserRoles/components/AssignRolesModal/index.tsx
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/pages/Users/index.tsx
  packages/console/src/utils/user.ts
Labels: feature, size/m

#3854 feat(core): sign hook payload data
  packages/core/src/libraries/hook.test.ts
  packages/core/src/libraries/hook.ts
  packages/core/src/utils/sign.test.ts
  packages/core/src/utils/sign.ts
  packages/integration-tests/src/helpers/index.ts
  packages/integration-tests/src/tests/api/hooks.test.ts
Labels: feature, size/m

#3879 feat: updates for openai plugins
  packages/cli/CHANGELOG.md
  packages/cli/package.json
  packages/cli/src/commands/translate/sync.ts
  packages/console/CHANGELOG.md
  packages/console/package.json
  packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/core/src/oidc/init.ts
  packages/core/src/routes/interaction/actions/submit-interaction.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/create/CHANGELOG.md
  packages/create/package.json
  packages/integration-tests/CHANGELOG.md
  packages/integration-tests/package.json
  packages/integration-tests/src/api/application.ts
  packages/integration-tests/src/tests/api/interaction/social-interaction.test.ts
  packages/integration-tests/src/tests/api/oidc/always-issue-refresh-token.test.ts
  packages/integration-tests/src/tests/api/oidc/content-type-json.test.ts
  packages/integration-tests/src/tests/api/oidc/get-access-token.test.ts
  packages/phrases/CHANGELOG.md
  packages/phrases/package.json
  packages/phrases/src/locales/de/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/es/translation/admin-console/application-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/it/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/application-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts
  packages/schemas/CHANGELOG.md
  packages/schemas/package.json
  packages/schemas/src/foundations/jsonb-types.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#3882 feat(core): get hook execution stats
  packages/core/src/libraries/hook.test.ts
  packages/core/src/libraries/hook.ts
  packages/core/src/queries/log.ts
  packages/core/src/routes/hook.test.ts
  packages/core/src/routes/hook.ts
  packages/integration-tests/src/tests/api/hooks.test.ts
  packages/schemas/src/types/hook.ts
Labels: feature, size/m

#3885 style(console): sidebar item should align to top
  packages/console/src/containers/ConsoleContent/Sidebar/index.module.scss
Labels: size/xs

#3887 chore(phrases): add send test payload error phrases
  packages/phrases/src/locales/de/errors/hook.ts
  packages/phrases/src/locales/en/errors/hook.ts
  packages/phrases/src/locales/es/errors/hook.ts
  packages/phrases/src/locales/fr/errors/hook.ts
  packages/phrases/src/locales/it/errors/hook.ts
  packages/phrases/src/locales/ja/errors/hook.ts
  packages/phrases/src/locales/ko/errors/hook.ts
  packages/phrases/src/locales/pl-pl/errors/hook.ts
  packages/phrases/src/locales/pt-br/errors/hook.ts
  packages/phrases/src/locales/pt-pt/errors/hook.ts
  packages/phrases/src/locales/ru/errors/hook.ts
  packages/phrases/src/locales/tr-tr/errors/hook.ts
  packages/phrases/src/locales/zh-cn/errors/hook.ts
  packages/phrases/src/locales/zh-hk/errors/hook.ts
  packages/phrases/src/locales/zh-tw/errors/hook.ts
Labels: chore, size/s

#3897 fix(console): hide success rate on the hook details page when no request happened
  packages/console/src/pages/WebhookDetails/index.tsx
Labels: bugfix, size/s

#3898 fix(console): refresh hook on data updated
  packages/console/src/pages/WebhookDetails/index.tsx
Labels: bugfix, size/xs

#3871 chore: update Dockerfile to support custom command
  Dockerfile
Labels: chore, size/xs

#3889 feat(core): test webhook
  packages/core/src/libraries/hook/index.test.ts
  packages/core/src/libraries/hook/index.ts
  packages/core/src/libraries/hook/utils.test.ts
  packages/core/src/libraries/hook/utils.ts
  packages/core/src/routes/hook.test.ts
  packages/core/src/routes/hook.ts
  packages/core/src/tenants/Libraries.ts
  packages/integration-tests/src/tests/api/hook/hook.testing.test.ts
Labels: feature, size/l

#3886 feat(console): test webhook
  packages/console/src/pages/WebhookDetails/WebhookSettings/components/TestWebhook/index.module.scss
  packages/console/src/pages/WebhookDetails/WebhookSettings/components/TestWebhook/index.tsx
  packages/console/src/pages/WebhookDetails/WebhookSettings/index.tsx
Labels: feature, size/s

#3901 feat(console): enable webhook management feature
  packages/console/src/containers/ConsoleContent/Sidebar/hook.tsx
  packages/console/src/containers/ConsoleContent/index.tsx
Labels: feature, size/s

#3903 refactor(console): remove webhook creation limit
  packages/console/src/pages/Webhooks/components/CreateFormModal/index.tsx
  packages/console/src/pages/Webhooks/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/en/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/es/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/fr/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/it/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/ja/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/ko/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/ru/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/webhooks.ts
  packages/shared/src/constants.ts
  packages/shared/src/universal.ts
Labels: enhancement, size/s

#3907 chore(test): clean up created hooks on test done
  packages/integration-tests/src/tests/api/hook/hook.testing.test.ts
Labels: chore, size/xs

#3906 refactor(console): replace confirm modal with useConfirmModal hook
  packages/console/src/pages/WebhookDetails/index.tsx
Labels: enhancement, size/s

#3902 feat(schemas): add cloudflare hostnames configs
  .changeset/famous-tips-search.md
  packages/schemas/src/types/system.ts
Labels: feature, size/s

#3884 feat(schemas): add domains table
  packages/schemas/alterations/next-1684822341-init-domains.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/tables/domains.sql
Labels: feature, size/m

#3865 feat(schemas,cli,core,cloud): add manage tenant self scope
  .github/workflows/integration-test.yml
  packages/cli/src/commands/database/seed/tenant.ts
  packages/cloud/src/queries/tenants.ts
  packages/console/src/App.tsx
  packages/core/src/middleware/koa-auth/index.test.ts
  packages/core/src/middleware/koa-auth/index.ts
  packages/integration-tests/package.json
  packages/integration-tests/src/api/api.ts
  packages/integration-tests/src/api/tenant.ts
  packages/integration-tests/src/helpers/admin-tenant.ts
  packages/integration-tests/src/tests/api-cloud/tenant.test.ts
  packages/integration-tests/src/tests/api/me.test.ts
  packages/integration-tests/src/tests/api/oidc/get-access-token.test.ts
  packages/integration-tests/src/tests/api/resource.scope.test.ts
  packages/schemas/alterations/next-1684837981-add-manage-tenant-self-scope-to-user-role.ts
  packages/schemas/src/seeds/cloud-api.ts
  packages/schemas/src/seeds/management-api.ts
Labels: feature, size/l

#3890 chore(cli,cloud,schemas): change default tenant name
  packages/cli/src/commands/database/seed/tenant.ts
  packages/cloud/src/libraries/tenants.ts
  packages/cloud/src/queries/tenants.ts
  packages/schemas/alterations/next-1684382842-add-name-tag-created-at-for-tenants-table.ts
  packages/schemas/src/models/tenants.ts
  packages/schemas/src/seeds/tenant.ts
  packages/schemas/tables/_after_all.sql
  packages/schemas/tables/_functions.sql
Labels: chore, size/s

#3911 fix(console): should not check duplicated keys when key is empty
  packages/console/src/pages/WebhookDetails/WebhookSettings/components/CustomHeaderField/index.tsx
Labels: bugfix, size/xs

#3909 fix(console): enforce SSOT for webhook signing key
  packages/console/src/pages/WebhookDetails/WebhookSettings/index.tsx
Labels: bugfix, size/xs

#3917 fix(console): fix toggle tip z-index on modal layer
  packages/console/src/components/Tip/ToggleTip/index.module.scss
  packages/console/src/components/Tip/ToggleTip/index.tsx
Labels: bugfix, size/xs

#3892 feat(core): add domain routes
  packages/core/src/__mocks__/domain.ts
  packages/core/src/__mocks__/index.ts
  packages/core/src/queries/domains.ts
  packages/core/src/routes/domain.test.ts
  packages/core/src/routes/domain.ts
  packages/core/src/routes/init.ts
  packages/core/src/tenants/Queries.ts
  packages/integration-tests/src/api/domain.ts
  packages/integration-tests/src/api/index.ts
  packages/integration-tests/src/tests/api/domains.test.ts
  packages/integration-tests/src/utils.ts
  packages/phrases/src/locales/de/errors/domain.ts
  packages/phrases/src/locales/de/errors/index.ts
  packages/phrases/src/locales/en/errors/domain.ts
  packages/phrases/src/locales/en/errors/index.ts
  packages/phrases/src/locales/es/errors/domain.ts
  packages/phrases/src/locales/es/errors/index.ts
  packages/phrases/src/locales/fr/errors/domain.ts
  packages/phrases/src/locales/fr/errors/index.ts
  packages/phrases/src/locales/it/errors/domain.ts
  packages/phrases/src/locales/it/errors/index.ts
  packages/phrases/src/locales/ja/errors/domain.ts
  packages/phrases/src/locales/ja/errors/index.ts
  packages/phrases/src/locales/ko/errors/domain.ts
  packages/phrases/src/locales/ko/errors/index.ts
  packages/phrases/src/locales/pl-pl/errors/domain.ts
  packages/phrases/src/locales/pl-pl/errors/index.ts
  packages/phrases/src/locales/pt-br/errors/domain.ts
  packages/phrases/src/locales/pt-br/errors/index.ts
  packages/phrases/src/locales/pt-pt/errors/domain.ts
  packages/phrases/src/locales/pt-pt/errors/index.ts
  packages/phrases/src/locales/ru/errors/domain.ts
  packages/phrases/src/locales/ru/errors/index.ts
  packages/phrases/src/locales/tr-tr/errors/domain.ts
  packages/phrases/src/locales/tr-tr/errors/index.ts
  packages/phrases/src/locales/zh-cn/errors/domain.ts
  packages/phrases/src/locales/zh-cn/errors/index.ts
  packages/phrases/src/locales/zh-hk/errors/domain.ts
  packages/phrases/src/locales/zh-hk/errors/index.ts
  packages/phrases/src/locales/zh-tw/errors/domain.ts
  packages/phrases/src/locales/zh-tw/errors/index.ts
  packages/schemas/src/types/domain.ts
  packages/schemas/src/types/index.ts
Labels: feature, size/l

#3913 feat(core): add message id for the webhook payload
  packages/core/src/libraries/hook/index.test.ts
  packages/core/src/libraries/hook/utils.test.ts
  packages/core/src/libraries/hook/utils.ts
Labels: feature, size/s

#3904 feat(core): support pagination for `GET /hooks` api
  packages/core/src/database/find-all-entities.ts
  packages/core/src/queries/application.ts
  packages/core/src/queries/hooks.ts
  packages/core/src/queries/resource.ts
  packages/core/src/routes/hook.test.ts
  packages/core/src/routes/hook.ts
  packages/integration-tests/src/tests/api/hook/hook.test.ts
Labels: feature, size/m

#3914 feat(console): support pagination for webhooks page
  packages/console/src/pages/Webhooks/index.tsx
Labels: feature, size/s

#3875 feat(cloud,schemas,cli): update cloud service tenant APIs
  packages/cloud/src/libraries/tenants.ts
  packages/cloud/src/queries/tenants.ts
  packages/cloud/src/routes/tenants.test.ts
  packages/cloud/src/routes/tenants.ts
  packages/cloud/src/test-utils/libraries.ts
  packages/console/src/cloud/pages/Main/Tenants.tsx
  packages/console/src/contexts/TenantsProvider.tsx
  packages/integration-tests/src/api/tenant.ts
  packages/integration-tests/src/tests/api-cloud/tenant.test.ts
  packages/schemas/src/seeds/tenant.ts
  packages/schemas/src/types/tenant.ts
Labels: feature, size/l

#3881 feat(cloud,schemas): add PATCH /tenants/:id API
  packages/cloud/src/libraries/tenants.ts
  packages/cloud/src/queries/tenants.ts
  packages/cloud/src/routes/tenants.test.ts
  packages/cloud/src/routes/tenants.ts
  packages/cloud/src/test-utils/libraries.ts
  packages/integration-tests/src/api/tenant.ts
  packages/integration-tests/src/tests/api-cloud/tenant.test.ts
Labels: feature, size/m

#3900 feat(cloud,test): add DELETE /tenants/:id API
  .github/workflows/integration-test.yml
  packages/cloud/src/libraries/tenants.ts
  packages/cloud/src/queries/tenants.ts
  packages/cloud/src/routes/tenants.test.ts
  packages/cloud/src/routes/tenants.ts
  packages/cloud/src/test-utils/libraries.ts
  packages/integration-tests/package.json
  packages/integration-tests/src/api/tenant.ts
  packages/integration-tests/src/tests/api-cloud/tenant.test.ts
  pnpm-lock.yaml
Labels: feature, size/l

#3923 test: add ui tests for webhook management
  packages/integration-tests/src/tests/ui/user-management.test.ts
  packages/integration-tests/src/tests/ui/webhooks.test.ts
  packages/integration-tests/src/ui-helpers/index.ts
Labels: testing, size/m

#3905 refactor: add google tag conversion report
  packages/cloud/src/middleware/with-security-headers.ts
  packages/console/src/include.d/gtag.d.ts
  packages/console/src/onboarding/App.tsx
  packages/console/src/onboarding/constants/index.ts
  packages/console/src/onboarding/utils.ts
Labels: enhancement, size/s

#3926 feat(cli): export add connectors utils
  packages/cli/src/commands/connector/utils.ts
Labels: feature, size/s

#3929 chore(phrases): add custom domain phrases for console
  packages/phrases/src/locales/de/translation/admin-console/domain.ts
  packages/phrases/src/locales/de/translation/admin-console/index.ts
  packages/phrases/src/locales/en/translation/admin-console/domain.ts
  packages/phrases/src/locales/en/translation/admin-console/index.ts
  packages/phrases/src/locales/es/translation/admin-console/domain.ts
  packages/phrases/src/locales/es/translation/admin-console/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/domain.ts
  packages/phrases/src/locales/fr/translation/admin-console/index.ts
  packages/phrases/src/locales/it/translation/admin-console/domain.ts
  packages/phrases/src/locales/it/translation/admin-console/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/domain.ts
  packages/phrases/src/locales/ja/translation/admin-console/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/domain.ts
  packages/phrases/src/locales/ko/translation/admin-console/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/domain.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/domain.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/domain.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/domain.ts
  packages/phrases/src/locales/ru/translation/admin-console/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/domain.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/domain.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/domain.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/domain.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/index.ts
Labels: chore, size/xl

#3933 chore(test): use fake time in webhook unit tests
  packages/core/src/libraries/hook/index.test.ts
Labels: chore, size/xs
