Repository logto-io/logto, pull requests merged in 2023-01, with the labels that each got.

#2798 refactor(core): check connector-kit compatibility when load connector
  packages/cli/jest.config.js
  packages/core/jest.config.js
  packages/core/package.json
  packages/core/src/connectors/index.ts
  packages/core/src/connectors/utilities/compatibility.ts
  packages/integration-tests/jest.config.js
  packages/integration-tests/jest.config.ui.js
  packages/schemas/jest.config.js
  packages/shared/jest.config.js
  packages/toolkit/connector-kit/package.json
  packages/toolkit/core-kit/jest.config.js
  packages/toolkit/language-kit/jest.config.js
  pnpm-lock.yaml
Labels: enhancement, size/s

#2800 chore: add changeset-staged dir
  .changeset-staged/README.md
  .dockerignore
  .scripts/package.sh
Labels: chore, size/s

#2811 chore: update README
  README.md
Labels: chore, size/xs

#2786 ci: use node 18 as default
  .github/workflows/integration-test.yml
  .github/workflows/main.yml
  Dockerfile
Labels: size/s

#2807 ci: turn off zap issue
  .github/workflows/pen-tests.yml
Labels: size/xs

#2809 refactor: connector loader
  packages/core/src/connectors/index.ts
  packages/core/src/connectors/utilities/compatibility.ts
  packages/core/src/connectors/utilities/loader.ts
  packages/core/src/index.ts
  packages/toolkit/connector-kit/package.json
  packages/toolkit/connector-kit/rollup.config.js
  packages/toolkit/core-kit/package.json
  packages/toolkit/core-kit/rollup.config.js
  packages/toolkit/language-kit/package.json
  packages/toolkit/language-kit/rollup.config.js
  pnpm-lock.yaml
Labels: enhancement, size/m

#2812 refactor(console): `useConnectorInUse` hook
  packages/console/src/hooks/use-connector-in-use.ts
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorRow/index.tsx
Labels: enhancement, size/m

#2814 fix(demo-app): demo app notificaiton should always follow system language
  packages/core/src/libraries/sign-in-experience/index.ts
Labels: bugfix, size/s

#2805 chore: improve comment for docker compose file
  docker-compose.yml
Labels: chore, size/xs

#2525 feat: add users_roles table and remove role_names
  packages/console/src/components/UserName/index.tsx
  packages/console/src/pages/UserDetails/components/UserSettings.tsx
  packages/console/src/pages/UserDetails/types.ts
  packages/console/src/pages/UserDetails/utils.ts
  packages/core/src/__mocks__/user.ts
  packages/core/src/libraries/user.ts
  packages/core/src/oidc/scope.ts
  packages/core/src/queries/roles.test.ts
  packages/core/src/queries/roles.ts
  packages/core/src/queries/user.test.ts
  packages/core/src/queries/user.ts
  packages/core/src/queries/users-roles.ts
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
  packages/integration-tests/src/tests/api/admin-user.test.ts
  packages/schemas/alterations/next-1672815959-user-roles.ts
  packages/schemas/src/seeds/roles.ts
  packages/schemas/src/types/user.ts
  packages/schemas/tables/users.sql
  packages/schemas/tables/usersroles.sql
Labels: feature, size/l

#2716 feat(toolkit): define optional keys for connector.getUserInfo
  packages/core/src/connectors/types.ts
  packages/core/src/libraries/social.ts
  packages/core/src/routes/interaction/types/guard.ts
  packages/core/src/routes/interaction/types/index.ts
  packages/core/src/routes/interaction/utils/social-verification.ts
  packages/core/src/routes/profile.test.ts
  packages/core/src/routes/session/social.test.ts
  packages/toolkit/connector-kit/src/types.ts
Labels: feature, size/s

#2815 chore(console): remove deprecated transfer component
  packages/console/src/components/DragDrop/DragDropProvider.tsx
  packages/console/src/components/DragDrop/DraggableItem.tsx
  packages/console/src/components/DragDrop/index.module.scss
  packages/console/src/components/DragDrop/index.tsx
  packages/console/src/components/Transfer/index.module.scss
  packages/console/src/components/Transfer/index.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SignInMethodEditBox/index.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SocialConnectorEditBox/index.tsx
Labels: chore, size/m

#2813 refactor(console): connectors table
  packages/console/src/components/Table/TableEmpty.module.scss
  packages/console/src/components/Table/TableEmpty.tsx
  packages/console/src/components/Table/index.tsx
  packages/console/src/consts/connectors.ts
  packages/console/src/hooks/use-connector-in-use.ts
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorName/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorRow/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorStatus/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorTypeColumn/index.tsx
  packages/console/src/pages/Connectors/index.tsx
Labels: enhancement, size/xl

#2672 feat(core): roles crud
  packages/core/src/queries/roles.test.ts
  packages/core/src/queries/roles.ts
  packages/core/src/routes/role.test.ts
  packages/core/src/routes/role.ts
  packages/phrases/src/locales/de/errors.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko/errors.ts
  packages/phrases/src/locales/pt-br/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
Labels: feature, size/l

#2757 feat(core): resource scopes crud
  packages/core/src/__mocks__/index.ts
  packages/core/src/queries/scope.ts
  packages/core/src/routes/resource.test.ts
  packages/core/src/routes/resource.ts
  packages/schemas/alterations/next-1672820345-scope-resourc-id.ts
  packages/schemas/tables/scopes.sql
Labels: feature, size/m

#2819 feat(core): list resources with scopes
  packages/core/src/__mocks__/index.ts
  packages/core/src/libraries/resource.test.ts
  packages/core/src/libraries/resource.ts
  packages/core/src/queries/scope.ts
  packages/core/src/routes/resource.test.ts
  packages/core/src/routes/resource.ts
  packages/schemas/src/types/index.ts
  packages/schemas/src/types/resource.ts
Labels: feature, size/m

#2820 feat(console): roles page
  packages/console/src/App.tsx
  packages/console/src/assets/images/role.svg
  packages/console/src/components/AppContent/components/Sidebar/hook.tsx
  packages/console/src/pages/Roles/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/index.ts
  packages/phrases/src/locales/de/translation/admin-console/roles.ts
  packages/phrases/src/locales/de/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/de/translation/admin-console/tabs.ts
  packages/phrases/src/locales/en/translation/admin-console/index.ts
  packages/phrases/src/locales/en/translation/admin-console/roles.ts
  packages/phrases/src/locales/en/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/en/translation/admin-console/tabs.ts
  packages/phrases/src/locales/fr/translation/admin-console/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/roles.ts
  packages/phrases/src/locales/fr/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/fr/translation/admin-console/tabs.ts
  packages/phrases/src/locales/ko/translation/admin-console/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/roles.ts
  packages/phrases/src/locales/ko/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/ko/translation/admin-console/tabs.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/roles.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tabs.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/roles.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tabs.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/roles.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tabs.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/roles.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tabs.ts
Labels: feature, size/m

#2821 feat(console): role details settings page
  packages/console/src/App.tsx
  packages/console/src/pages/RoleDetails/RoleSettings/index.tsx
  packages/console/src/pages/RoleDetails/index.module.scss
  packages/console/src/pages/RoleDetails/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/index.ts
  packages/phrases/src/locales/de/translation/admin-console/role-details.ts
  packages/phrases/src/locales/en/translation/admin-console/index.ts
  packages/phrases/src/locales/en/translation/admin-console/role-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/role-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/role-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/role-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/role-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/role-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/role-details.ts
Labels: feature, size/l

#2822 feat(console): create role
  packages/console/src/App.tsx
  packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
  packages/console/src/pages/Roles/components/CreateRoleModal/index.tsx
  packages/console/src/pages/Roles/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/roles.ts
  packages/phrases/src/locales/en/translation/admin-console/roles.ts
  packages/phrases/src/locales/fr/translation/admin-console/roles.ts
  packages/phrases/src/locales/ko/translation/admin-console/roles.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/roles.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/roles.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/roles.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/roles.ts
Labels: feature, size/m

#2824 feat(console): delete role
  packages/console/src/pages/RoleDetails/RoleSettings/index.tsx
  packages/console/src/pages/RoleDetails/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/role-details.ts
  packages/phrases/src/locales/en/translation/admin-console/role-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/role-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/role-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/role-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/role-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/role-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/role-details.ts
Labels: feature, size/s

#2818 refactor(console): support tiny pagination variant
  packages/console/src/components/Pagination/index.module.scss
  packages/console/src/components/Pagination/index.tsx
Labels: enhancement, size/m

#2828 fix(core): return role names for admin user detail api
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
Labels: bugfix, size/xs

#2829 feat(console): api resource permissions page
  packages/console/src/App.tsx
  packages/console/src/consts/page-tabs.ts
  packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/index.module.scss
  packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/index.tsx
  packages/console/src/pages/ApiResourceDetails/ApiResourceSettings/index.tsx
  packages/console/src/pages/ApiResourceDetails/index.module.scss
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/console/src/pages/ApiResourceDetails/types.ts
  packages/console/src/pages/ApiResources/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/en/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/api-resource-details.ts
Labels: feature, size/l

#2826 feat(core): role-scope api
  packages/core/src/queries/roles-scopes.ts
  packages/core/src/queries/scope.ts
  packages/core/src/routes/role.test.ts
  packages/core/src/routes/role.ts
  packages/phrases/src/locales/de/errors.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko/errors.ts
  packages/phrases/src/locales/pt-br/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
  packages/schemas/alterations/next-1672901841-roles-and-scopes-not-null.ts
  packages/schemas/tables/scopesroles.sql
Labels: feature, size/l

#2832 fix: version lifecycle script
  .changeset/slow-meals-enjoy.md
  .scripts/version.js
Labels: bugfix, size/s

#2823 refactor: add Generic type and remove deprecated Continue code type
  packages/toolkit/connector-kit/src/types.ts
Labels: enhancement, size/xs

#2830 feat(console): create permission
  packages/console/src/components/Table/index.module.scss
  packages/console/src/components/Table/index.tsx
  packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx
  packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/index.module.scss
  packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/index.tsx
Labels: feature, size/m

#2831 feat(console): delete permission
  packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/en/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/api-resource-details.ts
Labels: feature, size/s

#2842 fix(core): fix typo
  packages/core/src/routes/resource.ts
Labels: bugfix, size/xs

#2827 feat(core): user-role related api
  packages/core/src/queries/user.ts
  packages/core/src/queries/users-roles.ts
  packages/core/src/routes/admin-user-role.test.ts
  packages/core/src/routes/admin-user-role.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/role.test.ts
  packages/core/src/routes/role.ts
  packages/phrases/src/locales/de/errors.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko/errors.ts
  packages/phrases/src/locales/pt-br/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
Labels: feature, size/l

#2844 fix(core): prevent empty array to be used by sql in
  packages/core/src/libraries/resource.test.ts
  packages/core/src/libraries/resource.ts
  packages/core/src/queries/roles.ts
  packages/core/src/queries/scope.ts
  packages/core/src/queries/user.ts
Labels: bugfix, size/s

#2843 feat(core): add resource to response scopes
  packages/core/src/queries/resource.ts
  packages/core/src/routes/role.test.ts
  packages/core/src/routes/role.ts
  packages/schemas/src/types/index.ts
  packages/schemas/src/types/scope.ts
Labels: feature, size/s

#2848 chore!: drop Node 16
  package.json
  packages/cli/package.json
  packages/cli/src/commands/install/utils.ts
  packages/console/package.json
  packages/core/package.json
  packages/create/package.json
  packages/demo-app/package.json
  packages/integration-tests/package.json
  packages/phrases-ui/package.json
  packages/phrases/package.json
  packages/schemas/package.json
  packages/shared/package.json
  packages/toolkit/connector-kit/package.json
  packages/toolkit/core-kit/package.json
  packages/toolkit/language-kit/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: chore, size/s

#2836 feat(core): add search and pagination for roles
  packages/core/src/queries/roles.test.ts
  packages/core/src/queries/roles.ts
  packages/core/src/routes/role.test.ts
  packages/core/src/routes/role.ts
Labels: feature, size/s

#2840 feat(core): add search and optional pagination to scopes
  packages/core/src/middleware/koa-pagination.ts
  packages/core/src/queries/scope.ts
  packages/core/src/routes/resource.test.ts
  packages/core/src/routes/resource.ts
Labels: feature, size/s

#2845 feat(core): set resources pagination to optional
  packages/core/src/queries/resource.ts
  packages/core/src/routes/resource.test.ts
  packages/core/src/routes/resource.ts
Labels: feature, size/s

#2841 refactor(schemas): alter passcodes table and set jti to nullable
  packages/schemas/alterations/next-1673001922-support-generic-passcode.ts
  packages/schemas/tables/passcodes.sql
Labels: enhancement, size/s

#2865 feat(core): set roles pagination to optional
  packages/core/src/queries/roles.ts
  packages/core/src/routes/role.ts
Labels: feature, size/s

#2846 feat(core): filter users by exclude role id
  packages/core/src/routes/admin-user.ts
Labels: feature, size/s

#2839 feat(console): role users transfer component
  packages/console/src/components/RoleUsersTransfer/SourceUsersBox.tsx
  packages/console/src/components/RoleUsersTransfer/TargetUsersBox.tsx
  packages/console/src/components/RoleUsersTransfer/index.module.scss
  packages/console/src/components/RoleUsersTransfer/index.tsx
Labels: feature, size/l

#2852 refactor(core): move app to tenant instance
  packages/core/package.json
  packages/core/src/app/init.test.ts
  packages/core/src/app/init.ts
  packages/core/src/tenants/Tenant.test.ts
  packages/core/src/tenants/Tenant.ts
  packages/core/src/tenants/index.ts
  pnpm-lock.yaml
Labels: enhancement, size/m

#2859 refactor(console): user details page
  packages/console/src/App.tsx
  packages/console/src/components/AuditLogTable/index.tsx
  packages/console/src/consts/page-tabs.ts
  packages/console/src/pages/AuditLogDetails/index.tsx
  packages/console/src/pages/UserDetails/UserLogs/index.module.scss
  packages/console/src/pages/UserDetails/UserLogs/index.tsx
  packages/console/src/pages/UserDetails/UserSettings/components/UserConnectors/index.module.scss
  packages/console/src/pages/UserDetails/UserSettings/components/UserConnectors/index.tsx
  packages/console/src/pages/UserDetails/UserSettings/index.tsx
  packages/console/src/pages/UserDetails/components/CreateSuccess/index.module.scss
  packages/console/src/pages/UserDetails/components/CreateSuccess/index.tsx
  packages/console/src/pages/UserDetails/components/ResetPasswordForm/index.tsx
  packages/console/src/pages/UserDetails/components/UserLogs.tsx
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/pages/UserDetails/types.ts
  packages/console/src/pages/Users/index.tsx
Labels: enhancement, size/m

#2871 ci: deploy db alteration before app
  .github/workflows/release.yml
Labels: size/s

#2853 refactor(core,cli): application query factory
  packages/cli/src/queries/logto-config.ts
  packages/core/src/database/find-entity-by-id.ts
  packages/core/src/database/insert-into.test.ts
  packages/core/src/database/insert-into.ts
  packages/core/src/database/row-count.ts
  packages/core/src/database/update-where.test.ts
  packages/core/src/database/update-where.ts
  packages/core/src/libraries/logto-config.ts
  packages/core/src/queries/application.test.ts
  packages/core/src/queries/application.ts
  packages/core/src/queries/connector.test.ts
  packages/core/src/queries/passcode.test.ts
  packages/core/src/queries/resource.test.ts
  packages/core/src/queries/roles.test.ts
  packages/core/src/queries/setting.test.ts
  packages/core/src/queries/sign-in-experience.test.ts
  packages/core/src/queries/user.test.ts
Labels: enhancement, size/xl

#2869 feat(schemas,cli): seed default scope for management api
  packages/cli/src/commands/database/seed/index.ts
  packages/schemas/src/seeds/index.ts
  packages/schemas/src/seeds/resource.ts
  packages/schemas/src/seeds/roles.ts
  packages/schemas/src/seeds/scope.ts
Labels: feature, size/s

#2860 feat(console): user roles page
  packages/console/src/App.tsx
  packages/console/src/consts/page-tabs.ts
  packages/console/src/pages/UserDetails/UserRoles/index.module.scss
  packages/console/src/pages/UserDetails/UserRoles/index.tsx
  packages/console/src/pages/UserDetails/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/user-details.ts
  packages/phrases/src/locales/en/translation/admin-console/user-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/user-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/user-details.ts
Labels: feature, size/m

#2864 feat(console): role users page
  packages/console/src/App.tsx
  packages/console/src/consts/page-tabs.ts
  packages/console/src/pages/RoleDetails/RoleUsers/index.module.scss
  packages/console/src/pages/RoleDetails/RoleUsers/index.tsx
  packages/console/src/pages/RoleDetails/index.module.scss
  packages/console/src/pages/RoleDetails/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/role-details.ts
  packages/phrases/src/locales/en/translation/admin-console/role-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/role-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/role-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/role-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/role-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/role-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/role-details.ts
Labels: feature, size/l

#2854 refactor(core): connector query factory
  packages/core/src/queries/connector.ts
Labels: enhancement, size/m

#2856 refactor(core): custom phrase and log query factories
  packages/core/src/queries/custom-phrase.ts
  packages/core/src/queries/log.ts
Labels: enhancement, size/m

#2857 refactor(core): multiple query factories
  packages/core/src/queries/oidc-model-instance.ts
  packages/core/src/queries/passcode.ts
  packages/core/src/queries/resource.ts
  packages/core/src/queries/roles-scopes.ts
  packages/core/src/queries/roles.ts
  packages/core/src/queries/scope.ts
  packages/core/src/queries/setting.ts
  packages/core/src/queries/sign-in-experience.ts
Labels: enhancement, size/xl

#2858 refactor(core): users and users roles query factories
  packages/core/src/queries/user.ts
  packages/core/src/queries/users-roles.ts
Labels: enhancement, size/xl

#2863 refactor(core): use tenant context for route inits
  packages/core/package.json
  packages/core/src/app/init.ts
  packages/core/src/oidc/init.test.ts
  packages/core/src/oidc/init.ts
  packages/core/src/queries/passcode.ts
  packages/core/src/queries/user.ts
  packages/core/src/routes/admin-user-role.ts
  packages/core/src/routes/admin-user.ts
  packages/core/src/routes/application.ts
  packages/core/src/routes/authn.ts
  packages/core/src/routes/connector.ts
  packages/core/src/routes/custom-phrase.ts
  packages/core/src/routes/dashboard.ts
  packages/core/src/routes/hook.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/interaction/actions/submit-interaction.test.ts
  packages/core/src/routes/interaction/index.test.ts
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/log.ts
  packages/core/src/routes/phrase.content-language.test.ts
  packages/core/src/routes/phrase.test.ts
  packages/core/src/routes/phrase.ts
  packages/core/src/routes/profile.test.ts
  packages/core/src/routes/profile.ts
  packages/core/src/routes/resource.ts
  packages/core/src/routes/role.ts
  packages/core/src/routes/session/index.ts
  packages/core/src/routes/setting.ts
  packages/core/src/routes/sign-in-experience.ts
  packages/core/src/routes/status.ts
  packages/core/src/routes/types.ts
  packages/core/src/routes/well-known.test.ts
  packages/core/src/routes/well-known.ts
  packages/core/src/tenants/Queries.ts
  packages/core/src/tenants/Tenant.test.ts
  packages/core/src/tenants/Tenant.ts
  packages/core/src/tenants/TenantContext.ts
  packages/core/src/tenants/consts.ts
  packages/core/src/tenants/index.ts
  packages/core/src/test-utils/tenant.ts
  packages/core/src/utils/test-utils.ts
Labels: enhancement, size/l

#2851 refactor(core): upgrade oidc-provider to 8.0.0
  packages/core/package.json
  packages/core/src/event-listeners/index.ts
  packages/core/src/include.d/oidc-provider.d.ts
  packages/core/src/libraries/hook.ts
  packages/core/src/libraries/session.ts
  packages/core/src/middleware/koa-log-session-legacy.test.ts
  packages/core/src/middleware/koa-log-session-legacy.ts
  packages/core/src/middleware/koa-spa-session-guard.test.ts
  packages/core/src/middleware/koa-spa-session-guard.ts
  packages/core/src/oidc/init.ts
  packages/core/src/routes/interaction/actions/submit-interaction.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/core/src/routes/interaction/middleware/koa-interaction-details.ts
  packages/core/src/routes/interaction/middleware/koa-interaction-hooks.ts
  packages/core/src/routes/interaction/utils/interaction.ts
  packages/core/src/routes/interaction/utils/social-verification.ts
  packages/core/src/routes/interaction/verifications/identifier-payload-verification.ts
  packages/core/src/routes/interaction/verifications/identifier-verification.ts
  packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.test.ts
  packages/core/src/routes/session/continue.test.ts
  packages/core/src/routes/session/continue.ts
  packages/core/src/routes/session/forgot-password.test.ts
  packages/core/src/routes/session/forgot-password.ts
  packages/core/src/routes/session/index.test.ts
  packages/core/src/routes/session/middleware/koa-guard-session-action.ts
  packages/core/src/routes/session/middleware/passwordless-action.ts
  packages/core/src/routes/session/password.test.ts
  packages/core/src/routes/session/password.ts
  packages/core/src/routes/session/passwordless.test.ts
  packages/core/src/routes/session/passwordless.ts
  packages/core/src/routes/session/social.bind-social.test.ts
  packages/core/src/routes/session/social.test.ts
  packages/core/src/routes/session/social.ts
  packages/core/src/routes/session/utils.test.ts
  packages/core/src/routes/session/utils.ts
  packages/core/src/tenants/Tenant.ts
  packages/core/src/tenants/TenantContext.ts
  packages/core/src/test-utils/oidc-provider.ts
  pnpm-lock.yaml
Labels: enhancement, size/s

#2847 refactor: support EC key and ES signing algorithms
  .changeset-staged/six-falcons-sin.md
  packages/cli/src/commands/database/utilities.ts
  packages/core/src/env-set/oidc.ts
  packages/core/src/event-listeners/index.ts
  packages/core/src/oidc/init.ts
  packages/core/src/oidc/utils.ts
Labels: enhancement, size/m

#2867 refactor(core): migrate user library to factory mode
  packages/core/src/libraries/session.ts
  packages/core/src/libraries/user.test.ts
  packages/core/src/libraries/user.ts
  packages/core/src/queries/application.test.ts
  packages/core/src/queries/application.ts
  packages/core/src/queries/connector.test.ts
  packages/core/src/queries/oidc-model-instance.test.ts
  packages/core/src/queries/oidc-model-instance.ts
  packages/core/src/queries/passcode.test.ts
  packages/core/src/queries/resource.test.ts
  packages/core/src/queries/roles.test.ts
  packages/core/src/queries/setting.test.ts
  packages/core/src/queries/sign-in-experience.test.ts
  packages/core/src/queries/user.test.ts
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
  packages/core/src/routes/application.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/verifications/identifier-payload-verification.test.ts
  packages/core/src/routes/interaction/verifications/identifier-payload-verification.ts
  packages/core/src/routes/profile.test.ts
  packages/core/src/routes/profile.ts
  packages/core/src/tenants/Libraries.ts
  packages/core/src/tenants/Tenant.ts
  packages/core/src/tenants/TenantContext.ts
  packages/core/src/test-utils/tenant.ts
Labels: enhancement, size/xl

#2877 refactor: remove unused files
  packages/cli/src/commands/database/alteration/meta-url.ts
  packages/cli/src/commands/database/alteration/utils.ts
  packages/cli/src/meta-url.ts
  packages/cli/src/utilities.ts
Labels: enhancement, size/s

#2872 feat(core): hide admin console role
  packages/core/src/queries/roles.ts
Labels: feature, size/s

#2873 refactor(core,ui,test): migrate consent api to interaction
  packages/core/src/routes/interaction/consent.test.ts
  packages/core/src/routes/interaction/consent.ts
  packages/core/src/routes/interaction/const.ts
  packages/core/src/routes/interaction/index.test.ts
  packages/core/src/routes/interaction/index.ts
  packages/core/src/test-utils/oidc-provider.ts
  packages/core/src/test-utils/tenant.ts
  packages/integration-tests/src/api/interaction.ts
  packages/integration-tests/src/api/session.ts
  packages/integration-tests/src/client/index.ts
  packages/ui/src/apis/consent.ts
  packages/ui/src/apis/index.test.ts
Labels: enhancement, size/l

#2874 refactor(test): remove all session api tests in integration tests
  packages/integration-tests/src/api/index.ts
  packages/integration-tests/src/api/session.ts
  packages/integration-tests/src/helpers.ts
  packages/integration-tests/src/helpers/client.ts
  packages/integration-tests/src/helpers/connector.ts
  packages/integration-tests/src/helpers/index.ts
  packages/integration-tests/src/helpers/interactions.ts
  packages/integration-tests/src/helpers/sign-in-experience.ts
  packages/integration-tests/src/helpers/user.ts
  packages/integration-tests/src/tests/api/admin-user.search.test.ts
  packages/integration-tests/src/tests/api/admin-user.test.ts
  packages/integration-tests/src/tests/api/audit-logs/index.test.ts
  packages/integration-tests/src/tests/api/dashboard.test.ts
  packages/integration-tests/src/tests/api/get-access-token.test.ts
  packages/integration-tests/src/tests/api/hooks.test.ts
  packages/integration-tests/src/tests/api/interaction/forgot-password.test.ts
  packages/integration-tests/src/tests/api/interaction/register-with-identifier.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-passcode-identifier.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier.test.ts
  packages/integration-tests/src/tests/api/interaction/social-interaction.test.ts
  packages/integration-tests/src/tests/api/logs-legacy.test.ts
  packages/integration-tests/src/tests/api/session.test.ts
  packages/integration-tests/src/tests/api/social-session.test.ts
Labels: enhancement, size/xl

#2890 fix(console): fix indeterminate state issue and react warning in checkbox component
  packages/console/src/components/Checkbox/index.module.scss
  packages/console/src/components/Checkbox/index.tsx
Labels: bugfix, size/s

#2861 feat(core): scope name within the same resource should be unique
  packages/core/src/queries/scope.ts
  packages/core/src/routes/resource.test.ts
  packages/core/src/routes/resource.ts
  packages/phrases/src/locales/de/errors.ts
  packages/phrases/src/locales/en/errors.ts
  packages/phrases/src/locales/fr/errors.ts
  packages/phrases/src/locales/ko/errors.ts
  packages/phrases/src/locales/pt-br/errors.ts
  packages/phrases/src/locales/pt-pt/errors.ts
  packages/phrases/src/locales/tr-tr/errors.ts
  packages/phrases/src/locales/zh-cn/errors.ts
  packages/schemas/alterations/next-1673165463-scope-name-index.ts
  packages/schemas/tables/scopes.sql
Labels: feature, size/s

#2870 refactor(core): migrate sie library to factory mode
  packages/core/src/libraries/shared.ts
  packages/core/src/libraries/sign-in-experience/index.test.ts
  packages/core/src/libraries/sign-in-experience/index.ts
  packages/core/src/libraries/user.ts
  packages/core/src/routes/application.test.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/profile.ts
  packages/core/src/routes/sign-in-experience/guard.branding.test.ts
  packages/core/src/routes/sign-in-experience/guard.color.test.ts
  packages/core/src/routes/sign-in-experience/guard.test.ts
  packages/core/src/routes/sign-in-experience/index.test.ts
  packages/core/src/routes/sign-in-experience/index.ts
  packages/core/src/routes/well-known.test.ts
  packages/core/src/routes/well-known.ts
  packages/core/src/tenants/Libraries.ts
  packages/core/src/test-utils/tenant.ts
Labels: enhancement, size/l

#2879 refactor(core): reorg connector files
  packages/cli/src/commands/database/alteration/meta-url.ts
  packages/cli/src/commands/database/alteration/utils.ts
  packages/cli/src/meta-url.ts
  packages/cli/src/utilities.ts
  packages/core/src/__mocks__/connector.ts
  packages/core/src/connectors/index.ts
  packages/core/src/connectors/meta-url.ts
  packages/core/src/connectors/utilities/index.test.ts
  packages/core/src/index.ts
  packages/core/src/libraries/connector.test.ts
  packages/core/src/libraries/connector.ts
  packages/core/src/libraries/passcode.test.ts
  packages/core/src/libraries/passcode.ts
  packages/core/src/libraries/sign-in-experience/index.test.ts
  packages/core/src/libraries/sign-in-experience/index.ts
  packages/core/src/libraries/sign-in-experience/sign-in.ts
  packages/core/src/libraries/sign-in-experience/sign-up.ts
  packages/core/src/libraries/social.ts
  packages/core/src/routes/connector.test.ts
  packages/core/src/routes/connector.ts
  packages/core/src/routes/connector.update.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/core/src/routes/interaction/index.test.ts
  packages/core/src/routes/interaction/utils/find-user-by-identifier.test.ts
  packages/core/src/routes/interaction/utils/find-user-by-identifier.ts
  packages/core/src/routes/interaction/utils/social-verification.test.ts
  packages/core/src/routes/interaction/utils/social-verification.ts
  packages/core/src/routes/interaction/verifications/profile-verification-profile-registered.test.ts
  packages/core/src/routes/interaction/verifications/profile-verification-protected-identifier.test.ts
  packages/core/src/routes/interaction/verifications/profile-verification.ts
  packages/core/src/routes/profile.test.ts
  packages/core/src/routes/profile.ts
  packages/core/src/routes/session/social.bind-social.test.ts
  packages/core/src/routes/session/social.test.ts
  packages/core/src/routes/session/social.ts
  packages/core/src/routes/sign-in-experience/guard.branding.test.ts
  packages/core/src/routes/sign-in-experience/guard.color.test.ts
  packages/core/src/routes/sign-in-experience/guard.test.ts
  packages/core/src/routes/sign-in-experience/index.test.ts
  packages/core/src/routes/sign-in-experience/index.ts
  packages/core/src/routes/well-known.test.ts
  packages/core/src/routes/well-known.ts
  packages/core/src/utils/connectors/consts.ts
  packages/core/src/utils/connectors/factories.ts
  packages/core/src/utils/connectors/index.ts
  packages/core/src/utils/connectors/loader.ts
  packages/core/src/utils/connectors/platform.test.ts
  packages/core/src/utils/connectors/platform.ts
  packages/core/src/utils/connectors/types.ts
Labels: enhancement, size/xl

#2884 refactor(core): migrate connector library to factory mode
  packages/core/src/libraries/connector.test.ts
  packages/core/src/libraries/connector.ts
  packages/core/src/libraries/sign-in-experience/index.test.ts
  packages/core/src/libraries/sign-in-experience/index.ts
  packages/core/src/libraries/user.test.ts
  packages/core/src/routes/connector.test.ts
  packages/core/src/routes/connector.ts
  packages/core/src/routes/connector.update.test.ts
  packages/core/src/routes/session/social.test.ts
  packages/core/src/routes/sign-in-experience/guard.branding.test.ts
  packages/core/src/routes/sign-in-experience/guard.color.test.ts
  packages/core/src/routes/sign-in-experience/guard.test.ts
  packages/core/src/routes/sign-in-experience/index.test.ts
  packages/core/src/routes/sign-in-experience/index.ts
  packages/core/src/routes/well-known.test.ts
  packages/core/src/routes/well-known.ts
  packages/core/src/tenants/Libraries.ts
  packages/core/src/test-utils/tenant.ts
Labels: enhancement, size/l

#2885 refactor(core): migrate logto config library to factory mode
  packages/core/src/env-set/index.ts
  packages/core/src/libraries/__mocks__/logto-config.ts
  packages/core/src/libraries/logto-config.ts
Labels: enhancement, size/s

#2886 refactor(core): migrate phrase library to factory mode
  packages/core/src/libraries/phrase.test.ts
  packages/core/src/libraries/phrase.ts
  packages/core/src/routes/connector.test.ts
  packages/core/src/routes/phrase.content-language.test.ts
  packages/core/src/routes/phrase.test.ts
  packages/core/src/routes/phrase.ts
  packages/core/src/tenants/Libraries.ts
Labels: enhancement, size/m

#2892 fix(core): fix findUsersByIds for empty ids case
  packages/core/src/queries/user.ts
Labels: bugfix, size/s

#2878 refactor(core): remove session api
  .github/CODEOWNERS
  packages/core/src/middleware/koa-audit-log-legacy.test.ts
  packages/core/src/middleware/koa-audit-log-legacy.ts
  packages/core/src/middleware/koa-log-session-legacy.test.ts
  packages/core/src/middleware/koa-log-session-legacy.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/session/continue.test.ts
  packages/core/src/routes/session/continue.ts
  packages/core/src/routes/session/forgot-password.test.ts
  packages/core/src/routes/session/forgot-password.ts
  packages/core/src/routes/session/index.test.ts
  packages/core/src/routes/session/index.ts
  packages/core/src/routes/session/middleware/koa-guard-session-action.ts
  packages/core/src/routes/session/middleware/passwordless-action.ts
  packages/core/src/routes/session/password.test.ts
  packages/core/src/routes/session/password.ts
  packages/core/src/routes/session/passwordless.test.ts
  packages/core/src/routes/session/passwordless.ts
  packages/core/src/routes/session/social.bind-social.test.ts
  packages/core/src/routes/session/social.test.ts
  packages/core/src/routes/session/social.ts
  packages/core/src/routes/session/types.ts
  packages/core/src/routes/session/utils.test.ts
  packages/core/src/routes/session/utils.ts
  packages/core/src/routes/types.ts
  packages/ui/src/apis/social.ts
Labels: enhancement, size/xl

#2889 refactor(core,console,schemas): remove logDto
  packages/console/src/components/AuditLogTable/index.tsx
  packages/console/src/pages/AuditLogDetails/index.tsx
  packages/core/src/middleware/koa-audit-log.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/log.test.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/types/log-legacy.ts
  packages/schemas/src/types/log/index.ts
  packages/schemas/tables/logs.sql
Labels: enhancement, size/l

#2883 feat(console): assign users to a role
  packages/console/src/components/RoleUsersTransfer/SourceUsersBox.tsx
  packages/console/src/components/RoleUsersTransfer/index.tsx
  packages/console/src/pages/RoleDetails/RoleUsers/components/AssignUsersModal/index.tsx
  packages/console/src/pages/RoleDetails/RoleUsers/index.tsx
  packages/console/src/pages/Roles/components/CreateRoleModal/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/general.ts
  packages/phrases/src/locales/de/translation/admin-console/role-details.ts
  packages/phrases/src/locales/en/translation/admin-console/general.ts
  packages/phrases/src/locales/en/translation/admin-console/role-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/general.ts
  packages/phrases/src/locales/fr/translation/admin-console/role-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/general.ts
  packages/phrases/src/locales/ko/translation/admin-console/role-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/role-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/role-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/role-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/role-details.ts
Labels: feature, size/m

#2887 refactor(core): migrate resource library to factory mode
  packages/core/package.json
  packages/core/src/libraries/resource.test.ts
  packages/core/src/libraries/resource.ts
  packages/core/src/routes/resource.test.ts
  packages/core/src/routes/resource.ts
  packages/core/src/tenants/Libraries.ts
Labels: enhancement, size/m

#2891 refactor(core): migrate hook library to factory mode
  packages/core/package.json
  packages/core/src/libraries/hook.test.ts
  packages/core/src/libraries/hook.ts
  packages/core/src/middleware/koa-audit-log.test.ts
  packages/core/src/middleware/koa-audit-log.ts
  packages/core/src/model-routers/index.ts
  packages/core/src/oidc/init.test.ts
  packages/core/src/oidc/init.ts
  packages/core/src/routes/hook.ts
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/middleware/koa-interaction-hooks.ts
  packages/core/src/tenants/Libraries.ts
  packages/core/src/tenants/Tenant.ts
  packages/core/src/tenants/TenantContext.ts
  packages/core/src/test-utils/tenant.ts
Labels: enhancement, size/l

#2882 feat(console): assign permissions to a role
  packages/console/src/assets/images/caret-expanded.svg
  packages/console/src/assets/images/caret-folded.svg
  packages/console/src/components/RolePermissionsTransfer/SourcePermissionsBox.tsx
  packages/console/src/components/RolePermissionsTransfer/TargetPermissionsBox.tsx
  packages/console/src/components/RolePermissionsTransfer/components/ResourceItem/index.module.scss
  packages/console/src/components/RolePermissionsTransfer/components/ResourceItem/index.tsx
  packages/console/src/components/RolePermissionsTransfer/components/SourcePermissionItem/index.module.scss
  packages/console/src/components/RolePermissionsTransfer/components/SourcePermissionItem/index.tsx
  packages/console/src/components/RolePermissionsTransfer/components/TargetPermissionItem/index.module.scss
  packages/console/src/components/RolePermissionsTransfer/components/TargetPermissionItem/index.tsx
  packages/console/src/components/RolePermissionsTransfer/index.module.scss
  packages/console/src/components/RolePermissionsTransfer/index.tsx
  packages/console/src/components/RolePermissionsTransfer/types.ts
  packages/console/src/pages/RoleDetails/RolePermissions/components/AssignPermissionsModal/index.tsx
  packages/console/src/pages/RoleDetails/RolePermissions/index.tsx
  packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/roles.ts
  packages/phrases/src/locales/en/translation/admin-console/roles.ts
  packages/phrases/src/locales/fr/translation/admin-console/roles.ts
  packages/phrases/src/locales/ko/translation/admin-console/roles.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/roles.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/roles.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/roles.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/roles.ts
Labels: feature, size/xl

#2893 feat(core): list roles filter by userId
  packages/core/src/queries/roles.ts
  packages/core/src/routes/role.ts
  packages/shared/src/database/utils.ts
Labels: feature, size/s

#2897 refactor(core,ui): remove identity profile related apis and pages
  packages/core/src/libraries/session.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/profile.test.ts
  packages/core/src/routes/profile.ts
  packages/ui/src/App.tsx
  packages/ui/src/apis/profile.ts
  packages/ui/src/pages/Profile/components/FormCard/index.module.scss
  packages/ui/src/pages/Profile/components/FormCard/index.tsx
  packages/ui/src/pages/Profile/components/NavItem/index.module.scss
  packages/ui/src/pages/Profile/components/NavItem/index.tsx
  packages/ui/src/pages/Profile/components/Table/index.module.scss
  packages/ui/src/pages/Profile/components/Table/index.tsx
  packages/ui/src/pages/Profile/containers/DesktopView/index.tsx
  packages/ui/src/pages/Profile/containers/MobileView/index.tsx
  packages/ui/src/pages/Profile/index.module.scss
  packages/ui/src/pages/Profile/index.tsx
Labels: enhancement, size/xl

#2899 refactor(console): build url by `buildUrl` util
  packages/console/src/components/AuditLogTable/index.tsx
  packages/console/src/components/RoleUsersTransfer/SourceUsersBox.tsx
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/Users/index.tsx
  packages/console/src/utilities/url.ts
Labels: enhancement, size/s

#2905 fix(schemas): fix aleration script typo
  packages/schemas/alterations/next-1673349501-sms-sign-in-identifier-to-phone.ts
Labels: bugfix, size/xs

#2902 refactor(console): parse number to string by `String()`
  packages/console/src/components/AuditLogTable/index.tsx
  packages/console/src/components/RoleUsersTransfer/SourceUsersBox.tsx
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/Users/index.tsx
Labels: enhancement, size/s

#2901 refactor(core): migrate social library to factory mode
  packages/core/src/libraries/social.ts
  packages/core/src/routes/interaction/index.test.ts
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/utils/social-verification.test.ts
  packages/core/src/routes/interaction/utils/social-verification.ts
  packages/core/src/routes/interaction/verifications/identifier-payload-verification.test.ts
  packages/core/src/routes/interaction/verifications/identifier-payload-verification.ts
  packages/core/src/routes/interaction/verifications/identifier-verification.test.ts
  packages/core/src/routes/interaction/verifications/identifier-verification.ts
  packages/core/src/routes/interaction/verifications/user-identity-verification.test.ts
  packages/core/src/routes/interaction/verifications/user-identity-verification.ts
  packages/core/src/tenants/Libraries.ts
Labels: enhancement, size/l

#2903 refactor(core): migrate passcode library to factory mode
  packages/core/src/libraries/passcode.test.ts
  packages/core/src/libraries/passcode.ts
  packages/core/src/libraries/phrase.test.ts
  packages/core/src/routes/interaction/index.test.ts
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/utils/verification-code-validation.test.ts
  packages/core/src/routes/interaction/utils/verification-code-validation.ts
  packages/core/src/routes/interaction/verifications/identifier-payload-verification.test.ts
  packages/core/src/routes/interaction/verifications/identifier-payload-verification.ts
  packages/core/src/tenants/Libraries.ts
Labels: enhancement, size/l

#2906 refactor(core): remove deprecated library functions
  packages/core/package.json
  packages/core/src/libraries/connector.ts
  packages/core/src/libraries/shared.ts
  packages/core/src/libraries/sign-in-experience/index.ts
  packages/core/src/libraries/user.ts
  packages/core/src/routes/interaction/actions/submit-interaction.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/core/src/routes/interaction/index.test.ts
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/middleware/koa-interaction-sie.ts
  packages/core/src/routes/interaction/utils/find-user-by-identifier.test.ts
  packages/core/src/routes/interaction/utils/find-user-by-identifier.ts
  packages/core/src/routes/interaction/verifications/identifier-payload-verification.test.ts
  packages/core/src/routes/interaction/verifications/identifier-payload-verification.ts
  packages/core/src/routes/interaction/verifications/identifier-verification.test.ts
  packages/core/src/routes/interaction/verifications/identifier-verification.ts
  packages/core/src/routes/interaction/verifications/profile-verification.forgot-password.test.ts
  packages/core/src/routes/interaction/verifications/profile-verification.profile-exist.test.ts
  packages/core/src/routes/interaction/verifications/profile-verification.profile-registered.test.ts
  packages/core/src/routes/interaction/verifications/profile-verification.protected-identifier.test.ts
  packages/core/src/routes/interaction/verifications/profile-verification.ts
  packages/core/src/routes/interaction/verifications/user-identity-verification.test.ts
  packages/core/src/routes/interaction/verifications/user-identity-verification.ts
Labels: enhancement, size/xl

#2876 fix(console): fix sign-up identifier key
  packages/console/src/pages/SignInExperience/constants.ts
  packages/console/src/pages/SignInExperience/types.ts
Labels: bugfix, size/xs

#2881 test: add it for admin-user roles
  packages/core/src/queries/users-roles.ts
  packages/core/src/routes/admin-user.test.ts
  packages/integration-tests/src/api/admin-user.ts
  packages/integration-tests/src/tests/api/admin-user.roles.test.ts
Labels: testing, size/s

#2898 refactor(ui): simplify code verification hooks
  packages/ui/src/apis/interaction.ts
  packages/ui/src/containers/VerificationCode/index.tsx
  packages/ui/src/containers/VerificationCode/use-continue-flow-code-verification.ts
  packages/ui/src/containers/VerificationCode/use-continue-set-email-verification-code-validation.ts
  packages/ui/src/containers/VerificationCode/use-continue-set-phone-verification-code-validation.ts
  packages/ui/src/containers/VerificationCode/use-forgot-password-email-verification-code-validation.ts
  packages/ui/src/containers/VerificationCode/use-forgot-password-flow-code-verification.ts
  packages/ui/src/containers/VerificationCode/use-forgot-password-phone-verification-code-validation.ts
  packages/ui/src/containers/VerificationCode/use-general-verification-code-error-handler.ts
  packages/ui/src/containers/VerificationCode/use-identifier-error-alert.ts
  packages/ui/src/containers/VerificationCode/use-register-flow-code-verification.ts
  packages/ui/src/containers/VerificationCode/use-register-with-email-verification-code-validation.ts
  packages/ui/src/containers/VerificationCode/use-register-with-phone-verification-code-validation.ts
  packages/ui/src/containers/VerificationCode/use-sign-in-flow-code-verification.ts
  packages/ui/src/containers/VerificationCode/use-sign-in-with-phone-verification-code-validation.ts
  packages/ui/src/containers/VerificationCode/utils.ts
  packages/ui/src/pages/VerificationCode/index.tsx
  packages/ui/src/types/guard.ts
  packages/ui/src/types/index.ts
Labels: enhancement, size/xl

#2904 style(ui): replace the passwordless switch link pos
  packages/ui/src/assets/icons/switch-icon.svg
  packages/ui/src/components/TextLink/index.module.scss
  packages/ui/src/components/TextLink/index.tsx
  packages/ui/src/containers/PasswordSignInForm/PasswordlessSignInLink.tsx
  packages/ui/src/containers/PasswordSignInForm/index.module.scss
  packages/ui/src/containers/PasswordSignInForm/index.tsx
  packages/ui/src/containers/PasswordlessSwitch/index.tsx
  packages/ui/src/containers/VerificationCode/PasswordSignInLink.tsx
Labels: size/s

#2896 feat(console): assign roles to user
  packages/console/src/components/ModalLayout/index.tsx
  packages/console/src/components/UserRolesTransfer/components/SourceRoleItem/index.module.scss
  packages/console/src/components/UserRolesTransfer/components/SourceRoleItem/index.tsx
  packages/console/src/components/UserRolesTransfer/components/SourceRolesBox/index.module.scss
  packages/console/src/components/UserRolesTransfer/components/SourceRolesBox/index.tsx
  packages/console/src/components/UserRolesTransfer/components/TargetRoleItem/index.module.scss
  packages/console/src/components/UserRolesTransfer/components/TargetRoleItem/index.tsx
  packages/console/src/components/UserRolesTransfer/components/TargetRolesBox/index.module.scss
  packages/console/src/components/UserRolesTransfer/components/TargetRolesBox/index.tsx
  packages/console/src/components/UserRolesTransfer/index.module.scss
  packages/console/src/components/UserRolesTransfer/index.tsx
  packages/console/src/hooks/use-debounce.ts
  packages/console/src/pages/UserDetails/UserRoles/components/AssignRolesModal/index.tsx
  packages/console/src/pages/UserDetails/UserRoles/index.tsx
  packages/console/src/scss/transfer.module.scss
  packages/phrases/src/locales/de/translation/admin-console/user-details.ts
  packages/phrases/src/locales/en/translation/admin-console/user-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/user-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/user-details.ts
Labels: feature, size/xl

#2908 refactor(console): support pagination and search on the roles page
  packages/console/src/components/Pagination/index.tsx
  packages/console/src/components/Table/index.module.scss
  packages/console/src/components/Table/index.tsx
  packages/console/src/consts/index.ts
  packages/console/src/hooks/use-table-search-params.ts
  packages/console/src/pages/Roles/index.tsx
Labels: enhancement, size/l

#2911 fix(test): fix import file path
  packages/integration-tests/src/tests/api/admin-user.roles.test.ts
Labels: bugfix, size/xs

#2895 test: add IT for scopes
  packages/integration-tests/src/api/scope.ts
  packages/integration-tests/src/tests/api/resource.scope.test.ts
  packages/integration-tests/src/utils.ts
Labels: testing, size/m

#2900 test: add integration tests for roles
  packages/core/src/routes/role.test.ts
  packages/core/src/routes/role.ts
  packages/integration-tests/src/api/role.ts
  packages/integration-tests/src/tests/api/resource.scope.test.ts
  packages/integration-tests/src/tests/api/role.scope.test.ts
  packages/integration-tests/src/tests/api/role.test.ts
  packages/integration-tests/src/tests/api/role.user.test.ts
  packages/integration-tests/src/utils.ts
Labels: testing, size/l

#2907 refactor(core): remove deprecated query functions
  packages/core/src/libraries/user.ts
  packages/core/src/middleware/koa-check-demo-app.ts
  packages/core/src/oidc/adapter.test.ts
  packages/core/src/oidc/adapter.ts
  packages/core/src/oidc/init.ts
  packages/core/src/queries/application.ts
  packages/core/src/queries/connector.ts
  packages/core/src/queries/custom-phrase.ts
  packages/core/src/queries/log.ts
  packages/core/src/queries/oidc-model-instance.ts
  packages/core/src/queries/passcode.ts
  packages/core/src/queries/resource.ts
  packages/core/src/queries/roles-scopes.ts
  packages/core/src/queries/scope.ts
  packages/core/src/queries/setting.ts
  packages/core/src/queries/sign-in-experience.ts
  packages/core/src/queries/user.ts
  packages/core/src/routes/admin-user-role.test.ts
  packages/core/src/routes/admin-user-role.ts
  packages/core/src/routes/admin-user.ts
  packages/core/src/routes/application.test.ts
  packages/core/src/routes/application.ts
  packages/core/src/routes/custom-phrase.test.ts
  packages/core/src/routes/custom-phrase.ts
  packages/core/src/routes/dashboard.test.ts
  packages/core/src/routes/dashboard.ts
  packages/core/src/routes/log.test.ts
  packages/core/src/routes/log.ts
  packages/core/src/routes/role.test.ts
  packages/core/src/routes/role.ts
  packages/core/src/routes/setting.test.ts
  packages/core/src/routes/setting.ts
  packages/core/src/tenants/Tenant.ts
Labels: enhancement, size/xl

#2849 feat(core): add send and verify APIs for generic type verification code
  .changeset-staged/unlucky-months-clap.md
  .vscode/settings.json
  packages/core/src/libraries/passcode.test.ts
  packages/core/src/libraries/passcode.ts
  packages/core/src/queries/passcode.test.ts
  packages/core/src/queries/passcode.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/types/guard.ts
  packages/core/src/routes/interaction/types/index.ts
  packages/core/src/routes/interaction/utils/index.ts
  packages/core/src/routes/interaction/utils/verification-code-validation.ts
  packages/core/src/routes/interaction/verifications/identifier-payload-verification.ts
  packages/core/src/routes/verification-code.test.ts
  packages/core/src/routes/verification-code.ts
  packages/schemas/src/types/index.ts
  packages/schemas/src/types/interactions.ts
  packages/schemas/src/types/verification-code.ts
Labels: feature, size/l

#2875 feat(core): implement oidc getResourceServerInfo
  packages/core/src/libraries/user.test.ts
  packages/core/src/libraries/user.ts
  packages/core/src/oidc/init.ts
  packages/core/src/queries/roles-scopes.ts
  packages/core/src/queries/scope.ts
Labels: feature, size/s

#2916 feat(console): add assigned users column to roles table
  packages/console/src/pages/Roles/components/AssignedUsers/index.module.scss
  packages/console/src/pages/Roles/components/AssignedUsers/index.tsx
  packages/console/src/pages/Roles/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/roles.ts
  packages/phrases/src/locales/en/translation/admin-console/roles.ts
  packages/phrases/src/locales/fr/translation/admin-console/roles.ts
  packages/phrases/src/locales/ko/translation/admin-console/roles.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/roles.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/roles.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/roles.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/roles.ts
Labels: feature, size/s

#2918 fix(ui): format phone number in multiple places
  packages/ui/src/containers/VerificationCode/use-identifier-error-alert.ts
  packages/ui/src/containers/VerificationCode/use-register-flow-code-verification.ts
  packages/ui/src/containers/VerificationCode/use-sign-in-flow-code-verification.ts
Labels: bugfix, size/s

#2917 fix(ui): verification-code iteration fix
  packages/ui/src/components/Toast/index.tsx
  packages/ui/src/components/VerificationCode/index.test.tsx
  packages/ui/src/components/VerificationCode/index.tsx
  packages/ui/src/containers/VerificationCode/index.tsx
Labels: bugfix, size/m

#2910 style(ui): update social button style
  packages/ui/src/components/Button/SocialLinkButton.module.scss
  packages/ui/src/components/Button/index.module.scss
Labels: size/xs

#2912 refactor(console): role users transfer component
  packages/console/src/components/RoleUsersTransfer/SourceUsersBox.tsx
  packages/console/src/components/RoleUsersTransfer/TargetUsersBox.tsx
  packages/console/src/components/RoleUsersTransfer/components/SourceUserItem/index.module.scss
  packages/console/src/components/RoleUsersTransfer/components/SourceUserItem/index.tsx
  packages/console/src/components/RoleUsersTransfer/components/SourceUsersBox/index.module.scss
  packages/console/src/components/RoleUsersTransfer/components/SourceUsersBox/index.tsx
  packages/console/src/components/RoleUsersTransfer/components/TargetUserItem/index.module.scss
  packages/console/src/components/RoleUsersTransfer/components/TargetUserItem/index.tsx
  packages/console/src/components/RoleUsersTransfer/components/TargetUsersBox/index.module.scss
  packages/console/src/components/RoleUsersTransfer/components/TargetUsersBox/index.tsx
  packages/console/src/components/RoleUsersTransfer/index.module.scss
  packages/console/src/components/RoleUsersTransfer/index.tsx
  packages/console/src/pages/RoleDetails/RoleUsers/components/AssignUsersModal/index.tsx
Labels: enhancement, size/xl

#2909 style(ui): minor ui iteration
  packages/ui/src/assets/icons/radio-button-icon.svg
  packages/ui/src/components/BrandingHeader/index.module.scss
  packages/ui/src/components/Checkbox/index.tsx
  packages/ui/src/components/Input/phoneInput.module.scss
  packages/ui/src/components/TextLink/index.module.scss
  packages/ui/src/components/TextLink/index.tsx
  packages/ui/src/containers/AppNotification/index.module.scss
  packages/ui/src/containers/OtherMethodsLink/index.tsx
  packages/ui/src/containers/TermsOfUse/TermsOfUseConfirmModalContent/index.tsx
  packages/ui/src/containers/VerificationCode/index.module.scss
Labels: size/s

#2920 fix(schemas): modify management api default scope name
  packages/schemas/alterations/next-1673465463-ac-scope-name.ts
  packages/schemas/src/seeds/scope.ts
Labels: bugfix, size/s

#2925 feat(core): add search and pagination to role scopes
  packages/core/src/queries/scope.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/resource.test.ts
  packages/core/src/routes/resource.ts
  packages/core/src/routes/role.scope.test.ts
  packages/core/src/routes/role.scope.ts
  packages/core/src/routes/role.test.ts
  packages/core/src/routes/role.ts
Labels: feature, size/l

#2927 feat(core): add pagination and search to role users
  packages/core/src/queries/user.ts
  packages/core/src/routes/role.test.ts
  packages/core/src/routes/role.ts
Labels: feature, size/s

#2923 feat(core): add pagination and search to user roles api
  packages/core/src/queries/roles.ts
  packages/core/src/routes/admin-user-role.test.ts
  packages/core/src/routes/admin-user-role.ts
  packages/core/src/routes/role.test.ts
  packages/core/src/routes/role.ts
  packages/integration-tests/src/tests/api/admin-user.roles.test.ts
Labels: feature, size/s

#2919 fix(core): fix getResourceServerInfo userId
  packages/core/src/oidc/init.ts
  packages/integration-tests/src/tests/api/get-access-token.test.ts
  packages/integration-tests/src/utils.ts
  pnpm-lock.yaml
Labels: bugfix, size/s

#2914 refactor(console): role permissions transfer component
  packages/console/src/components/RolePermissionsTransfer/SourcePermissionsBox.tsx
  packages/console/src/components/RolePermissionsTransfer/TargetPermissionsBox.tsx
  packages/console/src/components/RolePermissionsTransfer/components/SourcePermissionItem/index.tsx
  packages/console/src/components/RolePermissionsTransfer/index.module.scss
  packages/console/src/components/RolePermissionsTransfer/index.tsx
  packages/console/src/components/RoleScopesTransfer/components/ResourceItem/index.module.scss
  packages/console/src/components/RoleScopesTransfer/components/ResourceItem/index.tsx
  packages/console/src/components/RoleScopesTransfer/components/SourceScopeItem/index.module.scss
  packages/console/src/components/RoleScopesTransfer/components/SourceScopeItem/index.tsx
  packages/console/src/components/RoleScopesTransfer/components/SourceScopesBox/index.module.scss
  packages/console/src/components/RoleScopesTransfer/components/SourceScopesBox/index.tsx
  packages/console/src/components/RoleScopesTransfer/components/TargetScopeItem/index.module.scss
  packages/console/src/components/RoleScopesTransfer/components/TargetScopeItem/index.tsx
  packages/console/src/components/RoleScopesTransfer/components/TargetScopesBox/index.module.scss
  packages/console/src/components/RoleScopesTransfer/components/TargetScopesBox/index.tsx
  packages/console/src/components/RoleScopesTransfer/index.module.scss
  packages/console/src/components/RoleScopesTransfer/index.tsx
  packages/console/src/components/RoleScopesTransfer/types.ts
  packages/console/src/pages/RoleDetails/RolePermissions/components/AssignPermissionsModal/index.tsx
  packages/console/src/pages/RoleDetails/RolePermissions/index.tsx
  packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
Labels: enhancement, size/xl

#2913 refactor: remove deprecated singleton instances
  packages/cli/src/commands/database/seed/oidc-config.ts
  packages/core/jest.setup.js
  packages/core/src/app/init.ts
  packages/core/src/database/find-entity-by-id.ts
  packages/core/src/database/insert-into.ts
  packages/core/src/database/row-count.ts
  packages/core/src/database/update-where.ts
  packages/core/src/env-set/index.ts
  packages/core/src/env-set/oidc.ts
  packages/core/src/index.ts
  packages/core/src/libraries/__mocks__/logto-config.ts
  packages/core/src/libraries/hook.ts
  packages/core/src/libraries/session.ts
  packages/core/src/libraries/user.ts
  packages/core/src/middleware/koa-auth.test.ts
  packages/core/src/middleware/koa-auth.ts
  packages/core/src/middleware/koa-error-handler.ts
  packages/core/src/middleware/koa-guard.ts
  packages/core/src/middleware/koa-root-proxy.ts
  packages/core/src/middleware/koa-spa-proxy.test.ts
  packages/core/src/middleware/koa-spa-proxy.ts
  packages/core/src/middleware/koa-spa-session-guard.ts
  packages/core/src/middleware/koa-welcome-proxy.test.ts
  packages/core/src/middleware/koa-welcome-proxy.ts
  packages/core/src/oidc/adapter.test.ts
  packages/core/src/oidc/adapter.ts
  packages/core/src/oidc/init.test.ts
  packages/core/src/oidc/init.ts
  packages/core/src/oidc/utils.test.ts
  packages/core/src/oidc/utils.ts
  packages/core/src/queries/oidc-model-instance.ts
  packages/core/src/queries/roles.ts
  packages/core/src/queries/user.ts
  packages/core/src/queries/users-roles.ts
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
  packages/core/src/routes/authn.test.ts
  packages/core/src/routes/authn.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/interaction/consent.test.ts
  packages/core/src/routes/interaction/consent.ts
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.test.ts
  packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.ts
  packages/core/src/tenants/Tenant.test.ts
  packages/core/src/tenants/Tenant.ts
  packages/core/src/tenants/TenantContext.ts
  packages/core/src/tenants/index.ts
  packages/core/src/test-utils/env-set.ts
  packages/core/src/test-utils/tenant.ts
  packages/schemas/src/types/logto-config.ts
Labels: enhancement, size/xl

#2933 refactor(console): make the `disabled` prop of the `CheckBox` optional
  packages/console/src/components/Checkbox/index.tsx
  packages/console/src/components/RoleScopesTransfer/components/ResourceItem/index.tsx
  packages/console/src/components/RoleScopesTransfer/components/SourceScopeItem/index.tsx
  packages/console/src/components/RoleUsersTransfer/components/SourceUserItem/index.tsx
  packages/console/src/components/UserRolesTransfer/components/SourceRoleItem/index.tsx
Labels: enhancement, size/xs

#2926 chore(core): add changeset files
  .changeset-staged/cyan-buses-trade.md
  .changeset-staged/large-windows-scream.md
  .changeset-staged/tender-maps-burn.md
Labels: chore, size/s

#2921 refactor(console): update rbac phrases
  packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/de/translation/admin-console/role-details.ts
  packages/phrases/src/locales/de/translation/admin-console/roles.ts
  packages/phrases/src/locales/de/translation/admin-console/user-details.ts
  packages/phrases/src/locales/en/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/en/translation/admin-console/role-details.ts
  packages/phrases/src/locales/en/translation/admin-console/roles.ts
  packages/phrases/src/locales/en/translation/admin-console/user-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/role-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/roles.ts
  packages/phrases/src/locales/fr/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/role-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/roles.ts
  packages/phrases/src/locales/ko/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/role-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/roles.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/role-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/roles.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/user-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/role-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/roles.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/role-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/roles.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/user-details.ts
Labels: enhancement, size/m

#2934 refactor(console): support pagination on rbac-related pages
  packages/console/src/components/PermissionsTable/index.module.scss
  packages/console/src/components/PermissionsTable/index.tsx
  packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/index.tsx
  packages/console/src/pages/RoleDetails/RolePermissions/index.tsx
  packages/console/src/pages/RoleDetails/RoleUsers/index.module.scss
  packages/console/src/pages/RoleDetails/RoleUsers/index.tsx
  packages/console/src/pages/UserDetails/UserRoles/index.module.scss
  packages/console/src/pages/UserDetails/UserRoles/index.tsx
Labels: enhancement, size/m

#2935 refactor(console): do not allow spaces in the permission name
  packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/en/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/api-resource-details.ts
  packages/toolkit/core-kit/src/regex.ts
Labels: enhancement, size/s

#2939 refactor(console): make scopes of the management api readonly
  packages/console/src/components/PermissionsTable/index.tsx
  packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/index.tsx
Labels: enhancement, size/s

#2949 fix(schemas): update sms alteration script
  packages/schemas/alterations/next-1673349501-sms-sign-in-identifier-to-phone.ts
Labels: bugfix, size/xs

#2947 style(console): role scopes transfer component
  packages/console/src/components/RoleScopesTransfer/components/ResourceItem/index.module.scss
  packages/console/src/components/RoleScopesTransfer/components/ResourceItem/index.tsx
  packages/console/src/components/RoleScopesTransfer/components/SourceScopeItem/index.module.scss
Labels: size/s

#2945 refactor(console): open resource and role details on current tab
  packages/console/src/components/PermissionsTable/index.tsx
  packages/console/src/pages/UserDetails/UserRoles/index.tsx
Labels: enhancement, size/s

#2948 refactor(console): update search placeholder
  packages/console/src/components/PermissionsTable/index.module.scss
  packages/console/src/components/PermissionsTable/index.tsx
  packages/console/src/components/Search/index.module.scss
  packages/console/src/components/Search/index.tsx
  packages/console/src/pages/RoleDetails/RoleUsers/index.tsx
  packages/console/src/pages/Roles/index.module.scss
  packages/console/src/pages/Roles/index.tsx
  packages/console/src/pages/UserDetails/UserRoles/index.tsx
  packages/console/src/pages/Users/index.module.scss
  packages/console/src/pages/Users/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/permissions.ts
  packages/phrases/src/locales/de/translation/admin-console/role-details.ts
  packages/phrases/src/locales/de/translation/admin-console/roles.ts
  packages/phrases/src/locales/de/translation/admin-console/user-details.ts
  packages/phrases/src/locales/de/translation/admin-console/users.ts
  packages/phrases/src/locales/en/translation/admin-console/permissions.ts
  packages/phrases/src/locales/en/translation/admin-console/role-details.ts
  packages/phrases/src/locales/en/translation/admin-console/roles.ts
  packages/phrases/src/locales/en/translation/admin-console/user-details.ts
  packages/phrases/src/locales/en/translation/admin-console/users.ts
  packages/phrases/src/locales/fr/translation/admin-console/permissions.ts
  packages/phrases/src/locales/fr/translation/admin-console/role-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/roles.ts
  packages/phrases/src/locales/fr/translation/admin-console/user-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/users.ts
  packages/phrases/src/locales/ko/translation/admin-console/permissions.ts
  packages/phrases/src/locales/ko/translation/admin-console/role-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/roles.ts
  packages/phrases/src/locales/ko/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/users.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/permissions.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/role-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/roles.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/users.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/permissions.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/role-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/roles.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/users.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/permissions.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/role-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/roles.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/user-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/users.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/permissions.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/role-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/roles.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/users.ts
Labels: enhancement, size/m

#2938 refactor(console): table hover behaviors
  packages/console/src/components/Table/index.module.scss
  packages/console/src/components/Table/index.tsx
  packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/LanguageDetails.tsx
Labels: enhancement, size/s

#2943 refactor(console): users page
  packages/console/src/components/ItemPreview/index.module.scss
  packages/console/src/pages/Users/index.module.scss
  packages/console/src/pages/Users/index.tsx
Labels: enhancement, size/m

#2941 test: add integration tests for generic verification APIs
  packages/integration-tests/src/__mocks__/connectors-mock.ts
  packages/integration-tests/src/api/interaction.ts
  packages/integration-tests/src/api/verification-code.ts
  packages/integration-tests/src/helpers/index.ts
  packages/integration-tests/src/tests/api/interaction/forgot-password.test.ts
  packages/integration-tests/src/tests/api/interaction/register-with-identifier.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-passcode-identifier.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier.test.ts
  packages/integration-tests/src/tests/api/verification-code.test.ts
Labels: testing, size/m

#2946 refactor(console): add deletion tip for rbac-related action buttons
  packages/console/src/components/PermissionsTable/index.tsx
  packages/console/src/components/Tip/Tooltip/index.module.scss
  packages/console/src/components/Tip/Tooltip/index.tsx
  packages/console/src/pages/RoleDetails/RoleUsers/index.tsx
  packages/console/src/pages/UserDetails/UserRoles/index.tsx
Labels: enhancement, size/s

#2942 feat(console,core)!: use rbac scope to control management resource
  packages/console/package.json
  packages/console/src/App.tsx
  packages/core/src/middleware/koa-auth.test.ts
  packages/core/src/middleware/koa-auth.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/interaction/consent.ts
  packages/demo-app/package.json
  packages/integration-tests/package.json
  pnpm-lock.yaml
Labels: feature, size/s

#2952 refactor(console): make descriptions of the role and permission required
  packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx
  packages/console/src/pages/RoleDetails/RoleSettings/index.tsx
Labels: enhancement, size/s

#2953 fix(schemas): add alteration for default ac scope
  packages/schemas/alterations/next-1673853579-ac-default-scope.ts
Labels: bugfix, size/s

#2915 style(ui): main page layout update
  packages/ui/src/containers/AppContent/index.module.scss
  packages/ui/src/containers/AppContent/index.tsx
  packages/ui/src/containers/SocialSignIn/SocialSignInList/index.test.tsx
  packages/ui/src/containers/SocialSignIn/SocialSignInList/index.tsx
  packages/ui/src/pages/Register/index.module.scss
  packages/ui/src/pages/Register/index.test.tsx
  packages/ui/src/pages/Register/index.tsx
  packages/ui/src/pages/SignIn/index.module.scss
  packages/ui/src/pages/SignIn/index.test.tsx
  packages/ui/src/pages/SignIn/index.tsx
Labels: size/m

#2950 feat(core): auto fill social email or phone
  packages/core/src/routes/interaction/index.test.ts
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/utils/interaction.ts
  packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.test.ts
  packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.ts
  packages/integration-tests/src/tests/api/interaction/social-interaction.test.ts
Labels: feature, size/xl

#2937 refactor(ui): remove bindWithSocial logic
  packages/core/src/routes/interaction/index.test.ts
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/utils/interaction.ts
  packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.test.ts
  packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.ts
  packages/integration-tests/src/tests/api/interaction/social-interaction.test.ts
  packages/ui/src/apis/interaction.ts
  packages/ui/src/apis/utils.ts
  packages/ui/src/containers/EmailForm/EmailContinue.test.tsx
  packages/ui/src/containers/EmailForm/EmailRegister.test.tsx
  packages/ui/src/containers/EmailForm/EmailResetPassword.test.tsx
  packages/ui/src/containers/EmailForm/EmailSignIn.test.tsx
  packages/ui/src/containers/EmailPassword/index.test.tsx
  packages/ui/src/containers/OtherMethodsLink/index.tsx
  packages/ui/src/containers/PasswordSignInForm/index.test.tsx
  packages/ui/src/containers/PhoneForm/PhoneContinue.test.tsx
  packages/ui/src/containers/PhoneForm/PhoneRegister.test.tsx
  packages/ui/src/containers/PhoneForm/PhoneResetPassword.test.tsx
  packages/ui/src/containers/PhoneForm/PhoneSignIn.test.tsx
  packages/ui/src/containers/PhonePassword/index.test.tsx
  packages/ui/src/containers/SocialCreateAccount/index.test.tsx
  packages/ui/src/containers/SocialCreateAccount/index.tsx
  packages/ui/src/containers/UsernameForm/SetUsername/index.test.tsx
  packages/ui/src/containers/UsernameForm/SetUsername/use-set-username.ts
  packages/ui/src/containers/UsernameSignIn/index.test.tsx
  packages/ui/src/containers/VerificationCode/index.test.tsx
  packages/ui/src/containers/VerificationCode/use-continue-flow-code-verification.ts
  packages/ui/src/containers/VerificationCode/use-sign-in-flow-code-verification.ts
  packages/ui/src/hooks/use-continue-sign-in-with-password.ts
  packages/ui/src/hooks/use-password-sign-in.ts
  packages/ui/src/hooks/use-required-profile-error-handler.ts
  packages/ui/src/hooks/use-send-verification-code.ts
  packages/ui/src/pages/Continue/SetPassword/index.test.tsx
  packages/ui/src/pages/Continue/SetPassword/use-set-password.ts
  packages/ui/src/pages/Continue/SetUsername/index.test.tsx
  packages/ui/src/pages/SignIn/index.tsx
  packages/ui/src/types/index.ts
Labels: enhancement, size/m

#2924 refactor(core,ui,schemas)!: refactor social identity verification payload
  packages/core/src/routes/interaction/index.test.ts
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/types/index.ts
  packages/core/src/routes/interaction/utils/interaction.ts
  packages/core/src/routes/interaction/verifications/identifier-payload-verification.test.ts
  packages/core/src/routes/interaction/verifications/identifier-payload-verification.ts
  packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.test.ts
  packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.ts
  packages/core/src/routes/interaction/verifications/user-identity-verification.test.ts
  packages/core/src/routes/interaction/verifications/user-identity-verification.ts
  packages/integration-tests/src/tests/api/interaction/social-interaction.test.ts
  packages/schemas/src/types/interactions.ts
  packages/ui/src/apis/interaction.ts
  packages/ui/src/apis/utils.ts
  packages/ui/src/containers/EmailForm/EmailContinue.test.tsx
  packages/ui/src/containers/EmailForm/EmailRegister.test.tsx
  packages/ui/src/containers/EmailForm/EmailResetPassword.test.tsx
  packages/ui/src/containers/EmailForm/EmailSignIn.test.tsx
  packages/ui/src/containers/EmailPassword/index.test.tsx
  packages/ui/src/containers/OtherMethodsLink/index.tsx
  packages/ui/src/containers/PasswordSignInForm/index.test.tsx
  packages/ui/src/containers/PhoneForm/PhoneContinue.test.tsx
  packages/ui/src/containers/PhoneForm/PhoneRegister.test.tsx
  packages/ui/src/containers/PhoneForm/PhoneResetPassword.test.tsx
  packages/ui/src/containers/PhoneForm/PhoneSignIn.test.tsx
  packages/ui/src/containers/PhonePassword/index.test.tsx
  packages/ui/src/containers/SocialCreateAccount/index.test.tsx
  packages/ui/src/containers/SocialCreateAccount/index.tsx
  packages/ui/src/containers/UsernameForm/SetUsername/index.test.tsx
  packages/ui/src/containers/UsernameForm/SetUsername/use-set-username.ts
  packages/ui/src/containers/UsernameSignIn/index.test.tsx
  packages/ui/src/containers/VerificationCode/index.test.tsx
  packages/ui/src/containers/VerificationCode/use-continue-flow-code-verification.ts
  packages/ui/src/containers/VerificationCode/use-sign-in-flow-code-verification.ts
  packages/ui/src/hooks/use-bind-social.ts
  packages/ui/src/hooks/use-continue-sign-in-with-password.ts
  packages/ui/src/hooks/use-password-sign-in.ts
  packages/ui/src/hooks/use-required-profile-error-handler.ts
  packages/ui/src/hooks/use-send-verification-code.ts
  packages/ui/src/pages/Continue/SetPassword/index.test.tsx
  packages/ui/src/pages/Continue/SetPassword/use-set-password.ts
  packages/ui/src/pages/Continue/SetUsername/index.test.tsx
  packages/ui/src/pages/SignIn/index.tsx
  packages/ui/src/types/guard.ts
  packages/ui/src/types/index.ts
Labels: enhancement, size/xl

#2957 fix(schemas): add alteration for default ac role scope
  packages/schemas/alterations/next-1673863835-ac-scope-role.ts
Labels: bugfix, size/s

#2951 refactor(console): audit logs table
  packages/console/src/components/AuditLogTable/index.module.scss
  packages/console/src/components/AuditLogTable/index.tsx
  packages/console/src/components/Table/index.tsx
  packages/console/src/hooks/use-page-search-parameters.ts
  packages/console/src/pages/AuditLogs/index.tsx
Labels: enhancement, size/l

#2962 fix(core): fix scope resource finder
  packages/core/src/routes/role.scope.ts
Labels: bugfix, size/xs

#2963 fix(core): fix roles count
  packages/core/src/queries/roles.ts
Labels: bugfix, size/xs

#2956 refactor(console): add empty state to transfers
  packages/console/src/components/DataEmpty/index.module.scss
  packages/console/src/components/DataEmpty/index.tsx
  packages/console/src/components/RoleScopesTransfer/components/SourceScopesBox/index.module.scss
  packages/console/src/components/RoleScopesTransfer/components/SourceScopesBox/index.tsx
  packages/console/src/components/RoleUsersTransfer/components/SourceUsersBox/index.module.scss
  packages/console/src/components/RoleUsersTransfer/components/SourceUsersBox/index.tsx
  packages/console/src/components/Table/TableEmpty.module.scss
  packages/console/src/components/Table/TableEmpty.tsx
  packages/console/src/components/UserRolesTransfer/components/SourceRolesBox/index.module.scss
  packages/console/src/components/UserRolesTransfer/components/SourceRolesBox/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/role-details.ts
  packages/phrases/src/locales/de/translation/admin-console/user-details.ts
  packages/phrases/src/locales/en/translation/admin-console/role-details.ts
  packages/phrases/src/locales/en/translation/admin-console/user-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/role-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/role-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/role-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/role-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/user-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/role-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/role-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/user-details.ts
Labels: enhancement, size/l

#2959 fix(console): hide table empty state on table error
  packages/console/src/components/Table/index.tsx
Labels: bugfix, size/xs

#2960 refactor(phrases): update the subtitle of the roles page
  packages/phrases/src/locales/de/translation/admin-console/roles.ts
  packages/phrases/src/locales/en/translation/admin-console/roles.ts
  packages/phrases/src/locales/fr/translation/admin-console/roles.ts
  packages/phrases/src/locales/ko/translation/admin-console/roles.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/roles.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/roles.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/roles.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/roles.ts
Labels: enhancement, size/s

#2964 style(console): role transfer component
  packages/console/src/components/RoleScopesTransfer/components/ResourceItem/index.tsx
  packages/console/src/components/RoleScopesTransfer/components/SourceScopeItem/index.module.scss
  packages/console/src/components/RoleScopesTransfer/components/TargetScopeItem/index.module.scss
Labels: size/xs

#2965 fix(schemas): fix ac admin id and scope
  packages/schemas/alterations/next-1673863835-ac-scope-role.ts
Labels: bugfix, size/s

#2967 feat(core): get all scopes for a role
  packages/core/src/routes/role.scope.test.ts
  packages/core/src/routes/role.scope.ts
  packages/integration-tests/src/tests/api/role.scope.test.ts
Labels: feature, size/s

#2969 fix(console): hide management api scope in role scopes transfer
  packages/console/src/components/RoleScopesTransfer/components/SourceScopesBox/index.tsx
Labels: bugfix, size/s

#2970 style(console): search input on user roles page
  packages/console/src/pages/UserDetails/UserRoles/index.module.scss
  packages/console/src/pages/UserDetails/UserRoles/index.tsx
Labels: size/xs

#2971 style(console): table loading style
  packages/console/src/components/Table/TableLoading.module.scss
  packages/console/src/components/Table/TableLoading.tsx
  packages/console/src/components/Table/index.tsx
Labels: size/s

#2954 fix(schemas): set scope description to required
  packages/integration-tests/src/tests/api/resource.scope.test.ts
  packages/schemas/alterations/next-1673940577-scope-description-not-null.ts
  packages/schemas/tables/scopes.sql
Labels: bugfix, size/s

#2955 fix: alteration issues
  .github/workflows/integration-test.yml
  .github/workflows/main.yml
  .scripts/check-alterations-sequence.js
  .scripts/compare-database.js
  package.json
  packages/schemas/alterations/next-1673882867-fix-alteration-issues.ts
  pnpm-lock.yaml
Labels: bugfix, size/m

#2977 style(console): role scopes item padding
  packages/console/src/components/RoleScopesTransfer/components/ResourceItem/index.module.scss
  packages/console/src/components/RoleScopesTransfer/components/SourceScopeItem/index.module.scss
Labels: size/xs

#2978 refactor(console): add error state to create role and permission form
  packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx
  packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
Labels: enhancement, size/xs

#2979 style(console): hidden role item info on overflow
  packages/console/src/components/UserRolesTransfer/components/TargetRoleItem/index.module.scss
Labels: size/xs

#2975 feat(cli): `rollback` command for alteration
  .changeset-staged/breezy-socks-joke.md
  .github/workflows/main.yml
  .scripts/check-alterations-sequence.js
  .scripts/compare-database.js
  packages/cli/package.json
  packages/cli/src/commands/database/alteration/index.test.ts
  packages/cli/src/commands/database/alteration/index.ts
  packages/cli/src/commands/database/alteration/version.ts
  packages/core/src/env-set/check-alteration-state.ts
  packages/schemas/alterations/1.0.0_beta.14-1667292082-remove-sign-in-method.ts
  packages/schemas/alterations/1.0.0_beta.14-1667900481-add-passcode-type-continue.ts
  packages/schemas/alterations/1.0.0_beta.18-1669091623-roles-and-scopes.ts
  packages/schemas/alterations/1.0.0_beta.18-1671080370-terms-of-use.ts
  packages/schemas/alterations/next-1672815959-user-roles.ts
  packages/schemas/alterations/next-1672820345-scope-resource-id.ts
  packages/schemas/alterations/next-1672901841-roles-and-scopes-not-null.ts
  packages/schemas/alterations/next-1673882867-fix-alteration-issues.ts
Labels: feature, size/m

#2976 ci: use current version for alteration test
  .github/workflows/main.yml
Labels: size/s

#2968 refactor(ui): update social bind account page content
  packages/phrases-ui/src/locales/de.ts
  packages/phrases-ui/src/locales/en.ts
  packages/phrases-ui/src/locales/fr.ts
  packages/phrases-ui/src/locales/ko.ts
  packages/phrases-ui/src/locales/pt-br.ts
  packages/phrases-ui/src/locales/pt-pt.ts
  packages/phrases-ui/src/locales/tr-tr.ts
  packages/phrases-ui/src/locales/zh-cn.ts
  packages/ui/src/components/Button/index.tsx
  packages/ui/src/containers/SocialLinkAccount/index.test.tsx
  packages/ui/src/containers/SocialLinkAccount/index.tsx
  packages/ui/src/pages/SocialLinkAccount/index.test.tsx
  packages/ui/src/pages/SocialLinkAccount/index.tsx
Labels: enhancement, size/l

#2972 feat!: migrate application role names to RBAC
  packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/core/src/__mocks__/index.ts
  packages/core/src/libraries/application.ts
  packages/core/src/oidc/init.ts
  packages/core/src/queries/applications-roles.ts
  packages/core/src/routes/application.test.ts
  packages/core/src/routes/application.ts
  packages/core/src/tenants/Libraries.ts
  packages/core/src/tenants/Queries.ts
  packages/schemas/alterations/next-1673941897-application-roles.ts
  packages/schemas/src/types/application.ts
  packages/schemas/src/types/index.ts
  packages/schemas/tables/applications.sql
  packages/schemas/tables/rolesapplications.sql
Labels: feature, size/l

#2973 fix(console): remove username admin tag
  packages/console/src/components/UserName/index.tsx
Labels: bugfix, size/s
