Repository logto-io/logto, pull requests merged in 2023-04, with the labels that each got.

#3656 fix(phrases): fix action change phrase
  packages/phrases-ui/src/locales/pt-br/action.ts
Labels: bugfix, size/xs

#3652 feat(cli): translation sync command
  .changeset/seven-dolphins-hammer.md
  packages/cli/package.json
  packages/cli/src/commands/translate/create.ts
  packages/cli/src/commands/translate/index.ts
  packages/cli/src/commands/translate/sync.ts
  packages/cli/src/commands/translate/utils.ts
  pnpm-lock.yaml
Labels: feature, size/m

#3647 refactor(ui): refactor ui hooks and provider structure
  packages/ui/src/App.tsx
  packages/ui/src/Layout/LandingPageLayout/index.tsx
  packages/ui/src/Providers/AppBoundary/hooks/use-color-theme.ts
  packages/ui/src/Providers/AppBoundary/hooks/use-custom-style.ts
  packages/ui/src/Providers/AppBoundary/hooks/use-meta-data.ts
  packages/ui/src/Providers/AppBoundary/hooks/use-theme.ts
  packages/ui/src/Providers/AppBoundary/index.tsx
  packages/ui/src/Providers/LoadingLayerProvider/index.tsx
  packages/ui/src/Providers/PageContextProvider/PageContext.tsx
  packages/ui/src/Providers/PageContextProvider/index.tsx
  packages/ui/src/Providers/PreviewProvider/index.tsx
  packages/ui/src/Providers/SettingsProvider/index.tsx
  packages/ui/src/Providers/SignInExperienceProvider/index.tsx
  packages/ui/src/Providers/ToastProvider/index.tsx
  packages/ui/src/__mocks__/RenderWithPageContext/ContextProvider.tsx
  packages/ui/src/__mocks__/RenderWithPageContext/SettingsProvider.tsx
  packages/ui/src/__mocks__/RenderWithPageContext/index.tsx
  packages/ui/src/components/LogtoSignature/index.tsx
  packages/ui/src/containers/SocialLanding/index.tsx
  packages/ui/src/containers/SocialSignInList/index.test.tsx
  packages/ui/src/containers/TermsAndPrivacy/TermsAndPrivacyConfirmModalContent/index.tsx
  packages/ui/src/containers/VerificationCode/index.test.tsx
  packages/ui/src/containers/VerificationCode/use-resend-verification-code.ts
  packages/ui/src/hooks/use-api.ts
  packages/ui/src/hooks/use-error-handler.ts
  packages/ui/src/hooks/use-native-message-listener.ts
  packages/ui/src/hooks/use-page-context.ts
  packages/ui/src/hooks/use-platform.ts
  packages/ui/src/hooks/use-required-profile-error-handler.ts
  packages/ui/src/hooks/use-sie.ts
  packages/ui/src/hooks/use-social-landing-handler.ts
  packages/ui/src/hooks/use-social-sign-in-listener.ts
  packages/ui/src/hooks/use-social.ts
  packages/ui/src/hooks/use-terms.ts
  packages/ui/src/hooks/use-toast.ts
  packages/ui/src/pages/Consent/index.tsx
  packages/ui/src/pages/ErrorPage/index.tsx
  packages/ui/src/pages/ForgotPassword/ForgotPasswordForm/index.test.tsx
  packages/ui/src/pages/ForgotPassword/index.test.tsx
  packages/ui/src/pages/Register/index.test.tsx
  packages/ui/src/pages/Register/index.tsx
  packages/ui/src/pages/ResetPassword/index.test.tsx
  packages/ui/src/pages/ResetPassword/use-reset-password.ts
  packages/ui/src/pages/SignIn/IdentifierSignInForm/index.test.tsx
  packages/ui/src/pages/SignIn/PasswordSignInForm/index.test.tsx
  packages/ui/src/pages/SignIn/index.test.tsx
  packages/ui/src/pages/SignIn/index.tsx
  packages/ui/src/pages/SignInPassword/PasswordForm/VerificationCodeLink.tsx
  packages/ui/src/pages/SignInPassword/index.test.tsx
  packages/ui/src/pages/SocialLanding/index.test.tsx
  packages/ui/src/pages/SocialLinkAccount/index.test.tsx
  packages/ui/src/pages/SocialSignInCallback/index.test.tsx
  packages/ui/src/pages/VerificationCode/index.test.tsx
Labels: enhancement, size/xl

#3590 feat(core): apply standard security headers 1/2
  .changeset-staged/shiny-crabs-wink.md
  packages/console/src/components/ImageWithErrorFallback/index.tsx
  packages/console/src/components/Markdown/components/GithubRawImage/index.tsx
  packages/console/src/components/Uploader/ImageUploader/index.tsx
  packages/core/package.json
  packages/core/src/middleware/koa-security-headers.ts
  packages/core/src/tenants/Tenant.ts
  packages/shared/src/env/UrlSet.test.ts
  packages/shared/src/env/UrlSet.ts
  packages/ui/src/Providers/IframeModalProvider/IframeModal/index.tsx
  packages/ui/src/components/BrandingHeader/index.tsx
  packages/ui/src/components/Button/SocialLinkButton.tsx
  packages/ui/src/containers/SocialLanding/index.tsx
  packages/ui/src/pages/Consent/index.tsx
  pnpm-lock.yaml
Labels: feature, size/m

#3648 refactor(console): improve color picker
  packages/console/package.json
  packages/console/src/components/ColorPicker/index.module.scss
  packages/console/src/components/ColorPicker/index.tsx
  packages/console/src/components/Dropdown/index.tsx
  pnpm-lock.yaml
Labels: enhancement, size/m

#3653 chore: update README.md
  README.md
Labels: chore, size/s

#3662 chore(cli): update translate command description
  packages/cli/src/commands/translate/create.ts
  packages/cli/src/commands/translate/sync.ts
Labels: chore, size/xs

#3651 refactor: update title in main flow and report pv for console sign-in
  packages/app-insights/package.json
  packages/cloud/src/index.ts
  packages/cloud/src/middleware/with-error-report.ts
  packages/console/src/App.tsx
  packages/core/src/app/init.ts
  packages/core/src/index.ts
  packages/core/src/middleware/koa-error-handler.ts
  packages/core/src/oidc/init.ts
  packages/phrases-ui/src/locales/de/description.ts
  packages/phrases-ui/src/locales/en/description.ts
  packages/phrases-ui/src/locales/es/description.ts
  packages/phrases-ui/src/locales/fr/description.ts
  packages/phrases-ui/src/locales/it/description.ts
  packages/phrases-ui/src/locales/ja/description.ts
  packages/phrases-ui/src/locales/ko/description.ts
  packages/phrases-ui/src/locales/pl-pl/description.ts
  packages/phrases-ui/src/locales/pt-br/description.ts
  packages/phrases-ui/src/locales/pt-pt/description.ts
  packages/phrases-ui/src/locales/ru/description.ts
  packages/phrases-ui/src/locales/tr-tr/description.ts
  packages/phrases-ui/src/locales/zh-cn/description.ts
  packages/phrases-ui/src/locales/zh-hk/description.ts
  packages/phrases-ui/src/locales/zh-tw/description.ts
  packages/schemas/src/consts/cookie.ts
  packages/schemas/src/consts/index.ts
  packages/schemas/src/types/cookie.ts
  packages/schemas/src/types/index.ts
  packages/ui/jest.config.ts
  packages/ui/package.json
  packages/ui/src/App.tsx
  packages/ui/src/Layout/AppLayout/index.tsx
  packages/ui/src/Layout/LandingPageLayout/index.tsx
  packages/ui/src/Layout/SecondaryPageLayout/index.tsx
  packages/ui/src/components/PageMeta/index.tsx
  packages/ui/src/index.html
  packages/ui/src/pages/ErrorPage/index.tsx
  packages/ui/src/pages/SocialSignInCallback/index.test.tsx
  packages/ui/src/pages/VerificationCode/index.test.tsx
  packages/ui/src/pages/VerificationCode/index.tsx
  packages/ui/src/utils/cookies.ts
  pnpm-lock.yaml
Labels: enhancement, size/m

#3664 refactor: conditional import app insights sdk
  packages/app-insights/src/node.ts
  packages/app-insights/src/react.ts
  packages/cloud/src/index.ts
  packages/console/src/App.tsx
  packages/core/src/index.ts
  packages/ui/src/App.tsx
Labels: enhancement, size/s

#3660 refactor: update pubilsh flow
  .changeset/README.md
  .changeset/config.json
  .github/workflows/changesets.yml
  .scripts/version.js
Labels: enhancement, size/s

#3661 refactor(core): add single-page apps as dependencies
  .changeset/config.json
  .pnpmfile.cjs
  packages/console/package.json
  packages/core/package.json
  packages/core/src/middleware/koa-spa-proxy.ts
  packages/demo-app/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: enhancement, size/s

#3663 refactor(ui): replace plain search string concatenate
  packages/ui/src/hooks/use-social-callback-handler.ts
Labels: enhancement, size/s

#3670 refactor(ui): leverage react-helmet to manage headers
  packages/ui/src/Layout/AppLayout/CustomContent.tsx
  packages/ui/src/Providers/AppBoundary/AppMeta.tsx
  packages/ui/src/Providers/AppBoundary/hooks/use-custom-style.ts
  packages/ui/src/Providers/AppBoundary/hooks/use-meta-data.ts
  packages/ui/src/Providers/AppBoundary/index.tsx
  packages/ui/src/Providers/AppBoundary/use-color-theme.ts
  packages/ui/src/Providers/SettingsProvider/index.tsx
  packages/ui/src/Providers/SettingsProvider/use-preview.ts
  packages/ui/src/Providers/SettingsProvider/use-sign-in-experience.ts
  packages/ui/src/Providers/SettingsProvider/use-theme.ts
  packages/ui/src/containers/VerificationCode/index.test.tsx
  packages/ui/src/hooks/use-sie.ts
  packages/ui/src/pages/VerificationCode/index.tsx
  packages/ui/src/utils/sign-in-experience.ts
Labels: enhancement, size/m

#3675 refactor(console): disable invalid pagination labels
  packages/console/src/components/Pagination/index.module.scss
  packages/console/src/components/Pagination/index.tsx
Labels: enhancement, size/s

#3678 fix(console): log event filter
  .changeset/curly-laws-hammer.md
  packages/console/src/components/AuditLogTable/components/EventSelector/index.tsx
  packages/console/src/components/AuditLogTable/index.tsx
  packages/console/src/consts/logs.ts
Labels: bugfix, size/m

#3680 feat(core): add management API to verify user password
  .changeset/new-windows-rescue.md
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
Labels: feature, size/s

#3674 chore(core,cloud): add cloud route security headers
  packages/cloud/package.json
  packages/cloud/src/index.ts
  packages/cloud/src/middleware/with-security-headers.ts
  packages/core/package.json
  packages/core/src/middleware/koa-security-headers.ts
  pnpm-lock.yaml
Labels: chore, size/m

#3672 refactor(console): remove redundant `hasError` prop from text input
  packages/console/src/components/MultiTextInput/index.tsx
  packages/console/src/components/TextInput/index.tsx
  packages/console/src/mdx-components/UriInputField/index.tsx
  packages/console/src/onboarding/pages/SignInExperience/index.tsx
  packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx
  packages/console/src/pages/ApiResourceDetails/ApiResourceSettings/index.tsx
  packages/console/src/pages/ApplicationDetails/components/Settings.tsx
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/ConnectorDetails/components/SenderTester/index.tsx
  packages/console/src/pages/Connectors/components/ConfigForm/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorForm/BasicForm.tsx
  packages/console/src/pages/Profile/containers/BasicUserInfoUpdateModal/index.tsx
  packages/console/src/pages/Profile/containers/ChangePasswordModal/index.tsx
  packages/console/src/pages/Profile/containers/LinkEmailModal/index.tsx
  packages/console/src/pages/Profile/containers/VerifyPasswordModal/index.tsx
  packages/console/src/pages/RoleDetails/RoleSettings/index.tsx
  packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
  packages/console/src/pages/SignInExperience/tabs/Branding/BrandingForm.tsx
  packages/console/src/pages/SignInExperience/tabs/Others/TermsForm.tsx
  packages/console/src/pages/UserDetails/UserSettings/index.tsx
  packages/console/src/pages/Users/components/CreateForm/index.tsx
Labels: enhancement, size/m

#3673 refactor(console): guard file types in the file input dialog box
  packages/console/src/components/Uploader/FileUploader/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/components.ts
  packages/phrases/src/locales/en/translation/admin-console/components.ts
  packages/phrases/src/locales/es/translation/admin-console/components.ts
  packages/phrases/src/locales/fr/translation/admin-console/components.ts
  packages/phrases/src/locales/it/translation/admin-console/components.ts
  packages/phrases/src/locales/ja/translation/admin-console/components.ts
  packages/phrases/src/locales/ko/translation/admin-console/components.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/components.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/components.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/components.ts
  packages/phrases/src/locales/ru/translation/admin-console/components.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/components.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/components.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/components.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/components.ts
Labels: enhancement, size/s

#3679 feat: central cache
  .changeset/spicy-pears-serve.md
  .dockerignore
  .gitignore
  packages/core/package.json
  packages/core/src/caches/index.ts
  packages/core/src/caches/types.ts
  packages/core/src/caches/well-known.ts
  packages/core/src/include.d/array.d.ts
  packages/core/src/index.ts
  packages/core/src/libraries/connector.ts
  packages/core/src/libraries/phrase.test.ts
  packages/core/src/libraries/phrase.ts
  packages/core/src/libraries/sign-in-experience/index.test.ts
  packages/core/src/libraries/sign-in-experience/index.ts
  packages/core/src/libraries/sign-in-experience/types.ts
  packages/core/src/queries/connector.test.ts
  packages/core/src/queries/connector.ts
  packages/core/src/queries/custom-phrase.ts
  packages/core/src/queries/sign-in-experience.test.ts
  packages/core/src/queries/sign-in-experience.ts
  packages/core/src/routes/custom-phrase.test.ts
  packages/core/src/routes/custom-phrase.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/core/src/routes/interaction/index.test.ts
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/middleware/koa-interaction-sie.ts
  packages/core/src/routes/well-known.phrases.content-language.test.ts
  packages/core/src/routes/well-known.phrases.test.ts
  packages/core/src/routes/well-known.test.ts
  packages/core/src/routes/well-known.ts
  packages/core/src/tenants/Libraries.ts
  packages/core/src/tenants/Queries.ts
  packages/core/src/tenants/Tenant.test.ts
  packages/core/src/tenants/Tenant.ts
  packages/core/src/tenants/index.ts
  packages/core/src/test-utils/tenant.ts
  packages/core/src/utils/connectors/types.ts
  packages/core/src/utils/request.ts
  packages/integration-tests/src/api/api.ts
  packages/integration-tests/src/tests/api/well-known.test.ts
  packages/shared/src/node/env/GlobalValues.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#3685 refactor(cli): use current directory as instance path if no input
  .changeset/wise-dingos-compete.md
  packages/cli/src/commands/connector/utils.ts
Labels: enhancement, size/xs

#3684 refactor: align console log
  packages/cli/package.json
  packages/cli/src/commands/connector/add.ts
  packages/cli/src/commands/connector/link.ts
  packages/cli/src/commands/connector/list.ts
  packages/cli/src/commands/connector/remove.ts
  packages/cli/src/commands/connector/utils.ts
  packages/cli/src/commands/database/alteration/index.ts
  packages/cli/src/commands/database/alteration/version.ts
  packages/cli/src/commands/database/config.ts
  packages/cli/src/commands/database/seed/cloud.ts
  packages/cli/src/commands/database/seed/index.ts
  packages/cli/src/commands/database/seed/oidc-config.ts
  packages/cli/src/commands/database/seed/tables.ts
  packages/cli/src/commands/database/system.ts
  packages/cli/src/commands/install/index.ts
  packages/cli/src/commands/install/utils.ts
  packages/cli/src/commands/translate/create.ts
  packages/cli/src/commands/translate/list-tags.ts
  packages/cli/src/commands/translate/openai.ts
  packages/cli/src/commands/translate/utils.ts
  packages/cli/src/connector/factories.ts
  packages/cli/src/connector/loader.ts
  packages/cli/src/database.ts
  packages/cli/src/index.ts
  packages/cli/src/utils.ts
  packages/core/package.json
  packages/core/src/app/init.ts
  packages/core/src/caches/index.ts
  packages/core/src/env-set/check-alteration-state.ts
  packages/core/src/event-listeners/index.ts
  packages/core/src/index.ts
  packages/core/src/libraries/hook.ts
  packages/core/src/libraries/logto-config.ts
  packages/core/src/middleware/koa-auth/index.ts
  packages/core/src/middleware/koa-error-handler.ts
  packages/core/src/middleware/koa-guard.ts
  packages/core/src/oidc/init.ts
  packages/core/src/tenants/SystemContext.ts
  packages/core/src/tenants/index.ts
  packages/core/src/test-utils/oidc-provider.ts
  packages/core/src/utils/console.ts
  packages/core/src/utils/tenant.ts
  packages/shared/src/node/env/ConsoleLog.ts
  packages/shared/src/node/env/index.ts
Labels: enhancement, size/l

#3645 feat(console): should mask confidential connector config values by default
  packages/console/src/components/TextInput/index.module.scss
  packages/console/src/components/TextInput/index.tsx
  packages/console/src/pages/Connectors/components/ConfigForm/index.tsx
  packages/toolkit/connector-kit/src/types.ts
Labels: feature, size/s

#3692 chore(phrases): improve wording in AC profile change password dialog
  packages/phrases/src/locales/de/translation/admin-console/profile.ts
  packages/phrases/src/locales/en/translation/admin-console/profile.ts
  packages/phrases/src/locales/es/translation/admin-console/profile.ts
  packages/phrases/src/locales/fr/translation/admin-console/profile.ts
  packages/phrases/src/locales/it/translation/admin-console/profile.ts
  packages/phrases/src/locales/ja/translation/admin-console/profile.ts
  packages/phrases/src/locales/ko/translation/admin-console/profile.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/profile.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/profile.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/profile.ts
  packages/phrases/src/locales/ru/translation/admin-console/profile.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/profile.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/profile.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/profile.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/profile.ts
Labels: chore, size/s

#3698 feat(core): provide management API to detect if user has password
  .changeset/popular-wasps-begin.md
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
Labels: feature, size/s

#3695 refactor(cli): improve translation cli
  packages/cli/src/commands/translate/create.ts
  packages/cli/src/commands/translate/openai.ts
  packages/cli/src/commands/translate/prompts.ts
  packages/cli/src/commands/translate/sync.ts
  packages/cli/src/commands/translate/utils.ts
  packages/phrases/src/locales/fr/translation/admin-console/components.ts
  packages/phrases/src/locales/ja/translation/admin-console/components.ts
  packages/phrases/src/locales/ko/translation/admin-console/components.ts
  packages/phrases/src/locales/ru/translation/admin-console/components.ts
Labels: enhancement, size/l

#3696 feat(console): suspend user
  .changeset/sweet-dots-ring.md
  packages/console/src/assets/images/forbidden.svg
  packages/console/src/assets/images/shield.svg
  packages/console/src/components/ItemPreview/index.module.scss
  packages/console/src/components/ItemPreview/index.tsx
  packages/console/src/components/RoleUsersTransfer/components/SourceUserItem/index.module.scss
  packages/console/src/components/RoleUsersTransfer/components/SourceUserItem/index.tsx
  packages/console/src/components/RoleUsersTransfer/components/TargetUserItem/index.module.scss
  packages/console/src/components/RoleUsersTransfer/components/TargetUserItem/index.tsx
  packages/console/src/pages/RoleDetails/RoleUsers/index.tsx
  packages/console/src/pages/UserDetails/index.module.scss
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/pages/Users/components/SuspendedTag/index.module.scss
  packages/console/src/pages/Users/components/SuspendedTag/index.tsx
  packages/console/src/pages/Users/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/user-details.ts
  packages/phrases/src/locales/en/translation/admin-console/user-details.ts
  packages/phrases/src/locales/es/translation/admin-console/user-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/user-details.ts
  packages/phrases/src/locales/it/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/user-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/user-details.ts
Labels: feature, size/l

#3694 feat(console): create user by multiple identifiers
  .changeset/slow-kings-march.md
  packages/console/src/components/UserAccountInformation/index.module.scss
  packages/console/src/components/UserAccountInformation/index.tsx
  packages/console/src/pages/ConnectorDetails/components/SenderTester/index.tsx
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/pages/Users/components/CreateForm/index.module.scss
  packages/console/src/pages/Users/components/CreateForm/index.tsx
  packages/console/src/utils/phone.ts
  packages/core/src/libraries/user.ts
  packages/phrases/src/locales/de/translation/admin-console/errors.ts
  packages/phrases/src/locales/de/translation/admin-console/user-details.ts
  packages/phrases/src/locales/de/translation/admin-console/users.ts
  packages/phrases/src/locales/en/translation/admin-console/errors.ts
  packages/phrases/src/locales/en/translation/admin-console/user-details.ts
  packages/phrases/src/locales/en/translation/admin-console/users.ts
  packages/phrases/src/locales/es/translation/admin-console/errors.ts
  packages/phrases/src/locales/es/translation/admin-console/user-details.ts
  packages/phrases/src/locales/es/translation/admin-console/users.ts
  packages/phrases/src/locales/fr/translation/admin-console/errors.ts
  packages/phrases/src/locales/fr/translation/admin-console/user-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/users.ts
  packages/phrases/src/locales/it/translation/admin-console/errors.ts
  packages/phrases/src/locales/it/translation/admin-console/user-details.ts
  packages/phrases/src/locales/it/translation/admin-console/users.ts
  packages/phrases/src/locales/ja/translation/admin-console/errors.ts
  packages/phrases/src/locales/ja/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/users.ts
  packages/phrases/src/locales/ko/translation/admin-console/errors.ts
  packages/phrases/src/locales/ko/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/users.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/errors.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/users.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/errors.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/users.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/errors.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/users.ts
  packages/phrases/src/locales/ru/translation/admin-console/errors.ts
  packages/phrases/src/locales/ru/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/users.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/errors.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/user-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/users.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/errors.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/users.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/errors.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/users.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/errors.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/users.ts
Labels: feature, size/l

#3693 fix(console): adding social connector should mark related get-started action item as completed
  .changeset/little-carpets-change.md
  packages/console/src/pages/Connectors/components/Guide/index.tsx
  packages/schemas/alterations/next-1681267285-fix-get-started-passwordless-status.ts
Labels: bugfix, size/s

#3703 chore: update changesets config
  .changeset/config.json
  .github/workflows/changesets.yml
Labels: chore, size/s

#3704 ci: remove duplicate version script
  .github/workflows/changesets.yml
Labels: size/xs

#3701 refactor(console): add user identity display rule
  packages/console/src/components/RoleUsersTransfer/components/SourceUserItem/index.module.scss
  packages/console/src/components/RoleUsersTransfer/components/SourceUserItem/index.tsx
  packages/console/src/components/RoleUsersTransfer/components/TargetUserItem/index.module.scss
  packages/console/src/components/RoleUsersTransfer/components/TargetUserItem/index.tsx
  packages/console/src/pages/RoleDetails/RoleUsers/index.tsx
  packages/console/src/pages/UserDetails/index.module.scss
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/pages/Users/index.tsx
  packages/console/src/utils/user.ts
Labels: enhancement, size/s

#3707 chore: specify versions for workspace protocol
  package.json
  packages/cli/package.json
  packages/cloud/package.json
  packages/connectors/connector-alipay-native/package.json
  packages/connectors/connector-alipay-web/package.json
  packages/connectors/connector-aliyun-dm/package.json
  packages/connectors/connector-aliyun-sms/package.json
  packages/connectors/connector-apple/package.json
  packages/connectors/connector-aws-ses/package.json
  packages/connectors/connector-azuread/package.json
  packages/connectors/connector-discord/package.json
  packages/connectors/connector-facebook/package.json
  packages/connectors/connector-feishu-web/package.json
  packages/connectors/connector-github/package.json
  packages/connectors/connector-google/package.json
  packages/connectors/connector-kakao/package.json
  packages/connectors/connector-logto-email/package.json
  packages/connectors/connector-logto-sms/package.json
  packages/connectors/connector-logto-social-demo/package.json
  packages/connectors/connector-mock-email-alternative/package.json
  packages/connectors/connector-mock-email/package.json
  packages/connectors/connector-mock-sms/package.json
  packages/connectors/connector-mock-social/package.json
  packages/connectors/connector-naver/package.json
  packages/connectors/connector-oauth2/package.json
  packages/connectors/connector-oidc/package.json
  packages/connectors/connector-saml/package.json
  packages/connectors/connector-sendgrid-email/package.json
  packages/connectors/connector-smtp/package.json
  packages/connectors/connector-tencent-sms/package.json
  packages/connectors/connector-twilio-sms/package.json
  packages/connectors/connector-wechat-native/package.json
  packages/connectors/connector-wechat-web/package.json
  packages/console/package.json
  packages/core/package.json
  packages/create/package.json
  packages/demo-app/package.json
  packages/integration-tests/package.json
  packages/phrases-ui/package.json
  packages/phrases/package.json
  packages/schemas/package.json
  packages/shared/package.json
  packages/toolkit/connector-kit/package.json
  packages/toolkit/core-kit/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: chore, size/m

#3706 refactor(core): improve cache behavior
  packages/core/src/caches/index.test.ts
  packages/core/src/caches/index.ts
  packages/core/src/caches/well-known.ts
  packages/core/src/index.ts
Labels: enhancement, size/s

#3700 refactor(core): reorg connector routes and UTs
  packages/core/src/routes/connector/config-testing.test.ts
  packages/core/src/routes/connector/config-testing.ts
  packages/core/src/routes/connector/index.delete.test.ts
  packages/core/src/routes/connector/index.get.test.ts
  packages/core/src/routes/connector/index.patch.test.ts
  packages/core/src/routes/connector/index.post.test.ts
  packages/core/src/routes/connector/index.ts
  packages/core/src/routes/init.ts
Labels: enhancement, size/xl

#3708 style(console): update modal overlay paddings
  packages/console/src/scss/modal.module.scss
Labels: size/xs

#3709 style(console): update permission table style
  packages/console/src/components/PermissionsTable/index.module.scss
  packages/console/src/components/PermissionsTable/index.tsx
  packages/console/src/components/Table/index.module.scss
Labels: size/s

#3711 chore: avoid using "primary" for email and phone identifiers
  packages/phrases/src/locales/de/translation/admin-console/user-details.ts
  packages/phrases/src/locales/en/translation/admin-console/user-details.ts
  packages/phrases/src/locales/es/translation/admin-console/user-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/user-details.ts
  packages/phrases/src/locales/it/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/user-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/user-details.ts
Labels: chore, size/s

#3713 chore: update README.md
  README.md
Labels: chore, size/xs

#3699 fix(connector,phrases): cloud sms/email connectors error message
  packages/connectors/connector-aliyun-dm/src/index.ts
  packages/connectors/connector-aliyun-sms/src/index.ts
  packages/connectors/connector-aws-ses/src/index.ts
  packages/connectors/connector-sendgrid-email/src/index.ts
  packages/connectors/connector-twilio-sms/src/index.ts
  packages/core/src/middleware/koa-connector-error-handler.test.ts
  packages/core/src/middleware/koa-connector-error-handler.ts
  packages/phrases/src/locales/de/errors/connector.ts
  packages/phrases/src/locales/en/errors/connector.ts
  packages/phrases/src/locales/es/errors/connector.ts
  packages/phrases/src/locales/fr/errors/connector.ts
  packages/phrases/src/locales/it/errors/connector.ts
  packages/phrases/src/locales/ja/errors/connector.ts
  packages/phrases/src/locales/ko/errors/connector.ts
  packages/phrases/src/locales/pl-pl/errors/connector.ts
  packages/phrases/src/locales/pt-br/errors/connector.ts
  packages/phrases/src/locales/pt-pt/errors/connector.ts
  packages/phrases/src/locales/ru/errors/connector.ts
  packages/phrases/src/locales/tr-tr/errors/connector.ts
  packages/phrases/src/locales/zh-cn/errors/connector.ts
  packages/phrases/src/locales/zh-hk/errors/connector.ts
  packages/phrases/src/locales/zh-tw/errors/connector.ts
  packages/toolkit/connector-kit/src/types.ts
Labels: bugfix, size/m

#3710 refactor(core,cloud): add ApplicationInsights URL to CSP directive
  packages/cloud/src/middleware/with-security-headers.ts
  packages/core/src/middleware/koa-security-headers.ts
Labels: enhancement, size/s

#3714 docs(connector): update connector docs links
  packages/connectors/connector-alipay-native/README.md
  packages/connectors/connector-alipay-web/README.md
  packages/connectors/connector-aliyun-dm/README.md
  packages/connectors/connector-aliyun-sms/README.md
  packages/connectors/connector-apple/README.md
  packages/connectors/connector-aws-ses/README.md
  packages/connectors/connector-github/README.md
  packages/connectors/connector-sendgrid-email/README.md
  packages/connectors/connector-smtp/README.md
  packages/connectors/connector-tencent-sms/README.md
  packages/connectors/connector-twilio-sms/README.md
  packages/connectors/connector-wechat-native/README.md
  packages/connectors/connector-wechat-web/README.md
Labels: size/s

#3716 chore: add changeset
  .changeset/rich-forks-heal.md
Labels: chore, size/xs

#3717 chore: allow setting appinsights string in core Dockerfile
  .github/workflows/release.yml
  Dockerfile
Labels: chore, size/xs

#3719 fix(console): remove react warning from Switch component
  packages/console/src/components/Switch/index.tsx
Labels: bugfix, size/xs

#3720 fix(console): remove react warning from connector config form
  packages/console/src/components/CodeEditor/index.tsx
  packages/console/src/components/Select/index.tsx
  packages/console/src/components/TextInput/index.tsx
  packages/console/src/components/Textarea/index.tsx
  packages/console/src/pages/Connectors/components/ConfigForm/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorForm/ConfigForm.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/SignUpForm.tsx
Labels: bugfix, size/s

#3715 fix(core): use client s3 sdk
  packages/core/package.json
  packages/core/src/utils/storage/s3-storage.ts
  pnpm-lock.yaml
Labels: bugfix, size/s

#3726 refactor(ui): use swc for testing
  packages/integration-tests/jest.setup.js
  packages/integration-tests/package.json
  packages/integration-tests/src/utils.ts
  packages/ui/jest.config.ts
  packages/ui/package.json
  packages/ui/src/jest.setup.ts
  packages/ui/tsconfig.test.json
  pnpm-lock.yaml
Labels: enhancement, size/s

#3725 feat(app-insights): click plugin, React context and hook
  .changeset/kind-spoons-retire.md
  .changeset/witty-beers-complain.md
  commitlint.config.cjs
  packages/app-insights/package.json
  packages/app-insights/src/react.ts
  packages/app-insights/src/react/AppInsightsReact.ts
  packages/app-insights/src/react/context.tsx
  packages/app-insights/src/react/index.ts
  packages/app-insights/src/react/use-app-insights.ts
  packages/app-insights/src/react/utils.ts
  packages/app-insights/tsconfig.build.json
  packages/app-insights/tsconfig.json
  packages/console/src/App.tsx
  packages/console/src/components/PageMeta/index.tsx
  packages/console/src/hooks/use-track-user-id.ts
  packages/console/src/onboarding/pages/About/index.tsx
  packages/console/src/onboarding/pages/Congrats/index.tsx
  packages/console/src/onboarding/pages/SignInExperience/index.tsx
  packages/console/src/onboarding/pages/Welcome/index.tsx
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/AuditLogDetails/index.tsx
  packages/console/src/pages/AuditLogs/index.tsx
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/Connectors/index.tsx
  packages/console/src/pages/Dashboard/index.tsx
  packages/console/src/pages/GetStarted/index.tsx
  packages/console/src/pages/Profile/index.tsx
  packages/console/src/pages/RoleDetails/index.tsx
  packages/console/src/pages/Roles/index.tsx
  packages/console/src/pages/SignInExperience/index.tsx
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/pages/Users/index.tsx
  packages/ui/src/App.tsx
  packages/ui/src/components/PageMeta/index.tsx
  pnpm-lock.yaml
Labels: feature, size/l

#3712 chore(cloud): add payload to service log
  packages/cloud/src/libraries/services.ts
  packages/cloud/src/queries/service-logs.ts
  packages/cloud/src/routes/service.test.ts
  packages/cloud/src/routes/services.ts
  packages/cloud/src/utils/guard.ts
Labels: chore, size/s

#3737 fix(console): fix react data router
  packages/console/src/pages/Main/index.tsx
Labels: bugfix, size/s

#3723 feat(connector): make official connectors scope configurable
  packages/connectors/connector-alipay-web/README.md
  packages/connectors/connector-alipay-web/src/constant.ts
  packages/connectors/connector-alipay-web/src/index.ts
  packages/connectors/connector-alipay-web/src/types.ts
  packages/connectors/connector-discord/README.md
  packages/connectors/connector-discord/src/constant.ts
  packages/connectors/connector-discord/src/index.ts
  packages/connectors/connector-discord/src/types.ts
  packages/connectors/connector-facebook/README.md
  packages/connectors/connector-facebook/src/constant.ts
  packages/connectors/connector-facebook/src/index.ts
  packages/connectors/connector-facebook/src/types.ts
  packages/connectors/connector-github/README.md
  packages/connectors/connector-github/src/constant.ts
  packages/connectors/connector-github/src/index.ts
  packages/connectors/connector-github/src/types.ts
  packages/connectors/connector-google/README.md
  packages/connectors/connector-google/src/constant.ts
  packages/connectors/connector-google/src/index.ts
  packages/connectors/connector-google/src/types.ts
  packages/connectors/connector-wechat-web/README.md
  packages/connectors/connector-wechat-web/src/constant.ts
  packages/connectors/connector-wechat-web/src/index.ts
  packages/connectors/connector-wechat-web/src/types.ts
Labels: feature, size/m

#3742 ci: update release workflow
  .github/workflows/clean-up-images.yml
  .github/workflows/release.yml
Labels: size/s

#3736 fix(console): switch component
  packages/console/src/components/Switch/index.tsx
  packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx
Labels: bugfix, size/s

#3730 refactor(schemas,core,console): use JsonObject instead of ArbitraryObject
  packages/console/package.json
  packages/console/src/components/ConnectorLogo/index.tsx
  packages/console/src/components/SignInExperiencePreview/index.tsx
  packages/console/src/components/UserAccountInformation/index.tsx
  packages/console/src/hooks/use-connector-in-use.ts
  packages/console/src/hooks/use-enabled-connector-types.ts
  packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx
  packages/console/src/pages/ConnectorDetails/components/ConnectorTabs/index.tsx
  packages/console/src/pages/ConnectorDetails/components/DeleteConnectorConfirmModal/index.tsx
  packages/console/src/pages/Connectors/components/CreateForm/index.tsx
  packages/console/src/pages/Connectors/components/Guide/index.tsx
  packages/console/src/pages/Connectors/index.tsx
  packages/console/src/pages/Profile/components/LinkAccountSection/index.tsx
  packages/console/src/pages/UserDetails/UserSettings/index.tsx
  packages/console/src/utils/user.ts
  packages/core/src/routes-me/user.ts
  packages/core/src/routes/admin-user.ts
  packages/core/src/routes/authn.ts
  packages/core/src/routes/connector/config-testing.ts
  packages/core/src/utils/zod.test.ts
  packages/core/src/utils/zod.ts
  packages/schemas/alterations/1.0.0-1678716747-service-logs.ts
  packages/schemas/alterations/1.0.0_beta.10-1-logto-config.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/types/interactions.ts
  packages/schemas/tables/connectors.sql
  packages/schemas/tables/logto_configs.sql
  packages/schemas/tables/service_logs.sql
  packages/schemas/tables/systems.sql
  packages/schemas/tables/users.sql
  pnpm-lock.yaml
Labels: enhancement, size/s

#3731 fix(console): code editor error and line number header width
  packages/console/src/components/CodeEditor/index.tsx
Labels: bugfix, size/xs

#3743 refactor(console,ui,demo-app): fix i18next types
  packages/console/jest.config.ts
  packages/console/jest.setup.ts
  packages/console/package.json
  packages/console/src/components/Alert/index.tsx
  packages/console/src/components/Button/index.tsx
  packages/console/src/components/CardTitle/index.tsx
  packages/console/src/components/DetailsPage/index.tsx
  packages/console/src/components/DynamicT/index.test.tsx
  packages/console/src/components/DynamicT/index.tsx
  packages/console/src/components/FormCard/index.tsx
  packages/console/src/components/PermissionsTable/index.tsx
  packages/console/src/components/RadioGroup/Radio.tsx
  packages/console/src/components/Table/TablePlaceholder.tsx
  packages/console/src/components/UserAccountInformation/index.tsx
  packages/console/src/containers/AppContent/components/SubMenu/index.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/components/Contact/index.tsx
  packages/console/src/include.d/i18next.d.ts
  packages/console/src/onboarding/components/CardSelector/MultiCardSelector/CardItem.tsx
  packages/console/src/onboarding/components/ReachLogto/index.tsx
  packages/console/src/pages/Connectors/components/ConnectorTypeColumn/index.tsx
  packages/console/src/pages/GetStarted/index.tsx
  packages/console/src/pages/Profile/components/CardContent/index.tsx
  packages/console/src/pages/Profile/components/MainFlowLikeModal/index.tsx
  packages/console/tsconfig.json
  packages/demo-app/src/include.d/react-i18next.d.ts
  packages/ui/src/Layout/SecondaryPageLayout/index.tsx
  packages/ui/src/components/BrandingHeader/index.tsx
  packages/ui/src/components/Button/index.tsx
  packages/ui/src/components/DynamicT/index.test.tsx
  packages/ui/src/components/DynamicT/index.tsx
  packages/ui/src/components/Notification/InlineNotification/index.tsx
  packages/ui/src/containers/SocialLinkAccount/index.tsx
  packages/ui/src/include.d/i18next.d.ts
  packages/ui/src/jest.setup.ts
  packages/ui/src/pages/ErrorPage/index.tsx
  pnpm-lock.yaml
Labels: enhancement, size/l

#3744 fix(connector): support crypto.getRandomValues in connectors
  packages/connectors/templates/preset/rollup.config.js
Labels: bugfix, size/xs

#3750 chore: add changesets
  .changeset/lemon-windows-call.md
  .changeset/violet-planes-juggle.md
Labels: chore, size/s

#3755 chore: update README.md
  README.md
Labels: chore, size/xs

#3756 refactor(console): add useMemo to resources and scopes
  packages/console/src/App.tsx
Labels: enhancement, size/s

#3748 refactor: use transaction to create user
  packages/core/src/libraries/user.ts
Labels: enhancement, size/s

#3746 chore(test): add ITs for logto-config APIs
  packages/integration-tests/src/api/index.ts
  packages/integration-tests/src/api/logto-config.ts
  packages/integration-tests/src/tests/api/logto-config.test.ts
Labels: chore, size/s

#3763 fix(console): language dropdown height should be calculated properly on first load
  packages/console/src/containers/AppContent/components/SubMenu/index.tsx
Labels: bugfix, size/s

#3779 refactor(cli): fallback to latest when current version is unavailable
  packages/cli/src/commands/install/utils.ts
Labels: enhancement, size/s

#3768 chore: update contribution guide connector part
  .github/CONTRIBUTING.md
Labels: chore, size/xs

#3764 feat: add overlay scrollbar on sidebar and main content
  packages/console/src/containers/ConsoleContent/Sidebar/index.tsx
  packages/console/src/containers/ConsoleContent/index.module.scss
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/scss/overlayscrollbars.scss
Labels: feature, size/m

#3760 chore(toolkit): add UTs for connector-kit
  packages/toolkit/connector-kit/jest.config.js
  packages/toolkit/connector-kit/package.json
  packages/toolkit/connector-kit/src/index.test.ts
  packages/toolkit/connector-kit/tsconfig.build.json
  packages/toolkit/connector-kit/tsconfig.test.json
  pnpm-lock.yaml
Labels: chore, size/s

#3774 chore(test): add SIE API guard
  packages/core/src/routes/sign-in-experience/index.ts
Labels: chore, size/s

#3772 chore(test): complete custom phrase API guard and add ITs
  packages/core/src/routes/custom-phrase.ts
  packages/integration-tests/package.json
  packages/integration-tests/src/api/custom-phrase.ts
  packages/integration-tests/src/tests/api/custom-phrase.test.ts
  pnpm-lock.yaml
Labels: chore, size/m

#3745 feat(console): add `CheckboxGroup`
  packages/console/src/components/Checkbox/Checkbox/index.module.scss
  packages/console/src/components/Checkbox/Checkbox/index.tsx
  packages/console/src/components/Checkbox/CheckboxGroup/index.module.scss
  packages/console/src/components/Checkbox/CheckboxGroup/index.tsx
  packages/console/src/components/Checkbox/index.tsx
Labels: feature, size/l

#3753 refactor(console): list pages
  packages/console/src/components/ListPage/index.tsx
  packages/console/src/components/PageMeta/index.tsx
  packages/console/src/components/Table/index.tsx
  packages/console/src/pages/ApiResources/index.module.scss
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/Applications/index.module.scss
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/AuditLogs/index.tsx
  packages/console/src/pages/Connectors/index.tsx
  packages/console/src/pages/Profile/index.tsx
  packages/console/src/pages/Roles/index.tsx
  packages/console/src/pages/Users/index.tsx
  packages/console/src/scss/page-layout.module.scss
Labels: enhancement, size/xl

#3762 chore(schemas,test,core): add IT to ensure mock connectors are installed
  packages/core/src/routes/connector/index.ts
  packages/integration-tests/src/api/connector.ts
  packages/integration-tests/src/tests/api/connector.test.ts
  packages/schemas/src/types/connector.ts
Labels: chore, size/s

#3786 fix(cloud): fix cloud admin ac iframe src error
  packages/cloud/src/middleware/with-security-headers.ts
Labels: bugfix, size/xs

#3791 chore(phrases): add webhook phrases
  packages/phrases/src/locales/de/translation/admin-console/index.ts
  packages/phrases/src/locales/de/translation/admin-console/tabs.ts
  packages/phrases/src/locales/de/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/de/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/en/translation/admin-console/index.ts
  packages/phrases/src/locales/en/translation/admin-console/tabs.ts
  packages/phrases/src/locales/en/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/en/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/es/translation/admin-console/index.ts
  packages/phrases/src/locales/es/translation/admin-console/tabs.ts
  packages/phrases/src/locales/es/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/es/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/fr/translation/admin-console/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/tabs.ts
  packages/phrases/src/locales/fr/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/it/translation/admin-console/index.ts
  packages/phrases/src/locales/it/translation/admin-console/tabs.ts
  packages/phrases/src/locales/it/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/it/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/ja/translation/admin-console/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/tabs.ts
  packages/phrases/src/locales/ja/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/ko/translation/admin-console/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/tabs.ts
  packages/phrases/src/locales/ko/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tabs.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tabs.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tabs.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/ru/translation/admin-console/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/tabs.ts
  packages/phrases/src/locales/ru/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tabs.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tabs.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tabs.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tabs.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/webhooks.ts
Labels: chore, size/xl

#3778 feat: support passing cli arguments via `@logto/create`
  .changeset/wise-jobs-push.md
  packages/create/index.sh
Labels: feature, size/xs

#3792 refactor: update tracking components
  .changeset/four-poets-change.md
  packages/app-insights/package.json
  packages/app-insights/src/custom-event.ts
  packages/app-insights/src/react/AppInsightsBoundary.tsx
  packages/app-insights/src/react/AppInsightsReact.ts
  packages/app-insights/src/react/TrackOnce.tsx
  packages/app-insights/src/react/index.ts
  packages/console/src/App.tsx
  packages/console/src/components/PageMeta/index.tsx
  packages/console/src/consts/index.ts
  packages/console/src/consts/storage.ts
  packages/console/src/contexts/AppThemeProvider/index.tsx
  packages/console/src/onboarding/App.tsx
  packages/console/src/onboarding/pages/About/index.tsx
  packages/console/src/onboarding/pages/Congrats/index.tsx
  packages/console/src/onboarding/pages/SignInExperience/index.tsx
  packages/console/src/onboarding/pages/Welcome/index.tsx
  packages/console/src/pages/Main/index.tsx
  packages/console/src/pages/Profile/components/LinkAccountSection/index.tsx
  packages/console/src/pages/Profile/containers/HandleSocialCallback/index.tsx
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/phrases/src/locales/de/translation/admin-console/cloud.ts
  packages/phrases/src/locales/en/translation/admin-console/cloud.ts
  packages/phrases/src/locales/es/translation/admin-console/cloud.ts
  packages/phrases/src/locales/fr/translation/admin-console/cloud.ts
  packages/phrases/src/locales/it/translation/admin-console/cloud.ts
  packages/phrases/src/locales/ja/translation/admin-console/cloud.ts
  packages/phrases/src/locales/ko/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/cloud.ts
  packages/phrases/src/locales/ru/translation/admin-console/cloud.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/cloud.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/cloud.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/cloud.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/cloud.ts
  packages/ui/src/App.tsx
  packages/ui/src/components/PageMeta/index.tsx
Labels: enhancement, size/l
