Repository logto-io/logto, pull requests merged in 2023-09, with the labels that each got.

#4417 fix(console): update default tenant id on manual navigation only
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/index.tsx
  packages/console/src/containers/TenantAccess/index.tsx
  packages/console/src/hooks/use-user-default-tenant-id.ts
Labels: bugfix, size/s

#4409 refactor(core): clean up useless interaction guard
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/types/guard.ts
  packages/core/src/routes/interaction/types/index.ts
  packages/schemas/src/types/interactions.ts
Labels: enhancement, size/s

#4414 fix(console): block margin should be the same on get-started page
  packages/console/src/pages/GetStarted/FreePlanNotification/index.module.scss
Labels: bugfix, size/xs

#4410 feat(toolkit): init password policy checker
  packages/toolkit/core-kit/jest.config.js
  packages/toolkit/core-kit/jest.setup.js
  packages/toolkit/core-kit/src/index.ts
  packages/toolkit/core-kit/src/password-policy.test.ts
  packages/toolkit/core-kit/src/password-policy.ts
Labels: feature, size/xl

#4423 chore(console): remove unused v1 guides and mdx-components
  packages/console/src/assets/docs/guides/m2m-general/README.mdx
  packages/console/src/assets/docs/guides/native-android-java/README.mdx
  packages/console/src/assets/docs/guides/native-android-kt/README.mdx
  packages/console/src/assets/docs/guides/native-capacitor/README.mdx
  packages/console/src/assets/docs/guides/native-flutter/README.mdx
  packages/console/src/assets/docs/guides/native-ios-swift/README.mdx
  packages/console/src/assets/docs/guides/spa-react/README.mdx
  packages/console/src/assets/docs/guides/spa-vanilla/README.mdx
  packages/console/src/assets/docs/guides/spa-vue/README.mdx
  packages/console/src/assets/docs/guides/web-asp-net-core/README.mdx
  packages/console/src/assets/docs/guides/web-express/README.mdx
  packages/console/src/assets/docs/guides/web-go/README.mdx
  packages/console/src/assets/docs/guides/web-gpt-plugin/README.mdx
  packages/console/src/assets/docs/guides/web-next-app-router/README.mdx
  packages/console/src/assets/docs/guides/web-next/README.mdx
  packages/console/src/assets/docs/guides/web-outline/README.mdx
  packages/console/src/assets/docs/guides/web-php/README.mdx
  packages/console/src/assets/docs/guides/web-python/README.mdx
  packages/console/src/assets/docs/guides/web-remix/README.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/android.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/android_zh-cn.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/express.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/express_zh-cn.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/go.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/go_zh-cn.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/ios.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/ios_zh-cn.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/next.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/next_zh-cn.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/react.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/react_zh-cn.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/vanilla.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/vanilla_zh-cn.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/vue.mdx
  packages/console/src/assets/docs/tutorial/integrate-sdk/vue_zh-cn.mdx
  packages/console/src/mdx-components-v2/Step/index.module.scss
  packages/console/src/mdx-components-v2/Step/index.tsx
  packages/console/src/mdx-components-v2/UriInputField/index.module.scss
  packages/console/src/mdx-components-v2/UriInputField/index.tsx
  packages/console/src/mdx-components/ApplicationCredentials/index.module.scss
  packages/console/src/mdx-components/ApplicationCredentials/index.tsx
  packages/console/src/mdx-components/README.md
  packages/console/src/mdx-components/Sample/index.module.scss
  packages/console/src/mdx-components/Sample/index.tsx
  packages/console/src/mdx-components/Step/index.module.scss
  packages/console/src/mdx-components/Step/index.tsx
  packages/console/src/mdx-components/Steps/FurtherReadings.tsx
  packages/console/src/mdx-components/Steps/index.module.scss
  packages/console/src/mdx-components/Steps/index.tsx
  packages/console/src/mdx-components/TabItem/index.module.scss
  packages/console/src/mdx-components/UriInputField/index.module.scss
  packages/console/src/mdx-components/UriInputField/index.tsx
Labels: chore, size/xl

#4426 refactor(phrases): update no-social connector notification
  packages/integration-tests/src/tests/ui/sign-in-experience/sign-up-and-sign-in/sad-path.test.ts
  packages/phrases/src/locales/de/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/es/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/it/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/sign-in-exp/index.ts
Labels: enhancement, size/s

#4422 refactor(console): remove add connectors tip when no social connector is set up
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SocialConnectorEditBox/index.tsx
Labels: enhancement, size/s

#4424 refactor(console): remove no-data social section from changes alert modal
  packages/console/src/pages/SignInExperience/components/SignUpAndSignInChangePreview/SignUpAndSignInDiffSection/SocialTargetsDiffSection.tsx
  packages/integration-tests/src/tests/ui/sign-in-experience/sign-up-and-sign-in/happy-path.test.ts
Labels: enhancement, size/s

#4287 refactor(toolkit): update input params type of SendMessageFunction
  packages/schemas/src/types/system.ts
  packages/toolkit/connector-kit/src/types.ts
Labels: enhancement, size/s, stale

#4435 refactor(connector): update aad connector
  packages/connectors/connector-azuread/README.md
  packages/connectors/connector-azuread/src/constant.ts
Labels: enhancement, size/s

#4429 fix(core,ui): clear ui preload link not used warning
  packages/core/src/middleware/koa-security-headers.ts
  packages/ui/src/index.html
Labels: bugfix, size/s

#4428 refactor(console): add missing section title and adjust card layout in get-started page
  packages/console/src/hooks/use-window-resize.ts
  packages/console/src/pages/Applications/components/GuideGroup/index.tsx
  packages/console/src/pages/GetStarted/index.tsx
Labels: enhancement, size/s

#4437 refactor(core): remove response data construction helper from libs
  packages/core/src/__mocks__/index.ts
  packages/core/src/libraries/hook/index.test.ts
  packages/core/src/libraries/hook/index.ts
  packages/core/src/libraries/resource.test.ts
  packages/core/src/libraries/resource.ts
  packages/core/src/routes/hook.test.ts
  packages/core/src/routes/hook.ts
  packages/core/src/routes/resource.test.ts
  packages/core/src/routes/resource.ts
  packages/core/src/tenants/Libraries.ts
  packages/core/src/utils/resource.ts
Labels: enhancement, size/m

#4430 refactor(console): retrieve subscription data from tenant response
  packages/console/package.json
  packages/console/src/components/MauExceededModal/index.tsx
  packages/console/src/components/PaymentOverdueModal/index.tsx
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/TenantDropdownItem/TenantStatusTag.tsx
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx
  packages/console/src/contexts/TenantsProvider.tsx
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/PaymentOverdueNotification/index.tsx
  packages/console/src/types/subscriptions.ts
  packages/console/src/utils/subscription.ts
  pnpm-lock.yaml
Labels: enhancement, size/m

#4433 refactor(console): add headline spacing prop for `FormField` component
  packages/console/src/ds-components/FormField/index.module.scss
  packages/console/src/ds-components/FormField/index.tsx
  packages/console/src/onboarding/pages/SignInExperience/index.module.scss
  packages/console/src/onboarding/pages/SignInExperience/index.tsx
  packages/console/src/onboarding/pages/Welcome/index.module.scss
  packages/console/src/onboarding/pages/Welcome/index.tsx
  packages/console/src/pages/ConnectorDetails/ConnectorContent/EmailServiceConnectorForm/index.module.scss
  packages/console/src/pages/ConnectorDetails/ConnectorContent/EmailServiceConnectorForm/index.tsx
  packages/console/src/pages/SignInExperience/tabs/Branding/BrandingForm.tsx
  packages/console/src/pages/SignInExperience/tabs/index.module.scss
Labels: enhancement, size/s

#4438 refactor(console): reorg connector creation modal
  packages/console/src/components/CreateConnectorForm/PlatformSelector/index.module.scss
  packages/console/src/components/CreateConnectorForm/index.tsx
Labels: enhancement, size/s

#4436 refactor: improve guide responsive rules
  packages/console/src/assets/docs/guides/spa-vanilla/README.mdx
  packages/console/src/mdx-components/Steps/index.module.scss
  packages/console/src/mdx-components/Steps/index.tsx
  packages/console/src/mdx-components/UriInputField/index.tsx
  packages/console/src/pages/ApplicationDetails/components/GuideDrawer/index.module.scss
  packages/console/src/pages/ApplicationDetails/components/GuideDrawer/index.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/Applications/components/Guide/index.module.scss
  packages/console/src/pages/Applications/components/Guide/index.tsx
  packages/console/src/pages/Applications/components/GuideCard/index.module.scss
  packages/console/src/pages/Applications/components/GuideCard/index.tsx
  packages/console/src/pages/Applications/components/GuideGroup/index.tsx
  packages/console/src/pages/Applications/components/GuideHeader/index.module.scss
  packages/console/src/pages/Applications/components/GuideHeader/index.tsx
  packages/console/src/pages/Applications/components/GuideLibrary/index.module.scss
  packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
  packages/console/src/pages/Applications/components/GuideLibraryModal/index.module.scss
  packages/console/src/pages/Applications/components/GuideLibraryModal/index.tsx
  packages/console/src/pages/Applications/components/GuideModal/index.module.scss
  packages/console/src/pages/Applications/components/GuideModal/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/scss/_dimensions.scss
Labels: enhancement, size/xl

#4440 fix(console): redirectUri input error message should be displayed properly
  packages/console/src/mdx-components/UriInputField/index.tsx
Labels: bugfix, size/xs

#4441 fix(console): optimize loading screens in app guides
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/Applications/components/Guide/index.tsx
  packages/console/src/pages/Applications/components/GuideModal/index.tsx
  packages/console/src/pages/Applications/components/StepsSkeleton/index.module.scss
Labels: bugfix, size/s

#4442 style(console): update section subtitle and inline code styles in app…
  packages/console/src/pages/Applications/components/Guide/index.module.scss
Labels: size/s

#4434 fix(toolkit): support plus and hyphen in mobile uri scheme
  packages/console/src/pages/ApplicationDetails/components/Settings.tsx
  packages/schemas/src/foundations/jsonb-types.ts
  packages/toolkit/core-kit/src/regex.ts
  packages/toolkit/core-kit/src/utils/url.test.ts
Labels: bugfix, size/s

#4419 feat(console): password policy
  packages/console/src/ds-components/TextInput/NumericInput.module.scss
  packages/console/src/ds-components/TextInput/NumericInput.tsx
  packages/console/src/ds-components/TextInput/index.module.scss
  packages/console/src/ds-components/TextInput/index.tsx
  packages/console/src/pages/SignInExperience/index.tsx
  packages/console/src/pages/SignInExperience/tabs/PasswordPolicy/index.module.scss
  packages/console/src/pages/SignInExperience/tabs/PasswordPolicy/index.tsx
  packages/console/src/pages/SignInExperience/types.ts
  packages/console/src/pages/SignInExperience/utils/form.ts
  packages/console/src/utils/a11y.ts
  packages/phrases/src/locales/de/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/de/translation/admin-console/sign-in-exp/password-policy.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/password-policy.ts
  packages/phrases/src/locales/es/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/es/translation/admin-console/sign-in-exp/password-policy.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp/password-policy.ts
  packages/phrases/src/locales/it/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/it/translation/admin-console/sign-in-exp/password-policy.ts
  packages/phrases/src/locales/ja/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/sign-in-exp/password-policy.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp/password-policy.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/sign-in-exp/password-policy.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp/password-policy.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp/password-policy.ts
  packages/phrases/src/locales/ru/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/sign-in-exp/password-policy.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp/password-policy.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp/password-policy.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/sign-in-exp/password-policy.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/sign-in-exp/password-policy.ts
Labels: feature, size/xl

#4447 chore: reorg webhook-related file structures
  packages/console/src/components/BasicWebhookForm/index.module.scss
  packages/console/src/components/BasicWebhookForm/index.tsx
  packages/console/src/components/SuccessRate/index.tsx
  packages/console/src/pages/WebhookDetails/WebhookSettings/CustomHeaderField/index.module.scss
  packages/console/src/pages/WebhookDetails/WebhookSettings/CustomHeaderField/index.tsx
  packages/console/src/pages/WebhookDetails/WebhookSettings/SigningKeyField/index.module.scss
  packages/console/src/pages/WebhookDetails/WebhookSettings/SigningKeyField/index.tsx
  packages/console/src/pages/WebhookDetails/WebhookSettings/TestWebhook/index.module.scss
  packages/console/src/pages/WebhookDetails/WebhookSettings/TestWebhook/index.tsx
  packages/console/src/pages/WebhookDetails/WebhookSettings/index.tsx
  packages/console/src/pages/WebhookDetails/index.tsx
  packages/console/src/pages/WebhookDetails/types.ts
  packages/console/src/pages/Webhooks/CreateFormModal/CreateForm.tsx
  packages/console/src/pages/Webhooks/CreateFormModal/index.tsx
  packages/console/src/pages/Webhooks/index.tsx
  packages/console/src/pages/Webhooks/types.ts
Labels: chore, size/s

#4446 fix(connector,console): fix SAML error recording and connector config form interaction
  packages/connectors/connector-saml/README.md
  packages/connectors/connector-saml/src/index.ts
  packages/console/src/components/ConnectorForm/ConfigForm/ConfigFormFields/index.tsx
  packages/console/src/components/Markdown/index.module.scss
  packages/console/src/pages/Connectors/Guide/index.module.scss
Labels: bugfix, size/m

#4445 refactor(toolkit): sync latest password rules
  packages/toolkit/core-kit/src/password-policy.test.ts
  packages/toolkit/core-kit/src/password-policy.ts
  packages/ui/src/Layout/SecondaryPageLayout/index.tsx
  packages/ui/src/containers/SetPassword/index.tsx
  packages/ui/src/hooks/use-sie.ts
  packages/ui/src/pages/Continue/SetPassword/index.tsx
  packages/ui/src/pages/RegisterPassword/index.tsx
  packages/ui/src/pages/ResetPassword/index.tsx
Labels: enhancement, size/m

#4449 fix(console): code editor text background
  packages/console/src/pages/Applications/components/Guide/index.module.scss
Labels: bugfix, size/xs

#4453 refactor(console): display webhook test result on details page
  packages/console/src/consts/storage.ts
  packages/console/src/ds-components/InlineNotification/index.tsx
  packages/console/src/pages/WebhookDetails/WebhookSettings/TestWebhook/index.module.scss
  packages/console/src/pages/WebhookDetails/WebhookSettings/TestWebhook/index.tsx
  packages/console/src/pages/WebhookDetails/WebhookSettings/TestWebhook/use-webhook-test-result.ts
  packages/core/src/libraries/hook/index.ts
  packages/integration-tests/src/tests/api/hook/hook.testing.test.ts
  packages/integration-tests/src/tests/ui/webhooks/helpers.ts
  packages/integration-tests/src/tests/ui/webhooks/index.test.ts
  packages/integration-tests/src/ui-helpers/index.ts
  packages/phrases/src/locales/de/errors/hook.ts
  packages/phrases/src/locales/de/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/en/errors/hook.ts
  packages/phrases/src/locales/en/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/es/errors/hook.ts
  packages/phrases/src/locales/es/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/fr/errors/hook.ts
  packages/phrases/src/locales/fr/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/it/errors/hook.ts
  packages/phrases/src/locales/it/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/ja/errors/hook.ts
  packages/phrases/src/locales/ja/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/ko/errors/hook.ts
  packages/phrases/src/locales/ko/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/pl-pl/errors/hook.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/pt-br/errors/hook.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/pt-pt/errors/hook.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/ru/errors/hook.ts
  packages/phrases/src/locales/ru/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/tr-tr/errors/hook.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/zh-cn/errors/hook.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/zh-hk/errors/hook.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/zh-tw/errors/hook.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/webhook-details.ts
  packages/schemas/src/types/hook.ts
Labels: enhancement, feature, size/l

#4378 refactor(core,schemas): update roles table schemas, add type column
  .changeset/violet-mugs-tickle.md
  .scripts/compare-database.js
  packages/core/src/__mocks__/index.ts
  packages/core/src/libraries/user.test.ts
  packages/core/src/middleware/koa-slonik-error-handler.ts
  packages/core/src/queries/roles.test.ts
  packages/core/src/routes/admin-user-role.test.ts
  packages/core/src/routes/admin-user-role.ts
  packages/core/src/routes/admin-user-search.test.ts
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/application.ts
  packages/core/src/routes/authn.test.ts
  packages/core/src/routes/role.scope.test.ts
  packages/core/src/routes/role.test.ts
  packages/integration-tests/src/api/role.ts
  packages/integration-tests/src/helpers/admin-tenant.ts
  packages/integration-tests/src/tests/api/admin-user.roles.test.ts
  packages/integration-tests/src/tests/api/oidc/get-access-token.test.ts
  packages/integration-tests/src/tests/api/role.scope.test.ts
  packages/integration-tests/src/tests/api/role.test.ts
  packages/integration-tests/src/tests/api/role.user.test.ts
  packages/phrases/src/locales/de/errors/entity.ts
  packages/phrases/src/locales/en/errors/entity.ts
  packages/phrases/src/locales/es/errors/entity.ts
  packages/phrases/src/locales/fr/errors/entity.ts
  packages/phrases/src/locales/it/errors/entity.ts
  packages/phrases/src/locales/ja/errors/entity.ts
  packages/phrases/src/locales/ko/errors/entity.ts
  packages/phrases/src/locales/pl-pl/errors/entity.ts
  packages/phrases/src/locales/pt-br/errors/entity.ts
  packages/phrases/src/locales/pt-pt/errors/entity.ts
  packages/phrases/src/locales/ru/errors/entity.ts
  packages/phrases/src/locales/tr-tr/errors/entity.ts
  packages/phrases/src/locales/zh-cn/errors/entity.ts
  packages/phrases/src/locales/zh-hk/errors/entity.ts
  packages/phrases/src/locales/zh-tw/errors/entity.ts
  packages/schemas/alterations/next-1694399696-add-type-col-to-roles-table.ts
  packages/schemas/src/seeds/cloud-api.ts
  packages/schemas/src/seeds/management-api.ts
  packages/schemas/tables/applications_roles.sql
  packages/schemas/tables/roles.sql
  packages/schemas/tables/users_roles.sql
Labels: enhancement, size/l, stale

#4382 refactor(core,phrases,test): add user role APIs guard
  packages/core/src/__mocks__/index.ts
  packages/core/src/queries/users-roles.ts
  packages/core/src/routes/admin-user-role.test.ts
  packages/core/src/routes/admin-user-role.ts
  packages/core/src/routes/role.test.ts
  packages/core/src/routes/role.ts
  packages/integration-tests/src/tests/api/admin-user.roles.test.ts
  packages/integration-tests/src/tests/api/role.user.test.ts
  packages/phrases/src/locales/de/errors/user.ts
  packages/phrases/src/locales/en/errors/user.ts
  packages/phrases/src/locales/es/errors/user.ts
  packages/phrases/src/locales/fr/errors/user.ts
  packages/phrases/src/locales/it/errors/user.ts
  packages/phrases/src/locales/ja/errors/user.ts
  packages/phrases/src/locales/ko/errors/user.ts
  packages/phrases/src/locales/pl-pl/errors/user.ts
  packages/phrases/src/locales/pt-br/errors/user.ts
  packages/phrases/src/locales/pt-pt/errors/user.ts
  packages/phrases/src/locales/ru/errors/user.ts
  packages/phrases/src/locales/tr-tr/errors/user.ts
  packages/phrases/src/locales/zh-cn/errors/user.ts
  packages/phrases/src/locales/zh-hk/errors/user.ts
  packages/phrases/src/locales/zh-tw/errors/user.ts
Labels: enhancement, size/m

#4448 refactor(console): re-use guide components in new api resource creation process
  packages/console/src/assets/docs/guides/m2m-general/components/EnableAdminAccess.tsx
  packages/console/src/assets/docs/guides/web-gpt-plugin/components/AlwaysIssueRefreshToken.tsx
  packages/console/src/assets/docs/guides/web-gpt-plugin/components/ClientBasics/index.tsx
  packages/console/src/assets/docs/guides/web-outline/components/EnvironmentVariables.tsx
  packages/console/src/components/Guide/GuideCard/index.module.scss
  packages/console/src/components/Guide/GuideCard/index.tsx
  packages/console/src/components/Guide/GuideCardGroup/index.module.scss
  packages/console/src/components/Guide/GuideCardGroup/index.tsx
  packages/console/src/components/Guide/ModalFooter/index.module.scss
  packages/console/src/components/Guide/ModalFooter/index.tsx
  packages/console/src/components/Guide/ModalHeader/RequestForm.tsx
  packages/console/src/components/Guide/ModalHeader/index.module.scss
  packages/console/src/components/Guide/ModalHeader/index.tsx
  packages/console/src/components/Guide/StepsSkeleton/index.module.scss
  packages/console/src/components/Guide/StepsSkeleton/index.tsx
  packages/console/src/components/Guide/hooks.ts
  packages/console/src/components/Guide/index.module.scss
  packages/console/src/components/Guide/index.tsx
  packages/console/src/mdx-components/ApplicationCredentials/index.tsx
  packages/console/src/mdx-components/Sample/index.tsx
  packages/console/src/mdx-components/Steps/index.tsx
  packages/console/src/mdx-components/UriInputField/index.tsx
  packages/console/src/pages/ApplicationDetails/components/AppGuide/index.module.scss
  packages/console/src/pages/ApplicationDetails/components/AppGuide/index.tsx
  packages/console/src/pages/ApplicationDetails/components/GuideDrawer/index.tsx
  packages/console/src/pages/ApplicationDetails/components/GuideModal/index.module.scss
  packages/console/src/pages/ApplicationDetails/components/GuideModal/index.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/Applications/components/Guide/index.tsx
  packages/console/src/pages/Applications/components/GuideLibrary/hook.ts
  packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
  packages/console/src/pages/Applications/components/GuideLibraryModal/index.module.scss
  packages/console/src/pages/Applications/components/GuideLibraryModal/index.tsx
  packages/console/src/pages/Applications/components/GuideModal/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/GetStarted/index.tsx
Labels: enhancement, size/xl

#4454 refactor(core): check personal info when setting password
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/utils/find-user-by-identifier.ts
  packages/core/src/routes/interaction/utils/validate-password.ts
Labels: enhancement, size/m

#4455 feat(console): add api resource metadata and guide for node express
  packages/console/src/assets/docs/guides/api-express/README.mdx
  packages/console/src/assets/docs/guides/api-express/index.ts
  packages/console/src/assets/docs/guides/api-express/logo.svg
  packages/console/src/assets/docs/guides/index.ts
Labels: feature, size/m

#4458 refactor(test): rename directories
  packages/core/src/routes/interaction/index.ts
  packages/integration-tests/package.json
  packages/integration-tests/src/tests/console/applications/constants.ts
  packages/integration-tests/src/tests/console/applications/helpers.ts
  packages/integration-tests/src/tests/console/applications/index.test.ts
  packages/integration-tests/src/tests/console/bootstrap.test.ts
  packages/integration-tests/src/tests/console/connectors/helpers.ts
  packages/integration-tests/src/tests/console/connectors/passwordless-connector-test-cases.ts
  packages/integration-tests/src/tests/console/connectors/passwordless-connectors.test.ts
  packages/integration-tests/src/tests/console/connectors/social-connector-test-cases.ts
  packages/integration-tests/src/tests/console/connectors/social-connectors.test.ts
  packages/integration-tests/src/tests/console/rbac.test.ts
  packages/integration-tests/src/tests/console/sign-in-experience/branding.test.ts
  packages/integration-tests/src/tests/console/sign-in-experience/helpers.ts
  packages/integration-tests/src/tests/console/sign-in-experience/sign-in-preview.test.ts
  packages/integration-tests/src/tests/console/sign-in-experience/sign-up-and-sign-in/connector-setup-helpers.ts
  packages/integration-tests/src/tests/console/sign-in-experience/sign-up-and-sign-in/happy-path.test.ts
  packages/integration-tests/src/tests/console/sign-in-experience/sign-up-and-sign-in/helpers.ts
  packages/integration-tests/src/tests/console/sign-in-experience/sign-up-and-sign-in/sad-path.test.ts
  packages/integration-tests/src/tests/console/user-management.test.ts
  packages/integration-tests/src/tests/console/webhooks/helpers.ts
  packages/integration-tests/src/tests/console/webhooks/index.test.ts
  packages/integration-tests/src/tests/flows/bootstrap.test.ts
Labels: enhancement, size/s

#4456 refactor(console): i18n phrases used in guides
  packages/console/src/components/Guide/GuideCard/index.tsx
  packages/console/src/components/Guide/index.tsx
  packages/console/src/pages/ApplicationDetails/components/GuideDrawer/index.tsx
  packages/console/src/pages/ApplicationDetails/components/GuideModal/index.tsx
  packages/console/src/pages/Applications/components/GuideLibrary/index.module.scss
  packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
  packages/console/src/pages/Applications/components/GuideLibraryModal/index.tsx
  packages/console/src/pages/Applications/index.module.scss
  packages/console/src/pages/Applications/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/applications.ts
  packages/phrases/src/locales/de/translation/admin-console/guide.ts
  packages/phrases/src/locales/de/translation/admin-console/index.ts
  packages/phrases/src/locales/en/translation/admin-console/applications.ts
  packages/phrases/src/locales/en/translation/admin-console/guide.ts
  packages/phrases/src/locales/en/translation/admin-console/index.ts
  packages/phrases/src/locales/es/translation/admin-console/applications.ts
  packages/phrases/src/locales/es/translation/admin-console/guide.ts
  packages/phrases/src/locales/es/translation/admin-console/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/applications.ts
  packages/phrases/src/locales/fr/translation/admin-console/guide.ts
  packages/phrases/src/locales/fr/translation/admin-console/index.ts
  packages/phrases/src/locales/it/translation/admin-console/applications.ts
  packages/phrases/src/locales/it/translation/admin-console/guide.ts
  packages/phrases/src/locales/it/translation/admin-console/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/applications.ts
  packages/phrases/src/locales/ja/translation/admin-console/guide.ts
  packages/phrases/src/locales/ja/translation/admin-console/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/applications.ts
  packages/phrases/src/locales/ko/translation/admin-console/guide.ts
  packages/phrases/src/locales/ko/translation/admin-console/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/applications.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/guide.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/applications.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/guide.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/applications.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/guide.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/applications.ts
  packages/phrases/src/locales/ru/translation/admin-console/guide.ts
  packages/phrases/src/locales/ru/translation/admin-console/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/applications.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/guide.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/guide.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/guide.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/guide.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/index.ts
Labels: enhancement, size/xl

#4469 fix(schemas): specify function db schema of check_role_type
  packages/schemas/alterations/next-1694418765-specify-check-role-type-function-to-be-public-schema.ts
  packages/schemas/tables/applications_roles.sql
  packages/schemas/tables/roles.sql
  packages/schemas/tables/users_roles.sql
Labels: bugfix, size/s

#4468 chore: remove deprecated challenge task flags
  packages/console/src/components/LivePreviewButton/index.tsx
  packages/console/src/containers/AppContent/index.tsx
  packages/console/src/hooks/use-connector-api.ts
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
  packages/core/src/__mocks__/index.ts
  packages/core/src/routes/logto-config.test.ts
  packages/integration-tests/src/tests/api/logto-config.test.ts
  packages/schemas/alterations/next-1694418456-remove-deprecated-challenge-flag.ts
  packages/schemas/src/seeds/logto-config.ts
  packages/schemas/src/types/logto-config.ts
Labels: chore, size/m

#4471 ci: always show logs for integration tests
  .github/workflows/integration-test.yml
Labels: size/xs

#4470 chore: update devcontainer
  .devcontainer/devcontainer.json
Labels: chore, size/xs

#4396 feat(schemas): add mfa to sign in experience table
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/queries/sign-in-experience.test.ts
  packages/schemas/alterations/next-1694403476-sie-mfa.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/seeds/sign-in-experience.ts
  packages/schemas/tables/sign_in_experiences.sql
  packages/ui/src/__mocks__/logto.tsx
  packages/ui/src/__mocks__/social-connectors.tsx
Labels: feature, size/l

#4477 fix(schemas): update alteration script timestamp
  packages/schemas/alterations/next-1694484927-remove-deprecated-challenge-flag.ts
Labels: bugfix, size/xs

#4473 feat(console): add tenant suspended page
  packages/console/src/cloud/pages/Main/TenantLandingPage/index.tsx
  packages/console/src/components/TenantEnvTag/index.module.scss
  packages/console/src/components/TenantEnvTag/index.tsx
  packages/console/src/components/Topbar/Contact/ContactModal/hook.tsx
  packages/console/src/components/Topbar/Contact/ContactModal/index.module.scss
  packages/console/src/components/Topbar/Contact/ContactModal/index.tsx
  packages/console/src/components/Topbar/Contact/index.module.scss
  packages/console/src/components/Topbar/Contact/index.tsx
  packages/console/src/components/Topbar/DocumentNavButton/index.module.scss
  packages/console/src/components/Topbar/DocumentNavButton/index.tsx
  packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/TenantStatusTag.tsx
  packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/index.module.scss
  packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx
  packages/console/src/components/Topbar/TenantSelector/index.module.scss
  packages/console/src/components/Topbar/TenantSelector/index.tsx
  packages/console/src/components/Topbar/UserInfo/SubMenu/index.module.scss
  packages/console/src/components/Topbar/UserInfo/SubMenu/index.tsx
  packages/console/src/components/Topbar/UserInfo/UserInfoSkeleton/index.module.scss
  packages/console/src/components/Topbar/UserInfo/UserInfoSkeleton/index.tsx
  packages/console/src/components/Topbar/UserInfo/index.module.scss
  packages/console/src/components/Topbar/UserInfo/index.tsx
  packages/console/src/components/Topbar/index.module.scss
  packages/console/src/components/Topbar/index.tsx
  packages/console/src/containers/AppContent/TenantSuspendedPage/index.module.scss
  packages/console/src/containers/AppContent/TenantSuspendedPage/index.tsx
  packages/console/src/containers/AppContent/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/DeleteModal/index.tsx
Labels: feature, size/m

#4478 fix(schemas): update alteration script timestamp
  packages/schemas/alterations/next-1694487524-sie-mfa.ts
Labels: bugfix, size/xs

#4479 fix(console): update flutter integration guide
  packages/console/src/assets/docs/guides/native-flutter/README.mdx
Labels: bugfix, size/xs

#4472 chore(core): add supplementary openapi json
  .vscode/settings.json
  packages/core/package.json
  packages/core/src/routes/status.openapi.json
  packages/core/src/routes/swagger.test.ts
  packages/core/src/routes/swagger.ts
Labels: chore, size/s

#4475 refactor: refine password policy details
  packages/console/src/ds-components/TextInput/NumericInput.module.scss
  packages/console/src/pages/SignInExperience/tabs/Content/index.tsx
  packages/console/src/pages/SignInExperience/tabs/PasswordPolicy/index.module.scss
  packages/console/src/pages/SignInExperience/tabs/PasswordPolicy/index.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/AdvancedOptions.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/index.tsx
  packages/integration-tests/src/tests/console/sign-in-experience/sign-up-and-sign-in/happy-path.test.ts
  packages/phrases/src/locales/de/translation/admin-console/sign-in-exp/content.ts
  packages/phrases/src/locales/de/translation/admin-console/sign-in-exp/password-policy.ts
  packages/phrases/src/locales/de/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/content.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/password-policy.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/es/translation/admin-console/sign-in-exp/content.ts
  packages/phrases/src/locales/es/translation/admin-console/sign-in-exp/password-policy.ts
  packages/phrases/src/locales/es/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp/content.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp/password-policy.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/it/translation/admin-console/sign-in-exp/content.ts
  packages/phrases/src/locales/it/translation/admin-console/sign-in-exp/password-policy.ts
  packages/phrases/src/locales/it/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/ja/translation/admin-console/sign-in-exp/content.ts
  packages/phrases/src/locales/ja/translation/admin-console/sign-in-exp/password-policy.ts
  packages/phrases/src/locales/ja/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp/content.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp/password-policy.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/sign-in-exp/content.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/sign-in-exp/password-policy.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp/content.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp/password-policy.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp/content.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp/password-policy.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/ru/translation/admin-console/sign-in-exp/content.ts
  packages/phrases/src/locales/ru/translation/admin-console/sign-in-exp/password-policy.ts
  packages/phrases/src/locales/ru/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp/content.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp/password-policy.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp/content.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp/password-policy.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/sign-in-exp/content.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/sign-in-exp/password-policy.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/sign-in-exp/content.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/sign-in-exp/password-policy.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/toolkit/core-kit/src/password-policy.ts
Labels: enhancement, size/l

#4467 feat(core): update mfa in sign in experience
  packages/core/src/libraries/sign-in-experience/mfa.test.ts
  packages/core/src/libraries/sign-in-experience/mfa.ts
  packages/core/src/routes/sign-in-experience/index.ts
  packages/integration-tests/src/tests/api/sign-in-experience.test.ts
  packages/phrases/src/locales/de/errors/sign-in-experiences.ts
  packages/phrases/src/locales/en/errors/sign-in-experiences.ts
  packages/phrases/src/locales/es/errors/sign-in-experiences.ts
  packages/phrases/src/locales/fr/errors/sign-in-experiences.ts
  packages/phrases/src/locales/it/errors/sign-in-experiences.ts
  packages/phrases/src/locales/ja/errors/sign-in-experiences.ts
  packages/phrases/src/locales/ko/errors/sign-in-experiences.ts
  packages/phrases/src/locales/pl-pl/errors/sign-in-experiences.ts
  packages/phrases/src/locales/pt-br/errors/sign-in-experiences.ts
  packages/phrases/src/locales/pt-pt/errors/sign-in-experiences.ts
  packages/phrases/src/locales/ru/errors/sign-in-experiences.ts
  packages/phrases/src/locales/tr-tr/errors/sign-in-experiences.ts
  packages/phrases/src/locales/zh-cn/errors/sign-in-experiences.ts
  packages/phrases/src/locales/zh-hk/errors/sign-in-experiences.ts
  packages/phrases/src/locales/zh-tw/errors/sign-in-experiences.ts
Labels: feature, size/m

#4466 refactor(test): add flows integration tests
  packages/integration-tests/package.json
  packages/integration-tests/src/constants.ts
  packages/integration-tests/src/tests/api/interaction/register-with-identifier/happy-path.test.ts
  packages/integration-tests/src/tests/flows/bootstrap.test.ts
  packages/integration-tests/src/tests/flows/password-policy.test.ts
  packages/integration-tests/src/ui-helpers/expect-flows.ts
  packages/integration-tests/src/ui-helpers/expect-page.ts
  packages/integration-tests/src/utils.ts
  packages/integration-tests/tsconfig.json
  packages/integration-tests/ui-test-sequencer.js
  packages/ui/src/components/ErrorMessage/index.tsx
  pnpm-lock.yaml
Labels: enhancement, size/xl

#4489 fix(console): input verification code in profile page should not crash the app
  .changeset/mean-jeans-clap.md
  packages/console/src/hooks/use-redirect-uri.ts
Labels: bugfix, size/xs

#4487 chore: fix container envs for codespaces
  .devcontainer/devcontainer.json
Labels: chore, size/xs

#4476 chore: legacy password policy cleanup
  packages/console/src/pages/Profile/containers/ChangePasswordModal/index.tsx
  packages/console/src/utils/password.ts
  packages/core/src/routes-me/user.ts
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
  packages/phrases-ui/src/locales/de/error/index.ts
  packages/phrases-ui/src/locales/en/error/index.ts
  packages/phrases-ui/src/locales/es/error/index.ts
  packages/phrases-ui/src/locales/fr/error/index.ts
  packages/phrases-ui/src/locales/it/error/index.ts
  packages/phrases-ui/src/locales/ja/error/index.ts
  packages/phrases-ui/src/locales/ko/error/index.ts
  packages/phrases-ui/src/locales/pl-pl/error/index.ts
  packages/phrases-ui/src/locales/pt-br/error/index.ts
  packages/phrases-ui/src/locales/pt-pt/error/index.ts
  packages/phrases-ui/src/locales/ru/error/index.ts
  packages/phrases-ui/src/locales/tr-tr/error/index.ts
  packages/phrases-ui/src/locales/zh-cn/error/index.ts
  packages/phrases-ui/src/locales/zh-hk/error/index.ts
  packages/phrases-ui/src/locales/zh-tw/error/index.ts
  packages/phrases/src/locales/de/translation/admin-console/errors.ts
  packages/phrases/src/locales/de/translation/admin-console/profile.ts
  packages/phrases/src/locales/en/translation/admin-console/errors.ts
  packages/phrases/src/locales/en/translation/admin-console/profile.ts
  packages/phrases/src/locales/es/translation/admin-console/errors.ts
  packages/phrases/src/locales/es/translation/admin-console/profile.ts
  packages/phrases/src/locales/fr/translation/admin-console/errors.ts
  packages/phrases/src/locales/fr/translation/admin-console/profile.ts
  packages/phrases/src/locales/it/translation/admin-console/errors.ts
  packages/phrases/src/locales/it/translation/admin-console/profile.ts
  packages/phrases/src/locales/ja/translation/admin-console/errors.ts
  packages/phrases/src/locales/ja/translation/admin-console/profile.ts
  packages/phrases/src/locales/ko/translation/admin-console/errors.ts
  packages/phrases/src/locales/ko/translation/admin-console/profile.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/errors.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/profile.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/errors.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/profile.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/errors.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/profile.ts
  packages/phrases/src/locales/ru/translation/admin-console/errors.ts
  packages/phrases/src/locales/ru/translation/admin-console/profile.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/errors.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/profile.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/errors.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/profile.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/errors.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/profile.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/errors.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/profile.ts
  packages/toolkit/core-kit/src/regex.test.ts
  packages/toolkit/core-kit/src/regex.ts
  packages/ui/src/utils/form.test.ts
  packages/ui/src/utils/form.ts
Labels: chore, size/l

#4488 chore: password policy release prep
  .changeset/cold-deers-drive.md
  .github/workflows/main.yml
  packages/schemas/alterations/next-1694509714-keep-existing-password-policy.ts
Labels: chore, size/m

#4464 refactor(ui): remove unused style settings
  packages/ui/src/components/InputFields/InputField/index.module.scss
  packages/ui/src/components/InputFields/InputField/index.tsx
Labels: enhancement, size/s

#4499 fix(console): hide mfa menu item before the feature is ready
  packages/console/src/containers/ConsoleContent/Sidebar/hook.tsx
Labels: bugfix, size/xs

#4439 feat(core,schemas): support region option for s3 storage
  .changeset/lucky-wolves-buy.md
  packages/core/src/utils/storage/index.ts
  packages/core/src/utils/storage/s3-storage.ts
  packages/schemas/src/types/system.ts
Labels: feature, size/s

#4501 fix(console): should display custom domain as alternative endpoint in app details and guides
  packages/console/src/components/ConnectorForm/ConfigForm/index.tsx
  packages/console/src/hooks/use-custom-domain.ts
  packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx
  packages/console/src/pages/ApplicationDetails/components/AppGuide/index.tsx
  packages/console/src/pages/ApplicationDetails/components/Settings.tsx
  packages/console/src/utils/domain.ts
Labels: bugfix, size/s

#4497 fix(core): allow ui unsafe inline script
  packages/core/src/middleware/koa-security-headers.ts
Labels: bugfix, size/xs

#4480 feat(schemas): add user verifications column
  packages/core/src/__mocks__/user.ts
  packages/core/src/queries/user.test.ts
  packages/schemas/alterations/next-1694746763-user-verifications.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/tables/users.sql
Labels: feature, size/s

#4506 refactor(console): add isDevFeaturesEnabled env const
  .github/workflows/integration-test.yml
  packages/console/src/consts/env.ts
  packages/console/src/pages/SignInExperience/index.tsx
  packages/integration-tests/src/tests/console/sign-in-experience/password-policy.test.ts
  packages/integration-tests/src/ui-helpers/expect-console.ts
Labels: enhancement, size/s

#4516 refactor(console): hide mfa quota content before feature launched
  packages/console/package.json
  packages/console/src/consts/quota-item-phrases.ts
  packages/console/src/containers/ConsoleContent/Sidebar/hook.tsx
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/DowngradeConfirmModalContent/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanQuotaTable/PlanQuotaKeyLabel/index.tsx
  packages/console/src/pages/TenantSettings/components/NotEligibleSwitchPlanModalContent/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-table.ts
  pnpm-lock.yaml
Labels: enhancement, size/m

#4508 refactor: ui -> experience (part 1)
  packages/integration-tests/package.json
  packages/integration-tests/src/tests/experience/bootstrap.test.ts
  packages/integration-tests/src/tests/experience/password-policy.test.ts
  packages/integration-tests/src/ui-helpers/expect-experience.ts
Labels: enhancement, size/m

#4513 refactor(test): add `cls` and `dcls` util functions
  packages/integration-tests/src/ui-helpers/expect-console.ts
  packages/integration-tests/src/ui-helpers/expect-page.ts
  packages/integration-tests/src/utils.ts
Labels: enhancement, size/s

#4515 refactor(console): add metadata and support endpoint and audience variables in api guides
  packages/console/src/assets/docs/guides/api-express/README.mdx
  packages/console/src/assets/docs/guides/api-express/index.ts
  packages/console/src/components/Guide/index.tsx
  packages/console/src/pages/ApiResourceDetails/components/ApiGuide/index.tsx
  packages/console/src/pages/ApiResourceDetails/components/GuideDrawer/index.tsx
  packages/console/src/pages/ApiResourceDetails/components/GuideModal/index.tsx
  packages/console/src/pages/ApiResourceDetails/index.tsx
Labels: enhancement, size/s

#4518 feat(console): add api resource guide for python
  packages/console/src/assets/docs/guides/api-python/README.mdx
  packages/console/src/assets/docs/guides/api-python/index.ts
  packages/console/src/assets/docs/guides/api-python/logo.svg
  packages/console/src/assets/docs/guides/index.ts
Labels: feature, size/m

#4522 chore: fix changeset
  .changeset/cold-deers-drive.md
  .changeset/funny-bikes-press.md
Labels: chore, size/xs

#4523 chore(console): enable password policy
  packages/console/src/pages/SignInExperience/index.tsx
Labels: chore, size/xs

#4524 fix(console): highlight current tab in sidebar
  packages/console/src/containers/ConsoleContent/Sidebar/index.tsx
  packages/integration-tests/src/tests/console/bootstrap.test.ts
Labels: bugfix, size/s

#4526 chore(console): fix wrong section title in python api guide
  packages/console/src/assets/docs/guides/api-python/README.mdx
Labels: chore, size/xs

#4528 chore: update devcontainer using default image
  .devcontainer/devcontainer.json
Labels: chore, size/s

#4525 refactor(console): improve m2m app guide content
  packages/console/src/assets/docs/guides/m2m-general/README.mdx
  packages/console/src/mdx-components/ApplicationCredentials/index.module.scss
  packages/console/src/pages/ApplicationDetails/components/AppGuide/index.tsx
Labels: enhancement, size/s

#4530 refactor(console): remove alternative endpoint from app guides
  packages/console/src/assets/docs/guides/m2m-general/README.mdx
  packages/console/src/assets/docs/guides/native-android-java/README.mdx
  packages/console/src/assets/docs/guides/native-android-kt/README.mdx
  packages/console/src/assets/docs/guides/native-capacitor/README.mdx
  packages/console/src/assets/docs/guides/native-flutter/README.mdx
  packages/console/src/assets/docs/guides/native-ios-swift/README.mdx
  packages/console/src/assets/docs/guides/spa-react/README.mdx
  packages/console/src/assets/docs/guides/spa-vanilla/README.mdx
  packages/console/src/assets/docs/guides/spa-vue/README.mdx
  packages/console/src/assets/docs/guides/web-asp-net-core-mvc/README.mdx
  packages/console/src/assets/docs/guides/web-asp-net-core/README.mdx
  packages/console/src/assets/docs/guides/web-express/README.mdx
  packages/console/src/assets/docs/guides/web-go/README.mdx
  packages/console/src/assets/docs/guides/web-gpt-plugin/README.mdx
  packages/console/src/assets/docs/guides/web-next-app-router/README.mdx
  packages/console/src/assets/docs/guides/web-next/README.mdx
  packages/console/src/assets/docs/guides/web-outline/README.mdx
  packages/console/src/assets/docs/guides/web-php/README.mdx
  packages/console/src/assets/docs/guides/web-python/README.mdx
  packages/console/src/assets/docs/guides/web-remix/README.mdx
  packages/console/src/components/Guide/index.tsx
  packages/console/src/pages/ApplicationDetails/components/AppGuide/index.tsx
Labels: enhancement, size/s

#4531 refactor(console): improve m2m app guide content
  packages/console/src/assets/docs/guides/m2m-general/README.mdx
Labels: enhancement, size/s

#4495 chore(core,test): enable advanced search params for GET /applications API
  packages/core/src/queries/application.ts
  packages/core/src/routes/application.test.ts
  packages/core/src/routes/application.ts
  packages/core/src/utils/search.ts
  packages/integration-tests/src/api/application.ts
  packages/integration-tests/src/tests/api/application.test.ts
Labels: chore, size/m

#4529 fix(core): quota guard for mfa feature
  packages/core/package.json
  packages/core/src/libraries/quota.ts
  packages/core/src/routes/sign-in-experience/index.ts
  pnpm-lock.yaml
Labels: bugfix, size/xs

#4503 refactor(console): refactor assign role modal
  packages/console/src/components/RoleEntitiesTransfer/components/SourceEntitiesBox/index.module.scss
  packages/console/src/components/RoleEntitiesTransfer/components/SourceEntitiesBox/index.tsx
  packages/console/src/components/RoleEntitiesTransfer/components/SourceEntityItem/index.module.scss
  packages/console/src/components/RoleEntitiesTransfer/components/SourceEntityItem/index.tsx
  packages/console/src/components/RoleEntitiesTransfer/components/TargetEntitiesBox/index.module.scss
  packages/console/src/components/RoleEntitiesTransfer/components/TargetEntitiesBox/index.tsx
  packages/console/src/components/RoleEntitiesTransfer/components/TargetEntityItem/index.module.scss
  packages/console/src/components/RoleEntitiesTransfer/components/TargetEntityItem/index.tsx
  packages/console/src/components/RoleEntitiesTransfer/index.module.scss
  packages/console/src/components/RoleEntitiesTransfer/index.tsx
  packages/console/src/components/RoleEntitiesTransfer/utils.ts
  packages/console/src/components/RoleScopesTransfer/components/SourceScopesBox/index.tsx
  packages/console/src/components/RoleUsersTransfer/components/SourceUserItem/index.tsx
  packages/console/src/components/RoleUsersTransfer/components/TargetUserItem/index.tsx
  packages/console/src/components/RoleUsersTransfer/index.tsx
  packages/console/src/consts/env.ts
  packages/console/src/pages/RoleDetails/RoleUsers/components/AssignUsersModal/index.tsx
  packages/console/src/pages/RoleDetails/RoleUsers/index.tsx
  packages/console/src/pages/Roles/components/AssignRoleModal/index.tsx
  packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
  packages/console/src/pages/Roles/components/CreateRoleModal/index.tsx
  packages/integration-tests/src/tests/console/rbac.test.ts
  packages/phrases/src/locales/de/translation/admin-console/role-details.ts
  packages/phrases/src/locales/en/translation/admin-console/role-details.ts
  packages/phrases/src/locales/es/translation/admin-console/role-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/role-details.ts
  packages/phrases/src/locales/it/translation/admin-console/role-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/role-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/role-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/role-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/role-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/role-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/role-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/role-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/role-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/role-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/role-details.ts
Labels: enhancement, size/xl

#4536 chore(phrases): add mfa session phrases
  packages/phrases/src/locales/de/errors/session.ts
  packages/phrases/src/locales/en/errors/session.ts
  packages/phrases/src/locales/es/errors/session.ts
  packages/phrases/src/locales/fr/errors/session.ts
  packages/phrases/src/locales/it/errors/session.ts
  packages/phrases/src/locales/ja/errors/session.ts
  packages/phrases/src/locales/ko/errors/session.ts
  packages/phrases/src/locales/pl-pl/errors/session.ts
  packages/phrases/src/locales/pt-br/errors/session.ts
  packages/phrases/src/locales/pt-pt/errors/session.ts
  packages/phrases/src/locales/ru/errors/session.ts
  packages/phrases/src/locales/tr-tr/errors/session.ts
  packages/phrases/src/locales/zh-cn/errors/session.ts
  packages/phrases/src/locales/zh-hk/errors/session.ts
  packages/phrases/src/locales/zh-tw/errors/session.ts
Labels: chore, size/s

#4532 refactor(console): add management api notice and update logo
  packages/console/src/assets/icons/api-resource-dark.svg
  packages/console/src/assets/icons/api-resource.svg
  packages/console/src/assets/icons/management-api-resource-dark.svg
  packages/console/src/assets/icons/management-api-resource.svg
  packages/console/src/hooks/use-user-preferences.ts
  packages/console/src/pages/ApiResourceDetails/components/ManagementApiNotice/index.tsx
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/console/src/pages/ApiResources/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/en/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/es/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/it/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/api-resource-details.ts
Labels: enhancement, size/l

#4534 refactor(console,phrases,schemas,core): reorg role table
  packages/console/src/assets/icons/m2m-role-dark.svg
  packages/console/src/assets/icons/m2m-role.svg
  packages/console/src/assets/icons/user-role-dark.svg
  packages/console/src/assets/icons/user-role.svg
  packages/console/src/cloud/types/router.ts
  packages/console/src/pages/Roles/components/AssignedEntities/index.module.scss
  packages/console/src/pages/Roles/components/AssignedEntities/index.tsx
  packages/console/src/pages/Roles/components/AssignedUsers/index.tsx
  packages/console/src/pages/Roles/index.module.scss
  packages/console/src/pages/Roles/index.tsx
  packages/core/src/queries/application.ts
  packages/core/src/queries/applications-roles.ts
  packages/core/src/routes/role.test.ts
  packages/core/src/routes/role.ts
  packages/phrases/src/locales/de/translation/admin-console/roles.ts
  packages/phrases/src/locales/en/translation/admin-console/roles.ts
  packages/phrases/src/locales/es/translation/admin-console/roles.ts
  packages/phrases/src/locales/fr/translation/admin-console/roles.ts
  packages/phrases/src/locales/it/translation/admin-console/roles.ts
  packages/phrases/src/locales/ja/translation/admin-console/roles.ts
  packages/phrases/src/locales/ko/translation/admin-console/roles.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/roles.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/roles.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/roles.ts
  packages/phrases/src/locales/ru/translation/admin-console/roles.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/roles.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/roles.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/roles.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/roles.ts
  packages/schemas/src/types/role.ts
Labels: enhancement, size/xl

#4481 feat(core): management user verifications
  packages/console/src/pages/Profile/components/BasicUserInfoSection/index.tsx
  packages/console/src/pages/Profile/components/LinkAccountSection/index.tsx
  packages/core/src/__mocks__/user.ts
  packages/core/src/routes/admin-user.test.ts
  packages/core/src/routes/admin-user.ts
  packages/core/src/utils/user.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/types/user.ts
Labels: feature, size/m

#4539 fix(console): grouped avatars should stack on each other
  packages/console/src/components/UserAvatar/index.module.scss
  packages/console/src/components/UserAvatar/index.tsx
Labels: bugfix, size/s

#4540 fix(console): should show user initial letter avatar in roles
  packages/core/src/routes/role.test.ts
  packages/core/src/routes/role.ts
  packages/schemas/src/types/role.ts
Labels: bugfix, size/s

#4543 fix(console): transfer items should all be rendered as 40px in height
  packages/console/src/components/RoleEntitiesTransfer/components/TargetEntityItem/index.module.scss
  packages/console/src/components/RoleEntitiesTransfer/components/TargetEntityItem/index.tsx
  packages/console/src/components/RoleScopesTransfer/components/ResourceItem/index.tsx
  packages/console/src/components/RoleScopesTransfer/components/TargetScopeItem/index.module.scss
  packages/console/src/components/RoleScopesTransfer/components/TargetScopeItem/index.tsx
  packages/console/src/components/UserRolesTransfer/components/TargetRoleItem/index.module.scss
  packages/console/src/components/UserRolesTransfer/components/TargetRoleItem/index.tsx
Labels: bugfix, size/s

#4544 fix(console): detail form tabs should not have unexpected margin-top
  packages/console/src/components/DetailsForm/index.module.scss
Labels: bugfix, size/s

#4545 refactor(cli): polish cli output
  .changeset/three-pigs-search.md
  packages/cli/src/commands/connector/utils.ts
  packages/cli/src/commands/database/seed/index.ts
  packages/cli/src/commands/database/seed/oidc-config.ts
  packages/cli/src/commands/install/utils.ts
  packages/cli/src/utils.ts
  packages/shared/src/node/env/ConsoleLog.ts
Labels: enhancement, size/s

#4538 feat(console): add quota paywall for mfa feature
  packages/console/src/components/ContactUsPhraseLink/index.tsx
  packages/console/src/ds-components/Switch/index.module.scss
  packages/console/src/pages/Mfa/MfaForm/index.module.scss
  packages/console/src/pages/Mfa/MfaForm/index.tsx
Labels: feature, size/s

#4559 feat(phrases): add mfa totp phrases
  packages/phrases/src/locales/de/errors/user.ts
  packages/phrases/src/locales/en/errors/user.ts
  packages/phrases/src/locales/es/errors/user.ts
  packages/phrases/src/locales/fr/errors/user.ts
  packages/phrases/src/locales/it/errors/user.ts
  packages/phrases/src/locales/ja/errors/user.ts
  packages/phrases/src/locales/ko/errors/user.ts
  packages/phrases/src/locales/pl-pl/errors/user.ts
  packages/phrases/src/locales/pt-br/errors/user.ts
  packages/phrases/src/locales/pt-pt/errors/user.ts
  packages/phrases/src/locales/ru/errors/user.ts
  packages/phrases/src/locales/tr-tr/errors/user.ts
  packages/phrases/src/locales/zh-cn/errors/user.ts
  packages/phrases/src/locales/zh-hk/errors/user.ts
  packages/phrases/src/locales/zh-tw/errors/user.ts
Labels: feature, size/s

#4561 fix: fix experience codecov report
  .github/workflows/master-codecov-report.yml
Labels: bugfix, size/xs

#4563 refactor(console): retrieve latest invoice id from stripe
  packages/console/package.json
  packages/console/src/hooks/use-invoices.ts
  packages/console/src/pages/TenantSettings/BillingHistory/index.tsx
  pnpm-lock.yaml
Labels: enhancement, size/s

#4564 refactor(console): update protect api guide for express.js
  .changeset/fuzzy-glasses-double.md
  packages/console/src/assets/docs/guides/api-express/README.mdx
Labels: enhancement, size/m

#4565 fix(phrases): phrase key should not contain dot
  .changeset/lovely-masks-relax.md
  packages/phrases-experience/README.md
  packages/phrases-experience/src/locales/de/description.ts
  packages/phrases-experience/src/locales/de/error/password-rejected.ts
  packages/phrases-experience/src/locales/en/description.ts
  packages/phrases-experience/src/locales/en/error/password-rejected.ts
  packages/phrases-experience/src/locales/es/description.ts
  packages/phrases-experience/src/locales/es/error/password-rejected.ts
  packages/phrases-experience/src/locales/fr/description.ts
  packages/phrases-experience/src/locales/fr/error/password-rejected.ts
  packages/phrases-experience/src/locales/it/description.ts
  packages/phrases-experience/src/locales/it/error/password-rejected.ts
  packages/phrases-experience/src/locales/ja/description.ts
  packages/phrases-experience/src/locales/ja/error/password-rejected.ts
  packages/phrases-experience/src/locales/ja/list.ts
  packages/phrases-experience/src/locales/ko/description.ts
  packages/phrases-experience/src/locales/ko/error/password-rejected.ts
  packages/phrases-experience/src/locales/pl-pl/description.ts
  packages/phrases-experience/src/locales/pl-pl/error/password-rejected.ts
  packages/phrases-experience/src/locales/pt-br/description.ts
  packages/phrases-experience/src/locales/pt-br/error/password-rejected.ts
  packages/phrases-experience/src/locales/pt-pt/description.ts
  packages/phrases-experience/src/locales/pt-pt/error/password-rejected.ts
  packages/phrases-experience/src/locales/ru/description.ts
  packages/phrases-experience/src/locales/ru/error/password-rejected.ts
  packages/phrases-experience/src/locales/tr-tr/description.ts
  packages/phrases-experience/src/locales/tr-tr/error/password-rejected.ts
  packages/phrases-experience/src/locales/zh-cn/description.ts
  packages/phrases-experience/src/locales/zh-cn/error/password-rejected.ts
  packages/phrases-experience/src/locales/zh-hk/description.ts
  packages/phrases-experience/src/locales/zh-hk/error/password-rejected.ts
  packages/phrases-experience/src/locales/zh-tw/description.ts
  packages/phrases-experience/src/locales/zh-tw/error/password-rejected.ts
  packages/phrases/README.md
Labels: bugfix, size/l

#4550 refactor(shared)!: standardize id and secret generators
  .changeset/proud-donuts-check.md
  packages/cli/src/commands/database/utils.ts
  packages/console/src/assets/docs/guides/web-asp-net-core-mvc/README.mdx
  packages/console/src/assets/docs/guides/web-asp-net-core/README.mdx
  packages/console/src/assets/docs/guides/web-express/README.mdx
  packages/console/src/assets/docs/guides/web-next-app-router/README.mdx
  packages/console/src/assets/docs/guides/web-next/README.mdx
  packages/console/src/assets/docs/guides/web-php/README.mdx
  packages/console/src/assets/docs/guides/web-python/README.mdx
  packages/console/src/assets/docs/guides/web-remix/README.mdx
  packages/console/src/pages/Profile/components/LinkAccountSection/index.tsx
  packages/core/src/__mocks__/index.ts
  packages/core/src/libraries/hook/index.test.ts
  packages/core/src/libraries/user.ts
  packages/core/src/middleware/koa-audit-log.test.ts
  packages/core/src/routes/admin-user-role.test.ts
  packages/core/src/routes/application-role.test.ts
  packages/core/src/routes/application.test.ts
  packages/core/src/routes/application.ts
  packages/core/src/routes/connector/index.ts
  packages/core/src/routes/custom-phrase.test.ts
  packages/core/src/routes/hook.ts
  packages/core/src/routes/resource.test.ts
  packages/core/src/routes/resource.ts
  packages/core/src/routes/role.application.test.ts
  packages/core/src/routes/role.scope.test.ts
  packages/core/src/routes/role.test.ts
  packages/core/src/routes/role.user.test.ts
  packages/core/src/test-utils/nanoid.ts
  packages/schemas/src/seeds/application.ts
  packages/shared/src/utils/id.test.ts
  packages/shared/src/utils/id.ts
  packages/toolkit/core-kit/src/models/tenant.ts
Labels: enhancement, bugfix, size/l

#4504 feat: init sentinel
  packages/schemas/alterations/next-1694854226-init-sentinel.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/gen/index.ts
  packages/schemas/src/gen/schema.ts
  packages/schemas/src/gen/types.ts
  packages/schemas/src/gen/utils.ts
  packages/schemas/src/types/index.ts
  packages/schemas/src/types/sentinel.ts
  packages/schemas/tables/logs.sql
  packages/schemas/tables/sentinel_activities.sql
Labels: feature, size/m

#4569 refactor(schemas,console,core): remove admin access switch for m2m apps
  packages/console/src/assets/docs/guides/m2m-general/README.mdx
  packages/console/src/assets/docs/guides/m2m-general/assets/assign-mgmt-api-role.webp
  packages/console/src/assets/docs/guides/m2m-general/assets/create-m2m-mgmt-api-role.webp
  packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/schemas/alterations/next-1695198741-remove-m2m-app-admin-access-switch.ts
Labels: enhancement, size/l

#4576 chore: add `dev_features_enabled` argument to dockerfile
  Dockerfile
Labels: chore, size/xs

#4554 feat(core): init basic sentinel
  packages/core/src/sentinel/basic-sentinel.test.ts
  packages/core/src/sentinel/basic-sentinel.ts
  packages/core/src/test-utils/query.ts
  packages/schemas/src/types/sentinel.ts
Labels: feature, size/l

#4560 feat(schemas,console): add mfa interaction log key
  packages/console/src/consts/logs.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/types/log/interaction.ts
Labels: feature, size/s

#4573 refactor(core): improve oidc error handling
  packages/cli/src/commands/translate/sync-keys/utils.ts
  packages/core/jest.setup.js
  packages/core/src/libraries/hook/index.test.ts
  packages/core/src/libraries/sign-in-experience/sign-up.test.ts
  packages/core/src/middleware/koa-connector-error-handler.test.ts
  packages/core/src/middleware/koa-error-handler.ts
  packages/core/src/middleware/koa-oidc-error-handler.test.ts
  packages/core/src/middleware/koa-oidc-error-handler.ts
  packages/core/src/oidc/init.ts
  packages/core/src/tenants/Tenant.ts
  packages/phrases/src/locales/de/errors/oidc.ts
  packages/phrases/src/locales/en/errors/oidc.ts
  packages/phrases/src/locales/es/errors/oidc.ts
  packages/phrases/src/locales/fr/errors/oidc.ts
  packages/phrases/src/locales/it/errors/oidc.ts
  packages/phrases/src/locales/ja/errors/oidc.ts
  packages/phrases/src/locales/ko/errors/oidc.ts
  packages/phrases/src/locales/pl-pl/errors/oidc.ts
  packages/phrases/src/locales/pt-br/errors/oidc.ts
  packages/phrases/src/locales/pt-pt/errors/oidc.ts
  packages/phrases/src/locales/ru/errors/oidc.ts
  packages/phrases/src/locales/tr-tr/errors/oidc.ts
  packages/phrases/src/locales/zh-cn/errors/oidc.ts
  packages/phrases/src/locales/zh-hk/errors/oidc.ts
  packages/phrases/src/locales/zh-tw/errors/oidc.ts
Labels: enhancement, size/l

#4562 feat(core): integrate basic sentinel
  .changeset/proud-meals-bathe.md
  packages/core/src/middleware/koa-i18next.ts
  packages/core/src/routes/interaction/verifications/identifier-payload-verification.ts
  packages/core/src/sentinel/basic-sentinel.ts
  packages/core/src/tenants/Tenant.ts
  packages/core/src/tenants/TenantContext.ts
  packages/core/src/test-utils/sentinel.ts
  packages/core/src/test-utils/tenant.ts
  packages/core/src/utils/i18n.ts
  packages/integration-tests/src/tests/experience/basic-sentinel.test.ts
  packages/integration-tests/src/tests/experience/bootstrap.test.ts
  packages/integration-tests/src/tests/experience/password-policy.test.ts
  packages/integration-tests/src/ui-helpers/expect-console.ts
  packages/integration-tests/src/ui-helpers/expect-experience.ts
  packages/integration-tests/src/ui-helpers/expect-page.ts
  packages/integration-tests/src/ui-helpers/index.ts
  packages/phrases/src/locales/de/errors/session.ts
  packages/phrases/src/locales/en/errors/session.ts
  packages/phrases/src/locales/es/errors/session.ts
  packages/phrases/src/locales/fr/errors/session.ts
  packages/phrases/src/locales/it/errors/session.ts
  packages/phrases/src/locales/ja/errors/session.ts
  packages/phrases/src/locales/ko/errors/session.ts
  packages/phrases/src/locales/pl-pl/errors/session.ts
  packages/phrases/src/locales/pt-br/errors/session.ts
  packages/phrases/src/locales/pt-pt/errors/session.ts
  packages/phrases/src/locales/ru/errors/session.ts
  packages/phrases/src/locales/tr-tr/errors/session.ts
  packages/phrases/src/locales/zh-cn/errors/session.ts
  packages/phrases/src/locales/zh-hk/errors/session.ts
  packages/phrases/src/locales/zh-tw/errors/session.ts
  packages/schemas/src/types/sentinel.ts
Labels: feature, size/l

#4581 refactor(console,phrases): hide role type selection on creation modal by default
  packages/console/src/ds-components/RadioGroup/Radio.module.scss
  packages/console/src/ds-components/RadioGroup/Radio.tsx
  packages/console/src/pages/Roles/components/CreateRoleForm/index.module.scss
  packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/roles.ts
  packages/phrases/src/locales/en/translation/admin-console/roles.ts
  packages/phrases/src/locales/es/translation/admin-console/roles.ts
  packages/phrases/src/locales/fr/translation/admin-console/roles.ts
  packages/phrases/src/locales/it/translation/admin-console/roles.ts
  packages/phrases/src/locales/ja/translation/admin-console/roles.ts
  packages/phrases/src/locales/ko/translation/admin-console/roles.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/roles.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/roles.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/roles.ts
  packages/phrases/src/locales/ru/translation/admin-console/roles.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/roles.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/roles.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/roles.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/roles.ts
Labels: enhancement, size/m

#4551 feat(core,phrases,schemas): implement bind mfa totp
  packages/core/package.json
  packages/core/src/__mocks__/mfa-verification.ts
  packages/core/src/routes/interaction/actions/submit-interaction.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/core/src/routes/interaction/additional.test.ts
  packages/core/src/routes/interaction/additional.ts
  packages/core/src/routes/interaction/index.test.ts
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/mfa.test.ts
  packages/core/src/routes/interaction/mfa.ts
  packages/core/src/routes/interaction/types/guard.ts
  packages/core/src/routes/interaction/types/index.ts
  packages/core/src/routes/interaction/utils/index.ts
  packages/core/src/routes/interaction/utils/sign-in-experience-valiation.test.ts
  packages/core/src/routes/interaction/utils/sign-in-experience-validation.ts
  packages/core/src/routes/interaction/utils/totp-validation.test.ts
  packages/core/src/routes/interaction/utils/totp-validation.ts
  packages/core/src/routes/interaction/verifications/index.ts
  packages/core/src/routes/interaction/verifications/mfa-payload-verification.test.ts
  packages/core/src/routes/interaction/verifications/mfa-payload-verification.ts
  packages/core/src/routes/interaction/verifications/mfa-verification.test.ts
  packages/core/src/routes/interaction/verifications/mfa-verification.ts
  packages/schemas/src/types/interactions.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#4584 chore: rename `ui` to `experience` in commit message scope enums
  commitlint.config.cjs
Labels: chore, size/xs

#4566 test: add tests for mfa totp flows
  packages/integration-tests/package.json
  packages/integration-tests/src/api/interaction.ts
  packages/integration-tests/src/helpers/sign-in-experience.ts
  packages/integration-tests/src/tests/api/interaction/mfa/totp.test.ts
  pnpm-lock.yaml
Labels: testing, size/m

#4587 fix(console): should not show admin console in audit log app selector
  packages/console/src/components/AuditLogTable/components/ApplicationSelector/index.tsx
Labels: bugfix, size/s

#4585 chore(console,phrases): fix console UI issues
  packages/console/src/pages/ApplicationDetails/components/MachineToMachineApplicationRoles/index.module.scss
  packages/console/src/pages/ApplicationDetails/components/MachineToMachineApplicationRoles/index.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/RoleDetails/RoleApplications/index.module.scss
  packages/console/src/pages/RoleDetails/RoleApplications/index.tsx
  packages/console/src/pages/RoleDetails/index.tsx
  packages/console/src/pages/Roles/components/AssignedEntities/index.tsx
  packages/console/src/pages/Roles/index.tsx
  packages/console/src/pages/UserDetails/UserRoles/index.module.scss
  packages/console/src/pages/UserDetails/UserRoles/index.tsx
  packages/integration-tests/src/tests/console/rbac.test.ts
  packages/phrases/src/locales/de/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/es/translation/admin-console/application-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/it/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/application-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts
Labels: chore, size/m

#4570 feat(core,schemas,phrases): verify totp to sign in
  packages/console/src/consts/logs.ts
  packages/core/src/routes/interaction/index.test.ts
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/mfa.test.ts
  packages/core/src/routes/interaction/mfa.ts
  packages/core/src/routes/interaction/types/guard.ts
  packages/core/src/routes/interaction/types/index.ts
  packages/core/src/routes/interaction/utils/interaction.ts
  packages/core/src/routes/interaction/verifications/mfa-payload-verification.test.ts
  packages/core/src/routes/interaction/verifications/mfa-payload-verification.ts
  packages/core/src/routes/interaction/verifications/mfa-verification.test.ts
  packages/core/src/routes/interaction/verifications/mfa-verification.ts
  packages/integration-tests/src/api/interaction.ts
  packages/integration-tests/src/tests/api/interaction/mfa/totp.test.ts
  packages/phrases/src/locales/de/errors/session.ts
  packages/phrases/src/locales/en/errors/session.ts
  packages/phrases/src/locales/es/errors/session.ts
  packages/phrases/src/locales/fr/errors/session.ts
  packages/phrases/src/locales/it/errors/session.ts
  packages/phrases/src/locales/ja/errors/session.ts
  packages/phrases/src/locales/ko/errors/session.ts
  packages/phrases/src/locales/pl-pl/errors/session.ts
  packages/phrases/src/locales/pt-br/errors/session.ts
  packages/phrases/src/locales/pt-pt/errors/session.ts
  packages/phrases/src/locales/ru/errors/session.ts
  packages/phrases/src/locales/tr-tr/errors/session.ts
  packages/phrases/src/locales/zh-cn/errors/session.ts
  packages/phrases/src/locales/zh-hk/errors/session.ts
  packages/phrases/src/locales/zh-tw/errors/session.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/types/interactions.ts
  packages/schemas/src/types/log/interaction.ts
Labels: feature, size/xl

#4588 fix(console,phrases): update content of assigning new roles on app details page
  packages/console/src/components/RolesTransfer/components/SourceRoleItem/index.tsx
  packages/console/src/components/RolesTransfer/components/SourceRolesBox/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/es/translation/admin-console/application-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/it/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/application-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts
Labels: bugfix, size/s

#4586 fix(console): fix AuditLogTable components application selector
  packages/console/src/components/AuditLogTable/index.tsx
Labels: bugfix, size/s

#4591 fix(console): update content of assigning new roles on app details page
  packages/console/src/components/RolesTransfer/components/SourceRoleItem/index.tsx
  packages/console/src/components/RolesTransfer/components/SourceRolesBox/index.tsx
  packages/console/src/components/RolesTransfer/components/TargetRoleItem/index.tsx
Labels: bugfix, size/s

#4592 fix(console): fix the invalid_target error block console consent issue
  packages/console/package.json
  packages/console/src/containers/ErrorBoundary/index.tsx
  pnpm-lock.yaml
Labels: bugfix, size/s

#4595 chore(phrases,test): update M2M RBAC i18n content
  packages/integration-tests/src/tests/console/rbac.test.ts
  packages/phrases/src/locales/de/translation/admin-console/application-details.ts
  packages/phrases/src/locales/de/translation/admin-console/role-details.ts
  packages/phrases/src/locales/de/translation/admin-console/roles.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/role-details.ts
  packages/phrases/src/locales/en/translation/admin-console/roles.ts
  packages/phrases/src/locales/en/translation/admin-console/user-details.ts
  packages/phrases/src/locales/es/translation/admin-console/application-details.ts
  packages/phrases/src/locales/es/translation/admin-console/role-details.ts
  packages/phrases/src/locales/es/translation/admin-console/roles.ts
  packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/role-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/roles.ts
  packages/phrases/src/locales/it/translation/admin-console/application-details.ts
  packages/phrases/src/locales/it/translation/admin-console/role-details.ts
  packages/phrases/src/locales/it/translation/admin-console/roles.ts
  packages/phrases/src/locales/it/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/role-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/roles.ts
  packages/phrases/src/locales/ja/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/role-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/roles.ts
  packages/phrases/src/locales/ko/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/role-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/roles.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/role-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/roles.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/role-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/roles.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/role-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/roles.ts
  packages/phrases/src/locales/ru/translation/admin-console/user-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/role-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/roles.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/role-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/roles.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/role-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/roles.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/role-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/roles.ts
Labels: chore, size/xl

#4599 chore(schemas): update management api access name/desc to sentence case
  packages/schemas/alterations/next-1695198741-remove-m2m-app-admin-access-switch.ts
Labels: chore, size/xs

#4593 chore: add M2M RBAC changeset and remove feature switch
  .changeset/famous-zebras-begin.md
  packages/console/src/components/RoleScopesTransfer/components/SourceScopesBox/index.tsx
  packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
Labels: chore, size/s

#4598 chore(test): add M2M RBAC console test
  packages/integration-tests/src/tests/console/applications/helpers.ts
  packages/integration-tests/src/tests/console/applications/index.test.ts
  packages/integration-tests/src/tests/console/machine-to-machine-rbac/machime-to-machime-rbac.test.ts
  packages/integration-tests/src/tests/console/machine-to-machine-rbac/utils.ts
Labels: chore, size/l
