Repository logto-io/logto, pull requests merged in 2023-08, with the labels that each got.

#4243 refactor(core,console): filter out webhook logs from audit logs list
  packages/console/src/components/AuditLogTable/index.tsx
  packages/console/src/consts/logs.ts
  packages/core/src/queries/log.ts
  packages/core/src/routes/hook.test.ts
  packages/core/src/routes/hook.ts
  packages/core/src/routes/log.test.ts
  packages/core/src/routes/log.ts
  packages/integration-tests/src/api/logs.ts
  packages/integration-tests/src/tests/api/audit-logs/index.test.ts
  packages/integration-tests/src/tests/api/hook/hook.trigger.test.ts
  packages/integration-tests/src/tests/api/log.test.ts
  packages/schemas/src/types/log/index.ts
Labels: enhancement, size/l

#4269 refactor: allow non-http scheme in cors origin
  .changeset/fast-shirts-switch.md
  packages/console/src/pages/ApplicationDetails/components/Settings.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/utils/validator.ts
  packages/core/src/routes/application.test.ts
  packages/schemas/src/foundations/jsonb-types.ts
Labels: enhancement, size/s

#4271 fix(core): exclude standard connectors when compute social connector usage
  packages/core/src/libraries/quota.ts
Labels: bugfix, size/xs

#4276 chore(phrases): apply title-cased plan name for tenant plan selection button
  packages/console/package.json
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/index.tsx
  packages/console/src/components/PlanName/index.tsx
  pnpm-lock.yaml
Labels: chore, size/s

#4277 ci(core): disable cloud metadata rule in zap
  .github/workflows/pen-tests.yml
  .zap/rules.conf
Labels: size/s

#4273 style(console): prepend space for plan usage percentage
  packages/console/src/components/PlanUsage/index.tsx
Labels: size/xs

#4274 fix(console): fix connector post/patch error rendering
  packages/console/src/components/ConnectorForm/ConfigForm/ConfigFormFields/index.tsx
  packages/console/src/pages/Connectors/Guide/index.tsx
Labels: bugfix, size/s

#4281 feat: mailgun connector
  .changeset/quiet-yaks-wink.md
  .changeset/spicy-maps-warn.md
  .vscode/settings.json
  packages/cli/src/connector/utils.ts
  packages/connectors/connector-mailgun/CHANGELOG.md
  packages/connectors/connector-mailgun/README.md
  packages/connectors/connector-mailgun/logo.png
  packages/connectors/connector-mailgun/package.json
  packages/connectors/connector-mailgun/src/constant.ts
  packages/connectors/connector-mailgun/src/index.test.ts
  packages/connectors/connector-mailgun/src/index.ts
  packages/connectors/connector-mailgun/src/type.test.ts
  packages/connectors/connector-mailgun/src/types.ts
  packages/connectors/connector-sendgrid-email/README.md
  packages/connectors/connector-sendgrid-email/src/constant.ts
  packages/connectors/connector-sendgrid-email/src/index.ts
  packages/core/src/errors/RequestError/index.ts
  packages/core/src/middleware/koa-connector-error-handler.ts
  packages/phrases/src/locales/de/errors/connector.ts
  packages/phrases/src/locales/en/errors/connector.ts
  packages/phrases/src/locales/es/errors/connector.ts
  packages/phrases/src/locales/fr/errors/connector.ts
  packages/phrases/src/locales/it/errors/connector.ts
  packages/phrases/src/locales/ja/errors/connector.ts
  packages/phrases/src/locales/ko/errors/connector.ts
  packages/phrases/src/locales/pl-pl/errors/connector.ts
  packages/phrases/src/locales/pt-br/errors/connector.ts
  packages/phrases/src/locales/pt-pt/errors/connector.ts
  packages/phrases/src/locales/ru/errors/connector.ts
  packages/phrases/src/locales/tr-tr/errors/connector.ts
  packages/phrases/src/locales/zh-cn/errors/connector.ts
  packages/phrases/src/locales/zh-hk/errors/connector.ts
  packages/phrases/src/locales/zh-tw/errors/connector.ts
  packages/toolkit/connector-kit/src/types.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#4286 refactor: validate config generic
  packages/connectors/connector-alipay-native/src/index.ts
  packages/connectors/connector-alipay-web/src/index.ts
  packages/connectors/connector-aliyun-dm/src/index.ts
  packages/connectors/connector-aliyun-sms/src/index.ts
  packages/connectors/connector-apple/src/index.ts
  packages/connectors/connector-aws-ses/src/index.ts
  packages/connectors/connector-azuread/src/index.ts
  packages/connectors/connector-discord/src/index.ts
  packages/connectors/connector-facebook/src/index.ts
  packages/connectors/connector-feishu-web/src/index.ts
  packages/connectors/connector-github/src/index.ts
  packages/connectors/connector-google/src/index.ts
  packages/connectors/connector-kakao/src/index.ts
  packages/connectors/connector-logto-email/src/index.ts
  packages/connectors/connector-logto-sms/src/index.ts
  packages/connectors/connector-logto-social-demo/src/index.ts
  packages/connectors/connector-mailgun/src/index.ts
  packages/connectors/connector-mock-email-alternative/src/index.ts
  packages/connectors/connector-mock-email/src/index.ts
  packages/connectors/connector-mock-sms/src/index.ts
  packages/connectors/connector-naver/src/index.ts
  packages/connectors/connector-oauth2/src/index.ts
  packages/connectors/connector-oidc/src/index.ts
  packages/connectors/connector-saml/src/index.ts
  packages/connectors/connector-sendgrid-email/src/index.ts
  packages/connectors/connector-smsaero/src/index.ts
  packages/connectors/connector-smtp/src/index.ts
  packages/connectors/connector-tencent-sms/src/index.ts
  packages/connectors/connector-twilio-sms/src/index.ts
  packages/connectors/connector-wechat-native/src/index.ts
  packages/connectors/connector-wechat-web/src/index.ts
  packages/toolkit/connector-kit/src/index.test.ts
  packages/toolkit/connector-kit/src/index.ts
Labels: enhancement, size/m

#4272 refactor(console): use `useSWRImmutable` to avoid redundant subscrtipion data fetching
  packages/console/src/components/MauExceededModal/index.tsx
  packages/console/src/components/PaymentOverdueModal/index.tsx
Labels: enhancement, size/m

#4290 refactor(connector): support mailgun endpoint
  packages/connectors/connector-mailgun/README.md
  packages/connectors/connector-mailgun/src/constant.ts
  packages/connectors/connector-mailgun/src/index.test.ts
  packages/connectors/connector-mailgun/src/index.ts
  packages/connectors/connector-mailgun/src/type.test.ts
  packages/connectors/connector-mailgun/src/types.ts
Labels: enhancement, size/s

#4289 feat(console): add learn more link for webhook settings description
  packages/console/src/pages/WebhookDetails/WebhookSettings/index.tsx
Labels: feature, size/xs

#4292 refactor(test): refactor `expectRejects` helper method to support status code checking
  packages/integration-tests/src/helpers/admin-tenant.ts
  packages/integration-tests/src/helpers/index.ts
  packages/integration-tests/src/helpers/interactions.ts
  packages/integration-tests/src/tests/api/admin-user.roles.test.ts
  packages/integration-tests/src/tests/api/admin-user.search.test.ts
  packages/integration-tests/src/tests/api/admin-user.test.ts
  packages/integration-tests/src/tests/api/connector.test.ts
  packages/integration-tests/src/tests/api/dashboard.test.ts
  packages/integration-tests/src/tests/api/hook/hook.test.ts
  packages/integration-tests/src/tests/api/hook/hook.testing.test.ts
  packages/integration-tests/src/tests/api/interaction/forgot-password.test.ts
  packages/integration-tests/src/tests/api/interaction/register-with-identifier.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-passcode-identifier.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier.test.ts
  packages/integration-tests/src/tests/api/interaction/social-interaction.test.ts
  packages/integration-tests/src/tests/api/log.test.ts
  packages/integration-tests/src/tests/api/me.test.ts
  packages/integration-tests/src/tests/api/resource.test.ts
  packages/integration-tests/src/tests/api/sign-in-experience.test.ts
  packages/integration-tests/src/tests/api/verification-code.test.ts
Labels: enhancement, size/l

#4296 test: add sad paths for sign-in with passcode flow
  packages/integration-tests/src/api/admin-user.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-passcode-identifier/happy-path.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-passcode-identifier/sad-path.test.ts
Labels: testing, size/l

#4305 fix(core,phrases): ignore cloudflare not found when deleting domain
  packages/core/src/libraries/domain.ts
  packages/core/src/utils/cloudflare/index.ts
  packages/phrases/src/locales/de/errors/domain.ts
  packages/phrases/src/locales/en/errors/domain.ts
  packages/phrases/src/locales/es/errors/domain.ts
  packages/phrases/src/locales/fr/errors/domain.ts
  packages/phrases/src/locales/it/errors/domain.ts
  packages/phrases/src/locales/ja/errors/domain.ts
  packages/phrases/src/locales/ko/errors/domain.ts
  packages/phrases/src/locales/pl-pl/errors/domain.ts
  packages/phrases/src/locales/pt-br/errors/domain.ts
  packages/phrases/src/locales/pt-pt/errors/domain.ts
  packages/phrases/src/locales/ru/errors/domain.ts
  packages/phrases/src/locales/tr-tr/errors/domain.ts
  packages/phrases/src/locales/zh-cn/errors/domain.ts
  packages/phrases/src/locales/zh-hk/errors/domain.ts
  packages/phrases/src/locales/zh-tw/errors/domain.ts
Labels: bugfix, size/s

#4302 chore: fix typo in README file
  README.md
Labels: chore, size/xs

#4308 refactor(console): update plan quota table
  packages/console/src/pages/TenantSettings/Subscription/PlanQuotaTable/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanQuotaTable/utils.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-table.ts
Labels: enhancement, size/s

#4312 chore(phrases): remove unused keys
  packages/phrases/src/locales/de/translation/admin-console/application-details.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/es/translation/admin-console/application-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/it/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko/errors/domain.ts
  packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/application-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts
Labels: chore, size/s

#4307 test(core): add hasActiveUser test case
  .github/CODEOWNERS
  packages/integration-tests/src/api/admin-user.ts
  packages/integration-tests/src/helpers/index.ts
  packages/integration-tests/src/tests/api/admin-user.search.test.ts
  packages/integration-tests/src/tests/ui/bootstrap.test.ts
Labels: testing, size/s

#4298 test: add sad paths for reset password flow
  packages/integration-tests/src/tests/api/interaction/forgot-password/happy-path.test.ts
  packages/integration-tests/src/tests/api/interaction/forgot-password/sad-path.test.ts
Labels: testing, size/m

#4294 test: add sad paths for sign in with password identifier flow
  packages/integration-tests/src/tests/api/interaction/sign-in-with-passcode-identifier/sad-path.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier/happy-path.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier/sad-path.test.ts
Labels: testing, size/m

#4310 refactor(cloud): clarify the isTest scope
  packages/core/src/env-set/create-pool.ts
  packages/core/src/env-set/index.ts
  packages/shared/src/node/env/GlobalValues.ts
Labels: enhancement, size/s

#4303 ci: changeset workflow is invalid on pull_request
  .github/workflows/changesets.yml
Labels: size/xs

#4285 fix: replace INFO with IGNORE in zap rules
  .zap/rules.conf
Labels: bugfix, size/s

#4315 chore: update CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: chore, size/xs

#4309 refactor(toolkit,connector,core,cli): cache access token for logto email service
  packages/cli/src/connector/utils.ts
  packages/connectors/connector-logto-email/src/grant-access-token.test.ts
  packages/connectors/connector-logto-email/src/grant-access-token.ts
  packages/connectors/connector-logto-email/src/index.test.ts
  packages/connectors/connector-logto-email/src/index.ts
  packages/connectors/connector-logto-email/src/mock.ts
  packages/core/src/libraries/cloud-connection.ts
  packages/core/src/libraries/connector.test.ts
  packages/core/src/libraries/connector.ts
  packages/core/src/libraries/sign-in-experience/index.test.ts
  packages/core/src/routes/connector/config-testing.ts
  packages/toolkit/connector-kit/package.json
  packages/toolkit/connector-kit/src/types.ts
  pnpm-lock.yaml
Labels: enhancement, size/l

#4317 refactor(console): improve tenant selector loading state
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/TenantDropdownItem/Skeleton/index.module.scss
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/TenantDropdownItem/Skeleton/index.tsx
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/TenantDropdownItem/TenantStatusTag.tsx
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/TenantDropdownItem/index.module.scss
  packages/console/src/containers/AppContent/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx
Labels: enhancement, size/s

#4318 refactor(console): only show loading status on selected subscription button
  packages/console/src/pages/TenantSettings/Subscription/SwitchPlanActionBar/index.tsx
Labels: enhancement, size/s

#4299 test: add sad paths for register with identifiers flow
  packages/integration-tests/src/tests/api/interaction/register-with-identifier/happy-path.test.ts
  packages/integration-tests/src/tests/api/interaction/register-with-identifier/sad-path.test.ts
Labels: testing, size/m

#4306 test: interaction api counter cases and response status guard
  packages/core/src/include.d/koa-router.d.ts
  packages/core/src/routes/interaction/index.ts
  packages/integration-tests/src/api/interaction.ts
  packages/integration-tests/src/tests/api/interaction/api-counter-cases/interaction-details-guard.test.ts
  packages/integration-tests/src/tests/api/interaction/api-counter-cases/interaction-results-checking.test.ts
  packages/integration-tests/src/tests/api/interaction/api-counter-cases/patch-interaction-identifiers.test.ts
  packages/integration-tests/src/tests/api/interaction/api-counter-cases/post-send-verification-code.test.ts
  packages/integration-tests/src/tests/api/interaction/api-counter-cases/put-interaction-event.test.ts
  packages/integration-tests/src/tests/api/interaction/api-counter-cases/put-interaction.test.ts
Labels: testing, size/xl

#4316 fix(core): fix cloudflare hostname not found error handler
  packages/core/src/libraries/domain.test.ts
  packages/core/src/libraries/domain.ts
Labels: bugfix, size/s

#4319 fix(console): react-markdown rendering error in parcel dev mode
  packages/console/package.json
  packages/console/src/components/Markdown/index.tsx
  pnpm-lock.yaml
Labels: bugfix, size/s

#4314 feat(cli): add key type for rotating command
  .changeset/serious-pants-beg.md
  packages/cli/src/commands/database/config.ts
  packages/cli/src/commands/database/utils.ts
Labels: feature, size/s

#4323 feat(schemas): add isSuspended columns
  packages/schemas/alterations/next-1691979708-add-is-suspend-column-to-tenants-table.ts
  packages/schemas/src/models/tenants.ts
Labels: feature, size/s

#4326 refactor(schemas): add isSuspended to the tenantInfo type
  packages/schemas/package.json
  packages/schemas/src/models/tenants.ts
  pnpm-lock.yaml
Labels: enhancement, size/xs

#4328 test: add ui tests for social connectors
  packages/console/src/utils/connector-form.ts
  packages/integration-tests/src/tests/ui/connectors/social-connector-test-cases.ts
  packages/integration-tests/src/tests/ui/connectors/social-connectors.test.ts
  packages/integration-tests/src/ui-helpers/index.ts
Labels: testing, size/xl

#4325 feat(console): guide modal v2
  packages/console/package.json
  packages/console/src/assets/docs/guides/README.md
  packages/console/src/assets/docs/guides/generate-metadata.js
  packages/console/src/assets/docs/guides/index.ts
  packages/console/src/assets/docs/guides/spa-react/README.mdx
  packages/console/src/assets/docs/guides/spa-react/index.ts
  packages/console/src/assets/docs/guides/spa-react/logo.svg
  packages/console/src/assets/docs/guides/types.ts
  packages/console/src/consts/env.ts
  packages/console/src/hooks/use-scroll.ts
  packages/console/src/mdx-components-v2/README.md
  packages/console/src/mdx-components-v2/Step/index.module.scss
  packages/console/src/mdx-components-v2/Step/index.tsx
  packages/console/src/mdx-components-v2/Steps/index.module.scss
  packages/console/src/mdx-components-v2/Steps/index.tsx
  packages/console/src/pages/Applications/components/Guide/GuideModal.tsx
  packages/console/src/pages/Applications/components/GuideHeaderV2/index.module.scss
  packages/console/src/pages/Applications/components/GuideHeaderV2/index.tsx
  packages/console/src/pages/Applications/components/GuideV2/index.module.scss
  packages/console/src/pages/Applications/components/GuideV2/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/applications.ts
  packages/phrases/src/locales/en/translation/admin-console/applications.ts
  packages/phrases/src/locales/es/translation/admin-console/applications.ts
  packages/phrases/src/locales/fr/translation/admin-console/applications.ts
  packages/phrases/src/locales/it/translation/admin-console/applications.ts
  packages/phrases/src/locales/ja/translation/admin-console/applications.ts
  packages/phrases/src/locales/ko/translation/admin-console/applications.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/applications.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/applications.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/applications.ts
  packages/phrases/src/locales/ru/translation/admin-console/applications.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/applications.ts
  packages/toolkit/core-kit/scss/_console-themes.scss
Labels: feature, size/xl

#4327 feat(console): show sample for the guide and allow request new guide
  packages/console/src/assets/docs/guides/generate-metadata.js
  packages/console/src/assets/docs/guides/index.ts
  packages/console/src/assets/docs/guides/spa-react/README.mdx
  packages/console/src/assets/docs/guides/spa-react/index.ts
  packages/console/src/assets/docs/guides/types.ts
  packages/console/src/assets/docs/guides/web-express/README.mdx
  packages/console/src/assets/docs/guides/web-express/index.ts
  packages/console/src/assets/docs/guides/web-express/logo.svg
  packages/console/src/consts/external-links.ts
  packages/console/src/ds-components/Button/index.module.scss
  packages/console/src/ds-components/Button/index.tsx
  packages/console/src/hooks/use-api.ts
  packages/console/src/hooks/use-me-custom-data.ts
  packages/console/src/mdx-components-v2/Sample/index.module.scss
  packages/console/src/mdx-components-v2/Sample/index.tsx
  packages/console/src/mdx-components-v2/Steps/index.tsx
  packages/console/src/pages/Applications/components/GuideHeaderV2/RequestGuide.tsx
  packages/console/src/pages/Applications/components/GuideHeaderV2/index.tsx
  packages/console/src/pages/Applications/components/GuideV2/index.tsx
  packages/core/src/routes/swagger.ts
  packages/phrases/src/locales/de/translation/admin-console/applications.ts
  packages/phrases/src/locales/de/translation/admin-console/general.ts
  packages/phrases/src/locales/en/translation/admin-console/applications.ts
  packages/phrases/src/locales/en/translation/admin-console/general.ts
  packages/phrases/src/locales/es/translation/admin-console/applications.ts
  packages/phrases/src/locales/es/translation/admin-console/general.ts
  packages/phrases/src/locales/fr/translation/admin-console/applications.ts
  packages/phrases/src/locales/fr/translation/admin-console/general.ts
  packages/phrases/src/locales/it/translation/admin-console/applications.ts
  packages/phrases/src/locales/it/translation/admin-console/general.ts
  packages/phrases/src/locales/ja/translation/admin-console/applications.ts
  packages/phrases/src/locales/ja/translation/admin-console/general.ts
  packages/phrases/src/locales/ko/translation/admin-console/applications.ts
  packages/phrases/src/locales/ko/translation/admin-console/general.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/applications.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/applications.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/applications.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
  packages/phrases/src/locales/ru/translation/admin-console/applications.ts
  packages/phrases/src/locales/ru/translation/admin-console/general.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/applications.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/general.ts
  packages/toolkit/core-kit/src/http.ts
  packages/toolkit/core-kit/src/index.ts
Labels: feature, size/xl

#4329 feat(cli): add rollback-to db action
  packages/cli/src/commands/database/alteration/index.ts
  packages/cli/src/commands/database/alteration/utils.ts
  packages/schemas/alterations/next-1692088012-add-is-suspend-column-to-tenants-table.ts
Labels: feature, size/m

#4334 feat(console): new app creation guide library
  packages/console/src/components/ListPage/index.tsx
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/ds-components/Checkbox/CheckboxGroup/index.module.scss
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/Applications/components/ApplicationsPlaceholder/index.module.scss
  packages/console/src/pages/Applications/components/ApplicationsPlaceholder/index.tsx
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/Applications/components/Guide/GuideModal.tsx
  packages/console/src/pages/Applications/components/Guide/index.tsx
  packages/console/src/pages/Applications/components/GuideCard/index.module.scss
  packages/console/src/pages/Applications/components/GuideCard/index.tsx
  packages/console/src/pages/Applications/components/GuideHeader/RequestGuide.tsx
  packages/console/src/pages/Applications/components/GuideHeader/index.module.scss
  packages/console/src/pages/Applications/components/GuideHeader/index.tsx
  packages/console/src/pages/Applications/components/GuideHeaderV2/index.module.scss
  packages/console/src/pages/Applications/components/GuideHeaderV2/index.tsx
  packages/console/src/pages/Applications/components/GuideLibrary/hook.ts
  packages/console/src/pages/Applications/components/GuideLibrary/index.module.scss
  packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
  packages/console/src/pages/Applications/components/GuideLibraryModal/index.module.scss
  packages/console/src/pages/Applications/components/GuideLibraryModal/index.tsx
  packages/console/src/pages/Applications/components/GuideV2/index.module.scss
  packages/console/src/pages/Applications/components/GuideV2/index.tsx
  packages/console/src/pages/Applications/index.module.scss
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/types/applications.ts
  packages/phrases/src/locales/de/translation/admin-console/applications.ts
  packages/phrases/src/locales/en/translation/admin-console/applications.ts
  packages/phrases/src/locales/es/translation/admin-console/applications.ts
  packages/phrases/src/locales/fr/translation/admin-console/applications.ts
  packages/phrases/src/locales/it/translation/admin-console/applications.ts
  packages/phrases/src/locales/ja/translation/admin-console/applications.ts
  packages/phrases/src/locales/ko/translation/admin-console/applications.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/applications.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/applications.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/applications.ts
  packages/phrases/src/locales/ru/translation/admin-console/applications.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/applications.ts
Labels: feature, size/xl

#4331 test: add ui tests for passwordless connectors
  packages/integration-tests/src/tests/ui/connectors/helpers.ts
  packages/integration-tests/src/tests/ui/connectors/passwordless-connector-test-cases.ts
  packages/integration-tests/src/tests/ui/connectors/passwordless-connectors.test.ts
  packages/integration-tests/src/tests/ui/connectors/social-connectors.test.ts
  packages/integration-tests/src/ui-helpers/index.ts
Labels: testing, size/xl

#4339 test: add ui tests for RBAC operations
  packages/integration-tests/src/tests/ui/rbac.test.ts
Labels: testing, size/l

#4324 test: add ui tests for sie branding config
  packages/integration-tests/src/tests/ui/sign-in-experience.test.ts
Labels: testing, size/m

#4341 chore(console): enable guide v2 in production env
  packages/console/src/consts/env.ts
  packages/console/src/pages/Applications/components/Guide/GuideModal.tsx
Labels: chore, size/s

#4340 fix(console): add max-width to guide card group
  packages/console/src/pages/Applications/components/GuideLibrary/index.module.scss
Labels: bugfix, size/xs

#4335 feat(console): python guide
  packages/console/src/assets/docs/guides/web-gpt-plugin/components/ClientBasics/index.tsx
  packages/console/src/assets/docs/guides/web-python/README.mdx
  packages/console/src/assets/docs/guides/web-python/index.ts
  packages/console/src/pages/Applications/components/GuideV2/index.module.scss
  packages/console/src/pages/Applications/components/GuideV2/index.tsx
Labels: feature, size/m

#4321 feat: post affiliate data to cloud
  packages/core/package.json
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/schemas/alterations/next-1692194751-add-affiliate-scopes.ts
  packages/schemas/src/seeds/cloud-api.ts
  pnpm-lock.yaml
Labels: feature, size/m

#4345 fix(console): add onClick handler to guide done button
  packages/console/src/pages/Applications/components/GuideV2/index.tsx
Labels: bugfix, size/xs

#4349 refactor(console): align further readings section
  packages/console/src/assets/docs/guides/native-android-java/README.mdx
  packages/console/src/assets/docs/guides/native-android-kt/README.mdx
  packages/console/src/assets/docs/guides/native-ios-swift/README.mdx
  packages/console/src/assets/docs/guides/spa-react/README.mdx
  packages/console/src/assets/docs/guides/spa-vanilla/README.mdx
  packages/console/src/assets/docs/guides/spa-vue/README.mdx
  packages/console/src/assets/docs/guides/web-express/README.mdx
  packages/console/src/assets/docs/guides/web-go/README.mdx
  packages/console/src/assets/docs/guides/web-next/README.mdx
  packages/console/src/mdx-components-v2/Step/index.tsx
  packages/console/src/mdx-components-v2/Steps/FurtherReadings.tsx
  packages/console/src/mdx-components-v2/Steps/index.tsx
Labels: enhancement, size/m

#4338 feat(console): add flutter guide
  packages/console/src/assets/docs/guides/native-flutter/README.mdx
Labels: feature, size/m

#4350 refactor(console): remove min-height for readonly code editors
  packages/console/src/ds-components/CodeEditor/index.module.scss
  packages/console/src/ds-components/CodeEditor/index.tsx
Labels: enhancement, size/s

#4343 feat(console): add m2m implementation guide
  packages/console/src/assets/docs/guides/m2m-general/README.mdx
  packages/console/src/assets/docs/guides/m2m-general/assets/api-identifier.png
  packages/console/src/assets/docs/guides/m2m-general/assets/enable-admin-access.png
  packages/console/src/assets/docs/guides/m2m-general/components/EnableAdminAccess.tsx
  packages/console/src/mdx-components-v2/ApplicationCredentials/index.module.scss
  packages/console/src/mdx-components-v2/ApplicationCredentials/index.tsx
  packages/console/src/pages/Applications/components/Guide/GuideModal.tsx
  packages/console/src/pages/Applications/components/GuideV2/index.tsx
Labels: feature, size/m

#4353 fix(schemas): hot fix bump alteration file timestamp
  packages/schemas/alterations/next-1692241956-add-affiliate-scopes.ts
Labels: bugfix, size/xs

#4346 feat(console): nextjs app router guide
  packages/console/src/assets/docs/guides/web-next-app-router/README.mdx
  packages/console/src/assets/docs/guides/web-next-app-router/index.ts
Labels: feature, size/l

#4351 feat(console): php guide
  packages/console/src/assets/docs/guides/web-php/README.mdx
  packages/console/src/assets/docs/guides/web-php/index.ts
  packages/console/src/assets/docs/guides/web-python/README.mdx
Labels: feature, size/m

#4337 feat(console): upsell m2m feature on guide card and library filter
  packages/console/src/components/ProTag/index.tsx
  packages/console/src/pages/Applications/components/GuideCard/index.module.scss
  packages/console/src/pages/Applications/components/GuideCard/index.tsx
  packages/console/src/pages/Applications/components/GuideLibrary/index.module.scss
  packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
Labels: feature, size/s

#4352 feat(console): remix guide
  packages/console/src/assets/docs/guides/index.ts
  packages/console/src/assets/docs/guides/spa-remix/README.mdx
  packages/console/src/assets/docs/guides/spa-remix/index.ts
  packages/console/src/assets/docs/guides/web-remix/README.mdx
  packages/console/src/assets/docs/guides/web-remix/index.ts
  packages/console/src/assets/docs/guides/web-remix/logo.svg
Labels: feature, size/m

#4347 refactor(console): hide navigation anchors from guide in compact view
  packages/console/src/assets/docs/guides/index.ts
  packages/console/src/assets/docs/guides/m2m-general/components/EnableAdminAccess.tsx
  packages/console/src/assets/docs/guides/web-chatgpt/README.mdx
  packages/console/src/assets/docs/guides/web-chatgpt/index.ts
  packages/console/src/assets/docs/guides/web-chatgpt/logo.svg
  packages/console/src/assets/docs/guides/web-gpt-plugin/components/AlwaysIssueRefreshToken.tsx
  packages/console/src/assets/docs/guides/web-gpt-plugin/components/ClientBasics/index.tsx
  packages/console/src/assets/docs/guides/web-gpt-plugin/index.ts
  packages/console/src/assets/docs/guides/web-gpt-plugin/logo.svg
  packages/console/src/assets/docs/guides/web-outline/components/EnvironmentVariables.tsx
  packages/console/src/assets/icons/arrow-left.svg
  packages/console/src/mdx-components-v2/ApplicationCredentials/index.tsx
  packages/console/src/mdx-components-v2/Sample/index.tsx
  packages/console/src/mdx-components-v2/Steps/index.module.scss
  packages/console/src/mdx-components-v2/Steps/index.tsx
  packages/console/src/mdx-components-v2/UriInputField/index.tsx
  packages/console/src/pages/ApplicationDetails/components/GuideDrawer/index.module.scss
  packages/console/src/pages/ApplicationDetails/components/GuideDrawer/index.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/Applications/components/Guide/GuideModal.tsx
  packages/console/src/pages/Applications/components/Guide/index.module.scss
  packages/console/src/pages/Applications/components/Guide/index.tsx
  packages/console/src/pages/Applications/components/GuideCard/index.module.scss
  packages/console/src/pages/Applications/components/GuideCard/index.tsx
  packages/console/src/pages/Applications/components/GuideGroup/index.module.scss
  packages/console/src/pages/Applications/components/GuideGroup/index.tsx
  packages/console/src/pages/Applications/components/GuideLibrary/index.module.scss
  packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
  packages/console/src/pages/Applications/components/GuideLibraryModal/index.tsx
  packages/console/src/pages/Applications/components/GuideV2/index.module.scss
  packages/console/src/pages/Applications/components/GuideV2/index.tsx
  packages/console/src/pages/Applications/components/SdkSelector/index.module.scss
  packages/console/src/pages/Applications/components/SdkSelector/index.tsx
  packages/console/src/types/applications.ts
  packages/phrases/src/locales/de/translation/admin-console/applications.ts
  packages/phrases/src/locales/en/translation/admin-console/applications.ts
  packages/phrases/src/locales/es/translation/admin-console/applications.ts
  packages/phrases/src/locales/fr/translation/admin-console/applications.ts
  packages/phrases/src/locales/it/translation/admin-console/applications.ts
  packages/phrases/src/locales/ja/translation/admin-console/applications.ts
  packages/phrases/src/locales/ko/translation/admin-console/applications.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/applications.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/applications.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/applications.ts
  packages/phrases/src/locales/ru/translation/admin-console/applications.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/applications.ts
Labels: enhancement, size/xl

#4355 revert: 4353
  packages/schemas/alterations/next-1692194751-add-affiliate-scopes.ts
Labels: size/xs

#4356 refactor(console): add post logout redirect uri in guides
  packages/console/src/assets/docs/guides/web-php/README.mdx
  packages/console/src/assets/docs/guides/web-python/README.mdx
Labels: enhancement, size/s

#4354 fix: logo size in get sample section in app integration guide
  packages/console/src/mdx-components-v2/Sample/index.module.scss
  packages/console/src/mdx-components-v2/Sample/index.tsx
  packages/console/src/pages/Applications/components/Guide/index.tsx
Labels: bugfix, size/s

#4357 refactor(console): settings tabs in application details page
  packages/console/src/consts/page-tabs.ts
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx
  packages/console/src/pages/ApplicationDetails/components/Settings.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/ApplicationDetails/types.ts
  packages/phrases/src/locales/de/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/es/translation/admin-console/application-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/it/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/application-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts
Labels: enhancement, size/m

#4358 fix(console): should hide filters from app list empty placeholder
  packages/console/src/pages/Applications/components/GuideGroup/index.module.scss
  packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
  packages/console/src/pages/Applications/components/GuideLibraryModal/index.tsx
Labels: bugfix, size/s

#4359 fix(console): adjust the app guide order
  packages/console/src/assets/docs/guides/index.ts
Labels: bugfix, size/m

#4360 fix(console): fix Golang guide crash
  packages/console/src/mdx-components-v2/UriInputField/index.tsx
Labels: bugfix, size/xs

#4361 fix(console): resolve forwardRef warning in debugger console
  packages/console/src/mdx-components-v2/Steps/FurtherReadings.tsx
Labels: bugfix, size/s

#4363 chore(console): update some app guide description content
  packages/console/src/assets/docs/guides/web-go/index.ts
  packages/console/src/assets/docs/guides/web-next-app-router/index.ts
  packages/console/src/assets/docs/guides/web-next/index.ts
  packages/console/src/assets/docs/guides/web-remix/index.ts
Labels: chore, size/xs

#4364 fix(console): guide navigation anchors should be clickable and jump to the step
  packages/console/src/mdx-components-v2/Steps/index.module.scss
  packages/console/src/mdx-components-v2/Steps/index.tsx
Labels: bugfix, size/s

#4369 fix(console): add trySafe to report methods
  packages/console/src/components/ReportConversion/utils.ts
Labels: bugfix, size/s

#4370 fix(console): remove inspire me phone as identifier options
  packages/console/src/onboarding/pages/SignInExperience/sie-config-templates.ts
Labels: bugfix, size/s

#4368 fix(console): show placeholder when no search is found in guide library
  packages/console/src/components/EmptyDataPlaceholder/index.tsx
  packages/console/src/pages/Applications/components/GuideLibrary/index.module.scss
  packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
Labels: bugfix, size/s

#4371 style(console): use shadow-3 for footer action bar
  packages/console/src/pages/Applications/components/Guide/index.module.scss
  packages/console/src/pages/Applications/components/GuideLibraryModal/index.module.scss
Labels: size/xs

#4372 refactor(console): add toast after creating application successfully
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/applications.ts
  packages/phrases/src/locales/en/translation/admin-console/applications.ts
  packages/phrases/src/locales/es/translation/admin-console/applications.ts
  packages/phrases/src/locales/fr/translation/admin-console/applications.ts
  packages/phrases/src/locales/it/translation/admin-console/applications.ts
  packages/phrases/src/locales/ja/translation/admin-console/applications.ts
  packages/phrases/src/locales/ko/translation/admin-console/applications.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/applications.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/applications.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/applications.ts
  packages/phrases/src/locales/ru/translation/admin-console/applications.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/applications.ts
Labels: enhancement, size/s

#4375 style(console): add margin around input fields in app guide
  packages/console/src/mdx-components-v2/UriInputField/index.module.scss
Labels: size/xs

#4373 test: add ui tests for sign-up and sign-in settings
  packages/integration-tests/src/tests/ui/sign-in-experience.test.ts
  packages/integration-tests/src/tests/ui/sign-in-experience/branding.test.ts
  packages/integration-tests/src/tests/ui/sign-in-experience/helpers.ts
  packages/integration-tests/src/tests/ui/sign-in-experience/sign-up-and-sign-in/connector-setup-helpers.ts
  packages/integration-tests/src/tests/ui/sign-in-experience/sign-up-and-sign-in/happy-path.test.ts
  packages/integration-tests/src/tests/ui/sign-in-experience/sign-up-and-sign-in/helpers.ts
  packages/integration-tests/src/tests/ui/sign-in-experience/sign-up-and-sign-in/sad-path.test.ts
  packages/integration-tests/src/ui-helpers/index.ts
Labels: testing, size/xl

#4377 test: add ui tests for sign-in preview
  packages/integration-tests/src/tests/ui/sign-in-experience/helpers.ts
  packages/integration-tests/src/tests/ui/sign-in-experience/sign-in-preview.test.ts
Labels: testing, size/m

#4367 fix(console): invalid guide url should show 404 not found
  packages/console/src/pages/Applications/components/Guide/index.module.scss
  packages/console/src/pages/Applications/components/Guide/index.tsx
  packages/console/src/pages/NotFound/index.tsx
Labels: bugfix, size/m

#4380 fix(connector): fix saml connector response guard
  packages/connectors/connector-saml/README.md
  packages/connectors/connector-saml/src/constant.ts
  packages/connectors/connector-saml/src/index.ts
  packages/connectors/connector-saml/src/types.ts
Labels: bugfix, size/s

#4381 chore(phrases): update i18n for new added app creation components
  packages/phrases/src/locales/de/translation/admin-console/application-details.ts
  packages/phrases/src/locales/de/translation/admin-console/applications.ts
  packages/phrases/src/locales/de/translation/admin-console/general.ts
  packages/phrases/src/locales/es/translation/admin-console/application-details.ts
  packages/phrases/src/locales/es/translation/admin-console/applications.ts
  packages/phrases/src/locales/es/translation/admin-console/general.ts
  packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/applications.ts
  packages/phrases/src/locales/fr/translation/admin-console/general.ts
  packages/phrases/src/locales/it/translation/admin-console/application-details.ts
  packages/phrases/src/locales/it/translation/admin-console/applications.ts
  packages/phrases/src/locales/it/translation/admin-console/general.ts
  packages/phrases/src/locales/ja/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/applications.ts
  packages/phrases/src/locales/ja/translation/admin-console/general.ts
  packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/applications.ts
  packages/phrases/src/locales/ko/translation/admin-console/general.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/applications.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/applications.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/applications.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
  packages/phrases/src/locales/ru/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/applications.ts
  packages/phrases/src/locales/ru/translation/admin-console/general.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/applications.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/general.ts
Labels: chore, size/xl

#4386 fix(console): fields should have default values in application advanced settings
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/ds-components/TabWrapper/index.module.scss
  packages/console/src/ds-components/TabWrapper/index.tsx
  packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx
  packages/console/src/pages/ApplicationDetails/components/Settings.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/ApplicationDetails/types.ts
  packages/console/src/pages/SignInExperience/tabs/Branding/index.tsx
  packages/console/src/pages/SignInExperience/tabs/Others/index.tsx
  packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/index.tsx
Labels: bugfix, size/s

#4385 refactor(console): align sign-in/out redirect uris
  packages/console/src/components/SessionExpired/index.tsx
  packages/console/src/consts/tenants.ts
  packages/console/src/containers/AppContent/components/Topbar/UserInfo/index.tsx
  packages/console/src/containers/ProtectedRoutes/index.tsx
  packages/console/src/hooks/use-redirect-uri.ts
  packages/console/src/pages/Welcome/index.tsx
Labels: enhancement, size/s

#4389 chore(console): optimize onboarding process
  packages/console/src/onboarding/pages/SignInExperience/index.tsx
  packages/console/src/onboarding/pages/SignInExperience/sie-config-templates.ts
  packages/console/src/onboarding/pages/Welcome/index.tsx
  packages/console/src/onboarding/types.ts
Labels: chore, size/s

#4392 chore: update console code owners
  .github/CODEOWNERS
Labels: chore, size/xs

#4391 fix(console): remove 'unhandledrejection' listener from ErrorBoundary
  packages/console/src/containers/ErrorBoundary/index.tsx
Labels: bugfix, size/s

#4387 fix(console): use correct sign-out redirect uri for api hooks
  packages/console/src/hooks/use-api.ts
  packages/console/src/hooks/use-redirect-uri.ts
Labels: bugfix, size/s

#4390 chore(console): code cleanup
  packages/console/src/ds-components/Search/index.tsx
  packages/console/src/hooks/use-api.ts
  packages/console/src/onboarding/pages/SignInExperience/components/PlatformTabs/PlatformTab.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/Dashboard/components/Block.tsx
  packages/console/src/pages/Profile/components/LinkAccountSection/index.tsx
  packages/console/src/pages/WebhookDetails/WebhookSettings/components/CustomHeaderField/index.tsx
Labels: chore, size/s

#4393 chore: update stale issue workflow
  .github/workflows/close-stale.yml
Labels: chore, size/xs

#4397 refactor(cli): add server connection application to the admin tenant
  packages/cli/src/commands/database/seed/cloud.ts
  packages/cli/src/commands/database/seed/tables.ts
Labels: enhancement, size/s

#4401 refactor(test): improve test codes about save & discard changes
  packages/integration-tests/src/tests/ui/connectors/passwordless-connectors.test.ts
  packages/integration-tests/src/tests/ui/connectors/social-connectors.test.ts
  packages/integration-tests/src/tests/ui/sign-in-experience/helpers.ts
  packages/integration-tests/src/tests/ui/sign-in-experience/sign-up-and-sign-in/sad-path.test.ts
  packages/integration-tests/src/tests/ui/user-management.test.ts
  packages/integration-tests/src/tests/ui/webhooks.test.ts
  packages/integration-tests/src/ui-helpers/index.ts
Labels: enhancement, size/s

#4403 feat(console): add asp.net core tutorial
  .changeset/purple-clouds-jog.md
  packages/console/src/assets/docs/guides/index.ts
  packages/console/src/assets/docs/guides/web-asp-net-core/README.mdx
  packages/console/src/assets/docs/guides/web-asp-net-core/index.ts
  packages/console/src/assets/docs/guides/web-asp-net-core/logo.svg
  packages/console/src/assets/docs/guides/web-csharp/README.mdx
  packages/console/src/assets/docs/guides/web-csharp/logo.svg
  packages/console/src/assets/docs/guides/web-java/README.mdx
Labels: feature, size/m

#4404 refactor(console): support explicit tutorial order
  packages/console/src/assets/docs/guides/README.md
  packages/console/src/assets/docs/guides/generate-metadata.js
  packages/console/src/assets/docs/guides/index.ts
  packages/console/src/assets/docs/guides/native-android-java/config.json
  packages/console/src/assets/docs/guides/native-android-kt/config.json
  packages/console/src/assets/docs/guides/native-capacitor/config.json
  packages/console/src/assets/docs/guides/native-flutter/config.json
  packages/console/src/assets/docs/guides/native-ios-swift/config.json
  packages/console/src/assets/docs/guides/spa-react/config.json
  packages/console/src/assets/docs/guides/spa-vanilla/config.json
  packages/console/src/assets/docs/guides/spa-vue/config.json
  packages/console/src/assets/docs/guides/web-asp-net-core/config.json
  packages/console/src/assets/docs/guides/web-express/config.json
  packages/console/src/assets/docs/guides/web-go/config.json
  packages/console/src/assets/docs/guides/web-gpt-plugin/config.json
  packages/console/src/assets/docs/guides/web-next-app-router/config.json
  packages/console/src/assets/docs/guides/web-next/config.json
  packages/console/src/assets/docs/guides/web-outline/config.json
  packages/console/src/assets/docs/guides/web-php/config.json
  packages/console/src/assets/docs/guides/web-python/config.json
  packages/console/src/assets/docs/guides/web-remix/config.json
Labels: enhancement, size/m

#4402 fix(console): app creation quota limit should be displayed on create app form
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
Labels: bugfix, size/xs

#4379 feat(core): add tenant is suspended guard
  packages/core/package.json
  packages/core/src/middleware/koa-tenant-guard.test.ts
  packages/core/src/middleware/koa-tenant-guard.ts
  packages/core/src/routes/init.ts
  packages/phrases/src/locales/de/errors/subscription.ts
  packages/phrases/src/locales/en/errors/subscription.ts
  packages/phrases/src/locales/es/errors/subscription.ts
  packages/phrases/src/locales/fr/errors/subscription.ts
  packages/phrases/src/locales/it/errors/subscription.ts
  packages/phrases/src/locales/ja/errors/subscription.ts
  packages/phrases/src/locales/ko/errors/subscription.ts
  packages/phrases/src/locales/pl-pl/errors/subscription.ts
  packages/phrases/src/locales/pt-br/errors/subscription.ts
  packages/phrases/src/locales/pt-pt/errors/subscription.ts
  packages/phrases/src/locales/ru/errors/subscription.ts
  packages/phrases/src/locales/tr-tr/errors/subscription.ts
  packages/phrases/src/locales/zh-cn/errors/subscription.ts
  packages/phrases/src/locales/zh-hk/errors/subscription.ts
  packages/phrases/src/locales/zh-tw/errors/subscription.ts
  packages/toolkit/connector-kit/package.json
  pnpm-lock.yaml
Labels: feature, size/m

#4406 fix: remove connector link from session storage
  packages/ui/src/hooks/use-social-callback-handler.ts
  packages/ui/src/utils/social-connectors.ts
Labels: bugfix, size/s

#4398 refactor(console): new get started page
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/ds-components/Button/index.tsx
  packages/console/src/pages/Applications/components/GuideCard/index.module.scss
  packages/console/src/pages/Applications/components/GuideCard/index.tsx
  packages/console/src/pages/GetStarted/components/Skeleton/index.module.scss
  packages/console/src/pages/GetStarted/components/Skeleton/index.tsx
  packages/console/src/pages/GetStarted/hook.ts
  packages/console/src/pages/GetStarted/index.module.scss
  packages/console/src/pages/GetStarted/index.tsx
  packages/console/src/utils/url.ts
  packages/phrases/src/locales/de/translation/admin-console/get-started.ts
  packages/phrases/src/locales/en/translation/admin-console/get-started.ts
  packages/phrases/src/locales/es/translation/admin-console/get-started.ts
  packages/phrases/src/locales/fr/translation/admin-console/get-started.ts
  packages/phrases/src/locales/it/translation/admin-console/get-started.ts
  packages/phrases/src/locales/ja/translation/admin-console/get-started.ts
  packages/phrases/src/locales/ko/translation/admin-console/get-started.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/get-started.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/get-started.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/get-started.ts
  packages/phrases/src/locales/ru/translation/admin-console/get-started.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/get-started.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/get-started.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/get-started.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/get-started.ts
Labels: enhancement, size/xl

#4408 fix(console): remove unexpected margin top from form elements
  packages/console/src/mdx-components-v2/UriInputField/index.module.scss
  packages/console/src/mdx-components-v2/UriInputField/index.tsx
Labels: bugfix, size/xs

#4412 refactor(test): add modal ui test helpers
  packages/integration-tests/src/tests/ui/connectors/helpers.ts
  packages/integration-tests/src/tests/ui/connectors/social-connectors.test.ts
  packages/integration-tests/src/tests/ui/rbac.test.ts
  packages/integration-tests/src/tests/ui/user-management.test.ts
  packages/integration-tests/src/tests/ui/webhooks.test.ts
  packages/integration-tests/src/ui-helpers/index.ts
Labels: enhancement, size/l

#4407 test: add ui tests for applications
  packages/integration-tests/src/tests/ui/applications/constants.ts
  packages/integration-tests/src/tests/ui/applications/helpers.ts
  packages/integration-tests/src/tests/ui/applications/index.test.ts
  packages/integration-tests/src/ui-helpers/index.ts
Labels: testing, size/l
