Repository logto-io/logto, pull requests merged in 2023-10, with the labels that each got.

#4617 chore(schemas): format alteration script
  packages/schemas/alterations/1.9.2-1695198741-remove-m2m-app-admin-access-switch.ts
Labels: chore, size/s

#4618 chore: add M2M RBAC changeset for @logto/core and update changelog
  .changeset/early-squids-cheat.md
  packages/console/CHANGELOG.md
Labels: chore, size/s

#4600 refactor(core): support `roles` scope for ID token
  .changeset/sweet-cows-burn.md
  packages/core/src/oidc/init.ts
  packages/core/src/oidc/scope.ts
  packages/integration-tests/src/tests/api/oidc/id-token.test.ts
  packages/toolkit/core-kit/src/scope.ts
Labels: enhancement, size/s

#4589 feat(experience): implement totp experience flow
  packages/experience/package.json
  packages/experience/src/App.tsx
  packages/experience/src/Layout/SectionLayout/index.module.scss
  packages/experience/src/Layout/SectionLayout/index.tsx
  packages/experience/src/apis/interaction.ts
  packages/experience/src/assets/icons/factor-backup-code.svg
  packages/experience/src/assets/icons/factor-totp.svg
  packages/experience/src/assets/icons/factor-webauthn.svg
  packages/experience/src/components/Button/MfaFactorButton.module.scss
  packages/experience/src/components/Button/MfaFactorButton.tsx
  packages/experience/src/components/Divider/index.tsx
  packages/experience/src/constants/env.ts
  packages/experience/src/containers/MfaFactorList/index.module.scss
  packages/experience/src/containers/MfaFactorList/index.tsx
  packages/experience/src/containers/TotpCodeVerification/index.module.scss
  packages/experience/src/containers/TotpCodeVerification/index.tsx
  packages/experience/src/containers/TotpCodeVerification/use-totp-code-verification.ts
  packages/experience/src/containers/VerificationCode/use-continue-flow-code-verification.ts
  packages/experience/src/containers/VerificationCode/use-register-flow-code-verification.ts
  packages/experience/src/containers/VerificationCode/use-sign-in-flow-code-verification.ts
  packages/experience/src/hooks/use-mfa-verification-error-handler.ts
  packages/experience/src/hooks/use-password-sign-in.ts
  packages/experience/src/hooks/use-pre-sign-in-error-handler.ts
  packages/experience/src/hooks/use-required-profile-error-handler.ts
  packages/experience/src/hooks/use-social-link-related-user.ts
  packages/experience/src/hooks/use-social-register.ts
  packages/experience/src/hooks/use-social-sign-in-listener.ts
  packages/experience/src/hooks/use-start-binding-totp.ts
  packages/experience/src/hooks/use-text-handler.ts
  packages/experience/src/pages/Continue/SetPassword/index.tsx
  packages/experience/src/pages/Continue/SetUsername/use-set-username.ts
  packages/experience/src/pages/MfaBinding/TotpBinding/SecretSection/index.module.scss
  packages/experience/src/pages/MfaBinding/TotpBinding/SecretSection/index.tsx
  packages/experience/src/pages/MfaBinding/TotpBinding/VerificationSection.tsx
  packages/experience/src/pages/MfaBinding/TotpBinding/index.module.scss
  packages/experience/src/pages/MfaBinding/TotpBinding/index.tsx
  packages/experience/src/pages/MfaBinding/index.tsx
  packages/experience/src/pages/MfaVerification/TotpVerification/index.module.scss
  packages/experience/src/pages/MfaVerification/TotpVerification/index.tsx
  packages/experience/src/pages/MfaVerification/index.tsx
  packages/experience/src/pages/RegisterPassword/index.tsx
  packages/experience/src/types/guard.ts
  packages/experience/src/types/index.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#4582 refactor(schemas,core,cli): alter signing key type to json object
  .changeset/lucky-brooms-hide.md
  packages/cli/src/commands/database/seed/oidc-config.ts
  packages/cli/src/commands/database/utils.ts
  packages/core/src/env-set/oidc.ts
  packages/core/src/middleware/koa-auth/utils.ts
  packages/schemas/alterations/next-1695647183-update-private-key-type.ts
  packages/schemas/src/types/logto-config.ts
Labels: enhancement, size/m

#4623 fix(core): fix new linked social email conflict error
  packages/core/src/routes/interaction/actions/helpers.ts
  packages/core/src/routes/interaction/actions/submit-interaction.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
Labels: bugfix, size/l

#4619 test(experience): add tests for totp experience flow
  packages/integration-tests/src/constants.ts
  packages/integration-tests/src/helpers/sign-in-experience.ts
  packages/integration-tests/src/tests/experience/mfa/totp/add-missing-profile-flow.test.ts
  packages/integration-tests/src/tests/experience/mfa/totp/passcode-identifier-flow.test.ts
  packages/integration-tests/src/tests/experience/mfa/totp/password-identifier-flow.test.ts
  packages/integration-tests/src/tests/experience/mfa/totp/social-flow.test.ts
  packages/integration-tests/src/tests/experience/mfa/totp/totp-testing-context.ts
  packages/integration-tests/src/ui-helpers/expect-experience.ts
  packages/integration-tests/src/ui-helpers/expect-totp-experience.ts
Labels: testing, size/xl

#4609 feat: guard text inputs for CustomHeaderField component
  packages/console/src/pages/WebhookDetails/WebhookSettings/CustomHeaderField/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/en/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/es/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/it/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/webhook-details.ts
Labels: feature, size/s, hacktoberfest-accepted

#4590 refactor(core): support oidc configuration hot replace
  packages/core/src/oidc/init.ts
Labels: enhancement, size/s

#4622 refactor: eliminate connector-kit dependency on logto/cloud
  packages/cli/package.json
  packages/cli/src/connector/factories.ts
  packages/cli/src/connector/types.ts
  packages/cli/src/connector/utils.ts
  packages/connectors/connector-logto-email/package.json
  packages/connectors/connector-logto-email/src/index.ts
  packages/core/src/__mocks__/connector.ts
  packages/core/src/routes/connector/config-testing.test.ts
  packages/core/src/routes/connector/config-testing.ts
  packages/core/src/routes/connector/index.ts
  packages/core/src/utils/connectors/index.ts
  packages/toolkit/connector-kit/package.json
  packages/toolkit/connector-kit/src/types.ts
  pnpm-lock.yaml
Labels: enhancement, chore, size/m

#4628 refactor(experience): reorg mfa factor switching logic
  packages/experience/src/components/SwitchMfaFactorsLink/index.tsx
  packages/experience/src/containers/MfaFactorList/index.tsx
  packages/experience/src/hooks/use-mfa-verification-error-handler.ts
  packages/experience/src/hooks/use-start-totp-binding.ts
  packages/experience/src/pages/MfaBinding/TotpBinding/index.module.scss
  packages/experience/src/pages/MfaBinding/TotpBinding/index.tsx
  packages/experience/src/pages/MfaBinding/index.tsx
  packages/experience/src/pages/MfaVerification/TotpVerification/index.tsx
  packages/experience/src/pages/MfaVerification/index.tsx
  packages/experience/src/types/guard.ts
Labels: enhancement, size/m

#4616 feat(schemas): init organization tables
  packages/schemas/alterations/next-1696657546-organization-tables.ts
  packages/schemas/src/foundations/schemas.ts
  packages/schemas/src/gen/index.ts
  packages/schemas/src/gen/schema.ts
  packages/schemas/src/gen/types.ts
  packages/schemas/src/gen/utils.ts
  packages/schemas/tables/organization_role_scope_relations.sql
  packages/schemas/tables/organization_role_user_relations.sql
  packages/schemas/tables/organization_roles.sql
  packages/schemas/tables/organization_scopes.sql
  packages/schemas/tables/organization_user_relations.sql
  packages/schemas/tables/organizations.sql
Labels: feature, size/l

#4594 feat(core,phrases): add apis to fetch, delete and rotate oidc private keys
  packages/cli/src/commands/database/config.ts
  packages/cli/src/commands/database/utils.ts
  packages/core/src/__mocks__/index.ts
  packages/core/src/queries/logto-config.test.ts
  packages/core/src/queries/logto-config.ts
  packages/core/src/routes/logto-config.test.ts
  packages/core/src/routes/logto-config.ts
  packages/core/src/test-utils/tenant.ts
  packages/core/src/utils/jwks.ts
  packages/integration-tests/src/api/logto-config.ts
  packages/integration-tests/src/tests/api/logto-config.test.ts
  packages/phrases/src/locales/de/errors/oidc.ts
  packages/phrases/src/locales/en/errors/oidc.ts
  packages/phrases/src/locales/es/errors/oidc.ts
  packages/phrases/src/locales/fr/errors/oidc.ts
  packages/phrases/src/locales/it/errors/oidc.ts
  packages/phrases/src/locales/ja/errors/oidc.ts
  packages/phrases/src/locales/ko/errors/oidc.ts
  packages/phrases/src/locales/pl-pl/errors/oidc.ts
  packages/phrases/src/locales/pt-br/errors/oidc.ts
  packages/phrases/src/locales/pt-pt/errors/oidc.ts
  packages/phrases/src/locales/ru/errors/oidc.ts
  packages/phrases/src/locales/tr-tr/errors/oidc.ts
  packages/phrases/src/locales/zh-cn/errors/oidc.ts
  packages/phrases/src/locales/zh-hk/errors/oidc.ts
  packages/phrases/src/locales/zh-tw/errors/oidc.ts
  packages/schemas/src/types/logto-config.ts
  packages/schemas/tables/logto_configs.sql
Labels: feature, size/xl

#4631 feat(phrases): add i18n phrases for private key rotation feature
  packages/phrases/src/locales/de/translation/admin-console/tenants.ts
  packages/phrases/src/locales/en/translation/admin-console/tenants.ts
  packages/phrases/src/locales/es/translation/admin-console/tenants.ts
  packages/phrases/src/locales/fr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/it/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ja/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ko/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ru/translation/admin-console/tenants.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tenants.ts
Labels: feature, size/xl

#4632 feat(console): add console UI for private keys rotation
  packages/console/src/ds-components/Dropdown/index.module.scss
  packages/console/src/ds-components/Dropdown/index.tsx
  packages/console/src/ds-components/Select/index.tsx
  packages/console/src/ds-components/Table/index.module.scss
  packages/console/src/ds-components/Table/index.tsx
  packages/console/src/ds-components/Table/types.ts
  packages/console/src/pages/TenantSettings/TenantBasicSettings/SigningKeys/index.module.scss
  packages/console/src/pages/TenantSettings/TenantBasicSettings/SigningKeys/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/index.tsx
  packages/toolkit/core-kit/scss/_console-themes.scss
Labels: feature, size/l

#4620 feat(core): org basic apis
  packages/core/src/database/delete-by-id.ts
  packages/core/src/database/row-count.ts
  packages/core/src/middleware/koa-guard.ts
  packages/core/src/middleware/koa-pagination.ts
  packages/core/src/queries/organizations.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/organizations.ts
  packages/core/src/routes/types.ts
  packages/core/src/tenants/Queries.ts
  packages/core/src/utils/SchemaRouter.test.ts
  packages/core/src/utils/SchemaRouter.ts
  packages/core/src/utils/TenantQueries.ts
  packages/integration-tests/src/api/organization.ts
  packages/integration-tests/src/tests/api/organization.test.ts
Labels: feature, size/xl

#4648 chore(console): bump react-markdown
  package.json
  packages/console/package.json
  packages/console/src/components/Markdown/index.tsx
  pnpm-lock.yaml
Labels: chore, size/s

#4644 refactor(schemas): split the jsonb-type file
  packages/schemas/src/consts/oidc.ts
  packages/schemas/src/foundations/index.ts
  packages/schemas/src/foundations/jsonb-types.ts
  packages/schemas/src/foundations/jsonb-types/custom-domain.ts
  packages/schemas/src/foundations/jsonb-types/hooks.ts
  packages/schemas/src/foundations/jsonb-types/index.ts
  packages/schemas/src/foundations/jsonb-types/logs.ts
  packages/schemas/src/foundations/jsonb-types/oidc-module.ts
  packages/schemas/src/foundations/jsonb-types/phrases.ts
  packages/schemas/src/foundations/jsonb-types/sentinel.ts
  packages/schemas/src/foundations/jsonb-types/sign-in-experience.ts
  packages/schemas/src/foundations/jsonb-types/users.ts
  packages/schemas/src/types/log/interaction.ts
  packages/schemas/src/types/user.ts
Labels: enhancement, size/xl

#4646 refactor(core,experience): generate totp qrcode on server side
  packages/core/package.json
  packages/core/src/routes/interaction/additional.test.ts
  packages/core/src/routes/interaction/additional.ts
  packages/experience/package.json
  packages/experience/src/apis/interaction.ts
  packages/experience/src/hooks/use-start-totp-binding.ts
  pnpm-lock.yaml
Labels: enhancement, size/s

#4647 feat(console): add tenant deletion guard
  packages/console/src/hooks/use-subscribe.ts
  packages/console/src/pages/TenantSettings/TenantBasicSettings/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/tenants.ts
  packages/phrases/src/locales/en/translation/admin-console/tenants.ts
  packages/phrases/src/locales/es/translation/admin-console/tenants.ts
  packages/phrases/src/locales/fr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/it/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ja/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ko/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ru/translation/admin-console/tenants.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tenants.ts
Labels: feature, size/m

#4649 chore: update experience tests since it will fail randomly when running ci
  packages/integration-tests/src/ui-helpers/expect-experience.ts
  packages/integration-tests/src/ui-helpers/expect-totp-experience.ts
Labels: chore, size/xs

#4640 feat(core): add organization scope APIs
  packages/core/src/queries/organization-scopes.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/organization-scopes.test.ts
  packages/core/src/routes/organization-scopes.ts
  packages/core/src/tenants/Queries.ts
  packages/integration-tests/src/api/organization-scope.ts
  packages/integration-tests/src/tests/api/organization-scope.test.ts
  packages/phrases/src/locales/de/errors/entity.ts
  packages/phrases/src/locales/en/errors/entity.ts
  packages/phrases/src/locales/es/errors/entity.ts
  packages/phrases/src/locales/fr/errors/entity.ts
  packages/phrases/src/locales/it/errors/entity.ts
  packages/phrases/src/locales/ja/errors/entity.ts
  packages/phrases/src/locales/ko/errors/entity.ts
  packages/phrases/src/locales/pl-pl/errors/entity.ts
  packages/phrases/src/locales/pt-br/errors/entity.ts
  packages/phrases/src/locales/pt-pt/errors/entity.ts
  packages/phrases/src/locales/ru/errors/entity.ts
  packages/phrases/src/locales/tr-tr/errors/entity.ts
  packages/phrases/src/locales/zh-cn/errors/entity.ts
  packages/phrases/src/locales/zh-hk/errors/entity.ts
  packages/phrases/src/locales/zh-tw/errors/entity.ts
Labels: feature, size/l

#4645 refactor(test): add ApiFactory for integration tests
  packages/integration-tests/src/api/factory.ts
  packages/integration-tests/src/api/organization-scope.ts
  packages/integration-tests/src/api/organization.ts
  packages/integration-tests/src/tests/api/organization-scope.test.ts
  packages/integration-tests/src/tests/api/organization.test.ts
Labels: enhancement, size/m

#4641 fix(core): dispose tenant cache on demand in order to hot reload oidc provider
  packages/core/src/caches/well-known.test.ts
  packages/core/src/caches/well-known.ts
  packages/core/src/routes/logto-config.ts
  packages/core/src/tenants/Tenant.test.ts
  packages/core/src/tenants/Tenant.ts
  packages/core/src/tenants/TenantContext.ts
  packages/core/src/tenants/index.ts
  packages/core/src/test-utils/tenant.ts
  packages/integration-tests/src/tests/api/logto-config.test.ts
Labels: bugfix, size/m

#4654 refactor(console): select dropdown should always pop downwards
  packages/console/src/ds-components/Dropdown/index.tsx
  packages/console/src/ds-components/Select/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/SigningKeys/index.tsx
Labels: enhancement, size/s

#4652 chore(phrases): update wording for rotate oidc signing keys
  packages/console/src/pages/TenantSettings/TenantBasicSettings/SigningKeys/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/tenants.ts
  packages/phrases/src/locales/en/translation/admin-console/tenants.ts
  packages/phrases/src/locales/es/translation/admin-console/tenants.ts
  packages/phrases/src/locales/fr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/it/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ja/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ko/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ru/translation/admin-console/tenants.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tenants.ts
Labels: chore, size/l

#4653 style(console): update compact table styles per latest design
  packages/console/src/ds-components/Table/index.module.scss
  packages/console/src/pages/TenantSettings/TenantBasicSettings/SigningKeys/index.module.scss
Labels: size/s

#4626 feat(core,schemas): bind webauthn
  packages/core/package.json
  packages/core/src/__mocks__/mfa-verification.ts
  packages/core/src/__mocks__/webauthn.ts
  packages/core/src/routes/interaction/actions/submit-interaction.mfa.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/core/src/routes/interaction/additional.test.ts
  packages/core/src/routes/interaction/additional.ts
  packages/core/src/routes/interaction/mfa.ts
  packages/core/src/routes/interaction/types/guard.ts
  packages/core/src/routes/interaction/types/index.ts
  packages/core/src/routes/interaction/utils/interaction.ts
  packages/core/src/routes/interaction/utils/webauthn.ts
  packages/core/src/routes/interaction/verifications/mfa-payload-verification.test.ts
  packages/core/src/routes/interaction/verifications/mfa-payload-verification.ts
  packages/core/src/routes/interaction/verifications/mfa-verification.ts
  packages/phrases/src/locales/de/errors/session.ts
  packages/phrases/src/locales/en/errors/session.ts
  packages/phrases/src/locales/es/errors/session.ts
  packages/phrases/src/locales/fr/errors/session.ts
  packages/phrases/src/locales/it/errors/session.ts
  packages/phrases/src/locales/ja/errors/session.ts
  packages/phrases/src/locales/ko/errors/session.ts
  packages/phrases/src/locales/pl-pl/errors/session.ts
  packages/phrases/src/locales/pt-br/errors/session.ts
  packages/phrases/src/locales/pt-pt/errors/session.ts
  packages/phrases/src/locales/ru/errors/session.ts
  packages/phrases/src/locales/tr-tr/errors/session.ts
  packages/phrases/src/locales/zh-cn/errors/session.ts
  packages/phrases/src/locales/zh-hk/errors/session.ts
  packages/phrases/src/locales/zh-tw/errors/session.ts
  packages/schemas/src/foundations/jsonb-types/users.ts
  packages/schemas/src/types/index.ts
  packages/schemas/src/types/interactions.ts
  packages/schemas/src/types/mfa.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#4651 feat(core): organization role APIs
  packages/core/package.json
  packages/core/src/queries/organization-roles.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/organization-roles.ts
  packages/core/src/tenants/Queries.ts
  packages/core/src/utils/RelationQueries.ts
  packages/core/src/utils/SchemaRouter.ts
  packages/integration-tests/src/api/organization-role.ts
  packages/integration-tests/src/tests/api/organization-role.test.ts
  packages/schemas/src/foundations/schemas.ts
  packages/schemas/src/gen/schema.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#4655 refactor(core): refactor organization queries
  packages/core/src/queries/organization-roles.ts
  packages/core/src/queries/organization-scopes.ts
  packages/core/src/queries/organizations.ts
  packages/core/src/routes/organization-roles.ts
  packages/core/src/routes/organization-scopes.test.ts
  packages/core/src/routes/organization-scopes.ts
  packages/core/src/tenants/Queries.ts
Labels: enhancement, size/m

#4657 feat(core): role - scope relation apis
  packages/core/src/queries/organizations.ts
  packages/core/src/routes/organization-roles.ts
  packages/core/src/utils/RelationQueries.ts
  packages/core/src/utils/SchemaRouter.ts
  packages/integration-tests/src/api/organization-role.ts
  packages/integration-tests/src/tests/api/organization-role.test.ts
Labels: feature, size/l

#4658 refactor(core): `addRelationRoutes()` for `SchemaRouter`
  packages/core/package.json
  packages/core/src/queries/organizations.ts
  packages/core/src/routes/organization-roles.ts
  packages/core/src/utils/SchemaRouter.ts
  packages/integration-tests/src/api/organization-role.ts
  packages/integration-tests/src/tests/api/organization-role.test.ts
  pnpm-lock.yaml
Labels: enhancement, size/m

#4662 feat(core): organization - organization role - user apis
  packages/core/src/queries/organizations.ts
  packages/core/src/routes/organizations.ts
  packages/core/src/utils/RelationQueries.ts
  packages/core/src/utils/SchemaRouter.ts
  packages/integration-tests/src/api/organization.ts
  packages/integration-tests/src/tests/api/organization.test.ts
  packages/phrases/src/locales/de/errors/index.ts
  packages/phrases/src/locales/de/errors/organization.ts
  packages/phrases/src/locales/en/errors/index.ts
  packages/phrases/src/locales/en/errors/organization.ts
  packages/phrases/src/locales/es/errors/index.ts
  packages/phrases/src/locales/es/errors/organization.ts
  packages/phrases/src/locales/fr/errors/index.ts
  packages/phrases/src/locales/fr/errors/organization.ts
  packages/phrases/src/locales/it/errors/index.ts
  packages/phrases/src/locales/it/errors/organization.ts
  packages/phrases/src/locales/ja/errors/index.ts
  packages/phrases/src/locales/ja/errors/organization.ts
  packages/phrases/src/locales/ko/errors/index.ts
  packages/phrases/src/locales/ko/errors/organization.ts
  packages/phrases/src/locales/pl-pl/errors/index.ts
  packages/phrases/src/locales/pl-pl/errors/organization.ts
  packages/phrases/src/locales/pt-br/errors/index.ts
  packages/phrases/src/locales/pt-br/errors/organization.ts
  packages/phrases/src/locales/pt-pt/errors/index.ts
  packages/phrases/src/locales/pt-pt/errors/organization.ts
  packages/phrases/src/locales/ru/errors/index.ts
  packages/phrases/src/locales/ru/errors/organization.ts
  packages/phrases/src/locales/tr-tr/errors/index.ts
  packages/phrases/src/locales/tr-tr/errors/organization.ts
  packages/phrases/src/locales/zh-cn/errors/index.ts
  packages/phrases/src/locales/zh-cn/errors/organization.ts
  packages/phrases/src/locales/zh-hk/errors/index.ts
  packages/phrases/src/locales/zh-hk/errors/organization.ts
  packages/phrases/src/locales/zh-tw/errors/index.ts
  packages/phrases/src/locales/zh-tw/errors/organization.ts
Labels: feature, size/l

#4663 refactor(core): reorg routes
  packages/core/src/database/row-count.ts
  packages/core/src/routes/admin-user/basics.test.ts
  packages/core/src/routes/admin-user/basics.ts
  packages/core/src/routes/admin-user/index.ts
  packages/core/src/routes/admin-user/role.test.ts
  packages/core/src/routes/admin-user/role.ts
  packages/core/src/routes/admin-user/search.test.ts
  packages/core/src/routes/admin-user/search.ts
  packages/core/src/routes/admin-user/social.test.ts
  packages/core/src/routes/admin-user/social.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/organization/index.ts
  packages/core/src/routes/organization/roles.ts
  packages/core/src/routes/organization/scopes.test.ts
  packages/core/src/routes/organization/scopes.ts
  packages/core/src/utils/RelationQueries.ts
  packages/core/src/utils/SchemaRouter.ts
  packages/integration-tests/src/api/organization-role.ts
  packages/integration-tests/src/tests/api/organization-role.test.ts
Labels: enhancement, size/m

#4659 feat(core): organization - user relation apis
  packages/core/src/database/row-count.ts
  packages/core/src/queries/organizations.ts
  packages/core/src/routes/admin-user/basics.test.ts
  packages/core/src/routes/admin-user/basics.ts
  packages/core/src/routes/admin-user/index.ts
  packages/core/src/routes/admin-user/role.test.ts
  packages/core/src/routes/admin-user/role.ts
  packages/core/src/routes/admin-user/search.test.ts
  packages/core/src/routes/admin-user/search.ts
  packages/core/src/routes/admin-user/social.test.ts
  packages/core/src/routes/admin-user/social.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/organization/index.ts
  packages/core/src/routes/organization/roles.ts
  packages/core/src/routes/organization/scopes.test.ts
  packages/core/src/routes/organization/scopes.ts
  packages/core/src/routes/organizations.ts
  packages/core/src/utils/RelationQueries.ts
  packages/core/src/utils/SchemaRouter.ts
  packages/integration-tests/src/api/organization-role.ts
  packages/integration-tests/src/api/organization.ts
  packages/integration-tests/src/tests/api/organization-role.test.ts
  packages/integration-tests/src/tests/api/organization.test.ts
  packages/phrases/src/locales/de/errors/index.ts
  packages/phrases/src/locales/de/errors/organization.ts
  packages/phrases/src/locales/en/errors/index.ts
  packages/phrases/src/locales/en/errors/organization.ts
  packages/phrases/src/locales/es/errors/index.ts
  packages/phrases/src/locales/es/errors/organization.ts
  packages/phrases/src/locales/fr/errors/index.ts
  packages/phrases/src/locales/fr/errors/organization.ts
  packages/phrases/src/locales/it/errors/index.ts
  packages/phrases/src/locales/it/errors/organization.ts
  packages/phrases/src/locales/ja/errors/index.ts
  packages/phrases/src/locales/ja/errors/organization.ts
  packages/phrases/src/locales/ko/errors/index.ts
  packages/phrases/src/locales/ko/errors/organization.ts
  packages/phrases/src/locales/pl-pl/errors/index.ts
  packages/phrases/src/locales/pl-pl/errors/organization.ts
  packages/phrases/src/locales/pt-br/errors/index.ts
  packages/phrases/src/locales/pt-br/errors/organization.ts
  packages/phrases/src/locales/pt-pt/errors/index.ts
  packages/phrases/src/locales/pt-pt/errors/organization.ts
  packages/phrases/src/locales/ru/errors/index.ts
  packages/phrases/src/locales/ru/errors/organization.ts
  packages/phrases/src/locales/tr-tr/errors/index.ts
  packages/phrases/src/locales/tr-tr/errors/organization.ts
  packages/phrases/src/locales/zh-cn/errors/index.ts
  packages/phrases/src/locales/zh-cn/errors/organization.ts
  packages/phrases/src/locales/zh-hk/errors/index.ts
  packages/phrases/src/locales/zh-hk/errors/organization.ts
  packages/phrases/src/locales/zh-tw/errors/index.ts
  packages/phrases/src/locales/zh-tw/errors/organization.ts
Labels: feature, size/xl

#4635 feat(core,schemas): verify webauthn
  packages/core/src/__mocks__/user.ts
  packages/core/src/__mocks__/webauthn.ts
  packages/core/src/routes/interaction/additional.test.ts
  packages/core/src/routes/interaction/additional.ts
  packages/core/src/routes/interaction/mfa.ts
  packages/core/src/routes/interaction/utils/webauthn.test.ts
  packages/core/src/routes/interaction/utils/webauthn.ts
  packages/core/src/routes/interaction/verifications/mfa-payload-verification.test.ts
  packages/core/src/routes/interaction/verifications/mfa-payload-verification.ts
  packages/phrases/src/locales/de/errors/session.ts
  packages/phrases/src/locales/en/errors/session.ts
  packages/phrases/src/locales/es/errors/session.ts
  packages/phrases/src/locales/fr/errors/session.ts
  packages/phrases/src/locales/it/errors/session.ts
  packages/phrases/src/locales/ja/errors/session.ts
  packages/phrases/src/locales/ko/errors/session.ts
  packages/phrases/src/locales/pl-pl/errors/session.ts
  packages/phrases/src/locales/pt-br/errors/session.ts
  packages/phrases/src/locales/pt-pt/errors/session.ts
  packages/phrases/src/locales/ru/errors/session.ts
  packages/phrases/src/locales/tr-tr/errors/session.ts
  packages/phrases/src/locales/zh-cn/errors/session.ts
  packages/phrases/src/locales/zh-hk/errors/session.ts
  packages/phrases/src/locales/zh-tw/errors/session.ts
  packages/schemas/src/types/interactions.ts
  packages/schemas/src/types/mfa.ts
Labels: feature, size/xl

#4667 style(console): update disable style of switch component
  packages/console/src/ds-components/Switch/index.module.scss
  packages/toolkit/core-kit/scss/_console-themes.scss
Labels: size/xs

#4669 chore(console): update mfa phrases
  packages/console/src/pages/Mfa/MfaForm/PolicyOptionTitle/index.module.scss
  packages/console/src/pages/Mfa/MfaForm/PolicyOptionTitle/index.tsx
  packages/console/src/pages/Mfa/MfaForm/constants.ts
  packages/console/src/pages/Mfa/MfaForm/index.module.scss
  packages/console/src/pages/Mfa/MfaForm/index.tsx
  packages/integration-tests/src/tests/console/mfa/helpers.ts
  packages/phrases/src/locales/de/translation/admin-console/mfa.ts
  packages/phrases/src/locales/en/translation/admin-console/mfa.ts
  packages/phrases/src/locales/es/translation/admin-console/mfa.ts
  packages/phrases/src/locales/fr/translation/admin-console/mfa.ts
  packages/phrases/src/locales/it/translation/admin-console/mfa.ts
  packages/phrases/src/locales/ja/translation/admin-console/mfa.ts
  packages/phrases/src/locales/ko/translation/admin-console/mfa.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/mfa.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/mfa.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/mfa.ts
  packages/phrases/src/locales/ru/translation/admin-console/mfa.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/mfa.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/mfa.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/mfa.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/mfa.ts
Labels: chore, size/m

#4671 refactor(test): reset mfa settings after testing
  packages/integration-tests/src/helpers/sign-in-experience.ts
  packages/integration-tests/src/tests/experience/mfa/totp/add-missing-profile-flow.test.ts
  packages/integration-tests/src/tests/experience/mfa/totp/passcode-identifier-flow.test.ts
  packages/integration-tests/src/tests/experience/mfa/totp/password-identifier-flow.test.ts
  packages/integration-tests/src/tests/experience/mfa/totp/social-flow.test.ts
Labels: enhancement, size/s

#4673 refactor(console): remove bottom padding from compact tables
  packages/console/src/ds-components/Table/index.module.scss
  packages/console/src/pages/TenantSettings/TenantBasicSettings/SigningKeys/index.tsx
Labels: enhancement, size/xs

#4670 refactor(schemas,core,console): unify the usage of OIDC "keyType" in both frontend and backend
  packages/console/src/pages/TenantSettings/TenantBasicSettings/SigningKeys/index.tsx
  packages/core/src/routes/logto-config.ts
  packages/integration-tests/src/api/logto-config.ts
  packages/integration-tests/src/tests/api/logto-config.test.ts
  packages/schemas/src/types/logto-config.ts
Labels: enhancement, size/s

#4664 chore: update README.md
  README.md
Labels: chore, size/s

#4672 feat(phrases,console): add toast messages on signing key rotated or deleted
  packages/console/src/pages/TenantSettings/TenantBasicSettings/SigningKeys/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/tenants.ts
  packages/phrases/src/locales/en/translation/admin-console/tenants.ts
  packages/phrases/src/locales/es/translation/admin-console/tenants.ts
  packages/phrases/src/locales/fr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/it/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ja/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ko/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ru/translation/admin-console/tenants.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tenants.ts
Labels: feature, size/s

#4639 fix(core): validate mandatory mfa
  packages/core/src/routes/interaction/verifications/mfa-verification.test.ts
  packages/core/src/routes/interaction/verifications/mfa-verification.ts
  packages/experience/src/hooks/use-mfa-verification-error-handler.ts
  packages/experience/src/types/guard.ts
Labels: bugfix, size/s

#4643 test(experience): add tests for webauthn experience flow
  packages/integration-tests/src/helpers/sign-in-experience.ts
  packages/integration-tests/src/tests/experience/mfa/webauthn/index.test.ts
  packages/integration-tests/src/ui-helpers/expect-experience.ts
  packages/integration-tests/src/ui-helpers/expect-totp-experience.ts
  packages/integration-tests/src/ui-helpers/expect-webauthn-experience.ts
Labels: testing, size/m

#4679 chore(phrases): add missing backup code phrases
  packages/phrases-experience/src/locales/de/mfa.ts
  packages/phrases-experience/src/locales/en/mfa.ts
  packages/phrases-experience/src/locales/es/mfa.ts
  packages/phrases-experience/src/locales/fr/mfa.ts
  packages/phrases-experience/src/locales/it/mfa.ts
  packages/phrases-experience/src/locales/ja/mfa.ts
  packages/phrases-experience/src/locales/ko/mfa.ts
  packages/phrases-experience/src/locales/pl-pl/mfa.ts
  packages/phrases-experience/src/locales/pt-br/mfa.ts
  packages/phrases-experience/src/locales/pt-pt/mfa.ts
  packages/phrases-experience/src/locales/ru/mfa.ts
  packages/phrases-experience/src/locales/tr-tr/mfa.ts
  packages/phrases-experience/src/locales/zh-cn/mfa.ts
  packages/phrases-experience/src/locales/zh-hk/mfa.ts
  packages/phrases-experience/src/locales/zh-tw/mfa.ts
Labels: chore, size/s

#4665 feat(core): get organizations for user api
  packages/core/src/queries/organizations.ts
  packages/core/src/routes/admin-user/index.ts
  packages/core/src/routes/admin-user/organization.ts
  packages/core/src/utils/SchemaRouter.ts
  packages/integration-tests/src/api/organization.ts
  packages/integration-tests/src/tests/api/organization.test.ts
Labels: feature, size/m

#4666 refactor(core): organization apis error handling
  packages/core/src/routes/organization/index.ts
  packages/core/src/routes/organization/roles.ts
  packages/core/src/routes/organization/scopes.test.ts
  packages/core/src/routes/organization/scopes.ts
  packages/core/src/routes/organization/utils.ts
  packages/core/src/utils/RelationQueries.ts
  packages/core/src/utils/SchemaRouter.ts
  packages/integration-tests/src/tests/api/organization-role.test.ts
  packages/integration-tests/src/tests/api/organization.test.ts
  packages/phrases/src/locales/de/errors/entity.ts
  packages/phrases/src/locales/en/errors/entity.ts
  packages/phrases/src/locales/es/errors/entity.ts
  packages/phrases/src/locales/fr/errors/entity.ts
  packages/phrases/src/locales/it/errors/entity.ts
  packages/phrases/src/locales/ja/errors/entity.ts
  packages/phrases/src/locales/ko/errors/entity.ts
  packages/phrases/src/locales/pl-pl/errors/entity.ts
  packages/phrases/src/locales/pt-br/errors/entity.ts
  packages/phrases/src/locales/pt-pt/errors/entity.ts
  packages/phrases/src/locales/ru/errors/entity.ts
  packages/phrases/src/locales/tr-tr/errors/entity.ts
  packages/phrases/src/locales/zh-cn/errors/entity.ts
  packages/phrases/src/locales/zh-hk/errors/entity.ts
  packages/phrases/src/locales/zh-tw/errors/entity.ts
Labels: enhancement, size/l

#4681 refactor(core): refactor post connector endpoint
  packages/cli/src/connector/factories.ts
  packages/cli/src/connector/types.ts
  packages/core/src/__mocks__/connector.ts
  packages/core/src/libraries/connector.ts
  packages/core/src/routes/connector/index.post.test.ts
  packages/core/src/routes/connector/index.ts
Labels: enhancement, size/m

#4668 refactor(core): remove `SchemaActions` class
  packages/core/src/middleware/koa-pagination.ts
  packages/core/src/routes/organization/index.ts
  packages/core/src/routes/organization/roles.ts
  packages/core/src/routes/organization/scopes.ts
  packages/core/src/utils/SchemaQueries.ts
  packages/core/src/utils/SchemaRouter.test.ts
  packages/core/src/utils/SchemaRouter.ts
Labels: enhancement, size/m

#4684 refactor(core): add time window validation tolerance for otp authenticator
  packages/core/src/routes/interaction/utils/totp-validation.ts
  packages/integration-tests/src/ui-helpers/expect-totp-experience.ts
Labels: enhancement, feature, bugfix, size/s

#4678 refactor(toolkit)!: split connector toolkit types
  .changeset/tough-kiwis-confess.md
  packages/toolkit/connector-kit/src/index.ts
  packages/toolkit/connector-kit/src/types.ts
  packages/toolkit/connector-kit/src/types/config-form.ts
  packages/toolkit/connector-kit/src/types/error.ts
  packages/toolkit/connector-kit/src/types/foundation.ts
  packages/toolkit/connector-kit/src/types/index.ts
  packages/toolkit/connector-kit/src/types/metadata.ts
  packages/toolkit/connector-kit/src/types/passwordless.ts
  packages/toolkit/connector-kit/src/types/social.ts
Labels: enhancement, size/xl

#4688 refactor(test): refactor connector ui tests
  packages/integration-tests/src/tests/console/connectors/passwordless-connector-test-cases.ts
  packages/integration-tests/src/tests/console/connectors/social-connector-test-cases.ts
  packages/integration-tests/src/ui-helpers/index.ts
Labels: enhancement, size/l

#4685 chore(phrases): add phrases of enterprise identities
  packages/console/src/pages/UserDetails/UserSettings/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/user-details.ts
  packages/phrases/src/locales/en/translation/admin-console/user-details.ts
  packages/phrases/src/locales/es/translation/admin-console/user-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/user-details.ts
  packages/phrases/src/locales/it/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/user-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/user-details.ts
Labels: chore, size/l

#4700 refactor(test): avoid sending connection tests to 3rd-party connector services
  packages/integration-tests/src/tests/console/connectors/helpers.ts
  packages/integration-tests/src/tests/console/connectors/passwordless-connector-test-cases.ts
  packages/integration-tests/src/tests/console/connectors/passwordless-connectors.test.ts
Labels: enhancement, chore, size/m

#4683 feat(console): init organization settings
  packages/console/src/assets/icons/organization.svg
  packages/console/src/components/DeleteButton/index.tsx
  packages/console/src/components/PermissionsTable/index.module.scss
  packages/console/src/containers/ConsoleContent/Sidebar/hook.tsx
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/ds-components/Dropdown/DropdownItem.tsx
  packages/console/src/ds-components/Dropdown/index.tsx
  packages/console/src/ds-components/Select/index.module.scss
  packages/console/src/ds-components/TabNav/TabNavItem.tsx
  packages/console/src/ds-components/Table/index.module.scss
  packages/console/src/ds-components/Table/index.tsx
  packages/console/src/ds-components/Tag/index.module.scss
  packages/console/src/ds-components/Tag/index.tsx
  packages/console/src/pages/Connectors/ConnectorDeleteButton/index.tsx
  packages/console/src/pages/Organizations/CreatePermissionModal/index.tsx
  packages/console/src/pages/Organizations/PermissionsField/index.tsx
  packages/console/src/pages/Organizations/Settings/index.tsx
  packages/console/src/pages/Organizations/TemplateTable/index.module.scss
  packages/console/src/pages/Organizations/TemplateTable/index.tsx
  packages/console/src/pages/Organizations/index.module.scss
  packages/console/src/pages/Organizations/index.tsx
  packages/console/src/scss/_underscore.scss
  packages/core/src/queries/organizations.ts
  packages/core/src/utils/SchemaQueries.ts
  packages/integration-tests/src/tests/console/webhooks/index.test.ts
Labels: feature, size/xl

#4694 feat(schemas): create sso_connectors table
  .github/workflows/main.yml
  packages/schemas/alterations/next-1697683802-add-sso-connectors-table.ts
  packages/schemas/src/foundations/jsonb-types/index.ts
  packages/schemas/src/foundations/jsonb-types/sso-connector.ts
  packages/schemas/tables/sso_connectors.sql
Labels: feature, size/m

#4680 refactor(core,phrases): change interaction bind-mfa to array
  packages/core/src/routes/interaction/actions/submit-interaction.mfa.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/core/src/routes/interaction/mfa.test.ts
  packages/core/src/routes/interaction/mfa.ts
  packages/core/src/routes/interaction/types/guard.ts
  packages/core/src/routes/interaction/types/index.ts
  packages/core/src/routes/interaction/verifications/mfa-verification.test.ts
  packages/core/src/routes/interaction/verifications/mfa-verification.ts
  packages/experience/src/apis/interaction.ts
  packages/integration-tests/src/api/interaction.ts
  packages/integration-tests/src/tests/api/interaction/mfa/totp.test.ts
  packages/phrases/src/locales/de/errors/session.ts
  packages/phrases/src/locales/en/errors/session.ts
  packages/phrases/src/locales/es/errors/session.ts
  packages/phrases/src/locales/fr/errors/session.ts
  packages/phrases/src/locales/it/errors/session.ts
  packages/phrases/src/locales/ja/errors/session.ts
  packages/phrases/src/locales/ko/errors/session.ts
  packages/phrases/src/locales/pl-pl/errors/session.ts
  packages/phrases/src/locales/pt-br/errors/session.ts
  packages/phrases/src/locales/pt-pt/errors/session.ts
  packages/phrases/src/locales/ru/errors/session.ts
  packages/phrases/src/locales/tr-tr/errors/session.ts
  packages/phrases/src/locales/zh-cn/errors/session.ts
  packages/phrases/src/locales/zh-hk/errors/session.ts
  packages/phrases/src/locales/zh-tw/errors/session.ts
Labels: enhancement, size/m

#4686 feat(phrases): add backup code phrases
  packages/phrases/src/locales/de/errors/session.ts
  packages/phrases/src/locales/en/errors/session.ts
  packages/phrases/src/locales/es/errors/session.ts
  packages/phrases/src/locales/fr/errors/session.ts
  packages/phrases/src/locales/it/errors/session.ts
  packages/phrases/src/locales/ja/errors/session.ts
  packages/phrases/src/locales/ko/errors/session.ts
  packages/phrases/src/locales/pl-pl/errors/session.ts
  packages/phrases/src/locales/pt-br/errors/session.ts
  packages/phrases/src/locales/pt-pt/errors/session.ts
  packages/phrases/src/locales/ru/errors/session.ts
  packages/phrases/src/locales/tr-tr/errors/session.ts
  packages/phrases/src/locales/zh-cn/errors/session.ts
  packages/phrases/src/locales/zh-hk/errors/session.ts
  packages/phrases/src/locales/zh-tw/errors/session.ts
Labels: feature, size/s

#4706 refactor(console): hide WebAuthn user-agent info on user details page
  packages/console/src/components/MfaFactorName/index.tsx
  packages/console/src/components/MfaFactorTitle/index.tsx
Labels: enhancement, size/s

#4707 chore(core,shared): add isDevFeatureEnabled to envset
  packages/console/src/consts/env.ts
  packages/core/src/libraries/sign-in-experience/mfa.ts
  packages/experience/src/App.tsx
  packages/experience/src/constants/env.ts
  packages/experience/src/hooks/use-pre-sign-in-error-handler.ts
  packages/shared/src/node/env/GlobalValues.ts
Labels: chore, size/s

#4627 ci: add alteration scripts compatibility test jobs
  .github/workflows/alteration-compatibility-integration-test.yml
  .github/workflows/integration-test.yml
Labels: size/m

#4690 feat(core,schemas): bind backup code
  packages/core/src/__mocks__/mfa-verification.ts
  packages/core/src/routes/interaction/actions/submit-interaction.mfa.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/core/src/routes/interaction/index.test.ts
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/mfa.test.ts
  packages/core/src/routes/interaction/mfa.ts
  packages/core/src/routes/interaction/utils/backup-code-validation.test.ts
  packages/core/src/routes/interaction/utils/backup-code-validation.ts
  packages/core/src/routes/interaction/verifications/mfa-payload-verification.test.ts
  packages/core/src/routes/interaction/verifications/mfa-payload-verification.ts
  packages/core/src/routes/interaction/verifications/mfa-verification.test.ts
  packages/core/src/routes/interaction/verifications/mfa-verification.ts
  packages/core/src/utils/user.ts
  packages/schemas/src/foundations/jsonb-types/users.ts
  packages/schemas/src/types/interactions.ts
  packages/schemas/src/types/user.ts
Labels: feature, size/l

#4709 refactor(console): add webauthn tips and update phrases
  packages/console/src/components/MfaFactorTitle/index.module.scss
  packages/console/src/components/MfaFactorTitle/index.tsx
  packages/console/src/pages/Mfa/MfaForm/FactorLabel/WebAuthnTipContent/index.module.scss
  packages/console/src/pages/Mfa/MfaForm/FactorLabel/WebAuthnTipContent/index.tsx
  packages/console/src/pages/Mfa/MfaForm/FactorLabel/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/mfa.ts
  packages/phrases/src/locales/en/translation/admin-console/mfa.ts
  packages/phrases/src/locales/es/translation/admin-console/mfa.ts
  packages/phrases/src/locales/fr/translation/admin-console/mfa.ts
  packages/phrases/src/locales/it/translation/admin-console/mfa.ts
  packages/phrases/src/locales/ja/translation/admin-console/mfa.ts
  packages/phrases/src/locales/ko/translation/admin-console/mfa.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/mfa.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/mfa.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/mfa.ts
  packages/phrases/src/locales/ru/translation/admin-console/mfa.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/mfa.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/mfa.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/mfa.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/mfa.ts
Labels: enhancement, size/m

#4715 refactor(console): clear search input on clear search results
  packages/console/src/ds-components/Search/index.tsx
Labels: enhancement, size/s

#4716 feat(console): support HTTP for webhook requests
  .changeset/tough-brooms-sip.md
  packages/console/src/components/BasicWebhookForm/index.tsx
  packages/integration-tests/src/tests/console/webhooks/helpers.ts
  packages/integration-tests/src/tests/console/webhooks/index.test.ts
  packages/phrases/src/locales/de/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/de/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/en/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/en/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/es/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/es/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/fr/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/it/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/it/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/ja/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/ko/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/ru/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/webhooks.ts
Labels: feature, size/m

#4696 feat(console,core): edit permissions and roles
  packages/console/src/assets/icons/edit.svg
  packages/console/src/components/DeleteButton/index.tsx
  packages/console/src/hooks/use-action-translation.ts
  packages/console/src/pages/Organizations/ActionsButton/index.module.scss
  packages/console/src/pages/Organizations/ActionsButton/index.tsx
  packages/console/src/pages/Organizations/PermissionModal/index.tsx
  packages/console/src/pages/Organizations/PermissionsField/index.tsx
  packages/console/src/pages/Organizations/RoleModal/index.tsx
  packages/console/src/pages/Organizations/RolesField/index.tsx
  packages/core/src/queries/organizations.ts
  packages/core/src/routes/organization/roles.ts
  packages/core/src/utils/RelationQueries.ts
  packages/core/src/utils/SchemaRouter.ts
  packages/integration-tests/src/api/organization-role.ts
  packages/integration-tests/src/tests/api/organization-role.test.ts
  packages/phrases/src/locales/de/translation/admin-console/general.ts
  packages/phrases/src/locales/de/translation/admin-console/organizations.ts
  packages/phrases/src/locales/en/translation/admin-console/general.ts
  packages/phrases/src/locales/en/translation/admin-console/organizations.ts
  packages/phrases/src/locales/es/translation/admin-console/general.ts
  packages/phrases/src/locales/es/translation/admin-console/organizations.ts
  packages/phrases/src/locales/fr/translation/admin-console/general.ts
  packages/phrases/src/locales/fr/translation/admin-console/organizations.ts
  packages/phrases/src/locales/it/translation/admin-console/general.ts
  packages/phrases/src/locales/it/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ja/translation/admin-console/general.ts
  packages/phrases/src/locales/ja/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ko/translation/admin-console/general.ts
  packages/phrases/src/locales/ko/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/general.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ru/translation/admin-console/general.ts
  packages/phrases/src/locales/ru/translation/admin-console/organizations.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/organizations.ts
Labels: feature, size/xl

#4698 feat(core): schema with search fields
  packages/core/src/database/find-all-entities.ts
  packages/core/src/database/row-count.ts
  packages/core/src/database/utils.ts
  packages/core/src/queries/organizations.ts
  packages/core/src/routes/organization/index.ts
  packages/core/src/routes/organization/roles.ts
  packages/core/src/routes/organization/scopes.ts
  packages/core/src/utils/SchemaQueries.ts
  packages/core/src/utils/SchemaRouter.test.ts
  packages/core/src/utils/SchemaRouter.ts
Labels: feature, size/m

#4702 refactor(console): use correct delete confirmation text
  packages/console/src/pages/Organizations/ActionsButton/index.tsx
  packages/console/src/pages/Organizations/PermissionsField/index.tsx
  packages/console/src/pages/Organizations/RolesField/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/organizations.ts
  packages/phrases/src/locales/en/translation/admin-console/organizations.ts
  packages/phrases/src/locales/es/translation/admin-console/organizations.ts
  packages/phrases/src/locales/fr/translation/admin-console/organizations.ts
  packages/phrases/src/locales/it/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ja/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ko/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ru/translation/admin-console/organizations.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/organizations.ts
Labels: enhancement, size/m

#4704 feat(phrases): organization phrases
  packages/phrases/src/locales/de/translation/admin-console/general.ts
  packages/phrases/src/locales/de/translation/admin-console/index.ts
  packages/phrases/src/locales/de/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/de/translation/admin-console/organizations.ts
  packages/phrases/src/locales/en/translation/admin-console/general.ts
  packages/phrases/src/locales/en/translation/admin-console/index.ts
  packages/phrases/src/locales/en/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/en/translation/admin-console/organizations.ts
  packages/phrases/src/locales/es/translation/admin-console/general.ts
  packages/phrases/src/locales/es/translation/admin-console/index.ts
  packages/phrases/src/locales/es/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/es/translation/admin-console/organizations.ts
  packages/phrases/src/locales/fr/translation/admin-console/general.ts
  packages/phrases/src/locales/fr/translation/admin-console/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/organizations.ts
  packages/phrases/src/locales/it/translation/admin-console/general.ts
  packages/phrases/src/locales/it/translation/admin-console/index.ts
  packages/phrases/src/locales/it/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/it/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ja/translation/admin-console/general.ts
  packages/phrases/src/locales/ja/translation/admin-console/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ko/translation/admin-console/general.ts
  packages/phrases/src/locales/ko/translation/admin-console/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/general.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ru/translation/admin-console/general.ts
  packages/phrases/src/locales/ru/translation/admin-console/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/organizations.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/organizations.ts
Labels: feature, size/xl

#4714 feat(core): organization apis
  packages/core/src/database/find-all-entities.ts
  packages/core/src/database/row-count.ts
  packages/core/src/database/utils.ts
  packages/core/src/include.d/koa-router.d.ts
  packages/core/src/queries/organizations.ts
  packages/core/src/queries/user.ts
  packages/core/src/routes/admin-user/organization.ts
  packages/core/src/routes/admin-user/search.test.ts
  packages/core/src/routes/admin-user/search.ts
  packages/core/src/routes/dashboard.test.ts
  packages/core/src/routes/dashboard.ts
  packages/core/src/routes/organization/index.ts
  packages/core/src/routes/organization/utils.ts
  packages/core/src/routes/role.user.ts
  packages/core/src/utils/RelationQueries.ts
  packages/core/src/utils/SchemaQueries.ts
  packages/core/src/utils/SchemaRouter.ts
  packages/core/src/utils/search.ts
  packages/integration-tests/src/api/organization.ts
  packages/integration-tests/src/tests/api/organization.test.ts
  packages/schemas/src/types/organization.ts
Labels: feature, size/xl

#4697 feat(core): skippable bind mfa prompt
  packages/core/src/routes/interaction/verifications/mfa-verification.test.ts
  packages/core/src/routes/interaction/verifications/mfa-verification.ts
  packages/integration-tests/src/helpers/sign-in-experience.ts
  packages/integration-tests/src/tests/api/interaction/mfa/totp.test.ts
Labels: feature, size/m

#4729 fix(core): get hostname from ctx for webauthn
  packages/core/src/routes/interaction/additional.ts
  packages/core/src/routes/interaction/mfa.ts
Labels: bugfix, size/xs

#4724 feat(experience): skip mfa binding
  packages/experience/src/App.tsx
  packages/experience/src/Layout/SecondaryPageLayout/index.tsx
  packages/experience/src/apis/interaction.ts
  packages/experience/src/components/NavBar/index.module.scss
  packages/experience/src/components/NavBar/index.tsx
  packages/experience/src/components/SwitchMfaFactorsLink/index.tsx
  packages/experience/src/containers/MfaFactorList/index.tsx
  packages/experience/src/hooks/use-mfa-error-handler.ts
  packages/experience/src/hooks/use-mfa-factors-state.ts
  packages/experience/src/hooks/use-skip-mfa.ts
  packages/experience/src/hooks/use-start-totp-binding.ts
  packages/experience/src/pages/MfaBinding/TotpBinding/index.tsx
  packages/experience/src/pages/MfaBinding/WebAuthnBinding/index.tsx
  packages/experience/src/pages/MfaBinding/index.tsx
  packages/experience/src/pages/MfaVerification/BackupCodeVerification/index.tsx
  packages/experience/src/pages/MfaVerification/TotpVerification/index.tsx
  packages/experience/src/pages/MfaVerification/WebAuthnVerification/index.tsx
  packages/experience/src/pages/MfaVerification/index.tsx
  packages/experience/src/types/guard.ts
  packages/integration-tests/src/tests/experience/mfa/user-controlled.test.ts
  packages/phrases-experience/src/locales/de/action.ts
  packages/phrases-experience/src/locales/en/action.ts
  packages/phrases-experience/src/locales/es/action.ts
  packages/phrases-experience/src/locales/fr/action.ts
  packages/phrases-experience/src/locales/it/action.ts
  packages/phrases-experience/src/locales/ja/action.ts
  packages/phrases-experience/src/locales/ko/action.ts
  packages/phrases-experience/src/locales/pl-pl/action.ts
  packages/phrases-experience/src/locales/pt-br/action.ts
  packages/phrases-experience/src/locales/pt-pt/action.ts
  packages/phrases-experience/src/locales/ru/action.ts
  packages/phrases-experience/src/locales/tr-tr/action.ts
  packages/phrases-experience/src/locales/zh-cn/action.ts
  packages/phrases-experience/src/locales/zh-hk/action.ts
  packages/phrases-experience/src/locales/zh-tw/action.ts
Labels: feature, size/l

#4728 fix(cli): fix unsupported signing key error when generating keys with cli
  packages/cli/src/commands/database/config.ts
Labels: bugfix, size/xs

#4732 feat(console): add mfa to plan quota table
  packages/console/src/consts/plan-quotas.ts
Labels: feature, size/xs

#4703 fix(core): set totp qrcode service and user name
  packages/core/src/routes/interaction/additional.test.ts
  packages/core/src/routes/interaction/additional.ts
  packages/shared/src/utils/index.ts
  packages/shared/src/utils/user-display-name.test.ts
  packages/shared/src/utils/user-display-name.ts
Labels: bugfix, size/s

#4735 fix(core): fix bind webauthn domain hostname
  packages/core/src/routes/interaction/mfa.ts
Labels: bugfix, size/xs

#4712 refactor(console): improve responsiveness in all details pages
  packages/console/src/assets/icons/file.svg
  packages/console/src/components/DetailsPage/DetailsPageHeader/index.module.scss
  packages/console/src/components/DetailsPage/DetailsPageHeader/index.tsx
  packages/console/src/components/FormCard/FormCardLayout/index.module.scss
  packages/console/src/components/FormCard/FormCardLayout/index.tsx
  packages/console/src/components/SuccessRate/index.tsx
  packages/console/src/containers/ConsoleContent/index.module.scss
  packages/console/src/ds-components/Button/index.module.scss
  packages/console/src/ds-components/CopyToClipboard/index.tsx
  packages/console/src/ds-components/Dropdown/DropdownItem.tsx
  packages/console/src/ds-components/Tag/index.module.scss
  packages/console/src/pages/ApiResourceDetails/index.module.scss
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/console/src/pages/ApplicationDetails/index.module.scss
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/ConnectorDetails/EmailUsage/index.module.scss
  packages/console/src/pages/ConnectorDetails/EmailUsage/index.tsx
  packages/console/src/pages/ConnectorDetails/index.module.scss
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/RoleDetails/index.module.scss
  packages/console/src/pages/RoleDetails/index.tsx
  packages/console/src/pages/UserDetails/index.module.scss
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/pages/WebhookDetails/index.module.scss
  packages/console/src/pages/WebhookDetails/index.tsx
  packages/console/src/pages/Webhooks/index.tsx
  packages/console/src/scss/_underscore.scss
  packages/integration-tests/src/tests/console/machine-to-machine-rbac/machime-to-machime-rbac.test.ts
  packages/integration-tests/src/tests/console/machine-to-machine-rbac/utils.ts
  packages/integration-tests/src/tests/console/rbac.test.ts
  packages/integration-tests/src/tests/console/sign-in-experience/sign-up-and-sign-in/sad-path.test.ts
  packages/integration-tests/src/tests/console/user-management.test.ts
  packages/integration-tests/src/tests/console/webhooks/helpers.ts
  packages/integration-tests/src/tests/console/webhooks/index.test.ts
  packages/integration-tests/src/ui-helpers/index.ts
Labels: enhancement, size/xl

#4737 fix(experience): correct mfa flow state for switch mfa factors link
  packages/experience/src/pages/MfaBinding/TotpBinding/index.tsx
  packages/integration-tests/src/tests/experience/mfa/factor-switching.test.ts
  packages/integration-tests/src/ui-helpers/expect-experience.ts
Labels: bugfix, size/s

#4717 feat(console): init organization table
  packages/console/src/assets/icons/organization-preview.svg
  packages/console/src/components/ActionsButton/index.module.scss
  packages/console/src/components/ActionsButton/index.tsx
  packages/console/src/components/EmptyDataPlaceholder/index.tsx
  packages/console/src/components/FormCard/index.module.scss
  packages/console/src/components/ItemPreview/UserPreview.tsx
  packages/console/src/components/OrganizationScopesSelect/index.tsx
  packages/console/src/components/ThemedIcon/index.module.scss
  packages/console/src/components/ThemedIcon/index.tsx
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/ds-components/ConfirmModal/index.tsx
  packages/console/src/ds-components/DangerousRaw/index.tsx
  packages/console/src/ds-components/Table/index.tsx
  packages/console/src/hooks/use-action-translation.ts
  packages/console/src/hooks/use-search-values.ts
  packages/console/src/pages/Organizations/CreateOrganizationModal/index.tsx
  packages/console/src/pages/Organizations/OrganizationsTable/index.tsx
  packages/console/src/pages/Organizations/PermissionModal/index.tsx
  packages/console/src/pages/Organizations/PermissionsField/index.tsx
  packages/console/src/pages/Organizations/RoleModal/index.tsx
  packages/console/src/pages/Organizations/RolesField/index.tsx
  packages/console/src/pages/Organizations/index.tsx
  packages/console/src/pages/RoleDetails/RoleUsers/index.tsx
  packages/console/src/utils/string.ts
  packages/toolkit/core-kit/scss/_console-themes.scss
Labels: feature, size/xl

#4718 feat(console): organization details
  packages/console/src/components/OrganizationRolesSelect/index.tsx
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/pages/OrganizationDetails/Members/EditOrganizationRolesModal.tsx
  packages/console/src/pages/OrganizationDetails/Members/index.module.scss
  packages/console/src/pages/OrganizationDetails/Members/index.tsx
  packages/console/src/pages/OrganizationDetails/Settings/index.tsx
  packages/console/src/pages/OrganizationDetails/index.module.scss
  packages/console/src/pages/OrganizationDetails/index.tsx
Labels: feature, size/xl

#4720 feat(console): add org members
  packages/console/src/components/EntitiesTransfer/components/EntityItem/index.module.scss
  packages/console/src/components/EntitiesTransfer/components/EntityItem/index.tsx
  packages/console/src/components/EntitiesTransfer/components/SourceEntitiesBox/index.module.scss
  packages/console/src/components/EntitiesTransfer/components/SourceEntitiesBox/index.tsx
  packages/console/src/components/EntitiesTransfer/components/SourceEntityItem/index.module.scss
  packages/console/src/components/EntitiesTransfer/components/SourceEntityItem/index.tsx
  packages/console/src/components/EntitiesTransfer/components/TargetEntitiesBox/index.module.scss
  packages/console/src/components/EntitiesTransfer/components/TargetEntitiesBox/index.tsx
  packages/console/src/components/EntitiesTransfer/components/TargetEntityItem/index.module.scss
  packages/console/src/components/EntitiesTransfer/components/TargetEntityItem/index.tsx
  packages/console/src/components/EntitiesTransfer/index.module.scss
  packages/console/src/components/EntitiesTransfer/index.tsx
  packages/console/src/pages/OrganizationDetails/Members/AddMembersToOrganization.tsx
  packages/console/src/pages/OrganizationDetails/Members/index.tsx
  packages/console/src/types/general.ts
Labels: feature, size/xl

#4731 refactor(console): make guide related components more generic
  packages/console/src/components/ActionBar/index.module.scss
  packages/console/src/components/ActionBar/index.tsx
  packages/console/src/components/Guide/ModalHeader/index.module.scss
  packages/console/src/components/Guide/ModalHeader/index.tsx
  packages/console/src/components/ProgressBar/index.module.scss
  packages/console/src/components/ProgressBar/index.tsx
  packages/console/src/ds-components/ModalHeader/index.module.scss
  packages/console/src/ds-components/ModalHeader/index.tsx
  packages/console/src/onboarding/pages/SignInExperience/index.tsx
  packages/console/src/onboarding/pages/Welcome/index.tsx
Labels: enhancement, size/m

#4721 refactor(console): remove role transfer component
  packages/console/src/components/EntitiesTransfer/components/EntityItem/index.tsx
  packages/console/src/components/RoleEntitiesTransfer/components/SourceEntitiesBox/index.module.scss
  packages/console/src/components/RoleEntitiesTransfer/components/SourceEntitiesBox/index.tsx
  packages/console/src/components/RoleEntitiesTransfer/components/SourceEntityItem/index.module.scss
  packages/console/src/components/RoleEntitiesTransfer/components/SourceEntityItem/index.tsx
  packages/console/src/components/RoleEntitiesTransfer/components/TargetEntitiesBox/index.module.scss
  packages/console/src/components/RoleEntitiesTransfer/components/TargetEntitiesBox/index.tsx
  packages/console/src/components/RoleEntitiesTransfer/components/TargetEntityItem/index.module.scss
  packages/console/src/components/RoleEntitiesTransfer/components/TargetEntityItem/index.tsx
  packages/console/src/components/RoleEntitiesTransfer/index.module.scss
  packages/console/src/components/RoleEntitiesTransfer/index.tsx
  packages/console/src/components/RoleEntitiesTransfer/utils.ts
  packages/console/src/pages/Roles/components/AssignRoleModal/index.tsx
  packages/core/src/utils/search.ts
Labels: enhancement, size/l

#4725 refactor(core,console): fixing to-dos
  packages/console/src/components/ItemPreview/index.module.scss
  packages/console/src/pages/OrganizationDetails/Members/AddMembersToOrganization.tsx
  packages/console/src/pages/OrganizationDetails/Members/index.tsx
  packages/console/src/pages/OrganizationDetails/index.module.scss
  packages/console/src/pages/OrganizationDetails/index.tsx
  packages/core/src/database/find-all-entities.ts
  packages/core/src/database/utils.ts
  packages/core/src/queries/organizations.ts
  packages/core/src/routes/organization/index.ts
  packages/core/src/routes/organization/utils.ts
  packages/core/src/utils/RelationQueries.ts
  packages/integration-tests/src/tests/api/organization-role.test.ts
  packages/integration-tests/src/tests/api/organization-scope.test.ts
  packages/phrases/src/locales/de/errors/entity.ts
  packages/phrases/src/locales/en/errors/entity.ts
  packages/phrases/src/locales/es/errors/entity.ts
  packages/phrases/src/locales/fr/errors/entity.ts
  packages/phrases/src/locales/it/errors/entity.ts
  packages/phrases/src/locales/ja/errors/entity.ts
  packages/phrases/src/locales/ko/errors/entity.ts
  packages/phrases/src/locales/pl-pl/errors/entity.ts
  packages/phrases/src/locales/pt-br/errors/entity.ts
  packages/phrases/src/locales/pt-pt/errors/entity.ts
  packages/phrases/src/locales/ru/errors/entity.ts
  packages/phrases/src/locales/tr-tr/errors/entity.ts
  packages/phrases/src/locales/zh-cn/errors/entity.ts
  packages/phrases/src/locales/zh-hk/errors/entity.ts
  packages/phrases/src/locales/zh-tw/errors/entity.ts
  packages/shared/src/database/types.ts
Labels: enhancement, size/m

#4726 refactor(console): fixing to-dos
  packages/console/src/components/EntitiesTransfer/index.module.scss
  packages/console/src/components/EntitiesTransfer/index.tsx
  packages/console/src/ds-components/Select/MultiSelect.tsx
  packages/console/src/pages/OrganizationDetails/Members/AddMembersToOrganization.tsx
  packages/console/src/pages/OrganizationDetails/Members/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/en/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/es/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/it/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/organization-details.ts
Labels: enhancement, size/s

#4738 refactor(test): manage test resource lifecycle
  packages/integration-tests/src/api/admin-user.ts
  packages/integration-tests/src/api/organization-role.ts
  packages/integration-tests/src/api/organization-scope.ts
  packages/integration-tests/src/api/organization.ts
  packages/integration-tests/src/helpers/organization.ts
  packages/integration-tests/src/helpers/user.ts
  packages/integration-tests/src/tests/api/organization-role.test.ts
  packages/integration-tests/src/tests/api/organization-scope.test.ts
  packages/integration-tests/src/tests/api/organization.test.ts
Labels: enhancement, size/l

#4739 chore(test): add integration tests for new APIs
  packages/console/src/pages/OrganizationDetails/Members/AddMembersToOrganization.tsx
  packages/core/src/middleware/koa-auth/index.ts
  packages/core/src/routes/organization/index.ts
  packages/integration-tests/src/api/organization.ts
  packages/integration-tests/src/helpers/organization.ts
  packages/integration-tests/src/helpers/user.ts
  packages/integration-tests/src/tests/api/admin-user.search.test.ts
  packages/integration-tests/src/tests/api/organization-user.test.ts
  packages/integration-tests/src/tests/api/organization.test.ts
  packages/integration-tests/src/utils.ts
Labels: chore, size/xl

#4736 feat(core): implement patch sso-connector config api
  packages/core/src/routes/sso-connector/index.ts
  packages/integration-tests/src/api/sso-connector.ts
  packages/integration-tests/src/tests/api/sso-connectors.test.ts
Labels: feature, size/s

#4734 feat(core): implement patch sso-connectors api
  packages/core/src/routes/sso-connector/index.ts
  packages/core/src/routes/sso-connector/type.ts
  packages/core/src/routes/sso-connector/utils.ts
  packages/core/src/sso/types/index.ts
  packages/integration-tests/src/api/sso-connector.ts
  packages/integration-tests/src/tests/api/sso-connectors.test.ts
Labels: feature, size/l

#4733 feat(core): implement delete sso-connector by id endpoint
  packages/core/src/routes/sso-connector/index.ts
  packages/core/src/routes/sso-connector/type.ts
  packages/core/src/routes/sso-connector/utils.ts
  packages/core/src/sso/types/index.ts
  packages/integration-tests/src/api/sso-connector.ts
  packages/integration-tests/src/tests/api/sso-connectors.test.ts
Labels: feature, size/s

#4730 feat(core): implement get sso-connector by id endpoint
  packages/core/src/routes/sso-connector/index.ts
  packages/core/src/routes/sso-connector/type.ts
  packages/core/src/routes/sso-connector/utils.ts
  packages/core/src/sso/types/index.ts
  packages/integration-tests/src/api/sso-connector.ts
  packages/integration-tests/src/tests/api/sso-connectors.test.ts
Labels: feature, size/l

#4742 style(experience): left align factor button text content
  packages/experience/src/components/Button/MfaFactorButton.module.scss
Labels: size/xs

#4744 style(experience): increase padding for binding backup code page
  packages/experience/src/pages/MfaBinding/BackupCodeBinding/index.module.scss
  packages/experience/src/pages/MfaBinding/BackupCodeBinding/index.tsx
Labels: size/s

#4745 refactor(experience): clear invalid totp code input
  packages/experience/src/containers/TotpCodeVerification/index.tsx
  packages/experience/src/containers/TotpCodeVerification/use-totp-code-verification.ts
  packages/experience/src/hooks/use-send-mfa-payload.ts
Labels: enhancement, size/s

#4723 feat(core): add GET sso-connectors api
  packages/core/src/routes/sso-connector/index.ts
  packages/core/src/routes/sso-connector/type.ts
  packages/core/src/routes/sso-connector/utils.test.ts
  packages/core/src/routes/sso-connector/utils.ts
  packages/core/src/sso/types/index.ts
  packages/core/src/sso/types/oidc.ts
  packages/core/src/utils/SchemaQueries.ts
  packages/core/src/utils/SchemaRouter.ts
  packages/integration-tests/src/api/sso-connector.ts
  packages/integration-tests/src/tests/api/sso-connectors.test.ts
Labels: feature, size/xl

#4743 refactor(experience): display secret code first when binding totp on mobile devices
  packages/experience/src/pages/MfaBinding/TotpBinding/SecretSection/index.tsx
Labels: enhancement, size/xs

#4722 refactor(console): use phrase key for `<AssignRoleModal>`
  packages/console/src/pages/Roles/components/AssignRoleModal/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/role-details.ts
  packages/phrases/src/locales/en/translation/admin-console/role-details.ts
  packages/phrases/src/locales/es/translation/admin-console/role-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/role-details.ts
  packages/phrases/src/locales/it/translation/admin-console/role-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/role-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/role-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/role-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/role-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/role-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/role-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/role-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/role-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/role-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/role-details.ts
Labels: enhancement, size/m

#4719 feat(core): add POST sso-connectors api
  packages/core/src/queries/sso-connectors.ts
  packages/core/src/routes/sso-connector/index.ts
  packages/core/src/routes/sso-connector/type.ts
  packages/core/src/routes/sso-connector/utils.test.ts
  packages/core/src/routes/sso-connector/utils.ts
  packages/core/src/sso/OidcConnector/index.ts
  packages/core/src/sso/OidcSsoConnector/index.ts
  packages/core/src/sso/index.ts
  packages/core/src/sso/types/index.ts
  packages/core/src/sso/types/oidc.ts
  packages/core/src/tenants/Queries.ts
  packages/core/src/utils/SchemaQueries.ts
  packages/core/src/utils/SchemaRouter.ts
  packages/integration-tests/src/api/sso-connector.ts
  packages/integration-tests/src/tests/api/sso-connectors.test.ts
Labels: feature, size/xl

#4701 feat(core): add OIDC SSO connector class
  packages/core/package.json
  packages/core/src/__mocks__/sso.ts
  packages/core/src/queries/sso-connectors.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/sso-connector/index.ts
  packages/core/src/routes/sso-connector/type.ts
  packages/core/src/routes/sso-connector/utils.test.ts
  packages/core/src/routes/sso-connector/utils.ts
  packages/core/src/sso/OidcConnector/index.ts
  packages/core/src/sso/OidcConnector/utils.test.ts
  packages/core/src/sso/OidcConnector/utils.ts
  packages/core/src/sso/OidcSsoConnector/index.test.ts
  packages/core/src/sso/OidcSsoConnector/index.ts
  packages/core/src/sso/index.ts
  packages/core/src/sso/types/index.ts
  packages/core/src/sso/types/oidc.test.ts
  packages/core/src/sso/types/oidc.ts
  packages/core/src/tenants/Queries.ts
  packages/core/src/utils/SchemaQueries.ts
  packages/core/src/utils/SchemaRouter.ts
  packages/integration-tests/src/api/sso-connector.ts
  packages/integration-tests/src/tests/api/sso-connectors.test.ts
  packages/toolkit/connector-kit/src/types/metadata.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#4746 refactor(console): fixing code review to-dos
  packages/console/src/components/OrganizationRolesSelect/index.tsx
  packages/console/src/components/OrganizationScopesSelect/index.tsx
  packages/console/src/ds-components/Select/MultiSelect.tsx
  packages/console/src/ds-components/Select/index.module.scss
  packages/console/src/hooks/use-search-values.ts
  packages/console/src/pages/OrganizationDetails/Members/AddMembersToOrganization.tsx
  packages/console/src/pages/OrganizationDetails/Members/EditOrganizationRolesModal.tsx
  packages/console/src/pages/OrganizationDetails/index.tsx
  packages/console/src/pages/Organizations/CreateOrganizationModal/index.tsx
  packages/console/src/pages/Organizations/OrganizationsTable/index.tsx
  packages/console/src/pages/Organizations/PermissionModal/index.tsx
  packages/console/src/pages/Organizations/PermissionsField/index.tsx
  packages/console/src/pages/Organizations/RoleModal/index.tsx
  packages/console/src/pages/Organizations/RolesField/index.tsx
  packages/console/src/pages/Organizations/TemplateTable/index.tsx
  packages/core/src/database/utils.ts
  packages/integration-tests/src/api/organization-role.ts
  packages/phrases/src/locales/de/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/de/translation/admin-console/organizations.ts
  packages/phrases/src/locales/en/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/en/translation/admin-console/organizations.ts
  packages/phrases/src/locales/es/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/es/translation/admin-console/organizations.ts
  packages/phrases/src/locales/fr/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/organizations.ts
  packages/phrases/src/locales/it/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/it/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ja/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ko/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ru/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/organizations.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/organizations.ts
Labels: enhancement, size/l

#4748 chore: use sentence case
  packages/connectors/connector-sendgrid-email/README.md
  packages/connectors/connector-smtp/src/constant.ts
  packages/connectors/connector-smtp/src/index.test.ts
  packages/connectors/connector-smtp/src/mock.ts
  packages/console/src/assets/docs/guides/m2m-general/README.mdx
  packages/console/src/assets/docs/guides/native-capacitor/README.mdx
  packages/console/src/assets/docs/guides/native-flutter/README.mdx
  packages/core/README.md
  packages/core/src/routes/interaction/verifications/identifier-payload-verification.ts
  packages/experience/src/hooks/use-social-sign-in-listener.ts
  packages/experience/src/pages/SignInPassword/index.tsx
  packages/integration-tests/src/tests/console/applications/helpers.ts
  packages/integration-tests/src/tests/console/applications/index.test.ts
  packages/integration-tests/src/tests/console/connectors/passwordless-connectors.test.ts
  packages/integration-tests/src/tests/console/machine-to-machine-rbac/machime-to-machime-rbac.test.ts
  packages/integration-tests/src/tests/console/machine-to-machine-rbac/utils.ts
  packages/integration-tests/src/tests/console/rbac.test.ts
  packages/integration-tests/src/tests/console/sign-in-experience/branding.test.ts
  packages/integration-tests/src/tests/console/sign-in-experience/sign-up-and-sign-in/connector-setup-helpers.ts
  packages/integration-tests/src/tests/console/sign-in-experience/sign-up-and-sign-in/happy-path.test.ts
  packages/integration-tests/src/tests/console/sign-in-experience/sign-up-and-sign-in/sad-path.test.ts
  packages/integration-tests/src/tests/console/user-management.test.ts
  packages/integration-tests/src/ui-helpers/index.ts
  packages/phrases/src/locales/de/translation/admin-console/connectors.ts
  packages/phrases/src/locales/de/translation/admin-console/guide.ts
  packages/phrases/src/locales/de/translation/admin-console/log-details.ts
  packages/phrases/src/locales/de/translation/admin-console/logs.ts
  packages/phrases/src/locales/de/translation/admin-console/tabs.ts
  packages/phrases/src/locales/en/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/en/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/applications.ts
  packages/phrases/src/locales/en/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/en/translation/admin-console/connectors.ts
  packages/phrases/src/locales/en/translation/admin-console/general.ts
  packages/phrases/src/locales/en/translation/admin-console/get-started.ts
  packages/phrases/src/locales/en/translation/admin-console/guide.ts
  packages/phrases/src/locales/en/translation/admin-console/log-details.ts
  packages/phrases/src/locales/en/translation/admin-console/logs.ts
  packages/phrases/src/locales/en/translation/admin-console/profile.ts
  packages/phrases/src/locales/en/translation/admin-console/role-details.ts
  packages/phrases/src/locales/en/translation/admin-console/roles.ts
  packages/phrases/src/locales/en/translation/admin-console/session-expired.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/en/translation/admin-console/user-details.ts
  packages/phrases/src/locales/en/translation/admin-console/users.ts
  packages/phrases/src/locales/en/translation/admin-console/webhook-details.ts
  packages/phrases/src/locales/en/translation/demo-app.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/logs.ts
Labels: chore, size/l

#4755 feat: organization featured members
  packages/console/src/pages/Organizations/OrganizationsTable/index.tsx
  packages/core/src/queries/application.ts
  packages/core/src/queries/organizations.ts
  packages/core/src/routes/organization/index.ts
  packages/core/src/routes/role.test.ts
  packages/core/src/routes/role.ts
  packages/core/src/utils/RelationQueries.ts
  packages/core/src/utils/SchemaRouter.ts
  packages/core/src/utils/search.ts
  packages/integration-tests/src/api/organization.ts
  packages/integration-tests/src/tests/api/organization.test.ts
  packages/schemas/src/types/application.ts
  packages/schemas/src/types/organization.ts
  packages/schemas/src/types/role.ts
  packages/schemas/src/types/user.ts
Labels: feature, size/l

#4758 feat(console): organizations tab for user details
  packages/console/src/consts/page-tabs.ts
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/pages/OrganizationDetails/Members/index.tsx
  packages/console/src/pages/Organizations/OrganizationsTable/index.tsx
  packages/console/src/pages/Organizations/TemplateTable/index.tsx
  packages/console/src/pages/UserDetails/UserOrganizations/index.module.scss
  packages/console/src/pages/UserDetails/UserOrganizations/index.tsx
  packages/console/src/pages/UserDetails/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/user-details.ts
  packages/phrases/src/locales/en/translation/admin-console/user-details.ts
  packages/phrases/src/locales/es/translation/admin-console/user-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/user-details.ts
  packages/phrases/src/locales/it/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/user-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/user-details.ts
Labels: feature, size/m

#4747 style(experience): remove the margin of dividers without a label
  packages/experience/src/components/Divider/index.module.scss
  packages/experience/src/components/Divider/index.tsx
Labels: size/s

#4757 fix(test): make m2m RBAC console integration test stable
  packages/integration-tests/src/tests/console/machine-to-machine-rbac/machime-to-machime-rbac.test.ts
Labels: bugfix, size/xs

#4760 feat(console,phrases): add organization creation guide (part 1)
  packages/console/src/assets/icons/organization-feature-dark.svg
  packages/console/src/assets/icons/organization-feature.svg
  packages/console/src/assets/icons/permission-feature-dark.svg
  packages/console/src/assets/icons/permission-feature.svg
  packages/console/src/assets/icons/rbac-feature-dark.svg
  packages/console/src/assets/icons/rbac-feature.svg
  packages/console/src/assets/images/organization-workflow.webp
  packages/console/src/components/ActionBar/index.module.scss
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/pages/Organizations/Guide/Step1/index.module.scss
  packages/console/src/pages/Organizations/Guide/Step1/index.tsx
  packages/console/src/pages/Organizations/Guide/index.module.scss
  packages/console/src/pages/Organizations/Guide/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/organizations.ts
  packages/phrases/src/locales/en/translation/admin-console/organizations.ts
  packages/phrases/src/locales/es/translation/admin-console/organizations.ts
  packages/phrases/src/locales/fr/translation/admin-console/organizations.ts
  packages/phrases/src/locales/it/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ja/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ko/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ru/translation/admin-console/organizations.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/organizations.ts
Labels: feature, size/xl

#4766 Revert "chore(deps): update parcel monorepo to v2.10.1"
  packages/console/package.json
  packages/demo-app/package.json
  packages/experience/package.json
  pnpm-lock.yaml
Labels: size/s

#4770 fix(experience): invoke webauthn on iOS devices
  packages/experience/src/hooks/use-webauthn-operation.ts
  packages/integration-tests/src/tests/experience/mfa/backup-code/index.test.ts
  packages/integration-tests/src/tests/experience/mfa/webauthn/index.test.ts
  packages/integration-tests/src/ui-helpers/expect-webauthn-experience.ts
  packages/phrases-experience/src/locales/de/mfa.ts
  packages/phrases-experience/src/locales/en/mfa.ts
  packages/phrases-experience/src/locales/es/mfa.ts
  packages/phrases-experience/src/locales/fr/mfa.ts
  packages/phrases-experience/src/locales/it/mfa.ts
  packages/phrases-experience/src/locales/ja/mfa.ts
  packages/phrases-experience/src/locales/ko/mfa.ts
  packages/phrases-experience/src/locales/pl-pl/mfa.ts
  packages/phrases-experience/src/locales/pt-br/mfa.ts
  packages/phrases-experience/src/locales/pt-pt/mfa.ts
  packages/phrases-experience/src/locales/ru/mfa.ts
  packages/phrases-experience/src/locales/tr-tr/mfa.ts
  packages/phrases-experience/src/locales/zh-cn/mfa.ts
  packages/phrases-experience/src/locales/zh-hk/mfa.ts
  packages/phrases-experience/src/locales/zh-tw/mfa.ts
Labels: bugfix, size/m

#4749 chore(test): add delay to ensure the skip mfa request and sign-in redirection to be handled
  packages/integration-tests/src/tests/experience/mfa/user-controlled.test.ts
Labels: chore, size/xs

#4773 fix(console): button icon and text margin
  packages/console/src/ds-components/Button/index.module.scss
Labels: bugfix, size/xs

#4764 style(experience): update mfa-related styles
  packages/experience/src/components/Button/MfaFactorButton.module.scss
  packages/experience/src/components/NavBar/index.module.scss
Labels: size/s

#4769 style(console): update radio disabled styles
  packages/console/src/ds-components/RadioGroup/Radio.module.scss
  packages/console/src/pages/Mfa/MfaForm/index.tsx
  packages/integration-tests/src/tests/console/mfa/index.test.ts
Labels: size/s

#4771 refactor(experience): update webauthn error message
  packages/experience/src/hooks/use-webauthn-operation.ts
  packages/phrases-experience/src/locales/de/mfa.ts
  packages/phrases-experience/src/locales/en/mfa.ts
  packages/phrases-experience/src/locales/es/mfa.ts
  packages/phrases-experience/src/locales/fr/mfa.ts
  packages/phrases-experience/src/locales/it/mfa.ts
  packages/phrases-experience/src/locales/ja/mfa.ts
  packages/phrases-experience/src/locales/ko/mfa.ts
  packages/phrases-experience/src/locales/pl-pl/mfa.ts
  packages/phrases-experience/src/locales/pt-br/mfa.ts
  packages/phrases-experience/src/locales/pt-pt/mfa.ts
  packages/phrases-experience/src/locales/ru/mfa.ts
  packages/phrases-experience/src/locales/tr-tr/mfa.ts
  packages/phrases-experience/src/locales/zh-cn/mfa.ts
  packages/phrases-experience/src/locales/zh-hk/mfa.ts
  packages/phrases-experience/src/locales/zh-tw/mfa.ts
Labels: enhancement, size/s

#4774 refactor(experience): hide nav bar on backup code binding page
  packages/experience/src/Layout/SecondaryPageLayout/index.tsx
  packages/experience/src/components/NavBar/index.module.scss
  packages/experience/src/components/NavBar/index.tsx
  packages/experience/src/pages/MfaBinding/BackupCodeBinding/index.tsx
Labels: enhancement, size/s

#4754 refactor(core): add the isSupportedSsoConnector type assertion
  packages/core/src/__mocks__/sso.ts
  packages/core/src/libraries/sso-connector.test.ts
  packages/core/src/libraries/sso-connector.ts
  packages/core/src/routes/sso-connector/index.ts
  packages/core/src/routes/sso-connector/utils.test.ts
  packages/core/src/routes/sso-connector/utils.ts
  packages/core/src/sso/index.ts
  packages/core/src/sso/types/index.ts
  packages/core/src/sso/utils.test.ts
  packages/core/src/sso/utils.ts
  packages/core/src/tenants/Libraries.ts
Labels: enhancement, size/l

#4752 refactor(core): refactor the sso-connector config guard logic
  packages/core/src/__mocks__/sso.ts
  packages/core/src/libraries/sso-connector.test.ts
  packages/core/src/libraries/sso-connector.ts
  packages/core/src/routes/sso-connector/index.ts
  packages/core/src/routes/sso-connector/utils.test.ts
  packages/core/src/routes/sso-connector/utils.ts
  packages/core/src/sso/index.ts
  packages/core/src/sso/types/index.ts
  packages/core/src/sso/utils.test.ts
  packages/core/src/sso/utils.ts
  packages/core/src/tenants/Libraries.ts
  packages/integration-tests/src/tests/api/sso-connectors.test.ts
Labels: enhancement, size/l

#4751 fix(core): remove user verification requirement for webauthn
  packages/core/src/routes/interaction/utils/webauthn.ts
Labels: bugfix, size/xs

#4750 fix(core): fix mfa log type
  packages/core/src/routes/interaction/mfa.ts
Labels: bugfix, size/xs

#4776 fix(console): fix disable state of mfa policy options
  packages/console/src/pages/Mfa/MfaForm/index.tsx
Labels: bugfix, size/xs

#4753 fix(core): fix validateBindMfaBackupCode to force linking backup code
  packages/core/src/routes/interaction/verifications/mfa-verification.test.ts
  packages/core/src/routes/interaction/verifications/mfa-verification.ts
Labels: bugfix, size/s

#4756 fix(core): block the use of unavailable MFA
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/verifications/mfa-verification.backup-code.test.ts
  packages/core/src/routes/interaction/verifications/mfa-verification.test.ts
  packages/core/src/routes/interaction/verifications/mfa-verification.ts
Labels: bugfix, size/l

#4762 chore(test): init org ui tests
  packages/console/src/pages/Organizations/CreateOrganizationModal/index.tsx
  packages/console/src/pages/Organizations/PermissionModal/index.tsx
  packages/integration-tests/src/constants.ts
  packages/integration-tests/src/tests/console/organizations.test.ts
  packages/integration-tests/src/ui-helpers/expect-console.ts
  packages/integration-tests/src/ui-helpers/expect-organizations.ts
  packages/integration-tests/src/ui-helpers/expect-page.ts
Labels: chore, size/l

#4775 refactor(experience): use last used factor when verifing mfa factors
  packages/experience/src/hooks/use-mfa-error-handler.ts
  packages/integration-tests/src/tests/experience/mfa/backup-code/index.test.ts
  packages/integration-tests/src/tests/experience/mfa/multi-factors.test.ts
  packages/integration-tests/src/ui-helpers/expect-mfa-experience.ts
  packages/integration-tests/src/ui-helpers/expect-totp-experience.ts
  packages/integration-tests/src/ui-helpers/expect-webauthn-experience.ts
Labels: enhancement, size/s

#4778 refactor(experience): hide webauthn on native webview
  packages/experience/src/hooks/use-mfa-error-handler.ts
  packages/experience/src/hooks/use-webauthn-operation.ts
  packages/phrases-experience/src/locales/de/mfa.ts
  packages/phrases-experience/src/locales/en/mfa.ts
  packages/phrases-experience/src/locales/es/mfa.ts
  packages/phrases-experience/src/locales/fr/mfa.ts
  packages/phrases-experience/src/locales/it/mfa.ts
  packages/phrases-experience/src/locales/ja/mfa.ts
  packages/phrases-experience/src/locales/ko/mfa.ts
  packages/phrases-experience/src/locales/pl-pl/mfa.ts
  packages/phrases-experience/src/locales/pt-br/mfa.ts
  packages/phrases-experience/src/locales/pt-pt/mfa.ts
  packages/phrases-experience/src/locales/ru/mfa.ts
  packages/phrases-experience/src/locales/tr-tr/mfa.ts
  packages/phrases-experience/src/locales/zh-cn/mfa.ts
  packages/phrases-experience/src/locales/zh-hk/mfa.ts
  packages/phrases-experience/src/locales/zh-tw/mfa.ts
Labels: enhancement, size/s

#4772 refactor(console): improve org settings page
  packages/console/src/ds-components/Select/index.module.scss
  packages/console/src/pages/Organizations/RoleModal/index.tsx
  packages/console/src/pages/Organizations/TemplateTable/index.module.scss
  packages/console/src/pages/Organizations/TemplateTable/index.tsx
  packages/core/src/utils/SchemaRouter.ts
Labels: enhancement, size/s

#4638 feat(console): add support for searching in select component
  packages/console/src/ds-components/Select/index.module.scss
  packages/console/src/ds-components/Select/index.tsx
Labels: feature, size/m

#4765 feat(core,phrases): add mfa verifications by api
  packages/core/src/libraries/user.test.ts
  packages/core/src/libraries/user.ts
  packages/core/src/routes/admin-user/basics.test.ts
  packages/core/src/routes/admin-user/basics.ts
  packages/core/src/routes/admin-user/index.ts
  packages/core/src/routes/admin-user/mfa-verifications.test.ts
  packages/core/src/routes/admin-user/mfa-verifications.ts
  packages/integration-tests/src/api/admin-user.ts
  packages/integration-tests/src/tests/api/admin-user.mfa-verifications.test.ts
  packages/phrases/src/locales/de/errors/user.ts
  packages/phrases/src/locales/en/errors/user.ts
  packages/phrases/src/locales/es/errors/user.ts
  packages/phrases/src/locales/fr/errors/user.ts
  packages/phrases/src/locales/it/errors/user.ts
  packages/phrases/src/locales/ja/errors/user.ts
  packages/phrases/src/locales/ko/errors/user.ts
  packages/phrases/src/locales/pl-pl/errors/user.ts
  packages/phrases/src/locales/pt-br/errors/user.ts
  packages/phrases/src/locales/pt-pt/errors/user.ts
  packages/phrases/src/locales/ru/errors/user.ts
  packages/phrases/src/locales/tr-tr/errors/user.ts
  packages/phrases/src/locales/zh-cn/errors/user.ts
  packages/phrases/src/locales/zh-hk/errors/user.ts
  packages/phrases/src/locales/zh-tw/errors/user.ts
Labels: feature, size/xl

#4779 style(experience): add border radius for totp qr code
  packages/experience/src/pages/MfaBinding/TotpBinding/SecretSection/index.module.scss
Labels: size/xs

#4777 feat(core): add ssoConnectors to the sie well-known api
  packages/core/src/__mocks__/index.ts
  packages/core/src/libraries/sign-in-experience/index.test.ts
  packages/core/src/libraries/sign-in-experience/index.ts
  packages/core/src/libraries/sign-in-experience/types.ts
  packages/core/src/libraries/sso-connector.ts
  packages/core/src/routes/well-known.test.ts
  packages/core/src/tenants/Libraries.ts
  packages/integration-tests/src/tests/api/sso-connectors.test.ts
  packages/integration-tests/src/tests/api/well-known.test.ts
  packages/schemas/src/types/index.ts
  packages/schemas/src/types/sso-connector.ts
Labels: feature, size/m

#4782 refactor(experience): polish handle mfa redirection codes and add comments
  packages/experience/src/hooks/use-mfa-error-handler.ts
Labels: enhancement, size/s

#4780 feat(console): add organization creation guide
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/pages/Organizations/Guide/CreateOrganization/index.tsx
  packages/console/src/pages/Organizations/Guide/CreatePermissions/index.tsx
  packages/console/src/pages/Organizations/Guide/CreateRoles/index.tsx
  packages/console/src/pages/Organizations/Guide/DynamicFormFields/index.module.scss
  packages/console/src/pages/Organizations/Guide/DynamicFormFields/index.tsx
  packages/console/src/pages/Organizations/Guide/Step1/index.module.scss
  packages/console/src/pages/Organizations/Guide/Step1/index.tsx
  packages/console/src/pages/Organizations/Guide/const.ts
  packages/console/src/pages/Organizations/Guide/index.module.scss
  packages/console/src/pages/Organizations/Guide/index.tsx
  packages/console/src/pages/Organizations/PermissionModal/index.tsx
  packages/console/src/pages/Organizations/RoleModal/index.tsx
  packages/console/src/pages/Organizations/index.tsx
Labels: feature, size/xl

#4781 refactor(phrases): update mfa phrases
  packages/integration-tests/src/tests/experience/mfa/multi-factors.test.ts
  packages/integration-tests/src/ui-helpers/expect-mfa-experience.ts
  packages/phrases-experience/src/locales/de/mfa.ts
  packages/phrases-experience/src/locales/en/mfa.ts
  packages/phrases-experience/src/locales/es/mfa.ts
  packages/phrases-experience/src/locales/fr/mfa.ts
  packages/phrases-experience/src/locales/it/mfa.ts
  packages/phrases-experience/src/locales/ja/mfa.ts
  packages/phrases-experience/src/locales/ko/mfa.ts
  packages/phrases-experience/src/locales/pl-pl/mfa.ts
  packages/phrases-experience/src/locales/pt-br/mfa.ts
  packages/phrases-experience/src/locales/pt-pt/mfa.ts
  packages/phrases-experience/src/locales/ru/mfa.ts
  packages/phrases-experience/src/locales/tr-tr/mfa.ts
  packages/phrases-experience/src/locales/zh-cn/mfa.ts
  packages/phrases-experience/src/locales/zh-hk/mfa.ts
  packages/phrases-experience/src/locales/zh-tw/mfa.ts
  packages/phrases/src/locales/de/translation/admin-console/mfa.ts
  packages/phrases/src/locales/de/translation/admin-console/user-details.ts
  packages/phrases/src/locales/en/translation/admin-console/mfa.ts
  packages/phrases/src/locales/en/translation/admin-console/user-details.ts
  packages/phrases/src/locales/es/translation/admin-console/mfa.ts
  packages/phrases/src/locales/es/translation/admin-console/user-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/mfa.ts
  packages/phrases/src/locales/fr/translation/admin-console/user-details.ts
  packages/phrases/src/locales/it/translation/admin-console/mfa.ts
  packages/phrases/src/locales/it/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/mfa.ts
  packages/phrases/src/locales/ja/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/mfa.ts
  packages/phrases/src/locales/ko/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/mfa.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/mfa.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/mfa.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/mfa.ts
  packages/phrases/src/locales/ru/translation/admin-console/user-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/mfa.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/mfa.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/mfa.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/mfa.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/user-details.ts
Labels: enhancement, size/xl

#4660 feat(core): google cloud storage provider
  packages/core/package.json
  packages/core/src/utils/storage/google-storage.ts
  packages/core/src/utils/storage/index.ts
  packages/schemas/src/types/system.ts
  pnpm-lock.yaml
Labels: feature, size/s

#4727 fix(console,core,test): support filter by type for GET roles and apps APIs
  .changeset/sixty-ladybugs-exercise.md
  packages/console/src/components/RolesTransfer/components/SourceRolesBox/index.tsx
  packages/console/src/pages/Roles/components/AssignRoleModal/index.tsx
  packages/core/src/queries/application.ts
  packages/core/src/queries/roles.ts
  packages/core/src/routes/admin-user/role.ts
  packages/core/src/routes/application-role.ts
  packages/core/src/routes/application.ts
  packages/core/src/routes/role.ts
  packages/core/src/utils/search.ts
  packages/integration-tests/src/api/admin-user.ts
  packages/integration-tests/src/api/application.ts
  packages/integration-tests/src/api/role.ts
  packages/integration-tests/src/tests/api/admin-user.roles.test.ts
  packages/integration-tests/src/tests/api/application.roles.test.ts
  packages/integration-tests/src/tests/api/role.application.test.ts
  packages/integration-tests/src/tests/api/role.user.test.ts
  packages/integration-tests/src/tests/console/machine-to-machine-rbac/machime-to-machime-rbac.test.ts
  packages/integration-tests/src/tests/console/machine-to-machine-rbac/utils.ts
Labels: bugfix, size/xl

#4789 chore(test): temporarily skip organization console integration tests
  packages/integration-tests/src/tests/console/organizations.test.ts
Labels: chore, size/xs

#4783 fix(core): prompt to bind mfa for register
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/core/src/routes/interaction/types/guard.ts
  packages/core/src/routes/interaction/types/index.ts
  packages/core/src/routes/interaction/verifications/mfa-verification.test.ts
  packages/core/src/routes/interaction/verifications/mfa-verification.ts
Labels: bugfix, size/s

#4785 feat(console,schemas): add new db config to record organization creation status
  packages/console/src/pages/Organizations/Guide/CreateOrganization/index.tsx
  packages/console/src/pages/Organizations/index.tsx
  packages/core/src/__mocks__/index.ts
  packages/integration-tests/src/tests/api/logto-config.test.ts
  packages/schemas/alterations/next-1698646271-add-organization-created-flag.ts
  packages/schemas/src/seeds/logto-config.ts
  packages/schemas/src/types/logto-config.ts
Labels: feature, size/s

#4767 feat(core): add last use time to user mfa verifications
  packages/core/src/routes/interaction/mfa.test.ts
  packages/core/src/routes/interaction/mfa.ts
  packages/core/src/routes/interaction/verifications/mfa-payload-verification.test.ts
  packages/core/src/routes/interaction/verifications/mfa-payload-verification.ts
  packages/core/src/routes/interaction/verifications/mfa-verification.test.ts
  packages/core/src/routes/interaction/verifications/mfa-verification.ts
  packages/schemas/src/foundations/jsonb-types/users.ts
Labels: feature, size/m

#4793 style: update mfa-related styles
  packages/console/src/ds-components/Switch/index.module.scss
  packages/experience/src/pages/MfaBinding/BackupCodeBinding/index.module.scss
  packages/experience/src/pages/MfaBinding/TotpBinding/SecretSection/index.module.scss
  packages/experience/src/pages/MfaVerification/BackupCodeVerification/index.tsx
  packages/experience/src/scss/_colors.scss
  packages/toolkit/core-kit/scss/_console-themes.scss
Labels: size/s

#4787 feat(core): add post single-sign-on authentication endpoint
  packages/console/src/consts/logs.ts
  packages/core/src/routes/interaction/const.ts
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/single-sign-on.ts
  packages/core/src/routes/interaction/utils/social-verification.ts
  packages/integration-tests/src/api/interaction-sso.ts
  packages/integration-tests/src/api/interaction.ts
  packages/integration-tests/src/constants.ts
  packages/integration-tests/src/tests/api/interaction/single-sign-on/happy-path.test.ts
  packages/integration-tests/src/tests/api/interaction/single-sign-on/sad-path.test.ts
  packages/schemas/src/types/log/interaction.ts
Labels: feature, size/l
