Repository logto-io/logto, pull requests merged in 2023-12, with the labels that each got.

#5027 fix(experience): move the navigate method to useEffect
  packages/experience/src/pages/SingleSignOnConnectors/index.tsx
Labels: bugfix, size/s

#5022 chore(core): add custom-phrases api doc descriptions
  packages/core/src/routes/custom-phrases.openapi.json
Labels: chore, size/s

#5021 chore(core): add verficiation code api doc descriptions
  packages/core/src/routes/verification-code.openapi.json
Labels: chore, size/s

#5020 chore(core): add hooks api doc descriptions
  packages/core/src/routes/hooks.openapi.json
Labels: chore, size/m

#5031 fix(experience): fix silent error bug
  packages/experience/src/App.tsx
  packages/experience/src/hooks/use-check-single-sign-on.ts
  packages/experience/src/hooks/use-password-sign-in.ts
  packages/experience/src/pages/SingleSignOnEmail/index.tsx
Labels: bugfix, size/s

#5032 fix(core): should not guard email if SSO is disabled
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/utils/single-sign-on-guard.test.ts
  packages/core/src/routes/interaction/utils/single-sign-on-guard.ts
  packages/core/src/routes/interaction/verifications/identifier-payload-verification.test.ts
  packages/core/src/routes/interaction/verifications/identifier-payload-verification.ts
  packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.test.ts
  packages/integration-tests/src/tests/api/interaction/register-with-identifier/sad-path.test.ts
  packages/integration-tests/src/tests/api/interaction/register-with-identifier/single-sign-on.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-passcode-identifier/sad-path.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-passcode-identifier/single-sign-on.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier/happy-path.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier/sad-path.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier/single-sign-on.test.ts
Labels: bugfix, size/xl

#5024 feat(connector,console,core): add SSO paywall for core management APIs
  packages/connectors/connector-logto-email/package.json
  packages/console/package.json
  packages/core/package.json
  packages/core/src/libraries/quota.ts
  packages/core/src/routes/sso-connector/index.ts
  pnpm-lock.yaml
Labels: feature, size/s

#5018 chore(core): add well-known api doc descriptions
  packages/core/src/routes/well-known.openapi.json
Labels: chore, size/s

#5035 feat(console): update content
  packages/console/src/assets/docs/single-sign-on/AzureAD/README.mdx
  packages/console/src/assets/docs/single-sign-on/GoogleWorkspace/README.mdx
  packages/console/src/assets/docs/single-sign-on/OIDC/README.mdx
  packages/console/src/assets/docs/single-sign-on/OKTA/README.mdx
  packages/console/src/assets/docs/single-sign-on/SAML/README.mdx
Labels: feature, size/s

#5039 chore(core): add api docs
  packages/core/package.json
  packages/core/src/routes/admin-user/basic.openapi.json
  packages/core/src/routes/admin-user/mfa-verification.openapi.json
  packages/core/src/routes/admin-user/organization.openapi.json
  packages/core/src/routes/admin-user/role.openapi.json
  packages/core/src/routes/admin-user/search.openapi.json
  packages/core/src/routes/admin-user/social.openapi.json
  packages/core/src/routes/admin-user/social.ts
  packages/core/src/routes/application-role.openapi.json
  packages/core/src/routes/application.openapi.json
  packages/core/src/routes/hooks.openapi.json
  packages/core/src/routes/organization/index.openapi.json
  packages/core/src/routes/organization/roles.openapi.json
  packages/core/src/routes/organization/scopes.openapi.json
  packages/core/src/routes/resource.openapi.json
  packages/core/src/routes/role.openapi.json
  pnpm-lock.yaml
Labels: chore, size/xl

#5011 chore: upgrade logto sdks
  packages/console/package.json
  packages/demo-app/package.json
  packages/demo-app/src/App.tsx
  packages/integration-tests/package.json
  packages/integration-tests/src/client/storage.ts
  packages/integration-tests/src/tests/api/oidc/id-token.test.ts
  packages/integration-tests/src/tests/api/oidc/refresh-token-grant.test.ts
  pnpm-lock.yaml
Labels: chore, size/s

#5036 chore(core): add domains api doc descriptions
  packages/core/src/routes/domain.openapi.json
Labels: chore, size/s

#5037 chore(core): add dashboard api doc descriptions
  packages/core/src/routes/dashboard.openapi.json
Labels: chore, size/s

#5041 feat(core): add authn docs
  packages/core/src/routes/authn.openapi.json
Labels: feature, size/s

#5040 feat(core): add sso-connectors openapi file
  packages/core/src/routes/sso-connector/index.openapi.json
Labels: feature, size/s

#5033 chore(core): add logto-config api doc descriptions
  packages/core/src/routes/logto-config.openapi.json
  packages/core/src/routes/logto-config.ts
Labels: chore, size/m

#5034 chore(core): add logs api doc descriptions
  packages/core/src/routes/log.openapi.json
Labels: chore, size/s

#5042 chore(core): add connector api doc descriptions
  packages/core/src/routes/connector/authorization-uri.openapi.json
  packages/core/src/routes/connector/config-testing.openapi.json
  packages/core/src/routes/connector/config-testing.ts
  packages/core/src/routes/connector/factory.openapi.json
  packages/core/src/routes/connector/index.openapi.json
Labels: chore, size/l

#5050 fix(console): should block form submit when error in domain input field
  packages/console/src/pages/EnterpriseSsoDetails/Connection/OidcMetadataForm/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/Experience/DomainsInput/consts.ts
  packages/console/src/pages/EnterpriseSsoDetails/Experience/DomainsInput/index.module.scss
  packages/console/src/pages/EnterpriseSsoDetails/Experience/DomainsInput/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/Experience/DomainsInput/utils.ts
  packages/console/src/pages/EnterpriseSsoDetails/Experience/index.tsx
Labels: bugfix, size/m

#5046 chore(core): add api tags descriptions
  .changeset/calm-ladybugs-doubt.md
  packages/core/src/routes/admin-user/basic.openapi.json
  packages/core/src/routes/application.openapi.json
  packages/core/src/routes/authn.openapi.json
  packages/core/src/routes/custom-phrases.openapi.json
  packages/core/src/routes/dashboard.openapi.json
  packages/core/src/routes/hooks.openapi.json
  packages/core/src/routes/interaction/index.openapi.json
  packages/core/src/routes/logto-config.openapi.json
  packages/core/src/routes/organization/index.openapi.json
  packages/core/src/routes/organization/roles.openapi.json
  packages/core/src/routes/organization/scopes.openapi.json
  packages/core/src/routes/resource.openapi.json
  packages/core/src/routes/role.openapi.json
  packages/core/src/routes/sign-in-experience/index.openapi.json
  packages/core/src/routes/status.openapi.json
  packages/core/src/routes/swagger/index.openapi.json
  packages/core/src/routes/swagger/index.ts
  packages/core/src/routes/swagger/utils/general.ts
  packages/core/src/routes/swagger/utils/parameters.ts
  packages/core/src/routes/user-assets.openapi.json
  packages/core/src/routes/verification-code.openapi.json
Labels: chore, size/m

#5049 refactor(core): add user ip to webhook event payload
  .changeset/spotty-ants-clap.md
  packages/core/src/libraries/hook/index.ts
  packages/core/src/libraries/hook/utils.ts
  packages/core/src/routes/interaction/middleware/koa-interaction-hooks.ts
  packages/integration-tests/src/tests/api/hook/hook.trigger.test.ts
  packages/schemas/src/types/hook.ts
Labels: enhancement, feature, size/s

#5052 fix(experience): should not show error message on sign-in page
  packages/experience/src/hooks/use-check-single-sign-on.ts
Labels: bugfix, size/s

#5053 chore(console,core): show invalid SSO config/metadata error message inline
  packages/console/src/pages/EnterpriseSso/types.ts
  packages/console/src/pages/EnterpriseSsoDetails/Connection/index.tsx
  packages/core/package.json
  packages/core/src/sso/SamlConnector/index.ts
  packages/core/src/sso/types/error.ts
  pnpm-lock.yaml
Labels: chore, size/m

#5056 refactor(console): hide saml social connector entrance and fix SSO creation paywall
  packages/console/src/components/CreateConnectorForm/index.tsx
  packages/console/src/pages/EnterpriseSso/SsoCreationModal/index.tsx
  packages/console/src/pages/EnterpriseSso/index.tsx
  packages/integration-tests/src/tests/console/connectors/social-connector-test-cases.ts
Labels: enhancement, size/m

#5057 refactor(core): add base url to swagger json
  packages/core/src/routes/swagger/index.ts
Labels: enhancement, size/xs

#5060 refactor(console): rename the sso connector guide path
  packages/console/src/assets/docs/single-sign-on/azure-ad/README.mdx
  packages/console/src/assets/docs/single-sign-on/azure-ad/assets/assign_users.webp
  packages/console/src/assets/docs/single-sign-on/azure-ad/assets/create_application.webp
  packages/console/src/assets/docs/single-sign-on/azure-ad/assets/default_attribute_mapping.webp
  packages/console/src/assets/docs/single-sign-on/azure-ad/assets/logto_attribute_mapping.webp
  packages/console/src/assets/docs/single-sign-on/azure-ad/assets/metadata_url.webp
  packages/console/src/assets/docs/single-sign-on/azure-ad/assets/set_up_single_sign_on.webp
  packages/console/src/assets/docs/single-sign-on/azure-ad/assets/sp_config.webp
  packages/console/src/assets/docs/single-sign-on/google-workspace/README.mdx
  packages/console/src/assets/docs/single-sign-on/google-workspace/assets/client_credentials.webp
  packages/console/src/assets/docs/single-sign-on/google-workspace/assets/consent_screen_scopes.webp
  packages/console/src/assets/docs/single-sign-on/google-workspace/assets/consent_screen_settings.webp
  packages/console/src/assets/docs/single-sign-on/google-workspace/assets/consent_screen_user_type.webp
  packages/console/src/assets/docs/single-sign-on/google-workspace/assets/create_credentials.webp
  packages/console/src/assets/docs/single-sign-on/google-workspace/assets/credentials.webp
  packages/console/src/assets/docs/single-sign-on/google-workspace/assets/credentials_config.webp
  packages/console/src/assets/docs/single-sign-on/index.ts
  packages/console/src/assets/docs/single-sign-on/oidc/README.mdx
  packages/console/src/assets/docs/single-sign-on/okta/README.mdx
  packages/console/src/assets/docs/single-sign-on/okta/assets/application_settings.webp
  packages/console/src/assets/docs/single-sign-on/okta/assets/assign_users.webp
  packages/console/src/assets/docs/single-sign-on/okta/assets/client_credentials.webp
  packages/console/src/assets/docs/single-sign-on/okta/assets/create_application.webp
  packages/console/src/assets/docs/single-sign-on/saml/README.mdx
Labels: enhancement, size/s

#5061 feat: add sso changeset
  .changeset/friendly-adults-swim.md
Labels: feature, size/s

#5063 chore: add changeset
  .changeset/shy-kiwis-speak.md
Labels: chore, size/s

#5064 chore: split SSO changesets
  .changeset/bright-pumas-beam.md
  .changeset/brown-cheetahs-hide.md
  .changeset/cuddly-hornets-search.md
  .changeset/metal-walls-enjoy.md
  .changeset/thirty-bugs-hear.md
  .changeset/wise-birds-itch.md
Labels: chore, size/s

#5065 fix(core): fix SSO quota guard
  packages/core/src/routes/sso-connector/index.ts
Labels: bugfix, size/xs

#5066 fix: should hide upsell tag for standard connectors in OSS version
  .changeset/tame-crabs-breathe.md
  packages/console/src/components/CreateConnectorForm/index.tsx
Labels: bugfix, size/s

#5074 chore(core): increase sso oidc token iat tolerance
  packages/core/src/sso/OidcConnector/utils.ts
Labels: chore, size/xs

#5071 chore(core): rename SSO connectors management API routes
  packages/core/src/routes/sso-connector/index.ts
Labels: chore, size/xs

#5080 chore(shared): add JSDoc comments
  packages/shared/src/utils/ttl-cache.ts
Labels: chore, size/s

#5079 feat(schemas): add tenant role enum and scope enum
  .changeset/brave-hounds-clean.md
  packages/schemas/src/types/tenant.ts
Labels: feature, size/s

#5084 chore: use Node 20 LTS for engine requirement
  .changeset/smooth-worms-play.md
  package.json
  packages/app-insights/package.json
  packages/cli/package.json
  packages/connectors/connector-alipay-native/package.json
  packages/connectors/connector-alipay-web/package.json
  packages/connectors/connector-aliyun-dm/package.json
  packages/connectors/connector-aliyun-sms/package.json
  packages/connectors/connector-apple/package.json
  packages/connectors/connector-aws-ses/package.json
  packages/connectors/connector-azuread/package.json
  packages/connectors/connector-discord/package.json
  packages/connectors/connector-facebook/package.json
  packages/connectors/connector-feishu-web/package.json
  packages/connectors/connector-github/package.json
  packages/connectors/connector-google/package.json
  packages/connectors/connector-kakao/package.json
  packages/connectors/connector-logto-email/package.json
  packages/connectors/connector-logto-sms/package.json
  packages/connectors/connector-logto-social-demo/package.json
  packages/connectors/connector-mailgun/package.json
  packages/connectors/connector-mock-email-alternative/package.json
  packages/connectors/connector-mock-email/package.json
  packages/connectors/connector-mock-sms/package.json
  packages/connectors/connector-mock-social/package.json
  packages/connectors/connector-naver/package.json
  packages/connectors/connector-oauth2/package.json
  packages/connectors/connector-oidc/package.json
  packages/connectors/connector-saml/package.json
  packages/connectors/connector-sendgrid-email/package.json
  packages/connectors/connector-smsaero/package.json
  packages/connectors/connector-smtp/package.json
  packages/connectors/connector-tencent-sms/package.json
  packages/connectors/connector-twilio-sms/package.json
  packages/connectors/connector-wechat-native/package.json
  packages/connectors/connector-wechat-web/package.json
  packages/connectors/templates/package.json
  packages/console/package.json
  packages/core/package.json
  packages/create/package.json
  packages/demo-app/package.json
  packages/experience/package.json
  packages/integration-tests/package.json
  packages/phrases-experience/package.json
  packages/phrases/package.json
  packages/schemas/package.json
  packages/shared/package.json
  packages/toolkit/connector-kit/package.json
  packages/toolkit/core-kit/package.json
  packages/toolkit/language-kit/package.json
  pnpm-lock.yaml
Labels: chore, size/m

#5086 fix(console): user identities table should not always be loading when no data
  packages/console/src/pages/UserDetails/UserSettings/components/UserSocialIdentities/index.tsx
Labels: bugfix, size/xs

#5081 fix(console,test): should clear error message and add console integration test
  packages/console/src/pages/EnterpriseSsoDetails/Experience/DomainsInput/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/Experience/index.tsx
  packages/integration-tests/src/tests/console/sso-connectors/sso-connectors.test.ts
Labels: bugfix, size/m

#5087 fix(console): discard application settings changes when switching tabs
  packages/console/src/components/UnsavedChangesAlertModal/index.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
Labels: bugfix, size/s

#5091 refactor(core): group the application routes under applications directory
  packages/core/src/routes/applications/application-role.openapi.json
  packages/core/src/routes/applications/application-role.test.ts
  packages/core/src/routes/applications/application-role.ts
  packages/core/src/routes/applications/application.openapi.json
  packages/core/src/routes/applications/application.test.ts
  packages/core/src/routes/applications/application.ts
  packages/core/src/routes/applications/types.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/role.application.ts
  packages/schemas/src/types/application.ts
Labels: enhancement, size/s

#5090 feat(core,schemas): add isThirdParty column to the applications table
  packages/core/src/__mocks__/index.ts
  packages/core/src/routes/applications/application-role.openapi.json
  packages/core/src/routes/applications/application-role.test.ts
  packages/core/src/routes/applications/application-role.ts
  packages/core/src/routes/applications/application.openapi.json
  packages/core/src/routes/applications/application.test.ts
  packages/core/src/routes/applications/application.ts
  packages/core/src/routes/applications/types.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/role.application.ts
  packages/schemas/alterations/next-1702274830-add-new-third-party-column-to-applications-table.ts
  packages/schemas/src/seeds/application.ts
  packages/schemas/src/types/application.ts
  packages/schemas/tables/applications.sql
Labels: feature, size/m

#5096 feat(core,phrases): update applications api to support third-party app
  packages/core/src/queries/application.test.ts
  packages/core/src/queries/application.ts
  packages/core/src/routes/applications/application.ts
  packages/core/src/routes/applications/types.ts
  packages/integration-tests/src/api/application.ts
  packages/integration-tests/src/tests/api/application.test.ts
  packages/phrases/src/locales/de/errors/application.ts
  packages/phrases/src/locales/en/errors/application.ts
  packages/phrases/src/locales/es/errors/application.ts
  packages/phrases/src/locales/fr/errors/application.ts
  packages/phrases/src/locales/it/errors/application.ts
  packages/phrases/src/locales/ja/errors/application.ts
  packages/phrases/src/locales/ko/errors/application.ts
  packages/phrases/src/locales/pl-pl/errors/application.ts
  packages/phrases/src/locales/pt-br/errors/application.ts
  packages/phrases/src/locales/pt-pt/errors/application.ts
  packages/phrases/src/locales/ru/errors/application.ts
  packages/phrases/src/locales/tr-tr/errors/application.ts
  packages/phrases/src/locales/zh-cn/errors/application.ts
  packages/phrases/src/locales/zh-hk/errors/application.ts
  packages/phrases/src/locales/zh-tw/errors/application.ts
Labels: feature, size/m

#4977 refactor(core,console,shared): use getUserDisplayName function
  packages/console/src/components/ConnectorTester/index.tsx
  packages/console/src/components/UserAvatar/index.tsx
  packages/console/src/pages/UserDetails/UserSettings/index.tsx
  packages/console/src/pages/UserDetails/utils.ts
  packages/console/src/pages/Users/components/CreateForm/index.tsx
  packages/console/src/utils/user.ts
  packages/core/src/routes/admin-user/mfa-verifications.ts
  packages/core/src/routes/interaction/additional.ts
  packages/core/src/routes/interaction/utils/webauthn.ts
  packages/shared/package.json
  packages/shared/src/utils/index.ts
  packages/shared/src/utils/phone.ts
  packages/shared/src/utils/user-display-name.ts
  pnpm-lock.yaml
Labels: enhancement, size/s

#5100 refactor(core): add on conflic ignore to the Relation insert query method
  .changeset/chilly-bobcats-doubt.md
  packages/core/src/routes/organization/index.openapi.json
  packages/core/src/routes/organization/roles.openapi.json
  packages/core/src/utils/RelationQueries.ts
  packages/integration-tests/src/tests/api/organization-role.test.ts
Labels: enhancement, size/s

#5102 feat(phrases): add phrases for pricing v2
  packages/console/src/pages/Applications/components/CreateForm/Footer/index.tsx
  packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/de/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/de/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/en/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/en/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/es/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/es/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/fr/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/it/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/it/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ja/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ko/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ru/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/upsell/paywall.ts
Labels: feature, size/xl

#5097 feat(schemas): add application permissions relation tables
  packages/schemas/alterations/next-1702372401-add-application-permissions-tables.ts
  packages/schemas/tables/application_user_consent_organization_scopes.sql
  packages/schemas/tables/application_user_consent_resource_scopes.sql
  packages/schemas/tables/application_user_consent_user_scopes.sql
Labels: feature, size/m

#5104 feat(cli): add option to seed test data
  packages/cli/src/commands/database/seed/index.ts
  packages/cli/src/commands/database/seed/tables.ts
Labels: feature, size/s

#5101 feat(core,phrases): add post application user consent scopes api
  .vscode/settings.json
  packages/core/src/database/find-entity-by-id.ts
  packages/core/src/libraries/application.ts
  packages/core/src/queries/application-user-consent-scopes.ts
  packages/core/src/queries/application.ts
  packages/core/src/routes/applications/application-user-consent-scope.openapi.json
  packages/core/src/routes/applications/application-user-consent-scope.ts
  packages/core/src/routes/init.ts
  packages/core/src/utils/SchemaQueries.ts
  packages/integration-tests/package.json
  packages/integration-tests/src/api/application-user-consent-scope.ts
  packages/integration-tests/src/tests/api/application-user-consent-scope.test.ts
  packages/phrases/src/locales/de/errors/application.ts
  packages/phrases/src/locales/en/errors/application.ts
  packages/phrases/src/locales/es/errors/application.ts
  packages/phrases/src/locales/fr/errors/application.ts
  packages/phrases/src/locales/it/errors/application.ts
  packages/phrases/src/locales/ja/errors/application.ts
  packages/phrases/src/locales/ko/errors/application.ts
  packages/phrases/src/locales/pl-pl/errors/application.ts
  packages/phrases/src/locales/pt-br/errors/application.ts
  packages/phrases/src/locales/pt-pt/errors/application.ts
  packages/phrases/src/locales/ru/errors/application.ts
  packages/phrases/src/locales/tr-tr/errors/application.ts
  packages/phrases/src/locales/zh-cn/errors/application.ts
  packages/phrases/src/locales/zh-hk/errors/application.ts
  packages/phrases/src/locales/zh-tw/errors/application.ts
  pnpm-lock.yaml
Labels: feature, size/l

#5103 feat(core,schemas): add GET application user consent scopes api
  packages/core/src/libraries/application.ts
  packages/core/src/queries/application-user-consent-scopes.ts
  packages/core/src/routes/applications/application-user-consent-scope.openapi.json
  packages/core/src/routes/applications/application-user-consent-scope.ts
  packages/core/src/utils/RelationQueries.ts
  packages/integration-tests/src/api/application-user-consent-scope.ts
  packages/integration-tests/src/tests/api/application-user-consent-scope.test.ts
  packages/schemas/src/types/application.ts
Labels: feature, size/m

#5115 refactor(console): update plan comparison table
  packages/console/src/consts/env.ts
  packages/console/src/consts/plan-quotas.ts
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/PlanQuotaGroupKeyLabel/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/PlanQuotaKeyLabel/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/index.module.scss
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/renderers/BasePrice.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/renderers/GenericFeatureFlag.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/renderers/GenericQuotaLimit.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/renderers/MauUnitPrices.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/renderers/QuotaValueWrapper/index.module.scss
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/renderers/QuotaValueWrapper/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/renderers/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/utils.ts
  packages/console/src/pages/TenantSettings/Subscription/PlanQuotaTable/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/index.tsx
  packages/console/src/types/subscriptions.ts
Labels: enhancement, size/xl

#5116 feat(console): add org feature items for comparison table
  packages/console/src/consts/plan-quotas.ts
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/PlanQuotaKeyLabel/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/renderers/MauUnitPrices.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/renderers/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/utils.ts
  packages/console/src/types/subscriptions.ts
Labels: feature, size/s

#5117 refactor(console): update usage-based beta features tip for org feature
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/renderers/GenericFeatureFlag.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/renderers/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-table.ts
Labels: enhancement, size/s

#5119 fix(console): hide feature tag when standard connectors is unlimited
  packages/console/src/components/CreateConnectorForm/index.tsx
Labels: bugfix, size/xs

#5112 feat(schemas): add new application type for protected app
  packages/console/src/components/Guide/hooks.ts
  packages/console/src/consts/applications.ts
  packages/console/src/types/applications.ts
  packages/core/src/routes/applications/types.ts
  packages/phrases/src/locales/de/translation/admin-console/guide.ts
  packages/phrases/src/locales/en/translation/admin-console/guide.ts
  packages/phrases/src/locales/es/translation/admin-console/guide.ts
  packages/phrases/src/locales/fr/translation/admin-console/guide.ts
  packages/phrases/src/locales/it/translation/admin-console/guide.ts
  packages/phrases/src/locales/ja/translation/admin-console/guide.ts
  packages/phrases/src/locales/ko/translation/admin-console/guide.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/guide.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/guide.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/guide.ts
  packages/phrases/src/locales/ru/translation/admin-console/guide.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/guide.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/guide.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/guide.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/guide.ts
  packages/schemas/alterations/next-1702871078-protected-application-type.ts
  packages/schemas/tables/applications.sql
Labels: feature, size/s

#5113 feat(schemas): add column protected_app_metadata
  packages/core/src/__mocks__/index.ts
  packages/core/src/routes/applications/types.ts
  packages/schemas/alterations/next-1702877515-protected-app-configs.ts
  packages/schemas/src/foundations/jsonb-types/applications.ts
  packages/schemas/src/foundations/jsonb-types/index.ts
  packages/schemas/src/seeds/application.ts
  packages/schemas/tables/applications.sql
Labels: feature, size/s

#5123 feat(core,connector): update koaQuotaGuard to fit new pricing model
  packages/connectors/connector-logto-email/package.json
  packages/core/package.json
  packages/core/src/libraries/quota.ts
  packages/core/src/routes/applications/application.ts
  packages/core/src/routes/connector/index.ts
  packages/core/src/routes/role.ts
  packages/core/src/utils/subscription/types.ts
  pnpm-lock.yaml
Labels: feature, size/s

#5088 chore(test): add test cases for testing config on SSO details page experience tab
  packages/integration-tests/src/tests/console/sso-connectors/sso-connectors.test.ts
Labels: chore, size/s

#5105 refactor(schemas,core,cli): init tenant organizations
  .github/workflows/alteration-compatibility-integration-test.yml
  .github/workflows/main.yml
  .scripts/compare-database.js
  packages/cli/src/commands/database/seed/index.ts
  packages/cli/src/commands/database/seed/tables.ts
  packages/cli/src/commands/database/seed/tenant-organizations.ts
  packages/cli/src/database.ts
  packages/schemas/alterations/next-1702544178-sync-tenant-orgs.ts
  packages/schemas/src/seeds/application.ts
  packages/schemas/src/types/index.ts
  packages/schemas/src/types/mapi-proxy.ts
  packages/schemas/src/types/tenant-organization.ts
  packages/schemas/src/types/tenant.ts
Labels: enhancement, size/xl

#5110 refactor(console): use organization token for management api
  packages/console/src/App.tsx
  packages/console/src/containers/TenantAccess/index.tsx
  packages/console/src/contexts/TenantsProvider.tsx
  packages/console/src/hooks/use-api.ts
Labels: enhancement, size/m

#5127 refactor(core): create tenant organization for first admin
  packages/core/src/routes/interaction/actions/submit-interaction.ts
Labels: enhancement, size/s

#5120 feat(core,schemas): add application user consent scope delete api
  packages/core/src/libraries/application.ts
  packages/core/src/queries/application-user-consent-scopes.ts
  packages/core/src/routes/applications/application-user-consent-scope.openapi.json
  packages/core/src/routes/applications/application-user-consent-scope.ts
  packages/integration-tests/src/api/application-user-consent-scope.ts
  packages/integration-tests/src/tests/api/application-user-consent-scope.test.ts
  packages/schemas/src/types/application.ts
Labels: feature, size/m

#5069 fix(connector): update connector readme images URL
  packages/connectors/connector-alipay-native/README.md
  packages/connectors/connector-apple/README.md
  packages/connectors/connector-wechat-native/README.md
  packages/connectors/connector-wechat-web/README.md
Labels: bugfix, size/s

#5121 refactor(console): update upsell instruction for m2m app & resource creation
  packages/console/src/components/QuotaGuardFooter/index.tsx
  packages/console/src/hooks/use-api-resources-usage.ts
  packages/console/src/hooks/use-applications-usage.ts
  packages/console/src/hooks/use-subscribe.ts
  packages/console/src/pages/ApiResources/components/CreateForm/Footer.tsx
  packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
  packages/console/src/pages/Applications/components/CreateForm/Footer/index.tsx
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
Labels: enhancement, size/l

#5126 refactor(console): treat hobby plan as the new pro plan
  packages/console/src/components/CreateConnectorForm/index.tsx
  packages/console/src/components/CreateTenantModal/EnvTagOptionContent/index.tsx
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/index.tsx
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/index.tsx
  packages/console/src/components/Guide/GuideCard/index.tsx
  packages/console/src/components/PlanDescription/index.tsx
  packages/console/src/components/PlanName/index.tsx
  packages/console/src/consts/subscriptions.ts
  packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
  packages/console/src/pages/Applications/components/TypeDescription/index.tsx
  packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/MauLimitExceededNotification/index.tsx
Labels: enhancement, size/s

#5125 feat(console): add charge notification for add-on features
  packages/console/src/components/ChargeNotification/index.tsx
  packages/console/src/components/ListPage/index.tsx
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/Applications/index.module.scss
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/Connectors/SignInExperienceSetupNotice/index.module.scss
  packages/console/src/pages/Connectors/SignInExperienceSetupNotice/index.tsx
  packages/console/src/scss/page-layout.module.scss
  packages/phrases/src/locales/de/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/en/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/es/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/it/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/upsell/index.ts
Labels: feature, size/m

#5128 refactor(console): add new quota items for subscription plan
  packages/console/package.json
  packages/console/src/consts/plan-quotas.ts
  packages/console/src/consts/quota-item-phrases.ts
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/PlanQuotaKeyLabel/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/renderers/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/utils.ts
  packages/console/src/types/subscriptions.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-table.ts
  pnpm-lock.yaml
Labels: enhancement, size/l

#5131 refactor(console): add machine-to-machine roles limit guard
  packages/console/src/pages/Roles/components/CreateRoleForm/Footer.tsx
  packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
  packages/console/src/pages/Roles/components/CreateRoleModal/index.tsx
  packages/console/src/pages/Roles/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/en/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/es/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/fr/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/it/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/ja/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/ko/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/ru/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/upsell/paywall.ts
Labels: enhancement, size/l

#5122 feat(schemas): add application sign-in-experience table
  packages/schemas/alterations/next-1702978120-application-sign-in-experience-table.ts
  packages/schemas/tables/application_sign_in_experiences.sql
Labels: feature, size/s

#5129 feat(core,schemas,phrases): add application sign-in-experience apis
  packages/core/src/libraries/application.ts
  packages/core/src/queries/application-sign-in-experience.ts
  packages/core/src/routes/applications/application-sign-in-experience.openapi.json
  packages/core/src/routes/applications/application-sign-in-experience.ts
  packages/core/src/routes/init.ts
  packages/core/src/tenants/Queries.ts
  packages/integration-tests/src/api/application-sign-in-experience.ts
  packages/integration-tests/src/tests/api/application/application-sign-in-experience.test.ts
  packages/integration-tests/src/tests/api/application/application-user-consent-scope.test.ts
  packages/integration-tests/src/tests/api/application/application.roles.test.ts
  packages/integration-tests/src/tests/api/application/application.test.ts
  packages/integration-tests/src/tests/api/organization/organization-role.test.ts
  packages/integration-tests/src/tests/api/organization/organization-scope.test.ts
  packages/integration-tests/src/tests/api/organization/organization-user.test.ts
  packages/integration-tests/src/tests/api/organization/organization.test.ts
  packages/phrases/src/locales/de/errors/application.ts
  packages/phrases/src/locales/en/errors/application.ts
  packages/phrases/src/locales/es/errors/application.ts
  packages/phrases/src/locales/fr/errors/application.ts
  packages/phrases/src/locales/it/errors/application.ts
  packages/phrases/src/locales/ja/errors/application.ts
  packages/phrases/src/locales/ko/errors/application.ts
  packages/phrases/src/locales/pl-pl/errors/application.ts
  packages/phrases/src/locales/pt-br/errors/application.ts
  packages/phrases/src/locales/pt-pt/errors/application.ts
  packages/phrases/src/locales/ru/errors/application.ts
  packages/phrases/src/locales/tr-tr/errors/application.ts
  packages/phrases/src/locales/zh-cn/errors/application.ts
  packages/phrases/src/locales/zh-hk/errors/application.ts
  packages/phrases/src/locales/zh-tw/errors/application.ts
  packages/schemas/src/types/application.ts
Labels: feature, size/l

#5134 fix(console): hide new protected app type in console guide
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
Labels: bugfix, size/s

#5136 refactor(console): update feature tag in card titles
  packages/console/src/components/Guide/GuideCard/index.tsx
  packages/console/src/pages/EnterpriseSso/index.tsx
  packages/console/src/pages/Mfa/PageWrapper/index.tsx
  packages/console/src/pages/Organizations/index.tsx
Labels: enhancement, size/s

#5137 refactor(console): navigate to plan & billing page on paywall button clicked
  packages/console/src/pages/ApiResources/components/CreateForm/Footer.tsx
  packages/console/src/pages/Applications/components/CreateForm/Footer/index.tsx
Labels: enhancement, size/s

#5133 fix(core): remove the COOP policy
  packages/core/src/middleware/koa-security-headers.ts
Labels: bugfix, size/xs

#5141 chore(deps): upgrade TypeScript
  .changeset/old-turkeys-beg.md
  packages/app-insights/package.json
  packages/cli/package.json
  packages/connectors/templates/package.json
  packages/connectors/templates/preset/tsconfig.base.json
  packages/console/package.json
  packages/console/src/consts/env.ts
  packages/console/tsconfig.json
  packages/core/package.json
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/demo-app/package.json
  packages/experience/package.json
  packages/experience/src/constants/env.ts
  packages/experience/tsconfig.json
  packages/integration-tests/package.json
  packages/phrases-experience/package.json
  packages/phrases/package.json
  packages/schemas/package.json
  packages/shared/package.json
  packages/toolkit/connector-kit/package.json
  packages/toolkit/core-kit/package.json
  packages/toolkit/core-kit/src/password-policy.ts
  packages/toolkit/language-kit/package.json
  pnpm-lock.yaml
Labels: chore, size/m

#5139 chore: update README.md
  README.md
Labels: chore, size/s

#5143 refactor(console): update plan comparison table
  packages/console/src/consts/plan-quotas.ts
Labels: enhancement, size/xs

#5146 refactor(console,phrases): update charge notification for add-on features
  packages/console/src/components/ChargeNotification/index.tsx
  packages/console/src/components/CreateConnectorForm/Footer/index.tsx
  packages/console/src/hooks/use-api-resources-usage.ts
  packages/console/src/hooks/use-applications-usage.ts
  packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/RoleDetails/RolePermissions/components/AssignPermissionsModal/index.tsx
  packages/console/src/pages/Roles/components/CreateRoleForm/Footer.tsx
  packages/console/src/pages/Webhooks/CreateFormModal/CreateForm.tsx
  packages/console/src/utils/quota.ts
  packages/phrases/src/locales/de/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/en/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/es/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/it/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/upsell/index.ts
Labels: enhancement, size/xl

#5142 refactor(phrases): update quota item phrases
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-item.ts
Labels: enhancement, size/s

#5148 feat(core,schemas): add daily token usage table to ease the usage calculation
  packages/core/src/event-listeners/access-token.test.ts
  packages/core/src/event-listeners/index.ts
  packages/core/src/event-listeners/record-active-users.test.ts
  packages/core/src/event-listeners/record-active-users.ts
  packages/core/src/oidc/utils.ts
  packages/core/src/queries/daily-token-usage.ts
  packages/core/src/tenants/Queries.ts
  packages/schemas/alterations/next-1703229996-daily-token-usage.ts
  packages/schemas/tables/daily_token_usage.sql
Labels: feature, size/m

#5147 refactor(console): update featured plan quota list
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/FeaturedPlanQuotaList/FeaturedQuotaItem/index.module.scss
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/FeaturedPlanQuotaList/FeaturedQuotaItem/index.tsx
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/FeaturedPlanQuotaList/index.module.scss
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/FeaturedPlanQuotaList/index.tsx
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/index.tsx
  packages/console/src/components/PlanQuotaList/QuotaItem/index.module.scss
  packages/console/src/components/PlanQuotaList/QuotaItem/index.tsx
  packages/console/src/components/PlanQuotaList/QuotaListItem/QuotaItemPhrase.tsx
  packages/console/src/components/PlanQuotaList/QuotaListItem/index.module.scss
  packages/console/src/components/PlanQuotaList/QuotaListItem/index.tsx
  packages/console/src/components/PlanQuotaList/index.module.scss
  packages/console/src/components/PlanQuotaList/index.tsx
  packages/console/src/consts/quota-item-phrases.ts
  packages/console/src/pages/TenantSettings/Subscription/DowngradeConfirmModalContent/PlanQuotaDiffCard/DiffQuotaItem/index.module.scss
  packages/console/src/pages/TenantSettings/Subscription/DowngradeConfirmModalContent/PlanQuotaDiffCard/DiffQuotaItem/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/DowngradeConfirmModalContent/PlanQuotaDiffCard/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/DowngradeConfirmModalContent/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-item.ts
Labels: enhancement, size/xl

#5150 refactor(console): guard charge notification directly in the cloud version
  packages/console/src/components/ChargeNotification/index.tsx
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/Applications/index.tsx
Labels: enhancement, size/s

#5114 feat(core): route for add protected application
  packages/core/src/routes/applications/application.test.ts
  packages/core/src/routes/applications/application.ts
  packages/core/src/routes/applications/constants.ts
  packages/core/src/routes/applications/types.ts
  packages/core/src/routes/applications/utils.ts
  packages/integration-tests/src/tests/api/application/application.test.ts
  packages/integration-tests/src/tests/console/applications/index.test.ts
  packages/phrases/src/locales/de/errors/application.ts
  packages/phrases/src/locales/en/errors/application.ts
  packages/phrases/src/locales/es/errors/application.ts
  packages/phrases/src/locales/fr/errors/application.ts
  packages/phrases/src/locales/it/errors/application.ts
  packages/phrases/src/locales/ja/errors/application.ts
  packages/phrases/src/locales/ko/errors/application.ts
  packages/phrases/src/locales/pl-pl/errors/application.ts
  packages/phrases/src/locales/pt-br/errors/application.ts
  packages/phrases/src/locales/pt-pt/errors/application.ts
  packages/phrases/src/locales/ru/errors/application.ts
  packages/phrases/src/locales/tr-tr/errors/application.ts
  packages/phrases/src/locales/zh-cn/errors/application.ts
  packages/phrases/src/locales/zh-hk/errors/application.ts
  packages/phrases/src/locales/zh-tw/errors/application.ts
Labels: feature, size/m

#5152 refactor(cli): update node version check
  .github/workflows/alteration-compatibility-integration-test.yml
  .github/workflows/integration-test.yml
  packages/cli/src/commands/install/utils.ts
Labels: enhancement, size/s

#5151 feat(console,core): support hidding charge notification on read
  packages/console/src/components/ChargeNotification/index.tsx
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/schemas/src/types/logto-config.ts
Labels: feature, size/s

#5153 feat(console): add charge notification for token usage
  packages/console/package.json
  packages/console/src/contexts/TenantsProvider.tsx
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/index.tsx
  packages/schemas/src/types/logto-config.ts
  pnpm-lock.yaml
Labels: feature, size/s

#5154 fix(console): correct surpass limitation check for m2m apps
  packages/console/src/hooks/use-applications-usage.ts
Labels: bugfix, size/xs

#5155 refactor(console): hide charge notification when loading
  packages/console/src/components/ChargeNotification/index.tsx
Labels: enhancement, size/s

#5156 feat(console): add new support items for plan comparison table
  packages/console/src/consts/plan-quotas.ts
  packages/console/src/consts/quota-item-phrases.ts
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/PlanQuotaKeyLabel/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/renderers/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/utils.ts
  packages/console/src/types/subscriptions.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-table.ts
Labels: feature, size/l

#5145 refactor: remove tenant owner role
  packages/cli/src/commands/database/seed/tables.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/schemas/alterations/next-1703152016-update-tenant-roles.ts
  packages/schemas/src/types/tenant-organization.ts
Labels: enhancement, size/m

#5161 feat(console): add next server actions guide
  packages/console/src/assets/docs/guides/index.ts
  packages/console/src/assets/docs/guides/web-next-server-actions/README.mdx
  packages/console/src/assets/docs/guides/web-next-server-actions/config.json
  packages/console/src/assets/docs/guides/web-next-server-actions/index.ts
  packages/console/src/assets/docs/guides/web-next-server-actions/logo.svg
  packages/console/src/assets/docs/guides/web-next/config.json
Labels: feature, size/l

#5165 refactor(console): apply new plans blog link for charge notifications
  packages/console/src/components/ChargeNotification/index.tsx
  packages/console/src/consts/external-links.ts
Labels: enhancement, size/xs

#5162 fix(schemas): update alteration script timestamp
  packages/schemas/alterations/next-1703230000-update-tenant-roles.ts
Labels: bugfix, size/xs

#5169 fix(console): update price calculation blog link
  packages/console/src/components/BillInfo/index.tsx
Labels: bugfix, size/xs

#5171 refactor(console): sign out user when insufficient permissions
  packages/console/src/hooks/use-api.ts
Labels: enhancement, size/s

#5173 chore(phrases): translate new pricing phrases
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/de/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/es/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/fr/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/it/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ja/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ko/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ru/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/upsell/index.ts
Labels: chore, size/xl

#5174 chore(core): resolve legacy unit tests comments and refactor
  packages/core/src/routes/interaction/additional.test.ts
  packages/core/src/routes/interaction/index.test.ts
Labels: chore, size/s

#5170 feat(core): case insensitive usernames
  .changeset/fresh-lies-breathe.md
  packages/core/src/queries/user.test.ts
  packages/core/src/queries/user.ts
  packages/shared/src/node/env/GlobalValues.ts
Labels: feature, size/s

#5172 refactor(console): support `isFullWidth` for `CopyToClipboard` component
  packages/console/src/ds-components/CopyToClipboard/index.module.scss
  packages/console/src/ds-components/CopyToClipboard/index.tsx
  packages/console/src/mdx-components/ApplicationCredentials/index.module.scss
  packages/console/src/mdx-components/ApplicationCredentials/index.tsx
  packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx
  packages/console/src/pages/ApplicationDetails/components/Settings.tsx
  packages/console/src/pages/ApplicationDetails/index.module.scss
  packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/index.module.scss
  packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/index.tsx
  packages/console/src/scss/_dimensions.scss
Labels: enhancement, size/s

#5181 refactor(console): update plan comparison data and styles
  packages/console/src/consts/plan-quotas.ts
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/PlanQuotaKeyLabel/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/components/TableDataWrapper/index.module.scss
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/components/TableDataWrapper/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/index.module.scss
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/renderers/BasePrice.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/renderers/GenericFeatureFlag.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/renderers/GenericQuotaLimit.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/renderers/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-table.ts
Labels: enhancement, size/l
