Repository logto-io/logto, pull requests merged in 2024-01, with the labels that each got.

#5185 refactor(console): add subscription data provider
  packages/console/src/components/ChargeNotification/index.tsx
  packages/console/src/components/CreateConnectorForm/Footer/index.tsx
  packages/console/src/components/CreateConnectorForm/index.tsx
  packages/console/src/components/MauExceededModal/index.tsx
  packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx
  packages/console/src/consts/tenants.ts
  packages/console/src/containers/AppContent/index.tsx
  packages/console/src/contexts/SubscriptionDataProvider/index.tsx
  packages/console/src/contexts/SubscriptionDataProvider/types.ts
  packages/console/src/contexts/SubscriptionDataProvider/use-subscription-data.ts
  packages/console/src/contexts/TenantsProvider.tsx
  packages/console/src/ds-components/CardTitle/index.tsx
  packages/console/src/hooks/use-api-resources-usage.ts
  packages/console/src/hooks/use-applications-usage.ts
  packages/console/src/hooks/use-subscription-plan.ts
  packages/console/src/hooks/use-subscription-plans.ts
  packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx
  packages/console/src/pages/ApiResources/components/CreateForm/Footer.tsx
  packages/console/src/pages/Applications/components/CreateForm/Footer/index.tsx
  packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
  packages/console/src/pages/Applications/components/TypeDescription/index.tsx
  packages/console/src/pages/EnterpriseSso/SsoCreationModal/index.tsx
  packages/console/src/pages/EnterpriseSso/index.tsx
  packages/console/src/pages/Mfa/MfaForm/index.tsx
  packages/console/src/pages/Mfa/PageWrapper/index.tsx
  packages/console/src/pages/Organizations/CreateOrganizationModal/index.tsx
  packages/console/src/pages/Organizations/index.tsx
  packages/console/src/pages/RoleDetails/RolePermissions/components/AssignPermissionsModal/index.tsx
  packages/console/src/pages/Roles/components/CreateRoleForm/Footer.tsx
  packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/MauLimitExceededNotification/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/index.tsx
  packages/console/src/pages/Webhooks/CreateFormModal/CreateForm.tsx
Labels: enhancement, size/xl

#5178 style(console): inherit background-color for text input
  packages/console/src/ds-components/TextInput/index.module.scss
Labels: size/xs

#5092 chore(test): add test cases for SSO connection info
  packages/integration-tests/src/tests/console/sso-connectors/helpers.ts
  packages/integration-tests/src/tests/console/sso-connectors/sso-connectors-test-cases.ts
  packages/integration-tests/src/tests/console/sso-connectors/sso-connectors.test.ts
Labels: chore, size/m, stale

#5180 refactor: deprecate staging env tag (1/2)
  packages/console/src/components/CreateTenantModal/EnvTagOptionContent/index.tsx
  packages/console/src/components/TenantEnvTag/index.tsx
  packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx
  packages/console/src/components/Topbar/TenantSelector/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/DeleteModal/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/tenants.ts
  packages/phrases/src/locales/en/translation/admin-console/tenants.ts
  packages/phrases/src/locales/es/translation/admin-console/tenants.ts
  packages/phrases/src/locales/fr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/it/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ja/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ko/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ru/translation/admin-console/tenants.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tenants.ts
  packages/schemas/src/types/tenant.ts
Labels: enhancement, size/s

#5187 refactor: deprecate staging env tag (2/2)
  packages/console/package.json
  packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx
  packages/console/src/components/Topbar/TenantSelector/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/DeleteModal/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/index.tsx
  packages/core/package.json
  pnpm-lock.yaml
Labels: enhancement, size/s

#5190 chore(console): update onboarding survey
  packages/console/src/onboarding/pages/Welcome/index.module.scss
  packages/console/src/onboarding/pages/Welcome/index.tsx
  packages/console/src/onboarding/pages/Welcome/options.tsx
  packages/console/src/onboarding/types.ts
  packages/phrases/src/locales/de/errors/application.ts
  packages/phrases/src/locales/de/translation/admin-console/cloud.ts
  packages/phrases/src/locales/en/translation/admin-console/cloud.ts
  packages/phrases/src/locales/es/errors/application.ts
  packages/phrases/src/locales/es/translation/admin-console/cloud.ts
  packages/phrases/src/locales/fr/errors/application.ts
  packages/phrases/src/locales/fr/translation/admin-console/cloud.ts
  packages/phrases/src/locales/it/errors/application.ts
  packages/phrases/src/locales/it/translation/admin-console/cloud.ts
  packages/phrases/src/locales/ja/errors/application.ts
  packages/phrases/src/locales/ja/translation/admin-console/cloud.ts
  packages/phrases/src/locales/ko/errors/application.ts
  packages/phrases/src/locales/ko/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pl-pl/errors/application.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pt-br/errors/application.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pt-pt/errors/application.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/cloud.ts
  packages/phrases/src/locales/ru/errors/application.ts
  packages/phrases/src/locales/ru/translation/admin-console/cloud.ts
  packages/phrases/src/locales/tr-tr/errors/application.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/cloud.ts
  packages/phrases/src/locales/zh-cn/errors/application.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/cloud.ts
  packages/phrases/src/locales/zh-hk/errors/application.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/cloud.ts
  packages/phrases/src/locales/zh-tw/errors/application.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/cloud.ts
Labels: chore, size/xl

#5192 fix(experience): update text content in the preview on custom phrases updated
  packages/experience/src/Providers/SettingsProvider/use-preview.ts
  packages/experience/src/i18n/init.ts
Labels: bugfix, size/s

#5193 fix(console): allow image/x-icon mime type
  packages/console/src/consts/user-assets.ts
  packages/console/src/hooks/use-image-mime-types.ts
  packages/console/src/utils/uploader.ts
  packages/schemas/src/types/user-assets.ts
Labels: bugfix, size/s

#5195 refactor(console): refactor sie form data parser
  packages/console/src/pages/SignInExperience/components/SignUpAndSignInChangePreview/SignUpAndSignInDiffSection/SignUpDiffSection.tsx
  packages/console/src/pages/SignInExperience/components/Welcome/GuideModal.tsx
  packages/console/src/pages/SignInExperience/hooks/use-preview-configs.ts
  packages/console/src/pages/SignInExperience/index.tsx
  packages/console/src/pages/SignInExperience/types.ts
  packages/console/src/pages/SignInExperience/utils/form.ts
  packages/console/src/pages/SignInExperience/utils/parser.ts
Labels: enhancement, size/m

#5196 refactor(console): merge `useMeCustomData` hook into `useCurrentUser`
  packages/console/src/App.tsx
  packages/console/src/cloud/pages/Main/index.tsx
  packages/console/src/components/Guide/ModalHeader/RequestForm.tsx
  packages/console/src/hooks/use-current-user.ts
  packages/console/src/hooks/use-me-custom-data.ts
  packages/console/src/hooks/use-user-default-tenant-id.ts
  packages/console/src/hooks/use-user-preferences.ts
  packages/console/src/onboarding/hooks/use-user-onboarding-data.ts
Labels: enhancement, size/m

#5078 refactor(core): add koaAutoConsent middleware
  packages/core/src/libraries/quota.ts
  packages/core/src/libraries/session.test.ts
  packages/core/src/libraries/session.ts
  packages/core/src/middleware/koa-auto-consent.ts
  packages/core/src/routes/interaction/consent.test.ts
  packages/core/src/routes/interaction/consent.ts
  packages/core/src/tenants/Tenant.ts
  packages/core/src/test-utils/oidc-provider.ts
  packages/integration-tests/src/client/index.ts
Labels: enhancement, size/l

#5144 feat(console,phrases): add new third-party application to the guide Library
  packages/console/src/assets/docs/guides/generate-metadata.js
  packages/console/src/assets/docs/guides/index.ts
  packages/console/src/assets/docs/guides/third-party-oidc/README.mdx
  packages/console/src/assets/docs/guides/third-party-oidc/index.ts
  packages/console/src/assets/docs/guides/third-party-oidc/logo.svg
  packages/console/src/assets/docs/guides/types.ts
  packages/console/src/components/Guide/GuideCard/index.tsx
  packages/console/src/components/Guide/hooks.ts
  packages/console/src/pages/ApplicationDetails/components/GuideDrawer/index.tsx
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
  packages/console/src/types/applications.ts
  packages/integration-tests/src/tests/console/applications/constants.ts
  packages/integration-tests/src/tests/console/applications/index.test.ts
  packages/phrases/src/locales/de/translation/admin-console/guide.ts
  packages/phrases/src/locales/en/translation/admin-console/guide.ts
  packages/phrases/src/locales/es/translation/admin-console/guide.ts
  packages/phrases/src/locales/fr/translation/admin-console/guide.ts
  packages/phrases/src/locales/it/translation/admin-console/guide.ts
  packages/phrases/src/locales/ja/translation/admin-console/guide.ts
  packages/phrases/src/locales/ko/translation/admin-console/guide.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/guide.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/guide.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/guide.ts
  packages/phrases/src/locales/ru/translation/admin-console/guide.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/guide.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/guide.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/guide.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/guide.ts
Labels: feature, size/m

#5149 feat(console,phrases): add third party app list page
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/hooks/use-subscription-plans.ts
  packages/console/src/hooks/use-tenant-pathname.ts
  packages/console/src/pages/Applications/hooks/use-application-data.ts
  packages/console/src/pages/Applications/hooks/use-legacy-application-data.ts
  packages/console/src/pages/Applications/index.module.scss
  packages/console/src/pages/Applications/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/applications.ts
  packages/phrases/src/locales/en/translation/admin-console/applications.ts
  packages/phrases/src/locales/es/translation/admin-console/applications.ts
  packages/phrases/src/locales/fr/translation/admin-console/applications.ts
  packages/phrases/src/locales/it/translation/admin-console/applications.ts
  packages/phrases/src/locales/ja/translation/admin-console/applications.ts
  packages/phrases/src/locales/ko/translation/admin-console/applications.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/applications.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/applications.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/applications.ts
  packages/phrases/src/locales/ru/translation/admin-console/applications.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/applications.ts
Labels: feature, size/l

#5168 refactor(phrases,console): refactor the application details form
  packages/console/src/consts/page-tabs.ts
  packages/console/src/ds-components/TabWrapper/index.tsx
  packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx
  packages/console/src/pages/ApplicationDetails/components/EndpointsAndCredentials.tsx
  packages/console/src/pages/ApplicationDetails/components/RefreshTokenSettings.tsx
  packages/console/src/pages/ApplicationDetails/components/Settings.tsx
  packages/console/src/pages/ApplicationDetails/index.module.scss
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/es/translation/admin-console/application-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/it/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/application-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts
Labels: enhancement, size/xl

#5201 fix(core): fix dev tenant migration data guard
  packages/schemas/src/types/logto-config.ts
Labels: bugfix, size/xs

#5176 feat(console): : add application branding tab
  packages/console/src/consts/page-tabs.ts
  packages/console/src/pages/ApplicationDetails/components/Branding/LogoUploader.tsx
  packages/console/src/pages/ApplicationDetails/components/Branding/index.module.scss
  packages/console/src/pages/ApplicationDetails/components/Branding/index.tsx
  packages/console/src/pages/ApplicationDetails/components/Branding/use-application-sign-in-experience-swr.ts
  packages/console/src/pages/ApplicationDetails/components/Branding/use-sign-in-experience-swr.ts
  packages/console/src/pages/ApplicationDetails/components/Branding/utils.ts
  packages/console/src/pages/ApplicationDetails/components/EndpointsAndCredentials.tsx
  packages/console/src/pages/ApplicationDetails/components/Settings.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/Applications/hooks/use-application-data.ts
  packages/phrases/src/locales/de/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/es/translation/admin-console/application-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/it/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/application-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts
Labels: feature, size/xl

#5130 feat(experience): experience support old browser
  packages/experience/package.json
  packages/experience/src/index.tsx
  pnpm-lock.yaml
Labels: feature, size/s

#5206 fix: update the alteration change detection script
  .github/workflows/alteration-compatibility-integration-test.yml
Labels: bugfix, size/xs

#5197 fix(console): remove hover state from tip button after tip is closed
  packages/console/src/ds-components/CopyToClipboard/index.tsx
  packages/console/src/ds-components/Tip/ToggleTip/index.tsx
Labels: bugfix, size/s

#5203 fix(console): display no data when no data is found by search filter
  packages/console/src/pages/Organizations/OrganizationsTable/index.tsx
  packages/console/src/pages/Roles/index.tsx
  packages/console/src/pages/SignInExperience/tabs/Content/components/ManageLanguage/LanguageEditor/AddLanguageSelector.module.scss
  packages/console/src/pages/SignInExperience/tabs/Content/components/ManageLanguage/LanguageEditor/AddLanguageSelector.tsx
  packages/console/src/pages/Users/index.tsx
Labels: bugfix, size/s

#5199 refactor(console): forward ref for button component
  packages/console/src/ds-components/ActionMenu/ActionMenuButton.tsx
  packages/console/src/ds-components/ActionMenu/index.module.scss
  packages/console/src/ds-components/ActionMenu/index.tsx
  packages/console/src/ds-components/Button/index.tsx
Labels: enhancement, size/s

#5204 style(console): update space size for table placeholder
  packages/console/src/ds-components/Table/TableEmptyWrapper.module.scss
  packages/console/src/ds-components/Table/TableEmptyWrapper.tsx
Labels: size/s

#5135 feat(core): sync site configs to KV for new protected app
  packages/core/src/__mocks__/index.ts
  packages/core/src/libraries/domain.test.ts
  packages/core/src/libraries/protected-app.test.ts
  packages/core/src/libraries/protected-app.ts
  packages/core/src/routes/applications/application.test.ts
  packages/core/src/routes/applications/application.ts
  packages/core/src/tenants/Libraries.ts
  packages/core/src/tenants/SystemContext.ts
  packages/core/src/utils/cloudflare/index.ts
  packages/core/src/utils/cloudflare/kv.ts
  packages/core/src/utils/cloudflare/types.ts
  packages/core/src/utils/cloudflare/utils.ts
  packages/integration-tests/src/tests/api/application/application.test.ts
  packages/phrases/src/locales/de/errors/application.ts
  packages/phrases/src/locales/en/errors/application.ts
  packages/phrases/src/locales/es/errors/application.ts
  packages/phrases/src/locales/fr/errors/application.ts
  packages/phrases/src/locales/it/errors/application.ts
  packages/phrases/src/locales/ja/errors/application.ts
  packages/phrases/src/locales/ko/errors/application.ts
  packages/phrases/src/locales/pl-pl/errors/application.ts
  packages/phrases/src/locales/pt-br/errors/application.ts
  packages/phrases/src/locales/pt-pt/errors/application.ts
  packages/phrases/src/locales/ru/errors/application.ts
  packages/phrases/src/locales/tr-tr/errors/application.ts
  packages/phrases/src/locales/zh-cn/errors/application.ts
  packages/phrases/src/locales/zh-hk/errors/application.ts
  packages/phrases/src/locales/zh-tw/errors/application.ts
  packages/schemas/src/types/system.ts
Labels: feature, size/l

#5205 chore(connector): remove legacy Test passwordless template type use case
  packages/connectors/connector-aliyun-dm/src/index.test.ts
  packages/connectors/connector-aliyun-sms/src/index.test.ts
  packages/connectors/connector-aws-ses/src/index.test.ts
  packages/connectors/connector-sendgrid-email/src/mock.ts
  packages/connectors/connector-smsaero/src/mock.ts
  packages/connectors/connector-tencent-sms/src/index.test.ts
  packages/connectors/connector-twilio-sms/src/mock.ts
Labels: chore, size/s

#5200 chore(connector): remove unused code
  packages/connectors/connector-oidc/src/utils.ts
Labels: chore, size/s

#5118 refactor: remove legacy resources
  packages/cli/src/commands/database/seed/tables.ts
  packages/cli/src/commands/database/seed/tenant-organizations.ts
  packages/cli/src/commands/database/seed/tenant.ts
  packages/console/src/App.tsx
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/integration-tests/src/helpers/admin-tenant.ts
  packages/schemas/alterations/next-1704692973-remove-legacy-resources.ts
  packages/schemas/src/seeds/cloud-api.ts
  packages/schemas/src/seeds/management-api.ts
  packages/schemas/src/types/index.ts
  packages/schemas/src/types/mapi-proxy.ts
  packages/schemas/src/types/user.ts
Labels: enhancement, size/l, stale

#5210 fix: fix the db alter detect ci script
  .github/workflows/alteration-compatibility-integration-test.yml
Labels: bugfix, size/s

#5188 feat(core): generate oidc metadata for protected app
  packages/core/src/routes/applications/application.test.ts
  packages/core/src/routes/applications/application.ts
  packages/core/src/routes/applications/utils.ts
Labels: feature, size/s

#5208 refactor(console): show auto generated acs url for SAML connector
  packages/console/src/components/ConnectorForm/ConfigForm/index.tsx
  packages/console/src/pages/ConnectorDetails/ConnectorContent/index.tsx
  packages/console/src/pages/Connectors/Guide/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/connectors.ts
  packages/phrases/src/locales/de/translation/admin-console/domain.ts
  packages/phrases/src/locales/en/translation/admin-console/connectors.ts
  packages/phrases/src/locales/en/translation/admin-console/domain.ts
  packages/phrases/src/locales/es/translation/admin-console/connectors.ts
  packages/phrases/src/locales/es/translation/admin-console/domain.ts
  packages/phrases/src/locales/fr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/fr/translation/admin-console/domain.ts
  packages/phrases/src/locales/it/translation/admin-console/connectors.ts
  packages/phrases/src/locales/it/translation/admin-console/domain.ts
  packages/phrases/src/locales/ja/translation/admin-console/connectors.ts
  packages/phrases/src/locales/ja/translation/admin-console/domain.ts
  packages/phrases/src/locales/ko/translation/admin-console/connectors.ts
  packages/phrases/src/locales/ko/translation/admin-console/domain.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/domain.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/domain.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/domain.ts
  packages/phrases/src/locales/ru/translation/admin-console/connectors.ts
  packages/phrases/src/locales/ru/translation/admin-console/domain.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/domain.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/connectors.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/domain.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/connectors.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/domain.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/connectors.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/domain.ts
Labels: enhancement, size/m

#5179 fix(core): fix next server action guide
  packages/console/src/assets/docs/guides/web-next-server-actions/README.mdx
Labels: bugfix, size/xs

#5175 refactor(core): use const pagination key name for swagger
  packages/core/src/middleware/koa-pagination.ts
  packages/core/src/routes/swagger/utils/parameters.ts
Labels: enhancement, size/s

#5216 fix(console): should not parse phone number if it is empty
  packages/console/src/pages/UserDetails/UserSettings/index.tsx
Labels: bugfix, size/xs

#5214 refactor(schemas): fix alteration script
  packages/schemas/alterations/next-1704692973-remove-legacy-resources.ts
Labels: enhancement, size/s

#5189 feat(core,phrases): update protected app
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/ApplicationDetails/utils.ts
  packages/core/src/routes/applications/application.test.ts
  packages/core/src/routes/applications/application.ts
  packages/core/src/routes/applications/types.ts
  packages/integration-tests/src/api/application.ts
  packages/integration-tests/src/tests/api/application/application.test.ts
  packages/phrases/src/locales/de/errors/application.ts
  packages/phrases/src/locales/en/errors/application.ts
  packages/phrases/src/locales/es/errors/application.ts
  packages/phrases/src/locales/fr/errors/application.ts
  packages/phrases/src/locales/it/errors/application.ts
  packages/phrases/src/locales/ja/errors/application.ts
  packages/phrases/src/locales/ko/errors/application.ts
  packages/phrases/src/locales/pl-pl/errors/application.ts
  packages/phrases/src/locales/pt-br/errors/application.ts
  packages/phrases/src/locales/pt-pt/errors/application.ts
  packages/phrases/src/locales/ru/errors/application.ts
  packages/phrases/src/locales/tr-tr/errors/application.ts
  packages/phrases/src/locales/zh-cn/errors/application.ts
  packages/phrases/src/locales/zh-hk/errors/application.ts
  packages/phrases/src/locales/zh-tw/errors/application.ts
Labels: feature, size/m

#5191 feat(core): delete protected app
  packages/core/src/libraries/protected-app.ts
  packages/core/src/routes/applications/application.test.ts
  packages/core/src/routes/applications/application.ts
  packages/core/src/utils/cloudflare/kv.ts
Labels: feature, size/s

#5222 refactor: update android integration guides
  packages/console/src/assets/docs/guides/native-android-java/README.mdx
  packages/console/src/assets/docs/guides/native-android-kt/README.mdx
Labels: enhancement, size/s

#5093 chore(test): add test cases for SAML and OIDC SSO configuration
  packages/integration-tests/src/tests/console/sso-connectors/helpers.ts
  packages/integration-tests/src/tests/console/sso-connectors/sso-connectors-test-cases.ts
  packages/integration-tests/src/tests/console/sso-connectors/sso-connectors.test.ts
Labels: chore, size/m

#5223 fix(console): upcoming billing info not updated when subscription changes
  packages/console/src/pages/TenantSettings/Subscription/SwitchPlanActionBar/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/index.tsx
Labels: bugfix, size/s

#5224 feat(schemas, core): init organization invitation apis
  packages/core/src/database/utils.ts
  packages/core/src/queries/organizations.ts
  packages/core/src/routes/organization/index.ts
  packages/core/src/routes/organization/invitations.openapi.json
  packages/core/src/routes/organization/invitations.ts
  packages/schemas/src/types/organization.ts
  packages/schemas/tables/magic_links.sql
Labels: feature, size/m

#5226 refactor(core): reorg organization queries
  packages/core/src/oidc/grants/refresh-token.ts
  packages/core/src/queries/organization/index.ts
  packages/core/src/queries/organization/relations.ts
  packages/core/src/tenants/Queries.ts
Labels: enhancement, size/l

#5232 feat(core): get and delete org invitation by id
  packages/core/src/routes/organization/invitations.openapi.json
  packages/core/src/routes/organization/invitations.ts
  packages/core/src/routes/swagger/index.ts
Labels: feature, size/s

#5234 feat(core,schemas): add block domain list
  packages/core/src/libraries/domain.test.ts
  packages/core/src/libraries/domain.ts
  packages/core/src/utils/domain.test.ts
  packages/core/src/utils/domain.ts
  packages/phrases/src/locales/de/errors/domain.ts
  packages/phrases/src/locales/en/errors/domain.ts
  packages/phrases/src/locales/es/errors/domain.ts
  packages/phrases/src/locales/fr/errors/domain.ts
  packages/phrases/src/locales/it/errors/domain.ts
  packages/phrases/src/locales/ja/errors/domain.ts
  packages/phrases/src/locales/ko/errors/domain.ts
  packages/phrases/src/locales/pl-pl/errors/domain.ts
  packages/phrases/src/locales/pt-br/errors/domain.ts
  packages/phrases/src/locales/pt-pt/errors/domain.ts
  packages/phrases/src/locales/ru/errors/domain.ts
  packages/phrases/src/locales/tr-tr/errors/domain.ts
  packages/phrases/src/locales/zh-cn/errors/domain.ts
  packages/phrases/src/locales/zh-hk/errors/domain.ts
  packages/phrases/src/locales/zh-tw/errors/domain.ts
  packages/schemas/src/types/system.ts
Labels: feature, size/s

#5228 feat(console): add protected app creation form
  packages/console/src/assets/icons/protected-app-dark.svg
  packages/console/src/assets/icons/protected-app.svg
  packages/console/src/consts/applications.ts
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
  packages/console/src/pages/Applications/components/ProtectedAppCard/index.module.scss
  packages/console/src/pages/Applications/components/ProtectedAppCard/index.tsx
  packages/console/src/pages/Applications/components/ProtectedAppForm/index.module.scss
  packages/console/src/pages/Applications/components/ProtectedAppForm/index.tsx
  packages/console/src/pages/Applications/components/ProtectedAppForm/types.ts
  packages/console/src/pages/Applications/components/ProtectedAppModal/index.tsx
  packages/console/src/types/applications.ts
  packages/phrases/src/locales/de/translation/admin-console/applications.ts
  packages/phrases/src/locales/de/translation/admin-console/index.ts
  packages/phrases/src/locales/de/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/en/translation/admin-console/applications.ts
  packages/phrases/src/locales/en/translation/admin-console/index.ts
  packages/phrases/src/locales/en/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/es/translation/admin-console/applications.ts
  packages/phrases/src/locales/es/translation/admin-console/index.ts
  packages/phrases/src/locales/es/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/fr/translation/admin-console/applications.ts
  packages/phrases/src/locales/fr/translation/admin-console/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/it/translation/admin-console/applications.ts
  packages/phrases/src/locales/it/translation/admin-console/index.ts
  packages/phrases/src/locales/it/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/ja/translation/admin-console/applications.ts
  packages/phrases/src/locales/ja/translation/admin-console/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/ko/translation/admin-console/applications.ts
  packages/phrases/src/locales/ko/translation/admin-console/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/applications.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/applications.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/applications.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/ru/translation/admin-console/applications.ts
  packages/phrases/src/locales/ru/translation/admin-console/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/applications.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/protected-app.ts
  packages/toolkit/core-kit/scss/_console-themes.scss
Labels: feature, size/xl

#5235 feat(schemas): add new application user consent orgs table
  packages/schemas/alterations/next-1705288654-add-application-user-consent-organizations-table.ts
  packages/schemas/tables/application_user_consent_organizations.sql
Labels: feature, size/s

#5236 feat(core): implement application user consent organizations api
  packages/core/src/libraries/application.ts
  packages/core/src/queries/application-user-consent-organizations.ts
  packages/core/src/queries/application.ts
  packages/core/src/routes/applications/application-user-consent-organization.openapi.json
  packages/core/src/routes/applications/application-user-consent-organization.ts
  packages/core/src/routes/init.ts
  packages/integration-tests/src/api/application-user-consent-organization.ts
  packages/integration-tests/src/tests/api/application/application-sign-in-experience.test.ts
  packages/integration-tests/src/tests/api/application/application-user-consent-organization.test.ts
  packages/integration-tests/src/tests/api/application/application-user-consent-scope.test.ts
Labels: feature, size/xl

#5211 feat(console,phrases): add permissions tab to the application details page 4-1
  packages/console/src/consts/page-tabs.ts
  packages/console/src/pages/ApplicationDetails/components/Branding/index.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/es/translation/admin-console/application-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/it/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/application-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts
Labels: feature, size/m

#5212 refactor(console): add permissions tab to the application details page 4-2
  packages/console/src/components/TemplateTable/index.module.scss
  packages/console/src/components/TemplateTable/index.tsx
  packages/console/src/pages/Organizations/PermissionsCard/index.tsx
  packages/console/src/pages/Organizations/RolesCard/index.tsx
Labels: enhancement, size/s

#5213 feat(console,phrases): add permissions tab to the application details page 4-3
  packages/console/src/components/TemplateTable/index.tsx
  packages/console/src/ds-components/Table/index.tsx
  packages/console/src/ds-components/Table/types.ts
  packages/console/src/pages/ApplicationDetails/components/Permissions/index.module.scss
  packages/console/src/pages/ApplicationDetails/components/Permissions/index.tsx
  packages/console/src/pages/ApplicationDetails/components/Permissions/use-permissions-table.ts
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/es/translation/admin-console/application-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/it/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/application-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts
Labels: feature, size/l

#5217 feat(core,shared,phrases): check subdomain when creating protected app
  packages/core/src/__mocks__/index.ts
  packages/core/src/libraries/protected-app.test.ts
  packages/core/src/libraries/protected-app.ts
  packages/core/src/queries/application.test.ts
  packages/core/src/queries/application.ts
  packages/core/src/routes/applications/application.test.ts
  packages/core/src/routes/applications/application.ts
  packages/core/src/routes/applications/types.ts
  packages/core/src/routes/applications/utils.ts
  packages/core/src/utils/cloudflare/kv.ts
  packages/integration-tests/src/tests/api/application/application.test.ts
  packages/phrases/src/locales/de/errors/application.ts
  packages/phrases/src/locales/en/errors/application.ts
  packages/phrases/src/locales/es/errors/application.ts
  packages/phrases/src/locales/fr/errors/application.ts
  packages/phrases/src/locales/it/errors/application.ts
  packages/phrases/src/locales/ja/errors/application.ts
  packages/phrases/src/locales/ko/errors/application.ts
  packages/phrases/src/locales/pl-pl/errors/application.ts
  packages/phrases/src/locales/pt-br/errors/application.ts
  packages/phrases/src/locales/pt-pt/errors/application.ts
  packages/phrases/src/locales/ru/errors/application.ts
  packages/phrases/src/locales/tr-tr/errors/application.ts
  packages/phrases/src/locales/zh-cn/errors/application.ts
  packages/phrases/src/locales/zh-hk/errors/application.ts
  packages/phrases/src/locales/zh-tw/errors/application.ts
  packages/schemas/src/types/system.ts
  packages/shared/src/utils/index.ts
  packages/shared/src/utils/sub-domain.test.ts
  packages/shared/src/utils/sub-domain.ts
Labels: feature, size/l

#5237 refactor(console): update quota pricing info
  packages/console/src/components/CreateConnectorForm/index.tsx
  packages/console/src/components/FeatureTag/index.module.scss
  packages/console/src/components/FeatureTag/index.tsx
  packages/console/src/ds-components/CardTitle/index.tsx
  packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
  packages/console/src/pages/Applications/components/TypeDescription/index.tsx
  packages/console/src/pages/EnterpriseSso/index.tsx
  packages/console/src/pages/Mfa/PageWrapper/index.tsx
  packages/console/src/pages/Organizations/index.tsx
  packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/components/TableDataWrapper/index.module.scss
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/components/TableDataWrapper/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/renderers/GenericFeatureFlag.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/renderers/GenericQuotaLimit.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/renderers/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-table.ts
Labels: enhancement, size/xl

#5242 fix(core): fix quota guard for schema routers
  packages/core/src/routes/organization/index.ts
  packages/core/src/routes/organization/roles.ts
  packages/core/src/routes/organization/scopes.ts
  packages/core/src/utils/SchemaRouter.ts
Labels: bugfix, size/s

#5243 refactor: remove next bill tip
  packages/console/src/components/BillInfo/index.module.scss
  packages/console/src/components/BillInfo/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/index.ts
Labels: enhancement, size/s

#5238 feat(console,phrases): support protected app creation in get-started page
  packages/console/src/ds-components/FormField/index.module.scss
  packages/console/src/ds-components/FormField/index.tsx
  packages/console/src/pages/Applications/components/GuideLibrary/index.module.scss
  packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
  packages/console/src/pages/Applications/components/ProtectedAppCard/index.module.scss
  packages/console/src/pages/Applications/components/ProtectedAppCard/index.tsx
  packages/console/src/pages/Applications/components/ProtectedAppForm/index.module.scss
  packages/console/src/pages/Applications/components/ProtectedAppForm/index.tsx
  packages/console/src/pages/Applications/components/ProtectedAppModal/index.tsx
  packages/console/src/pages/GetStarted/ProtectedAppCreationForm/index.module.scss
  packages/console/src/pages/GetStarted/ProtectedAppCreationForm/index.tsx
  packages/console/src/pages/GetStarted/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/general.ts
  packages/phrases/src/locales/de/translation/admin-console/get-started.ts
  packages/phrases/src/locales/de/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/en/translation/admin-console/general.ts
  packages/phrases/src/locales/en/translation/admin-console/get-started.ts
  packages/phrases/src/locales/en/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/es/translation/admin-console/general.ts
  packages/phrases/src/locales/es/translation/admin-console/get-started.ts
  packages/phrases/src/locales/es/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/fr/translation/admin-console/general.ts
  packages/phrases/src/locales/fr/translation/admin-console/get-started.ts
  packages/phrases/src/locales/fr/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/it/translation/admin-console/general.ts
  packages/phrases/src/locales/it/translation/admin-console/get-started.ts
  packages/phrases/src/locales/it/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/ja/translation/admin-console/general.ts
  packages/phrases/src/locales/ja/translation/admin-console/get-started.ts
  packages/phrases/src/locales/ja/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/ko/translation/admin-console/general.ts
  packages/phrases/src/locales/ko/translation/admin-console/get-started.ts
  packages/phrases/src/locales/ko/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/general.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/get-started.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/get-started.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/get-started.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/ru/translation/admin-console/general.ts
  packages/phrases/src/locales/ru/translation/admin-console/get-started.ts
  packages/phrases/src/locales/ru/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/get-started.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/get-started.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/get-started.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/get-started.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/protected-app.ts
Labels: feature, size/xl

#5244 fix(console): fix application refresh token settings
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
  packages/console/src/pages/ApplicationDetails/index.module.scss
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/ApplicationDetails/utils.ts
Labels: bugfix, size/xl

#5248 refactor(console): reorg application details page codes
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/LogoUploader.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/index.module.scss
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/use-application-sign-in-experience-swr.ts
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/use-sign-in-experience-swr.ts
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/utils.ts
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/EndpointsAndCredentials.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/GuideDrawer/index.module.scss
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/GuideDrawer/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/MachineLogs/index.module.scss
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/MachineLogs/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/MachineToMachineApplicationRoles/index.module.scss
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/MachineToMachineApplicationRoles/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/index.module.scss
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/use-permissions-table.ts
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/RefreshTokenSettings.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Settings.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.module.scss
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/utils.ts
  packages/console/src/pages/ApplicationDetails/GuideModal/index.module.scss
  packages/console/src/pages/ApplicationDetails/GuideModal/index.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
Labels: enhancement, size/s

#5251 fix(core): add management api scopes guard
  packages/core/src/libraries/application.ts
  packages/core/src/queries/scope.ts
  packages/core/src/routes/applications/application-user-consent-scope.ts
  packages/phrases/src/locales/de/errors/application.ts
  packages/phrases/src/locales/en/errors/application.ts
  packages/phrases/src/locales/es/errors/application.ts
  packages/phrases/src/locales/fr/errors/application.ts
  packages/phrases/src/locales/it/errors/application.ts
  packages/phrases/src/locales/ja/errors/application.ts
  packages/phrases/src/locales/ko/errors/application.ts
  packages/phrases/src/locales/pl-pl/errors/application.ts
  packages/phrases/src/locales/pt-br/errors/application.ts
  packages/phrases/src/locales/pt-pt/errors/application.ts
  packages/phrases/src/locales/ru/errors/application.ts
  packages/phrases/src/locales/tr-tr/errors/application.ts
  packages/phrases/src/locales/zh-cn/errors/application.ts
  packages/phrases/src/locales/zh-hk/errors/application.ts
  packages/phrases/src/locales/zh-tw/errors/application.ts
Labels: bugfix, size/s

#5246 refactor(console): add next bill tip for tax info
  packages/console/src/components/BillInfo/index.module.scss
  packages/console/src/components/BillInfo/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/index.ts
Labels: enhancement, size/s

#5250 refactor(phrases): update mfa title phrase
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-item.ts
Labels: enhancement, size/m

#5255 refactor(console,phrases): update plan comparison table content
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/PlanQuotaKeyLabel/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-table.ts
Labels: enhancement, size/s

#5249 feat(core): add third-party application scopes and organizations restriction
  packages/core/src/middleware/koa-auto-consent.ts
  packages/core/src/oidc/adapter.ts
  packages/core/src/oidc/grants/index.ts
  packages/core/src/oidc/grants/refresh-token.test.ts
  packages/core/src/oidc/grants/refresh-token.ts
  packages/core/src/oidc/init.ts
  packages/core/src/oidc/resource.ts
Labels: feature, size/l

#5259 feat(core): add get consent info api
  packages/core/src/libraries/session.ts
  packages/core/src/routes/interaction/consent.ts
  packages/schemas/src/types/consent.ts
  packages/schemas/src/types/index.ts
Labels: feature, size/m

#5241 feat(core): api to get protected app default domain
  packages/core/src/__mocks__/index.ts
  packages/core/src/__mocks__/protected-app.ts
  packages/core/src/libraries/protected-app.test.ts
  packages/core/src/libraries/protected-app.ts
  packages/core/src/routes/applications/application.test.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/system.openapi.json
  packages/core/src/routes/system.test.ts
  packages/core/src/routes/system.ts
Labels: feature, size/m

#5247 feat(core,schemas): prepare schemas for protected app custom domain
  packages/core/src/tenants/SystemContext.ts
  packages/schemas/src/foundations/jsonb-types/applications.ts
  packages/schemas/src/types/system.ts
Labels: feature, size/s

#5254 feat(core): add custom domain for protected app
  packages/core/src/__mocks__/index.ts
  packages/core/src/libraries/application.ts
  packages/core/src/libraries/protected-app.test.ts
  packages/core/src/libraries/protected-app.ts
  packages/core/src/routes/applications/application-protected-app-metadata.openapi.json
  packages/core/src/routes/applications/application-protected-app-metadata.test.ts
  packages/core/src/routes/applications/application-protected-app-metadata.ts
  packages/core/src/routes/applications/application.test.ts
  packages/core/src/routes/init.ts
Labels: feature, size/l

#5256 feat(core): check application custom domain conflict
  packages/core/src/queries/application.test.ts
  packages/core/src/queries/application.ts
  packages/core/src/routes/applications/application-protected-app-metadata.test.ts
  packages/core/src/routes/applications/application-protected-app-metadata.ts
Labels: feature, size/s

#5229 feat(console): implement DataTransferBox ds-component
  packages/console/src/components/RoleScopesTransfer/index.tsx
  packages/console/src/ds-components/ConfirmModal/index.tsx
  packages/console/src/ds-components/DataTransferBox/SourceDataItem/index.module.scss
  packages/console/src/ds-components/DataTransferBox/SourceDataItem/index.tsx
  packages/console/src/ds-components/DataTransferBox/SourceGroupItem/index.module.scss
  packages/console/src/ds-components/DataTransferBox/SourceGroupItem/index.tsx
  packages/console/src/ds-components/DataTransferBox/SourcePanel/index.module.scss
  packages/console/src/ds-components/DataTransferBox/SourcePanel/index.tsx
  packages/console/src/ds-components/DataTransferBox/TargetDataItem/index.module.scss
  packages/console/src/ds-components/DataTransferBox/TargetDataItem/index.tsx
  packages/console/src/ds-components/DataTransferBox/TargetPanel/index.module.scss
  packages/console/src/ds-components/DataTransferBox/TargetPanel/index.tsx
  packages/console/src/ds-components/DataTransferBox/index.module.scss
  packages/console/src/ds-components/DataTransferBox/index.tsx
  packages/console/src/ds-components/DataTransferBox/type.ts
Labels: feature, size/xl

#5266 feat(phrases): add experience consent page phrases
  packages/phrases-experience/src/locales/de/action.ts
  packages/phrases-experience/src/locales/de/description.ts
  packages/phrases-experience/src/locales/en/action.ts
  packages/phrases-experience/src/locales/en/description.ts
  packages/phrases-experience/src/locales/es/action.ts
  packages/phrases-experience/src/locales/es/description.ts
  packages/phrases-experience/src/locales/fr/action.ts
  packages/phrases-experience/src/locales/fr/description.ts
  packages/phrases-experience/src/locales/it/action.ts
  packages/phrases-experience/src/locales/it/description.ts
  packages/phrases-experience/src/locales/ja/action.ts
  packages/phrases-experience/src/locales/ja/description.ts
  packages/phrases-experience/src/locales/ko/action.ts
  packages/phrases-experience/src/locales/ko/description.ts
  packages/phrases-experience/src/locales/pl-pl/action.ts
  packages/phrases-experience/src/locales/pl-pl/description.ts
  packages/phrases-experience/src/locales/pt-br/action.ts
  packages/phrases-experience/src/locales/pt-br/description.ts
  packages/phrases-experience/src/locales/pt-pt/action.ts
  packages/phrases-experience/src/locales/pt-pt/description.ts
  packages/phrases-experience/src/locales/ru/action.ts
  packages/phrases-experience/src/locales/ru/description.ts
  packages/phrases-experience/src/locales/tr-tr/action.ts
  packages/phrases-experience/src/locales/tr-tr/description.ts
  packages/phrases-experience/src/locales/zh-cn/action.ts
  packages/phrases-experience/src/locales/zh-cn/description.ts
  packages/phrases-experience/src/locales/zh-hk/action.ts
  packages/phrases-experience/src/locales/zh-hk/description.ts
  packages/phrases-experience/src/locales/zh-tw/action.ts
  packages/phrases-experience/src/locales/zh-tw/description.ts
Labels: feature, size/l

#5252 refactor(console): refactor app details page to support protected apps
  packages/console/src/ds-components/FormField/index.module.scss
  packages/console/src/ds-components/FormField/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/index.module.scss
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Settings.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/utils.ts
  packages/console/src/pages/GetStarted/ProtectedAppCreationForm/index.module.scss
  packages/console/src/pages/GetStarted/ProtectedAppCreationForm/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/es/translation/admin-console/application-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/it/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/application-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts
Labels: enhancement, size/xl

#5267 refactor(core): update the consent apis
  packages/core/src/middleware/koa-auto-consent.ts
  packages/core/src/routes/interaction/consent.ts
  packages/schemas/src/types/consent.ts
Labels: enhancement, size/m

#5263 refactor(console): update android integration guide
  packages/console/src/assets/docs/guides/index.ts
  packages/console/src/assets/docs/guides/native-android-java/README.mdx
  packages/console/src/assets/docs/guides/native-android-java/config.json
  packages/console/src/assets/docs/guides/native-android-java/index.ts
  packages/console/src/assets/docs/guides/native-android-java/logo.svg
  packages/console/src/assets/docs/guides/native-android-kt/README.mdx
  packages/console/src/assets/docs/guides/native-android-kt/logo.svg
  packages/console/src/assets/docs/guides/native-android/README.mdx
  packages/console/src/assets/docs/guides/native-android/config.json
  packages/console/src/assets/docs/guides/native-android/index.ts
  packages/console/src/assets/docs/guides/native-android/logo.svg
Labels: enhancement, size/xl

#5230 feat(console,phrases): implement application permissions assignment 4-4
  packages/console/src/components/TemplateTable/index.tsx
  packages/console/src/ds-components/DataTransferBox/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/ApplicationScopesAssignmentModal/constants.ts
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/ApplicationScopesAssignmentModal/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/ApplicationScopesAssignmentModal/type.ts
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/ApplicationScopesAssignmentModal/use-application-scopes-assignment.ts
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/ApplicationScopesAssignmentModal/use-organization-scopes-assignment.ts
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/ApplicationScopesAssignmentModal/use-resource-scopes-assignment.ts
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/ApplicationScopesAssignmentModal/use-user-scopes-assignment.ts
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/use-scopes-table.ts
  packages/phrases/src/locales/de/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/es/translation/admin-console/application-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/it/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/application-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts
Labels: feature, size/xl

#5264 chore(phrases): reword onboarding option
  packages/phrases/src/locales/de/translation/admin-console/cloud.ts
  packages/phrases/src/locales/en/translation/admin-console/cloud.ts
  packages/phrases/src/locales/es/translation/admin-console/cloud.ts
  packages/phrases/src/locales/fr/translation/admin-console/cloud.ts
  packages/phrases/src/locales/it/translation/admin-console/cloud.ts
  packages/phrases/src/locales/ja/translation/admin-console/cloud.ts
  packages/phrases/src/locales/ko/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/cloud.ts
  packages/phrases/src/locales/ru/translation/admin-console/cloud.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/cloud.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/cloud.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/cloud.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/cloud.ts
Labels: chore, size/s

#5265 feat(experience): implement the consent page
  packages/experience/src/App.tsx
  packages/experience/src/Layout/LandingPageLayout/index.tsx
  packages/experience/src/apis/consent.ts
  packages/experience/src/apis/index.test.ts
  packages/experience/src/assets/icons/connect-icon.svg
  packages/experience/src/assets/icons/expandable-icon.svg
  packages/experience/src/assets/icons/organization-icon.svg
  packages/experience/src/components/BrandingHeader/index.module.scss
  packages/experience/src/components/BrandingHeader/index.tsx
  packages/experience/src/components/PageMeta/index.tsx
  packages/experience/src/pages/Consent/OrganizationSelector/OrganizationItem/index.module.scss
  packages/experience/src/pages/Consent/OrganizationSelector/OrganizationItem/index.tsx
  packages/experience/src/pages/Consent/OrganizationSelector/OrganizationSelectorModal/index.module.scss
  packages/experience/src/pages/Consent/OrganizationSelector/OrganizationSelectorModal/index.tsx
  packages/experience/src/pages/Consent/OrganizationSelector/index.module.scss
  packages/experience/src/pages/Consent/OrganizationSelector/index.tsx
  packages/experience/src/pages/Consent/ScopesListCard/index.module.scss
  packages/experience/src/pages/Consent/ScopesListCard/index.tsx
  packages/experience/src/pages/Consent/UserProfile/index.module.scss
  packages/experience/src/pages/Consent/UserProfile/index.tsx
  packages/experience/src/pages/Consent/index.module.scss
  packages/experience/src/pages/Consent/index.tsx
Labels: feature, size/xl

#5239 feat(console,phrases): add application permissions edit modal
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/ApplicationScopesManagementModal/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/use-scopes-table.ts
  packages/phrases/src/locales/de/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/de/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/es/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/es/translation/admin-console/application-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/it/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/it/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/application-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts
Labels: feature, size/l

#5257 feat(core): sync protected app domain status
  packages/core/src/__mocks__/index.ts
  packages/core/src/libraries/domain.ts
  packages/core/src/libraries/protected-app.test.ts
  packages/core/src/libraries/protected-app.ts
  packages/core/src/routes/applications/application-protected-app-metadata.openapi.json
  packages/core/src/routes/applications/application-protected-app-metadata.test.ts
  packages/core/src/routes/applications/application-protected-app-metadata.ts
  packages/core/src/utils/cloudflare/index.ts
  packages/core/src/utils/cloudflare/utils.ts
  packages/schemas/src/foundations/jsonb-types/applications.ts
Labels: feature, size/l

#5271 fix(schemas): remove catchall from cloudflare data guard
  packages/core/src/__mocks__/domain.ts
  packages/schemas/src/foundations/jsonb-types/custom-domain.ts
Labels: bugfix, size/s

#5272 refactor(console): update go sdk integration guide
  packages/console/src/assets/docs/guides/native-android/README.mdx
  packages/console/src/assets/docs/guides/web-go/README.mdx
Labels: enhancement, size/m

#5270 fix(console,core): fix application count bug
  packages/console/src/pages/Applications/hooks/use-application-data.ts
  packages/core/src/queries/application.ts
  packages/core/src/routes/applications/application.ts
  packages/integration-tests/src/api/application.ts
  packages/integration-tests/src/tests/api/application/application.test.ts
Labels: bugfix, size/s

#5274 fix(core): should throw 500 on file upload error
  packages/core/src/routes/user-assets.ts
Labels: bugfix, size/xs

#5260 feat(core): sync site configs and oidc metadata for custom domain
  packages/core/src/libraries/protected-app.test.ts
  packages/core/src/libraries/protected-app.ts
  packages/core/src/routes/applications/application-protected-app-metadata.test.ts
  packages/core/src/routes/applications/application-protected-app-metadata.ts
Labels: feature, size/s

#5261 feat(core,phrases): delete custom domain
  packages/core/src/libraries/protected-app.test.ts
  packages/core/src/libraries/protected-app.ts
  packages/core/src/routes/applications/application-protected-app-metadata.openapi.json
  packages/core/src/routes/applications/application-protected-app-metadata.test.ts
  packages/core/src/routes/applications/application-protected-app-metadata.ts
  packages/phrases/src/locales/de/errors/application.ts
  packages/phrases/src/locales/en/errors/application.ts
  packages/phrases/src/locales/es/errors/application.ts
  packages/phrases/src/locales/fr/errors/application.ts
  packages/phrases/src/locales/it/errors/application.ts
  packages/phrases/src/locales/ja/errors/application.ts
  packages/phrases/src/locales/ko/errors/application.ts
  packages/phrases/src/locales/pl-pl/errors/application.ts
  packages/phrases/src/locales/pt-br/errors/application.ts
  packages/phrases/src/locales/pt-pt/errors/application.ts
  packages/phrases/src/locales/ru/errors/application.ts
  packages/phrases/src/locales/tr-tr/errors/application.ts
  packages/phrases/src/locales/zh-cn/errors/application.ts
  packages/phrases/src/locales/zh-hk/errors/application.ts
  packages/phrases/src/locales/zh-tw/errors/application.ts
Labels: feature, size/m

#5283 chore(console): keep app description input field
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Settings.tsx
Labels: chore, size/s

#5262 fix(core,phrases): prevent application deletion for custom domain
  packages/core/src/__mocks__/index.ts
  packages/core/src/libraries/protected-app.ts
  packages/core/src/routes/applications/application-protected-app-metadata.test.ts
  packages/core/src/routes/applications/application.test.ts
  packages/core/src/routes/applications/application.ts
  packages/phrases/src/locales/de/errors/application.ts
  packages/phrases/src/locales/en/errors/application.ts
  packages/phrases/src/locales/es/errors/application.ts
  packages/phrases/src/locales/fr/errors/application.ts
  packages/phrases/src/locales/it/errors/application.ts
  packages/phrases/src/locales/ja/errors/application.ts
  packages/phrases/src/locales/ko/errors/application.ts
  packages/phrases/src/locales/pl-pl/errors/application.ts
  packages/phrases/src/locales/pt-br/errors/application.ts
  packages/phrases/src/locales/pt-pt/errors/application.ts
  packages/phrases/src/locales/ru/errors/application.ts
  packages/phrases/src/locales/tr-tr/errors/application.ts
  packages/phrases/src/locales/zh-cn/errors/application.ts
  packages/phrases/src/locales/zh-hk/errors/application.ts
  packages/phrases/src/locales/zh-tw/errors/application.ts
  packages/schemas/src/foundations/jsonb-types/applications.ts
Labels: bugfix, size/s

#5279 style(console): replace the oidc idp app icon
  packages/console/src/assets/docs/guides/third-party-oidc/logo.svg
Labels: size/s

#5280 fix(console): fix third-party app return link
  packages/console/src/pages/ApplicationDetails/index.tsx
Labels: bugfix, size/xs

#5287 ci: do not run release on master pushes
  .github/workflows/release.yml
Labels: size/xs

#5273 style(experience): fix some of the consent page styling
  packages/experience/src/assets/icons/default-user-avatar.svg
  packages/experience/src/pages/Consent/ScopesListCard/index.module.scss
  packages/experience/src/pages/Consent/ScopesListCard/index.tsx
  packages/experience/src/pages/Consent/UserProfile/index.module.scss
  packages/experience/src/pages/Consent/UserProfile/index.tsx
  packages/experience/src/pages/Consent/index.module.scss
  packages/experience/src/scss/_colors.scss
  packages/phrases-experience/src/locales/de/description.ts
  packages/phrases-experience/src/locales/en/description.ts
  packages/phrases-experience/src/locales/es/description.ts
  packages/phrases-experience/src/locales/fr/description.ts
  packages/phrases-experience/src/locales/it/description.ts
  packages/phrases-experience/src/locales/ja/description.ts
  packages/phrases-experience/src/locales/ko/description.ts
  packages/phrases-experience/src/locales/pl-pl/description.ts
  packages/phrases-experience/src/locales/pt-br/description.ts
  packages/phrases-experience/src/locales/pt-pt/description.ts
  packages/phrases-experience/src/locales/ru/description.ts
  packages/phrases-experience/src/locales/tr-tr/description.ts
  packages/phrases-experience/src/locales/zh-cn/description.ts
  packages/phrases-experience/src/locales/zh-hk/description.ts
  packages/phrases-experience/src/locales/zh-tw/description.ts
Labels: size/s

#5276 refactor(console): auto focus on the email field when creating user
  packages/console/src/pages/Users/components/CreateForm/index.tsx
Labels: enhancement, size/xs

#5275 style(console): adjust textarea scrollbar position
  packages/console/src/ds-components/Textarea/index.module.scss
Labels: size/xs

#5284 refactor(console): hide the empty count on tab
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/ApplicationScopesAssignmentModal/index.tsx
Labels: enhancement, size/s

#5282 fix(console): add displayName input placeholder
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/index.tsx
Labels: bugfix, size/xs

#5258 feat(console,phrases): support custom domain in protected app details
  packages/console/src/components/DomainStatusTag/index.tsx
  packages/console/src/components/OpenExternalLink/index.tsx
  packages/console/src/ds-components/ActionMenu/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/index.module.scss
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/utils.ts
  packages/console/src/pages/Applications/components/ProtectedAppForm/index.tsx
  packages/console/src/pages/Applications/components/ProtectedAppForm/types.ts
  packages/console/src/pages/GetStarted/ProtectedAppCreationForm/index.tsx
  packages/console/src/pages/TenantSettings/TenantDomainSettings/AddDomainForm/index.tsx
  packages/console/src/pages/TenantSettings/TenantDomainSettings/CustomDomain/ActivationProcess/index.tsx
  packages/console/src/pages/TenantSettings/TenantDomainSettings/CustomDomain/CustomDomainHeader/index.module.scss
  packages/console/src/pages/TenantSettings/TenantDomainSettings/CustomDomain/CustomDomainHeader/index.tsx
  packages/console/src/pages/TenantSettings/TenantDomainSettings/CustomDomain/index.module.scss
  packages/console/src/pages/TenantSettings/TenantDomainSettings/CustomDomain/index.tsx
  packages/console/src/pages/TenantSettings/TenantDomainSettings/DefaultDomain/index.module.scss
  packages/console/src/pages/TenantSettings/TenantDomainSettings/DefaultDomain/index.tsx
  packages/console/src/pages/TenantSettings/TenantDomainSettings/index.module.scss
  packages/console/src/pages/TenantSettings/TenantDomainSettings/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/application-details.ts
  packages/phrases/src/locales/de/translation/admin-console/domain.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/domain.ts
  packages/phrases/src/locales/es/translation/admin-console/application-details.ts
  packages/phrases/src/locales/es/translation/admin-console/domain.ts
  packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/domain.ts
  packages/phrases/src/locales/it/translation/admin-console/application-details.ts
  packages/phrases/src/locales/it/translation/admin-console/domain.ts
  packages/phrases/src/locales/ja/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/domain.ts
  packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/domain.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/domain.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/domain.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/domain.ts
  packages/phrases/src/locales/ru/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/domain.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/domain.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/domain.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/domain.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/domain.ts
  packages/toolkit/core-kit/src/regex.ts
Labels: feature, size/xl

#5290 fix(experience): add empty scopes fallback layout
  packages/experience/src/pages/Consent/ScopesListCard/index.tsx
Labels: bugfix, size/s

#5291 feat(experience): auto expand the scopes list
  packages/experience/src/pages/Consent/ScopesListCard/index.tsx
Labels: feature, size/s

#5289 style(experience): update scopes and organizations selector style
  packages/experience/src/assets/icons/expandable-icon.svg
  packages/experience/src/pages/Consent/OrganizationSelector/OrganizationItem/index.module.scss
  packages/experience/src/pages/Consent/OrganizationSelector/OrganizationItem/index.tsx
  packages/experience/src/pages/Consent/OrganizationSelector/OrganizationSelectorModal/index.module.scss
  packages/experience/src/pages/Consent/OrganizationSelector/OrganizationSelectorModal/index.tsx
  packages/experience/src/pages/Consent/OrganizationSelector/index.module.scss
  packages/experience/src/pages/Consent/OrganizationSelector/index.tsx
  packages/experience/src/pages/Consent/ScopesListCard/index.module.scss
  packages/experience/src/pages/Consent/ScopesListCard/index.tsx
Labels: size/m

#5296 feat(experience): add redirect uri info
  packages/core/src/routes/interaction/consent.ts
  packages/experience/src/pages/Consent/index.module.scss
  packages/experience/src/pages/Consent/index.tsx
  packages/phrases-experience/src/locales/de/description.ts
  packages/phrases-experience/src/locales/en/description.ts
  packages/phrases-experience/src/locales/es/description.ts
  packages/phrases-experience/src/locales/fr/description.ts
  packages/phrases-experience/src/locales/it/description.ts
  packages/phrases-experience/src/locales/ja/description.ts
  packages/phrases-experience/src/locales/ko/description.ts
  packages/phrases-experience/src/locales/pl-pl/description.ts
  packages/phrases-experience/src/locales/pt-br/description.ts
  packages/phrases-experience/src/locales/pt-pt/description.ts
  packages/phrases-experience/src/locales/ru/description.ts
  packages/phrases-experience/src/locales/tr-tr/description.ts
  packages/phrases-experience/src/locales/zh-cn/description.ts
  packages/phrases-experience/src/locales/zh-hk/description.ts
  packages/phrases-experience/src/locales/zh-tw/description.ts
  packages/schemas/src/types/consent.ts
Labels: feature, size/s

#5295 fix(console): hide the guide button for third-party app
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
Labels: bugfix, size/s

#5300 feat(console,experience,phrases): add user scopes descriptions
  packages/console/src/i18n/init.ts
  packages/console/src/include.d/i18next.d.ts
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/use-scopes-table.ts
  packages/experience/src/pages/Consent/ScopesListCard/index.tsx
  packages/phrases-experience/src/locales/de/index.ts
  packages/phrases-experience/src/locales/de/user-scopes.ts
  packages/phrases-experience/src/locales/en/index.ts
  packages/phrases-experience/src/locales/en/user-scopes.ts
  packages/phrases-experience/src/locales/es/index.ts
  packages/phrases-experience/src/locales/es/user-scopes.ts
  packages/phrases-experience/src/locales/fr/index.ts
  packages/phrases-experience/src/locales/fr/user-scopes.ts
  packages/phrases-experience/src/locales/it/index.ts
  packages/phrases-experience/src/locales/it/user-scopes.ts
  packages/phrases-experience/src/locales/ja/index.ts
  packages/phrases-experience/src/locales/ja/user-scopes.ts
  packages/phrases-experience/src/locales/ko/index.ts
  packages/phrases-experience/src/locales/ko/user-scopes.ts
  packages/phrases-experience/src/locales/pl-pl/index.ts
  packages/phrases-experience/src/locales/pl-pl/user-scopes.ts
  packages/phrases-experience/src/locales/pt-br/index.ts
  packages/phrases-experience/src/locales/pt-br/user-scopes.ts
  packages/phrases-experience/src/locales/pt-pt/index.ts
  packages/phrases-experience/src/locales/pt-pt/user-scopes.ts
  packages/phrases-experience/src/locales/ru/index.ts
  packages/phrases-experience/src/locales/ru/user-scopes.ts
  packages/phrases-experience/src/locales/tr-tr/index.ts
  packages/phrases-experience/src/locales/tr-tr/user-scopes.ts
  packages/phrases-experience/src/locales/zh-cn/index.ts
  packages/phrases-experience/src/locales/zh-cn/user-scopes.ts
  packages/phrases-experience/src/locales/zh-hk/index.ts
  packages/phrases-experience/src/locales/zh-hk/user-scopes.ts
  packages/phrases-experience/src/locales/zh-tw/index.ts
  packages/phrases-experience/src/locales/zh-tw/user-scopes.ts
Labels: feature, size/l

#5294 fix(console): update the third-party app details page tag
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/types/applications.ts
  packages/phrases/src/locales/de/translation/admin-console/applications.ts
  packages/phrases/src/locales/en/translation/admin-console/applications.ts
  packages/phrases/src/locales/es/translation/admin-console/applications.ts
  packages/phrases/src/locales/fr/translation/admin-console/applications.ts
  packages/phrases/src/locales/it/translation/admin-console/applications.ts
  packages/phrases/src/locales/ja/translation/admin-console/applications.ts
  packages/phrases/src/locales/ko/translation/admin-console/applications.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/applications.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/applications.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/applications.ts
  packages/phrases/src/locales/ru/translation/admin-console/applications.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/applications.ts
Labels: bugfix, size/s

#5286 fix(console): hide the organization row group
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/index.module.scss
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/use-scopes-table.ts
Labels: bugfix, size/s

#5277 fix(console): add UnsavedChangesAlert
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
Labels: bugfix, size/m

#5285 fix(console): fix the image uploader style
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/LogoUploader.module.scss
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/LogoUploader.tsx
Labels: bugfix, size/xs

#5303 chore(phrases): console phrases updates
  packages/phrases/src/locales/de/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/user-details.ts
  packages/phrases/src/locales/es/translation/admin-console/application-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/it/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/application-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts
Labels: chore, size/s

#5304 feat(console,phrases): adjust the application creation modal
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/applications.ts
  packages/phrases/src/locales/en/translation/admin-console/applications.ts
  packages/phrases/src/locales/es/translation/admin-console/applications.ts
  packages/phrases/src/locales/fr/translation/admin-console/applications.ts
  packages/phrases/src/locales/it/translation/admin-console/applications.ts
  packages/phrases/src/locales/ja/translation/admin-console/applications.ts
  packages/phrases/src/locales/ko/translation/admin-console/applications.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/applications.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/applications.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/applications.ts
  packages/phrases/src/locales/ru/translation/admin-console/applications.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/applications.ts
Labels: feature, size/s

#5305 feat(console): add the user permission tooltips
  packages/console/src/ds-components/Button/index.module.scss
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/index.module.scss
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/use-scopes-table.tsx
  packages/phrases/src/locales/de/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/es/translation/admin-console/application-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/it/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/application-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts
Labels: feature, size/s

#5301 refactor(console): remove pro tag from app category filter
  packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
Labels: enhancement, size/s

#5306 chore(phrases): update application content
  packages/phrases/src/locales/de/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/applications.ts
  packages/phrases/src/locales/es/translation/admin-console/application-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/it/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/application-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts
Labels: chore, size/s

#5309 fix(core): get tenant endpoint
  packages/core/src/libraries/protected-app.ts
Labels: bugfix, size/xs

#5308 fix(core): fix protected app callback uri
  packages/core/src/__mocks__/index.ts
  packages/core/src/constants/index.ts
  packages/core/src/libraries/protected-app.test.ts
  packages/core/src/libraries/protected-app.ts
  packages/core/src/routes/applications/application-protected-app-metadata.test.ts
  packages/core/src/routes/applications/application-protected-app-metadata.ts
  packages/core/src/routes/applications/application.test.ts
Labels: bugfix, size/s

#5245 feat: create invitation
  .changeset/good-stingrays-perform.md
  .changeset/strange-seals-poke.md
  .changeset/thin-bags-admire.md
  .changeset/tidy-phones-warn.md
  .changeset/twelve-carrots-do.md
  packages/connectors/connector-aliyun-dm/src/index.test.ts
  packages/connectors/connector-aliyun-dm/src/index.ts
  packages/connectors/connector-aliyun-dm/src/mock.ts
  packages/connectors/connector-aliyun-sms/src/index.test.ts
  packages/connectors/connector-aws-ses/src/index.test.ts
  packages/connectors/connector-aws-ses/src/mock.ts
  packages/connectors/connector-aws-ses/src/types.ts
  packages/connectors/connector-aws-ses/src/utils.ts
  packages/connectors/connector-logto-email/src/index.test.ts
  packages/connectors/connector-logto-email/src/index.ts
  packages/connectors/connector-logto-sms/src/index.test.ts
  packages/connectors/connector-mailgun/src/index.test.ts
  packages/connectors/connector-mailgun/src/index.ts
  packages/connectors/connector-mailgun/src/type.test.ts
  packages/connectors/connector-mailgun/src/types.ts
  packages/connectors/connector-sendgrid-email/src/index.test.ts
  packages/connectors/connector-sendgrid-email/src/index.ts
  packages/connectors/connector-smsaero/src/index.test.ts
  packages/connectors/connector-smsaero/src/index.ts
  packages/connectors/connector-smtp/src/index.test.ts
  packages/connectors/connector-smtp/src/index.ts
  packages/connectors/connector-smtp/src/mock.ts
  packages/connectors/connector-tencent-sms/src/index.test.ts
  packages/connectors/connector-tencent-sms/src/index.ts
  packages/connectors/connector-twilio-sms/src/index.ts
  packages/core/src/__mocks__/index.ts
  packages/core/src/libraries/connector.ts
  packages/core/src/libraries/organization-invitation.ts
  packages/core/src/libraries/passcode.test.ts
  packages/core/src/libraries/passcode.ts
  packages/core/src/queries/magic-link.ts
  packages/core/src/queries/organization/index.ts
  packages/core/src/queries/passcode.test.ts
  packages/core/src/queries/passcode.ts
  packages/core/src/routes-me/verification-code.ts
  packages/core/src/routes/connector/config-testing.test.ts
  packages/core/src/routes/connector/config-testing.ts
  packages/core/src/routes/interaction/utils/verification-code-validation.test.ts
  packages/core/src/routes/interaction/utils/verification-code-validation.ts
  packages/core/src/routes/organization/invitations.openapi.json
  packages/core/src/routes/organization/invitations.ts
  packages/core/src/routes/verification-code.test.ts
  packages/core/src/routes/verification-code.ts
  packages/core/src/tenants/Libraries.ts
  packages/integration-tests/src/tests/api/interaction/api-counter-cases/post-send-verification-code.test.ts
  packages/integration-tests/src/tests/api/swagger-check.test.ts
  packages/integration-tests/src/tests/api/verification-code.test.ts
  packages/toolkit/connector-kit/src/index.test.ts
  packages/toolkit/connector-kit/src/index.ts
  packages/toolkit/connector-kit/src/types/error.ts
  packages/toolkit/connector-kit/src/types/passwordless.ts
Labels: feature, size/xl

#5278 refactor(schemas): allow null inviter
  packages/schemas/alterations/next-1705991158-update-invitation-indices.ts
  packages/schemas/tables/organization_invitations.sql
Labels: enhancement, size/s

#5310 refactor(console): improve app creation page empty state layout
  packages/console/src/components/EmptyDataPlaceholder/index.module.scss
  packages/console/src/components/EmptyDataPlaceholder/index.tsx
  packages/console/src/pages/Applications/components/GuideLibrary/index.module.scss
  packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
  packages/console/src/pages/Applications/components/GuideLibraryModal/index.tsx
  packages/console/src/pages/Applications/components/ProtectedAppCard/index.module.scss
  packages/console/src/pages/Applications/components/ProtectedAppCard/index.tsx
  packages/console/src/pages/Applications/index.module.scss
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/scss/page-layout.module.scss
  packages/console/src/types/applications.ts
Labels: enhancement, size/s

#5312 fix(console): only request protected app domain if it is cloud and has dev features enabled
  packages/console/src/pages/Applications/components/ProtectedAppForm/index.tsx
Labels: bugfix, size/xs

#5299 fix(console): reset applicaiton form data with parsed data
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
Labels: bugfix, size/xs

#5298 refactor(console): update token charge info tip
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/renderers/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-table.ts
Labels: enhancement, size/s

#5297 refactor(console): remove dev tenant notification
  packages/console/src/pages/GetStarted/DevelopmentTenantNotification/index.module.scss
  packages/console/src/pages/GetStarted/DevelopmentTenantNotification/index.tsx
  packages/console/src/pages/GetStarted/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/tenants.ts
  packages/phrases/src/locales/en/translation/admin-console/tenants.ts
  packages/phrases/src/locales/es/translation/admin-console/tenants.ts
  packages/phrases/src/locales/fr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/it/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ja/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ko/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ru/translation/admin-console/tenants.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tenants.ts
Labels: enhancement, size/m

#5307 fix(console): fix m2m app log not accessible bug
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/pages/AuditLogDetails/index.tsx
  packages/integration-tests/src/api/api.ts
  packages/integration-tests/src/api/application.ts
  packages/integration-tests/src/tests/console/applications/index.test.ts
Labels: bugfix, size/s

#5319 fix(toolkit): domain regex should allow short subdomain and top-level domain
  packages/toolkit/core-kit/src/regex.test.ts
  packages/toolkit/core-kit/src/regex.ts
Labels: bugfix, size/s

#5317 fix(console): external link should use to the correct URL in protected app details
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/index.tsx
Labels: bugfix, size/s

#5321 style(console): fix the app creation modal size
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
Labels: size/xs

#5324 refactor: add invitation api tests
  packages/core/src/libraries/organization-invitation.ts
  packages/core/src/queries/organization/index.ts
  packages/core/src/routes/organization/invitations.ts
  packages/core/src/utils/SchemaRouter.ts
  packages/integration-tests/src/api/organization-invitation.ts
  packages/integration-tests/src/helpers/organization.ts
  packages/integration-tests/src/tests/api/organization/organization-invitation.test.ts
  packages/schemas/alterations/next-1706449174-update-organization-invitation-column.ts
  packages/schemas/tables/organization_invitation_role_relations.sql
Labels: enhancement, size/l

#5323 fix(console): add dot before protected app first-level domain
  packages/console/src/pages/Applications/components/ProtectedAppForm/index.tsx
Labels: bugfix, size/xs

#5320 feat(experience): hide the path and parameter in redirectUri
  packages/experience/src/pages/Consent/index.tsx
  packages/experience/src/pages/Consent/util.test.ts
  packages/experience/src/pages/Consent/util.ts
Labels: feature, size/s

#5318 fix(console): should hide personal user data row if is empty
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/use-scopes-table.tsx
Labels: bugfix, size/xs

#5315 fix(experience): fix the organization selector position
  packages/experience/src/pages/Consent/OrganizationSelector/OrganizationSelectorModal/index.tsx
Labels: bugfix, size/s

#5316 style(experience): fix the terms padding
  packages/experience/src/pages/Consent/ScopesListCard/index.module.scss
Labels: size/xs

#5331 feat(console): hide m2m and third-party app in the empty app list guide
  packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
  packages/integration-tests/src/tests/console/applications/helpers.ts
  packages/integration-tests/src/tests/console/applications/index.test.ts
Labels: feature, size/s

#5322 fix(core): include m2m apps in application limit
  packages/core/src/libraries/quota.ts
  packages/core/src/queries/application.ts
Labels: bugfix, size/s

#5325 refactor(core): remove default page rules
  packages/core/src/__mocks__/index.ts
  packages/core/src/routes/applications/constants.ts
Labels: enhancement, size/xs

#5240 chore(core): show errors of storage provider
  packages/core/src/routes/user-assets.ts
Labels: chore, size/xs

#5313 refactor(console): update next guide
  packages/console/src/assets/docs/guides/web-next/README.mdx
Labels: enhancement, size/s

#5314 refactor(console): update express guide
  packages/console/src/assets/docs/guides/web-express/README.mdx
Labels: enhancement, size/s

#5326 fix(core,schemas): use database index to prevent subdomain conflict
  packages/core/src/libraries/protected-app.test.ts
  packages/core/src/libraries/protected-app.ts
  packages/core/src/middleware/koa-slonik-error-handler.test.ts
  packages/core/src/middleware/koa-slonik-error-handler.ts
  packages/core/src/queries/application.test.ts
  packages/core/src/queries/application.ts
  packages/core/src/routes/applications/application.test.ts
  packages/core/src/routes/applications/application.ts
  packages/schemas/alterations/next-1706510290-protected-app-host-index.ts
  packages/schemas/tables/applications.sql
Labels: bugfix, size/m

#5327 refactor(console,schemas): bring back hidden get-started page
  packages/console/src/containers/ConsoleContent/Sidebar/hook.tsx
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/hooks/use-user-preferences.ts
  packages/schemas/alterations/next-1706512952-restore-get-started-page.ts
Labels: enhancement, size/s

#5328 fix(console): fix error handling on creating protected apps
  packages/console/src/pages/Applications/components/ProtectedAppForm/index.tsx
Labels: bugfix, size/s

#5332 fix(phrases,shared): only allow lowercase letters, numbers and hyphens in subdomains
  packages/phrases/src/locales/de/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/en/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/es/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/fr/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/it/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/ja/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/ko/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/ru/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/protected-app.ts
  packages/shared/src/utils/sub-domain.test.ts
  packages/shared/src/utils/sub-domain.ts
Labels: bugfix, size/s

#5333 refactor(console,phrases): protected app origin url should not contain pathname
  packages/console/src/pages/Applications/components/ProtectedAppForm/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/application-details.ts
  packages/phrases/src/locales/de/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/es/translation/admin-console/application-details.ts
  packages/phrases/src/locales/es/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/it/translation/admin-console/application-details.ts
  packages/phrases/src/locales/it/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/ja/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/ru/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/protected-app.ts
Labels: enhancement, size/s

#5334 refactor(console,phrases): show notification when modify origin url in protected app details
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/en/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/es/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/fr/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/it/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/ja/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/ko/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/ru/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/protected-app.ts
Labels: enhancement, size/s

#5337 fix(console): should navigate to details page after creating protected app
  packages/console/src/pages/Applications/components/ProtectedAppForm/index.tsx
Labels: bugfix, size/xs

#5330 feat(core): put invitation status
  packages/app-insights/package.json
  packages/cli/package.json
  packages/connectors/templates/package.json
  packages/console/package.json
  packages/core/package.json
  packages/core/src/libraries/organization-invitation.ts
  packages/core/src/queries/organization/index.ts
  packages/core/src/routes/organization/invitations.openapi.json
  packages/core/src/routes/organization/invitations.ts
  packages/experience/package.json
  packages/integration-tests/package.json
  packages/integration-tests/src/api/organization-invitation.ts
  packages/integration-tests/src/tests/api/organization/organization-invitation.creation.test.ts
  packages/integration-tests/src/tests/api/organization/organization-invitation.status.test.ts
  packages/phrases-experience/package.json
  packages/phrases/package.json
  packages/schemas/package.json
  packages/schemas/src/types/organization.ts
  packages/shared/package.json
  packages/toolkit/connector-kit/package.json
  packages/toolkit/core-kit/package.json
  pnpm-lock.yaml
Labels: feature, size/l

#5335 refactor: remove magic links
  packages/core/src/database/utils.ts
  packages/core/src/libraries/organization-invitation.ts
  packages/core/src/queries/magic-link.ts
  packages/core/src/queries/organization/index.ts
  packages/core/src/routes/organization/invitations.openapi.json
  packages/core/src/routes/organization/invitations.ts
  packages/integration-tests/src/api/organization-invitation.ts
  packages/integration-tests/src/helpers/organization.ts
  packages/integration-tests/src/tests/api/organization/organization-invitation.creation.test.ts
  packages/integration-tests/src/tests/api/organization/organization-invitation.status.test.ts
  packages/schemas/alterations/next-1706528755-remove-magic-links.ts
  packages/schemas/src/types/organization.ts
  packages/schemas/tables/magic_links.sql
  packages/schemas/tables/organization_invitations.sql
Labels: enhancement, size/l

#5338 refactor!: update mock connector file paths
  .changeset/clean-peaches-run.md
  .changeset/two-moles-hope.md
  packages/connectors/connector-mock-email-alternative/src/index.ts
  packages/connectors/connector-mock-email/src/index.ts
  packages/connectors/connector-mock-sms/src/index.ts
  packages/core/src/libraries/organization-invitation.ts
  packages/integration-tests/src/helpers/index.ts
  packages/integration-tests/src/helpers/interactions.ts
  packages/integration-tests/src/tests/api/interaction/forgot-password/happy-path.test.ts
  packages/integration-tests/src/tests/api/interaction/forgot-password/sad-path.test.ts
  packages/integration-tests/src/tests/api/interaction/register-with-identifier/happy-path.test.ts
  packages/integration-tests/src/tests/api/interaction/register-with-identifier/sad-path.test.ts
  packages/integration-tests/src/tests/api/interaction/register-with-identifier/single-sign-on.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-passcode-identifier/happy-path.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-passcode-identifier/sad-path.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-passcode-identifier/single-sign-on.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier/happy-path.test.ts
  packages/integration-tests/src/tests/api/verification-code.test.ts
  packages/integration-tests/src/tests/experience/mfa/totp/add-missing-profile-flow.test.ts
  packages/integration-tests/src/tests/experience/mfa/totp/passcode-identifier-flow.test.ts
  packages/integration-tests/src/tests/experience/password-policy.test.ts
  packages/integration-tests/src/ui-helpers/expect-experience.ts
  packages/toolkit/connector-kit/src/index.ts
Labels: enhancement, size/l

#5340 refactor: update organization invitation api connector payload
  packages/core/src/libraries/organization-invitation.ts
  packages/integration-tests/src/__mocks__/connectors-mock.ts
  packages/integration-tests/src/api/organization-invitation.ts
  packages/integration-tests/src/helpers/index.ts
  packages/integration-tests/src/tests/api/organization/organization-invitation.creation.test.ts
Labels: enhancement, size/s

#5345 feat(console,phrases): add feature tag and pricing table
  packages/console/package.json
  packages/console/src/components/FeatureTag/BetaTag.tsx
  packages/console/src/components/FeatureTag/index.module.scss
  packages/console/src/components/FeatureTag/index.tsx
  packages/console/src/components/Guide/GuideCard/index.module.scss
  packages/console/src/components/Guide/GuideCard/index.tsx
  packages/console/src/consts/plan-quotas.ts
  packages/console/src/consts/quota-item-phrases.ts
  packages/console/src/consts/tenants.ts
  packages/console/src/ds-components/Checkbox/Checkbox/index.module.scss
  packages/console/src/ds-components/Checkbox/CheckboxGroup/index.tsx
  packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/PlanQuotaKeyLabel/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/renderers/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-table.ts
  pnpm-lock.yaml
Labels: feature, size/l

#5346 feat(console,phrases): implement quota guard footer
  packages/console/src/hooks/use-applications-usage.ts
  packages/console/src/pages/Applications/components/CreateForm/Footer/index.tsx
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/en/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/es/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/fr/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/it/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/ja/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/ko/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/ru/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/upsell/paywall.ts
Labels: feature, size/s

#5342 fix(core,schemas): use database index to prevent custom domain conflict
  packages/core/src/middleware/koa-slonik-error-handler.test.ts
  packages/core/src/middleware/koa-slonik-error-handler.ts
  packages/core/src/queries/application.test.ts
  packages/core/src/queries/application.ts
  packages/core/src/routes/applications/application-protected-app-metadata.test.ts
  packages/core/src/routes/applications/application-protected-app-metadata.ts
  packages/schemas/alterations/next-1706585206-protected-app-custom-domain-unique.ts
  packages/schemas/tables/applications.sql
Labels: bugfix, size/m

#5350 feat(console): update the tenant creation plan modal
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/FeaturedPlanQuotaList/index.tsx
Labels: feature, size/xs

#5353 feat(console): add quota guard to protected app creation form
  packages/console/src/pages/Applications/components/ProtectedAppForm/index.tsx
  packages/console/src/pages/GetStarted/ProtectedAppCreationForm/index.module.scss
  packages/console/src/pages/GetStarted/ProtectedAppCreationForm/index.tsx
Labels: feature, size/s

#5351 fix(console): improve "try it" button style in protected app details page
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/index.module.scss
  packages/toolkit/core-kit/scss/_console-themes.scss
Labels: bugfix, size/s

#5352 feat(console,phrases): add verify JWT notice in protected app details page
  packages/console/src/assets/icons/alert.svg
  packages/console/src/ds-components/InlineNotification/index.module.scss
  packages/console/src/ds-components/InlineNotification/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/es/translation/admin-console/application-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/it/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/application-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts
Labels: feature, size/s
