Repository logto-io/logto, pull requests merged in 2024-10, with the labels that each got.

#6641 feat(core): trigger webhook event in profile api
  packages/core/src/routes/init.ts
  packages/core/src/routes/profile/index.ts
  packages/core/src/routes/types.ts
  packages/core/src/routes/verification/index.ts
  packages/integration-tests/src/api/api.ts
  packages/integration-tests/src/helpers/profile.ts
  packages/integration-tests/src/tests/api/profile/index.test.ts
Labels: feature, size/m

#6646 fix(core): expose syntax error response
  packages/core/src/middleware/koa-error-handler.ts
Labels: bugfix, size/xs

#6643 feat(core): add and change primary email
  packages/core/src/libraries/verification.ts
  packages/core/src/queries/verification-records.ts
  packages/core/src/routes/profile/index.openapi.json
  packages/core/src/routes/profile/index.ts
  packages/core/src/routes/verification/index.openapi.json
  packages/core/src/routes/verification/index.ts
  packages/integration-tests/src/api/profile.ts
  packages/integration-tests/src/api/verification-record.ts
  packages/integration-tests/src/helpers/profile.ts
  packages/integration-tests/src/tests/api/profile/email-and-phone.test.ts
  packages/integration-tests/src/tests/api/profile/index.test.ts
  packages/phrases/src/locales/en/errors/verification-record.ts
Labels: feature, size/xl

#6649 feat(core): check password policy before changing password
  packages/core/src/routes/profile/index.ts
  packages/integration-tests/src/tests/api/profile/index.test.ts
Labels: feature, size/s

#6650 feat(core): get user profile
  packages/core/src/routes/profile/index.openapi.json
  packages/core/src/routes/profile/index.ts
  packages/core/src/routes/profile/utils/get-scoped-profile.ts
  packages/integration-tests/src/api/profile.ts
  packages/integration-tests/src/tests/api/profile/email-and-phone.test.ts
  packages/integration-tests/src/tests/api/profile/index.test.ts
Labels: feature, size/m

#6665 refactor: align cloud API response type definition
  packages/console/src/cloud/types/router.ts
  packages/core/src/utils/subscription/types.ts
Labels: enhancement, size/s

#6642 fix(core): forgot password on the first access of migrated users
  packages/core/src/routes/interaction/verifications/profile-verification.forgot-password.test.ts
  packages/core/src/routes/interaction/verifications/profile-verification.ts
Labels: bugfix, size/s

#6667 refactor(core): update Cloud API response type definition
  packages/core/src/utils/subscription/types.ts
Labels: enhancement, size/xs

#6655 chore: fix typo in README.md
  README.md
Labels: chore, size/xs

#6664 refactor: move has{Reach,Surpass}Limit method to subscription context
  packages/console/src/components/CreateConnectorForm/Footer/index.tsx
  packages/console/src/containers/AppContent/index.tsx
  packages/console/src/contexts/SubscriptionDataProvider/index.tsx
  packages/console/src/contexts/SubscriptionDataProvider/types.ts
  packages/console/src/contexts/SubscriptionDataProvider/utils.ts
  packages/console/src/hooks/use-api-resources-usage.ts
  packages/console/src/hooks/use-applications-usage.ts
  packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx
  packages/console/src/pages/RoleDetails/RolePermissions/components/AssignPermissionsModal/index.tsx
  packages/console/src/pages/Roles/components/CreateRoleForm/Footer.tsx
  packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/hooks.ts
  packages/console/src/pages/Webhooks/CreateFormModal/CreateForm.tsx
  packages/console/src/utils/quota.ts
Labels: enhancement, size/l

#6659 feat(schemas): add SAML SSO IdP initated auth config table
  packages/schemas/alterations/next-1728357690-add-sso-connector-idp-initated-auth-configs-table.ts
  packages/schemas/src/foundations/jsonb-types/sso-connector.ts
  packages/schemas/tables/sso_connector_idp_initiated_auth_configs.sql
Labels: feature, size/s

#6660 feat(core,schemas): add sso idp initiated auth config api
  packages/core/src/libraries/sign-in-experience/index.test.ts
  packages/core/src/libraries/sso-connector.ts
  packages/core/src/queries/sso-connectors.ts
  packages/core/src/routes/interaction/utils/single-sign-on-guard.test.ts
  packages/core/src/routes/sso-connector/idp-initiated-auth-config.openapi.json
  packages/core/src/routes/sso-connector/idp-initiated-auth-config.ts
  packages/core/src/routes/sso-connector/index.ts
  packages/integration-tests/src/api/sso-connector.ts
  packages/integration-tests/src/tests/api/sso-connectors/sso-connector-idp-initiated-auth-config.test.ts
  packages/integration-tests/src/tests/api/sso-connectors/sso-connectors.test.ts
  packages/phrases/src/locales/en/errors/connector.ts
  packages/schemas/src/foundations/jsonb-types/sso-connector.ts
Labels: feature, size/l

#6662 feat(core): add patch and delete SAML IdP initiated config API
  packages/core/src/libraries/sign-in-experience/index.test.ts
  packages/core/src/libraries/sso-connector.ts
  packages/core/src/queries/sso-connectors.ts
  packages/core/src/routes/interaction/utils/single-sign-on-guard.test.ts
  packages/core/src/routes/sso-connector/idp-initiated-auth-config.openapi.json
  packages/core/src/routes/sso-connector/idp-initiated-auth-config.ts
  packages/integration-tests/src/api/sso-connector.ts
  packages/integration-tests/src/tests/api/sso-connectors/sso-connector-idp-initiated-auth-config.test.ts
Labels: feature, size/l

#6663 feat(schemas): add IdP initiated SAML SSO sessions table
  packages/schemas/alterations/next-1728526649-add-idp-initiated-saml-sso-sessions-table.ts
  packages/schemas/src/foundations/jsonb-types/sso-connector.ts
  packages/schemas/tables/idp_initiated_saml_sso_sessions.sql
Labels: feature, size/s

#6666 feat(core): handle idp initiated saml assertion request
  packages/core/src/constants/index.ts
  packages/core/src/libraries/sign-in-experience/index.test.ts
  packages/core/src/libraries/sso-connector.ts
  packages/core/src/queries/sso-connectors.ts
  packages/core/src/routes/authn.ts
  packages/core/src/routes/interaction/utils/single-sign-on-guard.test.ts
  packages/core/src/sso/SamlConnector/index.ts
  packages/core/src/sso/SamlConnector/utils.ts
  packages/integration-tests/src/__mocks__/sso-connectors-mock.ts
  packages/integration-tests/src/api/sso-connector.ts
  packages/integration-tests/src/tests/api/authn.test.ts
  packages/integration-tests/src/tests/api/interaction/single-sign-on/sad-path.test.ts
  packages/schemas/src/foundations/jsonb-types/sso-connector.ts
Labels: feature, size/l

#6668 feat(core,schemas): init auth flow for IdP initiated SAML SSO
  packages/core/package.json
  packages/core/src/libraries/sign-in-experience/index.test.ts
  packages/core/src/libraries/sso-connector.test.ts
  packages/core/src/libraries/sso-connector.ts
  packages/core/src/routes/authn.ts
  packages/core/src/routes/interaction/utils/single-sign-on-guard.test.ts
  packages/core/src/test-utils/mock-libraries.ts
  packages/integration-tests/src/tests/api/sso-connectors/sso-connector-idp-initiated-auth-config.test.ts
  packages/schemas/src/foundations/jsonb-types/sso-connector.ts
  pnpm-lock.yaml
Labels: feature, size/l

#6669 feat(core): consume IdP initiated session on SSO verification flow
  packages/core/src/__mocks__/sso.ts
  packages/core/src/libraries/sso-connector.test.ts
  packages/core/src/libraries/sso-connector.ts
  packages/core/src/queries/sso-connectors.ts
  packages/core/src/routes/interaction/utils/single-sign-on.test.ts
  packages/core/src/routes/interaction/utils/single-sign-on.ts
  packages/core/src/utils/test-utils.ts
Labels: feature, size/l

#6651 feat(core): update other profile data
  packages/core/src/routes/profile/index.openapi.json
  packages/core/src/routes/profile/index.ts
  packages/integration-tests/src/api/profile.ts
  packages/integration-tests/src/tests/api/profile/index.test.ts
Labels: feature, size/m

#6683 chore(account-elements): setup account elements project
  commitlint.config.ts
  packages/account-elements/README.md
  packages/account-elements/index.html
  packages/account-elements/package.json
  packages/account-elements/src/index.ts
  packages/account-elements/src/providers/logto-account-provider.ts
  packages/account-elements/src/react.ts
  packages/account-elements/tsconfig.json
  packages/account-elements/tsup.config.ts
  packages/account-elements/web-dev-server.config.js
  pnpm-lock.yaml
Labels: chore, size/m

#6684 feat(account-elements): add initial account api
  packages/account-elements/src/api/index.ts
  packages/account-elements/src/index.ts
  packages/account-elements/src/react.ts
Labels: feature, size/s

#6633 release: @logto/core-kit:2.5.1 and @logto/tunnel:0.2.1
  .changeset/tricky-mice-pay.md
  .changeset/violet-ligers-carry.md
  packages/toolkit/core-kit/CHANGELOG.md
  packages/toolkit/core-kit/package.json
  packages/tunnel/CHANGELOG.md
  packages/tunnel/package.json
Labels: size/s

#6675 feat(schemas): add idp-initiated SSO client side callback url columns
  packages/core/src/libraries/sso-connector.test.ts
  packages/schemas/alterations/next-1728887713-add-client-idp-initiated-auth-callback-uri-columns.ts
  packages/schemas/tables/sso_connector_idp_initiated_auth_configs.sql
Labels: feature, size/s

#6681 feat(core): add idp-initiated sso client sign-in redirect
  packages/core/src/routes/authn.ts
  packages/phrases/src/locales/en/errors/single-sign-on.ts
  packages/schemas/src/types/sso-connector.ts
Labels: feature, size/s

#6688 feat(console): add idp-initiated sso config page
  packages/console/src/consts/page-tabs.ts
  packages/console/src/ds-components/Select/index.module.scss
  packages/console/src/ds-components/Select/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/IdpInitiatedAuth/ConfigForm.tsx
  packages/console/src/pages/EnterpriseSsoDetails/IdpInitiatedAuth/index.module.scss
  packages/console/src/pages/EnterpriseSsoDetails/IdpInitiatedAuth/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/IdpInitiatedAuth/use-idp-initiated-auth-config-swr.ts
  packages/console/src/pages/EnterpriseSsoDetails/IdpInitiatedAuth/utils.ts
  packages/console/src/pages/EnterpriseSsoDetails/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/en/translation/admin-console/errors.ts
Labels: feature, size/xl

#6682 feat(core): add and change phone
  packages/core/src/routes/profile/index.openapi.json
  packages/core/src/routes/profile/index.ts
  packages/core/src/routes/verification/index.ts
  packages/integration-tests/src/api/profile.ts
  packages/integration-tests/src/tests/api/profile/email-and-phone.test.ts
Labels: feature, size/m

#6686 feat(core): add expiresAt in response of verification record creation
  packages/core/src/routes/verification/index.openapi.json
  packages/core/src/routes/verification/index.ts
  packages/integration-tests/src/api/verification-record.ts
Labels: feature, size/s

#6674 feat(core): database connection timeout env overwrite support (#6187)
  .changeset/fifty-apes-arrive.md
  packages/core/src/env-set/create-pool.ts
  packages/core/src/env-set/index.ts
  packages/shared/src/node/env/GlobalValues.ts
Labels: feature, size/s

#6691 feat(connector): add gatewayapi connector
  packages/connectors/connector-gatewayapi-sms/README.md
  packages/connectors/connector-gatewayapi-sms/logo.svg
  packages/connectors/connector-gatewayapi-sms/package.json
  packages/connectors/connector-gatewayapi-sms/src/constant.ts
  packages/connectors/connector-gatewayapi-sms/src/index.test.ts
  packages/connectors/connector-gatewayapi-sms/src/index.ts
  packages/connectors/connector-gatewayapi-sms/src/mock.ts
  packages/connectors/connector-gatewayapi-sms/src/types.ts
  pnpm-lock.yaml
Labels: feature, size/l

#6689 refactor(console,core): remove `isAddOnAvailable`
  packages/console/src/components/ApplicationCreation/CreateForm/Footer/index.tsx
  packages/console/src/components/ApplicationCreation/CreateForm/index.tsx
  packages/console/src/components/FeatureTag/index.tsx
  packages/console/src/components/PlanUsage/index.tsx
  packages/console/src/pages/ApiResources/components/CreateForm/Footer.tsx
  packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
  packages/console/src/pages/EnterpriseSso/SsoCreationModal/index.tsx
  packages/console/src/pages/EnterpriseSso/index.tsx
  packages/console/src/pages/Mfa/PageWrapper/index.tsx
  packages/console/src/pages/Organizations/CreateOrganizationModal/index.tsx
  packages/console/src/pages/Organizations/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/index.tsx
  packages/core/src/libraries/quota.ts
  packages/core/src/utils/subscription/index.ts
  pnpm-lock.yaml
Labels: enhancement, size/m

#6701 chore: launch au region
  packages/console/src/components/CreateTenantModal/index.tsx
Labels: chore, size/s

#6695 fix(console): fix enterprise tenants not displayed issue
  packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx
Labels: bugfix, size/s

#6697 fix(console): manually update tenant data when data get updated
  packages/console/src/contexts/SubscriptionDataProvider/use-new-subscription-data.ts
  packages/console/src/pages/CheckoutSuccessCallback/index.tsx
  packages/console/src/pages/TenantSettings/BillingHistory/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/index.tsx
Labels: bugfix, size/s

#6704 fix(console): fix inf loop for updating tenant context
  packages/console/src/pages/TenantSettings/Subscription/index.tsx
Labels: bugfix, size/s

#6698 fix(console): fix webhook modal paywall for enterprise plan
  packages/console/src/components/QuotaGuardFooter/index.tsx
  packages/console/src/pages/Webhooks/CreateFormModal/CreateForm.tsx
Labels: bugfix, size/s

#6690 chore(core): guard idp-initiated sso console and api
  packages/connectors/connector-logto-email/package.json
  packages/console/package.json
  packages/console/src/consts/quota-item-phrases.ts
  packages/console/src/consts/tenants.ts
  packages/console/src/pages/EnterpriseSsoDetails/index.tsx
  packages/core/package.json
  packages/core/src/routes/authn.ts
  packages/core/src/routes/sso-connector/idp-initiated-auth-config.openapi.json
  packages/core/src/routes/sso-connector/idp-initiated-auth-config.ts
  packages/core/src/routes/sso-connector/index.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-item.ts
  pnpm-lock.yaml
Labels: chore, size/s

#6696 fix(console): add applications and redirect uri placeholder
  packages/console/src/pages/EnterpriseSsoDetails/IdpInitiatedAuth/ConfigForm.tsx
  packages/console/src/pages/EnterpriseSsoDetails/IdpInitiatedAuth/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/IdpInitiatedAuth/utils.ts
  packages/phrases/src/locales/en/translation/admin-console/enterprise-sso-details.ts
Labels: bugfix, size/s

#6700 style(console): update radio card style
  packages/console/src/ds-components/RadioGroup/Radio.tsx
  packages/console/src/pages/EnterpriseSsoDetails/IdpInitiatedAuth/ConfigForm.tsx
  packages/console/src/pages/EnterpriseSsoDetails/IdpInitiatedAuth/index.module.scss
  packages/console/src/pages/EnterpriseSsoDetails/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/enterprise-sso-details.ts
Labels: size/s

#6685 feat(elements): introduce basic logto-account-provider
  .github/workflows/main.yml
  packages/elements/package.json
  packages/elements/src/account/__mocks__/account-api.ts
  packages/elements/src/account/providers/logto-account-provider.test.ts
  packages/elements/src/account/providers/logto-account-provider.ts
  packages/elements/web-test-runner.config.js
  pnpm-lock.yaml
Labels: feature, size/m

#6710 fix(console): refactor TenantxContext util methods
  packages/console/src/contexts/SubscriptionDataProvider/use-new-subscription-data.ts
  packages/console/src/contexts/TenantsProvider.tsx
Labels: chore, bugfix, size/s

#6712 chore: bump dependency versions
  packages/connectors/connector-postmark/package.json
  packages/core/package.json
  packages/integration-tests/package.json
  pnpm-lock.yaml
Labels: chore, size/xs

#6723 chore: add changeset of gatewayapi connector
  .changeset/tender-peaches-listen.md
  .changeset/wild-beers-run.md
Labels: chore, size/s

#6719 ci: install playwright for element tests
  .github/workflows/master-codecov-report.yml
Labels: size/xs

#6734 chore: add google connector default prompt
  .changeset/light-clocks-retire.md
  .changeset/tricky-walls-add.md
  packages/connectors/connector-google/src/constant.ts
  packages/console/src/utils/connector-form.ts
Labels: chore, size/s

#6741 refactor(core): refactor social verification class
  packages/core/src/routes/experience/classes/verifications/social-verification.ts
  packages/core/src/routes/verification/index.ts
Labels: enhancement, size/m

#6743 feat(core,console,schemas): add idp-initiated sso session create log
  packages/console/src/consts/logs.ts
  packages/core/src/routes/authn.ts
  packages/schemas/src/types/log/interaction.ts
Labels: feature, size/s

#6724 feat(elements): add logto-username element
  packages/elements/index.html
  packages/elements/src/account/components/logto-icon.ts
  packages/elements/src/account/components/logto-profile-item.ts
  packages/elements/src/account/elements/LogtoProfileItemElement.ts
  packages/elements/src/account/elements/logto-username.test.ts
  packages/elements/src/account/elements/logto-username.ts
  packages/elements/src/account/icons/index.d.ts
  packages/elements/src/account/icons/username.svg
  packages/elements/src/account/index.ts
  packages/elements/src/account/react.ts
  packages/elements/src/account/style.css
Labels: feature, size/l

#6726 feat(elements): add logto-user-email element
  packages/elements/src/account/elements/logto-user-email.test.ts
  packages/elements/src/account/elements/logto-user-email.ts
  packages/elements/src/account/icons/email.svg
  packages/elements/src/account/index.ts
  packages/elements/src/account/react.ts
Labels: feature, size/m

#6728 feat(elements): add logto-user-password element
  packages/elements/src/account/elements/logto-user-password.test.ts
  packages/elements/src/account/elements/logto-user-password.ts
  packages/elements/src/account/icons/password.svg
  packages/elements/src/account/index.ts
  packages/elements/src/account/react.ts
Labels: feature, size/m

#6687 refactor(core): use template type for code verification
  packages/connectors/connector-logto-email/src/index.ts
  packages/core/src/routes/experience/classes/experience-interaction.test.ts
  packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.test.ts
  packages/core/src/routes/experience/classes/verifications/code-verification.ts
  packages/core/src/routes/experience/verification-routes/verification-code.ts
  packages/core/src/routes/verification/index.ts
  packages/integration-tests/src/__mocks__/connectors-mock.ts
  packages/toolkit/connector-kit/src/types/passwordless.ts
Labels: enhancement, size/s

#6749 fix(core,console): show custom jwt error logs
  packages/console/src/consts/logs.ts
  packages/core/src/queries/log.ts
  packages/core/src/routes/log.test.ts
  packages/core/src/routes/log.ts
Labels: bugfix, size/s

#6732 feat(elements): add logto-user-phone element
  packages/elements/package.json
  packages/elements/src/account/elements/logto-user-phone.test.ts
  packages/elements/src/account/elements/logto-user-phone.ts
  packages/elements/src/account/icons/phone.svg
  packages/elements/src/account/index.ts
  packages/elements/src/account/react.ts
  packages/elements/src/account/utils/format.ts
  pnpm-lock.yaml
Labels: feature, size/m

#6736 feat(elements): add logto-social-identity element
  packages/elements/src/account/components/logto-identity-info.ts
  packages/elements/src/account/elements/logto-social-identity.test.ts
  packages/elements/src/account/elements/logto-social-identity.ts
  packages/elements/src/account/icons/fallback-avatar.svg
  packages/elements/src/account/index.ts
  packages/elements/src/account/react.ts
Labels: feature, size/m

#6737 feat(elements): add logto-account-center element
  packages/elements/index.html
  packages/elements/src/account/elements/logto-account-center.test.ts
  packages/elements/src/account/elements/logto-account-center.ts
  packages/elements/src/account/index.ts
  packages/elements/src/account/react.ts
Labels: feature, size/m

#6703 feat(core): add social identity
  packages/core/src/libraries/user.ts
  packages/core/src/routes/experience/classes/verifications/social-verification.ts
  packages/core/src/routes/profile/index.openapi.json
  packages/core/src/routes/profile/index.ts
  packages/core/src/routes/verification/index.openapi.json
  packages/core/src/routes/verification/index.ts
  packages/integration-tests/src/api/profile.ts
  packages/integration-tests/src/api/verification-record.ts
  packages/integration-tests/src/tests/api/profile/social.test.ts
  packages/phrases/src/locales/en/errors/verification-record.ts
Labels: feature, size/xl

#6738 chore(deps): update postcss-modules version
  packages/console/package.json
  packages/experience-legacy/package.json
  packages/experience/package.json
  pnpm-lock.yaml
Labels: chore, size/xs

#6709 feat(core): remove social identity
  packages/core/src/routes/profile/index.openapi.json
  packages/core/src/routes/profile/index.ts
  packages/integration-tests/src/api/profile.ts
  packages/integration-tests/src/tests/api/profile/social.test.ts
Labels: feature, size/m

#6733 chore(deps): update tsup dependency version
  package.json
  packages/connectors/connector-alipay-native/package.json
  packages/connectors/connector-alipay-web/package.json
  packages/connectors/connector-aliyun-dm/package.json
  packages/connectors/connector-aliyun-sms/package.json
  packages/connectors/connector-apple/package.json
  packages/connectors/connector-aws-ses/package.json
  packages/connectors/connector-azuread/package.json
  packages/connectors/connector-dingtalk-web/package.json
  packages/connectors/connector-discord/package.json
  packages/connectors/connector-facebook/package.json
  packages/connectors/connector-feishu-web/package.json
  packages/connectors/connector-gatewayapi-sms/package.json
  packages/connectors/connector-github/package.json
  packages/connectors/connector-gitlab/package.json
  packages/connectors/connector-google/package.json
  packages/connectors/connector-http-email/package.json
  packages/connectors/connector-huggingface/package.json
  packages/connectors/connector-kakao/package.json
  packages/connectors/connector-kook/package.json
  packages/connectors/connector-logto-email/package.json
  packages/connectors/connector-logto-sms/package.json
  packages/connectors/connector-logto-social-demo/package.json
  packages/connectors/connector-mailgun/package.json
  packages/connectors/connector-mock-email-alternative/package.json
  packages/connectors/connector-mock-email/package.json
  packages/connectors/connector-mock-sms/package.json
  packages/connectors/connector-mock-social/package.json
  packages/connectors/connector-naver/package.json
  packages/connectors/connector-oauth2/package.json
  packages/connectors/connector-oidc/package.json
  packages/connectors/connector-patreon/package.json
  packages/connectors/connector-postmark/package.json
  packages/connectors/connector-saml/package.json
  packages/connectors/connector-sendgrid-email/package.json
  packages/connectors/connector-smsaero/package.json
  packages/connectors/connector-smtp/package.json
  packages/connectors/connector-tencent-sms/package.json
  packages/connectors/connector-twilio-sms/package.json
  packages/connectors/connector-wechat-native/package.json
  packages/connectors/connector-wechat-web/package.json
  packages/connectors/connector-wecom/package.json
  packages/core/package.json
  packages/elements/package.json
  packages/integration-tests/package.json
  pnpm-lock.yaml
Labels: chore, size/s

#6740 chore(deps): align the d3-color deps version
  package.json
  pnpm-lock.yaml
Labels: chore, size/xs

#6735 chore(deps): override braces dependency version
  package.json
  pnpm-lock.yaml
Labels: chore, size/xs

#6654 feat(core): initial implementation of user set mfa secrets / codes
  packages/core/src/routes/admin-user/mfa-verification.openapi.json
  packages/core/src/routes/admin-user/mfa-verifications.test.ts
  packages/core/src/routes/admin-user/mfa-verifications.ts
  packages/core/src/routes/interaction/utils/backup-code-validation.ts
  packages/core/src/routes/interaction/utils/totp-validation.test.ts
  packages/core/src/routes/interaction/utils/totp-validation.ts
  packages/phrases/src/locales/en/errors/user.ts
Labels: feature, size/m

#6725 chore: override @75lb/deep-merge package version
  package.json
  pnpm-lock.yaml
Labels: chore, size/xs
