Repository logto-io/logto, pull requests merged in 2024-06, with the labels that each got.

#5962 chore: launch us region
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/index.tsx
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/index.tsx
  packages/console/src/components/CreateTenantModal/index.tsx
  packages/console/src/onboarding/pages/CreateTenant/index.tsx
Labels: chore, size/s

#5963 chore: update links
  packages/console/src/consts/external-links.ts
Labels: chore, size/xs

#5964 fix: use correct `disabled` logic for free plan
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/index.tsx
Labels: bugfix, size/xs

#5957 fix(console): only show m2m role notification for m2m roles
  packages/console/src/pages/RoleDetails/index.tsx
Labels: bugfix, size/s

#5956 refactor(console): make long text breakable in roles page
  packages/console/src/pages/Roles/index.module.scss
  packages/console/src/pages/Roles/index.tsx
Labels: enhancement, size/s

#5968 refactor(console): fix plausible hostname
  packages/console/src/components/Conversion/utils.ts
  packages/console/src/hooks/use-plausible-pageview.ts
Labels: enhancement, size/xs

#5969 feat(console): implement account deletion
  packages/console/src/App.tsx
  packages/console/src/containers/ConsoleRoutes/index.tsx
  packages/console/src/onboarding/index.tsx
  packages/console/src/pages/Profile/containers/DeleteAccountModal/components/DeletionConfirmationModal/index.tsx
  packages/console/src/pages/Profile/containers/DeleteAccountModal/components/FinalConfirmationModal/index.tsx
  packages/console/src/pages/Profile/containers/DeleteAccountModal/components/TenantsIssuesModal/index.tsx
  packages/console/src/pages/Profile/containers/DeleteAccountModal/components/TenantsList/index.module.scss
  packages/console/src/pages/Profile/containers/DeleteAccountModal/components/TenantsList/index.tsx
  packages/console/src/pages/Profile/containers/DeleteAccountModal/index.module.scss
  packages/console/src/pages/Profile/containers/DeleteAccountModal/index.tsx
  packages/console/src/pages/Profile/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/profile.ts
  packages/phrases/src/locales/en/translation/admin-console/profile.ts
  packages/phrases/src/locales/es/translation/admin-console/profile.ts
  packages/phrases/src/locales/fr/translation/admin-console/profile.ts
  packages/phrases/src/locales/it/translation/admin-console/profile.ts
  packages/phrases/src/locales/ja/translation/admin-console/profile.ts
  packages/phrases/src/locales/ko/translation/admin-console/profile.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/profile.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/profile.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/profile.ts
  packages/phrases/src/locales/ru/translation/admin-console/profile.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/profile.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/profile.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/profile.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/profile.ts
Labels: feature, size/xl

#5973 fix(console): avoid skipping m2m role assignment after switching browser tabs
  packages/console/src/components/ApplicationCreation/CreateForm/index.tsx
  packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
  packages/console/src/pages/Applications/components/GuideLibraryModal/index.tsx
  packages/console/src/pages/Applications/index.tsx
Labels: bugfix, size/m

#5974 fix(core): profile avatar upload should not return 400 error
  packages/core/src/routes-me/user-assets.ts
Labels: bugfix, size/xs

#5975 refactor(console,phrases): update rbac-related phrases
  packages/console/src/pages/RoleDetails/RoleApplications/index.tsx
  packages/console/src/pages/RoleDetails/RoleUsers/index.tsx
  packages/console/src/pages/Roles/components/AssignRoleModal/index.tsx
  packages/console/src/pages/Roles/components/CreateRoleModal/index.tsx
  packages/integration-tests/src/tests/console/applications/index.test.ts
  packages/integration-tests/src/tests/console/rbac/helper.ts
  packages/integration-tests/src/tests/console/rbac/machime-to-machime-rbac.test.ts
  packages/integration-tests/src/tests/console/rbac/user-rbac.test.ts
  packages/phrases/src/locales/de/translation/admin-console/application-details.ts
  packages/phrases/src/locales/de/translation/admin-console/role-details.ts
  packages/phrases/src/locales/de/translation/admin-console/user-details.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/role-details.ts
  packages/phrases/src/locales/en/translation/admin-console/user-details.ts
  packages/phrases/src/locales/es/translation/admin-console/application-details.ts
  packages/phrases/src/locales/es/translation/admin-console/role-details.ts
  packages/phrases/src/locales/es/translation/admin-console/user-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/role-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/user-details.ts
  packages/phrases/src/locales/it/translation/admin-console/application-details.ts
  packages/phrases/src/locales/it/translation/admin-console/role-details.ts
  packages/phrases/src/locales/it/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/role-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/role-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/role-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/role-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/role-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/role-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/user-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/role-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/role-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/role-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/role-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/user-details.ts
Labels: enhancement, size/xl

#5976 chore(schemas): add reserved plan ID for admin tenant
  packages/schemas/src/consts/subscriptions.ts
Labels: chore, size/xs

#5978 feat(core): report oidc exceptions to the appInsights
  packages/core/src/middleware/koa-oidc-error-handler.ts
Labels: feature, size/xs

#5981 refactor(console): click console logo should navigate to root page
  packages/console/src/components/Topbar/index.module.scss
  packages/console/src/components/Topbar/index.tsx
Labels: enhancement, size/s

#5980 fix(console): language switch should work on profile page
  packages/console/src/pages/Profile/index.tsx
Labels: bugfix, size/m

#5982 refactor(core): try to catch uncaught exception
  packages/core/src/tenants/Tenant.ts
Labels: enhancement, size/s

#5979 refactor(console): use permanently delete
  packages/console/src/pages/Profile/containers/DeleteAccountModal/components/FinalConfirmationModal/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/profile.ts
Labels: enhancement, size/xs

#5965 refactor(core): optimize redis error handling
  packages/core/package.json
  packages/core/src/caches/index.ts
  pnpm-lock.yaml
Labels: enhancement, size/s

#5977 chore(connector): improve DingTalk web connector readme
  packages/connectors/connector-dingtalk-web/README.md
  pnpm-lock.yaml
Labels: chore, size/s

#5983 chore: remove dev flags and add changeset for m2m guide feature
  .changeset/cool-cows-relax.md
  packages/console/src/components/ApplicationCreation/index.tsx
  packages/console/src/components/RolesTransfer/components/RoleInformation/index.tsx
  packages/console/src/components/RolesTransfer/index.tsx
  packages/console/src/pages/RoleDetails/index.tsx
Labels: chore, size/s

#5947 feat(console): add new feature content for m2m integration guide
  packages/console/src/assets/docs/guides/m2m-general/README.mdx
  packages/console/src/assets/docs/guides/m2m-general/assets/assign-m2m-roles-modal.png
  packages/console/src/assets/docs/guides/m2m-general/assets/assign-m2m-roles-page.png
Labels: feature, size/s

#5988 refactor(console): always display role creation hint in role assignment modal
  packages/console/src/components/ApplicationCreation/index.tsx
  packages/console/src/components/RoleAssignmentModal/index.tsx
  packages/console/src/pages/Roles/components/CreateRoleForm/index.module.scss
  packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
  packages/integration-tests/src/tests/console/rbac/helper.ts
  packages/phrases/src/locales/de/translation/admin-console/roles.ts
  packages/phrases/src/locales/en/translation/admin-console/roles.ts
  packages/phrases/src/locales/es/translation/admin-console/roles.ts
  packages/phrases/src/locales/fr/translation/admin-console/roles.ts
  packages/phrases/src/locales/it/translation/admin-console/roles.ts
  packages/phrases/src/locales/ja/translation/admin-console/roles.ts
  packages/phrases/src/locales/ko/translation/admin-console/roles.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/roles.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/roles.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/roles.ts
  packages/phrases/src/locales/ru/translation/admin-console/roles.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/roles.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/roles.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/roles.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/roles.ts
Labels: enhancement, size/m

#5986 refactor(core,schemas): add user detail payload to User.Deleted webhook event
  .changeset/fuzzy-eyes-add.md
  packages/core/src/libraries/hook/context-manager.ts
  packages/core/src/routes/admin-user/basics.test.ts
  packages/core/src/routes/admin-user/basics.ts
  packages/core/src/routes/well-known.test.ts
  packages/core/src/utils/test-utils.ts
  packages/integration-tests/src/tests/api/hook/hook.trigger.custom.data.test.ts
  packages/integration-tests/src/tests/api/hook/hook.trigger.data.test.ts
  packages/integration-tests/src/tests/api/hook/test-cases.ts
  packages/schemas/src/foundations/jsonb-types/hooks.ts
Labels: enhancement, size/s

#5989 refactor(console,phrases): update role assignment modal phrases
  packages/console/src/components/ApplicationCreation/index.tsx
  packages/console/src/components/RoleAssignmentModal/index.tsx
  packages/integration-tests/src/tests/console/applications/index.test.ts
  packages/integration-tests/src/tests/console/rbac/helper.ts
  packages/phrases/src/locales/de/translation/admin-console/applications.ts
  packages/phrases/src/locales/de/translation/admin-console/roles.ts
  packages/phrases/src/locales/en/translation/admin-console/applications.ts
  packages/phrases/src/locales/en/translation/admin-console/roles.ts
  packages/phrases/src/locales/es/translation/admin-console/applications.ts
  packages/phrases/src/locales/es/translation/admin-console/roles.ts
  packages/phrases/src/locales/fr/translation/admin-console/applications.ts
  packages/phrases/src/locales/fr/translation/admin-console/roles.ts
  packages/phrases/src/locales/it/translation/admin-console/applications.ts
  packages/phrases/src/locales/it/translation/admin-console/roles.ts
  packages/phrases/src/locales/ja/translation/admin-console/applications.ts
  packages/phrases/src/locales/ja/translation/admin-console/roles.ts
  packages/phrases/src/locales/ko/translation/admin-console/applications.ts
  packages/phrases/src/locales/ko/translation/admin-console/roles.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/applications.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/roles.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/applications.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/roles.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/applications.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/roles.ts
  packages/phrases/src/locales/ru/translation/admin-console/applications.ts
  packages/phrases/src/locales/ru/translation/admin-console/roles.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/applications.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/roles.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/roles.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/roles.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/roles.ts
Labels: enhancement, size/m

#5991 refactor(core): reorg organization routes
  packages/core/src/queries/organization/index.ts
  packages/core/src/queries/organization/role-user-relations.ts
  packages/core/src/queries/organization/user-relations.ts
  packages/core/src/routes/organization/index.ts
  packages/core/src/routes/organization/index.user-role-relations.ts
Labels: enhancement, size/l

#5995 feat(core): organization email domains apis
  packages/core/src/queries/organization/email-domains.ts
  packages/core/src/queries/organization/index.ts
  packages/core/src/routes/organization/index.email-domain.openapi.json
  packages/core/src/routes/organization/index.email-domains.ts
  packages/core/src/routes/organization/index.ts
  packages/integration-tests/src/api/organization.ts
  packages/integration-tests/src/tests/api/organization/organization-email-domains.test.ts
Labels: feature, size/l

#5996 feat(core): implement organization jit provisioning
  packages/core/src/libraries/user.ts
  packages/core/src/queries/organization/email-domains.ts
  packages/core/src/routes/organization/index.ts
  packages/integration-tests/src/api/admin-user.ts
  packages/integration-tests/src/helpers/interactions.ts
  packages/integration-tests/src/tests/api/admin-user.organization-jit.test.ts
  packages/integration-tests/src/tests/api/interaction/organization-jit.test.ts
  packages/integration-tests/src/tests/api/interaction/register-with-identifier/happy-path.test.ts
Labels: feature, size/m

#5997 refactor(core): trigger organization membership updated hook from jit
  packages/core/src/libraries/hook/context-manager.ts
  packages/core/src/libraries/hook/index.test.ts
  packages/core/src/libraries/user.ts
  packages/core/src/middleware/koa-management-api-hooks.test.ts
  packages/core/src/middleware/koa-management-api-hooks.ts
  packages/core/src/routes/admin-user/basics.test.ts
  packages/core/src/routes/admin-user/basics.ts
  packages/core/src/routes/admin-user/mfa-verifications.test.ts
  packages/core/src/routes/admin-user/search.test.ts
  packages/core/src/routes/admin-user/social.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.mfa.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/core/src/routes/interaction/middleware/koa-interaction-hooks.ts
  packages/core/src/routes/interaction/single-sign-on.ts
  packages/core/src/routes/interaction/utils/single-sign-on.test.ts
  packages/core/src/routes/interaction/utils/single-sign-on.ts
  packages/core/src/routes/organization/index.email-domains.ts
  packages/core/src/routes/organization/index.ts
  packages/core/src/routes/organization/index.user-role-relations.ts
  packages/core/src/routes/organization/roles.ts
  packages/core/src/routes/role.ts
  packages/core/src/utils/SchemaRouter.ts
  packages/integration-tests/src/api/organization.ts
  packages/integration-tests/src/tests/api/hook/hook.trigger.custom.data.test.ts
  packages/integration-tests/src/tests/api/hook/hook.trigger.data.test.ts
  packages/integration-tests/src/tests/api/hook/test-cases.ts
  packages/integration-tests/src/tests/api/interaction/organization-jit.test.ts
  packages/schemas/src/foundations/jsonb-types/hooks.ts
Labels: enhancement, size/l

#5881 feat: automatic social account linking
  .changeset/mean-dogs-pump.md
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SocialSignInForm/index.tsx
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/queries/sign-in-experience.test.ts
  packages/experience/src/__mocks__/logto.tsx
  packages/experience/src/hooks/use-sie.ts
  packages/experience/src/pages/SocialSignInWebCallback/use-social-sign-in-listener.ts
  packages/integration-tests/src/tests/experience/automatic-account-linking.test.ts
  packages/integration-tests/src/tests/experience/direct-sign-in.test.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/schemas/alterations/next-1717567857-social-sign-in-linking.ts
  packages/schemas/src/foundations/jsonb-types/sign-in-experience.ts
  packages/schemas/tables/sign_in_experiences.sql
Labels: feature, size/m

#6009 fix(core): prevent uncaught promise rejection
  packages/core/src/main.ts
  packages/core/src/tenants/Tenant.ts
Labels: bugfix, size/s

#5998 feat(console): implement organization jit ui
  packages/console/src/components/MultiOptionInput/index.module.scss
  packages/console/src/components/MultiOptionInput/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/Experience/DomainsInput/index.tsx
  packages/console/src/pages/OrganizationDetails/Settings/index.module.scss
  packages/console/src/pages/OrganizationDetails/Settings/index.tsx
  packages/console/src/pages/OrganizationDetails/index.tsx
  packages/console/src/pages/OrganizationDetails/types.ts
  packages/console/src/pages/TenantSettings/TenantMembers/InviteEmailsInput/index.tsx
  packages/core/src/routes/organization/index.email-domains.ts
  packages/phrases/src/locales/en/translation/admin-console/organization-details.ts
Labels: feature, size/l

#6002 feat(core,console): enable backchannel logout
  .changeset/stale-shrimps-compare.md
  .vscode/settings.json
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/BackchannelLogout.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/utils.ts
  packages/core/src/oidc/init.ts
  packages/integration-tests/src/client/index.ts
  packages/integration-tests/src/helpers/sign-in-experience.ts
  packages/integration-tests/src/tests/console/applications/helpers.ts
  packages/integration-tests/src/tests/console/backchannel-logout.test.ts
  packages/integration-tests/src/tests/experience/bootstrap.test.ts
  packages/integration-tests/src/ui-helpers/expect-console.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/schemas/src/foundations/jsonb-types/oidc-module.ts
  packages/schemas/src/utils/zod.ts
Labels: feature, size/l

#5999 chore(console,core): launch organization jit
  .changeset/smart-laws-compare.md
  packages/console/src/pages/OrganizationDetails/Settings/index.tsx
  packages/core/src/libraries/user.ts
  packages/core/src/routes/organization/index.ts
Labels: chore, size/m

#6013 style(console): update tab item style in readme docs
  packages/console/src/mdx-components/Tabs/index.module.scss
  packages/console/src/mdx-components/Tabs/index.tsx
Labels: size/s

#6015 refactor(console): imporve custom phrase fetch request error handling
  packages/console/src/pages/SignInExperience/PageContent/Content/LanguagesForm/ManageLanguage/LanguageEditor/LanguageDetails.tsx
Labels: enhancement, bugfix, size/xs

#6017 refactor(console): improve webhook test request error handling
  packages/console/src/pages/WebhookDetails/WebhookSettings/TestWebhook/index.tsx
Labels: enhancement, size/s

#6018 refactor(console): update spring boot api protection guide
  packages/console/src/assets/docs/guides/api-spring-boot/README.mdx
Labels: enhancement, size/s

#6012 refactor(console,experience,test): decouple isDevFeatureEnabled with isIntegrationTest
  .github/workflows/alteration-compatibility-integration-test.yml
  .github/workflows/integration-test.yml
  packages/console/src/consts/env.ts
  packages/experience/src/constants/env.ts
  packages/integration-tests/src/constants.ts
  packages/integration-tests/src/tests/console/bootstrap.test.ts
  packages/shared/src/node/env/GlobalValues.ts
Labels: enhancement, size/s

#6003 feat(core,console): organization mfa requirement
  packages/console/src/pages/OrganizationDetails/Settings/index.module.scss
  packages/console/src/pages/OrganizationDetails/Settings/index.tsx
  packages/core/src/oidc/grants/refresh-token.test.ts
  packages/core/src/oidc/grants/refresh-token.ts
  packages/core/src/queries/organization/index.ts
  packages/integration-tests/src/api/organization.ts
  packages/integration-tests/src/client/index.ts
  packages/integration-tests/src/helpers/organization.ts
  packages/integration-tests/src/tests/api/oidc/get-access-token.test.ts
  packages/integration-tests/src/tests/api/oidc/organization-token.test.ts
  packages/phrases/src/locales/en/translation/admin-console/organization-details.ts
  packages/schemas/alterations/next-1717818597-organization-mfa-requirement.ts
  packages/schemas/tables/organizations.sql
Labels: feature, size/l

#6020 refactor(console): allow view and update `user.profile` in settings
  .changeset/gold-bulldogs-draw.md
  packages/console/src/consts/external-links.ts
  packages/console/src/pages/UserDetails/UserSettings/index.tsx
  packages/console/src/pages/UserDetails/types.ts
  packages/console/src/pages/UserDetails/utils.ts
  packages/phrases/src/locales/en/translation/admin-console/user-details.ts
Labels: enhancement, size/s

#6022 refactor(console): update jit styles
  packages/console/src/pages/OrganizationDetails/Settings/index.module.scss
  packages/console/src/pages/OrganizationDetails/Settings/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/organization-details.ts
Labels: enhancement, size/m

#6021 refactor(console): improve swr error handling that previously omitted
  packages/console/src/components/ApplicationName/index.tsx
  packages/console/src/components/UserName/index.tsx
Labels: enhancement, size/xs

#6024 feat(core,console): organization jit roles
  packages/console/src/pages/OrganizationDetails/Settings/index.module.scss
  packages/console/src/pages/OrganizationDetails/Settings/index.tsx
  packages/console/src/pages/OrganizationDetails/index.tsx
  packages/console/src/pages/OrganizationDetails/types.ts
  packages/core/src/libraries/user.ts
  packages/core/src/queries/organization/email-domains.ts
  packages/core/src/queries/organization/index.ts
  packages/core/src/routes/organization/index.jit.email-domains.openapi.json
  packages/core/src/routes/organization/index.jit.email-domains.ts
  packages/core/src/routes/organization/index.jit.roles.openapi.json
  packages/core/src/routes/organization/index.ts
  packages/integration-tests/src/api/organization.ts
  packages/phrases/src/locales/en/translation/admin-console/organization-details.ts
  packages/schemas/alterations/next-1718340884-rename-org-email-domains-and-add-jit-roles-table.ts
  packages/schemas/tables/organization_jit_email_domains.sql
  packages/schemas/tables/organization_jit_roles.sql
Labels: feature, size/l

#6026 refactor: add organization jit role api tests
  packages/core/src/middleware/koa-pagination.test.ts
  packages/core/src/middleware/koa-pagination.ts
  packages/core/src/routes/organization/index.jit.roles.openapi.json
  packages/core/src/routes/organization/index.ts
  packages/core/src/routes/sso-connector/index.ts
  packages/core/src/utils/SchemaRouter.ts
  packages/integration-tests/src/api/organization-jit.ts
  packages/integration-tests/src/api/organization.ts
  packages/integration-tests/src/tests/api/admin-user.organization-jit.test.ts
  packages/integration-tests/src/tests/api/hook/hook.trigger.custom.data.test.ts
  packages/integration-tests/src/tests/api/interaction/organization-jit.test.ts
  packages/integration-tests/src/tests/api/organization/organization-email-domains.test.ts
  packages/integration-tests/src/tests/api/organization/organization-jit.test.ts
Labels: enhancement, size/l

#6027 chore: update changeset
  .changeset/smart-laws-compare.md
  packages/core/src/routes/organization/index.jit.roles.openapi.json
  packages/phrases/src/locales/en/translation/admin-console/organization-details.ts
Labels: chore, size/s

#6030 feat(connector): google one tap
  .changeset/breezy-bags-help.md
  .changeset/cold-masks-film.md
  packages/connectors/connector-google/package.json
  packages/connectors/connector-google/src/constant.ts
  packages/connectors/connector-google/src/index.test.ts
  packages/connectors/connector-google/src/index.ts
  packages/connectors/connector-google/src/types.ts
  packages/toolkit/connector-kit/src/types/foundation.ts
  packages/toolkit/connector-kit/src/types/metadata.ts
  packages/toolkit/connector-kit/src/types/social.ts
  pnpm-lock.yaml
Labels: feature, size/l

#6004 chore: add changeset
  .changeset/lucky-rocks-bow.md
Labels: chore, size/s

#6014 feat: add dev feature disabled test
  .github/workflows/dev-feature-disabled-integration-test.yml
  packages/integration-tests/src/utils.ts
Labels: feature, size/s

#6038 chore: update README.md
  README.md
Labels: chore, size/s

#6031 feat(core): google one tap
  .changeset/cyan-garlics-tan.md
  packages/core/src/__mocks__/connector.ts
  packages/core/src/libraries/sign-in-experience/index.test.ts
  packages/core/src/libraries/sign-in-experience/index.ts
  packages/core/src/libraries/sign-in-experience/types.ts
  packages/core/src/libraries/social.ts
  packages/core/src/middleware/koa-security-headers.ts
  packages/core/src/routes/interaction/index.ts
  packages/core/src/routes/interaction/utils/social-verification.test.ts
  packages/core/src/routes/interaction/utils/social-verification.ts
  packages/core/src/routes/well-known.test.ts
  packages/core/src/routes/well-known.ts
  packages/phrases/src/locales/en/errors/session.ts
  packages/schemas/src/types/index.ts
  packages/schemas/src/types/sign-in-experience.ts
Labels: feature, size/l

#6040 refactor(console): show sso status in jit domains
  packages/console/src/pages/OrganizationDetails/Settings/index.module.scss
  packages/console/src/pages/OrganizationDetails/Settings/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/enterprise-sso-details.ts
  packages/phrases/src/locales/en/translation/admin-console/organization-details.ts
Labels: enhancement, size/s

#6032 feat(experience): google one tap
  .changeset/nine-carrots-roll.md
  packages/experience/src/apis/interaction.ts
  packages/experience/src/components/GoogleOneTap/index.tsx
  packages/experience/src/containers/SocialSignInList/index.tsx
  packages/experience/src/containers/SocialSignInList/use-social.ts
  packages/experience/src/hooks/use-connectors.ts
  packages/experience/src/pages/Register/index.tsx
  packages/experience/src/pages/SignIn/Main.tsx
  packages/experience/src/pages/SignIn/index.tsx
  packages/experience/src/pages/SocialSignInWebCallback/use-single-sign-on-listener.ts
  packages/experience/src/pages/SocialSignInWebCallback/use-social-sign-in-listener.ts
  packages/experience/src/types/index.ts
  packages/experience/src/utils/social-connectors.ts
Labels: feature, size/m

#6034 feat(console): google one tap
  .changeset/mean-pumpkins-scream.md
  packages/console/src/components/ConnectorForm/GoogleOneTapCard/figure-dark.webp
  packages/console/src/components/ConnectorForm/GoogleOneTapCard/figure-light.webp
  packages/console/src/components/ConnectorForm/GoogleOneTapCard/index.module.scss
  packages/console/src/components/ConnectorForm/GoogleOneTapCard/index.tsx
  packages/console/src/components/FormCard/index.module.scss
  packages/console/src/ds-components/Checkbox/Checkbox/index.tsx
  packages/console/src/ds-components/Switch/index.module.scss
  packages/console/src/ds-components/Switch/index.tsx
  packages/console/src/hooks/use-connector-form-config-parser.tsx
  packages/console/src/pages/ConnectorDetails/ConnectorContent/index.tsx
  packages/console/src/types/connector.ts
  packages/console/src/utils/connector-form.ts
  packages/phrases/src/locales/en/translation/admin-console/connector-details.ts
Labels: feature, size/m

#6041 test(core): implement sso related integration tests
  packages/core/src/routes/interaction/utils/single-sign-on.ts
  packages/core/src/sso/OidcConnector/index.ts
  packages/core/src/sso/OidcConnector/test-utils.ts
  packages/integration-tests/src/api/interaction-sso.ts
  packages/integration-tests/src/api/sso-connector.ts
  packages/integration-tests/src/helpers/single-sign-on.ts
  packages/integration-tests/src/tests/api/hook/hook.trigger.custom.data.test.ts
  packages/integration-tests/src/tests/api/interaction/organization-jit.test.ts
  packages/integration-tests/src/tests/api/interaction/single-sign-on/happy-path.test.ts
Labels: testing, size/l

#6039 chore(connector): update outdated links in connector readme
  packages/connectors/connector-alipay-native/README.md
  packages/connectors/connector-alipay-web/README.md
  packages/connectors/connector-aliyun-dm/README.md
  packages/connectors/connector-aliyun-sms/README.md
  packages/connectors/connector-apple/README.md
  packages/connectors/connector-aws-ses/README.md
  packages/connectors/connector-dingtalk-web/README.md
  packages/connectors/connector-github/README.md
  packages/connectors/connector-mailgun/README.md
  packages/connectors/connector-sendgrid-email/README.md
  packages/connectors/connector-smsaero/README.md
  packages/connectors/connector-smtp/README.md
  packages/connectors/connector-tencent-sms/README.md
  packages/connectors/connector-twilio-sms/README.md
  packages/connectors/connector-wechat-native/README.md
  packages/connectors/connector-wechat-web/README.md
  packages/console/src/assets/docs/guides/web-outline/README.mdx
Labels: chore, size/s

#6036 feat(schemas): add `agree_to_terms_policy` for sie table
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/queries/sign-in-experience.test.ts
  packages/experience/src/__mocks__/logto.tsx
  packages/schemas/alterations/next-1718594164-add-agree-to-terms-policy.ts
  packages/schemas/tables/sign_in_experiences.sql
Labels: feature, size/s

#6037 feat(console,phrases): support agree to terms policy configuration
  packages/console/src/pages/SignInExperience/PageContent/Content/TermsForm.tsx
  packages/phrases/src/locales/de/translation/admin-console/sign-in-exp/content.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/content.ts
  packages/phrases/src/locales/es/translation/admin-console/sign-in-exp/content.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp/content.ts
  packages/phrases/src/locales/it/translation/admin-console/sign-in-exp/content.ts
  packages/phrases/src/locales/ja/translation/admin-console/sign-in-exp/content.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp/content.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/sign-in-exp/content.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp/content.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp/content.ts
  packages/phrases/src/locales/ru/translation/admin-console/sign-in-exp/content.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp/content.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp/content.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/sign-in-exp/content.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/sign-in-exp/content.ts
Labels: feature, size/m

#6044 feat(experience): support agree to terms policies
  .changeset/heavy-rabbits-own.md
  packages/experience/src/__mocks__/logto.tsx
  packages/experience/src/containers/SocialSignInList/use-social.ts
  packages/experience/src/containers/TermsAndPrivacyLinks/index.tsx
  packages/experience/src/hooks/use-terms.ts
  packages/experience/src/pages/Register/IdentifierRegisterForm/index.tsx
  packages/experience/src/pages/Register/index.module.scss
  packages/experience/src/pages/Register/index.tsx
  packages/experience/src/pages/SignIn/IdentifierSignInForm/index.module.scss
  packages/experience/src/pages/SignIn/IdentifierSignInForm/index.tsx
  packages/experience/src/pages/SignIn/Main.tsx
  packages/experience/src/pages/SignIn/PasswordSignInForm/index.module.scss
  packages/experience/src/pages/SignIn/PasswordSignInForm/index.tsx
  packages/experience/src/pages/SignIn/index.module.scss
  packages/experience/src/pages/SignIn/index.test.tsx
  packages/experience/src/pages/SignIn/index.tsx
  packages/experience/src/pages/SocialSignInWebCallback/use-single-sign-on-listener.ts
  packages/experience/src/pages/SocialSignInWebCallback/use-social-sign-in-listener.ts
  packages/integration-tests/src/tests/experience/automatic-account-linking.test.ts
  packages/integration-tests/src/tests/experience/direct-sign-in.test.ts
  packages/integration-tests/src/tests/experience/social-sign-in.test.ts
  packages/phrases-experience/src/locales/de/description.ts
  packages/phrases-experience/src/locales/en/description.ts
  packages/phrases-experience/src/locales/es/description.ts
  packages/phrases-experience/src/locales/fr/description.ts
  packages/phrases-experience/src/locales/it/description.ts
  packages/phrases-experience/src/locales/ja/description.ts
  packages/phrases-experience/src/locales/ko/description.ts
  packages/phrases-experience/src/locales/pl-pl/description.ts
  packages/phrases-experience/src/locales/pt-br/description.ts
  packages/phrases-experience/src/locales/pt-pt/description.ts
  packages/phrases-experience/src/locales/ru/description.ts
  packages/phrases-experience/src/locales/tr-tr/description.ts
  packages/phrases-experience/src/locales/zh-cn/description.ts
  packages/phrases-experience/src/locales/zh-hk/description.ts
  packages/phrases-experience/src/locales/zh-tw/description.ts
Labels: feature, size/l

#6046 feat(console): add Ruby app guide
  .changeset/large-gifts-cross.md
  packages/console/src/assets/docs/guides/generate-metadata.js
  packages/console/src/assets/docs/guides/index.tsx
  packages/console/src/assets/docs/guides/types.ts
  packages/console/src/assets/docs/guides/web-ruby/README.mdx
  packages/console/src/assets/docs/guides/web-ruby/config.json
  packages/console/src/assets/docs/guides/web-ruby/index.ts
  packages/console/src/assets/docs/guides/web-ruby/logo.webp
  packages/console/src/assets/index.d.ts
  packages/console/src/components/Guide/hooks.ts
  packages/console/src/components/Guide/index.tsx
  packages/console/src/pages/ApiResourceDetails/components/ApiGuide/index.tsx
  packages/console/src/pages/ApplicationDetails/components/AppGuide/index.tsx
Labels: feature, size/l

#6047 chore(console): update guide orders
  .github/CODEOWNERS
  packages/console/src/assets/docs/guides/index.tsx
  packages/console/src/assets/docs/guides/native-ios-swift/index.ts
  packages/console/src/assets/docs/guides/web-gpt-plugin/config.json
  packages/console/src/assets/docs/guides/web-gpt-plugin/index.ts
  packages/console/src/assets/docs/guides/web-java-spring-boot/index.ts
  packages/console/src/assets/docs/guides/web-ruby/index.ts
Labels: chore, size/s

#6049 feat(core): jit organization roles
  packages/core/src/libraries/user.ts
  packages/core/src/queries/organization/email-domains.ts
  packages/core/src/routes/admin-user/basics.test.ts
  packages/core/src/routes/admin-user/basics.ts
  packages/core/src/routes/admin-user/mfa-verifications.test.ts
  packages/core/src/routes/admin-user/search.test.ts
  packages/core/src/routes/admin-user/social.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.mfa.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/core/src/routes/interaction/utils/single-sign-on.test.ts
  packages/core/src/routes/interaction/utils/single-sign-on.ts
  packages/integration-tests/src/tests/api/admin-user.organization-jit.test.ts
  packages/integration-tests/src/tests/api/interaction/organization-jit.test.ts
Labels: feature, size/m

#6054 refactor: fix google one tap issues
  packages/connectors/connector-google/README.md
  packages/core/src/middleware/koa-security-headers.ts
  packages/experience/src/Providers/IframeModalProvider/IframeModal/index.module.scss
  packages/experience/src/Providers/IframeModalProvider/IframeModal/index.tsx
Labels: enhancement, size/s

#6061 chore(schemas): add legacy-pro tag to reserved plan ID
  packages/schemas/src/consts/subscriptions.ts
Labels: chore, size/xs

#6058 style(experience): add margin-bottom for terms checkbox on sign-in page
  packages/experience/src/pages/SignIn/IdentifierSignInForm/index.module.scss
  packages/experience/src/pages/SignIn/IdentifierSignInForm/index.tsx
Labels: size/xs

#6055 refactor(core): update relation queries
  packages/core/src/libraries/application.ts
  packages/core/src/libraries/organization-invitation.ts
  packages/core/src/libraries/user.ts
  packages/core/src/oidc/grants/refresh-token.ts
  packages/core/src/oidc/resource.ts
  packages/core/src/routes/applications/application-user-consent-organization.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/core/src/routes/interaction/consent/index.ts
  packages/core/src/routes/organization/index.ts
  packages/core/src/routes/organization/index.user-role-relations.ts
  packages/core/src/routes/organization/roles.ts
  packages/core/src/utils/RelationQueries.ts
  packages/core/src/utils/SchemaRouter.ts
Labels: enhancement, size/m

#6064 feat(core): init organization app apis
  packages/core/src/queries/organization/index.ts
  packages/core/src/routes/organization/index.applications.openapi.json
  packages/core/src/routes/organization/index.jit.roles.openapi.json
  packages/core/src/routes/organization/index.ts
  packages/core/src/routes/swagger/index.ts
  packages/core/src/routes/swagger/utils/general.ts
  packages/core/src/utils/SchemaRouter.ts
  packages/integration-tests/src/api/factory.ts
  packages/integration-tests/src/api/organization-jit.ts
  packages/integration-tests/src/api/organization.ts
  packages/integration-tests/src/tests/api/admin-user.organization-jit.test.ts
  packages/integration-tests/src/tests/api/hook/hook.trigger.data.test.ts
  packages/integration-tests/src/tests/api/hook/test-cases.ts
  packages/integration-tests/src/tests/api/interaction/organization-jit.test.ts
  packages/integration-tests/src/tests/api/organization/organization-application.test.ts
  packages/integration-tests/src/tests/api/organization/organization-jit.test.ts
  packages/schemas/alterations/next-1718785576-organization-application-relations.ts
  packages/schemas/tables/applications.sql
  packages/schemas/tables/organization_application_relations.sql
Labels: feature, size/l

#6065 refactor(core): reorg organization users api docs
  packages/core/src/routes/organization/index.applications.openapi.json
  packages/core/src/routes/organization/index.openapi.json
  packages/core/src/routes/organization/index.users.openapi.json
  packages/core/src/routes/swagger/index.ts
Labels: enhancement, size/l

#6053 chore(test): reorg the sso connector api cleanup logic
  packages/integration-tests/src/tests/api/hook/hook.trigger.custom.data.test.ts
  packages/integration-tests/src/tests/api/interaction/organization-jit.test.ts
Labels: chore, size/s

#6052 docs(console): add the troubleshooting section in expo guide
  packages/console/src/assets/docs/guides/native-expo/README.mdx
Labels: size/s

#6076 chore: rename legacy pro to grandfathered pro
  packages/schemas/src/consts/subscriptions.ts
Labels: chore, size/xs

#6074 refactor(console): update subscription plan ID
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/index.tsx
  packages/console/src/components/FeatureTag/index.tsx
  packages/console/src/components/PlanDescription/index.tsx
  packages/console/src/consts/plan-quotas.ts
  packages/console/src/consts/subscriptions.ts
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/MauLimitExceededNotification/index.tsx
  packages/console/src/pages/TenantSettings/components/NotEligibleSwitchPlanModalContent/index.tsx
Labels: enhancement, size/s

#6067 feat(core): organization jit sso apis
  packages/core/src/queries/organization/index.ts
  packages/core/src/routes/organization/index.jit.roles.openapi.json
  packages/core/src/routes/organization/index.jit.sso-connectors.openapi.json
  packages/core/src/routes/organization/index.ts
  packages/integration-tests/src/api/organization-jit.ts
  packages/integration-tests/src/tests/api/organization/organization-jit.test.ts
  packages/schemas/alterations/next-1718786576-organization-jit-sso-connectors.ts
  packages/schemas/tables/organization_jit_sso_connectors.sql
Labels: feature, size/l

#6025 chore(core): add dev feature tag for openapi.json
  packages/core/src/routes/swagger/index.ts
  packages/core/src/routes/swagger/utils/general.ts
Labels: chore, size/s

#6069 feat(core): organization jit sso
  packages/core/src/libraries/user.test.ts
  packages/core/src/libraries/user.ts
  packages/core/src/libraries/user.utils.ts
  packages/core/src/queries/organization/email-domains.ts
  packages/core/src/queries/organization/index.ts
  packages/core/src/queries/organization/sso-connectors.ts
  packages/core/src/routes-me/user.ts
  packages/core/src/routes/admin-user/basics.test.ts
  packages/core/src/routes/admin-user/basics.ts
  packages/core/src/routes/admin-user/mfa-verifications.test.ts
  packages/core/src/routes/admin-user/search.test.ts
  packages/core/src/routes/admin-user/social.test.ts
  packages/core/src/routes/interaction/actions/helpers.ts
  packages/core/src/routes/interaction/actions/submit-interaction.mfa.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/core/src/routes/interaction/utils/single-sign-on.ts
  packages/integration-tests/src/helpers/interactions.ts
  packages/integration-tests/src/tests/api/admin-user.organization-jit.test.ts
  packages/integration-tests/src/tests/api/hook/hook.trigger.custom.data.test.ts
  packages/integration-tests/src/tests/api/interaction/organization-jit.test.ts
Labels: feature, size/xl

#6080 fix(experience): apply agree to terms policy for sso
  packages/experience/src/hooks/use-single-sign-on-watch.ts
  packages/experience/src/pages/Register/IdentifierRegisterForm/index.tsx
  packages/experience/src/pages/SignIn/IdentifierSignInForm/index.tsx
  packages/experience/src/pages/SignIn/PasswordSignInForm/index.tsx
Labels: bugfix, size/s

#6073 feat(console): update jit config
  packages/console/src/components/MultiOptionInput/index.tsx
  packages/console/src/ds-components/ActionMenu/index.tsx
  packages/console/src/pages/EnterpriseSso/SsoConnectorLogo/index.module.scss
  packages/console/src/pages/OrganizationDetails/Settings/index.module.scss
  packages/console/src/pages/OrganizationDetails/Settings/index.tsx
  packages/console/src/pages/OrganizationDetails/Settings/utils.ts
  packages/console/src/pages/OrganizationDetails/index.tsx
  packages/console/src/pages/OrganizationDetails/types.ts
  packages/phrases/src/locales/en/translation/admin-console/organization-details.ts
Labels: feature, size/xl

#6077 chore: update changeset
  .changeset/smart-laws-compare.md
Labels: chore, size/s

#6072 refactor(core): update naming and fix typos
  packages/core/src/libraries/organization-invitation.ts
  packages/core/src/libraries/user.ts
  packages/core/src/oidc/grants/refresh-token.test.ts
  packages/core/src/oidc/grants/refresh-token.ts
  packages/core/src/queries/organization/application-role-relations.ts
  packages/core/src/queries/organization/index.ts
  packages/core/src/queries/organization/user-role-relations.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/core/src/routes/organization/index.application-role-relations.ts
  packages/core/src/routes/organization/index.applications.openapi.json
  packages/core/src/routes/organization/index.jit.email-domains.ts
  packages/core/src/routes/organization/index.ts
  packages/core/src/routes/organization/index.user-role-relations.ts
  packages/core/src/routes/organization/index.users.openapi.json
  packages/integration-tests/src/tests/api/organization/organization-application.test.ts
Labels: enhancement, size/s

#6078 refactor(core): reorg organization routes
  .github/workflows/dev-feature-disabled-integration-test.yml
  packages/core/src/routes/organization-invitation/index.openapi.json
  packages/core/src/routes/organization-invitation/index.ts
  packages/core/src/routes/organization-role/index.openapi.json
  packages/core/src/routes/organization-role/index.ts
  packages/core/src/routes/organization-scope/index.openapi.json
  packages/core/src/routes/organization-scope/index.ts
  packages/core/src/routes/organization/application/index.openapi.json
  packages/core/src/routes/organization/application/index.ts
  packages/core/src/routes/organization/application/role-relations.ts
  packages/core/src/routes/organization/index.ts
  packages/core/src/routes/organization/jit/email-domains.openapi.json
  packages/core/src/routes/organization/jit/email-domains.ts
  packages/core/src/routes/organization/jit/index.ts
  packages/core/src/routes/organization/jit/roles.openapi.json
  packages/core/src/routes/organization/jit/sso-connectors.openapi.json
  packages/core/src/routes/organization/user/index.openapi.json
  packages/core/src/routes/organization/user/index.ts
  packages/core/src/routes/organization/user/role-relations.ts
Labels: enhancement, size/l

#6045 feat(core): issue subject tokens
  packages/core/src/constants/index.ts
  packages/core/src/queries/subject-token.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/security/index.openapi.json
  packages/core/src/routes/security/index.ts
  packages/core/src/routes/swagger/index.ts
  packages/core/src/tenants/Queries.ts
  packages/integration-tests/src/api/subject-token.ts
  packages/integration-tests/src/tests/api/security.test.ts
  packages/schemas/alterations/next-1718865814-add-subject-tokens.ts
  packages/schemas/src/types/index.ts
  packages/schemas/src/types/subject-token.ts
  packages/schemas/tables/subject_tokens.sql
Labels: feature, size/m

#6081 chore: update code owners
  .github/CODEOWNERS
Labels: chore, size/s

#6085 refactor: filter whole supplement document if needed
  packages/core/src/routes/organization/application/index.openapi.json
  packages/core/src/routes/security/index.openapi.json
  packages/core/src/routes/swagger/index.ts
  packages/core/src/routes/swagger/utils/general.ts
Labels: enhancement, size/s

#6083 refactor(core): return roles in organization app get api
  packages/core/src/queries/application.ts
  packages/core/src/queries/organization/application-relations.ts
  packages/core/src/queries/organization/index.ts
  packages/core/src/queries/organization/user-relations.ts
  packages/core/src/queries/organization/utils.ts
  packages/core/src/queries/user.ts
  packages/core/src/routes/organization/application/index.ts
  packages/core/src/routes/organization/user/index.openapi.json
  packages/core/src/routes/organization/user/role-relations.ts
  packages/integration-tests/src/api/factory.ts
  packages/integration-tests/src/tests/api/organization/organization-application.test.ts
  packages/integration-tests/src/tests/api/organization/organization-user.test.ts
  packages/schemas/src/types/organization.ts
Labels: enhancement, size/l

#6084 feat: organization role types
  packages/console/src/pages/OrganizationRoleDetails/index.tsx
  packages/console/src/pages/OrganizationTemplate/OrganizationRoles/CreateOrganizationRoleModal.tsx
  packages/console/src/pages/OrganizationTemplate/OrganizationRoles/index.module.scss
  packages/console/src/pages/OrganizationTemplate/OrganizationRoles/index.tsx
  packages/console/src/pages/Roles/index.tsx
  packages/integration-tests/src/api/organization-role.ts
  packages/integration-tests/src/tests/api/organization/organization-application.test.ts
  packages/integration-tests/src/tests/api/organization/organization-user.test.ts
  packages/integration-tests/src/tests/console/rbac/helper.ts
  packages/phrases/src/locales/de/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/de/translation/admin-console/roles.ts
  packages/phrases/src/locales/en/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/en/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/en/translation/admin-console/roles.ts
  packages/phrases/src/locales/es/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/es/translation/admin-console/roles.ts
  packages/phrases/src/locales/fr/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/roles.ts
  packages/phrases/src/locales/it/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/it/translation/admin-console/roles.ts
  packages/phrases/src/locales/ja/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/roles.ts
  packages/phrases/src/locales/ko/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/roles.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/roles.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/roles.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/roles.ts
  packages/phrases/src/locales/ru/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/roles.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/roles.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/roles.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/roles.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/roles.ts
  packages/schemas/alterations/next-1719014832-organization-role-types.ts
  packages/schemas/src/types/role.ts
  packages/schemas/src/types/tenant-organization.ts
  packages/schemas/tables/organization_role_application_relations.sql
  packages/schemas/tables/organization_role_user_relations.sql
  packages/schemas/tables/organization_roles.sql
Labels: feature, size/l

#6086 feat(core): add organization - application apis
  packages/core/src/queries/application.ts
  packages/core/src/queries/organization/application-relations.ts
  packages/core/src/routes/admin-user/search.ts
  packages/core/src/routes/applications/application-organization.openapi.json
  packages/core/src/routes/applications/application-organization.ts
  packages/core/src/routes/applications/application.ts
  packages/core/src/routes/init.ts
  packages/integration-tests/src/api/application.ts
  packages/integration-tests/src/tests/api/application/application.organization.test.ts
  packages/integration-tests/src/tests/api/application/application.test.ts
Labels: feature, size/l

#6087 feat(core): update application organization role apis
  .changeset/fresh-gorillas-obey.md
  packages/core/src/routes/organization-role/index.ts
  packages/core/src/routes/organization/application/index.openapi.json
  packages/core/src/routes/organization/application/index.ts
  packages/core/src/routes/organization/application/role-relations.ts
  packages/core/src/routes/organization/user/index.openapi.json
  packages/core/src/routes/organization/user/role-relations.ts
  packages/integration-tests/src/api/organization.ts
  packages/integration-tests/src/helpers/organization.ts
  packages/integration-tests/src/tests/api/hook/hook.trigger.data.test.ts
  packages/integration-tests/src/tests/api/interaction/consent/happy-path.test.ts
  packages/integration-tests/src/tests/api/organization/organization-application.test.ts
  packages/integration-tests/src/tests/api/organization/organization-user.test.ts
Labels: feature, size/m

#6089 fix: generate valid OpenAPI spec
  .changeset/heavy-badgers-jog.md
  packages/core/src/routes/swagger/index.test.ts
  packages/core/src/routes/swagger/index.ts
  packages/core/src/routes/swagger/utils/parameters.ts
Labels: bugfix, size/s

#6023 feat: support prompt config for some built-in connectors
  .changeset/breezy-dodos-cheer.md
  .changeset/orange-dryers-joke.md
  .changeset/quick-schools-obey.md
  packages/connectors/connector-azuread/README.md
  packages/connectors/connector-azuread/src/constant.ts
  packages/connectors/connector-azuread/src/index.ts
  packages/connectors/connector-azuread/src/types.ts
  packages/connectors/connector-google/README.md
  packages/connectors/connector-google/src/constant.ts
  packages/connectors/connector-google/src/index.ts
  packages/console/src/components/ConnectorForm/ConfigForm/ConfigFormFields/index.module.scss
  packages/console/src/components/ConnectorForm/ConfigForm/ConfigFormFields/index.tsx
  packages/toolkit/connector-kit/src/types/config-form.ts
  packages/toolkit/connector-kit/src/types/social.ts
Labels: feature, size/m

#6095 refactor: refactor integration test ci job
  .github/workflows/alteration-compatibility-integration-test.yml
  .github/workflows/dev-feature-disabled-integration-test.yml
Labels: enhancement, size/s

#6094 feat(console,phrases): add issuer endpoint to application form
  .changeset/tiny-teachers-hug.md
  packages/console/src/consts/oidc.ts
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/EndpointsAndCredentials.tsx
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/enterprise-sso-details.ts
Labels: feature, size/m

#6101 fix(schemas): explicitly set search path
  packages/schemas/alterations/next-1719221205-fix-functions.ts
  packages/schemas/tables/applications.sql
  packages/schemas/tables/organization_roles.sql
Labels: bugfix, size/s

#6088 feat(console): show organization list for m2m apps
  packages/console/src/components/OrganizationList/index.module.scss
  packages/console/src/components/OrganizationList/index.tsx
  packages/console/src/consts/page-tabs.ts
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/MachineToMachineApplicationRoles/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
  packages/console/src/pages/OrganizationDetails/Members/EditOrganizationRolesModal.tsx
  packages/console/src/pages/UserDetails/UserOrganizations/index.tsx
  packages/integration-tests/src/tests/console/rbac/machime-to-machime-rbac.test.ts
  packages/phrases/src/locales/de/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/es/translation/admin-console/application-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/it/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/application-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts
Labels: feature, size/l

#6075 refactor(console): hide backchannel for m2m apps
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
Labels: enhancement, size/xs

#6102 refactor: add brief intro in swagger.json
  packages/core/src/routes/swagger/consts.ts
  packages/core/src/routes/swagger/index.ts
Labels: enhancement, size/s

#6092 fix: include `tenantId` and its root param in responses
  packages/core/src/routes/swagger/utils/parameters.ts
  packages/core/src/utils/zod.ts
Labels: bugfix, size/s

#6103 refactor(experience,phrases): update resend passcode phrases
  packages/experience/src/containers/VerificationCode/index.test.tsx
  packages/experience/src/containers/VerificationCode/index.tsx
  packages/experience/src/jest.setup.ts
  packages/phrases-experience/src/locales/de/description.ts
  packages/phrases-experience/src/locales/en/description.ts
  packages/phrases-experience/src/locales/es/description.ts
  packages/phrases-experience/src/locales/fr/description.ts
  packages/phrases-experience/src/locales/it/description.ts
  packages/phrases-experience/src/locales/ja/description.ts
  packages/phrases-experience/src/locales/ko/description.ts
  packages/phrases-experience/src/locales/pl-pl/description.ts
  packages/phrases-experience/src/locales/pt-br/description.ts
  packages/phrases-experience/src/locales/pt-pt/description.ts
  packages/phrases-experience/src/locales/ru/description.ts
  packages/phrases-experience/src/locales/tr-tr/description.ts
  packages/phrases-experience/src/locales/zh-cn/description.ts
  packages/phrases-experience/src/locales/zh-hk/description.ts
  packages/phrases-experience/src/locales/zh-tw/description.ts
Labels: enhancement, size/m

#6096 feat(core): add hasPassword field to custom JWT user context
  .changeset/sharp-cooks-explain.md
  packages/console/src/pages/CustomizeJwtDetails/utils/config.tsx
  packages/core/src/libraries/jwt-customizer.ts
  packages/integration-tests/src/__mocks__/jwt-customizer.ts
  packages/integration-tests/src/tests/api/oidc/get-access-token.test.ts
  packages/schemas/src/types/logto-config/jwt-customizer.ts
Labels: feature, size/s

#6112 refactor: handle potential errors during ky requests in koa-auth middleware
  packages/core/src/middleware/koa-auth/index.ts
Labels: enhancement, size/s

#6098 feat(core): issue organization token via client credentials
  packages/core/src/oidc/grants/client-credentials.test.ts
  packages/core/src/oidc/grants/client-credentials.ts
  packages/core/src/oidc/grants/refresh-token.test.ts
  packages/core/src/oidc/grants/refresh-token.ts
  packages/core/src/oidc/init.ts
  packages/core/src/oidc/resource.ts
  packages/core/src/queries/organization/application-role-relations.ts
  packages/integration-tests/src/api/api.ts
  packages/integration-tests/src/api/application.ts
  packages/integration-tests/src/tests/api/application/application.roles.test.ts
  packages/integration-tests/src/tests/api/oidc/client-credentials-grant.test.ts
Labels: feature, size/xl

#6110 chore: fix typo
  packages/connectors/connector-alipay-native/README.md
  packages/connectors/connector-huggingface/src/index.test.ts
  packages/console/src/assets/docs/guides/web-go/README.mdx
  packages/console/src/pages/SignInExperience/PageContent/Content/LanguagesForm/ManageLanguage/LanguageEditor/LanguageDetails.tsx
  packages/integration-tests/src/tests/console/applications/index.test.ts
  packages/integration-tests/src/tests/console/sign-in-experience/sign-up-and-sign-in/helpers.ts
  packages/integration-tests/src/tests/console/sign-in-experience/sign-up-and-sign-in/sad-path.test.ts
Labels: chore, size/s

#6113 refactor(console): upgrade mdx packages
  packages/console/.parcelrc
  packages/console/.parcelrc.arm64
  packages/console/package.json
  packages/console/parcel-transformer-mdx2.js
  packages/console/src/assets/docs/guides/api-express/README.mdx
  packages/console/src/assets/docs/guides/api-python/README.mdx
  packages/console/src/assets/docs/guides/api-spring-boot/README.mdx
  packages/console/src/assets/docs/guides/native-android/README.mdx
  packages/console/src/assets/docs/guides/native-capacitor/README.mdx
  packages/console/src/assets/docs/guides/native-expo/README.mdx
  packages/console/src/assets/docs/guides/native-flutter/README.mdx
  packages/console/src/assets/docs/guides/native-ios-swift/README.mdx
  packages/console/src/assets/docs/guides/spa-angular/README.mdx
  packages/console/src/assets/docs/guides/spa-react/README.mdx
  packages/console/src/assets/docs/guides/spa-vanilla/README.mdx
  packages/console/src/assets/docs/guides/spa-vue/README.mdx
  packages/console/src/assets/docs/guides/spa-webflow/README.mdx
  packages/console/src/assets/docs/guides/web-dotnet-core-blazor-server/README.mdx
  packages/console/src/assets/docs/guides/web-dotnet-core-blazor-wasm/README.mdx
  packages/console/src/assets/docs/guides/web-dotnet-core-mvc/README.mdx
  packages/console/src/assets/docs/guides/web-dotnet-core/README.mdx
  packages/console/src/assets/docs/guides/web-express/README.mdx
  packages/console/src/assets/docs/guides/web-go/README.mdx
  packages/console/src/assets/docs/guides/web-java-spring-boot/README.mdx
  packages/console/src/assets/docs/guides/web-next-app-router/README.mdx
  packages/console/src/assets/docs/guides/web-next-auth/README.mdx
  packages/console/src/assets/docs/guides/web-next/README.mdx
  packages/console/src/assets/docs/guides/web-nuxt/README.mdx
  packages/console/src/assets/docs/guides/web-php/README.mdx
  packages/console/src/assets/docs/guides/web-python/README.mdx
  packages/console/src/assets/docs/guides/web-remix/README.mdx
  packages/console/src/assets/docs/guides/web-ruby/README.mdx
  packages/console/src/assets/docs/guides/web-sveltekit/README.mdx
  packages/console/src/components/Guide/index.tsx
  packages/console/src/mdx-components/Code/index.tsx
  packages/console/src/mdx-components/MdxProvider/index.tsx
  packages/console/src/mdx-components/Mermaid/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/SsoGuide/index.tsx
  pnpm-lock.yaml
Labels: enhancement, size/xl

#6114 refactor: update nuxt guide
  packages/console/package.json
  packages/console/parcel-transformer-mdx2.js
  packages/console/src/assets/docs/fragments/_sign_in_explanation.md
  packages/console/src/assets/docs/guides/web-nuxt/README.mdx
  packages/console/src/ds-components/CodeEditor/index.module.scss
  packages/console/src/ds-components/CodeEditor/index.tsx
  packages/console/src/mdx-components/Code/index.tsx
  packages/console/src/mdx-components/Steps/index.tsx
  pnpm-lock.yaml
Labels: enhancement, size/m

#6116 refactor(console): update ruby guide
  packages/console/src/assets/docs/fragments/_redirect_uris.mdx
  packages/console/src/assets/docs/guides/m2m-general/index.ts
  packages/console/src/assets/docs/guides/native-android/index.ts
  packages/console/src/assets/docs/guides/native-expo/index.ts
  packages/console/src/assets/docs/guides/spa-angular/index.ts
  packages/console/src/assets/docs/guides/spa-react/index.ts
  packages/console/src/assets/docs/guides/spa-vanilla/index.ts
  packages/console/src/assets/docs/guides/spa-vue/index.ts
  packages/console/src/assets/docs/guides/types.ts
  packages/console/src/assets/docs/guides/web-dotnet-core-blazor-server/index.ts
  packages/console/src/assets/docs/guides/web-dotnet-core-blazor-wasm/index.ts
  packages/console/src/assets/docs/guides/web-dotnet-core-mvc/index.ts
  packages/console/src/assets/docs/guides/web-express/index.ts
  packages/console/src/assets/docs/guides/web-go/index.ts
  packages/console/src/assets/docs/guides/web-next-app-router/index.ts
  packages/console/src/assets/docs/guides/web-next/index.ts
  packages/console/src/assets/docs/guides/web-nuxt/README.mdx
  packages/console/src/assets/docs/guides/web-nuxt/index.ts
  packages/console/src/assets/docs/guides/web-php/index.ts
  packages/console/src/assets/docs/guides/web-python/index.ts
  packages/console/src/assets/docs/guides/web-ruby/README.mdx
  packages/console/src/assets/docs/guides/web-ruby/index.ts
  packages/console/src/assets/docs/guides/web-sveltekit/index.ts
  packages/console/src/assets/docs/guides/web-wordpress/index.ts
  packages/console/src/mdx-components/Steps/FurtherReadings.tsx
  packages/console/src/mdx-components/Steps/index.tsx
Labels: enhancement, size/m

#6119 refactor(console): update next guide
  packages/console/src/assets/docs/fragments/_redirect_uris.mdx
  packages/console/src/assets/docs/guides/web-next-app-router/README.mdx
  packages/console/src/assets/docs/guides/web-next/README.mdx
Labels: enhancement, size/l

#6120 refactor(core): update grant comments
  packages/core/src/oidc/grants/client-credentials.ts
Labels: enhancement, size/s

#6121 chore: update README.mdx
  packages/console/src/assets/docs/guides/web-express/README.mdx
Labels: chore, size/xs

#6123 refactor(console): update swift guide
  packages/console/src/assets/docs/fragments/_experience-overview.md
  packages/console/src/assets/docs/fragments/_redirect-uris-native.mdx
  packages/console/src/assets/docs/fragments/_redirect-uris-web.mdx
  packages/console/src/assets/docs/guides/native-ios-swift/README.mdx
  packages/console/src/assets/docs/guides/native-ios-swift/index.ts
  packages/console/src/assets/docs/guides/web-next-app-router/README.mdx
  packages/console/src/assets/docs/guides/web-next/README.mdx
  packages/console/src/assets/docs/guides/web-nuxt/README.mdx
  packages/console/src/assets/docs/guides/web-ruby/README.mdx
  packages/console/src/assets/docs/guides/web-ruby/index.ts
Labels: enhancement, size/m

#6122 refactor(console): polish ui
  packages/console/src/components/OrganizationList/index.tsx
  packages/console/src/components/OrganizationRolePermissionsAssignmentModal/index.tsx
  packages/console/src/consts/external-links.ts
  packages/console/src/ds-components/CodeEditor/index.module.scss
  packages/console/src/hooks/use-console-routes/index.tsx
  packages/console/src/hooks/use-console-routes/routes/mfa.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
  packages/console/src/pages/OrganizationDetails/Settings/JitSettings.tsx
  packages/console/src/pages/OrganizationDetails/Settings/index.tsx
  packages/integration-tests/src/ui-helpers/expect-organizations.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/organization-details.ts
Labels: enhancement, size/xl

#6135 refactor(console): use correct array for checking enterprise sso
  packages/console/src/pages/OrganizationDetails/Settings/JitSettings.tsx
  packages/console/src/pages/OrganizationDetails/Settings/index.module.scss
  packages/console/src/pages/OrganizationDetails/Settings/index.tsx
Labels: enhancement, size/m

#6124 refactor(console): update express guide
  packages/console/src/assets/docs/guides/web-express/README.mdx
Labels: enhancement, size/m

#6131 refactor(console): polish android guide
  packages/console/src/assets/docs/guides/native-android/README.mdx
Labels: enhancement, size/m

#6139 refactor(test): use secure random method in integration test util
  packages/integration-tests/src/utils.ts
Labels: enhancement, size/xs

#6142 refactor(console): polish guides
  packages/console/src/assets/docs/fragments/_redirect-uris-web.mdx
  packages/console/src/assets/docs/guides/web-next-app-router/README.mdx
  packages/console/src/assets/docs/guides/web-next/README.mdx
  packages/console/src/assets/docs/guides/web-php/README.mdx
  packages/console/src/assets/docs/guides/web-python/README.mdx
Labels: enhancement, size/s

#6137 chore(console): remove unmaintained remix guide
  packages/console/src/assets/docs/guides/index.tsx
  packages/console/src/assets/docs/guides/web-remix/README.mdx
  packages/console/src/assets/docs/guides/web-remix/config.json
  packages/console/src/assets/docs/guides/web-remix/index.ts
  packages/console/src/assets/docs/guides/web-remix/logo.svg
Labels: chore, size/m
