Repository logto-io/logto, pull requests merged in 2024-08, with the labels that each got.

#6375 refactor(core): allow cloudflare insights origin in csp
  packages/core/src/middleware/koa-security-headers.ts
Labels: enhancement, size/xs

#6368 feat(core,schemas): add mandatory password guard on register
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.test.ts
  packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.ts
  packages/core/src/routes/experience/classes/verifications/new-password-identity-verification.ts
  packages/core/src/routes/experience/verification-routes/new-password-identity-verification.ts
  packages/integration-tests/src/client/experience/index.ts
  packages/integration-tests/src/helpers/experience/index.ts
  packages/integration-tests/src/tests/api/experience-api/register-interaction/verification-code.test.ts
  packages/integration-tests/src/tests/api/experience-api/verifications/new-password-identity-verification.test.ts
  packages/phrases/src/locales/en/errors/session.ts
  packages/schemas/src/types/interactions.ts
Labels: feature, size/l

#6358 feat: add advanced search params to all supported endpoints
  packages/core/src/routes/swagger/index.ts
  packages/core/src/routes/swagger/utils/parameters.ts
Labels: feature, size/s

#6365 feat(cli): add cli command to setup custom ui local debugging proxy
  .changeset/slow-buses-rhyme.md
  packages/cli/package.json
  packages/cli/src/commands/proxy/index.ts
  packages/cli/src/commands/proxy/types.ts
  packages/cli/src/commands/proxy/utils.ts
  packages/cli/src/index.ts
  pnpm-lock.yaml
Labels: feature, size/l

#6370 feat(core,console,phrases): add custom data editor to application details page
  .changeset/gold-mails-sin.md
  .changeset/sweet-rules-hear.md
  packages/console/src/assets/docs/guides/web-gpt-plugin/components/AlwaysIssueRefreshToken.tsx
  packages/console/src/mdx-components/UriInputField/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Settings.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/utils.ts
  packages/core/src/queries/application.ts
  packages/core/src/routes/applications/application-custom-data.ts
  packages/core/src/routes/applications/application.ts
  packages/core/src/routes/applications/types.ts
  packages/integration-tests/src/tests/api/application/application-custom-data.test.ts
  packages/integration-tests/src/tests/api/application/application.test.ts
  packages/integration-tests/src/tests/console/backchannel-logout.test.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
Labels: feature, size/m

#6379 fix(core): allow non-json body type when parsing
  packages/core/src/oidc/init.ts
Labels: bugfix, size/xs

#6377 refactor(core): make password optional in NewPasswordIdentity
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.test.ts
  packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.ts
  packages/core/src/routes/experience/classes/verifications/new-password-identity-verification.ts
  packages/core/src/routes/experience/verification-routes/new-password-identity-verification.ts
  packages/integration-tests/src/client/experience/index.ts
  packages/integration-tests/src/tests/api/experience-api/register-interaction/verification-code.test.ts
  packages/integration-tests/src/tests/api/experience-api/verifications/new-password-identity-verification.test.ts
Labels: enhancement, size/l

#6369 refactor(console): get and check `skuId` from checkout session
  packages/console/package.json
  packages/console/src/pages/CheckoutSuccessCallback/index.tsx
  pnpm-lock.yaml
Labels: enhancement, size/s

#6380 refactor: add tests for content-type in oidc apis
  packages/core/src/oidc/init.ts
  packages/integration-tests/src/tests/api/oidc/content-type-json.test.ts
Labels: enhancement, size/s

#6345 refactor(console): delay module loading suspense component display by 500ms
  packages/console/src/containers/ConsoleContent/index.tsx
Labels: enhancement, size/s

#6382 fix(core): error data bug fixing
  packages/core/src/routes/experience/classes/libraries/password-validator.ts
  packages/core/src/routes/experience/classes/mfa.ts
Labels: bugfix, size/s

#6384 refactor(console): update billing info showed in subscription details page
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/index.tsx
Labels: enhancement, size/s

#6386 fix(console): add in-line error message
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Settings.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/utils.ts
  packages/console/src/pages/OrganizationDetails/Settings/index.tsx
  packages/console/src/pages/OrganizationDetails/Settings/utils.ts
  packages/console/src/utils/json.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
Labels: bugfix, size/m

#6381 fix(console): create tenant button should stretch to full width
  packages/console/src/components/Topbar/TenantSelector/index.module.scss
Labels: bugfix, size/xs

#6360 fix(console): manual update subscription data when add/delete resources
  packages/console/src/hooks/use-api.ts
  packages/console/src/hooks/use-subscribe.ts
  packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx
  packages/console/src/pages/ApiResourceDetails/index.tsx
Labels: bugfix, size/s

#6392 chore(phrases): update content
  packages/phrases/src/locales/en/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/ja/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/ko/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/upsell/paywall.ts
Labels: chore, size/m

#6393 fix(console): fix the subscription plan display in tenant dropdown
  packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx
Labels: bugfix, size/xs

#6394 refactor(core): should not guard sso authentication flow
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/enterprise-sso.test.ts
Labels: enhancement, size/s

#6387 fix(core): should not throw when not adding any new roles to a user
  packages/core/src/queries/users-roles.ts
  packages/integration-tests/src/api/admin-user.ts
  packages/integration-tests/src/tests/api/oidc/id-token.test.ts
Labels: bugfix, size/s

#6399 fix(console): should not call cloud API when tenant ID is not valid
  packages/console/src/hooks/use-new-subscription-quota.ts
  packages/console/src/hooks/use-new-subscription-scopes-usage.ts
  packages/console/src/hooks/use-new-subscription-usage.ts
Labels: bugfix, size/xs

#6404 feat(core,schemas): add support for argon2d and argon2id
  .changeset/thirty-cups-joke.md
  packages/core/src/libraries/user.test.ts
  packages/core/src/libraries/user.ts
  packages/schemas/alterations/next-1722926389-argon2d-argon2id.ts
  packages/schemas/tables/users.sql
Labels: feature, size/s

#6397 feat(console): support next auth v5
  packages/console/src/assets/docs/guides/web-next-auth/README.mdx
Labels: feature, size/s

#6376 refactor: produce br outputs
  packages/console/vite.config.ts
  packages/demo-app/index.html
  packages/demo-app/package.json
  packages/demo-app/vite.config.ts
  packages/experience/vite.config.ts
  pnpm-lock.yaml
Labels: enhancement, size/s

#6403 refactor: add `report:subscription:updates` Cloud scope
  packages/cli/src/commands/database/seed/tables.ts
  packages/core/src/libraries/cloud-connection.ts
  packages/schemas/alterations/next-1722914357-add-report-sub-updates-cloud-scope.ts
  packages/schemas/src/seeds/cloud-api.ts
Labels: enhancement, size/m

#6412 Revert "refactor: add `report:subscription:updates` Cloud scope"
  packages/cli/src/commands/database/seed/tables.ts
  packages/core/src/libraries/cloud-connection.ts
  packages/schemas/alterations/next-1722914357-add-report-sub-updates-cloud-scope.ts
  packages/schemas/src/seeds/cloud-api.ts
Labels: size/m

#6374 feat(core): add Sentinel guard
  packages/core/src/routes/experience/classes/libraries/sentinel-guard.ts
  packages/core/src/routes/experience/verification-routes/password-verification.ts
  packages/core/src/routes/experience/verification-routes/verification-code.ts
Labels: feature, size/m

#6395 feat(core): support google one tap
  packages/core/src/routes/experience/classes/verifications/social-verification.ts
  packages/core/src/routes/experience/verification-routes/enterprise-sso-verification.ts
  packages/core/src/routes/experience/verification-routes/social-verification.ts
  packages/core/src/routes/interaction/utils/social-verification.test.ts
  packages/core/src/routes/interaction/utils/social-verification.ts
  packages/integration-tests/src/tests/api/experience-api/verifications/social-verification.test.ts
  packages/schemas/src/types/interactions.ts
Labels: feature, size/s

#6401 refactor(core,schemas): refactor the register flow
  packages/core/src/routes/experience/classes/experience-interaction.test.ts
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/classes/libraries/profile-validator.ts
  packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.test.ts
  packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.ts
  packages/core/src/routes/experience/classes/profile.ts
  packages/core/src/routes/experience/classes/verifications/new-password-identity-verification.ts
  packages/core/src/routes/experience/classes/verifications/web-authn-verification.ts
  packages/core/src/routes/experience/index.ts
  packages/core/src/routes/experience/profile-routes.ts
  packages/core/src/routes/experience/types.ts
  packages/core/src/routes/experience/verification-routes/new-password-identity-verification.ts
  packages/core/src/routes/experience/verification-routes/web-authn-verification.ts
  packages/integration-tests/src/client/experience/index.ts
  packages/integration-tests/src/helpers/experience/index.ts
  packages/integration-tests/src/tests/api/experience-api/register-interaction/username-password.test.ts
  packages/integration-tests/src/tests/api/experience-api/register-interaction/verification-code.test.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/enterprise-sso.test.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/social.test.ts
  packages/integration-tests/src/tests/api/experience-api/verifications/new-password-identity-verification.test.ts
  packages/schemas/src/types/interactions.ts
Labels: enhancement, size/xl

#6409 feat: add add-on feature footer notice and paywall tag
  packages/console/src/components/AddOnNoticeFooter/index.module.scss
  packages/console/src/components/AddOnNoticeFooter/index.tsx
  packages/console/src/components/ApplicationCreation/CreateForm/Footer/index.module.scss
  packages/console/src/components/ApplicationCreation/CreateForm/Footer/index.tsx
  packages/console/src/components/ApplicationCreation/CreateForm/index.tsx
  packages/console/src/components/FeatureTag/AddOnTag.tsx
  packages/console/src/components/FeatureTag/index.tsx
  packages/console/src/consts/subscriptions.ts
  packages/console/src/ds-components/ModalLayout/index.tsx
  packages/console/src/hooks/use-user-preferences.ts
  packages/console/src/pages/ApiResources/components/CreateForm/Footer.tsx
  packages/console/src/pages/ApiResources/components/CreateForm/index.module.scss
  packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
  packages/console/src/pages/CustomizeJwt/CreateButton/index.tsx
  packages/console/src/pages/CustomizeJwt/UpsellNotice/index.module.scss
  packages/console/src/pages/CustomizeJwt/UpsellNotice/index.tsx
  packages/console/src/pages/CustomizeJwt/index.module.scss
  packages/console/src/pages/CustomizeJwt/index.tsx
  packages/console/src/pages/EnterpriseSso/SsoCreationModal/index.module.scss
  packages/console/src/pages/EnterpriseSso/SsoCreationModal/index.tsx
  packages/console/src/pages/EnterpriseSso/index.tsx
  packages/console/src/pages/Mfa/MfaForm/UpsellNotice/index.tsx
  packages/console/src/pages/Mfa/MfaForm/index.module.scss
  packages/console/src/pages/Mfa/MfaForm/index.tsx
  packages/console/src/pages/Mfa/PageWrapper/index.tsx
  packages/console/src/pages/OrganizationTemplate/index.tsx
  packages/console/src/pages/Organizations/CreateOrganizationModal/index.module.scss
  packages/console/src/pages/Organizations/CreateOrganizationModal/index.tsx
  packages/console/src/pages/Organizations/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/index.module.scss
  packages/phrases/src/locales/de/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/en/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/en/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/es/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/fr/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/it/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/ja/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/ko/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/ru/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/upsell/add-on.ts
Labels: feature, size/xl

#6413 feat(console): add new usage display for pro subscription plan
  packages/console/src/components/PlanUsage/ProPlanUsageCard/index.module.scss
  packages/console/src/components/PlanUsage/ProPlanUsageCard/index.tsx
  packages/console/src/components/PlanUsage/index.module.scss
  packages/console/src/components/PlanUsage/index.tsx
  packages/console/src/components/PlanUsage/utils.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/usage.ts
Labels: feature, size/l

#6419 feat: report subscription usage updates
  packages/core/package.json
  packages/core/src/libraries/quota.ts
  packages/core/src/middleware/koa-quota-guard.ts
  packages/core/src/routes/applications/application.ts
  packages/core/src/routes/hook.ts
  packages/core/src/routes/organization-role/index.ts
  packages/core/src/routes/organization-scope/index.ts
  packages/core/src/routes/organization/index.ts
  packages/core/src/routes/resource.ts
  packages/core/src/routes/sign-in-experience/index.ts
  packages/core/src/routes/sso-connector/index.ts
  packages/core/src/test-utils/quota.ts
  packages/core/src/utils/subscription/index.ts
  packages/core/src/utils/subscription/types.ts
  pnpm-lock.yaml
Labels: feature, size/m

#6400 feat: support `login_hint` params for sign-in url
  .changeset/popular-monkeys-complain.md
  packages/core/src/oidc/utils.test.ts
  packages/core/src/oidc/utils.ts
  packages/experience/src/pages/Register/IdentifierRegisterForm/index.tsx
  packages/experience/src/pages/SignIn/IdentifierSignInForm/index.tsx
  packages/experience/src/pages/SignIn/PasswordSignInForm/index.tsx
  packages/schemas/src/consts/oidc.ts
Labels: feature, size/s

#6426 refactor(console): avoid getSubscription call before authentication
  packages/console/src/containers/AppContent/index.tsx
  packages/console/src/contexts/SubscriptionDataProvider/index.tsx
  packages/console/src/contexts/SubscriptionDataProvider/types.ts
  packages/console/src/contexts/SubscriptionDataProvider/use-new-subscription-data.ts
  packages/console/src/hooks/use-api.ts
  packages/console/src/hooks/use-subscribe.ts
Labels: enhancement, size/m

#6227 feat(connector): add kook connector
  .changeset/pink-baboons-mix.md
  packages/connectors/connector-kook/README.md
  packages/connectors/connector-kook/docs/oauth2-link-builder.png
  packages/connectors/connector-kook/docs/oauth2-permission-required-page.png
  packages/connectors/connector-kook/logo.svg
  packages/connectors/connector-kook/package.json
  packages/connectors/connector-kook/src/constant.ts
  packages/connectors/connector-kook/src/index.test.ts
  packages/connectors/connector-kook/src/index.ts
  packages/connectors/connector-kook/src/mock.ts
  packages/connectors/connector-kook/src/types.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#6431 fix(console): catch timeout error when submitting form
  packages/console/src/utils/form.ts
Labels: bugfix, size/s

#6427 refactor(core): merge subscription usage API request
  packages/connectors/connector-logto-email/package.json
  packages/console/package.json
  packages/console/src/cloud/types/router.ts
  packages/console/src/contexts/SubscriptionDataProvider/index.tsx
  packages/console/src/contexts/SubscriptionDataProvider/types.ts
  packages/console/src/contexts/SubscriptionDataProvider/use-new-subscription-data.ts
  packages/console/src/hooks/use-new-subscription-quota.ts
  packages/console/src/hooks/use-new-subscription-scopes-usage.ts
  packages/console/src/hooks/use-new-subscription-usage.ts
  packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx
  packages/console/src/pages/RoleDetails/RolePermissions/components/AssignPermissionsModal/index.tsx
  packages/core/package.json
  packages/core/src/utils/subscription/types.ts
  pnpm-lock.yaml
Labels: enhancement, size/m

#6425 fix(experience): prevent errors from applying unsupported cached identifier types
  .changeset/rare-moons-unite.md
  packages/experience/src/Providers/UserInteractionContextProvider/UserInteractionContext.tsx
  packages/experience/src/Providers/UserInteractionContextProvider/index.tsx
  packages/experience/src/pages/ForgotPassword/ForgotPasswordForm/index.tsx
  packages/experience/src/pages/Register/IdentifierRegisterForm/index.tsx
  packages/experience/src/pages/SignIn/IdentifierSignInForm/index.tsx
  packages/integration-tests/src/tests/experience/identifier-input-cache.test.ts
Labels: bugfix, size/m

#6383 feat(schemas): init personal access tokens table
  packages/schemas/alterations/next-1722506508-personal-access-tokens.ts
  packages/schemas/tables/personal_access_tokens.sql
Labels: feature, size/s

#6434 refactor: stop using GET /:tenantId/usage API and GET /tenants usage field
  packages/console/src/cloud/types/router.ts
  packages/console/src/components/MauExceededModal/index.tsx
  packages/console/src/components/PlanUsage/index.tsx
  packages/console/src/contexts/SubscriptionDataProvider/use-new-subscription-data.ts
  packages/console/src/hooks/use-subscription-usage.ts
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/MauLimitExceededNotification/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/index.tsx
Labels: enhancement, size/m

#6388 feat(core): create PAT
  packages/core/src/middleware/koa-slonik-error-handler.ts
  packages/core/src/queries/personal-access-tokens.ts
  packages/core/src/routes/admin-user/index.ts
  packages/core/src/routes/admin-user/personal-access-token.openapi.json
  packages/core/src/routes/admin-user/personal-access-token.ts
  packages/core/src/tenants/Queries.ts
  packages/integration-tests/src/api/admin-user.ts
  packages/integration-tests/src/tests/api/admin-user.personal-access-tokens.test.ts
  packages/phrases/src/locales/en/errors/user.ts
Labels: feature, size/m

#6389 feat(core): list PATs
  packages/core/src/routes/admin-user/personal-access-token.openapi.json
  packages/core/src/routes/admin-user/personal-access-token.ts
  packages/integration-tests/src/api/admin-user.ts
  packages/integration-tests/src/tests/api/admin-user.personal-access-tokens.test.ts
Labels: feature, size/s

#6420 test(experience): update unit tests (migration-6)
  packages/experience/src/apis/api.ts
  packages/experience/src/apis/consent.ts
  packages/experience/src/apis/const.ts
  packages/experience/src/apis/experience/const.ts
  packages/experience/src/apis/interaction.ts
  packages/experience/src/apis/settings.ts
  packages/experience/src/apis/single-sign-on.ts
  packages/experience/src/containers/SocialLinkAccount/index.test.tsx
  packages/experience/src/containers/VerificationCode/index.test.tsx
  packages/experience/src/pages/Continue/SetEmailOrPhone/index.test.tsx
  packages/experience/src/pages/Continue/SetUsername/index.test.tsx
  packages/experience/src/pages/ForgotPassword/ForgotPasswordForm/index.test.tsx
  packages/experience/src/pages/Register/IdentifierRegisterForm/index.test.tsx
  packages/experience/src/pages/RegisterPassword/index.test.tsx
  packages/experience/src/pages/ResetPassword/index.test.tsx
  packages/experience/src/pages/SignIn/IdentifierSignInForm/index.test.tsx
  packages/experience/src/pages/SignIn/PasswordSignInForm/index.test.tsx
  packages/experience/src/pages/SignInPassword/PasswordForm/index.test.tsx
  packages/experience/src/pages/SignInPassword/index.test.tsx
  packages/experience/src/pages/SocialLinkAccount/index.test.tsx
  packages/experience/src/pages/SocialSignInWebCallback/index.test.tsx
  packages/experience/src/pages/VerificationCode/index.test.tsx
Labels: testing, size/xl

#6390 feat(core): modify and delete PATs
  packages/core/src/queries/personal-access-tokens.ts
  packages/core/src/routes/admin-user/personal-access-token.openapi.json
  packages/core/src/routes/admin-user/personal-access-token.ts
  packages/integration-tests/src/api/admin-user.ts
  packages/integration-tests/src/tests/api/admin-user.personal-access-tokens.test.ts
Labels: feature, size/m

#6438 fix: update tenant selector dropdown data source
  packages/console/package.json
  packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/TenantStatusTag.tsx
  packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx
  packages/console/src/consts/tenants.ts
  packages/core/package.json
  packages/core/src/libraries/quota.ts
  packages/core/src/utils/subscription/index.ts
  pnpm-lock.yaml
Labels: bugfix, size/s

#6435 feat(experience): add identifier sign-in page
  packages/experience/src/App.tsx
  packages/experience/src/Layout/FirstScreenLayout/index.module.scss
  packages/experience/src/Layout/FirstScreenLayout/index.tsx
  packages/experience/src/Layout/IdentifierPageLayout/index.module.scss
  packages/experience/src/Layout/IdentifierPageLayout/index.tsx
  packages/experience/src/Layout/LandingPageLayout/index.tsx
  packages/experience/src/components/PageMeta/index.tsx
  packages/experience/src/constants/env.ts
  packages/experience/src/hooks/use-identifier-params.ts
  packages/experience/src/pages/IdentifierSignIn/index.tsx
  packages/experience/src/pages/IdentifierSignIn/use-identifier-sign-in-methods.ts
  packages/experience/src/types/guard.ts
  packages/phrases-experience/src/locales/de/description.ts
  packages/phrases-experience/src/locales/en/description.ts
  packages/phrases-experience/src/locales/es/description.ts
  packages/phrases-experience/src/locales/fr/description.ts
  packages/phrases-experience/src/locales/it/description.ts
  packages/phrases-experience/src/locales/ja/description.ts
  packages/phrases-experience/src/locales/ko/description.ts
  packages/phrases-experience/src/locales/pl-pl/description.ts
  packages/phrases-experience/src/locales/pt-br/description.ts
  packages/phrases-experience/src/locales/pt-pt/description.ts
  packages/phrases-experience/src/locales/ru/description.ts
  packages/phrases-experience/src/locales/tr-tr/description.ts
  packages/phrases-experience/src/locales/zh-cn/description.ts
  packages/phrases-experience/src/locales/zh-hk/description.ts
  packages/phrases-experience/src/locales/zh-tw/description.ts
  packages/schemas/src/consts/experience.ts
Labels: feature, size/l

#6437 feat(experience): add identifier register page
  packages/experience/src/App.tsx
  packages/experience/src/pages/IdentifierRegister/index.tsx
  packages/experience/src/pages/IdentifierRegister/use-identifier-sign-up-methods.ts
  packages/phrases-experience/src/locales/de/description.ts
  packages/phrases-experience/src/locales/en/description.ts
  packages/phrases-experience/src/locales/es/description.ts
  packages/phrases-experience/src/locales/fr/description.ts
  packages/phrases-experience/src/locales/it/description.ts
  packages/phrases-experience/src/locales/ja/description.ts
  packages/phrases-experience/src/locales/ko/description.ts
  packages/phrases-experience/src/locales/pl-pl/description.ts
  packages/phrases-experience/src/locales/pt-br/description.ts
  packages/phrases-experience/src/locales/pt-pt/description.ts
  packages/phrases-experience/src/locales/ru/description.ts
  packages/phrases-experience/src/locales/tr-tr/description.ts
  packages/phrases-experience/src/locales/zh-cn/description.ts
  packages/phrases-experience/src/locales/zh-hk/description.ts
  packages/phrases-experience/src/locales/zh-tw/description.ts
  packages/schemas/src/consts/experience.ts
Labels: feature, size/m

#6441 fix(console): should not block custom JWT creation for OSS user
  .changeset/friendly-rice-sell.md
  packages/console/src/pages/CustomizeJwt/CreateButton/index.tsx
Labels: bugfix, size/s

#6417 refactor(experience): migrate mfa flow (migration-5)
  packages/experience/src/apis/api.ts
  packages/experience/src/apis/consent.ts
  packages/experience/src/apis/const.ts
  packages/experience/src/apis/experience.ts
  packages/experience/src/apis/experience/const.ts
  packages/experience/src/apis/experience/index.ts
  packages/experience/src/apis/experience/interaction.ts
  packages/experience/src/apis/experience/mfa.ts
  packages/experience/src/apis/experience/social.ts
  packages/experience/src/apis/interaction.ts
  packages/experience/src/apis/settings.ts
  packages/experience/src/apis/single-sign-on.ts
  packages/experience/src/containers/SocialLinkAccount/index.test.tsx
  packages/experience/src/containers/TotpCodeVerification/index.tsx
  packages/experience/src/containers/TotpCodeVerification/use-totp-code-verification.ts
  packages/experience/src/containers/VerificationCode/index.test.tsx
  packages/experience/src/hooks/use-mfa-error-handler.ts
  packages/experience/src/hooks/use-send-mfa-payload.ts
  packages/experience/src/hooks/use-skip-mfa.ts
  packages/experience/src/hooks/use-start-backup-code-binding.ts
  packages/experience/src/hooks/use-start-totp-binding.ts
  packages/experience/src/hooks/use-start-webauthn-processing.ts
  packages/experience/src/hooks/use-webauthn-operation.ts
  packages/experience/src/pages/Continue/SetEmailOrPhone/index.test.tsx
  packages/experience/src/pages/Continue/SetUsername/index.test.tsx
  packages/experience/src/pages/ForgotPassword/ForgotPasswordForm/index.test.tsx
  packages/experience/src/pages/MfaBinding/BackupCodeBinding/index.tsx
  packages/experience/src/pages/MfaBinding/TotpBinding/VerificationSection.tsx
  packages/experience/src/pages/MfaBinding/TotpBinding/index.tsx
  packages/experience/src/pages/MfaBinding/WebAuthnBinding/index.tsx
  packages/experience/src/pages/MfaVerification/WebAuthnVerification/index.tsx
  packages/experience/src/pages/Register/IdentifierRegisterForm/index.test.tsx
  packages/experience/src/pages/RegisterPassword/index.test.tsx
  packages/experience/src/pages/ResetPassword/index.test.tsx
  packages/experience/src/pages/SignIn/IdentifierSignInForm/index.test.tsx
  packages/experience/src/pages/SignIn/PasswordSignInForm/index.test.tsx
  packages/experience/src/pages/SignInPassword/PasswordForm/index.test.tsx
  packages/experience/src/pages/SignInPassword/index.test.tsx
  packages/experience/src/pages/SocialLinkAccount/index.test.tsx
  packages/experience/src/pages/SocialSignInWebCallback/index.test.tsx
  packages/experience/src/pages/VerificationCode/index.test.tsx
  packages/experience/src/types/guard.ts
Labels: enhancement, size/xl

#6442 refactor(cli): rename proxy cli to tunnel
  .changeset/long-rabbits-roll.md
  packages/cli/src/commands/tunnel/index.ts
  packages/cli/src/commands/tunnel/types.ts
  packages/cli/src/commands/tunnel/utils.ts
  packages/cli/src/index.ts
Labels: enhancement, size/s

#6436 feat(core): add experience APIs openapi docs
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/classes/verifications/new-password-identity-verification.ts
  packages/core/src/routes/experience/experience.openapi.json
  packages/core/src/routes/experience/index.ts
  packages/core/src/routes/experience/profile-routes.openapi.json
  packages/core/src/routes/experience/verification-routes/backup-code-verification.openapi.json
  packages/core/src/routes/experience/verification-routes/backup-code-verification.ts
  packages/core/src/routes/experience/verification-routes/enterprise-sso-verification.openapi.json
  packages/core/src/routes/experience/verification-routes/new-password-identity-verification.openapi.json
  packages/core/src/routes/experience/verification-routes/password-verification.openapi.json
  packages/core/src/routes/experience/verification-routes/password-verification.ts
  packages/core/src/routes/experience/verification-routes/social-verification.openapi.json
  packages/core/src/routes/experience/verification-routes/totp-verification.openapi.json
  packages/core/src/routes/experience/verification-routes/totp-verification.ts
  packages/core/src/routes/experience/verification-routes/verification-code.openapi.json
  packages/core/src/routes/experience/verification-routes/web-authn-verification.openapi.json
  packages/core/src/routes/experience/verification-routes/web-authn-verification.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/swagger/index.ts
  packages/core/src/routes/swagger/utils/operation-id.ts
  packages/integration-tests/src/tests/api/experience-api/verifications/backup-code-verification.test.ts
  packages/integration-tests/src/tests/api/experience-api/verifications/totp-verification.test.ts
Labels: feature, size/xl

#6448 refactor(console): separate subscription based usage
  packages/console/package.json
  packages/console/src/cloud/types/router.ts
  packages/console/src/components/MauExceededModal/index.tsx
  packages/console/src/components/PlanUsage/index.tsx
  packages/console/src/consts/tenants.ts
  packages/console/src/contexts/SubscriptionDataProvider/types.ts
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/MauLimitExceededNotification/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/index.tsx
  pnpm-lock.yaml
Labels: enhancement, size/m

#6447 fix(console): should be able to edit password and email in profile
  packages/console/src/cloud/AppRoutes.tsx
  packages/console/src/components/DelayedSuspenseFallback/index.module.scss
  packages/console/src/components/DelayedSuspenseFallback/index.tsx
  packages/console/src/containers/ConsoleContent/index.tsx
Labels: bugfix, size/m

#6443 fix: fix console issues for add-on
  packages/console/src/components/ApplicationCreation/CreateForm/Footer/index.tsx
  packages/console/src/components/ApplicationCreation/CreateForm/index.tsx
  packages/console/src/components/PlanUsage/ProPlanUsageCard/index.tsx
  packages/console/src/components/PlanUsage/index.tsx
  packages/console/src/components/PlanUsage/utils.ts
  packages/console/src/consts/subscriptions.ts
  packages/console/src/hooks/use-subscribe.ts
  packages/console/src/onboarding/pages/CreateTenant/index.tsx
  packages/console/src/pages/ApiResources/components/CreateForm/Footer.tsx
  packages/console/src/pages/CheckoutSuccessCallback/index.tsx
  packages/console/src/pages/Mfa/MfaForm/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/en/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/es/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/fr/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/it/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/ja/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/ko/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/ru/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/upsell/add-on.ts
Labels: bugfix, size/m

#6454 refactor(core): redesign get sso connectors endpoint
  packages/core/src/routes/experience/anonymous-routes/index.openapi.json
  packages/core/src/routes/experience/anonymous-routes/index.ts
  packages/core/src/routes/experience/index.ts
  packages/core/src/routes/experience/middleware/koa-experience-interaction.ts
  packages/core/src/routes/experience/verification-routes/enterprise-sso-verification.openapi.json
  packages/core/src/routes/experience/verification-routes/enterprise-sso-verification.ts
  packages/integration-tests/src/client/experience/index.ts
  packages/integration-tests/src/tests/api/experience-api/verifications/enterprise-sso-verification.test.ts
Labels: enhancement, size/m

#6452 fix(console): fix add-on console issues
  packages/console/src/components/AddOnNoticeFooter/index.tsx
  packages/console/src/components/ApplicationCreation/CreateForm/Footer/index.tsx
  packages/console/src/components/PlanUsage/PlanUsageCard/index.module.scss
  packages/console/src/components/PlanUsage/PlanUsageCard/index.tsx
  packages/console/src/components/PlanUsage/index.module.scss
  packages/console/src/components/PlanUsage/index.tsx
  packages/console/src/hooks/use-subscribe.ts
  packages/console/src/hooks/use-user-preferences.ts
  packages/console/src/pages/ApiResources/components/CreateForm/Footer.tsx
  packages/console/src/pages/EnterpriseSso/SsoCreationModal/index.tsx
  packages/console/src/pages/Organizations/CreateOrganizationModal/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/de/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/en/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/es/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/fr/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/it/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ja/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ko/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ru/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/upsell/add-on.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/upsell/add-on.ts
Labels: bugfix, size/xl

#6455 fix(core): fix google one tap validation error
  packages/core/src/routes/experience/verification-routes/social-verification.ts
Labels: bugfix, size/xs

#6453 refactor(console): refactor tag component
  packages/console/src/components/ApplicationCreation/CreateForm/index.tsx
  packages/console/src/components/FeatureTag/AddOnTag.tsx
  packages/console/src/components/FeatureTag/index.tsx
  packages/console/src/ds-components/CardTitle/index.tsx
  packages/console/src/ds-components/ModalLayout/index.tsx
  packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
  packages/console/src/pages/EnterpriseSso/SsoCreationModal/index.tsx
  packages/console/src/pages/EnterpriseSso/index.tsx
  packages/console/src/pages/Mfa/PageWrapper/index.tsx
  packages/console/src/pages/OrganizationTemplate/index.tsx
  packages/console/src/pages/Organizations/CreateOrganizationModal/index.tsx
  packages/console/src/pages/Organizations/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/index.tsx
Labels: enhancement, size/m

#6440 feat(experience): add identifier sso-only landing page
  packages/experience/src/App.tsx
  packages/experience/src/Layout/FocusedAuthPageLayout/index.module.scss
  packages/experience/src/Layout/FocusedAuthPageLayout/index.tsx
  packages/experience/src/pages/IdentifierRegister/index.tsx
  packages/experience/src/pages/IdentifierSignIn/index.tsx
  packages/experience/src/pages/SingleSignOnEmail/SingleSignOnForm/index.module.scss
  packages/experience/src/pages/SingleSignOnEmail/SingleSignOnForm/index.tsx
  packages/experience/src/pages/SingleSignOnEmail/index.tsx
  packages/experience/src/pages/SingleSignOnLanding/index.tsx
Labels: feature, size/l

#6446 feat(core,experience,schemas): support identifier page related params for sign-in url
  packages/core/src/oidc/utils.test.ts
  packages/core/src/oidc/utils.ts
  packages/experience/src/hooks/use-identifier-params.test.ts
  packages/experience/src/hooks/use-identifier-params.ts
  packages/schemas/src/consts/experience.ts
  packages/schemas/src/consts/oidc.ts
  packages/schemas/src/foundations/jsonb-types/sign-in-experience.ts
Labels: feature, size/m

#6456 chore(console): add display pricing change notice and update plan comparison table
  packages/console/src/consts/subscriptions.ts
  packages/console/src/hooks/use-user-preferences.ts
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/AddOnUsageChangesNotification/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-table.ts
Labels: chore, size/m

#6457 chore(experience): move shared form components into components file
  packages/experience/src/components/IdentifierRegisterForm/index.module.scss
  packages/experience/src/components/IdentifierRegisterForm/index.test.tsx
  packages/experience/src/components/IdentifierRegisterForm/index.tsx
  packages/experience/src/components/IdentifierRegisterForm/use-on-submit.ts
  packages/experience/src/components/IdentifierRegisterForm/use-register-with-username.ts
  packages/experience/src/components/IdentifierSignInForm/index.module.scss
  packages/experience/src/components/IdentifierSignInForm/index.test.tsx
  packages/experience/src/components/IdentifierSignInForm/index.tsx
  packages/experience/src/components/IdentifierSignInForm/use-on-submit.ts
  packages/experience/src/components/PasswordSignInForm/index.module.scss
  packages/experience/src/components/PasswordSignInForm/index.test.tsx
  packages/experience/src/components/PasswordSignInForm/index.tsx
  packages/experience/src/components/SingleSignOnForm/index.module.scss
  packages/experience/src/components/SingleSignOnForm/index.tsx
  packages/experience/src/pages/IdentifierRegister/index.tsx
  packages/experience/src/pages/IdentifierSignIn/index.tsx
  packages/experience/src/pages/Register/index.tsx
  packages/experience/src/pages/SignIn/Main.tsx
  packages/experience/src/pages/SingleSignOnEmail/index.tsx
  packages/experience/src/pages/SingleSignOnLanding/index.tsx
Labels: chore, size/s

#6445 feat(core): implement wellknown swagger endpoints
  packages/core/src/routes/init.ts
  packages/core/src/routes/interaction/index.openapi.json
  packages/core/src/routes/swagger/index.ts
  packages/core/src/routes/swagger/utils/documents.ts
  packages/core/src/routes/swagger/utils/general.ts
  packages/core/src/routes/swagger/utils/operation.ts
  packages/core/src/routes/well-known.openapi.json
  packages/core/src/routes/well-known/index.ts
  packages/core/src/routes/well-known/well-known.experience.ts
  packages/core/src/routes/well-known/well-known.openapi.json
  packages/core/src/routes/well-known/well-known.openapi.ts
  packages/core/src/routes/well-known/well-known.phrases.content-language.test.ts
  packages/core/src/routes/well-known/well-known.phrases.test.ts
  packages/core/src/routes/well-known/well-known.test.ts
  packages/integration-tests/src/tests/api/well-known.openapi.test.ts
Labels: feature, size/xl

#6459 chore(console): update add on tag CSS
  packages/console/src/components/FeatureTag/index.module.scss
  packages/console/src/components/FeatureTag/index.tsx
Labels: chore, size/xs

#6463 fix(console): fix impersonation tag in audit log
  packages/console/src/components/AuditLogTable/components/EventName/index.tsx
  packages/console/src/components/AuditLogTable/components/EventName/utils.ts
  packages/console/src/components/AuditLogTable/index.tsx
  packages/console/src/pages/AuditLogDetails/index.tsx
  packages/schemas/src/foundations/jsonb-types/logs.ts
Labels: bugfix, size/s

#6458 fix(cli): should proxy google social callback url properly to exp ui
  packages/cli/src/commands/tunnel/utils.test.ts
  packages/cli/src/commands/tunnel/utils.ts
Labels: bugfix, size/s

#6462 chore(core): remove devFeature guard
  packages/core/src/routes/experience/anonymous-routes/index.openapi.json
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/experience.openapi.json
  packages/core/src/routes/experience/index.ts
  packages/core/src/routes/experience/middleware/koa-experience-interaction.ts
  packages/core/src/routes/experience/profile-routes.openapi.json
  packages/core/src/routes/experience/verification-routes/backup-code-verification.openapi.json
  packages/core/src/routes/experience/verification-routes/enterprise-sso-verification.openapi.json
  packages/core/src/routes/experience/verification-routes/new-password-identity-verification.openapi.json
  packages/core/src/routes/experience/verification-routes/password-verification.openapi.json
  packages/core/src/routes/experience/verification-routes/social-verification.openapi.json
  packages/core/src/routes/experience/verification-routes/totp-verification.openapi.json
  packages/core/src/routes/experience/verification-routes/verification-code.openapi.json
  packages/core/src/routes/experience/verification-routes/web-authn-verification.openapi.json
  packages/core/src/routes/init.ts
  packages/integration-tests/src/tests/api/experience-api/bind-mfa/happpy-path.test.ts
  packages/integration-tests/src/tests/api/experience-api/bind-mfa/sad-path.test.ts
  packages/integration-tests/src/tests/api/experience-api/interaction.test.ts
  packages/integration-tests/src/tests/api/experience-api/profile/fulfill-user-profiles.test.ts
  packages/integration-tests/src/tests/api/experience-api/profile/reset-password.test.ts
  packages/integration-tests/src/tests/api/experience-api/register-interaction/organization-jti.test.ts
  packages/integration-tests/src/tests/api/experience-api/register-interaction/username-password.test.ts
  packages/integration-tests/src/tests/api/experience-api/register-interaction/verification-code.test.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/enterprise-sso.test.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/mfa-verification.test.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/password.test.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/social.test.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/verification-code.test.ts
  packages/integration-tests/src/tests/api/experience-api/verifications/backup-code-verification.test.ts
  packages/integration-tests/src/tests/api/experience-api/verifications/enterprise-sso-verification.test.ts
  packages/integration-tests/src/tests/api/experience-api/verifications/new-password-identity-verification.test.ts
  packages/integration-tests/src/tests/api/experience-api/verifications/password-verification.test.ts
  packages/integration-tests/src/tests/api/experience-api/verifications/social-verification.test.ts
  packages/integration-tests/src/tests/api/experience-api/verifications/totp-verification.test.ts
  packages/integration-tests/src/tests/api/experience-api/verifications/verification-code.test.ts
  packages/integration-tests/src/tests/api/hook/hook.trigger.experience.test.ts
Labels: chore, size/m

#6467 fix(experience): update dev features flag env handling
  packages/experience/src/constants/env.ts
  packages/experience/vite.config.ts
Labels: bugfix, size/s

#6468 fix(console): bring back accidentally deleted css file
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/SkuCardItem/index.module.scss
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/SkuCardItem/index.tsx
Labels: bugfix, size/m

#6464 test(experience): add integration tests for first screen feature
  packages/integration-tests/src/tests/experience/first-screen.test.ts
  packages/integration-tests/src/ui-helpers/expect-experience.ts
Labels: testing, size/m

#6469 feat(console): add label for new experience API logs
  packages/console/src/consts/logs.ts
Labels: feature, size/s

#6450 feat(core): token exchange by pat
  packages/core/src/oidc/grants/token-exchange/account.ts
  packages/core/src/oidc/grants/token-exchange/index.ts
  packages/core/src/oidc/grants/token-exchange/types.ts
  packages/core/src/queries/personal-access-tokens.ts
  packages/integration-tests/src/tests/api/oidc/token-exchange/index.test.ts
  packages/integration-tests/src/tests/api/oidc/token-exchange/personal-access-token.test.ts
Labels: feature, size/l

#6470 chore(console): fix add-on issues
  packages/console/src/components/ApplicationCreation/CreateForm/index.tsx
  packages/console/src/components/BillInfo/index.tsx
  packages/console/src/components/ChargeNotification/index.tsx
  packages/console/src/components/PlanUsage/index.tsx
  packages/console/src/consts/external-links.ts
  packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/index.tsx
Labels: chore, size/s

#6444 feat(console): user personal access tokens
  packages/console/src/pages/UserDetails/UserSettings/components/PersonalAccessTokens/CreateTokenModal.tsx
  packages/console/src/pages/UserDetails/UserSettings/components/PersonalAccessTokens/index.module.scss
  packages/console/src/pages/UserDetails/UserSettings/components/PersonalAccessTokens/index.tsx
  packages/console/src/pages/UserDetails/UserSettings/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/user-details.ts
Labels: feature, size/l

#6471 fix(console): add add-on display issues and refactor component PlanName
  packages/console/src/components/ApplicationCreation/CreateForm/Footer/index.tsx
  packages/console/src/components/CreateConnectorForm/Footer/index.tsx
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/SkuCardItem/index.tsx
  packages/console/src/components/Guide/GuideCard/index.tsx
  packages/console/src/components/MauExceededModal/index.tsx
  packages/console/src/components/PlanName/index.tsx
  packages/console/src/components/PlanUsage/index.module.scss
  packages/console/src/components/PlanUsage/index.tsx
  packages/console/src/components/SkuName/index.tsx
  packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx
  packages/console/src/consts/plan-quotas.ts
  packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx
  packages/console/src/pages/ApiResources/components/CreateForm/Footer.tsx
  packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
  packages/console/src/pages/Applications/components/ProtectedAppForm/index.tsx
  packages/console/src/pages/CheckoutSuccessCallback/index.tsx
  packages/console/src/pages/EnterpriseSso/SsoCreationModal/index.tsx
  packages/console/src/pages/OrganizationTemplate/index.tsx
  packages/console/src/pages/RoleDetails/RolePermissions/components/AssignPermissionsModal/index.tsx
  packages/console/src/pages/Roles/components/CreateRoleForm/Footer.tsx
  packages/console/src/pages/SignInExperience/PageContent/Branding/CustomUiForm/index.tsx
  packages/console/src/pages/TenantSettings/BillingHistory/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/DowngradeConfirmModalContent/PlanQuotaDiffCard/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/DowngradeConfirmModalContent/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/SwitchPlanActionBar/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/Footer/index.tsx
  packages/console/src/pages/TenantSettings/components/NotEligibleSwitchPlanModalContent/index.tsx
  packages/console/src/pages/Webhooks/CreateFormModal/CreateForm.tsx
  packages/console/src/types/subscriptions.ts
  packages/console/src/utils/subscription.ts
Labels: bugfix, size/l

#6473 fix(console): manually trigger usage api updates
  packages/console/src/pages/TenantSettings/TenantMembers/Invitations/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/index.tsx
Labels: bugfix, size/xs

#6472 fix(experience): correct first screen fallbacks
  packages/experience/src/pages/IdentifierRegister/index.tsx
  packages/experience/src/pages/SingleSignOnLanding/index.tsx
  packages/integration-tests/src/api/sso-connector.ts
  packages/integration-tests/src/tests/experience/first-screen.test.ts
Labels: bugfix, size/s

#6477 fix(experience): smart input field should have correct initial type
  packages/experience/src/components/InputFields/SmartInputField/use-smart-input-field.ts
  packages/experience/src/components/InputFields/SmartInputField/utils.ts
Labels: bugfix, size/s

#6478 fix(console): fix next auth guide typo
  packages/console/src/assets/docs/guides/web-next-auth/README.mdx
Labels: bugfix, size/xs

#6481 fix(console,core,connector): fix display issues and POST /connectors API code guard
  .changeset/hip-cats-destroy.md
  packages/connectors/connector-wecom/src/constant.ts
  packages/console/src/components/CreateConnectorForm/Footer/index.tsx
  packages/console/src/components/CreateConnectorForm/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/index.tsx
  packages/core/src/routes/connector/index.openapi.json
  packages/core/src/routes/connector/index.ts
Labels: bugfix, size/s

#6474 fix: translate cli workspace dependency reference
  package.json
  pnpm-lock.yaml
Labels: chore, bugfix, size/xs

#6475 fix(console): manually trigger usage api updates on org member deletion
  packages/console/src/pages/TenantSettings/TenantMembers/Members/index.tsx
Labels: bugfix, size/xs

#6484 chore(console): add beta tag to bring your ui feature
  packages/console/src/ds-components/FormField/index.module.scss
  packages/console/src/ds-components/FormField/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/Branding/CustomUiForm/index.tsx
Labels: chore, size/s

#6483 fix(console): fix console z index issue on modals and banners
  packages/console/src/containers/AppContent/TenantNotificationContainer/CreateProductionTenantBanner/index.module.scss
  packages/console/src/containers/AppContent/TenantNotificationContainer/CreateProductionTenantBanner/index.tsx
  packages/console/src/scss/modal.module.scss
  packages/console/src/scss/normalized.scss
Labels: bugfix, size/s

#6485 chore(console): remove beta tag from 3rd party app
  packages/console/src/components/Guide/GuideCard/index.tsx
  packages/console/src/components/Guide/GuideCardGroup/index.tsx
Labels: chore, size/s

#6415 Revert "Revert "refactor: add `report:subscription:updates` Cloud scope""
  packages/cli/src/commands/database/seed/tables.ts
  packages/core/src/libraries/cloud-connection.ts
  packages/schemas/alterations/next-1724229102-add-report-sub-updates-cloud-scope.ts
  packages/schemas/src/seeds/cloud-api.ts
Labels: size/m

#6488 fix: fix alteration script dependency
  packages/schemas/alterations/next-1724229102-add-report-sub-updates-cloud-scope.ts
Labels: bugfix, size/xs

#6490 style(experience): add missing brand-60 color token
  packages/experience/src/scss/_colors.scss
Labels: size/xs

#6494 fix: make alteration script compatible for core DB in all regions
  packages/schemas/alterations/next-1724229102-add-report-sub-updates-cloud-scope.ts
Labels: bugfix, size/s

#6496 feat(console): add doc link of pat
  packages/console/src/pages/UserDetails/UserSettings/components/PersonalAccessTokens/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/user-details.ts
Labels: feature, size/s

#6491 feat(console): edit personal access token name
  packages/console/src/pages/UserDetails/UserSettings/components/PersonalAccessTokens/EditTokenModal.tsx
  packages/console/src/pages/UserDetails/UserSettings/components/PersonalAccessTokens/index.tsx
Labels: feature, size/m

#6497 fix(core): remove grant id of token exchange
  packages/core/src/oidc/extra-token-claims.ts
  packages/core/src/oidc/grants/token-exchange/account.ts
  packages/core/src/oidc/grants/token-exchange/index.test.ts
  packages/core/src/oidc/grants/token-exchange/index.ts
Labels: bugfix, size/s

#6495 refactor(cli): show more info and add port in-use detection
  packages/cli/src/commands/tunnel/index.ts
  packages/cli/src/commands/tunnel/utils.ts
Labels: enhancement, size/m

#6500 fix(console): always show upsell notice for custom JWT
  packages/console/src/pages/CustomizeJwt/index.tsx
Labels: bugfix, size/xs

#6493 fix(core): remove the requirement of secured app for PAT
  packages/core/src/oidc/grants/token-exchange/index.ts
  packages/integration-tests/src/tests/api/oidc/token-exchange/personal-access-token.test.ts
Labels: bugfix, size/s

#6486 chore(core): add openapi operationId to experience APIs
  packages/core/src/routes/experience/anonymous-routes/index.openapi.json
  packages/core/src/routes/experience/experience.openapi.json
  packages/core/src/routes/experience/profile-routes.openapi.json
  packages/core/src/routes/experience/verification-routes/backup-code-verification.openapi.json
  packages/core/src/routes/experience/verification-routes/enterprise-sso-verification.openapi.json
  packages/core/src/routes/experience/verification-routes/new-password-identity-verification.openapi.json
  packages/core/src/routes/experience/verification-routes/password-verification.openapi.json
  packages/core/src/routes/experience/verification-routes/social-verification.openapi.json
  packages/core/src/routes/experience/verification-routes/totp-verification.openapi.json
  packages/core/src/routes/experience/verification-routes/verification-code.openapi.json
  packages/core/src/routes/experience/verification-routes/web-authn-verification.openapi.json
  packages/core/src/routes/swagger/utils/general.ts
  packages/core/src/routes/swagger/utils/operation-id.ts
Labels: chore, size/m

#6501 test: add integration tests for pat token introspection
  packages/integration-tests/src/tests/api/oidc/token-exchange/personal-access-token.test.ts
Labels: testing, size/s

#6498 feat(experience): add reset password first screen
  packages/core/src/oidc/utils.test.ts
  packages/core/src/oidc/utils.ts
  packages/experience/src/App.tsx
  packages/experience/src/Layout/FocusedAuthPageLayout/index.tsx
  packages/experience/src/pages/ForgotPassword/ForgotPasswordForm/index.tsx
  packages/experience/src/pages/ResetPasswordLanding/index.tsx
  packages/experience/src/pages/ResetPasswordLanding/use-reset-password-methods.ts
  packages/integration-tests/src/tests/experience/first-screen.test.ts
  packages/integration-tests/src/ui-helpers/expect-experience.ts
  packages/phrases-experience/src/locales/de/description.ts
  packages/phrases-experience/src/locales/en/description.ts
  packages/phrases-experience/src/locales/es/description.ts
  packages/phrases-experience/src/locales/fr/description.ts
  packages/phrases-experience/src/locales/it/description.ts
  packages/phrases-experience/src/locales/ja/description.ts
  packages/phrases-experience/src/locales/ko/description.ts
  packages/phrases-experience/src/locales/pl-pl/description.ts
  packages/phrases-experience/src/locales/pt-br/description.ts
  packages/phrases-experience/src/locales/pt-pt/description.ts
  packages/phrases-experience/src/locales/ru/description.ts
  packages/phrases-experience/src/locales/tr-tr/description.ts
  packages/phrases-experience/src/locales/zh-cn/description.ts
  packages/phrases-experience/src/locales/zh-hk/description.ts
  packages/phrases-experience/src/locales/zh-tw/description.ts
  packages/schemas/src/consts/experience.ts
  packages/schemas/src/consts/oidc.ts
Labels: feature, size/m

#6502 fix(core): add grant record for token exchange
  packages/core/src/oidc/grants/token-exchange/index.test.ts
  packages/core/src/oidc/grants/token-exchange/index.ts
  packages/integration-tests/src/tests/api/oidc/token-exchange/personal-access-token.test.ts
Labels: bugfix, size/s

#6503 fix(console): use safeLazy to dynamically import guide mdx
  packages/console/src/assets/docs/guides/index.tsx
  packages/console/src/assets/docs/guides/types.ts
  packages/console/src/assets/docs/single-sign-on/index.ts
  packages/console/src/components/Guide/index.tsx
Labels: bugfix, size/m

#6504 fix(console): change PAT and app secrets phrases
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/EndpointsAndCredentials/index.tsx
  packages/console/src/pages/UserDetails/UserSettings/components/PersonalAccessTokens/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/user-details.ts
  vite.shared.config.ts
Labels: bugfix, size/s

#6506 chore: remove optimize deps config for local dev
  vite.shared.config.ts
Labels: chore, size/xs

#6507 fix(core,schemas): check email verification status in me api
  packages/console/src/App.tsx
  packages/console/src/pages/Profile/containers/VerificationCodeModal/index.tsx
  packages/core/src/libraries/verification-status.ts
  packages/core/src/queries/verification-status.ts
  packages/core/src/routes-me/user.ts
  packages/core/src/routes-me/verification-code.ts
  packages/schemas/alterations/next-1724316971-add-verified-identifier-to-verification-statuses.ts
  packages/schemas/tables/verification_statuses.sql
Labels: bugfix, size/m

#6492 chore: add changeset
  .changeset/funny-goats-tap.md
Labels: chore, size/s

#6499 chore: remove dev feature guard of PAT
  packages/console/src/pages/UserDetails/UserSettings/index.tsx
  packages/core/src/routes/admin-user/index.ts
  packages/core/src/routes/admin-user/personal-access-token.openapi.json
  packages/integration-tests/src/tests/api/oidc/token-exchange/personal-access-token.test.ts
Labels: chore, size/s

#6510 fix(phrases): fix pl and ru i18n phrases
  packages/phrases-experience/src/locales/pl-pl/description.ts
  packages/phrases-experience/src/locales/ru/description.ts
Labels: bugfix, size/s

#6511 fix(core): should be able to update password in profile if verified via email
  packages/core/src/libraries/verification-status.ts
Labels: bugfix, size/xs

#6513 release: @logto/tunnel:0.1.0
  .changeset/long-rabbits-roll.md
  packages/tunnel/CHANGELOG.md
  packages/tunnel/package.json
Labels: size/s

#6508 refactor(experience): improve identifier prefilling
  packages/experience/src/components/IdentifierRegisterForm/index.tsx
  packages/experience/src/components/IdentifierSignInForm/index.tsx
  packages/experience/src/components/InputFields/SmartInputField/use-smart-input-field.ts
  packages/experience/src/components/PasswordSignInForm/index.tsx
  packages/experience/src/hooks/use-login-hint.ts
  packages/experience/src/hooks/use-prefilled-identifier.ts
  packages/experience/src/hooks/use-update-effect.ts
  packages/experience/src/pages/ResetPasswordLanding/index.tsx
Labels: enhancement, size/m

#6515 fix(core): avoid unexpected 500 error
  packages/core/package.json
  packages/core/src/middleware/koa-error-handler.test.ts
  packages/core/src/middleware/koa-error-handler.ts
  pnpm-lock.yaml
Labels: bugfix, size/s

#6517 refactor(experience): remove redundant `defaultType` prop for `SmartInputField`
  packages/experience/src/components/IdentifierRegisterForm/index.test.tsx
  packages/experience/src/components/IdentifierRegisterForm/index.tsx
  packages/experience/src/components/IdentifierSignInForm/index.tsx
  packages/experience/src/components/InputFields/SmartInputField/index.tsx
  packages/experience/src/components/InputFields/SmartInputField/use-smart-input-field.ts
  packages/experience/src/components/InputFields/SmartInputField/utils.ts
  packages/experience/src/components/PasswordSignInForm/index.tsx
  packages/experience/src/pages/Continue/IdentifierProfileForm/index.tsx
  packages/experience/src/pages/ForgotPassword/ForgotPasswordForm/index.test.tsx
  packages/experience/src/pages/ForgotPassword/ForgotPasswordForm/index.tsx
  packages/experience/src/pages/ForgotPassword/index.tsx
  packages/experience/src/pages/Register/index.test.tsx
  packages/integration-tests/src/tests/console/bootstrap.test.ts
  packages/integration-tests/src/tests/experience/bootstrap.test.ts
  packages/integration-tests/src/tests/experience/identifier-input-cache.test.ts
  packages/integration-tests/src/tests/experience/mfa/backup-code/index.test.ts
  packages/integration-tests/src/tests/experience/mfa/totp/passcode-identifier-flow.test.ts
  packages/integration-tests/src/tests/experience/mfa/totp/password-identifier-flow.test.ts
  packages/integration-tests/src/tests/experience/mfa/user-controlled.test.ts
  packages/integration-tests/src/tests/experience/mfa/webauthn/index.test.ts
  packages/integration-tests/src/tests/experience/password-policy.test.ts
Labels: enhancement, size/m

#6516 refactor(experience): cache input identifier for reset password first screen
  packages/experience/src/Providers/UserInteractionContextProvider/UserInteractionContext.tsx
  packages/experience/src/Providers/UserInteractionContextProvider/index.tsx
  packages/experience/src/hooks/use-prefilled-identifier.ts
  packages/experience/src/pages/ForgotPassword/index.tsx
  packages/experience/src/pages/ResetPassword/index.tsx
  packages/experience/src/pages/ResetPasswordLanding/index.tsx
Labels: enhancement, size/m

#6520 chore(experience): upgrade react-hook-form
  packages/experience/package.json
  pnpm-lock.yaml
Labels: chore, size/xs

#6521 fix(experience): apply form default value to smart input filed
  packages/experience/src/components/IdentifierRegisterForm/index.tsx
  packages/experience/src/components/IdentifierSignInForm/index.tsx
  packages/experience/src/components/PasswordSignInForm/index.tsx
  packages/experience/src/components/SingleSignOnForm/index.tsx
  packages/experience/src/pages/ForgotPassword/ForgotPasswordForm/index.tsx
Labels: bugfix, size/s

#6519 feat(core): add `error_code_key` query string param
  .changeset/tiny-fishes-bake.md
  packages/core/src/middleware/koa-oidc-error-handler.ts
Labels: feature, size/s

#6522 chore: remove dev feature guard for first screens
  .changeset/nine-vans-whisper.md
  packages/core/src/oidc/utils.ts
  packages/experience/src/App.tsx
  packages/experience/src/pages/IdentifierRegister/index.tsx
  packages/experience/src/pages/IdentifierSignIn/index.tsx
  packages/integration-tests/src/tests/experience/first-screen.test.ts
Labels: chore, size/m

#6525 refactor(core): refactor oidc error response query param
  .changeset/tiny-fishes-bake.md
  packages/core/src/middleware/koa-oidc-error-handler.ts
Labels: enhancement, size/s

#6514 feat: add Patreon connector
  .changeset/selfish-kangaroos-perform.md
  packages/connectors/connector-patreon/README.md
  packages/connectors/connector-patreon/logo-dark.svg
  packages/connectors/connector-patreon/logo.svg
  packages/connectors/connector-patreon/package.json
  packages/connectors/connector-patreon/src/constant.ts
  packages/connectors/connector-patreon/src/index.test.ts
  packages/connectors/connector-patreon/src/index.ts
  packages/connectors/connector-patreon/src/mock.ts
  packages/connectors/connector-patreon/src/types.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#6526 fix(experience): avoid carring identifer from reset password page to sign-in page
  packages/experience/src/pages/ResetPassword/index.tsx
Labels: bugfix, size/s

#6523 refactor(console): support entering name while creating a user
  .changeset/dry-candles-design.md
  packages/console/src/pages/Users/components/CreateForm/index.tsx
Labels: enhancement, size/s
