Repository logto-io/logto, pull requests merged in 2024-09, with the labels that each got.

#6524 refactor(core,toolkit): relocate customJwt local vm handler
  packages/core/src/libraries/jwt-customizer.ts
  packages/core/src/utils/custom-jwt/custom-jwt.ts
  packages/core/src/utils/custom-jwt/index.ts
  packages/core/src/utils/custom-jwt/local-vm-error.ts
  packages/core/src/utils/custom-jwt/local-vm.ts
  packages/toolkit/core-kit/src/custom-jwt/error-handling.ts
  packages/toolkit/core-kit/src/custom-jwt/index.ts
Labels: enhancement, size/s

#6509 chore(console): should use SKU to filter tenant dropdown and add display of dev/admin plan
  packages/console/src/components/SkuName/index.tsx
  packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx
  packages/console/src/types/subscriptions.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/index.ts
Labels: chore, size/s

#6537 chore(schemas): bump withtyped version
  .changeset/proud-baboons-hope.md
  packages/schemas/package.json
  pnpm-lock.yaml
Labels: chore, size/xs

#6529 feat: add GitLab connector
  .changeset/fast-adults-dream.md
  packages/connectors/connector-gitlab/README.md
  packages/connectors/connector-gitlab/logo.svg
  packages/connectors/connector-gitlab/package.json
  packages/connectors/connector-gitlab/src/constant.ts
  packages/connectors/connector-gitlab/src/index.test.ts
  packages/connectors/connector-gitlab/src/index.ts
  packages/connectors/connector-gitlab/src/mock.ts
  packages/connectors/connector-gitlab/src/types.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#6530 feat(tunnel): support cli deploy custom ui assets to cloud
  .changeset/modern-ghosts-sin.md
  packages/tunnel/package.json
  packages/tunnel/src/commands/deploy/index.ts
  packages/tunnel/src/commands/deploy/types.ts
  packages/tunnel/src/commands/deploy/utils.ts
  packages/tunnel/src/commands/tunnel/index.ts
  packages/tunnel/src/commands/tunnel/types.ts
  packages/tunnel/src/commands/tunnel/utils.test.ts
  packages/tunnel/src/commands/tunnel/utils.ts
  packages/tunnel/src/include.d/dom.d.ts
  packages/tunnel/src/index.ts
  packages/tunnel/src/utils.ts
  pnpm-lock.yaml
Labels: feature, size/l

#6539 refactor: flatten `UserSettings` component file structure
  packages/console/src/pages/UserDetails/UserSettings/PersonalAccessTokens/CreateTokenModal.tsx
  packages/console/src/pages/UserDetails/UserSettings/PersonalAccessTokens/EditTokenModal.tsx
  packages/console/src/pages/UserDetails/UserSettings/PersonalAccessTokens/index.module.scss
  packages/console/src/pages/UserDetails/UserSettings/PersonalAccessTokens/index.tsx
  packages/console/src/pages/UserDetails/UserSettings/UserSocialIdentities/index.module.scss
  packages/console/src/pages/UserDetails/UserSettings/UserSocialIdentities/index.tsx
  packages/console/src/pages/UserDetails/UserSettings/UserSsoIdentities/index.tsx
  packages/console/src/pages/UserDetails/UserSettings/index.tsx
Labels: enhancement, size/xs

#6538 fix(deps): update withtyped and cloud dependency version
  packages/cli/package.json
  packages/connectors/connector-logto-email/package.json
  packages/console/package.json
  packages/core/package.json
  packages/core/src/libraries/quota.ts
  packages/core/src/middleware/koa-quota-guard.ts
  packages/core/src/utils/subscription/types.ts
  packages/toolkit/connector-kit/package.json
  pnpm-lock.yaml
Labels: bugfix, size/s

#6532 feat(core): add denyAccess api context to customJwt script
  packages/core/src/libraries/jwt-customizer.ts
  packages/core/src/oidc/extra-token-claims.ts
  packages/core/src/routes/logto-config/jwt-customizer.ts
  packages/core/src/utils/custom-jwt/index.ts
  packages/integration-tests/src/__mocks__/jwt-customizer.ts
  packages/integration-tests/src/tests/api/logto-config.test.ts
  packages/schemas/src/types/logto-config/jwt-customizer.ts
Labels: feature, size/m

#6533 feat(console): add api context type declarations
  packages/console/scripts/custom-jwt-customizer-type-definition.ts
  packages/console/scripts/generate-jwt-customizer-type-definition.ts
  packages/console/src/pages/CustomizeJwtDetails/MainContent/ScriptSection/use-test-handler.ts
  packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/GuideCard/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/utils/config.tsx
  packages/console/src/pages/CustomizeJwtDetails/utils/type-definitions.ts
  packages/phrases/src/locales/ar/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/de/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/en/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/es/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/fr/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/it/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ja/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ko/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ru/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/jwt-claims.ts
Labels: feature, size/l

#6543 fix(core): add `hasPassword` field to user API response
  .changeset/polite-bats-learn.md
  packages/core/src/__mocks__/user.ts
  packages/core/src/routes/admin-user/basics.ts
  packages/core/src/routes/admin-user/search.test.ts
  packages/core/src/routes/admin-user/search.ts
  packages/core/src/routes/admin-user/social.ts
  packages/core/src/routes/role.user.ts
  packages/core/src/utils/user.ts
  packages/integration-tests/src/helpers/user.ts
  packages/integration-tests/src/tests/api/admin-user.test.ts
  packages/integration-tests/src/tests/api/organization/organization-user.test.ts
Labels: bugfix, size/m

#6541 feat(tunnel): support zip option in deploy command
  .changeset/modern-ghosts-sin.md
  packages/tunnel/src/commands/deploy/index.ts
  packages/tunnel/src/commands/deploy/types.ts
  packages/tunnel/src/commands/deploy/utils.ts
Labels: feature, size/m

#6547 release: @logto/tunnel:0.2.0
  .changeset/modern-ghosts-sin.md
  packages/tunnel/CHANGELOG.md
  packages/tunnel/package.json
Labels: size/s

#6534 feat: add support for nested attribute profile mapping
  .changeset/violet-beds-yawn.md
  packages/connectors/connector-oauth2/README.md
  packages/connectors/connector-oauth2/src/utils.test.ts
  packages/connectors/connector-oauth2/src/utils.ts
Labels: feature, size/m

#6544 feat(console): display user password information on user details page
  .changeset/brave-horses-knock.md
  packages/console/src/pages/UserDetails/UserSettings/UserPassword/index.module.scss
  packages/console/src/pages/UserDetails/UserSettings/UserPassword/index.tsx
  packages/console/src/pages/UserDetails/UserSettings/index.tsx
  packages/console/src/pages/UserDetails/components/ResetPasswordForm/index.tsx
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/pages/UserDetails/types.ts
  packages/phrases/src/locales/ar/translation/admin-console/user-details.ts
  packages/phrases/src/locales/de/translation/admin-console/user-details.ts
  packages/phrases/src/locales/en/translation/admin-console/general.ts
  packages/phrases/src/locales/en/translation/admin-console/user-details.ts
  packages/phrases/src/locales/es/translation/admin-console/user-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/user-details.ts
  packages/phrases/src/locales/it/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/user-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/user-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/user-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/user-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/user-details.ts
Labels: feature, size/l

#6548 style(console): adjust sample code editor height
  packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/jwt-claims.ts
Labels: size/xs

#6551 chore(console,phrases): update custom JWT phrases
  packages/console/src/pages/CustomizeJwt/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/utils/config.tsx
  packages/phrases/src/locales/en/errors/jwt-customizer.ts
  packages/phrases/src/locales/en/translation/admin-console/jwt-claims.ts
Labels: chore, size/s

#6553 feat(console,core): remove custom token claims api context dev guard
  .changeset/spicy-cameras-sleep.md
  packages/console/scripts/custom-jwt-customizer-type-definition.ts
  packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/utils/config.tsx
  packages/core/src/libraries/jwt-customizer.ts
  packages/core/src/oidc/extra-token-claims.ts
  packages/integration-tests/src/__mocks__/jwt-customizer.ts
  packages/integration-tests/src/tests/api/admin-user.personal-access-tokens.test.ts
  packages/integration-tests/src/tests/api/logto-config.test.ts
  packages/phrases/src/locales/en/translation/admin-console/jwt-claims.ts
  packages/schemas/src/types/logto-config/jwt-customizer.ts
Labels: feature, size/m

#6536 refactor: set `lang` attribute for html tag
  .changeset/quiet-penguins-join.md
  packages/console/src/App.tsx
  packages/demo-app/package.json
  packages/demo-app/src/App.tsx
  packages/experience/src/App.tsx
  packages/experience/src/Providers/AppBoundary/AppMeta.tsx
  pnpm-lock.yaml
Labels: enhancement, size/s

#6563 fix(core): fix custom UI not triggered bug
  packages/core/src/middleware/koa-spa-proxy.test.ts
  packages/core/src/middleware/koa-spa-proxy.ts
Labels: bugfix, size/s

#6562 fix: fix object comparison util method used in DB alteration CI
  .scripts/compare-database.js
Labels: bugfix, size/m

#6560 fix(experience): allow link social account on sign-in only mode
  .changeset/proud-books-itch.md
  packages/experience-legacy/src/containers/SocialLinkAccount/index.tsx
  packages/experience-legacy/src/hooks/use-social-register.ts
  packages/experience-legacy/src/pages/SocialSignInWebCallback/use-social-sign-in-listener.ts
  packages/experience/src/containers/SocialLinkAccount/index.tsx
  packages/experience/src/hooks/use-social-register.ts
  packages/experience/src/pages/SocialSignInWebCallback/use-social-sign-in-listener.ts
  packages/integration-tests/src/tests/experience/automatic-account-linking.test.ts
Labels: bugfix, size/l

#6559 feat(core): add koa oidc auth for profile API
  packages/core/src/middleware/koa-auth/index.test.ts
  packages/core/src/middleware/koa-auth/index.ts
  packages/core/src/middleware/koa-auth/koa-oidc-auth.test.ts
  packages/core/src/middleware/koa-auth/koa-oidc-auth.ts
  packages/core/src/middleware/koa-auth/types.ts
  packages/core/src/middleware/koa-auth/utils.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/profile/index.ts
  packages/core/src/routes/types.ts
  packages/core/src/utils/test-utils.ts
Labels: feature, size/l

#6567 feat(core): password checking api
  .changeset/yellow-yaks-bathe.md
  packages/core/src/routes-me/user.ts
  packages/core/src/routes/sign-in-experience/index.openapi.json
  packages/core/src/routes/sign-in-experience/index.ts
  packages/core/src/routes/swagger/utils/operation-id.ts
  packages/core/src/utils/password.ts
  packages/integration-tests/src/helpers/admin-tenant.ts
  packages/integration-tests/src/tests/api/me.test.ts
  packages/integration-tests/src/tests/api/sign-in-experience.test.ts
Labels: feature, size/l

#6565 refactor: update display, quota guard and usage report logic for enterprise users
  packages/console/package.json
  packages/console/src/components/ApplicationCreation/CreateForm/Footer/index.tsx
  packages/console/src/components/FeatureTag/index.tsx
  packages/console/src/components/PlanDescription/index.tsx
  packages/console/src/components/PlanUsage/PlanUsageCard/index.module.scss
  packages/console/src/components/PlanUsage/PlanUsageCard/index.tsx
  packages/console/src/components/PlanUsage/index.tsx
  packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx
  packages/console/src/consts/tenants.ts
  packages/console/src/pages/ApiResources/components/CreateForm/Footer.tsx
  packages/console/src/pages/EnterpriseSso/SsoCreationModal/index.tsx
  packages/console/src/pages/Organizations/CreateOrganizationModal/index.tsx
  packages/console/src/pages/TenantSettings/BillingHistory/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/SwitchPlanActionBar/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/index.tsx
  packages/console/src/utils/subscription.ts
  packages/core/package.json
  packages/core/src/libraries/quota.ts
  packages/core/src/utils/subscription/index.ts
  packages/phrases/src/locales/ar/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/index.ts
  packages/schemas/src/consts/subscriptions.ts
  pnpm-lock.yaml
Labels: enhancement, size/m

#6569 fix(console): fix log label typo
  packages/console/src/consts/logs.ts
Labels: bugfix, size/xs

#6572 fix(core): allow no password user to set password in console profile
  packages/core/src/routes-me/user.ts
Labels: bugfix, size/xs

#6570 refactor: use orgsLimit instead of orgsEnabled as org quota key
  packages/console/package.json
  packages/console/src/cloud/types/router.ts
  packages/console/src/components/PlanUsage/index.tsx
  packages/console/src/components/PlanUsage/utils.ts
  packages/console/src/consts/plan-quotas.ts
  packages/console/src/consts/quota-item-phrases.ts
  packages/console/src/consts/tenants.ts
  packages/console/src/pages/OrganizationTemplate/index.tsx
  packages/console/src/pages/Organizations/CreateOrganizationModal/index.tsx
  packages/console/src/pages/Organizations/index.tsx
  packages/console/src/utils/subscription.ts
  packages/core/package.json
  packages/core/src/routes/organization-role/index.ts
  packages/core/src/routes/organization-scope/index.ts
  packages/core/src/routes/organization/index.ts
  packages/core/src/utils/subscription/types.ts
  pnpm-lock.yaml
Labels: enhancement, size/m

#6575 fix(experience-legacy): add html attribute dir to better support RTL
  commitlint.config.ts
  packages/experience-legacy/src/Providers/AppBoundary/AppMeta.tsx
Labels: bugfix, size/xs

#6574 fix(core): avoid duplicate operationId
  packages/core/src/routes/experience/profile-routes.openapi.json
  packages/core/src/routes/experience/verification-routes/verification-code.openapi.json
  packages/core/src/routes/swagger/utils/general.ts
Labels: bugfix, size/s

#6578 fix: fix enterprise console issues
  packages/console/src/components/PlanUsage/index.tsx
  packages/console/src/components/SkuName/index.tsx
  packages/console/src/pages/Mfa/MfaForm/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/index.module.scss
  packages/console/src/pages/TenantSettings/Subscription/SwitchPlanActionBar/index.tsx
Labels: bugfix, size/s

#6566 feat(schemas): add verification record table
  packages/schemas/alterations/next-1725971571-add-verification-record.ts
  packages/schemas/src/foundations/jsonb-types/index.ts
  packages/schemas/src/foundations/jsonb-types/verification-records.ts
  packages/schemas/src/types/interactions.ts
  packages/schemas/src/types/log/interaction.ts
  packages/schemas/tables/verification_records.sql
Labels: feature, size/s

#6583 fix(experience-legacy): update text alignment for RTL support
  packages/experience-legacy/src/components/Button/MfaFactorButton.module.scss
  packages/experience-legacy/src/components/InputFields/InputField/NotchedBorder/index.module.scss
  packages/experience-legacy/src/containers/SocialLinkAccount/index.module.scss
Labels: bugfix, size/xs

#6580 refactor: refactor SkuName component to make isEnterprisePlan as input
  packages/console/src/components/ApplicationCreation/CreateForm/Footer/index.tsx
  packages/console/src/components/CreateConnectorForm/Footer/index.tsx
  packages/console/src/components/MauExceededModal/index.tsx
  packages/console/src/components/SkuName/index.tsx
  packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx
  packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx
  packages/console/src/pages/ApiResources/components/CreateForm/Footer.tsx
  packages/console/src/pages/Applications/components/ProtectedAppForm/index.tsx
  packages/console/src/pages/RoleDetails/RolePermissions/components/AssignPermissionsModal/index.tsx
  packages/console/src/pages/Roles/components/CreateRoleForm/Footer.tsx
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/index.tsx
  packages/console/src/pages/Webhooks/CreateFormModal/CreateForm.tsx
Labels: enhancement, size/s

#6579 test: add integration test for no password user setting password
  packages/integration-tests/src/api/connector.ts
  packages/integration-tests/src/api/sign-in-experience.ts
  packages/integration-tests/src/client/experience/index.ts
  packages/integration-tests/src/client/index.ts
  packages/integration-tests/src/helpers/admin-tenant.ts
  packages/integration-tests/src/helpers/client.ts
  packages/integration-tests/src/helpers/connector.ts
  packages/integration-tests/src/helpers/sign-in-experience.ts
  packages/integration-tests/src/tests/api/me.test.ts
Labels: testing, size/l

#6581 test: add ui integration test for lang and dir html attributes in experience
  packages/integration-tests/src/helpers/sign-in-experience.ts
  packages/integration-tests/src/tests/experience/bootstrap.test.ts
Labels: testing, size/s

#6584 fix(experience-legacy): flip arrow icons on rtl
  packages/experience-legacy/src/components/Button/MfaFactorButton.tsx
  packages/experience-legacy/src/components/FlipOnRtl/index.module.scss
  packages/experience-legacy/src/components/FlipOnRtl/index.tsx
  packages/experience-legacy/src/components/NavBar/index.tsx
Labels: bugfix, size/s

#6576 fix(core): add sso only email guard
  .changeset/witty-rivers-laugh.md
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.ts
  packages/core/src/routes/experience/classes/profile.ts
  packages/core/src/routes/experience/profile-routes.openapi.json
  packages/integration-tests/src/tests/api/experience-api/register-interaction/enterprise-sso.test.ts
Labels: bugfix, size/m

#6594 feat(console): au region
  packages/connectors/connector-logto-email/package.json
  packages/console/package.json
  packages/console/src/components/CreateTenantModal/index.tsx
  packages/console/src/components/Region/assets/au.svg
  packages/console/src/components/Region/assets/eu.svg
  packages/console/src/components/Region/assets/us.svg
  packages/console/src/components/Region/index.module.scss
  packages/console/src/components/Region/index.tsx
  packages/console/src/utils/form.ts
  packages/core/package.json
  pnpm-lock.yaml
Labels: feature, size/l

#6602 style(console): hide button title when loading
  packages/console/src/ds-components/Button/index.tsx
Labels: size/xs

#6564 feat(core): add feature flag switch for experience app
  packages/core/src/middleware/koa-spa-proxy.ts
  packages/core/src/middleware/utils/experience-proxy.test.ts
  packages/core/src/middleware/utils/experience-proxy.ts
  packages/core/src/utils/feature-flag.test.ts
  packages/core/src/utils/feature-flag.ts
  packages/core/src/utils/test-utils.ts
  packages/schemas/src/types/system.ts
Labels: feature, size/l

#6599 fix(experience): add missing button loading state
  packages/experience-legacy/src/containers/SocialLinkAccount/index.tsx
  packages/experience-legacy/src/hooks/use-webauthn-operation.ts
  packages/experience/src/containers/SocialLinkAccount/index.tsx
  packages/experience/src/hooks/use-webauthn-operation.ts
Labels: bugfix, size/s

#6606 refactor(console): fix region-related styles
  packages/console/src/components/Region/index.tsx
  packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/index.module.scss
  packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/TenantRegion/index.module.scss
  packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/TenantRegion/index.tsx
Labels: enhancement, size/s

#6610 refactor(console): fix flag styles
  packages/console/src/components/Region/assets/au.svg
  packages/console/src/components/Region/assets/eu.svg
  packages/console/src/components/Region/assets/us.svg
  packages/console/src/components/Region/index.tsx
  packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx
Labels: enhancement, size/l

#6611 fix(console): fix PlanUsage not displayed for enterprise plan w/o subscription
  packages/console/src/components/BillInfo/index.tsx
  packages/console/src/components/PlanUsage/index.tsx
Labels: bugfix, size/s

#6616 feat(console): hide the entrance of http email connector
  packages/console/src/components/CreateConnectorForm/index.tsx
Labels: feature, size/xs

#6592 feat(connector): add http email connector
  packages/connectors/connector-http-email/README.md
  packages/connectors/connector-http-email/logo-dark.svg
  packages/connectors/connector-http-email/logo.svg
  packages/connectors/connector-http-email/package.json
  packages/connectors/connector-http-email/src/constant.ts
  packages/connectors/connector-http-email/src/index.test.ts
  packages/connectors/connector-http-email/src/index.ts
  packages/connectors/connector-http-email/src/mock.ts
  packages/connectors/connector-http-email/src/types.ts
  pnpm-lock.yaml
Labels: feature, size/l

#6603 docs(connector): add readme of http email connector
  packages/connectors/connector-http-email/README.md
Labels: size/s

#6617 fix(connector): fix http email connector id
  packages/connectors/connector-http-email/src/constant.ts
Labels: bugfix, size/xs

#6621 fix(connector): add tooltip of authorization header field
  packages/connectors/connector-http-email/src/constant.ts
Labels: bugfix, size/xs

#6622 fix(connector): replace smtp logo
  packages/connectors/connector-smtp/logo-dark.svg
  packages/connectors/connector-smtp/logo.svg
Labels: bugfix, size/s

#6626 fix(console): fix empty string update of connector config form
  packages/console/src/hooks/use-connector-form-config-parser.tsx
  packages/console/src/pages/ConnectorDetails/ConnectorContent/index.tsx
  packages/console/src/utils/connector-form.ts
Labels: bugfix, size/s

#6625 fix(connector): add type list in readme
  packages/connectors/connector-http-email/README.md
Labels: bugfix, size/xs

#6571 feat(core): update password in profile
  packages/core/src/libraries/verification.ts
  packages/core/src/queries/verification-records.ts
  packages/core/src/routes/experience/classes/libraries/sentinel-guard.ts
  packages/core/src/routes/experience/classes/utils.ts
  packages/core/src/routes/experience/classes/verifications/password-verification.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/profile/index.openapi.json
  packages/core/src/routes/profile/index.ts
  packages/core/src/routes/swagger/consts.ts
  packages/core/src/routes/swagger/utils/documents.ts
  packages/core/src/routes/swagger/utils/operation-id.ts
  packages/core/src/routes/types.ts
  packages/core/src/routes/verification/index.openapi.json
  packages/core/src/routes/verification/index.ts
  packages/core/src/routes/well-known/well-known.openapi.json
  packages/core/src/routes/well-known/well-known.openapi.ts
  packages/core/src/tenants/Queries.ts
  packages/integration-tests/src/api/profile.ts
  packages/integration-tests/src/api/verification-record.ts
  packages/integration-tests/src/helpers/admin-tenant.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/password.test.ts
  packages/integration-tests/src/tests/api/experience-api/verifications/password-verification.test.ts
  packages/integration-tests/src/tests/api/profile/index.test.ts
  packages/integration-tests/src/tests/api/well-known.openapi.test.ts
  packages/phrases/src/locales/en/errors/index.ts
  packages/phrases/src/locales/en/errors/verification-record.ts
  packages/schemas/src/foundations/jsonb-types/sign-in-experience.ts
  packages/schemas/src/types/interactions.ts
Labels: feature, size/xl

#6627 Revert "fix(console): fix empty string update of connector config for…
  packages/console/src/hooks/use-connector-form-config-parser.tsx
  packages/console/src/pages/ConnectorDetails/ConnectorContent/index.tsx
  packages/console/src/utils/connector-form.ts
Labels: size/s

#6620 refactor(console): update pricing console page
  packages/console/package.json
  packages/console/src/components/PlanUsage/PlanUsageCard/index.module.scss
  packages/console/src/components/PlanUsage/PlanUsageCard/index.tsx
  packages/console/src/components/PlanUsage/index.tsx
  packages/console/src/components/PlanUsage/utils.ts
  packages/console/src/contexts/SubscriptionDataProvider/index.tsx
  packages/console/src/contexts/SubscriptionDataProvider/types.ts
  packages/console/src/contexts/SubscriptionDataProvider/use-new-subscription-data.ts
  packages/phrases/src/locales/ar/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ar/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/usage.ts
  pnpm-lock.yaml
Labels: enhancement, size/l

#6628 fix(console): fix console resource usage tooltip
  packages/console/src/components/PlanUsage/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/subscription/usage.ts
Labels: bugfix, size/s

#6629 fix(console): fix console resource usage tooltip
  packages/console/src/components/PlanUsage/index.tsx
Labels: bugfix, size/s

#6591 refactor(console): remove subscription plans
  packages/console/src/cloud/types/router.ts
  packages/console/src/consts/tenants.ts
  packages/console/src/contexts/SubscriptionDataProvider/index.tsx
  packages/console/src/contexts/SubscriptionDataProvider/types.ts
  packages/console/src/contexts/SubscriptionDataProvider/use-subscription-data.ts
  packages/console/src/hooks/use-subscription-plans.ts
  packages/console/src/pages/CheckoutSuccessCallback/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/MauLimitExceededNotification/index.tsx
  packages/console/src/types/subscriptions.ts
  packages/console/src/utils/subscription.ts
Labels: enhancement, size/m

#6630 fix(core,tunnel,phrases): support range requests when hosting custom ui assets
  .changeset/tasty-kings-fetch.md
  .changeset/tricky-mice-pay.md
  packages/core/src/middleware/koa-serve-custom-ui-assets.test.ts
  packages/core/src/middleware/koa-serve-custom-ui-assets.ts
  packages/core/src/utils/storage/azure-storage.ts
  packages/phrases/src/locales/en/errors/request.ts
  packages/toolkit/core-kit/src/utils/url.test.ts
  packages/toolkit/core-kit/src/utils/url.ts
  packages/tunnel/src/commands/tunnel/utils.test.ts
  packages/tunnel/src/commands/tunnel/utils.ts
Labels: bugfix, size/l

#6634 chore(core): update code comments in security header middleware
  packages/core/src/middleware/koa-security-headers.ts
Labels: chore, size/s

#6632 chore: split and add dedicated changeset for tunnel
  .changeset/tasty-kings-fetch.md
  .changeset/violet-ligers-carry.md
Labels: chore, size/s

#6328 refactor(cli): keep alteration scripts folder writable by gid 0
  Dockerfile
  packages/cli/src/commands/database/alteration/utils.ts
Labels: enhancement, size/s, stale

#6636 feat(core): add update name and avatar endpoint
  packages/core/src/routes/profile/index.openapi.json
  packages/core/src/routes/profile/index.ts
  packages/integration-tests/src/api/api.ts
  packages/integration-tests/src/api/profile.ts
  packages/integration-tests/src/api/verification-record.ts
  packages/integration-tests/src/helpers/admin-tenant.ts
  packages/integration-tests/src/helpers/profile.ts
  packages/integration-tests/src/tests/api/profile/index.test.ts
Labels: feature, size/m

#6640 feat(core): update username
  packages/core/src/routes/profile/index.openapi.json
  packages/core/src/routes/profile/index.ts
  packages/integration-tests/src/api/profile.ts
  packages/integration-tests/src/tests/api/profile/index.test.ts
Labels: feature, size/s
