Repository logto-io/logto, pull requests merged in 2024-05, with the labels that each got.

#5813 refactor: implement request id
  .changeset/green-phones-visit.md
  .changeset/grumpy-cougars-perform.md
  packages/app-insights/src/node.ts
  packages/core/src/app/init.ts
  packages/core/src/caches/index.ts
  packages/core/src/caches/utils.ts
  packages/core/src/caches/well-known.ts
  packages/core/src/env-set/check-alteration-state.ts
  packages/core/src/env-set/index.ts
  packages/core/src/event-listeners/index.ts
  packages/core/src/index.ts
  packages/core/src/libraries/hook/index.test.ts
  packages/core/src/libraries/hook/index.ts
  packages/core/src/libraries/jwt-customizer.ts
  packages/core/src/libraries/logto-config.ts
  packages/core/src/main.ts
  packages/core/src/middleware/koa-auth/index.ts
  packages/core/src/middleware/koa-error-handler.ts
  packages/core/src/middleware/koa-guard.ts
  packages/core/src/middleware/koa-oidc-error-handler.ts
  packages/core/src/routes/interaction/actions/helpers.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/core/src/routes/interaction/middleware/koa-interaction-hooks.ts
  packages/core/src/routes/logto-config/index.ts
  packages/core/src/routes/logto-config/jwt-customizer.test.ts
  packages/core/src/routes/logto-config/jwt-customizer.ts
  packages/core/src/routes/swagger/index.ts
  packages/core/src/routes/swagger/utils/general.ts
  packages/core/src/routes/user-assets.ts
  packages/core/src/tenants/SystemContext.ts
  packages/core/src/tenants/Tenant.test.ts
  packages/core/src/tenants/Tenant.ts
  packages/core/src/tenants/index.ts
  packages/core/src/utils/cloudflare/utils.ts
  packages/core/src/utils/connectors/index.ts
  packages/core/src/utils/console.test.ts
  packages/core/src/utils/console.ts
  packages/core/src/utils/request.ts
  packages/core/src/utils/tenant.ts
  packages/integration-tests/src/tests/api/health-check.test.ts
  packages/integration-tests/src/tests/api/well-known.test.ts
  packages/shared/src/node/env/ConsoleLog.test.ts
  packages/shared/src/node/env/ConsoleLog.ts
Labels: enhancement, size/xl

#5814 refactor: remove app insights domains from security headers
  packages/core/src/middleware/koa-security-headers.ts
Labels: enhancement, size/s

#5797 feat(connector): add hugging face connector
  .changeset/nasty-dots-lie.md
  .vscode/settings.json
  packages/connectors/connector-huggingface/README.md
  packages/connectors/connector-huggingface/logo.svg
  packages/connectors/connector-huggingface/package.json
  packages/connectors/connector-huggingface/src/constant.ts
  packages/connectors/connector-huggingface/src/index.test.ts
  packages/connectors/connector-huggingface/src/index.ts
  packages/connectors/connector-huggingface/src/types.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#5823 fix(core): invitee email check should be case insensitive
  .changeset/popular-chicken-share.md
  packages/core/src/libraries/organization-invitation.ts
Labels: bugfix, size/xs

#5824 fix(console): hide org resource scopes tab from 3rd-party app modal
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/ApplicationScopesAssignmentModal/index.tsx
Labels: bugfix, size/s

#5827 chore(deps): upgrade withtyped packages
  packages/cli/package.json
  packages/console/package.json
  packages/core/package.json
  packages/schemas/package.json
  packages/toolkit/connector-kit/package.json
  pnpm-lock.yaml
Labels: chore, size/s

#5826 refactor(core): optimize init
  packages/core/src/main.ts
  packages/core/src/tenants/index.ts
Labels: enhancement, size/xs

#5829 chore(deps): upgrade withtyped packages
  packages/cli/package.json
  packages/console/package.json
  packages/core/package.json
  packages/schemas/package.json
  packages/toolkit/connector-kit/package.json
  pnpm-lock.yaml
Labels: chore, size/s

#5825 refactor(console): make invitee email breakable in invitation list
  packages/console/src/pages/TenantSettings/TenantMembers/Invitations/index.tsx
Labels: enhancement, size/xs

#5808 feat(core,schemas): add org resource scopes to consent get
  packages/core/src/libraries/user.ts
  packages/core/src/oidc/init.ts
  packages/core/src/oidc/resource.ts
  packages/core/src/routes/interaction/consent.ts
  packages/integration-tests/src/tests/api/interaction/third-party-sign-in/happy-path.test.ts
  packages/schemas/src/types/consent.ts
Labels: feature, size/l

#5831 feat(experience): display org resource scopes on consent page
  packages/experience/src/pages/Consent/OrganizationSelector/index.module.scss
  packages/experience/src/pages/Consent/OrganizationSelector/index.tsx
  packages/experience/src/pages/Consent/ScopeGroup/index.module.scss
  packages/experience/src/pages/Consent/ScopeGroup/index.tsx
  packages/experience/src/pages/Consent/ScopesListCard/index.tsx
  packages/experience/src/pages/Consent/index.module.scss
  packages/experience/src/pages/Consent/index.tsx
  packages/phrases-experience/src/locales/de/description.ts
  packages/phrases-experience/src/locales/en/description.ts
  packages/phrases-experience/src/locales/es/description.ts
  packages/phrases-experience/src/locales/fr/description.ts
  packages/phrases-experience/src/locales/it/description.ts
  packages/phrases-experience/src/locales/ja/description.ts
  packages/phrases-experience/src/locales/ko/description.ts
  packages/phrases-experience/src/locales/pl-pl/description.ts
  packages/phrases-experience/src/locales/pt-br/description.ts
  packages/phrases-experience/src/locales/pt-pt/description.ts
  packages/phrases-experience/src/locales/ru/description.ts
  packages/phrases-experience/src/locales/tr-tr/description.ts
  packages/phrases-experience/src/locales/zh-cn/description.ts
  packages/phrases-experience/src/locales/zh-hk/description.ts
  packages/phrases-experience/src/locales/zh-tw/description.ts
Labels: feature, size/l

#5783 feat: init management api hook middleware function
  .changeset/fluffy-steaks-flow.md
  .changeset/metal-lions-swim.md
  packages/console/src/components/BasicWebhookForm/index.tsx
  packages/console/src/consts/webhooks.ts
  packages/console/src/pages/WebhookDetails/WebhookLogs/index.tsx
  packages/console/src/pages/Webhooks/index.tsx
  packages/core/package.json
  packages/core/src/__mocks__/hook.ts
  packages/core/src/libraries/hook/context-manager.ts
  packages/core/src/libraries/hook/index.test.ts
  packages/core/src/libraries/hook/index.ts
  packages/core/src/libraries/hook/types.ts
  packages/core/src/libraries/hook/utils.test.ts
  packages/core/src/libraries/hook/utils.ts
  packages/core/src/middleware/koa-management-api-hooks.test.ts
  packages/core/src/middleware/koa-management-api-hooks.ts
  packages/core/src/routes/hook.test.ts
  packages/core/src/routes/hook.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/interaction/middleware/koa-interaction-hooks.ts
  packages/core/src/routes/types.ts
  packages/integration-tests/src/tests/api/hook/hook.stats.test.ts
  packages/integration-tests/src/tests/api/hook/hook.test.ts
  packages/integration-tests/src/tests/api/hook/hook.testing.test.ts
  packages/integration-tests/src/tests/api/hook/hook.trigger.test.ts
  packages/schemas/src/foundations/jsonb-types/hooks.ts
  packages/schemas/src/types/hook.ts
  packages/shared/src/utils/index.ts
  packages/shared/src/utils/normalize-error.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#5832 feat(console): add webflow integration guide
  packages/console/src/assets/docs/guides/index.ts
  packages/console/src/assets/docs/guides/spa-webflow/README.mdx
  packages/console/src/assets/docs/guides/spa-webflow/config.json
  packages/console/src/assets/docs/guides/spa-webflow/index.ts
  packages/console/src/assets/docs/guides/spa-webflow/logo.svg
Labels: feature, size/m

#5833 refactor(console): update conversion report timing
  packages/console/src/components/Conversion/index.tsx
  packages/console/src/components/Conversion/use-retry.ts
  packages/console/src/components/Conversion/utils.ts
  packages/console/src/consts/env.ts
  packages/console/src/onboarding/index.tsx
  packages/console/src/onboarding/pages/SignInExperience/index.tsx
Labels: enhancement, size/m

#5737 feat(connector): can access all user email even if no public email is set
  .changeset/pretty-mirrors-peel.md
  packages/connectors/connector-github/package.json
  packages/connectors/connector-github/src/constant.ts
  packages/connectors/connector-github/src/index.test.ts
  packages/connectors/connector-github/src/index.ts
  packages/connectors/connector-github/src/types.ts
  pnpm-lock.yaml
Labels: feature, size/m

#5687 fix(console): make profile a tenant independent page
  packages/console/src/cloud/AppRoutes.tsx
  packages/console/src/components/Topbar/UserInfo/index.module.scss
  packages/console/src/components/Topbar/UserInfo/index.tsx
  packages/console/src/components/Topbar/index.tsx
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/containers/ConsoleRoutes/index.tsx
  packages/console/src/contexts/TenantsProvider.tsx
  packages/console/src/ds-components/Uploader/FileUploader/index.tsx
  packages/console/src/ds-components/Uploader/ImageUploaderField/index.tsx
  packages/console/src/hooks/use-console-routes/index.tsx
  packages/console/src/hooks/use-console-routes/routes/profile.tsx
  packages/console/src/hooks/use-user-assets-service.ts
  packages/console/src/pages/Profile/containers/BasicUserInfoUpdateModal/index.tsx
  packages/console/src/pages/Profile/index.module.scss
  packages/console/src/pages/Profile/index.tsx
  packages/core/src/routes-me/init.ts
  packages/core/src/routes-me/user-assets.ts
Labels: bugfix, size/l

#5839 fix(console): focus on org socpes tab on app scopes modal reopened
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/PermissionsCard/ApplicationScopesAssignmentModal/index.tsx
Labels: bugfix, size/xs

#5838 fix(console): fix the link social feature on logto cloud
  packages/console/src/pages/Profile/components/LinkAccountSection/index.tsx
Labels: bugfix, size/xs

#5840 fix(experience): hide scope list if no user scopes and resource scopes
  packages/experience/src/pages/Consent/ScopesListCard/index.tsx
Labels: bugfix, size/xs

#5841 refactor(console): refactor some console global routes
  packages/console/src/cloud/AppRoutes.tsx
  packages/console/src/containers/ConsoleRoutes/index.tsx
  packages/console/src/contexts/TenantsProvider.tsx
Labels: enhancement, size/s

#5842 fix(console): move handle social route to global anonymous route enum
  packages/console/src/cloud/AppRoutes.tsx
  packages/console/src/containers/ConsoleRoutes/index.tsx
  packages/console/src/contexts/TenantsProvider.tsx
Labels: bugfix, size/xs

#5846 refactor(console, phrases): update resource scopes assignment form title
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/PermissionsCard/ApplicationScopesAssignmentModal/use-resource-scopes-assignment.ts
  packages/phrases/src/locales/de/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/es/translation/admin-console/application-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/it/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/application-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts
Labels: enhancement, size/s

#5794 feat(core,console): enable custom JWT for OSS and can run script in local vm
  .changeset/itchy-eels-remain.md
  packages/console/src/containers/ConsoleContent/Sidebar/hook.tsx
  packages/console/src/hooks/use-console-routes/index.tsx
  packages/core/src/libraries/jwt-customizer.ts
  packages/core/src/oidc/extra-token-claims.ts
  packages/core/src/routes/logto-config/jwt-customizer.test.ts
  packages/core/src/routes/logto-config/jwt-customizer.ts
  packages/core/src/routes/logto-config/logto-config.openapi.json
  packages/core/src/tenants/Libraries.ts
  packages/core/src/utils/custom-jwt/index.ts
  packages/core/src/utils/custom-jwt/local-vm-error.ts
  packages/integration-tests/src/__mocks__/jwt-customizer.ts
  packages/integration-tests/src/api/logto-config.ts
  packages/integration-tests/src/tests/api/application/application.roles.test.ts
  packages/integration-tests/src/tests/api/logto-config.test.ts
  packages/integration-tests/src/tests/api/oidc/get-access-token.test.ts
  packages/schemas/src/types/logto-config/jwt-customizer.ts
  packages/toolkit/core-kit/package.json
  packages/toolkit/core-kit/src/custom-jwt/error-handling.ts
  packages/toolkit/core-kit/src/custom-jwt/index.ts
  packages/toolkit/core-kit/src/custom-jwt/script-execution.ts
  pnpm-lock.yaml
Labels: feature, size/l

#5719 chore: add changeset for org api resource
  .changeset/thirty-cameras-explain.md
Labels: chore, size/s

#5845 fix(core): filter scopes for 3rd-party app
  packages/core/src/oidc/resource.ts
  packages/core/src/routes/interaction/consent/index.ts
  packages/core/src/routes/interaction/consent/utils.ts
  packages/integration-tests/src/tests/api/interaction/third-party-sign-in/happy-path.test.ts
Labels: bugfix, size/m

#5851 chore: fix pnpm-lock
  pnpm-lock.yaml
Labels: chore, size/xs

#5853 ci(connector): build connectors before publish
  .scripts/publish.js
Labels: size/xs

#5743 chore(core,schemas): remove feature guard of organization api resource
  packages/core/src/oidc/extra-token-claims.ts
  packages/core/src/oidc/grants/refresh-token.ts
  packages/core/src/oidc/resource.ts
  packages/core/src/routes/applications/application-user-consent-scope.ts
  packages/core/src/routes/interaction/consent/index.ts
  packages/core/src/routes/interaction/consent/utils.ts
  packages/core/src/routes/organization/roles.ts
  packages/schemas/src/types/organization.ts
Labels: chore, size/m

#5854 chore(console): update jwt claims status in plan comparison table
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/index.tsx
Labels: chore, size/xs

#5828 feat(schemas): define data hook events
  packages/core/src/middleware/koa-management-api-hooks.test.ts
  packages/core/src/middleware/koa-management-api-hooks.ts
  packages/core/src/utils/test-utils.ts
  packages/integration-tests/package.json
  packages/integration-tests/src/tests/api/hook/WebhookMockServer.ts
  packages/integration-tests/src/tests/api/hook/hook.trigger.data.test.ts
  packages/integration-tests/src/tests/api/hook/hook.trigger.interaction.test.ts
  packages/integration-tests/src/tests/api/hook/test-cases.ts
  packages/schemas/src/foundations/jsonb-types/hooks.ts
  packages/schemas/src/types/hook.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#5844 feat(console): add wordpress integration guide
  packages/console/src/assets/docs/guides/index.ts
  packages/console/src/assets/docs/guides/web-wordpress/README.mdx
  packages/console/src/assets/docs/guides/web-wordpress/config.json
  packages/console/src/assets/docs/guides/web-wordpress/index.ts
  packages/console/src/assets/docs/guides/web-wordpress/logo.svg
Labels: feature, size/s

#5848 ci: use default runner
  .github/workflows/alteration-compatibility-integration-test.yml
  .github/workflows/integration-test.yml
  .github/workflows/main.yml
Labels: size/xs

#5834 refactor(core, schemas): update interaction webhook middleware using contextManager
  packages/core/src/libraries/hook/context-manager.ts
  packages/core/src/libraries/hook/index.test.ts
  packages/core/src/libraries/hook/index.ts
  packages/core/src/libraries/hook/type.ts
  packages/core/src/libraries/hook/types.ts
  packages/core/src/libraries/hook/utils.ts
  packages/core/src/middleware/koa-management-api-hooks.test.ts
  packages/core/src/middleware/koa-management-api-hooks.ts
  packages/core/src/routes/interaction/middleware/koa-interaction-hooks.ts
  packages/integration-tests/src/tests/api/hook/hook.trigger.data.test.ts
  packages/schemas/src/types/hook.ts
Labels: enhancement, feature, size/l

#5855 chore: build oauth2 connector on prepack
  .github/workflows/main.yml
  .github/workflows/upload-annotations.yml
  .scripts/publish.js
  packages/connectors/connector-oauth2/package.json
  packages/connectors/templates/sync-preset.js
Labels: chore, size/s

#5852 chore(core): add custom domain host to app insights
  packages/core/src/utils/request.ts
  packages/core/src/utils/test-utils.ts
Labels: chore, size/s

#5861 fix(core): add devFeature guard for DataHooks
  packages/core/src/middleware/koa-management-api-hooks.ts
  packages/core/src/routes/hook.ts
  packages/schemas/src/foundations/jsonb-types/hooks.ts
Labels: bugfix, size/s

#5858 refactor(core): update first admin user preconditions
  packages/core/src/routes/interaction/actions/submit-interaction.ts
Labels: enhancement, size/s

#5859 fix(core): fix consent scopes filter rule for non-3rd-party app
  packages/core/src/routes/interaction/consent/utils.ts
  packages/integration-tests/src/tests/api/interaction/consent/happy-path.test.ts
Labels: bugfix, size/s

#5863 refactor(console): do not parameterize guide id
  packages/console/src/utils/route.ts
Labels: enhancement, size/xs

#5864 chore(phrases): update organization permission column name
  packages/integration-tests/src/ui-helpers/expect-organizations.ts
  packages/phrases/src/locales/de/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/en/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/es/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/fr/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/it/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/ja/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/ko/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/ru/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/organization-template.ts
Labels: chore, size/s

#5857 fix(core): should sign out user after deletion or suspension
  .changeset/green-cougars-behave.md
  packages/core/src/libraries/user.ts
  packages/core/src/routes/admin-user/basics.test.ts
  packages/core/src/routes/admin-user/basics.ts
  packages/integration-tests/src/tests/api/admin-user.test.ts
Labels: bugfix, size/s

#5860 chore(console): update sdk doc reference links
  packages/console/src/assets/docs/guides/m2m-general/index.ts
  packages/console/src/assets/docs/guides/native-android/index.ts
  packages/console/src/assets/docs/guides/native-expo/index.ts
  packages/console/src/assets/docs/guides/spa-angular/index.ts
  packages/console/src/assets/docs/guides/spa-react/index.ts
  packages/console/src/assets/docs/guides/spa-vanilla/index.ts
  packages/console/src/assets/docs/guides/spa-vue/index.ts
  packages/console/src/assets/docs/guides/web-dotnet-core-blazor-server/README.mdx
  packages/console/src/assets/docs/guides/web-dotnet-core-blazor-server/index.ts
  packages/console/src/assets/docs/guides/web-dotnet-core-blazor-wasm/README.mdx
  packages/console/src/assets/docs/guides/web-dotnet-core-blazor-wasm/index.ts
  packages/console/src/assets/docs/guides/web-dotnet-core-mvc/README.mdx
  packages/console/src/assets/docs/guides/web-dotnet-core-mvc/index.ts
  packages/console/src/assets/docs/guides/web-dotnet-core/README.mdx
  packages/console/src/assets/docs/guides/web-express/index.ts
  packages/console/src/assets/docs/guides/web-go/index.ts
  packages/console/src/assets/docs/guides/web-next-app-router/index.ts
  packages/console/src/assets/docs/guides/web-next/index.ts
  packages/console/src/assets/docs/guides/web-nuxt/index.ts
  packages/console/src/assets/docs/guides/web-php/README.mdx
  packages/console/src/assets/docs/guides/web-php/index.ts
  packages/console/src/assets/docs/guides/web-python/README.mdx
  packages/console/src/assets/docs/guides/web-python/index.ts
  packages/console/src/assets/docs/guides/web-sveltekit/index.ts
Labels: chore, size/s

#5837 feat(core): trigger user create DataHook event on user registration
  packages/core/src/libraries/hook/context-manager.ts
  packages/core/src/routes/interaction/actions/helpers.ts
  packages/core/src/routes/interaction/actions/submit-interaction.mfa.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/core/src/routes/interaction/middleware/koa-interaction-hooks.ts
  packages/core/src/routes/interaction/single-sign-on.ts
  packages/core/src/routes/interaction/utils/single-sign-on.test.ts
  packages/core/src/routes/interaction/utils/single-sign-on.ts
  packages/integration-tests/src/helpers/connector.ts
  packages/integration-tests/src/helpers/hook.ts
  packages/integration-tests/src/helpers/interactions.ts
  packages/integration-tests/src/tests/api/hook/WebhookMockServer.ts
  packages/integration-tests/src/tests/api/hook/hook.trigger.data.test.ts
  packages/integration-tests/src/tests/api/hook/hook.trigger.interaction.test.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier/happy-path.test.ts
Labels: feature, size/xl

#5867 ci: remove corepack
  .github/workflows/main.yml
Labels: size/xs

#5866 refactor(console): report first app creation conversion
  packages/console/src/components/Conversion/utils.ts
  packages/console/src/onboarding/pages/SignInExperience/index.tsx
  packages/console/src/pages/Applications/components/CreateForm/index.tsx
Labels: enhancement, size/s

#5856 feat(console, phrases): update the supported webhook events
  .changeset/curvy-boxes-hide.md
  packages/console/src/components/BasicWebhookForm/index.tsx
  packages/console/src/consts/env.ts
  packages/console/src/consts/webhooks.ts
  packages/console/src/ds-components/Checkbox/CategorizedCheckboxGroup/index.module.scss
  packages/console/src/ds-components/Checkbox/CategorizedCheckboxGroup/index.tsx
  packages/console/src/ds-components/Checkbox/CheckboxGroup/index.tsx
  packages/console/src/pages/AuditLogDetails/index.tsx
  packages/console/src/pages/WebhookDetails/WebhookLogs/index.tsx
  packages/console/src/pages/WebhookDetails/utils.ts
  packages/console/src/pages/Webhooks/index.tsx
  packages/integration-tests/src/tests/api/hook/hook.trigger.interaction.test.ts
  packages/integration-tests/src/tests/console/webhooks/helpers.ts
  packages/integration-tests/src/tests/console/webhooks/index.test.ts
  packages/phrases/src/locales/de/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/en/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/es/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/fr/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/it/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/ja/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/ko/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/ru/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/webhooks.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/webhooks.ts
  packages/schemas/src/foundations/jsonb-types/hooks.ts
Labels: feature, size/xl

#5869 fix(console): update the svelte integration guide
  packages/console/src/assets/docs/guides/web-sveltekit/README.mdx
Labels: bugfix, size/s

#5871 style(console): update webhook list page styles
  packages/console/src/pages/Webhooks/index.tsx
Labels: size/xs

#5876 refactor(core,schemas,test): rename DataHook data update event name
  packages/core/src/routes/interaction/actions/submit-interaction.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/integration-tests/src/tests/api/hook/hook.trigger.interaction.test.ts
  packages/integration-tests/src/tests/api/hook/test-cases.ts
  packages/integration-tests/src/tests/console/webhooks/helpers.ts
  packages/schemas/alterations/next-1715829731-rename-data-hook-schema-update-event.ts
  packages/schemas/src/foundations/jsonb-types/hooks.ts
Labels: enhancement, size/m

#5877 chore: update README.md
  README.md
Labels: chore, size/xs

#5875 chore(deps): upgrade caniuse-lite
  pnpm-lock.yaml
Labels: chore, size/xs

#5873 feat(console): add next auth guide
  packages/console/src/assets/docs/guides/index.ts
  packages/console/src/assets/docs/guides/web-next-auth/README.mdx
  packages/console/src/assets/docs/guides/web-next-auth/config.json
  packages/console/src/assets/docs/guides/web-next-auth/index.ts
  packages/console/src/assets/docs/guides/web-next-auth/logo.svg
Labels: feature, size/m

#5878 refactor(core,schemas): move webhook event payload type definition to schemas
  packages/core/src/libraries/hook/context-manager.ts
  packages/core/src/libraries/hook/index.ts
  packages/core/src/libraries/hook/type.ts
  packages/core/src/libraries/hook/utils.ts
  packages/schemas/src/types/hook.ts
Labels: enhancement, size/m

#5880 feat(core): add suctom scopes.updated hook events
  packages/core/src/libraries/hook/context-manager.ts
  packages/core/src/libraries/hook/index.test.ts
  packages/core/src/libraries/hook/utils.ts
  packages/core/src/middleware/koa-management-api-hooks.ts
  packages/core/src/routes/dashboard.ts
  packages/core/src/routes/organization/roles.ts
  packages/core/src/routes/role.scope.test.ts
  packages/core/src/routes/role.scope.ts
  packages/core/src/routes/role.ts
  packages/core/src/routes/sso-connector/index.ts
  packages/core/src/routes/types.ts
  packages/integration-tests/src/tests/api/hook/hook.trigger.custom.data.test.ts
  packages/integration-tests/src/tests/api/hook/hook.trigger.interaction.test.ts
  packages/integration-tests/src/tests/api/hook/utils.ts
Labels: feature, size/l

#5883 feat(core): update test hook payload
  packages/core/src/libraries/hook/utils.ts
Labels: feature, size/s

#5887 fix(connector): fix invalid image path in connector readme
  packages/connectors/connector-wechat-web/README.md
Labels: chore, bugfix, size/xs

#5894 chore(connector): update wecom connector readme
  packages/connectors/connector-wecom/README.md
Labels: chore, size/xs

#5891 refactor: remove `TenantInfo` type
  packages/cli/src/commands/database/seed/tenant.ts
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/index.tsx
  packages/console/src/components/CreateTenantModal/index.tsx
  packages/console/src/components/CreateTenantModal/type.ts
  packages/console/src/components/CreateTenantModal/types.ts
  packages/console/src/hooks/use-subscribe.ts
  packages/integration-tests/src/api/tenant.ts
  packages/schemas/src/models/tenants.ts
  packages/toolkit/core-kit/src/models/tenant.ts
Labels: enhancement, size/s

#5774 refactor(experience): add global loading status on page redirect
  .changeset/friendly-chicken-pump.md
  packages/experience/src/containers/SocialLinkAccount/use-social-link-related-user.ts
  packages/experience/src/containers/VerificationCode/use-continue-flow-code-verification.ts
  packages/experience/src/containers/VerificationCode/use-register-flow-code-verification.ts
  packages/experience/src/containers/VerificationCode/use-sign-in-flow-code-verification.ts
  packages/experience/src/hooks/use-global-redirect-to.ts
  packages/experience/src/hooks/use-password-sign-in.ts
  packages/experience/src/hooks/use-send-mfa-payload.ts
  packages/experience/src/hooks/use-skip-mfa.ts
  packages/experience/src/hooks/use-social-link-account.ts
  packages/experience/src/hooks/use-social-register.ts
  packages/experience/src/pages/Consent/index.tsx
  packages/experience/src/pages/Continue/SetPassword/index.tsx
  packages/experience/src/pages/Continue/SetUsername/use-set-username.ts
  packages/experience/src/pages/RegisterPassword/index.tsx
  packages/experience/src/pages/SocialSignInWebCallback/use-single-sign-on-listener.ts
Labels: enhancement, size/m

#5897 fix(phrases): fix legacy sie phrases
  packages/phrases-experience/src/locales/de/description.ts
  packages/phrases-experience/src/locales/fr/description.ts
  packages/phrases-experience/src/locales/ko/description.ts
Labels: bugfix, size/xs

#5899 fix(console): fix Nuxt doc typo
  packages/console/src/assets/docs/guides/web-nuxt/README.mdx
Labels: bugfix, size/xs

#5900 chore(phrases): update tenant deletion modal content
  packages/phrases/src/locales/de/translation/admin-console/tenants.ts
  packages/phrases/src/locales/en/translation/admin-console/tenants.ts
  packages/phrases/src/locales/es/translation/admin-console/tenants.ts
  packages/phrases/src/locales/fr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/it/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ja/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ko/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ru/translation/admin-console/tenants.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tenants.ts
Labels: chore, size/l

#5901 fix(console): add pro tag for custom JWT page
  packages/console/src/pages/CustomizeJwt/index.tsx
Labels: bugfix, size/s

#5903 fix(console): fix Laravel misspelling
  packages/console/src/assets/docs/guides/web-php/index.ts
Labels: bugfix, size/xs

#5907 refactor(core): report forwarded headers
  packages/core/src/utils/request.ts
Labels: enhancement, size/s

#5904 refactor: remove internal role policies
  packages/core/src/routes/applications/application.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/integration-tests/src/tests/api/role.scope.test.ts
  packages/integration-tests/src/tests/api/role.test.ts
  packages/schemas/alterations/next-1716278409-remove-internal-role-database-policies.ts
  packages/schemas/src/types/user.ts
  packages/schemas/src/utils/role.ts
  packages/schemas/tables/_after_all.sql
Labels: enhancement, size/m

#5909 chore(console): update pricing table for organizations feature
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-table.ts
Labels: chore, size/m

#5898 feat(console,core): remove DataHook devFeature guard
  .changeset/hip-fireants-talk.md
  packages/console/src/components/BasicWebhookForm/index.tsx
  packages/console/src/consts/env.ts
  packages/console/src/pages/WebhookDetails/WebhookLogs/index.tsx
  packages/core/src/middleware/koa-management-api-hooks.ts
  packages/core/src/routes/hook.ts
  packages/core/src/routes/interaction/middleware/koa-interaction-hooks.ts
  packages/core/src/routes/organization/roles.ts
  packages/core/src/routes/role.ts
Labels: feature, size/m

#5908 feat: create pre-configured role with m-api access when seeding db
  .changeset/angry-tables-repeat.md
  packages/cli/src/commands/database/seed/roles.ts
  packages/cli/src/commands/database/seed/tables.ts
  packages/schemas/alterations/next-1716291265-create-pre-configured-m-api-role.ts
  packages/schemas/src/seeds/management-api.ts
Labels: feature, size/m

#5911 refactor(console): reorg role transfer component file structure
  packages/console/src/components/RolesTransfer/SourceRolesBox/SourceRoleItem/index.module.scss
  packages/console/src/components/RolesTransfer/SourceRolesBox/SourceRoleItem/index.tsx
  packages/console/src/components/RolesTransfer/SourceRolesBox/index.module.scss
  packages/console/src/components/RolesTransfer/SourceRolesBox/index.tsx
  packages/console/src/components/RolesTransfer/TargetRolesBox/TargetRoleItem/index.module.scss
  packages/console/src/components/RolesTransfer/TargetRolesBox/TargetRoleItem/index.tsx
  packages/console/src/components/RolesTransfer/TargetRolesBox/index.module.scss
  packages/console/src/components/RolesTransfer/TargetRolesBox/index.tsx
  packages/console/src/components/RolesTransfer/components/RoleInformation/index.module.scss
  packages/console/src/components/RolesTransfer/components/RoleInformation/index.tsx
  packages/console/src/components/RolesTransfer/components/TargetRoleItem/index.module.scss
  packages/console/src/components/RolesTransfer/components/TargetRoleItem/index.tsx
  packages/console/src/components/RolesTransfer/index.tsx
Labels: enhancement, size/m

#5920 fix(schemas): import `generateStandardId` from correct source
  packages/schemas/alterations/next-1716291265-create-pre-configured-m-api-role.ts
Labels: bugfix, size/xs

#5921 fix: add id generation utils for alteration scripts
  packages/schemas/alterations/next-1716291265-create-pre-configured-m-api-role.ts
  packages/schemas/alterations/utils/1716643968-id-generation.ts
  packages/schemas/package.json
  pnpm-lock.yaml
Labels: bugfix, size/s

#5918 refactor(console): add management api access flag for role options
  packages/console/src/assets/icons/management-api-access.svg
  packages/console/src/components/RolesTransfer/components/RoleInformation/index.module.scss
  packages/console/src/components/RolesTransfer/components/RoleInformation/index.tsx
  packages/console/src/components/RolesTransfer/index.module.scss
  packages/console/src/components/RolesTransfer/index.tsx
  packages/console/src/consts/env.ts
  packages/console/src/hooks/use-user-preferences.ts
  packages/phrases/src/locales/de/translation/admin-console/roles.ts
  packages/phrases/src/locales/en/translation/admin-console/roles.ts
  packages/phrases/src/locales/es/translation/admin-console/roles.ts
  packages/phrases/src/locales/fr/translation/admin-console/roles.ts
  packages/phrases/src/locales/it/translation/admin-console/roles.ts
  packages/phrases/src/locales/ja/translation/admin-console/roles.ts
  packages/phrases/src/locales/ko/translation/admin-console/roles.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/roles.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/roles.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/roles.ts
  packages/phrases/src/locales/ru/translation/admin-console/roles.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/roles.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/roles.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/roles.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/roles.ts
Labels: enhancement, size/m

#5919 refactor(console): add notification for m2m role
  packages/console/src/hooks/use-user-preferences.ts
  packages/console/src/pages/RoleDetails/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/role-details.ts
  packages/phrases/src/locales/en/translation/admin-console/role-details.ts
  packages/phrases/src/locales/es/translation/admin-console/role-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/role-details.ts
  packages/phrases/src/locales/it/translation/admin-console/role-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/role-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/role-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/role-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/role-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/role-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/role-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/role-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/role-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/role-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/role-details.ts
Labels: enhancement, size/s

#5923 fix(console): fix m2m guide curl code syntax error
  packages/console/src/assets/docs/guides/m2m-general/README.mdx
Labels: bugfix, size/s

#5924 refactor(console): setup m2m roles after creating m2m app
  packages/console/src/components/ApplicationCreation/CreateForm/Footer/index.tsx
  packages/console/src/components/ApplicationCreation/CreateForm/index.module.scss
  packages/console/src/components/ApplicationCreation/CreateForm/index.tsx
  packages/console/src/components/ApplicationCreation/index.tsx
  packages/console/src/components/RoleAssignmentModal/index.module.scss
  packages/console/src/components/RoleAssignmentModal/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/MachineToMachineApplicationRoles/index.tsx
  packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
  packages/console/src/pages/Applications/components/GuideLibraryModal/index.tsx
  packages/console/src/pages/GetStarted/index.tsx
  packages/console/src/pages/Roles/components/AssignToRoleModal/index.tsx
  packages/console/src/pages/UserDetails/UserRoles/index.tsx
  packages/integration-tests/src/tests/console/applications/index.test.ts
  packages/phrases/src/locales/de/translation/admin-console/applications.ts
  packages/phrases/src/locales/en/translation/admin-console/applications.ts
  packages/phrases/src/locales/es/translation/admin-console/applications.ts
  packages/phrases/src/locales/fr/translation/admin-console/applications.ts
  packages/phrases/src/locales/it/translation/admin-console/applications.ts
  packages/phrases/src/locales/ja/translation/admin-console/applications.ts
  packages/phrases/src/locales/ko/translation/admin-console/applications.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/applications.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/applications.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/applications.ts
  packages/phrases/src/locales/ru/translation/admin-console/applications.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/applications.ts
Labels: enhancement, size/l

#5931 refactor(console): support multi-region for paid plans
  packages/console/src/cloud/pages/Main/index.tsx
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/index.tsx
  packages/console/src/hooks/use-subscribe.ts
Labels: enhancement, size/s

#5925 fix(connector): fix GitHub connector GET /emails forbidden error
  .changeset/olive-deers-wink.md
  packages/connectors/connector-github/src/index.test.ts
  packages/connectors/connector-github/src/index.ts
Labels: bugfix, size/s

#5862 fix(console): remove outdated nextjs app router guide
  packages/console/src/assets/docs/guides/index.ts
  packages/console/src/assets/docs/guides/web-next-app-router/README.mdx
  packages/console/src/assets/docs/guides/web-next-app-router/config.json
  packages/console/src/assets/docs/guides/web-next-app-router/index.ts
  packages/console/src/assets/docs/guides/web-next-server-actions/README.mdx
  packages/console/src/assets/docs/guides/web-next-server-actions/config.json
  packages/console/src/assets/docs/guides/web-next-server-actions/index.ts
  packages/console/src/assets/docs/guides/web-next-server-actions/logo.svg
  packages/console/src/assets/docs/guides/web-next/index.ts
  packages/integration-tests/src/tests/console/applications/constants.ts
Labels: bugfix, size/xl

#5932 refactor(console): improve onboarding ux
  packages/console/src/components/CreateTenantModal/index.tsx
  packages/console/src/onboarding/pages/CreateTenant/index.tsx
  packages/console/src/onboarding/scss/layout.module.scss
  packages/phrases/src/locales/en/translation/admin-console/cloud.ts
  packages/phrases/src/locales/en/translation/admin-console/tenants.ts
Labels: enhancement, size/s

#5912 fix(core): fix azure oidc sso connector authorization error
  .changeset/serious-geese-admire.md
  packages/core/src/routes/interaction/single-sign-on.ts
  packages/core/src/sso/AzureOidcSsoConnector/index.ts
  packages/core/src/sso/OidcConnector/utils.ts
  packages/core/src/sso/types/oidc.ts
Labels: bugfix, size/s

#5915 feat(connector): add dingtalk connector
  packages/connectors/connector-dingtalk-web/README.md
  packages/connectors/connector-dingtalk-web/logo.svg
  packages/connectors/connector-dingtalk-web/package.json
  packages/connectors/connector-dingtalk-web/src/constant.ts
  packages/connectors/connector-dingtalk-web/src/index.test.ts
  packages/connectors/connector-dingtalk-web/src/index.ts
  packages/connectors/connector-dingtalk-web/src/mock.ts
  packages/connectors/connector-dingtalk-web/src/types.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#5939 chore(phrases): update cloud collaboration invite modal title
  packages/phrases/src/locales/de/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/en/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/es/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/fr/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/it/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/ja/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/ko/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/ru/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tenant-members.ts
Labels: chore, size/s

#5933 refactor(console): add prefix to pv path
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/hooks/use-plausible-pageview.ts
  packages/console/src/onboarding/index.tsx
  packages/console/src/pages/Profile/index.tsx
Labels: enhancement, size/s

#5936 refactor: optmize phrases
  packages/console/package.json
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/index.tsx
  packages/console/src/components/PlanName/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/index.ts
  packages/phrases/src/locales/en/translation/admin-console/tenants.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/index.ts
  pnpm-lock.yaml
Labels: enhancement, size/s

#5938 feat(console): invite collaborators during onboarding
  packages/console/src/cloud/hooks/use-cloud-api.ts
  packages/console/src/components/CreateTenantModal/index.tsx
  packages/console/src/onboarding/pages/CreateTenant/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/InviteEmailsInput/index.module.scss
  packages/console/src/pages/TenantSettings/TenantMembers/InviteEmailsInput/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/cloud.ts
  packages/phrases/src/locales/en/translation/admin-console/tenants.ts
Labels: feature, size/m

#5937 fix(core,console): update invalid documentation links in console and core
  .changeset/gentle-flies-boil.md
  packages/console/src/pages/ApiResourceDetails/components/ManagementApiNotice/index.tsx
  packages/core/src/env-set/preconditions.ts
Labels: bugfix, size/s

#5934 docs(core): remove pagination from get organization invitation api docs
  packages/core/src/routes/organization/invitations.openapi.json
Labels: size/xs

#5906 chore: update translate cli
  .changeset/shaggy-tables-taste.md
  packages/cli/src/commands/translate/sync-keys/utils.ts
Labels: chore, size/s

#5942 chore: fix typo
  packages/connectors/connector-logto-social-demo/src/constant.ts
  packages/experience/src/containers/SocialSignInList/use-social.ts
  packages/experience/src/pages/SocialSignInWebCallback/SocialSignIn.tsx
  packages/phrases/src/locales/en/translation/admin-console/cloud.ts
  packages/phrases/src/locales/en/translation/admin-console/connectors.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/index.ts
Labels: chore, size/s

#5943 refactor(console): fix onboarding issues
  packages/console/src/components/SignInExperiencePreview/index.tsx
  packages/console/src/contexts/AppDataProvider.tsx
  packages/console/src/onboarding/pages/SignInExperience/Preview/index.tsx
  packages/console/src/onboarding/pages/SignInExperience/index.tsx
Labels: enhancement, size/l

#5944 feat(console): show banner when only dev tenant found
  packages/console/src/cloud/pages/Main/TenantLandingPage/TenantLandingPageContent/index.tsx
  packages/console/src/components/Topbar/TenantSelector/index.tsx
  packages/console/src/containers/AppContent/TenantNotificationContainer/CreateProductionTenantBanner/index.module.scss
  packages/console/src/containers/AppContent/TenantNotificationContainer/CreateProductionTenantBanner/index.tsx
  packages/console/src/containers/AppContent/TenantNotificationContainer/index.tsx
  packages/console/src/ds-components/TextLink/index.module.scss
  packages/phrases/src/locales/en/translation/admin-console/tenants.ts
Labels: feature, size/s

#5945 refactor(phrases): update m2m role creation hint
  packages/phrases/src/locales/de/translation/admin-console/applications.ts
  packages/phrases/src/locales/en/translation/admin-console/applications.ts
  packages/phrases/src/locales/es/translation/admin-console/applications.ts
  packages/phrases/src/locales/fr/translation/admin-console/applications.ts
  packages/phrases/src/locales/it/translation/admin-console/applications.ts
  packages/phrases/src/locales/ja/translation/admin-console/applications.ts
  packages/phrases/src/locales/ko/translation/admin-console/applications.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/applications.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/applications.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/applications.ts
  packages/phrases/src/locales/ru/translation/admin-console/applications.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/applications.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/applications.ts
Labels: enhancement, size/s

#5946 refactor(phrases): update management api notification
  packages/phrases/src/locales/de/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/en/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/es/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/it/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/api-resource-details.ts
Labels: enhancement, size/s

#5941 refactor(console): sync m2m integration guide
  packages/console/src/assets/docs/guides/m2m-general/README.mdx
  packages/console/src/assets/docs/guides/m2m-general/assets/assign-mgmt-api-role.webp
  packages/console/src/assets/docs/guides/m2m-general/assets/create-m2m-mgmt-api-role.webp
  packages/console/src/assets/docs/guides/m2m-general/assets/logto-management-api.png
  packages/console/src/assets/docs/guides/m2m-general/components/EnableAdminAccess.tsx
Labels: enhancement, size/l

#5948 refactor(console): set portal `z-index` properly
  packages/console/src/containers/AppContent/TenantNotificationContainer/CreateProductionTenantBanner/index.module.scss
  packages/console/src/containers/AppContent/TenantNotificationContainer/CreateProductionTenantBanner/index.tsx
  packages/console/src/scss/modal.module.scss
  packages/console/src/scss/normalized.scss
Labels: enhancement, size/s

#5949 feat(console): support localStorage override and show dev feature status
  packages/console/src/consts/env.ts
  packages/console/src/consts/storage.ts
  packages/console/src/containers/ConsoleContent/Sidebar/index.module.scss
  packages/console/src/containers/ConsoleContent/index.module.scss
  packages/console/src/containers/ConsoleContent/index.tsx
Labels: feature, size/s

#5951 refactor: update naming
  packages/console/src/pages/Profile/components/ExperienceLikeModal/index.module.scss
  packages/console/src/pages/Profile/components/ExperienceLikeModal/index.tsx
  packages/console/src/pages/Profile/containers/ChangePasswordModal/index.tsx
  packages/console/src/pages/Profile/containers/LinkEmailModal/index.tsx
  packages/console/src/pages/Profile/containers/VerificationCodeModal/index.tsx
  packages/console/src/pages/Profile/containers/VerifyPasswordModal/index.tsx
  packages/core/src/middleware/koa-security-headers.ts
Labels: enhancement, size/s

#5940 feat(connector): add DingTalk web connector changeset
  .changeset/thirty-zoos-compare.md
  packages/connectors/connector-dingtalk-web/package.json
  packages/connectors/connector-dingtalk-web/src/index.ts
Labels: feature, size/xs

#5953 fix(console): avoid rendering outdated role options
  packages/console/src/components/RolesTransfer/SourceRolesBox/index.tsx
Labels: bugfix, size/xs

#5954 refactor(console): remove redundant notification from m2m guide
  packages/console/src/assets/docs/guides/m2m-general/README.mdx
Labels: enhancement, size/xs

#5955 feat(core,toolkit): add new sso_identities claim
  .changeset/quick-hairs-fail.md
  packages/core/src/libraries/jwt-customizer.ts
  packages/core/src/libraries/user.ts
  packages/core/src/oidc/scope.test.ts
  packages/core/src/oidc/scope.ts
  packages/core/src/routes/admin-user/basics.ts
  packages/toolkit/core-kit/src/openid.ts
Labels: feature, size/s

#5958 refactor: improve user experience
  packages/console/src/components/CreateTenantModal/index.tsx
  packages/console/src/onboarding/pages/CreateTenant/index.tsx
  packages/console/src/onboarding/pages/SignInExperience/options.tsx
  packages/phrases/src/locales/de/translation/admin-console/tenants.ts
  packages/phrases/src/locales/en/translation/admin-console/tenants.ts
  packages/phrases/src/locales/es/translation/admin-console/tenants.ts
  packages/phrases/src/locales/fr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/it/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ja/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ko/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ru/translation/admin-console/tenants.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tenants.ts
Labels: enhancement, size/s

#5950 feat(console): show version number for oss
  .changeset/rare-hornets-sneeze.md
  packages/console/src/assets/icons/cube.svg
  packages/console/src/components/Topbar/Contact/index.module.scss
  packages/console/src/components/Topbar/Contact/index.tsx
  packages/console/src/components/Topbar/ContactModal/hook.tsx
  packages/console/src/components/Topbar/ContactModal/index.module.scss
  packages/console/src/components/Topbar/ContactModal/index.tsx
  packages/console/src/components/Topbar/DocumentNavButton/index.module.scss
  packages/console/src/components/Topbar/DocumentNavButton/index.tsx
  packages/console/src/components/Topbar/index.module.scss
  packages/console/src/components/Topbar/index.tsx
  packages/console/src/components/Topbar/utils.test.ts
  packages/console/src/components/Topbar/utils.ts
  packages/console/src/consts/external-links.ts
  packages/core/src/middleware/koa-security-headers.ts
Labels: feature, size/l

#5959 refactor: remove service log fkey
  packages/schemas/alterations/next-1717148078-remove-service-log-reference.ts
  packages/schemas/tables/service_logs.sql
Labels: enhancement, size/s

#5960 refactor(console): improve onboarding data and subscription fetching
  packages/console/src/contexts/TenantsProvider.tsx
  packages/console/src/hooks/use-subscription.ts
  packages/console/src/onboarding/hooks/use-user-onboarding-data.ts
  packages/console/src/onboarding/pages/Welcome/index.tsx
Labels: enhancement, size/s
