Repository logto-io/logto, pull requests merged in 2024-11, with the labels that each got.

#6764 fix(core): should sync the sso identity detail on sign-in
  packages/core/src/queries/user-sso-identities.ts
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/classes/helpers.ts
  packages/core/src/routes/experience/classes/libraries/provision-library.ts
  packages/core/src/routes/experience/classes/verifications/enterprise-sso-verification.ts
  packages/core/src/routes/experience/types.ts
Labels: bugfix, size/s

#6763 fix(core): fix enterprise SSO unknown field not synced issue
  packages/core/src/queries/user-sso-identities.ts
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/classes/helpers.ts
  packages/core/src/routes/experience/classes/libraries/provision-library.ts
  packages/core/src/routes/experience/classes/verifications/enterprise-sso-verification.ts
  packages/core/src/routes/experience/types.ts
  packages/core/src/routes/interaction/utils/single-sign-on.ts
  packages/core/src/utils/json.test.ts
  packages/core/src/utils/json.ts
Labels: bugfix, size/m

#6745 style(experience): update the devTenantNotification style
  packages/experience-legacy/src/App.tsx
  packages/experience-legacy/src/Layout/AppLayout/index.tsx
  packages/experience-legacy/src/containers/DevelopmentTenantNotification/index.tsx
  packages/experience/src/App.tsx
  packages/experience/src/Layout/AppLayout/index.tsx
  packages/experience/src/containers/DevelopmentTenantNotification/index.tsx
Labels: size/s

#6761 feat(schemas): add account center table
  packages/schemas/alterations/next-1730689363-add-account-center.ts
  packages/schemas/src/foundations/jsonb-types/account-centers.ts
  packages/schemas/src/foundations/jsonb-types/index.ts
  packages/schemas/tables/account_centers.sql
Labels: feature, size/s

#6768 feat(connector): add vonage connector
  packages/connectors/connector-vonage-sms/README.md
  packages/connectors/connector-vonage-sms/logo.svg
  packages/connectors/connector-vonage-sms/package.json
  packages/connectors/connector-vonage-sms/src/constant.ts
  packages/connectors/connector-vonage-sms/src/index.test.ts
  packages/connectors/connector-vonage-sms/src/index.ts
  packages/connectors/connector-vonage-sms/src/mock.ts
  packages/connectors/connector-vonage-sms/src/types.ts
  packages/console/src/components/CreateConnectorForm/index.tsx
  pnpm-lock.yaml
Labels: feature, size/l

#6774 fix(console): fix vonage connector id
  packages/console/src/components/CreateConnectorForm/index.tsx
Labels: bugfix, size/xs

#6772 feat(core): add account center api
  packages/cli/src/commands/database/seed/tables.ts
  packages/core/src/queries/account-center.ts
  packages/core/src/routes/account-center/index.openapi.json
  packages/core/src/routes/account-center/index.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/swagger/utils/documents.ts
  packages/core/src/tenants/Queries.ts
  packages/integration-tests/src/api/account-center.ts
  packages/integration-tests/src/tests/api/account-center.test.ts
  packages/schemas/alterations/next-1731054001-init-account-center.ts
  packages/schemas/src/foundations/jsonb-types/account-center.ts
  packages/schemas/src/seeds/account-center.ts
Labels: feature, size/m

#6780 feat(console): support console url with wildcard tenant id
  packages/console/src/containers/TenantAccess/index.tsx
  packages/console/src/contexts/SubscriptionDataProvider/index.tsx
  packages/console/src/contexts/TenantsProvider.tsx
Labels: feature, size/s

#6784 fix(core): set default social session
  packages/core/src/routes/experience/classes/verifications/social-verification.ts
Labels: bugfix, size/xs

#6776 feat(core): apply account center field control
  packages/core/src/routes/profile/index.ts
  packages/core/src/routes/profile/middlewares/koa-account-center.ts
  packages/core/src/routes/profile/utils/get-scoped-profile.ts
  packages/core/src/routes/types.ts
  packages/core/src/routes/well-known/well-known.openapi.ts
  packages/integration-tests/src/api/account-center.ts
  packages/integration-tests/src/tests/api/account-center.test.ts
  packages/integration-tests/src/tests/api/profile/account-center-reject.test.ts
  packages/integration-tests/src/tests/api/profile/email-and-phone.test.ts
  packages/integration-tests/src/tests/api/profile/index.test.ts
  packages/integration-tests/src/tests/api/profile/social.test.ts
  packages/phrases/src/locales/en/errors/account-center.ts
  packages/phrases/src/locales/en/errors/index.ts
Labels: feature, size/l

#6791 fix(schemas): export account center seed function
  packages/schemas/src/seeds/index.ts
Labels: bugfix, size/xs

#6789 feat(schemas): add suppport email and website url to sie
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/queries/sign-in-experience.test.ts
  packages/experience-legacy/src/__mocks__/logto.tsx
  packages/experience/src/__mocks__/logto.tsx
  packages/schemas/alterations/next-1731304920-add-support-email-and-website-to-sie-table.ts
  packages/schemas/tables/sign_in_experiences.sql
Labels: feature, size/s

#6790 feat(core): add support email & website url format guard
  packages/core/src/routes/sign-in-experience/index.test.ts
  packages/core/src/routes/sign-in-experience/index.ts
  packages/integration-tests/src/tests/api/sign-in-experience.test.ts
Labels: feature, size/s

#6792 feat(console): add support fields config to sie
  packages/console/src/pages/SignInExperience/PageContent/Content/SupportForm/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/Content/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/content.ts
Labels: feature, size/s

#6793 feat(experience): display support info in error page
  packages/experience-legacy/src/pages/ErrorPage/SupportInfo.tsx
  packages/experience-legacy/src/pages/ErrorPage/index.module.scss
  packages/experience-legacy/src/pages/ErrorPage/index.tsx
  packages/experience/src/pages/ErrorPage/SupportInfo.tsx
  packages/experience/src/pages/ErrorPage/index.module.scss
  packages/experience/src/pages/ErrorPage/index.tsx
  packages/phrases-experience/src/locales/ar/description.ts
  packages/phrases-experience/src/locales/de/description.ts
  packages/phrases-experience/src/locales/en/description.ts
  packages/phrases-experience/src/locales/es/description.ts
  packages/phrases-experience/src/locales/fr/description.ts
  packages/phrases-experience/src/locales/it/description.ts
  packages/phrases-experience/src/locales/ja/description.ts
  packages/phrases-experience/src/locales/ko/description.ts
  packages/phrases-experience/src/locales/pl-pl/description.ts
  packages/phrases-experience/src/locales/pt-br/description.ts
  packages/phrases-experience/src/locales/pt-pt/description.ts
  packages/phrases-experience/src/locales/ru/description.ts
  packages/phrases-experience/src/locales/tr-tr/description.ts
  packages/phrases-experience/src/locales/zh-cn/description.ts
  packages/phrases-experience/src/locales/zh-hk/description.ts
  packages/phrases-experience/src/locales/zh-tw/description.ts
Labels: feature, size/m

#6800 feat(core,console): add trust unverified email settings to Azure SSO
  packages/console/src/pages/EnterpriseSsoDetails/Connection/OidcMetadataForm/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/types/oidc.ts
  packages/core/src/sso/AzureOidcSsoConnector/index.ts
  packages/core/src/sso/types/index.ts
  packages/phrases/src/locales/en/translation/admin-console/enterprise-sso-details.ts
Labels: feature, size/s

#6796 feat(schemas,core): add unknown session redirect url to sie
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/queries/sign-in-experience.test.ts
  packages/core/src/routes/sign-in-experience/index.openapi.json
  packages/core/src/routes/sign-in-experience/index.test.ts
  packages/core/src/routes/sign-in-experience/index.ts
  packages/experience-legacy/src/__mocks__/logto.tsx
  packages/experience/src/__mocks__/logto.tsx
  packages/schemas/alterations/next-1731377260-add-unknown-session-redirect-url-to-sie.ts
  packages/schemas/tables/sign_in_experiences.sql
Labels: feature, size/s

#6798 feat(core): redirect to redirect url from sie on session not found
  packages/core/src/middleware/koa-spa-session-guard.test.ts
  packages/core/src/middleware/koa-spa-session-guard.ts
Labels: feature, size/s

#6797 feat(console): add unknown session redirect url input field
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/AdvancedOptions/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/utils/parser.ts
  packages/core/src/middleware/koa-spa-session-guard.test.ts
  packages/core/src/middleware/koa-spa-session-guard.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
Labels: feature, size/s

#6803 chore: fix typo
  packages/integration-tests/src/tests/api/profile/account-center-reject.test.ts
Labels: chore, size/xs

#6806 chore(phrases): update content
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
Labels: chore, size/xs

#6807 feat(console,phrases): add support field description
  packages/console/src/pages/SignInExperience/PageContent/Content/SupportForm/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/content.ts
Labels: feature, size/xs

#6799 fix(core): allow all origins for profile and verification api
  packages/core/src/middleware/koa-cors.test.ts
  packages/core/src/middleware/koa-cors.ts
  packages/core/src/routes-me/init.ts
  packages/core/src/routes/init.ts
  packages/integration-tests/src/tests/api/profile/index.test.ts
Labels: bugfix, size/m

#6808 chore: remove dev feature guard
  .changeset/early-numbers-attend.md
  .changeset/four-deers-divide.md
  .changeset/wet-nails-guess.md
  packages/console/src/pages/EnterpriseSsoDetails/Connection/OidcMetadataForm/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/Content/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/AdvancedOptions/index.tsx
  packages/core/src/middleware/koa-spa-session-guard.test.ts
  packages/core/src/middleware/koa-spa-session-guard.ts
Labels: chore, size/m

#6801 refactor(core): move verification record id to header
  packages/core/src/libraries/verification.ts
  packages/core/src/middleware/koa-auth/constants.ts
  packages/core/src/middleware/koa-auth/index.ts
  packages/core/src/middleware/koa-auth/koa-oidc-auth.test.ts
  packages/core/src/middleware/koa-auth/koa-oidc-auth.ts
  packages/core/src/middleware/koa-auth/types.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/profile/index.openapi.json
  packages/core/src/routes/profile/index.ts
  packages/integration-tests/src/api/profile.ts
  packages/integration-tests/src/tests/api/profile/account-center-reject.test.ts
  packages/integration-tests/src/tests/api/profile/email-and-phone.test.ts
  packages/integration-tests/src/tests/api/profile/index.test.ts
  packages/integration-tests/src/tests/api/profile/social.test.ts
Labels: enhancement, size/l

#6802 refactor(core): split profile route
  packages/core/src/routes/profile/identities.ts
  packages/core/src/routes/profile/index.ts
Labels: enhancement, size/m

#6814 refactor(core): rename prefix to account
  packages/core/src/routes/account-center/index.openapi.json
  packages/core/src/routes/account/constants.ts
  packages/core/src/routes/account/email-and-phone.ts
  packages/core/src/routes/account/identities.ts
  packages/core/src/routes/account/index.openapi.json
  packages/core/src/routes/account/index.ts
  packages/core/src/routes/account/middlewares/koa-account-center.ts
  packages/core/src/routes/account/utils/get-scoped-profile.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/swagger/utils/operation-id.ts
  packages/core/src/routes/types.ts
  packages/core/src/routes/verification/index.ts
  packages/core/src/routes/well-known/well-known.openapi.ts
  packages/integration-tests/src/api/profile.ts
  packages/integration-tests/src/tests/api/account/account-center-reject.test.ts
  packages/integration-tests/src/tests/api/account/email-and-phone.test.ts
  packages/integration-tests/src/tests/api/account/index.test.ts
  packages/integration-tests/src/tests/api/account/social.test.ts
  packages/schemas/src/foundations/jsonb-types/account-center.ts
Labels: enhancement, size/l

#6815 chore: add app insights log for oidc server error
  packages/core/src/middleware/koa-oidc-error-handler.ts
Labels: chore, size/xs

#6818 chore: remove feature guard
  packages/core/src/routes/account-center/index.openapi.json
  packages/core/src/routes/account/index.openapi.json
  packages/core/src/routes/account/index.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/swagger/utils/documents.ts
  packages/core/src/routes/verification/index.openapi.json
  packages/core/src/routes/verification/index.ts
  packages/integration-tests/src/tests/api/account-center.test.ts
  packages/integration-tests/src/tests/api/account/account-center-reject.test.ts
  packages/integration-tests/src/tests/api/account/email-and-phone.test.ts
  packages/integration-tests/src/tests/api/account/index.test.ts
  packages/integration-tests/src/tests/api/account/social.test.ts
Labels: chore, size/s

#6813 chore: add changeset of account api
  .changeset/warm-pugs-divide.md
Labels: chore, size/s

#6823 fix(schemas): fix init account center alter run in chunks
  packages/schemas/alterations/next-1731054001-init-account-center.ts
Labels: bugfix, size/s

#6824 fix(schemas): resolve duplicates of init account center alter
  packages/schemas/alterations/next-1731054001-init-account-center.ts
Labels: bugfix, size/xs

#6826 fix(schemas): fix alter script of init account center
  packages/schemas/alterations/next-1731054001-init-account-center.ts
Labels: bugfix, size/xs

#6766 feat(schemas,core,console): add SAML application type
  packages/console/src/components/ApplicationCreation/CreateForm/index.tsx
  packages/console/src/components/ApplicationIcon/index.tsx
  packages/console/src/components/Guide/hooks.ts
  packages/console/src/components/ItemPreview/ApplicationPreview.tsx
  packages/console/src/consts/applications.ts
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/GuideDrawer/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/IdpInitiatedAuth/ConfigForm.tsx
  packages/core/src/routes/applications/application.ts
  packages/integration-tests/src/tests/api/application/application.secrets.test.ts
  packages/integration-tests/src/tests/api/application/application.test.ts
  packages/integration-tests/src/tests/console/applications/constants.ts
  packages/phrases/src/locales/en/errors/application.ts
  packages/schemas/alterations/next-1731900596-add-saml-application-type.ts
  packages/schemas/alterations/next-1731900631-add-saml-app-third-party-consistency-check.ts
  packages/schemas/src/utils/application.ts
  packages/schemas/tables/applications.sql
Labels: feature, size/m

#6817 feat(schemas): add `saml_application_configs` table
  packages/schemas/alterations/next-1731904029-add-saml-application-configs-table.ts
  packages/schemas/src/foundations/jsonb-types/index.ts
  packages/schemas/src/foundations/jsonb-types/saml-application-configs.ts
  packages/schemas/tables/saml_application_configs.sql
Labels: feature, size/s

#6819 fix(core): add redis ping interval
  packages/core/src/caches/index.ts
  packages/core/src/caches/well-known.ts
Labels: bugfix, size/s

#6820 refactor(schemas, console): remove deprecated ReservedPlanIds
  packages/console/src/components/ApplicationCreation/CreateForm/Footer/index.tsx
  packages/console/src/components/CreateConnectorForm/Footer/index.tsx
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/SkuCardItem/index.tsx
  packages/console/src/components/MauExceededModal/index.tsx
  packages/console/src/components/PlanDescription/index.tsx
  packages/console/src/components/SkuName/index.tsx
  packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx
  packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx
  packages/console/src/pages/ApiResources/components/CreateForm/Footer.tsx
  packages/console/src/pages/Applications/components/ProtectedAppForm/index.tsx
  packages/console/src/pages/RoleDetails/RolePermissions/components/AssignPermissionsModal/index.tsx
  packages/console/src/pages/Roles/components/CreateRoleForm/Footer.tsx
  packages/console/src/pages/TenantSettings/BillingHistory/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/SwitchPlanActionBar/index.tsx
  packages/console/src/pages/Webhooks/CreateFormModal/CreateForm.tsx
  packages/console/src/types/subscriptions.ts
  packages/schemas/src/consts/subscriptions.ts
Labels: enhancement, size/m

#6837 refactor(console): optimize onboarding
  packages/console/src/cloud/pages/SocialDemoCallback/index.tsx
  packages/console/src/components/ActionBar/index.tsx
  packages/console/src/components/CreateTenantModal/index.tsx
  packages/console/src/consts/tenants.ts
  packages/console/src/contexts/AppDataProvider.tsx
  packages/console/src/onboarding/components/CardSelector/CardSelector.tsx
  packages/console/src/onboarding/components/CardSelector/MultiCardSelector/CardItem.module.scss
  packages/console/src/onboarding/components/CardSelector/MultiCardSelector/CardItem.tsx
  packages/console/src/onboarding/components/CardSelector/MultiCardSelector/index.module.scss
  packages/console/src/onboarding/components/CardSelector/MultiCardSelector/index.tsx
  packages/console/src/onboarding/components/CardSelector/index.tsx
  packages/console/src/onboarding/components/CardSelector/types.ts
  packages/console/src/onboarding/components/DemoConnectorNotice/index.tsx
  packages/console/src/onboarding/hooks/use-tenant-api.ts
  packages/console/src/onboarding/hooks/use-tenant-swr-options.ts
  packages/console/src/onboarding/hooks/use-tenant-user-asset-service.ts
  packages/console/src/onboarding/index.tsx
  packages/console/src/onboarding/pages/CreateTenant/index.tsx
  packages/console/src/onboarding/pages/SignInExperience/InspireMe/index.module.scss
  packages/console/src/onboarding/pages/SignInExperience/InspireMe/index.tsx
  packages/console/src/onboarding/pages/SignInExperience/Preview/PlatformTabs/PlatformTab.module.scss
  packages/console/src/onboarding/pages/SignInExperience/Preview/PlatformTabs/PlatformTab.tsx
  packages/console/src/onboarding/pages/SignInExperience/Preview/PlatformTabs/index.module.scss
  packages/console/src/onboarding/pages/SignInExperience/Preview/PlatformTabs/index.tsx
  packages/console/src/onboarding/pages/SignInExperience/Preview/index.module.scss
  packages/console/src/onboarding/pages/SignInExperience/Preview/index.tsx
  packages/console/src/onboarding/pages/SignInExperience/Skeleton/index.module.scss
  packages/console/src/onboarding/pages/SignInExperience/Skeleton/index.tsx
  packages/console/src/onboarding/pages/SignInExperience/SocialSelector/index.tsx
  packages/console/src/onboarding/pages/SignInExperience/form-data-parser.ts
  packages/console/src/onboarding/pages/SignInExperience/index.module.scss
  packages/console/src/onboarding/pages/SignInExperience/index.tsx
  packages/console/src/onboarding/pages/SignInExperience/options.tsx
  packages/console/src/onboarding/pages/SignInExperience/sie-config-templates.ts
  packages/console/src/onboarding/pages/SignInExperience/types.ts
  packages/console/src/onboarding/pages/Welcome/index.module.scss
  packages/console/src/onboarding/pages/Welcome/index.tsx
  packages/console/src/onboarding/pages/Welcome/options.tsx
  packages/console/src/onboarding/types.ts
  packages/console/src/onboarding/utils.ts
  packages/phrases/src/locales/ar/translation/admin-console/cloud.ts
  packages/phrases/src/locales/de/translation/admin-console/cloud.ts
  packages/phrases/src/locales/en/translation/admin-console/cloud.ts
  packages/phrases/src/locales/es/translation/admin-console/cloud.ts
  packages/phrases/src/locales/fr/translation/admin-console/cloud.ts
  packages/phrases/src/locales/it/translation/admin-console/cloud.ts
  packages/phrases/src/locales/ja/translation/admin-console/cloud.ts
  packages/phrases/src/locales/ko/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/cloud.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/cloud.ts
  packages/phrases/src/locales/ru/translation/admin-console/cloud.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/cloud.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/cloud.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/cloud.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/cloud.ts
Labels: enhancement, size/xl

#6838 fix: add DB constraints sorting reference
  .scripts/compare-database.js
Labels: bugfix, size/xs

#6822 feat(core): add `POST /saml-applications` and `DEL /saml-applications/:id` APIs
  .gitignore
  packages/core/package.json
  packages/core/src/routes/applications/application.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/swagger/utils/general.ts
  packages/core/src/routes/swagger/utils/operation.ts
  packages/core/src/saml-applications/libraries/secrets.ts
  packages/core/src/saml-applications/libraries/utils.test.ts
  packages/core/src/saml-applications/libraries/utils.ts
  packages/core/src/saml-applications/queries/configs.ts
  packages/core/src/saml-applications/queries/secrets.ts
  packages/core/src/saml-applications/routes/index.ts
  packages/core/src/saml-applications/routes/utils.ts
  packages/core/src/tenants/Libraries.ts
  packages/core/src/tenants/Queries.ts
  packages/integration-tests/src/api/saml-application.ts
  packages/integration-tests/src/tests/api/application/application.test.ts
  packages/integration-tests/src/tests/api/application/saml-application.test.ts
  packages/phrases/src/locales/en/errors/application.ts
  packages/schemas/src/types/index.ts
  packages/schemas/src/types/saml-application.ts
  packages/schemas/tables/saml_application_configs.sql
  pnpm-lock.yaml
Labels: feature, size/xl

#6840 chore: rename SAML application secrets/configs constraints
  packages/schemas/alterations/next-1732851150-rename-saml-application-constraints.ts
  packages/schemas/tables/saml_application_configs.sql
  packages/schemas/tables/saml_application_secrets.sql
Labels: chore, size/s
