Repository logto-io/logto, pull requests merged in 2024-07, with the labels that each got.

#6134 refactor(console): update golang guide
  packages/console/src/assets/docs/guides/web-go/README.mdx
Labels: enhancement, size/m

#6132 refactor(console): fix switch styles
  packages/console/src/components/ConnectorForm/GoogleOneTapCard/index.module.scss
  packages/console/src/components/ConnectorForm/GoogleOneTapCard/index.tsx
  packages/console/src/ds-components/Switch/index.module.scss
Labels: enhancement, size/s

#6143 refactor(console): fix php guide
  packages/console/src/assets/docs/fragments/_checkpoint.md
  packages/console/src/assets/docs/guides/web-php/README.mdx
Labels: enhancement, size/s

#6105 feat: demo app dev panel
  .changeset/few-moose-sniff.md
  packages/console/package.json
  packages/demo-app/package.json
  packages/demo-app/src/App.module.scss
  packages/demo-app/src/App.tsx
  packages/demo-app/src/DevPanel.tsx
  packages/demo-app/src/utils.ts
  packages/phrases/src/locales/de/translation/demo-app.ts
  packages/phrases/src/locales/en/translation/demo-app.ts
  packages/phrases/src/locales/es/translation/demo-app.ts
  packages/phrases/src/locales/fr/translation/demo-app.ts
  packages/phrases/src/locales/it/translation/demo-app.ts
  packages/phrases/src/locales/ja/translation/demo-app.ts
  packages/phrases/src/locales/ko/translation/demo-app.ts
  packages/phrases/src/locales/pl-pl/translation/demo-app.ts
  packages/phrases/src/locales/pt-br/translation/demo-app.ts
  packages/phrases/src/locales/pt-pt/translation/demo-app.ts
  packages/phrases/src/locales/ru/translation/demo-app.ts
  packages/phrases/src/locales/tr-tr/translation/demo-app.ts
  packages/phrases/src/locales/zh-cn/translation/demo-app.ts
  packages/phrases/src/locales/zh-hk/translation/demo-app.ts
  packages/phrases/src/locales/zh-tw/translation/demo-app.ts
  pnpm-lock.yaml
Labels: feature, size/l

#6130 docs(console): update the sveltekit guide
  packages/console/src/assets/docs/guides/web-sveltekit/README.mdx
Labels: size/s

#6127 chore: launch jit
  packages/console/src/pages/OrganizationDetails/Settings/index.tsx
Labels: chore, size/xs

#6129 chore: launch m2m app for organizations
  .changeset/gentle-camels-film.md
  packages/console/src/hooks/use-console-routes/routes/organizations.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
  packages/console/src/pages/OrganizationDetails/index.tsx
  packages/console/src/pages/OrganizationTemplate/OrganizationRoles/CreateOrganizationRoleModal.tsx
  packages/core/src/oidc/grants/client-credentials.ts
  packages/core/src/routes/applications/application-organization.openapi.json
  packages/core/src/routes/applications/application-organization.ts
  packages/core/src/routes/organization/application/index.openapi.json
  packages/core/src/routes/organization/application/index.ts
  packages/core/src/routes/swagger/index.ts
  packages/integration-tests/src/tests/api/application/application.organization.test.ts
  packages/integration-tests/src/tests/api/oidc/client-credentials-grant.test.ts
  packages/integration-tests/src/tests/api/organization/organization-application.test.ts
  packages/integration-tests/src/tests/api/organization/organization-user.test.ts
Labels: chore, size/l

#6144 chore: normalize Logto DB region role names for DB alteration CI
  .scripts/compare-database.js
Labels: chore, size/xs

#6126 docs(console): update the expo SDK integration guide
  packages/console/src/assets/docs/fragments/_redirect-uris-native.mdx
  packages/console/src/assets/docs/guides/native-expo/README.mdx
Labels: size/s

#6057 feat(core,schemas): token exchange grant
  packages/core/src/event-listeners/grant.ts
  packages/core/src/oidc/grants/index.ts
  packages/core/src/oidc/grants/token-exchange.test.ts
  packages/core/src/oidc/grants/token-exchange.ts
  packages/core/src/oidc/utils.test.ts
  packages/core/src/oidc/utils.ts
  packages/core/src/queries/subject-token.ts
  packages/integration-tests/src/tests/api/oidc/token-exchange.test.ts
  packages/schemas/src/types/log/token.ts
  packages/schemas/src/types/oidc-config.ts
Labels: feature, size/l

#6148 fix(experience): add missing `agreeToTermsPolicy` deps
  packages/experience/src/pages/SocialSignInWebCallback/use-single-sign-on-listener.ts
Labels: bugfix, size/xs

#6149 refactor: fix mermaid in production
  packages/console/src/mdx-components/Mermaid/index.tsx
  packages/core/src/middleware/koa-security-headers.ts
Labels: enhancement, size/s

#6141 ci: rerun integration tests on failure
  .github/workflows/alteration-compatibility-integration-test.yml
  .github/workflows/integration-test.yml
  .github/workflows/rerun.yml
Labels: size/s

#6133 docs(console): update the java spring guide
  packages/console/src/assets/docs/fragments/_redirect-uris-web.mdx
  packages/console/src/assets/docs/guides/web-java-spring-boot/README.mdx
Labels: size/s

#6158 refactor(console): add retry button on error
  packages/console/src/components/AppError/index.module.scss
  packages/console/src/components/AppError/index.tsx
Labels: enhancement, size/s

#6156 refactor(console): update vanilla js integration guide
  packages/console/src/assets/docs/guides/spa-vanilla/README.mdx
Labels: enhancement, size/m

#6151 refactor(console): update react integration guide
  packages/console/src/assets/docs/guides/spa-react/README.mdx
  packages/console/src/components/Guide/index.module.scss
Labels: enhancement, size/m

#6153 refactor(console): update vue integration guide
  packages/console/src/assets/docs/guides/spa-vue/README.mdx
Labels: enhancement, size/m

#6157 refactor(console): update angular integration guide
  packages/console/src/assets/docs/guides/spa-angular/README.mdx
Labels: enhancement, size/s

#6155 refactor(console): load mermaid in dev
  packages/console/src/mdx-components/Mermaid/index.tsx
Labels: enhancement, size/xs

#6100 feat(core): third-party applications are not allowed for token exchange
  packages/core/src/oidc/grants/token-exchange.test.ts
  packages/core/src/oidc/grants/token-exchange.ts
  packages/integration-tests/src/tests/api/oidc/token-exchange.test.ts
Labels: feature, size/s

#6152 refactor: update compare DB alteration scripts
  .scripts/compare-database.js
Labels: enhancement, size/s

#6160 refactor: upgrade logto sdks
  packages/console/package.json
  packages/demo-app/package.json
  packages/integration-tests/package.json
  packages/integration-tests/src/tests/api/oidc/organization-token.test.ts
  pnpm-lock.yaml
Labels: enhancement, size/s

#6161 fix(console): fix broken api resource guides
  packages/console/src/assets/docs/guides/api-python/README.mdx
  packages/console/src/assets/docs/guides/api-spring-boot/README.mdx
Labels: bugfix, size/s

#6106 feat(core): organization token for token exchange flow
  packages/core/src/oidc/grants/token-exchange.test.ts
  packages/core/src/oidc/grants/token-exchange.ts
  packages/integration-tests/src/tests/api/oidc/token-exchange.test.ts
Labels: feature, size/l

#6162 refactor(console): optimize api resource guides
  packages/console/src/assets/docs/guides/api-python/README.mdx
  packages/console/src/assets/docs/guides/api-spring-boot/README.mdx
  packages/console/src/components/Guide/index.tsx
Labels: enhancement, size/s

#6166 fix(console): fix custom element swap in mdx
  packages/console/src/assets/docs/guides/api-python/README.mdx
  packages/console/src/assets/docs/guides/native-flutter/README.mdx
  packages/console/src/assets/docs/guides/native-ios-swift/README.mdx
  packages/console/src/assets/docs/guides/web-go/README.mdx
  packages/console/src/components/Guide/index.module.scss
  packages/console/src/mdx-components/Anchor/index.tsx
  packages/console/src/mdx-components/MdxProvider/index.tsx
Labels: bugfix, size/s

#6159 refactor(console): add aggregated npm installation component
  packages/console/package.json
  packages/console/src/assets/docs/guides/api-express/README.mdx
  packages/console/src/assets/docs/guides/api-spring-boot/README.mdx
  packages/console/src/assets/docs/guides/m2m-general/README.mdx
  packages/console/src/assets/docs/guides/native-capacitor/README.mdx
  packages/console/src/assets/docs/guides/native-expo/README.mdx
  packages/console/src/assets/docs/guides/native-flutter/README.mdx
  packages/console/src/assets/docs/guides/native-ios-swift/README.mdx
  packages/console/src/assets/docs/guides/spa-angular/README.mdx
  packages/console/src/assets/docs/guides/spa-react/README.mdx
  packages/console/src/assets/docs/guides/spa-vanilla/README.mdx
  packages/console/src/assets/docs/guides/spa-vue/README.mdx
  packages/console/src/assets/docs/guides/spa-webflow/README.mdx
  packages/console/src/assets/docs/guides/web-express/README.mdx
  packages/console/src/assets/docs/guides/web-next-app-router/README.mdx
  packages/console/src/assets/docs/guides/web-next/README.mdx
  packages/console/src/assets/docs/guides/web-nuxt/README.mdx
  packages/console/src/assets/docs/guides/web-php/README.mdx
  packages/console/src/assets/docs/guides/web-sveltekit/README.mdx
  packages/console/src/assets/docs/guides/web-wordpress/README.mdx
  packages/console/src/ds-components/CodeEditor/index.tsx
  packages/console/src/mdx-components/Code/index.tsx
  packages/console/src/mdx-components/NpmLikeInstallation/index.tsx
  packages/console/src/mdx-components/Tabs/index.tsx
Labels: enhancement, size/l

#6167 refactor: update ci and package
  .github/workflows/integration-test.yml
  .github/workflows/rerun.yml
  packages/integration-tests/package.json
  packages/integration-tests/src/tests/api/oidc/organization-token.test.ts
  pnpm-lock.yaml
Labels: enhancement, size/s

#6168 fix(console): hide error toast for non-existed application in audit logs
  .changeset/good-shrimps-cover.md
  packages/console/src/components/ApplicationName/index.tsx
Labels: bugfix, size/xs

#6108 feat: add `operationId` to HTTP methods on paths
  .changeset/brown-cobras-know.md
  packages/core/src/routes/swagger/index.test.ts
  packages/core/src/routes/swagger/index.ts
  packages/core/src/routes/swagger/utils/general.ts
  packages/core/src/routes/swagger/utils/operation-id.test.ts
  packages/core/src/routes/swagger/utils/operation-id.ts
  packages/integration-tests/src/api/index.ts
  packages/integration-tests/src/tests/api/swagger-check.test.ts
Labels: feature, size/l

#6010 feat(schemas): custom ui assets db update
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/queries/sign-in-experience.test.ts
  packages/experience/src/__mocks__/logto.tsx
  packages/schemas/alterations/next-1719312694-custom-ui-assets.ts
  packages/schemas/src/seeds/sign-in-experience.ts
  packages/schemas/tables/sign_in_experiences.sql
Labels: feature, size/s

#6170 fix(core): issue `organization_id` claim for client credentials
  packages/core/src/oidc/extra-token-claims.ts
  packages/integration-tests/src/tests/api/oidc/client-credentials-grant.test.ts
Labels: bugfix, size/xs

#6147 feat(core): handle oidc scopes for token exchange
  packages/core/src/oidc/grants/token-exchange.ts
  packages/integration-tests/src/tests/api/oidc/token-exchange.test.ts
Labels: feature, size/s

#6163 refactor(experience): rename `SingleSignOnContext` to `UserInteractionContext`
  packages/experience/src/App.tsx
  packages/experience/src/Providers/UserInteractionContextProvider/UserInteractionContext.tsx
  packages/experience/src/Providers/UserInteractionContextProvider/index.tsx
  packages/experience/src/hooks/use-check-single-sign-on.ts
  packages/experience/src/hooks/use-single-sign-on-watch.ts
  packages/experience/src/pages/Register/IdentifierRegisterForm/index.test.tsx
  packages/experience/src/pages/SignIn/IdentifierSignInForm/index.test.tsx
  packages/experience/src/pages/SignIn/PasswordSignInForm/index.test.tsx
  packages/experience/src/pages/SingleSignOnConnectors/index.tsx
  packages/experience/src/pages/SingleSignOnEmail/index.tsx
Labels: enhancement, size/m

#6181 fix(console): fix page issues
  packages/console/src/assets/docs/guides/spa-react/README.mdx
  packages/console/src/mdx-components/Mermaid/index.tsx
Labels: bugfix, size/s

#6183 refactor(console): check mermaid by integration test env
  packages/console/src/mdx-components/Mermaid/index.tsx
Labels: enhancement, size/xs

#5992 feat(core): implement new experience API routes
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/classes/verifications/index.ts
  packages/core/src/routes/experience/classes/verifications/password-verification.ts
  packages/core/src/routes/experience/classes/verifications/verification-record.ts
  packages/core/src/routes/experience/const.ts
  packages/core/src/routes/experience/index.ts
  packages/core/src/routes/experience/middleware/koa-experience-interaction.ts
  packages/core/src/routes/experience/types.ts
  packages/core/src/routes/experience/utils.ts
  packages/core/src/routes/experience/verification-routes/password-verification.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/interaction/utils/interaction.ts
  packages/integration-tests/src/client/experience/const.ts
  packages/integration-tests/src/client/experience/index.ts
  packages/integration-tests/src/helpers/client.ts
  packages/integration-tests/src/helpers/experience/index.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-with-password-verification/happy-path.test.ts
  packages/integration-tests/src/tests/api/experience-api/verifications/password-verification.test.ts
  packages/phrases/src/locales/en/errors/session.ts
  packages/schemas/src/types/interactions.ts
Labels: feature, size/xl

#6001 feat(core): implement verification code verification API
  packages/core/src/routes/experience/classes/verifications/code-verification.ts
  packages/core/src/routes/experience/classes/verifications/index.ts
  packages/core/src/routes/experience/index.ts
  packages/core/src/routes/experience/verification-routes/verification-code.ts
  packages/integration-tests/src/client/experience/index.ts
  packages/integration-tests/src/helpers/experience/index.ts
  packages/integration-tests/src/helpers/experience/verification-code.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/password.test.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/verification-code.test.ts
  packages/integration-tests/src/tests/api/experience-api/verifications/verification-code.test.ts
  packages/schemas/src/types/interactions.ts
Labels: feature, size/xl

#6177 refactor(console): improve dotnet guides
  packages/console/parcel-transformer-mdx2.js
  packages/console/src/assets/docs/fragments/_experience-overview.md
  packages/console/src/assets/docs/fragments/_experience-overview.mdx
  packages/console/src/assets/docs/fragments/_redirect-uris-native.mdx
  packages/console/src/assets/docs/fragments/_redirect-uris-web.mdx
  packages/console/src/assets/docs/fragments/_regarding-redirect-based-sign-in.md
  packages/console/src/assets/docs/guides/web-dotnet-core-blazor-server/README.mdx
  packages/console/src/assets/docs/guides/web-dotnet-core-blazor-wasm/README.mdx
  packages/console/src/assets/docs/guides/web-dotnet-core-mvc/README.mdx
  packages/console/src/assets/docs/guides/web-dotnet-core-mvc/fragments/_add-authentication.mdx
  packages/console/src/assets/docs/guides/web-dotnet-core-mvc/fragments/_configure-redirect-uris.mdx
  packages/console/src/assets/docs/guides/web-dotnet-core-mvc/fragments/_display-user-information.md
  packages/console/src/assets/docs/guides/web-dotnet-core-mvc/fragments/_installation.md
  packages/console/src/assets/docs/guides/web-dotnet-core-mvc/fragments/_sign-in-and-sign-out-flows.mdx
  packages/console/src/assets/docs/guides/web-dotnet-core/README.mdx
  packages/console/src/assets/docs/guides/web-java-spring-boot/README.mdx
  packages/console/src/assets/docs/guides/web-java-spring-boot/index.ts
  packages/console/src/assets/docs/guides/web-next/index.ts
  packages/console/src/components/Guide/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
  packages/console/src/pages/ApplicationDetails/components/AppGuide/index.tsx
Labels: enhancement, size/xl

#6178 refactor(console): add chrome extension guide
  .changeset/long-worms-refuse.md
  packages/console/src/assets/docs/guides/index.tsx
  packages/console/src/assets/docs/guides/spa-chrome-extension/README.mdx
  packages/console/src/assets/docs/guides/spa-chrome-extension/config.json
  packages/console/src/assets/docs/guides/spa-chrome-extension/extension-popup.webp
  packages/console/src/assets/docs/guides/spa-chrome-extension/index.ts
  packages/console/src/assets/docs/guides/spa-chrome-extension/logo.svg
  packages/console/src/mdx-components/UriInputField/index.tsx
  packages/console/src/types/guide.ts
Labels: enhancement, size/l

#6150 feat(core,schemas): implement social verification experience API endpoints
  packages/connectors/connector-mock-social/src/index.ts
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/classes/verifications/index.ts
  packages/core/src/routes/experience/classes/verifications/social-verification.ts
  packages/core/src/routes/experience/index.ts
  packages/core/src/routes/experience/verification-routes/social-verification.ts
  packages/core/src/routes/interaction/types/index.ts
  packages/integration-tests/src/client/experience/index.ts
  packages/integration-tests/src/helpers/experience/social-verification.ts
  packages/integration-tests/src/tests/api/experience-api/verifications/social-verification.test.ts
  packages/schemas/src/types/interactions.ts
Labels: feature, size/xl

#6190 refactor: correct phrases and translate some untranslate phrases for zh-cn
  packages/phrases-experience/src/locales/zh-cn/action.ts
  packages/phrases-experience/src/locales/zh-cn/description.ts
  packages/phrases-experience/src/locales/zh-cn/user-scopes.ts
Labels: enhancement, size/s

#6164 refactor(experience): cache user input identifier for a better sign-in experience
  packages/experience/src/Providers/UserInteractionContextProvider/UserInteractionContext.tsx
  packages/experience/src/Providers/UserInteractionContextProvider/index.tsx
  packages/experience/src/components/InputFields/SmartInputField/use-smart-input-field.ts
  packages/experience/src/containers/ForgotPasswordLink/index.tsx
  packages/experience/src/containers/VerificationCode/PasswordSignInLink.tsx
  packages/experience/src/containers/VerificationCode/index.tsx
  packages/experience/src/hooks/use-check-single-sign-on.ts
  packages/experience/src/hooks/use-global-redirect-to.ts
  packages/experience/src/hooks/use-send-verification-code.ts
  packages/experience/src/hooks/use-session-storages.ts
  packages/experience/src/pages/Continue/SetEmailOrPhone/index.tsx
  packages/experience/src/pages/Continue/SetUsername/index.tsx
  packages/experience/src/pages/ForgotPassword/ForgotPasswordForm/index.test.tsx
  packages/experience/src/pages/ForgotPassword/ForgotPasswordForm/index.tsx
  packages/experience/src/pages/ForgotPassword/index.test.tsx
  packages/experience/src/pages/ForgotPassword/index.tsx
  packages/experience/src/pages/Register/IdentifierRegisterForm/index.test.tsx
  packages/experience/src/pages/Register/IdentifierRegisterForm/index.tsx
  packages/experience/src/pages/ResetPassword/index.tsx
  packages/experience/src/pages/SignIn/IdentifierSignInForm/index.test.tsx
  packages/experience/src/pages/SignIn/IdentifierSignInForm/index.tsx
  packages/experience/src/pages/SignIn/IdentifierSignInForm/use-on-submit.ts
  packages/experience/src/pages/SignIn/PasswordSignInForm/index.tsx
  packages/experience/src/pages/SignInPassword/PasswordForm/index.test.tsx
  packages/experience/src/pages/SignInPassword/PasswordForm/index.tsx
  packages/experience/src/pages/SignInPassword/index.test.tsx
  packages/experience/src/pages/SignInPassword/index.tsx
  packages/experience/src/pages/VerificationCode/index.test.tsx
  packages/experience/src/pages/VerificationCode/index.tsx
  packages/experience/src/types/guard.ts
Labels: enhancement, size/xl

#6165 refactor(experience): add hidden identifier input for browser password manager
  packages/experience/src/containers/SetPassword/HiddenIdentifierInput.tsx
  packages/experience/src/containers/SetPassword/Lite.tsx
  packages/experience/src/containers/SetPassword/SetPassword.tsx
  packages/experience/src/types/guard.ts
Labels: enhancement, size/s

#6154 refactor(core): refactor identifyUser method
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/classes/utils.ts
  packages/core/src/routes/experience/classes/verifications/code-verification.ts
  packages/core/src/routes/experience/classes/verifications/index.ts
  packages/core/src/routes/experience/classes/verifications/password-verification.ts
  packages/core/src/routes/experience/classes/verifications/social-verification.ts
  packages/core/src/routes/experience/classes/verifications/verification-record.ts
  packages/core/src/routes/experience/index.ts
  packages/core/src/routes/experience/utils.ts
Labels: enhancement, size/l

#6104 refactor(experience,phrases): update phrases for link identities page
  packages/experience/src/containers/SocialLinkAccount/index.module.scss
  packages/experience/src/containers/SocialLinkAccount/index.test.tsx
  packages/experience/src/containers/SocialLinkAccount/index.tsx
  packages/experience/src/pages/SocialLinkAccount/index.test.tsx
  packages/integration-tests/src/tests/experience/automatic-account-linking.test.ts
  packages/integration-tests/src/tests/experience/mfa/totp/social-flow.test.ts
  packages/phrases-experience/src/locales/de/action.ts
  packages/phrases-experience/src/locales/de/description.ts
  packages/phrases-experience/src/locales/en/action.ts
  packages/phrases-experience/src/locales/en/description.ts
  packages/phrases-experience/src/locales/es/action.ts
  packages/phrases-experience/src/locales/es/description.ts
  packages/phrases-experience/src/locales/fr/action.ts
  packages/phrases-experience/src/locales/fr/description.ts
  packages/phrases-experience/src/locales/it/action.ts
  packages/phrases-experience/src/locales/it/description.ts
  packages/phrases-experience/src/locales/ja/action.ts
  packages/phrases-experience/src/locales/ja/description.ts
  packages/phrases-experience/src/locales/ko/action.ts
  packages/phrases-experience/src/locales/ko/description.ts
  packages/phrases-experience/src/locales/pl-pl/action.ts
  packages/phrases-experience/src/locales/pl-pl/description.ts
  packages/phrases-experience/src/locales/pt-br/action.ts
  packages/phrases-experience/src/locales/pt-br/description.ts
  packages/phrases-experience/src/locales/pt-pt/action.ts
  packages/phrases-experience/src/locales/pt-pt/description.ts
  packages/phrases-experience/src/locales/ru/action.ts
  packages/phrases-experience/src/locales/ru/description.ts
  packages/phrases-experience/src/locales/tr-tr/action.ts
  packages/phrases-experience/src/locales/tr-tr/description.ts
  packages/phrases-experience/src/locales/zh-cn/action.ts
  packages/phrases-experience/src/locales/zh-cn/description.ts
  packages/phrases-experience/src/locales/zh-hk/action.ts
  packages/phrases-experience/src/locales/zh-hk/description.ts
  packages/phrases-experience/src/locales/zh-tw/action.ts
  packages/phrases-experience/src/locales/zh-tw/description.ts
Labels: enhancement, size/m

#6179 refactor: remove unused patches
  packages/console/package.json
  packages/experience/package.json
  packages/experience/src/components/InputFields/SmartInputField/CountryCodeSelector/CountryCodeDropdown/index.test.tsx
  packages/experience/src/hooks/use-send-verification-code.ts
  packages/experience/src/jest.setup.ts
  packages/experience/src/pages/DirectSignIn/index.test.tsx
  packages/experience/src/pages/ForgotPassword/ForgotPasswordForm/index.test.tsx
  packages/experience/src/pages/SocialLanding/index.test.tsx
  packages/integration-tests/jest.setup.js
  packages/integration-tests/package.json
  pnpm-lock.yaml
Labels: enhancement, size/s

#6192 feat: organization logo
  .changeset/dull-goats-help.md
  .changeset/lazy-geese-bow.md
  packages/connectors/connector-mock-social/src/index.ts
  packages/console/src/hooks/use-user-assets-service.ts
  packages/console/src/pages/OrganizationDetails/Settings/Branding.tsx
  packages/console/src/pages/OrganizationDetails/Settings/index.module.scss
  packages/console/src/pages/OrganizationDetails/Settings/index.tsx
  packages/console/src/pages/OrganizationDetails/Settings/utils.ts
  packages/core/src/libraries/sign-in-experience/index.test.ts
  packages/core/src/libraries/sign-in-experience/index.ts
  packages/core/src/oidc/utils.ts
  packages/core/src/routes/well-known.ts
  packages/demo-app/src/App.tsx
  packages/demo-app/src/DevPanel.tsx
  packages/demo-app/src/utils.ts
  packages/experience/src/apis/settings.ts
  packages/experience/src/utils/search-parameters.ts
  packages/integration-tests/src/constants.ts
  packages/integration-tests/src/tests/api/admin-user.test.ts
  packages/integration-tests/src/tests/api/sign-in-experience.test.ts
  packages/integration-tests/src/tests/experience/overrides.test.ts
  packages/phrases/src/locales/en/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/index.ts
  packages/schemas/alterations/next-1720253939-add-organization-branding.ts
  packages/schemas/src/consts/oidc.ts
  packages/schemas/src/foundations/jsonb-types/sign-in-experience.ts
  packages/schemas/tables/application_sign_in_experiences.sql
  packages/schemas/tables/organizations.sql
Labels: feature, size/l

#6193 refactor(core, experience): remove `no_cache` param
  packages/core/src/oidc/utils.test.ts
  packages/core/src/oidc/utils.ts
  packages/experience/src/apis/settings.ts
  packages/experience/src/index.html
  packages/experience/src/utils/search-parameters.ts
Labels: enhancement, size/s

#6171 feat(core): actor token
  packages/core/src/oidc/extra-token-claims.ts
  packages/core/src/oidc/grants/index.ts
  packages/core/src/oidc/grants/token-exchange/actor-token.test.ts
  packages/core/src/oidc/grants/token-exchange/actor-token.ts
  packages/core/src/oidc/grants/token-exchange/index.test.ts
  packages/core/src/oidc/grants/token-exchange/index.ts
  packages/core/src/oidc/grants/token-exchange/types.ts
  packages/core/src/oidc/init.ts
  packages/integration-tests/src/tests/api/oidc/token-exchange.test.ts
Labels: feature, size/l

#6184 feat(console,schemas): add grant context to custom jwt
  packages/console/scripts/generate-jwt-customizer-type-definition.ts
  packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/GuideCard/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/utils/config.tsx
  packages/console/src/pages/CustomizeJwtDetails/utils/type-definitions.ts
  packages/phrases/src/locales/en/translation/admin-console/jwt-claims.ts
  packages/schemas/src/types/logto-config/jwt-customizer.ts
Labels: feature, size/s

#6185 feat(core): add subject token context to jwt customizer
  packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/utils/config.tsx
  packages/core/src/oidc/extra-token-claims.ts
  packages/integration-tests/src/__mocks__/jwt-customizer.ts
  packages/integration-tests/src/tests/api/oidc/token-exchange.test.ts
Labels: feature, size/m

#6186 refactor(core): refactor the sso interaction handlers
  packages/core/src/routes/interaction/types/index.ts
  packages/core/src/routes/interaction/utils/single-sign-on-session.ts
  packages/core/src/routes/interaction/utils/single-sign-on.test.ts
  packages/core/src/routes/interaction/utils/single-sign-on.ts
  packages/core/src/sso/types/session.ts
Labels: enhancement, size/m

#6198 feat(core): implement enterprise sso verification flow
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/classes/verifications/enterprise-sso-verification.ts
  packages/core/src/routes/experience/classes/verifications/index.ts
  packages/core/src/routes/experience/classes/verifications/social-verification.ts
  packages/core/src/routes/experience/index.ts
  packages/core/src/routes/experience/verification-routes/enterprise-sso-verification.ts
  packages/core/src/routes/interaction/utils/single-sign-on.ts
  packages/integration-tests/src/client/experience/index.ts
  packages/integration-tests/src/helpers/experience/enterprise-sso-verification.ts
  packages/integration-tests/src/tests/api/experience-api/verifications/enterprise-sso-verification.test.ts
Labels: feature, size/xl

#6200 refactor(experience): add label for input field
  packages/experience/src/components/InputFields/InputField/NotchedBorder/index.module.scss
  packages/experience/src/components/InputFields/InputField/NotchedBorder/index.tsx
  packages/experience/src/components/InputFields/InputField/index.module.scss
  packages/experience/src/components/InputFields/InputField/index.tsx
  packages/experience/src/components/InputFields/SmartInputField/CountryCodeSelector/CountryCodeDropdown/index.module.scss
  packages/experience/src/components/InputFields/SmartInputField/CountryCodeSelector/CountryCodeDropdown/index.tsx
  packages/experience/src/components/InputFields/SmartInputField/CountryCodeSelector/index.module.scss
  packages/experience/src/components/InputFields/SmartInputField/CountryCodeSelector/index.tsx
  packages/experience/src/components/InputFields/SmartInputField/index.tsx
  packages/experience/src/components/InputFields/SmartInputField/utils.test.ts
  packages/experience/src/components/InputFields/SmartInputField/utils.ts
  packages/experience/src/containers/SetPassword/Lite.tsx
  packages/experience/src/containers/SetPassword/SetPassword.tsx
  packages/experience/src/pages/MfaVerification/BackupCodeVerification/index.tsx
  packages/experience/src/pages/SignIn/PasswordSignInForm/index.tsx
  packages/experience/src/pages/SignInPassword/PasswordForm/index.tsx
Labels: enhancement, size/l

#6205 feat(core): add quota guard for subject tokens
  packages/core/package.json
  packages/core/src/libraries/quota.ts
  packages/core/src/routes/security/index.ts
  pnpm-lock.yaml
Labels: feature, size/s

#6211 style(experience): update floating label position
  packages/experience/src/components/InputFields/InputField/NotchedBorder/index.module.scss
Labels: size/xs

#6196 feat: support app-level branding
  .vscode/settings.json
  packages/console/src/ds-components/Checkbox/Checkbox/index.module.scss
  packages/console/src/ds-components/ColorPicker/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/LogoUploader.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/index.module.scss
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
  packages/core/src/caches/well-known.ts
  packages/core/src/libraries/sign-in-experience/index.test.ts
  packages/core/src/libraries/sign-in-experience/index.ts
  packages/core/src/oidc/init.ts
  packages/core/src/oidc/utils.test.ts
  packages/core/src/oidc/utils.ts
  packages/core/src/routes/applications/application-sign-in-experience.ts
  packages/core/src/routes/well-known.ts
  packages/core/src/tenants/Libraries.ts
  packages/demo-app/src/App.tsx
  packages/demo-app/src/DevPanel.tsx
  packages/demo-app/src/utils.ts
  packages/experience/src/apis/settings.ts
  packages/experience/src/components/LogtoSignature/index.module.scss
  packages/experience/src/index.html
  packages/experience/src/utils/search-parameters.ts
  packages/integration-tests/src/tests/api/application/application-sign-in-experience.test.ts
  packages/integration-tests/src/tests/experience/overrides.test.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/index.ts
  packages/schemas/alterations/next-1720345784-add-color-to-app-sie.ts
  packages/schemas/src/foundations/jsonb-types/sign-in-experience.ts
  packages/schemas/tables/application_sign_in_experiences.sql
Labels: feature, size/xl

#6206 refactor(console): reorg logo uploads
  packages/console/src/components/FormCard/Skeleton/index.module.scss
  packages/console/src/components/FormCard/Skeleton/index.tsx
  packages/console/src/components/ImageInputs/LogoAndFavicon.tsx
  packages/console/src/components/ImageInputs/index.module.scss
  packages/console/src/components/ImageInputs/index.tsx
  packages/console/src/ds-components/FormField/Skeleton.module.scss
  packages/console/src/ds-components/FormField/Skeleton.tsx
  packages/console/src/ds-components/Uploader/ImageUploader/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/LogoUploader.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/utils.ts
  packages/console/src/pages/OrganizationDetails/Settings/Branding.tsx
  packages/console/src/pages/OrganizationDetails/Settings/index.module.scss
  packages/console/src/pages/OrganizationDetails/Settings/index.tsx
  packages/console/src/pages/OrganizationDetails/Settings/utils.ts
  packages/console/src/pages/SignInExperience/PageContent/Branding/BrandingForm/LogoAndFaviconUploader/index.module.scss
  packages/console/src/pages/SignInExperience/PageContent/Branding/BrandingForm/LogoAndFaviconUploader/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/Branding/BrandingForm/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/utils/parser.ts
  packages/console/src/utils/object.ts
  packages/integration-tests/src/tests/console/sign-in-experience/sign-in-preview.test.ts
  packages/phrases/src/locales/de/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/es/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/it/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/sign-in-exp/index.ts
  packages/schemas/src/foundations/jsonb-types/sign-in-experience.ts
Labels: enhancement, size/xl

#6209 refactor(console): update all logo uploaders
  packages/connectors/connector-logto-email/src/constant.ts
  packages/console/src/components/ConnectorForm/BasicForm/index.tsx
  packages/console/src/components/ImageInputs/index.tsx
  packages/console/src/consts/external-links.ts
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/utils.ts
  packages/console/src/pages/ConnectorDetails/ConnectorContent/EmailServiceConnectorForm/index.tsx
  packages/console/src/pages/ConnectorDetails/ConnectorContent/index.tsx
  packages/console/src/pages/OrganizationDetails/Settings/index.tsx
  packages/console/src/pages/OrganizationDetails/Settings/utils.ts
  packages/console/src/pages/SignInExperience/PageContent/utils/parser.ts
  packages/console/src/types/sign-in-experience.ts
  packages/console/src/utils/connector-form.ts
  packages/integration-tests/src/tests/console/sign-in-experience/sign-in-preview.test.ts
  packages/phrases/src/locales/de/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/de/translation/admin-console/connectors.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/cloud.ts
  packages/phrases/src/locales/en/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/en/translation/admin-console/connectors.ts
  packages/phrases/src/locales/en/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/es/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/es/translation/admin-console/connectors.ts
  packages/phrases/src/locales/fr/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/it/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/it/translation/admin-console/connectors.ts
  packages/phrases/src/locales/ja/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/connectors.ts
  packages/phrases/src/locales/ko/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/connectors.ts
  packages/phrases/src/locales/ru/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/connectors.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/connectors.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/connectors.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/connector-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/connectors.ts
Labels: enhancement, size/xl

#6210 refactor(experience): show dark favicon
  packages/experience/src/Providers/AppBoundary/AppMeta.tsx
  packages/integration-tests/src/tests/experience/overrides.test.ts
Labels: enhancement, size/s

#6201 feat(core): implement TOTP verification routes
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/classes/verifications/index.ts
  packages/core/src/routes/experience/classes/verifications/totp-verification.ts
  packages/core/src/routes/experience/index.ts
  packages/core/src/routes/experience/verification-routes/totp-verification.ts
  packages/core/src/routes/interaction/additional.ts
  packages/integration-tests/src/client/experience/index.ts
  packages/integration-tests/src/helpers/experience/totp-verification.ts
  packages/integration-tests/src/tests/api/experience-api/verifications/totp-verification.test.ts
  packages/integration-tests/src/tests/api/interaction/mfa/totp.test.ts
  packages/phrases/src/locales/en/errors/session.ts
  packages/schemas/src/types/interactions.ts
Labels: feature, size/xl

#6207 feat(core,schemas): implement backup codes verification
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/classes/verifications/backup-code-verification.ts
  packages/core/src/routes/experience/classes/verifications/index.ts
  packages/core/src/routes/experience/index.ts
  packages/core/src/routes/experience/verification-routes/backup-code-verification.ts
  packages/integration-tests/src/client/experience/index.ts
  packages/integration-tests/src/helpers/experience/index.ts
  packages/integration-tests/src/tests/api/experience-api/verifications/backup-code-verification.test.ts
  packages/integration-tests/src/tests/api/experience-api/verifications/totp-verification.test.ts
  packages/schemas/src/types/interactions.ts
Labels: feature, size/l

#6221 fix(experience): use forgot password identifier in related flow
  packages/experience/src/pages/VerificationCode/index.tsx
Labels: bugfix, size/s

#6199 feat(core): handle dpop and client certificate for token exchange
  packages/core/src/oidc/grants/client-credentials.ts
  packages/core/src/oidc/grants/refresh-token.ts
  packages/core/src/oidc/grants/token-exchange/index.ts
  packages/core/src/oidc/grants/utils.ts
Labels: feature, size/m

#6222 refactor: fix experience branding fallback
  packages/experience/src/Providers/AppBoundary/AppMeta.tsx
  packages/integration-tests/src/tests/experience/overrides.test.ts
  packages/integration-tests/src/ui-helpers/expect-experience.ts
Labels: enhancement, size/m

#6223 refactor: fix third-party app experience branding
  packages/console/src/components/ImageInputs/index.tsx
  packages/core/src/libraries/sign-in-experience/index.ts
  packages/core/src/queries/application-sign-in-experience.ts
  packages/integration-tests/src/tests/experience/overrides.test.ts
Labels: enhancement, size/s

#6208 refactor(core): refactor organizations in grants
  packages/core/src/oidc/grants/client-credentials.ts
  packages/core/src/oidc/grants/refresh-token.test.ts
  packages/core/src/oidc/grants/refresh-token.ts
  packages/core/src/oidc/grants/token-exchange/index.ts
  packages/core/src/oidc/grants/utils.ts
  packages/integration-tests/src/tests/api/oidc/refresh-token-grant.test.ts
Labels: enhancement, size/l

#6226 refactor(console): improve branding experience
  packages/console/src/components/ConnectorForm/BasicForm/index.tsx
  packages/console/src/components/ImageInputs/LogoAndFavicon.tsx
  packages/console/src/components/ImageInputs/index.module.scss
  packages/console/src/ds-components/Tip/TipBubble/utils.ts
  packages/console/src/ds-components/Uploader/FileUploader/index.module.scss
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/index.module.scss
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
  packages/console/src/pages/OrganizationDetails/Settings/JitSettings.tsx
  packages/console/src/pages/OrganizationDetails/Settings/index.module.scss
  packages/console/src/pages/OrganizationDetails/Settings/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-table.ts
  packages/schemas/src/seeds/sign-in-experience.ts
Labels: enhancement, size/m

#6212 feat(core,schemas): introduce new PUT experience API
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/index.ts
  packages/core/src/routes/experience/middleware/koa-experience-interaction.ts
  packages/integration-tests/src/client/experience/index.ts
  packages/integration-tests/src/helpers/experience/index.ts
  packages/integration-tests/src/tests/api/experience-api/interaction.test.ts
  packages/schemas/src/types/interactions.ts
Labels: feature, size/m

#6229 refactor: experience ssr
  .changeset/shy-baboons-occur.md
  packages/core/src/middleware/koa-experience-ssr.test.ts
  packages/core/src/middleware/koa-experience-ssr.ts
  packages/core/src/middleware/koa-serve-static.ts
  packages/core/src/oidc/init.ts
  packages/core/src/oidc/utils.ts
  packages/core/src/routes/well-known.ts
  packages/core/src/tenants/Tenant.ts
  packages/core/src/utils/i18n.ts
  packages/experience/src/i18n/utils.ts
  packages/experience/src/include.d/global.d.ts
  packages/experience/src/index.html
  packages/experience/src/jest.setup.ts
  packages/experience/src/utils/search-parameters.ts
  packages/experience/src/utils/sign-in-experience.ts
  packages/integration-tests/src/include.d/global.d.ts
  packages/integration-tests/src/tests/experience/server-side-rendering.test.ts
  packages/schemas/src/types/cookie.ts
  packages/schemas/src/types/index.ts
  packages/schemas/src/types/sign-in-experience.ts
  packages/schemas/src/types/ssr.ts
Labels: enhancement, size/xl

#6232 feat(experience): support loading state for buttons
  packages/experience/src/assets/icons/loading-ring.svg
  packages/experience/src/components/Button/RotatingRingIcon.module.scss
  packages/experience/src/components/Button/RotatingRingIcon.tsx
  packages/experience/src/components/Button/SocialLinkButton.module.scss
  packages/experience/src/components/Button/SocialLinkButton.tsx
  packages/experience/src/components/Button/index.module.scss
  packages/experience/src/components/Button/index.tsx
  packages/experience/src/scss/_colors.scss
Labels: feature, size/m

#6239 chore: add changesets
  .changeset/polite-plums-tease.md
  .changeset/swift-stingrays-tap.md
Labels: chore, size/s

#6215 feat(core,schemas): implement the sie settings guard
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/classes/utils.ts
  packages/core/src/routes/experience/classes/validators/sign-in-experience-validator.test.ts
  packages/core/src/routes/experience/classes/validators/sign-in-experience-validator.ts
  packages/core/src/routes/experience/classes/verifications/code-verification.ts
  packages/core/src/routes/experience/index.ts
  packages/core/src/routes/experience/verification-routes/backup-code-verification.ts
  packages/core/src/routes/experience/verification-routes/totp-verification.ts
  packages/core/src/routes/experience/verification-routes/verification-code.ts
  packages/integration-tests/src/helpers/experience/index.ts
  packages/integration-tests/src/tests/api/experience-api/interaction.test.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/password.test.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/verification-code.test.ts
  packages/integration-tests/src/tests/api/experience-api/verifications/backup-code-verification.test.ts
  packages/integration-tests/src/tests/api/experience-api/verifications/password-verification.test.ts
  packages/integration-tests/src/tests/api/experience-api/verifications/social-verification.test.ts
  packages/integration-tests/src/tests/api/experience-api/verifications/totp-verification.test.ts
  packages/integration-tests/src/tests/api/experience-api/verifications/verification-code.test.ts
  packages/phrases/src/locales/en/errors/session.ts
  packages/schemas/src/types/interactions.ts
Labels: feature, size/xl

#6240 chore(deps): upgrade packages
  packages/cli/package.json
  packages/connectors/connector-alipay-native/package.json
  packages/connectors/connector-alipay-web/package.json
  packages/connectors/connector-aliyun-dm/package.json
  packages/connectors/connector-aliyun-sms/package.json
  packages/connectors/connector-apple/package.json
  packages/connectors/connector-aws-ses/package.json
  packages/connectors/connector-azuread/package.json
  packages/connectors/connector-dingtalk-web/package.json
  packages/connectors/connector-discord/package.json
  packages/connectors/connector-facebook/package.json
  packages/connectors/connector-feishu-web/package.json
  packages/connectors/connector-github/package.json
  packages/connectors/connector-google/package.json
  packages/connectors/connector-kakao/package.json
  packages/connectors/connector-logto-email/package.json
  packages/connectors/connector-logto-sms/package.json
  packages/connectors/connector-logto-social-demo/package.json
  packages/connectors/connector-mailgun/package.json
  packages/connectors/connector-mock-email-alternative/package.json
  packages/connectors/connector-mock-email/package.json
  packages/connectors/connector-mock-sms/package.json
  packages/connectors/connector-mock-social/package.json
  packages/connectors/connector-naver/package.json
  packages/connectors/connector-oauth2/package.json
  packages/connectors/connector-oidc/package.json
  packages/connectors/connector-saml/package.json
  packages/connectors/connector-sendgrid-email/package.json
  packages/connectors/connector-smsaero/package.json
  packages/connectors/connector-smtp/package.json
  packages/connectors/connector-tencent-sms/package.json
  packages/connectors/connector-twilio-sms/package.json
  packages/connectors/connector-wechat-native/package.json
  packages/connectors/connector-wechat-web/package.json
  packages/connectors/connector-wecom/package.json
  packages/core/package.json
  packages/demo-app/package.json
  packages/experience/package.json
  packages/integration-tests/package.json
  packages/schemas/package.json
  packages/shared/package.json
  pnpm-lock.yaml
Labels: chore, size/m

#6241 chore(deps): upgrade zod
  packages/cli/package.json
  packages/connectors/connector-alipay-native/package.json
  packages/connectors/connector-alipay-web/package.json
  packages/connectors/connector-aliyun-dm/package.json
  packages/connectors/connector-aliyun-sms/package.json
  packages/connectors/connector-apple/package.json
  packages/connectors/connector-aws-ses/package.json
  packages/connectors/connector-azuread/package.json
  packages/connectors/connector-dingtalk-web/package.json
  packages/connectors/connector-discord/package.json
  packages/connectors/connector-facebook/package.json
  packages/connectors/connector-feishu-web/package.json
  packages/connectors/connector-github/package.json
  packages/connectors/connector-google/package.json
  packages/connectors/connector-huggingface/package.json
  packages/connectors/connector-kakao/package.json
  packages/connectors/connector-logto-email/package.json
  packages/connectors/connector-logto-sms/package.json
  packages/connectors/connector-logto-social-demo/package.json
  packages/connectors/connector-mailgun/package.json
  packages/connectors/connector-mock-email-alternative/package.json
  packages/connectors/connector-mock-email/package.json
  packages/connectors/connector-mock-sms/package.json
  packages/connectors/connector-mock-social/package.json
  packages/connectors/connector-naver/package.json
  packages/connectors/connector-oauth2/package.json
  packages/connectors/connector-oidc/package.json
  packages/connectors/connector-saml/package.json
  packages/connectors/connector-sendgrid-email/package.json
  packages/connectors/connector-smsaero/package.json
  packages/connectors/connector-smtp/package.json
  packages/connectors/connector-tencent-sms/package.json
  packages/connectors/connector-twilio-sms/package.json
  packages/connectors/connector-wechat-native/package.json
  packages/connectors/connector-wechat-web/package.json
  packages/connectors/connector-wecom/package.json
  packages/console/package.json
  packages/core/package.json
  packages/core/src/oidc/utils.ts
  packages/core/src/routes/logto-config/jwt-customizer.ts
  packages/core/src/utils/SchemaRouter.ts
  packages/demo-app/package.json
  packages/experience/package.json
  packages/integration-tests/package.json
  packages/phrases-experience/package.json
  packages/phrases/package.json
  packages/schemas/package.json
  packages/toolkit/connector-kit/package.json
  packages/toolkit/core-kit/package.json
  packages/toolkit/language-kit/package.json
  pnpm-lock.yaml
Labels: chore, size/m

#6235 refactor(core): remove subject token api prefix
  packages/core/src/routes/init.ts
  packages/core/src/routes/subject-token.openapi.json
  packages/core/src/routes/subject-token.ts
  packages/core/src/routes/swagger/index.ts
  packages/core/src/routes/swagger/utils/operation-id.ts
  packages/integration-tests/src/api/subject-token.ts
Labels: enhancement, size/s

#6224 feat(core): add get available sso connectors endpoint
  packages/core/src/routes/experience/classes/validators/sign-in-experience-validator.ts
  packages/core/src/routes/experience/verification-routes/enterprise-sso-verification.ts
  packages/integration-tests/src/client/experience/index.ts
  packages/integration-tests/src/tests/api/experience-api/verifications/enterprise-sso-verification.test.ts
Labels: feature, size/m

#6237 feat(core,schemas): implement the register flow
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/classes/utils.ts
  packages/core/src/routes/experience/classes/validators/profile-validator.ts
  packages/core/src/routes/experience/classes/verifications/code-verification.ts
  packages/core/src/routes/experience/classes/verifications/enterprise-sso-verification.ts
  packages/core/src/routes/experience/classes/verifications/password-verification.ts
  packages/core/src/routes/experience/classes/verifications/social-verification.ts
  packages/core/src/routes/experience/classes/verifications/verification-record.ts
  packages/core/src/routes/experience/index.ts
  packages/core/src/routes/experience/types.ts
Labels: feature, size/xl

#6118 feat(core,schemas): add post custom ui assets api
  packages/core/package.json
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/queries/sign-in-experience.test.ts
  packages/core/src/routes-me/user-assets.ts
  packages/core/src/routes/sign-in-experience/custom-ui-assets/index.openapi.json
  packages/core/src/routes/sign-in-experience/custom-ui-assets/index.test.ts
  packages/core/src/routes/sign-in-experience/custom-ui-assets/index.ts
  packages/core/src/routes/sign-in-experience/index.ts
  packages/core/src/routes/swagger/index.ts
  packages/core/src/routes/swagger/utils/operation-id.ts
  packages/core/src/routes/user-assets.ts
  packages/core/src/tenants/SystemContext.ts
  packages/core/src/utils/file.test.ts
  packages/core/src/utils/file.ts
  packages/core/src/utils/storage/azure-storage.ts
  packages/core/src/utils/storage/consts.ts
  packages/experience/src/__mocks__/logto.tsx
  packages/schemas/alterations/next-1720505152-update-custom-ui-assets.ts
  packages/schemas/src/foundations/jsonb-types/sign-in-experience.ts
  packages/schemas/src/seeds/sign-in-experience.ts
  packages/schemas/src/types/system.ts
  packages/schemas/src/types/user-assets.ts
  packages/schemas/tables/sign_in_experiences.sql
  pnpm-lock.yaml
Labels: feature, size/l

#6249 feat(core,schemas): implement the username password registration flow
  packages/core/src/libraries/user.utils.ts
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/classes/utils.test.ts
  packages/core/src/routes/experience/classes/utils.ts
  packages/core/src/routes/experience/classes/validators/profile-validator.ts
  packages/core/src/routes/experience/classes/validators/sign-in-experience-validator.test.ts
  packages/core/src/routes/experience/classes/validators/sign-in-experience-validator.ts
  packages/core/src/routes/experience/classes/verifications/code-verification.ts
  packages/core/src/routes/experience/classes/verifications/index.ts
  packages/core/src/routes/experience/classes/verifications/new-password-identity-verification.ts
  packages/core/src/routes/experience/classes/verifications/password-verification.ts
  packages/core/src/routes/experience/index.ts
  packages/core/src/routes/experience/verification-routes/new-password-identity-verification.ts
  packages/integration-tests/src/client/experience/index.ts
  packages/integration-tests/src/helpers/experience/index.ts
  packages/integration-tests/src/tests/api/experience-api/register-interaction/username-password.test.ts
  packages/integration-tests/src/tests/api/experience-api/verifications/new-password-identity-verification.test.ts
  packages/schemas/src/types/interactions.ts
Labels: feature, size/xl

#6255 fix(experience): correct active state for input field
  packages/experience/src/components/InputFields/InputField/index.tsx
Labels: bugfix, size/s

#6234 refactor(console): use button loading in experience flow if possible
  packages/experience/src/Providers/LoadingLayerProvider/index.tsx
  packages/experience/src/components/LoadingLayer/index.module.scss
  packages/experience/src/components/LoadingLayer/index.tsx
  packages/experience/src/components/LoadingMask/index.module.scss
  packages/experience/src/components/LoadingMask/index.tsx
  packages/experience/src/containers/SetPassword/Lite.tsx
  packages/experience/src/containers/SetPassword/SetPassword.tsx
  packages/experience/src/containers/SetPassword/index.tsx
  packages/experience/src/containers/TotpCodeVerification/index.module.scss
  packages/experience/src/containers/TotpCodeVerification/index.tsx
  packages/experience/src/containers/TotpCodeVerification/use-totp-code-verification.ts
  packages/experience/src/containers/VerificationCode/index.module.scss
  packages/experience/src/containers/VerificationCode/index.tsx
  packages/experience/src/pages/Consent/index.tsx
  packages/experience/src/pages/Continue/IdentifierProfileForm/index.tsx
  packages/experience/src/pages/ForgotPassword/ForgotPasswordForm/index.tsx
  packages/experience/src/pages/MfaBinding/BackupCodeBinding/index.tsx
  packages/experience/src/pages/MfaBinding/WebAuthnBinding/index.tsx
  packages/experience/src/pages/MfaVerification/BackupCodeVerification/index.tsx
  packages/experience/src/pages/MfaVerification/WebAuthnVerification/index.tsx
  packages/experience/src/pages/Register/IdentifierRegisterForm/index.tsx
  packages/experience/src/pages/SignIn/IdentifierSignInForm/index.tsx
  packages/experience/src/pages/SignIn/PasswordSignInForm/index.tsx
  packages/experience/src/pages/SignInPassword/PasswordForm/index.tsx
  packages/experience/src/pages/SingleSignOnEmail/index.tsx
Labels: enhancement, size/l

#6236 refactor(experience): support and apply modal loading state
  packages/experience/src/Providers/ConfirmModalProvider/index.tsx
  packages/experience/src/Providers/ConfirmModalProvider/indext.test.tsx
  packages/experience/src/components/ConfirmModal/AcModal.tsx
  packages/experience/src/components/ConfirmModal/MobileModal.tsx
  packages/experience/src/components/ConfirmModal/type.ts
  packages/experience/src/containers/VerificationCode/use-identifier-error-alert.ts
  packages/experience/src/containers/VerificationCode/use-link-social-confirm-modal.ts
  packages/experience/src/containers/VerificationCode/use-register-flow-code-verification.ts
  packages/experience/src/containers/VerificationCode/use-sign-in-flow-code-verification.ts
  packages/experience/src/hooks/use-confirm-modal.ts
  packages/experience/src/hooks/use-terms.ts
  packages/experience/src/pages/Continue/SetPassword/index.tsx
  packages/experience/src/pages/RegisterPassword/index.tsx
  packages/experience/src/pages/ResetPassword/index.tsx
Labels: enhancement, size/xl

#6253 feat(core): add the new user provision
  packages/core/src/routes/experience/classes/experience-interaction.test.ts
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/classes/provision-library.ts
  packages/integration-tests/src/tests/api/experience-api/register-interaction/organization-jti.test.ts
  packages/integration-tests/src/tests/api/interaction/organization-jit.test.ts
Labels: feature, size/xl

#6256 feat(connector): enable custom headers for SMTP connector
  .changeset/slow-boxes-greet.md
  packages/connectors/connector-smtp/src/constant.ts
  packages/connectors/connector-smtp/src/index.test.ts
  packages/connectors/connector-smtp/src/index.ts
  packages/connectors/connector-smtp/src/mock.ts
  packages/connectors/connector-smtp/src/types.ts
Labels: feature, size/s

#6254 fix(console): fix Google connector `scope` field can not be unset bug
  .changeset/cool-otters-unite.md
  packages/console/src/pages/ConnectorDetails/ConnectorContent/index.tsx
  packages/console/src/utils/connector-form.ts
Labels: bugfix, size/s

#6260 style(experience): improve input filed style
  packages/experience/src/components/InputFields/InputField/NotchedBorder/index.module.scss
  packages/experience/src/components/InputFields/InputField/index.module.scss
Labels: size/s

#6214 feat(core): set up proxy to host custom ui assets if available
  packages/core/src/middleware/koa-serve-custom-ui-assets.test.ts
  packages/core/src/middleware/koa-serve-custom-ui-assets.ts
  packages/core/src/middleware/koa-spa-proxy.test.ts
  packages/core/src/middleware/koa-spa-proxy.ts
  packages/core/src/tenants/Tenant.ts
Labels: feature, bugfix, size/m

#6261 style(experience): remove autofill style from input component
  packages/experience/src/components/InputFields/InputField/index.module.scss
Labels: size/s

#6266 fix(console): fix image upload in onboarding process
  packages/console/src/onboarding/pages/SignInExperience/index.tsx
Labels: bugfix, size/xs

#6264 fix(console): fix grant data card height
  packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/index.tsx
Labels: bugfix, size/xs

#6268 fix(console): fix passwordless connector tester send failed bug
  packages/console/src/hooks/use-connector-form-config-parser.tsx
  packages/console/src/pages/ConnectorDetails/ConnectorContent/index.tsx
  packages/console/src/utils/connector-form.ts
Labels: bugfix, size/s

#6217 feat(console): implement custom ui assets upload component
  packages/console/src/assets/images/blur-preview.svg
  packages/console/src/components/CustomUiAssetsUploader/index.module.scss
  packages/console/src/components/CustomUiAssetsUploader/index.tsx
  packages/console/src/components/FileIcon/index.tsx
  packages/console/src/components/ImageInputs/index.tsx
  packages/console/src/components/SignInExperiencePreview/index.module.scss
  packages/console/src/components/SignInExperiencePreview/index.tsx
  packages/console/src/consts/user-assets.ts
  packages/console/src/ds-components/Uploader/FileUploader/index.tsx
  packages/console/src/ds-components/Uploader/ImageUploaderField/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/Experience/LogosUploader/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/Branding/CustomUiForm/index.module.scss
  packages/console/src/pages/SignInExperience/PageContent/Branding/CustomUiForm/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/Branding/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/utils/parser.ts
  packages/console/src/pages/SignInExperience/components/Preview/index.tsx
  packages/console/src/pages/SignInExperience/types.ts
  packages/console/src/utils/uploader.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/index.ts
  packages/schemas/src/types/user-assets.ts
Labels: feature, size/xl

#6276 ci: always set conclusion for alteration tests
  .github/workflows/alteration-compatibility-integration-test.yml
Labels: size/xs

#6265 style(experience): add transition for notched border
  packages/experience/src/components/InputFields/InputField/NotchedBorder/index.module.scss
Labels: size/xs

#6271 refactor(experience): avoid disabled button for continue button
  packages/experience/src/containers/TotpCodeVerification/index.tsx
  packages/experience/src/containers/VerificationCode/index.tsx
  packages/experience/src/hooks/use-error-handler.ts
  packages/phrases-experience/src/locales/de/error/index.ts
  packages/phrases-experience/src/locales/en/error/index.ts
  packages/phrases-experience/src/locales/es/error/index.ts
  packages/phrases-experience/src/locales/fr/error/index.ts
  packages/phrases-experience/src/locales/it/error/index.ts
  packages/phrases-experience/src/locales/ja/error/index.ts
  packages/phrases-experience/src/locales/pl-pl/error/index.ts
  packages/phrases-experience/src/locales/pt-br/error/index.ts
  packages/phrases-experience/src/locales/ru/error/index.ts
  packages/phrases-experience/src/locales/tr-tr/error/index.ts
  packages/phrases-experience/src/locales/zh-cn/error/index.ts
  packages/phrases-experience/src/locales/zh-hk/error/index.ts
  packages/phrases-experience/src/locales/zh-tw/error/index.ts
Labels: enhancement, size/s

#6273 feat(core): add api quota guard for bring your ui feature
  packages/core/package.json
  packages/core/src/libraries/quota.ts
  packages/core/src/routes/sign-in-experience/custom-ui-assets/index.ts
  pnpm-lock.yaml
Labels: feature, size/s

#6270 fix(console): should not toast invitation sent message when creating tenant w/o invitee
  packages/console/src/onboarding/pages/CreateTenant/index.tsx
Labels: bugfix, size/s

#6269 feat(console): add impersonation price item
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-table.ts
Labels: feature, size/xs

#6280 fix(experience): shrink input field when autofilled by the browser
  packages/experience/src/components/InputFields/InputField/index.module.scss
  packages/experience/src/components/InputFields/InputField/index.tsx
Labels: bugfix, size/s

#6267 feat(console): add impersonation tag to audit log
  packages/console/src/components/AuditLogTable/components/EventName/index.module.scss
  packages/console/src/components/AuditLogTable/components/EventName/index.tsx
  packages/console/src/consts/logs.ts
  packages/console/src/pages/AuditLogDetails/index.module.scss
  packages/console/src/pages/AuditLogDetails/index.tsx
Labels: feature, size/s

#6245 feat: init elements
  packages/console/package.json
  packages/console/src/pages/Profile/index.tsx
  packages/elements/README.md
  packages/elements/package.json
  packages/elements/src/components/logto-card.ts
  packages/elements/src/components/logto-form-card.ts
  packages/elements/src/components/logto-theme-provider.ts
  packages/elements/src/index.ts
  packages/elements/src/locales/en.ts
  packages/elements/src/locales/index.ts
  packages/elements/src/react.ts
  packages/elements/src/utils/css.ts
  packages/elements/src/utils/string.ts
  packages/elements/src/utils/theme.ts
  packages/elements/tsconfig.json
  packages/elements/tsup.config.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#6250 feat(elements): init i18n
  commitlint.config.ts
  packages/console/src/pages/Profile/index.tsx
  packages/elements/.gitignore
  packages/elements/lit-localize.json
  packages/elements/package.json
  packages/elements/src/components/logto-card-section.ts
  packages/elements/src/components/logto-form-card.ts
  packages/elements/src/elements/logto-profile-card.ts
  packages/elements/src/index.ts
  packages/elements/src/locales/en.ts
  packages/elements/src/locales/index.ts
  packages/elements/src/react.ts
  packages/elements/src/utils/locale.ts
  packages/elements/xliff/de.xlf
  packages/elements/xliff/es.xlf
  packages/elements/xliff/fr.xlf
  packages/elements/xliff/it.xlf
  packages/elements/xliff/ja.xlf
  packages/elements/xliff/ko.xlf
  packages/elements/xliff/pl-PL.xlf
  packages/elements/xliff/pt-BR.xlf
  packages/elements/xliff/pt-PT.xlf
  packages/elements/xliff/ru.xlf
  packages/elements/xliff/tr-TR.xlf
  packages/elements/xliff/zh-CN.xlf
  packages/elements/xliff/zh-HK.xlf
  packages/elements/xliff/zh-TW.xlf
  pnpm-lock.yaml
Labels: feature, size/l

#6252 feat(elements): add components
  packages/elements/README.md
  packages/elements/index.html
  packages/elements/package.json
  packages/elements/src/components/logto-avatar.ts
  packages/elements/src/components/logto-button.ts
  packages/elements/src/components/logto-card-section.ts
  packages/elements/src/components/logto-card.ts
  packages/elements/src/components/logto-form-card.ts
  packages/elements/src/components/logto-list-row.ts
  packages/elements/src/components/logto-list.ts
  packages/elements/src/elements/logto-profile-card.ts
  packages/elements/src/index.ts
  packages/elements/src/react.ts
  packages/elements/src/utils/theme.ts
  packages/elements/web-dev-server.config.js
  pnpm-lock.yaml
Labels: feature, size/l

#6257 feat(core,schemas): implement social/sso link and sync logic
  packages/connectors/connector-mock-social/src/index.ts
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/classes/utils.ts
  packages/core/src/routes/experience/classes/verifications/enterprise-sso-verification.ts
  packages/core/src/routes/experience/classes/verifications/social-verification.ts
  packages/core/src/routes/experience/classes/verifications/verification-record.ts
  packages/core/src/routes/experience/index.ts
  packages/integration-tests/src/api/sso-connector.ts
  packages/integration-tests/src/helpers/connector.ts
  packages/integration-tests/src/helpers/experience/index.ts
  packages/integration-tests/src/tests/api/experience-api/register-interaction/organization-jti.test.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/enterprise-sso.test.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/social.test.ts
  packages/schemas/src/types/interactions.ts
Labels: feature, size/l

#6262 feat(core): add mfa verification guard
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/classes/validators/mfa-validator.ts
  packages/core/src/routes/experience/classes/validators/sign-in-experience-validator.ts
  packages/core/src/routes/experience/classes/verifications/totp-verification.ts
  packages/core/src/routes/experience/index.ts
  packages/core/src/routes/experience/verification-routes/backup-code-verification.ts
  packages/core/src/routes/interaction/verifications/mfa-verification.ts
  packages/integration-tests/src/helpers/experience/totp-verification.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/mfa-verification.test.ts
  packages/integration-tests/src/tests/api/experience-api/verifications/totp-verification.test.ts
Labels: feature, size/l

#6246 chore: remove feature guard for token exchange
  packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/index.tsx
  packages/core/src/routes/subject-token.openapi.json
  packages/core/src/routes/subject-token.ts
  packages/core/src/routes/swagger/index.ts
  packages/integration-tests/src/tests/api/oidc/token-exchange.test.ts
  packages/integration-tests/src/tests/api/security.test.ts
Labels: chore, size/s

#6251 chore: add changeset for impersonation
  .changeset/seven-comics-tan.md
Labels: chore, size/s

#6286 chore(elements): move check to build
  packages/elements/package.json
  packages/elements/xliff/de.xlf
  packages/elements/xliff/es.xlf
  packages/elements/xliff/fr.xlf
  packages/elements/xliff/it.xlf
  packages/elements/xliff/ja.xlf
  packages/elements/xliff/ko.xlf
  packages/elements/xliff/pl-PL.xlf
  packages/elements/xliff/pt-BR.xlf
  packages/elements/xliff/pt-PT.xlf
  packages/elements/xliff/ru.xlf
  packages/elements/xliff/tr-TR.xlf
  packages/elements/xliff/zh-CN.xlf
  packages/elements/xliff/zh-HK.xlf
  packages/elements/xliff/zh-TW.xlf
Labels: chore, size/l

#6277 refactor(core,schemas): refactor `CodeVerification`
  packages/core/src/routes/experience/classes/experience-interaction.test.ts
  packages/core/src/routes/experience/classes/utils.ts
  packages/core/src/routes/experience/classes/validators/sign-in-experience-validator.test.ts
  packages/core/src/routes/experience/classes/validators/sign-in-experience-validator.ts
  packages/core/src/routes/experience/classes/verifications/code-verification.ts
  packages/core/src/routes/experience/classes/verifications/index.ts
  packages/core/src/routes/experience/classes/verifications/verification-record.ts
  packages/core/src/routes/experience/verification-routes/verification-code.ts
  packages/schemas/src/types/interactions.ts
Labels: enhancement, size/l

#6288 chore(deps): upgrade typescript and react
  packages/app-insights/package.json
  packages/cli/package.json
  packages/connectors/connector-alipay-native/package.json
  packages/connectors/connector-alipay-web/package.json
  packages/connectors/connector-aliyun-dm/package.json
  packages/connectors/connector-aliyun-sms/package.json
  packages/connectors/connector-apple/package.json
  packages/connectors/connector-aws-ses/package.json
  packages/connectors/connector-azuread/package.json
  packages/connectors/connector-dingtalk-web/package.json
  packages/connectors/connector-discord/package.json
  packages/connectors/connector-facebook/package.json
  packages/connectors/connector-feishu-web/package.json
  packages/connectors/connector-github/package.json
  packages/connectors/connector-google/package.json
  packages/connectors/connector-huggingface/package.json
  packages/connectors/connector-kakao/package.json
  packages/connectors/connector-logto-email/package.json
  packages/connectors/connector-logto-sms/package.json
  packages/connectors/connector-logto-social-demo/package.json
  packages/connectors/connector-mailgun/package.json
  packages/connectors/connector-mock-email-alternative/package.json
  packages/connectors/connector-mock-email/package.json
  packages/connectors/connector-mock-sms/package.json
  packages/connectors/connector-mock-social/package.json
  packages/connectors/connector-naver/package.json
  packages/connectors/connector-oauth2/package.json
  packages/connectors/connector-oidc/package.json
  packages/connectors/connector-saml/package.json
  packages/connectors/connector-sendgrid-email/package.json
  packages/connectors/connector-smsaero/package.json
  packages/connectors/connector-smtp/package.json
  packages/connectors/connector-tencent-sms/package.json
  packages/connectors/connector-twilio-sms/package.json
  packages/connectors/connector-wechat-native/package.json
  packages/connectors/connector-wechat-web/package.json
  packages/connectors/connector-wecom/package.json
  packages/console/package.json
  packages/core/package.json
  packages/demo-app/package.json
  packages/experience/package.json
  packages/integration-tests/package.json
  packages/phrases-experience/package.json
  packages/phrases-experience/src/types.ts
  packages/phrases/package.json
  packages/schemas/package.json
  packages/shared/package.json
  packages/toolkit/connector-kit/package.json
  packages/toolkit/core-kit/package.json
  packages/toolkit/language-kit/package.json
  pnpm-lock.yaml
Labels: chore, size/m

#6244 feat: add content schema to HTTP 201 CREATED messages
  packages/core/src/routes/swagger/index.ts
Labels: feature, size/xs

#6274 feat(console,phrases): add bring your ui quota item to pricing table
  packages/connectors/connector-logto-email/package.json
  packages/console/package.json
  packages/console/src/consts/quota-item-phrases.ts
  packages/console/src/consts/tenants.ts
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-table.ts
  pnpm-lock.yaml
Labels: feature, size/s

#6258 refactor(console,phrases,schemas): increase file upload size limit to 10mb
  packages/console/src/ds-components/Uploader/FileUploader/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/components.ts
  packages/phrases/src/locales/en/translation/admin-console/components.ts
  packages/phrases/src/locales/es/translation/admin-console/components.ts
  packages/phrases/src/locales/fr/translation/admin-console/components.ts
  packages/phrases/src/locales/it/translation/admin-console/components.ts
  packages/phrases/src/locales/ja/translation/admin-console/components.ts
  packages/phrases/src/locales/ko/translation/admin-console/components.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/components.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/components.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/components.ts
  packages/phrases/src/locales/ru/translation/admin-console/components.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/components.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/components.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/components.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/components.ts
  packages/schemas/src/types/user-assets.ts
Labels: enhancement, size/s

#6275 feat(console,phrases): add bring your UI feature paywall
  packages/console/src/components/CustomUiAssetsUploader/index.tsx
  packages/console/src/components/FeatureTag/index.tsx
  packages/console/src/ds-components/FormField/index.module.scss
  packages/console/src/ds-components/FormField/index.tsx
  packages/console/src/ds-components/Uploader/FileUploader/index.module.scss
  packages/console/src/ds-components/Uploader/FileUploader/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/Branding/CustomUiForm/index.module.scss
  packages/console/src/pages/SignInExperience/PageContent/Branding/CustomUiForm/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/upsell/paywall.ts
Labels: feature, size/s

#6297 chore: update README.md
  AWESOME.md
  README.md
Labels: chore, size/s

#6272 feat(elements): init modal and input
  packages/elements/README.md
  packages/elements/package.json
  packages/elements/src/components/logto-button.ts
  packages/elements/src/components/logto-card-section.ts
  packages/elements/src/components/logto-form-card.ts
  packages/elements/src/components/logto-icon-button.ts
  packages/elements/src/components/logto-modal-layout.ts
  packages/elements/src/components/logto-modal.context.ts
  packages/elements/src/components/logto-modal.ts
  packages/elements/src/components/logto-text-input.ts
  packages/elements/src/elements/logto-profile-card.ts
  packages/elements/src/icons/close.svg
  packages/elements/src/icons/index.d.ts
  packages/elements/src/index.ts
  packages/elements/src/utils/theme.ts
  packages/elements/tsup.config.ts
  packages/elements/web-dev-server.config.js
  packages/elements/xliff/de.xlf
  packages/elements/xliff/es.xlf
  packages/elements/xliff/fr.xlf
  packages/elements/xliff/it.xlf
  packages/elements/xliff/ja.xlf
  packages/elements/xliff/ko.xlf
  packages/elements/xliff/pl-PL.xlf
  packages/elements/xliff/pt-BR.xlf
  packages/elements/xliff/pt-PT.xlf
  packages/elements/xliff/ru.xlf
  packages/elements/xliff/tr-TR.xlf
  packages/elements/xliff/zh-CN.xlf
  packages/elements/xliff/zh-HK.xlf
  packages/elements/xliff/zh-TW.xlf
  pnpm-lock.yaml
Labels: feature, size/xl

#6296 style(experience): improve notched border animation
  packages/experience/src/components/InputFields/InputField/NotchedBorder/index.module.scss
Labels: size/xs

#6299 fix(console): sidebar width should not be shrunk
  packages/console/src/containers/ConsoleContent/Sidebar/index.module.scss
Labels: bugfix, size/xs

#6282 refactor(core): extract password-validator
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/classes/utils.test.ts
  packages/core/src/routes/experience/classes/utils.ts
  packages/core/src/routes/experience/classes/validators/password-validator.ts
  packages/core/src/routes/experience/classes/validators/profile-validator.ts
  packages/core/src/routes/experience/classes/validators/sign-in-experience-validator.ts
  packages/core/src/routes/experience/classes/verifications/new-password-identity-verification.ts
  packages/core/src/routes/experience/verification-routes/new-password-identity-verification.ts
Labels: enhancement, size/m

#6283 fix(core): should not sync registered identifier from social
  packages/core/src/routes/experience/classes/verifications/social-verification.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/social.test.ts
Labels: bugfix, size/s

#6302 style(experience): use brand loading color for buttons
  packages/experience/src/Providers/AppBoundary/use-color-theme.ts
  packages/experience/src/components/Button/SocialLinkButton.module.scss
  packages/experience/src/components/Button/index.module.scss
  packages/experience/src/scss/_colors.scss
Labels: size/xs

#6303 chore(console): remove dev feature guard
  packages/console/src/pages/CustomizeJwtDetails/utils/config.tsx
Labels: chore, size/s

#6285 refactor(core): extract helpers and provision methods
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/classes/helpers.ts
  packages/core/src/routes/experience/classes/utils.ts
  packages/core/src/routes/experience/classes/validators/provision-library.ts
Labels: enhancement, size/l

#6278 feat(elements): init user provider
  packages/elements/index.html
  packages/elements/package.json
  packages/elements/src/components/logto-button.styles.ts
  packages/elements/src/components/logto-button.ts
  packages/elements/src/components/logto-card-section.ts
  packages/elements/src/components/logto-form-card.ts
  packages/elements/src/components/logto-list-row.ts
  packages/elements/src/components/logto-modal-layout.ts
  packages/elements/src/elements/logto-profile-card.ts
  packages/elements/src/index.ts
  packages/elements/src/phrases/index.ts
  packages/elements/src/providers/logto-theme-provider.ts
  packages/elements/src/providers/logto-user-provider.ts
  packages/elements/src/utils/theme.ts
  packages/elements/xliff/de.xlf
  packages/elements/xliff/es.xlf
  packages/elements/xliff/fr.xlf
  packages/elements/xliff/it.xlf
  packages/elements/xliff/ja.xlf
  packages/elements/xliff/ko.xlf
  packages/elements/xliff/pl-PL.xlf
  packages/elements/xliff/pt-BR.xlf
  packages/elements/xliff/pt-PT.xlf
  packages/elements/xliff/ru.xlf
  packages/elements/xliff/tr-TR.xlf
  packages/elements/xliff/zh-CN.xlf
  packages/elements/xliff/zh-HK.xlf
  packages/elements/xliff/zh-TW.xlf
  pnpm-lock.yaml
Labels: feature, size/l

#6284 feat(elements): update name of user
  packages/console/src/pages/Profile/index.tsx
  packages/core/src/middleware/koa-cors.ts
  packages/elements/index.html
  packages/elements/package.json
  packages/elements/src/elements/logto-profile-card.ts
  packages/elements/src/index.ts
  packages/elements/src/providers/logto-user-provider.ts
  packages/elements/src/react.ts
  packages/elements/src/utils/api.ts
  pnpm-lock.yaml
Labels: feature, size/m

#6301 refactor(console,phrases): minor ui changes to file uploader component and ui description
  packages/console/src/ds-components/Uploader/FileUploader/index.module.scss
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/index.ts
Labels: enhancement, size/xs

#6307 refactor(console,schemas): misc updates for bring your ui feature
  packages/console/src/pages/SignInExperience/PageContent/Branding/CustomUiForm/index.tsx
  packages/schemas/src/types/user-assets.ts
Labels: enhancement, size/xs

#6287 feat(schemas): multiple app secrets
  .scripts/compare-database.js
  packages/schemas/alterations/next-1721483240-multiple-app-secrets.ts
  packages/schemas/src/consts/system.ts
  packages/schemas/tables/application_secrets.sql
  packages/schemas/tables/applications.sql
Labels: feature, size/m

#6300 fix(core): disable bring your ui feature for admin tenant
  packages/core/src/routes/sign-in-experience/custom-ui-assets/index.ts
  packages/phrases/src/locales/en/errors/guard.ts
Labels: bugfix, size/s

#6306 fix(console): should be able to remove the zip on upload error
  packages/console/src/components/CustomUiAssetsUploader/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/utils/parser.ts
  packages/console/src/pages/SignInExperience/types.ts
Labels: bugfix, size/s

#6313 fix(console): fix loading and error handling for org details page
  packages/console/src/pages/OrganizationDetails/index.tsx
Labels: bugfix, size/s

#6305 refactor(console): keep button loading before redirecting to sign-in success page
  packages/experience/src/containers/SocialLinkAccount/use-social-link-related-user.ts
  packages/experience/src/containers/VerificationCode/use-continue-flow-code-verification.ts
  packages/experience/src/containers/VerificationCode/use-register-flow-code-verification.ts
  packages/experience/src/containers/VerificationCode/use-sign-in-flow-code-verification.ts
  packages/experience/src/hooks/use-global-redirect-to.ts
  packages/experience/src/hooks/use-password-sign-in.ts
  packages/experience/src/hooks/use-send-mfa-payload.ts
  packages/experience/src/hooks/use-skip-mfa.ts
  packages/experience/src/hooks/use-social-link-account.ts
  packages/experience/src/hooks/use-social-register.ts
  packages/experience/src/pages/Consent/index.tsx
  packages/experience/src/pages/Continue/SetPassword/index.tsx
  packages/experience/src/pages/Continue/SetUsername/use-set-username.ts
  packages/experience/src/pages/RegisterPassword/index.tsx
  packages/experience/src/pages/SocialSignInWebCallback/use-single-sign-on-listener.ts
Labels: enhancement, size/s

#6289 refactor(core): implement verification records map
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/classes/helpers.ts
  packages/core/src/routes/experience/classes/validators/provision-library.ts
  packages/core/src/routes/experience/classes/verifications/enterprise-sso-verification.ts
  packages/core/src/routes/experience/classes/verifications/index.ts
  packages/core/src/routes/experience/classes/verifications/verification-records-map.ts
  packages/core/src/routes/experience/verification-routes/enterprise-sso-verification.ts
  packages/core/src/routes/experience/verification-routes/social-verification.ts
  packages/core/src/routes/experience/verification-routes/totp-verification.ts
  packages/core/src/routes/experience/verification-routes/verification-code.ts
Labels: enhancement, size/m

#6316 refactor(experience): use button loading for social sign-in
  packages/experience/src/containers/SocialSignInList/index.tsx
  packages/experience/src/containers/SocialSignInList/use-social.ts
  packages/experience/src/hooks/use-global-redirect-to.ts
  packages/experience/src/hooks/use-single-sign-on.ts
  packages/experience/src/pages/SingleSignOnConnectors/index.tsx
Labels: enhancement, size/m

#6314 refactor: use vite for demo app
  packages/core/src/middleware/koa-spa-proxy.ts
  packages/demo-app/.parcelrc.arm64
  packages/demo-app/index.html
  packages/demo-app/package.json
  packages/demo-app/tsconfig.json
  packages/demo-app/vite.config.ts
  pnpm-lock.yaml
Labels: enhancement, size/s

#6292 feat(core): multiple app secrets
  packages/core/package.json
  packages/core/src/event-listeners/index.ts
  packages/core/src/middleware/koa-app-secret-transpilation.test.ts
  packages/core/src/middleware/koa-app-secret-transpilation.ts
  packages/core/src/middleware/koa-oidc-error-handler.ts
  packages/core/src/middleware/koa-slonik-error-handler.ts
  packages/core/src/oidc/init.ts
  packages/core/src/queries/application-secrets.ts
  packages/core/src/routes/applications/application-secret.openapi.json
  packages/core/src/routes/applications/application-secret.ts
  packages/core/src/routes/applications/application.test.ts
  packages/core/src/routes/applications/application.ts
  packages/core/src/routes/init.ts
  packages/core/src/tenants/Queries.ts
  packages/integration-tests/src/api/application.ts
  packages/integration-tests/src/tests/api/application/application.secrets.test.ts
  packages/integration-tests/src/tests/api/application/application.test.ts
  packages/integration-tests/src/tests/api/oidc/client-authentication.test.ts
  packages/phrases/src/locales/en/errors/application.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#6304 feat(console): support multiple app secrets
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/CreateSecretModal.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/EndpointsAndCredentials.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.module.scss
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
Labels: feature, size/l

#6310 refactor: generate application secret on creation
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/EndpointsAndCredentials.tsx
  packages/core/src/__mocks__/index.ts
  packages/core/src/routes/applications/application.test.ts
  packages/core/src/routes/applications/application.ts
  packages/integration-tests/src/tests/api/application/application.secrets.test.ts
  packages/schemas/src/utils/application.ts
  packages/schemas/src/utils/index.ts
Labels: enhancement, size/m

#6312 refactor(core): log app secret name
  packages/core/src/event-listeners/grant.ts
  packages/core/src/event-listeners/utils.ts
  packages/core/src/middleware/koa-app-secret-transpilation.ts
  packages/integration-tests/src/tests/api/oidc/client-authentication.test.ts
Labels: enhancement, size/s

#6325 fix(console): use correct public url
  packages/console/vite.config.ts
Labels: bugfix, size/xs

#6323 refactor(console): use local mermaid import
  packages/console/src/consts/env.ts
  packages/console/src/mdx-components/Mermaid/index.tsx
  packages/core/src/middleware/koa-security-headers.ts
  vite.shared.config.ts
Labels: enhancement, size/s

#6326 refactor(console, experience): optimize bundling
  packages/console/index.html
  packages/console/package.json
  packages/console/vite.config.ts
  packages/demo-app/index.html
  packages/experience/vite.config.ts
  pnpm-lock.yaml
  vite.shared.config.ts
Labels: enhancement, size/s

#6321 refactor(core): rename some file names and methods
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/classes/libraries/mfa-validator.ts
  packages/core/src/routes/experience/classes/libraries/password-validator.ts
  packages/core/src/routes/experience/classes/libraries/profile-validator.ts
  packages/core/src/routes/experience/classes/libraries/provision-library.ts
  packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.test.ts
  packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.ts
  packages/core/src/routes/experience/classes/verifications/new-password-identity-verification.ts
  packages/core/src/routes/experience/classes/verifications/verification-records-map.ts
Labels: enhancement, size/s

#6329 fix(console): check scope only when data is ready
  packages/console/src/containers/ConsoleContent/hooks.ts
Labels: bugfix, size/s

#6293 feat(core,schemas): implement profile fulfillment flow
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/classes/libraries/password-validator.ts
  packages/core/src/routes/experience/classes/libraries/profile-validator.ts
  packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.ts
  packages/core/src/routes/experience/classes/profile.ts
  packages/core/src/routes/experience/classes/verifications/code-verification.ts
  packages/core/src/routes/experience/classes/verifications/new-password-identity-verification.ts
  packages/core/src/routes/experience/const.ts
  packages/core/src/routes/experience/index.ts
  packages/core/src/routes/experience/profile-routes.ts
  packages/core/src/routes/experience/types.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/enterprise-sso.test.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/social.test.ts
  packages/phrases/src/locales/en/errors/session.ts
  packages/schemas/src/types/interactions.ts
Labels: feature, size/xl

#6294 test(core): add profile fulfillment integration tests
  packages/integration-tests/src/client/experience/const.ts
  packages/integration-tests/src/client/experience/index.ts
  packages/integration-tests/src/helpers/experience/index.ts
  packages/integration-tests/src/tests/api/experience-api/profile/fulfill-user-profiles.test.ts
  packages/integration-tests/src/tests/api/experience-api/profile/reset-password.test.ts
  packages/integration-tests/src/tests/api/experience-api/register-interaction/verification-code.test.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/password.test.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/social.test.ts
Labels: testing, size/xl

#6333 fix(console): css loaded svg should be rendered properly
  packages/console/src/components/SignInExperiencePreview/index.module.scss
  packages/console/src/ds-components/TextInput/index.module.scss
  packages/console/src/onboarding/pages/SignInExperience/InspireMe/index.module.scss
  packages/console/src/pages/Welcome/index.module.scss
Labels: bugfix, size/s
