Repository logto-io/logto, pull requests merged in 2024-03, with the labels that each got.

#5451 refactor(core, schemas): enhance the time accuracy of dau data
  packages/core/src/event-listeners/record-active-users.ts
  packages/schemas/alterations/next-1709190131-enhance-dau-data-accuracy.ts
  packages/schemas/tables/daily_active_users.sql
Labels: enhancement, size/s

#5339 fix(schemas): set default password for tenant (#4535)
  packages/cli/src/commands/database/seed/index.ts
  packages/cli/src/commands/database/seed/tables.ts
  packages/schemas/tables/_before_all.sql
Labels: bugfix, size/s

#5454 feat(core,connector): support apple sign-in with email
  .changeset/eight-pans-wait.md
  .changeset/proud-birds-push.md
  packages/connectors/connector-apple/README.md
  packages/connectors/connector-apple/docs/sign-in-with-apple-consent-page.png
  packages/connectors/connector-apple/src/constant.ts
  packages/connectors/connector-apple/src/index.test.ts
  packages/connectors/connector-apple/src/index.ts
  packages/connectors/connector-apple/src/mock.ts
  packages/connectors/connector-apple/src/types.ts
  packages/core/src/middleware/koa-spa-proxy.ts
  packages/core/src/routes/callback.test.ts
  packages/core/src/routes/callback.ts
  packages/core/src/tenants/Tenant.ts
  packages/integration-tests/src/tests/api/callback.test.ts
Labels: feature, size/m

#5456 refactor(schemas): update schema to fit cloud
  packages/schemas/package.json
  packages/schemas/src/types/organization.ts
  pnpm-lock.yaml
Labels: enhancement, size/s

#5444 feat(core): support more encrypt methods
  packages/core/src/__mocks__/user.ts
  packages/core/src/libraries/user.test.ts
  packages/core/src/libraries/user.ts
  packages/core/src/utils/password.ts
  packages/schemas/alterations/next-1709521416-user-password-encrypt-method.ts
  packages/schemas/tables/users.sql
Labels: feature, size/m

#5462 chore(schemas): upgrade withtyped pacakge
  packages/schemas/package.json
  pnpm-lock.yaml
Labels: chore, size/xs

#5455 refactor(schemas): regenerate dau table data from logs
  packages/schemas/alterations/next-1709528944-regenerate-dau-data.ts
Labels: enhancement, size/s

#5446 feat(core): create user with password digest
  .changeset/real-eels-jam.md
  packages/core/src/routes/admin-user/basic.openapi.json
  packages/core/src/routes/admin-user/basics.test.ts
  packages/core/src/routes/admin-user/basics.ts
  packages/integration-tests/src/api/admin-user.ts
  packages/integration-tests/src/helpers/index.ts
  packages/integration-tests/src/tests/api/admin-user.test.ts
  packages/phrases/src/locales/de/errors/user.ts
  packages/phrases/src/locales/en/errors/user.ts
  packages/phrases/src/locales/es/errors/user.ts
  packages/phrases/src/locales/fr/errors/user.ts
  packages/phrases/src/locales/it/errors/user.ts
  packages/phrases/src/locales/ja/errors/user.ts
  packages/phrases/src/locales/ko/errors/user.ts
  packages/phrases/src/locales/pl-pl/errors/user.ts
  packages/phrases/src/locales/pt-br/errors/user.ts
  packages/phrases/src/locales/pt-pt/errors/user.ts
  packages/phrases/src/locales/ru/errors/user.ts
  packages/phrases/src/locales/tr-tr/errors/user.ts
  packages/phrases/src/locales/zh-cn/errors/user.ts
  packages/phrases/src/locales/zh-hk/errors/user.ts
  packages/phrases/src/locales/zh-tw/errors/user.ts
Labels: feature, size/m

#5457 refactor(core): migrate `dashboard/users/active` api data deps
  packages/core/src/queries/daily-active-user.ts
  packages/core/src/routes/dashboard.test.ts
  packages/core/src/routes/dashboard.ts
Labels: enhancement, size/s

#5464 chore(core): deprecate unused query methods for logs table
  packages/core/src/queries/log.ts
Labels: chore, size/s

#5466 refactor(console): refactor conversion tracking
  packages/console/src/App.tsx
  packages/console/src/components/Conversion/index.tsx
  packages/console/src/components/Conversion/use-retry.ts
  packages/console/src/components/Conversion/utils.test.ts
  packages/console/src/components/Conversion/utils.ts
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/index.tsx
  packages/console/src/components/ReportConversion/index.tsx
  packages/console/src/components/ReportConversion/utils.ts
  packages/console/src/consts/env.ts
  packages/console/src/include.d/tags.d.ts
  packages/console/src/onboarding/index.tsx
  packages/console/src/pages/CheckoutSuccessCallback/index.tsx
Labels: enhancement, size/xl

#5448 feat(console,phrases): add new jwt claims page
  packages/console/src/App.tsx
  packages/console/src/consts/env.ts
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/containers/ConsoleRoutes/index.tsx
  packages/console/src/pages/JwtClaims/index.module.scss
  packages/console/src/pages/JwtClaims/index.tsx
  packages/console/src/pages/JwtClaims/type.ts
  packages/phrases/src/locales/de/translation/admin-console/index.ts
  packages/phrases/src/locales/de/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/en/translation/admin-console/index.ts
  packages/phrases/src/locales/en/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/es/translation/admin-console/index.ts
  packages/phrases/src/locales/es/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/fr/translation/admin-console/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/it/translation/admin-console/index.ts
  packages/phrases/src/locales/it/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ja/translation/admin-console/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ko/translation/admin-console/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ru/translation/admin-console/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/jwt-claims.ts
Labels: feature, size/l

#5460 feat(console,phrases): integrate monaco editor
  packages/console/package.json
  packages/console/src/pages/JwtClaims/MonacoCodeEditor/config.ts
  packages/console/src/pages/JwtClaims/MonacoCodeEditor/index.module.scss
  packages/console/src/pages/JwtClaims/MonacoCodeEditor/index.tsx
  packages/console/src/pages/JwtClaims/MonacoCodeEditor/type.ts
  packages/console/src/pages/JwtClaims/config.ts
  packages/console/src/pages/JwtClaims/index.module.scss
  packages/console/src/pages/JwtClaims/index.tsx
  packages/console/src/pages/JwtClaims/type.ts
  packages/console/src/scss/_code-editor.scss
  packages/console/src/scss/normalized.scss
  packages/core/src/middleware/koa-security-headers.ts
  packages/phrases/src/locales/de/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/en/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/es/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/fr/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/it/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ja/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ko/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ru/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/jwt-claims.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#5469 feat(console, phrases): add data source guides
  packages/console/src/assets/icons/book.svg
  packages/console/src/assets/icons/start.svg
  packages/console/src/pages/JwtClaims/RightPanel/GuideCard.tsx
  packages/console/src/pages/JwtClaims/RightPanel/index.module.scss
  packages/console/src/pages/JwtClaims/RightPanel/index.tsx
  packages/console/src/pages/JwtClaims/config.ts
  packages/console/src/pages/JwtClaims/index.module.scss
  packages/console/src/pages/JwtClaims/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/en/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/es/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/fr/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/it/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ja/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ko/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ru/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/jwt-claims.ts
  packages/toolkit/core-kit/scss/_console-themes.scss
Labels: feature, size/xl

#5453 feat(schemas): update `logto_configs` table related types
  packages/schemas/src/types/index.ts
  packages/schemas/src/types/logto-config/index.ts
  packages/schemas/src/types/logto-config/oidc-provider.ts
Labels: feature, size/m

#5461 feat(core): add PUT /configs/jwt-customizer API
  packages/core/src/__mocks__/index.ts
  packages/core/src/libraries/cloud-connection.test.ts
  packages/core/src/libraries/logto-config.ts
  packages/core/src/libraries/sign-in-experience/index.test.ts
  packages/core/src/middleware/koa-guard.ts
  packages/core/src/queries/logto-config.ts
  packages/core/src/routes/logto-config.openapi.json
  packages/core/src/routes/logto-config.test.ts
  packages/core/src/routes/logto-config.ts
  packages/integration-tests/src/api/logto-config.ts
  packages/integration-tests/src/tests/api/logto-config.test.ts
Labels: feature, size/l

#5465 feat(core): add GET /configs/jwt-customizer API
  packages/core/src/libraries/cloud-connection.test.ts
  packages/core/src/libraries/logto-config.ts
  packages/core/src/libraries/sign-in-experience/index.test.ts
  packages/core/src/queries/logto-config.ts
  packages/core/src/routes/logto-config.openapi.json
  packages/core/src/routes/logto-config.test.ts
  packages/core/src/routes/logto-config.ts
  packages/integration-tests/src/api/logto-config.ts
  packages/integration-tests/src/tests/api/logto-config.test.ts
Labels: feature, size/m

#5467 feat(core): add DELETE /configs/jwt-customizer API
  packages/core/src/queries/logto-config.ts
  packages/core/src/routes/logto-config.openapi.json
  packages/core/src/routes/logto-config.test.ts
  packages/core/src/routes/logto-config.ts
  packages/integration-tests/src/api/logto-config.ts
  packages/integration-tests/src/tests/api/logto-config.test.ts
Labels: feature, size/m

#5471 refactor(console): implement environment variables input field (1/2)
  packages/console/src/ds-components/KeyValueInputField/index.module.scss
  packages/console/src/ds-components/KeyValueInputField/index.tsx
  packages/console/src/ds-components/TextInput/index.tsx
  packages/console/src/pages/WebhookDetails/WebhookSettings/CustomHeaderField/index.tsx
Labels: enhancement, size/l

#5479 feat(console,phrases): add test result component
  packages/console/src/pages/JwtClaims/SettingsPanel/TestResult.tsx
  packages/console/src/pages/JwtClaims/SettingsPanel/TestTab.tsx
  packages/console/src/pages/JwtClaims/SettingsPanel/index.module.scss
  packages/phrases/src/locales/de/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/en/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/es/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/fr/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/it/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ja/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ko/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ru/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/jwt-claims.ts
Labels: feature, size/m

#5476 feat(core): create user with avatar and custom data
  .changeset/clever-buttons-behave.md
  packages/core/src/routes/admin-user/basics.ts
  packages/integration-tests/src/helpers/index.ts
  packages/integration-tests/src/tests/api/admin-user.search.test.ts
  packages/integration-tests/src/tests/api/admin-user.test.ts
  packages/integration-tests/src/tests/api/dashboard.test.ts
  packages/integration-tests/src/tests/api/oidc/always-issue-refresh-token.test.ts
  packages/integration-tests/src/tests/api/oidc/get-access-token.test.ts
  packages/integration-tests/src/tests/api/oidc/id-token.test.ts
Labels: feature, size/s

#5481 feat(core): add password algorithm transition
  packages/core/src/libraries/user.test.ts
  packages/core/src/libraries/user.ts
  packages/core/src/routes-me/user.ts
  packages/core/src/routes/admin-user/basics.test.ts
  packages/core/src/routes/admin-user/basics.ts
  packages/core/src/routes/interaction/verifications/identifier-payload-verification.test.ts
  packages/core/src/routes/interaction/verifications/identifier-payload-verification.ts
  packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier/happy-path.test.ts
Labels: feature, size/m

#5480 chore(console): component rename
  packages/console/src/pages/JwtClaims/ScriptSection.tsx
  packages/console/src/pages/JwtClaims/SettingsSection/EnvironmentVariablesField.tsx
  packages/console/src/pages/JwtClaims/SettingsSection/GuideCard.tsx
  packages/console/src/pages/JwtClaims/SettingsSection/InstructionTab.tsx
  packages/console/src/pages/JwtClaims/SettingsSection/TestResult.tsx
  packages/console/src/pages/JwtClaims/SettingsSection/TestTab.tsx
  packages/console/src/pages/JwtClaims/SettingsSection/index.module.scss
  packages/console/src/pages/JwtClaims/SettingsSection/index.tsx
  packages/console/src/pages/JwtClaims/index.tsx
Labels: chore, size/s

#5478 fix(console): fix input field background color
  packages/console/src/ds-components/TextInput/index.module.scss
Labels: bugfix, size/xs

#5490 feat(console, phrases): implement the copy, clear and reset button
  packages/console/src/pages/JwtClaims/MonacoCodeEditor/ActionButton/CodeClearButton.tsx
  packages/console/src/pages/JwtClaims/MonacoCodeEditor/ActionButton/CodeRestoreButton.tsx
  packages/console/src/pages/JwtClaims/MonacoCodeEditor/ActionButton/index.tsx
  packages/console/src/pages/JwtClaims/MonacoCodeEditor/index.module.scss
  packages/console/src/pages/JwtClaims/MonacoCodeEditor/index.tsx
  packages/console/src/pages/JwtClaims/MonacoCodeEditor/type.ts
  packages/console/src/pages/JwtClaims/ScriptSection.tsx
  packages/console/src/pages/JwtClaims/SettingsSection/TestTab.tsx
  packages/console/src/pages/JwtClaims/config.tsx
  packages/console/src/pages/JwtClaims/index.tsx
  packages/console/src/pages/JwtClaims/type.ts
  packages/phrases/src/locales/de/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/en/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/es/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/fr/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/it/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ja/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ko/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ru/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/jwt-claims.ts
Labels: feature, size/l

#5487 feat(core,schemas): add JWT customizer user info context
  packages/core/src/libraries/jwt-customizer.ts
  packages/core/src/libraries/user.ts
  packages/core/src/tenants/Libraries.ts
  packages/schemas/src/types/index.ts
  packages/schemas/src/types/jwt-customizer.ts
Labels: feature, size/m

#5492 feat(console): add change alert and save changes footer
  packages/console/src/pages/JwtClaims/index.tsx
Labels: feature, size/s

#5491 refactor(experience): skip non-object messages in native
  .changeset/silent-singers-trade.md
  packages/experience/src/hooks/use-native-message-listener.ts
Labels: enhancement, size/s

#5474 refactor(core): update organization invitation apis
  packages/core/src/libraries/organization-invitation.ts
  packages/core/src/queries/organization/index.ts
  packages/core/src/queries/organization/relations.ts
  packages/core/src/routes/organization/invitations.openapi.json
  packages/core/src/routes/organization/invitations.ts
  packages/integration-tests/src/api/api.ts
  packages/integration-tests/src/api/organization-invitation.ts
  packages/integration-tests/src/tests/api/organization/organization-invitation.creation.test.ts
  packages/integration-tests/src/tests/api/organization/organization-invitation.get.test.ts
Labels: enhancement, size/l

#5493 refactor(core,console): align the jwt token path enum
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/pages/JwtClaims/ScriptSection.tsx
  packages/console/src/pages/JwtClaims/SettingsSection/InstructionTab.tsx
  packages/console/src/pages/JwtClaims/SettingsSection/TestTab.tsx
  packages/console/src/pages/JwtClaims/config.tsx
  packages/console/src/pages/JwtClaims/index.tsx
  packages/console/src/pages/JwtClaims/type.ts
  packages/core/src/routes/logto-config.ts
  packages/schemas/src/types/jwt-customizer.ts
Labels: enhancement, size/s

#5495 feat(console,phrases): integrate jwt customizer api
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/pages/JwtClaims/Main.tsx
  packages/console/src/pages/JwtClaims/MonacoCodeEditor/index.tsx
  packages/console/src/pages/JwtClaims/ScriptSection.tsx
  packages/console/src/pages/JwtClaims/SettingsSection/EnvironmentVariablesField.tsx
  packages/console/src/pages/JwtClaims/SettingsSection/TestTab.tsx
  packages/console/src/pages/JwtClaims/SettingsSection/index.module.scss
  packages/console/src/pages/JwtClaims/index.tsx
  packages/console/src/pages/JwtClaims/use-jwt-customizer.ts
  packages/console/src/pages/JwtClaims/utils.ts
  packages/phrases/src/locales/de/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/en/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/es/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/fr/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/it/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ja/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ko/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ru/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/jwt-claims.ts
Labels: feature, size/l

#5496 refactor(console,core,schemas): rename the jwtCustomizer related type and guards
  packages/console/src/pages/JwtClaims/Main.tsx
  packages/console/src/pages/JwtClaims/use-jwt-customizer.ts
  packages/console/src/pages/JwtClaims/utils.ts
  packages/core/src/routes/logto-config.ts
  packages/integration-tests/src/api/logto-config.ts
  packages/schemas/src/types/logto-config/index.ts
Labels: enhancement, size/s

#5500 feat(phrases): add i18n phrases for cloud collaboration
  packages/phrases/src/locales/de/translation/admin-console/index.ts
  packages/phrases/src/locales/de/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/de/translation/admin-console/tenants.ts
  packages/phrases/src/locales/en/translation/admin-console/index.ts
  packages/phrases/src/locales/en/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/en/translation/admin-console/tenants.ts
  packages/phrases/src/locales/es/translation/admin-console/index.ts
  packages/phrases/src/locales/es/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/es/translation/admin-console/tenants.ts
  packages/phrases/src/locales/fr/translation/admin-console/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/fr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/it/translation/admin-console/index.ts
  packages/phrases/src/locales/it/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/it/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ja/translation/admin-console/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/ja/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ko/translation/admin-console/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/ko/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tenants.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tenants.ts
  packages/phrases/src/locales/ru/translation/admin-console/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/ru/translation/admin-console/tenants.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tenants.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tenants.ts
Labels: feature, size/xl

#5498 feat(console): add global loading skeleton
  packages/console/src/pages/JwtClaims/CodeEditorLoadingContext.ts
  packages/console/src/pages/JwtClaims/Main.tsx
  packages/console/src/pages/JwtClaims/MonacoCodeEditor/index.tsx
  packages/console/src/pages/JwtClaims/PageLoadingSkeleton/index.module.scss
  packages/console/src/pages/JwtClaims/PageLoadingSkeleton/index.tsx
  packages/console/src/pages/JwtClaims/ScriptSection.tsx
  packages/console/src/pages/JwtClaims/index.module.scss
  packages/console/src/pages/JwtClaims/index.tsx
Labels: feature, size/m

#5499 fix(console): fix code edtior set undefined value bug
  packages/console/src/pages/JwtClaims/MonacoCodeEditor/index.tsx
  packages/console/src/pages/JwtClaims/ScriptSection.tsx
  packages/console/src/pages/JwtClaims/utils.ts
Labels: bugfix, size/s

#5506 fix(core): the koa response status guard missing 422 in sso integration API
  packages/core/src/routes/interaction/single-sign-on.ts
Labels: bugfix, size/xs

#5510 chore(schemas): export custom JWT API request body type
  packages/schemas/src/types/jwt-customizer.ts
Labels: chore, size/xs

#5507 chore: add changeset for the bug fix PR
  .changeset/thin-shoes-jog.md
Labels: chore, size/s

#5509 feat(core): set oidc issuer to custom domain
  packages/core/src/app/init.ts
  packages/core/src/env-set/index.ts
  packages/core/src/middleware/koa-spa-session-guard.ts
  packages/core/src/routes/interaction/actions/submit-interaction.mfa.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/core/src/routes/user-assets.ts
  packages/core/src/tenants/Tenant.ts
  packages/core/src/tenants/index.ts
  packages/core/src/utils/tenant.test.ts
  packages/core/src/utils/tenant.ts
Labels: feature, size/m

#5522 test(core): mock crypto functions in password tests
  packages/core/src/libraries/user.test.ts
  packages/core/src/routes/interaction/additional.test.ts
Labels: testing, size/s

#5521 refactor: allow unknown keys in send message payload
  .changeset/witty-moose-kick.md
  packages/core/src/utils/zod.ts
  packages/toolkit/connector-kit/src/index.test.ts
  packages/toolkit/connector-kit/src/index.ts
  packages/toolkit/connector-kit/src/types/passwordless.ts
Labels: enhancement, size/s

#5516 refactor(console): refactor the code editor type definition
  .gitignore
  packages/console/generate.sh
  packages/console/package.json
  packages/console/scripts/generate-jwt-customizer-type-definition.ts
  packages/console/src/pages/JwtClaims/Main.tsx
  packages/console/src/pages/JwtClaims/MonacoCodeEditor/index.tsx
  packages/console/src/pages/JwtClaims/MonacoCodeEditor/type.ts
  packages/console/src/pages/JwtClaims/ScriptSection.tsx
  packages/console/src/pages/JwtClaims/SettingsSection/InstructionTab.tsx
  packages/console/src/pages/JwtClaims/SettingsSection/TestTab.tsx
  packages/console/src/pages/JwtClaims/use-jwt-customizer.ts
  packages/console/src/pages/JwtClaims/utils/config.tsx
  packages/console/src/pages/JwtClaims/utils/format.ts
  packages/console/src/pages/JwtClaims/utils/type-definitions.ts
  packages/console/tsconfig.scripts.gen.json
  pnpm-lock.yaml
Labels: enhancement, size/l

#5519 refactor(console): replace the field table with type definition code
  packages/console/src/pages/JwtClaims/SettingsSection/InstructionTab.tsx
  packages/console/src/pages/JwtClaims/utils/config.tsx
  packages/console/src/pages/JwtClaims/utils/type-definitions.ts
Labels: enhancement, size/m

#5527 refactor(console,phrases): refactor the jwt customizer content
  packages/console/src/assets/icons/jwt-claims.svg
  packages/console/src/containers/ConsoleContent/Sidebar/hook.tsx
  packages/console/src/pages/JwtClaims/MonacoCodeEditor/config.ts
  packages/console/src/pages/JwtClaims/MonacoCodeEditor/index.tsx
  packages/console/src/pages/JwtClaims/MonacoCodeEditor/type.ts
  packages/console/src/pages/JwtClaims/SettingsSection/EnvironmentVariablesField.tsx
  packages/console/src/pages/JwtClaims/SettingsSection/InstructionTab.tsx
  packages/console/src/pages/JwtClaims/SettingsSection/TestTab.tsx
  packages/console/src/pages/JwtClaims/SettingsSection/index.module.scss
  packages/console/src/pages/JwtClaims/utils/config.tsx
  packages/phrases/src/locales/de/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/de/translation/admin-console/tabs.ts
  packages/phrases/src/locales/en/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/en/translation/admin-console/tabs.ts
  packages/phrases/src/locales/es/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/es/translation/admin-console/tabs.ts
  packages/phrases/src/locales/fr/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/fr/translation/admin-console/tabs.ts
  packages/phrases/src/locales/it/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/it/translation/admin-console/tabs.ts
  packages/phrases/src/locales/ja/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ja/translation/admin-console/tabs.ts
  packages/phrases/src/locales/ko/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ko/translation/admin-console/tabs.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tabs.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tabs.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tabs.ts
  packages/phrases/src/locales/ru/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ru/translation/admin-console/tabs.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tabs.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tabs.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tabs.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tabs.ts
Labels: enhancement, size/m

#5528 refactor(core): refactor oidc sso connector
  packages/core/src/sso/OidcConnector/index.ts
  packages/core/src/sso/OktaSsoConnector/index.ts
Labels: enhancement, size/s

#5533 ci: bump workflow version
  .github/workflows/alteration-compatibility-integration-test.yml
  .github/workflows/integration-test.yml
Labels: size/xs

#5503 fix(schemas): fix the get interation/consent api bug
  .changeset/seven-socks-perform.md
  packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx
  packages/experience/src/pages/Consent/ScopesListCard/index.tsx
  packages/integration-tests/src/api/interaction.ts
  packages/integration-tests/src/client/index.ts
  packages/integration-tests/src/tests/api/interaction/third-party-sign-in/happy-path.test.ts
  packages/integration-tests/src/tests/api/resource.scope.test.ts
  packages/schemas/alterations/next-1710408335-make-resource-scopes-description-nullable.ts
  packages/schemas/src/types/consent.ts
  packages/schemas/tables/scopes.sql
Labels: bugfix, size/m

#5529 refactor(core): update user context type
  packages/console/src/components/ItemPreview/UserPreview.tsx
  packages/console/src/components/UserAccountInformation/index.tsx
  packages/console/src/pages/Roles/components/AssignToRoleModal/index.tsx
  packages/console/src/pages/UserDetails/utils.ts
  packages/console/src/utils/user.ts
  packages/core/src/libraries/jwt-customizer.ts
  packages/core/src/libraries/scope.ts
  packages/core/src/routes/role.scope.ts
  packages/core/src/tenants/Libraries.ts
  packages/schemas/src/types/jwt-customizer.ts
  packages/schemas/src/types/user.ts
Labels: enhancement, size/m

#5524 chore(schemas): remove deprecated `prune:logs` scope
  packages/schemas/src/seeds/cloud-api.ts
Labels: chore, size/xs

#5525 feat(core): add POST /configs/jwt-customizer/test API
  packages/core/package.json
  packages/core/src/routes/logto-config.openapi.json
  packages/core/src/routes/logto-config.ts
  packages/core/src/routes/swagger/index.ts
  packages/core/src/routes/swagger/utils/general.ts
  packages/schemas/src/types/jwt-customizer.ts
  pnpm-lock.yaml
Labels: feature, size/m

#5532 feat(console): integrate jwt customizer test api
  packages/console/src/pages/JwtClaims/MonacoCodeEditor/index.tsx
  packages/console/src/pages/JwtClaims/MonacoCodeEditor/use-editor-height.ts
  packages/console/src/pages/JwtClaims/SettingsSection/TestTab.tsx
  packages/console/src/pages/JwtClaims/SettingsSection/index.module.scss
  packages/console/src/pages/JwtClaims/utils/config.tsx
  packages/console/src/pages/JwtClaims/utils/format.ts
  packages/core/src/libraries/cloud-connection.ts
  packages/core/src/routes/logto-config.ts
Labels: feature, size/m

#5501 feat(console): add tenant member and invitation lists
  packages/console/package.json
  packages/console/src/assets/icons/invitation.svg
  packages/console/src/assets/icons/members.svg
  packages/console/src/cloud/hooks/use-cloud-api.ts
  packages/console/src/cloud/types/router.ts
  packages/console/src/components/ItemPreview/UserPreview.tsx
  packages/console/src/consts/page-tabs.ts
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/EditMemberModal/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/Invitations/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/Members/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/index.module.scss
  packages/console/src/pages/TenantSettings/TenantMembers/index.tsx
  packages/console/src/pages/TenantSettings/index.tsx
  packages/console/src/utils/user.ts
  packages/toolkit/core-kit/scss/_console-themes.scss
  pnpm-lock.yaml
Labels: feature, size/xl

#5535 chore: update README.md
  README.md
Labels: chore, size/xs

#5526 feat: return and store social connector raw data
  .changeset/gentle-shoes-push.md
  .changeset/new-tables-breathe.md
  .changeset/olive-cycles-sip.md
  .changeset/wild-hotels-drop.md
  .gitpod.yml
  package.json
  packages/connectors/connector-alipay-native/src/index.test.ts
  packages/connectors/connector-alipay-native/src/index.ts
  packages/connectors/connector-alipay-web/src/index.test.ts
  packages/connectors/connector-alipay-web/src/index.ts
  packages/connectors/connector-apple/src/index.test.ts
  packages/connectors/connector-apple/src/index.ts
  packages/connectors/connector-azuread/package.json
  packages/connectors/connector-azuread/src/index.test.ts
  packages/connectors/connector-azuread/src/index.ts
  packages/connectors/connector-discord/src/index.test.ts
  packages/connectors/connector-discord/src/index.ts
  packages/connectors/connector-facebook/src/index.test.ts
  packages/connectors/connector-facebook/src/index.ts
  packages/connectors/connector-feishu-web/src/index.test.ts
  packages/connectors/connector-feishu-web/src/index.ts
  packages/connectors/connector-github/src/index.test.ts
  packages/connectors/connector-github/src/index.ts
  packages/connectors/connector-google/src/index.test.ts
  packages/connectors/connector-google/src/index.ts
  packages/connectors/connector-kakao/src/index.test.ts
  packages/connectors/connector-kakao/src/index.ts
  packages/connectors/connector-mock-social/src/index.ts
  packages/connectors/connector-naver/src/index.test.ts
  packages/connectors/connector-naver/src/index.ts
  packages/connectors/connector-oauth2/src/index.test.ts
  packages/connectors/connector-oauth2/src/index.ts
  packages/connectors/connector-oidc/src/index.test.ts
  packages/connectors/connector-oidc/src/index.ts
  packages/connectors/connector-wechat-native/src/index.test.ts
  packages/connectors/connector-wechat-native/src/index.ts
  packages/connectors/connector-wechat-web/src/index.test.ts
  packages/connectors/connector-wechat-web/src/index.ts
  packages/connectors/connector-wecom/src/index.test.ts
  packages/connectors/connector-wecom/src/index.ts
  packages/connectors/templates/sync-preset.js
  packages/integration-tests/src/constants.ts
  packages/integration-tests/src/tests/api/admin-user.test.ts
  packages/integration-tests/src/tests/api/interaction/social-interaction/happy-path.test.ts
  packages/schemas/src/foundations/jsonb-types/index.ts
  packages/toolkit/connector-kit/src/index.ts
  packages/toolkit/connector-kit/src/types/social.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#5530 feat: add oidc standard claims to user
  .changeset/grumpy-seas-begin.md
  .github/workflows/commitlint.yml
  packages/core/src/__mocks__/user.ts
  packages/core/src/libraries/hook/utils.ts
  packages/core/src/oidc/scope.test.ts
  packages/core/src/oidc/scope.ts
  packages/core/src/queries/user.test.ts
  packages/core/src/routes/admin-user/basic.openapi.json
  packages/core/src/routes/admin-user/basics.ts
  packages/integration-tests/src/api/admin-user.ts
  packages/integration-tests/src/helpers/index.ts
  packages/integration-tests/src/tests/api/admin-user.test.ts
  packages/phrases-experience/src/locales/de/user-scopes.ts
  packages/phrases-experience/src/locales/en/user-scopes.ts
  packages/phrases-experience/src/locales/es/user-scopes.ts
  packages/phrases-experience/src/locales/fr/user-scopes.ts
  packages/phrases-experience/src/locales/it/user-scopes.ts
  packages/phrases-experience/src/locales/ja/user-scopes.ts
  packages/phrases-experience/src/locales/ko/user-scopes.ts
  packages/phrases-experience/src/locales/pl-pl/user-scopes.ts
  packages/phrases-experience/src/locales/pt-br/user-scopes.ts
  packages/phrases-experience/src/locales/pt-pt/user-scopes.ts
  packages/phrases-experience/src/locales/ru/user-scopes.ts
  packages/phrases-experience/src/locales/tr-tr/user-scopes.ts
  packages/phrases-experience/src/locales/zh-cn/user-scopes.ts
  packages/phrases-experience/src/locales/zh-hk/user-scopes.ts
  packages/phrases-experience/src/locales/zh-tw/user-scopes.ts
  packages/schemas/alterations/next-1710859622-add-oidc-standard-claim-properties.ts
  packages/schemas/src/foundations/jsonb-types/users.ts
  packages/schemas/src/types/organization.ts
  packages/schemas/src/types/user.ts
  packages/schemas/src/utils/zod.ts
  packages/schemas/tables/_functions.sql
  packages/schemas/tables/users.sql
  packages/toolkit/core-kit/src/openid.ts
Labels: feature, size/xl

#5538 style(console): fix the jwt test panel layout
  packages/console/src/pages/JwtClaims/SettingsSection/TestTab.tsx
  packages/console/src/pages/JwtClaims/SettingsSection/index.module.scss
  packages/console/src/pages/JwtClaims/index.module.scss
  packages/console/src/pages/JwtClaims/utils/format.ts
Labels: size/s

#5517 refactor(core): remove unused mark mfa skip function
  packages/core/src/routes/interaction/verifications/mfa-verification.ts
Labels: enhancement, size/s

#5542 chore(schemas): add comments for `ReservedPlanId`
  packages/schemas/src/consts/subscriptions.ts
Labels: chore, size/s

#5543 refactor(console): extract shared quota between featured plan and comparison table
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/FeaturedPlanContent/use-featured-plan-content.ts
  packages/console/src/consts/subscriptions.ts
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/index.tsx
Labels: enhancement, size/s

#5544 refactor(console): avoid nested modal content for role creation
  packages/console/src/pages/Roles/components/CreateRoleModal/index.tsx
Labels: enhancement, size/s

#5508 feat(core): add the support on custom JWT feature
  packages/core/src/libraries/cloud-connection.ts
  packages/core/src/libraries/logto-config.ts
  packages/core/src/oidc/init.test.ts
  packages/core/src/oidc/init.ts
  packages/core/src/routes/logto-config.openapi.json
  packages/core/src/routes/logto-config.test.ts
  packages/core/src/routes/logto-config.ts
  packages/core/src/tenants/Tenant.ts
  packages/schemas/src/foundations/jsonb-types/users.ts
  pnpm-lock.yaml
Labels: feature, size/m

#5547 refactor(schemas,core,console): skip onboarding if user has pending invitations
  packages/console/src/onboarding/hooks/use-user-onboarding-data.ts
  packages/console/src/onboarding/pages/Welcome/index.tsx
  packages/console/src/onboarding/pages/Welcome/options.tsx
  packages/console/src/onboarding/types.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/schemas/src/types/index.ts
  packages/schemas/src/types/onboarding.ts
Labels: enhancement, size/m

#5546 refactor(phrases,core,console): update API and console error handling/display
  packages/console/src/pages/JwtClaims/SettingsSection/TestTab.tsx
  packages/core/src/routes/logto-config.ts
  packages/phrases/src/locales/de/errors/index.ts
  packages/phrases/src/locales/de/errors/jwt-customizer.ts
  packages/phrases/src/locales/en/errors/index.ts
  packages/phrases/src/locales/en/errors/jwt-customizer.ts
  packages/phrases/src/locales/es/errors/index.ts
  packages/phrases/src/locales/es/errors/jwt-customizer.ts
  packages/phrases/src/locales/fr/errors/index.ts
  packages/phrases/src/locales/fr/errors/jwt-customizer.ts
  packages/phrases/src/locales/it/errors/index.ts
  packages/phrases/src/locales/it/errors/jwt-customizer.ts
  packages/phrases/src/locales/ja/errors/index.ts
  packages/phrases/src/locales/ja/errors/jwt-customizer.ts
  packages/phrases/src/locales/ko/errors/index.ts
  packages/phrases/src/locales/ko/errors/jwt-customizer.ts
  packages/phrases/src/locales/pl-pl/errors/index.ts
  packages/phrases/src/locales/pl-pl/errors/jwt-customizer.ts
  packages/phrases/src/locales/pt-br/errors/index.ts
  packages/phrases/src/locales/pt-br/errors/jwt-customizer.ts
  packages/phrases/src/locales/pt-pt/errors/index.ts
  packages/phrases/src/locales/pt-pt/errors/jwt-customizer.ts
  packages/phrases/src/locales/ru/errors/index.ts
  packages/phrases/src/locales/ru/errors/jwt-customizer.ts
  packages/phrases/src/locales/tr-tr/errors/index.ts
  packages/phrases/src/locales/tr-tr/errors/jwt-customizer.ts
  packages/phrases/src/locales/zh-cn/errors/index.ts
  packages/phrases/src/locales/zh-cn/errors/jwt-customizer.ts
  packages/phrases/src/locales/zh-hk/errors/index.ts
  packages/phrases/src/locales/zh-hk/errors/jwt-customizer.ts
  packages/phrases/src/locales/zh-tw/errors/index.ts
  packages/phrases/src/locales/zh-tw/errors/jwt-customizer.ts
Labels: enhancement, size/m

#5552 fix(core): fix the post domains api error status code
  packages/core/src/routes/domain.ts
Labels: bugfix, size/xs

#5548 chore: bump @logto dependencies
  packages/connectors/connector-logto-email/package.json
  packages/connectors/connector-logto-email/src/index.ts
  packages/console/package.json
  packages/core/package.json
  packages/demo-app/package.json
  packages/integration-tests/package.json
  pnpm-lock.yaml
Labels: chore, size/s

#5553 chore(phrases): add i18n phrases for console invitation interim pages
  packages/phrases/src/locales/de/translation/admin-console/general.ts
  packages/phrases/src/locales/de/translation/admin-console/index.ts
  packages/phrases/src/locales/de/translation/admin-console/invitation.ts
  packages/phrases/src/locales/en/translation/admin-console/general.ts
  packages/phrases/src/locales/en/translation/admin-console/index.ts
  packages/phrases/src/locales/en/translation/admin-console/invitation.ts
  packages/phrases/src/locales/es/translation/admin-console/general.ts
  packages/phrases/src/locales/es/translation/admin-console/index.ts
  packages/phrases/src/locales/es/translation/admin-console/invitation.ts
  packages/phrases/src/locales/fr/translation/admin-console/general.ts
  packages/phrases/src/locales/fr/translation/admin-console/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/invitation.ts
  packages/phrases/src/locales/it/translation/admin-console/general.ts
  packages/phrases/src/locales/it/translation/admin-console/index.ts
  packages/phrases/src/locales/it/translation/admin-console/invitation.ts
  packages/phrases/src/locales/ja/translation/admin-console/general.ts
  packages/phrases/src/locales/ja/translation/admin-console/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/invitation.ts
  packages/phrases/src/locales/ko/translation/admin-console/general.ts
  packages/phrases/src/locales/ko/translation/admin-console/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/invitation.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/general.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/invitation.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/invitation.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/invitation.ts
  packages/phrases/src/locales/ru/translation/admin-console/general.ts
  packages/phrases/src/locales/ru/translation/admin-console/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/invitation.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/invitation.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/invitation.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/invitation.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/invitation.ts
Labels: chore, size/l

#5550 refactor(console): reorg sidebar menu items
  packages/console/src/containers/ConsoleContent/Sidebar/hook.tsx
  packages/phrases/src/locales/de/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/en/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/es/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/fr/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/it/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/ja/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/ko/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/ru/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tab-sections.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tab-sections.ts
Labels: enhancement, size/m

#5555 fix(core,phrases): fix custom JWT PUT API block admin tenant logic
  packages/core/src/routes/logto-config.ts
  packages/phrases/src/locales/de/errors/jwt-customizer.ts
  packages/phrases/src/locales/en/errors/jwt-customizer.ts
  packages/phrases/src/locales/es/errors/jwt-customizer.ts
  packages/phrases/src/locales/fr/errors/jwt-customizer.ts
  packages/phrases/src/locales/it/errors/jwt-customizer.ts
  packages/phrases/src/locales/ja/errors/jwt-customizer.ts
  packages/phrases/src/locales/ko/errors/jwt-customizer.ts
  packages/phrases/src/locales/pl-pl/errors/jwt-customizer.ts
  packages/phrases/src/locales/pt-br/errors/jwt-customizer.ts
  packages/phrases/src/locales/pt-pt/errors/jwt-customizer.ts
  packages/phrases/src/locales/ru/errors/jwt-customizer.ts
  packages/phrases/src/locales/tr-tr/errors/jwt-customizer.ts
  packages/phrases/src/locales/zh-cn/errors/jwt-customizer.ts
  packages/phrases/src/locales/zh-hk/errors/jwt-customizer.ts
  packages/phrases/src/locales/zh-tw/errors/jwt-customizer.ts
Labels: bugfix, size/s

#5536 feat: support direct sign-in
  .changeset/hip-ladybugs-fry.md
  .changeset/nasty-beds-flash.md
  .changeset/rude-radios-clean.md
  .changeset/smart-walls-occur.md
  packages/console/src/pages/Callback/index.tsx
  packages/core/src/libraries/verification-status.ts
  packages/core/src/oidc/init.ts
  packages/core/src/oidc/type.ts
  packages/core/src/oidc/utils.test.ts
  packages/core/src/oidc/utils.ts
  packages/core/src/routes/consts.ts
  packages/core/src/tenants/Tenant.ts
  packages/demo-app/src/App.tsx
  packages/experience/src/App.tsx
  packages/experience/src/__mocks__/RenderWithPageContext/SettingsProvider.tsx
  packages/experience/src/constants/env.ts
  packages/experience/src/hooks/use-check-single-sign-on.ts
  packages/experience/src/hooks/use-single-sign-on-watch.ts
  packages/experience/src/pages/Callback/index.tsx
  packages/experience/src/pages/Callback/use-social-callback-handler.ts
  packages/experience/src/pages/DirectSignIn/index.test.tsx
  packages/experience/src/pages/DirectSignIn/index.tsx
  packages/experience/src/pages/Register/IdentifierRegisterForm/index.test.tsx
  packages/experience/src/pages/SignIn/IdentifierSignInForm/index.test.tsx
  packages/experience/src/pages/SignIn/PasswordSignInForm/index.test.tsx
  packages/experience/src/pages/SocialSignInWebCallback/SingleSignOn.tsx
  packages/experience/src/pages/SocialSignInWebCallback/SocialSignIn.tsx
  packages/experience/src/pages/SocialSignInWebCallback/index.test.tsx
  packages/experience/src/pages/SocialSignInWebCallback/index.tsx
  packages/experience/src/pages/SocialSignInWebCallback/use-single-sign-on-listener.ts
  packages/experience/src/pages/SocialSignInWebCallback/use-social-sign-in-listener.ts
  packages/integration-tests/src/client/index.ts
  packages/integration-tests/src/helpers/client.ts
  packages/integration-tests/src/tests/api/interaction/social-sign-in/happy-path.test.ts
  packages/integration-tests/src/tests/api/interaction/social-sign-in/sad-path.test.ts
  packages/integration-tests/src/tests/experience/direct-sign-in.test.ts
  packages/integration-tests/src/tests/experience/password-policy.test.ts
  packages/integration-tests/src/ui-helpers/expect-experience.ts
  packages/schemas/src/consts/experience.ts
  packages/schemas/src/consts/index.ts
  packages/schemas/src/consts/oidc.ts
  packages/toolkit/core-kit/package.json
  packages/toolkit/core-kit/src/password-policy.ts
  packages/toolkit/core-kit/src/utils/integration-test.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#5531 feat(console): invite members dialog
  packages/console/src/pages/TenantSettings/TenantMembers/EditMemberModal/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/Invitations/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/InviteEmailsInput/index.module.scss
  packages/console/src/pages/TenantSettings/TenantMembers/InviteEmailsInput/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/InviteEmailsInput/utils.ts
  packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/types.ts
  packages/phrases/src/locales/de/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/en/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/es/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/fr/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/it/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/ja/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/ko/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/ru/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tenant-members.ts
Labels: feature, size/xl

#5554 feat(console): add console landing page to accept user invitation
  packages/console/src/App.tsx
  packages/console/src/cloud/AppRoutes.tsx
  packages/console/src/cloud/types/router.ts
  packages/console/src/contexts/TenantsProvider.tsx
  packages/console/src/pages/AcceptInvitation/SwitchAccount/index.module.scss
  packages/console/src/pages/AcceptInvitation/SwitchAccount/index.tsx
  packages/console/src/pages/AcceptInvitation/index.tsx
Labels: feature, size/m

#5545 chore(deps): update packges
  packages/connectors/templates/package.json
  packages/connectors/templates/preset/rollup.config.js
  packages/integration-tests/package.json
  packages/integration-tests/src/tests/console/applications/index.test.ts
  packages/integration-tests/src/tests/console/bootstrap.test.ts
  packages/integration-tests/src/tests/console/sign-in-experience/branding.test.ts
  packages/integration-tests/src/tests/console/sign-in-experience/sign-up-and-sign-in/happy-path.test.ts
  packages/integration-tests/src/tests/console/sign-in-experience/sign-up-and-sign-in/helpers.ts
  packages/integration-tests/src/tests/console/user-management.test.ts
  pnpm-lock.yaml
Labels: chore, size/s

#5540 feat(core,schemas): add new Azure OIDC SSO connector
  packages/core/src/sso/AzureAdSsoConnector/index.ts
  packages/core/src/sso/AzureOidcSsoConnector/index.ts
  packages/core/src/sso/OidcConnector/index.ts
  packages/core/src/sso/index.ts
  packages/schemas/src/types/sso-connector.ts
Labels: feature, size/m

#5541 refactor(core,schemas): refactor the sso connector factory type
  packages/core/src/routes/interaction/utils/single-sign-on-session.ts
  packages/core/src/routes/interaction/utils/single-sign-on.test.ts
  packages/core/src/routes/interaction/utils/single-sign-on.ts
  packages/core/src/routes/sso-connector/utils.test.ts
  packages/core/src/routes/sso-connector/utils.ts
  packages/core/src/sso/AzureAdSsoConnector/index.ts
  packages/core/src/sso/AzureOidcSsoConnector/index.ts
  packages/core/src/sso/GoogleWorkspaceSsoConnector/index.ts
  packages/core/src/sso/OidcSsoConnector/index.ts
  packages/core/src/sso/OktaSsoConnector/index.ts
  packages/core/src/sso/SamlSsoConnector/index.ts
  packages/core/src/sso/index.ts
  packages/core/src/sso/types/connector.ts
  packages/core/src/sso/types/index.ts
  packages/core/src/sso/types/session.ts
  packages/core/src/utils/saml-assertion-handler.ts
  packages/schemas/src/types/sso-connector.ts
Labels: enhancement, size/m

#5549 refactor(console): refactor useApi
  packages/console/src/hooks/use-api.ts
Labels: enhancement, size/s

#5551 refactor(console): refactor sso detail pages
  packages/console/src/pages/EnterpriseSso/SsoCreationModal/index.tsx
  packages/console/src/pages/EnterpriseSso/types.ts
  packages/console/src/pages/EnterpriseSsoDetails/Connection/BasicInfo/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/Connection/OidcConnectorForm.tsx
  packages/console/src/pages/EnterpriseSsoDetails/Connection/OidcMetadataForm/ParsedConfigPreview/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/Connection/OidcMetadataForm/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/Connection/SamlAttributeMapping/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/Connection/SamlConnectorForm.tsx
  packages/console/src/pages/EnterpriseSsoDetails/Connection/SamlMetadataForm/ParsedConfigPreview/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/Connection/SamlMetadataForm/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/Connection/ServiceProviderInfo/OidcConnectorSpInfo.tsx
  packages/console/src/pages/EnterpriseSsoDetails/Connection/ServiceProviderInfo/SamlConnectorSpInfo.tsx
  packages/console/src/pages/EnterpriseSsoDetails/Connection/ServiceProviderInfo/index.module.scss
  packages/console/src/pages/EnterpriseSsoDetails/Connection/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/config.ts
  packages/console/src/pages/EnterpriseSsoDetails/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/types/oidc.ts
  packages/console/src/pages/EnterpriseSsoDetails/types/saml.ts
  packages/console/src/pages/EnterpriseSsoDetails/use-delete-connector.ts
  packages/phrases/src/locales/de/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/en/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/es/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/fr/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/it/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/ja/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/ko/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/ru/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/upsell/paywall.ts
Labels: enhancement, size/xl

#5564 style(console): fix the color code white css
  packages/console/src/scss/_code-editor.scss
Labels: size/xs

#5561 fix(console,phrases): api resource indicator should be a valid absolute uri
  .changeset/hungry-dodos-do.md
  packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/en/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/es/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/fr/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/it/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/ja/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/ko/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/ru/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/api-resources.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/api-resources.ts
Labels: bugfix, size/s

#5557 chore(schemas): update customJwtFetcherGuard to specify custom jwt use case
  packages/schemas/src/types/jwt-customizer.ts
Labels: chore, size/s

#5563 fix(console): fix jwt test context code editor bug
  packages/console/src/pages/JwtClaims/SettingsSection/TestTab.tsx
  packages/console/src/pages/JwtClaims/utils/config.tsx
Labels: bugfix, size/s

#5566 fix(console): fix the zod-to-ts type infer bug
  packages/console/scripts/generate-jwt-customizer-type-definition.ts
Labels: bugfix, size/s

#5560 feat(console): implement interim landing page for new users to join invited tenants
  packages/connectors/connector-logto-email/package.json
  packages/console/package.json
  packages/console/src/cloud/pages/Main/InvitationList/index.module.scss
  packages/console/src/cloud/pages/Main/InvitationList/index.tsx
  packages/console/src/cloud/pages/Main/index.tsx
  packages/console/src/cloud/types/router.ts
  packages/console/src/hooks/use-user-invitations.ts
  packages/console/src/pages/AcceptInvitation/SwitchAccount/index.module.scss
  packages/console/src/pages/AcceptInvitation/index.tsx
  packages/core/package.json
  pnpm-lock.yaml
Labels: feature, size/m

#5567 feat(console): support permission editing
  packages/console/src/components/PermissionsTable/EditPermissionModal.tsx
  packages/console/src/components/PermissionsTable/index.module.scss
  packages/console/src/components/PermissionsTable/index.tsx
  packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/index.tsx
  packages/console/src/pages/RoleDetails/RolePermissions/index.tsx
  packages/integration-tests/src/tests/console/rbac/helper.ts
  packages/integration-tests/src/tests/console/rbac/machime-to-machime-rbac.test.ts
  packages/integration-tests/src/tests/console/rbac/user-rbac.test.ts
  packages/phrases/src/locales/de/translation/admin-console/permissions.ts
  packages/phrases/src/locales/en/translation/admin-console/permissions.ts
  packages/phrases/src/locales/es/translation/admin-console/permissions.ts
  packages/phrases/src/locales/fr/translation/admin-console/permissions.ts
  packages/phrases/src/locales/it/translation/admin-console/permissions.ts
  packages/phrases/src/locales/ja/translation/admin-console/permissions.ts
  packages/phrases/src/locales/ko/translation/admin-console/permissions.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/permissions.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/permissions.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/permissions.ts
  packages/phrases/src/locales/ru/translation/admin-console/permissions.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/permissions.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/permissions.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/permissions.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/permissions.ts
Labels: feature, size/xl

#5558 chore(schemas,core): update custom JWT sample token payload guard
  packages/console/src/pages/JwtClaims/utils/config.tsx
  packages/core/src/oidc/init.ts
  packages/schemas/src/types/logto-config/oidc-provider.ts
Labels: chore, size/m

#5571 refactor(console): update tenant settings access per user tenant scopes
  packages/console/src/components/ActionsButton/index.tsx
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/hooks/use-current-tenant-scopes.ts
  packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/Invitations/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/Members/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/index.tsx
  packages/console/src/pages/TenantSettings/index.tsx
Labels: enhancement, size/l

#5574 refactor: remove jest (partially)
  packages/app-insights/jest.config.js
  packages/app-insights/package.json
  packages/app-insights/src/normalize-error.test.ts
  packages/app-insights/tsconfig.json
  packages/app-insights/tsconfig.test.json
  packages/cli/jest.config.js
  packages/cli/package.json
  packages/cli/src/commands/database/alteration/index.test.ts
  packages/cli/src/include.d/import-meta.d.ts
  packages/cli/src/queries/system.test.ts
  packages/cli/src/test-utils.ts
  packages/cli/tsconfig.json
  packages/cli/tsconfig.test.json
  packages/integration-tests/src/tests/api/admin-user.test.ts
  packages/integration-tests/src/tests/api/interaction/register-with-identifier/happy-path.test.ts
  packages/schemas/jest.config.js
  packages/schemas/package.json
  packages/schemas/src/gen/utils.test.ts
  packages/schemas/src/utils/domain.test.ts
  packages/schemas/tsconfig.test.json
  packages/shared/jest.config.js
  packages/shared/package.json
  packages/shared/src/esm/module-proxy.ts
  packages/shared/src/include.d/import-meta.d.ts
  packages/shared/src/node/env/UrlSet.test.ts
  packages/shared/src/utils/id.test.ts
  packages/shared/src/utils/sub-domain.test.ts
  packages/shared/src/utils/ttl-cache.test.ts
  packages/shared/src/utils/user-display-name.test.ts
  packages/shared/tsconfig.json
  packages/shared/tsconfig.test.json
  packages/toolkit/connector-kit/jest.config.js
  packages/toolkit/connector-kit/package.json
  packages/toolkit/connector-kit/src/index.test.ts
  packages/toolkit/connector-kit/tsconfig.test.json
  packages/toolkit/core-kit/jest.config.js
  packages/toolkit/core-kit/jest.setup.js
  packages/toolkit/core-kit/package.json
  packages/toolkit/core-kit/src/password-policy.test.ts
  packages/toolkit/core-kit/src/regex.test.ts
  packages/toolkit/core-kit/src/utils/url.test.ts
  packages/toolkit/core-kit/tsconfig.test.json
  packages/toolkit/language-kit/jest.config.js
  packages/toolkit/language-kit/package.json
  packages/toolkit/language-kit/src/utility.test.ts
  packages/toolkit/language-kit/tsconfig.test.json
  pnpm-lock.yaml
Labels: enhancement, size/l

#5565 test: add integration tests for jwt
  packages/integration-tests/src/tests/api/oidc/get-access-token.test.ts
Labels: testing, size/s

#5578 refactor(schemas): remove invite member scope from tenant member role
  packages/schemas/alterations/next-1711607772-remove-invite-member-scope-from-tenant-member-role.ts
  packages/schemas/src/types/tenant-organization.ts
Labels: enhancement, size/s

#5583 chore: add comments for cloud seed data
  packages/cli/src/commands/database/seed/tables.ts
Labels: chore, size/xs

#5582 feat(schemas): add new scope read:member to both tenant admin and member roles
  packages/schemas/alterations/next-1711624564-add-read-member-scope-to-tenant-roles.ts
  packages/schemas/src/types/tenant-organization.ts
Labels: feature, size/s

#5581 fix(console,phrases): should check duplicated emails when inviting members
  packages/console/src/pages/TenantSettings/TenantMembers/InviteEmailsInput/hooks.ts
  packages/console/src/pages/TenantSettings/TenantMembers/InviteEmailsInput/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/InviteEmailsInput/utils.ts
  packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/en/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/es/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/fr/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/it/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/ja/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/ko/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/ru/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tenant-members.ts
Labels: bugfix, size/m

#5573 fix(console): revert the custom jwt forms overflow hidden
  packages/console/src/pages/JwtClaims/SettingsSection/TestTab.tsx
  packages/console/src/pages/JwtClaims/SettingsSection/index.module.scss
  packages/console/src/pages/JwtClaims/index.module.scss
Labels: bugfix, size/s

#5585 chore: update cloud version and the way to call cloud custom JWT API
  packages/connectors/connector-logto-email/package.json
  packages/console/package.json
  packages/core/package.json
  packages/core/src/oidc/init.ts
  packages/core/src/routes/logto-config.ts
  packages/schemas/src/types/jwt-customizer.ts
  pnpm-lock.yaml
Labels: chore, size/m

#5570 feat(schemas): add util method to convert admin tenant org id to user tenant id
  packages/schemas/src/types/tenant-organization.ts
Labels: feature, size/xs

#5589 feat: support direct sign-in for sso
  .changeset/great-peaches-work.md
  packages/experience/src/pages/DirectSignIn/index.test.tsx
  packages/experience/src/pages/DirectSignIn/index.tsx
  packages/integration-tests/src/tests/experience/direct-sign-in.test.ts
  packages/integration-tests/src/ui-helpers/expect-experience.ts
  packages/schemas/src/consts/oidc.ts
Labels: feature, size/m

#5595 chore(core): update GET /configs/jwt-customizer/:tokenPath API error handling
  packages/core/src/libraries/logto-config.ts
  packages/integration-tests/src/tests/api/logto-config.test.ts
Labels: chore, size/s

#5593 fix(console): refresh invitation list after inviting members
  packages/console/src/pages/TenantSettings/TenantMembers/Invitations/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/Members/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/index.tsx
Labels: bugfix, size/s

#5597 test: add tests for username case sensitive
  packages/integration-tests/src/tests/api/admin-user.username-case.test.ts
Labels: testing, size/s
