Repository logto-io/logto, pull requests merged in 2024-02, with the labels that each got.

#5359 refactor(phrases): update category name in app creation modal for protected app
  packages/phrases/src/locales/de/translation/admin-console/guide.ts
  packages/phrases/src/locales/en/translation/admin-console/guide.ts
  packages/phrases/src/locales/es/translation/admin-console/guide.ts
  packages/phrases/src/locales/fr/translation/admin-console/guide.ts
  packages/phrases/src/locales/it/translation/admin-console/guide.ts
  packages/phrases/src/locales/ja/translation/admin-console/guide.ts
  packages/phrases/src/locales/ko/translation/admin-console/guide.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/guide.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/guide.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/guide.ts
  packages/phrases/src/locales/ru/translation/admin-console/guide.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/guide.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/guide.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/guide.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/guide.ts
Labels: enhancement, size/s

#5361 refactor(core): use deepmerge
  packages/app-insights/package.json
  packages/cli/package.json
  packages/connectors/templates/package.json
  packages/console/package.json
  packages/core/package.json
  packages/core/src/utils/SchemaRouter.ts
  packages/experience/package.json
  packages/integration-tests/package.json
  packages/phrases-experience/package.json
  packages/phrases/package.json
  packages/schemas/package.json
  packages/shared/package.json
  packages/toolkit/connector-kit/package.json
  packages/toolkit/core-kit/package.json
  pnpm-lock.yaml
Labels: enhancement, size/s

#5348 feat(core): add third-party application creation quota guard
  packages/core/package.json
  packages/core/src/libraries/quota.ts
  packages/core/src/queries/application.ts
  packages/core/src/routes/applications/application.ts
  pnpm-lock.yaml
Labels: feature, size/s

#5360 fix(console): add default value for custom auth rules in protected app details
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/index.tsx
Labels: bugfix, size/xs

#5362 fix(console): fix domain items vertical spacing in get-started page
  packages/console/src/pages/GetStarted/ProtectedAppCreationForm/index.module.scss
Labels: bugfix, size/xs

#5363 chore(phrases): update wording in protected app pages
  packages/console/src/ds-components/Tip/TipBubble/index.module.scss
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/index.module.scss
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/application-details.ts
  packages/phrases/src/locales/de/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/es/translation/admin-console/application-details.ts
  packages/phrases/src/locales/es/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/it/translation/admin-console/application-details.ts
  packages/phrases/src/locales/it/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/ja/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/ru/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/protected-app.ts
Labels: chore, size/m

#5356 fix(console): upsell should locate on modal footer
  packages/console/src/pages/EnterpriseSso/index.tsx
Labels: bugfix, size/s

#5367 feat(console): add endpoints and credentials section to protected app details
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/EndpointsAndCredentials.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Settings.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/es/translation/admin-console/application-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/it/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/application-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts
Labels: feature, size/m

#5365 fix(console): block subsequent requests on deleting apps
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
Labels: bugfix, size/xs

#5366 feat(console,core): remove devFeature guard
  packages/console/src/components/Guide/hooks.ts
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/EndpointsAndCredentials.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
  packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
  packages/console/src/pages/Applications/hooks/use-legacy-application-data.ts
  packages/console/src/pages/Applications/index.tsx
  packages/core/src/middleware/koa-auto-consent.ts
  packages/core/src/oidc/adapter.ts
  packages/core/src/oidc/grants/refresh-token.ts
  packages/core/src/oidc/init.ts
  packages/core/src/routes/applications/application.ts
  packages/core/src/routes/applications/types.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/interaction/consent.ts
  packages/core/src/routes/organization/index.ts
  packages/core/src/routes/system.ts
Labels: feature, size/m

#5370 fix(phrases): profile should include username
  packages/phrases-experience/src/locales/de/user-scopes.ts
  packages/phrases-experience/src/locales/en/user-scopes.ts
  packages/phrases-experience/src/locales/es/user-scopes.ts
  packages/phrases-experience/src/locales/fr/user-scopes.ts
  packages/phrases-experience/src/locales/it/user-scopes.ts
  packages/phrases-experience/src/locales/ja/user-scopes.ts
  packages/phrases-experience/src/locales/ko/user-scopes.ts
  packages/phrases-experience/src/locales/pl-pl/user-scopes.ts
  packages/phrases-experience/src/locales/pt-br/user-scopes.ts
  packages/phrases-experience/src/locales/pt-pt/user-scopes.ts
  packages/phrases-experience/src/locales/ru/user-scopes.ts
  packages/phrases-experience/src/locales/tr-tr/user-scopes.ts
  packages/phrases-experience/src/locales/zh-cn/user-scopes.ts
  packages/phrases-experience/src/locales/zh-hk/user-scopes.ts
  packages/phrases-experience/src/locales/zh-tw/user-scopes.ts
Labels: bugfix, size/s

#5372 refactor(console): update import paths and type annotations in Python app guide
  packages/console/src/assets/docs/guides/api-python/README.mdx
  packages/console/src/assets/docs/guides/web-python/README.mdx
Labels: enhancement, size/s

#5374 feat(console): add third-party doc links
  packages/console/src/consts/external-links.ts
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
Labels: feature, size/s

#5373 refactor(console): update the flutter guide
  packages/console/src/assets/docs/guides/native-flutter/README.mdx
Labels: enhancement, size/m

#5368 chore(console): remove dev features flag from console client
  packages/console/src/consts/env.ts
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/index.tsx
  packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
  packages/console/src/pages/Applications/components/ProtectedAppForm/index.tsx
  packages/console/src/pages/GetStarted/index.tsx
Labels: chore, size/s

#5379 fix(console): protected app form field background should exclude error message
  packages/console/src/ds-components/TextInput/index.tsx
  packages/console/src/pages/Applications/components/ProtectedAppForm/index.tsx
Labels: bugfix, size/xs

#5344 chore(core): update api doc for create protected app
  packages/core/src/routes/applications/application.openapi.json
Labels: chore, size/s

#5375 feat(console): add .NET Blzor server tutorial
  .changeset/poor-laws-do.md
  packages/console/src/assets/docs/guides/index.ts
  packages/console/src/assets/docs/guides/web-dotnet-core-blazor-server/README.mdx
  packages/console/src/assets/docs/guides/web-dotnet-core-blazor-server/config.json
  packages/console/src/assets/docs/guides/web-dotnet-core-blazor-server/index.ts
  packages/console/src/assets/docs/guides/web-dotnet-core-blazor-server/logo.svg
  packages/console/src/assets/docs/guides/web-dotnet-core-mvc/README.mdx
  packages/console/src/assets/docs/guides/web-dotnet-core-mvc/config.json
  packages/console/src/assets/docs/guides/web-dotnet-core-mvc/index.ts
  packages/console/src/assets/docs/guides/web-dotnet-core-mvc/logo.svg
  packages/console/src/assets/docs/guides/web-dotnet-core/README.mdx
  packages/console/src/assets/docs/guides/web-dotnet-core/config.json
  packages/console/src/assets/docs/guides/web-dotnet-core/index.ts
  packages/console/src/assets/docs/guides/web-dotnet-core/logo.svg
  packages/console/src/components/Guide/index.module.scss
Labels: feature, size/l

#5378 refactor(console): update react and vue sdk integration guides
  packages/console/src/assets/docs/guides/spa-react/README.mdx
  packages/console/src/assets/docs/guides/spa-vue/README.mdx
  packages/console/src/assets/docs/guides/web-express/README.mdx
  packages/console/src/assets/docs/guides/web-next/README.mdx
  packages/console/src/mdx-components/Steps/FurtherReadings.tsx
  packages/console/src/mdx-components/Steps/index.tsx
Labels: enhancement, size/m

#5389 fix(console,phrases): improve error handling when user associated app is removed
  .changeset/silent-windows-behave.md
  packages/console/src/components/ApplicationName/index.tsx
  packages/console/src/hooks/use-swr-options.ts
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/use-application-sign-in-experience-swr.ts
  packages/console/src/pages/SignInExperience/PageContent/Content/LanguagesForm/ManageLanguage/LanguageEditor/LanguageDetails.tsx
  packages/console/src/utils/request.ts
  packages/phrases/src/locales/de/translation/admin-console/general.ts
  packages/phrases/src/locales/en/translation/admin-console/general.ts
  packages/phrases/src/locales/es/translation/admin-console/general.ts
  packages/phrases/src/locales/fr/translation/admin-console/general.ts
  packages/phrases/src/locales/it/translation/admin-console/general.ts
  packages/phrases/src/locales/ja/translation/admin-console/general.ts
  packages/phrases/src/locales/ko/translation/admin-console/general.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
  packages/phrases/src/locales/ru/translation/admin-console/general.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/general.ts
Labels: bugfix, size/m

#5377 feat(console): add .NET Blzor WASM tutorial
  .changeset/sixty-pears-flow.md
  packages/console/src/assets/docs/guides/index.ts
  packages/console/src/assets/docs/guides/web-dotnet-core-blazor-wasm/README.mdx
  packages/console/src/assets/docs/guides/web-dotnet-core-blazor-wasm/config.json
  packages/console/src/assets/docs/guides/web-dotnet-core-blazor-wasm/index.ts
  packages/console/src/assets/docs/guides/web-dotnet-core-blazor-wasm/logo.svg
Labels: feature, size/l

#5385 fix(core,phrases): add notice that protected app is cloud only
  packages/core/src/routes/applications/application-protected-app-metadata.openapi.json
  packages/core/src/routes/applications/application.openapi.json
  packages/core/src/routes/init.ts
  packages/phrases/src/locales/de/errors/application.ts
  packages/phrases/src/locales/en/errors/application.ts
  packages/phrases/src/locales/es/errors/application.ts
  packages/phrases/src/locales/fr/errors/application.ts
  packages/phrases/src/locales/it/errors/application.ts
  packages/phrases/src/locales/ja/errors/application.ts
  packages/phrases/src/locales/ko/errors/application.ts
  packages/phrases/src/locales/pl-pl/errors/application.ts
  packages/phrases/src/locales/pt-br/errors/application.ts
  packages/phrases/src/locales/pt-pt/errors/application.ts
  packages/phrases/src/locales/ru/errors/application.ts
  packages/phrases/src/locales/tr-tr/errors/application.ts
  packages/phrases/src/locales/zh-cn/errors/application.ts
  packages/phrases/src/locales/zh-hk/errors/application.ts
  packages/phrases/src/locales/zh-tw/errors/application.ts
Labels: bugfix, size/s

#5382 chore(console): update documentation links
  packages/console/src/consts/external-links.ts
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
  packages/console/src/pages/Applications/components/ProtectedAppCard/index.tsx
Labels: chore, size/s

#5371 chore(core): remove dev features flag from core
  packages/core/src/routes/applications/application.ts
  packages/core/src/routes/applications/types.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/role.application.ts
  packages/core/src/routes/system.ts
Labels: chore, size/s

#5383 refactor(console,phrases): update organization guide next step action link
  packages/console/src/consts/external-links.ts
  packages/console/src/pages/Organizations/Guide/OrganizationInfo/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/organizations.ts
  packages/phrases/src/locales/en/translation/admin-console/organizations.ts
  packages/phrases/src/locales/es/translation/admin-console/organizations.ts
  packages/phrases/src/locales/fr/translation/admin-console/organizations.ts
  packages/phrases/src/locales/it/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ja/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ko/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ru/translation/admin-console/organizations.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/organizations.ts
Labels: enhancement, size/s

#5387 refactor(console,phrases): update phrases in organizations
  packages/console/src/consts/external-links.ts
  packages/console/src/pages/Organizations/index.tsx
  packages/console/src/scss/page-layout.module.scss
  packages/phrases/src/locales/de/translation/admin-console/organizations.ts
  packages/phrases/src/locales/en/translation/admin-console/organizations.ts
  packages/phrases/src/locales/es/translation/admin-console/organizations.ts
  packages/phrases/src/locales/fr/translation/admin-console/organizations.ts
  packages/phrases/src/locales/it/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ja/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ko/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ru/translation/admin-console/organizations.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/organizations.ts
Labels: enhancement, size/s

#5390 refactor(console): remove mfa beta notice
  packages/console/src/pages/Mfa/PageWrapper/index.module.scss
  packages/console/src/pages/Mfa/PageWrapper/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/general.ts
  packages/phrases/src/locales/en/translation/admin-console/general.ts
  packages/phrases/src/locales/es/translation/admin-console/general.ts
  packages/phrases/src/locales/fr/translation/admin-console/general.ts
  packages/phrases/src/locales/it/translation/admin-console/general.ts
  packages/phrases/src/locales/ja/translation/admin-console/general.ts
  packages/phrases/src/locales/ko/translation/admin-console/general.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
  packages/phrases/src/locales/ru/translation/admin-console/general.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/general.ts
Labels: enhancement, size/s

#5380 chore: add changeset files for IdP feature
  .changeset/light-impalas-suffer.md
  .changeset/serious-schools-whisper.md
  .changeset/six-carrots-join.md
  .changeset/six-pens-hope.md
  .changeset/tame-keys-itch.md
Labels: chore, size/s

#5392 refactor(console): update next app router guide
  packages/console/src/assets/docs/guides/web-next-app-router/README.mdx
Labels: enhancement, size/l

#5401 ci: use new test option for seeding
  .github/workflows/main.yml
Labels: size/s

#5399 refactor(core): log cloudflare error
  packages/core/src/routes/applications/application.ts
  packages/core/src/utils/cloudflare/utils.ts
Labels: enhancement, size/xs

#5400 fix(console): protected app creation form field should have correct error background
  packages/console/src/pages/Applications/components/ProtectedAppForm/index.tsx
Labels: bugfix, size/xs

#5402 fix(console): improve protected app loading state in get started page
  packages/console/src/pages/GetStarted/ProtectedAppCreationForm/index.tsx
Labels: bugfix, size/xs

#5397 feat(console): add complete tutorial doc links for app guide
  packages/console/src/assets/docs/guides/m2m-general/index.ts
  packages/console/src/assets/docs/guides/native-android/index.ts
  packages/console/src/assets/docs/guides/spa-react/index.ts
  packages/console/src/assets/docs/guides/spa-vanilla/index.ts
  packages/console/src/assets/docs/guides/spa-vue/index.ts
  packages/console/src/assets/docs/guides/types.ts
  packages/console/src/assets/docs/guides/web-dotnet-core-blazor-server/index.ts
  packages/console/src/assets/docs/guides/web-dotnet-core-blazor-wasm/index.ts
  packages/console/src/assets/docs/guides/web-dotnet-core-mvc/index.ts
  packages/console/src/assets/docs/guides/web-express/index.ts
  packages/console/src/assets/docs/guides/web-go/index.ts
  packages/console/src/assets/docs/guides/web-next-app-router/index.ts
  packages/console/src/assets/docs/guides/web-next/index.ts
  packages/console/src/assets/docs/guides/web-php/index.ts
  packages/console/src/assets/docs/guides/web-python/index.ts
  packages/console/src/mdx-components/Steps/FurtherReadings.tsx
  packages/console/src/mdx-components/Steps/index.tsx
Labels: feature, size/s

#5398 ci: fix release workflow trigger
  .github/workflows/release.yml
Labels: size/xs

#5409 refactor(console): improve input confidentiality handling in TextInput component
  packages/console/src/ds-components/TextInput/index.tsx
Labels: enhancement, size/xs

#5395 refactor(core,schemas): remove cloudConnection call in koaTenantGuard
  packages/core/src/middleware/koa-tenant-guard.test.ts
  packages/core/src/middleware/koa-tenant-guard.ts
  packages/core/src/queries/tenant.ts
  packages/core/src/routes/init.ts
  packages/core/src/tenants/Queries.ts
  packages/schemas/alterations/next-1707360939-grant-is-suspended-read-permission.ts
  packages/schemas/tables/_after_all.sql
Labels: enhancement, size/m

#5410 feat(core,test): add PUT /users/:userId/identities/:target API
  packages/core/src/routes/admin-user/social.openapi.json
  packages/core/src/routes/admin-user/social.test.ts
  packages/core/src/routes/admin-user/social.ts
  packages/integration-tests/src/api/admin-user.ts
  packages/integration-tests/src/tests/api/admin-user.test.ts
  packages/schemas/src/foundations/jsonb-types/users.ts
Labels: feature, size/m

#5413 fix(toolkit): support dash in domain
  packages/toolkit/core-kit/src/regex.test.ts
  packages/toolkit/core-kit/src/regex.ts
Labels: bugfix, size/s

#5414 fix(phrases): use fast create for protected app
  packages/phrases/src/locales/de/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/en/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/es/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/fr/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/it/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/ja/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/ko/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/ru/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/protected-app.ts
Labels: bugfix, size/s

#5412 feat(console): add localhost notice
  packages/console/src/ds-components/TextInput/index.module.scss
  packages/console/src/ds-components/TextInput/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/components/SessionForm.module.scss
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/components/SessionForm.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/index.module.scss
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/index.tsx
  packages/console/src/pages/Applications/components/ProtectedAppForm/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/en/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/es/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/fr/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/it/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/ja/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/ko/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/ru/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/protected-app.ts
  packages/toolkit/core-kit/src/utils/url.test.ts
  packages/toolkit/core-kit/src/utils/url.ts
Labels: feature, size/l

#5417 refactor(console): plan comparison table
  packages/console/src/consts/plan-quotas.ts
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/PlanQuotaGroupKeyLabel/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/PlanQuotaKeyLabel/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/TableDataWrapper/TableDataContent/index.module.scss
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/TableDataWrapper/TableDataContent/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/TableDataWrapper/index.module.scss
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/TableDataWrapper/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/renderers/BasePrice.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/renderers/GenericFeatureFlag.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/renderers/GenericQuotaLimit.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/renderers/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/utils.ts
  packages/console/src/pages/TenantSettings/Subscription/index.tsx
  packages/console/src/types/subscriptions.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-table.ts
Labels: enhancement, size/xl

#5418 refactor(console): update featured plan content in tenant creation modal
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/FeaturedPlanContent/index.module.scss
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/FeaturedPlanContent/index.tsx
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/FeaturedPlanContent/use-featured-plan-content.ts
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/FeaturedPlanQuotaList/FeaturedQuotaItem/index.module.scss
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/FeaturedPlanQuotaList/FeaturedQuotaItem/index.tsx
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/FeaturedPlanQuotaList/index.module.scss
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/FeaturedPlanQuotaList/index.tsx
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/upsell/featured-plan-content.ts
  packages/phrases/src/locales/de/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/en/translation/admin-console/upsell/featured-plan-content.ts
  packages/phrases/src/locales/en/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/es/translation/admin-console/upsell/featured-plan-content.ts
  packages/phrases/src/locales/es/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/upsell/featured-plan-content.ts
  packages/phrases/src/locales/fr/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/it/translation/admin-console/upsell/featured-plan-content.ts
  packages/phrases/src/locales/it/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/upsell/featured-plan-content.ts
  packages/phrases/src/locales/ja/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/upsell/featured-plan-content.ts
  packages/phrases/src/locales/ko/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/upsell/featured-plan-content.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/upsell/featured-plan-content.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/upsell/featured-plan-content.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/upsell/featured-plan-content.ts
  packages/phrases/src/locales/ru/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/upsell/featured-plan-content.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/upsell/featured-plan-content.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/upsell/featured-plan-content.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/upsell/featured-plan-content.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/upsell/index.ts
Labels: enhancement, size/xl

#5381 feat(schemas): add `cleanup:outdated-logs` cloud scope
  packages/schemas/src/seeds/cloud-api.ts
Labels: feature, size/xs, stale

#5419 refactor(console): reorg downgrade plan notification modal
  packages/console/src/components/PlanQuotaList/QuotaListItem/index.tsx
  packages/console/src/components/PlanQuotaList/index.tsx
  packages/console/src/consts/plan-quotas.ts
  packages/console/src/consts/quota-item-phrases.ts
  packages/console/src/consts/tenants.ts
  packages/console/src/pages/TenantSettings/Subscription/DowngradeConfirmModalContent/PlanQuotaDiffCard/DiffQuotaItem/index.module.scss
  packages/console/src/pages/TenantSettings/Subscription/DowngradeConfirmModalContent/PlanQuotaDiffCard/DiffQuotaItem/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/DowngradeConfirmModalContent/PlanQuotaDiffCard/PlanQuotaList/DiffQuotaItem/QuotaItemPhrase.tsx
  packages/console/src/pages/TenantSettings/Subscription/DowngradeConfirmModalContent/PlanQuotaDiffCard/PlanQuotaList/DiffQuotaItem/index.module.scss
  packages/console/src/pages/TenantSettings/Subscription/DowngradeConfirmModalContent/PlanQuotaDiffCard/PlanQuotaList/DiffQuotaItem/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/DowngradeConfirmModalContent/PlanQuotaDiffCard/PlanQuotaList/index.module.scss
  packages/console/src/pages/TenantSettings/Subscription/DowngradeConfirmModalContent/PlanQuotaDiffCard/PlanQuotaList/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/DowngradeConfirmModalContent/PlanQuotaDiffCard/index.tsx
  packages/console/src/pages/TenantSettings/components/NotEligibleSwitchPlanModalContent/index.tsx
  packages/console/src/types/subscriptions.ts
  packages/console/src/utils/subscription.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-item.ts
Labels: enhancement, size/xl

#5421 chore(console): add comments for table component
  packages/console/src/ds-components/Table/index.tsx
  packages/console/src/ds-components/Table/types.ts
Labels: chore, size/s

#5420 chore(console): align PHP/Python guide structure with docs
  packages/console/src/assets/docs/guides/web-php/README.mdx
  packages/console/src/assets/docs/guides/web-php/index.ts
  packages/console/src/assets/docs/guides/web-python/README.mdx
Labels: chore, size/m

#5424 fix(core,console): block deletion on management API
  packages/console/src/components/DetailsPage/DetailsPageHeader/index.tsx
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/core/src/routes/init.ts
  packages/core/src/routes/resource.scope.test.ts
  packages/core/src/routes/resource.scope.ts
  packages/core/src/routes/resource.test.ts
  packages/core/src/routes/resource.ts
  packages/integration-tests/src/tests/api/resource.test.ts
  packages/phrases/src/locales/de/errors/resource.ts
  packages/phrases/src/locales/en/errors/resource.ts
  packages/phrases/src/locales/es/errors/resource.ts
  packages/phrases/src/locales/fr/errors/resource.ts
  packages/phrases/src/locales/it/errors/resource.ts
  packages/phrases/src/locales/ja/errors/resource.ts
  packages/phrases/src/locales/ko/errors/resource.ts
  packages/phrases/src/locales/pl-pl/errors/resource.ts
  packages/phrases/src/locales/pt-br/errors/resource.ts
  packages/phrases/src/locales/pt-pt/errors/resource.ts
  packages/phrases/src/locales/ru/errors/resource.ts
  packages/phrases/src/locales/tr-tr/errors/resource.ts
  packages/phrases/src/locales/zh-cn/errors/resource.ts
  packages/phrases/src/locales/zh-hk/errors/resource.ts
  packages/phrases/src/locales/zh-tw/errors/resource.ts
Labels: bugfix, size/xl

#5426 refactor(console): tutorial -> guide
  packages/console/src/assets/docs/guides/m2m-general/index.ts
  packages/console/src/assets/docs/guides/native-android/index.ts
  packages/console/src/assets/docs/guides/spa-react/index.ts
  packages/console/src/assets/docs/guides/spa-vanilla/index.ts
  packages/console/src/assets/docs/guides/spa-vue/index.ts
  packages/console/src/assets/docs/guides/types.ts
  packages/console/src/assets/docs/guides/web-dotnet-core-blazor-server/index.ts
  packages/console/src/assets/docs/guides/web-dotnet-core-blazor-wasm/index.ts
  packages/console/src/assets/docs/guides/web-dotnet-core-mvc/index.ts
  packages/console/src/assets/docs/guides/web-express/index.ts
  packages/console/src/assets/docs/guides/web-go/index.ts
  packages/console/src/assets/docs/guides/web-next-app-router/index.ts
  packages/console/src/assets/docs/guides/web-next/index.ts
  packages/console/src/assets/docs/guides/web-php/index.ts
  packages/console/src/assets/docs/guides/web-python/index.ts
  packages/console/src/mdx-components/Steps/FurtherReadings.tsx
  packages/console/src/mdx-components/Steps/index.tsx
Labels: enhancement, size/s

#5427 docs(console): add guides
  .changeset/short-boats-suffer.md
  packages/console/.parcelrc
  packages/console/.parcelrc.arm64
  packages/console/src/assets/docs/fragments/_checkpoint.md
  packages/console/src/assets/docs/guides/index.ts
  packages/console/src/assets/docs/guides/native-expo/README.mdx
  packages/console/src/assets/docs/guides/native-expo/config.json
  packages/console/src/assets/docs/guides/native-expo/index.ts
  packages/console/src/assets/docs/guides/native-expo/logo.svg
  packages/console/src/assets/docs/guides/spa-angular/README.mdx
  packages/console/src/assets/docs/guides/spa-angular/config.json
  packages/console/src/assets/docs/guides/spa-angular/index.ts
  packages/console/src/assets/docs/guides/spa-angular/logo.svg
  packages/console/src/assets/docs/guides/web-nuxt/README.mdx
  packages/console/src/assets/docs/guides/web-nuxt/config.json
  packages/console/src/assets/docs/guides/web-nuxt/index.ts
  packages/console/src/assets/docs/guides/web-nuxt/logo.svg
  packages/console/src/assets/docs/guides/web-sveltekit/README.mdx
  packages/console/src/assets/docs/guides/web-sveltekit/config.json
  packages/console/src/assets/docs/guides/web-sveltekit/index.ts
  packages/console/src/assets/docs/guides/web-sveltekit/logo.svg
  packages/console/src/ds-components/InlineNotification/index.module.scss
Labels: size/xl

#5403 refactor(console): refactor error handling in Express tutorial
  packages/console/src/assets/docs/guides/api-express/README.mdx
Labels: enhancement, size/xs

#5432 fix(console): center align card title when subtitle is not available
  packages/console/src/ds-components/DangerousRaw/index.tsx
Labels: bugfix, size/xs

#5435 feat(console): upgrade nextjs server actions guide
  packages/console/src/assets/docs/guides/web-next-server-actions/README.mdx
Labels: feature, size/l

#5437 refactor(console): update content
  packages/phrases/src/locales/de/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/en/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/es/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/fr/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/it/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/ja/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/ko/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/ru/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/protected-app.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/protected-app.ts
Labels: enhancement, size/l

#5425 fix(core): mgmt API scopes are not assignable to user roles
  packages/core/src/libraries/role-scope.ts
  packages/core/src/routes/role.scope.test.ts
  packages/core/src/routes/role.scope.ts
  packages/core/src/routes/role.test.ts
  packages/core/src/routes/role.ts
  packages/core/src/tenants/Libraries.ts
  packages/integration-tests/src/tests/api/oidc/get-access-token.test.ts
  packages/integration-tests/src/tests/api/role.scope.test.ts
  packages/integration-tests/src/tests/api/role.test.ts
  packages/phrases/src/locales/de/errors/role.ts
  packages/phrases/src/locales/en/errors/role.ts
  packages/phrases/src/locales/es/errors/role.ts
  packages/phrases/src/locales/fr/errors/role.ts
  packages/phrases/src/locales/it/errors/role.ts
  packages/phrases/src/locales/ja/errors/role.ts
  packages/phrases/src/locales/ko/errors/role.ts
  packages/phrases/src/locales/pl-pl/errors/role.ts
  packages/phrases/src/locales/pt-br/errors/role.ts
  packages/phrases/src/locales/pt-pt/errors/role.ts
  packages/phrases/src/locales/ru/errors/role.ts
  packages/phrases/src/locales/tr-tr/errors/role.ts
  packages/phrases/src/locales/zh-cn/errors/role.ts
  packages/phrases/src/locales/zh-hk/errors/role.ts
  packages/phrases/src/locales/zh-tw/errors/role.ts
  packages/schemas/alterations/next-1708916601-remove-management-api-scopes-assigned-to-user-role.ts
Labels: bugfix, size/l

#5442 chore(console): update vanilla js integration guide
  packages/console/src/assets/docs/guides/spa-vanilla/README.mdx
Labels: chore, size/s

#5411 feat(connector): add connector-wecom
  .gitignore
  packages/connectors/connector-wecom/README.md
  packages/connectors/connector-wecom/logo.svg
  packages/connectors/connector-wecom/package.json
  packages/connectors/connector-wecom/src/constant.ts
  packages/connectors/connector-wecom/src/index.test.ts
  packages/connectors/connector-wecom/src/index.ts
  packages/connectors/connector-wecom/src/mock.ts
  packages/connectors/connector-wecom/src/types.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#5441 fix(connector): always show SMTP connector TLS configurations in the admin console
  .changeset/wet-squids-move.md
  packages/connectors/connector-smtp/src/constant.ts
Labels: bugfix, size/s

#5438 fix(core,test): fix integration test
  packages/core/src/routes/sso-connector/index.ts
  packages/integration-tests/src/__mocks__/sso-connectors-mock.ts
  packages/integration-tests/src/api/api.ts
  packages/integration-tests/src/constants.ts
  packages/integration-tests/src/tests/console/sso-connectors/helpers.ts
  packages/integration-tests/src/tests/console/sso-connectors/sso-connectors-test-cases.ts
  packages/integration-tests/src/tests/console/sso-connectors/sso-connectors.test.ts
Labels: bugfix, size/m

#5439 refactor(test): remove dropdown modal waitForTimeout
  packages/integration-tests/src/tests/console/sign-in-experience/helpers.ts
  packages/integration-tests/src/tests/console/sign-in-experience/sign-in-preview.test.ts
  packages/integration-tests/src/tests/console/sign-in-experience/sign-up-and-sign-in/happy-path.test.ts
  packages/integration-tests/src/tests/console/sign-in-experience/sign-up-and-sign-in/helpers.ts
  packages/integration-tests/src/ui-helpers/index.ts
  packages/integration-tests/src/ui-helpers/select-dropdown-menu-item.ts
Labels: enhancement, size/s

#5447 chore(connector): fix wecom package file
  packages/connectors/connector-wecom/package.json
Labels: chore, size/xs

#5449 refactor(console): update loading component
  packages/console/src/assets/images/loading-illustration-dark.svg
  packages/console/src/assets/images/loading-illustration.svg
  packages/console/src/components/AppLoading/index.module.scss
  packages/console/src/components/AppLoading/index.tsx
Labels: enhancement, size/m

#5452 refactor(schemas): rename `cleanup:outdated-logs` scope to`prune:logs`
  packages/schemas/src/seeds/cloud-api.ts
Labels: enhancement, size/xs
