Repository logto-io/logto, pull requests merged in 2024-04, with the labels that each got.

#5590 refactor(console): move organization template into a single page
  packages/console/src/assets/icons/research.svg
  packages/console/src/consts/external-links.ts
  packages/console/src/consts/page-tabs.ts
  packages/console/src/containers/ConsoleContent/Sidebar/hook.tsx
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/ds-components/CardTitle/index.module.scss
  packages/console/src/ds-components/CardTitle/index.tsx
  packages/console/src/pages/OrganizationTemplate/OrgPermissions/index.module.scss
  packages/console/src/pages/OrganizationTemplate/OrgPermissions/index.tsx
  packages/console/src/pages/OrganizationTemplate/OrgRoles/index.module.scss
  packages/console/src/pages/OrganizationTemplate/OrgRoles/index.tsx
  packages/console/src/pages/OrganizationTemplate/index.module.scss
  packages/console/src/pages/OrganizationTemplate/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/index.ts
  packages/phrases/src/locales/de/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/de/translation/admin-console/tabs.ts
  packages/phrases/src/locales/en/translation/admin-console/index.ts
  packages/phrases/src/locales/en/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/en/translation/admin-console/tabs.ts
  packages/phrases/src/locales/es/translation/admin-console/index.ts
  packages/phrases/src/locales/es/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/es/translation/admin-console/tabs.ts
  packages/phrases/src/locales/fr/translation/admin-console/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/fr/translation/admin-console/tabs.ts
  packages/phrases/src/locales/it/translation/admin-console/index.ts
  packages/phrases/src/locales/it/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/it/translation/admin-console/tabs.ts
  packages/phrases/src/locales/ja/translation/admin-console/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/ja/translation/admin-console/tabs.ts
  packages/phrases/src/locales/ko/translation/admin-console/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/ko/translation/admin-console/tabs.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tabs.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tabs.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tabs.ts
  packages/phrases/src/locales/ru/translation/admin-console/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/ru/translation/admin-console/tabs.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tabs.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tabs.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tabs.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tabs.ts
Labels: enhancement, size/xl

#5579 feat(console): implement custom jwt landing page
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/pages/CustomizeJwt/CreateButton/index.module.scss
  packages/console/src/pages/CustomizeJwt/CreateButton/index.tsx
  packages/console/src/pages/CustomizeJwt/CustomizerItem/index.module.scss
  packages/console/src/pages/CustomizeJwt/CustomizerItem/index.tsx
  packages/console/src/pages/CustomizeJwt/index.module.scss
  packages/console/src/pages/CustomizeJwt/index.tsx
  packages/console/src/pages/CustomizeJwt/use-jwt-customizer.ts
  packages/console/src/pages/CustomizeJwt/utils/path.ts
  packages/console/src/pages/JwtClaims/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/general.ts
  packages/phrases/src/locales/de/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/en/translation/admin-console/general.ts
  packages/phrases/src/locales/en/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/es/translation/admin-console/general.ts
  packages/phrases/src/locales/es/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/fr/translation/admin-console/general.ts
  packages/phrases/src/locales/fr/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/it/translation/admin-console/general.ts
  packages/phrases/src/locales/it/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ja/translation/admin-console/general.ts
  packages/phrases/src/locales/ja/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ko/translation/admin-console/general.ts
  packages/phrases/src/locales/ko/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/general.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ru/translation/admin-console/general.ts
  packages/phrases/src/locales/ru/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/general.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/jwt-claims.ts
  packages/toolkit/core-kit/scss/_console-themes.scss
Labels: feature, size/xl

#5591 refactor(console): redesign the jwt details page
  packages/console/src/assets/icons/conical-flask.svg
  packages/console/src/components/SubmitFormChangesActionBar/index.tsx
  packages/console/src/containers/ConsoleContent/Sidebar/hook.tsx
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/MainContent/MonacoCodeEditor/ActionButton/CodeRestoreButton.tsx
  packages/console/src/pages/CustomizeJwtDetails/MainContent/MonacoCodeEditor/ActionButton/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/MainContent/MonacoCodeEditor/Dashboard/index.module.scss
  packages/console/src/pages/CustomizeJwtDetails/MainContent/MonacoCodeEditor/Dashboard/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/MainContent/MonacoCodeEditor/config.ts
  packages/console/src/pages/CustomizeJwtDetails/MainContent/MonacoCodeEditor/index.module.scss
  packages/console/src/pages/CustomizeJwtDetails/MainContent/MonacoCodeEditor/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/MainContent/MonacoCodeEditor/type.ts
  packages/console/src/pages/CustomizeJwtDetails/MainContent/MonacoCodeEditor/use-editor-height.ts
  packages/console/src/pages/CustomizeJwtDetails/MainContent/ScriptSection/ErrorContent/index.module.scss
  packages/console/src/pages/CustomizeJwtDetails/MainContent/ScriptSection/ErrorContent/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/MainContent/ScriptSection/index.module.scss
  packages/console/src/pages/CustomizeJwtDetails/MainContent/ScriptSection/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/MainContent/ScriptSection/use-test-handler.ts
  packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/EnvironmentVariablesField.tsx
  packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/GuideCard/index.module.scss
  packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/GuideCard/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/index.module.scss
  packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/TestResult.tsx
  packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/TestTab.tsx
  packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/TestTab/index.module.scss
  packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/TestTab/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/index.module.scss
  packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/MainContent/index.module.scss
  packages/console/src/pages/CustomizeJwtDetails/MainContent/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/utils/config.tsx
  packages/console/src/pages/EnterpriseSsoDetails/Connection/SamlConnectorForm.tsx
  packages/console/src/scss/_code-editor.scss
  packages/console/src/scss/_underscore.scss
  packages/phrases/src/locales/de/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/en/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/es/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/fr/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/it/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ja/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ko/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ru/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/jwt-claims.ts
  packages/toolkit/core-kit/scss/_console-themes.scss
  packages/toolkit/core-kit/scss/_fonts.scss
Labels: enhancement, size/xl

#5599 chore(cli): update translate CLI configs
  packages/cli/src/commands/translate/openai.ts
Labels: chore, size/xs

#5601 fix(console): only pending invitations can be resent
  packages/console/src/pages/TenantSettings/TenantMembers/Invitations/index.tsx
Labels: bugfix, size/xs

#5609 fix(core): update expired invitation to expired before inserting a new one
  packages/core/src/libraries/organization-invitation.ts
  packages/core/src/queries/organization/index.ts
Labels: bugfix, size/s

#5602 fix(console): joining tenant should navigate user to the new tenant
  packages/console/src/cloud/pages/Main/InvitationList/index.tsx
  packages/console/src/components/Topbar/TenantSelector/TenantInvitationDropdownItem/index.tsx
  packages/console/src/pages/AcceptInvitation/index.tsx
Labels: bugfix, size/s

#5611 chore(core,console): update error handling of testing custom JWT
  packages/console/src/pages/CustomizeJwtDetails/MainContent/ScriptSection/ErrorContent/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/MainContent/ScriptSection/use-test-handler.ts
  packages/console/src/pages/CustomizeJwtDetails/utils/config.tsx
  packages/console/src/pages/CustomizeJwtDetails/utils/format.ts
  packages/core/src/errors/RequestError/index.ts
  packages/core/src/routes/logto-config/jwt-customizer.ts
  packages/schemas/src/types/index.ts
  packages/schemas/src/types/logto-config/index.ts
  packages/schemas/src/types/logto-config/jwt-customizer.ts
Labels: chore, size/m

#5468 feat(core): add PATCH /configs/jwt-customizer API
  packages/core/src/libraries/cloud-connection.test.ts
  packages/core/src/libraries/logto-config.ts
  packages/core/src/libraries/sign-in-experience/index.test.ts
  packages/core/src/routes/logto-config/jwt-customizer.test.ts
  packages/core/src/routes/logto-config/jwt-customizer.ts
  packages/core/src/routes/logto-config/logto-config.openapi.json
  packages/integration-tests/src/__mocks__/jwt-customizer.ts
  packages/integration-tests/src/api/logto-config.ts
  packages/integration-tests/src/tests/api/logto-config.test.ts
  packages/schemas/src/types/logto-config/jwt-customizer.test.ts
  packages/schemas/src/types/logto-config/jwt-customizer.ts
Labels: feature, size/l

#5612 fix(console): reset form as soon as JWT customizer is created
  packages/console/src/pages/CustomizeJwt/CustomizerItem/index.tsx
  packages/console/src/pages/CustomizeJwt/use-jwt-customizer.ts
  packages/console/src/pages/CustomizeJwt/utils/path.ts
  packages/console/src/pages/CustomizeJwtDetails/MainContent/index.tsx
Labels: bugfix, size/s

#5539 feat(core,schemas): log extraTokenClaims exception
  packages/console/src/consts/logs.ts
  packages/console/src/pages/WebhookDetails/WebhookLogs/index.tsx
  packages/core/src/oidc/init.ts
  packages/schemas/src/types/log/index.ts
  packages/schemas/src/types/log/jwt-customizer.ts
Labels: feature, size/s

#5616 refactor(schemas): rename tenant member role to collaborator
  packages/console/src/pages/TenantSettings/TenantMembers/EditMemberModal/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/en/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/es/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/fr/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/it/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/ja/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/ko/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/ru/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tenant-members.ts
  packages/schemas/alterations/next-1712041436-rename-organization-member-role-to-collaborator.ts
  packages/schemas/src/types/tenant-organization.ts
Labels: enhancement, feature, size/m

#5614 fix(console,phrases): fix a batch of organization invitation console ui issues
  packages/console/src/assets/icons/invitation.svg
  packages/console/src/cloud/pages/Main/InvitationList/index.module.scss
  packages/console/src/cloud/pages/Main/InvitationList/index.tsx
  packages/console/src/components/ItemPreview/index.module.scss
  packages/console/src/components/ItemPreview/index.tsx
  packages/console/src/components/Topbar/TenantSelector/index.module.scss
  packages/console/src/components/Topbar/TenantSelector/index.tsx
  packages/console/src/pages/AcceptInvitation/SwitchAccount/index.module.scss
  packages/console/src/pages/AcceptInvitation/SwitchAccount/index.tsx
  packages/console/src/pages/AcceptInvitation/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/index.tsx
  packages/console/src/pages/TenantSettings/index.tsx
  packages/integration-tests/src/tests/console/applications/index.test.ts
  packages/integration-tests/src/tests/console/rbac/machime-to-machime-rbac.test.ts
  packages/integration-tests/src/tests/console/rbac/user-rbac.test.ts
  packages/integration-tests/src/tests/console/sign-in-experience/sign-up-and-sign-in/connector-setup-helpers.ts
  packages/phrases/src/locales/de/translation/admin-console/invitation.ts
  packages/phrases/src/locales/en/translation/admin-console/invitation.ts
  packages/phrases/src/locales/es/translation/admin-console/invitation.ts
  packages/phrases/src/locales/fr/translation/admin-console/invitation.ts
  packages/phrases/src/locales/it/translation/admin-console/invitation.ts
  packages/phrases/src/locales/ja/translation/admin-console/invitation.ts
  packages/phrases/src/locales/ko/translation/admin-console/invitation.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/invitation.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/invitation.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/invitation.ts
  packages/phrases/src/locales/ru/translation/admin-console/invitation.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/invitation.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/invitation.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/invitation.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/invitation.ts
Labels: bugfix, size/m

#5603 feat(console): support org permission management on new org template page
  packages/console/src/consts/page-tabs.ts
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/pages/OrganizationTemplate/OrgPermissions/index.tsx
  packages/console/src/pages/OrganizationTemplate/OrganizationPermissions/OrganizationPermissionModal.tsx
  packages/console/src/pages/OrganizationTemplate/OrganizationPermissions/index.module.scss
  packages/console/src/pages/OrganizationTemplate/OrganizationPermissions/index.tsx
  packages/console/src/pages/OrganizationTemplate/OrganizationRoles/index.module.scss
  packages/console/src/pages/OrganizationTemplate/OrganizationRoles/index.tsx
  packages/console/src/pages/OrganizationTemplate/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/en/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/es/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/fr/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/it/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/ja/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/ko/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/ru/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/organization-template.ts
Labels: feature, size/xl

#5610 feat(console): add org role details general settings page
  packages/console/src/consts/page-tabs.ts
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/pages/OrganizationRoleDetails/Permissions/index.tsx
  packages/console/src/pages/OrganizationRoleDetails/Settings/index.tsx
  packages/console/src/pages/OrganizationRoleDetails/index.tsx
  packages/console/src/pages/OrganizationTemplate/OrganizationRoles/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/index.ts
  packages/phrases/src/locales/de/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/en/translation/admin-console/index.ts
  packages/phrases/src/locales/en/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/es/translation/admin-console/index.ts
  packages/phrases/src/locales/es/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/it/translation/admin-console/index.ts
  packages/phrases/src/locales/it/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/organization-role-details.ts
Labels: feature, size/xl

#5621 chore(console,phrases): update content and fix console
  packages/console/src/pages/CustomizeJwt/CreateButton/index.module.scss
  packages/console/src/pages/CustomizeJwt/CreateButton/index.tsx
  packages/console/src/pages/CustomizeJwt/CustomizerItem/index.module.scss
  packages/console/src/pages/CustomizeJwt/CustomizerItem/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/index.module.scss
  packages/console/src/pages/CustomizeJwtDetails/MainContent/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/utils/config.tsx
  packages/phrases/src/locales/de/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/en/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/es/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/fr/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/it/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ja/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ko/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ru/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/jwt-claims.ts
Labels: chore, size/l

#5618 refactor(console,phrases): rename tenant member role to collaborator
  packages/connectors/connector-logto-email/package.json
  packages/console/package.json
  packages/console/src/pages/TenantSettings/TenantMembers/EditMemberModal/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/Invitations/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/index.tsx
  packages/core/package.json
  packages/phrases/src/locales/de/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/en/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/es/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/fr/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/it/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/ja/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/ko/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/ru/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tenant-members.ts
  pnpm-lock.yaml
Labels: enhancement, size/s

#5623 chore(console,toolkit): update custom JWT details page code editor action buttons style
  packages/console/src/pages/CustomizeJwtDetails/MainContent/MonacoCodeEditor/ActionButton/CodeRestoreButton.tsx
  packages/console/src/pages/CustomizeJwtDetails/MainContent/MonacoCodeEditor/ActionButton/index.module.scss
  packages/console/src/pages/CustomizeJwtDetails/MainContent/MonacoCodeEditor/index.module.scss
  packages/console/src/pages/CustomizeJwtDetails/MainContent/MonacoCodeEditor/index.tsx
  packages/toolkit/core-kit/scss/_console-themes.scss
Labels: chore, size/s

#5624 refactor(experience): fix sso callback page style
  packages/experience/src/pages/SocialSignInWebCallback/SingleSignOn.tsx
Labels: enhancement, size/xs

#5606 refactor(phrases): add zh-cn phrases in OIDC consent page
  packages/phrases-experience/src/locales/zh-cn/description.ts
Labels: enhancement, feature, size/s

#5622 refactor(console,phrases): display inviter name on tenant invitations table
  packages/connectors/connector-logto-email/package.json
  packages/console/package.json
  packages/console/src/pages/TenantSettings/TenantMembers/Invitations/index.tsx
  packages/core/package.json
  packages/phrases/src/locales/de/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/en/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/es/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/fr/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/it/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/ja/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/ko/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/ru/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tenant-members.ts
  pnpm-lock.yaml
Labels: enhancement, size/s

#5629 fix(console): temporarily fix pro plan cannot invite members issue
  packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/index.tsx
Labels: bugfix, size/s

#5625 chore(console): update style
  packages/console/src/components/SubmitFormChangesActionBar/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/MainContent/MonacoCodeEditor/index.module.scss
  packages/console/src/pages/CustomizeJwtDetails/MainContent/MonacoCodeEditor/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/MainContent/ScriptSection/index.module.scss
  packages/console/src/pages/CustomizeJwtDetails/MainContent/ScriptSection/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/index.module.scss
  packages/console/src/pages/CustomizeJwtDetails/MainContent/index.module.scss
  packages/console/src/pages/CustomizeJwtDetails/MainContent/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/utils/config.tsx
Labels: chore, size/s

#5630 feat(console): create organization role
  packages/console/src/pages/OrganizationTemplate/OrganizationRoles/CreateOrganizationRoleModal.tsx
  packages/console/src/pages/OrganizationTemplate/OrganizationRoles/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/en/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/es/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/fr/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/it/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/ja/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/ko/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/ru/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/organization-template.ts
Labels: feature, size/l

#5631 feat(console): add permissions page for org role details page
  packages/console/src/components/ManageOrganizationPermissionModal/index.tsx
  packages/console/src/pages/OrganizationRoleDetails/Permissions/index.module.scss
  packages/console/src/pages/OrganizationRoleDetails/Permissions/index.tsx
  packages/console/src/pages/OrganizationTemplate/OrganizationPermissions/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/en/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/es/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/it/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/organization-role-details.ts
Labels: feature, size/m

#5634 refactor(console): reorg resource details page
  packages/console/src/components/PermissionsTable/index.tsx
  packages/console/src/consts/page-tabs.ts
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/index.tsx
  packages/console/src/pages/ApiResourceDetails/ApiResourceSettings/index.tsx
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/console/src/pages/ApiResourceDetails/types.ts
  packages/console/src/pages/ApiResources/index.tsx
  packages/integration-tests/src/tests/console/rbac/machime-to-machime-rbac.test.ts
  packages/integration-tests/src/tests/console/rbac/user-rbac.test.ts
  packages/integration-tests/src/ui-helpers/index.ts
  packages/phrases/src/locales/de/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/en/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/es/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/it/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/api-resource-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/api-resource-details.ts
Labels: enhancement, size/m

#5627 feat(core): search organization roles
  .changeset/quick-kings-tie.md
  packages/core/src/queries/organization/index.ts
  packages/core/src/routes/organization/roles.ts
  packages/integration-tests/src/tests/api/organization/organization-role.test.ts
Labels: feature, size/s

#5608 feat(core,schemas): add organization resource scope relations
  packages/core/src/queries/organization/index.ts
  packages/core/src/routes/organization/roles.openapi.json
  packages/core/src/routes/organization/roles.ts
  packages/integration-tests/src/api/factory.ts
  packages/integration-tests/src/api/organization-role.ts
  packages/integration-tests/src/helpers/resource.ts
  packages/integration-tests/src/tests/api/organization/organization-role.test.ts
  packages/schemas/alterations/next-1711955211-organization-resource-scope.ts
  packages/schemas/tables/organization_role_resource_scope_relations.sql
Labels: feature, size/l

#5592 feat(console): add azure OIDC guide
  packages/console/src/assets/docs/single-sign-on/azure-oidc/README.mdx
  packages/console/src/assets/docs/single-sign-on/azure-oidc/assets/application_details.webp
  packages/console/src/assets/docs/single-sign-on/azure-oidc/assets/config_application.webp
  packages/console/src/assets/docs/single-sign-on/azure-oidc/assets/create_application.webp
  packages/console/src/assets/docs/single-sign-on/azure-oidc/assets/create_secret.webp
  packages/console/src/assets/docs/single-sign-on/azure-oidc/assets/endpoints.webp
  packages/console/src/assets/docs/single-sign-on/index.ts
Labels: feature, size/s

#5613 feat(core,schemas): edit and query resource scopes for org role
  packages/core/src/queries/organization/index.ts
  packages/core/src/routes/organization/roles.openapi.json
  packages/core/src/routes/organization/roles.ts
  packages/integration-tests/src/api/factory.ts
  packages/integration-tests/src/api/organization-role.ts
  packages/integration-tests/src/tests/api/organization/organization-role.test.ts
  packages/schemas/src/types/organization.ts
Labels: feature, size/m

#5641 fix(console,phrases): update the jwt test section content
  packages/console/src/pages/CustomizeJwtDetails/utils/config.tsx
  packages/phrases/src/locales/de/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/en/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/es/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/fr/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/it/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ja/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ko/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/ru/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/jwt-claims.ts
Labels: bugfix, size/s

#5642 style(console): fix the jwt details page style
  packages/console/src/pages/CustomizeJwtDetails/MainContent/ScriptSection/index.module.scss
  packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/index.module.scss
  packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/TestTab/index.module.scss
  packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/TestTab/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/MainContent/index.module.scss
  packages/console/src/pages/CustomizeJwtDetails/index.module.scss
Labels: size/s

#5643 fix(console): fix test result panel overflow bug
  packages/console/src/pages/CustomizeJwtDetails/MainContent/MonacoCodeEditor/index.module.scss
  packages/console/src/pages/CustomizeJwtDetails/MainContent/MonacoCodeEditor/index.tsx
Labels: bugfix, size/s

#5645 chore(schemas): fix alteration timestamp
  packages/schemas/alterations/next-1712545011-fix-organization-resource-scope.ts
Labels: chore, size/s

#5646 feat(console): support searching for organization roles
  packages/console/src/pages/OrganizationTemplate/OrganizationRoles/index.module.scss
  packages/console/src/pages/OrganizationTemplate/OrganizationRoles/index.tsx
Labels: feature, size/s

#5649 refactor(console): show confirm box when inviting a member as admin
  packages/console/src/ds-components/ConfirmModal/index.module.scss
  packages/console/src/ds-components/ConfirmModal/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/InviteEmailsInput/index.module.scss
  packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/index.module.scss
  packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/index.tsx
Labels: enhancement, size/s

#5647 feat(console): add guide for organization template page
  packages/console/src/pages/OrganizationTemplate/index.tsx
Labels: feature, size/s

#5652 refactor(console): collaborator can see tenant domain settings in readonly mode
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/pages/TenantSettings/TenantDomainSettings/AddDomainForm/index.tsx
  packages/console/src/pages/TenantSettings/TenantDomainSettings/CustomDomain/CustomDomainHeader/index.tsx
  packages/console/src/pages/TenantSettings/TenantDomainSettings/CustomDomain/index.tsx
  packages/console/src/pages/TenantSettings/TenantDomainSettings/index.tsx
  packages/console/src/pages/TenantSettings/index.tsx
Labels: enhancement, size/s

#5654 refactor(console): hide switching tabs and invite button for collaborators
  packages/console/src/pages/TenantSettings/TenantMembers/index.tsx
Labels: enhancement, size/s

#5655 refactor(console): improve switch button styles
  packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/index.module.scss
  packages/console/src/pages/TenantSettings/TenantMembers/index.module.scss
Labels: enhancement, size/s

#5657 fix(console): user should switch account and accept invitation properly in console
  packages/console/package.json
  packages/console/src/pages/AcceptInvitation/index.tsx
  packages/demo-app/package.json
  packages/integration-tests/package.json
  pnpm-lock.yaml
Labels: bugfix, size/xs

#5659 refactor(console): improve tenant member role related experience
  packages/console/src/pages/TenantSettings/TenantMembers/EditMemberModal/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/index.module.scss
  packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/Members/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/index.module.scss
Labels: enhancement, size/s

#5661 refactor(console,phrases): improve invite email input
  packages/console/src/pages/TenantSettings/TenantMembers/InviteEmailsInput/hooks.ts
  packages/console/src/pages/TenantSettings/TenantMembers/InviteEmailsInput/index.module.scss
  packages/console/src/pages/TenantSettings/TenantMembers/InviteEmailsInput/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/types.ts
  packages/phrases/src/locales/de/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/en/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/es/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/fr/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/it/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/ja/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/ko/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/ru/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tenant-members.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tenant-members.ts
Labels: enhancement, size/m

#5663 fix(console): go to onboarding process on clicking create new tenant button
  packages/console/src/cloud/pages/Main/InvitationList/index.tsx
Labels: bugfix, size/m

#5658 fix(connector): fix microsoft social connector readme
  packages/connectors/connector-azuread/README.md
Labels: bugfix, size/s

#5670 fix(experience): fix the terms of use not clickable bug
  packages/experience/src/pages/SocialSignInWebCallback/SingleSignOn.tsx
  packages/experience/src/pages/SocialSignInWebCallback/SocialSignIn.tsx
  packages/experience/src/pages/SocialSignInWebCallback/use-single-sign-on-listener.ts
  packages/experience/src/pages/SocialSignInWebCallback/use-social-sign-in-listener.ts
Labels: bugfix, size/s

#5672 chore(console): update pricing plan items for jwt claims
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/index.tsx
Labels: chore, size/xs

#5669 refactor(console): redirect to sign-up page on clicking invitation links
  packages/console/src/containers/ProtectedRoutes/index.tsx
Labels: enhancement, size/xs

#5668 chore: add changeset
  .changeset/breezy-eyes-bathe.md
Labels: chore, size/xs

#5673 refactor(experience): fall back to sign-in page when error
  packages/experience/src/pages/SocialSignInWebCallback/index.test.tsx
  packages/experience/src/pages/SocialSignInWebCallback/index.tsx
  packages/experience/src/pages/SocialSignInWebCallback/use-single-sign-on-listener.ts
  packages/experience/src/pages/SocialSignInWebCallback/use-social-sign-in-listener.ts
  packages/integration-tests/src/tests/experience/direct-sign-in.test.ts
  packages/integration-tests/src/tests/experience/social-sign-in.test.ts
  packages/integration-tests/src/ui-helpers/expect-experience.ts
  packages/integration-tests/src/ui-helpers/expect-page.ts
  packages/integration-tests/src/ui-helpers/index.ts
  packages/integration-tests/src/utils.ts
Labels: enhancement, size/l

#5671 feat(console): display api resources in org role permission table
  packages/console/src/components/EditScopeModal/index.tsx
  packages/console/src/components/PermissionsTable/index.tsx
  packages/console/src/pages/OrganizationRoleDetails/Permissions/ResourceName/index.module.scss
  packages/console/src/pages/OrganizationRoleDetails/Permissions/ResourceName/index.tsx
  packages/console/src/pages/OrganizationRoleDetails/Permissions/index.tsx
  packages/console/src/pages/OrganizationRoleDetails/Permissions/use-organization-role-scopes.ts
  packages/console/src/pages/OrganizationTemplate/OrganizationRoles/index.tsx
Labels: feature, size/l

#5676 refactor: uncomment feature guard
  packages/core/src/routes/organization/index.ts
Labels: enhancement, size/xs

#5664 feat(console): assign permissions for org roles
  packages/console/src/components/OrganizationRolePermissionsAssignmentModal/index.tsx
  packages/console/src/components/OrganizationRolePermissionsAssignmentModal/types.ts
  packages/console/src/components/OrganizationRolePermissionsAssignmentModal/use-organization-role-permissions-assignment.ts
  packages/console/src/components/OrganizationRolePermissionsAssignmentModal/use-organization-scopes-assignment.ts
  packages/console/src/components/OrganizationRolePermissionsAssignmentModal/use-resource-scopes-assignment.ts
  packages/console/src/pages/OrganizationRoleDetails/Permissions/index.tsx
  packages/console/src/pages/OrganizationTemplate/OrganizationRoles/CreateOrganizationRoleModal.tsx
  packages/console/src/pages/OrganizationTemplate/OrganizationRoles/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/en/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/es/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/it/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/organization-role-details.ts
Labels: feature, size/l

#5596 refactor(core): partially remove got
  packages/core/package.json
  packages/core/src/libraries/cloud-connection.ts
  packages/core/src/libraries/hook/index.test.ts
  packages/core/src/libraries/hook/index.ts
  packages/core/src/libraries/hook/utils.test.ts
  packages/core/src/libraries/hook/utils.ts
  packages/integration-tests/src/api/application.ts
  packages/integration-tests/src/tests/api/hook/hook.trigger.test.ts
  packages/integration-tests/src/tests/api/oidc/refresh-token-grant.test.ts
  packages/shared/src/utils/fetch.ts
  packages/shared/src/utils/index.ts
  pnpm-lock.yaml
Labels: enhancement, size/s

#5680 refactor(console): update protected app custom domain field to app domain
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/index.tsx
Labels: enhancement, size/xs

#5626 fix(core): not allow to modify management api resource
  .changeset/four-goats-rush.md
  packages/core/src/routes/resource.scope.test.ts
  packages/core/src/routes/resource.scope.ts
  packages/core/src/routes/resource.test.ts
  packages/core/src/routes/resource.ts
  packages/integration-tests/src/tests/api/resource.scope.test.ts
  packages/integration-tests/src/tests/api/resource.test.ts
  packages/phrases/src/locales/de/errors/resource.ts
  packages/phrases/src/locales/en/errors/resource.ts
  packages/phrases/src/locales/es/errors/resource.ts
  packages/phrases/src/locales/fr/errors/resource.ts
  packages/phrases/src/locales/it/errors/resource.ts
  packages/phrases/src/locales/ja/errors/resource.ts
  packages/phrases/src/locales/ko/errors/resource.ts
  packages/phrases/src/locales/pl-pl/errors/resource.ts
  packages/phrases/src/locales/pt-br/errors/resource.ts
  packages/phrases/src/locales/pt-pt/errors/resource.ts
  packages/phrases/src/locales/ru/errors/resource.ts
  packages/phrases/src/locales/tr-tr/errors/resource.ts
  packages/phrases/src/locales/zh-cn/errors/resource.ts
  packages/phrases/src/locales/zh-hk/errors/resource.ts
  packages/phrases/src/locales/zh-tw/errors/resource.ts
Labels: bugfix, size/m

#5681 refactor(console): deprecate original organization template page
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/pages/Organizations/index.tsx
Labels: enhancement, size/s

#5679 feat(console): add paywall for organization template
  packages/console/src/pages/OrganizationTemplate/index.module.scss
  packages/console/src/pages/OrganizationTemplate/index.tsx
Labels: feature, size/s

#5683 refactor(console): update reservation link
  packages/console/src/consts/external-links.ts
Labels: enhancement, size/xs

#5682 feat(core): add custom jwt worker deploy
  packages/core/package.json
  packages/core/src/libraries/cloud-connection.test.ts
  packages/core/src/libraries/logto-config.ts
  packages/core/src/libraries/sign-in-experience/index.test.ts
  packages/core/src/routes/logto-config/jwt-customizer.test.ts
  packages/core/src/routes/logto-config/jwt-customizer.ts
  packages/core/src/utils/custom-jwt.ts
  pnpm-lock.yaml
Labels: feature, size/m

#5685 feat(core): undeploy worker scripts when jwt customizer is deleted
  packages/core/src/libraries/cloud-connection.test.ts
  packages/core/src/libraries/logto-config.ts
  packages/core/src/libraries/sign-in-experience/index.test.ts
  packages/core/src/routes/logto-config/jwt-customizer.test.ts
  packages/core/src/routes/logto-config/jwt-customizer.ts
  packages/core/src/test-utils/mock-libraries.ts
Labels: feature, size/s

#5688 refactor(console,phrases): update organization template phrases
  packages/console/src/components/PermissionsTable/index.tsx
  packages/console/src/pages/OrganizationRoleDetails/Permissions/index.tsx
  packages/integration-tests/src/tests/console/rbac/user-rbac.test.ts
  packages/phrases/src/locales/de/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/de/translation/admin-console/permissions.ts
  packages/phrases/src/locales/en/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/en/translation/admin-console/permissions.ts
  packages/phrases/src/locales/es/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/es/translation/admin-console/permissions.ts
  packages/phrases/src/locales/fr/translation/admin-console/permissions.ts
  packages/phrases/src/locales/it/translation/admin-console/permissions.ts
  packages/phrases/src/locales/ja/translation/admin-console/permissions.ts
  packages/phrases/src/locales/ko/translation/admin-console/permissions.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/permissions.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/permissions.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/permissions.ts
  packages/phrases/src/locales/ru/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/permissions.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/permissions.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/permissions.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/permissions.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/permissions.ts
Labels: enhancement, size/s

#5699 refactor(console): split route objects
  packages/console/src/hooks/use-console-routes/index.tsx
  packages/console/src/hooks/use-console-routes/routes/api-resources.tsx
  packages/console/src/hooks/use-console-routes/routes/applications.tsx
  packages/console/src/hooks/use-console-routes/routes/audit-logs.tsx
  packages/console/src/hooks/use-console-routes/routes/connectors.tsx
  packages/console/src/hooks/use-console-routes/routes/customize-jwt.tsx
  packages/console/src/hooks/use-console-routes/routes/enterprise-sso.tsx
  packages/console/src/hooks/use-console-routes/routes/organization-template.tsx
  packages/console/src/hooks/use-console-routes/routes/organizations.tsx
  packages/console/src/hooks/use-console-routes/routes/profile.tsx
  packages/console/src/hooks/use-console-routes/routes/roles.tsx
  packages/console/src/hooks/use-console-routes/routes/sign-in-experience.tsx
  packages/console/src/hooks/use-console-routes/routes/tenant-settings.tsx
  packages/console/src/hooks/use-console-routes/routes/users.tsx
  packages/console/src/hooks/use-console-routes/routes/webhooks.tsx
Labels: enhancement, size/xl

#5686 feat(core): add jwt-customizer test script deployment
  packages/core/src/routes/logto-config/jwt-customizer.test.ts
  packages/core/src/routes/logto-config/jwt-customizer.ts
  packages/core/src/test-utils/mock-libraries.ts
  packages/core/src/test-utils/tenant.ts
Labels: feature, size/m

#5697 feat(console): add api permission content for organization guide
  packages/console/src/pages/Organizations/Guide/Introduction/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/organizations.ts
  packages/phrases/src/locales/en/translation/admin-console/organizations.ts
  packages/phrases/src/locales/es/translation/admin-console/organizations.ts
  packages/phrases/src/locales/fr/translation/admin-console/organizations.ts
  packages/phrases/src/locales/it/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ja/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ko/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ru/translation/admin-console/organizations.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/organizations.ts
Labels: feature, size/s

#5694 style(console): align resource icon with resource name
  packages/console/src/pages/OrganizationRoleDetails/Permissions/ResourceName/index.module.scss
Labels: size/xs

#5691 refactor(console): update org template sidebar icon
  packages/console/src/assets/icons/organization-template-feature.svg
  packages/console/src/containers/ConsoleContent/Sidebar/hook.tsx
Labels: enhancement, size/xs

#5692 style(console): update signing key sidebar icon
  packages/console/src/assets/icons/key.svg
Labels: size/xs

#5693 refactor(phrases): update organization template subtitle
  packages/phrases/src/locales/de/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/en/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/es/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/fr/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/it/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/ja/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/ko/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/ru/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/organization-template.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/organization-template.ts
Labels: enhancement, size/s

#5696 refactor(core,schemas): make the jwt customizer script field mandatory
  packages/core/src/routes/logto-config/jwt-customizer.test.ts
  packages/core/src/routes/logto-config/jwt-customizer.ts
  packages/schemas/alterations/next-1712912361-delete-jwt-customier-with-empty-script.ts
  packages/schemas/src/types/logto-config/jwt-customizer.test.ts
  packages/schemas/src/types/logto-config/jwt-customizer.ts
Labels: enhancement, size/m

#5689 fix(console): fix the quota guard layout
  packages/console/src/components/QuotaGuardFooter/index.module.scss
Labels: bugfix, size/xs

#5700 chore(console): restrict route component in pages
  packages/console/.eslintrc.cjs
  packages/console/package.json
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/console/src/pages/OrganizationDetails/index.tsx
  packages/console/src/pages/OrganizationRoleDetails/index.tsx
  packages/console/src/pages/Organizations/Guide/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/index.tsx
Labels: chore, size/m

#5702 refactor(console): reorg organization details routes
  packages/console/src/hooks/use-console-routes/routes/organizations.tsx
  packages/console/src/pages/OrganizationDetails/Members/index.tsx
  packages/console/src/pages/OrganizationDetails/Settings/index.tsx
  packages/console/src/pages/OrganizationDetails/index.tsx
  packages/console/src/pages/OrganizationDetails/types.ts
Labels: enhancement, size/s

#5695 refactor(console): update tab order on role details page
  packages/console/src/consts/page-tabs.ts
  packages/console/src/hooks/use-console-routes/routes/roles.tsx
  packages/console/src/pages/RoleDetails/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/role-details.ts
  packages/phrases/src/locales/en/translation/admin-console/role-details.ts
  packages/phrases/src/locales/es/translation/admin-console/role-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/role-details.ts
  packages/phrases/src/locales/it/translation/admin-console/role-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/role-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/role-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/role-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/role-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/role-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/role-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/role-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/role-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/role-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/role-details.ts
Labels: enhancement, size/s

#5709 chore: add Cloudflare worker config for custom JWT
  packages/schemas/src/types/system.ts
Labels: chore, size/s

#5701 feat(core): add api to fetch organization scopes for a user
  .changeset/real-camels-cheat.md
  packages/core/package.json
  packages/core/src/oidc/grants/refresh-token.test.ts
  packages/core/src/queries/organization/relations.ts
  packages/core/src/routes/organization/index.openapi.json
  packages/core/src/routes/organization/index.ts
  packages/integration-tests/src/api/organization.ts
  packages/integration-tests/src/tests/api/organization/organization-user.test.ts
Labels: feature, size/m

#5713 style(console): update organization template layout
  packages/console/src/pages/OrganizationRoleDetails/index.module.scss
  packages/console/src/pages/OrganizationRoleDetails/index.tsx
  packages/console/src/pages/OrganizationTemplate/index.module.scss
Labels: size/s

#5715 refactor(console): update console routes
  packages/console/src/hooks/use-console-routes/routes/api-resources.tsx
  packages/console/src/hooks/use-console-routes/routes/organization-template.tsx
  packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/index.tsx
  packages/console/src/pages/ApiResourceDetails/ApiResourceSettings/index.tsx
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/console/src/pages/ApiResourceDetails/types.ts
  packages/console/src/pages/OrganizationRoleDetails/Permissions/index.tsx
  packages/console/src/pages/OrganizationRoleDetails/Settings/index.tsx
  packages/console/src/pages/OrganizationRoleDetails/index.tsx
  packages/console/src/pages/OrganizationRoleDetails/types.ts
Labels: enhancement, size/m

#5716 fix(console): mutate org roles once a org role is deleted
  packages/console/src/pages/OrganizationRoleDetails/index.tsx
Labels: bugfix, size/s

#5653 feat(core): handle access token with organization api resource
  packages/core/src/libraries/user.ts
  packages/core/src/oidc/extra-token-claims.ts
  packages/core/src/oidc/grants/refresh-token.test.ts
  packages/core/src/oidc/grants/refresh-token.ts
  packages/core/src/oidc/init.ts
  packages/core/src/oidc/resource.ts
  packages/core/src/queries/organization/relations.ts
  packages/core/src/queries/user.ts
  packages/integration-tests/src/client/index.ts
  packages/integration-tests/src/tests/api/oidc/organization-api-resource.test.ts
Labels: feature, size/xl

#5711 style(console): minor custom jwt page style iteration
  packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/PageLoadingSkeleton/index.module.scss
Labels: size/xs

#5717 chore(test): improve organization user test stability
  packages/integration-tests/src/tests/api/organization/organization-user.test.ts
Labels: chore, size/xs

#5708 feat(core): add customJwt paywall guard to core API
  packages/console/package.json
  packages/console/src/consts/quota-item-phrases.ts
  packages/console/src/consts/tenants.ts
  packages/console/src/contexts/AppConfirmModalProvider/index.tsx
  packages/console/src/pages/CustomizeJwt/CreateButton/index.tsx
  packages/core/package.json
  packages/core/src/libraries/quota.ts
  packages/core/src/routes/logto-config/jwt-customizer.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/de/translation/admin-console/tabs.ts
  packages/phrases/src/locales/de/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/en/translation/admin-console/tabs.ts
  packages/phrases/src/locales/en/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/es/translation/admin-console/tabs.ts
  packages/phrases/src/locales/es/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/fr/translation/admin-console/tabs.ts
  packages/phrases/src/locales/fr/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/it/translation/admin-console/tabs.ts
  packages/phrases/src/locales/it/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ja/translation/admin-console/tabs.ts
  packages/phrases/src/locales/ja/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ko/translation/admin-console/tabs.ts
  packages/phrases/src/locales/ko/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tabs.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tabs.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tabs.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/ru/translation/admin-console/tabs.ts
  packages/phrases/src/locales/ru/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tabs.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/tabs.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/tabs.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tabs.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/upsell/paywall.ts
  pnpm-lock.yaml
Labels: feature, size/l

#5690 refactor(core): dont throw for status errors in prod
  .changeset/cuddly-buses-obey.md
  packages/core/src/middleware/koa-guard.test.ts
  packages/core/src/middleware/koa-guard.ts
Labels: enhancement, size/s

#5724 chore(console): update incorrect swr cache key usages
  packages/console/src/pages/TenantSettings/TenantMembers/Invitations/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/InviteEmailsInput/hooks.ts
  packages/console/src/pages/TenantSettings/TenantMembers/Members/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/hooks.ts
  packages/console/src/pages/TenantSettings/TenantMembers/index.tsx
Labels: chore, size/s

#5720 feat(console): update user access immediately on tenant role updates
  packages/connectors/connector-logto-email/package.json
  packages/console/package.json
  packages/console/src/containers/ConsoleContent/hooks.ts
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/hooks/use-console-routes/routes/tenant-settings.tsx
  packages/console/src/hooks/use-current-tenant-scopes.ts
  packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/index.tsx
  packages/console/src/pages/TenantSettings/TenantDomainSettings/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/EditMemberModal/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/Invitations/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/Members/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/hooks.ts
  packages/console/src/pages/TenantSettings/TenantMembers/index.tsx
  packages/console/src/pages/TenantSettings/index.tsx
  packages/core/package.json
  packages/demo-app/package.json
  packages/integration-tests/package.json
  pnpm-lock.yaml
Labels: feature, size/m

#5728 refactor: remove pnpm script
  .pnpmfile.cjs
  packages/connectors/connector-alipay-native/package.json
  packages/connectors/connector-alipay-web/package.json
  packages/connectors/connector-aliyun-dm/package.json
  packages/connectors/connector-aliyun-sms/package.json
  packages/connectors/connector-apple/package.json
  packages/connectors/connector-aws-ses/package.json
  packages/connectors/connector-azuread/package.json
  packages/connectors/connector-discord/package.json
  packages/connectors/connector-facebook/package.json
  packages/connectors/connector-feishu-web/package.json
  packages/connectors/connector-github/package.json
  packages/connectors/connector-google/package.json
  packages/connectors/connector-kakao/package.json
  packages/connectors/connector-logto-email/package.json
  packages/connectors/connector-logto-sms/package.json
  packages/connectors/connector-logto-social-demo/package.json
  packages/connectors/connector-mailgun/package.json
  packages/connectors/connector-mock-email-alternative/package.json
  packages/connectors/connector-mock-email/package.json
  packages/connectors/connector-mock-sms/package.json
  packages/connectors/connector-mock-social/package.json
  packages/connectors/connector-naver/package.json
  packages/connectors/connector-oauth2/package.json
  packages/connectors/connector-oidc/package.json
  packages/connectors/connector-saml/package.json
  packages/connectors/connector-sendgrid-email/package.json
  packages/connectors/connector-smsaero/package.json
  packages/connectors/connector-smtp/package.json
  packages/connectors/connector-tencent-sms/package.json
  packages/connectors/connector-twilio-sms/package.json
  packages/connectors/connector-wechat-native/package.json
  packages/connectors/connector-wechat-web/package.json
  packages/connectors/connector-wecom/package.json
  packages/connectors/templates/package.json
  pnpm-lock.yaml
Labels: enhancement, size/xl

#5725 fix(core): set oidc access denied error code to 403
  .changeset/forty-grapes-relax.md
  packages/core/src/oidc/grants/refresh-token.ts
  packages/integration-tests/src/tests/api/oidc/refresh-token-grant.test.ts
Labels: bugfix, size/s

#5736 refactor(console,phrases): update phrases for organization role
  packages/console/src/pages/Organizations/Guide/Introduction/index.tsx
  packages/phrases/src/locales/de/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/de/translation/admin-console/organizations.ts
  packages/phrases/src/locales/en/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/en/translation/admin-console/organizations.ts
  packages/phrases/src/locales/es/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/es/translation/admin-console/organizations.ts
  packages/phrases/src/locales/fr/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/organizations.ts
  packages/phrases/src/locales/it/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/it/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ja/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ko/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organizations.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organizations.ts
  packages/phrases/src/locales/ru/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/organizations.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/organizations.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/organization-role-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/organizations.ts
Labels: enhancement, size/m

#5734 fix(console): cloud collaboration minor bug fixes
  packages/console/src/containers/ConsoleContent/hooks.ts
  packages/console/src/hooks/use-current-tenant-scopes.ts
Labels: bugfix, size/s

#5730 fix(core,console): invitee emails should be case insensitive
  .changeset/afraid-stingrays-perform.md
  packages/console/src/pages/TenantSettings/TenantMembers/InviteEmailsInput/hooks.ts
  packages/core/src/queries/organization/index.ts
  packages/integration-tests/src/tests/api/organization/organization-invitation.get.test.ts
Labels: bugfix, size/s

#5732 feat(console): add plausible
  packages/console/package.json
  packages/console/src/components/Conversion/index.tsx
  packages/console/src/components/Conversion/utils.ts
  packages/console/src/containers/ConsoleContent/index.tsx
  packages/console/src/hooks/use-console-routes/index.tsx
  packages/console/src/hooks/use-plausible-pageview.ts
  packages/console/src/include.d/tags.d.ts
  packages/console/src/onboarding/containers/AppContent/index.tsx
  packages/console/src/onboarding/index.tsx
  packages/console/src/utils/route.ts
  pnpm-lock.yaml
Labels: feature, size/m

#5729 test(console): assign permissions to organization role
  packages/integration-tests/src/tests/console/rbac/organization-rbac.test.ts
  packages/integration-tests/src/ui-helpers/expect-api-resources.ts
  packages/integration-tests/src/ui-helpers/expect-console.ts
  packages/integration-tests/src/ui-helpers/expect-organizations.ts
Labels: testing, size/l

#5733 refactor(console): remove AppInsights
  packages/console/jest.config.ts
  packages/console/package.json
  packages/console/src/App.tsx
  packages/console/src/components/PageMeta/index.tsx
  packages/console/src/containers/ConsoleRoutes/index.tsx
  packages/console/src/hooks/use-track-user-id.ts
  packages/console/src/onboarding/index.tsx
  packages/console/src/onboarding/pages/SignInExperience/index.tsx
  packages/console/src/onboarding/pages/Welcome/index.tsx
  packages/console/src/pages/ApiResourceDetails/index.tsx
  packages/console/src/pages/ApiResources/index.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/pages/Applications/index.tsx
  packages/console/src/pages/AuditLogDetails/index.tsx
  packages/console/src/pages/AuditLogs/index.tsx
  packages/console/src/pages/ConnectorDetails/index.tsx
  packages/console/src/pages/Connectors/index.tsx
  packages/console/src/pages/CustomizeJwt/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/index.tsx
  packages/console/src/pages/Dashboard/index.tsx
  packages/console/src/pages/EnterpriseSso/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/index.tsx
  packages/console/src/pages/GetStarted/index.tsx
  packages/console/src/pages/Mfa/index.tsx
  packages/console/src/pages/NotFound/index.tsx
  packages/console/src/pages/OrganizationRoleDetails/index.tsx
  packages/console/src/pages/OrganizationTemplate/index.tsx
  packages/console/src/pages/Profile/index.tsx
  packages/console/src/pages/RoleDetails/index.tsx
  packages/console/src/pages/Roles/index.tsx
  packages/console/src/pages/SignInExperience/index.tsx
  packages/console/src/pages/SigningKeys/index.tsx
  packages/console/src/pages/TenantSettings/BillingHistory/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/index.tsx
  packages/console/src/pages/TenantSettings/TenantDomainSettings/index.tsx
  packages/console/src/pages/UserDetails/index.tsx
  packages/console/src/pages/Users/index.tsx
  packages/console/src/pages/WebhookDetails/index.tsx
  packages/console/src/pages/Webhooks/index.tsx
  pnpm-lock.yaml
Labels: enhancement, size/m

#5742 refactor: remove AppInsights for React
  .changeset/ten-steaks-melt.md
  packages/app-insights/package.json
  packages/app-insights/src/react/AppInsightsBoundary.tsx
  packages/app-insights/src/react/AppInsightsReact.ts
  packages/app-insights/src/react/TrackOnce.tsx
  packages/app-insights/src/react/context.tsx
  packages/app-insights/src/react/index.ts
  packages/app-insights/src/react/utils.ts
  packages/app-insights/tsconfig.json
  packages/experience/jest.config.ts
  packages/experience/package.json
  packages/experience/src/App.tsx
  packages/experience/src/components/PageMeta/index.tsx
  pnpm-lock.yaml
Labels: enhancement, size/xl

#5746 fix(console): always display create org button
  packages/console/src/pages/Organizations/index.tsx
  packages/integration-tests/src/tests/console/organizations.test.ts
  packages/integration-tests/src/ui-helpers/expect-organizations.ts
Labels: bugfix, testing, size/s

#5752 fix(console): force dev feature enabled false
  packages/console/src/consts/env.ts
Labels: bugfix, size/xs

#5749 chore: upgrade packages
  package.json
  packages/connectors/connector-aws-ses/package.json
  packages/integration-tests/package.json
  pnpm-lock.yaml
Labels: chore, size/xs

#5619 feat(core): add redis cluster and tls extra options support
  .changeset/dull-frogs-perform.md
  packages/core/src/caches/index.test.ts
  packages/core/src/caches/index.ts
  packages/core/src/tenants/Tenant.ts
Labels: feature, size/m

#5747 chore(console): update custom JWT scripts sample
  packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/utils/config.tsx
Labels: chore, size/s

#5745 refactor(core): update cloud dependency, cloud client calls
  packages/connectors/connector-logto-email/package.json
  packages/console/package.json
  packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/utils/config.tsx
  packages/core/package.json
  packages/core/src/libraries/logto-config.script-merging.test.ts
  packages/core/src/libraries/logto-config.ts
  packages/core/src/oidc/extra-token-claims.ts
  packages/core/src/routes/logto-config/jwt-customizer.test.ts
  packages/core/src/routes/logto-config/jwt-customizer.ts
  packages/core/src/utils/custom-jwt/custom-jwt.ts
  packages/core/src/utils/custom-jwt/index.ts
  packages/core/src/utils/custom-jwt/types.ts
  pnpm-lock.yaml
Labels: enhancement, bugfix, size/xl

#5755 fix(console): revert the isDevFeaturesEnabled changes in console
  packages/console/src/consts/env.ts
Labels: bugfix, size/xs

#5757 chore: upgrade json5 to 2.2.3
  pnpm-lock.yaml
Labels: chore, size/xs

#5758 fix(console): pagination bar should be fully visible
  packages/console/src/pages/TenantSettings/TenantMembers/EditMemberModal/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/index.module.scss
Labels: bugfix, size/s

#5760 fix(console): replace ts with js for JWT customizer
  packages/console/src/pages/CustomizeJwtDetails/MainContent/MonacoCodeEditor/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/utils/config.tsx
Labels: bugfix, size/s

#5759 fix(console): rotate signing-key dropdown should be visible
  packages/console/src/components/Guide/ModalFooter/index.module.scss
  packages/console/src/components/Guide/index.module.scss
  packages/console/src/ds-components/Button/index.module.scss
  packages/console/src/ds-components/CodeEditor/index.module.scss
  packages/console/src/ds-components/ConfirmModal/index.module.scss
  packages/console/src/ds-components/Dropdown/index.module.scss
  packages/console/src/ds-components/Tip/TipBubble/index.module.scss
  packages/console/src/pages/ApiResourceDetails/components/GuideDrawer/index.module.scss
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/GuideDrawer/index.module.scss
  packages/console/src/pages/ApplicationDetails/components/AppGuide/index.module.scss
  packages/console/src/pages/Applications/components/GuideLibrary/index.module.scss
  packages/console/src/scss/_underscore.scss
Labels: bugfix, size/s

#5764 fix(console): copy to clipboard component should display at full width properly
  packages/console/src/components/ConnectorForm/ConfigForm/index.module.scss
  packages/console/src/components/ConnectorForm/ConfigForm/index.tsx
  packages/console/src/ds-components/CopyToClipboard/index.module.scss
  packages/console/src/ds-components/CopyToClipboard/index.tsx
  packages/console/src/mdx-components/ApplicationCredentials/index.tsx
  packages/console/src/mdx-components/OidcCallbackUri/index.module.scss
  packages/console/src/mdx-components/OidcCallbackUri/index.tsx
  packages/console/src/mdx-components/SsoSamlSpMetadata/index.module.scss
  packages/console/src/mdx-components/SsoSamlSpMetadata/index.tsx
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/EndpointsAndCredentials.tsx
  packages/console/src/pages/EnterpriseSsoDetails/Connection/OidcMetadataForm/index.module.scss
  packages/console/src/pages/EnterpriseSsoDetails/Connection/OidcMetadataForm/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/Connection/SamlAttributeMapping/index.module.scss
  packages/console/src/pages/EnterpriseSsoDetails/Connection/SamlAttributeMapping/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/Connection/SamlMetadataForm/ParsedConfigPreview/index.module.scss
  packages/console/src/pages/EnterpriseSsoDetails/Connection/SamlMetadataForm/ParsedConfigPreview/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/Connection/ServiceProviderInfo/OidcConnectorSpInfo.tsx
  packages/console/src/pages/EnterpriseSsoDetails/Connection/ServiceProviderInfo/SamlConnectorSpInfo.tsx
  packages/console/src/pages/EnterpriseSsoDetails/Connection/ServiceProviderInfo/index.module.scss
  packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/index.tsx
  packages/integration-tests/src/tests/console/sso-connectors/helpers.ts
Labels: bugfix, size/s

#5761 fix(console): fix the jwt creation page idle bug after submit form
  packages/console/src/pages/CustomizeJwtDetails/MainContent/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/use-data-fetch.ts
  packages/console/src/pages/CustomizeJwtDetails/utils/path.ts
Labels: bugfix, size/s

#5765 refactor(console): implement new jwt customizer delete modal
  packages/console/src/contexts/AppConfirmModalProvider/index.tsx
  packages/console/src/pages/CustomizeJwt/CustomizerItem/index.tsx
  packages/console/src/pages/CustomizeJwt/DeleteConfirmModal.tsx
  packages/console/src/pages/CustomizeJwt/index.tsx
Labels: enhancement, size/m

#5766 refactor(console): update organization guide and tenant member routers
  packages/console/src/hooks/use-console-routes/index.tsx
  packages/console/src/hooks/use-console-routes/routes/tenant-settings.tsx
  packages/console/src/pages/Organizations/Guide/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/index.tsx
Labels: enhancement, size/s

#5769 chore(experience): package update
  packages/experience/package.json
  pnpm-lock.yaml
Labels: chore, size/xs

#5771 style(experience): fix the terms of use link style
  packages/experience/src/components/TermsLinks/index.module.scss
  packages/experience/src/components/TermsLinks/index.tsx
  packages/experience/src/containers/TermsAndPrivacyCheckbox/index.module.scss
  packages/experience/src/containers/TermsAndPrivacyCheckbox/index.tsx
  packages/experience/src/containers/TermsAndPrivacyCheckbox/intext.test.tsx
  packages/experience/src/containers/TermsAndPrivacyConfirmModalContent/index.tsx
  packages/experience/src/containers/TermsAndPrivacyLinks/index.tsx
  packages/experience/src/hooks/use-terms.ts
  packages/experience/src/pages/Register/IdentifierRegisterForm/index.tsx
  packages/experience/src/pages/Register/index.tsx
Labels: size/s

#5772 chore(core): fix typo in code comments
  packages/core/src/oidc/init.ts
Labels: chore, size/xs

#5740 feat(console): add spring boot integration guide
  .changeset/soft-stingrays-beam.md
  packages/console/src/assets/docs/guides/index.ts
  packages/console/src/assets/docs/guides/web-java-spring-boot/README.mdx
  packages/console/src/assets/docs/guides/web-java-spring-boot/config.json
  packages/console/src/assets/docs/guides/web-java-spring-boot/index.ts
  packages/console/src/assets/docs/guides/web-java-spring-boot/logo.svg
  packages/console/src/assets/docs/guides/web-java/index.ts
  packages/console/src/assets/docs/guides/web-java/logo.svg
Labels: feature, size/l

#5773 feat(core): support comma separated resource param
  .changeset/rare-lamps-worry.md
  packages/core/src/middleware/koa-resource-param.test.ts
  packages/core/src/middleware/koa-resource-param.ts
  packages/core/src/oidc/init.ts
Labels: feature, size/s

#5782 fix(core): bump oidc-provider to fix resource indicator check
  .changeset/thick-carrots-tickle.md
  packages/core/package.json
  pnpm-lock.yaml
Labels: bugfix, size/xs

#5777 feat: add the new dockerize-edge job
  .github/workflows/release.yml
Labels: feature, size/s

#5762 feat(connector): support `client_secret_basic` and `client_secret_jwt` methods for oauth2 connectors
  .changeset/chilled-pugs-notice.md
  .github/workflows/main.yml
  .github/workflows/upload-annotations.yml
  packages/connectors/connector-oauth2/README.md
  packages/connectors/connector-oauth2/package.json
  packages/connectors/connector-oauth2/src/constant.ts
  packages/connectors/connector-oauth2/src/index.ts
  packages/connectors/connector-oauth2/src/oauth2/form-items.ts
  packages/connectors/connector-oauth2/src/oauth2/index.ts
  packages/connectors/connector-oauth2/src/oauth2/types.ts
  packages/connectors/connector-oauth2/src/oauth2/utils.test.ts
  packages/connectors/connector-oauth2/src/oauth2/utils.ts
  packages/connectors/connector-oauth2/src/types.ts
  packages/connectors/connector-oauth2/src/utils.ts
  packages/connectors/connector-oidc/README.md
  packages/connectors/connector-oidc/package.json
  packages/connectors/connector-oidc/src/constant.ts
  packages/connectors/connector-oidc/src/index.ts
  packages/connectors/connector-oidc/src/types.ts
  packages/connectors/connector-oidc/src/utils.ts
  packages/core/jest.config.js
  packages/core/nodemon.json
  packages/shared/package.json
  pnpm-lock.yaml
Labels: feature, size/xl

#5786 chore: ignore the hidden file found zap alert
  .zap/rules.conf
Labels: chore, size/xs

#5788 fix: fix zap config file
  .zap/rules.conf
Labels: bugfix, size/xs

#5784 refactor(core): update `AuthedRouter` -> `ManagementApiRouter`
  packages/core/src/routes/admin-user/basics.ts
  packages/core/src/routes/admin-user/index.ts
  packages/core/src/routes/admin-user/mfa-verifications.ts
  packages/core/src/routes/admin-user/organization.ts
  packages/core/src/routes/admin-user/role.ts
  packages/core/src/routes/admin-user/search.ts
  packages/core/src/routes/admin-user/social.ts
  packages/core/src/routes/applications/application-protected-app-metadata.ts
  packages/core/src/routes/applications/application-role.ts
  packages/core/src/routes/applications/application-sign-in-experience.ts
  packages/core/src/routes/applications/application-user-consent-organization.ts
  packages/core/src/routes/applications/application-user-consent-scope.ts
  packages/core/src/routes/applications/application.ts
  packages/core/src/routes/connector/authorization-uri.ts
  packages/core/src/routes/connector/config-testing.ts
  packages/core/src/routes/connector/factory.ts
  packages/core/src/routes/connector/index.ts
  packages/core/src/routes/custom-phrase.ts
  packages/core/src/routes/dashboard.ts
  packages/core/src/routes/domain.ts
  packages/core/src/routes/hook.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/log.ts
  packages/core/src/routes/logto-config/index.ts
  packages/core/src/routes/logto-config/jwt-customizer.ts
  packages/core/src/routes/organization/index.ts
  packages/core/src/routes/organization/invitations.ts
  packages/core/src/routes/organization/roles.ts
  packages/core/src/routes/organization/scopes.ts
  packages/core/src/routes/resource.scope.ts
  packages/core/src/routes/resource.ts
  packages/core/src/routes/role.application.ts
  packages/core/src/routes/role.scope.ts
  packages/core/src/routes/role.ts
  packages/core/src/routes/role.user.ts
  packages/core/src/routes/sign-in-experience/index.ts
  packages/core/src/routes/sso-connector/index.ts
  packages/core/src/routes/system.ts
  packages/core/src/routes/types.ts
  packages/core/src/routes/user-assets.ts
  packages/core/src/routes/verification-code.ts
  packages/core/src/utils/test-utils.ts
Labels: enhancement, size/m

#5785 feat: support organization custom data
  .changeset/healthy-knives-draw.md
  packages/console/src/pages/OrganizationDetails/Settings/index.tsx
  packages/integration-tests/src/helpers/organization.ts
  packages/integration-tests/src/tests/api/organization/organization.test.ts
  packages/phrases/src/locales/de/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/en/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/es/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/fr/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/it/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/ja/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/ko/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/ru/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/organization-details.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/organization-details.ts
  packages/schemas/alterations/next-1713942039-add-organization-custom-data.ts
  packages/schemas/tables/organizations.sql
Labels: feature, size/m

#5793 refactor(core): move the deploy/undeploy worker methods to jwtCustomizerLibrary
  packages/core/src/libraries/jwt-customizer.script-merging.test.ts
  packages/core/src/libraries/jwt-customizer.ts
  packages/core/src/libraries/logto-config.ts
  packages/core/src/routes/logto-config/jwt-customizer.test.ts
  packages/core/src/routes/logto-config/jwt-customizer.ts
  packages/core/src/tenants/Libraries.ts
  packages/core/src/tenants/Tenant.ts
  packages/core/src/test-utils/mock-libraries.ts
  packages/core/src/test-utils/tenant.ts
Labels: enhancement, size/l

#5792 chore: add code coverage token
  .github/workflows/main.yml
  .github/workflows/master-codecov-report.yml
Labels: chore, size/xs

#5800 fix(experience): use correct callback path for native environments
  .changeset/funny-books-sell.md
  packages/experience/src/containers/SocialSignInList/use-social.ts
  packages/experience/src/hooks/use-single-sign-on.ts
  packages/experience/src/pages/SocialSignInWebCallback/index.test.tsx
Labels: bugfix, size/s

#5798 refactor(console): remove useless log title definitions
  packages/console/src/consts/logs.ts
Labels: enhancement, size/s

#5735 fix(core): fix status code of create new user api
  packages/core/src/routes/admin-user/basics.ts
Labels: bugfix, size/xs

#5796 fix(experience,core): fix SSO register hook event not triggering bug
  .changeset/nine-turtles-learn.md
  packages/core/src/routes/interaction/single-sign-on.ts
  packages/experience/src/apis/interaction.ts
  packages/experience/src/apis/single-sign-on.ts
Labels: bugfix, size/s

#5803 feat(schemas): add table for app org resource scope consent
  packages/schemas/alterations/next-1714270244-application-org-resource-scope.ts
  packages/schemas/tables/application_user_consent_organization_resource_scopes.sql
Labels: feature, size/s

#5799 refactor: update plausible domain
  packages/console/src/components/Conversion/utils.ts
Labels: enhancement, size/xs

#5804 feat(core,schemas): add CRUD for consent organization resource scopes
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/ApplicationScopesAssignmentModal/constants.ts
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/ApplicationScopesAssignmentModal/use-application-scopes-assignment.ts
  packages/core/src/libraries/application.ts
  packages/core/src/queries/application-user-consent-scopes.ts
  packages/core/src/queries/application.ts
  packages/core/src/routes/applications/application-user-consent-scope.openapi.json
  packages/core/src/routes/applications/application-user-consent-scope.ts
  packages/integration-tests/src/api/application-user-consent-scope.ts
  packages/integration-tests/src/tests/api/application/application-user-consent-scope.test.ts
  packages/schemas/src/types/application.ts
Labels: feature, size/m
