Repository logto-io/logto, pull requests merged in 2024-12, with the labels that each got.

#6827 feat(core): add `PATCH/GET /saml-applications/:id` APIs
  packages/core/src/saml-applications/libraries/saml-applications.ts
  packages/core/src/saml-applications/libraries/secrets.ts
  packages/core/src/saml-applications/libraries/utils.ts
  packages/core/src/saml-applications/queries/configs.ts
  packages/core/src/saml-applications/routes/index.ts
  packages/core/src/saml-applications/routes/utils.ts
  packages/core/src/tenants/Libraries.ts
  packages/integration-tests/src/api/saml-application.ts
  packages/integration-tests/src/tests/api/application/saml-application.test.ts
  packages/schemas/src/foundations/jsonb-types/saml-application-configs.ts
  packages/schemas/src/types/saml-application.ts
Labels: feature, size/l

#6832 feat: add SAML app secret related APIs
  packages/core/src/saml-applications/libraries/saml-applications.ts
  packages/core/src/saml-applications/queries/secrets.ts
  packages/core/src/saml-applications/routes/index.ts
  packages/integration-tests/src/api/saml-application.ts
  packages/integration-tests/src/tests/api/application/saml-application.test.ts
  packages/phrases/src/locales/en/errors/application.ts
  packages/schemas/src/types/saml-application.ts
Labels: feature, size/m

#6833 feat: add SAML app anonymous metadata and certificate APIs
  packages/core/src/routes/init.ts
  packages/core/src/saml-applications/libraries/saml-applications.ts
  packages/core/src/saml-applications/libraries/utils.test.ts
  packages/core/src/saml-applications/libraries/utils.ts
  packages/core/src/saml-applications/queries/configs.ts
  packages/core/src/saml-applications/queries/secrets.ts
  packages/core/src/saml-applications/routes/anonymous.ts
  packages/core/src/saml-applications/routes/index.ts
  packages/core/src/utils/content-disposition.ts
  packages/integration-tests/src/api/saml-application.ts
  packages/integration-tests/src/tests/api/application/saml-application.test.ts
  packages/phrases/src/locales/en/errors/application.ts
  packages/schemas/src/foundations/jsonb-types/saml-application-configs.ts
  packages/schemas/src/types/saml-application.ts
Labels: feature, size/l

#6845 fix(core): fix applications APIs status guard
  packages/core/src/routes/applications/application.ts
  packages/integration-tests/src/tests/api/application/saml-application.test.ts
Labels: bugfix, size/s

#6849 refactor(console,core,schemas): allow SAML application to use IdP-initiated SSO
  packages/console/src/pages/EnterpriseSsoDetails/IdpInitiatedAuth/ConfigForm.tsx
  packages/console/src/pages/EnterpriseSsoDetails/IdpInitiatedAuth/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/IdpInitiatedAuth/utils.ts
  packages/core/src/libraries/sso-connector.test.ts
  packages/core/src/libraries/sso-connector.ts
  packages/phrases/src/locales/en/translation/admin-console/guide.ts
  packages/schemas/alterations/next-1733212543-add-saml-application-type-to-idp-initiated-sso-application-allow-list.ts
  packages/schemas/tables/sso_connector_idp_initiated_auth_configs.sql
Labels: enhancement, size/m

#6852 fix: fix some SAML app bugs
  packages/core/src/saml-applications/libraries/saml-applications.ts
  packages/core/src/saml-applications/libraries/utils.test.ts
  packages/core/src/saml-applications/libraries/utils.ts
  packages/core/src/saml-applications/queries/secrets.ts
  packages/core/src/saml-applications/routes/anonymous.ts
  packages/core/src/saml-applications/routes/index.ts
  packages/integration-tests/src/tests/api/application/saml-application.test.ts
  packages/schemas/src/foundations/jsonb-types/saml-application-configs.ts
  packages/schemas/src/types/saml-application.ts
Labels: bugfix, size/l

#6856 refactor: remove SAML app certificate/metadata download APIs
  packages/core/src/saml-applications/routes/index.ts
  packages/core/src/utils/content-disposition.ts
  packages/integration-tests/src/api/saml-application.ts
  packages/integration-tests/src/tests/api/application/saml-application.test.ts
Labels: enhancement, size/s

#6853 feat(console): add SAML IdP settings page
  packages/console/src/assets/icons/download.svg
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
  packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/CertificateActionMenu/index.module.scss
  packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/CertificateActionMenu/index.tsx
  packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/Settings.tsx
  packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/index.module.scss
  packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/index.tsx
  packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/use-secret-table-columns.tsx
  packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/utils.ts
  packages/console/src/pages/ApplicationDetails/components/Branding/NonThirdPartyBrandingForm.tsx
  packages/console/src/pages/ApplicationDetails/components/Branding/index.module.scss
  packages/console/src/pages/ApplicationDetails/components/Branding/index.tsx
  packages/console/src/pages/ApplicationDetails/components/Branding/use-application-sign-in-experience-swr.ts
  packages/console/src/pages/ApplicationDetails/components/Branding/use-sign-in-experience-swr.ts
  packages/console/src/pages/ApplicationDetails/components/Branding/utils.ts
  packages/console/src/pages/ApplicationDetails/components/Permissions/PermissionsCard/ApplicationScopesAssignmentModal/constants.ts
  packages/console/src/pages/ApplicationDetails/components/Permissions/PermissionsCard/ApplicationScopesAssignmentModal/index.tsx
  packages/console/src/pages/ApplicationDetails/components/Permissions/PermissionsCard/ApplicationScopesAssignmentModal/type.ts
  packages/console/src/pages/ApplicationDetails/components/Permissions/PermissionsCard/ApplicationScopesAssignmentModal/use-application-scopes-assignment.ts
  packages/console/src/pages/ApplicationDetails/components/Permissions/PermissionsCard/ApplicationScopesAssignmentModal/use-organization-scopes-assignment.ts
  packages/console/src/pages/ApplicationDetails/components/Permissions/PermissionsCard/ApplicationScopesAssignmentModal/use-resource-scopes-assignment.ts
  packages/console/src/pages/ApplicationDetails/components/Permissions/PermissionsCard/ApplicationScopesAssignmentModal/use-user-scopes-assignment.ts
  packages/console/src/pages/ApplicationDetails/components/Permissions/PermissionsCard/ApplicationScopesManagementModal/index.tsx
  packages/console/src/pages/ApplicationDetails/components/Permissions/PermissionsCard/index.module.scss
  packages/console/src/pages/ApplicationDetails/components/Permissions/PermissionsCard/index.tsx
  packages/console/src/pages/ApplicationDetails/components/Permissions/PermissionsCard/use-scopes-table.tsx
  packages/console/src/pages/ApplicationDetails/components/Permissions/index.module.scss
  packages/console/src/pages/ApplicationDetails/components/Permissions/index.tsx
  packages/console/src/pages/ApplicationDetails/index.tsx
  packages/console/src/utils/downloader.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/general.ts
Labels: feature, size/xl

#6857 feat(console): feat add SAML application creation
  packages/console/src/assets/docs/guides/generate-metadata.js
  packages/console/src/assets/docs/guides/index.tsx
  packages/console/src/assets/docs/guides/saml-idp/README.mdx
  packages/console/src/assets/docs/guides/saml-idp/index.ts
  packages/console/src/assets/docs/guides/saml-idp/logo.svg
  packages/console/src/assets/docs/guides/types.ts
  packages/console/src/components/ApplicationCreation/CreateForm/index.tsx
  packages/console/src/components/Guide/hooks.ts
Labels: feature, size/s

#6753 chore: add tips for HTTP email connector
  packages/connectors/connector-http-email/README.md
Labels: chore, size/xs

#6858 chore: upgrade vitest and happy-dom
  packages/app-insights/package.json
  packages/cli/package.json
  packages/connectors/connector-alipay-native/package.json
  packages/connectors/connector-alipay-web/package.json
  packages/connectors/connector-aliyun-dm/package.json
  packages/connectors/connector-aliyun-sms/package.json
  packages/connectors/connector-apple/package.json
  packages/connectors/connector-aws-ses/package.json
  packages/connectors/connector-azuread/package.json
  packages/connectors/connector-dingtalk-web/package.json
  packages/connectors/connector-discord/package.json
  packages/connectors/connector-facebook/package.json
  packages/connectors/connector-feishu-web/package.json
  packages/connectors/connector-gatewayapi-sms/package.json
  packages/connectors/connector-github/package.json
  packages/connectors/connector-gitlab/package.json
  packages/connectors/connector-google/package.json
  packages/connectors/connector-http-email/package.json
  packages/connectors/connector-huggingface/package.json
  packages/connectors/connector-kakao/package.json
  packages/connectors/connector-kook/package.json
  packages/connectors/connector-logto-email/package.json
  packages/connectors/connector-logto-sms/package.json
  packages/connectors/connector-logto-social-demo/package.json
  packages/connectors/connector-mailgun/package.json
  packages/connectors/connector-mock-email-alternative/package.json
  packages/connectors/connector-mock-email/package.json
  packages/connectors/connector-mock-sms/package.json
  packages/connectors/connector-mock-social/package.json
  packages/connectors/connector-naver/package.json
  packages/connectors/connector-oauth2/package.json
  packages/connectors/connector-oidc/package.json
  packages/connectors/connector-patreon/package.json
  packages/connectors/connector-postmark/package.json
  packages/connectors/connector-saml/package.json
  packages/connectors/connector-sendgrid-email/package.json
  packages/connectors/connector-smsaero/package.json
  packages/connectors/connector-smtp/package.json
  packages/connectors/connector-tencent-sms/package.json
  packages/connectors/connector-twilio-sms/package.json
  packages/connectors/connector-vonage-sms/package.json
  packages/connectors/connector-wechat-native/package.json
  packages/connectors/connector-wechat-web/package.json
  packages/connectors/connector-wecom/package.json
  packages/schemas/package.json
  packages/shared/package.json
  packages/toolkit/connector-kit/package.json
  packages/toolkit/core-kit/package.json
  packages/toolkit/language-kit/package.json
  packages/translate/package.json
  packages/tunnel/package.json
  pnpm-lock.yaml
Labels: chore, size/m

#6860 chore: whitelist add_on_sku_id
  .scripts/compare-database.js
Labels: chore, size/xs

#6861 refactor(console): replace get sku api
  packages/console/src/hooks/use-logto-skus.ts
Labels: enhancement, size/xs

#6862 fix: fix fetch official connector CLI error
  .changeset/chilled-radios-cover.md
  packages/cli/src/commands/connector/utils.ts
Labels: bugfix, size/s

#6834 fix(core): fix the subscription api response type
  packages/core/src/utils/subscription/index.ts
  packages/core/src/utils/subscription/types.ts
Labels: bugfix, size/s

#6868 Revert "refactor(console): replace get sku api"
  packages/console/src/hooks/use-logto-skus.ts
Labels: size/xs

#6869 fix(console): fix enterprise tenant current sku always return dev
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/index.tsx
  packages/console/src/contexts/SubscriptionDataProvider/use-new-subscription-data.ts
  packages/console/src/hooks/use-logto-skus.ts
  packages/console/src/pages/CheckoutSuccessCallback/index.tsx
  packages/console/src/utils/subscription.ts
Labels: bugfix, size/s

#6875 chore: remove unexpected console log
  packages/integration-tests/src/tests/console/user-management.test.ts
Labels: chore, size/xs

#6876 chore: bump ws version
  package.json
  pnpm-lock.yaml
Labels: chore, size/xs

#6863 refactor(console): refactor console paywall guards
  packages/console/src/components/ApplicationCreation/CreateForm/index.tsx
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/SkuCardItem/index.tsx
  packages/console/src/components/FeatureTag/index.tsx
  packages/console/src/components/Guide/GuideCard/index.tsx
  packages/console/src/components/PlanDescription/index.tsx
  packages/console/src/components/PlanUsage/index.tsx
  packages/console/src/consts/plan-quotas.ts
  packages/console/src/consts/subscriptions.ts
  packages/console/src/ds-components/CardTitle/index.tsx
  packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
  packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
  packages/console/src/pages/CustomizeJwt/index.tsx
  packages/console/src/pages/EnterpriseSso/SsoCreationModal/index.tsx
  packages/console/src/pages/EnterpriseSso/index.tsx
  packages/console/src/pages/Mfa/MfaForm/UpsellNotice/index.tsx
  packages/console/src/pages/Mfa/PageWrapper/index.tsx
  packages/console/src/pages/OrganizationTemplate/index.tsx
  packages/console/src/pages/Organizations/CreateOrganizationModal/index.tsx
  packages/console/src/pages/Organizations/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/Branding/CustomUiForm/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/AddOnUsageChangesNotification/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/MauLimitExceededNotification/index.tsx
  packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/index.tsx
  packages/console/src/pages/TenantSettings/components/NotEligibleSwitchPlanModalContent/index.tsx
  packages/console/src/utils/subscription.ts
Labels: enhancement, size/m

#6874 refactor(console, core): refactor console to support new pro plan
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/SkuCardItem/FeaturedSkuContent/use-featured-sku-content.ts
  packages/console/src/components/MauExceededModal/index.tsx
  packages/console/src/components/PlanUsage/index.tsx
  packages/console/src/consts/subscriptions.ts
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/SwitchPlanActionBar/index.tsx
  packages/console/src/utils/subscription.ts
  packages/core/src/libraries/quota.ts
  packages/phrases/src/locales/ar/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-table.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-table.ts
Labels: enhancement, size/l

#6882 chore: bump transitive dev-deps
  package.json
  pnpm-lock.yaml
Labels: chore, size/xs

#6879 fix(core): add the missing status code
  packages/core/src/routes/interaction/index.ts
Labels: bugfix, size/xs

#6886 refactor(console): add get tenant add-on-skus endpoint
  packages/connectors/connector-logto-email/package.json
  packages/connectors/connector-logto-email/src/index.ts
  packages/console/package.json
  packages/console/src/cloud/types/router.ts
  packages/console/src/components/PlanUsage/PlanUsageCard/index.tsx
  packages/console/src/components/PlanUsage/index.tsx
  packages/console/src/hooks/use-subscribe.ts
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/index.tsx
  packages/core/package.json
  packages/phrases/src/locales/ar/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/usage.ts
  pnpm-lock.yaml
Labels: enhancement, size/m

#6889 fix(console): should not apply dev guard
  packages/console/src/pages/TenantSettings/Subscription/index.tsx
Labels: bugfix, size/xs

#6880 feat(core,console): new mfa prompt policy
  .changeset/hot-oranges-join.md
  packages/console/src/pages/Mfa/MfaForm/constants.ts
  packages/console/src/pages/Mfa/MfaForm/index.tsx
  packages/console/src/pages/Mfa/MfaForm/utils.ts
  packages/console/src/pages/Mfa/types.ts
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/libraries/sign-in-experience/mfa.test.ts
  packages/core/src/routes/experience/classes/mfa.ts
  packages/core/src/routes/interaction/mfa.ts
  packages/core/src/routes/interaction/middleware/koa-interaction-sie.ts
  packages/core/src/routes/interaction/verifications/mfa-verification.backup-code.test.ts
  packages/core/src/routes/interaction/verifications/mfa-verification.test.ts
  packages/core/src/routes/interaction/verifications/mfa-verification.ts
  packages/experience-legacy/src/__mocks__/logto.tsx
  packages/experience/src/__mocks__/logto.tsx
  packages/integration-tests/src/helpers/sign-in-experience.ts
  packages/integration-tests/src/tests/api/experience-api/bind-mfa/happpy-path.test.ts
  packages/integration-tests/src/tests/api/sign-in-experience.test.ts
  packages/phrases/src/locales/en/translation/admin-console/mfa.ts
  packages/schemas/src/foundations/jsonb-types/sign-in-experience.ts
Labels: feature, size/l

#6892 fix(core): should not be able to skip mandatory MFA
  packages/core/src/routes/experience/classes/mfa.ts
  packages/core/src/routes/interaction/verifications/mfa-verification.ts
  packages/integration-tests/src/tests/api/experience-api/bind-mfa/happpy-path.test.ts
  packages/integration-tests/src/tests/api/interaction/mfa/totp.test.ts
Labels: bugfix, size/s

#6835 feat(core): add subscription cache class
  packages/core/src/caches/base-cache.ts
  packages/core/src/caches/tenant-subscription.ts
  packages/core/src/caches/types.ts
  packages/core/src/caches/well-known.test.ts
  packages/core/src/caches/well-known.ts
  packages/core/src/routes/experience/classes/verifications/password-verification.ts
  packages/core/src/sso/types/session.ts
  packages/core/src/utils/subscription/types.ts
  packages/schemas/src/consts/subscriptions.ts
Labels: feature, size/l

#6895 fix(console): auto close mfa switch
  packages/console/src/pages/Mfa/MfaForm/index.tsx
Labels: bugfix, size/xs

#6896 refactor(phrases): update mfa prompt selection text
  packages/phrases/src/locales/en/translation/admin-console/mfa.ts
Labels: enhancement, size/xs

#6877 feat(core): add token usage guard
  packages/core/src/__mocks__/cloud-connection.ts
  packages/core/src/caches/base-cache.ts
  packages/core/src/caches/tenant-subscription.ts
  packages/core/src/libraries/subscription.test.ts
  packages/core/src/libraries/subscription.ts
  packages/core/src/middleware/koa-token-usage-guard.ts
  packages/core/src/oidc/init.test.ts
  packages/core/src/oidc/init.ts
  packages/core/src/queries/daily-token-usage.ts
  packages/core/src/tenants/Tenant.ts
  packages/core/src/test-utils/tenant.ts
  packages/core/src/utils/subscription/types.ts
  packages/phrases/src/locales/en/errors/auth.ts
Labels: feature, size/l

#6872 feat(core): add SAML IdP `GET /saml-applications/:id/callback` API
  packages/core/src/saml-applications/libraries/consts.ts
  packages/core/src/saml-applications/libraries/saml-applications.ts
  packages/core/src/saml-applications/routes/anonymous.ts
  packages/core/src/saml-applications/routes/utils.test.ts
  packages/core/src/saml-applications/routes/utils.ts
  packages/core/src/sso/OidcConnector/utils.test.ts
  packages/core/src/sso/OidcConnector/utils.ts
  packages/core/src/sso/types/oidc.ts
  packages/phrases/src/locales/en/errors/application.ts
Labels: feature, size/xl

#6899 chore: update translation of connector readmes
  packages/connectors/connector-feishu-web/README.md
  packages/connectors/connector-tencent-sms/README.md
Labels: chore, size/m

#6897 refactor(console): show token usage exceed modal
  packages/console/src/components/MauTokenExceededModal/index.module.scss
  packages/console/src/components/MauTokenExceededModal/index.tsx
  packages/console/src/containers/AppContent/TenantNotificationContainer/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/upsell/index.ts
Labels: enhancement, size/s

#6898 feat(console): add token usage notification banner
  packages/console/src/components/PlanUsage/PlanUsageCard/index.module.scss
  packages/console/src/components/PlanUsage/PlanUsageCard/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/TokenLimitExceededNotification/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/subscription/index.ts
Labels: feature, size/m

#6901 fix(console): fix mfa form mandatory reset
  packages/console/src/pages/Mfa/MfaForm/index.tsx
Labels: bugfix, size/s

#6903 style(console): update the default font color
  packages/demo-app/src/scss/normalized.scss
Labels: size/xs

#6902 fix(core): handle unexpected user unique identifier error
  packages/core/src/middleware/koa-slonik-error-handler.ts
Labels: bugfix, size/s

#6904 feat(console): add token exceed tag
  packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/TenantStatusTag.tsx
  packages/phrases/src/locales/en/translation/admin-console/tenants.ts
Labels: feature, size/s

#6907 feat(console): add token usage exceed notification
  packages/console/src/pages/TenantSettings/DevTenantNotification/index.tsx
  packages/console/src/pages/TenantSettings/index.module.scss
  packages/console/src/pages/TenantSettings/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/subscription/index.ts
Labels: feature, size/s

#6908 chore(core): remove token limit dev feature guard
  packages/core/src/oidc/init.ts
Labels: chore, size/xs

#6881 feat: add saml app sessions table
  packages/core/src/saml-applications/queries/sessions.ts
  packages/core/src/tenants/Queries.ts
  packages/schemas/alterations/next-1735012422-add-saml-application-sessions-table.ts
  packages/schemas/src/foundations/jsonb-types/index.ts
  packages/schemas/src/foundations/jsonb-types/saml-application-sessions.ts
  packages/schemas/tables/saml_application_sessions.sql
Labels: feature, size/m

#6905 feat(connector): add Xiaomi social login connector
  .changeset/rotten-lizards-buy.md
  packages/connectors/connector-xiaomi/README.md
  packages/connectors/connector-xiaomi/README.zh-CN.md
  packages/connectors/connector-xiaomi/logo.svg
  packages/connectors/connector-xiaomi/package.json
  packages/connectors/connector-xiaomi/src/constant.ts
  packages/connectors/connector-xiaomi/src/index.test.ts
  packages/connectors/connector-xiaomi/src/index.ts
  packages/connectors/connector-xiaomi/src/mock.ts
  packages/connectors/connector-xiaomi/src/types.ts
  pnpm-lock.yaml
Labels: feature, size/xl
