Repository logto-io/logto, pull requests merged in 2025-05, with the labels that each got.

#7355 feat(core,schemas,console): add email blocklist policy to sie
  packages/console/src/pages/SignInExperience/PageContent/utils/parser.ts
  packages/console/src/pages/SignInExperience/types.ts
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/libraries/sign-in-experience/email-blocklist-policy.test.ts
  packages/core/src/libraries/sign-in-experience/email-blocklist-policy.ts
  packages/core/src/libraries/sign-in-experience/index.ts
  packages/core/src/queries/sign-in-experience.test.ts
  packages/core/src/routes/sign-in-experience/index.ts
  packages/experience/src/__mocks__/logto.tsx
  packages/phrases/src/locales/en/errors/sign-in-experiences.ts
  packages/schemas/alterations/next-1745735646-add-email-blocklist-policy-column-to-sie-table.ts
  packages/schemas/src/foundations/jsonb-types/sign-in-experience.ts
  packages/schemas/tables/sign_in_experiences.sql
Labels: feature, size/m

#7356 feat(console,core,toolkit,phrases): add email blocklist page
  packages/console/src/components/MultiOptionInput/index.module.scss
  packages/console/src/components/MultiOptionInput/index.tsx
  packages/console/src/consts/external-links.ts
  packages/console/src/hooks/use-console-routes/routes/security.tsx
  packages/console/src/pages/Security/Blocklist/BlocklistForm/index.module.scss
  packages/console/src/pages/Security/Blocklist/BlocklistForm/index.tsx
  packages/console/src/pages/Security/Blocklist/index.module.scss
  packages/console/src/pages/Security/Blocklist/index.tsx
  packages/console/src/pages/Security/index.tsx
  packages/console/src/pages/Security/types.ts
  packages/core/src/libraries/sign-in-experience/email-blocklist-policy.ts
  packages/phrases/src/locales/ar/errors/sign-in-experiences.ts
  packages/phrases/src/locales/ar/translation/admin-console/security.ts
  packages/phrases/src/locales/de/errors/sign-in-experiences.ts
  packages/phrases/src/locales/de/translation/admin-console/security.ts
  packages/phrases/src/locales/en/translation/admin-console/security.ts
  packages/phrases/src/locales/es/errors/sign-in-experiences.ts
  packages/phrases/src/locales/es/translation/admin-console/security.ts
  packages/phrases/src/locales/fr/errors/sign-in-experiences.ts
  packages/phrases/src/locales/fr/translation/admin-console/security.ts
  packages/phrases/src/locales/it/errors/sign-in-experiences.ts
  packages/phrases/src/locales/it/translation/admin-console/security.ts
  packages/phrases/src/locales/ja/errors/sign-in-experiences.ts
  packages/phrases/src/locales/ja/translation/admin-console/security.ts
  packages/phrases/src/locales/ko/errors/sign-in-experiences.ts
  packages/phrases/src/locales/ko/translation/admin-console/security.ts
  packages/phrases/src/locales/pl-pl/errors/sign-in-experiences.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/security.ts
  packages/phrases/src/locales/pt-br/errors/sign-in-experiences.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/security.ts
  packages/phrases/src/locales/pt-pt/errors/sign-in-experiences.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/security.ts
  packages/phrases/src/locales/ru/errors/sign-in-experiences.ts
  packages/phrases/src/locales/ru/translation/admin-console/security.ts
  packages/phrases/src/locales/tr-tr/errors/sign-in-experiences.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/security.ts
  packages/phrases/src/locales/zh-cn/errors/sign-in-experiences.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/security.ts
  packages/phrases/src/locales/zh-hk/errors/sign-in-experiences.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/security.ts
  packages/phrases/src/locales/zh-tw/errors/sign-in-experiences.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/security.ts
  packages/toolkit/core-kit/src/regex.test.ts
  packages/toolkit/core-kit/src/regex.ts
Labels: feature, size/xl

#7368 feat(core): add email blocklist guard
  .npmrc
  packages/core/src/libraries/sign-in-experience/email-blocklist-policy.test.ts
  packages/core/src/libraries/sign-in-experience/email-blocklist-policy.ts
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.ts
  packages/core/src/routes/experience/classes/profile.ts
  packages/integration-tests/src/tests/api/experience-api/register-interaction/email-blocklist.test.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/password.test.ts
  packages/phrases/src/locales/ar/errors/session.ts
  packages/phrases/src/locales/de/errors/session.ts
  packages/phrases/src/locales/en/errors/session.ts
  packages/phrases/src/locales/es/errors/session.ts
  packages/phrases/src/locales/fr/errors/session.ts
  packages/phrases/src/locales/it/errors/session.ts
  packages/phrases/src/locales/ja/errors/session.ts
  packages/phrases/src/locales/ko/errors/session.ts
  packages/phrases/src/locales/pl-pl/errors/session.ts
  packages/phrases/src/locales/pt-br/errors/session.ts
  packages/phrases/src/locales/pt-pt/errors/session.ts
  packages/phrases/src/locales/ru/errors/session.ts
  packages/phrases/src/locales/tr-tr/errors/session.ts
  packages/phrases/src/locales/zh-cn/errors/session.ts
  packages/phrases/src/locales/zh-hk/errors/session.ts
  packages/phrases/src/locales/zh-tw/errors/session.ts
Labels: feature, size/xl

#7382 feat(core): enhanced user lookup by phone number
  .changeset/nice-houses-sneeze.md
  packages/core/src/libraries/social.ts
  packages/core/src/queries/user.ts
  packages/core/src/routes/experience/classes/utils.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/password.test.ts
  packages/shared/src/utils/phone.test.ts
  packages/shared/src/utils/phone.ts
Labels: feature, size/l

#7374 feat(core,experience): add disposable email validation
  packages/console/src/pages/Security/Blocklist/BlocklistForm/index.tsx
  packages/core/src/libraries/sign-in-experience/email-blocklist-policy.ts
  packages/experience/src/hooks/use-email-blocked-error-handler.ts
  packages/experience/src/hooks/use-submit-interaction-error-handler.ts
  packages/phrases/src/locales/ar/errors/session.ts
  packages/phrases/src/locales/de/errors/session.ts
  packages/phrases/src/locales/en/errors/session.ts
  packages/phrases/src/locales/es/errors/session.ts
  packages/phrases/src/locales/fr/errors/session.ts
  packages/phrases/src/locales/it/errors/session.ts
  packages/phrases/src/locales/ja/errors/session.ts
  packages/phrases/src/locales/ko/errors/session.ts
  packages/phrases/src/locales/pl-pl/errors/session.ts
  packages/phrases/src/locales/pt-br/errors/session.ts
  packages/phrases/src/locales/pt-pt/errors/session.ts
  packages/phrases/src/locales/ru/errors/session.ts
  packages/phrases/src/locales/tr-tr/errors/session.ts
  packages/phrases/src/locales/zh-cn/errors/session.ts
  packages/phrases/src/locales/zh-hk/errors/session.ts
  packages/phrases/src/locales/zh-tw/errors/session.ts
  packages/shared/src/node/env/GlobalValues.ts
Labels: feature, size/m

#7376 feat(core): add email blocklist validation to account API
  packages/core/src/routes/account/email-and-phone.ts
  packages/integration-tests/src/tests/api/account/email-and-phone.test.ts
Labels: feature, size/s

#7377 feat(core): add email blocklist policy paywall guard
  packages/core/src/libraries/sign-in-experience/email-blocklist-policy.test.ts
  packages/core/src/libraries/sign-in-experience/email-blocklist-policy.ts
  packages/core/src/queries/tenant-usage/index.ts
  packages/core/src/routes/sign-in-experience/index.ts
Labels: feature, size/s

#7389 refactor: use `gpt-4.1` as the default translate model
  .changeset/funny-eels-wonder.md
  .changeset/moody-turtles-bake.md
  packages/translate/src/openai.ts
  packages/translate/src/sync-keys/utils.ts
Labels: enhancement, size/s

#7386 fix(console): manual trigger usage update
  packages/console/src/pages/Security/Blocklist/BlocklistForm/index.tsx
  packages/console/src/pages/Security/Captcha/index.tsx
  packages/console/src/pages/Security/General/GeneralForm/index.tsx
Labels: bugfix, size/s

#7387 fix(console,phrases): update console phrases
  packages/console/src/pages/Security/Blocklist/BlocklistForm/index.tsx
  packages/phrases/src/locales/ar/errors/session.ts
  packages/phrases/src/locales/ar/translation/admin-console/security.ts
  packages/phrases/src/locales/de/errors/session.ts
  packages/phrases/src/locales/de/translation/admin-console/security.ts
  packages/phrases/src/locales/en/translation/admin-console/security.ts
  packages/phrases/src/locales/es/errors/session.ts
  packages/phrases/src/locales/es/translation/admin-console/security.ts
  packages/phrases/src/locales/fr/errors/session.ts
  packages/phrases/src/locales/fr/translation/admin-console/security.ts
  packages/phrases/src/locales/it/errors/session.ts
  packages/phrases/src/locales/it/translation/admin-console/security.ts
  packages/phrases/src/locales/ja/errors/session.ts
  packages/phrases/src/locales/ja/translation/admin-console/security.ts
  packages/phrases/src/locales/ko/errors/session.ts
  packages/phrases/src/locales/ko/translation/admin-console/security.ts
  packages/phrases/src/locales/pl-pl/errors/session.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/security.ts
  packages/phrases/src/locales/pt-br/errors/session.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/security.ts
  packages/phrases/src/locales/pt-pt/errors/session.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/security.ts
  packages/phrases/src/locales/ru/errors/session.ts
  packages/phrases/src/locales/ru/translation/admin-console/security.ts
  packages/phrases/src/locales/tr-tr/errors/session.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/security.ts
  packages/phrases/src/locales/zh-cn/errors/session.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/security.ts
  packages/phrases/src/locales/zh-hk/errors/session.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/security.ts
  packages/phrases/src/locales/zh-tw/errors/session.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/security.ts
Labels: bugfix, size/m

#7388 fix(experience): add email blocked error handler
  packages/experience/src/pages/SocialSignInWebCallback/use-single-sign-on-listener.ts
Labels: bugfix, size/s

#7385 refactor(core): has user with normalized phone number match
  packages/core/src/libraries/user.ts
  packages/core/src/queries/user.ts
  packages/core/src/routes/account/email-and-phone.ts
  packages/core/src/routes/admin-user/basics.test.ts
  packages/core/src/routes/admin-user/basics.ts
  packages/core/src/routes/admin-user/mfa-verifications.test.ts
  packages/core/src/routes/experience/classes/experience-interaction.test.ts
  packages/core/src/routes/experience/classes/libraries/profile-validator.ts
  packages/core/src/routes/experience/classes/verifications/social-verification.ts
  packages/core/src/routes/interaction/actions/helpers.ts
  packages/core/src/routes/interaction/actions/submit-interaction.mfa.test.ts
  packages/core/src/routes/interaction/actions/submit-interaction.test.ts
  packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.test.ts
  packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.ts
  packages/core/src/routes/interaction/verifications/profile-verification.profile-exist.test.ts
  packages/core/src/routes/interaction/verifications/profile-verification.profile-registered.test.ts
  packages/core/src/routes/interaction/verifications/profile-verification.protected-identifier.test.ts
  packages/core/src/routes/interaction/verifications/profile-verification.ts
  packages/integration-tests/src/tests/api/account/email-and-phone.test.ts
  packages/integration-tests/src/tests/api/admin-user.test.ts
  packages/integration-tests/src/tests/api/experience-api/profile/fulfill-user-profiles.test.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/password.test.ts
  packages/integration-tests/src/utils.ts
Labels: enhancement, size/l

#7390 chore: update README.md
  README.md
  assets/logto-features.jpg
  assets/logto-features.png
Labels: chore, size/s

#7392 refactor(core): make userinfo endpoint optional for OIDC SSO connectors
  .changeset/dirty-mice-fail.md
  packages/core/src/saml-application/SamlApplication/index.ts
  packages/core/src/sso/AzureOidcSsoConnector/index.ts
  packages/core/src/sso/OidcConnector/index.ts
  packages/core/src/sso/types/oidc.ts
Labels: enhancement, size/s

#7395 feat(core,experience): pre validate email blocklist
  packages/core/src/libraries/sign-in-experience/email-blocklist-policy.ts
  packages/core/src/routes/experience/verification-routes/verification-code.ts
  packages/experience/src/hooks/use-send-verification-code.ts
  packages/experience/src/pages/Continue/IdentifierProfileForm/index.tsx
  packages/integration-tests/src/tests/api/experience-api/register-interaction/email-blocklist.test.ts
Labels: feature, size/m

#5882 feat: add phone number validation to user APIs
  .changeset/big-games-deny.md
  packages/console/package.json
  packages/console/src/pages/UserDetails/UserSettings/index.tsx
  packages/core/src/libraries/user.ts
  packages/core/src/queries/user.ts
  packages/core/src/routes/admin-user/mfa-verifications.test.ts
  packages/core/src/routes/interaction/utils/single-sign-on.ts
  packages/core/src/utils/user.ts
  packages/experience/package.json
  packages/experience/src/utils/country-code.ts
  packages/experience/src/utils/form.ts
  packages/integration-tests/src/tests/api/admin-user.phone-number.test.ts
  packages/integration-tests/src/tests/api/admin-user.search.test.ts
  packages/integration-tests/src/tests/api/role.user.test.ts
  packages/shared/package.json
  packages/shared/src/utils/phone.ts
  pnpm-lock.yaml
Labels: feature, size/l

#7396 fix(console): update captcha backlink and always show captcha toggle
  .changeset/perfect-phones-relax.md
  packages/console/src/pages/CaptchaDetails/index.tsx
  packages/console/src/pages/Security/Captcha/EnableCaptcha/index.tsx
  packages/console/src/pages/Security/Captcha/index.tsx
Labels: bugfix, size/s

#7397 feat(core): remove dev feature guard for email blocklist
  .changeset/honest-news-rush.md
  .changeset/soft-eggs-sell.md
  packages/console/src/hooks/use-console-routes/routes/security.tsx
  packages/console/src/pages/Security/index.tsx
  packages/core/src/libraries/sign-in-experience/email-blocklist-policy.ts
  packages/core/src/routes/account/email-and-phone.ts
  packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.ts
  packages/core/src/routes/sign-in-experience/index.openapi.json
  packages/integration-tests/src/tests/api/account/email-and-phone.test.ts
  packages/integration-tests/src/tests/api/experience-api/register-interaction/email-blocklist.test.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/password.test.ts
Labels: feature, size/l

#7384 feat(console): add remix guide
  packages/console/src/assets/docs/guides/index.tsx
  packages/console/src/assets/docs/guides/web-remix/README.mdx
  packages/console/src/assets/docs/guides/web-remix/config.json
  packages/console/src/assets/docs/guides/web-remix/index.ts
  packages/console/src/assets/docs/guides/web-remix/logo-dark.svg
  packages/console/src/assets/docs/guides/web-remix/logo.svg
Labels: feature, size/m

#7380 feat(connector): add QQ connector
  .changeset/red-rules-cheat.md
  packages/connectors/connector-qq/README.md
  packages/connectors/connector-qq/README.zh-CN.md
  packages/connectors/connector-qq/logo.svg
  packages/connectors/connector-qq/package.json
  packages/connectors/connector-qq/src/constant.ts
  packages/connectors/connector-qq/src/index.test.ts
  packages/connectors/connector-qq/src/index.ts
  packages/connectors/connector-qq/src/mock.ts
  packages/connectors/connector-qq/src/types.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#7400 Revert "fix(console): update captcha backlink and always show captcha toggle"
  .changeset/perfect-phones-relax.md
  packages/console/src/pages/CaptchaDetails/index.tsx
  packages/console/src/pages/Security/Captcha/EnableCaptcha/index.tsx
  packages/console/src/pages/Security/Captcha/index.tsx
Labels: size/s

#7402 fix(console): update captcha backlink and always show captcha toggle
  .changeset/perfect-phones-relax.md
  packages/console/src/pages/CaptchaDetails/index.tsx
  packages/console/src/pages/Security/Captcha/CaptchaForm.module.scss
  packages/console/src/pages/Security/Captcha/CaptchaForm.tsx
  packages/console/src/pages/Security/Captcha/EnableCaptcha/index.tsx
  packages/console/src/pages/Security/Captcha/index.module.scss
  packages/console/src/pages/Security/Captcha/index.tsx
Labels: bugfix, size/l

#7404 fix(console): mutate sie data on captcha settings update
  packages/console/src/pages/Security/Captcha/CaptchaForm.tsx
Labels: bugfix, size/xs

#7405 chore: update README.md
  README.md
Labels: chore, size/xs

#7403 feat(console,core,schemas): support multiple passkeys with custom name
  packages/console/package.json
  packages/console/src/components/MfaFactorName/index.module.scss
  packages/console/src/components/MfaFactorName/index.tsx
  packages/console/src/components/MfaFactorTitle/index.tsx
  packages/core/src/utils/user.ts
  packages/schemas/src/foundations/jsonb-types/users.ts
  packages/schemas/src/types/interactions.ts
  packages/schemas/src/types/user.ts
  pnpm-lock.yaml
Labels: feature, size/s

#7408 feat(core): add passkey via account api
  packages/core/src/routes/account/index.openapi.json
  packages/core/src/routes/account/index.ts
  packages/core/src/routes/account/mfa-verifications.ts
  packages/core/src/routes/verification/index.openapi.json
  packages/core/src/routes/verification/index.ts
  packages/integration-tests/src/api/verification-record.ts
  packages/integration-tests/src/helpers/index.ts
  packages/integration-tests/src/helpers/sign-in-experience.ts
  packages/integration-tests/src/tests/api/account/mfa.test.ts
  packages/schemas/src/foundations/jsonb-types/account-centers.ts
Labels: feature, size/l

#7419 fix(console): hide name label if agent is empty
  packages/console/src/components/MfaFactorName/index.tsx
Labels: bugfix, size/xs

#7415 feat(core): update webauthn passkey name
  packages/core/src/routes/account/index.openapi.json
  packages/core/src/routes/account/mfa-verifications.ts
  packages/core/src/routes/verification/index.openapi.json
Labels: feature, size/s, size/l
