Repository logto-io/logto, pull requests merged in 2025-02, with the labels that each got.

#6995 fix: otp double signin bug
  packages/experience-legacy/src/containers/TotpCodeVerification/index.tsx
  packages/experience/src/containers/TotpCodeVerification/index.tsx
Labels: bugfix, size/s

#6967 chore: add SAML app API docs
  packages/core/src/routes/saml-application/anonymous.ts
  packages/core/src/routes/saml-application/index.openapi.json
  packages/core/src/routes/saml-application/saml-app-auth-flow.openapi.json
  packages/core/src/routes/swagger/utils/documents.ts
  packages/core/src/routes/swagger/utils/general.ts
  packages/core/src/routes/swagger/utils/operation.ts
Labels: chore, size/xl

#7005 fix(core): trigger webhook in organization invitation flow
  .changeset/afraid-turkeys-swim.md
  packages/core/src/routes/organization-invitation/index.ts
  packages/integration-tests/src/tests/api/hook/hook.trigger.custom.data.test.ts
Labels: bugfix, size/s

#7007 feat(console): display jwks uri on application details page
  .changeset/purple-glasses-fix.md
  packages/console/src/consts/oidc.ts
  packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/EndpointsAndCredentials/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
Labels: feature, size/s

#7011 chore: add paywall banner to SAML app footer
  packages/console/src/components/ApplicationCreation/CreateForm/Footer/index.tsx
  packages/console/src/consts/external-links.ts
  packages/phrases/src/locales/ar/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/de/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/en/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/es/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/fr/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/it/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/ja/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/ko/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/ru/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/upsell/paywall.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/upsell/paywall.ts
Labels: chore, size/s

#7013 fix(cli): fix cli add official connectors command missing connectors bug
  .changeset/rotten-bugs-pretend.md
  packages/cli/src/commands/connector/utils.ts
Labels: bugfix, size/s

#7019 fix(core): update openapi.json for post user asset api
  packages/core/src/routes/user-assets.openapi.json
Labels: bugfix, size/s

#7002 feat(schemas): add new email templates table
  packages/schemas/alterations/next-1738828268-add-email-templates-table.ts
  packages/schemas/src/foundations/jsonb-types/email-templates.ts
  packages/schemas/src/foundations/jsonb-types/index.ts
  packages/schemas/tables/email_templates.sql
Labels: feature, size/s

#7010 feat(core): add PUT and DELETE email-templates api
  packages/core/src/queries/email-templates.ts
  packages/core/src/routes/email-template/index.openapi.json
  packages/core/src/routes/email-template/index.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/sso-connector/idp-initiated-auth-config.openapi.json
  packages/core/src/routes/sso-connector/index.ts
  packages/core/src/routes/swagger/utils/documents.ts
  packages/core/src/routes/swagger/utils/parameters.ts
  packages/core/src/tenants/Queries.ts
  packages/integration-tests/src/__mocks__/email-templates.ts
  packages/integration-tests/src/api/email-templates.ts
  packages/integration-tests/src/helpers/email-templates.ts
  packages/integration-tests/src/tests/api/email-templates.test.ts
Labels: feature, size/l

#7006 fix(connector): fix kook connector fail with empty banner
  .changeset/itchy-singers-allow.md
  packages/connectors/connector-kook/src/index.test.ts
  packages/connectors/connector-kook/src/types.ts
Labels: bugfix, size/s

#7016 feat(core): add get email-templates api
  packages/core/src/queries/email-templates.ts
  packages/core/src/routes/email-template/index.openapi.json
  packages/core/src/routes/email-template/index.ts
  packages/integration-tests/src/api/email-templates.ts
  packages/integration-tests/src/tests/api/email-templates.test.ts
Labels: feature, size/m

#7017 feat(core): add update email template details api
  packages/core/src/routes/email-template/index.openapi.json
  packages/core/src/routes/email-template/index.ts
  packages/integration-tests/src/api/email-templates.ts
  packages/integration-tests/src/tests/api/email-templates.test.ts
Labels: feature, size/m

#7018 feat(core): delete email template by langaugeTag or templateType
  packages/core/src/queries/email-templates.ts
  packages/core/src/routes/email-template/index.openapi.json
  packages/core/src/routes/email-template/index.ts
  packages/core/src/routes/swagger/utils/operation-id.ts
  packages/integration-tests/src/api/email-templates.ts
  packages/integration-tests/src/tests/api/email-templates.test.ts
Labels: feature, size/m

#7023 refactor(core): redesign email templates bulk delete API
  packages/core/src/routes/email-template/index.openapi.json
  packages/core/src/routes/email-template/index.ts
  packages/core/src/routes/swagger/utils/operation-id.ts
  packages/integration-tests/src/api/email-templates.ts
  packages/integration-tests/src/tests/api/email-templates.test.ts
  packages/phrases/src/locales/en/errors/connector.ts
Labels: enhancement, size/m

#7025 fix(experience): filter wechat connectors by platform
  .changeset/pink-roses-confess.md
  .changeset/rotten-bugs-pretend.md
  packages/experience-legacy/src/utils/sign-in-experience.ts
  packages/experience/src/utils/sign-in-experience.ts
Labels: bugfix, size/s

#7022 fix(core): apply custom domain on SAML SSO and app
  .changeset/wise-cows-scream.md
  packages/console/src/mdx-components/SsoSamlSpMetadata/index.tsx
  packages/core/src/env-set/index.ts
  packages/core/src/routes/authn.ts
  packages/core/src/routes/interaction/utils/single-sign-on.test.ts
  packages/core/src/routes/interaction/utils/single-sign-on.ts
  packages/core/src/routes/saml-application/anonymous.ts
  packages/core/src/routes/saml-application/index.ts
  packages/core/src/routes/sso-connector/index.ts
  packages/core/src/routes/sso-connector/utils.test.ts
  packages/core/src/routes/sso-connector/utils.ts
  packages/core/src/saml-application/SamlApplication/index.test.ts
  packages/core/src/saml-application/SamlApplication/index.ts
  packages/core/src/sso/SamlConnector/index.ts
  packages/core/src/sso/SamlSsoConnector/index.test.ts
  packages/core/src/sso/SamlSsoConnector/index.ts
Labels: bugfix, size/m

#7027 fix(console): add missing `/api` segment in SAML app SSO URL
  .changeset/gentle-rabbits-chew.md
  packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/Settings.tsx
Labels: bugfix, size/xs

#7035 chore: bump dependencies for security update
  .changeset/weak-tigers-cover.md
  package.json
  packages/app-insights/package.json
  packages/cli/package.json
  packages/connectors/connector-alipay-native/package.json
  packages/connectors/connector-alipay-web/package.json
  packages/connectors/connector-aliyun-dm/package.json
  packages/connectors/connector-aliyun-sms/package.json
  packages/connectors/connector-apple/package.json
  packages/connectors/connector-aws-ses/package.json
  packages/connectors/connector-azuread/package.json
  packages/connectors/connector-dingtalk-web/package.json
  packages/connectors/connector-discord/package.json
  packages/connectors/connector-facebook/package.json
  packages/connectors/connector-feishu-web/package.json
  packages/connectors/connector-gatewayapi-sms/package.json
  packages/connectors/connector-github/package.json
  packages/connectors/connector-gitlab/package.json
  packages/connectors/connector-google/package.json
  packages/connectors/connector-http-email/package.json
  packages/connectors/connector-huggingface/package.json
  packages/connectors/connector-kakao/package.json
  packages/connectors/connector-kook/package.json
  packages/connectors/connector-logto-email/package.json
  packages/connectors/connector-logto-sms/package.json
  packages/connectors/connector-logto-social-demo/package.json
  packages/connectors/connector-mailgun/package.json
  packages/connectors/connector-mock-email-alternative/package.json
  packages/connectors/connector-mock-email/package.json
  packages/connectors/connector-mock-sms/package.json
  packages/connectors/connector-mock-social/package.json
  packages/connectors/connector-naver/package.json
  packages/connectors/connector-oauth2/package.json
  packages/connectors/connector-oidc/package.json
  packages/connectors/connector-patreon/package.json
  packages/connectors/connector-postmark/package.json
  packages/connectors/connector-saml/package.json
  packages/connectors/connector-sendgrid-email/package.json
  packages/connectors/connector-smsaero/package.json
  packages/connectors/connector-smtp/package.json
  packages/connectors/connector-tencent-sms/package.json
  packages/connectors/connector-twilio-sms/package.json
  packages/connectors/connector-vonage-sms/package.json
  packages/connectors/connector-wechat-native/package.json
  packages/connectors/connector-wechat-web/package.json
  packages/connectors/connector-wecom/package.json
  packages/connectors/connector-xiaomi/package.json
  packages/connectors/connector-yunpian-sms/package.json
  packages/console/package.json
  packages/core/package.json
  packages/demo-app/package.json
  packages/integration-tests/package.json
  packages/schemas/package.json
  packages/shared/package.json
  packages/toolkit/connector-kit/package.json
  packages/toolkit/core-kit/package.json
  packages/toolkit/language-kit/package.json
  packages/translate/package.json
  packages/tunnel/package.json
  pnpm-lock.yaml
Labels: chore, size/l

#7028 fix(core): prevent i18n context contamination by using request-scoped instance
  .changeset/rare-readers-cry.md
  packages/core/src/errors/RequestError/index.ts
  packages/core/src/errors/RequestError/request-error.test.ts
  packages/core/src/middleware/koa-error-handler.test.ts
  packages/core/src/middleware/koa-error-handler.ts
  packages/core/src/middleware/koa-experience-ssr.test.ts
  packages/core/src/middleware/koa-i18next.test.ts
  packages/core/src/middleware/koa-i18next.ts
  packages/core/src/middleware/koa-oidc-error-handler.test.ts
  packages/core/src/middleware/koa-oidc-error-handler.ts
  packages/core/src/oidc/init.ts
  packages/core/src/tenants/Tenant.ts
  packages/core/src/utils/i18n.ts
  packages/core/src/utils/test-utils.ts
Labels: bugfix, size/m

#7040 refactor: remove unnecessary quota guard and usage report
  packages/core/src/middleware/koa-quota-guard.ts
  packages/core/src/routes/organization-role/index.ts
  packages/core/src/routes/organization-scope/index.ts
Labels: enhancement, size/s

#7033 refactor: sync SAML app redirectUris upon custom domain status updates
  packages/core/src/libraries/domain.test.ts
  packages/core/src/libraries/domain.ts
  packages/core/src/libraries/saml-application/saml-applications.ts
  packages/core/src/routes/domain.test.ts
  packages/core/src/routes/domain.ts
  packages/core/src/routes/saml-application/index.ts
  packages/core/src/saml-application/SamlApplication/index.test.ts
  packages/core/src/saml-application/SamlApplication/index.ts
Labels: enhancement, size/m

#7046 fix(core): fix incorrect condition check
  .changeset/seven-cows-look.md
  packages/core/src/routes/verification/index.ts
Labels: bugfix, size/s

#7041 fix(experience): fix email/phone identifier conflict handling logic during user registration
  .changeset/loud-beds-obey.md
  packages/experience/src/containers/VerificationCode/use-register-flow-code-verification.ts
  packages/experience/src/hooks/use-sie.ts
Labels: bugfix, size/s

#7047 fix(core): fix SAML app redirect URIs sync custom domains logic
  packages/core/src/libraries/saml-application/saml-applications.ts
  packages/core/src/routes/domain.test.ts
  packages/core/src/routes/domain.ts
Labels: bugfix, size/m

#7015 feat(connector): add x connector
  .changeset/strange-ghosts-draw.md
  packages/connectors/connector-x/README.md
  packages/connectors/connector-x/logo.svg
  packages/connectors/connector-x/package.json
  packages/connectors/connector-x/src/constant.ts
  packages/connectors/connector-x/src/index.test.ts
  packages/connectors/connector-x/src/index.ts
  packages/connectors/connector-x/src/mock.ts
  packages/connectors/connector-x/src/types.ts
  packages/connectors/connector-x/src/utils.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#7021 feat(connector): add slack connector
  .changeset/rude-books-applaud.md
  packages/connectors/connector-slack/README.md
  packages/connectors/connector-slack/logo.svg
  packages/connectors/connector-slack/package.json
  packages/connectors/connector-slack/src/constant.ts
  packages/connectors/connector-slack/src/index.test.ts
  packages/connectors/connector-slack/src/index.ts
  packages/connectors/connector-slack/src/mock.ts
  packages/connectors/connector-slack/src/types.ts
  pnpm-lock.yaml
Labels: feature, size/l

#7052 fix(connector): update Aliyun SMS connector config
  packages/connectors/connector-aliyun-sms/src/constant.ts
  packages/connectors/connector-aliyun-sms/src/index.ts
  packages/connectors/connector-aliyun-sms/src/types.ts
  packages/connectors/connector-aliyun-sms/src/utils.test.ts
  packages/connectors/connector-aliyun-sms/src/utils.ts
Labels: bugfix, size/s

#7054 chore: update SAML auth request info guard and add more info to log
  packages/core/src/routes/saml-application/anonymous.ts
  packages/schemas/src/foundations/jsonb-types/saml-application-sessions.ts
Labels: chore, size/xs

#7055 fix(core): should not apply custom domain to SAML app SP entity ID
  packages/core/src/routes/saml-application/anonymous.ts
  packages/core/src/saml-application/SamlApplication/index.ts
Labels: bugfix, size/s

#7032 feat(connector): add linkedin connector
  .changeset/thin-paws-yell.md
  packages/connectors/connector-linkedin/README.md
  packages/connectors/connector-linkedin/logo.svg
  packages/connectors/connector-linkedin/package.json
  packages/connectors/connector-linkedin/src/constant.ts
  packages/connectors/connector-linkedin/src/index.test.ts
  packages/connectors/connector-linkedin/src/index.ts
  packages/connectors/connector-linkedin/src/mock.ts
  packages/connectors/connector-linkedin/src/types.ts
  packages/connectors/connector-linkedin/src/utils.ts
  pnpm-lock.yaml
Labels: feature, size/l

#7034 feat(connector): add amazon social connector
  .changeset/beige-shoes-remain.md
  packages/connectors/connector-amazon/README.md
  packages/connectors/connector-amazon/logo.svg
  packages/connectors/connector-amazon/package.json
  packages/connectors/connector-amazon/src/constant.ts
  packages/connectors/connector-amazon/src/index.test.ts
  packages/connectors/connector-amazon/src/index.ts
  packages/connectors/connector-amazon/src/mock.ts
  packages/connectors/connector-amazon/src/types.ts
  pnpm-lock.yaml
Labels: feature, size/l

#7039 feat(connector): add line connector
  .changeset/itchy-impalas-remain.md
  packages/connectors/connector-line/README.md
  packages/connectors/connector-line/logo.svg
  packages/connectors/connector-line/package.json
  packages/connectors/connector-line/src/constant.ts
  packages/connectors/connector-line/src/index.test.ts
  packages/connectors/connector-line/src/index.ts
  packages/connectors/connector-line/src/mock.ts
  packages/connectors/connector-line/src/types.ts
  packages/connectors/connector-line/src/utils.ts
  pnpm-lock.yaml
Labels: feature, size/l

#7037 feat(core,toolkit): pass locale ctx to sendMessage method
  packages/cli/src/connector/utils.ts
  packages/connectors/connector-mock-email/src/index.ts
  packages/core/src/libraries/connector.ts
  packages/core/src/libraries/passcode.ts
  packages/core/src/queries/email-templates.ts
  packages/core/src/routes-me/init.ts
  packages/core/src/routes-me/types.ts
  packages/core/src/routes-me/verification-code.ts
  packages/core/src/routes/connector/config-testing.openapi.json
  packages/core/src/routes/connector/config-testing.ts
  packages/core/src/routes/experience/classes/verifications/code-verification.ts
  packages/core/src/routes/experience/types.ts
  packages/core/src/routes/experience/verification-routes/verification-code.ts
  packages/core/src/routes/interaction/additional.ts
  packages/core/src/routes/interaction/utils/verification-code-validation.ts
  packages/core/src/routes/verification-code.ts
  packages/core/src/routes/verification/index.ts
  packages/integration-tests/src/__mocks__/email-templates.ts
  packages/integration-tests/src/api/connector.ts
  packages/integration-tests/src/helpers/email-templates.ts
  packages/integration-tests/src/helpers/index.ts
  packages/integration-tests/src/helpers/profile.ts
  packages/integration-tests/src/tests/api/email-templates/connector-test-api.test.ts
  packages/integration-tests/src/tests/api/email-templates/index.test.ts
  packages/integration-tests/src/tests/api/email-templates/organization-invitation.test.ts
  packages/integration-tests/src/tests/api/email-templates/user-account-api.test.ts
  packages/schemas/src/foundations/jsonb-types/email-templates.ts
  packages/toolkit/connector-kit/src/types/email-template.ts
  packages/toolkit/connector-kit/src/types/index.ts
  packages/toolkit/connector-kit/src/types/passwordless.ts
Labels: feature, size/xl

#7048 feat(connector): update email connectors to support i18n
  packages/connectors/connector-aliyun-dm/src/index.test.ts
  packages/connectors/connector-aliyun-dm/src/index.ts
  packages/connectors/connector-aliyun-dm/src/mock.ts
  packages/connectors/connector-aws-ses/src/index.test.ts
  packages/connectors/connector-aws-ses/src/index.ts
  packages/connectors/connector-aws-ses/src/mock.ts
  packages/connectors/connector-aws-ses/src/utils.ts
  packages/connectors/connector-mailgun/src/index.test.ts
  packages/connectors/connector-mailgun/src/index.ts
  packages/connectors/connector-mock-email/src/index.ts
  packages/connectors/connector-sendgrid-email/src/index.test.ts
  packages/connectors/connector-sendgrid-email/src/index.ts
  packages/connectors/connector-sendgrid-email/src/mock.ts
  packages/connectors/connector-smtp/src/index.test.ts
  packages/connectors/connector-smtp/src/index.ts
Labels: feature, size/xl

#7057 fix(core): add AuthnStatement for SAML assertion response
  packages/core/src/routes/saml-application/anonymous.ts
  packages/core/src/routes/saml-application/utils.ts
  packages/core/src/saml-application/SamlApplication/consts.ts
  packages/core/src/saml-application/SamlApplication/index.test.ts
  packages/core/src/saml-application/SamlApplication/index.ts
Labels: bugfix, size/m

#7049 refactor(core): add email templates redis cache
  packages/core/src/caches/base-cache.ts
  packages/core/src/caches/well-known.test.ts
  packages/core/src/caches/well-known.ts
  packages/core/src/queries/email-templates.ts
Labels: enhancement, size/m

#7053 feat(toolkit,core): support nested properties in email template variables
  .changeset/small-hairs-pretend.md
  packages/connectors/connector-mock-email/src/index.ts
  packages/connectors/connector-tencent-sms/src/index.ts
  packages/core/src/libraries/organization-invitation.ts
  packages/core/src/routes/organization-invitation/index.ts
  packages/core/src/utils/connectors/extra-information.ts
  packages/integration-tests/src/tests/api/email-templates/organization-invitation.test.ts
  packages/toolkit/connector-kit/src/index.test.ts
  packages/toolkit/connector-kit/src/index.ts
  packages/toolkit/connector-kit/src/types/passwordless.ts
Labels: feature, size/l

#7056 feat(core): pass extra context to email template
  packages/core/src/libraries/organization-invitation.ts
  packages/core/src/libraries/passcode.test.ts
  packages/core/src/libraries/passcode.ts
  packages/core/src/middleware/koa-auth/koa-oidc-auth.test.ts
  packages/core/src/middleware/koa-auth/koa-oidc-auth.ts
  packages/core/src/middleware/koa-auth/types.ts
  packages/core/src/routes-me/verification-code.ts
  packages/core/src/routes/experience/classes/verifications/code-verification.ts
  packages/core/src/routes/experience/verification-routes/verification-code.ts
  packages/core/src/routes/interaction/additional.test.ts
  packages/core/src/routes/interaction/additional.ts
  packages/core/src/routes/interaction/utils/verification-code-validation.ts
  packages/core/src/routes/organization-invitation/index.ts
  packages/core/src/routes/verification-code.ts
  packages/core/src/routes/verification/index.ts
  packages/core/src/utils/connectors/extra-information.ts
  packages/core/src/utils/connectors/types.ts
  packages/integration-tests/src/helpers/index.ts
  packages/integration-tests/src/tests/api/email-templates/experience-api.test.ts
  packages/integration-tests/src/tests/api/email-templates/interaction-api.test.ts
  packages/integration-tests/src/tests/api/email-templates/organization-invitation.test.ts
  packages/integration-tests/src/tests/api/email-templates/user-account-api.test.ts
Labels: feature, size/xl

#7063 fix(tunnel): fix potential garbled text response in tunnel mode
  .changeset/rich-seas-burn.md
  packages/tunnel/package.json
  packages/tunnel/src/commands/tunnel/utils.ts
  pnpm-lock.yaml
Labels: bugfix, size/s

#7061 refactor: adjust TOTP secret length to 20 bytes
  .changeset/four-houses-invite.md
  packages/core/src/routes/interaction/utils/totp-validation.ts
Labels: enhancement, feature, size/s

#7066 release(tunnel): release tunnel cli 0.2.6
  .changeset/rich-seas-burn.md
  packages/tunnel/CHANGELOG.md
  packages/tunnel/package.json
Labels: size/s

#7060 chore: add changesets
  .changeset/beige-dolls-cheat.md
  .changeset/six-mugs-greet.md
Labels: chore, size/s

#7069 fix(console): update docs link
  .changeset/twelve-glasses-dance.md
  packages/console/src/consts/external-links.ts
Labels: bugfix, size/xs

#7070 fix(core): show all organization permissions
  .changeset/strange-oranges-sort.md
  packages/core/src/routes/organization-role/index.openapi.json
  packages/core/src/routes/organization-role/index.ts
  packages/core/src/routes/organization-scope/index.openapi.json
  packages/core/src/routes/organization-scope/index.ts
  packages/core/src/utils/SchemaRouter.ts
  packages/integration-tests/src/tests/api/hook/hook.trigger.data.test.ts
  packages/integration-tests/src/tests/api/organization/organization-scope.test.ts
  packages/integration-tests/src/tests/api/organization/organization-user.test.ts
Labels: bugfix, size/s

#7062 fix(connector): fix misuse of replyTo field
  packages/connectors/connector-mailgun/src/index.test.ts
  packages/connectors/connector-mailgun/src/index.ts
  packages/connectors/connector-sendgrid-email/src/index.test.ts
  packages/connectors/connector-sendgrid-email/src/index.ts
  packages/connectors/connector-smtp/src/index.test.ts
  packages/toolkit/connector-kit/src/types/email-template.ts
Labels: bugfix, size/s

#7072 chore: remove unnecessary console log
  packages/core/src/libraries/saml-application/saml-applications.ts
Labels: chore, size/xs

#7078 chore: update README
  README.md
Labels: chore, size/s

#7076 feat(core): assign organization roles by name
  .changeset/spicy-pets-approve.md
  packages/core/src/queries/organization/index.ts
  packages/core/src/routes/organization/user/index.openapi.json
  packages/core/src/routes/organization/user/role-relations.ts
  packages/integration-tests/src/api/organization.ts
  packages/integration-tests/src/tests/api/organization/organization-user.test.ts
  packages/phrases/src/locales/en/errors/organization.ts
Labels: feature, size/m

#7036 feat(core): implement legacy password migration support
  .changeset/empty-feet-leave.md
  packages/core/src/libraries/user.test.ts
  packages/core/src/libraries/user.ts
  packages/core/src/routes/admin-user/basics.ts
  packages/core/src/utils/password.test.ts
  packages/core/src/utils/password.ts
  packages/phrases/src/locales/ar/errors/password.ts
  packages/phrases/src/locales/de/errors/password.ts
  packages/phrases/src/locales/en/errors/password.ts
  packages/phrases/src/locales/es/errors/password.ts
  packages/phrases/src/locales/fr/errors/password.ts
  packages/phrases/src/locales/it/errors/password.ts
  packages/phrases/src/locales/ja/errors/password.ts
  packages/phrases/src/locales/ko/errors/password.ts
  packages/phrases/src/locales/pl-pl/errors/password.ts
  packages/phrases/src/locales/pt-br/errors/password.ts
  packages/phrases/src/locales/pt-pt/errors/password.ts
  packages/phrases/src/locales/ru/errors/password.ts
  packages/phrases/src/locales/tr-tr/errors/password.ts
  packages/phrases/src/locales/zh-cn/errors/password.ts
  packages/phrases/src/locales/zh-hk/errors/password.ts
  packages/phrases/src/locales/zh-tw/errors/password.ts
  packages/schemas/alterations/next-1739429593-add-legacy-password-encryption.ts
  packages/schemas/tables/users.sql
Labels: feature, size/l

#7080 fix(experience): add loading status
  packages/experience/src/hooks/use-send-verification-code.ts
  packages/experience/src/pages/SignInPassword/PasswordForm/VerificationCodeLink.tsx
Labels: bugfix, size/s

#7074 fix(connector): update logo of connectors
  .changeset/hungry-bears-argue.md
  packages/connectors/connector-amazon/logo-dark.svg
  packages/connectors/connector-amazon/logo.svg
  packages/connectors/connector-amazon/src/constant.ts
  packages/connectors/connector-line/logo-dark.svg
  packages/connectors/connector-line/logo.svg
  packages/connectors/connector-line/src/constant.ts
  packages/connectors/connector-x/logo-dark.svg
  packages/connectors/connector-x/logo.svg
  packages/connectors/connector-x/src/constant.ts
Labels: bugfix, size/s
