Repository logto-io/logto, pull requests merged in 2025-04, with the labels that each got.

#7217 test: increase wait time for backchannel logout test
  packages/integration-tests/src/tests/console/backchannel-logout.test.ts
Labels: testing, size/xs

#7204 feat(core): add recatpcha enterprise verification
  packages/core/src/routes/experience/classes/libraries/captcha-validator.ts
  packages/schemas/src/foundations/jsonb-types/captcha.ts
Labels: feature, size/s

#7218 feat(experience,core): add recaptcha enterprise to frontend
  packages/core/src/middleware/koa-security-headers.ts
  packages/experience/src/components/ReCaptchaEnterprise/index.module.scss
  packages/experience/src/components/ReCaptchaEnterprise/index.tsx
  packages/experience/src/containers/CaptchaBox/index.tsx
Labels: feature, size/s

#7203 feat(core): check captcha before sending verification code
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/verification-routes/verification-code.ts
  packages/integration-tests/src/tests/api/experience-api/captcha/index.test.ts
Labels: feature, size/s

#7224 fix(core): fix recaptcha verification
  packages/core/src/routes/experience/classes/libraries/captcha-validator.ts
Labels: bugfix, size/s

#7223 chore: bump js sdks and demonstrate skip clearing token usage in demo-app
  packages/console/package.json
  packages/core/package.json
  packages/demo-app/package.json
  packages/demo-app/src/App.tsx
  packages/integration-tests/package.json
  pnpm-lock.yaml
Labels: chore, size/s

#7226 fix(console): should not show diff modal for default values update
  packages/console/src/pages/SignInExperience/PageContent/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/utils/parser.ts
Labels: bugfix, size/s

#7227 fix(experience): fix the interaction event in continue sign-in
  packages/experience/src/containers/VerificationCode/use-continue-flow-code-verification.ts
  packages/experience/src/containers/VerificationCode/use-sign-in-with-exist-identifier-confirm-modal.ts
Labels: bugfix, size/s

#7225 refactor(experience): execute captcha when click
  packages/experience/src/App.tsx
  packages/experience/src/Providers/CaptchaContextProvider/CaptchaContext.tsx
  packages/experience/src/Providers/CaptchaContextProvider/constant.ts
  packages/experience/src/Providers/CaptchaContextProvider/index.tsx
  packages/experience/src/Providers/CaptchaContextProvider/utils.ts
  packages/experience/src/components/IdentifierRegisterForm/index.tsx
  packages/experience/src/components/ReCaptchaEnterprise/index.module.scss
  packages/experience/src/components/ReCaptchaEnterprise/index.tsx
  packages/experience/src/components/Turnstile/index.tsx
  packages/experience/src/containers/CaptchaBox/index.module.scss
  packages/experience/src/containers/CaptchaBox/index.tsx
  packages/experience/src/hooks/use-captcha.ts
  packages/experience/src/include.d/global.d.ts
Labels: enhancement, size/xl

#7229 refactor(demo-app): better showcase the magic link usage in demo app
  packages/demo-app/src/App.tsx
  packages/demo-app/src/Callback.tsx
Labels: enhancement, size/s

#7228 refactor(experience): improve go back logic handling in one-time token pages
  packages/experience/src/pages/ErrorPage/index.tsx
  packages/experience/src/pages/OneTimeToken/index.tsx
  packages/experience/src/pages/SwitchAccount/index.tsx
Labels: enhancement, size/s

#7220 fix(core): provision user who has valid sign-in session to organizations when using one-time token
  packages/core/src/libraries/one-time-token.ts
  packages/core/src/middleware/koa-consent-guard.test.ts
  packages/core/src/middleware/koa-consent-guard.ts
  packages/core/src/tenants/Tenant.ts
  packages/experience/src/App.tsx
  packages/experience/src/pages/OneTimeToken/index.tsx
  packages/experience/src/pages/Register/index.tsx
  packages/experience/src/pages/SignIn/index.tsx
  packages/experience/src/pages/SwitchAccount/index.tsx
  packages/schemas/src/consts/experience.ts
Labels: bugfix, size/m

#7232 fix(experience): browser password manager should pick up one-time token email from hidden input
  packages/experience/src/pages/OneTimeToken/index.tsx
Labels: bugfix, size/s

#7230 chore(core): bump the tar-fs dep version
  package.json
  pnpm-lock.yaml
Labels: chore, size/xs

#7236 feat(core): add management API to fetch one-time token by ID
  packages/core/src/libraries/one-time-token.ts
  packages/core/src/queries/one-time-tokens.ts
  packages/core/src/routes/one-time-tokens.openapi.json
  packages/core/src/routes/one-time-tokens.ts
  packages/core/src/routes/swagger/utils/documents.ts
  packages/integration-tests/src/api/one-time-token.ts
  packages/integration-tests/src/tests/api/one-time-tokens.test.ts
Labels: feature, size/l

#7237 feat(core): add management API to delete one-time token
  packages/core/src/queries/one-time-tokens.ts
  packages/core/src/routes/one-time-tokens.openapi.json
  packages/core/src/routes/one-time-tokens.ts
  packages/integration-tests/src/api/one-time-token.ts
  packages/integration-tests/src/tests/api/one-time-tokens.test.ts
Labels: feature, size/s

#7239 feat(core): add management API to batch fetch one-time tokens
  packages/core/src/queries/one-time-tokens.ts
  packages/core/src/routes/one-time-tokens.openapi.json
  packages/core/src/routes/one-time-tokens.ts
  packages/integration-tests/src/api/one-time-token.ts
  packages/integration-tests/src/tests/api/one-time-tokens.test.ts
Labels: feature, size/m

#7235 chore: bump dependencies
  package.json
  packages/integration-tests/package.json
  pnpm-lock.yaml
Labels: chore, size/xs

#7243 fix(console): change recaptcha form fields label
  packages/console/src/pages/Security/CaptchaFormFields/index.tsx
  packages/console/src/pages/Security/CreateCaptchaForm/constants.ts
  packages/console/src/pages/Security/CreateCaptchaForm/types.ts
  packages/phrases/src/locales/en/translation/admin-console/security.ts
Labels: bugfix, size/s

#7244 fix(console): add turnstile readme
  packages/console/src/pages/Security/CreateCaptchaForm/constants.ts
Labels: bugfix, size/s

#7246 fix(console): add recaptcha readme
  packages/console/src/pages/Security/CreateCaptchaForm/constants.ts
Labels: bugfix, size/s

#7251 chore: remove dev feature test for SAML app
  packages/integration-tests/src/tests/api/application/saml-application.test.ts
Labels: chore, size/xs

#7242 fix(core,console): fix captcha deletion behavior
  packages/console/src/pages/CaptchaDetails/index.tsx
  packages/console/src/pages/Security/Guide/index.tsx
  packages/console/src/pages/Security/use-data-fetch.ts
  packages/core/src/routes/captcha-provider/index.ts
Labels: bugfix, size/s

#7248 fix(core): skip catpcha for otp
  packages/core/src/routes/experience/verification-routes/one-time-token.ts
  packages/integration-tests/src/tests/api/experience-api/captcha/index.test.ts
Labels: bugfix, size/s

#7250 chore(core): remove password encryption worker dev guard
  .changeset/hungry-elephants-look.md
  packages/core/src/utils/password.ts
  packages/core/src/workers/tasks/argon2i.ts
Labels: chore, size/s

#7258 refactor(console): refactor security page structure
  packages/console/src/hooks/use-console-routes/routes/security.tsx
  packages/console/src/pages/CaptchaDetails/CaptchaContent/index.tsx
  packages/console/src/pages/CaptchaDetails/index.tsx
  packages/console/src/pages/Security/Captcha/CaptchaCard/index.module.scss
  packages/console/src/pages/Security/Captcha/CaptchaCard/index.tsx
  packages/console/src/pages/Security/Captcha/CaptchaFormFields/index.tsx
  packages/console/src/pages/Security/Captcha/CaptchaLogo/index.module.scss
  packages/console/src/pages/Security/Captcha/CaptchaLogo/index.tsx
  packages/console/src/pages/Security/Captcha/CreateCaptchaForm/ProviderRadioGroup/ProviderRadio/index.module.scss
  packages/console/src/pages/Security/Captcha/CreateCaptchaForm/ProviderRadioGroup/ProviderRadio/index.tsx
  packages/console/src/pages/Security/Captcha/CreateCaptchaForm/ProviderRadioGroup/index.module.scss
  packages/console/src/pages/Security/Captcha/CreateCaptchaForm/ProviderRadioGroup/index.tsx
  packages/console/src/pages/Security/Captcha/CreateCaptchaForm/constants.ts
  packages/console/src/pages/Security/Captcha/CreateCaptchaForm/index.module.scss
  packages/console/src/pages/Security/Captcha/CreateCaptchaForm/index.tsx
  packages/console/src/pages/Security/Captcha/CreateCaptchaForm/types.ts
  packages/console/src/pages/Security/Captcha/EnableCaptcha/index.module.scss
  packages/console/src/pages/Security/Captcha/EnableCaptcha/index.tsx
  packages/console/src/pages/Security/Captcha/Guide/index.module.scss
  packages/console/src/pages/Security/Captcha/Guide/index.tsx
  packages/console/src/pages/Security/Captcha/index.module.scss
  packages/console/src/pages/Security/Captcha/index.tsx
  packages/console/src/pages/Security/Captcha/types.tsx
  packages/console/src/pages/Security/Captcha/use-data-fetch.ts
  packages/console/src/pages/Security/index.module.scss
  packages/console/src/pages/Security/index.tsx
  packages/console/src/pages/Security/types.ts
  packages/phrases/src/locales/en/translation/admin-console/security.ts
Labels: enhancement, size/l

#7260 refactor(phrases): update token not found error message
  packages/core/src/queries/one-time-tokens.ts
  packages/phrases/src/locales/ar/errors/one-time-token.ts
  packages/phrases/src/locales/de/errors/one-time-token.ts
  packages/phrases/src/locales/en/errors/one-time-token.ts
  packages/phrases/src/locales/es/errors/one-time-token.ts
  packages/phrases/src/locales/fr/errors/one-time-token.ts
  packages/phrases/src/locales/it/errors/one-time-token.ts
  packages/phrases/src/locales/ja/errors/one-time-token.ts
  packages/phrases/src/locales/ko/errors/one-time-token.ts
  packages/phrases/src/locales/pl-pl/errors/one-time-token.ts
  packages/phrases/src/locales/pt-br/errors/one-time-token.ts
  packages/phrases/src/locales/pt-pt/errors/one-time-token.ts
  packages/phrases/src/locales/ru/errors/one-time-token.ts
  packages/phrases/src/locales/tr-tr/errors/one-time-token.ts
  packages/phrases/src/locales/zh-cn/errors/one-time-token.ts
  packages/phrases/src/locales/zh-hk/errors/one-time-token.ts
  packages/phrases/src/locales/zh-tw/errors/one-time-token.ts
Labels: enhancement, size/s

#7174 feat: calculate tenant usage in core
  packages/core/src/libraries/quota.ts
  packages/core/src/queries/tenant-usage/index.ts
  packages/core/src/queries/tenant-usage/types.ts
  packages/core/src/routes/resource.scope.ts
  packages/core/src/routes/role.scope.ts
  packages/core/src/routes/sign-in-experience/index.ts
  packages/core/src/tenants/Libraries.ts
  packages/core/src/tenants/Queries.ts
  packages/core/src/test-utils/quota.ts
Labels: feature, size/xl

#7212 refactor(core): refactor org apis
  packages/core/src/routes/organization/index.ts
  packages/core/src/utils/SchemaRouter.ts
Labels: enhancement, size/m

#7271 chore(phrases): sync password policy phrases
  packages/phrases/src/locales/ar/translation/admin-console/security.ts
  packages/phrases/src/locales/de/translation/admin-console/security.ts
  packages/phrases/src/locales/es/translation/admin-console/security.ts
  packages/phrases/src/locales/fr/translation/admin-console/security.ts
  packages/phrases/src/locales/it/translation/admin-console/security.ts
  packages/phrases/src/locales/ja/translation/admin-console/security.ts
  packages/phrases/src/locales/ko/translation/admin-console/security.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/security.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/security.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/security.ts
  packages/phrases/src/locales/ru/translation/admin-console/security.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/security.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/security.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/security.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/security.ts
Labels: chore, size/l

#7267 fix(console): add required tag to captcha form guide
  packages/console/src/pages/Security/Captcha/CaptchaFormFields/index.tsx
Labels: bugfix, size/xs

#7261 chore(phrases): update i18n translations
  packages/phrases/src/locales/ar/errors/session.ts
  packages/phrases/src/locales/ar/translation/admin-console/security.ts
  packages/phrases/src/locales/ar/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/de/errors/session.ts
  packages/phrases/src/locales/de/translation/admin-console/security.ts
  packages/phrases/src/locales/de/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/es/errors/session.ts
  packages/phrases/src/locales/es/translation/admin-console/security.ts
  packages/phrases/src/locales/es/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/fr/errors/session.ts
  packages/phrases/src/locales/fr/translation/admin-console/security.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/it/errors/session.ts
  packages/phrases/src/locales/it/translation/admin-console/security.ts
  packages/phrases/src/locales/it/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/ja/errors/session.ts
  packages/phrases/src/locales/ja/translation/admin-console/security.ts
  packages/phrases/src/locales/ja/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/ko/errors/session.ts
  packages/phrases/src/locales/ko/translation/admin-console/security.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/pl-pl/errors/session.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/security.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/pt-br/errors/session.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/security.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/pt-pt/errors/session.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/security.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/ru/errors/session.ts
  packages/phrases/src/locales/ru/translation/admin-console/security.ts
  packages/phrases/src/locales/ru/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/tr-tr/errors/session.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/security.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/zh-cn/errors/session.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/security.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/zh-hk/errors/session.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/security.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/zh-tw/errors/session.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/security.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
Labels: chore, size/m

#7266 fix(console): fix change captcha guide route path
  packages/console/src/pages/Security/Captcha/CreateCaptchaForm/index.tsx
Labels: bugfix, size/xs

#7262 fix(translate): translate cli tool should read model name from env
  .changeset/six-rivers-lick.md
  packages/translate/src/openai.ts
  packages/translate/src/sync.ts
Labels: bugfix, size/s

#7256 chore(core): clean up legacy test cases
  packages/core/src/middleware/koa-spa-proxy.test.ts
Labels: chore, size/s

#7249 feat(schemas): add sentinel policy
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/queries/sign-in-experience.test.ts
  packages/experience/src/__mocks__/logto.tsx
  packages/schemas/alterations/next-1744013256-add-sentinel-policy-column-to-sie-table.ts
  packages/schemas/src/foundations/jsonb-types/sign-in-experience.ts
  packages/schemas/tables/sign_in_experiences.sql
Labels: feature, size/s

#7255 feat(core): read sentinel policy settings
  packages/core/src/sentinel/basic-sentinel.test.ts
  packages/core/src/sentinel/basic-sentinel.ts
  packages/core/src/tenants/Tenant.ts
Labels: feature, size/m

#7277 style(console): add paddings to identifier information
  packages/console/src/ds-components/CopyToClipboard/index.module.scss
Labels: size/xs

#7269 refactor(core): optimize public captcha config fetching
  packages/core/src/libraries/sign-in-experience/index.ts
Labels: enhancement, size/s

#7275 feat(core,console): add captcha log
  packages/console/src/consts/logs.ts
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/classes/libraries/captcha-validator.ts
  packages/schemas/src/types/log/interaction.ts
Labels: feature, size/s

#7279 fix(core): do not check sign-in method on one-time token verification
  packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.ts
  packages/integration-tests/src/tests/api/experience-api/register-interaction/one-time-token.test.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/one-time-token.test.ts
Labels: bugfix, size/l

#7252 feat(console): add paywall to security
  packages/console/package.json
  packages/console/src/components/FormCard/index.tsx
  packages/console/src/components/Region/assets/jp.svg
  packages/console/src/components/Region/index.tsx
  packages/console/src/consts/quota-item-phrases.ts
  packages/console/src/consts/tenants.ts
  packages/console/src/pages/Security/Captcha/UpsellNotice/index.module.scss
  packages/console/src/pages/Security/Captcha/UpsellNotice/index.tsx
  packages/console/src/pages/Security/Captcha/index.module.scss
  packages/console/src/pages/Security/Captcha/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-item.ts
  packages/phrases/src/locales/en/translation/admin-console/upsell/paywall.ts
  pnpm-lock.yaml
Labels: feature, size/m

#7278 feat(core, schemas): add API to clear sentinel activities
  packages/core/src/queries/sentinel-activities.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/sentinel-activities.openapi.json
  packages/core/src/routes/sentinel-activities.ts
  packages/core/src/routes/swagger/utils/operation-id.ts
  packages/core/src/sentinel/basic-sentinel.ts
  packages/core/src/tenants/Queries.ts
  packages/integration-tests/src/tests/api/experience-api/basic-sentinel.test.ts
  packages/schemas/alterations/next-1744357867-add-sentinel-activities-hash-index.ts
  packages/schemas/tables/sentinel_activities.sql
Labels: feature, size/l

#7288 chore: allow pnpm 10
  package.json
  packages/cli/src/connector/loader.ts
Labels: chore, size/xs

#7285 feat(console): add sentinel unblock modal
  packages/console/src/assets/icons/unlock.svg
  packages/console/src/pages/Security/General/GeneralForm/index.tsx
  packages/console/src/pages/Security/General/SentinelUnlockModal/index.module.scss
  packages/console/src/pages/Security/General/SentinelUnlockModal/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/security.ts
Labels: feature, size/m

#7289 fix: publish scripts
  .scripts/packages-meta.js
Labels: bugfix, size/xs

#7276 fix(connector): support string typed boolean ID token claims for OIDC connector
  .changeset/selfish-zoos-worry.md
  packages/connectors/connector-oidc/src/constant.ts
  packages/connectors/connector-oidc/src/index.ts
  packages/connectors/connector-oidc/src/types.test.ts
  packages/connectors/connector-oidc/src/types.ts
Labels: bugfix, size/m

#7284 fix(experience): prevent multiple captcha widget
  packages/experience/src/Providers/CaptchaContextProvider/index.tsx
Labels: bugfix, size/xs

#7287 fix(console): update readme of turnstile widget mode
  packages/console/src/pages/Security/Captcha/CreateCaptchaForm/constants.ts
Labels: bugfix, size/xs

#7291 refactor(cli): loose CLI version restriction on Node.js
  .changeset/sweet-houses-lie.md
  .github/workflows/alteration-compatibility-integration-test.yml
  .github/workflows/integration-test.yml
  packages/cli/src/commands/install/utils.ts
Labels: enhancement, size/s

#7290 refactor(core): respond 404 for non-existing paths in `/assets`
  .changeset/five-melons-kneel.md
  packages/core/src/middleware/koa-spa-proxy.ts
  packages/integration-tests/src/tests/api/spa-proxy.test.ts
Labels: enhancement, size/s

#7295 feat(core, phrases): security phrases update
  packages/console/src/consts/external-links.ts
  packages/console/src/pages/Security/PasswordPolicy/PasswordPolicyForm/index.tsx
  packages/core/src/routes/experience/classes/libraries/sentinel-guard.ts
  packages/core/src/routes/experience/verification-routes/one-time-token.ts
  packages/core/src/routes/experience/verification-routes/password-verification.ts
  packages/core/src/routes/experience/verification-routes/verification-code.ts
  packages/core/src/routes/verification/index.ts
  packages/phrases/src/locales/ar/translation/admin-console/security.ts
  packages/phrases/src/locales/de/translation/admin-console/security.ts
  packages/phrases/src/locales/en/translation/admin-console/security.ts
  packages/phrases/src/locales/es/translation/admin-console/security.ts
  packages/phrases/src/locales/fr/translation/admin-console/security.ts
  packages/phrases/src/locales/it/translation/admin-console/security.ts
  packages/phrases/src/locales/ja/translation/admin-console/security.ts
  packages/phrases/src/locales/ko/translation/admin-console/security.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/security.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/security.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/security.ts
  packages/phrases/src/locales/ru/translation/admin-console/security.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/security.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/security.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/security.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/security.ts
Labels: feature, size/xl

#7296 refactor(schemas): change default sentinel settings
  packages/core/src/sentinel/basic-sentinel.test.ts
  packages/core/src/sentinel/basic-sentinel.ts
  packages/integration-tests/src/tests/api/experience-api/basic-sentinel.test.ts
  packages/integration-tests/src/tests/experience/basic-sentinel.test.ts
  packages/integration-tests/src/ui-helpers/index.ts
  packages/schemas/src/consts/sentinel.ts
Labels: enhancement, size/m

#7298 feat(console): update security page
  packages/console/src/pages/Security/General/SentinelUnlockModal/index.tsx
  packages/console/src/pages/Security/index.tsx
  packages/phrases/src/locales/ar/translation/admin-console/security.ts
  packages/phrases/src/locales/de/translation/admin-console/security.ts
  packages/phrases/src/locales/en/translation/admin-console/security.ts
  packages/phrases/src/locales/es/translation/admin-console/security.ts
  packages/phrases/src/locales/fr/translation/admin-console/security.ts
  packages/phrases/src/locales/it/translation/admin-console/security.ts
  packages/phrases/src/locales/ja/translation/admin-console/security.ts
  packages/phrases/src/locales/ko/translation/admin-console/security.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/security.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/security.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/security.ts
  packages/phrases/src/locales/ru/translation/admin-console/security.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/security.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/security.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/security.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/security.ts
Labels: feature, size/s

#7304 ci: update stale tag days
  .github/workflows/close-stale.yml
Labels: size/xs

#7294 fix(experience): render captchabox near submit button
  packages/experience/src/components/PasswordSignInForm/index.tsx
  packages/experience/src/pages/ForgotPassword/ForgotPasswordForm/index.tsx
  packages/experience/src/pages/SignInPassword/PasswordForm/index.tsx
Labels: bugfix, size/s

#7303 refactor(console): refactor sign-in experience page data
  packages/console/src/components/SignInExperiencePreview/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignInChangePreview/PasswordDisabledNotification.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignInChangePreview/SignUpAndSignInDiffSection/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignInChangePreview/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/utils/form.ts
  packages/console/src/pages/SignInExperience/PageContent/utils/parser.ts
  packages/console/src/pages/SignInExperience/components/Preview/index.tsx
  packages/console/src/pages/SignInExperience/types.ts
Labels: enhancement, size/m

#7299 feat(core): add dev guard for sentinel policy
  packages/core/src/routes/sign-in-experience/index.ts
Labels: feature, size/s

#7253 chore: prepare to release the one-time token feature
  .changeset/gorgeous-apricots-breathe.md
  packages/core/src/routes/experience/index.ts
  packages/core/src/routes/experience/verification-routes/one-time-token.openapi.json
  packages/core/src/routes/init.ts
  packages/core/src/routes/one-time-tokens.openapi.json
  packages/core/src/routes/swagger/utils/documents.ts
  packages/core/src/routes/swagger/utils/general.ts
  packages/core/src/routes/swagger/utils/operation-id.ts
  packages/experience/src/App.tsx
  packages/integration-tests/src/tests/api/experience-api/register-interaction/one-time-token.test.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/one-time-token.test.ts
  packages/integration-tests/src/tests/api/experience-api/verifications/one-time-token.test.ts
  packages/integration-tests/src/tests/api/one-time-tokens.test.ts
Labels: chore, size/s

#7314 chore(console): provide default console embedded pricing url
  packages/console/src/consts/env.ts
  packages/console/src/pages/TenantSettings/Subscription/ConsoleEmbeddedPricing/index.tsx
Labels: chore, size/xs

#7316 refactor(console): fix region flag logic
  packages/console/src/components/Region/index.tsx
Labels: enhancement, size/s

#7301 fix(experience): handle captcha front-end error
  packages/experience/src/Providers/CaptchaContextProvider/index.tsx
  packages/experience/src/include.d/global.d.ts
  packages/phrases-experience/src/locales/ar/error/index.ts
  packages/phrases-experience/src/locales/de/error/index.ts
  packages/phrases-experience/src/locales/en/error/index.ts
  packages/phrases-experience/src/locales/es/error/index.ts
  packages/phrases-experience/src/locales/fr/error/index.ts
  packages/phrases-experience/src/locales/it/error/index.ts
  packages/phrases-experience/src/locales/ja/error/index.ts
  packages/phrases-experience/src/locales/ko/error/index.ts
  packages/phrases-experience/src/locales/pl-pl/error/index.ts
  packages/phrases-experience/src/locales/pt-br/error/index.ts
  packages/phrases-experience/src/locales/pt-pt/error/index.ts
  packages/phrases-experience/src/locales/ru/error/index.ts
  packages/phrases-experience/src/locales/tr-tr/error/index.ts
  packages/phrases-experience/src/locales/zh-cn/error/index.ts
  packages/phrases-experience/src/locales/zh-hk/error/index.ts
  packages/phrases-experience/src/locales/zh-tw/error/index.ts
Labels: bugfix, size/s

#7286 fix(core): remove auto captcha enable
  packages/core/src/routes/captcha-provider/index.ts
Labels: bugfix, size/xs

#7297 style(console): fix disabled button icon color
  packages/console/src/ds-components/Button/index.module.scss
Labels: size/xs

#7309 style(console): fix captcha form bottom action position
  packages/console/src/pages/Security/Captcha/index.module.scss
Labels: size/xs

#7313 chore(schemas): clean up experience feature flag key
  packages/schemas/src/types/system.ts
Labels: chore, size/s

#7293 fix(console): add placeholder to captcha form
  packages/console/src/pages/Security/Captcha/CaptchaFormFields/index.tsx
  packages/console/src/pages/Security/Captcha/CreateCaptchaForm/constants.ts
  packages/console/src/pages/Security/Captcha/CreateCaptchaForm/types.ts
Labels: bugfix, size/s

#7319 feat(console): integrate inkeep ai assistant into cloud console
  .vscode/settings.json
  packages/console/package.json
  packages/console/src/assets/icons/logto-ai-bot-dark.svg
  packages/console/src/assets/icons/logto-ai-bot.svg
  packages/console/src/components/Topbar/InkeepAskAi/index.module.scss
  packages/console/src/components/Topbar/InkeepAskAi/index.tsx
  packages/console/src/components/Topbar/index.tsx
  packages/console/src/consts/env.ts
  packages/console/src/contexts/AppThemeProvider/index.module.scss
  packages/console/src/hooks/use-inkeep-configs.ts
  packages/console/src/scss/_underscore.scss
  packages/console/vite.config.ts
  pnpm-lock.yaml
Labels: feature, size/l

#7315 feat(core): add security features quota guard
  packages/connectors/connector-logto-email/package.json
  packages/console/package.json
  packages/console/src/consts/quota-item-phrases.ts
  packages/console/src/consts/tenants.ts
  packages/core/package.json
  packages/core/src/__mocks__/cloud-connection.ts
  packages/core/src/libraries/quota.ts
  packages/core/src/queries/tenant-usage/index.ts
  packages/core/src/queries/tenant-usage/types.ts
  packages/core/src/routes/sign-in-experience/index.ts
  packages/core/src/utils/subscription/types.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-item.ts
  pnpm-lock.yaml
Labels: feature, size/s

#7323 chore: remove captcha quota key
  packages/console/src/consts/plan-quotas.ts
Labels: chore, size/xs

#7308 fix(experience): add loading layer while executing captcha
  packages/experience/src/Providers/CaptchaContextProvider/index.tsx
Labels: bugfix, size/s

#7322 refactor(experience): handle captcha in hooks
  packages/experience/src/components/IdentifierRegisterForm/index.tsx
  packages/experience/src/components/IdentifierRegisterForm/use-on-submit.ts
  packages/experience/src/components/IdentifierRegisterForm/use-register-with-username.ts
  packages/experience/src/components/PasswordSignInForm/index.tsx
  packages/experience/src/hooks/use-password-sign-in.ts
  packages/experience/src/hooks/use-send-verification-code.ts
  packages/experience/src/pages/ForgotPassword/ForgotPasswordForm/index.tsx
  packages/experience/src/pages/SignInPassword/PasswordForm/index.tsx
Labels: enhancement, size/s

#7318 feat(console): add usage card
  packages/console/src/components/PlanUsage/index.tsx
  packages/console/src/components/PlanUsage/utils.ts
  packages/phrases/src/locales/ar/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/de/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/es/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/fr/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/it/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/ja/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/ko/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/ru/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/usage.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/usage.ts
Labels: feature, size/s

#7327 fix(console): fix crash issue caused by mis-used inkeep code editor theme
  packages/console/package.json
  packages/console/src/hooks/use-inkeep-configs.ts
  pnpm-lock.yaml
Labels: bugfix, size/s

#7328 chore(console): optimize console build chunks
  packages/console/src/components/Topbar/InkeepAskAi/index.tsx
  packages/console/src/components/Topbar/index.tsx
  packages/console/vite.config.ts
Labels: chore, size/s

#7268 feat(core): add paywall of captcha
  packages/core/src/routes/captcha-provider/index.ts
Labels: feature, size/xs

#7325 fix(console): fix security page default tab
  packages/console/src/hooks/use-console-routes/routes/security.tsx
Labels: bugfix, size/xs

#7330 refactor(console): improve inkeep ai bot for better i18n support
  packages/console/src/components/Topbar/InkeepAskAi/index.tsx
  packages/console/src/hooks/use-inkeep-configs.ts
  packages/phrases/src/locales/ar/translation/admin-console/index.ts
  packages/phrases/src/locales/ar/translation/admin-console/inkeep-ai-bot.ts
  packages/phrases/src/locales/de/translation/admin-console/index.ts
  packages/phrases/src/locales/de/translation/admin-console/inkeep-ai-bot.ts
  packages/phrases/src/locales/en/translation/admin-console/index.ts
  packages/phrases/src/locales/en/translation/admin-console/inkeep-ai-bot.ts
  packages/phrases/src/locales/en/translation/admin-console/jwt-claims.ts
  packages/phrases/src/locales/es/translation/admin-console/index.ts
  packages/phrases/src/locales/es/translation/admin-console/inkeep-ai-bot.ts
  packages/phrases/src/locales/fr/translation/admin-console/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/inkeep-ai-bot.ts
  packages/phrases/src/locales/it/translation/admin-console/index.ts
  packages/phrases/src/locales/it/translation/admin-console/inkeep-ai-bot.ts
  packages/phrases/src/locales/ja/translation/admin-console/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/inkeep-ai-bot.ts
  packages/phrases/src/locales/ko/translation/admin-console/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/inkeep-ai-bot.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/inkeep-ai-bot.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/inkeep-ai-bot.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/inkeep-ai-bot.ts
  packages/phrases/src/locales/ru/translation/admin-console/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/inkeep-ai-bot.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/inkeep-ai-bot.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/inkeep-ai-bot.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/inkeep-ai-bot.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/inkeep-ai-bot.ts
Labels: enhancement, size/l

#7329 fix(console): update security docs link
  packages/console/src/consts/external-links.ts
Labels: bugfix, size/xs

#7333 fix(console): update captcha card description
  packages/console/src/pages/CaptchaDetails/CaptchaContent/index.tsx
  packages/console/src/pages/Security/Captcha/Guide/index.tsx
Labels: bugfix, size/xs

#7335 feat(core): clean up feature flag util method
  packages/core/src/utils/feature-flag.test.ts
  packages/core/src/utils/feature-flag.ts
Labels: feature, size/s

#7334 refactor(console,phrases): security page phrases update
  packages/phrases/src/locales/ar/translation/admin-console/security.ts
  packages/phrases/src/locales/de/translation/admin-console/security.ts
  packages/phrases/src/locales/en/translation/admin-console/security.ts
  packages/phrases/src/locales/es/translation/admin-console/security.ts
  packages/phrases/src/locales/fr/translation/admin-console/security.ts
  packages/phrases/src/locales/it/translation/admin-console/security.ts
  packages/phrases/src/locales/ja/translation/admin-console/security.ts
  packages/phrases/src/locales/ko/translation/admin-console/security.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/security.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/security.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/security.ts
  packages/phrases/src/locales/ru/translation/admin-console/security.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/security.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/security.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/security.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/security.ts
Labels: enhancement, size/s

#7270 chore: add changeset of captcha
  .changeset/plenty-roses-rhyme.md
Labels: chore, size/s

#7332 chore: add changesets
  .changeset/khaki-stingrays-mate.md
  .changeset/loud-emus-study.md
  .changeset/witty-tables-search.md
  .changeset/yellow-poems-decide.md
Labels: chore, size/s

#7336 refactor(core,experience): remove captcha dev feature guard
  packages/core/src/libraries/sign-in-experience/index.ts
  packages/core/src/routes/captcha-provider/index.openapi.json
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/index.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/swagger/utils/documents.ts
  packages/core/src/routes/well-known/index.ts
  packages/core/src/routes/well-known/well-known.experience.ts
  packages/experience/src/Providers/CaptchaContextProvider/index.tsx
  packages/integration-tests/src/tests/api/captcha-provider.test.ts
  packages/integration-tests/src/tests/api/experience-api/captcha/index.test.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/one-time-token.test.ts
Labels: enhancement, size/s

#7338 chore: enable Cloudflare Worker deploy/delete when doing Cloud integration tests
  packages/core/src/routes/logto-config/jwt-customizer.ts
Labels: chore, size/s

#7342 Revert "fix(experience): add loading layer while executing captcha"
  packages/experience/src/Providers/CaptchaContextProvider/index.tsx
Labels: size/s

#7344 fix(experience): loading button should be disabled
  packages/experience/src/components/Button/SocialLinkButton.tsx
  packages/experience/src/components/Button/index.module.scss
  packages/experience/src/components/Button/index.tsx
Labels: bugfix, size/s

#7340 chore: pnpm audit fix
  package.json
  pnpm-lock.yaml
Labels: chore, size/s

#7346 chore(console): remove beta tag from bring your ui
  packages/console/src/pages/SignInExperience/PageContent/Branding/CustomUiForm/index.tsx
Labels: chore, size/xs

#7348 fix(experience): replace global loading layer
  packages/experience/src/components/LoadingLayer/index.tsx
  packages/experience/src/pages/DirectSignIn/index.module.scss
  packages/experience/src/pages/DirectSignIn/index.tsx
Labels: bugfix, size/s

#7337 chore(console): remove dev feature guard from inkeep ai bot
  packages/console/src/components/Topbar/index.tsx
Labels: chore, size/xs

#7205 feat(phrases): add uk-UA locale
  packages/phrases-experience/src/index.ts
  packages/phrases-experience/src/locales/uk-ua/action.ts
  packages/phrases-experience/src/locales/uk-ua/description.ts
  packages/phrases-experience/src/locales/uk-ua/development-tenant.ts
  packages/phrases-experience/src/locales/uk-ua/error/index.ts
  packages/phrases-experience/src/locales/uk-ua/error/password-rejected.ts
  packages/phrases-experience/src/locales/uk-ua/index.ts
  packages/phrases-experience/src/locales/uk-ua/input.ts
  packages/phrases-experience/src/locales/uk-ua/list.ts
  packages/phrases-experience/src/locales/uk-ua/mfa.ts
  packages/phrases-experience/src/locales/uk-ua/secondary.ts
  packages/phrases-experience/src/locales/uk-ua/user-scopes.ts
Labels: feature, size/l

#7126 fix(cli): convert Windows absolute paths to file URLs for dynamic imports
  packages/cli/src/commands/database/alteration/index.ts
Labels: bugfix, size/xs

#7350 fix: uk-ua mistake translate captcha_verification_failed
  packages/phrases-experience/src/locales/uk-ua/error/index.ts
Labels: bugfix, size/xs

#7358 fix: typos
  packages/cli/src/commands/database/seed/tables.ts
  packages/console/src/assets/docs/guides/web-dotnet-core-mvc/fragments/_sign-in-and-sign-out-flows.mdx
Labels: bugfix, size/xs

#7359 fix(experience): captcha not show on indetifier singin form
  .changeset/swift-glasses-drive.md
  packages/experience/src/components/IdentifierRegisterForm/use-register-with-username.ts
  packages/experience/src/components/IdentifierSignInForm/index.tsx
  packages/experience/src/hooks/use-password-sign-in.ts
  packages/experience/src/hooks/use-send-verification-code.ts
Labels: bugfix, size/s
