Repository logto-io/logto, pull requests merged in 2025-01, with the labels that each got.

#6887 feat(core): add SAML auth request handling endpoints
  packages/core/src/constants/index.ts
  packages/core/src/routes/swagger/utils/operation.ts
  packages/core/src/saml-applications/libraries/saml-applications.ts
  packages/core/src/saml-applications/queries/index.ts
  packages/core/src/saml-applications/routes/anonymous.ts
  packages/core/src/saml-applications/routes/utils.test.ts
  packages/core/src/saml-applications/routes/utils.ts
  packages/core/src/tenants/Queries.ts
  packages/phrases/src/locales/en/errors/application.ts
  packages/phrases/src/locales/en/errors/oidc.ts
Labels: feature, size/xl

#6910 feat(core,console): enable create and activate/deactivate SAML app secrets
  packages/console/src/components/DateTime/index.tsx
  packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/CertificateActionMenu/index.module.scss
  packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/CertificateActionMenu/index.tsx
  packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/CreateSecretModal.tsx
  packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/Settings.tsx
  packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/index.module.scss
  packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/use-secret-table-columns.tsx
  packages/core/src/saml-applications/libraries/saml-applications.ts
  packages/core/src/saml-applications/libraries/utils.test.ts
  packages/core/src/saml-applications/libraries/utils.ts
  packages/core/src/saml-applications/routes/index.ts
  packages/integration-tests/src/api/saml-application.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/phrases/src/locales/en/translation/admin-console/general.ts
Labels: feature, size/l

#6912 feat: support SAML app encryption and nameIdFormat config
  packages/core/src/saml-applications/libraries/utils.ts
  packages/integration-tests/src/tests/api/application/saml-application.test.ts
  packages/schemas/alterations/next-1735274337-add-encryption-config-to-saml-apps.ts
  packages/schemas/src/foundations/jsonb-types/saml-application-configs.test.ts
  packages/schemas/src/foundations/jsonb-types/saml-application-configs.ts
  packages/schemas/src/types/saml-application.ts
  packages/schemas/tables/saml_application_configs.sql
Labels: feature, size/m

#6913 refactor: make SAML apps to be first party apps
  packages/console/src/components/ApplicationIcon/index.tsx
  packages/core/src/saml-applications/routes/index.ts
  packages/schemas/alterations/next-1735292380-make-saml-app-first-party-app.ts
  packages/schemas/tables/applications.sql
Labels: enhancement, size/s

#6909 refactor(core): build SamlApplication class
  packages/core/src/saml-applications/SamlApplication/index.test.ts
  packages/core/src/saml-applications/SamlApplication/index.ts
  packages/core/src/saml-applications/SamlApplication/utils.test.ts
  packages/core/src/saml-applications/SamlApplication/utils.ts
  packages/core/src/saml-applications/routes/anonymous.ts
  packages/core/src/saml-applications/routes/utils.test.ts
  packages/core/src/saml-applications/routes/utils.ts
Labels: enhancement, size/xl

#6916 feat(console,core): add attribute mapping
  packages/console/src/consts/page-tabs.ts
  packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/AttributeMapping.module.scss
  packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/AttributeMapping.tsx
  packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/index.tsx
  packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/utils.ts
  packages/core/src/saml-applications/libraries/saml-applications.ts
  packages/integration-tests/src/tests/api/application/saml-application.test.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
  packages/schemas/src/foundations/jsonb-types/saml-application-configs.ts
  packages/toolkit/core-kit/src/openid.ts
Labels: feature, size/xl

#6926 chore(console): fix SAML app text display
  packages/console/src/components/ItemPreview/ApplicationPreview.tsx
  packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/CreateSecretModal.tsx
  packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/index.tsx
  packages/console/src/types/applications.ts
  packages/phrases/src/locales/en/translation/admin-console/applications.ts
Labels: chore, size/s

#6924 feat(core): support custom endpoint and addressing style for S3
  .changeset/afraid-otters-crash.md
  packages/core/src/utils/storage/index.ts
  packages/core/src/utils/storage/s3-storage.ts
  packages/schemas/src/types/system.ts
Labels: feature, size/s

#6929 feat(console,core): enable configure on nameIdFormat and encryption
  packages/console/src/ds-components/Textarea/index.module.scss
  packages/console/src/ds-components/Textarea/index.tsx
  packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/Settings.tsx
  packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/index.module.scss
  packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/utils.ts
  packages/core/src/saml-applications/SamlApplication/index.test.ts
  packages/core/src/saml-applications/SamlApplication/index.ts
  packages/core/src/saml-applications/SamlApplication/utils.test.ts
  packages/core/src/saml-applications/SamlApplication/utils.ts
  packages/core/src/saml-applications/queries/index.ts
  packages/phrases/src/locales/en/errors/application.ts
  packages/phrases/src/locales/en/translation/admin-console/application-details.ts
Labels: feature, size/l

#6930 refactor(core): build SAML app sign in URL scope with attribute mapping
  packages/core/src/saml-applications/SamlApplication/index.test.ts
  packages/core/src/saml-applications/SamlApplication/index.ts
Labels: enhancement, size/m

#6932 feat(core): add default redirect URI for SAML apps on creation
  packages/core/src/saml-applications/SamlApplication/index.test.ts
  packages/core/src/saml-applications/SamlApplication/index.ts
  packages/core/src/saml-applications/SamlApplication/utils.ts
  packages/core/src/saml-applications/routes/index.ts
  packages/integration-tests/src/tests/api/application/saml-application.test.ts
Labels: feature, size/m

#6931 feat(core): add SAML app audit logs
  packages/console/src/consts/logs.ts
  packages/core/src/saml-applications/routes/anonymous.ts
  packages/schemas/src/types/log/index.ts
  packages/schemas/src/types/log/saml.ts
Labels: feature, size/s

#6937 feat(core): add state/redirect URI validate on SP init SAML SSO callback endpoint
  packages/core/src/saml-applications/SamlApplication/index.test.ts
  packages/core/src/saml-applications/SamlApplication/index.ts
  packages/core/src/saml-applications/queries/sessions.ts
  packages/core/src/saml-applications/routes/anonymous.ts
  packages/phrases/src/locales/en/errors/application.ts
Labels: feature, size/m

#6938 refactor(core): refactor GET saml app metadata endpoint
  packages/core/src/saml-applications/SamlApplication/index.ts
  packages/core/src/saml-applications/libraries/saml-applications.ts
  packages/core/src/saml-applications/routes/anonymous.ts
Labels: enhancement, size/m

#6941 refactor(core): add SAML app quota guard
  packages/console/package.json
  packages/console/src/consts/quota-item-phrases.ts
  packages/console/src/consts/tenants.ts
  packages/core/package.json
  packages/core/src/__mocks__/cloud-connection.ts
  packages/core/src/saml-applications/routes/index.ts
  packages/core/src/utils/subscription/types.ts
  packages/phrases/src/locales/en/translation/admin-console/subscription/quota-item.ts
  pnpm-lock.yaml
Labels: enhancement, size/s

#6944 feat(console): add SAML app flow
  .github/workflows/integration-test.yml
  packages/console/src/assets/docs/guides/saml-idp/index.ts
  packages/console/src/components/Guide/hooks.ts
  packages/console/src/types/applications.ts
  packages/phrases/src/locales/en/translation/admin-console/guide.ts
Labels: feature, size/s

#6948 feat(console): hide entrance for creating SAML apps
  packages/console/src/components/Guide/hooks.ts
  packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
Labels: feature, size/s

#6953 fix(core): fix SAML attributes data
  packages/core/src/saml-applications/SamlApplication/index.test.ts
  packages/core/src/saml-applications/SamlApplication/index.ts
  packages/core/src/saml-applications/SamlApplication/utils.ts
Labels: bugfix, size/l

#6959 refactor(experience): remove the image CORS attributes
  .changeset/soft-kings-grin.md
  packages/experience-legacy/src/components/BrandingHeader/index.tsx
  packages/experience-legacy/src/components/Button/SocialLinkButton.tsx
  packages/experience-legacy/src/containers/SocialLanding/index.tsx
  packages/experience/src/components/BrandingHeader/index.tsx
  packages/experience/src/components/Button/SocialLinkButton.tsx
  packages/experience/src/containers/SocialLanding/index.tsx
Labels: enhancement, size/s

#6961 fix(core): fix SAML validator setup
  packages/core/src/saml-applications/SamlApplication/index.ts
Labels: bugfix, size/s

#6962 fix(core,console): make SAML related log visible in audit log listing page
  packages/core/src/queries/log.ts
  packages/core/src/routes/log.test.ts
  packages/core/src/routes/log.ts
  packages/core/src/saml-applications/routes/anonymous.ts
Labels: bugfix, size/s

#6966 refactor(core): reorg SAML app related codes
  packages/core/src/libraries/saml-application/saml-applications.ts
  packages/core/src/libraries/saml-application/utils.test.ts
  packages/core/src/libraries/saml-application/utils.ts
  packages/core/src/queries/saml-application/configs.ts
  packages/core/src/queries/saml-application/index.ts
  packages/core/src/queries/saml-application/secrets.ts
  packages/core/src/queries/saml-application/sessions.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/saml-application/anonymous.ts
  packages/core/src/routes/saml-application/index.ts
  packages/core/src/saml-application/SamlApplication/consts.ts
  packages/core/src/saml-application/SamlApplication/index.test.ts
  packages/core/src/saml-application/SamlApplication/index.ts
  packages/core/src/saml-application/SamlApplication/utils.test.ts
  packages/core/src/saml-application/SamlApplication/utils.ts
  packages/core/src/tenants/Libraries.ts
  packages/core/src/tenants/Queries.ts
Labels: enhancement, size/s

#6968 chore: update error message
  packages/core/src/queries/saml-application/index.ts
  packages/core/src/routes/saml-application/anonymous.ts
Labels: chore, size/s

#6969 fix: fix SAML app console issues
  packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/utils.ts
  packages/schemas/src/foundations/jsonb-types/saml-application-configs.ts
Labels: bugfix, size/s

#6970 fix: fix SAML app console issues
  packages/console/src/assets/icons/download.svg
  packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/CertificateActionMenu/index.tsx
  packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/Settings.tsx
  packages/phrases/src/locales/ar/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/de/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/en/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/es/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/fr/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/it/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/ja/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/ko/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/ru/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/enterprise-sso.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/enterprise-sso.ts
Labels: bugfix, size/m

#6972 chore: add changeset to patch @logto/shared
  .changeset/wicked-kids-rescue.md
Labels: chore, size/xs

#6975 chore: bump vite versions
  package.json
  packages/console/package.json
  packages/demo-app/package.json
  packages/experience-legacy/package.json
  packages/experience/package.json
  pnpm-lock.yaml
Labels: chore, size/s

#6977 fix(console,core): fix SAML app attribute mapping issues
  packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/AttributeMapping.tsx
  packages/core/src/libraries/saml-application/saml-applications.ts
  packages/integration-tests/src/tests/api/application/saml-application.test.ts
Labels: bugfix, size/s

#6978 fix: fix SAML app attribute mapping not working issue
  packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/AttributeMapping.tsx
  packages/core/src/saml-application/SamlApplication/index.test.ts
  packages/core/src/saml-application/SamlApplication/index.ts
  packages/integration-tests/src/tests/api/application/saml-application.test.ts
  packages/schemas/src/foundations/jsonb-types/saml-application-configs.ts
Labels: bugfix, size/m

#6604 chore: add changeset for http email
  .changeset/blue-flowers-rule.md
  packages/console/src/components/CreateConnectorForm/index.tsx
Labels: chore, size/xs, stale

#6979 chore(core): hide oidcClientMetadata of SAML apps when using GET app APIs
  packages/core/src/routes/applications/application.ts
  packages/core/src/routes/saml-application/index.ts
  packages/integration-tests/src/tests/api/application/saml-application.test.ts
Labels: chore, size/s

#6985 chore: update SAML app attribute mapping doc link
  packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/AttributeMapping.tsx
Labels: chore, size/xs

#6983 feat: remove SAML app dev feature guard
  packages/console/src/components/Guide/hooks.ts
  packages/core/src/routes/applications/application.ts
  packages/core/src/routes/init.ts
Labels: feature, size/s

#6986 refactor: add enterprise tag for SAML apps
  packages/console/src/components/ApplicationCreation/CreateForm/Footer/index.tsx
  packages/console/src/components/FeatureTag/index.tsx
  packages/console/src/components/Guide/GuideCard/index.tsx
  packages/console/src/components/Guide/GuideCardGroup/index.tsx
  packages/console/src/components/Guide/hooks.ts
  packages/console/src/hooks/use-applications-usage.ts
  packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
Labels: enhancement, size/m

#6987 chore: remove SAML app guide card feature guard
  packages/console/src/assets/docs/guides/saml-idp/index.ts
  packages/console/src/components/Guide/GuideCard/index.tsx
Labels: chore, size/xs

#6982 chore: add core-kit changeset
  .changeset/loud-trees-check.md
  packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/AttributeMapping.tsx
  packages/schemas/src/foundations/jsonb-types/saml-application-configs.ts
  packages/toolkit/core-kit/src/openid.ts
Labels: chore, size/s
