Repository logto-io/logto, pull requests merged in 2025-08, with the labels that each got.

#7630 fix(console,experience,schemas): refactor profile field details and improve label handling
  packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/ProfileFieldDetails/ProfileFieldDetailsForm/index.module.scss
  packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/ProfileFieldDetails/ProfileFieldDetailsForm/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/ProfileFieldDetails/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/hooks.ts
  packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/utils.ts
  packages/console/src/pages/SignInExperience/PageContent/components/ProfileFieldPartSubForm/index.tsx
  packages/experience/src/pages/Continue/ExtraProfileForm/AddressSubForm/index.tsx
  packages/experience/src/pages/Continue/ExtraProfileForm/FullnameSubForm/index.tsx
  packages/experience/src/types/guard.ts
  packages/schemas/src/foundations/jsonb-types/custom-profile-fields.ts
  packages/schemas/src/types/custom-profile-fields.ts
Labels: bugfix, size/l

#7642 fix(phrases): fix date format strings across all i18n locales
  packages/phrases/src/locales/de/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/es/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/it/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/ru/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp/custom-profile-fields.ts
Labels: bugfix, size/s

#7585 feat: adding pbkdf2 support
  packages/core/src/utils/password.ts
Labels: feature, size/s

#7640 refactor(console,phrases,schemas): make option label optional and add default i18n gender options
  packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/CreateProfileFieldModal/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/ProfileFieldDetails/ProfileFieldDetailsForm/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/ProfileFieldList/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/data-parser.ts
  packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/hooks.ts
  packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/types.ts
  packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/use-i18n-field-label.ts
  packages/console/src/pages/SignInExperience/PageContent/components/CompositionPartsSelector/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/components/DateFormatSelector/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/components/ProfileFieldPartSubForm/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/components/RangedNumberInputs/index.tsx
  packages/experience/src/components/InputFields/PrimitiveProfileInputField/index.tsx
  packages/experience/src/pages/Continue/ExtraProfileForm/use-validate-field.ts
  packages/experience/src/types/guard.ts
  packages/phrases-experience/src/locales/ar/profile.ts
  packages/phrases-experience/src/locales/de/profile.ts
  packages/phrases-experience/src/locales/en/profile.ts
  packages/phrases-experience/src/locales/es/profile.ts
  packages/phrases-experience/src/locales/fr/profile.ts
  packages/phrases-experience/src/locales/it/profile.ts
  packages/phrases-experience/src/locales/ja/profile.ts
  packages/phrases-experience/src/locales/ko/profile.ts
  packages/phrases-experience/src/locales/pl-pl/profile.ts
  packages/phrases-experience/src/locales/pt-br/profile.ts
  packages/phrases-experience/src/locales/pt-pt/profile.ts
  packages/phrases-experience/src/locales/ru/profile.ts
  packages/phrases-experience/src/locales/tr-tr/profile.ts
  packages/phrases-experience/src/locales/uk-ua/profile.ts
  packages/phrases-experience/src/locales/zh-cn/profile.ts
  packages/phrases-experience/src/locales/zh-hk/profile.ts
  packages/phrases-experience/src/locales/zh-tw/profile.ts
  packages/schemas/src/foundations/jsonb-types/custom-profile-fields.ts
  packages/schemas/src/types/custom-profile-fields.ts
Labels: enhancement, size/xl

#7644 chore: add changeset of pbkdf2
  .changeset/add-pbkdf2-support.md
Labels: chore, size/s

#7645 fix(test): resolve intermittent timeout in organization-user test
  packages/integration-tests/src/tests/api/organization/organization-user.test.ts
Labels: bugfix, size/s

#7648 refactor(phrases): update i18n phrases of collect user profile
  packages/console/src/pages/SignInExperience/PageContent/components/CompositionPartsSelector/index.tsx
  packages/phrases/src/locales/ar/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/de/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/en/translation/admin-console/profile.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/es/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/it/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/ja/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/ru/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/sign-in-exp/custom-profile-fields.ts
Labels: enhancement, size/m

#7629 chore: remove unused google one tap APIs
  packages/core/src/routes/google-one-tap/index.openapi.json
  packages/core/src/routes/google-one-tap/index.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/swagger/utils/documents.ts
  packages/core/src/routes/swagger/utils/general.ts
  packages/core/src/routes/swagger/utils/operation-id.ts
  packages/integration-tests/src/tests/api/google-one-tap.test.ts
Labels: chore, size/l

#7631 chore: remove unused auth status page and phrases
  packages/console/src/cloud/AppRoutes.tsx
  packages/console/src/contexts/TenantsProvider.tsx
  packages/console/src/pages/AuthStatus/consts.ts
  packages/console/src/pages/AuthStatus/hooks.ts
  packages/console/src/pages/AuthStatus/index.module.scss
  packages/console/src/pages/AuthStatus/index.tsx
  packages/console/src/pages/AuthStatus/types.ts
  packages/console/src/pages/AuthStatus/utils.test.ts
  packages/console/src/pages/AuthStatus/utils.ts
  packages/core/src/middleware/koa-security-headers.ts
  packages/phrases/src/locales/ar/translation/admin-console/auth-status.ts
  packages/phrases/src/locales/ar/translation/admin-console/index.ts
  packages/phrases/src/locales/de/translation/admin-console/auth-status.ts
  packages/phrases/src/locales/de/translation/admin-console/index.ts
  packages/phrases/src/locales/en/translation/admin-console/auth-status.ts
  packages/phrases/src/locales/en/translation/admin-console/index.ts
  packages/phrases/src/locales/es/translation/admin-console/auth-status.ts
  packages/phrases/src/locales/es/translation/admin-console/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/auth-status.ts
  packages/phrases/src/locales/fr/translation/admin-console/index.ts
  packages/phrases/src/locales/it/translation/admin-console/auth-status.ts
  packages/phrases/src/locales/it/translation/admin-console/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/auth-status.ts
  packages/phrases/src/locales/ja/translation/admin-console/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/auth-status.ts
  packages/phrases/src/locales/ko/translation/admin-console/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/auth-status.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/auth-status.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/auth-status.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/auth-status.ts
  packages/phrases/src/locales/ru/translation/admin-console/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/auth-status.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/auth-status.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/auth-status.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/auth-status.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/index.ts
Labels: chore, size/xl

#7632 chore(console): remove dev feature guard for console GOT landing page
  packages/console/src/cloud/AppRoutes.tsx
Labels: chore, size/s

#7611 feat: add forgot password methods
  packages/console/src/components/SignInExperiencePreview/index.tsx
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/libraries/sign-in-experience/index.test.ts
  packages/core/src/libraries/sign-in-experience/index.ts
  packages/core/src/queries/sign-in-experience.test.ts
  packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.ts
  packages/core/src/routes/sign-in-experience/index.test.ts
  packages/core/src/routes/sign-in-experience/index.ts
  packages/core/src/routes/well-known/well-known.test.ts
  packages/experience/src/__mocks__/logto.tsx
  packages/integration-tests/src/tests/api/experience-api/profile/reset-password.test.ts
  packages/integration-tests/src/tests/api/hook/hook.trigger.experience.test.ts
  packages/integration-tests/src/tests/api/sign-in-experience.forgot-password.test.ts
  packages/integration-tests/src/tests/api/sign-in-experience.test.ts
  packages/integration-tests/src/tests/experience/first-screen.test.ts
  packages/integration-tests/src/tests/experience/mfa/totp/add-missing-profile-flow.test.ts
  packages/integration-tests/src/tests/experience/mfa/totp/password-identifier-flow.test.ts
  packages/integration-tests/src/tests/experience/mfa/user-controlled.test.ts
  packages/integration-tests/src/tests/experience/mfa/webauthn/index.test.ts
  packages/phrases/src/locales/en/errors/sign-in-experiences.ts
  packages/schemas/alterations/next-1753689065-add-forgot-password-methods-to-sie-table.ts
  packages/schemas/src/foundations/jsonb-types/sign-in-experience.ts
  packages/schemas/src/types/sign-in-experience.ts
  packages/schemas/tables/sign_in_experiences.sql
Labels: feature, size/l

#7617 feat(console): setup forgot password methods
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignInForm/ForgotPasswordMethodEditBox/VerificationMethodItem.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignInForm/ForgotPasswordMethodEditBox/index.module.scss
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignInForm/ForgotPasswordMethodEditBox/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignInForm/ForgotPasswordMethodEditBox/utils.ts
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignInForm/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignInChangePreview/SignUpAndSignInDiffSection/ForgotPasswordMethodsDiffSection.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignInChangePreview/SignUpAndSignInDiffSection/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/utils/form.ts
  packages/console/src/pages/SignInExperience/PageContent/utils/parser.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
Labels: feature, size/l

#7650 refactor(core): refactor findPayloadByPayloadField query
  packages/core/src/queries/oidc-model-instance.test.ts
  packages/core/src/queries/oidc-model-instance.ts
Labels: enhancement, size/s

#7510 feat(connector): add http sms connector
  .changeset/olive-maps-wave.md
  packages/connectors/connector-http-sms/README.md
  packages/connectors/connector-http-sms/logo-dark.svg
  packages/connectors/connector-http-sms/logo.svg
  packages/connectors/connector-http-sms/package.json
  packages/connectors/connector-http-sms/src/constant.ts
  packages/connectors/connector-http-sms/src/index.test.ts
  packages/connectors/connector-http-sms/src/index.ts
  packages/connectors/connector-http-sms/src/mock.ts
  packages/connectors/connector-http-sms/src/types.ts
  pnpm-lock.yaml
Labels: feature, size/l

#7653 feat(core): bind Email MFA
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/classes/helpers.ts
  packages/core/src/routes/experience/classes/libraries/mfa-validator.ts
  packages/core/src/routes/experience/classes/mfa.ts
  packages/core/src/routes/experience/classes/verifications/code-verification.ts
  packages/core/src/routes/experience/profile-routes.ts
  packages/core/src/routes/experience/types.ts
  packages/experience/src/apis/experience/mfa.ts
  packages/integration-tests/src/helpers/sign-in-experience.ts
  packages/integration-tests/src/tests/api/experience-api/bind-mfa/email-mfa-binding.test.ts
Labels: feature, size/l

#7659 fix(experience): field i18n label should be displayed properly in error message on profile fulfulling page
  packages/experience/src/pages/Continue/ExtraProfileForm/use-field-label.ts
  packages/experience/src/types/guard.ts
  packages/phrases-experience/src/locales/ar/profile.ts
  packages/phrases-experience/src/locales/de/profile.ts
  packages/phrases-experience/src/locales/en/profile.ts
  packages/phrases-experience/src/locales/es/profile.ts
  packages/phrases-experience/src/locales/fr/profile.ts
  packages/phrases-experience/src/locales/it/profile.ts
  packages/phrases-experience/src/locales/ja/profile.ts
  packages/phrases-experience/src/locales/ko/profile.ts
  packages/phrases-experience/src/locales/pl-pl/profile.ts
  packages/phrases-experience/src/locales/pt-br/profile.ts
  packages/phrases-experience/src/locales/pt-pt/profile.ts
  packages/phrases-experience/src/locales/ru/profile.ts
  packages/phrases-experience/src/locales/tr-tr/profile.ts
  packages/phrases-experience/src/locales/uk-ua/profile.ts
  packages/phrases-experience/src/locales/zh-cn/profile.ts
  packages/phrases-experience/src/locales/zh-hk/profile.ts
  packages/phrases-experience/src/locales/zh-tw/profile.ts
Labels: bugfix, size/s

#7661 refactor: add minLength and maxLength default values to profile fulfilling text fields
  packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/data-parser.ts
Labels: enhancement, size/xs

#7664 refactor(experience): select field should cut off overflow text and have extra dropdown padding
  packages/experience/src/components/Dropdown/index.module.scss
  packages/experience/src/components/InputFields/PrimitiveProfileInputField/index.tsx
  packages/experience/src/components/InputFields/SelectField/index.module.scss
Labels: enhancement, size/xs

#7666 refactor(console): update profile fulfill dropdown icon and improve options parser
  packages/console/src/assets/icons/field-type-dropdown.svg
  packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/data-parser.ts
Labels: enhancement, size/s

#7667 refactor(experience,phrases): add optional label support to input fields
  packages/experience/src/components/InputFields/InputField/index.tsx
  packages/experience/src/components/InputFields/PrimitiveProfileInputField/index.tsx
  packages/experience/src/components/InputFields/SelectField/index.tsx
  packages/experience/src/pages/Continue/ExtraProfileForm/AddressSubForm/index.tsx
  packages/experience/src/pages/Continue/ExtraProfileForm/FullnameSubForm/index.tsx
  packages/experience/src/pages/Continue/ExtraProfileForm/index.tsx
  packages/phrases-experience/src/locales/ar/input.ts
  packages/phrases-experience/src/locales/de/input.ts
  packages/phrases-experience/src/locales/en/input.ts
  packages/phrases-experience/src/locales/es/input.ts
  packages/phrases-experience/src/locales/fr/input.ts
  packages/phrases-experience/src/locales/it/input.ts
  packages/phrases-experience/src/locales/ja/input.ts
  packages/phrases-experience/src/locales/ko/input.ts
  packages/phrases-experience/src/locales/pl-pl/input.ts
  packages/phrases-experience/src/locales/pt-br/input.ts
  packages/phrases-experience/src/locales/pt-pt/input.ts
  packages/phrases-experience/src/locales/ru/input.ts
  packages/phrases-experience/src/locales/tr-tr/input.ts
  packages/phrases-experience/src/locales/uk-ua/input.ts
  packages/phrases-experience/src/locales/zh-cn/input.ts
  packages/phrases-experience/src/locales/zh-hk/input.ts
  packages/phrases-experience/src/locales/zh-tw/input.ts
Labels: enhancement, size/s

#7669 refactor(core): remove unused email sms mfa code
  packages/core/src/libraries/user.utils.ts
  packages/core/src/routes/experience/classes/helpers.ts
  packages/core/src/routes/experience/classes/libraries/mfa-validator.ts
  packages/core/src/routes/experience/classes/mfa.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/core/src/routes/interaction/verifications/mfa-payload-verification.ts
  packages/experience/src/apis/experience/mfa.ts
  packages/experience/src/containers/VerificationCode/use-continue-flow-code-verification.ts
  packages/experience/src/hooks/use-send-mfa-payload.ts
  packages/schemas/src/foundations/jsonb-types/users.ts
  packages/schemas/src/types/interactions.ts
Labels: enhancement, size/l

#7676 fix(experience): date field should not report type error when fulfilling profile
  packages/experience/src/types/guard.ts
Labels: bugfix, size/xs

#7674 fix(core): validate sub-component types in address and fullname fields
  packages/core/src/libraries/custom-profile-fields/utils.ts
  packages/integration-tests/src/tests/api/custom-profile-fields.test.ts
  packages/phrases/src/locales/ar/errors/custom-profile-fields.ts
  packages/phrases/src/locales/de/errors/custom-profile-fields.ts
  packages/phrases/src/locales/en/errors/custom-profile-fields.ts
  packages/phrases/src/locales/es/errors/custom-profile-fields.ts
  packages/phrases/src/locales/fr/errors/custom-profile-fields.ts
  packages/phrases/src/locales/it/errors/custom-profile-fields.ts
  packages/phrases/src/locales/ja/errors/custom-profile-fields.ts
  packages/phrases/src/locales/ko/errors/custom-profile-fields.ts
  packages/phrases/src/locales/pl-pl/errors/custom-profile-fields.ts
  packages/phrases/src/locales/pt-br/errors/custom-profile-fields.ts
  packages/phrases/src/locales/pt-pt/errors/custom-profile-fields.ts
  packages/phrases/src/locales/ru/errors/custom-profile-fields.ts
  packages/phrases/src/locales/tr-tr/errors/custom-profile-fields.ts
  packages/phrases/src/locales/zh-cn/errors/custom-profile-fields.ts
  packages/phrases/src/locales/zh-hk/errors/custom-profile-fields.ts
  packages/phrases/src/locales/zh-tw/errors/custom-profile-fields.ts
Labels: bugfix, size/m

#7670 test: add email mfa verification tests
  packages/integration-tests/src/tests/api/experience-api/verifications/email-mfa-verification.test.ts
Labels: testing, size/s

#7675 fix(experience): display loading spinner on submit buttons when navigating to user app
  packages/experience/src/containers/SetPassword/Lite.tsx
  packages/experience/src/containers/SetPassword/SetPassword.tsx
  packages/experience/src/pages/Continue/ExtraProfileForm/index.tsx
  packages/experience/src/pages/Continue/IdentifierProfileForm/index.tsx
  packages/experience/src/pages/ForgotPassword/ForgotPasswordForm/index.tsx
  packages/experience/src/pages/MfaVerification/BackupCodeVerification/index.tsx
  packages/experience/src/pages/SignInPassword/PasswordForm/index.tsx
Labels: bugfix, size/s

#7686 feat(experience): add a new DateField component to improve user input experience
  packages/experience/src/components/InputFields/DateField/index.module.scss
  packages/experience/src/components/InputFields/DateField/index.tsx
  packages/experience/src/components/InputFields/PrimitiveProfileInputField/index.tsx
Labels: feature, size/l

#7688 fix(console): use consistent field tags across list page and details page
  packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/ProfileFieldDetails/ProfileFieldDetailsForm/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/ProfileFieldList/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/utils.ts
Labels: bugfix, size/s

#7681 feat(experience): setup phone MFA
  packages/experience/src/App.tsx
  packages/experience/src/containers/MfaFactorList/index.tsx
  packages/experience/src/pages/MfaBinding/EmailMfaBinding/index.tsx
  packages/experience/src/pages/MfaBinding/PhoneMfaBinding/index.tsx
  packages/experience/src/pages/MfaBinding/VerificationCodeMfaBinding/index.module.scss
  packages/experience/src/pages/MfaBinding/VerificationCodeMfaBinding/index.tsx
  packages/experience/src/types/guard.ts
  packages/integration-tests/src/tests/experience/mfa/phone/index.test.ts
  packages/phrases-experience/src/locales/ar/mfa.ts
  packages/phrases-experience/src/locales/de/mfa.ts
  packages/phrases-experience/src/locales/en/mfa.ts
  packages/phrases-experience/src/locales/es/mfa.ts
  packages/phrases-experience/src/locales/fr/mfa.ts
  packages/phrases-experience/src/locales/it/mfa.ts
  packages/phrases-experience/src/locales/ja/mfa.ts
  packages/phrases-experience/src/locales/ko/mfa.ts
  packages/phrases-experience/src/locales/pl-pl/mfa.ts
  packages/phrases-experience/src/locales/pt-br/mfa.ts
  packages/phrases-experience/src/locales/pt-pt/mfa.ts
  packages/phrases-experience/src/locales/ru/mfa.ts
  packages/phrases-experience/src/locales/tr-tr/mfa.ts
  packages/phrases-experience/src/locales/uk-ua/mfa.ts
  packages/phrases-experience/src/locales/zh-cn/mfa.ts
  packages/phrases-experience/src/locales/zh-hk/mfa.ts
  packages/phrases-experience/src/locales/zh-tw/mfa.ts
Labels: feature, size/l

#7696 feat(experience): email phone MFA verification
  packages/experience/src/App.tsx
  packages/experience/src/apis/experience/mfa.ts
  packages/experience/src/containers/MfaCodeVerification/index.module.scss
  packages/experience/src/containers/MfaCodeVerification/index.tsx
  packages/experience/src/containers/MfaCodeVerification/use-mfa-code-verification.ts
  packages/experience/src/containers/MfaCodeVerification/use-resend-mfa-verification-code.ts
  packages/experience/src/pages/MfaVerification/EmailVerificationCode/index.module.scss
  packages/experience/src/pages/MfaVerification/EmailVerificationCode/index.tsx
  packages/experience/src/pages/MfaVerification/PhoneVerificationCode/index.module.scss
  packages/experience/src/pages/MfaVerification/PhoneVerificationCode/index.tsx
  packages/integration-tests/src/tests/experience/mfa/email-verification/index.test.ts
  packages/phrases-experience/src/locales/ar/mfa.ts
  packages/phrases-experience/src/locales/de/mfa.ts
  packages/phrases-experience/src/locales/en/mfa.ts
  packages/phrases-experience/src/locales/es/mfa.ts
  packages/phrases-experience/src/locales/fr/mfa.ts
  packages/phrases-experience/src/locales/it/mfa.ts
  packages/phrases-experience/src/locales/ja/mfa.ts
  packages/phrases-experience/src/locales/ko/mfa.ts
  packages/phrases-experience/src/locales/pl-pl/mfa.ts
  packages/phrases-experience/src/locales/pt-br/mfa.ts
  packages/phrases-experience/src/locales/pt-pt/mfa.ts
  packages/phrases-experience/src/locales/ru/mfa.ts
  packages/phrases-experience/src/locales/tr-tr/mfa.ts
  packages/phrases-experience/src/locales/uk-ua/mfa.ts
  packages/phrases-experience/src/locales/zh-cn/mfa.ts
  packages/phrases-experience/src/locales/zh-hk/mfa.ts
  packages/phrases-experience/src/locales/zh-tw/mfa.ts
Labels: feature, size/xl

#7703 refactor(console,experience): minor improvements to hints and translation
  packages/console/src/pages/SignInExperience/PageContent/components/ProfileFieldPartSubForm/index.tsx
  packages/phrases-experience/src/locales/en/profile.ts
Labels: enhancement, size/s

#7694 chore: remove dev feature guard of the collect user profile feature
  packages/console/src/pages/SignInExperience/PageContent/index.tsx
  packages/core/src/libraries/sign-in-experience/index.test.ts
  packages/core/src/libraries/sign-in-experience/index.ts
  packages/core/src/routes/custom-profile-fields.openapi.json
  packages/core/src/routes/experience/experience.openapi.json
  packages/core/src/routes/experience/index.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/swagger/utils/documents.ts
  packages/core/src/routes/swagger/utils/general.ts
  packages/core/src/routes/swagger/utils/operation-id.ts
  packages/experience/src/hooks/use-required-profile-error-handler.ts
  packages/integration-tests/src/tests/api/custom-profile-fields.test.ts
  packages/integration-tests/src/tests/api/experience-api/profile/fulfill-user-profiles.test.ts
  packages/schemas/src/types/sign-in-experience.ts
Labels: chore, size/m

#7693 refactor(experience): improve a11y and keyboard control on the select field
  packages/experience/src/components/Dropdown/DropdownItem.module.scss
  packages/experience/src/components/Dropdown/DropdownItem.tsx
  packages/experience/src/components/InputFields/SelectField/index.module.scss
  packages/experience/src/components/InputFields/SelectField/index.test.tsx
  packages/experience/src/components/InputFields/SelectField/index.tsx
  packages/experience/src/jest.setup.ts
Labels: enhancement, size/l

#7697 feat(core,connector): add new verification code type for mfa
  .changeset/tasty-panthers-cross.md
  packages/connectors/connector-logto-email/src/index.ts
  packages/connectors/connector-mock-email/docs/config-template.json
  packages/connectors/connector-mock-sms/docs/config-template.json
  packages/core/src/routes/experience/classes/verifications/code-verification.ts
  packages/core/src/routes/experience/verification-routes/verification-code.ts
  packages/integration-tests/src/__mocks__/connectors-mock.ts
  packages/toolkit/connector-kit/src/types/passwordless.ts
Labels: feature, size/s

#7701 refactor(core): require captcha only for unidentified users
  packages/core/src/routes/experience/verification-routes/verification-code.ts
Labels: enhancement, size/xs

#7678 refactor(core): remove refresh_token token usage report
  packages/core/src/event-listeners/index.ts
Labels: enhancement, size/s

#7679 feat(schemas,console): reserve new pro-202508 planId
  packages/console/src/components/FeatureTag/index.tsx
  packages/console/src/components/PlanDescription/index.tsx
  packages/console/src/components/SkuName/index.tsx
  packages/console/src/consts/plan-quotas.ts
  packages/console/src/consts/subscriptions.ts
  packages/console/src/utils/subscription.ts
  packages/core/src/libraries/quota.ts
  packages/core/src/libraries/subscription.test.ts
  packages/schemas/src/consts/subscriptions.ts
Labels: feature, size/s

#7699 feat(core,experience): show masked email/phone for MFA verification c…
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/interaction/verifications/mfa-verification.ts
  packages/experience/src/hooks/use-mfa-error-handler.ts
  packages/experience/src/pages/MfaVerification/EmailVerificationCode/index.tsx
  packages/experience/src/pages/MfaVerification/PhoneVerificationCode/index.tsx
  packages/experience/src/types/guard.ts
  packages/experience/src/utils/format.ts
  packages/phrases-experience/src/locales/ar/mfa.ts
  packages/phrases-experience/src/locales/de/mfa.ts
  packages/phrases-experience/src/locales/en/mfa.ts
  packages/phrases-experience/src/locales/es/mfa.ts
  packages/phrases-experience/src/locales/fr/mfa.ts
  packages/phrases-experience/src/locales/it/mfa.ts
  packages/phrases-experience/src/locales/ja/mfa.ts
  packages/phrases-experience/src/locales/ko/mfa.ts
  packages/phrases-experience/src/locales/pl-pl/mfa.ts
  packages/phrases-experience/src/locales/pt-br/mfa.ts
  packages/phrases-experience/src/locales/pt-pt/mfa.ts
  packages/phrases-experience/src/locales/ru/mfa.ts
  packages/phrases-experience/src/locales/tr-tr/mfa.ts
  packages/phrases-experience/src/locales/uk-ua/mfa.ts
  packages/phrases-experience/src/locales/zh-cn/mfa.ts
  packages/phrases-experience/src/locales/zh-hk/mfa.ts
  packages/phrases-experience/src/locales/zh-tw/mfa.ts
  packages/shared/src/utils/index.ts
  packages/shared/src/utils/mask.ts
Labels: feature, size/m

#7710 release(connector): release connector kit 4.5.0
  .changeset/tasty-panthers-cross.md
  packages/connectors/connector-mock-email/CHANGELOG.md
  packages/connectors/connector-mock-email/package.json
  packages/connectors/connector-mock-sms/CHANGELOG.md
  packages/connectors/connector-mock-sms/package.json
  packages/toolkit/connector-kit/CHANGELOG.md
  packages/toolkit/connector-kit/package.json
Labels: size/s

#7717 fix(core): fix session relation not found error
  packages/core/src/queries/oidc-model-instance.ts
Labels: bugfix, size/xs

#7698 feat(core): enable new add-on SKU real-time usage report
  packages/connectors/connector-logto-email/package.json
  packages/console/package.json
  packages/console/src/consts/subscriptions.ts
  packages/core/package.json
  packages/core/src/routes/applications/application.ts
  packages/core/src/routes/role.test.ts
  packages/core/src/routes/role.ts
  packages/core/src/routes/saml-application/index.ts
  packages/core/src/utils/subscription/types.ts
  pnpm-lock.yaml
Labels: feature, size/s

#7708 refactor(experience): improve date field backspace behavior and tests
  packages/experience/src/components/InputFields/DateField/index.test.tsx
  packages/experience/src/components/InputFields/DateField/index.tsx
Labels: enhancement, size/m

#7709 fix(console): should close the profile field creation modal on esc
  packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/CreateProfileFieldModal/index.tsx
Labels: bugfix, size/xs

#7726 chore: update cloud package
  packages/connectors/connector-logto-email/package.json
  packages/connectors/connector-logto-email/src/index.ts
  packages/console/package.json
  packages/core/package.json
  pnpm-lock.yaml
Labels: chore, size/xs

#7702 docs(console): update microsoft entra id oidc and okta readme
  packages/console/src/assets/docs/single-sign-on/azure-oidc/README.mdx
  packages/console/src/assets/docs/single-sign-on/azure-oidc/assets/add_api_permissions.webp
  packages/console/src/assets/docs/single-sign-on/okta/README.mdx
Labels: chore, size/s

#7721 docs: update the EU region endpoint in the Gateway API guide
  packages/connectors/connector-gatewayapi-sms/README.md
Labels: size/xs

#7732 feat(schemas): add organization level custom css support
  packages/integration-tests/src/tests/api/organization/organization.test.ts
  packages/schemas/alterations/next-1756191517-add-organization-custom-css.ts
  packages/schemas/tables/organizations.sql
Labels: feature, size/s

#7733 feat(core): add org-level custom css support in sign-in-exp API
  packages/core/src/libraries/sign-in-experience/index.ts
  packages/integration-tests/src/tests/experience/overrides.test.ts
Labels: feature, size/s

#7737 refactor: revert organization-level custom css db alteration
  packages/core/src/libraries/sign-in-experience/index.ts
  packages/integration-tests/src/tests/api/organization/organization.test.ts
  packages/integration-tests/src/tests/experience/overrides.test.ts
  packages/schemas/alterations/next-1756191517-add-organization-custom-css.ts
  packages/schemas/tables/organizations.sql
Labels: enhancement, size/s

#7736 feat(console): support dynamic regions when creating a new tenant
  packages/connectors/connector-logto-email/package.json
  packages/console/package.json
  packages/console/src/components/CreateTenantModal/index.module.scss
  packages/console/src/components/CreateTenantModal/index.tsx
  packages/console/src/components/Region/index.tsx
  packages/console/src/onboarding/pages/CreateTenant/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/TenantRegion/index.tsx
  packages/core/package.json
  pnpm-lock.yaml
Labels: feature, size/m

#7741 fix(core,connector): add bind mfa verification code type
  .changeset/kind-cherries-yawn.md
  packages/connectors/connector-logto-email/src/index.ts
  packages/core/src/routes/experience/verification-routes/verification-code.ts
  packages/integration-tests/src/__mocks__/connectors-mock.ts
  packages/toolkit/connector-kit/src/types/passwordless.ts
Labels: bugfix, size/s

#7750 refactor(console): hide tenant convert buttons for dev-only regions
  packages/console/src/components/CreateTenantModal/index.tsx
  packages/console/src/consts/tenants.ts
  packages/console/src/contexts/TenantsProvider.tsx
  packages/console/src/hooks/use-available-regions.ts
  packages/console/src/pages/GetStarted/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/TenantEnvironment/index.tsx
Labels: enhancement, size/s

#7735 refactor(console,core): remove new pricing dev feature guards
  packages/console/src/components/ApplicationCreation/CreateForm/Footer/index.tsx
  packages/console/src/components/ApplicationCreation/CreateForm/index.tsx
  packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/SkuCardItem/FeaturedSkuContent/use-featured-sku-content.ts
  packages/console/src/components/Guide/GuideCardGroup/index.tsx
  packages/console/src/components/PlanUsage/utils.ts
  packages/console/src/consts/subscriptions.ts
  packages/console/src/pages/Roles/components/CreateRoleForm/Footer.tsx
  packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
  packages/console/src/pages/Roles/index.tsx
  packages/core/src/event-listeners/index.ts
  packages/core/src/middleware/koa-security-headers.ts
  packages/core/src/routes/applications/application.ts
  packages/core/src/routes/role.ts
  packages/core/src/routes/saml-application/index.ts
  packages/core/src/utils/subscription/types.ts
Labels: enhancement, size/m
