Repository logto-io/logto, pull requests merged in 2025-09, with the labels that each got.

#7754 chore: add dev feature guard for org-level branding settings
  packages/console/src/pages/ApplicationDetails/components/Branding/NonThirdPartyBrandingForm.tsx
  packages/console/src/pages/OrganizationDetails/Settings/index.tsx
  packages/console/src/pages/OrganizationDetails/index.tsx
Labels: chore, size/s

#7742 refactor(experience): send mfa verification code before loading compo…
  packages/experience/src/containers/MfaFactorList/index.tsx
  packages/experience/src/hooks/use-mfa-error-handler.ts
  packages/experience/src/hooks/use-send-mfa-verification-code.ts
  packages/experience/src/pages/MfaVerification/EmailVerificationCode/index.tsx
  packages/experience/src/pages/MfaVerification/PhoneVerificationCode/index.tsx
Labels: enhancement, size/m

#7744 fix(connector): add full usage types to default value
  packages/connectors/connector-aliyun-dm/src/constant.ts
  packages/connectors/connector-aliyun-sms/src/constant.ts
  packages/connectors/connector-aws-ses/src/constant.ts
  packages/connectors/connector-gatewayapi-sms/src/constant.ts
  packages/connectors/connector-postmark/src/constant.ts
  packages/connectors/connector-sendgrid-email/src/constant.ts
  packages/connectors/connector-smsaero/src/constant.ts
  packages/connectors/connector-smtp/src/constant.ts
  packages/connectors/connector-tencent-sms/src/constant.ts
  packages/connectors/connector-twilio-sms/src/constant.ts
  packages/connectors/connector-vonage-sms/src/constant.ts
  packages/connectors/connector-yunpian-sms/src/constant.ts
Labels: bugfix, size/l

#7756 feat(core): save rpid for passkey
  packages/core/src/__mocks__/mfa-verification.ts
  packages/core/src/__mocks__/webauthn.ts
  packages/core/src/routes/experience/classes/verifications/web-authn-verification.test.ts
  packages/core/src/routes/experience/classes/verifications/web-authn-verification.ts
  packages/core/src/routes/interaction/verifications/mfa-payload-verification.test.ts
  packages/core/src/routes/interaction/verifications/mfa-payload-verification.ts
  packages/schemas/src/foundations/jsonb-types/users.ts
  packages/schemas/src/types/interactions.ts
  packages/schemas/src/types/verification-records/web-authn-verification.ts
Labels: feature, size/m

#7759 refactor(console): hide title for empty diff section
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignInChangePreview/SignUpAndSignInDiffSection/SignInDiffSection.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignInChangePreview/SignUpAndSignInDiffSection/SignUpDiffSection.tsx
Labels: enhancement, size/xs

#7766 fix(console): skip forgot password migration for empty value
  packages/console/src/pages/SignInExperience/PageContent/index.tsx
Labels: bugfix, size/xs

#7769 fix(console): add beta tag to email phone MFA
  packages/console/src/pages/Mfa/MfaForm/FactorLabel/index.module.scss
  packages/console/src/pages/Mfa/MfaForm/FactorLabel/index.tsx
Labels: bugfix, size/s

#7764 fix(core): bind WebAuthn rpId to request domain for account api
  .changeset/thin-walls-tap.md
  packages/core/src/routes/verification/index.ts
  packages/integration-tests/src/tests/api/account/mfa-webauthn.test.ts
Labels: bugfix, size/s

#7773 chore(console): remove dev feature guard for org-level branding
  packages/console/src/pages/ApplicationDetails/components/Branding/NonThirdPartyBrandingForm.tsx
  packages/console/src/pages/OrganizationDetails/Settings/index.tsx
  packages/console/src/pages/OrganizationDetails/index.tsx
  packages/console/src/pages/OrganizationDetails/utils.ts
Labels: chore, size/s

#7776 refactor(core): sort available factors
  packages/core/src/routes/experience/classes/mfa.ts
Labels: enhancement, size/s

#7770 chore: remove email phone MFA feature flag
  packages/console/src/components/SignInExperiencePreview/index.tsx
  packages/console/src/pages/Mfa/MfaForm/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignInForm/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignInChangePreview/SignUpAndSignInDiffSection/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/utils/form.ts
  packages/console/src/pages/SignInExperience/PageContent/utils/parser.ts
  packages/core/src/libraries/sign-in-experience/index.ts
  packages/core/src/libraries/sign-in-experience/mfa.ts
  packages/core/src/routes/account/index.openapi.json
  packages/core/src/routes/account/index.ts
  packages/core/src/routes/experience/classes/helpers.ts
  packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.ts
  packages/core/src/routes/experience/classes/mfa.ts
  packages/core/src/routes/experience/profile-routes.openapi.json
  packages/core/src/routes/experience/profile-routes.ts
  packages/core/src/routes/sign-in-experience/index.ts
  packages/experience/src/App.tsx
  packages/integration-tests/src/tests/api/account/mfa-settings.test.ts
  packages/integration-tests/src/tests/api/experience-api/bind-mfa/email-phone.test.ts
  packages/integration-tests/src/tests/api/experience-api/bind-mfa/email-with-signup.test.ts
  packages/integration-tests/src/tests/api/experience-api/bind-mfa/mfa-suggestion.test.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/skip-mfa-on-sign-in.test.ts
  packages/integration-tests/src/tests/api/experience-api/verifications/email-phone-mfa-verification.test.ts
  packages/integration-tests/src/tests/api/sign-in-experience.forgot-password.test.ts
  packages/integration-tests/src/tests/api/sign-in-experience.test.ts
  packages/integration-tests/src/tests/experience/mfa/email-verification/index.test.ts
  packages/integration-tests/src/tests/experience/mfa/email/index.test.ts
  packages/integration-tests/src/tests/experience/mfa/phone/index.test.ts
  packages/integration-tests/src/tests/experience/mfa/suggest-additional-on-register.test.ts
  packages/schemas/alterations/next-1756954492-add-default-to-forgot-password-methods.ts
  packages/schemas/src/gen/schema.ts
  packages/schemas/tables/sign_in_experiences.sql
Labels: chore, size/xl

#7782 fix(core): skip MFA suggestion when user has factors from non-reg
  packages/core/src/routes/experience/classes/mfa.ts
  packages/integration-tests/src/tests/api/experience-api/bind-mfa/mfa-suggestion.test.ts
Labels: bugfix, size/m

#7771 refactor(core): introduce new env for multiple custom domains feature
  packages/core/src/routes/domain.test.ts
  packages/core/src/routes/domain.ts
  packages/integration-tests/src/tests/api/domains.test.ts
  packages/shared/src/node/env/GlobalValues.ts
Labels: enhancement, size/s

#7705 chore: add changeset of email/phone mfa
  .changeset/chilled-houses-arrive.md
  .changeset/short-balloons-suffer.md
Labels: chore, size/s

#7795 feat(experience): improve MFA button text for email/phone verification
  packages/experience/src/components/Button/MfaFactorButton.tsx
  packages/phrases-experience/src/locales/ar/mfa.ts
  packages/phrases-experience/src/locales/de/mfa.ts
  packages/phrases-experience/src/locales/en/mfa.ts
  packages/phrases-experience/src/locales/es/mfa.ts
  packages/phrases-experience/src/locales/fr/mfa.ts
  packages/phrases-experience/src/locales/it/mfa.ts
  packages/phrases-experience/src/locales/ja/mfa.ts
  packages/phrases-experience/src/locales/ko/mfa.ts
  packages/phrases-experience/src/locales/pl-pl/mfa.ts
  packages/phrases-experience/src/locales/pt-br/mfa.ts
  packages/phrases-experience/src/locales/pt-pt/mfa.ts
  packages/phrases-experience/src/locales/ru/mfa.ts
  packages/phrases-experience/src/locales/th/mfa.ts
  packages/phrases-experience/src/locales/tr-tr/mfa.ts
  packages/phrases-experience/src/locales/uk-ua/mfa.ts
  packages/phrases-experience/src/locales/zh-cn/mfa.ts
  packages/phrases-experience/src/locales/zh-hk/mfa.ts
  packages/phrases-experience/src/locales/zh-tw/mfa.ts
Labels: feature, size/s

#7800 fix(experience): fix page flashing issue on page load
  packages/experience/src/Providers/SettingsProvider/use-sign-in-experience.ts
  packages/experience/src/Providers/SettingsProvider/use-theme.ts
Labels: bugfix, size/s

#7799 feat: add multiple custom domains
  packages/console/src/consts/env.ts
  packages/console/src/hooks/use-custom-domain.ts
  packages/console/src/pages/TenantSettings/TenantDomainSettings/AddDomainForm/index.tsx
  packages/console/src/pages/TenantSettings/TenantDomainSettings/MultipleCustomDomainsFormField/index.module.scss
  packages/console/src/pages/TenantSettings/TenantDomainSettings/MultipleCustomDomainsFormField/index.tsx
  packages/console/src/pages/TenantSettings/TenantDomainSettings/SingleCustomDomainFormField/index.module.scss
  packages/console/src/pages/TenantSettings/TenantDomainSettings/SingleCustomDomainFormField/index.tsx
  packages/console/src/pages/TenantSettings/TenantDomainSettings/index.module.scss
  packages/console/src/pages/TenantSettings/TenantDomainSettings/index.tsx
  packages/console/vite.config.ts
  packages/core/src/queries/domains.ts
  packages/core/src/routes/domain.ts
  packages/phrases/src/locales/ar/errors/domain.ts
  packages/phrases/src/locales/ar/translation/admin-console/domain.ts
  packages/phrases/src/locales/de/errors/domain.ts
  packages/phrases/src/locales/de/translation/admin-console/domain.ts
  packages/phrases/src/locales/en/errors/domain.ts
  packages/phrases/src/locales/en/translation/admin-console/domain.ts
  packages/phrases/src/locales/es/errors/domain.ts
  packages/phrases/src/locales/es/translation/admin-console/domain.ts
  packages/phrases/src/locales/fr/errors/domain.ts
  packages/phrases/src/locales/fr/translation/admin-console/domain.ts
  packages/phrases/src/locales/it/errors/domain.ts
  packages/phrases/src/locales/it/translation/admin-console/domain.ts
  packages/phrases/src/locales/ja/errors/domain.ts
  packages/phrases/src/locales/ja/translation/admin-console/domain.ts
  packages/phrases/src/locales/ko/errors/domain.ts
  packages/phrases/src/locales/ko/translation/admin-console/domain.ts
  packages/phrases/src/locales/pl-pl/errors/domain.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/domain.ts
  packages/phrases/src/locales/pt-br/errors/domain.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/domain.ts
  packages/phrases/src/locales/pt-pt/errors/domain.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/domain.ts
  packages/phrases/src/locales/ru/errors/domain.ts
  packages/phrases/src/locales/ru/translation/admin-console/domain.ts
  packages/phrases/src/locales/th/errors/domain.ts
  packages/phrases/src/locales/th/translation/admin-console/domain.ts
  packages/phrases/src/locales/tr-tr/errors/domain.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/domain.ts
  packages/phrases/src/locales/zh-cn/errors/domain.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/domain.ts
  packages/phrases/src/locales/zh-hk/errors/domain.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/domain.ts
  packages/phrases/src/locales/zh-tw/errors/domain.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/domain.ts
Labels: feature, size/l

#7804 feat: add limits for multiple custom domains
  packages/core/src/constants/index.ts
  packages/core/src/routes/domain.ts
  packages/phrases/src/locales/ar/errors/domain.ts
  packages/phrases/src/locales/de/errors/domain.ts
  packages/phrases/src/locales/en/errors/domain.ts
  packages/phrases/src/locales/es/errors/domain.ts
  packages/phrases/src/locales/fr/errors/domain.ts
  packages/phrases/src/locales/it/errors/domain.ts
  packages/phrases/src/locales/ja/errors/domain.ts
  packages/phrases/src/locales/ko/errors/domain.ts
  packages/phrases/src/locales/pl-pl/errors/domain.ts
  packages/phrases/src/locales/pt-br/errors/domain.ts
  packages/phrases/src/locales/pt-pt/errors/domain.ts
  packages/phrases/src/locales/ru/errors/domain.ts
  packages/phrases/src/locales/th/errors/domain.ts
  packages/phrases/src/locales/tr-tr/errors/domain.ts
  packages/phrases/src/locales/zh-cn/errors/domain.ts
  packages/phrases/src/locales/zh-tw/errors/domain.ts
Labels: feature, size/s

#7796 fix(console): deduplicate audit log event titles
  packages/console/src/consts/logs.ts
Labels: bugfix, size/s

#7812 fix: security issues audit fix
  package.json
  pnpm-lock.yaml
Labels: bugfix, size/xs

#7813 style: update add domain input styles and copy
  packages/console/src/pages/TenantSettings/TenantDomainSettings/AddDomainForm/index.tsx
  packages/console/src/pages/TenantSettings/TenantDomainSettings/MultipleCustomDomainsFormField/index.tsx
  packages/phrases/src/locales/ar/translation/admin-console/domain.ts
  packages/phrases/src/locales/de/translation/admin-console/domain.ts
  packages/phrases/src/locales/en/translation/admin-console/domain.ts
  packages/phrases/src/locales/es/translation/admin-console/domain.ts
  packages/phrases/src/locales/fr/translation/admin-console/domain.ts
  packages/phrases/src/locales/it/translation/admin-console/domain.ts
  packages/phrases/src/locales/ja/translation/admin-console/domain.ts
  packages/phrases/src/locales/ko/translation/admin-console/domain.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/domain.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/domain.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/domain.ts
  packages/phrases/src/locales/ru/translation/admin-console/domain.ts
  packages/phrases/src/locales/th/translation/admin-console/domain.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/domain.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/domain.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/domain.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/domain.ts
Labels: size/s

#7802 feat(core,experience,schemas): support ui_locales in Experience UI
  packages/core/src/middleware/koa-experience-ssr.ts
  packages/core/src/oidc/init.ts
  packages/core/src/utils/i18n.ts
  packages/experience/src/i18n/utils.ts
  packages/experience/src/utils/search-parameters.ts
  packages/schemas/src/types/cookie.ts
  packages/schemas/src/types/ssr.ts
Labels: feature, size/s

#7811 feat(core,toolkit): add ui_locales support in email template variables
  packages/core/src/libraries/passcode.ts
  packages/core/src/routes-me/verification-code.ts
  packages/core/src/routes/experience/verification-routes/verification-code-helpers.ts
  packages/core/src/routes/interaction/additional.ts
  packages/core/src/routes/interaction/utils/verification-code-validation.ts
  packages/core/src/routes/verification/index.ts
  packages/core/src/utils/cookie.ts
  packages/toolkit/connector-kit/src/types/passwordless.ts
Labels: feature, size/s

#7818 refactor(console): update M2M guide samples with real app metadata
  packages/console/src/assets/docs/guides/m2m-general/README.mdx
  packages/console/src/components/Guide/index.tsx
  packages/console/src/ds-components/CopyToClipboard/index.tsx
  packages/console/src/mdx-components/ApplicationCredentials/index.tsx
  packages/console/src/pages/ApiResourceDetails/components/ApiGuide/index.tsx
  packages/console/src/pages/ApplicationDetails/components/AppGuide/index.tsx
Labels: enhancement, size/m

#7823 style(console): fix read-only state drop down icon color for select component
  packages/console/src/ds-components/Select/index.module.scss
Labels: size/s

#7825 chore: add changeset for ui_locales feature
  .changeset/great-starfishes-help.md
Labels: chore, size/s

#7827 feat(connector): add email support for x connector
  .changeset/wicked-mails-peel.md
  packages/connectors/connector-x/README.md
  packages/connectors/connector-x/src/index.test.ts
  packages/connectors/connector-x/src/index.ts
  packages/connectors/connector-x/src/types.ts
Labels: feature, size/s

#7832 fix(console): open learn more link in blank target
  packages/console/src/components/PlanUsage/PlanUsageCard/index.tsx
Labels: bugfix, size/xs

#7835 refactor: read feature flag from tenant response
  packages/connectors/connector-logto-email/package.json
  packages/connectors/connector-logto-email/src/index.ts
  packages/console/package.json
  packages/console/src/consts/env.ts
  packages/console/src/pages/TenantSettings/TenantDomainSettings/index.tsx
  packages/console/vite.config.ts
  packages/core/package.json
  pnpm-lock.yaml
Labels: enhancement, size/s

#7857 fix(experience): replace `||=` operator with compatible assignments for broader browser stability
  packages/experience/src/pages/OneTimeToken/index.tsx
Labels: bugfix, size/xs
