Repository logto-io/logto, pull requests merged in 2025-07, with the labels that each got.

#7489 refactor(schemas): split secret_connector_relations table
  packages/schemas/alterations/next-1750744685-add-triggers-to-delete-secrets-on-social-identities-deletion.ts
  packages/schemas/alterations/next-1751255436-split-secret-connector-relatioins-table.ts
  packages/schemas/tables/secret_connector_relations.sql
  packages/schemas/tables/secret_enterprise_sso_connector_relations.sql
  packages/schemas/tables/secret_social_connector_relations.sql
Labels: enhancement, size/xl

#7491 feat(core,schemas): add custom profile fields to sign-in experience well-known cache
  packages/core/src/__mocks__/custom-profile-fields.ts
  packages/core/src/__mocks__/index.ts
  packages/core/src/libraries/sign-in-experience/index.test.ts
  packages/core/src/libraries/sign-in-experience/index.ts
  packages/integration-tests/src/tests/api/well-known.test.ts
  packages/schemas/src/types/sign-in-experience.ts
Labels: feature, size/m

#7492 refactor(core,phrases): disallow sign-in identifiers in custom profile fields
  packages/core/src/libraries/custom-profile-fields/utils.ts
  packages/integration-tests/src/__mocks__/profile-fields-mock.ts
  packages/integration-tests/src/tests/api/custom-profile-fields.test.ts
  packages/phrases/src/locales/ar/errors/custom-profile-fields.ts
  packages/phrases/src/locales/de/errors/custom-profile-fields.ts
  packages/phrases/src/locales/en/errors/custom-profile-fields.ts
  packages/phrases/src/locales/es/errors/custom-profile-fields.ts
  packages/phrases/src/locales/fr/errors/custom-profile-fields.ts
  packages/phrases/src/locales/it/errors/custom-profile-fields.ts
  packages/phrases/src/locales/ja/errors/custom-profile-fields.ts
  packages/phrases/src/locales/ko/errors/custom-profile-fields.ts
  packages/phrases/src/locales/pl-pl/errors/custom-profile-fields.ts
  packages/phrases/src/locales/pt-br/errors/custom-profile-fields.ts
  packages/phrases/src/locales/pt-pt/errors/custom-profile-fields.ts
  packages/phrases/src/locales/ru/errors/custom-profile-fields.ts
  packages/phrases/src/locales/tr-tr/errors/custom-profile-fields.ts
  packages/phrases/src/locales/zh-cn/errors/custom-profile-fields.ts
  packages/phrases/src/locales/zh-hk/errors/custom-profile-fields.ts
  packages/phrases/src/locales/zh-tw/errors/custom-profile-fields.ts
Labels: enhancement, size/s

#7497 feat(console): add tenant type converting entry
  packages/console/src/assets/icons/convert-line.svg
  packages/console/src/assets/icons/rocket.svg
  packages/console/src/components/ConvertToProductionModal/index.module.scss
  packages/console/src/components/ConvertToProductionModal/index.tsx
  packages/console/src/consts/tenants.ts
  packages/console/src/pages/GetStarted/ConvertToProductionCard.tsx
  packages/console/src/pages/GetStarted/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/TenantEnvironment/index.module.scss
  packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/TenantEnvironment/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/get-started.ts
  packages/phrases/src/locales/en/translation/admin-console/upsell/index.ts
Labels: feature, size/l

#7506 chore: transient deps audit fix
  package.json
  pnpm-lock.yaml
Labels: chore, size/s

#7493 feat(core,schemas): add requireMfaOnSignIn
  .gitignore
  packages/core/src/__mocks__/user.ts
  packages/core/src/routes/account/index.openapi.json
  packages/core/src/routes/account/index.ts
  packages/integration-tests/src/api/my-account.ts
  packages/integration-tests/src/tests/api/account/mfa-settings.test.ts
  packages/schemas/alterations/next-1751337183-add-require-mfa-on-sign-in-to-users.ts
  packages/schemas/tables/users.sql
Labels: feature, size/l

#7500 test: add integration tests for token storage
  .github/workflows/alteration-compatibility-integration-test.yml
  .github/workflows/integration-test.yml
  packages/connectors/connector-mock-social/src/constant.ts
  packages/connectors/connector-mock-social/src/index.ts
  packages/integration-tests/src/api/admin-user.ts
  packages/integration-tests/src/api/connector.ts
  packages/integration-tests/src/helpers/experience/index.ts
  packages/integration-tests/src/tests/api/connector.test.ts
  packages/integration-tests/src/tests/api/experience-api/profile/social-fullfill-user-profiles.test.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/social.test.ts
Labels: testing, size/xl

#7501 feat(core): update social account API
  packages/core/src/libraries/social.ts
  packages/core/src/routes/account/identities.ts
  packages/integration-tests/src/tests/api/account/social.test.ts
Labels: feature, size/m

#7499 feat(core): apply requireMfaOnSignIn
  packages/core/src/routes/experience/classes/libraries/mfa-validator.ts
  packages/core/src/routes/interaction/verifications/mfa-verification.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/require-mfa-on-sign-in.test.ts
Labels: feature, size/m

#7504 feat(core): manage custom data in account api
  packages/core/src/routes/account/index.openapi.json
  packages/core/src/routes/account/index.ts
  packages/integration-tests/src/tests/api/account/index.test.ts
Labels: feature, size/s

#7508 feat(schemas,core): add enable_token_storage field to SSO connector
  packages/core/src/__mocks__/sso.ts
  packages/core/src/routes/sso-connector/index.ts
  packages/core/src/routes/sso-connector/type.ts
  packages/schemas/alterations/next-1751529530394-add-enable-token-storage-column-to-sso-connectors-table.ts
  packages/schemas/tables/sso_connectors.sql
Labels: feature, size/s

#7516 refactor(core): refactor sso getUserInfo endpoint
  packages/core/src/routes/interaction/utils/single-sign-on.test.ts
  packages/core/src/routes/interaction/utils/single-sign-on.ts
  packages/core/src/sso/AzureOidcSsoConnector/index.ts
  packages/core/src/sso/OidcConnector/index.ts
  packages/core/src/sso/OidcConnector/utils.test.ts
  packages/core/src/sso/OidcConnector/utils.ts
  packages/core/src/sso/SamlSsoConnector/index.ts
Labels: enhancement, size/s

#7498 feat(core): add support for more profile fields in update profile experience API
  packages/core/src/libraries/custom-profile-fields/utils.ts
  packages/core/src/routes/experience/classes/libraries/profile-validator.test.ts
  packages/core/src/routes/experience/classes/libraries/profile-validator.ts
  packages/core/src/routes/experience/classes/profile.ts
  packages/core/src/routes/experience/profile-routes.openapi.json
  packages/core/src/routes/experience/profile-routes.ts
  packages/core/src/routes/experience/types.ts
  packages/integration-tests/src/tests/api/experience-api/profile/fulfill-user-profiles.test.ts
  packages/phrases/src/locales/ar/errors/custom-profile-fields.ts
  packages/phrases/src/locales/de/errors/custom-profile-fields.ts
  packages/phrases/src/locales/en/errors/custom-profile-fields.ts
  packages/phrases/src/locales/es/errors/custom-profile-fields.ts
  packages/phrases/src/locales/fr/errors/custom-profile-fields.ts
  packages/phrases/src/locales/it/errors/custom-profile-fields.ts
  packages/phrases/src/locales/ja/errors/custom-profile-fields.ts
  packages/phrases/src/locales/ko/errors/custom-profile-fields.ts
  packages/phrases/src/locales/pl-pl/errors/custom-profile-fields.ts
  packages/phrases/src/locales/pt-br/errors/custom-profile-fields.ts
  packages/phrases/src/locales/pt-pt/errors/custom-profile-fields.ts
  packages/phrases/src/locales/ru/errors/custom-profile-fields.ts
  packages/phrases/src/locales/tr-tr/errors/custom-profile-fields.ts
  packages/phrases/src/locales/zh-cn/errors/custom-profile-fields.ts
  packages/phrases/src/locales/zh-hk/errors/custom-profile-fields.ts
  packages/phrases/src/locales/zh-tw/errors/custom-profile-fields.ts
  packages/schemas/src/types/custom-profile-fields.ts
  packages/schemas/src/types/interactions.ts
Labels: feature, size/l

#7522 feat(core,schemas): implement sso token storage
  packages/core/src/libraries/social.ts
  packages/core/src/libraries/sso-connector.ts
  packages/core/src/queries/secret.ts
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/classes/helpers.ts
  packages/core/src/routes/experience/classes/libraries/provision-library.ts
  packages/core/src/routes/experience/classes/verifications/enterprise-sso-verification.ts
  packages/core/src/routes/experience/types.ts
  packages/core/src/routes/interaction/utils/single-sign-on.test.ts
  packages/core/src/routes/interaction/utils/single-sign-on.ts
  packages/core/src/test-utils/mock-libraries.ts
  packages/core/src/utils/secret-encryption.ts
  packages/schemas/src/types/logto-config/jwt-customizer.ts
  packages/schemas/src/types/secrets.ts
  packages/schemas/src/types/verification-records/enterprise-sso-verification.ts
  packages/schemas/src/types/verification-records/social-verification.ts
  packages/toolkit/connector-kit/src/types/social.ts
  single-sign-on.test.js
Labels: feature, size/l

#7523 feat(core): add get user enterprise sso identity API
  packages/core/src/queries/secret.ts
  packages/core/src/routes/admin-user/enterprise-sso.openapi.json
  packages/core/src/routes/admin-user/enterprise-sso.test.ts
  packages/core/src/routes/admin-user/enterprise-sso.ts
  packages/core/src/routes/admin-user/index.ts
  packages/core/src/routes/admin-user/social.ts
  packages/core/src/utils/secret-encryption.ts
  packages/phrases/src/locales/ar/errors/user.ts
  packages/phrases/src/locales/ar/translation/admin-console/get-started.ts
  packages/phrases/src/locales/ar/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/de/errors/user.ts
  packages/phrases/src/locales/de/translation/admin-console/get-started.ts
  packages/phrases/src/locales/de/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/en/errors/user.ts
  packages/phrases/src/locales/es/errors/user.ts
  packages/phrases/src/locales/es/translation/admin-console/get-started.ts
  packages/phrases/src/locales/es/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/fr/errors/user.ts
  packages/phrases/src/locales/fr/translation/admin-console/get-started.ts
  packages/phrases/src/locales/fr/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/it/errors/user.ts
  packages/phrases/src/locales/it/translation/admin-console/get-started.ts
  packages/phrases/src/locales/it/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/ja/errors/user.ts
  packages/phrases/src/locales/ja/translation/admin-console/get-started.ts
  packages/phrases/src/locales/ja/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/ko/errors/user.ts
  packages/phrases/src/locales/ko/translation/admin-console/get-started.ts
  packages/phrases/src/locales/ko/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/pl-pl/errors/user.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/get-started.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/pt-br/errors/user.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/get-started.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/pt-pt/errors/user.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/get-started.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/ru/errors/user.ts
  packages/phrases/src/locales/ru/translation/admin-console/get-started.ts
  packages/phrases/src/locales/ru/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/tr-tr/errors/user.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/get-started.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/zh-cn/errors/user.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/get-started.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/zh-hk/errors/user.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/get-started.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/upsell/index.ts
  packages/phrases/src/locales/zh-tw/errors/user.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/get-started.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/upsell/index.ts
  packages/schemas/src/types/secrets.ts
Labels: feature, size/xl

#7526 style: update convert tenant banner icon
  packages/console/src/assets/icons/convert-tenant-header.svg
  packages/console/src/pages/GetStarted/ConvertToProductionCard.tsx
Labels: size/s

#7527 Revert "feat(core): verify user totp (#7505)"
  packages/core/src/routes/account/index.openapi.json
  packages/core/src/routes/account/mfa-verifications.ts
  packages/integration-tests/src/api/my-account.ts
  packages/integration-tests/src/tests/api/account/mfa-verification.test.ts
Labels: size/m

#7512 feat: init `@logto/api`
  .changeset/README.md
  .changeset/config.json
  .changeset/shaggy-fans-remain.md
  docker-compose.yml
  packages/api/.gitignore
  packages/api/README.md
  packages/api/check-types.sh
  packages/api/docker-compose.local.yml
  packages/api/generate-types.sh
  packages/api/package.json
  packages/api/src/client-credentials.test.ts
  packages/api/src/client-credentials.ts
  packages/api/src/management.test.ts
  packages/api/src/management.ts
  packages/api/tsconfig.build.json
  packages/api/tsconfig.json
  pnpm-lock.yaml
Labels: feature, size/xl

#7533 feat(experience): add select field component
  packages/experience/package.json
  packages/experience/src/App.tsx
  packages/experience/src/components/Dropdown/DropdownItem.module.scss
  packages/experience/src/components/Dropdown/DropdownItem.tsx
  packages/experience/src/components/Dropdown/index.module.scss
  packages/experience/src/components/Dropdown/index.tsx
  packages/experience/src/components/InputFields/InputField/index.module.scss
  packages/experience/src/components/InputFields/InputField/index.tsx
  packages/experience/src/components/InputFields/SelectField/index.module.scss
  packages/experience/src/components/InputFields/SelectField/index.tsx
  packages/experience/src/components/OverlayScrollbar/index.tsx
  packages/experience/src/hooks/use-position.ts
  packages/experience/src/scss/_colors.scss
  packages/experience/src/scss/overlayscrollbars.scss
  packages/experience/src/types/positioning.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#7539 refactor(core): support extra profile validation and redirection
  packages/core/src/routes/experience/classes/libraries/profile-validator.ts
  packages/core/src/routes/experience/classes/profile.ts
  packages/experience/src/pages/Continue/SetEmailOrPhone/index.tsx
  packages/schemas/src/types/interactions.ts
Labels: enhancement, size/s

#7534 feat(core): add third-party token account API
  packages/core/src/routes/account/index.openapi.json
  packages/core/src/routes/account/index.ts
  packages/core/src/routes/account/middlewares/koa-account-center.ts
  packages/core/src/routes/account/third-party-tokens.ts
  packages/core/src/routes/swagger/utils/documents.ts
  packages/core/src/utils/sql.ts
  packages/phrases/src/locales/en/errors/index.ts
  packages/phrases/src/locales/en/errors/secrets.ts
  packages/schemas/src/types/secrets.ts
  packages/shared/src/database/types.ts
Labels: feature, size/m

#7538 feat(core): implement token refresh flow
  packages/connectors/connector-github/src/index.ts
  packages/core/src/libraries/social.ts
  packages/core/src/libraries/sso-connector.ts
  packages/core/src/routes/account/third-party-tokens.ts
  packages/core/src/routes/interaction/utils/single-sign-on.ts
  packages/core/src/sso/GoogleWorkspaceSsoConnector/index.ts
  packages/core/src/sso/OidcConnector/index.ts
  packages/core/src/sso/OidcConnector/utils.ts
  packages/core/src/test-utils/mock-libraries.ts
  packages/core/src/utils/secret-encryption.ts
  packages/toolkit/connector-kit/src/types/social.ts
Labels: feature, size/l

#7541 feat(experience,phrases): add fullname and address input fields in sie
  packages/experience/src/components/InputFields/AddressField/index.module.scss
  packages/experience/src/components/InputFields/AddressField/index.tsx
  packages/experience/src/components/InputFields/AddressField/utils.ts
  packages/experience/src/components/InputFields/FullnameField/index.module.scss
  packages/experience/src/components/InputFields/FullnameField/index.tsx
  packages/experience/src/components/InputFields/InputField/index.tsx
  packages/experience/src/components/InputFields/SelectField/index.tsx
  packages/phrases-experience/src/locales/ar/index.ts
  packages/phrases-experience/src/locales/ar/profile.ts
  packages/phrases-experience/src/locales/de/index.ts
  packages/phrases-experience/src/locales/de/profile.ts
  packages/phrases-experience/src/locales/en/index.ts
  packages/phrases-experience/src/locales/en/profile.ts
  packages/phrases-experience/src/locales/es/index.ts
  packages/phrases-experience/src/locales/es/profile.ts
  packages/phrases-experience/src/locales/fr/index.ts
  packages/phrases-experience/src/locales/fr/profile.ts
  packages/phrases-experience/src/locales/it/index.ts
  packages/phrases-experience/src/locales/it/profile.ts
  packages/phrases-experience/src/locales/ja/index.ts
  packages/phrases-experience/src/locales/ja/profile.ts
  packages/phrases-experience/src/locales/ko/index.ts
  packages/phrases-experience/src/locales/ko/profile.ts
  packages/phrases-experience/src/locales/pl-pl/index.ts
  packages/phrases-experience/src/locales/pl-pl/profile.ts
  packages/phrases-experience/src/locales/pt-br/index.ts
  packages/phrases-experience/src/locales/pt-br/profile.ts
  packages/phrases-experience/src/locales/pt-pt/index.ts
  packages/phrases-experience/src/locales/pt-pt/profile.ts
  packages/phrases-experience/src/locales/ru/index.ts
  packages/phrases-experience/src/locales/ru/profile.ts
  packages/phrases-experience/src/locales/tr-tr/index.ts
  packages/phrases-experience/src/locales/tr-tr/profile.ts
  packages/phrases-experience/src/locales/uk-ua/index.ts
  packages/phrases-experience/src/locales/uk-ua/profile.ts
  packages/phrases-experience/src/locales/zh-cn/index.ts
  packages/phrases-experience/src/locales/zh-cn/profile.ts
  packages/phrases-experience/src/locales/zh-hk/index.ts
  packages/phrases-experience/src/locales/zh-hk/profile.ts
  packages/phrases-experience/src/locales/zh-tw/index.ts
  packages/phrases-experience/src/locales/zh-tw/profile.ts
Labels: feature, size/xl

#7545 fix(core): add response data for mfa settings
  packages/core/src/routes/account/index.openapi.json
  packages/core/src/routes/account/index.ts
  packages/integration-tests/src/api/my-account.ts
  packages/integration-tests/src/tests/api/account/mfa-settings.test.ts
Labels: bugfix, size/s

#7540 feat(console): add enable token storage switch
  packages/console/src/components/ConnectorForm/BasicForm/index.tsx
  packages/console/src/pages/ConnectorDetails/ConnectorContent/index.tsx
  packages/console/src/pages/Connectors/Guide/index.tsx
  packages/console/src/types/connector.ts
  packages/console/src/utils/connector-form.ts
  packages/core/src/utils/connectors/index.ts
  packages/phrases/src/locales/ar/errors/index.ts
  packages/phrases/src/locales/ar/errors/secrets.ts
  packages/phrases/src/locales/ar/translation/admin-console/connectors.ts
  packages/phrases/src/locales/de/errors/index.ts
  packages/phrases/src/locales/de/errors/secrets.ts
  packages/phrases/src/locales/de/translation/admin-console/connectors.ts
  packages/phrases/src/locales/en/translation/admin-console/connectors.ts
  packages/phrases/src/locales/es/errors/index.ts
  packages/phrases/src/locales/es/errors/secrets.ts
  packages/phrases/src/locales/es/translation/admin-console/connectors.ts
  packages/phrases/src/locales/fr/errors/index.ts
  packages/phrases/src/locales/fr/errors/secrets.ts
  packages/phrases/src/locales/fr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/it/errors/index.ts
  packages/phrases/src/locales/it/errors/secrets.ts
  packages/phrases/src/locales/it/translation/admin-console/connectors.ts
  packages/phrases/src/locales/ja/errors/index.ts
  packages/phrases/src/locales/ja/errors/secrets.ts
  packages/phrases/src/locales/ja/translation/admin-console/connectors.ts
  packages/phrases/src/locales/ko/errors/index.ts
  packages/phrases/src/locales/ko/errors/secrets.ts
  packages/phrases/src/locales/ko/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pl-pl/errors/index.ts
  packages/phrases/src/locales/pl-pl/errors/secrets.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-br/errors/index.ts
  packages/phrases/src/locales/pt-br/errors/secrets.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-pt/errors/index.ts
  packages/phrases/src/locales/pt-pt/errors/secrets.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/connectors.ts
  packages/phrases/src/locales/ru/errors/index.ts
  packages/phrases/src/locales/ru/errors/secrets.ts
  packages/phrases/src/locales/ru/translation/admin-console/connectors.ts
  packages/phrases/src/locales/tr-tr/errors/index.ts
  packages/phrases/src/locales/tr-tr/errors/secrets.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/zh-cn/errors/index.ts
  packages/phrases/src/locales/zh-cn/errors/secrets.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/connectors.ts
  packages/phrases/src/locales/zh-hk/errors/index.ts
  packages/phrases/src/locales/zh-hk/errors/secrets.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/connectors.ts
  packages/phrases/src/locales/zh-tw/errors/index.ts
  packages/phrases/src/locales/zh-tw/errors/secrets.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/connectors.ts
  packages/schemas/src/types/connector.ts
Labels: feature, size/l

#7543 feat(experience,phrases): render profile form and collect extra profile info
  packages/core/src/libraries/custom-profile-fields/utils.ts
  packages/core/src/routes/experience/classes/libraries/profile-validator.test.ts
  packages/core/src/routes/experience/classes/libraries/profile-validator.ts
  packages/experience/package.json
  packages/experience/src/apis/experience/index.ts
  packages/experience/src/components/InputFields/AddressField/index.module.scss
  packages/experience/src/components/InputFields/AddressField/index.tsx
  packages/experience/src/components/InputFields/FullnameField/index.module.scss
  packages/experience/src/components/InputFields/FullnameField/index.tsx
  packages/experience/src/components/InputFields/InputField/index.module.scss
  packages/experience/src/components/InputFields/InputField/index.tsx
  packages/experience/src/components/InputFields/SelectField/index.tsx
  packages/experience/src/hooks/use-required-profile-error-handler.ts
  packages/experience/src/pages/Continue/ExtraProfileForm/FullnameSubForm/index.module.scss
  packages/experience/src/pages/Continue/ExtraProfileForm/FullnameSubForm/index.tsx
  packages/experience/src/pages/Continue/ExtraProfileForm/index.module.scss
  packages/experience/src/pages/Continue/ExtraProfileForm/index.tsx
  packages/experience/src/pages/Continue/ExtraProfileForm/use-field-label.ts
  packages/experience/src/pages/Continue/ExtraProfileForm/use-validate-field.ts
  packages/experience/src/pages/Continue/SetExtraProfile/index.tsx
  packages/experience/src/pages/Continue/SetExtraProfile/use-set-extra-profile.ts
  packages/experience/src/pages/Continue/index.tsx
  packages/experience/src/types/guard.ts
  packages/phrases-experience/src/locales/ar/description.ts
  packages/phrases-experience/src/locales/ar/error/index.ts
  packages/phrases-experience/src/locales/de/description.ts
  packages/phrases-experience/src/locales/de/error/index.ts
  packages/phrases-experience/src/locales/en/description.ts
  packages/phrases-experience/src/locales/en/error/index.ts
  packages/phrases-experience/src/locales/es/description.ts
  packages/phrases-experience/src/locales/es/error/index.ts
  packages/phrases-experience/src/locales/fr/description.ts
  packages/phrases-experience/src/locales/fr/error/index.ts
  packages/phrases-experience/src/locales/it/description.ts
  packages/phrases-experience/src/locales/it/error/index.ts
  packages/phrases-experience/src/locales/ja/description.ts
  packages/phrases-experience/src/locales/ja/error/index.ts
  packages/phrases-experience/src/locales/ko/description.ts
  packages/phrases-experience/src/locales/ko/error/index.ts
  packages/phrases-experience/src/locales/pl-pl/description.ts
  packages/phrases-experience/src/locales/pl-pl/error/index.ts
  packages/phrases-experience/src/locales/pt-br/description.ts
  packages/phrases-experience/src/locales/pt-br/error/index.ts
  packages/phrases-experience/src/locales/pt-pt/description.ts
  packages/phrases-experience/src/locales/pt-pt/error/index.ts
  packages/phrases-experience/src/locales/ru/description.ts
  packages/phrases-experience/src/locales/ru/error/index.ts
  packages/phrases-experience/src/locales/tr-tr/description.ts
  packages/phrases-experience/src/locales/tr-tr/error/index.ts
  packages/phrases-experience/src/locales/uk-ua/description.ts
  packages/phrases-experience/src/locales/uk-ua/error/index.ts
  packages/phrases-experience/src/locales/zh-cn/description.ts
  packages/phrases-experience/src/locales/zh-cn/error/index.ts
  packages/phrases-experience/src/locales/zh-hk/description.ts
  packages/phrases-experience/src/locales/zh-hk/error/index.ts
  packages/phrases-experience/src/locales/zh-tw/description.ts
  packages/phrases-experience/src/locales/zh-tw/error/index.ts
  packages/schemas/src/types/custom-profile-fields.ts
  pnpm-lock.yaml
Labels: feature, size/xl

#7546 fix(console): add token storage switch to SSO connector
  packages/console/src/pages/EnterpriseSsoDetails/Experience/index.tsx
Labels: bugfix, size/s

#7552 feat(cli): add alteration file timestamp digit length check
  packages/cli/src/commands/database/alteration/utils.test.ts
  packages/cli/src/commands/database/alteration/utils.ts
  packages/schemas/alterations/next-1751529530-add-enable-token-storage-column-to-sso-connectors-table.ts
Labels: feature, size/s

#7544 refactor: fix workspace fixed dep versions
  packages/cli/package.json
  packages/core/package.json
  pnpm-lock.yaml
Labels: enhancement, size/xs

#7559 fix(core,experience): relax validation for optional custom profile field
  packages/core/src/libraries/custom-profile-fields/utils.ts
  packages/experience/src/pages/Continue/ExtraProfileForm/index.tsx
  packages/experience/src/pages/Continue/ExtraProfileForm/use-validate-field.ts
Labels: bugfix, size/s

#7561 fix(experience): should revalidate the profile form on blur
  packages/experience/src/components/InputFields/AddressField/index.tsx
  packages/experience/src/components/InputFields/SelectField/index.tsx
  packages/experience/src/pages/Continue/ExtraProfileForm/FullnameSubForm/index.tsx
  packages/experience/src/pages/Continue/ExtraProfileForm/index.tsx
Labels: bugfix, size/s

#7529 chore: add changeset of account api mfa
  .changeset/neat-points-invite.md
  packages/core/src/routes/account/index.openapi.json
  packages/core/src/routes/account/mfa-verifications.ts
  packages/integration-tests/src/tests/api/account/mfa-backup-codes.test.ts
  packages/integration-tests/src/tests/api/account/mfa-totp.test.ts
Labels: chore, size/l

#7555 refactor(core): refactor get user social/sso identities API
  packages/core/src/routes/admin-user/enterprise-sso.openapi.json
  packages/core/src/routes/admin-user/enterprise-sso.test.ts
  packages/core/src/routes/admin-user/enterprise-sso.ts
  packages/core/src/routes/admin-user/social.openapi.json
  packages/core/src/routes/admin-user/social.ts
  packages/integration-tests/src/api/admin-user.ts
  packages/integration-tests/src/tests/api/account/social.test.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/enterprise-sso.test.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/social.test.ts
Labels: enhancement, size/m

#7558 feat(core): add get user social and sso identities API
  packages/core/src/queries/secret.ts
  packages/core/src/routes/admin-user/enterprise-sso.openapi.json
  packages/core/src/routes/admin-user/enterprise-sso.ts
  packages/core/src/routes/admin-user/social.ts
  packages/schemas/src/types/user.ts
Labels: feature, size/m

#7569 feat(core): add sanitized interaction data API and tests
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/classes/mfa.ts
  packages/core/src/routes/experience/classes/profile.ts
  packages/core/src/routes/experience/classes/verifications/backup-code-verification.ts
  packages/core/src/routes/experience/classes/verifications/code-verification.ts
  packages/core/src/routes/experience/classes/verifications/enterprise-sso-verification.ts
  packages/core/src/routes/experience/classes/verifications/index.ts
  packages/core/src/routes/experience/classes/verifications/new-password-identity-verification.ts
  packages/core/src/routes/experience/classes/verifications/one-time-token-verification.ts
  packages/core/src/routes/experience/classes/verifications/password-verification.ts
  packages/core/src/routes/experience/classes/verifications/social-verification.ts
  packages/core/src/routes/experience/classes/verifications/totp-verification.ts
  packages/core/src/routes/experience/classes/verifications/verification-record.ts
  packages/core/src/routes/experience/classes/verifications/web-authn-verification.ts
  packages/core/src/routes/experience/const.ts
  packages/core/src/routes/experience/experience.openapi.json
  packages/core/src/routes/experience/index.ts
  packages/core/src/routes/experience/types.ts
  packages/integration-tests/src/client/experience/const.ts
  packages/integration-tests/src/client/experience/index.ts
  packages/integration-tests/src/client/experience/types.ts
  packages/integration-tests/src/tests/api/experience-api/interaction.test.ts
  packages/schemas/src/types/verification-records/backup-code-verification.ts
  packages/schemas/src/types/verification-records/enterprise-sso-verification.ts
  packages/schemas/src/types/verification-records/new-password-identity-verification.ts
  packages/schemas/src/types/verification-records/social-verification.ts
  packages/schemas/src/types/verification-records/totp-verification.ts
  packages/schemas/src/types/verification-records/web-authn-verification.ts
Labels: feature, size/xl

#7571 refactor(core): add `hasRefreshToken` to token secret response
  packages/core/src/routes/admin-user/enterprise-sso.test.ts
  packages/core/src/utils/secret-encryption.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/social.test.ts
  packages/schemas/src/types/secrets.ts
Labels: enhancement, size/s

#7573 feat(console,core): add user social identity details page
  packages/console/src/components/ConnectorName/index.tsx
  packages/console/src/components/ConnectorTokenStatus/index.module.scss
  packages/console/src/components/ConnectorTokenStatus/index.tsx
  packages/console/src/hooks/use-console-routes/routes/users.tsx
  packages/console/src/pages/UserDetails/UserSettings/UserConnections/UserSocialIdentities.tsx
  packages/console/src/pages/UserDetails/UserSettings/UserConnections/UserSsoIdentities.tsx
  packages/console/src/pages/UserDetails/UserSettings/UserConnections/index.module.scss
  packages/console/src/pages/UserIdentityDetails/DeleteSocialIdentityConfirmModal.tsx
  packages/console/src/pages/UserIdentityDetails/SocialIdentityDetails.tsx
  packages/console/src/pages/UserIdentityDetails/TokenStorage/DeleteSecretConfirmModal.tsx
  packages/console/src/pages/UserIdentityDetails/TokenStorage/TokenCard.module.scss
  packages/console/src/pages/UserIdentityDetails/TokenStorage/TokenCard.tsx
  packages/console/src/pages/UserIdentityDetails/TokenStorage/index.module.scss
  packages/console/src/pages/UserIdentityDetails/TokenStorage/index.tsx
  packages/console/src/pages/UserIdentityDetails/index.module.scss
  packages/console/src/pages/UserIdentityDetails/use-social-identity-data.ts
  packages/phrases/src/locales/en/translation/admin-console/index.ts
  packages/phrases/src/locales/en/translation/admin-console/user-details.ts
  packages/phrases/src/locales/en/translation/admin-console/user-identity-details.ts
Labels: feature, size/xl

#7577 feat(console): add collect user profile management to sign-in experience
  packages/console/src/assets/images/collect-user-profile-empty-dark.svg
  packages/console/src/assets/images/collect-user-profile-empty.svg
  packages/console/src/consts/external-links.ts
  packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/index.module.scss
  packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/utils.ts
  packages/console/src/pages/SignInExperience/PageContent/index.tsx
  packages/console/src/pages/SignInExperience/types.ts
  packages/phrases/src/locales/ar/translation/admin-console/profile.ts
  packages/phrases/src/locales/ar/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/ar/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/de/translation/admin-console/profile.ts
  packages/phrases/src/locales/de/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/de/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/en/translation/admin-console/profile.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/es/translation/admin-console/profile.ts
  packages/phrases/src/locales/es/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/es/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/fr/translation/admin-console/profile.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/it/translation/admin-console/profile.ts
  packages/phrases/src/locales/it/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/it/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/ja/translation/admin-console/profile.ts
  packages/phrases/src/locales/ja/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/ja/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/ko/translation/admin-console/profile.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/profile.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/profile.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/profile.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/ru/translation/admin-console/profile.ts
  packages/phrases/src/locales/ru/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/ru/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/profile.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/profile.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/profile.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/sign-in-exp/index.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/profile.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/sign-in-exp/index.ts
Labels: feature, size/xl

#7582 feat(console): implement custom profile field creation modal
  packages/console/src/hooks/use-console-routes/routes/sign-in-experience.tsx
  packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/index.tsx
  packages/console/src/pages/SignInExperience/components/CreateProfileFieldModal/index.module.scss
  packages/console/src/pages/SignInExperience/components/CreateProfileFieldModal/index.tsx
  packages/phrases/src/locales/ar/errors/custom-profile-fields.ts
  packages/phrases/src/locales/ar/translation/admin-console/profile.ts
  packages/phrases/src/locales/ar/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/de/errors/custom-profile-fields.ts
  packages/phrases/src/locales/de/translation/admin-console/profile.ts
  packages/phrases/src/locales/de/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/en/errors/custom-profile-fields.ts
  packages/phrases/src/locales/en/translation/admin-console/profile.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/es/errors/custom-profile-fields.ts
  packages/phrases/src/locales/es/translation/admin-console/profile.ts
  packages/phrases/src/locales/es/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/fr/errors/custom-profile-fields.ts
  packages/phrases/src/locales/fr/translation/admin-console/profile.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/it/errors/custom-profile-fields.ts
  packages/phrases/src/locales/it/translation/admin-console/profile.ts
  packages/phrases/src/locales/it/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/ja/errors/custom-profile-fields.ts
  packages/phrases/src/locales/ja/translation/admin-console/profile.ts
  packages/phrases/src/locales/ja/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/ko/errors/custom-profile-fields.ts
  packages/phrases/src/locales/ko/translation/admin-console/profile.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/pl-pl/errors/custom-profile-fields.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/profile.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/pt-br/errors/custom-profile-fields.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/profile.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/pt-pt/errors/custom-profile-fields.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/profile.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/ru/errors/custom-profile-fields.ts
  packages/phrases/src/locales/ru/translation/admin-console/profile.ts
  packages/phrases/src/locales/ru/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/tr-tr/errors/custom-profile-fields.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/profile.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/zh-cn/errors/custom-profile-fields.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/profile.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/zh-hk/errors/custom-profile-fields.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/profile.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/sign-in-exp/custom-profile-fields.ts
  packages/phrases/src/locales/zh-tw/errors/custom-profile-fields.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/profile.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/sign-in-exp/custom-profile-fields.ts
Labels: feature, size/xl

#7590 refactor(console, core): add offline access to google SSO connector
  packages/console/src/pages/EnterpriseSsoDetails/Connection/OidcMetadataForm/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/types/oidc.ts
  packages/core/src/sso/GoogleWorkspaceSsoConnector/index.ts
  packages/phrases/src/locales/en/translation/admin-console/enterprise-sso-details.ts
Labels: enhancement, size/s

#7587 fix(console): console iterations
  packages/console/src/components/CreateConnectorForm/index.tsx
  packages/console/src/ds-components/Button/index.module.scss
  packages/console/src/ds-components/Button/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/Connection/OidcMetadataForm/index.tsx
  packages/console/src/pages/UserDetails/UserSettings/UserConnections/UserSocialIdentities.tsx
  packages/console/src/pages/UserDetails/UserSettings/UserConnections/UserSsoIdentities.tsx
  packages/console/src/pages/UserDetails/UserSettings/UserMfaVerifications/index.tsx
  packages/console/src/pages/UserIdentityDetails/TokenStorage/TokenCard.tsx
  packages/console/src/pages/UserIdentityDetails/TokenStorage/index.tsx
  packages/phrases/src/locales/ar/errors/user.ts
  packages/phrases/src/locales/ar/errors/verification-record.ts
  packages/phrases/src/locales/ar/translation/admin-console/user-identity-details.ts
  packages/phrases/src/locales/de/errors/user.ts
  packages/phrases/src/locales/de/errors/verification-record.ts
  packages/phrases/src/locales/de/translation/admin-console/user-identity-details.ts
  packages/phrases/src/locales/en/translation/admin-console/user-identity-details.ts
  packages/phrases/src/locales/es/errors/user.ts
  packages/phrases/src/locales/es/errors/verification-record.ts
  packages/phrases/src/locales/es/translation/admin-console/user-identity-details.ts
  packages/phrases/src/locales/fr/errors/user.ts
  packages/phrases/src/locales/fr/errors/verification-record.ts
  packages/phrases/src/locales/fr/translation/admin-console/user-identity-details.ts
  packages/phrases/src/locales/it/errors/user.ts
  packages/phrases/src/locales/it/errors/verification-record.ts
  packages/phrases/src/locales/it/translation/admin-console/user-identity-details.ts
  packages/phrases/src/locales/ja/errors/user.ts
  packages/phrases/src/locales/ja/errors/verification-record.ts
  packages/phrases/src/locales/ja/translation/admin-console/user-identity-details.ts
  packages/phrases/src/locales/ko/errors/user.ts
  packages/phrases/src/locales/ko/errors/verification-record.ts
  packages/phrases/src/locales/ko/translation/admin-console/user-identity-details.ts
  packages/phrases/src/locales/pl-pl/errors/user.ts
  packages/phrases/src/locales/pl-pl/errors/verification-record.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/user-identity-details.ts
  packages/phrases/src/locales/pt-br/errors/user.ts
  packages/phrases/src/locales/pt-br/errors/verification-record.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/user-identity-details.ts
  packages/phrases/src/locales/pt-pt/errors/user.ts
  packages/phrases/src/locales/pt-pt/errors/verification-record.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/user-identity-details.ts
  packages/phrases/src/locales/ru/errors/user.ts
  packages/phrases/src/locales/ru/errors/verification-record.ts
  packages/phrases/src/locales/ru/translation/admin-console/user-identity-details.ts
  packages/phrases/src/locales/tr-tr/errors/user.ts
  packages/phrases/src/locales/tr-tr/errors/verification-record.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/user-identity-details.ts
  packages/phrases/src/locales/zh-cn/errors/user.ts
  packages/phrases/src/locales/zh-cn/errors/verification-record.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/user-identity-details.ts
  packages/phrases/src/locales/zh-hk/errors/user.ts
  packages/phrases/src/locales/zh-hk/errors/verification-record.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/user-identity-details.ts
  packages/phrases/src/locales/zh-tw/errors/user.ts
  packages/phrases/src/locales/zh-tw/errors/verification-record.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/user-identity-details.ts
Labels: bugfix, size/xl

#7589 feat(core): delete token secrets on token storage disabled
  packages/core/src/queries/secret.ts
  packages/core/src/routes/connector/index.ts
  packages/core/src/routes/sso-connector/index.ts
  packages/integration-tests/src/api/sso-connector.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/enterprise-sso.test.ts
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/social.test.ts
Labels: feature, size/m

#7592 chore: remove catpcha enabled key
  packages/connectors/connector-logto-email/package.json
  packages/console/package.json
  packages/console/src/consts/plan-quotas.ts
  packages/console/src/consts/quota-item-phrases.ts
  packages/console/src/consts/tenants.ts
  packages/core/package.json
  packages/core/src/__mocks__/cloud-connection.ts
  packages/core/src/utils/subscription/types.ts
  pnpm-lock.yaml
Labels: chore, size/s

#7580 feat(console,schemas): add phone and email mfa factors
  packages/console/src/assets/icons/factor-email.svg
  packages/console/src/assets/icons/factor-phone.svg
  packages/console/src/components/MfaFactorName/index.tsx
  packages/console/src/components/MfaFactorTitle/index.tsx
  packages/console/src/pages/Mfa/MfaForm/FactorLabel/index.tsx
  packages/console/src/pages/Mfa/MfaForm/index.tsx
  packages/console/src/pages/Mfa/MfaForm/utils.ts
  packages/console/src/pages/Mfa/types.ts
  packages/core/src/libraries/user.utils.ts
  packages/core/src/routes/experience/profile-routes.ts
  packages/core/src/routes/interaction/actions/submit-interaction.ts
  packages/core/src/routes/interaction/verifications/mfa-payload-verification.ts
  packages/experience/src/apis/experience/mfa.ts
  packages/experience/src/assets/icons/factor-email.svg
  packages/experience/src/assets/icons/factor-phone.svg
  packages/experience/src/components/Button/MfaFactorButton.tsx
  packages/phrases-experience/src/locales/ar/mfa.ts
  packages/phrases-experience/src/locales/de/mfa.ts
  packages/phrases-experience/src/locales/en/mfa.ts
  packages/phrases-experience/src/locales/es/mfa.ts
  packages/phrases-experience/src/locales/fr/mfa.ts
  packages/phrases-experience/src/locales/it/mfa.ts
  packages/phrases-experience/src/locales/ja/mfa.ts
  packages/phrases-experience/src/locales/ko/mfa.ts
  packages/phrases-experience/src/locales/pl-pl/mfa.ts
  packages/phrases-experience/src/locales/pt-br/mfa.ts
  packages/phrases-experience/src/locales/pt-pt/mfa.ts
  packages/phrases-experience/src/locales/ru/mfa.ts
  packages/phrases-experience/src/locales/tr-tr/mfa.ts
  packages/phrases-experience/src/locales/uk-ua/mfa.ts
  packages/phrases-experience/src/locales/zh-cn/mfa.ts
  packages/phrases-experience/src/locales/zh-hk/mfa.ts
  packages/phrases-experience/src/locales/zh-tw/mfa.ts
  packages/phrases/src/locales/en/translation/admin-console/mfa.ts
  packages/schemas/src/foundations/jsonb-types/sign-in-experience.ts
  packages/schemas/src/foundations/jsonb-types/users.ts
  packages/schemas/src/types/interactions.ts
Labels: feature, size/l

#7599 refactor(console): update console components for new requirements
  packages/console/src/components/DetailsForm/index.tsx
  packages/console/src/components/DetailsPage/DetailsPageHeader/index.module.scss
  packages/console/src/components/DetailsPage/DetailsPageHeader/index.tsx
  packages/console/src/components/FormCard/index.tsx
  packages/console/src/components/SubmitFormChangesActionBar/index.tsx
  packages/console/src/ds-components/Checkbox/CheckboxGroup/index.tsx
  packages/console/src/ds-components/TextInput/NumericInput.tsx
  packages/console/src/ds-components/TextInput/index.module.scss
  packages/console/src/ds-components/TextInput/index.tsx
Labels: enhancement, size/m

#7596 fix(schemas): add tenant-aware foreign key constraint
  .changeset/brave-boats-travel.md
  packages/schemas/alterations/next-1753669579-add-organization-user-relations-foreign-key.ts
  packages/schemas/tables/organization_user_relations.sql
  packages/schemas/tables/users.sql
Labels: bugfix, size/s

#7603 feat(connector): enable token storage for OIDC standard connector
  packages/connectors/connector-oidc/src/constant.ts
  packages/connectors/connector-oidc/src/index.ts
  packages/connectors/connector-oidc/src/utils.ts
Labels: feature, size/m

#7607 feat(console): add drag and drop support to changing profile fields sorting order
  packages/console/src/ds-components/DragDrop/DraggableItem.tsx
  packages/console/src/ds-components/Table/TablePlaceholder.tsx
  packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/index.module.scss
  packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/index.tsx
  packages/core/src/queries/custom-profile-fields.ts
Labels: feature, size/l

#7609 refactor(core): add access token existence check
  packages/core/src/libraries/social.ts
  packages/core/src/routes/interaction/utils/single-sign-on.ts
Labels: enhancement, size/s

#7620 fix(console): should not show paywall on profile field creation modal in OSS version
  packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/CreateProfileFieldModal/index.tsx
Labels: bugfix, size/xs

#7622 refactor(console): add icons to the field type selector dropdown
  packages/console/src/assets/icons/field-type-checkbox.svg
  packages/console/src/assets/icons/field-type-date.svg
  packages/console/src/assets/icons/field-type-dropdown.svg
  packages/console/src/assets/icons/field-type-number.svg
  packages/console/src/assets/icons/field-type-regex.svg
  packages/console/src/assets/icons/field-type-text.svg
  packages/console/src/assets/icons/field-type-url.svg
  packages/console/src/pages/SignInExperience/PageContent/components/ProfileFieldPartSubForm/index.module.scss
  packages/console/src/pages/SignInExperience/PageContent/components/ProfileFieldPartSubForm/index.tsx
Labels: enhancement, size/s

#7624 fix(console): fix the console token storage issues
  packages/console/src/components/ConnectorForm/BasicForm/index.tsx
  packages/console/src/consts/external-links.ts
  packages/console/src/pages/EnterpriseSsoDetails/Experience/index.tsx
  packages/console/src/pages/UserIdentityDetails/TokenStorage/index.module.scss
  packages/phrases/src/locales/ar/translation/admin-console/connectors.ts
  packages/phrases/src/locales/de/translation/admin-console/connectors.ts
  packages/phrases/src/locales/en/translation/admin-console/connectors.ts
  packages/phrases/src/locales/es/translation/admin-console/connectors.ts
  packages/phrases/src/locales/fr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/it/translation/admin-console/connectors.ts
  packages/phrases/src/locales/ja/translation/admin-console/connectors.ts
  packages/phrases/src/locales/ko/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/connectors.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/connectors.ts
  packages/phrases/src/locales/ru/translation/admin-console/connectors.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/connectors.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/connectors.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/connectors.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/connectors.ts
Labels: bugfix, size/m

#7625 feat(console): remove dev feature guard for token storage
  packages/connectors/connector-google/src/constant.ts
  packages/console/src/components/ConnectorForm/BasicForm/index.tsx
  packages/console/src/components/CreateConnectorForm/index.tsx
  packages/console/src/hooks/use-console-routes/routes/users.tsx
  packages/console/src/pages/ConnectorDetails/ConnectorContent/index.tsx
  packages/console/src/pages/Connectors/Guide/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/Connection/OidcMetadataForm/index.tsx
  packages/console/src/pages/EnterpriseSsoDetails/Experience/index.tsx
  packages/console/src/pages/UserDetails/UserSettings/UserSocialIdentities/index.module.scss
  packages/console/src/pages/UserDetails/UserSettings/UserSocialIdentities/index.tsx
  packages/console/src/pages/UserDetails/UserSettings/UserSsoIdentities/index.tsx
  packages/console/src/pages/UserDetails/UserSettings/index.tsx
  packages/console/src/types/connector.ts
  packages/console/src/utils/connector-form.ts
Labels: feature, size/l

#7627 feat(core): add KEK environment variable guard
  packages/core/src/routes/connector/index.ts
  packages/core/src/routes/sso-connector/index.ts
Labels: feature, size/s

#7600 feat(console,core): handle sign in and mfa email phone confict
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignInForm/SignInMethodEditBox/SignInMethodItem.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignInForm/SignInMethodEditBox/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignInForm/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/SignUpIdentifiersEditBox/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/utils.ts
  packages/console/src/pages/SignInExperience/PageContent/index.tsx
  packages/core/src/libraries/sign-in-experience/sign-in.test.ts
  packages/core/src/libraries/sign-in-experience/sign-in.ts
  packages/core/src/routes/sign-in-experience/index.test.ts
  packages/core/src/routes/sign-in-experience/index.ts
  packages/integration-tests/src/tests/api/sign-in-experience.test.ts
  packages/phrases/src/locales/en/errors/sign-in-experiences.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
Labels: feature, size/l

#7634 chore: update social and enterprise connector readme for token storage
  packages/connectors/connector-facebook/README.md
  packages/connectors/connector-github/README.md
  packages/connectors/connector-google/README.md
  packages/connectors/connector-oauth2/README.md
  packages/connectors/connector-oidc/README.md
  packages/console/src/assets/docs/single-sign-on/google-workspace/README.mdx
  packages/console/src/assets/docs/single-sign-on/oidc/README.mdx
Labels: chore, size/xl
