Repository logto-io/logto, pull requests merged in 2025-03, with the labels that each got.

#7084 refactor: improve translate CLI for better language and package compatibility
  .changeset/ten-kings-flash.md
  .changeset/twenty-crabs-hammer.md
  packages/toolkit/language-kit/src/const.ts
  packages/translate/src/sync.ts
  packages/translate/src/utils.ts
Labels: enhancement, size/s

#7088 feat: add `one_time_tokens` table
  packages/schemas/alterations/next-1740982044-add-one-time-tokens-table.ts
  packages/schemas/src/foundations/jsonb-types/index.ts
  packages/schemas/src/foundations/jsonb-types/one-time-tokens.ts
  packages/schemas/tables/one_time_tokens.sql
Labels: feature, size/s

#7097 feat(core): migrate experience package for OSS
  .changeset/hungry-olives-sell.md
  packages/core/src/middleware/koa-spa-proxy.test.ts
  packages/core/src/middleware/utils/experience-proxy.test.ts
  packages/core/src/middleware/utils/experience-proxy.ts
Labels: feature, size/s

#7090 feat: add POST /one-time-tokens API
  packages/core/src/queries/one-time-tokens.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/one-time-tokens.openapi.json
  packages/core/src/routes/one-time-tokens.ts
  packages/core/src/routes/swagger/utils/documents.ts
  packages/core/src/routes/swagger/utils/general.ts
  packages/core/src/tenants/Queries.ts
  packages/integration-tests/src/api/one-time-token.ts
  packages/integration-tests/src/tests/api/one-time-tokens.test.ts
Labels: feature, size/m

#7104 feat(schemas): add organizationRequiredMfa policy settings
  packages/integration-tests/src/tests/api/sign-in-experience.test.ts
  packages/schemas/src/foundations/jsonb-types/sign-in-experience.ts
Labels: feature, size/s

#7112 chore: update readme
  README.md
Labels: chore, size/xs

#7113 feat(console): add organizationRequiredMfaPolicy config
  packages/console/src/pages/Mfa/MfaForm/index.tsx
  packages/console/src/pages/Mfa/MfaForm/utils.ts
  packages/console/src/pages/Mfa/types.ts
  packages/phrases/src/locales/en/translation/admin-console/mfa.ts
Labels: feature, size/s

#7110 chore: sync and update translations
  packages/phrases/src/locales/ar/errors/organization.ts
  packages/phrases/src/locales/de/errors/organization.ts
  packages/phrases/src/locales/es/errors/organization.ts
  packages/phrases/src/locales/fr/errors/organization.ts
  packages/phrases/src/locales/it/errors/organization.ts
  packages/phrases/src/locales/ja/errors/organization.ts
  packages/phrases/src/locales/ko/errors/organization.ts
  packages/phrases/src/locales/pl-pl/errors/organization.ts
  packages/phrases/src/locales/pt-br/errors/organization.ts
  packages/phrases/src/locales/pt-pt/errors/organization.ts
  packages/phrases/src/locales/ru/errors/organization.ts
  packages/phrases/src/locales/tr-tr/errors/organization.ts
  packages/phrases/src/locales/zh-cn/errors/organization.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
  packages/phrases/src/locales/zh-hk/errors/organization.ts
  packages/phrases/src/locales/zh-tw/errors/organization.ts
Labels: chore, size/s

#7106 feat(schemas): add captcha policy field
  packages/core/src/__mocks__/sign-in-experience.ts
  packages/core/src/queries/sign-in-experience.test.ts
  packages/experience-legacy/src/__mocks__/logto.tsx
  packages/experience/src/__mocks__/logto.tsx
  packages/schemas/alterations/next-1741240284-add-captcha-policy.ts
  packages/schemas/src/foundations/jsonb-types/sign-in-experience.ts
  packages/schemas/tables/sign_in_experiences.sql
Labels: feature, size/s

#7114 chore(core): update some experience API doc descriptions
  packages/core/src/routes/experience/experience.openapi.json
  packages/core/src/routes/experience/verification-routes/social-verification.openapi.json
  packages/schemas/src/types/interactions.ts
Labels: chore, size/s

#7105 feat(schemas): add captcha provider table
  packages/schemas/alterations/next-1741572426-add-captcha-providers.ts
  packages/schemas/src/foundations/jsonb-types/captcha.ts
  packages/schemas/src/foundations/jsonb-types/index.ts
  packages/schemas/tables/captcha_providers.sql
Labels: feature, size/s

#7098 feat: add POST /one-time-tokens/verify API
  packages/core/src/libraries/one-time-token.ts
  packages/core/src/queries/one-time-tokens.ts
  packages/core/src/routes/one-time-tokens.openapi.json
  packages/core/src/routes/one-time-tokens.ts
  packages/core/src/routes/swagger/utils/documents.ts
  packages/core/src/routes/swagger/utils/operation-id.ts
  packages/core/src/tenants/Libraries.ts
  packages/integration-tests/src/api/one-time-token.ts
  packages/integration-tests/src/tests/api/one-time-tokens.test.ts
  packages/phrases/src/locales/en/errors/index.ts
  packages/phrases/src/locales/en/errors/one-time-token.ts
  packages/schemas/alterations/next-1741318144-add-one-time-token-unique-index.ts
  packages/schemas/tables/one_time_tokens.sql
Labels: feature, size/l

#7122 fix(connector): filter out locale param in AliyunSMS
  packages/connectors/connector-aliyun-sms/src/index.test.ts
  packages/connectors/connector-aliyun-sms/src/index.ts
  packages/connectors/connector-tencent-sms/src/index.test.ts
  packages/connectors/connector-tencent-sms/src/index.ts
Labels: bugfix, size/s

#7124 chore: ignore readme assets in docker build
  .dockerignore
Labels: chore, size/xs

#7128 chore: fix typos
  packages/core/src/routes/experience/classes/verifications/code-verification.ts
  packages/core/src/routes/experience/verification-routes/verification-code.openapi.json
  packages/integration-tests/src/tests/api/experience-api/verifications/verification-code.test.ts
Labels: chore, size/xs

#7111 feat(core): add crud routes for captcha provider
  packages/core/src/queries/captcha-providers.ts
  packages/core/src/routes/captcha-provider/index.openapi.json
  packages/core/src/routes/captcha-provider/index.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/swagger/utils/documents.ts
  packages/core/src/tenants/Queries.ts
  packages/integration-tests/src/api/captcha-provider.ts
  packages/integration-tests/src/tests/api/captcha-provider.test.ts
Labels: feature, size/l

#7091 refactor(core): optimize password encryption process
  packages/core/package.json
  packages/core/src/utils/password.test.ts
  packages/core/src/utils/password.ts
  packages/core/src/workers/password-encryption-worker.ts
  packages/core/src/workers/tasks/argon2i.ts
  packages/core/tsup.config.ts
  pnpm-lock.yaml
Labels: enhancement, size/m

#7132 fix(core): fix OIDC SSO token request failed issue
  .changeset/dull-dolphins-return.md
  packages/core/src/saml-application/SamlApplication/index.test.ts
  packages/core/src/sso/OidcConnector/utils.test.ts
  packages/core/src/sso/OidcConnector/utils.ts
Labels: bugfix, size/s

#7123 feat(console): add security home page
  packages/console/src/assets/icons/security.svg
  packages/console/src/consts/external-links.ts
  packages/console/src/containers/ConsoleContent/Sidebar/hook.tsx
  packages/console/src/hooks/use-console-routes/index.tsx
  packages/console/src/hooks/use-console-routes/routes/security.tsx
  packages/console/src/pages/Security/index.module.scss
  packages/console/src/pages/Security/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/index.ts
  packages/phrases/src/locales/en/translation/admin-console/security.ts
  packages/phrases/src/locales/en/translation/admin-console/tabs.ts
Labels: feature, size/m

#7129 feat: implement verify one-time token experience api
  packages/core/src/routes/experience/classes/helpers.ts
  packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.ts
  packages/core/src/routes/experience/classes/verifications/index.ts
  packages/core/src/routes/experience/classes/verifications/one-time-token-verification.ts
  packages/core/src/routes/experience/classes/verifications/verification-record.ts
  packages/core/src/routes/experience/index.ts
  packages/core/src/routes/experience/verification-routes/one-time-token.openapi.json
  packages/core/src/routes/experience/verification-routes/one-time-token.ts
  packages/core/src/sentinel/basic-sentinel.ts
  packages/integration-tests/src/client/experience/index.ts
  packages/integration-tests/src/tests/api/experience-api/register-interaction/one-time-token.test.ts
  packages/integration-tests/src/tests/api/experience-api/verifications/one-time-token.test.ts
  packages/schemas/src/foundations/jsonb-types/sentinel.ts
  packages/schemas/src/foundations/jsonb-types/verification-records.ts
  packages/schemas/src/types/interactions.ts
Labels: feature, size/xl

#7137 refactor(core): refactor setProfileByVerificationId
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/classes/profile.ts
  packages/core/src/routes/experience/classes/verifications/code-verification.ts
  packages/core/src/routes/experience/profile-routes.ts
  packages/core/src/routes/experience/types.ts
Labels: enhancement, size/m

#7136 feat: render pricing content from website
  packages/console/src/consts/env.ts
  packages/console/src/pages/TenantSettings/Subscription/ConsoleEmbedPricing/Skeleton/index.module.scss
  packages/console/src/pages/TenantSettings/Subscription/ConsoleEmbedPricing/Skeleton/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/ConsoleEmbedPricing/index.module.scss
  packages/console/src/pages/TenantSettings/Subscription/ConsoleEmbedPricing/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/SwitchPlanActionBar/index.module.scss
  packages/console/src/pages/TenantSettings/Subscription/SwitchPlanActionBar/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/index.tsx
  packages/console/vite.config.ts
Labels: feature, size/m

#7141 refactor(console): support unknown region
  packages/console/src/components/Region/index.tsx
  packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx
  packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/TenantRegion/index.tsx
Labels: enhancement, size/s

#7130 feat(console): add captcha modal
  packages/console/src/assets/images/recaptcha.svg
  packages/console/src/assets/images/turnstile.svg
  packages/console/src/pages/Security/CaptchaLogo/index.module.scss
  packages/console/src/pages/Security/CaptchaLogo/index.tsx
  packages/console/src/pages/Security/CreateCaptchaForm/ProviderRadioGroup/ProviderRadio/index.module.scss
  packages/console/src/pages/Security/CreateCaptchaForm/ProviderRadioGroup/ProviderRadio/index.tsx
  packages/console/src/pages/Security/CreateCaptchaForm/ProviderRadioGroup/index.module.scss
  packages/console/src/pages/Security/CreateCaptchaForm/ProviderRadioGroup/index.tsx
  packages/console/src/pages/Security/CreateCaptchaForm/constants.ts
  packages/console/src/pages/Security/CreateCaptchaForm/index.module.scss
  packages/console/src/pages/Security/CreateCaptchaForm/index.tsx
  packages/console/src/pages/Security/CreateCaptchaForm/types.ts
  packages/console/src/pages/Security/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/security.ts
Labels: feature, size/l

#7131 feat(console): captcha list page
  packages/console/src/pages/Security/CaptchaCard/index.module.scss
  packages/console/src/pages/Security/CaptchaCard/index.tsx
  packages/console/src/pages/Security/index.tsx
  packages/console/src/pages/Security/use-data-fetch.ts
  packages/phrases/src/locales/en/translation/admin-console/security.ts
Labels: feature, size/m

#7135 feat(console): captcha detail page
  packages/console/src/components/Drawer/index.tsx
  packages/console/src/hooks/use-console-routes/routes/security.tsx
  packages/console/src/pages/CaptchaDetails/CaptchaContent/index.tsx
  packages/console/src/pages/CaptchaDetails/index.module.scss
  packages/console/src/pages/CaptchaDetails/index.tsx
  packages/console/src/pages/Security/CaptchaCard/index.tsx
  packages/console/src/pages/Security/CreateCaptchaForm/constants.ts
  packages/console/src/pages/Security/CreateCaptchaForm/types.ts
  packages/phrases/src/locales/en/translation/admin-console/security.ts
Labels: feature, size/l

#7148 chore: remove embedded pricing url for docker build
  Dockerfile
Labels: chore, size/xs

#7147 feat(console): captcha required flows
  packages/console/src/pages/Security/RequiredFlows/index.module.scss
  packages/console/src/pages/Security/RequiredFlows/index.tsx
  packages/console/src/pages/Security/index.module.scss
  packages/console/src/pages/Security/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/security.ts
Labels: feature, size/m

#7103 chore: make report subscription usage to be non-blocking
  packages/core/src/routes/applications/application.ts
  packages/core/src/routes/sign-in-experience/index.ts
Labels: chore, size/xs

#7109 chore: reuse subscription library cache in quota library to reduce cross region HTTP requests
  packages/core/src/libraries/quota.ts
  packages/core/src/libraries/subscription.test.ts
  packages/core/src/libraries/subscription.ts
  packages/core/src/tenants/Libraries.ts
  packages/core/src/tenants/Tenant.ts
  packages/core/src/test-utils/tenant.ts
  packages/core/src/utils/subscription/index.ts
Labels: chore, size/m

#7151 chore: remove dev guard for embedded pricing content
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/TableDataWrapper/TableDataContent/index.module.scss
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/TableDataWrapper/TableDataContent/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/TableDataWrapper/index.module.scss
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/TableDataWrapper/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/index.module.scss
  packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/index.tsx
Labels: chore, size/l

#7146 feat(console): create captcha guide
  packages/console/src/hooks/use-console-routes/routes/security.tsx
  packages/console/src/pages/CaptchaDetails/CaptchaContent/index.tsx
  packages/console/src/pages/CaptchaDetails/index.tsx
  packages/console/src/pages/Security/CreateCaptchaForm/ProviderRadioGroup/index.tsx
  packages/console/src/pages/Security/CreateCaptchaForm/index.tsx
  packages/console/src/pages/Security/Guide/index.module.scss
  packages/console/src/pages/Security/Guide/index.tsx
  packages/console/src/pages/Security/index.tsx
  packages/console/src/pages/Security/types.tsx
  packages/phrases/src/locales/en/translation/admin-console/security.ts
Labels: feature, size/l

#7139 refactor: whitelist one_time_token param in oidc redirection
  packages/core/src/oidc/utils.test.ts
  packages/core/src/oidc/utils.ts
  packages/schemas/src/consts/oidc.ts
Labels: enhancement, size/s

#7152 feat(console): add recaptcha enterprise
  packages/console/src/pages/CaptchaDetails/CaptchaContent/index.tsx
  packages/console/src/pages/Security/CaptchaFormFields/index.tsx
  packages/console/src/pages/Security/CreateCaptchaForm/constants.ts
  packages/console/src/pages/Security/CreateCaptchaForm/types.ts
  packages/console/src/pages/Security/Guide/index.tsx
  packages/console/src/pages/Security/types.tsx
  packages/integration-tests/src/tests/api/captcha-provider.test.ts
  packages/phrases/src/locales/en/translation/admin-console/security.ts
  packages/schemas/src/foundations/jsonb-types/captcha.ts
Labels: feature, size/m

#7162 fix(console): prevent unsaved modal from flashing when navigating within parent path
  packages/console/src/components/UnsavedChangesAlertModal/index.tsx
Labels: bugfix, size/s

#7134 chore: fix pnpm requirements in CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: chore, size/xs

#7165 fix(console): fix visibility of Stripe customer portal
  packages/console/src/components/BillInfo/index.tsx
  packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/index.tsx
Labels: bugfix, size/s

#7087 chore: add scopes field to MS Azure AD connector
  .changeset/bright-pans-deny.md
  packages/connectors/connector-azuread/README.md
  packages/connectors/connector-azuread/src/constant.ts
  packages/connectors/connector-azuread/src/index.ts
  packages/connectors/connector-azuread/src/types.ts
Labels: chore, size/s, stale

#7169 chore(core): update xml-crypto dep
  package.json
  pnpm-lock.yaml
Labels: chore, size/xs

#7127 feat(core,schemas): add secondary sign-up identifiers
  .changeset/purple-waves-sit.md
  packages/core/src/libraries/sign-in-experience/sign-in.test.ts
  packages/core/src/libraries/sign-in-experience/sign-in.ts
  packages/core/src/libraries/sign-in-experience/sign-up.test.ts
  packages/core/src/libraries/sign-in-experience/sign-up.ts
  packages/core/src/routes/sign-in-experience/index.ts
  packages/integration-tests/src/tests/api/sign-in-experience.test.ts
  packages/phrases/src/locales/en/errors/sign-in-experiences.ts
  packages/schemas/src/foundations/jsonb-types/sign-in-experience.ts
Labels: feature, size/xl

#7142 feat(experience): handle secondary sign-up identifiers
  packages/experience/src/components/IdentifierRegisterForm/use-register-with-username.ts
  packages/experience/src/constants/env.ts
  packages/experience/src/containers/VerificationCode/use-register-flow-code-verification.ts
  packages/experience/src/containers/VerificationCode/use-sign-in-flow-code-verification.ts
  packages/experience/src/hooks/use-sie.ts
  packages/experience/src/pages/RegisterPassword/index.tsx
  packages/experience/src/pages/VerificationCode/index.tsx
  packages/experience/vite.config.ts
Labels: feature, size/m

#7168 feat(console): add multi sign-up identifiers
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignInForm/SignInMethodEditBox/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/SignUpForm.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/SignUpIdentifiersEditBox/SignUpIdentifierItem.module.scss
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/SignUpIdentifiersEditBox/SignUpIdentifierItem.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/SignUpIdentifiersEditBox/index.module.scss
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/SignUpIdentifiersEditBox/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/components/IdentifiersAddButton/index.module.scss
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/components/IdentifiersAddButton/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/utils.ts
  packages/console/src/pages/SignInExperience/PageContent/constants.ts
  packages/console/src/pages/SignInExperience/PageContent/utils/parser.ts
  packages/console/src/pages/SignInExperience/types.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/schemas/src/foundations/jsonb-types/sign-in-experience.ts
Labels: feature, size/xl

#7164 fix(toolkit): language tag check should be case insensitive
  .changeset/tame-snails-fold.md
  packages/toolkit/language-kit/src/utility.ts
  packages/translate/src/prompts.ts
Labels: bugfix, size/s

#7155 feat(experience): add switch account page
  packages/experience/src/pages/SwitchAccount/index.module.scss
  packages/experience/src/pages/SwitchAccount/index.tsx
  packages/phrases-experience/src/locales/ar/action.ts
  packages/phrases-experience/src/locales/ar/description.ts
  packages/phrases-experience/src/locales/de/action.ts
  packages/phrases-experience/src/locales/de/description.ts
  packages/phrases-experience/src/locales/en/action.ts
  packages/phrases-experience/src/locales/en/description.ts
  packages/phrases-experience/src/locales/es/action.ts
  packages/phrases-experience/src/locales/es/description.ts
  packages/phrases-experience/src/locales/fr/action.ts
  packages/phrases-experience/src/locales/fr/description.ts
  packages/phrases-experience/src/locales/it/action.ts
  packages/phrases-experience/src/locales/it/description.ts
  packages/phrases-experience/src/locales/ja/action.ts
  packages/phrases-experience/src/locales/ja/description.ts
  packages/phrases-experience/src/locales/ko/action.ts
  packages/phrases-experience/src/locales/ko/description.ts
  packages/phrases-experience/src/locales/pl-pl/action.ts
  packages/phrases-experience/src/locales/pl-pl/description.ts
  packages/phrases-experience/src/locales/pt-br/action.ts
  packages/phrases-experience/src/locales/pt-br/description.ts
  packages/phrases-experience/src/locales/pt-pt/action.ts
  packages/phrases-experience/src/locales/pt-pt/description.ts
  packages/phrases-experience/src/locales/ru/action.ts
  packages/phrases-experience/src/locales/ru/description.ts
  packages/phrases-experience/src/locales/tr-tr/action.ts
  packages/phrases-experience/src/locales/tr-tr/description.ts
  packages/phrases-experience/src/locales/zh-cn/action.ts
  packages/phrases-experience/src/locales/zh-cn/description.ts
  packages/phrases-experience/src/locales/zh-hk/action.ts
  packages/phrases-experience/src/locales/zh-hk/description.ts
  packages/phrases-experience/src/locales/zh-tw/action.ts
  packages/phrases-experience/src/locales/zh-tw/description.ts
Labels: feature, size/m

#7154 refactor(console): refactor SIE settings form
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignInForm/SignInMethodEditBox/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/SignUpForm.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/SignUpIdentifiersEditBox/SignUpIdentifierItem.module.scss
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/SignUpIdentifiersEditBox/SignUpIdentifierItem.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/SignUpIdentifiersEditBox/index.module.scss
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/SignUpIdentifiersEditBox/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/components/IdentifiersAddButton/index.module.scss
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/components/IdentifiersAddButton/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/utils.ts
  packages/console/src/pages/SignInExperience/PageContent/constants.ts
  packages/console/src/pages/SignInExperience/PageContent/utils/parser.ts
  packages/console/src/pages/SignInExperience/types.ts
  packages/core/src/libraries/sign-in-experience/sign-in.test.ts
  packages/core/src/libraries/sign-in-experience/sign-in.ts
  packages/integration-tests/src/tests/console/sign-in-experience/sign-up-and-sign-in/happy-path.test.ts
  packages/integration-tests/src/tests/console/sign-in-experience/sign-up-and-sign-in/sad-path.test.ts
  packages/integration-tests/src/utils.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/schemas/src/foundations/jsonb-types/sign-in-experience.ts
Labels: enhancement, size/xl

#7175 fix(console): fix sign-in method can not removed bug
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignInForm/SignInMethodEditBox/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/SignUpForm.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/SignUpIdentifiersEditBox/index.tsx
  packages/integration-tests/src/tests/console/sign-in-experience/sign-up-and-sign-in/happy-path.test.ts
  packages/integration-tests/src/tests/console/sign-in-experience/sign-up-and-sign-in/helpers.ts
Labels: bugfix, size/xl

#7167 refactor(translate): improve prompts to better support i18n suffixes
  .changeset/hungry-terms-smash.md
  packages/translate/src/prompts.ts
Labels: enhancement, size/s

#7178 refactor(experience): refactor usePreSignInErrorHandler hook
  packages/experience/src/components/IdentifierRegisterForm/use-register-with-username.ts
  packages/experience/src/containers/SocialLinkAccount/use-social-link-related-user.ts
  packages/experience/src/containers/VerificationCode/use-continue-flow-code-verification.ts
  packages/experience/src/containers/VerificationCode/use-register-flow-code-verification.ts
  packages/experience/src/containers/VerificationCode/use-sign-in-flow-code-verification.ts
  packages/experience/src/hooks/use-password-sign-in.ts
  packages/experience/src/hooks/use-pre-sign-in-error-handler.ts
  packages/experience/src/hooks/use-send-mfa-payload.ts
  packages/experience/src/hooks/use-skip-mfa.ts
  packages/experience/src/hooks/use-social-link-account.ts
  packages/experience/src/hooks/use-social-register.ts
  packages/experience/src/hooks/use-submit-interaction-error-handler.ts
  packages/experience/src/pages/Continue/SetPassword/index.tsx
  packages/experience/src/pages/Continue/SetUsername/use-set-username.ts
  packages/experience/src/pages/RegisterPassword/index.tsx
  packages/experience/src/pages/SocialSignInWebCallback/use-social-sign-in-listener.ts
Labels: enhancement, size/m

#7159 feat(experience): add one-time token landing page to handle magic link auth
  packages/experience/src/App.tsx
  packages/experience/src/apis/experience/index.ts
  packages/experience/src/apis/experience/one-time-token.ts
  packages/experience/src/hooks/use-fallback-route.ts
  packages/experience/src/pages/DirectSignIn/index.tsx
  packages/experience/src/pages/OneTimeToken/index.tsx
  packages/experience/src/utils/search-parameters.ts
  packages/phrases-experience/src/locales/ar/error/index.ts
  packages/phrases-experience/src/locales/de/error/index.ts
  packages/phrases-experience/src/locales/en/error/index.ts
  packages/phrases-experience/src/locales/es/error/index.ts
  packages/phrases-experience/src/locales/fr/error/index.ts
  packages/phrases-experience/src/locales/it/error/index.ts
  packages/phrases-experience/src/locales/ja/error/index.ts
  packages/phrases-experience/src/locales/ko/error/index.ts
  packages/phrases-experience/src/locales/pl-pl/error/index.ts
  packages/phrases-experience/src/locales/pt-br/error/index.ts
  packages/phrases-experience/src/locales/pt-pt/error/index.ts
  packages/phrases-experience/src/locales/ru/error/index.ts
  packages/phrases-experience/src/locales/tr-tr/error/index.ts
  packages/phrases-experience/src/locales/zh-cn/error/index.ts
  packages/phrases-experience/src/locales/zh-hk/error/index.ts
  packages/phrases-experience/src/locales/zh-tw/error/index.ts
  packages/schemas/src/consts/experience.ts
Labels: feature, size/l

#7179 feat(core): merge idToken claims with userinfo response
  packages/core/src/sso/AzureOidcSsoConnector/index.ts
  packages/core/src/sso/OidcConnector/utils.ts
Labels: feature, size/s

#7176 feat(core): check captcha token when creating interaction
  packages/core/src/__mocks__/captcha.ts
  packages/core/src/__mocks__/index.ts
  packages/core/src/libraries/sign-in-experience/index.test.ts
  packages/core/src/libraries/sign-in-experience/index.ts
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/classes/libraries/captcha-validator.ts
  packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.ts
  packages/core/src/routes/experience/index.ts
  packages/core/src/routes/well-known/index.ts
  packages/core/src/routes/well-known/well-known.experience.ts
  packages/core/src/routes/well-known/well-known.test.ts
  packages/integration-tests/src/helpers/captcha.ts
  packages/integration-tests/src/helpers/client.ts
  packages/integration-tests/src/helpers/experience/index.ts
  packages/integration-tests/src/helpers/sign-in-experience.ts
  packages/integration-tests/src/tests/api/experience-api/captcha/index.test.ts
  packages/phrases/src/locales/en/errors/session.ts
  packages/schemas/src/types/interactions.ts
  packages/schemas/src/types/sign-in-experience.ts
Labels: feature, size/l

#7184 refactor(console): change captcha policy to single switch
  packages/console/src/pages/Security/EnableCaptcha/index.module.scss
  packages/console/src/pages/Security/EnableCaptcha/index.tsx
  packages/console/src/pages/Security/RequiredFlows/index.tsx
  packages/console/src/pages/Security/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/security.ts
  packages/schemas/src/foundations/jsonb-types/sign-in-experience.ts
Labels: enhancement, size/m

#7180 feat(console): add wordpress plugin guide
  .changeset/old-lions-return.md
  packages/console/src/assets/docs/guides/index.tsx
  packages/console/src/assets/docs/guides/web-wordpress-plugin/README.mdx
  packages/console/src/assets/docs/guides/web-wordpress-plugin/config.json
  packages/console/src/assets/docs/guides/web-wordpress-plugin/index.ts
  packages/console/src/assets/docs/guides/web-wordpress-plugin/logo.svg
Labels: feature, size/m

#7189 feat(core): guard captcha before creating users
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.ts
  packages/integration-tests/src/helpers/admin-tenant.ts
  packages/integration-tests/src/helpers/client.ts
  packages/integration-tests/src/helpers/experience/index.ts
  packages/integration-tests/src/helpers/sign-in-experience.ts
  packages/integration-tests/src/tests/api/email-templates/experience-api.test.ts
  packages/integration-tests/src/tests/api/experience-api/bind-mfa/happpy-path.test.ts
  packages/integration-tests/src/tests/api/experience-api/bind-mfa/organization-required-mfa.test.ts
  packages/integration-tests/src/tests/api/experience-api/bind-mfa/sad-path.test.ts
  packages/integration-tests/src/tests/api/experience-api/captcha/index.test.ts
  packages/integration-tests/src/tests/api/experience-api/interaction.test.ts
  packages/integration-tests/src/tests/api/experience-api/profile/fulfill-user-profiles.test.ts
  packages/integration-tests/src/tests/api/experience-api/profile/reset-password.test.ts
  packages/integration-tests/src/tests/api/experience-api/register-interaction/enterprise-sso.test.ts
  packages/integration-tests/src/tests/api/experience-api/register-interaction/one-time-token.test.ts
  packages/integration-tests/src/tests/api/experience-api/register-interaction/username-password.test.ts
  packages/integration-tests/src/tests/api/experience-api/register-interaction/verification-code.test.ts
  packages/integration-tests/src/tests/api/hook/hook.trigger.experience.test.ts
Labels: feature, size/l

#7186 fix(console): disable conflicted sign-up identifiers
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/SignUpIdentifiersEditBox/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/components/IdentifiersAddButton/index.module.scss
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/components/IdentifiersAddButton/index.tsx
Labels: bugfix, size/s

#7191 refactor(console,core): refactor sign-up verify and sign-in syncing
  packages/console/src/ds-components/Checkbox/Checkbox/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignInForm/SignInMethodEditBox/SignInMethodItem.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignInForm/SignInMethodEditBox/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/SignUpForm.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/SignUpIdentifiersEditBox/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/use-sign-up-password-listeners.ts
  packages/core/src/libraries/sign-in-experience/sign-up.test.ts
  packages/core/src/libraries/sign-in-experience/sign-up.ts
  packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.test.ts
  packages/integration-tests/src/tests/api/experience-api/register-interaction/username-password.test.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
Labels: enhancement, size/l

#7190 chore: enable quota guard for cloud integration test
  packages/core/src/libraries/quota.ts
Labels: chore, size/s

#7194 feat(console): add new signUpDiff modal
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignInChangePreview/SignUpAndSignInDiffSection/SignUpDiffSection.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignInChangePreview/SignUpAndSignInDiffSection/index.tsx
Labels: feature, size/s

#7187 chore(phrases): update sign-up identifer phrases
  packages/phrases/src/locales/ar/errors/sign-in-experiences.ts
  packages/phrases/src/locales/ar/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/de/errors/sign-in-experiences.ts
  packages/phrases/src/locales/de/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/es/errors/sign-in-experiences.ts
  packages/phrases/src/locales/es/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/fr/errors/sign-in-experiences.ts
  packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/it/errors/sign-in-experiences.ts
  packages/phrases/src/locales/it/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/ja/errors/sign-in-experiences.ts
  packages/phrases/src/locales/ja/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/ko/errors/sign-in-experiences.ts
  packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/pl-pl/errors/sign-in-experiences.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/pt-br/errors/sign-in-experiences.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/pt-pt/errors/sign-in-experiences.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/ru/errors/sign-in-experiences.ts
  packages/phrases/src/locales/ru/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/tr-tr/errors/sign-in-experiences.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/zh-cn/errors/sign-in-experiences.ts
  packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/zh-hk/errors/sign-in-experiences.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
  packages/phrases/src/locales/zh-tw/errors/sign-in-experiences.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
Labels: chore, size/m

#7193 refactor(core): provision user to organizations upon successful one-time token auth
  packages/core/src/libraries/user.ts
  packages/core/src/queries/organization/index.ts
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/classes/libraries/provision-library.ts
  packages/core/src/routes/experience/classes/verifications/one-time-token-verification.ts
Labels: enhancement, size/m

#7195 refactor(core,experience): adjust missing profiles prompt order
  packages/core/src/routes/experience/classes/libraries/profile-validator.ts
  packages/experience/src/components/IdentifierRegisterForm/use-register-with-username.ts
  packages/experience/src/hooks/use-sie.ts
Labels: enhancement, size/s

#7160 feat(core): guard one-time token on consent request
  packages/core/src/middleware/koa-consent-guard.test.ts
  packages/core/src/middleware/koa-consent-guard.ts
  packages/core/src/tenants/Tenant.ts
  packages/experience/src/App.tsx
  packages/experience/src/pages/OneTimeToken/index.tsx
  packages/experience/src/pages/Register/index.tsx
  packages/experience/src/pages/SignIn/index.tsx
  packages/experience/src/pages/SwitchAccount/index.module.scss
  packages/experience/src/pages/SwitchAccount/index.tsx
  packages/experience/src/utils/search-parameters.ts
Labels: feature, size/l

#7201 feat(console): add password not enabled notification
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignInChangePreview/PasswordDisabledNotification.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignInChangePreview/index.module.scss
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignInChangePreview/index.tsx
  packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
Labels: feature, size/s

#7202 fix(console): show vonage connector
  packages/console/src/components/CreateConnectorForm/index.tsx
Labels: bugfix, size/xs

#7206 feat(demo-app,core): support one-time token in demo-app
  packages/core/src/middleware/koa-auto-consent.ts
  packages/core/src/routes/interaction/consent/index.ts
  packages/demo-app/src/App.tsx
Labels: feature, size/s

#7208 refactor(phrases): add "continue_as" phrase key
  packages/experience/src/pages/SwitchAccount/index.tsx
  packages/phrases-experience/src/locales/ar/action.ts
  packages/phrases-experience/src/locales/de/action.ts
  packages/phrases-experience/src/locales/en/action.ts
  packages/phrases-experience/src/locales/es/action.ts
  packages/phrases-experience/src/locales/fr/action.ts
  packages/phrases-experience/src/locales/it/action.ts
  packages/phrases-experience/src/locales/ja/action.ts
  packages/phrases-experience/src/locales/ko/action.ts
  packages/phrases-experience/src/locales/pl-pl/action.ts
  packages/phrases-experience/src/locales/pl-pl/description.ts
  packages/phrases-experience/src/locales/pl-pl/user-scopes.ts
  packages/phrases-experience/src/locales/pt-br/action.ts
  packages/phrases-experience/src/locales/pt-br/user-scopes.ts
  packages/phrases-experience/src/locales/pt-pt/action.ts
  packages/phrases-experience/src/locales/pt-pt/user-scopes.ts
  packages/phrases-experience/src/locales/ru/action.ts
  packages/phrases-experience/src/locales/tr-tr/action.ts
  packages/phrases-experience/src/locales/tr-tr/description.ts
  packages/phrases-experience/src/locales/tr-tr/user-scopes.ts
  packages/phrases-experience/src/locales/zh-cn/action.ts
  packages/phrases-experience/src/locales/zh-hk/action.ts
  packages/phrases-experience/src/locales/zh-hk/user-scopes.ts
  packages/phrases-experience/src/locales/zh-tw/action.ts
  packages/phrases-experience/src/locales/zh-tw/user-scopes.ts
Labels: enhancement, size/m

#7177 feat(core): add security headers for captcha
  packages/core/src/middleware/koa-security-headers.ts
Labels: feature, size/xs

#7207 fix(core): fix provision organization by ids query
  packages/core/src/queries/organization/index.ts
Labels: bugfix, size/s

#7199 fix(console): fix disable sign-in password settings bug
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/use-sign-up-password-listeners.ts
Labels: bugfix, size/s

#7172 fix(phrases): improve wording of "existing account?" question
  packages/phrases-experience/src/locales/en/description.ts
  packages/phrases-experience/src/locales/en/secondary.ts
Labels: bugfix, size/xs

#7196 feat(core): skip captcha for social and sso
  packages/core/src/routes/experience/verification-routes/enterprise-sso-verification.ts
  packages/core/src/routes/experience/verification-routes/social-verification.ts
  packages/integration-tests/src/tests/api/experience-api/captcha/index.test.ts
Labels: feature, size/s

#7188 feat(experience): render captcha in register form
  packages/experience/src/apis/experience/index.ts
  packages/experience/src/apis/experience/interaction.ts
  packages/experience/src/apis/utils.ts
  packages/experience/src/components/IdentifierRegisterForm/index.test.tsx
  packages/experience/src/components/IdentifierRegisterForm/index.tsx
  packages/experience/src/components/IdentifierRegisterForm/use-on-submit.ts
  packages/experience/src/components/IdentifierRegisterForm/use-register-with-username.ts
  packages/experience/src/components/IdentifierSignInForm/index.test.tsx
  packages/experience/src/components/Turnstile/index.module.scss
  packages/experience/src/components/Turnstile/index.tsx
  packages/experience/src/containers/CaptchaBox/index.tsx
  packages/experience/src/hooks/use-captcha.ts
  packages/experience/src/hooks/use-send-verification-code.ts
  packages/experience/src/pages/Continue/SetEmailOrPhone/index.test.tsx
  packages/experience/src/pages/ForgotPassword/ForgotPasswordForm/index.test.tsx
  packages/experience/src/pages/SignInPassword/PasswordForm/index.test.tsx
Labels: feature, size/m

#7210 fix(phrases): fix i18n translations in regional variation locales
  packages/phrases/src/locales/pl-pl/errors/one-time-token.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/mfa.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/security.ts
  packages/phrases/src/locales/pl-pl/translation/admin-console/tabs.ts
  packages/phrases/src/locales/pt-br/errors/one-time-token.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/mfa.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/security.ts
  packages/phrases/src/locales/pt-br/translation/admin-console/tabs.ts
  packages/phrases/src/locales/pt-pt/errors/one-time-token.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/mfa.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/security.ts
  packages/phrases/src/locales/pt-pt/translation/admin-console/tabs.ts
  packages/phrases/src/locales/tr-tr/errors/one-time-token.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/mfa.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/security.ts
  packages/phrases/src/locales/tr-tr/translation/admin-console/tabs.ts
  packages/phrases/src/locales/zh-hk/errors/one-time-token.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/mfa.ts
  packages/phrases/src/locales/zh-hk/translation/admin-console/security.ts
  packages/phrases/src/locales/zh-tw/errors/one-time-token.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/mfa.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/security.ts
  packages/phrases/src/locales/zh-tw/translation/admin-console/tabs.ts
Labels: bugfix, size/l

#7211 feat(core, console, experience): remove dev feature guards
  .changeset/hot-dodos-refuse.md
  packages/console/src/pages/Mfa/MfaForm/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignInForm/SignInMethodEditBox/SignInMethodItem.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignInForm/SignInMethodEditBox/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/SignUpForm.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/SignUpIdentifiersEditBox/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/utils.ts
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignInChangePreview/PasswordDisabledNotification.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignInChangePreview/SignUpAndSignInDiffSection/SignUpDiffSection.tsx
  packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignInChangePreview/SignUpAndSignInDiffSection/index.tsx
  packages/console/src/pages/SignInExperience/PageContent/constants.ts
  packages/console/src/pages/SignInExperience/PageContent/utils/form.ts
  packages/console/src/pages/SignInExperience/PageContent/utils/parser.ts
  packages/console/src/pages/SignInExperience/types.ts
  packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.ts
  packages/core/src/routes/sign-in-experience/index.openapi.json
  packages/experience/src/containers/VerificationCode/use-continue-flow-code-verification.ts
  packages/experience/src/hooks/use-sie.ts
  packages/integration-tests/src/tests/api/experience-api/register-interaction/username-password.test.ts
  packages/integration-tests/src/tests/api/experience-api/register-interaction/verification-code.test.ts
  packages/integration-tests/src/tests/console/sign-in-experience/sign-up-and-sign-in/happy-path.test.ts
  packages/integration-tests/src/tests/console/sign-in-experience/sign-up-and-sign-in/sad-path.test.ts
Labels: feature, size/xl

#7200 refactor(core): skip sign-in mode check for one-time token verification
  packages/core/src/routes/experience/classes/experience-interaction.ts
  packages/core/src/routes/experience/classes/helpers.ts
  packages/core/src/routes/experience/classes/libraries/provision-library.ts
  packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.test.ts
  packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.ts
  packages/core/src/routes/experience/classes/verifications/one-time-token-verification.ts
  packages/core/src/routes/experience/types.ts
  packages/integration-tests/src/tests/api/experience-api/register-interaction/one-time-token.test.ts
Labels: enhancement, size/m
