Repository logto-io/logto, pull requests merged in 2025-06, with the labels that each got.

#7420 feat(core): get mfa verifications
  packages/core/src/routes/account/index.openapi.json
  packages/core/src/routes/account/mfa-verifications.ts
  packages/phrases/src/locales/en/errors/account-center.ts
Labels: feature, size/s, size/m

#7424 feat(core): allow origin list for webauthn register and verify
  packages/core/src/routes/experience/classes/verifications/web-authn-verification.ts
  packages/core/src/routes/experience/verification-routes/web-authn-verification.ts
  packages/core/src/routes/interaction/utils/webauthn.test.ts
  packages/core/src/routes/interaction/utils/webauthn.ts
  packages/core/src/routes/interaction/verifications/mfa-payload-verification.ts
  packages/core/src/routes/verification/index.ts
Labels: feature, size/s, size/m

#7425 feat(core,schemas): added updated_at to user_sso_identities
  .changeset/blue-brooms-clean.md
  packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/enterprise-sso.test.ts
  packages/schemas/alterations/next-1749005587-user-sso-identities-table-add-updated-at-column.ts
  packages/schemas/tables/user_sso_identities.sql
Labels: feature, size/s

#7432 chore: update awesome list
  AWESOME.md
Labels: chore, size/xs

#7426 feat(schemas): add oidc_session_extensions table
  packages/schemas/alterations/next-1749026308-add-oidc-session-extension-table.ts
  packages/schemas/tables/oidc_model_instances.sql
  packages/schemas/tables/oidc_session_extensions.sql
Labels: feature, size/s, size/m

#7438 feat(test): add test cases for PAT organization token
  packages/integration-tests/src/tests/api/oidc/token-exchange/personal-access-token.test.ts
Labels: feature, size/s

#7439 fix(core): add display name to webauthn registration options
  .changeset/pink-rules-compare.md
  packages/core/src/routes/interaction/additional.ts
  packages/core/src/routes/interaction/utils/webauthn.ts
  packages/integration-tests/src/tests/api/account/mfa.test.ts
Labels: bugfix, size/s

#7437 feat(core,console,schemas): add interaction context to custom claims
  packages/console/scripts/generate-jwt-customizer-type-definition.ts
  packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/GuideCard/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/index.tsx
  packages/console/src/pages/CustomizeJwtDetails/utils/config.tsx
  packages/console/src/pages/CustomizeJwtDetails/utils/type-definitions.ts
  packages/core/src/oidc/extra-token-claims.ts
  packages/core/src/queries/oidc-session-extensions.ts
  packages/core/src/routes/experience/classes/verifications/enterprise-sso-verification.ts
  packages/core/src/routes/experience/classes/verifications/index.ts
  packages/core/src/utils/zod.ts
  packages/integration-tests/src/__mocks__/jwt-customizer.ts
  packages/integration-tests/src/tests/api/oidc/get-access-token.test.ts
  packages/phrases/src/locales/en/translation/admin-console/jwt-claims.ts
  packages/schemas/src/types/logto-config/jwt-customizer.ts
  packages/schemas/src/types/verification-records/enterprise-sso-verification.ts
Labels: feature, size/l

#7441 chore(console, core): add dev feature guard
  packages/console/src/pages/CustomizeJwtDetails/utils/config.tsx
  packages/core/src/libraries/session.ts
  packages/core/src/oidc/extra-token-claims.ts
Labels: chore, size/s

#7435 chore: add changeset of account api webauthn
  .changeset/purple-zebras-deliver.md
Labels: chore, size/s

#7453 refactor(core): handle webauthn regsitration verify error
  packages/core/src/routes/interaction/utils/webauthn.ts
  packages/integration-tests/src/tests/api/account/mfa.test.ts
Labels: enhancement, size/s

#7418 feat(schemas): add custom-profile-fields table
  packages/schemas/alterations/next-1749523818-add-custom-profile-fields.ts
  packages/schemas/src/foundations/jsonb-types/custom-profile-fields.ts
  packages/schemas/src/foundations/jsonb-types/index.ts
  packages/schemas/src/foundations/jsonb-types/users.ts
  packages/schemas/src/types/custom-profile-fields.ts
  packages/schemas/src/types/index.ts
  packages/schemas/tables/custom_profile_fields.sql
Labels: feature, size/m, size/l

#7445 fix(console): fix payment page cannot open in iOS Safari issue
  packages/console/src/hooks/use-subscribe.ts
Labels: bugfix, size/xs

#7457 fix(core): make access_token optional for Azure SSO
  .changeset/lemon-walls-fry.md
  packages/core/src/sso/AzureOidcSsoConnector/index.ts
Labels: bugfix, size/s

#7417 feat(core): add Google One Tap verify API
  packages/core/src/middleware/koa-cors.ts
  packages/core/src/middleware/koa-logto-anonymous-cors.test.ts
  packages/core/src/middleware/koa-logto-anonymous-cors.ts
  packages/core/src/routes/google-one-tap/index.openapi.json
  packages/core/src/routes/google-one-tap/index.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/swagger/utils/operation-id.ts
  packages/phrases/src/locales/en/errors/session.ts
  packages/toolkit/connector-kit/src/types/social.ts
Labels: feature, size/m, size/l, size/xl

#7458 chore(tunnel): security updates for tunnel-cli dependencies
  .changeset/sour-poems-whisper.md
  packages/tunnel/package.json
  pnpm-lock.yaml
Labels: chore, size/xs

#7476 fix(schemas): change password encrypted length to 256
  .changeset/olive-falcons-invite.md
  packages/core/src/routes/admin-user/basics.ts
  packages/integration-tests/src/tests/api/admin-user.test.ts
  packages/schemas/alterations/next-1750663091-change-user-password-encrypted-length.ts
  packages/schemas/tables/users.sql
Labels: bugfix, size/s

#7468 feat(core): generate totp secret
  packages/core/src/routes/account/index.openapi.json
  packages/core/src/routes/account/mfa-verifications.ts
  packages/integration-tests/src/api/my-account.ts
  packages/integration-tests/src/tests/api/account/mfa.test.ts
Labels: feature, size/s

#7446 feat(core): add management APIs for custom profile fields
  packages/console/src/components/Guide/ModalHeader/RequestForm.tsx
  packages/console/src/hooks/use-user-default-tenant-id.ts
  packages/console/src/hooks/use-user-preferences.ts
  packages/core/src/libraries/custom-profile-fields/index.ts
  packages/core/src/libraries/custom-profile-fields/utils.ts
  packages/core/src/middleware/koa-slonik-error-handler.ts
  packages/core/src/queries/custom-profile-fields.ts
  packages/core/src/routes/custom-profile-fields.openapi.json
  packages/core/src/routes/custom-profile-fields.ts
  packages/core/src/routes/init.ts
  packages/core/src/routes/swagger/utils/documents.ts
  packages/core/src/routes/swagger/utils/general.ts
  packages/core/src/routes/swagger/utils/operation-id.ts
  packages/core/src/tenants/Libraries.ts
  packages/core/src/tenants/Queries.ts
  packages/integration-tests/src/__mocks__/profile-fields-mock.ts
  packages/integration-tests/src/api/custom-profile-fields.ts
  packages/integration-tests/src/api/index.ts
  packages/integration-tests/src/tests/api/custom-profile-fields.test.ts
  packages/phrases/src/locales/ar/errors/custom-profile-fields.ts
  packages/phrases/src/locales/de/errors/custom-profile-fields.ts
  packages/phrases/src/locales/en/errors/custom-profile-fields.ts
  packages/phrases/src/locales/es/errors/custom-profile-fields.ts
  packages/phrases/src/locales/fr/errors/custom-profile-fields.ts
  packages/phrases/src/locales/it/errors/custom-profile-fields.ts
  packages/phrases/src/locales/ja/errors/custom-profile-fields.ts
  packages/phrases/src/locales/ko/errors/custom-profile-fields.ts
  packages/phrases/src/locales/pl-pl/errors/custom-profile-fields.ts
  packages/phrases/src/locales/pt-br/errors/custom-profile-fields.ts
  packages/phrases/src/locales/pt-pt/errors/custom-profile-fields.ts
  packages/phrases/src/locales/ru/errors/custom-profile-fields.ts
  packages/phrases/src/locales/tr-tr/errors/custom-profile-fields.ts
  packages/phrases/src/locales/zh-cn/errors/custom-profile-fields.ts
  packages/phrases/src/locales/zh-hk/errors/custom-profile-fields.ts
  packages/phrases/src/locales/zh-tw/errors/custom-profile-fields.ts
  packages/schemas/alterations/next-1749724664-drop-sie-order-constraint-from-custom-profile-fields.ts
  packages/schemas/src/types/custom-profile-fields.ts
  packages/schemas/src/types/tenant.ts
  packages/schemas/src/types/user.ts
  packages/schemas/tables/custom_profile_fields.sql
Labels: feature, size/l, size/xl

#7428 chore: update compare DB script data sorting logics
  .scripts/compare-database.js
  .scripts/compare-database.test.js
  package.json
Labels: chore, size/s

#7474 fix(experience): adding flexible size property in turnstile widget
  packages/experience/src/Providers/CaptchaContextProvider/index.tsx
  packages/experience/src/include.d/global.d.ts
Labels: bugfix, size/xs

#7478 feat(core): add TOTP verification to MFA endpoints
  packages/core/src/routes/account/index.openapi.json
  packages/core/src/routes/account/mfa-verifications.ts
  packages/integration-tests/src/api/account-center.ts
  packages/integration-tests/src/api/my-account.ts
  packages/integration-tests/src/tests/api/account/mfa.test.ts
Labels: feature, size/m, size/l

#7480 test: add integration tests for delete mfa
  packages/integration-tests/src/api/my-account.ts
  packages/integration-tests/src/tests/api/account/mfa.test.ts
Labels: testing, size/s

#7481 feat(core): add backup code
  packages/core/src/routes/account/index.openapi.json
  packages/core/src/routes/account/mfa-verifications.ts
  packages/integration-tests/src/api/my-account.ts
  packages/integration-tests/src/helpers/sign-in-experience.ts
  packages/integration-tests/src/tests/api/account/mfa.test.ts
Labels: feature, size/l

#7477 feat(schemas, core): add secret encryption util method
  packages/core/src/utils/secret-encryption.test.ts
  packages/core/src/utils/secret-encryption.ts
  packages/schemas/src/foundations/jsonb-types/secrets.ts
  packages/schemas/src/types/index.ts
  packages/schemas/src/types/secrets.ts
  packages/schemas/tables/secrets.sql
  packages/shared/src/database/types.ts
  packages/shared/src/node/env/GlobalValues.ts
Labels: feature, size/m

#7486 test: add backup code test cases
  packages/integration-tests/src/helpers/mfa-test.ts
  packages/integration-tests/src/tests/api/account/mfa-backup-codes.test.ts
  packages/integration-tests/src/tests/api/account/mfa-totp.test.ts
  packages/integration-tests/src/tests/api/account/mfa-webauthn.test.ts
Labels: testing, size/xl
